### ISSUE TITLE
Better default of SpaceVim.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#10]
please let me know what default should be? Thanks!

关于默认配置，大家有什么想法，请留下你的想法，万分感谢！

**Comment by JinWuZhao** [comment]
去spacemacs那里抄啊😁

**Comment by wsdjeg** [comment]
@JinWuZhao 兄弟 要是你能吧el抄成viml也算你牛了，哈哈。

**Comment by JinWuZhao** [comment]
抄下设计就行了，直接翻译代码也不一定能工作啊，强烈建议你去体验下spacemacs，有很多不错的点子在里面。

**Comment by wsdjeg** [comment]
我知道，我最近在读他的源码，我的思路和他不是太一样，不过原理一致，都是模块化载入，目前我觉得默认就应该是非常简单的，一些常有的设置。能够满足最简单的文件 文档编辑。

**Comment by wsdjeg** [comment]
The defalut setting will be in default.vim
