### ISSUE TITLE
Allow replacing SpaceVim mappings with custom mappings

### ISSUE THREAD

**Issue by BenBergman** [wsdjeg/SpaceVim#100]
### Expected behavior, english is recommend
When adding mappings to my `~/.SpaceVim.d/init.vim`, they get clobbered by mappings made in `~/.SpaceVim/autoload/SpaceVim/plugins.vim`. I would like to disable some of the mappings in SpaceVim without having to modify files in the SpaceVim repository.

Looking at `.SpaceVim/config/main.vim`, `.SpaceVim.d/init.vim` is loaded during the call to `SpaceVim#loadCustomConfig()` and `~/.SpaceVim/autoload/SpaceVim/plugins.vim` is loaded in the next step, `SpaceVim#end()`. Previously I was using spf13 for my vim configuration and they solved this problem by having one custom file that was loaded before the main files and one that was loaded after.

### Environment Information
- OS: Arch Linux
- vim version: n/a
- neovim version: NVIM 0.1.7

### The reproduce ways from Vim starting (Required!)
Add the following line to `~/.SpaceVim.d/init.vim`

```
nmap <C-l> <C-w>l
```

Press `<C-l>` in normal mode and it will try to run  `:Ydc` instead of switching panes.

**Comment by wsdjeg** [comment]
I think you can use autocmd. SpaceVim has some lazy load config for mappings.
add this to your custom config
```viml
augroup SpaceVimCheckInstall
    au!
    au VimEnter * call s:customMappings()
augroup END
func s:customMappings()
     nnoremap <C-l> <C-w>l
endf
```
I think you can use autocmd. SpaceVim has some lazy load config for mappings.
add this to your custom config
```viml
augroup custom_config
    au!
    au VimEnter * call s:customMappings()
augroup END
func s:customMappings()
     nnoremap <C-l> <C-w>l
endf
```

**Comment by wsdjeg** [comment]
I think you can use autocmd. SpaceVim has some lazy load config for mappings.
add this to your custom config
```viml
augroup custom_config
    au!
    au VimEnter * call s:customMappings()
augroup END
func s:customMappings()
     nnoremap <C-l> <C-w>l
endf
```

**Comment by AlphaLiu** [comment]
custom config is your ~/.local.vim

**Comment by wsdjeg** [comment]
@AlphaLiu
I just support ~/.SpaceVim.d/init.vim
