### ISSUE TITLE
E605: Exception not caught

### ISSUE THREAD

**Issue by ccfwwm** [wsdjeg/SpaceVim#1003]
## Environment Information
- OS:
- vim version:
- neovim version:

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
what is the issue?
