### ISSUE TITLE
Battary don’t show on macbook

### ISSUE THREAD

**Issue by kamontat** [wsdjeg/SpaceVim#1008]
## Environment Information
- OS: MacOS
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
- start vim
- toggle battary 
- nothing happen

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by kamontat** [comment]
Add debug info 
```viml
g:spacevim_enable_statusline_display_mode = 1
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.6.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimQuickFix', 'HelpDescribe']
g:spacevim_default_indent = 4
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'slant'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'onedark'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['wakatime/vim-wakatime']]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_ale = 0
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_cursorcolumn = 1
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_key_frequency = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_lint_on_save = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 1
g:spacevim_keep_server_alive = 1
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_unite_leader = 'U'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = 'FuraCode\ Nerd\ Font\ Mono\ 16'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'VersionControl', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm'
, 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'osx', 'lang#javascript', 'lang#t
ypescript', 'lang#json', 'lang#sh', 'lang#python', 'lang#vim', 'lang#ruby', 'incsearch', 'shell', 'vim', 'tools#screensaver', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 1
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/kamontat/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_realtime_leader_guide = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_github_username = 'kamontat'
g:spacevim_leader_guide_hspace = 5
g:spacevim_automatic_update = 1
g:spacevim_denite_leader = 's'
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 2
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_custom_color_palette = []
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_leader_guide_vertical = 0
g:spacevim_language = ''
g:spacevim_enable_vimfiler_gitstatus = 1
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.2.0_1/bin/nvim)
version: 704
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:59:28] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
```

**Comment by kamontat** [comment]
Add system infomation

![screen shot 2017-11-18 at 14 01 58](https://user-images.githubusercontent.com/14089557/32977892-1677a62a-cc69-11e7-9acb-59844af4d795.png)

**Comment by wsdjeg** [comment]
| Key Binding | Description                                                         |
| ----------- | ------------------------------------------------------------------- |
| `SPC t m b` | toggle the battery status (need to install acpi)                    |
| `SPC t m c` | toggle the org task clock (available in org layer)(TODO)            |
| `SPC t m m` | toggle the minor mode lighters                                      |
| `SPC t m M` | toggle the major mode                                               |
| `SPC t m n` | toggle the cat! (if colors layer is declared in your dotfile)(TODO) |
| `SPC t m p` | toggle the cursor position                                          |
| `SPC t m t` | toggle the time                                                     |
| `SPC t m d` | toggle the date                                                     |
| `SPC t m T` | toggle the mode line itself                                         |
| `SPC t m v` | toggle the version control info                                     |


you need to install acpi, which is the command to get the battary info.

**Comment by kamontat** [comment]
I don’t know how to install `acpi` on macOS. And on my research macOS are preinstall `acpi` right??

**Comment by wsdjeg** [comment]
hmm, I do not use mac os, I will try to find out how to get the battary info in mac os.

**Comment by kamontat** [comment]
How about this one? https://github.com/lambdalisue/battery.vim

**Comment by wsdjeg** [comment]
I will read the code of this plugins, Thanks.

**Comment by wsdjeg** [comment]
![2017-11-19_293x67](https://user-images.githubusercontent.com/13142418/32988181-873bdf4a-cd39-11e7-9415-b8d76a870d36.png)

@kamontat How about this icon?

**Comment by kamontat** [comment]
Excellent, but I want number too. Maybe customable will be great, Thank you

**Comment by wsdjeg** [comment]
sorry, I do not want to add too many statusline specified option, if you readlly like to custom statusline, I think you should create custom sectinon, and rename it as `battery status`, SpaceVim's statusline will support custom sections.

**Comment by wsdjeg** [comment]
for example, you can add this to your custom config:

```vim
func! s:get_battery_status()
  " here you can get a battery status info and return a number
endf
call SpaceVim#layers#core#statusline#register_sections('battery status', function('s:get_battery_status'))
```

**Comment by wsdjeg** [comment]
I am working on MacOS support。

**Comment by wsdjeg** [comment]
`pmset -g batt` will show

```
Now drawing from 'AC Power'
 -InternalBattery-0 (id=4128867)                     100%; changed; 0:00 remaining present: true
```
