### ISSUE TITLE
mac fc-cache mkfontdir mkfontscale not exists

### ISSUE THREAD

**Issue by zhangjiayin** [wsdjeg/SpaceVim#1016]
## Environment Information
- OS: mac High Sierra
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  3 2017 02:46:58)
- neovim version:

**Comment by wsdjeg** [comment]
I do not use mac os, if someone family with this os, PR is welcome.

**Comment by zhangjiayin** [comment]
so I create  #1017  for this

**Comment by wsdjeg** [comment]
@zhangjiayin Thanks for your PR, can you please sign the cla?

**Comment by zhangjiayin** [comment]
done

**Comment by wsdjeg** [comment]
Thanks, merged!
