### ISSUE TITLE
The phpcd.vim is error,php file is empty

### ISSUE THREAD

**Issue by taurusbo** [wsdjeg/SpaceVim#1019]
## Environment Information
- OS:windows 10  64bit
- vim version:8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)

#
## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
It should be reported in phpcd.vim issues.

**Comment by wsdjeg** [comment]
no more info, closed.
