### ISSUE TITLE
The Eerror "No vimproc_cygwin" under win10

### ISSUE THREAD

**Issue by xushaobo** [wsdjeg/SpaceVim#1022]
I use vim under Git bash under win10,and the errors shows "no vimproc_cygwin". Will it have influence?If the answer is no,how to remove this error message.

**Comment by Shougo** [comment]
https://github.com/Shougo/vimshell.vim/issues/234

https://github.com/Shougo/vimproc.vim/pull/277

Related issues.

**Comment by Shougo** [comment]
@xushaobo You can execute `make make_cygwin.mak` in vimproc repository.

**Comment by xushaobo** [comment]
thanks, I rename the vimproc_win64.dll to vimproc_cygwin.dll,and the error removed. Thank you for your rapid reply
