### ISSUE TITLE
The Home and End key is not work by ssh?

### ISSUE THREAD

**Issue by kecaiwu** [wsdjeg/SpaceVim#1038]
When i want to the start of a line, and i choose the 'Home' key, i get the 'H' in the last line. or i want to the end of a line, and i choose the 'End' key, i get the 'F' in the previous line. The vim is work in the command mode, and use the ssh link the PC. Thanks for providing solution.

![image](https://user-images.githubusercontent.com/17605639/33360911-d5dc4494-d510-11e7-93a4-1dc7d6b4e994.png)

![image](https://user-images.githubusercontent.com/17605639/33360897-c44b8758-d510-11e7-97d5-edd083134fd4.png)

**Comment by wsdjeg** [comment]
@kecaiwu you should have a try with `vim -u NONE`, I think it is the issue with your terminal, the `Home` an d `End` key can not be sent to vim.

**Comment by kecaiwu** [comment]
Thank for help, and i set the export TERM=screen-256color to xterm-256color, and everything is ok.
