### ISSUE TITLE
when i install spacevim and start it , i meet a bug

### ISSUE THREAD

**Issue by linsir6** [wsdjeg/SpaceVim#1044]
## Expected behavior, english is recommended

when i install spacevim and start it , i meet a bug

## Environment Information
- OS: macOs
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 22 2017 03:02:45)
- neovim version: NVIM v0.2.0

## The reproduce ways from Vim starting (Required!)

![](https://ws1.sinaimg.cn/large/006tNc79ly1fm19zdiwjpj31640signz.jpg)

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.
like this

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@linsir6 what is output of `vi --version`?

**Comment by linsir6** [comment]
![](https://ws3.sinaimg.cn/large/006tNc79ly1fm1adktev0j30qw03wq32.jpg)

![](https://ws3.sinaimg.cn/large/006tNc79ly1fm1aemj2duj31540303yr.jpg)

![](https://ws3.sinaimg.cn/large/006tNc79ly1fm1af8vnvnj31kw0o4jvn.jpg)


now, i use nvim xxx  is successful

**Comment by wsdjeg** [comment]
the python issue is bug of your vim, I think you need to install a gui version of vim, such as vim-gtk2 or gvim

**Comment by linsir6** [comment]
ok, thanks
