### ISSUE TITLE
YouCompleteMe g:ycm_semantic_triggers lose efficacy

### ISSUE THREAD

**Issue by chenong** [wsdjeg/SpaceVim#1047]
I set the g:ycm_semantic_triggers in ~/.SpaceVim.d/init.vim ：
```vim
call SpaceVim#layers#load('autocomplete')
let g:spacevim_enable_ycm = 1

let g:ycm_semantic_triggers =  {
  \   'c' : ['->', '.', 're!\[[_a-zA-Z]+\w*\s', 're!^\s*[^\W\d]\w*\s', 're!\[.*\]\s'],
  \ }
```
     
and then I start VIM， input
```shell
 :echo g:ycm_semantic_triggers
```

then the VIM show:

```python
{
'vim': ['re![_a-zA-Z]+[_\w]*\.'], 
'erlang': [':'], 'c': ['->', '.'], 
'perl': ['->'],
'cpp,objcpp': ['->', '.', '::'], 
'lua': ['.', ':'],
'cs,javascript,d,python,perl6,scala,vb,elixir,go': ['.'],
'php': ['->', '::'],
'objc': ['->', '.'],
'ocaml': ['.', '#'],
'ruby': ['.', '::'], 
'java,jsp': ['.']
}
```

## Environment Information
- OS:  Ubuntu 16.04.2 LTS
- vim version: VIM - Vi IMproved 8.0
- neovim version:

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by chenong** [comment]
I find the g:ycm_semantic_triggers set in ~/.SpaceVim/config/plugins_before/YouCompleteMe.vim
    
![image](https://user-images.githubusercontent.com/17999132/33472985-7e152c1c-d6af-11e7-8e24-67a964ddfc65.png)
     
and I commented out this code,  in the ~/.SpaceVim.d/init.vim configure is work OK.

**Comment by wsdjeg** [comment]
I will fix ycm config, Thanks for your report.
