### ISSUE TITLE
Ycm <Tab> not selecting completion

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1051]
#892 broke ycm support in SpaceVim as removing SuperTab disabled the smart <Tab> mapping.

Right now my <Tab> gets mapped as:
```
:imap <Tab>
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
```

and during completion if I hit it, it will just write a tab character.

YCM should have its own tab support, but spacevim heavily remap <Tab> making ycm configurations useless. 

See here for more info:
* https://github.com/Valloric/YouCompleteMe#the-gycm_key_list_select_completion-option

**Comment by wsdjeg** [comment]
ultisnips do not support expr mapping, and it do not provide func for checking jumpable and expandable. so I can not fix it. BTW, plugin's config sometimes break the core feature of spacevim, so sometimes we disable it.

**AND** that is why YCM and ultisnips is not enabled by default in spacevim, they do not provide a better interface for Integration.

**Comment by wsdjeg** [comment]
Move to #1078
