### ISSUE TITLE
press down spc is not show keyboard like first

### ISSUE THREAD

**Issue by linsir6** [wsdjeg/SpaceVim#1053]
## Expected behavior, english is recommended

keyboard like first

## Environment Information
- OS: MacOs
- vim version: VIM - Vi IMproved 8.0
- neovim version: NVIM v0.2.0
## Output of the ':SPDebugInfo!'

init.vim
```
...
let mapleader = "\<space>"
...

```

![image](https://user-images.githubusercontent.com/16979367/33483717-208edec8-d6da-11e7-8dbf-4539f5383c6f.png)

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
This is not a bug, this picture is same as when press `\` in SpaceVim , if you do not set `mapleader`.  this is the really `Leader` in vim, but in SpaceVim we do not use `Space` as `Leader`, we only use `Space` as `Leader in normal/visual` mode.
