### ISSUE TITLE
SPC + x + K raise unexpected behavior after moving to top

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1056]
## Expected behavior, english is recommended

After the text is moved to the top of the buffer, it should stop there. 
If I press [SPC] + x + K, the moving process should be smooth, while it flashes my editor a lot. 

to be concrete, a video is recorded for reference. [Bug video Recording](https://asciinema.org/a/9RE7qqVM24M4ssEJu6oLGskue)

## Environment Information
- OS: macOS 10.13
- vim version:
- neovim version: 0.2.2

## The reproduce ways from Vim starting (Required!)

Please refer to [Bug video recording](https://asciinema.org/a/9RE7qqVM24M4ssEJu6oLGskue)

## Output of the ':SPDebugInfo!'

```viml
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimQuickFix', 'HelpDescribe']
g:spacevim_default_indent = 2
g:spacevim_custom_plugins = [['terryma/vim-smooth-scroll'], ['chr4/nginx.vim'], ['ryanoasis/vim-devicons']]
g:spacevim_buffer_index_type = 0
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_error_symbol = '✖'
g:spacevim_enable_key_frequency = 0
g:spacevim_max_column = 120
g:spacevim_enable_insert_leader = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_plugin_groups_exclude = []
g:spacevim_dein_installed = 1
g:spacevim_enable_neomake = 1
g:spacevim_relativenumber = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_denite_leader = 'F'
g:spacevim_enable_cursorline = 1
g:spacevim_leader_guide_vertical = 0
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'version control info']
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.6.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_plugin_manager = 'dein'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_debug = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_enable_ycm = 0
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_neobundle_installed = 0
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_custom_color_palette = []
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_language = ''
g:spacevim_enable_vimfiler_gitstatus = 0
```

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.
```viml
"let g:one_allow_italics = 1 " I love italic for comments
let g:spacevim_colorscheme_bg = 'dark'
" let g:spacevim_colorscheme = 'one'

"Credit joshdick
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

set mouse=a

"""""""""""" 
let g:spacevim_enable_vimfiler_welcome = 0
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_vimfiler_filetypeicon = 1
let g:spacevim_enable_os_fileformat_icon = 1


" If you want to add some custom plugins, use these options:
let g:spacevim_custom_plugins = [
    \ ['terryma/vim-smooth-scroll'],
    \ ['chr4/nginx.vim'], 
    \ ['ryanoasis/vim-devicons'],
    \ ]

" options for vim-devicons
let g:WebDevIconsOS = 'Darwin'

let g:python_host_skip_check=1
let g:python_host_prog = '/usr/bin/python'
let g:python3_host_skip_check=1
let g:python3_host_prog = '/usr/local/bin/python3'
let g:ruby_host_skip_check=1

" disabled plugins
let g:spacevim_disabled_plugins=[
    \ ['tmux-navigator'],
    \ ]

" let g:spacevim_lint_on_save = 1

noremap <silent> <c-u> :call smooth_scroll#up(&scroll, 0, 2)<CR>
noremap <silent> <c-d> :call smooth_scroll#down(&scroll, 0, 2)<CR>
noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 0, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 0, 4)<CR>



call SpaceVim#layers#load('incsearch')
let g:incsearch#auto_nohlsearch = 0
call SpaceVim#layers#load('autocomplete')
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#ruby')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('tags')

" NeoVim Preview 
set inccommand=nosplit

" Nerdcommenter
let g:NERDCustomDelimiters = {'c': { 'left': '/*', 'rightAlt': '*/' }}


" Default mapping
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'



" Google java formatter 
let g:neoformat_java_google = {
            \ 'exe': 'google-java-format',
            \ 'args': ['-'],
            \ 'stdin': 1,
            \ }
let g:neoformat_enabled_java= ['google']
```

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
I can repruduce it now.

https://asciinema.org/a/DwSly1iBkAFg2DjgViSgd0OiB

BTW, there is also a bug, when cursor is on the top, press `K` will delete the first line, but it should do nothing.

**Comment by wsdjeg** [comment]
![2017-12-06-16-16-28](https://user-images.githubusercontent.com/13142418/33651716-759fa65e-da2c-11e7-8755-31ab00509171.gif)

**Comment by wsdjeg** [comment]
Fixed.

**Comment by icearith** [comment]
@wsdjeg which terminal did you use to record this? My GUI flashes a lot when I hold [SPC] + x + K to keep the line going up.

**Comment by icearith** [comment]
@wsdjeg I tried iterm2 and VimR, they both flash a lot. really annoying. :(

**Comment by icearith** [comment]
@wsdjeg when I press and hold [u] to undo, the line keeps moving down and up smoothly. Is it because of the implementation of moving lines?

**Comment by wsdjeg** [comment]
hmm， I am using neovim  in termite. I do not know if termite has a mac version.

**Comment by wsdjeg** [comment]
hmm. I will try to improve it.

**Comment by icearith** [comment]
@wsdjeg as you can see from your gif above, it does flash a bit, but not much.

**Comment by wsdjeg** [comment]
@icearith can you test the latest version of spacevim? I just improve it.

**Comment by icearith** [comment]
@wsdjeg I tried the latest version, which improved a lot. At least, it does not flash a lot when moving lines up or down. However, it is not as smooth as when you undo the moving. I did some research that `move +1` or `m +1` could move lines down very smoothly, while both the command `move -1` or `m -` does not work in neovim and vim. I tried to bind `move +1` to [SPC] + x + J, it works well, just as smooth as when holding the `u` to undo. 

I also saw some guys on StackOverflow, they mentioned to use `move +1` and `move -1`. I don't know why `move -1` doesn't work, is it because of an implementation change during the time? I will do some more research on this, if this implementation work well on all platform, I will send a PR.

BTW, could you help test the `move` command on your platform, as well as the performance of this command.

**Comment by wsdjeg** [comment]
I use move command for ctrl-Shift-UP/Down in
SpaceVim, I think you Can also check how SpaceVim binding key for this.

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/default.vim#L200

**Comment by icearith** [comment]
@wsdjeg what do the two equals `==` mean?  when I remove the two `==`, the moving seems more smooth. why do you use two different implementations for the same functionality? I am a bit confused about this.

**Comment by icearith** [comment]
Just got some useful explanation for this mapping:

[Link to code](https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/default.vim#L200)

```viml
"Ctrl+Shift+Up/Down to move up and down
  nnoremap <silent><C-S-Down> :m .+1<CR>==
  nnoremap <silent><C-S-Up> :m .-2<CR>==
  inoremap <silent><C-S-Down> <Esc>:m .+1<CR>==gi
  inoremap <silent><C-S-Up> <Esc>:m .-2<CR>==gi
  vnoremap <silent><C-S-Down> :m '>+1<CR>gv=gv
  vnoremap <silent><C-S-Up> :m '<-2<CR>gv=gv
```

The command :m .+1 (which can be abbreviated to :m+) moves the current line to after line number .+1 (current line number + 1). That is, the current line is moved down one line.

The command :m .-2 (which can be abbreviated to :m-2) moves the current line to after line number .-2 (current line number − 2). That is, the current line is moved up one line.

After visually selecting some lines, entering :m '>+1 moves the selected lines to after line number '>+1 (one line after the last selected line; '> is a mark assigned by Vim to identify the selection end). That is, the block of selected lines is moved down one line.

The == re-indents the line to suit its new position. For the visual-mode mappings, gv reselects the last visual block and = re-indents that block.

**Comment by wsdjeg** [comment]
Thanks， and can you send a PR?

**Comment by icearith** [comment]
OK, I will work on this :) @wsdjeg
