### ISSUE TITLE
font is install failed

### ISSUE THREAD

**Issue by linsir6** [wsdjeg/SpaceVim#1058]
## Environment Information
- OS: macos 
- vim version: VIM - Vi IMproved 8.0 
- neovim version:  NVIM v0.2.0

## The reproduce ways from Vim starting (Required!)

when i download spacevim,it report this error

```
Downloaded wingding.ttf
Updating font cache... cp: /Users/mac/.local/share/fonts/*: No such file or directory
done
```

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@linsir6 what is the output of `ls $HOME/.local/share/fonts/*` in your terminal?

**Comment by zg9uagfv** [comment]
run command:

> curl -sLf https://spacevim.org/cn/install.sh | bash


get an error as below:

> `[➭] 正在构建字体缓存，请稍等...
> 
> cp: /Users/xxxx/.local/share/fonts/*: No such file or directory
> 
> [✔] 字体安装已完成!`



Nothing in my ~/.local/share/font/

> `bash-3.2$ ls /Users/xxxx/.local/share/fonts/
> 
> bash-3.2$`

>
