### ISSUE TITLE
markdown plugin error

### ISSUE THREAD

**Issue by linsir6** [wsdjeg/SpaceVim#1059]
## Environment Information
- OS: macos
- vim version: VIM - Vi IMproved 8.0
- neovim version: VIM v0.2.0

## The reproduce ways from Vim starting (Required!)

```
vi xxx.md
:MarkdownPreview
```

![image](https://user-images.githubusercontent.com/16979367/33511405-36cab452-d755-11e7-8cb6-6c91553ddca3.png)

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
your vim has no `+python3` support, and the plugin for preview markdown file needs the feature, I can not fix it, BTW it is not bug.

@iamcco even thouth this is not a bug, but I think when run plugin command, just echo message with error highligh, and catch Unkown func error E117 would be nice and has better iuser experience

**Comment by linsir6** [comment]
![image](https://user-images.githubusercontent.com/16979367/33532493-209cd1e8-d8d5-11e7-93b5-45a64e5ce62c.png)

**Comment by wsdjeg** [comment]
@linsir6 this is just for `+python` not `+python3`,  you should run `pip3 install neovim`

**Comment by iamcco** [comment]
@wsdjeg use echoerr instead of echo，done

**Comment by wsdjeg** [comment]
@iamcco Thanks.
