### ISSUE TITLE
some problems about completion

### ISSUE THREAD

**Issue by fcangss** [wsdjeg/SpaceVim#1062]
## Environment Information
- OS:macos/ubuntu
- vim version: v8.0
- neovim version:

## Output of the ':SPDebugInfo!'
in macos, i find that spacevim can not complete stl key words,the others are ok.
in ubuntu , my spacevim complete nothing.
should i neet to configure some configuration files to solve these problems?

**Comment by tracyone** [comment]
You need to config deoplete-clang plugin.

see https://github.com/zchee/deoplete-clang#gdeopletesourcesclangflags

The smart way is read flag from text file in project root then set the variable of deoplete-clang.

```vim

    function! AddCFlags(dir)
        let l:dir=a:dir.'/'
        if strlen(a:dir) == 0
            let l:dir=getcwd().'/'
        endif
        if empty(glob(l:dir.'.clang_complete'))
           return 1 
        else
            for s:line in readfile(l:dir.'.clang_complete', '')
                :call add(g:deoplete#sources#clang#flags,matchstr(s:line,"\\v[^']+"))
            endfor
        endif
        return 0
    endfunction
    :call AddCFlags('')

```

**Comment by wsdjeg** [comment]
@tracyone but we are use tweekmonster/deoplete-clang2 in spacevim's c layer.

**Comment by tracyone** [comment]
@wsdjeg ok.In this case, "Create a .clang file at your project root.  paste most of your compile flags in there"
