### ISSUE TITLE
Visually mark buffers with modifications

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1066]
Hello,
I was wondering if there is a way to differentiate between saved buffers and buffers with modifications in the top list of buffers.

Before SpaceVim I was using a different plugin (BufExplorer) which had different colours for modified buffers.

**Comment by wsdjeg** [comment]
@crisidev nice feature, will add it. but the latest version of SpaceVim dot support it.

**Comment by crisidev** [comment]
Wonderful, thanks#

**Comment by asim215** [comment]
Hello. Can I somehow add symbol "*" to the tab name which was modified? For example current "1 init.toml" to "*1 init.toml"? I saw that it appeared in the status line (changed from - to *), but how I can add it to tab name? Some color themes make me hard to distinguish between colors (changed buffer) like in gruvbox light.
