### ISSUE TITLE
Install additional Plugins (with specific order)

### ISSUE THREAD

**Issue by weilbith** [wsdjeg/SpaceVim#1073]
Besides the mass of already installed plugins, I wanna install another one on my own. I've got two questions for this:

1. In which configuration I place the _dein.vim_ instructions best? Simply into `.SpaceVim.d/init.vim` and where ever I want?

2. One on these plugins have to be loaded after particular other plugins. E.g. _NERDtree_ . I've set _NERDtree_ as my default file manger in SpaceVim. Any hints how to get this work?

**Comment by wsdjeg** [comment]
you can use g:spacevim_custom_plugins, this option is a list of custom plugins, each item is a list of one or two items. the first one the repos, and the next one is options:  read `:h dein-options` for more info.

here is an example from my own SpaceVim custom config

https://github.com/wsdjeg/DotFiles/blob/master/SpaceVim.d/init.vim

```vim
let g:spacevim_custom_plugins = [
            \ ['tweekmonster/startuptime.vim', {'merged' : 0}],
            \ ['mivok/vimtodo', {'merged' : 0}],
            \ ['rakr/vim-one', {'merged' : 0}],
            \ ['AndrewRadev/undoquit.vim', {'merged' : 0}],
            \ ['junegunn/vader.vim', {'merged' : 0}],
            \ ]
```

**Comment by wsdjeg** [comment]
and if you want to use nerdtree instead of vimfiler, just need to add `let g:spacevim_filemanager             = 'nerdtree'` to your custom config

**Comment by weilbith** [comment]
First: Thanks for the fast response.

Okay, so installing seems to be easy.
Set _NERDtree_ wasn't the problems, cause it was well documented (as I mentioned in the kick of message). But now _NERDtree_ is loaded by _SpaceVim_. If I add some custom plugins, how can I be sure it will be loaded after _NERDtree_ does?
Maybe more specific: I wanna use [Vim-DevIcons](https://github.com/ryanoasis/vim-devicons). It comes around with some features, which apply direct to other plugins. But only if it is loaded after them.

**Comment by Shougo** [comment]
@weilbith You can use `on_source` feature in dein.vim.

Note: NERDTree must be lazy loaded plugin.

**Comment by wsdjeg** [comment]
SpaceVim support icon in file manager. no need to install vim-devicons. it will cause some font issue.

when using vimfiler as file manager, you can set

let g:spacevim_enable_vimfiler_filetypeicon = 1

**Comment by weilbith** [comment]
@Shougo 
Thats a good hint. For others who maybe read this: [here](https://github.com/Shougo/dein.vim/blob/master/doc/dein.txt) it is defined.

@wsdjeg 
I know. Tried this option but am not that impressed by _vimfiler_. I prefer the tree display, when working with directory structures. So far I know, _vimfiler_ always just show the content of a single folder.

**Comment by Shougo** [comment]
> I know. Tried this option but am not that impressed by vimfiler. I prefer the tree display, when working with directory structures. So far I know, vimfiler always just show the content of a single folder.

vimfiler supports explorer mode.
`:VimFiler -explorer`.
And you can toggle the directory tree by `t` key.

**Comment by wsdjeg** [comment]
no，in SpaceVim， by default we use vimfiler as file tree. you can use o to expand the dir

**Comment by weilbith** [comment]
Ok, @wsdjeg ist right. So far I just know _NERDtree_ and there was it the other way around.
Kinda slow when open a subtree, but works.
