### ISSUE TITLE
How do I hide hidden files?

### ISSUE THREAD

**Issue by linwaytin** [wsdjeg/SpaceVim#1075]
Hi guys,

I just tried SpaceVim. The vimfiler is great but I think the documentation is not very complete. I couldn't find a way to hide hidden files. They occupy a lot of space. Is there a way to solve this?

**Comment by wsdjeg** [comment]
the default mapping `.` in vimfiler should hide the dot files.

**Comment by wsdjeg** [comment]
hmm, I have fix it in #1074,

**Comment by linwaytin** [comment]
Now it works! Thank you for such a quick response.

**Comment by wsdjeg** [comment]
welcome
