### ISSUE TITLE
Ultisnip selection does not work anymore

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1078]
One or more of these 3 commits broke Ultisnips selection: 
* d3931cd67334c91c17f3e8922924f9b199608913
* 54ec968bc9e2816477afc2063f6c8f7eb6140f52
* 83568afc5f43b9bf62af808f8edb6302adf2926f

Before commits above if I was in the pumvisible and I moved to a snipped and pressed <Tab>, the snippet was added to my file and than with further presses of <Tab> I was able to navigate between part of the snippets. Now tab just moves to next item in the completion list without expanding the snippet.

This is my current <Tab> mapping:
```
i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
        Last set from ~/.cache/vimfiles/repos/github.com/Valloric/YouCompleteMe/autoload/youcompleteme.vim
```

Also setting ultisnips triggers like this does now work for me:
```
" UltiSnips triggering
let g:UltiSnipsExpandTrigger = '<C-j>'
let g:UltiSnipsJumpForwardTrigger = '<C-j>'
let g:UltiSnipsJumpBackwardTrigger = '<C-k>'
```

**Comment by wsdjeg** [comment]
@crisidev I want to redesign the login of `smart tab` in autocomplete layer, use `Tab` to expand snippet will break the popupmenu feature, people can not select next Item with `Tab`.

**Comment by crisidev** [comment]
Is there any news about this? I still cannot use snippets with YCM. 

I know you prefer supporting deoplete, but I find YCM way faster and with some features which are lacking in deoplete, such has collecting identifiers from tags, documentation and not only from the underlying language provider and especially a very consistent semantic analyzer which allows me to jump to definitions and declarations, rename, and get code documentation without a ton of other plugins like you need in deoplete.

**Comment by wsdjeg** [comment]
Can you list what should be done to support snippet with ycm? This should be done before v0.8.0

**Comment by crisidev** [comment]
Honestly I do not know what should be done.. YCM has a default integration with ultisnippets which is also used to improve the completion terms for the language.

Everything was working fine untill one of the three commits I posted in the first message of this issue.

**Comment by wsdjeg** [comment]
Ok, I will test spacevim with:

```
let g:spacevim_enable_ycm = 1
let g:spacevim_snippet_engine = 'ultisnips'
```

**Comment by wsdjeg** [comment]
![2018-04-22-15-29-25](https://user-images.githubusercontent.com/13142418/39092568-4f229aac-45d6-11e8-953b-08e6b6a8dd94.gif)

**Comment by crisidev** [comment]
Awesome, it works perfectly. Thank you very much!

**Comment by wsdjeg** [comment]
welcome :)
