### ISSUE TITLE
feature request ：is there any time manage plugin in spacevim???

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#1080]
i have an idea: if i open a project in vim ,the plugin can record the time i am using in this project

**Comment by wsdjeg** [comment]
I can not understand it. what info do you want to record?

**Comment by v-leonhou** [comment]
i get it https://github.com/wakatime/vim-wakatime

it's a coding time recorder

**Comment by wsdjeg** [comment]
@v-leonhou what do you want? includ this plugin to which layer? or a new layer for it?

**Comment by v-leonhou** [comment]
no , just want to know is there any  plugin of this type in spacevim, maybe no need to add to spacevim, i will close this issue
