### ISSUE TITLE
Improve smart tab in autocomplete layer

### ISSUE THREAD

**Issue by ihexon** [wsdjeg/SpaceVim#1086]
## Use \<TAB\> to simulating \<Down\> to move cursor down in autocompletion popup menu.
 When I got autocompletion popup menu in vim ：
![screenshot_2017-12-07_10-37-00](https://user-images.githubusercontent.com/14349453/33723405-9e751dc0-db3a-11e7-9dba-1ff7a0162bea.png)

 I want use \<TAB\> to simulating \<Down\> to move cursor down in autocompletion popup menu to select **getchar** like this:
![screenshot_2017-12-07_10-37-00](https://user-images.githubusercontent.com/14349453/33723562-08003b8a-db3b-11e7-8f67-df083b3266f9.png)

But when I `<Tab>`, It only Select the first one **getopt** and automatically expand the code block，That's not what I expected...

I know it can use `<C-n><C-p>` to move Courses down and up, But may use `<Tab>` to move down the courses in popup menu, and use `<Enter>` to expand the code block is a nice idea too!

**Comment by wsdjeg** [comment]
hmm, the smart tab feature has some issue, I think you can use cycle tab feature. just load autocomplete with argv like this:

```vim
call SpaceVim#layers#load('autocomplete', {
  \   'auto-completion-tab-key-behavior' : 'cycle',
   \ })
```

**Comment by wsdjeg** [comment]
It is feature, when enable smart tab, the key `tab` is not only for cycle items in popup menu, it will expand snippet before cursor.
