### ISSUE TITLE
[dein] recache_runtimepath() is disabled in sudo session.

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1088]
![image](https://user-images.githubusercontent.com/22193642/33749957-c81c2d36-dc0b-11e7-8984-a62871cbd92c.png)

## Environment Information
- OS:10.13.2
- vim version:8.0
- neovim version:

**Comment by Shougo** [comment]
It seems dein.vim feature.

**Comment by wsdjeg** [comment]
@Shougo But as I know he is not   using `root`,  how does dein check the root session?

**Comment by wsdjeg** [comment]
@ForestFDemo dein use this func to check if you are a root.

```vim
function! dein#util#_is_sudo() abort
  return $SUDO_USER !=# '' && $USER !=# $SUDO_USER
      \ && $HOME !=# expand('~'.$USER)
      \ && $HOME ==# expand('~'.$SUDO_USER)
endfunction
```

you can test with `:echo dein#util#_is_sudo()`

**Comment by ghost** [comment]
1

**Comment by Shougo** [comment]
`$SUDO_USER` is already set.
I don't know why though.
