### ISSUE TITLE
Toogle Spell Checking Permantently

### ISSUE THREAD

**Issue by weilbith** [wsdjeg/SpaceVim#1089]
The spell checker is available by the shortcut `<space> t S`. But it seems to be 'untoggled' after each restart.
What about the possibility to toggle the spell checker in the configurations?
So far I searched in the [documentation](http://spacevim.org/documentation/) and in the `~/.SpaceVim/autoload/SpaceVim.vim` for such an option, but couldn't find it.

**Comment by wsdjeg** [comment]
spacevim do not enable spell check by default, you can add `set spell` in your custom config.
