### ISSUE TITLE
vim 中项目管理和项目间切换

### ISSUE THREAD

**Issue by snaker95** [wsdjeg/SpaceVim#1090]
## vim 中项目管理和项目间切换
本猿类之前用的sublime, 最近开始学习Vim, 使用spacevim后, 发现其很漂亮, 在学习使用过程中, 觉得
在vim中实现类似IDE中的项目管理, 以及多项目之间的切换, 例如sublime中的control+command+p项目切换
![image](https://user-images.githubusercontent.com/19548096/33769081-b3cf5c6a-dc63-11e7-8fa6-6ae8902846b9.png)

**Comment by wsdjeg** [comment]
我看到这个图片想到两个问题：

1. how to get the project name? it is only the name of the root dir?

2. how to open manager buffer? denite/unite/ctrlp or project manager it's own buffer?

**Comment by snaker95** [comment]
1. 新增一个项目并添加响应的文件目标, 会生成一个****.project的文件记录该项目的对应目录和当前编辑的文件. 
2. 通过快捷键control+command+p, 调用所有项目进行切换

**Comment by wsdjeg** [comment]
不建议在当前目录键如新文件，这种特性只能在IDE里面搞搞，他才不管什么版本控制问题，如果在当前目录新建一些工程文件，很容易污染用户项目。

**Comment by wsdjeg** [comment]
done!
