### ISSUE TITLE
Tagbar - Multiple Error Messages

### ISSUE THREAD

**Issue by weilbith** [wsdjeg/SpaceVim#1097]
## Expected behavior
When I'm in a _C++_ project and open an implementation into a buffer, I get the error messages shown in the screenshot. Obviously I'm not able to open the tagbar buffer at all.
I tried to add the plugin _ctags_ my own trough the `g:spacevim_custom_plugins` option. _Dein_ has installed it successfully, but the exception remains.

## Environment Information
- OS: Ubuntu 16.4 LTS
- vim version: 7.4 (Huge)
- neovim version: 0.2.0-3ppa1~ubuntu16.04.2

## The reproduce ways from Vim starting (Required!)
- Start _Vim_
- Open a `.cpp` file.

### SpaceVim Options :

```viml
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'minor mode lighters', 'version control info']
g:spacevim_enable_statusline_display_mode = 1
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.6.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimQuickFix', 'HelpDescribe']
g:spacevim_default_indent = 2
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'jellybeans'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['vim-scripts/ctags.vim', {'merged': 0}]]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_key_frequency = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_lint_on_save = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'neocomplcache'
g:spacevim_enable_vimfiler_filetypeicon = 1
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = 'DejaVu\ Sans\ Mono\ for\ Powerline\ 11'
g:spacevim_info_symbol = '🛈'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'VersionControl', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'ctrlp', 'autocomplete', 'nvim', 'linux', 'incsearch', 'lang#c', 'lang#elixir', 'lang#haskell', 'lang#java', 'lang#javascript', 'lang#lua', 'lang#perl', 'lang#php', 'lang#python', 'lang#rust', 'lang#swig', 'lang#tmux', 'lang#vim', 'lang#xml', 'shell', 'tools#screensaver', 'tags', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/thore/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_keep_server_alive = 1
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_custom_color_palette = []
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_language = ''
g:spacevim_enable_vimfiler_gitstatus = 1
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/nvim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:18:20] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
```

## Screenshots
![1512821954](https://user-images.githubusercontent.com/12543647/33795613-ff40ae70-dce4-11e7-8058-be1d99ff8857.png)

**Comment by wsdjeg** [comment]
ctags is not a plugin, but it is a command line tools, you need to install it via `sudo apt-get install ctags` or install https://github.com/universal-ctags/ctags

**Comment by weilbith** [comment]
Oh. Was so ensnared into plugins etc. that I havn't thought it could be something in this direction. So I just searched for some _Vim_ specific tool in _GitHub_. I'm sry.
It is working now...

**Comment by wsdjeg** [comment]
greate, enjoy it.

**Comment by weilbith** [comment]
Does not work as expected. :thinking: 
Is there an option to open a static like window that always shows the outline of the currently active buffer. In case it is the vimfiler or something this kind, it just remains in the last buffers state or is empty. 
Looking for something in this direction...

**Comment by wsdjeg** [comment]
can you show me the gif or use asciinema? I can not understand, by default tagbar should show the static of current buffer.

**Comment by weilbith** [comment]
Description:
I'm in the upper left buffer. 
I open the outline with `f o`.
The open buffer will be replicated and on the right side the outline is displayed.
I try to make the window greater, but it doesn't work.

![spacevim_outlinebug](https://user-images.githubusercontent.com/12543647/33796619-b5df371a-dcf8-11e7-8bdb-7425bcfd88cb.gif)

**Comment by wsdjeg** [comment]
@weilbith `f o` is unite-outline, but it is not tagbar, `F2` is Tagbar.

**Comment by weilbith** [comment]
'F2' does nothing for me. Hit and nothing happens. 
So what's unite-outline? Just now from Eclipse or Intellij that's called Outline, so thought that's it.

**Comment by wsdjeg** [comment]
if your `F2` does not work, how about run command `:Tagbar`?

**Comment by weilbith** [comment]
I should not write so much here...
Newbee to Vim and rly wanna learn it. So I crash it a bit and do my whole work there now. Maybe smaller steps would be a better choice.

**Comment by weilbith** [comment]
@wsdjeg
Do u see the "effect" in the gif, that the status lines of the windows, which are not active, have some problems? The segment separators are white and the segments do not change the background colors accordingly. 
Is this behavior normal?

**Comment by wsdjeg** [comment]
It seems too bug of statusline, it does not refused.  but the statusline theme is not gruvbox, you change it?

**Comment by weilbith** [comment]
I changed the colors with `g:spacevim_custom_color_palette`. Moreover I haven't touched it.
