### ISSUE TITLE
[Request] Aggregate plugins of web languages to one layer

### ISSUE THREAD

**Issue by sei40kr** [wsdjeg/SpaceVim#1100]
## Reason

1. As `dein` can load plugins lazily, we have no reason to make each layer small. And I think it will be faster to load by merging plugins to one layer because of less disk I/O.
2. Plugins of web language such as `html`, `less`, `sass` are currently existing in `lang` layer. This is not good. 

## Solution

Merge layers `javascript` , `typescript` and some plugins in `lang` layer to a new layer `web`

**Comment by wsdjeg** [comment]
but some people do not need all the plugins, and you can read the code of spacevim, we do not load plugins in the layer, we just merge them together, and load plugins at the same time.  merging these plugin into one layer will not save much disk I/O.


```vim
function! SpaceVim#plugins#load() abort
  if zvim#plug#enable_plug()
    call zvim#plug#begin(g:spacevim_plugin_bundle_dir)
    call zvim#plug#fetch()
    call s:load_plugins()
    call s:disable_plugins(g:spacevim_disabled_plugins)
    call zvim#plug#end()
  endif

endfunction
function! s:load_plugins() abort
  for group in g:spacevim_plugin_groups
    let g:_spacevim_plugin_layer = group
    for plugin in s:getLayerPlugins(group)
      if len(plugin) == 2
        call zvim#plug#add(plugin[0], plugin[1])
        if zvim#plug#tap(split(plugin[0], '/')[-1]) && get(plugin[1], 'loadconf', 0 )
          call zvim#plug#defind_hooks(split(plugin[0], '/')[-1])
        endif
        if zvim#plug#tap(split(plugin[0], '/')[-1]) && get(plugin[1], 'loadconf_before', 0 )
          call zvim#plug#loadPluginBefore(split(plugin[0], '/')[-1])
        endif
      else
        call zvim#plug#add(plugin[0])
      endif
    endfor
    call s:loadLayerConfig(group)
  endfor
  unlet g:_spacevim_plugin_layer
  for plugin in g:spacevim_custom_plugins
    if len(plugin) == 2
      call zvim#plug#add(plugin[0], plugin[1])
    else
      call zvim#plug#add(plugin[0])
    endif
  endfor
endfunction
```

all plugins are loaded when we `call dein#end()`

**Comment by sei40kr** [comment]
Perhaps it won't reduce disk I/O.
But I don't think it's good idea to put web language plugins (HTML, SCSS, stylus and so on) in `lang` layer.

```vim
" In lang.vim
    let plugins = [
                \ ['groenewege/vim-less',                    { 'on_ft' : ['less']}],
                \ ['cakebaker/scss-syntax.vim',              { 'on_ft' : ['scss','sass']}],
                \ ['hail2u/vim-css3-syntax',                 { 'on_ft' : ['css','scss','sass']}],
                \ ['ap/vim-css-color',                       { 'on_ft' : ['css','scss','sass','less','styl']}],
                \ ['othree/html5.vim',                       { 'on_ft' : ['html']}],
                \ ['wavded/vim-stylus',                      { 'on_ft' : ['stylus']}],
```

I've noticed this when implementing LSP support for CSS.
I think it should be put in other new layer at least.

**Comment by wsdjeg** [comment]
@sei40kr half a year ago, there is not layer named `lang#****`, all language layer are in lang layer, but it make spacevim too heavy.

so I split them into different layers, and I think html scss stylus also should be separated.

before we separate them, maybe we could check out the layer list of spacemacs. :smile:

**Comment by wsdjeg** [comment]
@sei40kr I found enable `use_lsp` in every lang layer maybe is not a good idea, there is an `lsp` layer, all things about lsp maybe should be managered in this layer.

**Comment by sei40kr** [comment]
@wsdjeg 
I agree that too.
I wanted to do so at first, but I noticed that there's no way to check if `lsp` layer included from other layers.

There're some plugins LSP can replace (like TernJS),
and there're also plugins LSP can't replace (like ImportJS, and syntax highlighting and textobj-s).

So language layers should know if there's LSP layer when making plugins list, to stop loading needless plugins.
I think it's possible but it takes much to implement in smarter way.

**Comment by wsdjeg** [comment]
@sei40kr I will implement this feature. I know the lang#* layer should be able to check if the lsp has been enabled for current language.

**Comment by wsdjeg** [comment]
@sei40kr for lsp support, there are too many plugins:

- https://github.com/tjdevries/nvim-langserver-shim created by the auther of neovim's build-in lsp

- https://github.com/autozimu/LanguageClient-neovim **need rust**

- https://github.com/prabirshrestha/vim-lsp pure viml

- https://github.com/natebosch/vim-lsc

**Comment by wsdjeg** [comment]
@prabirshrestha I want to inclue your vim-lsp for vim with out +py feature, Thanks for your work. :)

**Comment by wsdjeg** [comment]
see: https://github.com/SpaceVim/SpaceVim/pull/1165
