### ISSUE TITLE
How to uninstall SpaceVIm on Windows?

### ISSUE THREAD

**Issue by Whisht** [wsdjeg/SpaceVim#1109]
Sorry for that,but I think my workflow doesn't need so complex.I  just need a bike nor a tank~
It seems that `install.sh --uninstall` doesn't work in my machine.
Every time I execute this in powershell,it will call out **git-bash**  and flash without any use.The **Vimfiles,plugins** still exist,I can't go back to my primal vim config.

**Comment by wsdjeg** [comment]
we do not have script for uninstall in windows. you can delete vimfiles in your home dir.
