### ISSUE TITLE
rust support

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#111]
- [x] autocompletion

- [x] syntax check

- [x] go to definetion

~~- [ ] debug~~

**Comment by deepseeksss** [comment]
dose support rust autocompletion now ??? 
i install spacevim today, but not work

**Comment by wsdjeg** [comment]
It should work, you need install racer, OK , I will update lang#rust layer document. 

Thanks for supporting spacevim.

**Comment by deepseeksss** [comment]
i used orginal vim before, i install racer and vim-racer already, it works well.... so, is there some thing should be config?

**Comment by deepseeksss** [comment]
it seems same to #161,  i manually compile the ycm, but when start vim, it says not found module named ycmd...

**Comment by wsdjeg** [comment]
I do not recommand to use youcompleteme, you can use neocomplete by default, but if you really want to use ycm, please read `:h SpaceVim-faq`.

**Comment by wsdjeg** [comment]
rust support is done in #165
