### ISSUE TITLE
Improve the documentation of searching

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1115]
Technically, searching in Spacevim can be roughly subdivided into two categories: **searching files** and **search text**.  

Currently, the documentation contains a loads of key mapping that related to searching. I feel like it's ok to have different combinations of key mapping to trigger different searching actions, but keep the two **category** separated is necessary to keep the documentation readable and understandable. 

Apart from that, key mappings like:

1.  `[SPC] p f`: search files in current project is not included in the doc, which is super useful then.
2. `[SPC] s g G`: grep text  on the fly in current project has two different descriptions in the doc, which should be improved to keep consistency. 

I would suggest that we should split the documentation of searching text and searching file. If you guys think this is necessary, I will send a new PR.

**Comment by wsdjeg** [comment]
I am ok,  but I think in current `Searching section of documentation`, there is only text searching, no file searching.

**Comment by wsdjeg** [comment]
I am ok,  but I think in current `Searching section of documentation`, there is only text searching, no file searching.

for file searching, it should be listed in `Managing projects` with has sama level as `Searching` and `Editing`

https://github.com/SpaceVim/SpaceVim/blob/dev/docs/documentation.md#managing-projects

EDIT:

`SPC s g G` and `SPC s g g` should be kept.

and maybe `SPC s g G` can be change to `SPC s /` or `SPC s  {other char}`?
