### ISSUE TITLE
Fixed Window IDs For Often Used Buffers

### ISSUE THREAD

**Issue by weilbith** [wsdjeg/SpaceVim#1120]
# Feature Request
### Problem / Current Behavior
When spawn new windows, each one get his own ID u can use to quick switch to it. By experiments it's seems to be so, that this ID depends on the order the windows have been spawned. By this it happens that often used buffers with their own window (vimfiler, tagbar, shell, ...) switching their IDs over time and sessions. So it is not possible to learn some automatically key-stroke to quick access such a buffer. You always have to take a quick look on the ID in the responsible statusline. There is not 

### Solution / Expected Behavior
A bunch of standard buffers should get their an option to switch fast to them. This could be a fixed ID or a new shortcut definition.
It could be think about if this should also create the buffer/window if it is not open yet or not.

**Comment by wsdjeg** [comment]
but the windows ID is generated by vim itself, we can not change it. maybe new key bindings for these kind of special buffer will be better.

**Comment by wsdjeg** [comment]
I think change the window number is not a good idea, you can see the pic, all the number is in order, from topleft to downright.

![2017-12-16-13 00 48](https://user-images.githubusercontent.com/13142418/34067485-c907e226-e1ec-11e7-8870-db8a21f7220c.png)

use `F2` and `F3` to quick jump to tagbar, and vimfiler.

**Comment by weilbith** [comment]
@wsdjeg but both toggle these windows. Means  my whole window structure gets destroyed by this. Furthermore it would not help for the console. 
Whats about the idea of the additional shortcuts? Maybe more an option to easily define shortcuts for windows with a specific name in the _init.vim_?

**Comment by wsdjeg** [comment]
can you show me an example? which widow do you want to jump to?

**Comment by weilbith** [comment]
Maybe this feature isn't that well-thought-out. As I realized, _vimfiler_ or _tagbar_ are more visual. Using the _unite_ outline is often faster to use. Same for open files with other tools. The last remain (static) window I continuesly switching to is the console. But that time "lost" shouldn't be the reason to build something new here. 
Thank you! :)

**Comment by wsdjeg** [comment]
if you want to jump back to unite buffer, I think you should use `f r`, which means resume unite buffer. 

This is the feature when press Enter in unite buffer, the unite buffer will be closed.

**Comment by weilbith** [comment]
Sry, was just able to check it out. Nice functionality, but do not show only unite windows and neither the tagbar nor the shell. But that is no problem. Was just an idea.
