### ISSUE TITLE
SPC-f-f not behaving as expected

### ISSUE THREAD

**Issue by Evidlo** [wsdjeg/SpaceVim#1122]
`SPC f f` does not match spacemacs behavior well.  Keep in mind that `SPC f f` in spacemacs is intended for navigation, not searching for files.

Screenshot: [Spacemacs vs Spacevim behavior](https://i.imgur.com/c8YNGr0.png)

## Environment Information
- OS: Fedora 25
- neovim version: 0.1.7
- SpaceVim: 0.6.0-dev

**Comment by wsdjeg** [comment]
spacemacs's `SPC f f` is not better than Spacevim IMO, because it only show files/dirs in path, but do not show all files in the subdirectory.

It is just same as `:Denite file`, but we use `:Dnite file_rec`
