### ISSUE TITLE
C++ code completion with dereferenced objects snaps cursor to similar word

### ISSUE THREAD

**Issue by oliverlars** [wsdjeg/SpaceVim#1128]
## Expected behaviour
Given a function foo(bar *x) inside the body, when I type "x->" it should suggest the member functions/variables and then let me select which one I want and paste the word. 

However, what actually happens is it will snap the cursor to the nearest word, in this case it will snap the cursor to the function definition where the "obj *x" is.

## Environment Information
- OS: Windows 10
- vim version: 80-586
- neovim version: N/A

## The reproduce ways from Vim starting (Required!)
Open a c++ file such as:

`class test{
public:
	x();
	void foo();
};

void bar(test *t){
}
`
accessing the function foo within bar will cause the cursor to snap to "*t"

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
I can not reproduce it, can you make a record via asciinema?
