### ISSUE TITLE
How to disable tabline on startup?

### ISSUE THREAD

**Issue by bfrg** [wsdjeg/SpaceVim#1132]
How can I disable the tabline? I've tried putting 
```vim
set showtabline=0
```
in my `~/.SpaceVim.d/init.vim` file but this has no effect.
It seems like some Vim options are overridden by SpaceVim.

**Comment by Shougo** [comment]
You can test it by `:verbose set showtabline?`

**Comment by wsdjeg** [comment]
@bfrg why do you want to disable tabline, in SpaceVim it is enable by default, and many feature is base on it, for example, use `\+number ` to jump to buffer,  or mouse click on the tabline also switch to the buffer.

if you disable tabline, all these feature will be disabled.

**Comment by bfrg** [comment]
Well, I'm using (Neo)vim so that I don't have to use the mouse anymore 😄 . I also prefer using `<space>bb` to list/switch buffers and similarly `<space>tt` for tabs. Alternatively there's also `]b`, `[b` and `gt`, `gT`. In general, I like to keep my UI very simple. The tabbar is more distracting than useful for me. 
It's too bad that some Vim built-in options cannot be set by the user. Maybe it should be mentioned in the documentation which options will be overridden by SpaceVim.

**Comment by wsdjeg** [comment]
@bfrg sorry, I will update spacevim, and there is no need to override this option.

**Comment by wsdjeg** [comment]
If the pr is merged, you can use `call SpaceVim#layers#disable('core#tabline')` to disable tabline.
