### ISSUE TITLE
not call gofmt when save go files

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1133]
## Environment Information
- OS: any
- vim version: any
- neovim version: any

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Ok, go layer should be updated.

**Comment by wsdjeg** [comment]
@Matrix-Zhang sorry, I can not understand this issue, Is it a bug report or feature request? you want to auto format go file when saving a go file?

**Comment by deepseeksss** [comment]
@wsdjeg 
a feature, right now not auto format when save go files

**Comment by wsdjeg** [comment]
Sorry, We can not add this feature, auto format do is dangerous, SpaceVim should not change content without confirm. If you really need this this feature. I recommand to use custom script.

```
au BufWritePost *.go Neoformat
```

and You can also use `SPC  b f` to format current buffer. BTW, I go layer, we use vim-go, so you can check it's document, I am not sure if It support auto format when save go files.
