### ISSUE TITLE
Leader set - keyboard - idea

### ISSUE THREAD

**Issue by mnivoliez** [wsdjeg/SpaceVim#114]
### Expected behavior, english is recommend
Should spacevim provide different leader set depending of the keyboard? Like for mac keyboard or azerty one? Because depending of the keyboard some default leader will need key combinaisons to be made and vim will record them as combo and not as a single key.

### Environment Information
- OS: osX
- vim version:
- neovim version: 0.1.7

### The reproduce ways from Vim starting (Required!)
Use leader key.

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
Not needed.

**Comment by wsdjeg** [comment]
sorry, I can not understand, in vim, you can set the leader in your vimrc, for example `let mapleader= ","`.

**Comment by mnivoliez** [comment]
I mean currently a default leader set is provided:

> global origin vim leader, default : \
> 
> vim's origin global leader can be used in all the mode.
> local origin vim leader, default : ,
> 
> vim's origin local leader can be used in all the mode.
> windows function leader, default : s
> 
> windows function leader can only be used in normal mode. for the list of mappings see the link
> unite work flow leader, default : f
> 
> unite work flow leader can only be used in normal mode. unite leader need unite groups.

I belived it works just fine why qwerty keyboards since "\" is a plain key. But on other keyboard like mac ones you need to press "ALT+SHIFT+:" to get the same char. Vim/NeoVim interprets it as a combo of key. It's the same for azerty keyboard. Shall SpaceVim include this in its configuration detection? Like to load automatically an optimized set of leaders depending of the keyboard configuration? (For example, like spacemacs with the macos layer)

**Comment by wsdjeg** [comment]
But I can not find the way how to detect the keyboard type, but I think user can change the leader themself.

**Comment by mnivoliez** [comment]
They can of course. But if we could detect it some way. could be an improvement.

**Comment by wsdjeg** [comment]
@mnivoliez Ok, I will try to find how to detect the keyboard type in cli.

**Comment by wsdjeg** [comment]
sorry, I can not find out how to implement this feature. and maybe it should be set by users themself.

**Comment by wsdjeg** [comment]
There is a option `'keymap'`, this should be detected.
