### ISSUE TITLE
Provide a choice for pygments when use the tags layer

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1141]
When use the tags layer, `SPC m g c`  can only create gtags database without --gtagslabel=pygments.  It can provide  a choice to  use this option.  Otherwise,  users need to run `gtags --gtagslabel=pygments` by themselves, it is inconvenient.

**Comment by wsdjeg** [comment]
@nnsnow I think it should base on the filetype of current file, if it is python file, then add this argv, what do you think?

**Comment by wsdjeg** [comment]
@nnsnow please read http://spacevim.org/layers/tags/

gtags will read your config from `~/.globalrc`
