### ISSUE TITLE
Substitute character with `s` doesn't work

### ISSUE THREAD

**Issue by Coffei** [wsdjeg/SpaceVim#1142]
## Expected behavior
The `s` key in normal mode should delete and substitute character, but it does nothing as far as I can tell. The `S` works fine though.
Is there any way to see what action is this key bound to and rebind it to its original action?

I have a fairly clean spacevim installation, just installed yesterday and only enabled some plugins.

## Environment Information
- OS: Fedora 27
- vim version: 8.0
- neovim version: 0.2.2

## Reproducer instructions
Open file, move cursor over some character and hit `s`.

**Comment by wsdjeg** [comment]
Use `s` as a replace key, it a kind of waste, you can use `c` `x` or even`i<bs>`. here is how SpaceVim use `s`

##### Window Management

| Key             |  Mode  | Action                                                                                                                                                                                                                          |
| --------------- | :----: | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `q`             | Normal | Smart buffer close                                                                                                                                                                                                              |
| `s`+`p`         | Normal | Split nicely                                                                                                                                                                                                                    |
| `s`+`v`         | Normal | :split                                                                                                                                                                                                                          |
| `s`+`g`         | Normal | :vsplit                                                                                                                                                                                                                         |
| `s`+`t`         | Normal | Open new tab (:tabnew)                                                                                                                                                                                                          |
| `s`+`o`         | Normal | Close other windows (:only)                                                                                                                                                                                                     |
| `s`+`x`         | Normal | Remove buffer, leave blank window                                                                                                                                                                                               |
| `s`+`q`         | Normal | Closes current buffer (:close)                                                                                                                                                                                                  |
| `s`+`Q`         | Normal | Removes current buffer, left buffer in the tabline will be displayed, if there is no buffer on the left, the right buffer will be displayed, if this is the last buffer in the tabline, then an empty buffer will be displayed. |
| `Tab`           | Normal | Next window or tab                                                                                                                                                                                                              |
| `Shift`+`Tab`   | Normal | Previous window or tab                                                                                                                                                                                                          |
| `<leader>`+`sv` | Normal | Split with previous buffer                                                                                                                                                                                                      |
| `<leader>`+`sg` | Normal | Vertical split with previous buffer                                                                                                                                                                                             |

SpaceVim has mapped normal <kbd>q</kbd> as smart buffer close, the normal func of <kbd>q</kbd>
can be get by <kbd>`<leader>` q r</kbd>


if you do not like this feature, add `let g:spacevim_windows_leader = ''` to your spacevim custom config.

**Comment by Coffei** [comment]
Great, setting the windows leader fixed it.
Thanks, closing the issue.

**Comment by wsdjeg** [comment]
Note: `s` should works well in visual mode.
