### ISSUE TITLE
刚开始装 出错了

### ISSUE THREAD

**Issue by dodong471520** [wsdjeg/SpaceVim#1145]
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..<SNR>40_load_plugins..<SNR>40_loadLayerConfig..SpaceVim#layers#ch
at#config..38:
line   11:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
ValueError: zero length field name in format
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..<SNR>40_load_plugins:
line   16:
E170: Missing :endfor
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load:
line    4:
E171: Missing :endif
Error detected while processing /root/.SpaceVim/vimrc:
line   11:
E171: Missing :endif
Error detected while processing function <SNR>56_neomake_cursor_move_delay:
line    2:
E117: Unknown function: timer_start
Error detected while processing function <SNR>56_neomake_cursor_move_delay:
line    2:
E15: Invalid expression: timer_start(g:neomake_cursormoved_delay, function('s:neomake_signatures_current_error'))

**Comment by wsdjeg** [comment]
Your vim is too old, and do not support timer, `Unknown function: timer_start`.

and please do not use `root`.

**Comment by dodong471520** [comment]
thanks
