### ISSUE TITLE
Suggestions for lang layers

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1148]
As I am currently working on Lua layer, I feel like we should produce something like a template, say, `SPC l r` to run, `SPC l c` to compile or check for syntax. As each language has their own specific feature, the semantics of the key mapping may vary, however, this could still help to keep consistency. if you switch from Java layer to Lua, most key mappings should have roughly the same semantics. 

Apart from that, as the number of the contributors grows, we also need A development guide and convention to help new contributors get started. Also, this could help keep the project organised. 
@wsdjeg

**Comment by wsdjeg** [comment]
@icearith can we talk in #923

**Comment by icearith** [comment]
OK this one can be closed.

**Comment by wsdjeg** [comment]
OK
