### ISSUE TITLE
The Vim will be stuck when i input a dot in the python?

### ISSUE THREAD

**Issue by kecaiwu** [wsdjeg/SpaceVim#1151]
![image](https://user-images.githubusercontent.com/17605639/34237041-7f504cac-e635-11e7-9045-e5cdce09d6e7.png)

sess**.**run()

What should i do, thx?

**Comment by wsdjeg** [comment]
please post info of "SPC h I"

**Comment by kecaiwu** [comment]
![image](https://user-images.githubusercontent.com/17605639/34239829-0d7d8238-e645-11e7-9b13-18cbe6d2bdf4.png)

I'm not change the default configure about the spacevim.

**Comment by wsdjeg** [comment]
you need to post info of "SPC h I", otherwise I Can not check it.

**Comment by kecaiwu** [comment]
I don't know what is "SPC h l" and how to get it. my issue is similiar the #1104.

**Comment by wsdjeg** [comment]
press "space h I"， Then copy the content。

**Comment by kecaiwu** [comment]
SpaceVim layers:

+ VersionControl:           loaded          no exists
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete
+ chat:                     loaded          https://spacevim.org/layers/chat
+ checkers:                 loaded          https://spacevim.org/layers/checkers
- chinese:              not loaded          https://spacevim.org/layers/chinese
+ colorscheme:              loaded          https://spacevim.org/layers/colorscheme
+ core/banner:              loaded          no exists
+ core/statusline:          loaded          no exists
+ core/tabline:             loaded          no exists
+ core:                     loaded          no exists
+ ctrlp:                    loaded          no exists
- debug:                not loaded          https://spacevim.org/layers/debug
+ default:                  loaded          https://spacevim.org/layers/default
- denite:               not loaded          no exists
+ edit:                     loaded          no exists
- exprfold:             not loaded          no exists
+ format:                   loaded          no exists
- games:                not loaded          no exists
+ git:                      loaded          https://spacevim.org/layers/git
+ github:                   loaded          no exists
+ incsearch:                loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          no exists
+ lang/c:                   loaded          https://spacevim.org/layers/lang/c
- lang/clojure:         not loaded          no exists
- lang/crystal:         not loaded          no exists
+ lang/elixir:              loaded          https://spacevim.org/layers/lang/elixir
+ lang/go:                  loaded          https://spacevim.org/layers/lang/go
+ lang/haskell:             loaded          no exists
- lang/java:            not loaded          https://spacevim.org/layers/lang/java
- lang/javascript:      not loaded          https://spacevim.org/layers/lang/javascript
- lang/json:            not loaded          no exists
- lang/julia:           not loaded          no exists
- lang/kotlin:          not loaded          no exists
- lang/lisp:            not loaded          https://spacevim.org/layers/lang/lisp
- lang/lua:             not loaded          no exists
+ lang/markdown:            loaded          https://spacevim.org/layers/lang/markdown
- lang/ocaml:           not loaded          no exists
+ lang/perl:                loaded          no exists
- lang/php:             not loaded          https://spacevim.org/layers/lang/php
- lang/pony:            not loaded          no exists
- lang/ps1:             not loaded          no exists
- lang/puppet:          not loaded          no exists
+ lang/python:              loaded          https://spacevim.org/layers/lang/python
- lang/ruby:            not loaded          https://spacevim.org/layers/lang/ruby
- lang/rust:            not loaded          no exists
- lang/scala:           not loaded          no exists
- lang/sh:              not loaded          no exists

**Comment by wsdjeg** [comment]
"SPC h I" is not "SPC h l"， it is capitalize of `i`
