### ISSUE TITLE
The following problems arise with direct command installation

### ISSUE THREAD

**Issue by rdcentermrzhi** [wsdjeg/SpaceVim#1152]
Use the command -curl -sLf https://spacevim.org/install.sh | bash

There are some problems：

$:vim he
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..<SNR>39_load_plugins..<SNR>39_loadLayerConfig..SpaceVim#layers#chat#config..38:
line   11:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
ValueError: zero length field name in format
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..<SNR>39_load_plugins:
line   16:
E170: Missing :endfor
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load:
line    4:
E171: Missing :endif
Error detected while processing /root/.SpaceVim/vimrc:
line   11:
E171: Missing :endif

**Comment by rdcentermrzhi** [comment]
trouble shooting

**Comment by wsdjeg** [comment]
@rdcentermrzhi what is your `vim --version`? Btw please do not use `root` user, dein do not support `root`.
