### ISSUE TITLE
vimshell configuration does not work

### ISSUE THREAD

**Issue by Yihen-Liu** [wsdjeg/SpaceVim#1153]
## Environment Information
- OS: MacOS 10.10.4
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)

I have add the config of vimshell into init.vim, the content just like below as follow:
call SpaceVim#layers#load('shell',
        \ {
        \ 'default_position' : 'bottom',
        \ 'default_height' : 30,
        \ }
        \ )

however, when I open the terminal, It does not in the bottom; It is in the top;
## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
```vim
call SpaceVim#layers#load('shell',
            \ {
            \ 'default_position' : 'bottom',
            \ 'default_height' : 30,
            \ }
            \ )
```

works well for me.
