### ISSUE TITLE
2 buffer and 1 shell

### ISSUE THREAD

**Issue by hongjiujin** [wsdjeg/SpaceVim#1157]
Hi,

I open two buffer and use SPC '  to open a shell inside buffer.  If SPC b to switch between buffers, once enter into the shell, i dont know how to back to buffer window(code edit).

**Comment by wsdjeg** [comment]
use `Esc` to switch to normal mode, by default, we switch to terminal mode when jump to terminal windows.

you can use `ctrl` + left/up/right/down to swith between windows.

**Comment by hongjiujin** [comment]
No.

1) use SPC ' to open a shell inside buffer
2) use ctrl +w + down to back to buffer
3) use SPC b n to switch, it will automatically enter to shell 
4) can't back to buffer?

**Comment by wsdjeg** [comment]
It is vim's feature. `SPC b n` is `:bnext`, and terminal(shell) is also a buffer. but we can improve it, just make `SPC b n` only switch between listed buffer.

**Comment by hongjiujin** [comment]
Hi,

how to config the font of terminal(shell).

**Comment by wsdjeg** [comment]
It base on what terminal you are using.
