### ISSUE TITLE
Error detected while processing BufEnter Auto commands for "*.ts"

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1158]
## Environment Information
- OS: Ubuntu
- neovim version: 0.2.2

```
Error detected while processing BufEnter Auto commands for "*.ts":                                                                                             
E117: Unknown function: TSOnBufEnter
E117: Unknown function: TSOnBufEnter
```
When I open `*.ts` file, it will report the above mistakes.

**Comment by wsdjeg** [comment]
`call dein#recache_runtimepath()` will fix this issue.

**Comment by darthcoder** [comment]
> 
> 
> `call dein#recache_runtimepath()` will fix this issue.

hi I am getting the same error. I don't understand where I have to write this message, I mean in which file. Can you please guide me?

**Comment by Mayeu** [comment]
@darthcoder You don't have to write that in a file. You have to run that in vim. (hit `:` then type the command).
