### ISSUE TITLE
CSS check tool is invalid

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1159]
## Environment Information
- OS: Ubuntu
- neovim version: 0.2.2

I installed `stylelint cli`, and I also set `let g:neomake_css_enabled_makers = ['stylelint'], but it didn't work.

**Comment by wsdjeg** [comment]
Thanks for reportting , after #1161 is merged, I will check it.

**Comment by wsdjeg** [comment]
you need to run command like `stylelint main.css` in terminal , I think you will see:

```
Error: No configuration provided for /home/wsdjeg/SpaceVim/SpaceVim/main.css
    at module.exports (/home/wsdjeg/.npm-packages/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at stylelint._fullExplorer.load.then.then.config (/home/wsdjeg/.npm-packages/lib/node_modules/stylelint/lib/getConfigForFile.js:46:15)
    at <anonymous>
```

That is why the lint does not work:

please read https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md

cc @blueyed

**Comment by wsdjeg** [comment]
you need to create a `.stylelintrc` file.

**Comment by blueyed** [comment]
Improved this a bit in Neomake: https://github.com/neomake/neomake/pull/1797.

It might be better to trigger a real error message instead, but for that the stylelint maker should be switched to using the JSON output format probably first.
