### ISSUE TITLE
unknown Error

### ISSUE THREAD

**Issue by vingi** [wsdjeg/SpaceVim#1164]
执行SPUpdate时出现未知异常
SPC b m below
![2222](https://user-images.githubusercontent.com/1768640/34320032-002bc922-e82b-11e7-86d3-2ed54c093c4a.png)
SPC h I below

## Environment Information

- OS:Windows
- vim version:
- neovim version:704

### SpaceVim Options :

```viml
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_default_indent = 2
g:spacevim_custom_plugins = [['rking/ag.vim'], ['tacahiroy/vim-vb']]
g:spacevim_buffer_index_type = 1
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_error_symbol = '✖'
g:spacevim_enable_key_frequency = 0
g:spacevim_max_column = 120
g:spacevim_enable_insert_leader = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_enable_neomake = 1
g:spacevim_relativenumber = 1
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_denite_leader = 'F'
g:spacevim_enable_cursorline = 1
g:spacevim_leader_guide_vertical = 0
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'version control info', 'hunks']
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.6.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_plugin_manager = 'dein'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_debug = 1
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_vim_help_language = 'en'
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_autocomplete_method = 'asyncomplete'
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_enable_ycm = 0
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_neobundle_installed = 0
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_enable_powerline_fonts = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_guifont = ''
g:spacevim_language = ''
g:spacevim_plugin_bundle_dir = 'C:\Users\Administrator\.cache\vimfiles\'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_statusline_separator = 'arrow'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_enable_ale = 0
g:spacevim_custom_color_palette = []
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_auto_disable_touchpad = 1
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_keep_server_alive = 1
g:spacevim_unite_leader = 'f'
g:spacevim_disabled_plugins = [['zchee/deoplete-go'], ['lvht/phpcd.vim'], ['lvht/phpfold.vim']]
g:spacevim_info_symbol = '🛈'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'VersionControl', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#banner', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'ctrlp', 'autocomplete', 'nvim', 'windows', 'incsearch', 'lang#c', 'lang#elixir', 'lang#haskell', 'lang#java', 'lang#javascript', 'lang#lua', 'lang#perl', 'lang#php', 'lang#python', 'lang#rust', 'lang#swig', 'lang#tmux', 'lang#vim', 'lang#xml', 'lang#aspvbs', 'shell', 'tools#screensaver', 'aspnetide#aspnetide', 'colorscheme']
g:spacevim_enable_neocomplcache = 0
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_leader_guide_hspace = 5
g:spacevim_windows_index_type = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(C:\tools\neovim\Neovim\bin\nvim.exe)
version: 704
OS: Windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!

```
## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by wsdjeg** [comment]
@vingi what is your custom config? `SPC f v d` could open the custom config.

**Comment by vingi** [comment]
my custom setting below
" Dark powered mode of SpaceVim, generated by SpaceVim automatically.
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#elixir')
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#haskell')
call SpaceVim#layers#load('lang#java')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#perl')
call SpaceVim#layers#load('lang#php')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#rust')
call SpaceVim#layers#load('lang#swig')
call SpaceVim#layers#load('lang#tmux')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('lang#aspvbs')
call SpaceVim#layers#load('shell')   
call SpaceVim#layers#load('tools#screensaver')
call SpaceVim#layers#load('aspnetide#aspnetide')

let g:spacevim_disabled_plugins=[
    \ ['zchee/deoplete-go'],
    \ ['lvht/phpcd.vim'],
    \ ['lvht/phpfold.vim'],
    \ ]

let g:spacevim_custom_plugins = [
    \ ['rking/ag.vim'],
    \ ['tacahiroy/vim-vb'],
    \ ]

let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
let g:deoplete#auto_complete_delay = 150
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:neomake_vim_enabled_makers = []
if executable('vimlint')
    call add(g:neomake_vim_enabled_makers, 'vimlint') 
endif
if executable('vint')
    call add(g:neomake_vim_enabled_makers, 'vint') 
endif
if has('python3')
    let g:ctrlp_map = ''
    nnoremap <silent> <C-p> :Denite file_rec<CR>
endif
let g:clang2_placeholder_next = ''
let g:clang2_placeholder_prev = ''

let Tlist_Show_One_File=1    "不同时显示多个文件的tag，只显示当前文件的
let Tlist_Exit_OnlyWindow=1  "如果taglist窗口是最后一个窗口，则退出vim
let Tlist_Use_Right_Window = 0         "在右侧窗口中显示taglist窗口
" let Tlist_Use_SingleClick= 1    " 缺省情况下，在双击一个tag时，才会跳到该tag定义的位置
let Tlist_Winwidth = 26
let Tlist_Auto_Open = 1       "在启动VIM后，自动打开taglist窗口
let Tlist_Process_File_Always=1  "taglist始终解析文件中的tag，不管taglist窗口有没有打开
let Tlist_File_Fold_Auto_Close=1 "同时显示多个文件中的tag时，可使taglist只显示当前文件tag，其它文件的tag都被折叠起来

" let g:Powerline_symbols = 'unicode'
" let g:airline_powerline_fonts=1

" asp/vb setting
let g:filetype_asa = "vb"
let g:filetype_asp = "vb"
let g:filetype_vbs = "vb"

" set tags=tags;
" set autochdir
set autocmd BufEnter * silent! lcd %:p:h
set ignorecase smartcase

" VimFiler Setting
function! s:VimFilerExplorerFix()
  exec 'VimFilerBufferDir -explorer'
endfunction
noremap <Leader>n :<C-u>call <SID>VimFilerExplorerFix()<cr>

" Tagbar
noremap <F9> :TagbarToggle<CR> 

" insert mode shortcut   
inoremap jj <esc>
inoremap  <C-h>   <Left>
inoremap  <C-j>   <Down>
inoremap  <C-k>   <Up>
inoremap  <C-l>   <Right>
inoremap  <C-d>   <DELETE>

**Comment by wsdjeg** [comment]
`set autocmd BufEnter * silent! lcd %:p:h`

这句 删掉，
