### ISSUE TITLE
php support in windows.

### ISSUE THREAD

**Issue by taurusbo** [wsdjeg/SpaceVim#1168]
win10系统64--neovim64--spacevim
打开php文件的时候卡死，需要从任务管理器中关闭进程才可以关闭。

**Comment by wsdjeg** [comment]
你需要确保，php对应的插件 phpcd 你安装成功了。

**Comment by wsdjeg** [comment]
等 #1165 合并吧，这个PR 里面添加了 php LSP 的支持。

**Comment by taurusbo** [comment]
phpcd已经安装成功了

**Comment by wsdjeg** [comment]
那么打开php卡斯，进程里面卡住的是什么程序？

**Comment by taurusbo** [comment]
nvim-qt.exe进程卡死，nvim.exe进程cpu还在跑。

**Comment by wsdjeg** [comment]
你试过gvim吗？ neovim-qt是一个壳子，很有可能 nvim.exe出错了。

**Comment by taurusbo** [comment]
以前是用gvim不成功，然后安装的neovim

**Comment by wsdjeg** [comment]
It seems phpcd do not support windows.

**Comment by wsdjeg** [comment]
php lsp works well in windows now.
