### ISSUE TITLE
LSP feedback

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1171]
lsp supporting is a new feature in SpaceVim. any feedback is welcome!

**Comment by chairping** [comment]
关于php 的 lsp  貌似没有对应的 与之对应的补全功能。 
像LanguageServer-php-neovim 插件， https://github.com/roxma/LanguageServer-php-neovim/blob/master/ftplugin/php.vim 就有这个功能。

对应php layer 中的phpcd 插件，需要额外的php自动加载配置composer， php才可以自动补全。
要想补全php内置的类和函数， 就需要 https://github.com/JetBrains/phpstorm-stubs （compsoer 自动加载使用）， phpcd有一定的局限性。

**Comment by fcying** [comment]
`SPC l e` not exist, call LanguageClient_textDocument_definition() can work.(clangd, nvim)

**Comment by wsdjeg** [comment]
@fcying which filetype?

**Comment by fcying** [comment]
@wsdjeg 
c && cpp
```
call SpaceVim#layers#load('lsp',
            \ {
            \ 'filetypes' : ['c', 'cpp'],
            \ 'override_cmd' : {
            \ 'c': ['clangd'],
            \ 'cpp': ['clangd']
            \ }})

```

**Comment by wsdjeg** [comment]
I have fixed it, please update SpaceVim.

**Comment by fcying** [comment]
```
call SpaceVim#layers#load('lsp',
            \ {
            \ 'filetypes' : ['c', 'cpp']
            \ })
nnoremap <silent> <leader>gd :call LanguageClient_textDocument_definition()<CR>
```
update to 26234851e157ba, `<leader>gd` work fine, `SPC l e` not exist also.
![1](https://user-images.githubusercontent.com/106934/34349180-7c79d58e-ea4a-11e7-9fbd-dc83451ec6cd.jpg)
