### ISSUE TITLE
linux 普通用户的问题

### ISSUE THREAD

**Issue by snaker95** [wsdjeg/SpaceVim#1172]
请教一下, 我在linux环境中: `普通用户` 执行`curl -sLf https://spacevim.org/install.sh | bash`, 打开vim, 报
![b05ffaca-efeb-4095-8f69-0740399613a0](https://user-images.githubusercontent.com/19548096/34331899-034ff8b2-e966-11e7-8203-7a5449a0ea86.png)

**Comment by wsdjeg** [comment]
what is your vim --version?

**Comment by wsdjeg** [comment]
please install vim8 or neovim
