### ISSUE TITLE
问个弱智的问题，SPC是指什么呢？

### ISSUE THREAD

**Issue by yuzhewo** [wsdjeg/SpaceVim#1173]
各种快捷键使用方法，但是始终不知道SPC是指的什么键？  麻烦懂得人告知一下，win与Mac都说一下呢、、、

**Comment by wsdjeg** [comment]
SPC指的是空格键，normal模式下的自定义快捷键前缀

**Comment by chenlei0x** [comment]
我也搜到这里来了。。。
SPC 还以为是SpaceVim 的Space呢。。。

**Comment by gdbcode** [comment]
谢谢

**Comment by PilotPhil** [comment]
thanks
