### ISSUE TITLE
the priority of .git directory or .projections.json or .clang when creating project

### ISSUE THREAD

**Issue by ws198601** [wsdjeg/SpaceVim#1176]
## Environment Information

- OS:Windows
- vim version:800
- neovim version:

## Output of the `:SPDebugInfo!`
******************************************************
if the parent directory haves .git drectory or .svn drectory  the project root will be the .git drectory,  even if  i have create .clang file in current directory, but the parent directory as the root is not expected.

**Comment by wsdjeg** [comment]
`.clang` is used only when `lang#c` layer is loaded.

**Comment by wsdjeg** [comment]
@ws198601 I have fix this issue in #1245 

please update spacevim, and check the new doc for project manager.
