### ISSUE TITLE
Go support is not loaded anymore

### ISSUE THREAD

**Issue by phacops** [wsdjeg/SpaceVim#118]
### Expected behavior, english is recommend
When opening a Go file, I expect to be able to run a command from the vim-go plugin (for example GoImports). Better, it would run automatically (as the default config is configured that way).

### Environment Information
- OS: Arch Linux
- neovim version: 0.1.7

### The reproduce ways from Vim starting (Required!)
Open a file ending by `.go`, type `<leader>GoImports` and it fails.

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
E492: Not an editor command: GoImports
[ SpaceVim ] : logger file /home/phacops/.SpaceVim/.SpaceVim.log does not exists!

**Comment by wsdjeg** [comment]
Sorry, forgot to add it to default layers, can you send a pr？
In spacevim#default#setplugins just add lang#go

**Comment by phacops** [comment]
Go is already in it (https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/default.vim#L114). Not sure if this is the case. Seems like the plugins is not even registered as in the group or something like that.

**Comment by wsdjeg** [comment]
It is wrong, change  go to lang#go will fix it.
