### ISSUE TITLE
Auto complete crashed after the .clang file was created.

### ISSUE THREAD

**Issue by mrmodolo** [wsdjeg/SpaceVim#1192]
## Environment Information
- OS:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
- vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Correções incluídas: 1-1689
Correções extras:8.0.0056

## The reproduce ways from Vim starting (Required!)
Create a .c file
In the same folder, create the .clang file with the required flags one per line
Open the .c file and test autocompletion.

**Comment by wsdjeg** [comment]
please test it with the latest version of SpaceVim, I just update the c layer.

**Comment by wsdjeg** [comment]
as you said in provious issue, you can not include the dir when edit the `#include` line. I will fix it.

**Comment by wsdjeg** [comment]
Fixed!

![2017-12-28-23 22 36](https://user-images.githubusercontent.com/13142418/34414906-89cecf4c-ebb1-11e7-9d1f-56c6ecfe29db.png)

**Comment by mrmodolo** [comment]
Hi!

I created the .ctags file with the command below and added the flags '-xc', '-Wall', and '-Werror':
`pkg-config --cflags --libs gtk+-3.0 | tr ' ' '\n' > .clang`

I also created the compile_commands.json file with the help of the Bear https://github.com/rizsotto/Bear utility:
`bear make`

It seems to me that the compile_commands.json file is ignored and only the .ctags is read!

The bug does not happen anymore :+1: !!

One question. I have autocomplete based on buffer (B), is there any way to have autocomplete based on the include files? Like the plugin YouCompleteMe?

Anyway, your work is excellent, the VIM is very beautiful! I am attaching the folder with the .clang, compile_commands.json, main.c and Makefile files if they are useful.

[hello.zip](https://github.com/SpaceVim/SpaceVim/files/1591537/hello.zip)

![image](https://user-images.githubusercontent.com/1923174/34415710-4eae589e-ebd7-11e7-9ab5-3e256ebaaa83.png)

Thank you,
Marcelo Módolo

**Comment by wsdjeg** [comment]
in spacevim, `[B]` is just buffer source from deoplete, by default it include words in all loaded buffers, BTW  the best completion item is clang2 source, wich provide syntax completion.

see:

![2017-12-28-22 34 25](https://user-images.githubusercontent.com/13142418/34413715-d34c3468-ebaa-11e7-8387-5924c871f55d.png)

**Comment by mrmodolo** [comment]
How do I trigger this autocomplete?

**Comment by mrmodolo** [comment]
Hi!

I think I found another problem ...
Errors are no longer reported to me!
I inserted a line with garbage, saved with ':w' and no error was reported!

**Comment by mrmodolo** [comment]
Hi!

Am I doing something wrong? Is the format of my .clang file correct?

Thank you
