### ISSUE TITLE
SPCUpdate error, and open php file error

### ISSUE THREAD

**Issue by gatspy** [wsdjeg/SpaceVim#1194]
## Environment Information
- OS: osx `10.12.6`
- vim version: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 22 2017 14:31:27)
macOS version
Included patches: 1-1420
Compiled by Homebrew
```
- neovim version: `NVIM v0.2.2`
- iterm2: `3.1.5`

when run `SPCUpdate` in `nvim`.  has error:
![jietu20171228-231744](https://user-images.githubusercontent.com/804446/34414641-671ee76a-ec25-11e7-8cae-65a6a9fd32f9.jpg)

Use `nvim` open php file, has error:
![jietu20171228-232047](https://user-images.githubusercontent.com/804446/34414720-cc240294-ec25-11e7-8d95-28659a041f58.jpg)

`~/.SpaceVim.d/init.vim` 
```viml
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#elixir')
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#haskell')
call SpaceVim#layers#load('lang#java')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#perl')
call SpaceVim#layers#load('lang#php')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#rust')
call SpaceVim#layers#load('lang#swig')
call SpaceVim#layers#load('lang#tmux')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('shell')
call SpaceVim#layers#load('tools#screensaver')
let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
let g:deoplete#auto_complete_delay = 150
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:neomake_vim_enabled_makers = []
if executable('vimlint')
    call add(g:neomake_vim_enabled_makers, 'vimlint')
endif
if executable('vint')
    call add(g:neomake_vim_enabled_makers, 'vint')
endif
if has('python3')
    let g:ctrlp_map = ''
    nnoremap <silent> <C-p> :Denite file_rec<CR>
endif
let g:clang2_placeholder_next = ''
let g:clang2_placeholder_prev = ''
```

**Comment by wsdjeg** [comment]
you can update spacevim via `:SPUpdate SpaceVim`, then read the php layer doc, by defualt the php layer use phpcd.vim, this plugin requit:


1.  [PHP 5.3+](http://php.net/)
2.  [PCNTL](http://php.net/manual/en/book.pcntl.php) Extension
3.  [Msgpack 0.5.7+(for NeoVim)](https://github.com/msgpack/msgpack-php) Extension or [JSON(for Vim 7.4+)](http://php.net/manual/en/intro.json.php) Extension
4.  [Composer](https://getcomposer.org/) Project

**Comment by gatspy** [comment]
run `:SPUpdate` always show the following error:

```
Error detected while processing function <SNR>278_on_pull_exit[36]..<SNR>278_pull[5]..58:
line    3:
E475: Invalid argument: expected valid directory
Press ENTER or type command to continue
```

**Comment by gatspy** [comment]
This issue can be closed, because the composer is set wrong. remove `.composer` in home ,then run `composer install` in `phpcd` root directory.
By the way, `auto-complete` and `go to define` can not be used, but also need to customize the plugin configuration?

**Comment by wsdjeg** [comment]
you need to load lsp layer for PHP. phpcd do not support gd.

**Comment by TamaMcGlinn** [comment]
I just installed SpaceVim for the first time, ran `:SPUpdate` just as the documentation says I can do to update SpaceVim itself and all plugin, and got the same error. Is the documentation wrong for recommending this?

**Comment by Shougo** [comment]
Please upload the error log.

**Comment by TamaMcGlinn** [comment]
Hmmm... My `~/.local/share/nvim/log` was last updated in 2018. And `$NVIM_LOG_FILE` is an empty string.
Also, I can't reproduce the error upon restarting. Thanks anyway, I will just forget about this.

**Comment by Shougo** [comment]
OK
