### ISSUE TITLE
Tab item still in tab manager when tab has been closed.

### ISSUE THREAD

**Issue by everettjf** [wsdjeg/SpaceVim#1196]
## Expected behavior
Tab item still in tab manager when tab has been closed. Expect tab item not appear in the tab manager when closed.

## Environment Information
- OS:macOS 10.13.1 (17B1003)
- vim version:VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  5 2017 12:26:40)
- neovim version: N/A

## The reproduce ways from Vim starting (Required!)

```
vim
SPC w F
SPC t t
:q
:q
SPC t t
```
Now, there are 2 tab item in the tab manager: 
![image](https://user-images.githubusercontent.com/1665109/34416736-d76e9f42-ec2f-11e7-885d-cacb26c8f43e.png)
Move to the 2nd item( which does not exist) , and try to open it.

```
j
<Enter>
```

Then , the error below occur:
![image](https://user-images.githubusercontent.com/1665109/34416713-b4446290-ec2f-11e7-9679-e0892744d82c.png)

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

[log.log](https://github.com/SpaceVim/SpaceVim/files/1591626/log.log)

**Comment by wsdjeg** [comment]
This is a bug of tabmanager, I will fix it later.
