### ISSUE TITLE
Crash on pasting text 

### ISSUE THREAD

**Issue by da2r-20** [wsdjeg/SpaceVim#1197]
## Expected behavior, english is recommended
Crash when pasting text in a new file

## Environment Information
- OS: Ubuntu 16.04
- vim version: 7.4
   Included patches: 1-1689
   Extra patches: 8.0.0056

## The reproduce ways from Vim starting
- vim t.py
- insert mode
- paste following text

```
# content of test_sample.py
def func(x):
    return x + 1

def test_answer():
    assert func(3) == 5
```

**Comment by wsdjeg** [comment]
I can not reproduce it , and these is no issue template.
