### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by AlphaLiu** [wsdjeg/SpaceVim#12]
Error detected while processing /~/.cache/vimfiles/.cache/vimrc/.dein/plugin/dwm.vim:
line   19:
E117: Unknown function: unite#custom_action
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
@AlphaLiu ~~你好，这是因为unite这个插件没有正常安装，你可以 看看 `ls ~/.cache/vimfiles/repos/github.com/Shougo/unite.vim/` 这个命令输出.~~

sorry , it should be a bug.

**Comment by wsdjeg** [comment]
该文件是 https://github.com/kannokanno/unite-dwm 这一个插件，按理不应该有错误，你的unite安装正常吗， `ls ~/.cache/vimfiles/repos/github.com/Shougo/unite.vim/` 这一命令输出是什么？

**Comment by AlphaLiu** [comment]
确实是unite没有正常安装。
另外还有一个问题是statusbar出现了乱码，应该是我没安装相应的powerline字体。请问默认的字体是什么？怎么修改成我自己的字体？

**Comment by wsdjeg** [comment]
不好意思，这个问题是我的错，因该提供设置来设置字体， 我来修复下。

**Comment by wsdjeg** [comment]
修复了 你可以在 `～/.local.vim` 里面 加入 类似于`let g:spacevim_guifont                 = 'DejaVu\ Sans\ Mono\ for\ Powerline\ 11'`

如果仍然有问题 可以reopen
