### ISSUE TITLE
c/c++ support

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#120]
Spacevim should support c family language.

**Comment by Keepmoving-ZXY** [comment]
Should spacevim Integrate plugins about C/C++ code completion and syntax check,like YouCompleteMe and syntatic?

**Comment by wsdjeg** [comment]
@Keepmoving-ZXY SpaceVim contains these two plugins, but it is disabled by default. for completion spacevim use deoplete and neocomplete as default, for check, spacevim use neomake as default.

**Comment by wsdjeg** [comment]
done;

![2017-01-18-23 46 54](https://cloud.githubusercontent.com/assets/13142418/22071386/fc3c3718-ddd9-11e6-92f4-65cfdb3c004f.png)
