### ISSUE TITLE
Improve SPC f f , expect similar to spacemacs's SPC f f

### ISSUE THREAD

**Issue by everettjf** [wsdjeg/SpaceVim#1210]
曾经使用过spacemacs，使用习惯是这样：
打开emacs
SPC f f 浏览目录、文件的体验会更好。
如图：
![image](https://user-images.githubusercontent.com/1665109/34455940-0c25efba-edc5-11e7-823a-4fb2ba19cda4.png)

---
如果使用SpaceVim，使用习惯可能是这样：
打开MacVim
:e <filepath> 回车

---
启动MacVim后，直接SPC f f ，如下图
![image](https://user-images.githubusercontent.com/1665109/34455946-3641cf3a-edc5-11e7-81a9-0a94a9a0812f.png)
可能由于是HOME目录，文件很多，功能应该是失效的。（当前buffer对应的文件如果在某个文件少的目录下，是可以输入文件名过滤的方式打开的，如下图）

![image](https://user-images.githubusercontent.com/1665109/34455978-e9800760-edc5-11e7-8d69-79eccea3a716.png)

---

希望增加的功能是：启动MacVim后，SPC f f 能有个文件浏览器逐步定位打开文件。简单说就是能和spacemacs 的SPC f f一样哈。

**Comment by tracyone** [comment]
音区思婷，好像没找到

**Comment by wsdjeg** [comment]
@everettjf 我知道你说的内容是什么意思了，你可以试试 `:Denite file`, 这个命令应该和你说的功能类似，但是这个功能不能展开子目录，仅仅显示一层机构，不太适合全局打开工程项目。

**Comment by wsdjeg** [comment]
and some feature is missed in `Denite file`.

**Comment by everettjf** [comment]
@wsdjeg 确实 `f f`可以实现我类似的需求。哈哈。不过`SPC f f`在当前文件所在文件夹的文件特别多的情况下看起来是工作不正常。例如我的HOME目录下，`SPC f f`就没有内容显示。

@tracyone 你可以试试`f f`

**Comment by everettjf** [comment]
仔细试了试 `f f`，在HOME下文件多的情况下，仍然是比较卡。再研究研究了。

**Comment by Pillar1989** [comment]
我觉得SpaceVim就应该是SpaceVim， 不能说spacemacs有的，就要有。

**Comment by wsdjeg** [comment]
是的，我还是希望更具需求来实现功能

**Comment by everettjf** [comment]
@Pillar1989 赞同。`f f`可以看怎么优化下。
这个issue还是关闭啦

**Comment by wsdjeg** [comment]
其实你可以试试 `F f` :)

**Comment by tracyone** [comment]
https://github.com/tracyone/ctrlp-findfile

**Comment by wsdjeg** [comment]
@tracyone SpaceVim has already support this feature, and it is same as `Denite file` , but you link is for vim without +py3. good job.
