### ISSUE TITLE
Issue w/ Clean SpaceVim Install

### ISSUE THREAD

**Issue by mmstick** [wsdjeg/SpaceVim#1211]
- OS: Solus OS
- NeoVIM: 0.2.2

Basically, running the curl | bash script generates the following errors:

```
[dein] neosnippet-snippets
[dein] Error revision number: fatal: Not a git repository (or any of the parent directories): .git
[dein] jellybeans.vim
[dein] Error revision number: fatal: Not a git repository (or any of the parent directories): .git
```

Then when using it, it will generate errors at first run regarding some plugins failing to update, and when entering into insert mode, an error about neosnippet-snippets being missing.

**Comment by wsdjeg** [comment]
`call dein#reinstall(['jellybeans.vim', 'neosnippet-snippets'])`

**Comment by mmstick** [comment]
@wsdjeg Thanks. That worked.

**Comment by mmstick** [comment]
Although the error comes back after restarting nvim.

**Comment by wsdjeg** [comment]
you need `call dein#recache_runtimepath()`
