### ISSUE TITLE
SpaceVim: Updating failed,  The plugin dir is dirty

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [wsdjeg/SpaceVim#1212]
## Expected behavior, english is recommended
When I run SPUpdate SpaceVim i'm getting this error "SpaceVim: Updating failed,  The plugin dir is dirty"

## Environment Information
- OS: 10.13.1
- vim version: 8.0.1420 (144)

## The reproduce ways from Vim starting (Required!)
SPUpdate SpaceVim

**Comment by dbrw** [comment]
Did you change any file on `~/.SpaceVim` directory?
The error similar to git error. Maybe running `git checkout .` on `~/.SpaceVim` directory before updating SpaceVim will help.

**Comment by wsdjeg** [comment]
This error message has already tell you what is going on:

`"SpaceVim: Updating failed, The plugin dir is dirty"`

you need run `git checkout .` in `~/.SpaceVim`

**Comment by CodeMonkeyKevin** [comment]
I tried git checkout . and it has no issue but still get this update error.

**Comment by wsdjeg** [comment]
you can reinstall this plugin which directory is dirty.

**Comment by pedrogarrett** [comment]
I'm getting this error as well. ~/.SpaceVim is clean, and "git checkout ." does not help.

What do you mean by "you can reinstall this plugin which directory is dirty"?

**Comment by CodeMonkeyKevin** [comment]
Ya, I can't figure out how to clean out the plugin dir as well. I'm still facing this issue.

**Comment by wsdjeg** [comment]
please use new issue

**Comment by pedrogarrett** [comment]
I've discovered that if I checkout the "master" branch in the ~/.SpaceVim/ folder, then updating works.

The "dev" branch was what was checked out before. Is being on the "master" branch correct?

**Comment by wsdjeg** [comment]
yeah， dev branch has been deleted.

**Comment by batFINGER** [comment]
Came across this issue also.  Suggest running  "git status" remove listed files, and then pull.

**Comment by ehytig** [comment]
> Came across this issue also. Suggest running "git status" remove listed files, and then pull.

Really help. It seems that I modified some files in ~/.SpaceVim so this issue occured.

**Comment by Bost** [comment]
> I've discovered that if I checkout the "master" branch in the ~/.SpaceVim/ folder, then updating works.
> 
> The "dev" branch was what was checked out before. Is being on the "master" branch correct?

It's looks like it you must be on a master branch. No other branch name works. So if you want to use a stable release do (e.g. for the 1.7.0 release):
```bash
git checkout v1.7.0 -B master
```
Edit: and it looks like anytime I do `:SPUpdate` the tip of the branch is fast-forwarded and I have to repeat this command again. Hmm.

**Comment by relh** [comment]
This link has the answer: [https://frantzroulet.com/blog/jekyll/update/2021/11/16/how_to_fix_the_spacevim_error_updating_failed__the_plugin_dir_is_dirty.html](https://frantzroulet.com/blog/jekyll/update/2021/11/16/how_to_fix_the_spacevim_error_updating_failed__the_plugin_dir_is_dirty.html)

Basically you need to additionally delete all the cached .github.com files to get :SPUpdate to not complain:

`rm -rf ~/.cache/vimfiles/repos/github.com/*`

**Comment by wasaCheney** [comment]
Same issue, and helps a lot, thx @relh
