### ISSUE TITLE
Plugins failing during update: FlatColor, phpcd, phpfold

### ISSUE THREAD

**Issue by shoemakerdr** [wsdjeg/SpaceVim#1225]
## Expected behavior, english is recommended

Expected all plugins to update successfully

## Environment Information
- OS: macOS High Sierra 10.13.2
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)

Run `:SPUpdate`.

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

![spacevim-fail](https://user-images.githubusercontent.com/24695425/34539145-03569a42-f095-11e7-930e-db6fc22012bb.jpeg)

![spacevim-fail2](https://user-images.githubusercontent.com/24695425/34539146-054de530-f095-11e7-96c2-22ee860beecd.jpeg)

**Comment by wsdjeg** [comment]
use gf on the line of the plugin to open the plugin dir, the update it with git commnd. the author use git push -f in the repo of FlatColor. I can not fix it.


for phpcd and phpfold, you have a try with compeser install

**Comment by shoemakerdr** [comment]
Got it. I don't use either of these plugins, but I didn't know if this was some kind of issue that would affect other users. I'll close this one out. Thanks!

**Comment by wsdjeg** [comment]
Thanks
