### ISSUE TITLE
Locate code about window management

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#1229]
## Expected behavior, english is recommended
How can I locate the codes about window management? 
I've spent too much time finding it. Still couldn't find where it is

## Screenshots
![image](https://user-images.githubusercontent.com/12933851/34552303-94ad80fc-f15b-11e7-9b9e-ce8f942f2e60.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Gabirel** [comment]
It's here: https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/mapping/leader.vim#L158-L163

It is in the `leader.vim`. Too hard to find it.

**Comment by wsdjeg** [comment]
@Gabirel I reopen this issue, add will add discribe for `s` prefix key bindings.

after implement this featue, you will be able to jump to the code via `SPC h d k s q g d`

`SPC h d k` will start a discribe prompt, and insert the key bindings you want, when find the discribe, it will open a help buffer, then you can use `g d` to jump to the definition position.

now you can try:  `SPC h d k SPC b n` then press `g d`.

**Comment by Gabirel** [comment]
Awesome feature!! Looking forward to it
