### ISSUE TITLE
Error detected while processing function asyncomplete#register_source[5]..

### ISSUE THREAD

**Issue by OATOMO** [wsdjeg/SpaceVim#1234]
[
## Environment Information
- OS: ubuntu
- vim version: 7.4
- neovim version:

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![spacevim](https://user-images.githubusercontent.com/27196560/34562993-b135ca24-f18b-11e7-89f6-f3096a6811c4.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@OATOMO we use `has('timers')` as the checker for using asyncomplete, maybe it is wrong, `getbufinfo()` is added in patch-7.4.2204, and `+timers` is added in patch-7.4.1626.

I am not sure what is the minimum version for asyncomplete. Is it possible to find the minimum version for this plugin?

cc @prabirshrestha

**Comment by OATOMO** [comment]
I don't know why，but it works

**Comment by OATOMO** [comment]
thank you

**Comment by prabirshrestha** [comment]
@wsdjeg Can you file a new bug in asyncomplete about `getbufinfo()`. We should be only dependent on `timers()`.

This PR which was merged couple of days brought dependency in `getbufinfo`. https://github.com/prabirshrestha/asyncomplete.vim/pull/42
I would be more than happy to revert that change if you can verify and that version of Ubuntu ships with older version of vim without `getbufinfo`. Most OS ship with older version of vim so I would like asyncomplete to support it if possible. And then I could enable caching of sources only if `getbufinfo()` exists.

**Comment by wsdjeg** [comment]
OK, Will look into it.

**Comment by prabirshrestha** [comment]
I have reverted the change.

**Comment by wsdjeg** [comment]
@prabirshrestha Thanks, I close this issue.
