### ISSUE TITLE
Unknown linter ICON

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1242]
https://github.com/SpaceVim/SpaceVim/blob/dfee127e6fdd9f5034f5380626356b6945341c11/config/plugins/neomake.vim#L33

Let's choose a proper one. This icon does not work well with `powerline` and `nerdfont`. I will send a PR after a decision is made.

**Comment by wsdjeg** [comment]
![2018-01-05_85x82](https://user-images.githubusercontent.com/13142418/34599956-c5da952a-f1ba-11e7-884c-be912a9d43c3.png)


It works well for me.

```
charmap -p 🛈
🛈	U+1F6C8	CIRCLED INFORMATION SOURCE
```

**Comment by wsdjeg** [comment]
move your cursor onto this char, and press `ga` you will see the char info.

**Comment by icearith** [comment]
which font are you using? it's wired isn't.  

spacevim_warning_symbol and error symbol works well with my powerline font patched with nerdfont

**Comment by wsdjeg** [comment]
Noto Sans symbols

**Comment by wsdjeg** [comment]
It is `Transport and Map symbols` groups

**Comment by icearith** [comment]
I tried this font, it still doesn't work, so I am wondering if this is related to my OS, I am using macOS 10.13.2. 

I will try this on my Linux desktop when I got home.

**Comment by icearith** [comment]
@wsdjeg are you using this font?

https://github.com/powerline/fonts/tree/master/NotoMono

**Comment by wsdjeg** [comment]
I use the spacevim's install script to install font. :)
