### ISSUE TITLE
very slow when enter insert mode and werid hehavior when input `.` in cpp file

### ISSUE THREAD

**Issue by zhangzq** [wsdjeg/SpaceVim#1243]
## Expected behavior, english is recommended

1. very slow, specialy when switch mode, e.g. press `i` to enter insert mode will cost 2 seconds.
2. very werid behavior. when I edit a cpp file, insert any '.' will cause cursor jump to other place. for example, when I enter 'abc.', then will jump to a previous abc.

I install spacevim with document and all default config, didn't change any file.

I tried on two difference machines (all with ubuntu 16.04), both have above two problems.

## Environment Information
- OS: ubuntu 16.04
- vim version:
- neovim version:  v0.2.2

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

No custom config.

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by zhangzq** [comment]
when add support of python，the problem two is fixed.

**Comment by zhangzq** [comment]
another problem, when enter something, will output a warning on the bottom:
```
plugin : indentLines has not been installed, please use `:call dein#install(["indentLine"])` to install this plugin,
```
but when I type `:call dein#install(["indentLine"])` , I got:

```
[dein] Target plugins are not found.
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.
```

**Comment by wsdjeg** [comment]
@zhangzq please use issue template, I need to check the spacevim optinons. 

and you need to use `:SPUpdate indentLine`

**Comment by JinsongWei263** [comment]
@zhangzq How to add support of python?

**Comment by weijinsong** [comment]
Thanks for your help!
I recompiled vim8.0 with python support. After that my spacevim behaviors properly.
