### ISSUE TITLE
vim looks not ok

### ISSUE THREAD

**Issue by lxlhlp** [wsdjeg/SpaceVim#1247]
## Expected behavior, english is recommended
in terminal vim seems not ok
but in gvim its all right

## Environment Information
- OS:macOs X
- vim version:macVim or vim installed by brew

## Screenshots
![image](https://user-images.githubusercontent.com/8266227/34609044-107e56fc-f256-11e7-830e-d8268d4fe92d.png)

![image](https://user-images.githubusercontent.com/8266227/34610411-f7e40ac8-f25b-11e7-912f-6f5d048d7e98.png)

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/issues?q=is%3Aissue+true+colors+is%3Aclosed

**Comment by lxlhlp** [comment]
I still dont konw how to fix it

**Comment by wsdjeg** [comment]
you need make sure your terminal support true color.
