### ISSUE TITLE
mac 终端vim 主题颜色显示异常

### ISSUE THREAD

**Issue by lxlhlp** [wsdjeg/SpaceVim#1249]
## Expected behavior, english is recommended
为了使用clipboard 使用brew 安装了vim 8.0
发现终端使用时主题颜色显示异常，而mac自带及macVim 的 gvim无异常

## Environment Information
- OS:macOS X
- vim version: vim8.0

## The reproduce ways from Vim starting (Required!)
``` ssh
brew install vim
# 新开终端页面
vim
```

## Screenshots
*  text  /usr/local/bin/vim
异常截图
![image](https://user-images.githubusercontent.com/8266227/34620340-1f798062-f280-11e7-822f-b00b6bea91fa.png)

* text /usr/bin/vim
正常截图
![image](https://user-images.githubusercontent.com/8266227/34620381-3fda30c2-f280-11e7-9557-aee6f5b5fd3a.png)

**Comment by tracyone** [comment]
You need a terminal emulator which is support true color.

**Comment by magiclyx** [comment]
Consider using iterm.

 In addition，spacevim can not work correctly with “brew install vim”. you should add compile options to generate a "huge feature" version

**Comment by lxlhlp** [comment]
it's not work well when use mac native terminal even add compile options to generate a "huge feature" version.
however it perform perfect  with iterm2-nightly,anyway thanks~
