### ISSUE TITLE
vim get very slow when i paste something from the system clipboard into vim

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#125]
when i want to paste something in my system clipboard into vim ,vim get very slowy ,and it's like when i input something from keyboard because the compelte function is excuting,so how to get this fixed?  i think 
spacevim could fix this by detecting the input method ,if the input method is from keyboad ,the complete function may be execute ,but when the input is from the keyboard ,disable the complete detect

**Comment by Shougo** [comment]
Hint: `:help 'paste'`

**Comment by v-leonhou** [comment]
get it ,thanks
