### ISSUE TITLE
please use `:call dein#install(["indentLine"])` 

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1252]
在我的Mac系统中，当我按 i （输入）的时候的时候，出现下面的提示：`plugin : indentLines has not been installed, please use `:call dein#install(["indentLine"])` to install this plugin,`，然后我输入了：`:call dein#install(["indentLine"])`提示信息为：`update/install is disable in sudo session Spacevim`,最后我安装完后运行 vim 没有出现欢迎界面。

**Comment by wsdjeg** [comment]
Dein do not support sudo session. This can not be fixed in SpaceVim. you should make sure you are not using `"sudo"`.

**Comment by chinaxy1** [comment]
no help.

**Comment by unlockingc** [comment]
run
```
:call dein#install(["indentLine"]
:call dein#install(["indentLines"]
```
shows 

```
[dein] Target plugins are not found.
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.
```

**Comment by bartenbach** [comment]
Same.  Running either does not install the plugin.

Edit:  I am not running Vim as root.

**Comment by wsdjeg** [comment]
please use new issue instead.

**Comment by xuanyimo** [comment]
Update vim to latest version.

**Comment by westfly** [comment]
Update vim on Ubuntu20.04
```
sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim
```
