### ISSUE TITLE
-> operation issue

### ISSUE THREAD

**Issue by hongjiujing** [wsdjeg/SpaceVim#1259]
## Environment Information
- OS:Ubuntu
- vim version:VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 27 2017 13:21:06)
- neovim version:

## The reproduce ways from Vim starting (Required!)
git pull the latest spacevim
vim 1.c
ci->hdr = "test";
type another "ci->xxx", the cursor will jumping.

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
I can not reproduce it, please use issue template, and you need to post debug info.
