### ISSUE TITLE
when open multipule buffer ,the bufferline display get wrong 

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#126]
![t27 ex e6 5fs lpez4z if](https://cloud.githubusercontent.com/assets/8463045/22055621/058840f2-dd97-11e6-9ed1-38aa7ca3e004.png)
 you can see buffer 5 and buffer 6 is normal while buffer 8,9,10 get wrong character

**Comment by wsdjeg** [comment]
You need install poweline font, and you can find it in my dotfiles.

**Comment by v-leonhou** [comment]
ok ，get it ，i have fixed this ,thanks
