### ISSUE TITLE
Set project title for file tree

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1261]
in vimfiler, the first line is:

```
[in] /home/wsdjeg/SpaceVim
```

I hope vimfiler provide a option to set the text. we can use a funcref as the value of the func. and call this func with one argv (path). then return the text which will be used as title.

see the picture in emacs.

![pic](https://cloud.githubusercontent.com/assets/2835826/23342211/60fc4608-fc24-11e6-898e-cec9cab9a44e.png)

**Comment by Shougo** [comment]
Sorry, I don't want to add the feature in vimfiler.
Because I should create the new file explorer instead.

**Comment by wsdjeg** [comment]
Yeah, That would be better, hope this feature can be implemeneted in the new file explorer plugin.

**Comment by Shougo** [comment]
OK.  Todo listed in defx.nvim.

**Comment by wsdjeg** [comment]
Thanks
