### ISSUE TITLE
typing do not trigger completion list, but itself completion work 

### ISSUE THREAD

**Issue by robgrzel** [wsdjeg/SpaceVim#1267]
Hi! This distro is wonderfull! Good job guys! Keep fighting then ship it as v 1.0 🗡 !!!

[I will populate more info later]

## Expected behavior, english is recommended

Yesterday I had problem with my windows ubuntu subsystem. Maybe its due to using wsl-terminal that give me 256 colors, but as in topic, completion do not trigger menu.

When I work in python file, ie. test.py:

I do:

def...

And expect it to trigger list like:

> def
> defc
> defm
> defd
> ...

Just nothing shows. But when I press <CR> (do not remember exactly what key it was), I get:

```
def myfunc():
      pass
```

So something is working. I removed spacevim, but will set it again, then put debug infor here. I did it before, and only LUA was not working, is it bcos of this I have that bug?

## Environment Information
- OS: Windows ubuntu subsystem
- vim version: -
- neovim version: v0.2.2

## The reproduce ways from Vim starting (Required!)

nvim test.py
:w!<CR>
#type
def<CR>

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
auto completion does not work.
But neosnippet works.

**Comment by wsdjeg** [comment]
SpaceVim/vim-luacomplete only support Vim now， neovim support needs if_lua.

**Comment by robgrzel** [comment]
Im noob in vim, just started few days ago. 
So sorry for miss conceptions, 
but what plugin gives this drop down poping out
menu when I start typing, is it snippet or completion plugin?

So when I start typing "def" and then 
would like to trigger this menu with list of patterns, 
it will be triggered by snippets or deoplete? 

So to make it work properly deoplete requires lua? 
Then I just need to install lua. Or I need to get nvim that was build with lua too?

**Comment by wsdjeg** [comment]
deoplete is a completion plugin for multiple sources, snippet source, omni source, etc. 

vim-luacomplete is a omni plugin for lua. it need Vim compile with +lua.

when typing, the popupmenu is out, it should cotains snippet and buffer words, but I think you want omni completion which is provided by vim-luacomplete.

in insert mode if the tab key is binded as smart tab, it can expand snippet or select next item in popupmenu.

I recommend you to readme the SpaceVim's autocomplete layer doc, you Can set tab as cycle only.

**Comment by Shougo** [comment]
> So to make it work properly deoplete requires lua?

No.

**Comment by robgrzel** [comment]
![You know this guy? Hes famous and asian too! Somehow this memo was first thing I thought about now -.-](https://user-images.githubusercontent.com/7314853/34862141-07861acc-f769-11e7-8fc7-f66a5272a35f.jpg)

Anyway will try to crack it!

**Comment by robgrzel** [comment]
ok, i made it work, but dont remember exactly how,
will read logs, like this apt-get log: /var/log/apt/history.log
then put steps here I had taken

**Comment by robgrzel** [comment]
Also is it possible to use both YCM and deoplete? Will they crash or something if I use both? They are separate servers right?

**Comment by robgrzel** [comment]
I found out that ycm is much more smooth, maybe its due to working on wsl-terminal on windows that lay pipe on ubuntu bash, so I had build in lags already. Deoplete is so laggy due to its beeing in python or other dynamic o-language?

**Comment by Shougo** [comment]
> Also is it possible to use both YCM and deoplete? Will they crash or something if I use both? They are separate servers right?

You should not the mix.  It conflicts.

> I found out that ycm is much more smooth, maybe its due to working on wsl-terminal on windows that lay pipe on ubuntu bash, so I had build in lags already. Deoplete is so laggy due to its beeing in python or other dynamic o-language?

In virtual box or Linux environment, deoplete is faster.

https://github.com/Shougo/deoplete.nvim/issues/471

**Comment by Shougo** [comment]
@robgrzel You can test the brunch.
It is faster than before.

https://github.com/Shougo/deoplete.nvim/issues/471
