### ISSUE TITLE
Key Binding

### ISSUE THREAD

**Issue by sentient-22** [wsdjeg/SpaceVim#1269]
No doubt, space vim is awesome, but I spent 6 months learning vim keybinding, for example, ESC q > quit, but there everything is bound to space. SPC was there special need to do that. Was there any special reason to map ESC to SPC ?

**Comment by wsdjeg** [comment]
@valhalla22 what do you mean? SpaceVim do not map `Esc` in normal mode. if you like use `ESC q` to quit vim, you can use add the key bindings into spacevim custom config.

**Comment by sentient-22** [comment]
Yeah, later i figured it, its working with both binding. I think it was my anxiety for being idiot. Thanks for response.

**Comment by wsdjeg** [comment]
welcome, enjoy spacevim, you will like it, :)
