### ISSUE TITLE
Could we change or add  `SPC c l` with `SPC c c` to comment lines?

### ISSUE THREAD

**Issue by everettjf** [wsdjeg/SpaceVim#1275]
As I see that commenting lines is the most common use actions in the `SPC c` menus, except for the `SPC c l`. I recommend that change `SPC c l`  to `SPC c l` when `c` is still unused in `SPC c` menus.

Or ,how could I add my own mapping (in to init.vim) `SPC c c` to implement the `comment lines` feature?

**Comment by wsdjeg** [comment]
> I recommend that change SPC c l to SPC c l when c is still unused in SPC c menus.

what do you mean?

**Comment by wsdjeg** [comment]
you can use:

```vim
call SpaceVim#custom#SPC('nmap', ['c', 'c'], '<Plug>NERDCommenterInvert', 'comment or uncomment lines', 0)
```

**Comment by everettjf** [comment]
Thanks

**Comment by everettjf** [comment]
`SPC c c` is still not mapped by any actions. haha . I think it is the best key for comment lines.

**Comment by wsdjeg** [comment]
I do not like press same key twice, it will hurt your fingers.
