### ISSUE TITLE
Question: How to toggle background setting permanently

### ISSUE THREAD

**Issue by foxyblocks** [wsdjeg/SpaceVim#1280]
I'd like toggle the background off permanently (`SPC t b`), but I can't seem to find what setting corresponds to this toggle. Is there a good way to find what setting corresponds to each toggle?

## Background

I just setup a fresh spacevim installation and followed the instructions to choose the one dark colorscheme, by adding the following to my config. 
```
let g:spacevim_colorscheme = 'one'
let g:spacevim_colorscheme_bg = 'dark'
```
It sets the the correctly but the background is white, not dark. running `spc t b` fixes the issue but I want it to save that setting rather than having to run it every time at startup.

**Comment by wsdjeg** [comment]
This is a bug of vim-one, see https://github.com/SpaceVim/SpaceVim/issues/507

**Comment by wsdjeg** [comment]
also see https://github.com/rakr/vim-one/pull/72
