### ISSUE TITLE
Language client settings won't be loaded when no file specified on launch

### ISSUE THREAD

**Issue by sei40kr** [wsdjeg/SpaceVim#1281]
@wsdjeg 
Could you revert this commit? It includes a bug. I'm sorry.
https://github.com/SpaceVim/SpaceVim/commit/eeef756b8a53317e90fe274b9a5f420a6591b4b7

## Expected behavior, english is recommended

* Language client settings are loaded.

## Environment Information
- OS: any
- vim version: any
- neovim version: any

## The reproduce ways from Vim starting (Required!)

* Change language client settings
* Add lsp layer with some filetype(s)
* Install language server(s)
* Launch Neovim
* Language client settings won't be loaded

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
sorry， we can not revert commit，It will break autoupdate when user run git pull. But we can use new commit, I will look into it tonight.

**Comment by sei40kr** [comment]
I've created PR.
https://github.com/SpaceVim/SpaceVim/pull/1282

**Comment by wsdjeg** [comment]
Ok, merged, Thanks

**Comment by wsdjeg** [comment]
@sei40kr can be closed?

**Comment by sei40kr** [comment]
I'm closing this ticket. I'll create a new ticket about the original issue.

**Comment by wsdjeg** [comment]
ok
