### ISSUE TITLE
ES6 project, how to fix jshint: use 'esversion: 6'?

### ISSUE THREAD

**Issue by codesve** [wsdjeg/SpaceVim#1283]
I'am not use `jshint` before.

I find a [solution](https://stackoverflow.com/questions/27441803/why-does-jshint-throw-a-warning-if-i-am-using-const) is add a `.jshintrc` file in project root.

But I want to know is there a way to fix it in `spacevim`? 

Thanks.

## Screenshots
![image](https://user-images.githubusercontent.com/5095947/34978217-744304dc-fad8-11e7-9606-b9449344376f.png)

**Comment by wsdjeg** [comment]
you need to add a `.jshintrc` file yourself, I think this file is part of your project, and it should not be changeable in spacevim.

**Comment by wsdjeg** [comment]
I will look into jshint, if I find the cli tool support argv for enable esversion 6, I will add this feature.

**Comment by wsdjeg** [comment]
see: http://jshint.com/docs/cli/

**Comment by wsdjeg** [comment]
also you can read https://github.com/AtomLinter/linter-jshint/issues/237#issuecomment-199836393

**Comment by codesve** [comment]
@wsdjeg OK, Thank you.

**Comment by rahulsharma991** [comment]
In windows
open VS Code then press ctrl+shift+p together > command palellet will appear > open user settings>search jshint> click on jshint:options > "jshint.options": { "esversion": 6, }

**Comment by idontknoiw** [comment]
This doesn't help @rahulsharma991 . I am writing a userscript, not a bomb. Please explain this in neater terms WITHOUT Visual Studio, thank you.

**Comment by SJDUKE03** [comment]
@rahulsharma991 thanks for your knowledge and once again thank you
