### ISSUE TITLE
Error detected while processing

### ISSUE THREAD

**Issue by onerciller** [wsdjeg/SpaceVim#130]
### Environment Information
- OS: windows
- vim version:7.4 gvim

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

Error detected while processing function SpaceVim#default[3]..SpaceVim#d
efault#SetMappings:
line    3:
E488: Trailing characters: <<<<<<< HEAD
Error detected while processing C:\Users\oner\vimfiles\autoload\SpaceVim
\plugins.vim:
line    2:
E488: Trailing characters: <<<<<<< HEAD
line  244:
E488: Trailing characters: =======
line  245:
E488: Trailing characters: >>>>>>> c6132d41343da33e7113ab2be46ebe0b3
a2539af

**Comment by wsdjeg** [comment]
Can you update SpaceVim, I can not reproduce this issue .

**Comment by wsdjeg** [comment]
@onerciller I can not find any chat like `<<<<<<< HEAD`. clossing.
