### ISSUE TITLE
[Request] Add key binding to open buffer directory in Vimfiler

### ISSUE THREAD

**Issue by sei40kr** [wsdjeg/SpaceVim#1301]
I want key binding to open a directory where current buffer exists (`:VimFilerBufferDir`).
Because I usually open a buffer via Denite at first, and edit related files via Vimfiler.

**Comment by sei40kr** [comment]
Is there suitable mapping for it?

**Comment by wsdjeg** [comment]
@sei40kr You can push to this repo now, just same as me, but the master branch is protected, as it need all checks run successfully, and need review from other people or code owner, and the code owner now is definded in `.github/CODEOWNERS `. for more info see my new PR and https://help.github.com/articles/about-codeowners/

for open buffer dir,  there is  `SPC b t` for this feature, and it has been implemented.

**Comment by sei40kr** [comment]
@wsdjeg 
I didn't notice. Thanks! I'm closing this ticket.

**Comment by wsdjeg** [comment]
the best way to find this feature is use fly grep.

press `SPC s /`, and insert `VimFilerBufferDir`.
