### ISSUE TITLE
layer c.vim s:use_libclang = 0 control flow error

### ISSUE THREAD

**Issue by unlockingc** [wsdjeg/SpaceVim#1317]
in **.SpaceVim/autoload/SpaceVim/layers/lang/c.vim** line 70

```
if has('nvim')
    if has('python3')
      call add(plugins, ['arakashic/chromatica.nvim', { 'merged' : 0}])
    else
      call add(plugins, ['bbchung/Clamp', { 'if' : has('python')}])
    endif
  elseif has('job')
    call add(plugins, ['bbchung/clighter8', { 'if' : has('python')}])
  else
    call add(plugins, ['bbchung/clighter', { 'if' : has('python')}])
  endif
  call add(plugins, ['lyuts/vim-rtags', { 'if' : has('python')}])
```
The first `elseif` should test if `s:use_libclang is 0`
otherwise, you are forcing me to install clang to write c code.
As clang and libclang-py3 has many version problem, This is not a good solution~

**Comment by wsdjeg** [comment]
@unlockingc Would you like to send a PR, I can not understand it clearly.

**Comment by unlockingc** [comment]
Sorry, what do you mean by PR? 
I don't know the contact.
I'm a freshman so maybe I did not make it clear.
# What I mean is:
If you did not install clang and llvm using apt or yum,
you will get an error everytime you edit c/c++ file.
This is because the clighter8/clighter plugin rely on clang.
but as SpaceVim install script didn't install clang, So many people may get the the error as mine.

# solution
So to fix this I reviewed you c.vim, and found out that there does exist a variable named `s:use_libclang = 0`, but it is not used in the right way. So I came up with this issue.

**Comment by wsdjeg** [comment]
@unlockingc oh, I got it, I will fix it later. Thanks for your info.

**Comment by unlockingc** [comment]
Glad to help~
