### ISSUE TITLE
SpaceVim spews a bunch of errors on startup

### ISSUE THREAD

**Issue by ijt** [wsdjeg/SpaceVim#1319]
## Expected behavior, english is recommended
Vim should start without errors.

## Environment Information
- OS: Mac OS 
Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64

- vim version: 
issactrotts-macbookpro:github issactrotts$ vi --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv          

- neovim version:
None.

## The reproduce ways from Vim starting (Required!)
$ vi

## Output of the ':SPDebugInfo!'
tagbar_indent         #2
loaded_vimballPlugin   v35
spacevim_statusline_left_sections ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'version co
ntrol info', 'hunks']
ctrlp_working_path_mode  ra
spacevim_enable_statusline_display_mode #0
tagbar_silent         #0
vimproc#popen2_commands {'screen': 1, 'zsh': 1, 'csh': 1, 'su': 1, 'ipython3': 1, 'tcsh': 1, 'sh': 1, 'rhino': 1, 'bash': 1
, 'yaourt': 1, 'tmux': 1, 'python': 1, 'ipython': 1}
NERDRPlace             <]
better_whitespace_filetypes_blacklist ['diff', 'gitcommit', 'unite', 'qf', 'help', 'markdown', 'leaderGuide']
tagbar_singleclick    #0
vimfiler_tree_indentation #1
spacevim_enable_os_fileformat_icon #0
spacevim_leader_guide_position  botright
automkdir_silent      #0
spacevim_version       0.7.0-dev
gitgutter_eager       #1
spacevim_force_global_config #0
unite_source_menu_menus {'git': {'command_candidates': [['▷ tig                                                        ⌘ ,g
t', 'normal ,gt'], ['▷ git status       (Fugitive)                                ⌘ ,gs', 'Gstatus'], ['▷ git diff
(Fugitive)                                ⌘ ,gd', 'Gdiff'], ['▷ git commit       (Fugitive)
⌘ ,gc', 'Gcommit'], ['▷ git log          (Fugitive)                                ⌘ ,gl', 'exe "silent Glog | Unite quickf
ix"'], ['▷ git blame        (Fugitive)                                ⌘ ,gb', 'Gblame'], ['▷ git stage        (Fugitive)
                             ⌘ ,gw', 'Gwrite'], ['▷ git checkout     (Fugitive)                                ⌘ ,go', 'Gre
ad'], ['▷ git rm           (Fugitive)                                ⌘ ,gr', 'Gremove'], ['▷ git mv           (Fugitive)
                             ⌘ ,gm', 'exe "Gmove " input("destino: ")'], ['▷ git push         (Fugitive, salida por buffer)
             ⌘ ,gp', 'Git! push'], ['▷ git pull         (Fugitive, salida por buffer)             ⌘ ,gP', 'Git! pull'], ['▷
 git prompt       (Fugitive, salida por buffer)             ⌘ ,gi', 'exe "Git! " input("comando git: ")'], ['▷ git cd
     (Fugitive)', 'Gcd']], 'description': '            gestionar repositorios git                            ⌘ [espacio]g'}
, 'MpvPlayer': {'command_candidates': [], 'description': 'Musics list                   <leader>lm'}, 'AddedPlugins': {'com
mand_candidates': [['[lang]                   [digitaltoad/vim-jade]                    [lazy loaded]  [{''on_ft'': [''jade
'']}]', 'OpenBrowser https://github.com/digitaltoad/vim-jade'], ['[lang]                   [juvenn/mustache.vim]
          [lazy loaded]  [{''on_ft'': [''mustache'']}]', 'OpenBrowser https://github.com/juvenn/mustache.vim'], ['[lang]
                [kchmck/vim-coffee-script]                [lazy loaded]  [{''on_ft'': [''coffee'']}]', 'OpenBrowser https:/
/github.com/kchmck/vim-coffee-script'], ['[lang]                   [elixir-lang/vim-elixir]                  [lazy loaded]
 [{''on_ft'': ''elixir''}]', 'OpenBrowser https://github.com/elixir-lang/vim-elixir'], ['[lang]                   [Potatoes
Master/i3-vim-syntax]            [lazy loaded]  [{''on_ft'': ''i3''}]', 'OpenBrowser https://github.com/PotatoesMaster/i3-v
im-syntax'], ['[lang]                   [isundil/vim-irssi-syntax]                [lazy loaded]  [{''on_ft'': ''irssi''}]',
 'OpenBrowser https://github.com/isundil/vim-irssi-syntax'], ['[lang]                   [lervag/vimtex]
       [lazy loaded]  [{''on_ft'': ''tex''}]', 'OpenBrowser https://github.com/lervag/vimtex'], ['[lang]
[vimperator/vimperator.vim]               [lazy loaded]  [{''on_ft'': ''vimperator''}]', 'OpenBrowser https://github.com/vi
mperator/vimperator.vim'], ['[lang]                   [voxpupuli/vim-puppet]                    [lazy loaded]  [{''on_ft'':
 ''puppet''}]', 'OpenBrowser https://github.com/voxpupuli/vim-puppet'], ['[lang]                   [peterhoeg/vim-qml]
                  [lazy loaded]  [{''on_ft'': ''qml''}]', 'OpenBrowser https://github.com/peterhoeg/vim-qml'], ['[lang]
               [cespare/vim-toml]                        [lazy loaded]  [{''on_ft'': ''toml''}]', 'OpenBrowser https://gith
ub.com/cespare/vim-toml'], ['[edit]                   [tpope/vim-surround]', 'OpenBrowser https://github.com/tpope/vim-surr
ound'], ['[edit]                   [tpope/vim-repeat]', 'OpenBrowser https://github.com/tpope/vim-repeat'], ['[edit]

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
<img width="569" alt="screen shot 2018-01-23 at 6 45 09 pm" src="https://user-images.githubusercontent.com/15530/35311854-974a4572-006d-11e8-8ccc-a99f25016788.png">

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
Oh, `funcref()`.

`funcref()` is implemented in Vim 7.4.2137+.
SpaceVim should check if `funcref()` exists.

**Comment by Shougo** [comment]
> issactrotts-macbookpro:github issactrotts$ vi --version
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 4 2017 18:14:54)
> Included patches: 1-898, 8056

`funcref()` is not supported in the version.

**Comment by wsdjeg** [comment]
@Shougo Thanks I will fix this issue.
