### ISSUE TITLE
[LSP] Error/warning symbols are not colorized

### ISSUE THREAD

**Issue by sei40kr** [wsdjeg/SpaceVim#1320]
## Expected behavior, english is recommended

Error/warning symbols are colorized.

## Environment Information
- OS: macOS, elementary OS
- vim version:
- neovim version: v0.2.0

## The reproduce ways from Vim starting (Required!)

1. Launch Neovim **without arguments**.
1. Open a file.
1. Let error/warning by language server appear.

## Output of the ':SPDebugInfo!'

```vim
call SpaceVim#layers#load('lsp', {
      \ 'filetypes': ['css', 'haskell', 'html', 'javascript', 'json', 'less', 'php', 'python', 'rust', 'scss'],
      \ 'override_cmd': {
      \ 'css': ['css-languageserver', '--stdio'],
      \ 'html': ['html-languageserver', '--stdio'],
      \ 'javascript': ['flow-language-server', '--stdio'],
      \ 'json': ['json-languageserver', '--stdio'],
      \ 'less': ['css-languageserver', '--stdio'],
      \ 'scss': ['css-languageserver', '--stdio'],
      \ }
      \ })
```

## Screenshots

I'll upload later.

**Comment by sei40kr** [comment]
I confirmed it occurs only when using ALE.

**Comment by wsdjeg** [comment]
@sei40kr what is your custom configration, I want to reproduce this issue and try to fix it.

**Comment by sei40kr** [comment]
@wsdjeg 
I tried to reproduce this problem again, but I couldn't made it.
I'm closing this and reopen/recreate new issue on next time I see it. Thanks.
