### ISSUE TITLE
Automatically complete the first document

### ISSUE THREAD

**Issue by fengwei15** [wsdjeg/SpaceVim#1332]
## Is spacevim's auto-completion candidate source customizable? Each time I type a header, I get a lot of candidates for the unwanted directories. I specify only the header I need in the `.clang` configuration file, the other headers are not configured, but the header is pop-up I have not shown in front of the distribution of the list, I always want to be the bottom, as shown input iostream, strstream, algorithm. Or is there a way to get the row I want in front of it?

This English is directly translated with Google after the copy, I do not know if there are any translation errors

![qq 20180126103622](https://user-images.githubusercontent.com/29158660/35422770-4f7ee4c2-0285-11e8-8659-01c11ae155f7.png)
![qq 20180126111538](https://user-images.githubusercontent.com/29158660/35423733-4b20c10c-028a-11e8-8310-1ecedcb4df49.png)
![qq 20180126111504](https://user-images.githubusercontent.com/29158660/35423738-511f819c-028a-11e8-958b-544911d145c8.png)

``
## Environment Information

- OS:Linux
- vim version:
- neovim version:0.2.2

### SpaceVim Options :

```viml
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'version control info', 'hunks']
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.7.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_default_indent = 2
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_enable_language_specific_leader = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 0
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_smartclose = 'q'
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_ale = 0
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_key_frequency = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_project_rooter_automatically = 1
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'VersionControl', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#banner', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'linux', 'incsearch', 'lang#c', 'lang#haskell', 'lang#java', 'lang#javascript', 'lang#lua', 'lang#perl', 'lang#php', 'lang#python', 'lang#vim', 'lang#xml', 'shell', 'tools#screensaver', 'colorscheme']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/w-nvim/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_keep_server_alive = 1
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_filetype_icons = {}
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_custom_color_palette = []
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_language = ''
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:37:37] [ Info ] Skip glob configration of SpaceVim
[ SpaceVim ] [09:37:37] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [09:37:42] [ Info ] Find project root('.git/','/home/w-nvim/.SpaceVim/autoload/SpaceVim/layers/lang/c.vim'):/home/w-nvim/.SpaceVim/.git/
[ SpaceVim ] [09:37:42] [ Info ] change to root:/home/w-nvim/.SpaceVim
[ SpaceVim ] [09:37:42] [ Info ] change to root:/home/w-nvim/.SpaceVim
```
## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by wsdjeg** [comment]
> g:spacevim_autocomplete_method = 'deoplete'

@Shougo I think the match of neoinclude should be like this:

`iso` only much

```
i[^/]*s[^/]*o[^/]*
```

so when user input `iso` it will list all iso-like file or dirs.

**Comment by wsdjeg** [comment]
or maybe we could custom a match for neoinclude source in deoplete.

**Comment by Shougo** [comment]
@wsdjeg You have enabled fuzzy match in neoinclude(It seems matcher_full_fuzzy).
You should disable it.

```vim
call deoplete#custom#source('file/include', 'matchers', 'matcher_head')
```

**Comment by wsdjeg** [comment]
@Shougo really sorry. I will disable it.

**Comment by fengwei15** [comment]
I added the following statement` init.vim `file, start the error can not find that  function:

> call deoplete#custom#source('file/include', 'matchers', 'matcher_head')

Finally, I added it to the `~/.SpaceVim/config/plugins/deoplete.vimfile`, after retry to eliminate a lot of useless make up options,the effect is good.
thank you very much for your help

**Comment by wsdjeg** [comment]
@fengwei15 You should not edit files in `~/.SpaceVim`. if this dir is changed, when you update spacevim, it will failed. I will fix this issue, and of cause PR is welcome.
