### ISSUE TITLE
All plugs updating failed when execute SPUpdate 

### ISSUE THREAD

**Issue by bigbigda** [wsdjeg/SpaceVim#1334]
## Environment Information
- OS: Ubuntu16.04 and MacOS
- vim version:  Ubuntu: 7.4 Included patches: 1-1689  Extra pathces: 8.0
                        MacOS: 7.4 Included patches:1-898,8056

## The reproduce ways from Vim starting 
I install SpaceVim on my ubuntu and MacOS machine, the install steps goes well. However, when I input the SPUpdate command, all updating failed. 
I have tried many times to reinstall the Spacevim and Vim itself, but this situation always occur.

## Output of the :SPDebugInfo!
![selection_002](https://user-images.githubusercontent.com/11570400/35468969-fb19de4c-0364-11e8-92c2-8a0263a76b08.png)
![selection_003](https://user-images.githubusercontent.com/11570400/35468970-fcf48bae-0364-11e8-979c-14b3931f3120.png)

## Screenshots
![selection_001](https://user-images.githubusercontent.com/11570400/35468822-a5880614-0361-11e8-9aef-3709f36ff0b8.png)
<img width="1672" alt="2018-01-27 12 57 52" src="https://user-images.githubusercontent.com/11570400/35468864-ce669a72-0362-11e8-9285-8ff8bdf14ba0.png">

**Comment by wsdjeg** [comment]
Please reinstall spacevim, 

```
rm -rf ~/.SpaceVim
rm ~/.vim
```

**Comment by bigbigda** [comment]
I have reinstall spacevim for many times. Except ~/.SpaceVim and ~/.vim, I have also tried deleted ~/.cache/*. These doesn't work.

**Comment by wsdjeg** [comment]
do you try with vim8? and you should report issue with issue templete, you error message is not complete. you can post resut of `SPC h I` and `SPC b m`.

**Comment by bigbigda** [comment]
I input `SPC h I` and `SPC b m`, respectively generate a blank __Message_Buffer__ and **issue_report.md** file. I have post the figure.  I have not tried vim8. I will give a try.

**Comment by bigbigda** [comment]
The vim8 solved my problem. Thank you !!!

**Comment by wsdjeg** [comment]
@bigbigda But this issue should be fix in vim7.4, what is your vim --version ?

**Comment by wsdjeg** [comment]
and does it happend in both mac and ubuntu?

**Comment by bigbigda** [comment]
Yes, both ubuntu and mac. my vim version is 7.4.
Below is the vim --version of mac:

> 

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com

**Comment by wsdjeg** [comment]
please keep this issue open, I will test it.

**Comment by bigbigda** [comment]
With vim8, there is still some building failed. Is these matters? I guess it's because the vim is not compiled with php etc.
![selection_001](https://user-images.githubusercontent.com/11570400/35469718-79b17024-0376-11e8-96c7-75714073ce83.png)

**Comment by bigbigda** [comment]
Ok, the macos system and ubuntu system is really clean. (I don't install many things on them). The ubuntu is almost a raw 16.04.

**Comment by wsdjeg** [comment]
You can build this plugin yourself.

**Comment by bigbigda** [comment]
Where should I put the built file?

**Comment by bigbigda** [comment]
I am really new to the plugin system of vim, is there one example or tutorial?

**Comment by wsdjeg** [comment]
please read the document of spacevim.

**Comment by bigbigda** [comment]
OK. I have read the document and found something like this:

> 

>  If you want to add some custom plugins, use these options:
> let g:spacevim_custom_plugins = [
> \ ['plasticboy/vim-markdown', {'on_ft' : 'markdown'}],
> \ ['wsdjeg/GitHub.vim'],
> \ ]`

> 

I wondered where to put the custom_plugins in to make it can be loaded by SpaceVim.

**Comment by bigbigda** [comment]
I get it. I just need to write the repository name here and don't need to download anything. ORZ

**Comment by wsdjeg** [comment]
@bigbigda I just update spacevim, can you check it in the vim7.4?

**Comment by bigbigda** [comment]
still not work.

**Comment by wsdjeg** [comment]
@bigbigda can you post `SPC h I` info?

**Comment by bigbigda** [comment]
![screenshot from 2018-01-31 14-58-23](https://user-images.githubusercontent.com/11570400/35609168-3e00328a-0697-11e8-971e-240e2cb82145.png)

**Comment by wsdjeg** [comment]
can you post the info of  `vim --version`, I will test it later.

**Comment by bigbigda** [comment]
![screenshot from 2018-01-31 15-05-20](https://user-images.githubusercontent.com/11570400/35609417-2ea6f0e8-0698-11e8-8d15-f1cd48e3015e.png)

**Comment by bigbigda** [comment]
I have reproduced this bug in my another ubuntu machine. (now two ubuntu16.04 and one macos)

**Comment by bigbigda** [comment]
Another assosicative problem is that if I change my conda python enviroment, the vim will failed to run.
Perhaps this is a correct behavior.
![screenshot from 2018-01-31 15-09-58](https://user-images.githubusercontent.com/11570400/35609585-d33d28f2-0698-11e8-8d43-939df8bec32c.png)

**Comment by wsdjeg** [comment]
I got it, It is a vim bug.

**Comment by bigbigda** [comment]
could you explain it concretely ?

**Comment by wsdjeg** [comment]
you vim has `+python3` feature, then `echo has('python3')` will return 1, but I think you can not use `:py3 import io`

**Comment by bigbigda** [comment]
I input `:py3 import io`, nothing returned. But if I input `:py3 print ('2')`, it returned `2`

**Comment by wsdjeg** [comment]
as the picture shown above, your vim's py does not work. This is not issue with SpaceVim.

**Comment by bigbigda** [comment]
I am not sure wheter I confuse you with that picture. The original problem is under my normal vim enviroment and won't generate the `failed to import the site` error. That picture describe another problem that I can lanuch vim when I swith my python enviroment.

In fact, these are two problems and I should have post the second problem under a new issue.
FYI

**Comment by wsdjeg** [comment]
@bigbigda Sorry I can not reproduce in my vim.
