### ISSUE TITLE
Hi! How to open remote dir as project in spacevim? 

### ISSUE THREAD

**Issue by robgrzel** [wsdjeg/SpaceVim#1336]
Hi!

I wish to not install spacevim on every server I use. 
Also I dont want to scp each time I change file.
How to open remote directory as project (NERDTree directory) in neovim?

**Comment by wsdjeg** [comment]
:h vimfilter will tell you how to open ssh file. but I think we should add key binding for it.

**Comment by robgrzel** [comment]
what ssh file?
u mean some plugin?

**Comment by wsdjeg** [comment]
here is some info about open remote dir:

https://stackoverflow.com/questions/2136127/how-to-use-gvim-to-edit-a-remote-file
