### ISSUE TITLE
Better Experience to Quit Vim with Unsaved Files

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1357]
Is there a way to ask for users' action when quitting Spacevim?

When closing a file with unsaved content, we often see something like this:
<img width="657" alt="screen shot 2018-01-31 at 4 17 37 pm" src="https://user-images.githubusercontent.com/2555093/35612381-97254998-06a3-11e8-818d-23d26e6893e7.png">

As we are trying to deliver IDE like experience to users, this kind of error should be caught properly. I got two idea in my brain,   The first one is to catch the error and show friendly message in message area. 

The second idea is to show a prompt option. Something like when you open a file in a split window, you use **A** or **B** to choose which side to open the file. 
<img width="1440" alt="screen shot 2018-01-31 at 4 31 46 pm" src="https://user-images.githubusercontent.com/2555093/35612604-4896c0ee-06a4-11e8-8077-0c664ac89472.png">

Is there a way to show three buttons like this when close an unsaved file to let the user choose discard or cancel or save.

**Comment by wsdjeg** [comment]
![fix_quit](https://user-images.githubusercontent.com/13142418/35634374-2fcb65fc-0671-11e8-8e30-89933d36451e.gif)
