### ISSUE TITLE
Let the plug manager get faster.

### ISSUE THREAD

**Issue by imahobbit** [wsdjeg/SpaceVim#136]
# **I find a plug for vim can let the plug manager get more fast.**
<img src="https://raw.githubusercontent.com/junegunn/i/master/vim-plug/installer.gif" height="450">
[here is the url](https://github.com/junegunn/vim-plug)

**Comment by wsdjeg** [comment]
I like dein though, vim-plug is not fast than dein, by default vim-plug use 16 thread to download plugin, but dein use only 8, I like github, so I do not want to use 16 thread.

BTW spacevim support vim-plug, but, it is not default plugin manager. please read the doc.

**Comment by imahobbit** [comment]
but when I install the SpaceVim ,dein nealy use one hour to unfinish the install.
Now I'm useing liuchengxu/space-vim because I can install it.

**Comment by wsdjeg** [comment]
SpaceVim now has 200+ plugins though. it has too many awesome feature than space-vim.

**Comment by Shougo** [comment]
You can change the dein's default thread though...

> but when I install the SpaceVim ,dein nealy use one hour to unfinish the install.

Wow.  Your network is too slow.

**Comment by wsdjeg** [comment]
I think he should use VPN.

**Comment by imahobbit** [comment]
> I think he should use VPN.

I didn't want to use VPN because I don't can't pay it monthly.  
I just a senior hight school students and I don't have stable source of income. 
So can you packup SpaceVim as a tarfile and recommend a Free VPN?

**Comment by wsdjeg** [comment]
@imahobbit Thanks for support this project, I will upload all the plugins to qq group. if you are a chinese, I think it will help you.

**Comment by imahobbit** [comment]
谢谢。但我不知道你们的Q群号。
