### ISSUE TITLE
Neomake errors / warnings are printed in the code when moving the cursor over the line in normal mode

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1362]
Neomake errors / warnings are printed in the code when moving the cursor over the line in normal mode. After you move to another line, they are cleared.

**Comment by wsdjeg** [comment]
This is a feature. if will display cursor error under current line. but It does not change the content. Don't worry about the file is changed.

**Comment by crisidev** [comment]
Is there a way to disable this? It is really annoying :)

**Comment by wsdjeg** [comment]
The checker layer need to be fixed, the layer option does not work now.

**Comment by sei40kr** [comment]
https://github.com/SpaceVim/SpaceVim/pull/1364
After merging this, you can set:

```vim
call SpaceVim#layers#load('checkers', { 'show_cursor_error': 0 })
```
