### ISSUE TITLE
Not an editor command: Noeformat. 

### ISSUE THREAD

**Issue by macowie** [wsdjeg/SpaceVim#1367]
## Expected behavior, english is recommended

Running the Ruby layer's Rubocop formatter runs `Neoformat` and not `Noeformat`
https://github.com/SpaceVim/SpaceVim/blob/fd3a0ce1087303c1101037ee5033c421a05036b0/autoload/SpaceVim/layers/lang/ruby.vim#L38

## Environment Information
- OS: Fedora 27
- vim version:
- neovim version: 0.2.2

## The reproduce ways from Vim starting (Required!)

Load a ruby file, do `SPC l c f`

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

**Comment by wsdjeg** [comment]
@macowie sorry, this is a type in spacevim, will fix it soon.
