### ISSUE TITLE
Bad runtimepath when in $HOME

### ISSUE THREAD

**Issue by silvioricardoc** [wsdjeg/SpaceVim#1370]
## Expected behavior
When I open neovim, SpaceVim should add `$HOME/.SpaceVim.d` in the runtimepath.
This does happen most of the time, but if the current directory is `$HOME`, then only the relative path `.SpaceVim.d` is prepended to the runtimepath. This relative path breaks whenever any code `cd`s into another directory. The ideal solution would be to always prepend an absolute path to runtimepath.

## Environment information
- OS: Ubuntu 17.04
- neovim version: NVIM v0.2.1-dev

## Reproducing this behavior
```
$ cd $HOME
$ nvim
: echo &rtp
```

## Output of the ':SPDebugInfo!'

(This is a clean install).

**Comment by wsdjeg** [comment]
It is feature， SpaceVim support project specific config，that means, if you create a `.SpaceVim.d/init.vim` in the root of your project, it will only load the project's config. but there is an option for forcus global config. you can read :h spacevim-config

**Comment by wsdjeg** [comment]
got it， I will fix it，Thanks.
