### ISSUE TITLE
Install on win10, got below error

### ISSUE THREAD

**Issue by ccorzlol** [wsdjeg/SpaceVim#1374]
## Environment Information
- OS: win10 1709
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
after follow instructions in https://github.com/Gabirel/Hack-SpaceVim/blob/master/zh_CN/installation/installation-for-windows.md#%E5%AE%89%E8%A3%85neovim

and double click gvim on desktop got below error

```
Error detected while processing function SpaceVim#loadCustomConfig:

line   28:

E117: Unknown function: SpaceVim#logger#info

Error detected while processing C:\Users\ccorz\vimfiles\config\main.vim:

line   57:

E117: Unknown function: SpaceVim#server#connect

Error detected while processing function SpaceVim#end:

line   13:

E117: Unknown function: SpaceVim#server#export_server

Error detected while processing C:\Users\ccorz\vimfiles\config\main.vim:

line   61:

E117: Unknown function: SpaceVim#plugins#projectmanager#Rootchandg
eCallback

line   67:

E117: Unknown function: SpaceVim#autocmds#init
```

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

Got error, Unknown function: SpaceVim#logger#viewLog

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![wechat image_20180204005746](https://user-images.githubusercontent.com/13084227/35769475-735b5566-0946-11e8-98ac-6d36a5a1d13c.png)

**Comment by wsdjeg** [comment]
please use the installl script for windows in home page, and your spacevim is broken

**Comment by ccorzlol** [comment]
Much appreciated for looking into the issue!

remove spacevim and uninstall vim, and redo from scratch, but the issue remains the same,

using install script for windows, it seems successful ..
```
==> Starting Testing Procedure...

==> Testing git
git version 2.14.2.windows.1
[OK] Test successfully. Moving to next...

==> Testing vim
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 19:48:19)
[OK] Test successfully. Moving to next...
<== Testing Procedure Completed. Moving to next...


==> Trying to clone SpaceVim
Cloning into 'C:\Users\test\.SpaceVim'...
remote: Counting objects: 16047, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 16047 (delta 0), reused 1 (delta 0), pack-reused 16043
Receiving objects: 100% (16047/16047), 5.48 MiB | 3.29 MiB/s, done.
Resolving deltas: 100% (11557/11557), done.

symbolic link created for C:\Users\test\vimfiles <<===>> C:\Users\test\.SpaceVim

Almost done!
==============================================================================
==        Open GVim and it will install the plugins automatically           ==
==============================================================================

That's it. Thanks for installing SpaceVim. Enjoy!

Press any key to continue . . .
```

then open gvim and run as administrator,
```
C:\windows\system32\cmd.exe /c git clone https://github.com/Shougo/dein.vim "C:\Users\test\.cache\vimfiles\repos\github.com\Shougo\dein.vim"
Cloning into 'C:\Users\test\.cache\vimfiles\repos\github.com\Shougo\dein.vim'...
remote: Counting objects: 4775, done.
remote: Total 4775 (delta 0), reused 0 (delta 0), pack-reused 4775
Receiving objects: 100% (4775/4775), 910.62 KiB | 609.00 KiB/s, done.
Resolving deltas: 100% (2723/2723), done.
Hit any key to close this window...
```

Then I got a message,
```
:!git clone https://github.com/Shougo/dein.vim "C:\Users\test\.cache\vimfiles\repos\github.com\Shougo\dein.
vim"
```

at this point, I didn't a failure in the entire installation process, however, when launch gvim, same error pops up....

**Comment by wsdjeg** [comment]
```
:!git clone https://github.com/Shougo/dein.vim "C:\Users\test\.cache\vimfiles\repos\github.com\Shougo\dein.
vim"
```

This is just a message for auto installl dein, and it should only shown one times, do you try to restart gvim?

**Comment by ccorzlol** [comment]
yup, have tried to restart gvim for multiple times but the same error would show up each time when double click on the gvim.exe, Error detected while processing function SpaceVim#loadCustomConfig: blablabla.

just tried with win7 and using install script, same error....

**Comment by wsdjeg** [comment]
so what is the content in your custom config `~/.SpceVim.d/init.vim`?

**Comment by ccorzlol** [comment]
Below is the output,

```
" Dark powered mode of SpaceVim, generated by SpaceVim automatically.
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#elixir')
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#haskell')
call SpaceVim#layers#load('lang#java')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#perl')
call SpaceVim#layers#load('lang#php')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#rust')
call SpaceVim#layers#load('lang#swig')
call SpaceVim#layers#load('lang#tmux')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('shell')   
call SpaceVim#layers#load('tools#screensaver')
let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
let g:deoplete#auto_complete_delay = 150
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:neomake_vim_enabled_makers = []
if executable('vimlint')
    call add(g:neomake_vim_enabled_makers, 'vimlint') 
endif
if executable('vint')
    call add(g:neomake_vim_enabled_makers, 'vint') 
endif
if has('python3')
    let g:ctrlp_map = ''
    nnoremap <silent> <C-p> :Denite file_rec<CR>
endif
let g:clang2_placeholder_next = ''
let g:clang2_placeholder_prev = ''
```

**Comment by wsdjeg** [comment]
sorry, I can not reproduce it.

**Comment by wsdjeg** [comment]
you should delete `~/.SpaceVim` `~/vimfiles` and try to reinstall spacevim. BTW, what is `$HOEM` evn value? do you change it?

**Comment by ccorzlol** [comment]
$HOME env as below

```
C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Windows\system3
2;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0
\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Users\Administrator\.dnx\b
in;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\13
0\Tools\Binn\;C:\Program Files (x86)\Lua53;C:\Program Files (x86)\Git\bin;C:\Pro
gram Files\Python36;C:\Program Files (x86)\Vim\vim80;C:\Users\Administrator\AppD
ata\Roaming\npm
```

tried to delete `~/.SpaceVim` and `~/vimfiles`, same thing...do you want me to record a video for the entire installation process?

**Comment by wsdjeg** [comment]
you should know what is HOME, vim load user config from `HOME/vimfiles`, that means, if you change this value, vim will not add `C:\Users\test\vimfiles` into your rtp, and then you will get unkown func.

**Comment by wsdjeg** [comment]
you install spacevim for user `C:\Users\test`, but you are using gvim in `C:\Users\ccorz`.

**Comment by wsdjeg** [comment]
you should reinstall spacevim in `C:\Users\ccorz`, and delete `C:\Users\ccorz\vimfiles` and `C:\Users\ccorz\.SpaceVim`

**Comment by ccorzlol** [comment]
sorry for the confusion, as test is my home PC and ccorz is my corporate PC hence you see the path different. 

By further testing, it turns out the error would occur if I kick off the gvim under home path.

> C:\Users\test>gvim  // error pops up

The error would go away as long as I switch to `c:\Windows\System32` and kick off gvim

> c:\Windows\System32>gvim  // no issues

Then everything working as expected. Same issue can be reproduced at win7.

If I double click gvim on desktop, error would pops up, and if I manually change the `Start in` location to c:\Windows\System32 under Properties setting, then it works fine.

 ![wechat image_20180204005746](https://user-images.githubusercontent.com/13084227/35778062-add27b2c-09f3-11e8-93fe-e71eee7ec268.png)

could you please try to kick off the gvim under a different path other than  `c:\Windows\System32` to see if you got a reproduce the issue or not?

**Comment by wsdjeg** [comment]
I do not use windows, but I think you can have a try with remove the `HOME` EVN, and you can check `:version` in gvim, it  will show you where the gvim will load the vimrc.'

**Comment by ccorzlol** [comment]
either remove `HOME` env or change to a different location other than user home directory can workaround the issue and everything works like a charm.

Thank you for your timely reply :)

**Comment by wsdjeg** [comment]
welcome
