### ISSUE TITLE
Key remap issues in SpaceVim

### ISSUE THREAD

**Issue by BowenWang** [wsdjeg/SpaceVim#1378]
I just downloaded the SpaceVim and have already started to use it.

Because I use Programmer Dvorak Keyboard Layout, so when I use Vim, I remap some keys. Here is my remap settings used to be in .vimrc file:

nnoremap [ 7
nnoremap { 5
nnoremap } 3
nnoremap ( 1
nnoremap = 9
nnoremap * 0
nnoremap ) 2
nnoremap + 4
nnoremap ] 6
nnoremap ! 8
nnoremap 7 [
nnoremap 5 {
nnoremap 3 }
nnoremap 1 (
nnoremap 9 =
nnoremap 0 *
nnoremap 2 )
nnoremap 4 +
nnoremap 6 ]
nnoremap 8 !

nnoremap t j
nnoremap n k
nnoremap s l

nnoremap j t
nnoremap k n
nnoremap l s

nnoremap ; :
nnoremap : ;

vnoremap [ 7
vnoremap { 5
vnoremap } 3
vnoremap ( 1
vnoremap = 9
vnoremap * 0
vnoremap ) 2
vnoremap + 4
vnoremap ] 6
vnoremap ! 8
vnoremap 7 [
vnoremap 5 {
vnoremap 3 }
vnoremap 1 (
vnoremap 9 =
vnoremap 0 *
vnoremap 2 )
vnoremap 4 +
vnoremap 6 ]
vnoremap 8 !

vnoremap t j
vnoremap n k
vnoremap s l

vnoremap j t
vnoremap k n
vnoremap l s

vnoremap ; :
vnoremap : ;

onoremap [ 7
onoremap { 5
onoremap } 3
onoremap ( 1
onoremap = 9
onoremap * 0
onoremap ) 2
onoremap + 4
onoremap ] 6
onoremap ! 8
onoremap 7 [
onoremap 5 {
onoremap 3 }
onoremap 1 (
onoremap 9 =
onoremap 0 *
onoremap 2 )
onoremap 4 +
onoremap 6 ]
onoremap 8 !

onoremap t j
onoremap n k
onoremap s l

onoremap j t
onoremap k n
onoremap l s

onoremap ; :
onoremap : ;

After I put this configuration in ~/.SpaceVim.d/init.vim, it seems many remappings don't work. Any ideas?

**Comment by wsdjeg** [comment]
ohhhh, my god! I will look into it.

**Comment by wsdjeg** [comment]
I think you can wrappe this key bindings into a func, and use an autocmd call it, for example

```vim
func! s:init_Dvorak()
  " put your mapping here.
endf

autocmd VimEnter * call s:init_Dvorak()
