### ISSUE TITLE
C code typing issue

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1380]
## Expected behavior, english is recommended
In the ‘hello world’  C code， when I type the ***h*** in *printf("h")*， the cursor goes to the place after the dot in ***stdio.h***, the code is shown below.

     #include <stdio.h>                                                          
     int main(void)                                                              
     {                                                                           
       printf("h") ;                                                              
     }  

## Environment Information
- OS:Ubuntu 1604
- neovim version: 0.2.2

## The reproduce ways from Vim starting (Required!)
nvim hello.c

**Comment by ghost** [comment]
When move cursor manually, got the same result

**Comment by wsdjeg** [comment]
no issue template

**Comment by Shougo** [comment]
> In the ‘hello world’ C code， when I type the h in printf("h")， the cursor goes to the place after the dot in stdio.h, the code is shown below.

Your installed plugins seems broken.
The minimal vimrc is needed.

**Comment by wsdjeg** [comment]
@Shougo I think he is using asyncomplete, seems same issue as #1330 , I want to remove asyncomplete support.

**Comment by Shougo** [comment]
Oh, OK.
