### ISSUE TITLE
Local configuration in `.SpaceVim.d` allows arbitrary code execution

### ISSUE THREAD

**Issue by silvioricardoc** [wsdjeg/SpaceVim#1385]
## Context
When SpaceVim opens a file which contains a local nearby `.SpaceVim.d` directory, it will load the `init.vim` file from this directory. This can be super useful for local project configurations.

## The problem
The problem happens when a user downloads some textual files (for example, from a git repository) containing a `.SpaceVim.d` directory. This directory will be hidden, but `.SpaceVim.d/init.vim` will be executed without a warning. This means that anyone can silently run arbitrary code on the side of SpaceVim users by hiding a `.SpaceVim` directory in their repository.

## Possible solution
The first time a given file is opened, SpaceVim should probably ask its users if they want trust the local `.SpaceVim.d` and want to load it. There could be three options, for example `(y)es, (n)ever, (a)lways`. If the user selects `yes` or `always`, then the file `.SpaceVim.d/init.vim` can be executed, otherwise it should not be executed.

**Comment by wsdjeg** [comment]
@silvioricardoc Nice issue.

but vim do not save the valus when we restart. to implement this feature, maybe we can use a cache file. just the path of the local `.SpaceVim.d/init.vim` as the key. that means, for a new cloned project, SpaceVim wll ask users if they want to trust the local config.

another idea: should we disable this feature by default?

**Comment by silvioricardoc** [comment]
What if the following plugin was automatically included in SpaceVim?
https://github.com/LucHermitte/local_vimrc
It seems to implement this exact feature, but it allows some configuration of how each directory will be handled, and by default it will *ask* whether the user wants to load the file.

**Comment by wsdjeg** [comment]
@silvioricardoc sorry, I can not implement this feature, spacevim need to read config before the vim screen is openned, so can not ask whether the user wants to load the file.
