### ISSUE TITLE
Improve the quick start guide

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1390]
any discussion about this guide is welcome.

**Comment by Gabirel** [comment]
## The basic rules
Quick-start guide must include **no more than 20% of the main document**.

## Content
- Layer feature
- The basic instructions for managing `SpaceVim` or its plugins.
- The most frequent used shortcut keys, like commenting and advanced moving or whatever something else
- IDE-like feature, including 3 main lang., like **C++/Java/Python**
