### ISSUE TITLE
Expand spacevim_custom_color_palette help

### ISSUE THREAD

**Issue by bearcatsandor** [wsdjeg/SpaceVim#1395]
Can you expand on the spacevim_custom_color_palette setting? The help only gives an example. Can i assume that the hex values select specific colors and the numerals select colors from your theme? So selecting #66000 makes something red, but 122 selects color #122 from your loaded them? More importantly, what's the mapping for the command.  When i  change a value, how do i know what i'm changing in the ui?  What areas of the UI do these colors affect?

After answering here, would you expand the help item for it?

Thank you

**Comment by wsdjeg** [comment]
ok, thanks for your report. I will update the doc after `highlight symbol` and `iedit mode` features are implemented.

ref: #1394

**Comment by bearcatsandor** [comment]
Very much looking forward to it.
