### ISSUE TITLE
[SPC]is should be changed to Unite ultisnips while using ultisnips engine

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#1398]
## ultisnips snippets should be listed while using ultisnips engine

In autoload/SpaceVim/layers/autocomplete.vim, line 155, [SPC]is is unconditionaly binded to Unite neosnippets.  It should be determined by let g:spacevim_snippet_engine.

## Environment Information
- OS: Linux
- vim version: 8.0.1436
- neovim version: N/A

## The reproduce ways from Vim starting (Required!)
Edit a python source file, enter [SPC]is

## Output of the ':SPDebugInfo!'

`let g:spacevim_snippet_engine = 'ultisnips'

## Screenshots

N/A

**Comment by wsdjeg** [comment]
yeah, this should be changed.
