### ISSUE TITLE
How to add the third party source completion?

### ISSUE THREAD

**Issue by BlasphemyAngels** [wsdjeg/SpaceVim#1400]
I want to add the third party source completion, for example  the opencv in c++. I use the "ctags" to generate the tags file and set the tags file path in vim. But it doesn't work. I want to know how to add the thid party source completion?

## Environment Information
- OS: OS X
- vim version: 8.0

**Comment by wsdjeg** [comment]
no issue template!

and I do not know how do you `set the tags file path in vim`.
