### ISSUE TITLE
What's the different between [SPC]m and [SPC]l ?

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#1402]
In SpaceVim, jump_to_alternate is binded to `SPC l j a`, but in Spacemacs, it's binded to `SPC m j a` in C/C++ layer.  So, what's the different between [SPC]m and [SPC]l ?  Should we use `SPC l j a` or `SPC m j a` ?

**Comment by wsdjeg** [comment]
SPC l is language specific key bindings, it is auto changed when edit different filetype.

it is different from major SPC m. SPC m is for layer key bindings.

why?

in spacemacs, key bindings with prefix `SPC m ` will be override when you load two layer which have same key bindings.

but the language specific key bindings will not be override, even if you load JAVA and python layer at same time.

so, if you want to add key bindings for a language, Please use SPC l. and if you want to add key bindings for layer or for tools, please use SPC m.

you can check out the language specific key binding example in JAVA or python layer.

**Comment by wsdjeg** [comment]
for example, in python layer, you can use `SPC l r` run python script. and in Ruby layer, you can use `SPC l r` run Ruby script too.

**Comment by thawk** [comment]
So, I should use `SPC l j a` to jump to alternated file (.h/.cpp) for CPP ?

**Comment by wsdjeg** [comment]
yeah， I also use this key binding Jump to JAVA test file in maven project.
