### ISSUE TITLE
Provide uniform hotkey for jump-to-definition and jump-to-reference

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#1403]
In +tags layer, there're already two key binding for these proposes : `SPC m g d` and `SPC m g r`.  But those key binding not work for languages like python.  I suggest providing uniform hotkey for all suitable languages.

BTW, in Spacemacs, `,` is mapped to `SPC m`, while in SpaceVim, `,` is mapped to `SPC l`.  Is it intended?

**Comment by wsdjeg** [comment]
`,` is language specific key binding short leader. maybe we can add an major leader.

**Comment by wsdjeg** [comment]
sorry, I can not add this feature, because Override origin key bindings is not a good idea,  If you readlly need this feature, you can add this to your config:

```
nmap ; [SPC]m
```

or maybe we can use `,` for `[SPC]m`?

**Comment by wsdjeg** [comment]
sorry, we can not change language leader, use `,` for `SPC l` is better thanks `SPC m`
