### ISSUE TITLE
the cursor jump to a random position when i enter char i or m

### ISSUE THREAD

**Issue by begend** [wsdjeg/SpaceVim#1405]
## Environment Information
- OS: 10.12.6 
- vim version:  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
- neovim version: NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/build/config -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/build/include

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
no info about `Output of the ':SPDebugInfo!'`

**Comment by djvolz** [comment]
I'm also seeing this issue. It doesn't happen in iTerm 2 on macOS, but it does happen on Red Hat Linux default terminal and on Linux Mint default terminal.  It makes spacevim unusable.

Edit (2/23/18):
Upon looking into this further. The commonality between my Linux vim's is that they were both compiled from source without python/python3 (can be checked by running vim --version).  They are both vim 8.  Mac version of vim does have +python so I assume this means it is not using asyncomplete by default.

As a test I explicitly changed my .SpaceVim.d/init.vim on my mac to use asyncomplete and now I see the same issue as #1330.

**Comment by wsdjeg** [comment]
open issue with issue template please

**Comment by djvolz** [comment]
No need for a new issue open. It's definitely the same as this documented issue: https://github.com/SpaceVim/SpaceVim/issues/1330

I've disabled asyncomplete, but as far as I can tell if asyncomplete is facing this issue, and SpaceVim is installing asyncomplete, then unfortunately it is also an issue with SpaceVim.

Anyways, great work with SpaceVim.  Love what has been done. Not expecting anyone to rush out and fix this issue. Just wanted to post so if anyone stumbled upon this issue from Google, they could get linked to a way of working around the issue.

**Comment by wsdjeg** [comment]
yeah，it is an issue with that plugin. But I can not fix it though. I also have ping the author, but no replys.

**Comment by wsdjeg** [comment]
Fixed!
