### ISSUE TITLE
use local eslint 

### ISSUE THREAD

**Issue by caoer** [wsdjeg/SpaceVim#1408]
Happy Chinese New Year~~~

There are some behaviors I think can be improved. If I choose to use local eslint. and there are multiple local eslint versions, it always uses the top level one. 

for example:
this is how the directory looks like:
```
/users/spacevim/project/
/users/spacevim/project/.git
/users/spacevim/project/node_modules/
/users/spacevim/project/node_modules/.bin/eslint
/users/spacevim/project/packages/
/users/spacevim/project/packages/client-project/
/users/spacevim/project/packages/client-project/node_modules/
/users/spacevim/project/packages/client-project/node_modules/.bin/eslint
/users/spacevim/project/packages/client-project/index.js
```

while I'm editing `/users/spacevim/project/packages/client-project/index.js`, it always uses `/users/spacevim/project/node_modules/.bin/eslint`. but I'd like to use `/users/spacevim/project/packages/client-project/node_modules/.bin/eslint` since it looks like most closed to my interests. 

there is a thread talked about it: https://github.com/neomake/neomake/issues/247

I believe here is the function of this behavior I'm talking about
```
function! s:preferLocalEslint() 
  let dir = expand('%:p:h')
  while  finddir('node_modules' ,dir ) is ''
    let next_dir = fnamemodify(dir, ':h')
    if dir == next_dir
      break
    endif
    let dir = next_dir
  endwhile
  let node_modules_path = dir . '/node_modules'
  let eslint_bin = node_modules_path . '/.bin/eslint'
  if (executable(eslint_bin)) 
    let b:neomake_javascript_eslint_exe = eslint_bin
  endif
endfunction
```

BTW, current directory always changed to top .git directory, whenever I saved the file after changed it. do you know where I can customize it? 

At last, there is a plugin which can make eslint feels faster, https://github.com/mantoni/eslint_d.js 
not sure if you think it is worth to add into spacevim

**Comment by wsdjeg** [comment]
Thanks, I will look.into this issue tomorrow.

**Comment by sei40kr** [comment]
`g:spacevim_project_rooter_automatically`
Does this have something to do with this?

Please try
`let g:spacevim_project_rooter_automatically = 0`

**Comment by sei40kr** [comment]
Maybe
`let g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'node_modules/']`
should also work.

**Comment by wsdjeg** [comment]
@sei40kr Should we add `'node_modules/'` to `g:spacevim_project_rooter_pattern` in javascript layer and typescript layer?

**Comment by sei40kr** [comment]
@wsdjeg 
Yes.
The other solution is removing preferLocalEslint.
Because eslint/eslint-cli (not eslint/eslint) finds nearest local eslint by default.

**Comment by wsdjeg** [comment]
I will look into it tonight, If eslint-cli can use nearest eslint automatically, I think no need to searching for local eslint.

**Comment by caoer** [comment]
thanks @sei40kr 
`let g:spacevim_project_rooter_automatically = 0` is what I'm looking for. 

Adding `node_modules` to search pattern is very useful for javascript mono projects, which can be managed by [lerna](https://github.com/lerna/lerna) or use `yarn`'s workspace settings.
