### ISSUE TITLE
Some Problems of syntax checking, deoplete, tabline

### ISSUE THREAD

**Issue by QingQiz** [wsdjeg/SpaceVim#1409]
## Environment Information
- OS: Ubuntu 17.10
- vim version: VIM - Vi IMproved 8.0
- neovim version: 
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-0hqwXz/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-0hqwXz/neovim-0.2.2/build/config -I/build/neovim-0hqwXz/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-0hqwXz/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-0hqwXz/neovim-0.2.2/build/include

## The reproduce ways from Vim starting (Required!)
See below screenshot:
When I try to save a C file, spacevim show me...
![screenshot from 2018-02-17 23-54-43](https://user-images.githubusercontent.com/33107216/36342803-b75102ea-143e-11e8-8e1a-1c67a5474167.png)

![screenshot from 2018-02-17 22-42-26](https://user-images.githubusercontent.com/33107216/36342654-79fd47ca-143c-11e8-9270-72fa1a842bf9.png)

'spacevim' often throws me this...
![screenshot from 2018-02-18 00-04-13](https://user-images.githubusercontent.com/33107216/36342871-9501efd2-143f-11e8-8df5-96ee820f66e7.png)

And, when I execute 'q', it often throws me this...
![screenshot from 2018-02-17 22-45-47](https://user-images.githubusercontent.com/33107216/36342822-e80fd3a2-143e-11e8-81c9-172a2400b683.png)

BTW, 'tabline has disappeared...
![screenshot from 2018-02-17 22-47-46](https://user-images.githubusercontent.com/33107216/36342888-ceb1a588-143f-11e8-9bd1-faa046903f3e.png)

The above problems appear after the update.

### SpaceVim Options :

```viml
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'version control info', 'hunks']
g:spacevim_enable_statusline_display_mode = 1
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.7.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_default_indent = 4
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_enable_language_specific_leader = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_smartclose = 'q'
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_custom_color_palette = []
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 0
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_vimfiler_gitstatus = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_key_frequency = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_lint_on_save = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_project_rooter_automatically = 1
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'VersionControl', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#banner', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'vim', 'linux', 'incsearch', 'lang#c', 'lang#elixir', 'lang#haskell', 'lang#java', 'lang#javascript', 'lang#lua', 'lang#perl', 'lang#php', 'lang#python', 'lang#rust', 'lang#swig', 'lang#tmux', 'lang#vim', 'lang#xml', 'shell', 'tools#screensaver', 'colorscheme']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 1
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/angel/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 1
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 1
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_keep_server_alive = 1
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_realtime_leader_guide = 1
g:spacevim_src_root = 'E:\sources\'
g:spacevim_automatic_update = 1
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_filetype_icons = {}
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_leader_guide_vertical = 0
g:spacevim_language = ''
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:26:10] [ Info ] Skip glob configration of SpaceVim
```

**Comment by Shougo** [comment]
@QingQiz 
deoplete child processes are crashed.
Please update deoplete to the latest version.
It prints more useful information.

Please test dp_main.py.
https://github.com/Shougo/deoplete.nvim/issues/635#issuecomment-363331278

Please test neovim-python module.
https://github.com/neovim/python-client#usage-through-the-python-repl

Note: You can disable parallel feature by `g:deoplete#num_processes`.  It is
workaround.

**Comment by QingQiz** [comment]
thanks, the problems by using ycm or disabling clang2, but the tabline still can not work...

**Comment by QingQiz** [comment]
thanks, the problems can be solved by using ycm or disabling clang2, but the tabline still can not work...

**Comment by wsdjeg** [comment]
@QingQiz please use split issue for tabline, and you need post your custom config and whole sreenshort. in SpaceVim we us clang2 as default c source, so you need to install llvm/libclang.
