### ISSUE TITLE
fcitx.vim is still being installed 

### ISSUE THREAD

**Issue by timothyjlaurent** [wsdjeg/SpaceVim#141]
### Expected behavior, english is recommend
I updated to the newest SpaceVim with 
```
curl -sLf https://raw.githubusercontent.com/SpaceVim/SpaceVim/dev/install.sh | bash
```
and noticed that I was still getting the socke error for fcitx.vim 

I found the `lilydjwg/fcitx.vim` in my `~/.cache` directory and removed it. When starting neovim again the `lilydjwg/fcitx.vim` gets put back

### Environment Information
- OS: MacOs sierra
- vim version: 7.4
- neovim version: 0.1.7

### The reproduce ways from Vim starting (Required!)

Install SpaceVim without fcitx executable. It will get put in the cache directory

**Comment by wsdjeg** [comment]
what is the result of `echo executable('fcitx')`

**Comment by timothyjlaurent** [comment]
`echo executable('fcitx')`
0

**Comment by timothyjlaurent** [comment]
@wsdjeg you need to just start working on a macbook 😆

**Comment by wsdjeg** [comment]
can you check https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/layers/edit.vim#L12-L14

if it is 0, this plugin will not be added, can you run `call dein#update()`.

**Comment by timothyjlaurent** [comment]
Yes I saw the fix -- That is why I updated to the newest version with 
`curl -sLf https://raw.githubusercontent.com/SpaceVim/SpaceVim/dev/install.sh | bash`

So this is what I did just now
1. open nvim
2. delete lilydjwg folder
3. run :call dein#update()

about half way through the update I checked and see that lilydjwg is back again.

I notice that although my repo is up to date, I'm on master and not on the dev branch where the layers/edit.vim is located. So I checkout the dev branch thinking that this must have been the problem all along. 
I verify that the layers/edit.vim is there with the executable('fxitx') block.... I delete the lilydjwg folder again and restart nvim .... and dein#update() reinstalls fctix...

**Comment by wsdjeg** [comment]
@timothyjlaurent thanks, you mean the script change the branch to master?

**Comment by timothyjlaurent** [comment]
It was master when I checked anf i switched it to dev. The fcitx.vim still got reinstalled

**Comment by wsdjeg** [comment]
you should not use master branch, dev is default branch, and in dev branch, if you has no fcitx ,fcitx.vim will not be installed.

**Comment by timothyjlaurent** [comment]
I understand that is your assertion, yet I have no fcitx and it gets installed on the dev branch.

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/blob/fc38d9cb302f21ae3f3f4275fe91186df59da540/autoload/SpaceVim/layers/edit.vim#L12-L14

change this line to
```viml
 if 0 
         let g:testfpp = 1
        call add(plugins,['lilydjwg/fcitx.vim',        { 'on_i' : 1}])
endif
```

then echo g:testfpp

**Comment by timothyjlaurent** [comment]
When I try to echo g:testfpp it complains about undefined variable as expected

![image](https://cloud.githubusercontent.com/assets/2000204/22217753/1a0fa040-e159-11e6-8e11-1536b4cc1c10.png)


If I switch to:
```
    1     if executable('fcitx')
+ 13      ¦   let g:testfpp = 1
    1     ¦   call add(plugins,['lilydjwg/fcitx.vim',        { 'on_i' : 1}])
    2     endif
```

and echo  g:testfpp I get the same error about no variable but the lilydjwg/fcitx.vim still gets reinstalled.

So if I search for 'lilydjwg':

```
ag lilydjwg
autoload/SpaceVim/layers/edit.vim
14:        call add(plugins,['lilydjwg/fcitx.vim',        { 'on_i' : 1}])

autoload/SpaceVim/plugins.vim
326:        call zvim#plug#add('lilydjwg/fcitx.vim',        { 'on_i' : 1})
```

So it must be getting installed in plugins.vim

**Comment by timothyjlaurent** [comment]
Ok I pulled the latest changes and now it won't get reinstalled. woohoo ... Thanks for your help with this, closing.

**Comment by soo-shan** [comment]
Hi,
Are these changes merged to master branch ? I'm still getting the error message and fcitx is there in .cache.
Where do I remove the package name from ?

**Comment by nouh** [comment]
same to me here
