### ISSUE TITLE
想问一下安装好了之后，该怎样启动SpaceVim啊？

### ISSUE THREAD

**Issue by darrenliuwei** [wsdjeg/SpaceVim#1410]
## Environment Information
- OS: Ubuntu 17.10
- vim version: 8.0.550
- neovim version:

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by darrenliuwei** [comment]
输入命令： `vim`
打开后是这样：
![screenshot from 2018-02-18 17-55-07](https://user-images.githubusercontent.com/10508248/36350557-104798aa-14d5-11e8-8fe3-2642dd1aff19.png)

**Comment by darrenliuwei** [comment]
输入命令：`init.vim` 也还是无法启动 SpaceVim
![screenshot from 2018-02-18 18-03-29](https://user-images.githubusercontent.com/10508248/36350607-495438f0-14d6-11e8-9259-da512cc63f39.png)

**Comment by wsdjeg** [comment]
use gitee.com/spacevim/SpaceVim for issue in Chinese.
