### ISSUE TITLE
something wrong with status bar in my computer

### ISSUE THREAD

**Issue by PraflyGod** [wsdjeg/SpaceVim#1411]
in my computer, something is wrong, but I don't know how to fix it. 
![image](https://user-images.githubusercontent.com/13954697/36360030-61ee4d6c-155b-11e8-89a4-1a8ccc4adaf6.png)

**Comment by wsdjeg** [comment]
you need to install nerd-font

**Comment by PraflyGod** [comment]
![image](https://user-images.githubusercontent.com/13954697/36404416-8182536a-1625-11e8-82d9-2bc79ced7aee.png)
still not work. I had installed nerd-font.

**Comment by sei40kr** [comment]
Installing Nerd Fonts is not enough. Nerd Fonts are patched fonts to include special signs the general fonts don't have.
So you have to set them as terminal font.

**Comment by PraflyGod** [comment]
but how to set them as terminal font. I had installed them all. I tried to get the answer for google and nerd font's github page. But failed to get any tips.
