### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by ShilnaChie** [wsdjeg/SpaceVim#1412]
# Chinese garbled
我非常喜欢spacevim,可无奈因为中文乱码切换到了盗版的space-vim,在网上找了很多方法,都没有用,希望能改进这个问题
Google Translate
I really like spacevim, but unfortunately because Chinese garbled switch to the pirated space-vim, find a lot of ways online, no use, hoping to improve the problem
#  Screenshot
https://i4.bvimg.com/632957/be67167698e63adf.png

**Comment by Shougo** [comment]
I think the screenshot is needed.

**Comment by wsdjeg** [comment]
please read the installation section in the documentation. why do not install nerd-fonts?

**Comment by wsdjeg** [comment]
and it is duplicate with #1411
