### ISSUE TITLE
clang error

### ISSUE THREAD

**Issue by ShilnaChie** [wsdjeg/SpaceVim#1418]
Hello，能帮我解决一下Spacevim中我遇到到问题吗，在最新版0.70中，安装后会有一个关于clang的error错误（本人英语渣看不懂）目前通过禁用c语言插件没有了这个error错误，求怎么从根源上解决这个问题 

Hello, can help me solve Spacevim I encountered problems in the latest version of 0.70, after installation there will be an error on the clang error (I can not read English slag) By disabling the c language plug-in this error Wrong, how to solve this problem from the root cause

**Comment by wsdjeg** [comment]
no issue template, no error message, no os info!

you should make sure you have clang/libclang installed. if `:py import clang` works well That will be ok.
