### ISSUE TITLE
papercolor with light theme

### ISSUE THREAD

**Issue by ming-codes** [wsdjeg/SpaceVim#143]
### Expected behavior, english is recommend
Expect white background, but got dark gray background.

https://github.com/SpaceVim/SpaceVim/blob/41de5e8d21c38d19b9c5ac7aaa04f77ddee43146/config/general.vim#L8

Looks like this line is forcing dark theme

### Environment Information
- OS: MacOS
- neovim version: 0.1.7

### The reproduce ways from Vim starting (Required!)
Just start vim

**Comment by wsdjeg** [comment]
Ohh, sorry, will fix it.

**Comment by wsdjeg** [comment]
@ming-codes I have fixed it, you can add `set backgroud=light` to your custom config file.
