### ISSUE TITLE
Disable auto-insert when switching to terminal buffer

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1430]
https://github.com/SpaceVim/SpaceVim/blob/bb106aa33d0707394077c3447ac1a131de588af8/config/neovim.vim#L74

Think of this scenario, when you have several regular buffers and a terminal buffer, which may look like the following image:

<img width="508" alt="screen shot 2018-02-22 at 10 46 08 am" src="https://user-images.githubusercontent.com/2555093/36517582-9f3d96be-17bd-11e8-9463-7fb9940fbe26.png">

When you switch around these buffers, `] b` will be input as regular text rather than key mapping sequence. This experience is really annoying. 

When I suggest is to remove the auto insert command, instead, we should use `stopinsert` to keep the buffer switching experience consistency as other regular buffers.

**Comment by wsdjeg** [comment]
Do you have a try with `ALt + Left/Right`?

**Comment by icearith** [comment]
`ALT + Left/Right` works well

**Comment by wsdjeg** [comment]
```diff
diff --git a/autoload/SpaceVim/layers/default.vim b/autoload/SpaceVim/layers/default.vim
index 508635c4..dfc46b4a 100644
--- a/autoload/SpaceVim/layers/default.vim
+++ b/autoload/SpaceVim/layers/default.vim
@@ -30,8 +30,8 @@ function! SpaceVim#layers#default#config() abort
   nnoremap <silent>]e  :<c-u>execute 'move +'. v:count1<cr>
 
   " [b or ]n go to previous or next buffer
-  nnoremap <silent> [b :<c-u>bN<cr>
-  nnoremap <silent> ]b :<c-u>bn<cr>
+  nnoremap <silent> [b :<c-u>bN \| stopinsert<cr>
+  nnoremap <silent> ]b :<c-u>bn \| stopinsert<cr>
 
   " [f or ]f go to next or previous file in dir
   nnoremap <silent> ]f :<c-u>call <SID>next_file()<cr>
diff --git a/autoload/SpaceVim/plugins/windowsmanager.vim b/autoload/SpaceVim/plugins/windowsmanager.vim
index e7ebc140..8ae41982 100644
--- a/autoload/SpaceVim/plugins/windowsmanager.vim
+++ b/autoload/SpaceVim/plugins/windowsmanager.vim
@@ -29,6 +29,9 @@ endfunction
 
 function! SpaceVim#plugins#windowsmanager#UpdateRestoreWinInfo() abort
     if !&buflisted
+      if &buftype == 'terminal'
+        noautocmd q
+      endif
         return
     endif
     let s:unmarked = 1
```
