### ISSUE TITLE
After install.cmd installation on Windows 7, gvim only opens once without errors

### ISSUE THREAD

**Issue by tjcertified** [wsdjeg/SpaceVim#1434]
## Expected behavior, english is required
gvim should open with SpaceVim enabled

## The reproduce ways from Vim starting (Required!)
run install.cmd, then open gvim, then close gvim, then open gvim again
## Debug info
None, because it won't start correctly after the first start

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
what is the issue？ I can not understand.
