### ISSUE TITLE
How to view package update errors

### ISSUE THREAD

**Issue by nedludd** [wsdjeg/SpaceVim#1435]
How do you see the errors that occur during a package update (`SPUpdate`)?

Several packages are failing, but I can't see why.

For example:

<img width="402" alt="_usr_local_bin_vim_-r__vim_" src="https://user-images.githubusercontent.com/17875/36564647-fc7f7bca-17eb-11e8-9cf2-1c13eb4a1b2c.png">

**Comment by nedludd** [comment]
More and more packages are failing on update. But no way to see what's going wrong.

**Comment by wsdjeg** [comment]
In the new PR, #1446, `gi` is a key binding for view plugin status;

![2018-03-02-21 05 54](https://user-images.githubusercontent.com/13142418/36900516-321aadd8-1de9-11e8-8a9f-ae090f1bf314.png)
