### ISSUE TITLE
Consider adding vim-netranger

### ISSUE THREAD

**Issue by zaisheng** [wsdjeg/SpaceVim#1439]
https://github.com/ipod825/vim-netranger

Vim-netranger is a ranger-like system/cloud storage explorer for Vim/Neovim. It brings together the best of Vim, ranger, and rclone:

**Comment by wsdjeg** [comment]
what is the advantage? in SpaceVim, we use vimfiler as default file explorer ( next version is https://github.com/Shougo/defx.nvim )
