### ISSUE TITLE
Crashed when typing

### ISSUE THREAD

**Issue by shiningdracon** [wsdjeg/SpaceVim#1445]
## The reproduce ways from Vim starting (Required!)
```
#include <stdio.h>

int main(int argc, char *argv[])
{
  int a
  return 0;
}

```
When typing the `int a` crash happened right after `a` key is pressed (other character keys the same).

## Debug info
Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

ProblemType: Crash
Architecture: amd64
CrashCounter: 1
CurrentDesktop: Unity
Date: Tue Feb 27 16:35:49 2018
DistroRelease: Ubuntu 16.04
ExecutablePath: /usr/bin/vim.basic
ExecutableTimestamp: 1480021012
ProcCmdline: vi main.c
ProcCwd: /home/bz/setuid
ProcEnviron:
 TERM=xterm-256color
 SHELL=/bin/bash
 PATH=(custom, user)
 LANG=en_CA.UTF-8
 LANGUAGE=en_CA:en
 XDG_RUNTIME_DIR=<set>

Disassembly:
 => 0x7f866620e830 <__libc_start_main+240>:     mov    %eax,%edi
    0x7f866620e832 <__libc_start_main+242>:     callq  0x7f8666228030 <__GI_exit>
    0x7f866620e837 <__libc_start_main+247>:     xor    %edx,%edx
    0x7f866620e839 <__libc_start_main+249>:     jmpq   0x7f866620e779 <__libc_start_main+57>
    0x7f866620e83e <__libc_start_main+254>:     mov    0x3a8ecb(%rip),%rax        # 0x7f86665b7710 <__libc_pthread_functions+400>
    0x7f866620e845 <__libc_start_main+261>:     ror    $0x11,%rax
    0x7f866620e849 <__libc_start_main+265>:     xor    %fs:0x30,%rax
    0x7f866620e852 <__libc_start_main+274>:     callq  *%rax
    0x7f866620e854 <__libc_start_main+276>:     mov    0x3a8ea5(%rip),%rax        # 0x7f86665b7700 <__libc_pthread_functions+384>
    0x7f866620e85b <__libc_start_main+283>:     ror    $0x11,%rax
    0x7f866620e85f <__libc_start_main+287>:     xor    %fs:0x30,%rax
    0x7f866620e868 <__libc_start_main+296>:     lock decl (%rax)
    0x7f866620e86b <__libc_start_main+299>:     sete   %dl
    0x7f866620e86e <__libc_start_main+302>:     test   %dl,%dl
    0x7f866620e870 <__libc_start_main+304>:     je     0x7f866620e892 <__libc_start_main+338>
    0x7f866620e872 <__libc_start_main+306>:     xor    %eax,%eax
EcryptfsInUse: Yes
InstallationDate: Installed on 2018-01-22 (36 days ago)
InstallationMedia: Ubuntu 16.04.3 LTS "Xenial Xerus" - Release amd64 (20170801)

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
It seems not SpaceVim issue.

**Comment by wsdjeg** [comment]
Please use gvim8.0 instead.
