### ISSUE TITLE
ctrlp layer is disabled by default

### ISSUE THREAD

**Issue by jetm** [wsdjeg/SpaceVim#1448]
## Expected behavior, English is required
ctrlp layer enabled by default, as it used to be before.

## The reproduce ways from Vim starting (Required!)

Press <ctrl-p> and not list files completion will show up.

I tracked down the problem to the following commits:

* c580ac62 (origin/master, origin/HEAD) Rewrite plugin manager (#1446)
* 43f79143 Merge pull request #1438 from wsdjeg/default
* 52eb8de9 Merge branch 'master' into default
* 651aeb6d Remove func
* 3ea4db47 Update default
* 8892d0a8 Fix key in mapping guide
* 2fce2172 Disable some layers
* 307aa50e Fix indent
* 3ac76a0c Better default

Not sure which is the culprit.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
for better default, I do not want to load unite denite ctrlp layer at same time. there is an issue for disscution about better default

**Comment by jetm** [comment]
Thanks. I am following the discussion #1436. I read more about denite and I can understand why could be a better option than ctrlp. I still need to learn how to use it. Meanwhile, I would keep behind of master to see where it goes. I have missed the old days when dev and master branches existed. dev for development and master for releases and more stable.

**Comment by wsdjeg** [comment]
let's move to that channel, :)
