### ISSUE TITLE
Any new install on clean ubuntu-based distro gives errors, not installing anything and vim is ugly broken

### ISSUE THREAD

**Issue by idchlife** [wsdjeg/SpaceVim#1449]
## Expected behavior, english is required

First start everything working fine

## The reproduce ways from Vim starting (Required!)
Make fresh install of ubuntu-based distro (ubuntu, mint), get error after starting via "vim" command

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
![image](https://user-images.githubusercontent.com/4563032/36921601-fc22145e-1e75-11e8-8075-b1874ea18aad.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

Error info in text:

```python
Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install[18]..<SNR>115_set
line[2]..6:
line   19:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install[18]..<SNR>115_set
line[2]..6:
line   19:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install[18]..<SNR>115_set
line[2]..6:
line   19:
AttributeError: module 'string' has no attribute 'atoi'
Press ENTER or type command to continue
```

No kidding. I love SpaceVim so much I even reinstalled distro

**Comment by wsdjeg** [comment]
@idchlife I think it is bug of python string mode itself. why `atoi` is deleted?

```
string.atoi has been deprecated for a very long time. Since Python 2.0, in fact, and it doesn't exist in Python 3.

Simply use

value = int(s)
instead, and don't call your variable str. That's a bad habit, as it shadows the builtin string type str.
```

https://stackoverflow.com/questions/20208570/python-attributeerror-module-object-has-no-attribute-atoi

**Comment by idchlife** [comment]
@wsdjeg I believe this fix fired this error now (not creating new issue since name of current suits perfectly):

![image](https://user-images.githubusercontent.com/4563032/36931899-0499fd4e-1ed1-11e8-82a3-7cc06a993501.png)


```python
Error detected while processing function <SNR>115_on_install_exit:
line    3:
E716: Key not present in Dictionary: -1
Press ENTER or type command to continue
Error detected while processing function <SNR>115_on_install_exit:
line    3:
E116: Invalid arguments for function <SNR>115_msg_on_install_done
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install:
line   26:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin:
line    4:
E171: Missing :endif
Press ENTER or type command to continue
```

Also, installing plugins is frozen and vim looks like this:

![image](https://user-images.githubusercontent.com/4563032/36931918-479ea05e-1ed1-11e8-8d31-372053bf3b24.png)

Could this be something with python in system or library? On my macos spacevim works flawlessly. But it maybe because I did install a whole bunch of different software on macos, including python, lua, ruby, etc

**Comment by wsdjeg** [comment]
@idchlife What is your vim version? please use issue template.

**Comment by idchlife** [comment]
@wsdjeg VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)

You mean create new issue instead writing here?

**Comment by idchlife** [comment]
Issue resolved for good after installation of new Vim.

Thanks!
