### ISSUE TITLE
cc:  ... Static check messy code

### ISSUE THREAD

**Issue by zgpio** [wsdjeg/SpaceVim#1453]
## Expected behavior, english is required
I install nerd-fonts successly. When I edit a C file which have a warning, the info "cc: ..." is messy code.
How should I solve this problem？Or how can I turn off the “cc:...” information.

## The reproduce ways from Vim starting (Required!)
Just new a .c file, and then insert just like 
```c
#include<stdio.h>
int main()
{
  int a;
  return 0;
}
```
After save the c file, move the cursor to line ``` int a;```,  the ```cc: ...``` information is messy code just like the screenshots.
## Screenshots
![test](https://raw.githubusercontent.com/userboot/PortableGvim/master/Screenshot_20180303_101128.png)

**Comment by wsdjeg** [comment]
what is the debug info, I can not reproduce it.

**Comment by wsdjeg** [comment]
![2018-03-04-22 49 52](https://user-images.githubusercontent.com/13142418/36946913-0f4d9ce6-1f8a-11e8-977b-8a8685763ac5.png)

ok, I think it is due to there are two `‘` arroud `a`. will try to fix it.

**Comment by zgpio** [comment]
I think so

**Comment by wsdjeg** [comment]
@zgpTree can you copy the content of that line here, I can not get the char arroud `a`.

you can move cursor to the error line, then run `:let @+=neomake#GetCurrentErrorMsg()`, the post here.
