### ISSUE TITLE
Error while processing function neosnippet

### ISSUE THREAD

**Issue by astroclark** [wsdjeg/SpaceVim#1456]
Various insert operations result in "Can't create file ~/.cache/neosnippet/BLAH" and the mouse disappears (so I can't copy the error message in! Please see the screen cap below)

## Expected behavior, english is required
Vim should go into insert mode as normal

## The reproduce ways from Vim starting (Required!)
OS: Ubuntu 16.04

Open a file with:  
```
vim /path/to/file.py
```
Attempt to insert new line with:
```
:o
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

Any keyboard operation makes the error message vanish and operation continues as normal

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![screenshot from 2018-03-03 08-50-00](https://user-images.githubusercontent.com/5039139/36935094-ba6587c6-1ec0-11e8-84ad-265449972693.png)

**Comment by wsdjeg** [comment]
@astroclark What is your custom config?

**Comment by astroclark** [comment]
I don't think there's anything custom in it:
```
[jclark@balor] $ cat ~/.SpaceVim.d/init.vim
" Dark powered mode of SpaceVim, generated by SpaceVim automatically.
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#elixir')
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#haskell')
call SpaceVim#layers#load('lang#java')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#perl')
call SpaceVim#layers#load('lang#php')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#rust')
call SpaceVim#layers#load('lang#swig')
call SpaceVim#layers#load('lang#tmux')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('shell')   
call SpaceVim#layers#load('tools#screensaver')
let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
let g:deoplete#auto_complete_delay = 150
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:neomake_vim_enabled_makers = []
let g:spacevim_colorscheme = 'torte'
let g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles/'

if executable('vimlint')
    call add(g:neomake_vim_enabled_makers, 'vimlint') 
endif
if executable('vint')
    call add(g:neomake_vim_enabled_makers, 'vint') 
endif
if has('python3')
    let g:ctrlp_map = ''
    nnoremap <silent> <C-p> :Denite file_rec<CR>
endif
let g:clang2_placeholder_next = ''
let g:clang2_placeholder_prev = ''
```

**Comment by wsdjeg** [comment]
I can not reproduce it. please make sure your spacevim and plugins are update to date.

**Comment by Shougo** [comment]
@astroclark You should check `~/.cache/neosnippet` permission.
I think it cannot be writeable.
