### ISSUE TITLE
Uninstall on Windows?

### ISSUE THREAD

**Issue by xitska** [wsdjeg/SpaceVim#1458]
So, I'd rather switch back to normal Vim, is there a way to uninstall on windows?

**Comment by wsdjeg** [comment]
just delete ~/vimfiles

**Comment by Anogoya-Dagaate** [comment]
I think there should be a more comprehensive guide than this - during configuration users may have pointed directories such as plug-in add-ons to be installed into the vimfiles folder, as was my case. Naturally, its their responsibility but we know people will still blame it on Spacevim if they indiscriminately lose configuration as a result of 'just delete ~/vimfiles'.

**Comment by wsdjeg** [comment]
Yeah, But if user use install script. vimfiles is a symlink to .SpaceVim, so just delete it. Please use new issue if there are any suggestions.
