### ISSUE TITLE
Win10 fail to open spacevim ....

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1461]
open gvim and show the info like this :

Error detected while processing function 
SpaceVim#begin[34]..SpaceVim#default#opti
ons:

line   66:

E739: Cannot create directory: C:\Users\simon
/.cache/SpaceVim

Error detected while processing C:\Users\simo
n\vimfiles\vimrc:

line   11:

E171: Missing :endif

**Comment by ghost** [comment]
i fixed the problem.
it's because the Windows Defender on win10 prevents me from creating  directory.
so if you have the same issue as me , you need to close the windows defender, and then open the gvim.
Or you can create folder called .cache, then open the gvim. 
Hope it can help you.

**Comment by wsdjeg** [comment]
@teemola Thanks for your info.

**Comment by fanmmy** [comment]
Run cmd with Anministor then located at C:/Users/XXX，mkdir .cache ，then open the gVim.exe

**Comment by suning2012** [comment]
@MurrayFan Thank you .Your suggestion is very useful.

**Comment by wsdjeg** [comment]
I have fix this issue.
