### ISSUE TITLE
Fail  to open SpaceVim under Ubuntu

### ISSUE THREAD

**Issue by GGGGGarfield** [wsdjeg/SpaceVim#1467]
![2018-03-04 23-07-06](https://user-images.githubusercontent.com/36780800/36947087-4c121558-2002-11e8-9eb1-75261ed47aa5.png)

**Comment by JosueELP** [comment]
i have the same issue :(

**Comment by wsdjeg** [comment]
what is your Vim version？

`vim --version`

**Comment by GGGGGarfield** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056

**Comment by wsdjeg** [comment]
vim --version

**Comment by GGGGGarfield** [comment]
I update Vim to the latest version then fixed the problem

**Comment by wsdjeg** [comment]
@GGGGGarfield I think this is an error in vim7.4. I will try to fix it.
