### ISSUE TITLE
how to use SpaceVim to debug a C program

### ISSUE THREAD

**Issue by greatlim** [wsdjeg/SpaceVim#1469]
I only see the demo of debugging Python in the youtube.
I try to launch the debugger to debug a C program, however,  I don't know how to configure it.
I'm a novice and hope someone can give me some instructions.

**Comment by wsdjeg** [comment]
@GreatLim first, you need to load the debug layer,

```vim
call SpaceVim#layers#load('debug')
```

then, you need to read the doc of debug layer, it list all the key bindings for debug.

http://spacevim.org/layers/debug/

**Comment by greatlim** [comment]
I have load debug layer, and it seems work when I debug python. But, when I want to debug C and try to launch debugger, it shows a message as this picture:
![](https://ws2.sinaimg.cn/large/006tNc79gy1fp27ny78ioj311w0vcdjy.jpg)

**Comment by wsdjeg** [comment]
Ok, I will look into it.

**Comment by wsdjeg** [comment]
first you need compile your c file with `-g` options, then you can use `VBGstartGDB a.out` to launching the debugger.
