### ISSUE TITLE
底部状态栏不显示分支问题

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1472]
请教一下，为何底部不显示分支情况，字体和图标都装了，mac的平台。
 
<img width="1680" alt="2018-03-07_14-59-34" src="https://user-images.githubusercontent.com/22193642/37078028-85604646-2218-11e8-87e2-313078a8fb85.png">

**Comment by wsdjeg** [comment]
Englist is recommended, by default, `git` and `VersionControl` layer is not loaded, you need to load them in your spacevim config.

and also there is a new PR ref this issue: #1470

**Comment by ghost** [comment]
OK，But..
<img width="481" alt="2018-03-07_15-31-36" src="https://user-images.githubusercontent.com/22193642/37079234-de3dbd9e-221c-11e8-8afb-37b0102a173a.png">

**Comment by wsdjeg** [comment]
You need to load git layer in current version , after the new PR git layer is not needed.

**Comment by ghost** [comment]
I do not understand, @wsdjeg

**Comment by wsdjeg** [comment]
`git` and `VersionControl` are two different layer, you need to load them at same time.

**Comment by wsdjeg** [comment]
BTW, I think you need to remove `let mapleader="\<space>"` as SpaceVim do not use Space as Leader, we use Space as a custom leader, this leader only used in normal and visual mode.

**Comment by ghost** [comment]
Thank you very much！

**Comment by wsdjeg** [comment]
Done.
