### ISSUE TITLE
Error detected when editing a C or C++ source file

### ISSUE THREAD

**Issue by yangtetris** [wsdjeg/SpaceVim#1473]
## Expected behavior, english is recommend

The source should be opened without error message.

## Environment Information

- OS:Ubuntu 14.04
- vim version:
- neovim version:0.2.3

## The reproduce ways from Vim starting (Required!)

Install SpaceVim using the given script, and launch nvim to install plugins
```nvim test.c``` or ```nvim test.cpp```
the error message will appear
- Error detected while processing function <SNR>158_start_clamp[4]..ClampOnTextChanged:

I didn't modify any file. Could you please give me some suggestions?

### SpaceVim Options :

```viml
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'version control info', 'hunks']
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.7.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_default_indent = 2
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_enable_language_specific_leader = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_smartclose = 'q'
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_ale = 0
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_key_frequency = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_lint_on_save = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'completor'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 16
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_project_rooter_automatically = 1
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/dmt/disk/baiyang/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_keep_server_alive = 1
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'package.json']
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_realtime_leader_guide = 1
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_filetype_icons = {}
g:spacevim_plugin_name = 'nord-vim'
g:spacevim_enable_cursorline = 1
g:spacevim_custom_color_palette = []
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_language = ''
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:53:55] [ Info ] Skip glob configration of SpaceVim
[ SpaceVim ] [19:53:55] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
```
## Screenshots

![2018-03-08 1](https://user-images.githubusercontent.com/7304058/37150420-934c96b6-230c-11e8-8b7b-0a1e93028b30.png)

**Comment by hsienkaikuo** [comment]
@HALO-04 Did you solve the issue, I guess I ran into the same one. Thanks

**Comment by ghost** [comment]
I can reproduce.

The workaround is to put

```
let g:clamp_autostart = 0
```

into the config to disable it.

I have a suspicion it has something to do with the `neovim/python-client`.

**Comment by wsdjeg** [comment]
Ok, I got it, this is issue about c highlight plugins, now there many kinds of clang based highlight plugin, I hope we can make a discussion about them.

in current version of spacevim, the logic is:

```
  if has('nvim')
    if s:CPT.has('python3') && SpaceVim#util#haspy3lib('clang')
      call add(plugins, ['arakashic/chromatica.nvim', { 'merged' : 0}])
    else
      call add(plugins, ['bbchung/Clamp', { 'if' : has('python')}])
    endif
  elseif has('job')
    call add(plugins, ['bbchung/clighter8', { 'if' : has('python')}])
  else
    call add(plugins, ['bbchung/clighter', { 'if' : has('python')}])
  endif
```

I think this logic is wrong. we need to improve it.

**Comment by yangtetris** [comment]
I re-installed SpaceVim 5 days ago in the same environment, and I can't reproduce the bug for unknown reasons. Now everything works fine.

**Comment by wsdjeg** [comment]
@HALO-04 Thanks, but the logic need to be updated, let's keep this issue opened until we fix the logic.

**Comment by ihexon** [comment]
Oh ,I have same Bugs,I recommond change to chromatica, and remove clighter8

**Comment by wsdjeg** [comment]
does chromatica works well in Vim8？

**Comment by ihexon** [comment]
@wsdjeg No chromatica do not work with Vim8

**Comment by ghost** [comment]
Actually, regarding chromatica, it doesn't even appear on the list of plugins, even though I'm using neovim and the lastert version of spacevim. It used to work some time ago, at the time when a user had to specify a libclang path manually (which I did). Should I open a new issue?

**Comment by wsdjeg** [comment]
@light2yellow if your issue is not same as this, ofcause you can open a new issue.

**Comment by george-githinji** [comment]
I have a similar issue with the same error message. Installing and recompiling neovim and spacevim did not work.   Spacevim version 0.8.0-dev

**Comment by wsdjeg** [comment]
I have changed the logic.

**Comment by evopen** [comment]
@wsdjeg is the problem solved yet? No problem with vim, but with neovim 0.2.2 on ubuntu.

**Comment by wsdjeg** [comment]
yeah, please update neovim.

**Comment by techwoes** [comment]
I had a similar problem and had to delete the neocomplete folder in my .cache folder on Ubuntu 18.04
