### ISSUE TITLE
Gtags command does not work?

### ISSUE THREAD

**Issue by ls-zhu** [wsdjeg/SpaceVim#1477]
## Expected behavior, english is required
Since I see Gtagts in included in the tags layer, I think Gtags command should work, like Gtags -r func

## The reproduce ways from Vim starting (Required!)
:Gtags -r some_function, it will show that this command not found.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@ls-zhu What is your custom config, do you load `tags` layer?

**Comment by ls-zhu** [comment]
@wsdjeg I don't have a custom config, nothing changed form this repo, just my first try. The tags layer is not auto-loaded. I think if we have gtags.vim, we don't have to "load" it.

**Comment by wsdjeg** [comment]
Not all layers in spacevim are loaded when first time using spacevim, not all users need all layers, you need to config spacevim.

**Comment by ls-zhu** [comment]
@wsdjeg How to loaded it? IMHO, gtags ia quite common for development, does it make any sense to config it auto loaded?

**Comment by wsdjeg** [comment]
no, you need to read https://spacevim.org/layers/
