### ISSUE TITLE
nvim hint error under windows

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1478]
## Expected behavior, english is required

no error message output

## The reproduce ways from Vim starting (Required!)

always

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

![default](https://user-images.githubusercontent.com/1751829/37243941-9b9d844a-24bc-11e8-828d-14c8733f3c8e.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Please reinstall spacevim, and I can not reproduce it. and you need to post your os and vim info.

for example path of SpaceVim.

**Comment by xumuyao** [comment]
I encountered the same problem.
When I started gvim from Win+R, gvim showed
![2018-03-30_08-52-30](https://user-images.githubusercontent.com/22831312/38119957-107a082a-33f8-11e8-9197-9af7fc482d04.png)
When I started gvim from cmd, gvim worked fine.

OS version: Windows 10 professional 64bit
vim version: gvim80 i586
![default](https://user-images.githubusercontent.com/22831312/38120336-b5fcf828-33fa-11e8-97d4-9987cb175ee1.png)

SpaceVim was cloned at ~/vimfiles.  The .cache and .SpaceVim.d directories were created succussfullly.  vimproc.dll was built sucessfully.
This is my home directory.
![default](https://user-images.githubusercontent.com/22831312/38120066-aa1c8ba6-33f8-11e8-8fa6-d3d924c7f4a7.png)

**Comment by wsdjeg** [comment]
as can  load `SpaceVim#loadCustomConfig`, why it can not load `SpaceVim#logger#info`? they are in same runtimepath. I think it is bug of vim itself. and I can not fix it.

**Comment by xumuyao** [comment]
And I find that if PWD is $HOME, gvim cannot load properly
![default](https://user-images.githubusercontent.com/22831312/38121962-f49050f8-3404-11e8-9786-19a7bce3092f.png)
But when PWD is changed to $HOME\.SpaceVim.d,  gvim can load properly.
![default](https://user-images.githubusercontent.com/22831312/38122177-1464109e-3406-11e8-9bbd-6ba02da56a0b.png)

**Comment by wzhe** [comment]
I encountered the same problem too.

![17b4e21a-c8d6-4110-887e-22317464e3fc](https://user-images.githubusercontent.com/6120110/38132218-c09ef2da-343c-11e8-8d85-5cfc117d11a4.jpg)

**Comment by xumuyao** [comment]
If I double-click gvim.exe, the vim files are loaded.  If I try to start vim/gvim from the Win+R menu or cmd, the problem always occurs.
I agree on the idea that this problem may be a bug of vim itself.

**Comment by wsdjeg** [comment]
I can not reproduce this issue on master now.

**Comment by wsdjeg** [comment]
@Matrix-Zhang can you test the master branch?

**Comment by deepseeksss** [comment]
@wsdjeg 

may i need to reinstall?

after git pull from the master, the problem also reduce,,,,

![default](https://user-images.githubusercontent.com/1751829/39569060-ab94cd4a-4ef6-11e8-9137-4f168e4b1b6a.png)

**Comment by deepseeksss** [comment]
after reinstall. it will be fine..
