### ISSUE TITLE
Invalid source name "gtags/path" is detected.

### ISSUE THREAD

**Issue by jgimeno** [wsdjeg/SpaceVim#1479]
I am getting this error while using tags layer, I cant go to definition in a php project,

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by jgimeno** [comment]
Sorry guys, this is solved adding unite layer. It is disabled by default, so maybe it is a good idea to add this to the tags config page. Thanks!

**Comment by wsdjeg** [comment]
yeah, I will update the layer documentation.

**Comment by wsdjeg** [comment]
`gtags/path` I think this plugin should be included in tags layer.

**Comment by wsdjeg** [comment]
Let's move to #1511
