### ISSUE TITLE
Correct way to map jj to exit insert mode.

### ISSUE THREAD

**Issue by jgimeno** [wsdjeg/SpaceVim#1480]
Hi! This is not a bug, just a doubt I have, I am very happy about nearly all the mappings that spacevim brings. The only one that I miss is jj to exit insert mode, I have seen that I can do this with jk. But, is it worth it to learn this new way instead of adding my jj? I think it is more standard way to exit the insert mode.

Thanks!!

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
double click will hurt your finger. jk is fast than jj. we should avoid double click in mappings.
