### ISSUE TITLE
Can't change airline theme

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [wsdjeg/SpaceVim#1483]
## Expected behavior, english is required
Can't change airline theme:

## The reproduce ways from Vim starting (Required!)
Install theme:

```
let g:spacevim_custom_plugins = [
 \ ['dracula/vim', {'merged': 0}],
 \ ['vim-airline/vim-airline-themes', {'merged': 0}]
 \ ]
```

colorscheme dracula
let g:airline_theme='dracula'

Color scheme changes but the airline theme does not.
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

SpaceVim layers:

> + autocomplete:             loaded          https://spacevim.org/layers/autocomplete
> - chat:                 not loaded          https://spacevim.org/layers/chat
> + checkers:                 loaded          https://spacevim.org/layers/checkers
> - chinese:              not loaded          https://spacevim.org/layers/chinese
> + colorscheme:              loaded          https://spacevim.org/layers/colorscheme
> + core/banner:              loaded          no exists
> + core/statusline:          loaded          no exists
> + core/tabline:             loaded          no exists
> + core:                     loaded          no exists
> - cscope:               not loaded          https://spacevim.org/layers/cscope
> - ctrlp:                not loaded          https://spacevim.org/layers/ctrlp
> - debug:                not loaded          https://spacevim.org/layers/debug
> - denite:               not loaded          https://spacevim.org/layers/denite
> + edit:                     loaded          no exists
> - exprfold:             not loaded          no exists
> + format:                   loaded          no exists
> - games:                not loaded          no exists
> - git:                  not loaded          https://spacevim.org/layers/git
> - github:               not loaded          https://spacevim.org/layers/github
> - incsearch:            not loaded          no exists
> - indentmove:           not loaded          no exists
> - japanese:             not loaded          no exists
> - lang/c:               not loaded          https://spacevim.org/layers/lang/c
> - lang/clojure:         not loaded          no exists
> - lang/crystal:         not loaded          no exists
> - lang/csharp:          not loaded          https://spacevim.org/layers/lang/csharp
> - lang/dart:            not loaded          https://spacevim.org/layers/lang/dart
> - lang/elixir:          not loaded          https://spacevim.org/layers/lang/elixir
> + lang/go:                  loaded          https://spacevim.org/layers/lang/go
> - lang/haskell:         not loaded          https://spacevim.org/layers/lang/haskell
> - lang/html:            not loaded          https://spacevim.org/layers/lang/html
> - lang/java:            not loaded          https://spacevim.org/layers/lang/java
> - lang/javascript:      not loaded          https://spacevim.org/layers/lang/javascript
> - lang/json:            not loaded          no exists
> - lang/julia:           not loaded          no exists
> - lang/kotlin:          not loaded          no exists
> - lang/lisp:            not loaded          https://spacevim.org/layers/lang/lisp
> - lang/lua:             not loaded          https://spacevim.org/layers/lang/lua
> - lang/markdown:        not loaded          https://spacevim.org/layers/lang/markdown
> - lang/ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml
> - lang/perl:            not loaded          no exists
> - lang/php:             not loaded          https://spacevim.org/layers/lang/php
> - lang/pony:            not loaded          no exists
> - lang/ps1:             not loaded          no exists
> - lang/puppet:          not loaded          no exists
> - lang/python:          not loaded          https://spacevim.org/layers/lang/python
> - lang/ruby:            not loaded          https://spacevim.org/layers/lang/ruby
> - lang/rust:            not loaded          no exists
> - lang/scala:           not loaded          no exists
> - lang/sh:              not loaded          no exists
> - lang/solidity:        not loaded          no exists
> - lang/swig:            not loaded          no exists
> - lang/tmux:            not loaded          no exists
> - lang/typescript:      not loaded          https://spacevim.org/layers/lang/typescript
> - lang/vim:             not loaded          https://spacevim.org/layers/lang/vim
> - lang/xml:             not loaded          no exists
> - lang:                 not loaded          no exists
> - lsp:                  not loaded          no exists
> - mail:                 not loaded          no exists
> - operator:             not loaded          no exists
> - shell:                not loaded          https://spacevim.org/layers/shell
> - tags:                 not loaded          https://spacevim.org/layers/tags
> - tmux:                 not loaded          no exists
> - tools/dash:           not loaded          https://spacevim.org/layers/tools/dash
> - tools/screensaver:    not loaded          no exists
> + tools:                    loaded          no exists
> + ui:                       loaded          https://spacevim.org/layers/ui
> + unite:                    loaded          https://spacevim.org/layers/unite
> - VersionControl:       not loaded          https://spacevim.org/layers/VersionControl
> - vim:                  not loaded          no exists

## Screenshots
![screen shot 2018-03-12 at 9 12 40 pm](https://user-images.githubusercontent.com/29370/37317242-24791f94-263a-11e8-91cc-51e70d699bb9.png)

**Comment by wsdjeg** [comment]
In SpaceVim，the default statusline is not airline。we have default statusline plugin.

**Comment by CodeMonkeyKevin** [comment]
Thanks.
