### ISSUE TITLE
how to append syntax rule for certain file type?

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#1484]
## Expected

syntax for python variable type annotation
[PEP 526](https://www.python.org/dev/peps/pep-0526/) 

![image](https://user-images.githubusercontent.com/5415510/37344833-64a4f9f4-2706-11e8-99d4-9b9b97e19e5a.png)

## Environment Information
 * OS: linux
 * vim version: 8.0
 * neovim version: 0.2.2

https://github.com/wsdjeg/DotFiles/issues/70

**Comment by y9c** [comment]
I wrap my own plugin and import it from spacevim.d/init.vim.

![image](https://user-images.githubusercontent.com/5415510/37385257-4afcd4b2-278e-11e8-9ab4-892ec2c36bb9.png)

It works, but I don't think it the best solution.

---

![image](https://user-images.githubusercontent.com/5415510/37385356-9f147c58-278e-11e8-8902-653b1279e648.png)

**Comment by wsdjeg** [comment]
same as https://github.com/SpaceVim/SpaceVim/issues/1488, I can not fix it, this should be fixed by colorscheme or user's config.
