### ISSUE TITLE
Auto close pair mess up when typing triple quote.

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#1486]
It is almost impossible to input triple quote for python docstring, or triple back quote for markdown code block.

\"\"\"  test for python \"\"\"

\`\`\`  test for mardown \`\`\`

---

Only 5 quote symbol type in, after hiting the key 6 times, and the position of the cursor is weird.

**Comment by wsdjeg** [comment]
This is an issue about Raimondi/delimitMate.

The only way for me to fix it is press`` ````foo```` ``, then you will get `` ```foo``` ``

**Comment by y9c** [comment]
I think it is time to rewrite the project and expose more APIs to the users.
 
For example, to fix this issue, I need the known which function is responsible for closing tags, and even though you figure out the plugin, it is difficult to location which vim script call this plugin.

By searching source code in the github repo, I find this plugin in autocomplete layer, but there isn't an  API for modifying the layer.  Disabling the plugin is the only way to fix it.

**Comment by y9c** [comment]
Layer is good design. It is on top of plugin, and plugin is on top of function. Plugin never destroy internal function, so does layer.

**Comment by wsdjeg** [comment]
you need to read `:h delimitMate` the plugins's option can be setted in your configuration file.
