### ISSUE TITLE
yaml, toml or json?

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1490]
In current version, we use Vim script to write config file. maybe we could support other language!

**Comment by wsdjeg** [comment]
current version of spacevim only support json, but yaml or toml will be supportted in the feature.

**Comment by CermakM** [comment]
Are there any plans to support `lang#yaml` in the near future as well?

**Comment by wsdjeg** [comment]
@CermakM what feature should be included in `lang#yaml` layer? please use new issue for feature request,thanks.
