### ISSUE TITLE
Missing cursor indicator in Incsearch

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1493]
## Expected behavior, english is required

Incsearch should show a "1/10" label on status line to tell user the cursor is on which result. This feature was introduced in a very early version and has been disappeared for a long time.

## The reproduce ways from Vim starting (Required!)
1. load layer "incsearch"
2. search arbitrary thing

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@icearith I have fix this issue, please load `incsearch` layer.
