### ISSUE TITLE
go-vim error.

### ISSUE THREAD

**Issue by verifier-studio** [wsdjeg/SpaceVim#1494]
I use ArchLinux and Neovim.
when I open *.go file, and insert something, show this error.
```shell
vim-go: go#util#Exec() called with empty a:cmd 
```

![1](https://user-images.githubusercontent.com/22971135/37507983-0c113ab4-292c-11e8-9467-edb5e2b5da6a.png)

**Comment by y9c** [comment]
Run `:GoInstallBinaries` at the first time that you open a *.go file.

If you don't have internet access to golang.org repo. Use a http_proxy or install the required packages manually.

**Comment by y9c** [comment]
The dependent packages are not documented in the user manual. Try it out...

**Comment by verifier-studio** [comment]
@yech1990 Thank you, my neovim still can't use, but vim no the error, I use vim now.

**Comment by wsdjeg** [comment]
I can not reproduce it, you need to intsall go lang tools.
