### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by tianxingyang** [wsdjeg/SpaceVim#1495]
## The reproduce ways from Vim starting (Required!)

after using "curl -sLf https://spacevim.org/install.sh | bash -i" to install spacevim, every time when I open vim, some garbled text shows on my screen, "^[[2;2R^[[>0;136;0c" for example. After that, the image below shows.

## Screenshots

![image](https://user-images.githubusercontent.com/7824181/37508892-0648b04a-2930-11e8-9180-037e5348f23a.png)

**Comment by wsdjeg** [comment]
what is your vim --version？

**Comment by tianxingyang** [comment]
![image](https://user-images.githubusercontent.com/7824181/37512097-16c2ab4a-293c-11e8-9c58-71019004d304.png)

**Comment by wsdjeg** [comment]
I recommend to use vim 8

**Comment by tianxingyang** [comment]
thx a lot! vim 8 does solve my problem.

**Comment by wsdjeg** [comment]
nice！
