### ISSUE TITLE
micro "q" do not work

### ISSUE THREAD

**Issue by dindom999** [wsdjeg/SpaceVim#1496]
## Expected behavior, english is required
vim /tmp/test.txt
when I try to recode a micro with key "q", nothing happend
but when I use : sudo vim /tmp/test.txt
It work fine.

## The reproduce ways from Vim starting (Required!)
I am using i3wm
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
nothing shows
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
http://spacevim.org/documentation/#differences-between-vimneovim-and-spacevim
