### ISSUE TITLE
Unable to modify concealcusor setting.

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#1499]
## settings

default Spacevim setting.

## vim version

both vim 8.0 and neovim 0.2.2

## Bug

Can't modify the conceal setting (`concealcursor` and `conceallevel`).
Adding `let g:indentLine_concealcursor = ""` or `let g:concealcursor=""` or `set concealcursor=""` to init.vim file makes no effect.

![demo](https://user-images.githubusercontent.com/5415510/37532435-f7e44420-2979-11e8-9f74-cfa8b1a1155e.gif)

**Comment by y9c** [comment]
@wsdjeg

**Comment by wsdjeg** [comment]
can you post example file? the text of this gif?

**Comment by wsdjeg** [comment]
use `verbose set concealcursor` to see where this option was set.
