### ISSUE TITLE
The first letter of hints message is covered by the line number.

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#1500]
![demo](https://user-images.githubusercontent.com/5415510/37540092-c213e14a-2990-11e8-9fc2-1f4aedff7ef6.png)

**Comment by wsdjeg** [comment]
Do you have reproduce step? or example file? I can not reproduce it.

**Comment by y9c** [comment]
- save this  code snippet  into a new python file.

```python
print(hello)
print(100)
```

- save the file to trigger type hints.

- move the cursor into the first line, and wait..

- hints message will appear in the line bellow cursor

**Comment by y9c** [comment]
![image](https://user-images.githubusercontent.com/5415510/37566933-b22cc484-2afa-11e8-9c78-d367cb4b6403.png)

**Comment by wsdjeg** [comment]
Nothing is missing, the second `1` is relativenumber, and whole error message is

```
lake8: F821 undefinded name 'hello' (E)
```

**Comment by y9c** [comment]
### It is a Universal Error for any kind of language in vim.

I guess once there is error or warning message exist, SpaceVim will show a special symbol in font of row number, which takes up width of one character and cover the full message.

**Comment by y9c** [comment]
@wsdjeg 

the full message should be 

```
flake8: F821 undefinded name 'hello' (E)
```

**Comment by y9c** [comment]
`flake8` is the name of linter.

**Comment by wsdjeg** [comment]
ohh, the first word is `flake8` instead of `lake8`. I will check it.

**Comment by wsdjeg** [comment]
@yech1990 I have fix this issue. closed.

**Comment by y9c** [comment]
More serious error occur after patching the update!

a long unwanted phrase after the hints.

![image](https://user-images.githubusercontent.com/5415510/37878170-272db18e-3097-11e8-9485-55a088d49fed.png)

correct line cropped in the hints message. 
![image](https://user-images.githubusercontent.com/5415510/37878178-40f871da-3097-11e8-8a52-c558b8765369.png)

**Comment by wsdjeg** [comment]
It is bug of Vim itself. i can not fix it. see #1542

**Comment by y9c** [comment]
@wsdjeg  
I use neovim...

**Comment by crisidev** [comment]
Me too..

**Comment by wsdjeg** [comment]
Neovim has same bug

**Comment by wsdjeg** [comment]
OK I will improve this feature

**Comment by wsdjeg** [comment]
I have fix this issue, please update spacevim.

**Comment by y9c** [comment]
cool! It works fine now.
