### ISSUE TITLE
typescript layer can't be load automatically.

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#1501]
> To use this configuration layer, add call SpaceVim#layers#load('lang#typescript') to your custom configuration file. 

Typescript is treated as xml file in vim, thus call typescript layer won't install the corresponding plugins.

**Comment by wsdjeg** [comment]
do you have a try?

just add `call SpaceVim#layers#load('lang#typescript')` to your config, the plugins should be installled.

**Comment by y9c** [comment]
@wsdjeg

Use a complete new SpaceVim installation with default configuration to reproduce this bug.

`SpaceVim#layers#load('lang#typescript')` command will load typescript.vim file and run the code in it, but only when open a typescript file, the plugin will start to install. However, typescript file is treated as a xml file in default vim configuration.

**Comment by y9c** [comment]
Once the plugin is installed, typescript file can be rendered correctly, and the problem disappear.

**Comment by yech1990** [comment]
Once the plugin is installed, typescript file can be rendered correctly, and the problem disappear.

**Comment by y9c** [comment]
It is a issue of low priority. Close it if you don't have time to fix it.
I can install the correct plugin manually to make it work.

**Comment by wsdjeg** [comment]
sorry，I can not understand，SpaceVim do not load any language layer by default. if you are a typeacript developer. you should load typeacript layer. then it should works.

**Comment by kopach** [comment]
I have the same issue. All my `*.ts` files are recognized as `xml` by default. So, layer installation isn't working for me.
![screenshot at 13-01-02](https://user-images.githubusercontent.com/8749624/37828133-5f58d876-2e9a-11e8-8348-1d57642d115f.png)

**Comment by kopach** [comment]
@yech1990, how have you managed to  install it manually?

**Comment by wsdjeg** [comment]
@kopach what is your custom config?

**Comment by kopach** [comment]
@wsdjeg, it shows wrong filetype for typescript out of the box, without any modifications in configs.
I've also tried to add `call SpaceVim#layers#load('lang#typescipt')` in `init.vim` but this didn't helped me.

Another think I've tried to do - is adding `au BufRead,BufNewFile *.ts set filetype=typescipt` to `filetype.vim` - this solved problem with correct filetype, but haven't solved problem with typescript syntax

**Comment by wsdjeg** [comment]
I can not reproduce this problem.

first you should not edit any file in `~/.SpaceVim` or `~/.vim`, the user custom config is openned via `SPC f v d`, the path should be `~/.SpaceVim.d/init.vim`.

if you edit file in the repo, you will failed to update spacevim via `git pull`.

**Comment by kopach** [comment]
@wsdjeg, how can I completely uninstall SpaceVim with all the cached files etc? I would do this to try to install it again. I've reverted all my changed I've done before in `init.vim` and `filetype.vim` - edited config provided by `SPC f v d` but nothing helped me. I still see `xml` filetype for `*.ts` files :/

**Comment by wsdjeg** [comment]
No need to remove all things,

you can go to spacevim's root `~/.SpaceVim`, run `git checkout .`, this command will revert all your changes.

then press `SPC f v d`, you will see new buffer is open, just add

```
call SpaceVim#layers#load('lang#typescipt')
```

then restart vim, run `:SPUpdate`.

**Comment by kopach** [comment]
@wsdjeg, I did as you've described but I'm still facing the same issue. Moreover, I went even further: I've got another laptop (also on MacOS). In this case, there was no even standard vim configuration changed as no one was using vim on it. Here are steps I've done there:

1. `cd ~`
2. `curl -sLf https://spacevim.org/install.sh | bash`
3. `vim` (open vim from terminal)
4. I've got prompt about using what command line I would like to use. I've selected `dark powered` over `basic` one
5. in vim `SPC f v d` -> added `call SpaceVim#layers#load('lang#typescipt')`

```
"=============================================================================
" dark_powered.vim --- Dark powered mode of SpaceVim
" Copyright (c) 2016-2017 Wang Shidong & Contributors
" Author: Wang Shidong < wsdjeg at 163.com >
" URL: https://spacevim.org
" License: GPLv3
"=============================================================================


" SpaceVim Options: {{{
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
" }}}

" SpaceVim Layers: {{{
  call SpaceVim#layers#load('lang#typescipt')
" }}}
```

6. exit vim `:q`
7. `vim` (open vim from terminal)
8. after open - left panel appeared showing plugins installation progress
9. after installation success - I've closed vim again `:q`
10.  `vim` (open vim from terminal)
11.  run `:SPUpdate`
12. after installation success - I've closed vim again `:q`
13. `touch test.ts`
14. `vim test.ts`

at this point vim still recognizes `*.ts` file as `xml`. The sam way as I showed [here](https://github.com/SpaceVim/SpaceVim/issues/1501#issuecomment-375644152)

So, do you think this is still problem in configuration?

**Comment by wsdjeg** [comment]
But I do not know why it works well for me:

https://asciinema.org/a/Ay6nI2KmunShgsBCIo0ATCsTX

**Comment by y9c** [comment]
@kopach 

- open a new file with extension `.ts`
- run `:set ft=typescript` in command mode.
- write something your like in the file.
- then, run `:call SpaceVim#layers#load('lang#typescipt')` in command mode.
- exit and reopen the file.

**Comment by wsdjeg** [comment]
```
:verbose autocmd BufRead *.ts                                                                                                                          
--- Auto-Commands ---                                                                                                                                  
filetypedetect  BufReadPost                                                                                                                            
    *.ts      setf xml                                                                                                                                 
        Last set from /usr/local/share/nvim/runtime/filetype.vim                                                                                       
    *.ts      set filetype=typescript                                                                                                                  
        Last set from ~/.cache/vimfiles/.cache/init.vim/.dein/ftdetect/ftdetect.vim 
```

**Comment by wsdjeg** [comment]
I think it is because your dein do not generate the right ftdetect.vim.
for me, you can see the result of `verbose autocmd BufRead *.ts`.

**Comment by wsdjeg** [comment]
and you should waitting for plugin update done and runtimecache done. you can use `call dein#recacheruntimepath()` to regenerate the cache which include the ftdetect file.

**Comment by kopach** [comment]
Thanks guys for a help. I think key here is NeoVim. I'm using vim v8. 

```
:verbose autocmd BufRead *.ts
--- Auto-Commands ---
filetypedetect  BufRead
    *.ts      setf xml
        Last set from /usr/local/Cellar/vim/8.0.1250/share/vim/vim80/filetype.vim
```

**Comment by y9c** [comment]
The issue template does not help for problem solving. I don't think the author will start a complete new user account with the identical conf file exactly to reproduce the bug.

**Comment by kopach** [comment]
Can we have this issue reopened?

**Comment by kopach** [comment]
I finally managed to make it working. I had to uninstall SpaceVim and remove all the related files. 

- rm -rf .SpaceVim
- rm -rf .cache/SpaceVim
- rm -rf .SpaceVim.d
- `curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall`

Also I've installed NeoVim (which is the key point to have this working).
After all I've installed SpaceVim again (`curl -sLf https://spacevim.org/install.sh | bash`) , added `call SpaceVim#layers#load('lang#typescipt')` into the buffer opened by press `SPC f v d`. Saved, reloaded vim - and got typescript working.

Anyway, I believe this defect with `vim` (not `neovim`) should be fixed. Also it should be possible to get it working by `:SPUpdate` without **force** reinstall everything! So, please, reopen this issue unless this fixed

**Comment by wsdjeg** [comment]
OK, I think the mini vimrc needed for reprodue in vim. this seems issue with dein.vim

and I will try to reproduce it tonight.

cc @Shougo

**Comment by wsdjeg** [comment]
This issue has been fixed, `call dein#recache_runtimepath` only will cache plugins for current program (vim or neovim), so please run `call dein#recacheruntimepath()` again.
