### ISSUE TITLE
Improve the fuzzy finder layers in SpaceVim

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1502]
In SpaceVim, we have `unite`, `denite`, `leaderf`, `ctrlp` and `fzf` layer.
I want to make these layers provide same feature and same key bindings.

User only need to load one of these layers, then will be able to get these
features.

## Key bindings

| Key bindings         | Discription                   |
| -------------------- | ----------------------------- |
| `<Leader> f <space>` | Fuzzy find menu:CustomKeyMaps |
| `<Leader> f e`       | Fuzzy find register           |
| `<Leader> f f`       | Fuzzy find file               |
| `<Leader> f h`       | Fuzzy find history/yank       |
| `<Leader> f j`       | Fuzzy find jump, change       |
| `<Leader> f l`       | Fuzzy find location list      |
| `<Leader> f m`       | Fuzzy find output messages    |
| `<Leader> f o`       | Fuzzy find outline            |
| `<Leader> f q`       | Fuzzy find quick fix          |
| `<Leader> f r`       | Resumes Unite window          |

But in current version of SpaceVim, leaderf/ctrlp and fzf layer has not be finished.

| Feature             | unite   | denite  | leaderf | ctrlp | fzf     | fzy |
| ------------------- | ------- | ------- | ------- | ----- | ------- | ------- |
| menu: CustomKeyMaps | **yes** | **yes**  | no      | no    | no      | |
| register            | **yes** | **yes** | no      | **yes**    | **yes**      | |
| file                | **yes** | **yes** | **yes** | **yes**    | **yes** | |
| yank history        | **yes** | **yes** | no      | no    | **yes** | |
| jump                | **yes** | **yes** | no      | **yes**   | **yes** | |
| location list       | **yes** | **yes** | no      | no    | **yes**      | |
| outline             | **yes** | **yes** | **yes** | **yes**    | **yes**      | |
| message             | **yes** | **yes** | no      | no    | **yes** | |
| quickfix list       | **yes** | **yes** | no      | **yes**    | **yes**      | |
| resume windows      | **yes** | **yes** | no      | no    | no      | |

- [x] denite layer
- [x] unite layer
- [ ] leaderf layer
- [ ] ctrlp layer
- [ ] fzf layer
- [ ] fzy layer

all source marked as `no` will roll back to unite extension.

**Comment by Shougo** [comment]
> resume windows yes | no | no | no | -- | -- | -- | -- | --




denite has resume feature.
Why?

**Comment by wsdjeg** [comment]
Sorry, I do not know how to make it work.

**Comment by wsdjeg** [comment]
Ok, I will reopen this issue and mark it as discussion. Just found many awesome tools.

ref link:

- https://www.reddit.com/r/vim/comments/873dxs/what_fuzzy_find_tool_do_you_use_for_gui_vim/
- https://github.com/mattn/vim-fz
- https://blog.lilydjwg.me/2018/9/16/skim.213485.html
- https://github.com/lotabout/skim

**Comment by wsdjeg** [comment]
I will not add fzy layer, as it can not but used in windows 7. if people find it works well in windows7 PR is welcome.
