### ISSUE TITLE
How to replace statusline with Airline?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [wsdjeg/SpaceVim#1505]
I read through the doc but couple figure out how to replace the default statusline with airline. Could someone point me in the right direction please.

**Comment by wsdjeg** [comment]
Maybe a  new layer airline layer?

**Comment by wsdjeg** [comment]
Add this to your config:

```
call SpaceVim#layers#disable('core#statusline')
call SpaceVim#layers#disable('core#tabline')
```

**Comment by CodeMonkeyKevin** [comment]
thanks mister.
