### ISSUE TITLE
E492: Not an editor command: Denite file_rec

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1513]
today after :SPUpdate, unite and many plugins not work

**Comment by wsdjeg** [comment]
Do you load denite layer. by default it is not loaded.

**Comment by deepseeksss** [comment]
ok. it loaded default before

**Comment by wsdjeg** [comment]
yeah，this is changed. because SpaceVim provide 5 kind fuzzy finder layers.
