### ISSUE TITLE
SpaceVim Crashed!

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#1514]
After run `:SPUpdate` spacevim lost the theme and some plugins.

Removing all user configuration and reinstalling spacevim can't  solve this issue.

**Comment by wsdjeg** [comment]
please use  issue template. I can not understand your issue.

**Comment by y9c** [comment]
SpaceVim 0.7.0 disabled some plugin by default. 

You should enable `colorscheme` layer manually.

https://github.com/SpaceVim/SpaceVim/commit/6feff44a0d4e089e6c4af87eba2055741e9402ba
