### ISSUE TITLE
Documentation Typo 'Separatos'

### ISSUE THREAD

**Issue by jasl8r** [wsdjeg/SpaceVim#1515]
https://github.com/SpaceVim/SpaceVim/blob/e55d6cf27067acce2bf1cf6a98c631f9a6c75b8c/doc/SpaceVim.txt#L208
https://github.com/SpaceVim/SpaceVim/blob/e55d6cf27067acce2bf1cf6a98c631f9a6c75b8c/doc/SpaceVim.cnx#L206
https://github.com/SpaceVim/SpaceVim/blob/f088e5f18bb3816ec8a13391985fb780ebc18bd6/autoload/SpaceVim.vim#L176

Are the cnx files generated, or do all three files need to be updated?

**Comment by wsdjeg** [comment]
yeah, the doc file is generated from vim file. all of them need to be updated. thank for your issue.
