### ISSUE TITLE
SPC ff or ff to find file not working in 0.7.0 release

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [wsdjeg/SpaceVim#1517]
It looks like ff or SPC ff is not working in current head or 0.7.0 release

returns the below error:

> E492: Not an editor command: LeaderfFile .

**Comment by wsdjeg** [comment]
oh, This key binding should be moved to fuzzy finder kayers (unite, denite,fzf, etc.).

I will fix it.

**Comment by lukeberry99** [comment]
Whilst waiting on a fix, what's the solution to still be able to use ff?

**Comment by CodeMonkeyKevin** [comment]
@lukeberry99  CTRL + p

**Comment by wsdjeg** [comment]
change the function of key `f` is not a good idea, we have use cleval-f instead. now you can use `<c-p>` for searching files. and if you load any fuzzy finder layers, you can use `<Leader> + f + stuff` to find anything.

now we have five fuzzy finder layers, see #1502

**Comment by CodeMonkeyKevin** [comment]
I loaded the fzf layer "call SpaceVim#layers#load('fzf')" but doing a "SPC ff" returns this error: 

`E492: Not an editor command: LeaderfFile app/controllers`

**Comment by wsdjeg** [comment]
I have fix this issue, please load one fuzzy finder layer, and have a try with `SPC f f` and `<C-p>`.
