### ISSUE TITLE
split vertically splits NERDTREE instead of opening new vertical split

### ISSUE THREAD

**Issue by s4njee** [wsdjeg/SpaceVim#1518]
Opening a new file with 'sv' from nerdtree should open a split on the left side.

Open a file in vim, open another file using the nerdtree shortcut 'sv'

https://imgur.com/a/5brn0

As you can see, vertical split splits nerdtree instead of splitting the main buffer. Are my settings configured wrong?

**Comment by wsdjeg** [comment]
where do you get this key binding `sv`? in SpaceVim documentation, `sv` is means  `[WIN]v` - vertically split current windows.

**Comment by s4njee** [comment]
http://spacevim.org/documentation/#open-file-with-file-tree

sg and sv are supposed to open a file in a new vertical or horizontal split

sg works, but sv splits the file tree itself instead of the main buffer

**Comment by wsdjeg** [comment]
I Will fix it.

**Comment by wsdjeg** [comment]
@Shougo

I think there is something wrong with `vimfiler#do_action('split')`, in current version fo spacevim I use `sv` to call this action, but it will split window from vimfiler, 
![2018-03-24-20 21 31](https://user-images.githubusercontent.com/13142418/37863944-092eac6e-2f35-11e8-86e6-e02bab8504ea.png)

but I think, maybe after do this action, the windows layout should be:
![2018-03-24-20 22 07](https://user-images.githubusercontent.com/13142418/37863948-1d1374d0-2f35-11e8-9f32-baabe3fcfdc3.png)

**Comment by s4njee** [comment]
Thanks!
