### ISSUE TITLE
How do you create custom key mappings?

### ISSUE THREAD

**Issue by derekchiang** [wsdjeg/SpaceVim#1530]
I'm a little confused as to why the following doesn't work (I'm putting it in `~/.SpaceVim.d/init.vim`:

```
noremap <C-k> <Space>ft
```

My intention is to make it so that pressing `Ctrl+k` does exactly the same thing as pressing `space-f-t`, which opens the file viewer.

**Comment by wsdjeg** [comment]
why do not just using command？

for example：

```
noremap <C-k> :Vimfiler<cr>
```

you are using `noremap` so `<Space>ft` will not open file tree.

maybe you can use:

```
map <c-k> <space>ft
```

**Comment by derekchiang** [comment]
@wsdjeg that worked.  Thanks!
