### ISSUE TITLE
Why's my code collapsing?

### ISSUE THREAD

**Issue by derekchiang** [wsdjeg/SpaceVim#1532]
My JavaScript code is collapsing like this:

![image](https://user-images.githubusercontent.com/1535686/37814648-3ef9d476-2e28-11e8-8391-2aedad3d330b.png)

I couldn't quite figure out which plugin is causing this.  How do I make my code not collapse by default?

**Comment by wsdjeg** [comment]
please read `:h foldenable`, by default vim enable code fold, and if you want to disable fold, you can use `set nofoldenable` or use `modelines`.

just like the end of a vim file, you will see something like

```
" vim:set et sw=2:
```
which means `set et` and `set sw=2` for current buffer.

**Comment by xiuliren** [comment]
can I configure this in the toml file?
I tried `foldenable=false`, but do not work.
