### ISSUE TITLE
install script failed

### ISSUE THREAD

**Issue by tracyone** [wsdjeg/SpaceVim#155]
### Expected behavior, english is recommend

install failed.

### Environment Information
- OS:macOS
- vim version:8.0 1-206
- neovim version:0.2.0

### The reproduce ways from Vim starting (Required!)
```bash
curl -sLf https://spacevim.org/install.sh | bash
fatal: destination path '/Users/tracyone/.SpaceVim' already exists and is not an empty directory.
```

but /Users/tracyone/.SpaceVim is not  exist

**Comment by wsdjeg** [comment]
But I can not reproduce, what is your bash version, and what is your shell?
![2017-01-23_757x135](https://cloud.githubusercontent.com/assets/13142418/22207607/bb784c8c-e1ba-11e6-85cb-3a5ad1d96d79.png)


cc @mhinz

**Comment by tracyone** [comment]
@wsdjeg  **.SpaceVim**，I think this name is the key point of this issue,because this project doesn't use this directory.

**Comment by wsdjeg** [comment]
no, SpaceVim will be clone to `~/.SpaceVim`, and `~/.vim` is just a link to `~/.SpaceVim`.

**Comment by mhinz** [comment]
What's the output of this:

```
$ bash -c 'if [[ -d "$HOME/.SpaceVim" ]]; then echo yay; fi'
```

If it outputs nothing, do `git clone https://github.com/SpaceVim/SpaceVim.git "$HOME/.SpaceVim"` and try again.

**Comment by tracyone** [comment]
@mhinz output is nothing.

I think I have found the problem, `install.sh` is not work in zsh.

**Comment by mhinz** [comment]
Please post the full log. In my case:

```
$ echo $SHELL
/bin/zsh
$ bash -c 'if [[ -d "$HOME/.SpaceVim" ]]; then echo yay; fi'
$ git clone https://github.com/SpaceVim/SpaceVim.git "$HOME/.SpaceVim"
Cloning into '/Users/mhi/.SpaceVim'...
remote: Counting objects: 1430, done.
remote: Total 1430 (delta 0), reused 0 (delta 0), pack-reused 1430
Receiving objects: 100% (1430/1430), 373.12 KiB | 669.00 KiB/s, done.
Resolving deltas: 100% (903/903), done.
$ bash -c 'if [[ -d "$HOME/.SpaceVim" ]]; then echo yay; fi'
yay
```

**Comment by wsdjeg** [comment]
@tracyone BTW, what is `~/.SpaceVim` it your pc? we chech if it is a derectory, we just run git pull, otherwise we clone repo?
you can check it in terminal
```sh
file ~/.SpaceVim
```
