### ISSUE TITLE
More Humanized Error Sign Recommended

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#156]
The default error sign symbol is just a stupid symbol like this `✖ `.

I strongly recommend this symbol: `✗`

**Comment by wsdjeg** [comment]
`✗` looks too strange, it like a italic char, and is not at the middle of the col. I can show you two pics.

**Comment by wsdjeg** [comment]
![2017-01-23-23 32 11](https://cloud.githubusercontent.com/assets/13142418/22213855/ab366898-e1d0-11e6-8fb2-3b75861dd242.png)
![2017-01-23-23 36 01](https://cloud.githubusercontent.com/assets/13142418/22213856/ab399270-e1d0-11e6-9da1-dde74c9193ba.png)

**Comment by Gabirel** [comment]
Actually I don't mind this. This decision depends on you.
