### ISSUE TITLE
Can not install new plugin

### ISSUE THREAD

**Issue by tracyone** [wsdjeg/SpaceVim#157]
### Environment Information
- OS:macOS
- vim version:8.0 1-206
- neovim version:

### The reproduce ways from Vim starting (Required!)
I add a plugin to tools layer ,see ][SpaceVim/layers/tools.vim#L33](https://github.com/tracyone/SpaceVim/blob/dev/autoload/SpaceVim/layers/tools.vim#L33)

```vim
:call dein#install()
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.
```

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

[ SpaceVim ] : logger file /Users/tracyone/.SpaceVim/.SpaceVim.log does not exists!

**Comment by wsdjeg** [comment]
ok, I will fix log, and please update spacevim, and post log.

**Comment by wsdjeg** [comment]
I just fix logger.

**Comment by wsdjeg** [comment]
Now no need call dein#install(), spacevim will do it automatically.

**Comment by wsdjeg** [comment]
new plugin should be autoinstalled, I can not reproduce it in dev branch.

**Comment by tracyone** [comment]
Plugins were installed to ~/.cache/vimfiles/repos/github.com(anything wrong?????)

If I open vim in this directory,some error occur:

Error detected while processing /Users/tracyone/.cache/vimfiles/.cache/vimrc/.dein/plugin/dwm.vim:
line   19:
E117: Unknown function: unite#custom_action

**Comment by tracyone** [comment]
You can not produce my problem because your environment is linux...

macvim crash issue still not be solved...

**Comment by wsdjeg** [comment]
@tracyone yes, for example
`~/.cache/vimfiles/repos/github.com/Shougo/dein.vim`
this is because dein do not only support github.
unknow functinon is due to your unite is not been installed.

**Comment by tracyone** [comment]
unite.vim has been installed.

open vim in other directory,no error occur.

This is a issue of spacevim

**Comment by wsdjeg** [comment]
> macvim crash issue still not be solved...

please open new issue about it, and you should provide the stack.

**Comment by wsdjeg** [comment]
> If I open vim in this directory,some error occur:

ok , I will have a try, what is the reproduce step?

```
cd ~/.cache/vimfiles/repos/github.com
vim or vim foo
```

**Comment by wsdjeg** [comment]
I got it.

**Comment by wsdjeg** [comment]
![2017-01-25_1278x458](https://cloud.githubusercontent.com/assets/13142418/22296390/f5422302-e354-11e6-8094-3fc16793f7b4.png)

**Comment by wsdjeg** [comment]
@Shougo should be issue of dein. rtp is wrong
```
runtimepath=~/.SpaceVim.d,~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,~/.cache/vimfiles/repos/flattened,~/.cache
/vimfiles/repos/vim-openbuf,~/.cache/vimfiles/repos/jellybeans.vim,~/.cache/vimfiles/repos/vim-unite-history,~/.cache/vimfiles/repos/GitHub-api.vim,~/.
cache/vimfiles/repos/unite-gem,~/.cache/vimfiles/repos/unite-haskellimport,~/.cache/vimfiles/repos/unite-remotefile,~/.cache/vimfiles/repos/neosnippet-
snippets,~/.cache/vimfiles/repos/unite-quickfix,~/.cache/vimfiles/repos/unite-rails,~/.cache/vimfiles/repos/vim-rooter,~/.cache/vimfiles/repos/neobundl
e-vim-recipes,~/.cache/vimfiles/repos/oceanic-next,~/.cache/vimfiles/repos/gruvbox,~/.cache/vimfiles/repos/vim-airline,~/.cache/vimfiles/repos/vimproc.
vim,~/.cache/vimfiles/repos/twilight256.vim,~/.cache/vimfiles/repos/yowish.vim,~/.cache/vimfiles/repos/vim-hybrid,~/.cache/vimfiles/repos/dein.vim,~/.c
ache/vimfiles/repos/FlatColor,~/.cache/vimfiles/repos/unite-adb,~/.cache/vimfiles/repos/focuspoint-vim,~/.cache/vimfiles/repos/unite-tag,~/.cache/vimfi
les/repos/unite-locate,~/.cache/vimfiles/repos/vim-unite-svn,~/.cache/vimfiles/repos/indentLine,~/.cache/vimfiles/repos/webapi-vim,~/.cache/vimfiles/re
pos/papercolor-theme,~/.cache/vimfiles/repos/unite-help,~/.cache/vimfiles/repos/vim-hybrid-material,~/.cache/vimfiles/repos/unite-qf,~/.cache/vimfiles/
repos/Apprentice,~/.cache/vimfiles/repos/unite-grails,~/.cache/vimfiles/repos/deoplete-padawan,~/.cache/vimfiles/repos/anderson.vim,~/.cache/vimfiles/r
epos/ctrlp.vim,~/.cache/vimfiles/repos/vim-unite-giti,~/.cache/vimfiles/repos/unite-everything,~/.cache/vimfiles/repos/wombat256.vim,~/.cache/vimfiles/
repos/vim-unite-id,~/.cache/vimfiles/repos/unite-vim_advent-calendar,~/.cache/vimfiles/repos/unite-airline_themes,~/.cache/vimfiles/repos/vim-unite-iss
ue,~/.cache/vimfiles/repos/vim-airline-themes,~/.cache/vimfiles/repos/unite.vim,~/.cache/vimfiles/repos/vim-lucius,~/.cache/vimfiles/repos/gist-vim,~/.
cache/vimfiles/repos/unite-zf,~/.cache/vimfiles/repos/ctrlp-py-matcher,~/.cache/vimfiles/repos/Atom,~/.cache/vimfiles/repos/nerdtree-git-plugin,~/.cach
e/vimfiles/repos/molokayo,~/.cache/vimfiles/repos/deoplete-clang2,~/.cache/vimfiles/repos/vim-unite-ack,~/.cache/vimfiles/repos/vim-addon-mw-utils,~/.c
ache/vimfiles/repos/unite-launch,~/.cache/vimfiles/repos/unite-dwm,~/.cache/vimfiles/repos/neoyank.vim,~/.cache/vimfiles/repos/job.vim,~/.cache/vimfile
s/repos/nerdcommenter,~/.cache/vimfiles/repos/vim-leader-guide,~/.cache/vimfiles/repos/vim-gista-unite,~/.cache/vimfiles/repos/neomru.vim,~/.cache/vimf
iles/repos/vim-unite-cake,~/.cache/vimfiles/repos/vim-scriptease,~/.cache/vimfiles/repos/unite-qflist,~/.cache/vimfiles/repos/unite-mark,~/.cache/vimfi
les/repos/base16-vim,~/.cache/vimfiles/repos/unite-vimpatches,~/.cache/vimfiles/repos/neomake,~/.cache/vimfiles/repos/vim-janah,~/.cache/vimfiles/repos
/unite-outline,~/.cache/vimfiles/repos/vim-scheakur,~/.cache/vimfiles/repos/unite-vim_hacks,~/.cache/vimfiles/repos/vimfiler.vim,~/.cache/vimfiles/repo
s/onedark.vim,~/.cache/vimfiles/repos/unite-ctags,~/.cache/vimfiles/repos/LeaderF,~/.cache/vimfiles/repos/vim-signify,~/.cache/vimfiles/repos/unite-pul
l-request,~/.cache/vimfiles/repos/unite-projects,~/.cache/vimfiles/repos/unite-gtags,~/.cache/vimfiles/repos/Lightning,~/.cache/vimfiles/repos/vim-star
tify,~/.cache/vimfiles/repos/unite-alias,~/.cache/vimfiles/repos/neoformat,~/.cache/vimfiles/repos/vim-surround,~/.cache/vimfiles/repos/unite-font,~/.c
ache/vimfiles/repos/unite-filetype,~/.cache/vimfiles/repos/unite-grep-vcs,~/.cache/vimfiles/repos/unite-sf2,~/.cache/vimfiles/repos/vim-colors-solarize
d,~/.cache/vimfiles/repos/seoul256.vim,~/.cache/vimfiles/repos/vim-searchindex,~/.cache/vimfiles/repos/unite-file-vcs,~/.cache/vimfiles/repos/unite-sto
ck,~/.cache/vimfiles/repos/tagbar,~/.cache/vimfiles/repos/denite.nvim,~/.cache/vimfiles/repos/unite-radio.vim,~/.cache/vimfiles/repos/unite-gist,~/.cac
he/vimfiles/repos/vim-automkdir,~/.cache/vimfiles/repos/vim-multiple-cursors,~/.cache/vimfiles/repos/pyte,~/.cache/vimfiles/repos/vim-fugitive,~/.cache
/vimfiles/repos/vim-ref,~/.cache
```

**Comment by wsdjeg** [comment]
@tracyone I can reproduce it.

I have vim-luacomplete in `~/SpaceVim/vim-luacomplete`

when I open vim in `~`, everytime `dein#check_install()` returen 1, and show me vim-luacomplete has not been installed.

I think it is due to dein can not check install plugin which has a clone in or below current directory.

cc @Shougo

**Comment by Shougo** [comment]
@wsdjeg 
I don't understand the problem.
Please create new issue in dein.vim without spacevim configuration.
I will try it.

**Comment by Shougo** [comment]
If the problem can reproduce without SpaceVim, OK.  It is dein.vim problem.
I will fix it.

**Comment by Shougo** [comment]
> when I open vim in ~, everytime dein#check_install() returen 1, and show me vim-luacomplete has not been installed.

I think your dein configuration is wrong.

> I think it is due to dein can not check install plugin which has a clone in or below current directory.

dein supports local plugin directory.

**Comment by wsdjeg** [comment]
> I think your dein configuration is wrong.

yes, it should be issue with spacevim.

> dein supports local plugin directory.

ok, I should fix it, SpaceVim do not use local plugins, but  SpaceVim's custom plugin should support local plugins.

**Comment by wsdjeg** [comment]
@Shougo I can reproduce it, I will create a new issue.

**Comment by Shougo** [comment]
I have fixed the problem.

**Comment by wsdjeg** [comment]
@Shougo 
Thanks for your work, It works well for me now.
@tracyone 
please update dein and spacevim, Now it should works well.

**Comment by wsdjeg** [comment]
I have test it , it works well. clossing.
