### ISSUE TITLE
iTerm2 transparent not working

### ISSUE THREAD

**Issue by SteamedFish** [wsdjeg/SpaceVim#1571]
## Expected behavior, english is required

I setup transparency in iTerm2 Preferences. I used to get transparency when I open vim in iTerm2, but transparency is gone after commit abef4b78705c778ad20989a2d7a75af8e6f65270

## The reproduce ways from Vim starting (Required!)

* setup transparency in iTerm2 Preferences
* git checkout to 5b41ad5bc37eb9262e5828309046f130ea50230c and transparency works fine
* git checkout to abef4b78705c778ad20989a2d7a75af8e6f65270 and transparency is gone

## Screenshots

* transparency:
    ![](https://steamedfish.org/externalimages/transparency.png)
* no transparency
    ![](https://steamedfish.org/externalimages/notransparency.png)

**Comment by SteamedFish** [comment]
Sorry，I have figured out that this is my own fault. 
There's a setting in iTerm2 "Keep background colors opaque"

**Comment by wsdjeg** [comment]
OK
