### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by imxcai** [wsdjeg/SpaceVim#1574]
之前在 V2EX 上反馈过，有些字体在安装脚本上是无效的地址，如下：
DejaVu Sans Mono Bold Oblique for Powerline.ttf
DejaVu Sans Mono Bold for Powerline.ttf
DejaVu Sans Mono Oblique for Powerline.ttf
DejaVu Sans Mono for Powerline.ttf

**Comment by ghost** [comment]
I am using windows.It said that you can use install.cmd to install the spacevim.Then you open the gvim it will download the plugin automatically.When i run intall.cmd ,it say open gvim it will install.But after i open gvim.It has no reaction。How can i solve the problem?

**Comment by ghost** [comment]
![wenti1](https://user-images.githubusercontent.com/20223381/38084719-8f62c794-3380-11e8-97bd-e32b64cf5c84.PNG)

**Comment by wsdjeg** [comment]
We recommend to use English in github, Chinese in gitee.com/spacevim

**Comment by wsdjeg** [comment]
@weareyoungi Your issue is not same as OP.

**Comment by wsdjeg** [comment]
@imxcai But it works well for me, please post the output of your command, here is link of the first font.

https://github.com/wsdjeg/DotFiles/blob/master/local/share/fonts/DejaVu%20Sans%20Mono%20Bold%20Oblique%20for%20Powerline.ttf
