### ISSUE TITLE
[Feature Suggestion] Glyph-free, simple ASCII theme

### ISSUE THREAD

**Issue by isentropic** [wsdjeg/SpaceVim#1589]
I usually fire up a new system by installing Neovim and SpaceVim, but installing powerline glyphs and patched fonts feel too complicated, as some terminals do not have proper rendering ([example](https://github.com/zeit/hyper/issues/2201)) and some quirky systems like Bash on Windows struggle too. Some people might prefer an old-school looking plain (neo)vim-like interface with additional functions from SpaceVim. It would be very nice to have simple toggle like "set spacevim_enable_simple_theme = 1" that would return both powerline and the tab-bar to a simplistic nature without glyphs.

**Comment by wsdjeg** [comment]
@isentropic one option `spacevim_enable_simple_theme` override all other options is not a good idea, but I think  maybe we should do it in basic mode of SpaceVim. this options can be setted in:

https://github.com/SpaceVim/SpaceVim/blob/master/mode/basic.vim

In basic mode, we assume your terminal do not support truecolors, and you do not have extra fonts installed.

**Comment by isentropic** [comment]
@wsdjeg I have tried basic mode and still think that it keeps some of the glyphs, it feels like it only makes everything 'straight' without angles and powerline delimiters. I'm using bash on windows and still, I see some broken glyphs. It is still a better mode for lesser systems, but having a complete 'back to origins' looking mode would be very nice.

**Comment by wsdjeg** [comment]
Ok, I will improve basic mode.
