### ISSUE TITLE
Ctrl-E does not scroll past the end of the document

### ISSUE THREAD

**Issue by derekchiang** [wsdjeg/SpaceVim#1595]
In normal Vim, `Ctrl+E` scrolls past the end of the document, but it doesn't in SpaceVim.  Is there a way to change this?

**Comment by wsdjeg** [comment]
sorry, I can not understand it, in spacevim, we have changed the behavior, maybe we can recover it in vimcompatible mode, see #1596

**Comment by tracyone** [comment]
@wsdjeg You should have a look at it:https://github.com/tpope/vim-rsi

Every linux user use readline keybinding .

**Comment by wsdjeg** [comment]
in current version of spacevim, ctrl_e works well for scrolls past the end of the document.
