### ISSUE TITLE
Can't change Colorscheme

### ISSUE THREAD

**Issue by spidyshivam** [wsdjeg/SpaceVim#1601]
Hey, i am changing my VIM colorscheme in vimrc in .vim folder in home directory by 
`syntax on `
`colorscheme monokai`
But when i am opening my space vim with a python file it only shows some colors in my file. Like if and else are not highlighting . It was working with default VIM configuration .
I tried many colorschemes but none of them is working . I think i have to do extra configuration .And yes default colorscheme is working fine .
When i am removing these lines
`syntax on `
`colorscheme monokai`
Default color scheme i.e gruvbox is working fine

**Comment by wsdjeg** [comment]
http://spacevim.org/documentation/#colorschemes
http://spacevim.org/layers/colorscheme/

**Comment by spidyshivam** [comment]
this is not working too

**Comment by wsdjeg** [comment]
do you load colorscheme layer?

**Comment by spidyshivam** [comment]
yes, but by this http://spacevim.org/documentation/#colorschemes
, colorscheme is not changing . It remains at default.
And  i saved my colorscheme files in ~/.vim/colors/

**Comment by wsdjeg** [comment]
~/.vim is a link to SpaceVim repo, you should not change things in it.

**Comment by spidyshivam** [comment]
i had just copy my colorschemes in colors folder . And do just as in http://spacevim.org/documentation/#colorschemes

**Comment by spidyshivam** [comment]
oh sorry, i was just doing it in wrong directory

**Comment by spidyshivam** [comment]
yes it works , thanks for answering me
