### ISSUE TITLE
Neovim display issues

### ISSUE THREAD

**Issue by ryanhuang1014** [wsdjeg/SpaceVim#1607]
## The reproduce ways from Vim starting (Required!)

Terminal: Xshell
Server OS: Ubuntu 16.04
Host OS: Win 10
Editor: NeoVim 0.23

I am a newbie to SpaceVim, and I find lots of display errors, including statusline errors on the bottom and top, window display errors, etc. These problems seem to come from the low refresh rate? As I follow the official instruction, It is weird that I come across so many problems.

All the problems are shown in the following screenshots.
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

All information is right.

## Screenshots
![image](https://user-images.githubusercontent.com/7006130/38467224-b2b56636-3b67-11e8-900d-591eb4a3ac90.png)

![image](https://user-images.githubusercontent.com/7006130/38467200-790947e0-3b67-11e8-958b-5bd62ab8e8f2.png)

![image](https://user-images.githubusercontent.com/7006130/38467176-2d37dc64-3b67-11e8-9329-016ffea0441f.png)

![image](https://user-images.githubusercontent.com/7006130/38467233-e1a6313c-3b67-11e8-9a89-259a983f3670.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
how about add `set nolazzyredraw` to your custom config? or run `:redraw!`
