### ISSUE TITLE
Completor requires vim compiled with python or python3 and has features `job`, `timers` and `lambda`

### ISSUE THREAD

**Issue by pablogmorales** [wsdjeg/SpaceVim#1608]
Hello
I was able to install it on my mac, but on centos 7 it does not.

SpaceVim ] [11:27:28] [ Warn ] smart tab in autocomplete layer need patch 7.4.774
Completor requires vim compiled with python or python3 and has features `job`, `timers` and `lambda`

Error detected while processing function <SNR>86_on_install_exit:
line    3:
E716: Key not present in Dictionary: -1
Press ENTER or type command to continue
Error detected while processing function <SNR>86_on_install_exit:
line    3:
E116: Invalid arguments for function <SNR>86_msg_on_install_done
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin..SpaceVim#plugins#manager#install:
line   26:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin:
line    4:
E171: Missing :endif

vim-enhanced-7.4.160-2.el7.x86_64
vim-minimal-7.4.160-2.el7.x86_64
vim-filesystem-7.4.160-2.el7.x86_64
vim-common-7.4.160-2.el7.x86_64

Installed Packages
Name        : python
Arch        : x86_64
Version     : 2.7.5
Release     : 58.el7

CentOS Linux release 7.4.1708 (Core)

ldd /bin/vim
	linux-vdso.so.1 =>  (0x00007fffc1320000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f5a630a5000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f5a62e7d000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f5a62c53000)
	libacl.so.1 => /lib64/libacl.so.1 (0x00007f5a62a4a000)
	libgpm.so.2 => /lib64/libgpm.so.2 (0x00007f5a62842000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5a6263e000)
	libperl.so => /usr/lib64/perl5/CORE/libperl.so (0x00007f5a622b0000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5a62093000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f5a61cd0000)
	/lib64/ld-linux-x86-64.so.2 (0x0000564475282000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f5a61a6e000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007f5a61868000)
	libncurses.so.5 => /lib64/libncurses.so.5 (0x00007f5a61641000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f5a61427000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f5a6120d000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f5a60fd6000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f5a60dd3000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f5a60bcf000)

Any advice on this?

Thanks
Regards

**Comment by Shougo** [comment]
SpaceVim should detect completor.vim environment properly.
