### ISSUE TITLE
 I encountered some problems when using SpaceVim

### ISSUE THREAD

**Issue by jiangbai333** [wsdjeg/SpaceVim#1617]
First of all, sorry, I didn't learn English well. I encountered some problems when using SpaceVim

My system is Centos6.8, and the kernel is:
`Linux localhost 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

vim version: 
```bash
# vim -version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:10:41)
Garbage after option argument: "-version"
More info with: "vim -h"
```

When i start vim：
```bash
# vim
[ SpaceVim ] [17:55:34] [ Warn ] smart tab in autocomplete layer need patch 7.4.774
Press ENTER or type command to continue
```

When i press ENTER and in welcome page, prompt me at the bottom of the window ：
`[vimproc] vimproc's Dll: "/root/.cach... Please read :help vimproc and make it."`

When i execute `:help vimproc`, it tall me 'E149: Sorry, no help for vimproc'

why why why!

**Comment by wsdjeg** [comment]
You need to update vim. your vim is too old.
