### ISSUE TITLE
Leaving vim error

### ISSUE THREAD

**Issue by Aya-Yang** [wsdjeg/SpaceVim#1618]
OS: macos 10.13.3
VIm: vim 8.0

when run :q to leave vim, there will be errors. 
Error info:
Error detected while processing VimLeavePre Auto command for "*";
Unknon function: Spacevim#plugins#manager#terminal

**Comment by wsdjeg** [comment]
This is fixed. please update spacevim.

**Comment by Aya-Yang** [comment]
But I installed by curl -sLf https://spacevim.org/install.sh | bash right now....

**Comment by wsdjeg** [comment]
You need to update spacevim.
