### ISSUE TITLE
什么情况，群怎么解散了？我错过了什么？

### ISSUE THREAD

**Issue by GavinHsueh** [wsdjeg/SpaceVim#1622]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please use issue only for bug report or feature request.
