### ISSUE TITLE
Bug report: vimproc build process completion unknown

### ISSUE THREAD

**Issue by duytrung** [wsdjeg/SpaceVim#1628]
## Expected behavior, english is required
spacevim should finish install vimproc
## The reproduce ways from Vim starting (Required!)
I started install spacevim from scratch. but ended up with vimproc plugin stall
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
no results
## Screenshots
![image](https://user-images.githubusercontent.com/2046672/38797553-01453c22-419e-11e8-87a6-2e74584bc537.png)
The vimproc was just like that for hours
If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by duytrung** [comment]
Here is the debug log:

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'asyncomplete'
g:spacevim_buffer_index_type = 0
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_dein_installed = 1
g:spacevim_denite_leader = '\f'
g:spacevim_disabled_plugins = []
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 0
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '<bf>'
g:spacevim_expand_tab = 1
g:spacevim_error_symbol = '<bf>'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = '<bf>'
g:spacevim_gitcommit_pr_icon = '<bf>'
g:spacevim_github_username = ''
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = '<d8>'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_neobundle_installed = 0
g:spacevim_plugin_bundle_dir = 'C:\Users\310 G1\.cache\vimfiles\'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_max_processes = 16
g:spacevim_plugin_name = 'vim-projectionist'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_unite_leader = '\f'
g:spacevim_version = '0.8.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vim_plug_installed = 0
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '<bf>'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```
### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 800
OS: Windows
[shell, shellcmdflag, shellslash]: ['C:\WINDOWS\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.
Checking +python:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!

```

Press ENTER or type command to continue

**Comment by duytrung** [comment]
Here is another message I tried to run gvim

![image](https://user-images.githubusercontent.com/2046672/38809258-1d6de9c0-41c2-11e8-844c-6d766945b8b7.png)

The user folder name has a "space" in it. Is that the cause of the bug that vim could not load the file.

**Comment by pwood310** [comment]
I am seeing the same 2 issues with Windows 7: the stalled build and also the loadCustomConfig when started from my home directory. 
Same issue if vim 8.0 or with neovim.
I have no problems il with my Mac or with Windows 10, FWIW

**Comment by Yeeyao** [comment]
Try to install MinGW in your windows and set the path of make.exe(under where you install  MinGW) to your environment path of your system.
Then run SPUpdate in your vim.

I try and solve this problem. 

If you don't know how to make it, just download the dll file and put it to the correct path:
https://github.com/Shougo/vimproc.vim/releases

**Comment by wsdjeg** [comment]
To show the build log need rewrite the dein ui and logic, i will implement this feature in v0.9.0 , and also PR is welcome!

**Comment by redcartel** [comment]
Newb question but: I built vimproc independently of SPUpdate. Is there a way I can remove it from SPUpdate's package list so the update doesn't stall?

**Comment by wsdjeg** [comment]
@redcartel in current version we can not do that. But you can disable that plugin, and clone it to your disk, add `set rtp+=path/to/vimproc` to your bootstrap function.

**Comment by EasonTong** [comment]
> Try to install MinGW in your windows and set the path of make.exe(under where you install MinGW) to your environment path of your system.
> Then run SPUpdate in your vim.
> 
> I try and solve this problem.
> 
> If you don't know how to make it, just download the dll file and put it to the correct path:
> https://github.com/Shougo/vimproc.vim/releases

where should I put it in ?

**Comment by wsdjeg** [comment]
I have improve the build function, and on_exit handle will update the page.

**Comment by ghost** [comment]
> > Try to install MinGW in your windows and set the path of make.exe(under where you install MinGW) to your environment path of your system.
> > Then run SPUpdate in your vim.
> > I try and solve this problem.
> > If you don't know how to make it, just download the dll file and put it to the correct path:
> > https://github.com/Shougo/vimproc.vim/releases
> 
> where should I put it in ?

in your \.cache\...\github.com\Shougo\vimproc.vim\lib
