### ISSUE TITLE
Grep in current directory or buffer directory

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#1630]
It's convenient to grep in current directory and grep in the same directory of current file.

**Comment by wsdjeg** [comment]
grep in current dir has already implemented, It is `SPC s /` and `SPC s p` and `SPC s P`, the description said it search in project dir, but it search in current dir.

I will implement new feature about search in buffer directory, the prefix is `d` and `D`. so all key bindings should be : 

- `SPC s d`: search in buffer directory with default searching tool
- `SPC s D`: search cursor word in buffer directory with defailt searhing tool
- `SPC s a d`:  search in buffer directory with ag
- `SPC s a D`: search cursor word in buffer directory with ag
- `SPC s g d`:  search in buffer directory with grep
- `SPC s g D`: search cursor word in buffer directory with grep
- `SPC s k d`:  search in buffer directory with ack
- `SPC s k D`:  search cursor word in buffer directory with ack
- `SPC s r d`:  search in buffer directory with rg
- `SPC s r D`: search cursor word in buffer directory with rg
- `SPC s t d`:  search in buffer directory with pt
- `SPC s t D`: search cursor word in buffer directory with pt
