### ISSUE TITLE
Display current function/tag name in statusline

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#1631]
In vim-airline, if tagbar is enabled, it will display current tag/function name in the statusline using following code:
`tagbar#currenttag('%', '', '')`

It's very useful to have this feature.

**Comment by wsdjeg** [comment]
yeah, This feature is useful, and I will try to implement it

**Comment by wsdjeg** [comment]
hello @thawk where do you want to disply the tag and filename. in current version of spacevim, if we have opened two file with same name, the file path will be displayed on the statusline, and you should see:

```
1 > foo.txt > XXXXXX > XXX> src/wsdjeg/foo.txt                       < unix |  XXXX < XXXXX
```

so where should we displyed the tag name? how about:

```
1 > foo.txt > XXXXXX > XXX> src/wsdjeg/foo.txt             tagname < unix |  XXXX < XXXXX
```

**Comment by thawk** [comment]
Thx @wsdjeg. I think your second picture is what I want.

**Comment by wsdjeg** [comment]
Ok, I will try to add this feature.
