### ISSUE TITLE
Neoformat in conjunction with google-java-format fails...

### ISSUE THREAD

**Issue by ck3mp3r** [wsdjeg/SpaceVim#1633]
Hi,

neoformat within the java layer doesn't behave as expected.

## Expected behavior, english is required
When issuing :Neoformat googlefmt the document should be well formatted.

## The reproduce ways from Vim starting (Required!)
Vanilla SpaceVim installation with java layer activated and the following additional config added as per documentation:
`let g:spacevim_layer_lang_java_formatter = '/usr/local/Cellar/google-java-format/1.5/libexec/google-java-format-1.5-all-deps.jar'
`
## Debug
```
google-java-format /var/folders/bb/hfdh0rjj0dv4njk68m767xsddf1sp0/T/nvimWGHazG/6 
Skipping non-Java file: /var/folders/bb/hfdh0rjj0dv4njk68m767xsddf1sp0/T/nvimWGHazG/6
```
Whereas:
```
cat /var/folders/bb/hfdh0rjj0dv4njk68m767xsddf1sp0/T/nvimWGHazG/6 | google-java-format -
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {
  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

  public String test() {
    return "test";
  }
}
```
## Screenshots
![screen shot 2018-04-18 at 5 05 07 pm](https://user-images.githubusercontent.com/622232/38944022-b4866968-432a-11e8-8e9e-c3b4fa5b3d0f.png)

**Comment by wsdjeg** [comment]
This is a bug of neoformat. the temp file should has same suffix

cc @sbdchd

**Comment by ck3mp3r** [comment]
Here is a fix which works for me in the `~/.SpaceVim/autoload/SpaceVim/layers/lang/java.vim` file. No need to change Neoformat, just the way you tell it to call google-java-format.
```
   let g:neoformat_java_googlefmt = {
        \ 'exe': 'java',
        \ 'args': ['-jar', get(g:,'spacevim_layer_lang_java_formatter', ''), '-'],
        \ 'replace': 0,
        \ 'stdin': 1,
        \ 'no_append': 0,
        \ }

```

**Comment by wsdjeg** [comment]
@shoreflyer yeah, I have fix it just know, but this still a bug of neoformat, when `stdin` is 0, the temp file should has same suffix as origin file.

**Comment by gcorrel** [comment]
> Here is a fix which works for me in the `~/.SpaceVim/autoload/SpaceVim/layers/lang/java.vim` file. No need to change Neoformat, just the way you tell it to call google-java-format.
> 
> ```
>    let g:neoformat_java_googlefmt = {
>         \ 'exe': 'java',
>         \ 'args': ['-jar', get(g:,'spacevim_layer_lang_java_formatter', ''), '-'],
>         \ 'replace': 0,
>         \ 'stdin': 1,
>         \ 'no_append': 0,
>         \ }
> ```

Thanks for that pointer though but I don't seem to have the "/autoload/SpaceVim/layers/lang/java.vim"
After installation of SpaceVim, a quick directory search shows that I've only got the following folders;

/home/wigTel/.SpaceVim/docker/init.toml
/home/wigTel/.SpaceVim/mode/basic.toml
/home/wigTel/.SpaceVim/mode/dark_powered.toml
/home/wigTel/.SpaceVim.d/init.toml
/home/wigTel/.cache/SpaceVim/backup/init.toml~
/home/wigTel/.cache/SpaceVim/undofile/%home%wigTel%.SpaceVim.d%init.toml

Please, how can I go about this to install the Java Plugin?

Thanks in anticipation of your response.

**Comment by gcorrel** [comment]
Basically, how do I create the file you specified so, to insert the line of codes that follows?? Does it require creating manually or there's a certain instruction to go by? Thanks again.
