### ISSUE TITLE
Customizable statusline

### ISSUE THREAD

**Issue by cserb** [wsdjeg/SpaceVim#1635]
I think for everyone different type of information is useful depending on their workflow.
I'd like for example to display the file's parent folder and project folder. Also I don't need to know the file size.

While this is a lot of work to implement a fully customizable statusline why not make it optional so we could use either our own implementations or something like `vim-airline`?

**Comment by nickclasener** [comment]
Now you can use vim-airline.
Restart and you'll be able to use it
```
"=============================================================================
" dark_powered.vim --- Dark powered mode of SpaceVim
" Copyright (c) 2016-2017 Wang Shidong & Contributors
" Author: Wang Shidong < wsdjeg at 163.com >
" URL: https://spacevim.org
" License: GPLv3
"=============================================================================

" SpaceVim Options: {{{
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_automatic_update = 1
let g:spacevim_custom_plugins = [
      \['vim-airline/vim-airline'],
      \ ]
" }}}

" SpaceVim Layers: {{{
" }}}


```

**Comment by cserb** [comment]
@nickclasener how can I call `airline#add_statusline_func` from within `.SpaceVim.d/init.vim`? Adding it like in this example https://github.com/vim-airline/vim-airline#extensible-pipeline is not working: `E117: Unknown function: airline#add_statusline_func`

**Comment by wsdjeg** [comment]
By default spacevim do not load airline, if you want to use, just disabe the build-in statusline and table

```vim
call SpaceVim#layers#disable('core#statusline')
call SpaceVim#layers#disable('core#tabline')
```

and by defult, in spacevim's statusline, if you open two files with same name, the path info will be displayed in statusline, so no need to custom it.

**Comment by wsdjeg** [comment]
for example, if I open two `init.vim` file, so I need to know the path of current one, just check the statusline.

![2018-04-23_1365x76](https://user-images.githubusercontent.com/13142418/39126244-7147ae0a-46c7-11e8-9d9b-78f003026332.png)
