### ISSUE TITLE
cursor jump problem in insert mode when editing CPP

### ISSUE THREAD

**Issue by weijinsong** [wsdjeg/SpaceVim#1639]
when I call a class's function, like this " b.a", the cursor will jump the define of the call, after i write '.'

**Comment by wsdjeg** [comment]
It is known bug of asyncomplete. I can not fix it.

**Comment by weijinsong** [comment]
Thanks for your attention.
Dose asyncomplete mean l install vim incompleted？



发自我的小米手机
在 Wang Shidong <notifications@github.com>，2018年4月20日 下午1:14写道：

It is known bug of asyncomplete. I can not fix it.

**Comment by weijinsong** [comment]
thanks again！
Anyway, I make spacevim work properly.
I recompile vim with python surport and reinstall vim and spacevim, then it works.
I don't know why, but it works



发自我的小米手机
在 Wang Shidong <notifications@github.com>，2018年4月20日 下午1:14写道：

It is known bug of asyncomplete. I can not fix it.
