### ISSUE TITLE
Automic closing of brackets in golang

### ISSUE THREAD

**Issue by phacops** [wsdjeg/SpaceVim#164]
### Expected behavior, english is recommend
I'd like braces and parenthesis to close automatically. It is not the case right now.

### Environment Information
- OS: Linux
- vim version:
- neovim version: 0.1.7

### The reproduce ways from Vim starting (Required!)
Open a file ending in `.go`, try to create a `func main(` and the parenthesis won't close itself.

**Comment by wsdjeg** [comment]
SpaceVim use neosnippet, after complete `main(` is no argv in this func, the parenthesis should be closed by default.

**Comment by wsdjeg** [comment]
but if `main(` is not complete by neocomplete or deoplete, it is what you type into, will not be closed, if you want , you can write snippet for go, read `:h neosnippet`.

**Comment by wsdjeg** [comment]
I think you should use neosnippet,  the more snippets you have, the more happy you will be.
By default when edit a `.go` file, if you want to inset main func, no need type into `func main(`, just type `main<tab>`, main will auto expanded as
```go
func main() {
     _  is the cursor.
}
```
