### ISSUE TITLE
Disable welcome message

### ISSUE THREAD

**Issue by cserb** [wsdjeg/SpaceVim#1640]
Make it possible to disable the welcome message

**Comment by wsdjeg** [comment]
why this feature is needed？

**Comment by cserb** [comment]
It's not really _needed_. I can live with the welcome message, but I don't care for it at all :) e.g. Spacemacs also allows you to turn it off

**Comment by wsdjeg** [comment]
The welcome message is not same as spacemacs(which contains many links to spacemacs info), it just show the recent opened files, and you can reopen them quickly. I do not think we need this option, if you do not like the welcome page, just disable the plugin.

```vim
let g:spacevim_disabled_plugins = ['vim-startify']
```

**Comment by cserb** [comment]
I was actually talking about `core#banner`
I tried to disable it via `call SpaceVim#layers#disable('core#banner')` but it seems to just turn off the random banner... which is something

**Comment by c02y** [comment]
I hate the banner, and the default banner is random, it is even worse.

**Comment by mattmc3** [comment]
Found this issue via Google search. The response thus far is disappointing to say the least. It doesn't seem that much to ask to be able to configure SpaceVim start up to not say "Show Me Your Vim" and "Vim: Bite Me" as the defaults. Seems tone deaf.

Regardless of my opinion on the matter, I was able to solve this by adding this setting:

```vim
" if you want to use startify with no header do this
let g:startify_custom_header = []

" if you want to use startify with the basic SpaceVim header do this
let g:startify_custom_header = g:_spacevim_welcome_banners[0]
```
