### ISSUE TITLE
How do i add a project directory to [SPC] p p

### ISSUE THREAD

**Issue by nickclasener** [wsdjeg/SpaceVim#1644]
When i press `[SPC] p p` The only available option i see is the current directory.
I understand by default spacevim uses Unite as project manager.
The doc's are a bit unclear for me.

If anyone can point me in the right direction it'll be greatly appreciated.

**Comment by wsdjeg** [comment]
If you open a new file in project A, A will be added into the list. so you can not added project manually. 

SpaceVim detect a project via `g:spacevim_project_rooter_patterns`, please read `:h g:spacevim_project_rooter_patterns`
