### ISSUE TITLE
Where are custom plugins installed?

### ISSUE THREAD

**Issue by derekchiang** [wsdjeg/SpaceVim#1646]
Where are custom plugins installed?  I'm trying to modify one of them but I can't find it.

**Comment by crisidev** [comment]
They are in your home, folder is `.cache/vimfiles/repos` 

Usually from there you will find the path of the git repos, usually `github.com/$user/$repo`

**Comment by wsdjeg** [comment]
dein will merge all plugin into one path if it is mergeable. so if you want to modify the custom plugin, please disable merged optinon.

for example:

```vim
let g:spacevim_custom_plugins = [
      \ ['lilydjwg/colorizer', {'merged' : 0}]
      \ ]
```
