### ISSUE TITLE
Top buffer list does not scroll left / right

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1648]
Hello,
I find myself in a bit of struggle when I have a lot of files open in the same vim session.

The buffer bar on the top continues to append files on the right and when there are a lot of them, the one on the left side "disappears" as they get covered by the vim interface.

Is there a way to scroll back and show the file names when they are focused?

**Comment by crisidev** [comment]
I am pretty sure the plugin I was using for buffers before spacevim had this feature: https://github.com/fholgado/minibufexpl.vim

**Comment by wsdjeg** [comment]
The tabline should be improved, and I will look into it. I have find many tabline plugins in github, here is a list of plugin I have found:

- airline's tabline
- minibufexpl - https://github.com/fholgado/minibufexpl.vim
- vim-workspace - https://github.com/bagrat/vim-workspace

**Comment by wsdjeg** [comment]
the tabline may looks like:

```
<- 10 | 1 foo.vim | 2 Foo.java | 3 SpaceVim.vim | 4 javacomplete.vim | 5 util.vim | 13 ->
```

which means there are 10 buffers before foo.vim, and there are 13 buffer after util.vim. when click on `<-` just move forward 1 buffer. 

when create new buffer, it will be appended to end of the buffer list.

**Comment by crisidev** [comment]
Yes, this makes sense. One thing I think is important is that the buffer list should focus should also move accordingly with the focused buffer number.

**Comment by wsdjeg** [comment]
> One thing I think is important is that the buffer list should focus should also move accordingly with the focused buffer number.

I can not understand.

**Comment by crisidev** [comment]
What I mean is that if we I am at buffer 10 and I cannot see buffer 1 and I switch to buffer 1, the bar should move and go back to buffer 1. Does it make sense?

**Comment by wsdjeg** [comment]
move to #1917

**Comment by wsdjeg** [comment]
@crisidev This feature has been implemented.
