### ISSUE TITLE
Documentation missing for gitstatus

### ISSUE THREAD

**Issue by mikepc** [wsdjeg/SpaceVim#1657]
It would be nice to have documentation on how to enable the git status of files in vimfiler. I know it's possible, but I enabled it on my work machine and now at home, I forgot what the global variable name is. The documentation doesn't have it anywhere, I randomly ran across it somewhere, and I'm stumbling through google trying to find it again.

I think it is a pretty common ask and should be made apparent somewhere in the docs.

**Comment by wsdjeg** [comment]
`:h g:spacevim_enable_vimfiler_gitstatus`
