### ISSUE TITLE
 show input menu in status bar

### ISSUE THREAD

**Issue by gstormlee** [wsdjeg/SpaceVim#1658]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Plese do not open issue with title only, and empty issue template, and what is `input menu`?
