### ISSUE TITLE
dein#update error

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#166]
### Expected behavior, english is recommend

dein#update with no errors

### Environment Information
- OS: Ubuntu 16.10
- vim version: 8.0
- neovim version: none

### The reproduce ways from Vim starting (Required!)

call dein#update

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

![image](https://cloud.githubusercontent.com/assets/1751829/22331566/20716e04-e407-11e6-872c-0719ceab6a58.png)

**Comment by wsdjeg** [comment]
It is issue of ycm, in it's help file, there are duplcate tags. you should ask the author of ycm to fix it.
