### ISSUE TITLE
Recent commit in deim.vim renders `sudo vim` unusable

### ISSUE THREAD

**Issue by ricpelo** [wsdjeg/SpaceVim#1660]
## (EDITED to point out the source of the issue)

Bisecting and testing I've found that the issue is introduced by Shougo/dein.vim@ec5a35c. If I use the previous commit, SpaceVim works like a charm with `sudo`.

## Expected behavior, english is required

SpaceVim should works OK with `sudo`.

## Environment Information

- OS: Linux
- vim version: 8.0.1453
- neovim version: -
- SpaceVim version: 0.8.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

`vim hello.txt` works as expected, but `sudo vim hello.txt` gives me the following error message:

```
Error detected while processing function dein#autoload#_on_default_event:
line   12:
E714: List required
E714: List required
Press ENTER or type command to continue
```

After pressing ENTER, Vim opens the file and when I type `i` to go into Insert mode, I get the following error message:

```
plugin : indentLines has not been installed, please use ...ll dein#install(["indentLine"])` to install this plugin,
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_buffer_index_type = 1
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'NeoSolarized'
g:spacevim_colorscheme_bg = 'light'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = [['ryanoasis/vim-devicons']]
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_dein_installed = 1
g:spacevim_denite_leader = '\f'
g:spacevim_disabled_plugins = ['fcitx.vim', 'deoplete']
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 1
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_github_username = ''
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_neobundle_installed = 0
g:spacevim_plugin_bundle_dir = '/home/ricardo/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_max_processes = 16
g:spacevim_plugin_name = 'GitHub-api.vim'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_unite_leader = '\f'
g:spacevim_version = '0.8.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vim_plug_installed = 0
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```

### SpaceVim Health checking :

```
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.
```

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:05:43] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
```

## Screenshots

https://asciinema.org/a/p2HRvtnnvWGKxLvXInLLIOdxl

**Comment by wsdjeg** [comment]
do you run `:call dein#install(["indentLine"])`?

**Comment by ricpelo** [comment]
No, I don't run anything. Just installed SpaceVim.

**Comment by ricpelo** [comment]
I've just updated the issue info and attached an asciinema session.

**Comment by ricpelo** [comment]
`sudo vim` is terribly broken. Every time I press [Tab] key, I get an error. I attach an Asciinema session:

https://asciinema.org/a/ehB4dV3qMyoAUxBwrfwhuyR13

**Comment by wsdjeg** [comment]
sorry, I can not fix it, dein do not support `sudo`. I do not know why dein can not support sudo, does this issue happend with vim-plug?

cc @Shougo

**Comment by ricpelo** [comment]
I don't know. I'm a bare Vim & SpaceVim newbie and I don't know how to handle it nor how to use vim-pug.

Up to now, I used Vim with Vundle plugins and it worked perfectly well with `sudo`.

I use Vim very much for editing system config files in my Ubuntu system, but I can't use SpaceVim to do that.

Do you know any basic way to use SpaceVim for editing system files with `sudo`?

Thank you very much, @wsdjeg .

**Comment by 0x647262** [comment]
fwiw: `sudo -E` will preserve your environment when starting `{,n}vim`.

From `sudo`'s manpage:

```
-E' The -E (preserve environment) option indicates to the security policy that the user wishes to preserve their existing environment variables. The security policy may return an error if the -E option is specified and the user does not have permission to preserve the environment.
```

It looks like some `dein` features are disabled in `sudo` sessions. SpaceVim logs _should_ provide more details.

**Comment by ricpelo** [comment]
@devopsdeluxe Thanks for the info. Unfortunately, it doesn't work either with the `-E` option.

How can I see the SpaceVim logs?

**Comment by ricpelo** [comment]
I get it.

Bisecting and testing I've found that the issue is introduced by Shougo/dein.vim@ec5a35c. If I use the previous commit, SpaceVim works like a charm with `sudo`.

**Comment by ricpelo** [comment]
Another workaround is to change:

https://github.com/SpaceVim/SpaceVim/blob/cd77e665845603043f712022082d26efcd1235c6/autoload/zvim/plug.vim#L142

to:

```viml
call dein#add('Shougo/dein.vim', {'trusted': 1})
```

But I don't know if that could lead to further nasty implications.

**Comment by jetm** [comment]
@ricpelo: A workaround, or how to use SpaceVim or Vim with _sudo,_ is to call Vim as a normal user and save the file with the keybinding `<SPC> f W`. That key combination will call _sudo_ to write the file changes.
I have used Vim that way and it always works fine because I don't have to bother if work with root user or not.

**Comment by ricpelo** [comment]
Thank you very much, @jetm. It's a useful workaround. However, If I want to edit a file which my current, unprivileged user can't read (due to its 600 permissions and owned by root, for example), I MUST open it with `sudo vim` instead of only `vim`, otherwise it opens an empty file. The ability to use `sudo vim` is a must.

**Comment by jetm** [comment]
@ricpelo: oh I see. Meanwhile, you also can use `sudo vim -u NONE` to edit that specific file. It will not load _SpaceVim_ settings or any _vimrc_ settings and you will be able to edit the file without issue.

**Comment by Shougo** [comment]
It is dein.vim's intended behavior.
It is security reason.
In sudo session, plugin  can do anything in root permission.
It is very dangerous.

**Comment by Shougo** [comment]
https://thehackernews.com/2018/03/text-editors-extensibility.html

Please read it.

**Comment by ricpelo** [comment]
@Shougo Thank you very much for the answer.

How can I use `trusted` option with SpaceVim? Is there an easy way to load *all* SpaceVim plugins as 'trusted'?

Thanks again in advance.

**Comment by wsdjeg** [comment]
@ricpelo  No, I do not want to support sudo session, I can not guarantee all the upstream plugins. It is too dangerous. and Plugins can do anything with root permission. Maybe In the feature, SpaceVim would provide a noplugin version, In that version I would support sudo session.

**Comment by wsdjeg** [comment]
But In SpaceVim we already have `sudo` layer, and It is enabled by default, so you can use `:W` command to save file with root permission.

**Comment by ricpelo** [comment]
Thank you very much, @wsdjeg .
