### ISSUE TITLE
Java layer error on opening java file - No Javavi library classes found

### ISSUE THREAD

**Issue by avastmick** [wsdjeg/SpaceVim#1662]
## Expected behaviour
Open java file, no error. Behaviour as per [SpaceVim Layers: lang#java page](https://spacevim.org/layers/lang/java/)

## The reproduce ways from Vim starting (Required!)
Add `java` layer to `~/SpaceVim.d/init.vim`

```
call SpaceVim#layers#load('lang#java')
```

Open a `java` file:

```nvim HelloWorld.java```

## Environment

OS - Arch linux - version: "4.16.4-1-arch"
SpaceVim - `NeoVim`

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

```
$ java -version
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
```

`javac` available on `PATH`

```
$ javac -version
javac 1.8.0_141
```

Maven installed:

```
$ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T03:49:05+08:00)
Maven home: /home/avastmick/.asdf/installs/maven/3.5.3
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: /home/avastmick/.asdf/installs/java/8.141/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.16.4-1-arch", arch: "amd64", family: "unix"
```
## Debug info
```
Error detected while processing function <SNR>213_JobNeoVimResponseHandler[3]..javacomplete#server#CompilationJobHandler:                                 
line   10:
javac: invalid target release: 1.8 
```
## Screenshots
![spacevim-java-open](https://user-images.githubusercontent.com/16931995/39345059-f0e550dc-4a18-11e8-865c-5b69575ed5b7.png)

![spacevim-java-error](https://user-images.githubusercontent.com/16931995/39344730-bf9c34b6-4a16-11e8-90d0-17710a15673f.png)

**Comment by avastmick** [comment]
Ok. I looked into this more and it's an issue with `vim-javacomplete2`

So I looked for other issues with that plugin (all are old...) see [https://github.com/artur-shaik/vim-javacomplete2/issues/220](https://github.com/artur-shaik/vim-javacomplete2/issues/220). I followed the instructions.

```
$ cd ~/.cache/vimfiles/repos/github.com/artur-shaik/vim-javacomplete2/libs/javavi
$ mvn compile
```
The startup errors are no longer present, **but** now I get for any attempted completions, or use of `F4`

```
"HelloWorld.java" 6L, 175C                                                                                                                                
could not open socket, try again
could not open socket, try again
could not open socket, try again
could not open socket, try again
could not open socket, try again
could not open socket, try again
could not open socket, try again
could not open socket, try again
Press ENTER or type command to continue
```
Stuck now as there is an open issue on the plugin [https://github.com/artur-shaik/vim-javacomplete2/issues/328](https://github.com/artur-shaik/vim-javacomplete2/issues/328) :frowning_face:

**Comment by wsdjeg** [comment]
@avastmick Thanks let's move to jc2 issue tracker.
