### ISSUE TITLE
Support projective search

### ISSUE THREAD

**Issue by meijieru** [wsdjeg/SpaceVim#1663]
[FlyGrep.vim](https://github.com/wsdjeg/FlyGrep.vim) should support in the entire project instead only currernt dir.

**Comment by wsdjeg** [comment]
ok，I will improve the implement of flygrep.

**Comment by meijieru** [comment]
Nice work, thanks. But why could not issues be open there?

**Comment by wsdjeg** [comment]
what kind issue? if it is issue with upstream plugin, we recommand to use plugin's issue tracker.

**Comment by meijieru** [comment]
Issues could not be proposed in [FlyGrep.vim](https://github.com/wsdjeg/FlyGrep.vim)

**Comment by wsdjeg** [comment]
in spacevim, the build-in plugin flygrep is not same as  https://github.com/wsdjeg/FlyGrep.vim

to support projective search, we need to improve the code in spacevim.

**Comment by meijieru** [comment]
Yeah, as it is a stand-alone plugin, it should have its own issue trackers while it not now.

**Comment by wsdjeg** [comment]
This issue have been fixed, and you can use `SPC s p` and `SPC s P` for searching in project. and `SPC s /` searching current directory.

**Comment by meijieru** [comment]
Thanks
