### ISSUE TITLE
Installation failed on windows10

### ISSUE THREAD

**Issue by TillLindemann** [wsdjeg/SpaceVim#1672]
os system: windows10

installation: install.cmd

problem: keep crushing whenever I double click or run as administrater the install.cmd. A window just flashed through,nothing happened, open gvim,nothing changed.

**Comment by wsdjeg** [comment]
please load log info, or screen short, I can not debug it.

**Comment by PeteW** [comment]
@TillLindemann  take a look at issue #1606 which might be similar? If so @miurahur was able to find a workaround.
