### ISSUE TITLE
SpaceVim does not load successful while startup on windows.

### ISSUE THREAD

**Issue by waderchan** [wsdjeg/SpaceVim#1675]
## Expected behavior

After gVim/Neovim startup, SpaceVim was loaded successfully.

## The reproduce ways from Vim starting

After updated the lasted version of SpaceVim, start gVim/Neovim.

## Debug info

Startup failed, so there was no debug info.

## Screenshots
![spacevim_startup](https://user-images.githubusercontent.com/470374/39457188-98d8be70-4d1e-11e8-9556-7b52f3837e65.PNG)

**Comment by wsdjeg** [comment]
you can have a try with this patch, and post the message here:

```diff
diff --git a/autoload/SpaceVim.vim b/autoload/SpaceVim.vim
index dbdf21f9..a01737a8 100644
--- a/autoload/SpaceVim.vim
+++ b/autoload/SpaceVim.vim
@@ -570,7 +570,11 @@ function! SpaceVim#end() abort
     let g:spacevim_windows_leader = ''
     let g:spacevim_windows_smartclose = 0
   endif
-  call SpaceVim#server#connect()
+  try
+    call SpaceVim#server#connect()
+  catch
+    echom &rtp 
+  endtry
 
   if g:spacevim_enable_neocomplcache
     let g:spacevim_autocomplete_method = 'neocomplcache'
```

**Comment by waderchan** [comment]
I do not know how to make the patch take effect, can you help?

**Comment by zgpio** [comment]
When I start gvim from my home directory，it works. But when I start gvim from other directory, I get Message of E117: Unknown function: SpaceVim#server#connect. When I delete the line `call SpaceVim#custom#load()` in `config\main.vim` file, I can start gvim from other directory.

**Comment by deepseeksss** [comment]
C:\Users\Matrix\AppData\Local\nvim\after
Error detected while processing function SpaceVim#end:
line   23:
E117: Unknown function: SpaceVim#server#export_server
Press ENTER or type command to continue

**Comment by taosean** [comment]
I have the same kind of issues. After installing gVim, I installed SpaceVim as described [here](http://spacevim.org/quick-start-guide/#windows). Then I reopened the gVim icon on my desktop. It automatically started to install some plugins (53 plugins in total), however, it never completed. one of the plugins was always building and never finished. I searched  and found it was compiling vimproc.dll  file.(Maybe not?) So I downloaded a vimproc.dll file [here](https://github.com/Shougo/vimproc.vim/releases), and put it under `~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim/lib/`. After all these steps, I still get the following error.
<img width="424" alt="default" src="https://user-images.githubusercontent.com/17960909/39802214-12e3d98e-53a0-11e8-8b10-da3330b2546c.PNG">

**Comment by wsdjeg** [comment]
Please have a try with #1700
