### ISSUE TITLE
run spacevim, hit space,then error occured

### ISSUE THREAD

**Issue by tianxiayu007** [wsdjeg/SpaceVim#1679]
as the gif show belows:
![space_error](https://user-images.githubusercontent.com/3746672/39467895-fa0f589a-4d62-11e8-9019-40f405faecb1.gif)

**Comment by wsdjeg** [comment]
your vim is too old, `matchaddpos` was added in vim 7.4.330, but This  should be fix in spacevim. I will try to improve it.
