### ISSUE TITLE
After adding dart layer, code completion not work

### ISSUE THREAD

**Issue by jonahfang** [wsdjeg/SpaceVim#1683]
## Expected behavior, english is required
After adding dart layer, code completion should work.

## The reproduce ways from Vim starting (Required!)
I use MacBookPro MacOS 10.13.x, and Dart VM version: 2.0.0-dev.48.0.
1.Use git to clone SpaceVim into `~/.config/nvim`.
2.Use NVIM v0.2.2 with empty `~/.SpaceVim.d` fold.
3.Add dart layer to auto created `~/SpaceVim.d/init.toml`.
4.Restart NVIM.

I tested the dart layer feature, the result is:
- code formatting ok
- code runner ok

**Comment by wsdjeg** [comment]
Please read dart layer doc, and you need to install dart sdk
