### ISSUE TITLE
Add support of closing tag automatically in HTML and XML

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#169]
### Expected behavior
Closing tag automatically is expected.

For example:
After I finish this:
![image](https://cloud.githubusercontent.com/assets/12933851/22378995/14605186-e47d-11e6-9130-b71496208eb2.png)

I expect Vim could close it for me intelligently instead of wasting time to close it manually. For example:
![image](https://cloud.githubusercontent.com/assets/12933851/22379056/5ed08fce-e47d-11e6-97ba-545e927cd045.png)

> Notice: The tag should be closed without human being, and also vim goes into `insert` mode. Just like the picture above.

Of course, it should meet all demands' of XML-file, not just HTML file but also PHP file. 

Yeah, you know, sometimes you have to write some HTML codes in PHP file.

**Comment by wsdjeg** [comment]
@Gabirel SpaceVim has too many plugins for html etc, 
for example, if you want to close `<html>`, no need insert `<html>`, just insert `html` and type `<tab>` to expand the tag.

**Comment by Gabirel** [comment]
What about the XML-autocompletion? I do reproduce that in HTML. How about XML?

**Comment by wsdjeg** [comment]
Autocompletion? Or snippet? Neosnippet works well in xml file, maybe you should write a your own   snippet.

**Comment by wsdjeg** [comment]
OK , I think I should add document about custom snippet.

**Comment by Gabirel** [comment]
In XML, you could use custom snippet to finish this job? I don't think so according to features of XML documents.

**Comment by wsdjeg** [comment]
XML has omni complete , but need config as I know. Will look into it later.

**Comment by wsdjeg** [comment]
I just add link for neosnippet's help. I think you can add custom snippet, BTW, omnifunc works well for me, you can see the pic shown in #185

**Comment by Gabirel** [comment]
1. My `.local.vim`:
![image](https://cloud.githubusercontent.com/assets/12933851/22471219/5b863fea-e797-11e6-95ab-a4d81fd62778.png)

omnifunc does works for me very well.

That is not only I want.(HTML works for me well.)

2. I've already done `git pull`

For example:
![image](https://cloud.githubusercontent.com/assets/12933851/22471320/9dae0c0e-e797-11e6-9a75-5a6d107be88f.png)
 
> after finishing typing `>` or something else, I need him to help me finish this:

![image](https://cloud.githubusercontent.com/assets/12933851/22471504/23aac4f0-e798-11e6-898f-62e82c508381.png)

3. No, you can't customize our own code snippets because you won't know the structure before you starting your project. The elements of XML files are totally random. So you can't do that.

**Comment by wsdjeg** [comment]
have you read the layer doc? I just update it, you should read the omnifunc's document in `/usr/local/share/nvim/runtime/autoload/xmlcomplete.vim`, xml's omni func need create connection. so you should run a func, for example :`call  xmlcomplete#CreateConnection('xhtml10s')`.

**Comment by Gabirel** [comment]
I'm sorry, I don't have much patience to read that `xmlcomplete.vim`. Too complicated for me.

I can't edit XML freely with SpaceVim even if I do `call xmlcomplete#CreateConnection('xhtml10s')`
The result is still the same as I mentioned before.

**Comment by wsdjeg** [comment]
1. open an xml file, and `:echo &omnifunc` what is the result?
2. `call xmlcomplete#CreateConnection('xhtml10s')`, then type into `<body `, type `<c-x><c-o>`,what is shown?

**Comment by Gabirel** [comment]
1. `:echo &omnifunc` ==> `xmlcomplete#CompleteTags`

2. result:
![image](https://cloud.githubusercontent.com/assets/12933851/22472477/5ccef122-e79b-11e6-99f1-e5fbf9293f19.png)

3. Another example:
![image](https://cloud.githubusercontent.com/assets/12933851/22472534/8e13dd60-e79b-11e6-8515-f77977daf4a6.png)

Yes, according to this 'way', this works. But I want more. It's too ill-advised to finish this kind of job. I have to finish this feature with `SIX` keystrokes. If I were you, I wouldn't choose vim to edit XML file just like this.

I used to use my own vimrc. I've been using one of best xml viml. I could get whole things done after typing  just a `>` instead of `SIX` keystrokes.

**Comment by wsdjeg** [comment]
So what is the plugin are you using?

**Comment by Gabirel** [comment]
I've been using this(I don't remember whether I modified this file):
```viml
" File:         HTML AutoCloseTag.vim
" Author:       Michael Sanders (msanders42 [at] gmail [dot] com)
" Last Updated: April 7 2009
" Version:      0.3
" Description:  Automatically closes HTML tag once you finish typing it with >

if exists('b:mapped_auto_closetag') || &cp | finish | endif
let b:mapped_auto_closetag = 1

ino <buffer> <silent> < <><left>
ino <buffer> <silent> > <c-r>=<SID>CloseTag()<cr>
ino <buffer> <expr> <cr> <SID>Return()

if exists('s:did_auto_closetag') | finish | endif
let s:did_auto_closetag = 1

" Gets the current HTML tag by the cursor.
fun s:GetCurrentTag()
	return matchstr(matchstr(getline('.'),
						\ '<\zs\(\w\|=\| \|''\|"\)*>\%'.col('.').'c'), '^\a*')
endf

" Cleanly return after autocompleting an html/xml tag.
fun s:Return()
	let tag = s:GetCurrentTag()
	return tag != '' && match(getline('.'), '</'.tag.'>') > -1 ?
				\ "\<cr>\<cr>\<up>" : "\<cr>"
endf

fun s:InComment()
	return stridx(synIDattr(synID(line('.'), col('.')-1, 0), 'name'), 'omment') != -1
endf

" Counts occurance of needle in page, when not in a comment.
fun s:CountInPage(needle)
	let pos = [line('.'), col('.')]
	call cursor(1, 1)
	let counter = search(a:needle, 'Wc')
	while search(a:needle, 'W')
		if !s:InComment() | let counter += 1 | endif
	endw
	call cursor(pos)
	return counter
endf

" Returns whether a closing tag has already been inserted.
fun s:ClosingTag(tag)
	return s:CountInPage('\c<'.a:tag.'.\{-}>') <= s:CountInPage('\c</'.a:tag.'>')
endf

" Automatically inserts closing tag after starting tag is typed
fun s:CloseTag()
	let line = getline('.')
	let col = col('.')
	if line[col-1] != '>' | return '>' | endif
	let col += 1
	call cursor(0, col)
	" Don't autocomplete next to a word or another tag or if inside comment
	if line[col] !~ '\w\|<\|>' && !s:InComment()
		let tag = s:GetCurrentTag()
		" Insert closing tag if tag is not self-closing and has not already
		" been closed
		if tag != '' && tag !~ '\vimg|input|link|meta|br|hr|area|base|param|dd|dt'
					\ && !s:ClosingTag(tag)
			let line = substitute(line, '\%'.col.'c', '</'.escape(tag, '/').'>', '')
			call setline('.', line)
			call cursor(0, col)
		endif
	endif
	return ''
endf

set tabstop=4  
set shiftwidth=4  
" vim:noet:sw=4:ts=4:ft=vim
```

**Comment by wsdjeg** [comment]
@Gabirel I have fix it.

**Comment by Gabirel** [comment]
I don't know how it works for me still.

**Comment by wsdjeg** [comment]
@Gabirel just en a xml file ,insert `<sss`, then if you insert `>`, you will get `<sss></sss>`

**Comment by Gabirel** [comment]
Fine, I got it.

I think you can make it more perfet. 
It do save a lot of time for me.
Like this:

![image](https://cloud.githubusercontent.com/assets/12933851/22502079/6ab59c9e-e8a6-11e6-8fcb-50a15036daff.png)


But I hope it could be like this:
![image](https://cloud.githubusercontent.com/assets/12933851/22502102/7dc9e560-e8a6-11e6-934e-00225c04b902.png)

There's difference between the one above and the other one below.

**Comment by wsdjeg** [comment]
~~I do not recommand add an empty line when close tag, not all user need this feature, But I can improve `<Cr>`, when you type `<cr>` in picture one, you will get picture two.~~

EDITE: IF you want to a new line, you should type `>` twice.

**Comment by Gabirel** [comment]
Why I can't reproduce auto-completion at my the other laptop? `.local.vim` has same content. I can't understand. Firstly I thought maybe I messed up the `.SpaceVim` folder, so I re-cloned it again. Still, no way to close tags automatically.

`.local.vim`:
```viml
let g:spacevim_colorscheme='molokai'
let g:spacevim_max_column=80
let g:spacevim_error_symbol='✗'
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#xml')
```

**Comment by Gabirel** [comment]
Thanks for work. It been work for me very well. I know where it goes wrong.

My own `/etc/vimrc` stops `imap >` working.

Double `>` works for me very well. Thanks very much.

**Comment by wsdjeg** [comment]
Well, nice to hear that.

**Comment by Gabirel** [comment]
But I still insist that `<CR>` should be inserted automatically. No one would put tags in one line.

I hope you could add this special trick into your document in case nobody won't know about how to insert it.

**Comment by wsdjeg** [comment]
sometimes when edit html file , I do not want the new empty line be inserted automatically, when I write tables, I hope all items in a line.

**Comment by Gabirel** [comment]
Yes, I understand that. So, let's make it unchanged
