### ISSUE TITLE
uninstall does not remove every spacevim things

### ISSUE THREAD

**Issue by JimJeon** [wsdjeg/SpaceVim#1691]
When I run uninstall script to remove SpaceVim, it says uninstalled.
But I checked my directory, and found .SpaceVim and .SpaceVim.d.
So I go to .cache/vimfiles directory which stores add-ons for SpaceVim, I guess.
And there were add-ons which are not deleted.

```
$ curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
Trying to uninstall SpaceVim
Uninstall SpaceVim for vim
```

I was able to delete .SpaceVim and .SpaceVim.d manually. But I don't know how to do with .cache directory. I hope that uninstall script deletes every SpaceVim features, so that user just don't care.

**Comment by wsdjeg** [comment]
no，the cache dir can be changed in config file. so the I can not add this feature
