### ISSUE TITLE
How can I add GoReferrers to language specification key binding?

### ISSUE THREAD

**Issue by YueHonghui** [wsdjeg/SpaceVim#1695]
Feature Request:
I find language specification key binding of golang lacks `GoReferrers` which from vim go. Expected to see GoReferrers when typing `SPC l` with Golang project.

**Comment by wsdjeg** [comment]
@YueHonghui  sorry for late reply, which key bindings do you prefer? before implement this feature, I need to tell you SpaceVim has already implement a tags layer, in that layer we can use `SPC m g r` to find all references. you can checkout our tags layer doc.

https://spacevim.org/layers/tags/

**Comment by wsdjeg** [comment]
@YueHonghui This key binding has been added.
