### ISSUE TITLE
custom config 无法生效

### ISSUE THREAD

**Issue by AlphaLiu** [wsdjeg/SpaceVim#17]
一些overwrite的设置，放在.local.vim里面无法生效，经查是这些设置在其他config已经被定义了，而那些config又比custom config晚加载。建议修改一下这种加载顺序，custom应该最晚加载才好。

**Comment by wsdjeg** [comment]
确实是这样的，我来修复下，你说的是 类似 `set options`  这样的？

**Comment by AlphaLiu** [comment]
是的，我想set tabstop之类的，但是没法成功

**Comment by wsdjeg** [comment]
其实 这是一个非常困难的事情， spcevim 的 一个 option 来设置 是否启动number， 他因该是先载入用户设置， 再去执行set语句， 如果 先执行了set语句，那么载入用户设置后，再执行一次？

**Comment by wsdjeg** [comment]
你可以看 这一文件， https://github.com/SpaceVim/SpaceVim/blob/dev/config/general.vim， 这文件实在 载入用户设置后再载入的， 里面需要采集用户设置。

**Comment by AlphaLiu** [comment]
README里面关于.local.vim，有一行

> " anything defined here are simply overrides
> set wildignore+=\*/node_modules/\*
> set guifont=Wingdings:h10


事实上guifont就没法被override，所以才有后来#12的fix。
只不过难道每个option你都要额外提供一个变量吗?太麻烦

**Comment by wsdjeg** [comment]
确实不是非常好的方式，我觉得应该采用dein的原理 用 hooks， 读取用户配置，后 在合适的时间进行设置，而不是直接设置。我会尽快修复这个问题，并更改readme
