### ISSUE TITLE
How to set mapleader

### ISSUE THREAD

**Issue by onerciller** [wsdjeg/SpaceVim#170]
how to set mapleader in .local.vim I tried it but it doesn't work . how can I do this ?

**Comment by wsdjeg** [comment]
add something like `let mapleader = ';'`  to `~/.SpaceVim.d/init.vim`. this setting is for `<leader>`,  SpaceVim also support widnows mapping leader, and unite leader, please read `:h g:spacevim_windows_leader`, and `:h g:spacevim_unite_leader`.

**Comment by onerciller** [comment]
thanks for your help
