### ISSUE TITLE
en_US.UTF-8 should be used instead of en_US.utf8

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#1702]
## Expected behavior, english is required

en_US.UTF-8 should be choosed for default.  en_US.utf8 may failed at some environment, e.g. Termux at Android.

## The reproduce ways from Vim starting (Required!)

In Termux terminal, error occurs when Vim is started: Can not set language to en_US.utf8.  E197 is raised when executing :lang en_US.utf8.

It's successfully to use en_US.UTF-8.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

- OS： Linux
- vim version: 8.0.1750
- SpaceVim version: 0.8.0-dev

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
More discussions are needed for language setting. As I know, in archlinux, It works well.

**Comment by thawk** [comment]
Yes, but en_US.UTF-8 works well too :smile:

**Comment by wsdjeg** [comment]
OK，thanks，I will have a try.
