### ISSUE TITLE
vimproc win32_dll not found

### ISSUE THREAD

**Issue by onerciller** [wsdjeg/SpaceVim#171]
every time when I open vim, I am getting error "vimproc_win32.dll not found".what is this exactly ?  I've tried disable to vimproc in .local.vim but I cannot it. how can i solve it ?
os : windows
vim version : 8.0

**Comment by wsdjeg** [comment]
@onerciller thanks for feedback, some old plugin need install `shougo/vimproc.vim`, but this plugin need compile, if you can not compile it, you should down load the dll from
https://github.com/Shougo/vimproc.vim/releases,

check your os, if it is 32 bit, download win32_dll, and put it into
`~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim/lib/`

**Comment by onerciller** [comment]
thank you

**Comment by wsdjeg** [comment]
welcome

**Comment by Rom1deTroyes** [comment]
For posterity, you may haave to rename it vimproc_cygwin.dll if you are using spacevim in GitBash.

**Comment by ghost** [comment]
> @onerciller thanks for feedback, some old plugin need install `shougo/vimproc.vim`, but this plugin need compile, if you can not compile it, you should down load the dll from
> https://github.com/Shougo/vimproc.vim/releases,
> 
> check your os, if it is 32 bit, download win32_dll, and put it into
> `~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim/lib/`

so I don't need to download gcc and friends using cygwin or mingw?
