### ISSUE TITLE
Yank and P not pasting from clipboard

### ISSUE THREAD

**Issue by hansbonini** [wsdjeg/SpaceVim#1716]
## Expected behavior, english is required
" + P = Paste from clipboard
## The reproduce ways from Vim starting (Required!)
V for enter in visual mode, Leader "\\" key pressed and the option menu open and when i select p for yank paste, nothing happens.
I'm using xterm as terminal,

**Comment by wsdjeg** [comment]
if you press `\p` quickly, and the menu will not be opened, then does it works?

**Comment by wsdjeg** [comment]
I can not reproduce it, you can have a try with `"+P`, if it does not work, you need to recompile your vim with `+clipboard` feature.

**Comment by hansbonini** [comment]
Nops, when i press ```\p``` quickly nothing happens...
pressing only ```\``` menu opens but if i try to choose ```p``` option... nothing happens too!

Checking my vim with ```vim --version | grep clipboard``` flag was set as ```-clipboard```
Vim recompiled with +clipboard flag and working flawness, thank u for the tip!
