### ISSUE TITLE
Permission denied when installing.

### ISSUE THREAD

**Issue by Le0000000000n** [wsdjeg/SpaceVim#1720]
Here is the outcomes.

Leons-MacBook-Pro:~ leon$ sudo curl -sLf https://spacevim.org/install.sh | bash
        /######                                     /##    /##/##             
       /##__  ##                                   | ##   | #|__/             
      | ##  \__/ /######  /######  /####### /######| ##   | ##/##/######/#### 
      |  ###### /##__  ##|____  ##/##_____//##__  #|  ## / ##| #| ##_  ##_  ##
       \____  #| ##  \ ## /######| ##     | ########\  ## ##/| #| ## \ ## \ ##
       /##  \ #| ##  | ##/##__  #| ##     | ##_____/ \  ###/ | #| ## | ## | ##
      |  ######| #######|  ######|  ######|  #######  \  #/  | #| ## | ## | ##
       \______/| ##____/ \_______/\_______/\_______/   \_/   |__|__/ |__/ |__/
               | ##                                                           
               | ##                                                           
               |__/                                                           
                      version : 0.8.0-dev       by : spacevim.org             
[➭] Trying to clone SpaceVim
fatal: could not create work tree dir '/Users/leon/.SpaceVim': Permission denied
[✔] Successfully clone SpaceVim
mv: rename /Users/leon/.vimrc to /Users/leon/.vimrc_back: Permission denied
[✔] Backup /Users/leon/.vimrc to /Users/leon/.vimrc_back
mv: rename /Users/leon/.vim to /Users/leon/.vim_back: Permission denied
[✔] BackUp /Users/leon/.vim to /Users/leon/.vim_back
ln: /Users/leon/.vim/.SpaceVim: Permission denied
[✔] Installed SpaceVim for vim
ln: /Users/leon/.config/nvim: File exists
[✔] Installed SpaceVim for neovim
[➭] Install dein.vim
fatal: could not create leading directories of '/Users/leon/.cache/vimfiles/repos/github.com/Shougo/dein.vim': Permission denied
[✔] dein.vim installation done
[✔] Downloaded DejaVu Sans Mono Bold Oblique for Powerline.ttf
[✔] Downloaded DejaVu Sans Mono Bold for Powerline.ttf
[✔] Downloaded DejaVu Sans Mono Oblique for Powerline.ttf
[✔] Downloaded DejaVu Sans Mono for Powerline.ttf
[✔] Downloaded DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf
[✔] Downloaded Ubuntu Mono derivative Powerline Nerd Font Complete.ttf
[✔] Downloaded WEBDINGS.TTF
[✔] Downloaded WINGDNG2.ttf
[✔] Downloaded WINGDNG3.ttf
[✔] Downloaded devicons.ttf
[✔] Downloaded mtextra.ttf
[✔] Downloaded symbol.ttf
[✔] Downloaded wingding.ttf
[➭] Updating font cache, please wait ...
[✔] font cache done!

Almost done!
==============================================================================
==    Open Vim or Neovim and it will install the plugins automatically      ==
==============================================================================

That's it. Thanks for installing SpaceVim. Enjoy!

**Comment by wsdjeg** [comment]
Why use sudo!?

**Comment by Le0000000000n** [comment]
I did not use sudo in the first place and got the same problem. So I tried sudo because I thought it was because I did not have the permission to wright under this folder.

**Comment by wsdjeg** [comment]
`'/Users/leon/.cache/vimfiles/repos/github.com/Shougo/dein.vim': Permission denied`

this means you do not has permission with this dir, I can do nothing with it.

**Comment by alexya** [comment]
@Le0000000000n 
I met the same errors as you. how did you resolve it? thx.
