### ISSUE TITLE
Help, SpaceVim update error

### ISSUE THREAD

**Issue by qichaotang** [wsdjeg/SpaceVim#1724]
Hi,
now:
![image](https://user-images.githubusercontent.com/12878507/39987630-e5b1d924-5797-11e8-8608-b23727a1ffc4.png)

before:
![image](https://user-images.githubusercontent.com/12878507/39987612-da173b7c-5797-11e8-8a22-94fcaf2cb88b.png)

MacOS 10.13.4

What error? What should I to slove this error.
I try to update SpaceVim(by vim , : SPUpdate ), but error,

![image](https://user-images.githubusercontent.com/12878507/39987801-4a621672-5798-11e8-8c86-5ff47c72a77e.png)

**Comment by wsdjeg** [comment]
I can not understand your issue, please use issue template, or reinstall spacevim.

**Comment by qichaotang** [comment]
slove it by xcode-select --install ,mac update system ,generate error
