### ISSUE TITLE
Supports old vim

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1727]
SpaceVim should support:

- [ ]  vim 7.4.052 for ubuntu 14.04
- [ ]  vim 7.4.1689 for ubuntu 16.04

**Comment by NickSiena** [comment]
is there a way you can run the app like windows in Ubuntu in its old version? You might have to uninstall and reinstall an older version.

**Comment by x3rAx** [comment]
@TheMacNerd you are probably looking for a [docker](https://www.docker.com/) container with an Ubuntu 14/16 image.
