### ISSUE TITLE
SpaceVim.org is down

### ISSUE THREAD

**Issue by thedelchop** [wsdjeg/SpaceVim#1728]
## Expected behavior, english is required
Visit SpaceVim.org, see a webpage.

**Comment by wsdjeg** [comment]
Yeah, it is known bug. I will fix it.

**Comment by wsdjeg** [comment]
before it was fixed , you can use https://spacevim.github.io/SpaceVim

**Comment by wsdjeg** [comment]
I have fixed this issue, if you still can not visit our website, please let me know. thank you for you issue.

**Comment by GrayCatCode** [comment]
I just tried visiting the site and it appears to be offline at this point in time:

![image](https://user-images.githubusercontent.com/21042310/56476298-b0aa4700-6463-11e9-803f-603af990a671.png)

Thank you in advance! :smiley_cat:

**Comment by iluu** [comment]
@wsdjeg would you mind taking a look at this issue again. Looks like https://spacevim.org is unavailable atm.

**Comment by wsdjeg** [comment]
It works well for me now.

________________________________
wsdjeg@outlook.com

**Comment by jholt1** [comment]
spacevim.org looks to be down now

**Comment by wsdjeg** [comment]
I know, we just move the domain to cloudflare, it seems need 24 hours.
--------------
wsdjeg

**Comment by wsdjeg** [comment]
This has been fixed.
--------------
wsdjeg
