### ISSUE TITLE
why many plugins are not working ? 

### ISSUE THREAD

**Issue by onerciller** [wsdjeg/SpaceVim#173]
I tried many plugins such us gitgutter, gita, but they did not  work.what could be reason for this ?

**Comment by wsdjeg** [comment]
Does all the plugins have been installed, you can try to run `:call dein#install()` and `:call dein#update()` to install and update all the plugins.

**Comment by onerciller** [comment]
yes I've updated  all plugins like you said,  but for instance, when i try to run Gita plugin with shortcuts(e.g leader gs), it does not work

**Comment by wsdjeg** [comment]
It should be my fault, the Gita is lazy load plugin, and it is lazy loaded on command `Gita`, so mapping will not make this plugin be loaded, I will fix it. sorry.

**Comment by wsdjeg** [comment]
Fixed. it there is any issue, we can reopen it.
