### ISSUE TITLE
how can i use SPCgl instead of $ ?

### ISSUE THREAD

**Issue by seven-linglx** [wsdjeg/SpaceVim#1731]
i had writed this in init.vim:
call SpaceVim#custom#SPCGroupName(['g'], 'CustomGroup')
call SpaceVim#custom#SPC('nnoremap', ['g', 'l'], '$', 'go to end of line', 1)

but it donesn't work...

**Comment by wsdjeg** [comment]
`SPC g` is the prefix for `git/versioncontril` so you can not change it. but you can add a new key bindings `SPC g |` if it does not exist.

**Comment by seven-linglx** [comment]
ok, follow what you said,
' SPC g l ' is not exist
i had writed
call SpaceVim#custom#SPCGroupName(['g'], 'CustomGroup')
call SpaceVim#custom#SPC('nnoremap', ['g', 'l'], '$', 'go to end of line', 1)

when i type ' SPC g l ', it doesn't jump to the end of line what function the '$' has.

**Comment by wsdjeg** [comment]
I have create a PR for this queation, please wait for this PR.
