### ISSUE TITLE
Unification for key notations in documentation

### ISSUE THREAD

**Issue by DrWowa** [wsdjeg/SpaceVim#1732]
I suggest uniform key notations in documentation for more readable and easy to learn key sequences.

Summary:
* use uppercase for keyboard button: `TAB, SPC, DOWN`
* use uppercase in square brackets for rest special keys: `[LEADER], [UNITE], [MOUSE-LEFT], [NUMBER]`
* use space as delimiter for key sequences: `SPC t w, s Q, [LEADER] s g`
* use dash-notation for key combination with mod-key: `<S-TAB>, [LEADER] <C-c>`
* use comma as delimiter for list of sequences: `h, j, k, l`
* use 'or' for alternative sequences: `TAB or <C-j>`

Below more detailed explanation with examples.

Currently, special keys uses capital-case, uppercase, angle brackets, square brackets:
`Tab, Down`
`SPC`
`<space>, <leader>, <Mouse-left>`
`[SPC], [Unite]`
Suggested style: use uppercase for keyboard button and square brackets with uppercase for rest
`TAB, SPC, DOWN`
`[LEADER], [UNITE], [MOUSE-LEFT], [NUMBER]`

Sequences uses spaces, plus-sign, spaceless or mixed style:
`SPC t w`
`s + Q`
`gr`
`<leader> + sg`

Suggested style: use spaces
`SPC t w`
`s Q`
`g r`
`[LEADER] s g`

Key combinations with mod-key uses plus-sign or dash-notation in angle brackets:
`Shift + Tab, <leader> + Ctrl + c`
`<C-k>`
Suggested style: use dash-notation
`<S-TAB>, [LEADER] <C-c>`
`<C-k>` #

**Comment by DrWowa** [comment]
I take this task for myself, not i needed remarks and formal agreement.

**Comment by wsdjeg** [comment]
@DrWowa We should follow the format of vim doc, in `:h index` we can see all the keys.

**Comment by wsdjeg** [comment]
@DrWowa I start a PR about this issue. for keyboard button if it is not abbreviation, I think only the first letter should be uppercase, this is just same as what you will see in vim build-in help file.

**Comment by wsdjeg** [comment]
@DrWowa Hi, after readding the doc of vim, I just list some tips here, what do you think about this?

- use capital case and angle brackets for keyboard button: `<Down>`, `<Up>`
- use uppercase for custom leader: `SPC`, `WIN`, `UNITE`, `DENITE`
- use space as delimiter for key sequences: `SPC t w`, `<Leader> f f`
- use `/` for alternative sequences: `<Tab>` / `<C-n>`

**Comment by wsdjeg** [comment]
Update:

- Use `Ctrl-e` instead of `<C-e>` in documentation, It is easy to be understood.

**Comment by wsdjeg** [comment]
I just merged that pr, but any feedback is welcome in this issue.
