### ISSUE TITLE
language-server-protocol documentation update re use of toml

### ISSUE THREAD

**Issue by ck3mp3r** [wsdjeg/SpaceVim#1734]
Update the [language-server-protocol](https://spacevim.org/layers/language-server-protocol/) page illustrating how to configure using toml.

**Comment by ck3mp3r** [comment]
According to the [toml spec](https://github.com/toml-lang/toml#user-content-keys) this is valid:
```
[[layers]]
name = 'lsp'
filetypes = [ 'javascript' ]
[override_cmd]
javascript = [ 'flow-language-server', '--stdio' ]
```
It still ignores the override command...

**Comment by wsdjeg** [comment]
I have fixed lsp layer document, but I think the doc of all the other layers should also be improved.
