### ISSUE TITLE
.SpaceVim.d/autoload/myspacevim.vim not loaded when starting nvim outside of home directory

### ISSUE THREAD

**Issue by ck3mp3r** [wsdjeg/SpaceVim#1738]
## Expected behavior, english is required
`~/.SpaceVim.d/autoload/myspacevim.vim` should be loaded regardless of which directory I start neovim from.

## The reproduce ways from Vim starting (Required!)
Using a vanilla install of SpaceVim using the curl | bash command as described in the documentation.
```
mkdir ~/.SpaceVim.d/autoload
touch ~/.SpaveVim.d/autoload/myspacevim.vim
```
Edit the new file and enter the following content:
```
function! myspacevim#before() abort
  call SpaceVim#logger#info('myspacevim#before called')
endfunction
```

Also add the following to your `~/.SpaceVim.d/init.toml`
```
...
[options]
   bootstrap_before = "myspacevim#before"
...
```
Start neovim within the ~/ directory and print out the debug info. `:SPDebugInfo!`
You should see "myspacevim#before called" in the log output at the bottom indicating that it worked.
## Debug info
<img width="1406" alt="screen shot 2018-05-22 at 11 42 43" src="https://user-images.githubusercontent.com/622232/40357943-9abb8360-5db5-11e8-92d1-b670d9134389.png">

Now quit neovim and `cd Documents` or any other directory and start neovim again.
## Debug info
<img width="1424" alt="screen shot 2018-05-22 at 11 44 09" src="https://user-images.githubusercontent.com/622232/40357903-7f7237de-5db5-11e8-92ac-5217efa8e497.png">

**Comment by wsdjeg** [comment]
@shoreflyer you should use 

```
touch ~/.SpaceVim.d/autoload/myspacevim.vim
```

instead of 

```
touch ~/.SpaveVim.d/autoload/myspacevim.vim
```
But SpaceVim also has a bug about this feature, and it is fixed in #1741
