### ISSUE TITLE
Can't change spacevim color scheme.

### ISSUE THREAD

**Issue by marcusjwhelan** [wsdjeg/SpaceVim#1745]
## Expected behavior, english is required
Simply try and change color scheme given the directions in the wiki. Tried changing the file
~/.SpaceVim.d/init.toml but nothing happens

## The reproduce ways from Vim starting (Required!)

```
nvim "any file" 
```
No color changes will show up

**Comment by wsdjeg** [comment]
The doc about changing colorscheme should be updated, I will fix it.

**Comment by wsdjeg** [comment]
please read colorscheme layer doc

**Comment by marcusjwhelan** [comment]
@wsdjeg  I think you should post somewhere about how to get new color schemes. Since there is nothing about that. I had to find the answer in a closed issue in a random colorscheme to figure it out. 

Install the color scheme 

```
git clone https://github.com/morhetz/gruvbox.git ~/.vim/pack/default/start/gruvbox
```

So when installing other colorschemes do the same thing. 

However when needing to update. All the directions on colorschemes I see have editing done this way
https://github.com/morhetz/gruvbox/wiki/Configuration

However none of these edits work in `init.toml`

So.. How do we edit using this sort of editing format?

I use, nvim, with zsh, and directions point to putting this in `.vimrc` which I have done and nothing happens

**Comment by wsdjeg** [comment]
I will update the doc.
