### ISSUE TITLE
Feature request: random-theme switch colorscheme by custom time

### ISSUE THREAD

**Issue by sicojuy** [wsdjeg/SpaceVim#1751]
Now, when I set up random-theme layer, SpaceVim will switch colorscheme every startup. It is too often to me. I hope that I can config the switch strategy, e.g. switch per hour, per day, per week etc.

**Comment by wsdjeg** [comment]
This feature LGTM, and I also want this feature, to implement this feature, we need to create a  cache file to same the last colorschem name.

in current version of SpaceVim, the toml file was cached as json file in `~/.cache/SpaceVim`, and maybe we can cache the colorscheme name into too.

when vim startup just check the time of the cached file, and change the colorscheme according to the frequency.
