### ISSUE TITLE
High cpu/lag with anything but small files

### ISSUE THREAD

**Issue by zachthompson** [wsdjeg/SpaceVim#1759]
## Expected behavior, english is required

Can hardly navigate when files have a line count over some threshold.  Not sure what that is but the file in the asciinema only had about 900.  I've tested with md, pl, and a few others

## The reproduce ways from Vim starting (Required!)

Install and open a larger file

Same behavior on Ubuntu 16.04.

## Environment Information

- OS: FreeBSD 11.1-STABLE
- vim version: 8.0.1769
- neovim version: -
- SpaceVim version: 0.8.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_background = 'dark'
g:spacevim_buffer_index_type = 4
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_dein_installed = 1
g:spacevim_denite_leader = '\f'
g:spacevim_disabled_plugins = []
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 0
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 1
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = ''
g:spacevim_github_username = ''
g:spacevim_guicolors = 1
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_neobundle_installed = 0
g:spacevim_plugin_bundle_dir = '/home/user/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_max_processes = 16
g:spacevim_plugin_name = 'vim-grepper'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_display_mode = 0
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_unite_leader = '\f'
g:spacevim_version = '0.8.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vim_plug_installed = 0
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/bin/vim)
version: 800
OS: FreeBSD
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:01:43] [ Info ] force loadding global config >>>
[ SpaceVim ] [12:01:43] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [12:01:43] [ Info ] Find project root('.git/',''):/home/user/.SpaceVim/.git/
[ SpaceVim ] [12:01:43] [ Info ] change to root:/home/user/.SpaceVim
[ SpaceVim ] [12:01:44] [ Info ] change to root:/home/user/.SpaceVim
```

## Screenshots

https://asciinema.org/a/VCk75Wj7Wg496UpeDGVRM8QiK

**Comment by wsdjeg** [comment]
I think it is because the perl is too long, and the syntax highlight will parser the contents, so it is slow. I need these info:

1. do you load `lang#perl` layer?
2. does it happed when disable indentline, the key bindings is `SPC t h i`
3. does it happed when disable syntex highliht, the key bindings is `SPC t h s`

**Comment by zachthompson** [comment]
1. No lang#perl, was pretty much a default install
2. Didn't help
3.  This seems to fix it.  Stops as soon as j/k is not pressed.  Was a few hundred lines after letting up on the key in the asciinema.  cpu goes up to 15-16% when continuously scrolling.

**Comment by zachthompson** [comment]
With `relativenumber=false` and current line highlighting (`SPC t h h`) disabled,  it is usable with syntax highlighting on.  cpu goes a bit higher (~30%) when scrolling a lot and there's a hitch around 20-30 lines.

Side note: I noticed that the toggles are reset every time I open the shell with `SPC '`.

**Comment by wsdjeg** [comment]
> This seems to fix it

so this is issue with vim's perl syntax file? when move to a line I do not recommand to hold one j or k, vim provides many ways for jump to a line, hold on j/k is the slowest way.

BTW, I can not reproduce it in vim file, so this is issue with perl specified.

**Comment by wsdjeg** [comment]
> toggles are reset every time I open the shell with SPC '

what do you mean?  what  is reset?

**Comment by zachthompson** [comment]
I'm only holding j/k to illustrate the problem.  This happens when going a few lines back and forth.

"toggle reset"

1. Open a file and disable line highlighting `SPC t h h`
2. Open shell `SPC '`
3. Switch to back to file and line highlighting is on again

**Comment by wsdjeg** [comment]
ok, `toggle reset` is a bug of SpaceVim.

**Comment by xiuliren** [comment]
I have the same issue with editing latex file. all the three methods do not work for me...

**Comment by wsdjeg** [comment]
@zachthompson @jingpengw This issue report two things:

1. j/k is slow, I can not reproduce it.
2. `SPC t h h` is reset after switch buffer ( please use new issue for it)
