### ISSUE TITLE
Fix the C/C++ compiler invalid argument bug in SpaceVim

### ISSUE THREAD

**Issue by Ionizing** [wsdjeg/SpaceVim#176]
### Expected behavior, english is recommend
When editing C/C++ source files, SpaceVim could compile the tile right after you `:w`, and show the warnings and errors. But some source files were written according to C++11 standard, which requires to add `--std=c++11` or `--std=c++14` argument to the compile command.

### Environment Information
- OS: Ubuntu 16.10
- vim version: 8.0
- neovim version: 

### The reproduce ways from Vim starting (Required!)

> #include\<iostream\> 
int main()
{
    int* p = nullptr;
    auto i = 10;
    return 0;
}

You can type it SpaceVim and 
> :w

SpaceVim will report errors in line 4, indicating that 'nullptr' is unidentified. However when you use `auto` type which also be a c++11 variable type, the compiler will only show a warning that remind you it requires --std=c++11 arguments.

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
![screenshot from 2017-01-30 00-26-45](https://cloud.githubusercontent.com/assets/17506747/22405840/94a8d11c-e683-11e6-8f9e-534174811b73.png)

![screenshot from 2017-01-30 00-33-39](https://cloud.githubusercontent.com/assets/17506747/22405865/ce731d6c-e683-11e6-9212-d6d59f35e096.png)

**Comment by wsdjeg** [comment]
I just open an issue about it, https://github.com/tweekmonster/deoplete-clang2/issues/5

**Comment by Ionizing** [comment]
Okay. I will read it . Thank you very much .

Ionizing Radiation

**Comment by Giacom** [comment]
Is there any workarounds for this? Also, if possible, how do you make it use clang instead of GCC?

**Comment by wsdjeg** [comment]
I will write a doc for this issue, and I think I can fix it, but maybe it is not the best solution.

**Comment by wsdjeg** [comment]
SpaceVim use neomake as the lint, if you just want to use clang maker,
you can set `let g:neomake_cpp_enabled_makers=["clang"]`, for more info please keep watch on the deoplete-clang2's issuse link show above.

**Comment by romanlarionov** [comment]
This is still an issue out of the box, but [this](https://github.com/neomake/neomake/issues/228) resolved it:
```
let g:neomake_cpp_enable_markers=['clang']
let g:neomake_cpp_clang_args = ["-std=c++14", "-Wextra", "-Wall", "-fsanitize=undefined","-g"]
```
