### ISSUE TITLE
Please add offline user manual download link at spacevim.org

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1764]
## Expected behavior, english is required
I want to read the manual at spacevim.org to learn more about the advance skill for spacevim.org,but is limited at if the network connection.so can add download link for the user manual,let I can read the manual anywhere
?
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
SpaceVim's website is build by jekyll, so you can build the website locally. if you start SpaceVim from the path ( ~/.SpaceVim), the SpaceVim development config will be loaded, and you can use `SPC a w` to start the local website, then you can use this url to visit the website:

```
http://127.0.0.1:4000/
```

**Comment by ghost** [comment]
emm, I mean the pdf format manual for SpaceVim

**Comment by wsdjeg** [comment]
sorry, I can not provide PDF version of SpaceVim's documentation, I think you can open the website of spacevim using firefox, then generate the PDF version of the page.
