### ISSUE TITLE
Modulize vim functions with separated files in same layer

### ISSUE THREAD

**Issue by zhujinxuan** [wsdjeg/SpaceVim#1767]
Hi, I am thinking about whether there is a way to avoid some large vim configs in special layer.

Suppose I have a layer config at

```
layerName.vim
```
which includes several functions to build a function like `findXXX`.   Too many functions in the same file confuse the code readers, so I am thinking whether we can do code splitting in one layer.

Is it possible to have the layer loaded by file 
```
layerName/index.vim
layerName/findXXX.vim
```
and then in `index.vim`, we can load function from different file like:
```
load_function('findXXX', './findXXX.vim');
```

**Comment by wsdjeg** [comment]
I do not want to use multiple file for a layer, a layer is a very simple script which provide a list of plugins, and some configurations, also maybe some key bindings.

there are two reason why I do not want to use multiple files.

first, in a layer, most of the value and function are script specific, we use `s:` scope. if we use multiple file, we need to use global variable and functions, which will pollute the vim runtime. all of this public function maybe called by users.

if the layer contains to many config, maybe some of these config can be moved to SpaceVim API.

second, loading multiple files is slow than a single file.

use multiple file for a layer is way to solve some questions. so I think your question is:

- if the layer contains too many code in it, it is hard to read and understand. 

I think , we can use fold feature of vim, here is how the build-in plugin flygrep code looks like:

![2018-05-31-21 47 36](https://user-images.githubusercontent.com/13142418/40786346-727fd50c-64b0-11e8-9ce8-1c8ec0b546d1.png)

**Comment by zhujinxuan** [comment]
@wsdjeg I agree.  We shall not make layers too complex.  If we need something complex, we shall make plugins rather than layers.

Problem solved.
