### ISSUE TITLE
Is there any way to disable keymapping jk?

### ISSUE THREAD

**Issue by chenlei0x** [wsdjeg/SpaceVim#1771]
jk is mapped to quit insert mode, which is not convenient for me.

Thanks.

**Comment by xiayyu** [comment]
Add a line `bootstrap_after = "myspacevim#after"` to the [option] section in file `.SpaceVim.d/init.toml`
Then create file `.SpaceVim.d/autoload/myspacevim.vim` with content
```
func! myspacevim#after() abort
  exec "iunmap jk"
endf
```
You may want to add some other scripts as you wish in the function.

**Comment by wsdjeg** [comment]
@xiayyu Thanks for your answer, we still need some documentation about how to use bootstrap function.

**Comment by chenlei0x** [comment]
Thanks for your help.
If possible, could we more offen use `<Alt-x> `combination, where x means any key, to map some function?
Great spacevim!!!

**Comment by wsdjeg** [comment]
I do not use alt key, but you can read `:h <M-`
