### ISSUE TITLE
Problem with space in directory name?

### ISSUE THREAD

**Issue by NightMachinery** [wsdjeg/SpaceVim#1772]
## Expected behavior, english is required
When I open vim from directory ` /Base/- Code/Clj/withering_spell/withering-spell/`, The following is shown:
![image](https://user-images.githubusercontent.com/36224762/40781358-cba0b904-64f0-11e8-8033-9ded3cff1e3b.png)

`E172: Only one file name allowed: cd /Base/- Code/Clj/withering_spell/withering-spell/`
When I open it from `~/`, it works ok. Neovim also works correctly.
## Debug info
`SPC h I` doesn't work correctly.

**Comment by wsdjeg** [comment]
@NightMachinary It seems a bug of SpaceVim, I will look into it.
