### ISSUE TITLE
E734/E171 error

### ISSUE THREAD

**Issue by YunShengTeng** [wsdjeg/SpaceVim#1773]
- OS: macOS
- os version: 10.13.4
- vim version: stable 8.1.0001 (bottled), HEAD
- SpaceVim version: 0.8.0-dev

`Error detected while processing /Users/iabsorbed/.SpaceVim/config/main.vim:`
`line   24:`
`E734: Wrong variable type for +=`
`Error detected while processing /Users/iabsorbed/.SpaceVim/vimrc:`
`line   11:`
`E171: Missing :endif`
`Press ENTER or type command to continue`

vim --version
`VIM - Vi IMproved 8.1 (2018 May 17, compiled May 22 2018 22:51:49)`
`macOS version`
`Included patches: 1`
`Compiled by Homebrew`
`Huge version without GUI.  Features included (+) or not (-):`
`+acl               +farsi             +mouse_sgr         -tag_any_white`
`+arabic            +file_in_path      -mouse_sysmouse    -tcl`
`+autocmd           +find_in_path      +mouse_urxvt       +termguicolors`
`-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static`

`system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"`

`Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1`
`Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.2/lib/perl5/5.26.2/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.5.1 -lobjc`

[![asciicast](https://asciinema.org/a/u5Jg2MOugdfqGJ78kkvZOCnzi.png)](https://asciinema.org/a/u5Jg2MOugdfqGJ78kkvZOCnzi)

**Comment by wsdjeg** [comment]
can you try to reinstall spacevim？ I can not reproduce this issue.

**Comment by YunShengTeng** [comment]
@wsdjeg i has tried it many times,but it don't work

**Comment by YunShengTeng** [comment]
@wsdjeg thx, it has work
