### ISSUE TITLE
Some questions about Spacevim 

### ISSUE THREAD

**Issue by sundy-li** [wsdjeg/SpaceVim#1776]
- The `space` response to show help too slowly,  but the combine key works quickly( such as :  `space + 1 ` ), Is there some way to improve this？

- When vim a small file, it starts a little slow than pure vim, and exits a little slow than pure vim

- When using the `open shell`, some shortcut key on shell not work, such as Ctrl + W, Ctrl + E,  I know it is still in Vim, but is there any solution to make some common useful shell shortcut key work as normal?

**Comment by wsdjeg** [comment]
@sundy-li 

> The space response to show help too slowly, but the combine key works quickly( such as : space + 1 ), Is there some way to improve this？

This is feature of vim, I can not change it, in spacevim not all people need the guide, so if you remember the key bindings no guide should be opened. when you forget the next key, the your there is a delay, the guide will be opened.



> When vim a small file, it starts a little slow than pure vim, and exits a little slow than pure vim

pure vim has no plugins, some plugins make vim slow, by default spacevim has only 53 plugin now. if you find any plugin can be disabled by default, please let me kown.



> When using the open shell, some shortcut key on shell not work, such as Ctrl + W, Ctrl + E, I know it is still in Vim, but is there any solution to make some common useful shell shortcut key work as normal?

if you are using neovim, you can create key bindings in terminal, but if you are using vim8, you can not do it, vim8 does not support `tnoremap`.
