### ISSUE TITLE
the theme 'Material' is hoped to be added to SpaceVim

### ISSUE THREAD

**Issue by prontera** [wsdjeg/SpaceVim#1782]
## Expected behavior
a new theme is suggest to be added into Spacevim

## The reproduce ways from Vim starting
no reproduce

## Debug info
The theme 'Material Design' make me very impressive. 
The Github address is below
https://github.com/equinusocio/material-theme

This repo for that theme was designed to Sublime, but it had become deprecated since the author consider Sublime is an obsolete software.

However, this did not affect any passion for the theme. There was even an extend for the theme in IntelliJ IDEA, named "Material Theme UI".

Some developers bring it to VIM, e.g.
https://github.com/hzchirs/vim-material
![](https://camo.githubusercontent.com/2d2c461793a0293b85d7c37db38041550991258c/68747470733a2f2f696d6775722e636f6d2f786647597777632e6a7067?raw=true)
![](https://camo.githubusercontent.com/842de6f31912c2c030c64e7a1baf4cc012cb823d/68747470733a2f2f75706c6f61642e63632f692f7a437670484a2e706e67?raw=true)
https://github.com/jdkanani/vim-material-theme
![](https://camo.githubusercontent.com/b1fe09e25227ca0997e8e2bfd59e7a8c8ec0d2c8/687474703a2f2f692e696d6775722e636f6d2f564e78637635332e706e67?raw=true)
I hope it can be added to SpaceVim if possible.

Best Wishes.

**Comment by wsdjeg** [comment]
also the Official Portings

https://github.com/kristijanhusak/vim-hybrid-material

![](https://cloud.githubusercontent.com/assets/1782860/8340203/483e81f2-1abd-11e5-8fc6-b1ca5c646404.png)

**Comment by wsdjeg** [comment]
I just fork the repo, and will make it more suitable for SpaceVim:

https://github.com/SpaceVim/vim-material
