### ISSUE TITLE
unite open file failed under windows

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1788]
![default](https://user-images.githubusercontent.com/1751829/40907142-7169b5b2-6815-11e8-9c81-31db144b8ceb.png)

the filename contains the CRLF character, so open fail

**Comment by wsdjeg** [comment]
@Matrix-Zhang what is the reproduce step?

**Comment by deepseeksss** [comment]
just enable unite layer, then ctrl + p

**Comment by wsdjeg** [comment]
do you have `ag.exe` in your PATH? in spacevim, the unite's config contains:

```vim
let g:unite_source_rec_async_command = get(g:,
      \ 'unite_source_rec_async_command',
      \ ['ag', '--follow', '--nocolor', '--nogroup',
      \  '--hidden', '-g', ''])

```

**Comment by deepseeksss** [comment]
of course i have installed the ag.exe from choco package manager, otherwise the unite should hint error if can't find ag in path

**Comment by wsdjeg** [comment]
I do not know why the ag command output some many `CRLF character`.

**Comment by wsdjeg** [comment]
you can have a try with running the ag command in vim's terminal. or use system(), then see the result. if the result contains CRLF character, then it is issue with your ag execuatable.

**Comment by deepseeksss** [comment]
i have tried the ag in vim's termial, it seems normal....

![default](https://user-images.githubusercontent.com/1751829/41020492-a5c7d204-6995-11e8-99ca-2c655edef271.png)

**Comment by wsdjeg** [comment]
where do you download ag?

**Comment by deepseeksss** [comment]
from choco package manager

**Comment by wsdjeg** [comment]
It seems a bug of ag, the output contains unneeded chars.
