### ISSUE TITLE
edit.vim basic mode - ability to disable floobits

### ISSUE THREAD

**Issue by emaxerrno** [wsdjeg/SpaceVim#1790]
## Expected behavior, english is required
Not to create ~/floobits for user. 
Ability to choose which base layers to use.

## The reproduce ways from Vim starting (Required!)
just start default spacevim

## Debug info
no need. works as expected. d

## Screenshots

# Additional comments:
i really like the layers mode, 
however the basic edit.vim configuration loads up floobits - which is a site to i guess share code. 

i consider this service kind of a specialty use case and something that should be allowed to be configured out of the base config: 

https://github.com/SpaceVim/SpaceVim/blob/7c07f62c76d9022fca6c5e0d154f992cd74cdab0/autoload/SpaceVim/layers/edit.vim#L31

similar to the github layer - for those wanting the sersvice it looks easy enough to use a [[layer]] annotation and makes it less scary when ppl are trying to figure out where these directories are coming from. 

creates for a weird first experience. 

This is the second layer which again seems to be kind of an specialty layer for translation
https://github.com/SpaceVim/SpaceVim/blob/7c07f62c76d9022fca6c5e0d154f992cd74cdab0/autoload/SpaceVim/layers/edit.vim#L35

Consider that it is only one language and it's strange to make it the default for *all* users for *all* languages. 

I'd be happy to submit a PR to remove these 2 plugins, but I am not sure if it's a good direction. 

Maybe it requires a lot more work and I'm new to vimscript.

**Comment by emaxerrno** [comment]
note that adding 

```
[[layers]]
name = "floobits"
enable = false
```
didn't work. 

so seems like a couple of things as well: https://spacevim.org/layers/#disable-layers

**Comment by wsdjeg** [comment]
see https://github.com/SpaceVim/SpaceVim/pull/1697

**Comment by emaxerrno** [comment]
haha @wsdjeg  you were reading my mind! great! can't wait to try it.

**Comment by emaxerrno** [comment]
there is still the other translation plugin that would be great if edit - was just about edit for example.

**Comment by wsdjeg** [comment]
I am not sure if we should create new layer for vim-youdao-translater, or just moving it to Chinese layer.

**Comment by wsdjeg** [comment]
@senior7515 This plugin `ianva/vim-youdao-translater` should be move to chinese layer. I think.
