### ISSUE TITLE
How to create custom layer

### ISSUE THREAD

**Issue by emaxerrno** [wsdjeg/SpaceVim#1791]
## Expected behavior, english is required
Guide to create a custom layer. 

* Not sure what functions one would override 
* what order
* what folder they should be in
* how to load custom plugins from either github and how to debug it if it doesn't work
* how to ping the plugin at specific revision

## The reproduce ways from Vim starting (Required!)
n/a
## Debug info
n/a

## Screenshots
n/a

# Additional Notes:
In spacemacs, it's pretty easy to follow these steps. Is there any guide on how to create a custom layer?
https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org

**Comment by wsdjeg** [comment]
The development page has a simple guide for creating custom layer.

https://spacevim.org/development/#contributing-a-layer

this guide is for contributing a layer, if you want to create custom layer, you need to put this files into `~/.SpaceVim.d/`

**Comment by emaxerrno** [comment]
Thanks will give it a shot.
