### ISSUE TITLE
hint error when use sudo

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1792]
for example sudo nvim xxxx

![default](https://user-images.githubusercontent.com/1751829/40951428-8c61611e-68a9-11e8-83c9-67e43e0bca77.png)

**Comment by wsdjeg** [comment]
@Matrix-Zhang I can not reproduce this issue, please use issue template, and post your config.

**Comment by deepseeksss** [comment]
just default init.toml. and run in ubuntu server

**Comment by wsdjeg** [comment]
@Matrix-Zhang what is your vim version?

**Comment by deepseeksss** [comment]
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

**Comment by wsdjeg** [comment]
dein do not support sudo session, but in SpaceVim we have a  sudo layer, you can save file via `SPC f W` after load this layer.

**Comment by bric3** [comment]
@wsdjeg That won't work if editing a file like `/etc/sudoers` because it cannot be read (at the opposite of `/etc/hosts`).

```
-r--r-----  1 root  wheel   1.5K Oct 25 11:52 /etc/sudoers
-rw-r--r--  1 root  wheel   250B Oct 25 11:43 /etc/hosts
```

And `visudo` loads spacevim for some reason.

The most easy way was to `sudo su` then `vim /etc/sudoers`, in this way, `vim` is not using spacevim, and is usable again.
