### ISSUE TITLE
Open file failed

### ISSUE THREAD

**Issue by xsxnet** [wsdjeg/SpaceVim#1793]
I just open vim and double click on a file of the right side file-manager
error log:
[unite.vim] function <SNR>180_on_double_click[7]..<SNR>180_execute_system_associated[12]..vimfiler#mappings#do_dir_action[23]..unite#mappings#do_action[1]..unite#action#do[70]..179[18]..<SNR>217_open, line 41
[unite.vim] vital: System.File: open(): Not supported.
[unite.vim] Error occurred while executing "vimfiler__execute" action!

![image](https://user-images.githubusercontent.com/3366595/40956893-20e89a44-68c5-11e8-8c3a-b17b74564887.png)

**Comment by deepseeksss** [comment]
same error

**Comment by wsdjeg** [comment]
no issue template

**Comment by xsxnet** [comment]
@Matrix-Zhang Have you solved it?

**Comment by Shougo** [comment]
unite.vim uses the function to open file.

```vim
function! s:open(filename) abort
  let filename = fnamemodify(a:filename, ':p')

  " Detect desktop environment.
  if s:is_windows
    " For URI only.
    if s:need_trans
      let filename = iconv(filename, &encoding, 'char')
    endif
    " Note:
    "   # and % required to be escaped (:help cmdline-special)
    silent execute printf(
          \ '!start rundll32 url.dll,FileProtocolHandler %s',
          \ escape(filename, '#%'),
          \)
  elseif s:is_cygwin
    " Cygwin.
    call system(printf('%s %s', 'cygstart',
          \ shellescape(filename)))
  elseif executable('xdg-open')
    " Linux.
    call system(printf('%s %s &', 'xdg-open',
          \ shellescape(filename)))
  elseif exists('$KDE_FULL_SESSION') && $KDE_FULL_SESSION ==# 'true'
    " KDE.
    call system(printf('%s %s &', 'kioclient exec',
          \ shellescape(filename)))
  elseif exists('$GNOME_DESKTOP_SESSION_ID')
    " GNOME.
    call system(printf('%s %s &', 'gnome-open',
          \ shellescape(filename)))
  elseif executable('exo-open')
    " Xfce.
    call system(printf('%s %s &', 'exo-open',
          \ shellescape(filename)))
  elseif s:is_mac && executable('open')
    " Mac OS.
    call system(printf('%s %s &', 'open',
          \ shellescape(filename)))
  else
    " Give up.
    throw 'vital: System.File: open(): Not supported.'
  endif
endfunction
```

I think open commands are not install.

**Comment by deepseeksss** [comment]
@Shougo what is open coomands? how to install?

**Comment by wsdjeg** [comment]
@xsxnet @Matrix-Zhang  hello, I just check this issue, you use `double click` on vimfiler? so you want to open the file via default tools instead of vim itself?  this should same as `double click` on system file explorer.

what is your os? 

@Shougo  I think it is not due to `there is no commad`, as the error message is thrown, so in this function, unite can not check which os it is. 

```vim
else
    " Give up.
    throw 'vital: System.File: open(): Not supported.'
```

these above code has been executed. so I think `s:is_windows` and `s:is_cygwin` is false.
