### ISSUE TITLE
require lang#sql layer

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1794]
right now, when edit sql files, hint require dbext plugin

**Comment by wsdjeg** [comment]
any recommanded plugins for this layer?

**Comment by deepseeksss** [comment]
dbext plugin

**Comment by xylinkun** [comment]
I require lang#sql layer too.

**Comment by wsdjeg** [comment]
the latest version of dbext is v23.00, and the development is stoped.

https://github.com/vim-scripts/dbext.vim

as I remember, there is an active fork v26.00, but I can not find the link.

we also need sql language plugin:

1. syntax highlighting
2. indent
3. code complete
4. code format

**Comment by wsdjeg** [comment]
also find another tools, https://github.com/cosminadrianpopescu/vim-sql-workbench

this works well in neovim and vim8

**Comment by wsdjeg** [comment]
also https://github.com/tpope/vim-dadbod
