### ISSUE TITLE
how to make Neoformat on save??

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#1798]
:h spacevim-confog no anwser

**Comment by wsdjeg** [comment]
@Matrix-Zhang please use gitter for usage questions, issue tracker is only for bug report and feature request. if you want to run Neoformat on save, you can create autocmd, please read the bootstrap function section on spacevim's documentation on the website.

for example:

 au BufWrite * Neoformat

**Comment by deepseeksss** [comment]
i means maybe add a spacevim config for this option?

**Comment by wsdjeg** [comment]
Maybe add an option for format layer?

**Comment by wsdjeg** [comment]
@Matrix-Zhang as this is a config for plugin, so I just add doc about it.
