### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by thedelchop** [wsdjeg/SpaceVim#1801]
I have been trying out SpaceVim and enjoying it so far, congrats, this is a tremendous effort.  

My confusion is in the docs, they reference both `<Leader>` and `<leader>` when describing commands, for example:

Key Binding|Description
-----------|-------------
\<Leader\> 1 | Jump to index 1 on tabline
\<leader\>+sv | Split with previous buffer

I can't figure out how to access that second command.  Obviously, `<Leader>` is `\`, but is `<leader>` mapped to something entirely different?  Am I missing a piece of understanding with the docs?

**Comment by wsdjeg** [comment]
This should be a type in doc, in vim you can use both `<leader>` and `<Leader>`, they are same things. The default key is \, and spacevim do not change it by default.

For example, you can use:

`nnoremap <leader> :echo 1<cr>`

`nnoremap <Leader> :echo 1<cr>`


These key bindings are same thing.

**Comment by thedelchop** [comment]
Thank you.
