### ISSUE TITLE
Both 'SPDebugInfo' and 'SPC h I' fail

### ISSUE THREAD

**Issue by PeterDing** [wsdjeg/SpaceVim#1803]
## Expected behavior, english is required
Originally I wanted to issue an other question, but, when I did `SPC h I` and `:SPDebugInfo` or `:SPDebugInfo!`, finding errors.
So, I need to solve this one first.

## The reproduce ways from Vim starting (Required!)
My `~/.SpaceVim.d/init.vim` and `CheckHealth` are following:

```
"=============================================================================
" dark_powered.vim --- Dark powered mode of SpaceVim
" Copyright (c) 2016-2017 Wang Shidong & Contributors
" Author: Wang Shidong < wsdjeg at 163.com >
" URL: https://spacevim.org
" License: GPLv3
"=============================================================================


" SpaceVim Options: {{{
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_statusline_display_mode = 0
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
" }}}

" SpaceVim Layers: {{{
call SpaceVim#layers#load('ui')
call SpaceVim#layers#load('colorscheme')
call SpaceVim#layers#load('autocomplete', {'auto-completion-complete-with-key-sequence' : 'nil'})
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#rust')
call SpaceVim#layers#load('lang#tmux')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('shell')
call SpaceVim#layers#load('tools#screensaver')

call SpaceVim#layers#load('cscope')
call SpaceVim#layers#load('unite')
call SpaceVim#layers#load('tags')
" }}}


" solarized do not support true colors. you should use Neosolarized
let g:spacevim_terminal_cursor_shape = 1   " enable non-blinking mode-sensitive cursor
let g:spacevim_enable_guicolors = 1
"let g:spacevim_colorscheme = 'base16-solarized-dark'
let g:spacevim_colorscheme = 'onedark'
let g:spacevim_colorscheme_bg = 'dark'
let g:spacevim_statusline_separator = 'fire'
let g:spacevim_default_indent = 4
let g:python3_host_prog = '/usr/local/bin/python3'
let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python3'
let g:jedi#force_py_version = 3

" To disable Python 2 support
" let g:loaded_python_provider = 1

" jedi
" The completion is too slow!
" 1. Completion of complex libraries (like Numpy) should only be slow the first time you complete them.
" After that the results should be cached and very fast.
" 
" 2. If it is still slow after the initial completion and you have installed the python-mode Vim plugin,
" try disabling its rope mode:
let g:pymode_rope = 0
" 3. You can also use deoplete-jedi for completions, which uses Jedi,
" but does completions asynchronously (requires Neovim).
" It makes sense to use both jedi-vim and deoplete-jedi,
" but you should disable jedi-vim's completions then:
let g:jedi#completions_enabled = 0

set virtualedit=onemore             " Allow for cursor beyond last character

" Use H and L to move to the previous/next tabpage.
" only work at normal mode
nmap H [b
nmap L ]b

" go to $
nmap g9 g$

" rust.vim
let g:rustfmt_autosave = 1
let g:rustfmt_options = '-f'

au FileType rust nmap hd <Plug>(rust-def)
au FileType rust nmap hs <Plug>(rust-def-split)
au FileType rust nmap hv <Plug>(rust-def-vertical)
au FileType rust nmap ho <Plug>(rust-doc)

" show all uncompliable symbols
set listchars=tab:>-,trail:~,extends:>,precedes:<
set list

" custom plugins
" need to add 'davidhalter/jedi-vim' to pop up jedi actions
let g:spacevim_custom_plugins = [
    \ ['luochen1990/rainbow'],
    \ ['davidhalter/jedi-vim'],
    \]

let g:rainbow_active = 1
```

## `CheckHealth`

health#jedi#check
========================================================================
#### Jedi-vim debug information
Using Python version: 3
 - global sys.version: `3.6.5 (default, Apr 14 2018, 10:24:02), [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]`
 - global site module: `/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py`
Jedi path: `/Users/peter/.cache/vimfiles/.cache/init.vim/.dein/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.0
 - environment: <Environment: 3.6.5 in /usr/local>
 - sys_path:
    - `/private/tmp/t`
    - `/Users/peter/dev/afanti`
    - `/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python36.zip`
    - `/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6`
    - `/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload`
    - `/usr/local/lib/python3.6/site-packages`
 - jedi-vim git version: fatal: not a git repository (or any of the parent directories): .git
 - jedi git submodule status: fatal: not a git repository (or any of the parent directories): .git

##### Settings
```
g:jedi#force_py_version = 3 (default: 'auto')
g:jedi#completions_enabled = 0 (default: 1)


  omnifunc=htmlcomplete#CompleteTags
	Last set from /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/ftplugin/html.vim
  completeopt=menu,menuone,longest
	Last set from ~/.SpaceVim/autoload/SpaceVim/default.vim
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: xterm-256color
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.15
  - INFO: python2-neovim version: 0.2.6
  - OK: Latest python2-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.5
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - INFO: Node: v10.3.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?

----------

## Debug info
I can't as above description.

## Screenshots
`SPDebugInfo`:
<img width="1276" alt="screen shot 2018-06-07 at 12 25 03" src="https://user-images.githubusercontent.com/670690/41078431-63103f90-6a4f-11e8-9284-7e0aac476e50.png">

`SPC H I`
<img width="1280" alt="screen shot 2018-06-07 at 12 25 29" src="https://user-images.githubusercontent.com/670690/41078434-66bd04b6-6a4f-11e8-9cb5-9c9998ade68f.png">

**Comment by wsdjeg** [comment]
@PeterDing Hi, I can reproduce this issue, thanks. I will look into it.
