### ISSUE TITLE
Terminal does not work

### ISSUE THREAD

**Issue by x-tit** [wsdjeg/SpaceVim#1804]
Hello，
When I type SPC + ' to start a terminal ,SpaceVim reports that Terminal is not supported in this version.

I have vim 8 and spacevim0.8.0-dev and shell layer enabled.
Thank you.

**Comment by wsdjeg** [comment]
you need to recompile your vim with +terminal suport, or downloaded it from https://github.com/vim/vim-win32-installer if your are using windows os.
