### ISSUE TITLE
feature request: lsp support for typescript

### ISSUE THREAD

**Issue by rolfst** [wsdjeg/SpaceVim#1805]
Spacevim supports typescript,
but it doesnt support typescript via lsp

can this be added?

**Comment by wsdjeg** [comment]
yeah, this feature should be supported in spacevim, as I know typescript has a language server:

https://github.com/theia-ide/typescript-language-server

**Comment by ijsnow** [comment]
Also consider this one https://github.com/sourcegraph/javascript-typescript-langserver

**Comment by wsdjeg** [comment]
[javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver/pulse/monthly) development is more active.
