### ISSUE TITLE
Doc clarification

### ISSUE THREAD

**Issue by docwhat** [wsdjeg/SpaceVim#1807]
The following bit of text in the docs is confusing to me:

<https://github.com/SpaceVim/SpaceVim/blob/92aa47e3dc3642eeefcb78797a49d1e3139966bc/doc/SpaceVim.txt#L85-L86>

I was trying to figure out how to configure things, since some docs talk about `init.toml` and others act as if I had a `~/.vimrc` I should be editing.

**Comment by wsdjeg** [comment]
the help file need to be updated, so what do you want to configrue?

**Comment by docwhat** [comment]
I just don't understand it.

I _think_ the options are for a vim file (`~/.SpaceVim.d/init.vim`?) not a `.toml` file.

Should I throw away the `.toml` file and use a `.vim` file?

Or both?

Or just the `.toml`?

**Comment by wsdjeg** [comment]
SpaceVim will only support toml as configuration file in next release.

**Comment by docwhat** [comment]
Ah, hah!  Cool.

**Comment by crisidev** [comment]
Wait, what? Are you saying the init.vim will not be supported anymore? I have a ton of customization there and I don't what to use toml at all in the future. Will you still support init.vim?

**Comment by wsdjeg** [comment]
how about moving all content to bootstrap function?

**Comment by crisidev** [comment]
Honestly, I don't see the point... Than I need to both configure vim with toml and a bootstrap function for the rest. Is it not possible just to keep the init.vim loading as every other vim distribution is doing and always will do? I mean, you are basically breaking compatibility with vim in my honest point of view..

**Comment by wsdjeg** [comment]
I have added the FAQ for why use toml as default config.

**Comment by crisidev** [comment]
Do you mind to link the FAQ to me? I cannot find it.

**Comment by wsdjeg** [comment]
@crisidev sorry, It is https://spacevim.org/cn/faq ， But It is chinese version, and I am updating the english version of this page in #1837
