### ISSUE TITLE
How to define key bindings in init.toml

### ISSUE THREAD

**Issue by ccojocar** [wsdjeg/SpaceVim#1809]
Is it possible to define new key bindings or overwrite exiting key binding in `init.toml`? I looked a bit around but haven't found any documentation. 

Thanks for your help

**Comment by wsdjeg** [comment]
You can read the doc, https://spacevim.org/documentation/#bootstrap-functions

just crate a bootstrap function, and in this function, you can use vim script, so you can add key bindings, autocmd, command, etc.

**Comment by jhessin** [comment]
Yes but WHERE do we create this bootstrap function? Is there a particular file we should edit for it?
