### ISSUE TITLE
Occasional lockups/freeze when making a newline

### ISSUE THREAD

**Issue by anoadragon453** [wsdjeg/SpaceVim#1820]
## Expected behavior, english is required

A new line is made under the current one.

## The reproduce ways from Vim starting (Required!)

Unfortunately this only happens very infrequently, but enough for it to be annoying (3-4 times per day). The application just stops responding correctly to input. The cursor still blinks. Pressing any key causes the cursor to blink again, but nothing else happens.

## Debug info

> Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

Unfortunately I can't press this while the application is locked up. Is there any other way to get this info? (Log files perhaps?)

This is using Spacevim with neovim.

Thanks.

**Comment by wsdjeg** [comment]
I can not reproduce this issue, please check the neovim's wiki for how to set logfile. BTW issue templete is needed for issue report.

**Comment by anoadragon453** [comment]
Turns out this happens just when hitting 'Enter' to make a newline as well.

@wsdjeg could you link the instructions you're referring to? I don't see them on Neovim's github wiki.

**Comment by wsdjeg** [comment]
@anoadragon453 You can just restart spacevim, and press `SPC h I`, and post debug info.

**Comment by anoadragon453** [comment]
Will try that next time, thanks.
