### ISSUE TITLE
your vim is too old, getcompletion() need patch7-4-2010

### ISSUE THREAD

**Issue by taizilongxu** [wsdjeg/SpaceVim#183]
### Expected behavior, english is recommend

I found that the autocomplete for python dose not work, and I have already `$ brew info neovim/neovim/neovim`
### Environment Information
- OS: macOS 10.12.3
- vim version: 
- neovim version: 0.1.7

### The reproduce ways from Vim starting (Required!)

Anytime when I enter the nvim

### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

`:message` cannot display any thing

and `:echo SpaceVim#logger#viewLog()`

```log

SpaceVim Options :

your vim is too old, getcompletion() need patch7-4-2010
[ SpaceVim ] : logger file /Users/limbo/.SpaceVim/.SpaceVim.log does not exists, only log for current process will be shown!

```

**Comment by wsdjeg** [comment]
I will fix it.
