### ISSUE TITLE
loading vim failed in WSL

### ISSUE THREAD

**Issue by a1mersnow** [wsdjeg/SpaceVim#1834]
## Expected behavior, english is required
vim should load successfully

## The reproduce ways from Vim starting (Required!)
1. make sure you are in WSL on windows10
2. `cd ~ && curl -sLf https://spacevim.org/install.sh | bash`
3. `vim`
4. you will see the errors:
```
Error detected while processing /home/aimergenge/.SpaceVim/vimrc:
line    8:
E492: Not an editor command: ^M
line   10:
E15: Invalid expression: 1^M
line   14:
E171: Missing :endif
```

## Debug info

Unable to post the debug info because SpaceVim is not loaded.

## Screenshots

![image](https://user-images.githubusercontent.com/13799160/41396896-f42b6384-6fe4-11e8-8ded-73db1f7789c2.png)

**Comment by wsdjeg** [comment]
1. E492: Not an editor command: ^M

The problem was git auto added ^M when cloning, solved by:

```sh
git config --global core.autocrlf input
```
