### ISSUE TITLE
Paste in fuzzy find

### ISSUE THREAD

**Issue by ArnaudValensi** [wsdjeg/SpaceVim#1835]
Hi!
First thank all the contributors for the great job you've done!

I have a quick question: is it possible to paste the content of the vim clipboard register and the system clipboard when we are in the fuzzy search ('space pf' for example). I've tryed with unite, denite and fzf.

Thank you

**Comment by wsdjeg** [comment]
@ArnaudValensi Nice feature request, I also think denite should support this featrue. and I will implement this feature in flygrep.

@Shougo, how about add this feature in denite? maybe provide a key binding in insert move, for example when presss `<C-v>`, put the content of register `@+` into denite prompt.

**Comment by Melkor333** [comment]
I'm on my phone right now so I can't check, but does <ctrl + R> {registername} not work? This is how you can insert a register while in insert mode.  [proof](https://stackoverflow.com/questions/2861627/paste-in-insert-mode)

**Comment by ArnaudValensi** [comment]
@Melkor333 unfortunately it doesn't. It seems to be bound to something else, like refresh or clean.

**Comment by Shougo** [comment]
Hm.

**Comment by Shougo** [comment]
@wsdjeg ~~Please create the new issue for it.~~

**Comment by Shougo** [comment]
Please use `<C-r>` in insert mode.
It is your desired feature.
`:help <denite:paste_from_register>`

**Comment by wsdjeg** [comment]
thanks， I will have a try.

**Comment by wsdjeg** [comment]
denite has provide this feature. after press `SPC p f`, just press `Ctrl-r` and `{registername}`.
