### ISSUE TITLE
SpaceVim 在OSX下卡死

### ISSUE THREAD

**Issue by Gatsby23** [wsdjeg/SpaceVim#1839]
mac是2017年15寸新款，用的是OSX 10.13.5。
 现在经常出现的位是在用macvim+SPacevim的时候出现卡死情况（原来在terminal下用vim也有过），Linux下好像没有这种问题。
也没有报错，代码量也不大，今天是两次在编写std::endl的时候开始卡死，显示还是insert模式，但是什么都做不了，很奇怪，不知道能不能解决

**Comment by wsdjeg** [comment]
English only in GitHub，otherwise please use gitee.
