### ISSUE TITLE
Completion python problem

### ISSUE THREAD

**Issue by nathanielsimard** [wsdjeg/SpaceVim#184]
### Expected behavior, english is recommend
When coding in python and use autocompletion, it always put a 0 instead of completion.
Exemple:

If I write "self" then a dot ".", a 0 appear.

class Example:

    def __init__(self, object):
        self.something
        self.0

There is also that message:
Omni completion (^O^N^P) Back to original

### Environment Information
- OS Arch linux:
- vim version: 8.0
- neovim version:

### The reproduce ways from Vim starting (Required!)

Open a python file with a fresh install of Spacevim.
Then use autocompletion after a dot.

**Comment by wsdjeg** [comment]
I can not reproduce it, it works well for me , I also use vim8 in arch
![2017-01-31-23 30 28](https://cloud.githubusercontent.com/assets/13142418/22471553/a5410464-e80d-11e6-8ec4-04a885a67572.png)
![2017-01-31-23 30 58](https://cloud.githubusercontent.com/assets/13142418/22471554/a54e6a8c-e80d-11e6-8e76-76cee815113b.png)

**Comment by nasim80** [comment]
Oh I just tried another terminal emulator. It seems to be a problem with xfce4-terminal and Lxterminal. In Konsole it works fine. But I don't know why it's a problem.

**Comment by wsdjeg** [comment]
I use termite, it also works well, sorry, I do not use xface etc.

**Comment by nathanielsimard** [comment]
Finally it's not a terminal issues. It only works one time in konsole and it doesn't work in termine neither.  I use python 3.6 on KDE. 

It works fine with neovim !

**Comment by wsdjeg** [comment]
Do you have jedi installed?

**Comment by nathanielsimard** [comment]
Oh, it seems that was the problem. With jedi installed there is no issue. Normally when you install jedi-vim, there is an error message when you don't have jedi installed. Maybe that would be helpfull to have the same kind of message in spacevim or just mention it in the doc.

**Comment by wsdjeg** [comment]
Thanks I will add info about it in doc.

**Comment by wsdjeg** [comment]
Done in #188.
