### ISSUE TITLE
The SpaceVim often get stuck under the OSX

### ISSUE THREAD

**Issue by Gatsby23** [wsdjeg/SpaceVim#1840]
My mac is OSX10.13.5, I used macvim and the vim to support the spacevim. It's weired that the spacevim often get stuck when I write the std::endl and some other command. The macvim is stoped that I can only stop it by use the kill command and there are no error informations about this stuck. But the spacevim is worked fine under the Linux system. Do you know why?

**Comment by wsdjeg** [comment]
please follow the issue templete, the debug info is needed, you can press `SPC h I` in SpaceVim, then post all the content of the debug buffer.

**Comment by wsdjeg** [comment]
no reply, closed.
