### ISSUE TITLE
Feature request: don't overwrite .vimrc/init.vim

### ISSUE THREAD

**Issue by bluddy** [wsdjeg/SpaceVim#1844]
It would be really great if I could try SpaceVim without overwriting my .vimrc or init.vim. I'm not used to SpaceVim's workflow, and I can't afford to disrupt my current workflow. If SpaceVim created a file (e.g. `svim`) that invoked nvim or vim with a different configuration file, that would be much preferable to the current situation, and would allow me to learn to adapt to SpaceVim gradually.

Also, the installer *has* to warn you that your current configuration will be overwritten. It's not acceptable not to do that.

**Comment by wsdjeg** [comment]
A simple guide for how to use SpaceVim without overwrite user's config is needed, I will update the website. and thank you for your feedback.

**Comment by wsdjeg** [comment]
@bluddy I just open a PR about this issue, what do you think about that pr?
