### ISSUE TITLE
Can you safely uninstall spacevim?

### ISSUE THREAD

**Issue by jeremyf21** [wsdjeg/SpaceVim#1845]
Hi, I would like to install spacevim to try it out. However looking at the install script I see it removes all my vim and neovim installations. Is there a way to safely and easily remove all of SpaceVim if I wish to do so?

**Comment by wsdjeg** [comment]
@jeremyf21 The install script do not remove your config, It just change the name for `~/.vim` to `~/.vim_back`, and if you uninstalll SpaceVim, your vim config will come back. you can run 

```sh
curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
```

**Edit:**

please read [How to uninstall SpaceVim?](https://spacevim.org/faq/#how-to-uninstall-spacevim) in FAQ page.

**Comment by thegreyfellow** [comment]
Sorry for bringing this issue again, but can we have this on the Readme? I spent half a day looking then randomly searched all issues for `uninstall` to find this. Thanks a lot 🙏!

**Comment by Zhaoxian-Wu** [comment]
I have run the command ```curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall```, but the spacevim stiil stay in my computer.
```bash
lenovo-ideapad-500s-14isk:~$ curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
[➭] Trying to uninstall SpaceVim
Thanks!
```
the uninstall script seems not to work

**Comment by kotx** [comment]
The SpaceVim configuration directories will remain, just delete them with `rm -rf ~/.SpaceVim*`

**Comment by ruddhisundar** [comment]
> @jeremyf21 The install script do not remove your config, It just change the name for `~/.vim` to `~/.vim_back`, and if you uninstalll SpaceVim, your vim config will come back. you can run
> 
> ```shell
> curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
> ```

YOU SAVED THE DAY! I tried the spacevim configuration on the FreeBSD console, but it failed miserably. Uninstalling helped!

**Comment by Anogoya-Dagaate** [comment]
What is the Windows version of this - there are SpaceVim options such as SPClean SPConfig SPDebugInfo SPReinstall etc but nothing for uninstall? I also tried SpaceVim and got into all kinds of trouble with my standard Vim and Neovim configuration. I think it could be made easier for others like @thegreyfellow suggested

**Comment by Morpheus2023** [comment]
Copy and paste this command to get rid of SpaceVIm

`curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall`

**Comment by daweth** [comment]
This still leaves the .Spacevim folders in root. @Morpheus2023

**Comment by slopslug** [comment]
@Morpheus2023 That's for Linux, OP was asking for a Windows equivalent.
