### ISSUE TITLE
julia 0.6 or newer support

### ISSUE THREAD

**Issue by xiuliren** [wsdjeg/SpaceVim#1846]
## Expected behavior, english is required
the julia plugin `deoplete-julia` was deprecated. It only support Julia 0.5 without update to Julia 0.6 or recent 0.7.
To upgrade the support, `LanguageServer.jl` was preferred.
 See this issue:
https://github.com/JuliaEditorSupport/deoplete-julia/issues/10

## The reproduce ways from Vim starting (Required!)
edit any Julia 0.6 code.

## Screenshots
![image](https://user-images.githubusercontent.com/7651573/41558643-6deb4d42-730f-11e8-855f-f182508b4a21.png)

**Comment by wsdjeg** [comment]
please keep this issue open, I want to know if deoplete-jujlia is still maintained.
