### ISSUE TITLE
spacevim edit color abnormal

### ISSUE THREAD

**Issue by vbirds** [wsdjeg/SpaceVim#1851]
### Environment Information
- OS: ubuntu16.04 LTS
- vim version: vim8.1

when i open vim, I see the following screenshots, please help me

### Screenshots
![vim](https://user-images.githubusercontent.com/9044488/41640295-c92f603c-7493-11e8-82ff-5ae339169ada.png)

**Comment by wsdjeg** [comment]
which terminal are you using, does it support true colors, have you try to disable true colors?

**Comment by vbirds** [comment]
thank you for reminding me. this is my xshell question ,it's not support for ture color, when i use tmux open vim it's fine . @wsdjeg

**Comment by wsdjeg** [comment]
OK ：）
