### ISSUE TITLE
JUPYTER 3 CONSOLE IN SPACE VIM

### ISSUE THREAD

**Issue by linux2coder** [wsdjeg/SpaceVim#1854]
**Feature Request**
The SpaceVim is an almost complete package for me just one thing  I miss in this. I want to SpaceVim to be embedded with jupyter interactive control with vim.
.

**Comment by wsdjeg** [comment]
I just found a plugin for this feature, and I will create a new layer `jupyter` or `lang#ipynb`.

https://github.com/szymonmaszke/vimpyter
