### ISSUE TITLE
Using python 3 as default for spacevim

### ISSUE THREAD

**Issue by vlurgio** [wsdjeg/SpaceVim#1855]
I'm having some trouble with python in spacevim and it's the only thing I can't seem to get to work correctly. I want the execute file command (SPC l r) in python to run the file with python3 but it will only run it with python 2. Also my autocomplete is using the jedi backend with python2 as well (I know this because it wont autocomplete any packages that are only available with python3). I feel like there's just a variable I need to set but i can't figure out how. :checkhealth shows both python 2 and 3 are install and configured correctly. 
## Expected behavior, english is required
Executing a file in python uses python 3 for the execution. 
## The reproduce ways from Vim starting (Required!)
open a python file and press SPC l r to execute
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@vlurgio Please improve the reproduce step, I can not reproduce it, what is the content in the python file.

try to add this to the begin of your python file

```
#! /usr/bin/python3
```

**Comment by hsingll** [comment]
<img width="585" alt="snipaste_2018-11-10_21-48-43" src="https://user-images.githubusercontent.com/26346635/48302086-91ad9d80-e532-11e8-809e-aa505d02e7f2.png">
Sorry,bug happens today.
And,without add "#! /usr/bin/python3" in file,can we set python3 as default? @wsdjeg

**Comment by vanor89** [comment]
Hey guys, hope im not too late, but SpaceVim picks up on your Virtual Environment, so if you  `source bin/activate` and then open vim, it should use the Python on your venv. 
Cheers!
