### ISSUE TITLE
Assembly support

### ISSUE THREAD

**Issue by evopen** [wsdjeg/SpaceVim#1856]
Are there any plans for assembly support? 
Especially for code formatting.

**Comment by wsdjeg** [comment]
@evopen do you ever use vim for assembly? any recommend vim plugins? many we need to create a new layer for assembly?

**Comment by wsdjeg** [comment]
ok, just find one plugin 

https://github.com/rhysd/vim-wasm

**Comment by evopen** [comment]
@wsdjeg um.. That plugin is for web assembly. I was talking about .S file. And sorry i don't know any plugin. Maybe there is no formating plugin for asm due to various formats of asm.

**Comment by evopen** [comment]
Spacemacs has no asm code formating function, only indenting. And its language specific function is very limited which only aim for x86 architecture. 

So i guess there are few plugins for asm. If there is one, i guess it would only provide code indent. 
If you found nothing. You might wanna close this.

**Comment by wsdjeg** [comment]
ok, I just add new layer label. will try to find what plugins should be included.

**Comment by wsdjeg** [comment]
@evopen hi, I think you are talking about spacemacs's Major mode for Asm86 assembly, it includes narm-mode.el

in vim, I just search in github, and I have found a list of arm support plugins:

- https://github.com/compnerd/arm64asm-vim AArch64 (ARM64) Assembly Syntax Highlighting (for VIM)
- https://github.com/maxbane/vim-asm_ca65 Vim syntax highlighting for the ca65 assembler
- https://github.com/vim-scripts/asm8051.vim Syntax for 8051 Assembly (some IAR specifics)
- https://github.com/vim-scripts/asmM6502.vim MOS 6502 Assembly syntax
- https://github.com/vim-scripts/asmx86 A Simple x86-ASM syntax for VIM

I want to know, what is the most used suffix for assembler file? is there any differences between the suffix of these kind of assembler file?

**Comment by evopen** [comment]
@wsdjeg Sorry, I've only written some aarch64 asm for my OS class. I don't know much about other syntax.

**Comment by wsdjeg** [comment]
@evopen so what is the best name for this layer? in spacevim all programming language layer has `lang#` prefix, for example `lang#python` layer is for python development, `lang#java` layer is for java development, so what is the name of this language?

**Comment by lukaszmoskwa** [comment]
I would be interested as well in a layer for assembly, and ```lang#asmx86``` would be quite appropriate imo

**Comment by wsdjeg** [comment]
@Lykos94 so which plugin should be included in this layer?

**Comment by wsdjeg** [comment]
Hello, I have create a plugin https://github.com/wsdjeg/vim-assembly in this plugin, it will support all assembly language in the future. currently only `.asm` file is supported.

**Comment by wsdjeg** [comment]
@Lykos94 I just add a new layer `lang#assembly`, but I think the name is wrong, `assembly` is not a name of a language. I should rename it into asmx86 etc.

**Comment by lukaszmoskwa** [comment]
Thanks for your work! And yes, the name was a bit misleading at first :)

**Comment by wsdjeg** [comment]
but there are too many kind of assembly language. merged into one layer will make it easier to maintained. Base on github language detection, I will make assembly layer support x86 assembly, x68 assembly and agc.
