### ISSUE TITLE
Hello Mr.Big

### ISSUE THREAD

**Issue by wjstud** [wsdjeg/SpaceVim#1859]
Please help me!
`Error detected while processing function <lambda>26[1]..completor#do[7]..completor#utils#get_completer:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
`
The error with use spacevim edit files

**Comment by evopen** [comment]
We got the same error. #1858

**Comment by wsdjeg** [comment]
@wjstud It is same as #1858, closed.
