### ISSUE TITLE
Add lang#autohotkey layer

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1865]
any recommanded plugin is welcome.

**Comment by fcying** [comment]
Plug 'vim-scripts/autohotkey-ahk', {'for':'autohotkey'}
Plug 'huleiak47/vim-AHKcomplete', {'for':'autohotkey'}
autocmd FileType autohotkey setl omnifunc=ahkcomplete#Complete

**Comment by wsdjeg** [comment]
@fcying I will create a new repo vim-autohotkey, and remove +py requietment.
