### ISSUE TITLE
Python autocompletion without tags layer -- using jedi

### ISSUE THREAD

**Issue by rezende** [wsdjeg/SpaceVim#1867]
Before moving to SpaceVim, I was using vim-jedi's Go to definition (<leader>+d) https://github.com/davidhalter/jedi-vim#features to navigate around Python code.

I read through all the layers from SpaceVim and it seems that auto-completion is done through Tag management ('tag' layer)

I wanted to do navigation without having to manage generate or manage tags. One option would be installing vim-jedi as a custom plugin and just enabling the completion feature and choosing a hotkey for it.

I wanted to see if there's a more integrated way of navigating using Jedi with SpaceVim (i.e. I missed something obvious, which is very possible) or if the only recommended and/or support way was through tags.

Thanks!

**Comment by wsdjeg** [comment]
@rezende  if you are editing python file, you need to enable `lang#python` layer, and in this layer vim-jedi or deoplete-jedi will be loaded, which provides many features for python.

for jump to defenition position of synbol, the key binding is `g d`.

**Comment by rezende** [comment]
@wsdjeg Like I said it was very possible I was missing something obvious. Now I see it's documented under the `g` commands. Thanks again.

I will test and close this soon.

**Comment by wsdjeg** [comment]
@rezende hello, does this issue still exist?

**Comment by rezende** [comment]
@wsdjeg It seems like using `gd` just takes me to the definition in the same file, for example taking me to the import line. It never jumps across files to find the right definition, as I was used to with vim-jedi.

Is this some configuration I am missing?

**Comment by wsdjeg** [comment]
oh, it seems a bug of python layer, we should regester a go to defintion postion command.

**Comment by wsdjeg** [comment]
jedi-vim's implementation has some bug, if the file has not been saved, it will report errors:

```
Traceback (most recent call last):
  File "/home/wsdjeg/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/jedi_vim.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/wsdjeg/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/jedi_vim.py", line 279, in goto
    vim.command('tjump %s' % tagname)
vim.error: Vim(tjump):E429: File "/home/wsdjeg/SpaceVim/SpaceVim/main.py" does not exist
```

 I will warpper a function for this feature.

BTW, the only thing it does is just run `vim.command('tjump %s' % tagname)` which can be   implement in vim script.

**Comment by rezende** [comment]
Hey! Thanks for looking into it!

I don't if this was fixed or not but right now my spacevim is on commit `5030e0f1` and `gd` is working the same way.

But I realized that `<leader>d` works exactly as I thought `gd` should, which is that I wanted. If you need or want extra info just ask.

Att.

**Comment by wsdjeg** [comment]
@rezende hello, what does `<Leader>d` mapping to ?

you can check it via `:map <Leader>d`

**Comment by L-stt** [comment]
@rezende It works well for me, what is your custom config? do you enable lsp layer for python?

**Comment by wsdjeg** [comment]
Thanks for your info. in current version of SpaceVim. `gd` just call same function as what `<Leader>d` does in python file.

Shidong Wang
wsdjeg@outlook.com

________________________________________

**Comment by yinzhenhua** [comment]
when I write some code in gvim, the new window will pop up about jedi. So the bug is fixed? or will I change the autocomplete plug?.
My environment is: windows 10, python 2.7.15, gvim 8.0
thanks.

**Comment by Shougo** [comment]
set completeopt-=preview

**Comment by yinzhenhua** [comment]
>           set completeopt-=preview

I added this to _vimrc file，and the same as before.
