### ISSUE TITLE
Disable set spell and set list for Go

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1868]
## Expected behavior, english is required
The golang layer is setting the spell enabled for the go filetype and set list option also.
I would like a way to be able to avoid that, since It is just messing and making most of my codebase marked as red :)

## The reproduce ways from Vim starting (Required!)
Open a go file.

**Comment by wsdjeg** [comment]
I get same errors when edit go file, I think the spell option should not  be enabled by default. BTW we have key bindings for toggle spell option, It is `SPC t S`

**Comment by crisidev** [comment]
Yes, I am using it, but I agree with you this should be the default.

**Comment by wsdjeg** [comment]
I just open an PR for this issue.

cc @ccojocar

**Comment by crisidev** [comment]
Thanks!
