### ISSUE TITLE
[QUESTION] How to toggle the shell

### ISSUE THREAD

**Issue by mictian** [wsdjeg/SpaceVim#1871]
Hi,

I would like to know how to toggle the shell and leave whatever process it has running.

My use case is that I am developing some backend code in node, and I would like to see the shell to start node, install npm deps, etc, and later on close it without killing the node process (so for example the server is still running).

The documentation [here](https://spacevim.org/layers/shell/) says that ```SPC '``` opens and closes the shell.  
But 
a) I cannot make the shortcut work to close the shell  
b) how can I close it without killing the process running?

Finally, is it possible to show the shell only in one buffer?
If I have multiple files open, then open the shell, the shell will appear for all buffers.

Thanks in advance,
Mictian

**Comment by wsdjeg** [comment]
I recommand to use gitter for usage question.

**Comment by wsdjeg** [comment]
and if you think It is a type in doc or website, then you can create a  issue.

**Comment by mictian** [comment]
Yes! sorry, that make all the sense :+1:
