### ISSUE TITLE
Multiple occurrence in a single line shows as multiple candidates in flygrep.

### ISSUE THREAD

**Issue by 0x161e-swei** [wsdjeg/SpaceVim#1873]
This issue relates to FlyGrep only I believe
It can be reproduced withou SpaceVim.

## Expected behavior, english is required
E.g. I have a file as following:
```
hello hello hello
```
And search with  command `:FlyGrep<CR>hello`  gives result as:
```
hello:1:1:hello hello hello
hello:1:7:hello hello hello
hello:1:13:hello hello hello
```
## The reproduce ways from Vim starting (Required!)
Search with `:FlyGrep<CR>hello` in file with multiple occurrences of 'hello'
## Debug info

N/A

## Screenshots

N/A

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

Is this is an expected behavior (feature) or a bug?
If it is indeed a feature, could you please justify why?

**Comment by wsdjeg** [comment]
@0x161e-swei what is the file name of buffer? is it just `hello`?

**Comment by 0x161e-swei** [comment]
@wsdjeg I have tried `hello` and `test`...both gave me the same result.

**Comment by wsdjeg** [comment]
ok, It is a bug, this issue should not happed if the file name has a suffix， such as `hello.txt`

**Comment by 0x161e-swei** [comment]
In fact, even with a suffix like `hello.txt`, I am able to reproduce this on both mint 18.2 and RHEL 7.5....as following:
```
hello.txt:1:1:hello hello hello
hello.txt:1:7:hello hello hello
hello.txt:1:13:hello hello hello
```

**Comment by wsdjeg** [comment]
@0x161e-swei can you test latest version of flygrep? I have fixed it.

**Comment by 0x161e-swei** [comment]
Yes, it works with my `rg` and `ag`. Thanks!
