### ISSUE TITLE
`g:spacevim_project_rooter_patterns` not work

### ISSUE THREAD

**Issue by s97712** [wsdjeg/SpaceVim#1874]
I try to use
```
[[layers]]
name="lang#javascript" 
```
or
```
call add(g:spacevim_project_rooter_patterns, 'package.json')
```
But it not work, I think it should be related to the loading order.

## env
vim: 8.1
spacevim: 0.9

**Comment by wsdjeg** [comment]
I can reproduce it, It is a bug of SpaceVim's project manager.

**Comment by s97712** [comment]
I found the reason, you can see this #1880

**Comment by wsdjeg** [comment]
OK, can you reopen that pr, I will check it, if it can fix this issue, I will merge it.
