### ISSUE TITLE
Differences between custom before and after functions

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1876]
Hello,
I am trying to understand what should go into myspacevim#before and myspacevim#after functions called by init.toml.

Currently I have everything in myspacevim#before function and it works fine, but I am sure I am not doing the right thing...

Is there any documentation about this?

Thanks for your awesome work!

**Comment by wsdjeg** [comment]
sorry, there is no documentation about this, I will improve the SpaceVim's boostrap logic. and add some documentation about the differences of these two options.

**Comment by wsdjeg** [comment]
@crisidev I have update the doc, any other info should we add?

**Comment by crisidev** [comment]
Nope, thanks, we can close this.
