### ISSUE TITLE
How change the default code fomarter?

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#1878]
How to replace the default formater (yarp) for python to Black(https://github.com/ambv/black)?

**Comment by wsdjeg** [comment]
for usage question, please use gitter or google mail group. issue tracker is only for feature request and bug report. and if you want to change the formater, you need to know what plugin SpaceVim is using for format code, and read the help of the that plugin. the add the plugin config to the bootstrap function.

**Comment by y9c** [comment]
So, which plugin in SpaceVim is for formating python code?

**Comment by crisidev** [comment]
It is either neoformat or ale or syntastic. I am running black with ale and works out of the box..

**Comment by wsdjeg** [comment]
if you mean the key binding `spc b f`, it is neoformat.
