### ISSUE TITLE
help: how to call func on on fzf layer

### ISSUE THREAD

**Issue by emaxerrno** [wsdjeg/SpaceVim#1882]
```
function! override#before() abort
endfunction


function! override#after() abort
  call SpaceVim#layers#load('fzf')
  command! -bang -nargs=* Chaser call fzf#run(
      \ fzf#wrap({'source': 'git grep --line-number'.shellescape(<q-args>) ,
      \ 'column':  0,
      \ 'down' : '40%',
      \ 'dir': systemlist('git rev-parse --show-toplevel')[0],
      \ 'options': ['--reverse'],
      \ }, <bang>0))

    call SpaceVim#mapping#space#def('nnoremap', ['p', 'r'], 'Chaser', 'git grep', 1)
endfunction

```

I have my layers override to this. 

I'm having a hard time understanding how to call fzf functions. 

I wanted to use this:

``` https://github.com/junegunn/fzf.vim/blob/1b01a5069b216ae0ac40b24788b27ce1e0c7c6ea/autoload/fzf/vim.vim#L678 
```
Via:
```
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   { 'dir': systemlist('git rev-parse --show-toplevel')[0] }, <bang>0)

```

From the readme but after loading the fzf layer, i can't seem to get that function defined. 

Thanks!

**Comment by wsdjeg** [comment]
Please use issue template, and make sure your bootstrap fucntion is loaded successfully.

**Comment by emaxerrno** [comment]
Hi Sure, happy to. I don't think this is an issue w/ the behavior, that's why i didn't follow, i think spacevim works as advertise. I'm just trying to figure out how to hook into the lifecycle events to load a function. 


## Expected behavior, english is required

spacevim i think is behaving as expected

## The reproduce ways from Vim starting (Required!)

## Debug info

in asciinema

## Screenshots

https://asciinema.org/a/zIrGFuqidqB5WFwAe19z7g0QQ

**Comment by emaxerrno** [comment]
@wsdjeg  - let me know if that makes sense.

**Comment by wsdjeg** [comment]
fzf layer do not included the plugin `fzf.vim`, This plugin is just a wrap of fzf command, in fzf layer, we wrap the command our self.

so the only function you can use is `fzf#run(.....)` but you can also use custom_plugins to add fzf.vim

you also should not load layer in bootstrap function, to load a layer, you should edit toml file.

**Comment by wsdjeg** [comment]
@senior7515 I have recheck this issue, here is some step you need to done.

1. if you want to load a layer, for example `fzf` layer, you need to edit your init.toml file:

```toml
[[layers]]
    name = 'fzf'
```
2. by default fzf layer do not includ fzf.vim, if you want to use this plugin, please use custom plugin list:

```toml
[[custom_plugins]]
 name = 'junegunn/fzf.vim'
 merged = 0
```

3. to defind custom command, you can use bootstrap_before or bootstrap_after, so, this is ok:

```vim
function! override#after() abort
  command! -bang -nargs=* Chaser call fzf#run(
      \ fzf#wrap({'source': 'git grep --line-number'.shellescape(<q-args>) ,
      \ 'column':  0,
      \ 'down' : '40%',
      \ 'dir': systemlist('git rev-parse --show-toplevel')[0],
      \ 'options': ['--reverse'],
      \ }, <bang>0))
endfunction
```

4. if you want defind `SPC` key bindings, you need to use this instead

```vim
call SpaceVim#custom#SPC('nore', ['p', 'r'], 'Chaser', 'git grep', 1)
```

**Comment by emaxerrno** [comment]
@wsdjeg  - it worked! thanks!
