### ISSUE TITLE
Make g:vimfiler_quick_look_command configurable

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1888]
## Expected behavior, english is required
I am on mac and I don't have sublime installed. Once calling quick-look from Vimfiler, I get an error:
```
[vimfiler] g:vimfiler_quick_look_command "/Applications//Sublime\ Text.app/Contents/MacOS/Sublime\ Text" is not executable.
```

Can we make this option configurable here: https://github.com/SpaceVim/SpaceVim/blob/3870759a2aba7eceb930c17b11d13bd68a41056c/config/plugins/vimfiler.vim#L25-L30

## The reproduce ways from Vim starting (Required!)
Try to quicklook a file from VimFiler on mac without having Sublime installed

**Comment by wsdjeg** [comment]
@crisidev Thanks，I think we should change it to:

```vim
 if has('mac') 
   let g:vimfiler_quick_look_command = 
         \ get(g:, 'vimfiler_quick_look_command', '/Applications//Sublime\ Text.app/Contents/MacOS/Sublime\ Text') 
 else 
   let g:vimfiler_quick_look_command = 
        \ get(g:, 'vimfiler_quick_look_command', 'gloobus-preview') 
 endif 
``` 

what do you think should be the default quick look command? and PR is welcome.

**Comment by crisidev** [comment]
I will send a pr today!

**Comment by crisidev** [comment]
I would use `qlmanage -p` which uses the Preview.app and it is available on every OSX system.
