### ISSUE TITLE
Development doc for language specific key bindings

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#1899]
All language specified key bindings are started with `SPC l` prefix.

we recommended to keep same language specified key bindings for different languages:

| Key Binding | Description                                      |
| ----------- | ------------------------------------------------ |
| `SPC l r`   | start a runner for current file                  |
| `SPC l e`   | rename symbol                                    |
| `SPC l d`   | show doc                                         |
| `SPC l i r` | remove unused imports                            |
| `SPC l i s` | sort imports with isort                          |
| `SPC l s i` | Start a language specified inferior REPL process |
| `SPC l s b` | send buffer and keep code buffer focused         |
| `SPC l s l` | send line and keep code buffer focused           |
| `SPC l s s` | send selection text and keep code buffer focused |
| `g d` | jump to definition |

**Comment by icearith** [comment]
- Run a file(for Golang, a package)
- Show docs
- Show definition
- Go to definition
- Import related staff 

As a developer with 3 years experience on golang, python and java. The above 5 things are the ones I really care about.

**Comment by wsdjeg** [comment]
What is the difference between `Show definition` and `Go to definition`? How do you show definition on general IDE?

We have a built-in code runner plugin, and we can register a commnd in language layer, for example in `lang#lua` layer, we use  this sinippet to register command, `%s` will be replaced as the file name of current file.

```vim
call SpaceVim#plugins#runner#reg_runner('lua', 'lua %s')
```

and here is key binding:

```vim
call SpaceVim#mapping#space#langSPC('nmap', ['l','r'], 'call SpaceVim#plugins#runner#open()', 'execute current file', 1)
```

**Comment by icearith** [comment]
@wsdjeg the difference is: 

Show definition: show a variable's type, a function's schema, like: 
![image](https://user-images.githubusercontent.com/2555093/44979807-ab65be00-afa0-11e8-9226-fde439f02599.png)

![image](https://user-images.githubusercontent.com/2555093/44979867-d8b26c00-afa0-11e8-8176-11c71b79a862.png)

While `go to definition` will leave the context you are woking on, and move to the Implementation of the identifier. 

The former is often heavily used in coding stage, when you need to have a quick info of  a variable(eg. check its type).

The latter one is heavily used in code review, where you need to read the concrete implementation of the method or functions under your cursor. 

Is it clear?

**Comment by wsdjeg** [comment]
how about using `SPC l t` or `SPC l k` for show type? for `go to definition` we are using `g d`.

**Comment by icearith** [comment]
@wsdjeg why not just keep the current one `SPC l h` ? Do you have any reason for this ?

**Comment by wsdjeg** [comment]
ok, just keep the `SPC l h` to show go info.
