### ISSUE TITLE
spacevim canot work on win10 64

### ISSUE THREAD

**Issue by csbde** [wsdjeg/SpaceVim#1901]
## Env
OS: win10 64bit
VIM:  64bit gui version with python support
Python: 64bit
Config: default spacevim config

echo has("python")  return value is 1 

i have tried reinstall gvim and spacevim, the same error. 

![image](https://user-images.githubusercontent.com/478239/42204158-6fb4ecee-7ed3-11e8-9b33-0ef5d6bb5511.png)

**Comment by wsdjeg** [comment]
`echo has("python") return value is 1` does not means you can use `:py` command, you can check it via `:py import vim`.

**Comment by wsdjeg** [comment]
Ok, I will improve the py check in plugin manager.
