### ISSUE TITLE
start fail at first time after install

### ISSUE THREAD

**Issue by rh-chen** [wsdjeg/SpaceVim#1912]
rh@nt2444  ~  vim
Error detected while processing function SpaceVim#end[78]..SpaceVim#plugins#load[2]..zvim#plug#begin[11]..dein#begin[1]..dein#util#_begin[6]..dein#util#_error[1]..<SNR>46_msg2list:
line    1:
E121: Undefined variable: v:t_list
E15: Invalid expression: type(a:expr) ==# v:t_list ? a:expr : split(a:expr, '\n')
Error detected while processing function SpaceVim#end[78]..SpaceVim#plugins#load[2]..zvim#plug#begin[11]..dein#begin[1]..dein#util#_begin[6]..dein#util#_error:
line    1:
E714: List required
Press ENTER or type command to continue

![image](https://user-images.githubusercontent.com/22390932/42301369-68fc76fe-8047-11e8-9497-3aa6ccfea85a.png)

**Comment by wsdjeg** [comment]
see #1736 and #1723

**Comment by rh-chen** [comment]
thank you very much.  it's fixed. 

just excute: 
 sed -i "s/'dein'/'neobundle'/" ~/.SpaceVim/autoload/SpaceVim.vim

**Comment by wsdjeg** [comment]
You **should** use spacevim config file `~/.SpaceVim.d/init.toml` instead of edit content in `~/.SpaceVim`
