### ISSUE TITLE
[feature] Reordering elements on the tabline

### ISSUE THREAD

**Issue by MrQubo** [wsdjeg/SpaceVim#1917]
The new feature should add the possibility of reordering elements on the tabline.

Most editors do have such a feature.
It's a handy feature, because you're able to put similar files next to each other for faster switching between them with Alt + LeftArrow/RightArrow shortcuts.

For example in Firefox I can move the tab to the left/right with CTRL + SHIFT + PgUp/PgDown.

We could use ALT + CTRL + LeftArrow/RightArrow.

**Comment by wsdjeg** [comment]
sorry for later reply, this feature will be added in v1.2.0, the tabline will be improved in that released.

**Comment by wsdjeg** [comment]
in neovim/vim `ctrl-alt-right` send same code as `right`. how about using `Ctrl-Shift-Right` and `Ctrl-Shift-Left`?

**Comment by MrQubo** [comment]
> in neovim/vim `ctrl-alt-right` send same code as `right`. how about using `Ctrl-Shift-Right` and `Ctrl-Shift-Left`?

`Ctrl-Shift-Right` and `Ctrl-Shift-Left` are good. Of course, those should be customizable anyway.

**Comment by wsdjeg** [comment]
Move to google mail list.

**Comment by wsdjeg** [comment]
@MrQubo `ctrl-shift-left/right` key binding has been added, but now it only for tabpage, not for buffer list.

**Comment by wsdjeg** [comment]
https://groups.google.com/d/msgid/spacevim/ME3P282MB1842317B0D75764888D5DEEFD4209%40ME3P282MB1842.AUSP282.PROD.OUTLOOK.COM
