### ISSUE TITLE
[Feature] Onboard git-time-metrics plugin

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#1921]
Hello,
I am heavily using https://github.com/git-time-metric/gtm-vim-plugin to track how much time I am staying on projects.

The plugin requires https://github.com/git-time-metric/gtm to be installed and provides a nice status line feature I am unable to include in spacevim without heavy modification.

I think this could be a good addition to the git workflow system implemented in SpaceVim.

**Comment by wsdjeg** [comment]
@crisidev I just add this feature, but git-time-metric/gtm-vim-plugin  plugin has too many bugs, and also too slow, I will rewrite the function in SpaceVim.

1. slow, I will use SpaceVim job api to run this command
2. wrong error, when open plugin buffer, it shows me wrong error ( no gtm in PATH)

**Comment by crisidev** [comment]
Oh, this is amazing. I noticed the official plugin is very slow. Thanks for your work on this!
