### ISSUE TITLE
SPUpdate indentLine: Updating failed

### ISSUE THREAD

**Issue by milkdeliver** [wsdjeg/SpaceVim#1925]
## The reproduce ways from Vim starting (Required!)
git -C ~/.Spacevim pull
SPUpdate

then a plugin update failed
x IndentLine: Updating failed

## Screenshots
![image](https://user-images.githubusercontent.com/3108407/42413473-64d4b268-8253-11e8-9bd4-c8a114b511a7.png)
![image](https://user-images.githubusercontent.com/3108407/42413481-a67cf338-8253-11e8-8814-76ef59bc2df9.png)

**Comment by milkdeliver** [comment]
Solution
```
cd /Users/<yourname>/.cache/vimfiles/repos/github.com
rm -rvf Yggdroot/
```
 Open vim again then the Plugin will be installed again.

**Comment by wsdjeg** [comment]
thanks
