### ISSUE TITLE
flygrep crash after on startify screen

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#1927]
## Expected behavior, english is required

Flygrep works as expected.

## The reproduce ways from Vim starting (Required!)
Start a vim editor,
Press `SPC s / `, then it would crash.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
SpaceVim layers:

- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete
- chat:                 not loaded          https://spacevim.org/layers/chat
+ checkers:                 loaded          https://spacevim.org/layers/checkers
- chinese:              not loaded          https://spacevim.org/layers/chinese
+ colorscheme:              loaded          https://spacevim.org/layers/colorscheme
+ core/banner:              loaded          no exists
+ core/statusline:          loaded          no exists
+ core/tabline:             loaded          no exists
+ core:                     loaded          no exists
- cscope:               not loaded          https://spacevim.org/layers/cscope
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp
+ debug:                    loaded          https://spacevim.org/layers/debug
+ denite:                   loaded          https://spacevim.org/layers/denite
+ edit:                     loaded          no exists
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits
+ format:                   loaded          no exists
- fzf:                  not loaded          https://spacevim.org/layers/fzf
- games:                not loaded          no exists
+ git:                      loaded          https://spacevim.org/layers/git
- github:               not loaded          https://spacevim.org/layers/github
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          no exists
- lang/c:               not loaded          https://spacevim.org/layers/lang/c
- lang/clojure:         not loaded          no exists
- lang/crystal:         not loaded          no exists
- lang/csharp:          not loaded          https://spacevim.org/layers/lang/csharp
- lang/dart:            not loaded          https://spacevim.org/layers/lang/dart
- lang/elixir:          not loaded          https://spacevim.org/layers/lang/elixir
+ lang/go:                  loaded          https://spacevim.org/layers/lang/go
- lang/haskell:         not loaded          https://spacevim.org/layers/lang/haskell
- lang/html:            not loaded          https://spacevim.org/layers/lang/html
- lang/java:            not loaded          https://spacevim.org/layers/lang/java
+ lang/javascript:          loaded          https://spacevim.org/layers/lang/javascript
- lang/json:            not loaded          no exists
- lang/julia:           not loaded          no exists
- lang/kotlin:          not loaded          no exists
- lang/lisp:            not loaded          https://spacevim.org/layers/lang/lisp
+ lang/lua:                 loaded          https://spacevim.org/layers/lang/lua
- lang/markdown:        not loaded          https://spacevim.org/layers/lang/markdown
- lang/ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml
- lang/perl:            not loaded          no exists
- lang/php:             not loaded          https://spacevim.org/layers/lang/php
- lang/pony:            not loaded          no exists
- lang/ps1:             not loaded          no exists
- lang/puppet:          not loaded          no exists
+ lang/python:              loaded          https://spacevim.org/layers/lang/python
- lang/r:               not loaded          no exists
- lang/ruby:            not loaded          https://spacevim.org/layers/lang/ruby
- lang/rust:            not loaded          no exists
- lang/scala:           not loaded          no exists
- lang/sh:              not loaded          no exists
- lang/solidity:        not loaded          no exists
- lang/swig:            not loaded          no exists
- lang/tmux:            not loaded          no exists
- lang/toml:            not loaded          no exists
- lang/typescript:      not loaded          https://spacevim.org/layers/lang/typescript
- lang/vim:             not loaded          https://spacevim.org/layers/lang/vim
- lang/xml:             not loaded          no exists
- lang:                 not loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell
+ sudo:                     loaded          no exists
+ tags:                     loaded          https://spacevim.org/layers/tags
- tmux:                 not loaded          no exists
- tools/dash:           not loaded          https://spacevim.org/layers/tools/dash
- tools/screensaver:    not loaded          no exists
- tools:                not loaded          https://spacevim.org/layers/tools
+ ui:                       loaded          https://spacevim.org/layers/ui
- unite:                not loaded          https://spacevim.org/layers/unite
- vim:                  not loaded          no exists

## Screenshots
![image](https://user-images.githubusercontent.com/2555093/42485751-9b5da0e0-842b-11e8-82f0-a5f9f5f1462f.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by crisidev** [comment]
It happens to me also from inside a project

**Comment by wsdjeg** [comment]
Before pressing `SPC s /`, just run `:py import vim`, I think this error will disappear.

**Comment by crisidev** [comment]
Yep, it does.

**Comment by wsdjeg** [comment]
@icearith I have fixed it in new PR, can you test it?

**Comment by crisidev** [comment]
It works fine. Thanks as usual for the quick fix.
