### ISSUE TITLE
Plugins and config are not loaded for lang layers

### ISSUE THREAD

**Issue by ksamborski** [wsdjeg/SpaceVim#1928]
I have wondered why I had empty language specified menu. I've searched, debugged and found this:

autoload/SpaceVim/plugins.vim:
51: let p = SpaceVim#layers#{a:layer}#plugins()
...
59: call SpaceVim#layers#{a:layer}#config()

but when layer name is "lang/php" the slash character should be substituted for "#". I came up with something like this:

let p = SpaceVim#layers#{substitute(a:layer, "\/", "#", "")}#plugins()

Could you fix it?

**Comment by wsdjeg** [comment]
what is the issue？PHP layer can not be loaded?

**Comment by ksamborski** [comment]
The issue is that the two functions called SpaceVim#layers#lang#php#plugins and SpaceVim#layers#lang#php#config are not executed at all. It is that because of their names.

As you know the a:layer variable has the layer name but in case of lang layers it has "/" character instead of "#". So it is looking for SpaceVim#layers#lang/php#plugins which doesn't exist.

**Comment by wsdjeg** [comment]
@ksamborski I can not reproduce your issue, before call that function, all layer name has been fixed.

**Comment by wsdjeg** [comment]
and there is no layer named `lang/php`. please read : 

https://spacevim.org/layers/lang/php/
