### ISSUE TITLE
[bug]SpaceVim 0.9-dev,vim startup report error

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#1935]
SpaceVim 0.9-dev,vim startup report error,error message:

Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..zvim#plug#begin..dein#begin..dein#util#_begin..dein#util#_error..<SNR>48_msg2list:
line    1:
E121: Undefined variable: v:t_list
E15: Invalid expression: type(a:expr) ==# v:t_list ? a:expr : split(a:expr, '\n')
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..zvim#plug#begin..dein#begin..dein#util#_begin..dein#util#_error:
line    1:
E714: List required
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
same as #1723
