### ISSUE TITLE
Icons displayed incorrectly in Debian stretch gnome-terminal

### ISSUE THREAD

**Issue by pietrushnic** [wsdjeg/SpaceVim#1938]
## Expected behavior, english is recommend

Icons should display correctly.

Despite setting `Edit->Profile Preferences->General->Custom font` to `Droid
Sans Mono for Powerline Plus Nerd File Types Mono Regular 12` I still can't
display various icons correctly (see screenshots). This is probably more of
terminal/font issue, but I SpaceVim look annoying without setting it correctly.

## Environment Information

- OS: linux
- vim version: 8.0(1-197, 322, 377-378, 550, 703, 706-707)
- neovim version: -
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 
- Debian stretch
- Gnome Terminal: 3.22.2

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

Run Vim:

```
vim
```

### SpaceVim Options :

```viml
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_api_json_true = v:null
g:spacevim_auto_disable_touchpad = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_autocomplete_parens = 1
g:spacevim_background = 'dark'
g:spacevim_buffer_index_type = 4
g:spacevim_checkinstall = 1
g:spacevim_colorscheme = 'solarized'
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_custom_color_palette = []
g:spacevim_custom_plugins = []
g:spacevim_debug_level = 1
g:spacevim_default_indent = 2
g:spacevim_disabled_plugins = []
g:spacevim_enable_ale = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_enable_cursorline = 1
g:spacevim_enable_debug = 0
g:spacevim_enable_googlesuggest = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_language_specific_leader = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_neomake = 1
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_enable_statusline_display_mode = 0
g:spacevim_enable_statusline_mode = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_ycm = 0
g:spacevim_error_symbol = '✖'
g:spacevim_expand_tab = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_filetype_icons = {}
g:spacevim_force_global_config = 0
g:spacevim_gitcommit_issue_icon = ''
g:spacevim_gitcommit_pr_icon = '䄎'
g:spacevim_github_username = ''
g:spacevim_guifont = ''
g:spacevim_hiddenfileinfo = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_info_symbol = 'ⓘ'
g:spacevim_keep_server_alive = 1
g:spacevim_language = ''
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_leader_guide_flatten = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_leader_guide_max_size = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_leader_guide_vertical = 0
g:spacevim_lint_on_save = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_max_column = 120
g:spacevim_plugin_bundle_dir = '/home/user/.cache/vimfiles/'
g:spacevim_plugin_manager = 'dein'
g:spacevim_plugin_manager_processes = 16
g:spacevim_plugin_name = 'vim-grepper'
g:spacevim_project_rooter_automatically = 1
g:spacevim_project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
g:spacevim_realtime_leader_guide = 1
g:spacevim_relativenumber = 1
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_sidebar_width = 30
g:spacevim_simple_mode = 0
g:spacevim_smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
g:spacevim_statusline_separator = 'arrow'
g:spacevim_statusline_unicode_symbols = 1
g:spacevim_terminal_cursor_shape = 2
g:spacevim_version = '0.9.0-dev'
g:spacevim_vim_help_language = 'en'
g:spacevim_vimcompatible = 0
g:spacevim_warning_symbol = '⚠'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_windows_index_type = 0
g:spacevim_windows_leader = 's'
g:spacevim_windows_smartclose = 'q'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(vim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:44:23] [ Info ] find config file: /home/user/.SpaceVim.d/init.toml
[ SpaceVim ] [15:44:23] [ Info ] loadding cached config: /home/user/.cache/SpaceVim/conf/_home_user__SpaceVim_d_init_toml.json
```
## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
![missing_fonts](https://user-images.githubusercontent.com/1071894/42723642-2c5e57a4-8762-11e8-9cf9-905163edc25b.png)
![icons_issue](https://user-images.githubusercontent.com/1071894/42723644-2e16ac04-8762-11e8-940c-61691d2176c5.png)

**Comment by wsdjeg** [comment]
sorry, I can not fix this issue, maybe you need to install another nerd fonts, you can choose them in : 

https://gitter.im/ryanoasis/nerd-fonts

**Comment by wsdjeg** [comment]
you can also try to open such file, and see if there is any differences.

https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim

**Comment by pietrushnic** [comment]
@wsdjeg webdevicons also have problems (please check screenshot).

![webdevicons](https://user-images.githubusercontent.com/1071894/42727248-7157e546-87a3-11e8-8491-5f7f278a386a.png)

I'm not sure I get the problem, do you mean you cannot identify fonts that are required to correctly render characters used in SpaceVim? My understanding would be that SpaceVim distribution installer should deploy all required components, am I missing something?

**Comment by wsdjeg** [comment]
@pietrushnic SpaceVim install script has downloaded the font, but I do not know why your terminal can not display this icons.

https://github.com/SpaceVim/SpaceVim/blob/master/docs/install.sh#L355-L384
