### ISSUE TITLE
press Ctrl + V，enter the Visual Line mode, can not select all content

### ISSUE THREAD

**Issue by kevinadmin** [wsdjeg/SpaceVim#1943]
when i press Ctrl + V，enter the Visual Line mode, but can not select all content
****
![image](https://user-images.githubusercontent.com/6966034/42726369-c2ca6d82-87c5-11e8-9d83-e589488c5036.png)

can not move right with "l"

**Comment by wsdjeg** [comment]
This should be a usage question of vim.

**Comment by wsdjeg** [comment]
and you can use gitter room for such question, issue is only for bug report and feature request.
