### ISSUE TITLE
FlyGrep Preview Toggle & Custom Mapping

### ISSUE THREAD

**Issue by techgaun** [wsdjeg/SpaceVim#1947]
## Expected behavior, english is required

I think we should be able to configure custom mapping for flygrep ideally. Because of https://github.com/SpaceVim/SpaceVim/blob/d0c7c389ff78724e39f1b42fe5366cf905c8016e/autoload/SpaceVim/plugins/flygrep.vim#L442 and https://github.com/SpaceVim/SpaceVim/blob/652b7100992a88b2f0cb1408545544fece2c912e/autoload/SpaceVim/layers/denite.vim#L31, it may not be working as expected.

I really like flygrep and have been using a lot but toggling search result preview does not seem to be working as expected. Please advise if I am not looking at this correctly. Thanks!

**Comment by wsdjeg** [comment]
flygrep preview key binding is not mapping, so It will not conflict with denite's key binding.

But we should also provide an option For changging flygrep's default key binding.

**Comment by wsdjeg** [comment]
> but toggling search result preview does not seem to be working as expected. 

what do you mean? you can not toggle searching result preview?

**Comment by techgaun** [comment]
> flygrep preview key binding is not mapping, so It will not conflict with denite's key binding.

@wsdjeg thanks for the update. I am not sure if I follow this properly and probably need to look deeper (which I have not done). When I press <C-p> it opens denite file_rec minibuffer. Can you point me on right direction on how to use it?

> But we should also provide an option For changging flygrep's default key binding.

This would be absolutely awesome.

**Comment by wsdjeg** [comment]
just press `<C-p>` after flygrep is openned.

https://asciinema.org/a/1rh6yz5N3dKDkHy4MwtMzyIdP

**Comment by techgaun** [comment]
@wsdjeg it is working fine as expected. thanks for checking. also, is there a keybinding for opening/closing FlyGrep buffer so that our search are preserved after opening the file?

**Comment by wsdjeg** [comment]
@techgaun no, in crrent version of flygrep, it does not support resume flygrep windows, but it support searching histroy, you can use `<Up>` and `<Down>` to switch between searching history.

even though flygrep key bindings will not conflict with vim mappings, but maybe we should profile function for setting them.

**Comment by wsdjeg** [comment]
@techgaun hello, I just add a new plugin, `SPC s J`, with this cammand, you can search cursor symbol in current dir. the result will be put into quickfix list. then you can use quickfix list key binding.

so any other think do you think should be done with flygrep?

**Comment by techgaun** [comment]
@wsdjeg yeah I think thats good. Thanks for the update
