### ISSUE TITLE
search failed

### ISSUE THREAD

**Issue by Land-Fairy** [wsdjeg/SpaceVim#1950]
When using SPC + s + s to search,  result is below.
![_20180717193046](https://user-images.githubusercontent.com/22864341/42814792-f1ea8898-89f7-11e8-9d43-1c5cfc5be326.png)
but, if I use / or ? to search, successed
My env:
    Gvim 8.1  + win 10

**Comment by wsdjeg** [comment]
@Land-Fairy if you get errors, please use issue template, you need to post runtime logs.
