### ISSUE TITLE
icon display incorrectly on Windows Gvim

### ISSUE THREAD

**Issue by zgpio** [wsdjeg/SpaceVim#1955]
## Expected behavior
With the nerd font I use, the icons in the `tabline/statuline/startify` and `fileformat` should be correctly display.

## The reproduce ways from Vim starting (Required!)
I use [gvim8.1](https://github.com/vim/vim-win32-installer) on Windows.
I installed nerd font from [here](https://github.com/ryanoasis/nerd-fonts/releases). 
Problem #1701 isn't solved. 

Put the repo `vim-devicons` into `.../pack/git/opt/`, and then change as follow, the icons display correctly:
```bash
diff --git a/config/plugins/vim-startify.vim b/config/plugins/vim-startify.vim
index b5d23ae..d61479c 100644
--- a/config/plugins/vim-startify.vim
+++ b/config/plugins/vim-startify.vim
@@ -69,8 +69,10 @@ if g:spacevim_enable_tabline_filetype_icon
     return empty(icon) ? ' ' : icon
   endfunction

+  packadd vim-devicons
   function! StartifyEntryFormat()
-    return 'FileIcon(entry_path) ."  ". entry_path'
+    "return 'FileIcon(entry_path) ."  ". entry_path'
+    return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
   endfunction

 endif
```
## Screenshots
我安装的字体是能够正确显示icons的, 但SpaceVim的tabline/statusline/startify上的icons都不能正常显示(包括fileformat的icon).
With the nerd font I use, the icons in `file.vim` display well in the buffer, but not the icon of tabline/statuline/startify.
As follow:
![default](https://user-images.githubusercontent.com/19503791/43041685-1e12be4a-8d9a-11e8-93a8-79f75afa68eb.png)

![default](https://user-images.githubusercontent.com/19503791/42862535-7ac3e55c-8a92-11e8-855b-0b1058c45253.png)

但是`vim-devicons`插件可以正常显示这些icons, Windows+gvim+SpaceVim不能正常显示?
Also, the `vim-devicons` plugin can display the icons from `file.vim`, but spacevim can't display them correctly in the tabline/statuline/startify on windows gvim.

让`config/plugins/vim-startify.vim`文件中的`FileIcon`函数直接返回`file.vim`中的图标, 
![default](https://user-images.githubusercontent.com/19503791/43041551-8e64451e-8d96-11e8-95a1-475b534139f6.png)
这是能够正常显示的(这说明不是字体的原因):
![default](https://user-images.githubusercontent.com/19503791/43041575-1809366c-8d97-11e8-819f-6f7df9f20226.png)

但是让`file.vim`中`s:filetypeIcon`函数直接返回图标
![default](https://user-images.githubusercontent.com/19503791/43041594-9206170a-8d97-11e8-874a-491ac30b84c1.png)
这样乱码了:
![default](https://user-images.githubusercontent.com/19503791/43041598-9f190b5a-8d97-11e8-9bd5-92518ac10f1d.png)

Can't be fixed on 0.9.0 dev?

**Comment by zgpio** [comment]
I use Chinese for clearer explanation. Sorry about it.

**Comment by wsdjeg** [comment]
Please use issue template, and post your vim/neovim version.

**Comment by zgpio** [comment]
Updated, pls check it.

**Comment by wsdjeg** [comment]
sorry, I can not reproduce this issue, and  I am using spacevim's install script to install font.

**Comment by zgpio** [comment]
I check the `install.cmd` on `https://spacevim.org/quick-start-guide`, it does not include font install .

**Comment by wsdjeg** [comment]
sorry, font install only supportted in `install.sh`.

**Comment by zgpio** [comment]
I hope that the support for windows can be improved.

**Comment by wsdjeg** [comment]
if, you think vim-devicons can desplay well, you can try to modified SpaceVim, and if it desplay well, you can post a sceenshort.

**Comment by zgpio** [comment]
OK, I will try it.

**Comment by xylinkun** [comment]
我也遇到这个问题，试了好久没有解决，@zgpio 您解决了吗？

**Comment by zgpio** [comment]
I can't find the problem, but I can provide the following information:
I copy the `line 21-161` from the `file.vim` to `vim-startify.vim`, and replace `s:FILE.fticon` to `s:filetypeIcon`, it works:
![default](https://user-images.githubusercontent.com/19503791/44299413-cf31ce80-a327-11e8-858b-ff67297dddc6.png)
I guess the packaging of the api break it or other.
I need your help. Can you reproduce it on Windows Gvim? @wsdjeg

**Comment by wsdjeg** [comment]
> I copy the line 21-161 from the file.vim to vim-startify.vim, and replace s:FILE.fticon to s:filetypeIcon,

I can not understand this, please use git diff patch.

**Comment by zgpio** [comment]
It's too long if use `git diff`, copy from line 21 to 161.
Translation: 
① 拷贝file.vim文件第21行到161的内容到 SpaceVim 的 `vim-startify.vim` 中;
② 用s:filetypeIcon替换`vim-startify.vim`中的`s:FILE.fticon`, 然后startify的icon可以正常显示.

**Comment by zgpio** [comment]
My God, I found that only the following modifications, the icon can be displayed normally:
Translate to Chinese: 我发现仅仅修改一行就可以使icon正常工作. 
@wsdjeg 
```diff
diff --git a/autoload/SpaceVim.vim b/autoload/SpaceVim.vim
index 23bf1d0..dd48e52 100644
--- a/autoload/SpaceVim.vim
+++ b/autoload/SpaceVim.vim
@@ -163,7 +163,7 @@ let g:spacevim_enable_insert_leader    = 1
 " <
 let g:spacevim_plugin_bundle_dir
       \ = $HOME. join(['', '.cache', 'vimfiles', ''],
-      \ SpaceVim#api#import('file').separator)
+      \ '\')

```

**Comment by xylinkun** [comment]
奇怪了，同样的配置，我在公司的电脑上就显示为空白。

zgpio <notifications@github.com> 于2018年8月20日周一 下午7:35写道：

**Comment by zgpio** [comment]
There is no such problem on neovim-qt. I can't find a specific reason now.

**Comment by zgpio** [comment]
I got it. SpaceVim `set encoding` in `config/init.vim`, but it is to late. 
The reason NeoVim does not have this problem is that ` 'encoding' ("utf-8" is always used)`.
To fix it maybe need restruct init order of SpaceVim.
Translate to Chinese:
我终于知道了, SpaceVim 在 `config/init.vim`中设置`encoding`, 但是这太迟了.
NeoVim 没有这个问题的原因是 `它总是utf-8`
为了修复它, 可能需要重新组织初始化顺序, 还是你做修改吧! @wsdjeg 
正如下所示, 可以使startify/tabline/fileformat icon正常工作.
```diff
diff --git a/autoload/SpaceVim/api/file.vim b/autoload/SpaceVim/api/file.vim
index 87513c3..f1b3465 100644
--- a/autoload/SpaceVim/api/file.vim
+++ b/autoload/SpaceVim/api/file.vim
@@ -5,6 +5,7 @@
 " URL: https://spacevim.org
 " License: GPLv3
 "=============================================================================
+set encoding=utf-8
 scriptencoding utf-8
 let s:file = {}
```

**Comment by wsdjeg** [comment]
I have created a new pr for this issue, you can check it.
