### ISSUE TITLE
flygrep can't search some special characters like '(' `\'

### ISSUE THREAD

**Issue by fcying** [wsdjeg/SpaceVim#1956]
## Expected behavior, english is required
Can search for special characters

## The reproduce ways from Vim starting (Required!)
<SPC>s/
main(

## Screenshots
![image](https://user-images.githubusercontent.com/106934/42868176-3ccf847e-8aa4-11e8-95fd-9a7f4d85917a.png)
![image](https://user-images.githubusercontent.com/106934/42868216-56eebdb6-8aa4-11e8-86f3-c3454f11988a.png)

**Comment by wsdjeg** [comment]
you are using expr mode, you can switch to string mode, the key is `<C-e>` in flygrep.

**Comment by fcying** [comment]
![image](https://user-images.githubusercontent.com/106934/42879672-0620d5b6-8ac4-11e8-9488-11f3e677d3b0.png)
expr mode not support `\(`?

**Comment by wsdjeg** [comment]
@fcying when using `rg -e load\(` you will see:

```
Error parsing regex near 'load(' at character offset 4: Unclosed parenthesis.
(Hint: Try the --fixed-strings flag to search for a literal string.)
```
rg will throw a error if the pattern is not a correct regex.

**Comment by wsdjeg** [comment]
I just fix it, but the highlight has some errors.

![2018-07-21-08 58 31](https://user-images.githubusercontent.com/13142418/43030643-90953e0a-8cc5-11e8-8bd9-160a70c47c84.png)
