### ISSUE TITLE
Consistantly getting errors on startup even with fresh copy of Spacevim

### ISSUE THREAD

**Issue by robjac** [wsdjeg/SpaceVim#1958]
## Expected behavior, english is required
open vim / spacevim wiht no errors
## The reproduce ways from Vim starting (Required!)
open spacevim. no fancy custom stuff. 
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
^ the above command didn't copy to clipboard / didn't do anything.
I will paste what I have in :messages.

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function matchup#loader#bufwinenter[4]..matchup#loader#init_buffer[9]..<SNR>131_init_delim_r
egexes:
line   20:
E488: Trailing characters: <<<<<<< HEAD
Error detected while processing function matchup#loader#init_buffer[9]..<SNR>131_init_delim_regexes:
line   20:
E488: Trailing characters: <<<<<<< HEAD
Error detected while processing function matchup#loader#init_buffer[9]..<SNR>131_init_delim_regexes:
line   20:
E488: Trailing characters: <<<<<<< HEAD
Error detected while processing function matchup#loader#init_buffer[9]..<SNR>131_init_delim_regexes:
line   20:
E21: Cannot make changes, 'modifiable' is off: <<<<<<< HEAD
Error detected while processing function SpaceVim#welcome:
line   20:
E171: Missing :endif
Error detected while processing function matchup#loader#init_buffer[9]..<SNR>131_init_delim_regexes:
line   20:
E488: Trailing characters: <<<<<<< HEAD
Error detected while processing function matchup#loader#bufwinenter[4]..matchup#loader#init_buffer[9]..<SNR>131_init_delim_r
egexes:
line   20:
E488: Trailing characters: <<<<<<< HEAD
```
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by crisidev** [comment]
I think your spacevim folder is corrupted.. 

Do you mind to send the output of `cd ~/.vim && git status`

**Comment by robjac** [comment]
Sure thing: 

```
~  cd ~/.vim && git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by justicek** [comment]
not sure if this is related but in case it helps, i was trying to use spacevim for the first time (fresh install using install.sh script .. it showed everything as being install correctly) and got the following errors upon opening vim after installation:

❯ vim
Error detected while processing function SpaceVim#end[78]..SpaceVim#plugins#load[2]..zvim#plug#begin[11]..dein#begin[1]..dein#util#_begin[6]..dein#util#_error[1]..<SNR>40_msg2list:
line    1:
E121: Undefined variable: v:t_list
E15: Invalid expression: type(a:expr) ==# v:t_list ? a:expr : split(a:expr, '\n')
Error detected while processing function SpaceVim#end[78]..SpaceVim#plugins#load[2]..zvim#plug#begin[11]..dein#begin[1]..dein#util#_begin[6]..dein#util#_error:
line    1:
E714: List required
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
@robjac I think it is due to the author of vim-matchup use `git push -f` in his plugin, so you need to reinstall that plugin, you can use `:SPReinstall vim-matchup`

@justicek It is due to your vim is old, it is same issue as #1723
