### ISSUE TITLE
Input method automatically switches the problem

### ISSUE THREAD

**Issue by floatval** [wsdjeg/SpaceVim#1959]
## Debug info

All right. Now, i don't know how to copy Spc vim to clipboard , if u nedd it , i'll try do.

**Comment by wsdjeg** [comment]
It should be a bug of https://github.com/lilydjwg/fcitx.vim

cc @lilydjwg

**Comment by floatval** [comment]
@wsdjeg i solve it.
When i use i3-gaps, when i When it in insert model input method is english, it's ok, but then i switch to normal model with Ctrl + o ,the input method automatically to Chinese.
But now i use xfce4, it work well.
Thanks for u replay!

**Comment by wsdjeg** [comment]
Ok.
