### ISSUE TITLE
checkers layer bug

### ISSUE THREAD

**Issue by 2b2b2b2b** [wsdjeg/SpaceVim#1965]
我使用checkers layer 设置使用用ale，并且在初始化里添加ale配置的相关脚本
![image](https://user-images.githubusercontent.com/16076364/43058079-3d5314ec-8e78-11e8-8b85-6fb0b3e51891.png)
之前并没有问题，现在输入时会引发明显卡顿，下方会报错 <urloepn error timed out>

**Comment by wsdjeg** [comment]
1. english only
2. you need follow the issue template, I need the debug info.
3. you can also post your SpaceVim config.
