### ISSUE TITLE
How to enable autocompletion

### ISSUE THREAD

**Issue by YvesZHI** [wsdjeg/SpaceVim#1967]
I've just installed neovim + SpaceVim on my Ubuntu 16.04.3.

But I don't know how to enable the function of autocompletion.

I've tried to add things below to `~/.SpaceVim.d/init.toml`:

```
[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"
```

And then I execute `nvim` and find the plugin is installed correctly.

But when I execute `nvim` again and type c++ codes, the codes can't still be auto-completed.

I don't how to enable the autocompletion of SpaceVim.

Also, in my system, there is no `/usr/bin/clang`. So does it mean that I have to install clang for my ubuntu? or is there another method?

**Comment by wsdjeg** [comment]
autocomplete layer is enabled by default, for c++ file, you need to install clang. and make sure your neovim support +python3. This can be checked via `:py3 import vim`
