### ISSUE TITLE
Install script error

### ISSUE THREAD

**Issue by zhangweiii** [wsdjeg/SpaceVim#1971]
## I get `Successfully and Installed SpaceVim` when i cannot connect to GitHub

<img width="755" alt="4d21cb5bd505ccdfddbced387b2dff09" src="https://user-images.githubusercontent.com/31117497/43176186-37f61516-8ff5-11e8-94c9-71759f1799c4.png">

**Comment by wsdjeg** [comment]
we should check the exit number of git clone comamnd.
