### ISSUE TITLE
windows_leader

### ISSUE THREAD

**Issue by WoWIllidan** [wsdjeg/SpaceVim#1973]
init.toml 

[options]
     .....
     windows_leader = ""
 

does not work. errors below.

Error detected while processing function SpaceVim#end[29]..SpaceVim#mapping#leader#defindKEYs:
line    4:
E121: Undefined variable: g:_spacevim_mappings_windows
E116: Invalid arguments for function extend

**Comment by crisidev** [comment]
Leader needs to be set using the custom before function. It cannot be set inside the toml configuration.

**Comment by windseeker1024** [comment]
This is my first time using SpaceVim.  I don't know how to set up windows_leader  .    can you provide an example?    Thanks!

**Comment by wsdjeg** [comment]
It is a bug, SpaceVim should support `windows_leader` option.
