### ISSUE TITLE
long startuptime

### ISSUE THREAD

**Issue by fcying** [wsdjeg/SpaceVim#1975]
spacevim: commit e677da4c368e63d95c023
vim : VIM - Vi IMproved 8.1  1-191
nvim: NVIM v0.3.0-dev

start with spacevim spend a long time

init.toml
```
[options]
    colorscheme = "gruvbox"
    background = "dark"
    enable_guicolors = false
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_display_mode = false
    statusline_unicode_symbols = false
    vimcompatible = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'git'
```
test cmd:
```
vim -u NORC --startuptime s_norc.log
vim --startuptime s_vim.log
nvim --startuptime s_nvim.log
```
vim -u NORC spend `004.813`
spacevim with vim spend `567.841`
spacevim with nvim spend `834.150`

[s_vim.log](https://github.com/SpaceVim/SpaceVim/files/2227274/s_vim.log)
[s_nvim.log](https://github.com/SpaceVim/SpaceVim/files/2227275/s_nvim.log)
[s_norc.log](https://github.com/SpaceVim/SpaceVim/files/2227276/s_norc.log)

**Comment by wsdjeg** [comment]
I just read the all the log, but it is hard to debug.

**Comment by chemzqm** [comment]
1. `Startify` is not async, it's really slow.
2. Neovim provider has a `pull` request, it takes about 200ms for each remote host. Check out https://github.com/neovim/neovim/issues/5728#issuecomment-406475616 for optimize.
3. https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/api/vim/compatible.vim#L23 use python code for python support check, it could be change to `has('python')` and `has('python3')`, or at least use cache for the result.

**Comment by wsdjeg** [comment]
@chemzqm 

1. startify is a nice plugin, I do not want to disable it by default. but maybe I will create a new welcome page plugin for SpaceVim
2. I want to add a provider.vim into SpaceVim, and override the built-in one
3. even if `has('python')` return 1, it does not mean you can use `:py` command, sometimes it also cause many errors.

**Comment by chemzqm** [comment]
> 3. even if has('python') return 1, it does not mean you can use :py command, sometimes it also cause many errors.

I would consider it as vim or user's problem and vim or user should be responsible to fix the problem instead of consider it as not supported, neovim/vim have python check already.

For issue https://github.com/vim/vim/issues/3117, you can check `has('patch-8.1.201')`, and use 
```
if !has('nvim') && has('python3')
  silent! python3 1
endif
```
for vim.

**Comment by crisidev** [comment]
For 3, you can at least cache the result and do the `has('python')` and `has('python3')` only once and use the cached value. Am I missing anything?

**Comment by wsdjeg** [comment]
> For issue vim/vim#3117, you can check has('patch-8.1.201'), and use

It is not same issue, as I remember, in old version of SpaceVim, we use `has('python')` to check if vim support `:py` command, but sometion it cause errors, because if user's vim is `+python/dyn`, it may cause errors.

**Comment by wsdjeg** [comment]
> at least cache the result and do the has('python') and has('python3') only once and use the cached value

yeah, that is a good idea.

**Comment by chemzqm** [comment]
Extra option like `skip_python2_check` and `skip_python3_check` could be provided.

**Comment by wsdjeg** [comment]
as I know, these option has been remove from neovim's master.

**Comment by chemzqm** [comment]
That's because neovim could use `g:python_host_prog` and `g:python3_host_prog` to prevent detect, when that's provided by user, the check is disabled.

Spacevim could also check that.

**Comment by p10q** [comment]
Just fyi if you were to add the `g:python[3]_host_prog` checks. In (
https://github.com/SpaceVim/SpaceVim/blob/master/config/main.vim#L61):

```
call SpaceVim#begin()

call SpaceVim#custom#load()

call SpaceVim#end()
```
`SpaceVim#custom#load` comes after `SpaceVim#begin` which I believe does python checks. So if the user sets the values in ` ~/.SpaceVim.d/autoload/myspacevim.vim`, that'll be called too late.

(via https://github.com/neovim/neovim/issues/2437#issuecomment-522240491)

Probably not the most elegant but setting `g:python_host_prog` and `g:python3_host_prog` at the top `~/.SpaceVim/config/main.vim` works for me.

**Comment by p10q** [comment]
Cleaner approach is to set in bash/zsh rc:
```
export PYTHON_HOST_PROG=`which python2`
export PYTHON3_HOST_PROG=`which python`
```
(or `set PYTHON3_HOST_PROG` etc. for fish).

**Comment by robertwt7** [comment]
@p10q by putting that in .zshrc I got 

`Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated l
og file. Also, the host stderr is available in messages.`

Not sure why, my startup is very very slow from both nvim and vim...
