### ISSUE TITLE
bookmark

### ISSUE THREAD

**Issue by WoWIllidan** [wsdjeg/SpaceVim#1978]
[https://spacevim.org/cn/documentation/#bookmarks-management](https://spacevim.org/cn/documentation/#bookmarks-management)

According to the above documentation, is the bookmark shortcut in the latest version 0.9.0-dev not available? I did not succeed in the operation

**Comment by windseeker1024** [comment]
When I set `vimcompatible = true`, the bookmark shortcut does not take effect.    In normal mode, after pressing f to search for characters, the comma and semicolon buttons cannot be used.

**Comment by wsdjeg** [comment]
@helloworldgnu the bookmarks manager need tools layer, you need to load this layer.

by default, f is mapped to clever-f, you can read the doc of that plugin, it is awesome plugin and better than default `f`.
