### ISSUE TITLE
Stage/Undo hunk Version Control (transient state)

### ISSUE THREAD

**Issue by Fetz** [wsdjeg/SpaceVim#1984]
Currently the stage/undo in transient state is not implemented and that feature looks like will not be implemented by vim-signify https://github.com/mhinz/vim-signify/issues/148, should SpaceVim use vimgutter instead since it supports hunks https://github.com/airblade/vim-gitgutter#hunks?

**Comment by wsdjeg** [comment]
but `VersionControl` is not for git, it is also for other version control system (VCS)

**Comment by Fetz** [comment]
Yes @wsdjeg you are right.

Than I would suggest to only add the stage hunks mapping when we add git layer. 

And for mappings that aren't yet implemented maybe would be a better user experience or to comment out that or to show a message that, that feature is not yet implemented.

**Comment by wsdjeg** [comment]
hi, sorry for long reply, I just look into this issue, will add these mappings to git layer.

**Comment by VarunBatraIT** [comment]
I second the thought - What I miss is to keep pressing ]s in gitgitter when I am sure I am done with the function or a line.

**Comment by stfl** [comment]
gitgutter does this by interally applying a patch from the hunk. It should be possible to reimplement that. the gitgutter code is a bit to gitgutter-specific.

I used to have gitgutter for git and signify for everything else installed.
signify allows to white-/blacklist version control systems it activates.

      let g:signify_vcs_list = ['cvs', 'hg', 'svn', ...]

https://github.com/mhinz/vim-signify/blob/master/doc/signify.txt#L153

**Comment by wsdjeg** [comment]
@mhinz How about add a new option for signify blacklist, it seems `g:signify_vcs_list` is for white list.
