### ISSUE TITLE
vimcompatible

### ISSUE THREAD

**Issue by WoWIllidan** [wsdjeg/SpaceVim#1994]
in init.toml, when i set vimcompatible = true,     Commas, semicolons, `<C-x>`, etc. in vim mode, not in the original vim mode behavior in SpaceVim

Does not match the description at [https://spacevim.org/documentation/#vim-compatible-mode](https://spacevim.org/documentation/#vim-compatible-mode)

> Vim Compatible Mode
This a list of different key bindings between SpaceVim and origin vim. If you still want to use this origin function, you can enable vimcompatible mode, via vimcompatible = true in [options] section.

Even if`enable_language_specific_leader = false` is set, after pressing f to search for a character, "," and ";" key still cannot search for the next match down.

**Comment by wsdjeg** [comment]
@helloworldgnu can you list all the keys which does not work as expected in vimcompatible mode.

**Comment by windseeker1024** [comment]
Sorry, currently in the buttons I use, I only found that these three keys do not match their original vim mode behavior. If I find something else, I will add it here.

**Comment by windseeker1024** [comment]
In SpaceVim,  press `q:` to enter the command line mode. At this time, press `<C-f>` , the command line window is not opened.

**Comment by wsdjeg** [comment]
I just add discussion label, and I will check the key binding list.
