### ISSUE TITLE
Installing Plugins Error

### ISSUE THREAD

**Issue by Laphet** [wsdjeg/SpaceVim#1997]
Error detected while processing function <SNR>99_on_install_exit:
line    7:
E716: Key not present in Dictionary: 1
Press ENTER or type command to continue
Error detected while processing function <SNR>99_on_install_exit:
line    7:
E116: Invalid arguments for function <SNR>99_msg_on_install_done
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin..SpaceVim#plugins#manager#install..<SNR>99_install:
line   19:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin..SpaceVim#plugins#manager#install:
line   41:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
@Laphet what is the output of `vim --version`?

and what is your os?

**Comment by XIAZY** [comment]
here's my vim version and I am able to reproduce the issue
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
```

**Comment by seltzy** [comment]
Same problem here, same version. OS = Ubuntu 14.04.
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
Included patches: 1-52
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
```

Error:
```
Error detected while processing function <SNR>105_on_install_exit:
line    7:
E716: Key not present in Dictionary: 1
Press ENTER or type command to continue
```

**Comment by sbseltzer** [comment]
Same problem on my Ubuntu 14.04 box.
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
Included patches: 1-52
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
```

**Comment by advpetc** [comment]
same here
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 21 2015 13:04:09)
Included patches: 1-712
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
```

**Comment by lengyijun** [comment]
dein is based on vim8, you need to update vim

**Comment by sbseltzer** [comment]
Can this be clarified in the README and perhaps add a version check before hitting the error? It's very cryptic.

**Comment by wsdjeg** [comment]
old vim supported has been added into todo list #1727
