### ISSUE TITLE
git status

### ISSUE THREAD

**Issue by hongjiujing** [wsdjeg/SpaceVim#1998]
## The reproduce ways from Vim starting (Required!)
before upgrade,  SPC support "git status" style  which can print git vcs info,  why it disappear after upgrade?
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@hongjiujing what do you mean git status? you want to show git status on statusline? maybe you need to load `git` layer or `VersionControl` layer

**Comment by hongjiujing** [comment]
Hi ,

Spacevim should  support bind key to  git status? after i upgrade, i can't see it.

**Comment by wsdjeg** [comment]
It is `SPC g s`  in git layer.
