### ISSUE TITLE
Development announce [ 开发笔记 ]

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2]
Hi, users.

I will create new distributionfor vim and neovim.
It is SpaceVim (Like spacemacs, but for vim).

大家好：
   我将新建一个新的vim模块化配置集合SpaceVim，这一项目主要灵感来源于spacemacs.

**Comment by cookiengineer** [comment]
Hint: Change the default branch to dev in the repo settings. So people are not confused and won't think this repo is empty.

Anyways, looking forward to spacevim!

**Comment by wsdjeg** [comment]
Yeah, should be done.

**Comment by wsdjeg** [comment]
how to enable a layer?

`call SpaceVim#Layer(layer_name, {layer_option})`

**Comment by rafi** [comment]
The README.md looks very familiar. It would've been nice to give credit.

**Comment by wsdjeg** [comment]
@rafi it is copy from yours some mounths ago. and first time I copy it to wsdjeg/DotFiles and I change all my nvim config based on yours

see https://github.com/wsdjeg/DotFiles/issues/24

**Comment by wsdjeg** [comment]
@rafi I am really sorry. I think I should add links in the readme.

**Comment by wsdjeg** [comment]
@rafi @bling I have add Credits, thanks a lot!!

**Comment by liuchengxu** [comment]
@wsdjeg I just want to point out the typo in this issue's label 🙈 . anouncement -> announcement

**Comment by wsdjeg** [comment]
@liuchengxu  are you sure? It is not a type.
![2017-01-06-23 36 37](https://cloud.githubusercontent.com/assets/13142418/21722838/48609802-d469-11e6-999b-7ab7f7adc415.png)

**Comment by wsdjeg** [comment]
@liuchengxu thanks.

**Comment by wsdjeg** [comment]
clossing, for info about development announce, please check the commits history.
