### ISSUE TITLE
E492: Not an editor command: IndentLinesToggle

### ISSUE THREAD

**Issue by casdr** [wsdjeg/SpaceVim#20]
I just installed SpaceVim plain, but I'm getting the following error when I go to Insert mode:

```
Error detected while processing function <SNR>25_tool:
line    2:
E492: Not an editor command:         IndentLinesToggle
```

**Comment by wsdjeg** [comment]
Before go to insert mode,Please install the plugin. 
`call dein#install()`. then wait for it finished.

**Comment by belst** [comment]
This should probably be documented somewhere or the installer should do it automatically

**Comment by wsdjeg** [comment]
Yeah. will do it tonight. and thanks for your feedback.

**Comment by casdr** [comment]
@wsdjeg thanks, that fixed it!

**Comment by heuripedes** [comment]
Looks like all plugins fail to install/build when I run `call dein#install()`. All I get is a bunch of

```
Build failed. Uninstall "PLUGIN NAME" now?
(y)es, [N]o:
```

**edit** Looks like SpaceVim requires python2 & python3 support. Please add that to the README too.

**Comment by wsdjeg** [comment]
@heuripedes what is your os? do you has `git` in you PATH?

**Comment by heuripedes** [comment]
@wsdjeg My nvim install was fairly minimal and I hadn't enabled python support.

**Comment by wsdjeg** [comment]
@heuripedes to install neovim and python support , you should check neovim's wiki.

> Looks like SpaceVim requires python2 & python3 support. Please add that to the README too.

yeah, should be added. will do it.
