### ISSUE TITLE
Call for code owners

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2002]
as described in [Github code owner](https://blog.github.com/2017-07-06-introducing-code-owners/), we want to call for code owners for each language layer.

current status:

| layer | code owner | pull request
--- | --- | ---
`lang#javascript` |   @zhujinxuan @S1ngS1ng @chemzqm  |  #2003 
`lang#c` |  @yangyinqi |
`lang#kotlin` |  @c4dr01d  | 
`lang#julia` | @jingpengw |

any feedback is welcome!

**Comment by wsdjeg** [comment]
Join SpaceVim org？

[Join us](http://probot-invite.herokuapp.com/join/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTcGFjZVZpbSIsImlzcyI6NjgzODA1LCJyb2xlIjoibWVtYmVyIiwidGVhbXMiOlsiMzA4OTgxNCJdLCJpYXQiOjE1NTA2NTE3MTN9.0IUuIkjmPb-fPvM8EoCWiieBDbDjGuNcA-83l3FJYRs)

**Comment by zhujinxuan** [comment]
Joined.  Thank you!

**Comment by xiuliren** [comment]
sorry, I am not using Julia recently.
