### ISSUE TITLE
SPC '  buffer support mouse scroll 

### ISSUE THREAD

**Issue by hongjiujing** [wsdjeg/SpaceVim#2006]
## Expected behavior, english is required
after SPC ' to create a buffer, how to support "mouse scroll" to see previous buffer  output?
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
It is usage question of neovim's terminal buffer, please read the doc of neovim's terminal.
