### ISSUE TITLE
Support relative line number auto change.

### ISSUE THREAD

**Issue by ariesdevil** [wsdjeg/SpaceVim#2008]
support this plugin? https://github.com/jeffkreeftmeijer/vim-numbertoggle

**Comment by wsdjeg** [comment]
This plugin is only 5 line code, and we recomment to merge code instead of using a git command to install plugin. but I am not sure all users need this feature.

```
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
augroup END
```

**Comment by ariesdevil** [comment]
@wsdjeg Maybe make it optional?

**Comment by wsdjeg** [comment]
hmm, I do not think this feature is usefull, we can keep this issue open ,and if more people request for this feature, I will included it into SpaceVim. before we add this feature, you can use bootstrap function, and put these five line vim script into it.

**Comment by matt1003** [comment]
+1 for this feature.

I have been using [numbers.vim](https://github.com/myusuf3/numbers.vim) for years; not sure how it differs from [vim-numbertoggle](https://github.com/jeffkreeftmeijer/vim-numbertoggle) though.

**Comment by crisidev** [comment]
I have this implemented in my custom config. +1 for the feature

**Comment by matt1003** [comment]
I also use the following option:
```vim
let g:numbers_exclude = ['help', 'nerdtree', 'tagbar', 'qf', 'undotree']
```
This prevents line numbering on the specified file types.

**Comment by wsdjeg** [comment]
Ok, I will implement this feature.

**Comment by wkcosmology** [comment]
I have found this feature is not stable. Sometimes when I focus on other things and go back to vim, it will not change to the relative number and I always jump to the wrong line since I thought it is relative line number.
This feature can be disabled by adding
```
let g:spacevim_relativenumber = 0
set relativenumber
```
in the config file.

**Comment by wsdjeg** [comment]
if you can reproduce it, please use new issue.
