### ISSUE TITLE
SPC + s + s search will create a  new buff

### ISSUE THREAD

**Issue by Land-Fairy** [wsdjeg/SpaceVim#2010]
1. vim init.toml
2. search for some string  
      SPC + s + s  
   then click Enter
      type  layers
   FlyGrep  will show the search  results
   then
       Use  TAB to change between these results, find one, and click Enter
  the result is a new buffer named this results's line number was created, not jump to this search results

## Screenshots

![selection_002](https://user-images.githubusercontent.com/22864341/43621053-1acea2ea-9708-11e8-835d-d0769a5ed53e.png)
![selection_003](https://user-images.githubusercontent.com/22864341/43621064-2585b638-9708-11e8-9a15-6eb3832e1991.png)

## Debug info
![selection_004](https://user-images.githubusercontent.com/22864341/43621070-2a03342e-9708-11e8-9332-af70ef831472.png)

**Comment by wsdjeg** [comment]
@Land-Fairy This is a bug of ag support in flygrep, before this issue is fixed, you can install rg.

**Comment by wsdjeg** [comment]
sorry, I can not fix this issue, ag do not support print filename when searhing in only one file.
