### ISSUE TITLE
Install problems on Android Termux...

### ISSUE THREAD

**Issue by QGB** [wsdjeg/SpaceVim#2019]
已下载 symbol.ttf
[✔] 已下载 wingding.ttf
[➭] 正在构建字体缓存，请稍等...
main: line 384: fc-cache: command not found
main: line 385: mkfontdir: command not found
main: line 386: mkfontscale: command not found
[✔] 字体安装已完成!

安装已完成!
==============================================================================
==               打开 Vim 或 Neovim，所有插件将会自动安装                   ==
==============================================================================

感谢支持 SpaceVim，欢迎反馈！

$ vim
Error detected while processing /data/data/com.termux/files/home/.cache/vimfiles/.cache/vimrc/.dein/plugin/matchup.vim:
line   32:
match-up must be loaded before matchit
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
It is issue with your vim, your vim do not has matchit in default rtp. and you need to install these three commands: fc-cache, mkfontdir and mkfontscache. or you can install font yourself.
