### ISSUE TITLE
Reinstall Frequently

### ISSUE THREAD

**Issue by minibear0523** [wsdjeg/SpaceVim#2029]
## Expected behavior, english is required
I'm using MacVim's vim to replace the default vim in macOS 10.13.6. I have installed the latest spaceVim and I have exported SVN_EDITOR to vim. When I using `vim` or `svn commit`, the spaceVim usually reinstall itself. And it's frequently. 

## The reproduce ways from Vim starting (Required!)
```
# svn ci
:!git clone https://github.com/Shougo/dein.vim "/Users/leizhang/.cache/vimfiles/repos/github.com/Shougo/dein.vim"
                                                                                                                 Cloning into '/Users/leizhang/.cache/vimfiles/repos/github.com/Shougo/dein.vim'...
remote: Counting objects: 5034, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 5034 (delta 5), reused 13 (delta 5), pack-reused 5017
Receiving objects: 100% (5034/5034), 986.08 KiB | 27.00 KiB/s, done.
Resolving deltas: 100% (2874/2874), done.

Press ENTER or type command to continue
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
It is just to install dein, this should only clone dein when first time start SpaceVim.

**Comment by minibear0523** [comment]
Yes, it is should be install at first time. But this is what the problem is, when I using pycharm's terminal and iTerm with oh-my-zsh, it was usually reinstall dein again and again. It is about 2-4 times per day which depends on the frequency using vim.

**Comment by wsdjeg** [comment]
in SpaceVim there is a check for `if dein is installed`

```
        if filereadable(expand(g:spacevim_plugin_bundle_dir)
                    \ . join(['repos', 'github.com',
                    \ 'Shougo', 'dein.vim', 'README.md'],
                    \ s:Fsep))
            let g:_spacevim_dein_installed = 1

```

so you can check via 
```
:echo filereadable(expand(g:spacevim_plugin_bundle_dir) . join(['repos', 'github.com',  'Shougo', 'dein.vim', 'README.md'],  '/' ))
```

**Comment by minibear0523** [comment]
OK, I will check it and open this issue if I have found the reproduce procedure. Thank you.

**Comment by wsdjeg** [comment]
welcome.

**Comment by minibear0523** [comment]
I have found how to reproduce this problem. It is because of the plugins location is in ~/.cache/ directory. Just like the issue#2076. I usually use the Dr.Clean app to clean my mac and purge memory. It will automatically delete the .cache directory. After change the plugin location to other directory which will not be deleted by this app, it works fine.
Although this, I suggest maybe change the default location of plugins will be better?

**Comment by wsdjeg** [comment]
I can not change it. it will make all spacevim users reinstall their plugins.
