### ISSUE TITLE
Visual Block Mode not reported in statusline

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#2031]
If I hit <CTRL-V> to enter in visual block mode, there is no report of the mode itself in the status line.

Using the normal visual mode (v from command mode) works as expected.

**Comment by wsdjeg** [comment]
I can not understand this issue, what do you want to show on statusline?

**Comment by crisidev** [comment]
When you have the option `enable_statusline_mode = true` in the toml config and I go into visual mode, in the left corner of the statusline I see "VISUAL" (in red). This changes when I change input mode. It is defined here: https://github.com/SpaceVim/SpaceVim/blob/04dc1a1fa45e05ff542580764e7793de4008c2ec/autoload/SpaceVim/layers/core/statusline.vim#L628-L647

It works for all modes apart from VISUAL BLOCK, which I enter using <CTRL-V>. In visual block mode it does not print anything.

**Comment by wsdjeg** [comment]
@crisidev The mode text function should be inproved, and It should at least distinguish `v` and `V` mode, Does VISUAL BLOCK mode means `<C-V>`?

**Comment by crisidev** [comment]
Yep, it means `<C-V>`

**Comment by wsdjeg** [comment]
I just read the code of airline, and maybe we can use same feature:

```vim
call extend(g:airline_mode_map, {
        \ '__' : '------',
        \ 'n'  : 'NORMAL',
        \ 'i'  : 'INSERT',
        \ 'R'  : 'REPLACE',
        \ 'v'  : 'VISUAL',
        \ 'V'  : 'V-LINE',
        \ 'c'  : 'COMMAND',
        \ '' : 'V-BLOCK',
        \ 's'  : 'SELECT',
        \ 'S'  : 'S-LINE',
        \ '' : 'S-BLOCK',
        \ 't'  : 'TERMINAL',
        \ }, 'keep')
```

**Comment by wsdjeg** [comment]
@crisidev what do you think about this:

![modetext](https://user-images.githubusercontent.com/13142418/44001883-84558704-9e6c-11e8-9bfd-7cbd17e80333.gif)

**Comment by crisidev** [comment]
I think it is great. I cannot test it right now, but it looks good.
