### ISSUE TITLE
SPC b b SPC f r can't use.

### ISSUE THREAD

**Issue by paopaol** [wsdjeg/SpaceVim#2036]
when i type spc b b , there not found spc b b 
version 0.9.0 dev

**Comment by wsdjeg** [comment]
##### Buffers manipulation key bindings

Buffer manipulation commands (start with `b`):

| Key Binding     | Description                                                                    |
| --------------- | ------------------------------------------------------------------------------ |
| `SPC TAB`       | switch to alternate buffer in the current window (switch back and forth)       |
| `SPC b .`       | buffer transient state                                                         |
| `SPC b b`       | switch to a buffer (via denite/unite)                                          |


you need to load a fuzzy finder layer, denite or unite. for usage question, please use gitter chatting room instead. issue is only for bug report and feature request. and issue template is needed.
