### ISSUE TITLE
How to add a new SPC prefix key bindings

### ISSUE THREAD

**Issue by gennad** [wsdjeg/SpaceVim#2038]
I found in the documentation the following

> if you want to add custom SPC prefix key bindings, you can add this to SpaceVim configuration file, be sure the key bindings is not used in SpaceVim.  call SpaceVim#custom#SPCGroupName(['G'], '+TestGroup') call SpaceVim#custom#SPC('nore', ['G', 't'], 'echom 1', 'echomessage 1', 1)

However, it's unclear where to add those lines of code. I have the most recent version with init.toml configuration file.

I tried to add them to ~/.SpaceVim/init.vim but it did not work (i did not see that new group when I restarted and presses space).

Would you please explain and update docs? Thank you.

**Comment by wsdjeg** [comment]
> I tried to add them to ~/.SpaceVim/init.vim but it did not work

I will update the doc. but user should not edit content in `~/.SpaceVim` dir, because SpaceVim use `git pull` to update itself. if the file in this repo is changed, you may failed to updated SpaceVim.
