### ISSUE TITLE
How do I hook up a custom plugin to SpaceVim

### ISSUE THREAD

**Issue by gennad** [wsdjeg/SpaceVim#2039]
I'd like to write a simple custom plugin which is located on local file system, not github. 
How do I hook it up to SpaceVim?

**Comment by wsdjeg** [comment]
> `which is located on local file system, not github`

you can read `:h rtp`, in vim rtp path, the script in `plugin/` dir will be loaded when vim startup. the `ftplugin/` will be loaded when &filetype is changed.

in SpaceVim, `~/.SpaceVim.d/` is your custom configuration directory. so you can create a vim script file in `~/.SpaceVim.d/plugin/`.  

**NOTE**, it is `~/.SpaceVim.d/plugin/`  not `~/.SpaceVim/plugin/`.

for example you can create `~/.SpaceVim.d/plugin/myfirstscript.vim`

**Comment by wsdjeg** [comment]
also, you can use `set rtp+=/path/to/your/plugin_dir`, you can put this script into bootstrap function, you can check my DotFiles repo on github to see how to use bootstrap function.

https://github.com/wsdjeg/DotFiles/tree/master/SpaceVim.d

**Comment by gennad** [comment]
Thank you, @wsdjeg I'll give it a try! If it works, I will close this task

**Comment by gennad** [comment]
~/.SpaceVim.d/plugin/myfirstscript.vim did the trick :+1:
