### ISSUE TITLE
Add support of Haskell

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#204]
# Add support of Haskell

**Comment by wsdjeg** [comment]
@raichoo I am watching neovim repo, my main editor is neovim, I am author of SpaceVim, I just see you open issue in neovim repo, and you are main author of haskell-vim, now I want to add lang#haskell layer, any plugins recommand?
the `lang#haskell` layer should have these main features:
1. code completion
2. syntax hi, and check
3. jump to definition
4. doc lookup
other features:
1. refactor
2. haskell ref

**Comment by raichoo** [comment]
This is the `haskell` section from my `init.vim`. I'm using very few plugins, but maybe this is helpful:

```viml
"haskell
Plug 'neovimhaskell/haskell-vim'
Plug 'pbrisbin/vim-syntax-shakespeare'
Plug 'eagletmt/neco-ghc'
```
