### ISSUE TITLE
Feature request: lang#LaTeX layer

### ISSUE THREAD

**Issue by Dothion** [wsdjeg/SpaceVim#2046]
Spacevim do not support LaTeX now. Plugin [vim-LaTeX](http://vim-latex.sourceforge.net/) will be a nice solution for language support and live preview, perhaps.

**Comment by wsdjeg** [comment]
@Dothion What do you think about https://github.com/vim-latex/vim-latex ?

**Comment by Dothion** [comment]
either is ok. wish for live preview(using latexmk or other ways).
thx for your contribution to the open source community.

**Comment by wsdjeg** [comment]
@Dothion do you know https://github.com/lervag/vimtex, I do not know the differences between these two plugins, and I will have a try with them.

**Comment by weidenka** [comment]
I'm currently using vimtex. I used vim-LaTeX  and vim-latex the others in the past and I think vimtex is the way better option (though I forgot what I didn't like about the others). 
+1 for vimtex from my side.

**Comment by Dothion** [comment]
i tried vimtex and vim-latex suite. both meet my demand, but now i think vimtex is better a plugin.
vote for vimtex.

**Comment by wsdjeg** [comment]
ok, I have create a pr for this issue, and what is the recommended lanaguge specified key bindings for latex layer?  all key bindings start with `SPC l` prefix.
