### ISSUE TITLE
Julia layer didn't work well

### ISSUE THREAD

**Issue by honghuzi** [wsdjeg/SpaceVim#2058]
I tried Julia layer in Gvim and vim in WSL(ubuntu 18.04), only highlight feature worked as expected. I can't input any Greek letter. After typing "SPC + l", i just got an empty buffer.

![lgip2ls n u66 15pu_kj](https://user-images.githubusercontent.com/8718754/44297034-cc6db400-a2fc-11e8-9e90-6955fbe164f5.png)

**Comment by wsdjeg** [comment]
I just create a pr for this issue, but still has some issues:

1. when using julia layer, I see 

```
match-up: function b:match_words not supported 
````

I just run `:echo b:match_words`, I see:

```
JuliaGetMatchWords()
```

It should be a function name.

```
echo JuliaGetMatchWords()
```

I see:

```
\<\>:\<\>  
```

this should be a bug of @andymass vim-matchup or julia.vim itself.

**Comment by andymass** [comment]
I've enabled this feature.  https://github.com/andymass/vim-matchup/commit/ee7ccbbd2b5b10db9c069dc3c1db4edf1774fffc.  The error message is gone and highlighting and `%` should work.

`[%`, etc will not work yet but this is a known limitation of matchit+julia-vim as well.  I plan to enhance this in the future.

**Comment by wsdjeg** [comment]
@andymass Thanks For your help. :)

**Comment by xiuliren** [comment]
The LanguageServer.jl is not working, there are some fixing PRs. We are waiting for that PRs got merged and release a new version.

**Comment by wsdjeg** [comment]
@jingpengw ok, thanks.
