### ISSUE TITLE
SpaceVim write C header files the macro command have highlight

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2059]
## Expected behavior, english is required
When i writing C code in the C header file, the clighter plugin highlight the macro command
## The reproduce ways from Vim starting (Required!)
Start editing the C header file
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
Screenshots
![bug](https://user-images.githubusercontent.com/20458813/44298017-f7accf00-a30d-11e8-90aa-8f49893016ab.PNG)

**Comment by brakchen** [comment]
Are you open the cpp model?
on the bottom of left,it said cpp.
if you open a c file ,here should be c
![snip20180819_90](https://user-images.githubusercontent.com/17734336/44306140-d4485980-a3cb-11e8-9038-1c0ce9ffa16f.png)

**Comment by ghost** [comment]
But, I report is header file bug,not source file bug

**Comment by wsdjeg** [comment]
I can not reproduce it in neovim. please use issue template. 
![2018-08-19_221x127](https://user-images.githubusercontent.com/13142418/44308860-d7554100-a3ef-11e8-8c1b-00fc095a6f60.png)

**Comment by wsdjeg** [comment]
![2018-08-19_202x119](https://user-images.githubusercontent.com/13142418/44308865-023f9500-a3f0-11e8-9450-1369b7c6ab40.png)

In vim8, it can not works, It is a bug of c highlighting plugin. I can not fix it though.

**Comment by ghost** [comment]
Can provide the plugin's github link? I want to report this bug

**Comment by wsdjeg** [comment]
https://github.com/bbchung/clighter8

**Comment by ghost** [comment]
Thanks.
