### ISSUE TITLE
neomake signs redefine error

### ISSUE THREAD

**Issue by brakchen** [wsdjeg/SpaceVim#2061]
## Expected behavior
This should be a syntax check plugin.This error message should not showup when saving.
## reproduce ways
reproduce this error is quite simple.
just open a c file and edit something then save.The error will popup immediately

## Debug info
Sorry about  that.There is no any debug info .I didnt open the clipboard on vim.
BUT there is a few info about the system.Hope helps.
```
$uname -r
3.16.0-6-amd64
$ cat /etc/*release           
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
BTW.This error also on Mac.
Here is system info:
![snip20180819_89](https://user-images.githubusercontent.com/17734336/44306104-2341bf00-a3cb-11e8-98e1-86e71e92244f.png)

## Screenshots
![snip20180819_88](https://user-images.githubusercontent.com/17734336/44306098-00afa600-a3cb-11e8-99ca-9590bad85ebf.png)

**Comment by wsdjeg** [comment]
@brakchen can you post all content in `SPC b m`? instead of using pisture, I can not see all th e info of error message.

**Comment by brakchen** [comment]
@wsdjeg 
```
"test.c" 6L, 87C written
Error detected while processing function neomake#signs#DefineSigns[1]..neomake#signs#RedefineErrorSign[9]..neomake#signs#RedefineSign:
line    6:
E239: Invalid sign text: <bf>
Neomake error in: function <SNR>183_process_action_queue[31]..<SNR>183_process_pending_output[3]..<SNR>183_ProcessPendingOutput[22]..<SNR>183_ProcessJobOutput[6]..<SNR>183_pcall[3]..<SNR>183_ProcessJobOutput[104]..<SNR>183_AddExprCallback[174]..<SNR>183_ProcessEntries[6]..<SNR>183_pcall[3]..<SNR>183_ProcessEntries[146]..neomake#signs#PlaceSigns, line 58
Neomake: Error during output processing for clang: Vim(sign):E155: Unknown sign: neomake_file_warn.
```
Here you are.This is all the info i copy from vim.

**Comment by wsdjeg** [comment]
what is  

```
echo g:spacevim_error_symbol
echo g:spacevim_warning_symbol
echo g:spacevim_info_symbol
```

**Comment by brakchen** [comment]
[asciinema recoding](https://asciinema.org/a/JlRGoPbF7pXV7znl7UwIs8tn0)
The error just disappear and I don't know why .It is working fine.

**Comment by brakchen** [comment]
This is error caused i didnot setup some env variables on linux.
Here is a solution to setup correctly
[SOLUTION](https://github.com/asciinema/asciinema/issues/206)

**Comment by wsdjeg** [comment]
Ok. :) so this issue can be closed?

**Comment by brakchen** [comment]
yes
