### ISSUE TITLE
Q: What is the leader key used by fuzzy finder?

### ISSUE THREAD

**Issue by HouzuoGuo** [wsdjeg/SpaceVim#2064]
## Expected behavior
The fuzzy finder is supposed to be invoked by a leader key according to https://spacevim.org/documentation/:

<pre>
Leader f f | Fuzzy find file
</pre>

Earlier in the same manual, it says 
<pre>
default Leader is \
</pre>

I have a fresh spacevim installation with no custom key mapping, and this happens when i try to invoke fuzzy find for files:

<pre>
 ❶  * No Name  ❖ ⓢ                                               | utf-8  6:0  Bot   ❷  vimfiler 
 [+] window next                         [5] tabline index 5                     [\] <Plug>(easymotion-prefix)
 [-] window previous                     [6] tabline index 6                     [l] +Location movement
 [1] tabline index 1                     [7] tabline index 7                     [P] "+P
 [2] tabline index 2                     [8] tabline index 8                     [p] "+p
 [3] tabline index 3                     [9] tabline index 9                     [q] +Quickfix movement
 [4] tabline index 4
 Guide:  <leader>  [C-h paging/help]
 ff
</pre>

What would be the correct key to use with fuzzy finder? Thanks.

## Debug info
https://clbin.com/Jt9WF

**Comment by wsdjeg** [comment]
you need to load a fuzzy find layer. spacevim has 5 fuzzy find layers.

**Comment by xiuliren** [comment]
@wsdjeg I have tried 3 kinds of layers (unite, denite, fzf), but still have the same problem. 
There is no fuzzy find key!
I am currently using fzf layer, this is the options I get:
![image](https://user-images.githubusercontent.com/7651573/44748408-b5d61280-aadd-11e8-823c-1a519dab067a.png)

**Comment by xiuliren** [comment]
Oh, just tried SPC f f, it works!
So the `Leader` key should be `SPC`, this should be corrected in documentation?

**Comment by wsdjeg** [comment]
no， leader is `\ ` by default.

**Comment by pprintz** [comment]
SPC f f works for me as well, while Leader (\) f f is not working

**Comment by Griatch** [comment]
Confirming too, that `\ ff` does not lead to any file fuzzy find and the help buffer has no such entry. 
`SPC ff` opens "Find files in the directory of the current buffer" which does not appear to be the same.

**Comment by wsdjeg** [comment]
you should load one fuzzy finder layer, SpaceVim provides five fuzzy finder layer

________________________________
wsdjeg@outlook.com

**Comment by tkuichooseyou** [comment]
@wsdjeg thanks, I have "denite" loaded and `Leader f f` still doesn't work though

<img width="2038" alt="image" src="https://user-images.githubusercontent.com/1953999/51584331-2744b080-1f18-11e9-924c-a97070472b5b.png">

**Comment by wsdjeg** [comment]
Oh, sorry, the doc is wrong, `Leader f f` has been removed, and in current version, there are two key bindings for searching files, `SPC f f` search files in the dir of current file, `SPC p f` searching files in current project, I will update the doc.

________________________________
wsdjeg@outlook.com
