### ISSUE TITLE
auto `set wrap` only when  working in markdown layer

### ISSUE THREAD

**Issue by kingrongH** [wsdjeg/SpaceVim#2066]
## Description

It's annoying that I have to edit long words in a line when editing markdown files.

And I know `set wrap` works well for me.I do not want to set it everytime or set it globally.

## Request

`set wrap` automatically **only when editing markdown files**

eg：

![screenshot](https://i.loli.net/2018/08/21/5b7b6c7faf165.png "wrap")

Thanks

**Comment by kingrongH** [comment]
add the line below in my config : 

    au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown wrap

works well

**Comment by wsdjeg** [comment]
you do not need to use set ft. this should works too.

```vim
au FileType markdown setlocal wrap
```

**Comment by kingrongH** [comment]
oh yes ,that works!
thanks for your job

**Comment by willismonroe** [comment]
Could this be added to the lang#markdown layer?  It would be very useful.

**Comment by wsdjeg** [comment]
you can use autocmd event within bootstarp function.

**Comment by willismonroe** [comment]
I created a file called ~/.SpaceVim.d/autoload/markdown.vim

and added these contents:
```
function! markdown#after() abort
  au FileType markdown setlocal wrap
  au FileType markdown setlocal spell
endfunction    
```
and then I added this line to my ~/.SpaceVim.d/init.toml
```
bootstrap_after = "markddown#after"
```

But when I open a markdown file (*.md) wrap and spell still aren't set.

**Comment by NightMachinery** [comment]
It doesn’t work for me either. 

```
# ignore the line numbers
func! myspacevim#before() abort                                                  
  6   set wrap                                                                       
  5   augroup custom_autocmd                                                         
  4   ┊ ┊ ┊au!                                                                       
  3   ┊ ┊ ┊au FileType text setlocal textwidth=78                                    
  2   augroup END                                                                    
  1 endf                                                                             
8   func! myspacevim#after() abort                                                   
  1   set wrap                                                                       
  2   au FileType markdown setlocal wrap                                             
  3   au FileType markdown setlocal spell                                            
  4 endf                
```

**Comment by oeyoews** [comment]
> It doesn’t work for me either.
> 
> ```
> # ignore the line numbers
> func! myspacevim#before() abort                                                  
>   6   set wrap                                                                       
>   5   augroup custom_autocmd                                                         
>   4   ┊ ┊ ┊au!                                                                       
>   3   ┊ ┊ ┊au FileType text setlocal textwidth=78                                    
>   2   augroup END                                                                    
>   1 endf                                                                             
> 8   func! myspacevim#after() abort                                                   
>   1   set wrap                                                                       
>   2   au FileType markdown setlocal wrap                                             
>   3   au FileType markdown setlocal spell                                            
>   4 endf                
> ```

-  you should put it in `myspacevim#after()`, Don't repeat  to` set wrap` in two functions
