### ISSUE TITLE
When I press j in normal mode, SpaceVim makes a pause for a second

### ISSUE THREAD

**Issue by gennad** [wsdjeg/SpaceVim#2069]
![screenshot from 2018-08-21 15-40-29](https://user-images.githubusercontent.com/394648/44432906-dc81cf80-a558-11e8-99db-08fb65668614.png)
When I press j in normal mode, SpaceVim makes a pause for a second and only then changes the line.

## Expected behavior, english is required

When I press j in normal mode, SpaceVim should change the line immediately.

## The reproduce ways from Vim starting (Required!)

Open any file with text. Press j, see the pause.

**Comment by gennad** [comment]
If it's not a bug, how to disable this behavior?

**Comment by wsdjeg** [comment]
This because we have `inoremap jk <Esc>` in src, if you do not like this behavior, you can unimap this key binding in bootstrap function.

same as #2020
