### ISSUE TITLE
About document for SpaceVim 

### ISSUE THREAD

**Issue by floatval** [wsdjeg/SpaceVim#2083]
## Now SpaceVim is closely to stable version
  I would like to maintain a document on top of the original.

## This Issues is report schedule of document
  In Mid-September I will start.You can provide your thoughts before this.

**Comment by wsdjeg** [comment]
Hello, in spacevim website I just Add some guide, for example `use spacevim as IDE` for general usage. `Use spacevim as Python IDE` for language specific usage.
