### ISSUE TITLE
Cannot get debug info by pressing <kbd>SPC d</kbd>.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2084]
## Expected behavior: 
I want to get the debug info by pressing <kbd>SPC d</kdb>.

But I get nothing. The command SPDebug works very well. I use Windows 10 and Gvim 8.1 .
## The reproduce ways:
Press <kbd>SPC d</kdb> after Vim starting.
## Debug info
I can get the debug info by the command "SPDebug", but I don't know how to copy them to the clipboard.
The issue template shows that "Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below." but I cannot get the debug info by pressing <kbd>SPC h I</kbd>. What I get is only a blank issue_report.md file opened in vim, and nothing is copied to clipboard.

**Comment by wsdjeg** [comment]
sorry, `SPC d` is for debug layer, and it is for debug project. in current version, SpaceVim's debug info can be get via `SPC h I`. if you want to copy the content in current buffer, you can use `ggVG"+y`, this is usage of vim itself.

**Comment by xylinkun** [comment]
![a](https://user-images.githubusercontent.com/5350867/44586689-339ad500-a7e3-11e8-8c46-804411d1d5ef.gif)
I cannot copy the debug info to clipboard by pressing <kbd>ggVG"+y</kdb>.

**Comment by wsdjeg** [comment]
why use mouse?  just press `SPC h I`, you will see debug info, then press `ggVG"+y` to copy.

**Comment by xylinkun** [comment]
I cannot get the debug info by pressing SPC h I. What I get is only a blank issue_report.md file opened in vim, and nothing is copied to clipboard.

**Comment by xylinkun** [comment]
I cannot copy the debug info to clipboard by pressing ggVG"+y neighter.

**Comment by wsdjeg** [comment]
`black issue_report.md` file? It is a bug!

**Comment by wsdjeg** [comment]
please use gif, what happened when you press `SPC h I`.

**Comment by xylinkun** [comment]
That's just what I want to report to you.  Wait for a monment.
Please do not upgrade the version to 1.0 in a few months. That is my answer to the question you asked in zhihu.

**Comment by xylinkun** [comment]
![a](https://user-images.githubusercontent.com/5350867/44588638-d86be100-a7e8-11e8-9c1e-8d44a3a02f38.gif)

**Comment by wsdjeg** [comment]
what is your  vim version?

**Comment by xylinkun** [comment]
Latest version gVim 8.1 downloaded from vim.org.

**Comment by wsdjeg** [comment]
I can not reproduce this issue. :(
