### ISSUE TITLE
`:set spell` doesn't work.

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#209]
## Expected behavior
Real time spell check is expected.

SpaceVim doesn't work probably even if `<leader>`+`ts` is triggered
## Environment Information
- OS: Arch Linux
- vim version: vim8.0

**Comment by wsdjeg** [comment]
This Should works well, and this Mapping is just run `:set spell`, I think you can read `:h 'spell'`

**Comment by wsdjeg** [comment]
It works  like belows, wrong words well be under line.

![2017-02-07-20 55 57](https://cloud.githubusercontent.com/assets/13142418/22692051/156e24b4-ed78-11e6-99ba-38d1489794c3.png)

**Comment by Gabirel** [comment]
Have ever created something like `spellfile`? It fails again to me.

**Comment by Gabirel** [comment]
I put something like this:
![image](https://cloud.githubusercontent.com/assets/12933851/22727195/7f4e10f2-ee12-11e6-831f-b08981e2b3bc.png)

The wired thing happened here:
1. I just typed `z=`(`z=` means show suggestions if it has spell error.)

2. It shows me like this:
![image](https://cloud.githubusercontent.com/assets/12933851/22727214/adbf511c-ee12-11e6-9691-bf36953935f4.png)

This means spell check do works. But it isn't very willing to mark wrong words to me. 
Eg: 
![image](https://cloud.githubusercontent.com/assets/12933851/22727253/e2c5409c-ee12-11e6-8517-c5a0d329d097.png)

So, any suggestion?

**Comment by wsdjeg** [comment]
I can not reproduce it in both window xp, win 7, and arch linux.

**Comment by Gabirel** [comment]
I finally know why. But not exactly why.

In my virtualOS, which is `Fedora23`, I just installed SpaceVim. More importantly, I just pressed `\ts`. It can find spell errors for me. The picture below can prove:

![image](https://cloud.githubusercontent.com/assets/12933851/23025387/c3c29690-f498-11e6-94b4-ca7a073a6051.png)


However, I wonder whether my `~/.local.vim` is causing this. So I decide to rename my `~/.local.vim` into `~/.local.vim.bak`. Finally it works for me now.
![image](https://cloud.githubusercontent.com/assets/12933851/23025471/1516eece-f499-11e6-9e15-eb16c95e60bf.png)

Here's `.local.vim`:
```vim
let g:spacevim_colorscheme  =   'molokai'
let g:spacevim_max_column   =   80
let g:spacevim_error_symbol =   '✗'
"let g:spacevim_custom_plugins=[
"            \ ['example/vim-example'],
"            \
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#xml')
```

Then I discovered that spell check will do the job if I just un-comment `let g:spacevim_colorscheme  =   'molokai'`.

I do really really want to use this `molokai` theme. Can you fix this since I don't know how to fix this damn tricky thing.

**Comment by wsdjeg** [comment]
I just try to add `let g:spacevim_colorscheme  =   'molokai'` to config, it works well.
![2017-02-16_1362x726](https://cloud.githubusercontent.com/assets/13142418/23026586/b0dfe466-f49c-11e6-9f89-d2520c1164a6.png)

**Comment by Gabirel** [comment]
what??!!
WHY? This doesn't work for me if I enable `molokai`.

**Comment by Gabirel** [comment]
I'm pretty sure about this. It is `molokai` that causes this problem. I copied vimfiles into fedora23.

I can reproduce this problem. But you don't. I guess we have different `vimfiles`.

So, is it necessary for me to delete all of files and reinstall it again?

**Comment by wsdjeg** [comment]
~~Maybe you can have a try, or run `git pull` in `~/vimfiles`.~~

sorry.

**Comment by Gabirel** [comment]
I just reinstall everything which SpaceVim needs. Still the same problem. 

I can't use spell check when `molokai` is enabled. What's in your `.local.vim`? Can you show me please?

Why does it work for you? not for me?

**Comment by Gabirel** [comment]
I tested on another colorschemes.

colorschemes which seem not to support spellcheck or something are as follows:
- atom
- hybrid-material
- peachpuff
- pyte
- ron
- shine
- slate
- torte
- twilight256
- wombat256mod
- zellner
- Keep testing tomorrow......To Be Continued Tomorrow

> Note: some works for me, such as `something(default in SpaceVim)`, `solarized` and etc.

You could try to reproduce with these colorschemes. If you still cannot reproduce, I think you should really look into this issue.

**Comment by Gabirel** [comment]
Also
 ![](https://cloud.githubusercontent.com/assets/13142418/23026586/b0dfe466-f49c-11e6-9f89-d2520c1164a6.png)

your spellcheck doesn't work very well to be exactly as it shows in the picture above. Because `SpaceVim` is not a normal correct word. It should get marked by underline just like github does.

![image](https://cloud.githubusercontent.com/assets/12933851/23032555/aafaa690-f4af-11e6-8c42-7e344a222532.png)

**Comment by Gabirel** [comment]
Tested colorschems can be found here: [Click Me To Find More ColorSchemes In SpaceVim](https://github.com/SpaceVim/SpaceVim/blob/dev/doc/SpaceVim.txt#L324)

colorschemes which seem not to support spellcheck or something are as follows:
- atom
- blue
- darkblue
- default
- delek
- desert
- elflord
- evening
- focuspoint
- hybrid-material
- industry
- koehler
- molokai(`fixed already`)
- molokayo
- morning
- murphy
- pablo
- peachpuff
- pyte
- ron
- shine
- slate
- torte
- twilight256
- wombat256mod
- zellner

@wsdjeg These are colorthemes that seem not to support spell check.
> Note: I didn't test all colorthemes in `base16-*`. Just a few tested. They passed. I guess they belong to the same author who may consider about supporting spell check. So, I ignored testing them all. I wish they all could work.

**Comment by Gabirel** [comment]
I looked into their source code in `flatcolor` and `molokai`.

`flatcolor` ==> [flatcolor.vim#L191](https://github.com/rafi/awesome-vim-colorschemes/blob/master/colors/flatcolor.vim#L197)

`molokai` ==> [molokai.vim#L203](https://github.com/rafi/awesome-vim-colorschemes/blob/master/colors/molokai.vim#L202)

Does it means that `molokai` doesn't have any underline mark? Just `flatcolor` has this feature?

`flatcolor`:
![image](https://cloud.githubusercontent.com/assets/12933851/23052305/42d66fc0-f50b-11e6-9911-685d82c25053.png)

`molokai`:
![image](https://cloud.githubusercontent.com/assets/12933851/23052316/55a84998-f50b-11e6-8e5c-4500df2a5540.png)

**Comment by wsdjeg** [comment]
Can you test in other terminal? For example termite

**Comment by Gabirel** [comment]
My terminal is the very normal one, which is `xfce4-terminal`.

Yes, It has no connection with any terminal. Other terminals have the same problem, including `termite`. 

Have you ever tried other colorschemes? As I said before, your spellcheck doesn't works very well too.

**Comment by Gabirel** [comment]
You can remote `No reproduce` label right now. Because I've already know why and how to solve it.

I ported a `molokai` theme from `tomasr/molokai`. 

Right now, I can use spell check very well.

![image](https://cloud.githubusercontent.com/assets/12933851/23054428/d41dca96-f51a-11e6-98b7-767870810802.png)

I suggest that you could change [['tomasr/molokai']](https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/layers/colorscheme.vim#L141)
 into `['Gabirel/molokai']`. If you allow me to submit a PR, I can do that. :smiley: 

BTW, it does have few bugs right now. But I can fix those later.

**Comment by wsdjeg** [comment]
PR welcome. You can merge @justinmk's molokai fork.

**Comment by Gabirel** [comment]
I've already merged justinmk's molokai.

Also, you should remove `No reproduce` label right now.
