### ISSUE TITLE
how can i display full path at statusline

### ISSUE THREAD

**Issue by JimmyHoSF** [wsdjeg/SpaceVim#2093]
i want to display full path at statusline permanently, how can I do it?

**Comment by crisidev** [comment]
Same here. It would be nice to have it configurable..

**Comment by wsdjeg** [comment]
@hcgcarry @crisidev by default SpaceVim will show the file path when you open twi files with same file name.

**Comment by JimmyHoSF** [comment]
but i want not only open two file with same name but also  single file

**Comment by wsdjeg** [comment]
hmm, I will try to add this feature, and an option will be added for this feature, disabled by default.

as spacevi's statusline is different than airline or any other plugins, it has too many content on it. if you want to enable this feature, you should make sure your PC screen is big enough.
