### ISSUE TITLE
Disable conceal feature for TeX/LaTeX by default

### ISSUE THREAD

**Issue by weidenka** [wsdjeg/SpaceVim#2095]
## Expected behavior, english is required
Concealed feature of vim should be disabled for TeX/LaTeX by default. Otherwise typing math formular is impossible.
## The reproduce ways from Vim starting (Required!)
Open any TeX file and start typing e.g. $\rightarrow$. Already when tying $ the problem is obvious.
## Debug info
[debug.txt](https://github.com/SpaceVim/SpaceVim/files/2324752/debug.txt)
## Screenshots
https://asciinema.org/a/Kpj8I6z0Ktfof7znjyGjt43ON
## Solution
I add some lines to ```boostrap_after```:
```
au BufWrite *.tex set conceallevel=0
au BufWrite *.tex set concealcursor=""
set conceallevel=0
set concealcursor=""
```
If I open a file I have to write it once in order to set the variables. Unfortunatly, BufRead etc. are NOT working here. I have no idea how to do it better.

**Comment by wsdjeg** [comment]
SpaceVim do not has latex layer now, but it has been added to todo list. please see #2046

**Comment by weidenka** [comment]
I'm fine with loading vimtex myself. But my point here is that I consider it a bug that the conceal feature is enabled for tex files. I mean it is ibviously not enabled for all file types. Why can't we simply remove it for tex files, too? Unfortunatly, I have no idea on how to do that.

**Comment by weidenka** [comment]
A proper solution is to set ```au BufRead *.tex let g:indentLine_setConceal = 0```
in your bootstrap_before method. I think this should be a default setting of SpaceVim. Otherwise, as mentioned above, editing TeX documents is impossible.

**Comment by wsdjeg** [comment]
OK, I will try to look into this issue.

**Comment by wsdjeg** [comment]
see #2531
