### ISSUE TITLE
Toggle for SmartTab

### ISSUE THREAD

**Issue by adawalli** [wsdjeg/SpaceVim#2096]
The smart tab functionality is usually great...but it would be nice to have a toggle for when we need it explicitly off

Can this be added to the `[SPC]t` menu?

**Comment by wsdjeg** [comment]
you need to insert a tab? or you need to insert 4 spaces?

**Comment by adawalli** [comment]
It switched to spaces but I needed tabs

**Comment by wsdjeg** [comment]
This is feature of vim itself. and spacevim enable enpandtab by default, if you want to insert a tab instead of  spacevim, just press `<C-v><tab>`. or run `:set noexpandtab`.

**Comment by adawalli** [comment]
Thanks - for some reason, I thought spacevim hooked this. Closing request!

**Comment by wsdjeg** [comment]
OK :)
