### ISSUE TITLE
Two questions about tags layer.

### ISSUE THREAD

**Issue by shawnyangcis** [wsdjeg/SpaceVim#2098]
I found that there are three plugins in tags layer:
- [ludovicchabant/vim-gutentags](https://github.com/ludovicchabant/vim-gutentags)
- [SpaceVim/gtags.vim](https://github.com/SpaceVim/gtags.vim)
- [tsukkee/unite-tag](https://github.com/tsukkee/unite-tag)
and also other plugins, like **denite-gtags**.

So two things baffle me:
1. **[ludovicchabant/vim-gutentags](https://github.com/ludovicchabant/vim-gutentags)** is a plugin for tags file management, which supplies a suite of interfaces. Why not use it only, or use some other similar plugins instead, such as [jsfaint/gen_tags.vim](https://github.com/jsfaint/gen_tags.vim). In a word, there might be plugins redundancy in tags layer.
2. The key mapping for tags layer just handles the tags file in current project dir, which smudges project dir. I found the tag dir existing in ~/.cache/tags/, which was generated by gutentags automatically. But they are not seem used.

**Comment by wsdjeg** [comment]
@yangyinqi I want to use SpaceVim/gtags.vim to replace vim-gutentags. gutentags is a plugin for manager tags file which can be done in gtags.vim.  unite-tag should be used only when unite layer is loaded, we have 5 fuzzy find layer. maybe we also need to use change the plugin for other fuzzy finder layer.

**Comment by shawnyangcis** [comment]
It will be better that setting up a special directory for tags file, instead of project local directory.
