### ISSUE TITLE
Feature request: testing layer

### ISSUE THREAD

**Issue by Fetz** [wsdjeg/SpaceVim#2099]
Currently I'm using https://github.com/janko-m/vim-test as a testing layer in SpaceVim and maybe will be cool for others too. If yes I can try to create a PR for a new layer.

Currently I'm using this configuration:

```viml
" > in init.toml
[[custom_plugins]]
name ="janko-m/vim-test"

" > in autoload/myspacevim.vim#before

  " Tests Layer
  call SpaceVim#custom#SPCGroupName(['k'], '+Test')
  call SpaceVim#custom#SPC('nore', ['k', 'n'], 'TestNearest', 'nearest', 1)
  call SpaceVim#custom#SPC('nore', ['k', 'f'], 'TestFile', 'file', 1)
  call SpaceVim#custom#SPC('nore', ['k', 's'], 'TestSuite', 'suite', 1)
  call SpaceVim#custom#SPC('nore', ['k', 'l'], 'TestLast', 'last', 1)
  call SpaceVim#custom#SPC('nore', ['k', 'g'], 'TestVisit', 'visit', 1)

 " trying https://github.com/uptech/alt to alternate between test and code
 " but doesn't work for projects using lerna or tests in folder __tests_
 " looking for another smarter alternative
 " call SpaceVim#custom#SPC('nore', ['k', 't'], 'call AltCommand(expand("%"), ":e")', 'alternate source/test', 1) 
```

**Comment by wsdjeg** [comment]
I am ok with this key bindings.  but I do not use this plugins, I need to test it with other layers. BTW does the author of this plugin will provide supports for this layer?

**Comment by Fetz** [comment]
I [created an issue](https://github.com/janko-m/vim-test/issues/316) on their repo asking if they can provide support

**Comment by janko** [comment]
Author of vim-test here 👋. Yes, I'd be ok with providing support for this feature, especially if vim-test introduces any breaking changes.
