### ISSUE TITLE
transition between tabs

### ISSUE THREAD

**Issue by onerciller** [wsdjeg/SpaceVim#210]
is there shortcut for transition between tabs ?  i cannot find in documentation

![untitled](https://cloud.githubusercontent.com/assets/7740849/22617602/ec2e89fc-ead1-11e6-8410-5bb508bc56eb.png)

**Comment by wsdjeg** [comment]
You can you `<leader>` + 1-9 jump to the index, if you are using neovim, you can use `Alt + 1-9` and `Alt + right or left`

**Comment by wsdjeg** [comment]
BTW, you can install the font https://github.com/wsdjeg/DotFiles/tree/master/fonts

**Comment by onerciller** [comment]
thanks for your support and help I have advice for you, you should take video or gif in order to using shortcut in spacevim. spacevim is awesome and has many features but maybe I dont use its many features.
current documantation is pretty good but it is not enough according to me

**Comment by Gabirel** [comment]
@onerciller The current documentation isn't enough for everyone. HAHAHAHA

You can see more details by pressing `f` + `ma`

**Comment by onerciller** [comment]
thanks @Gabirel  i will try it :)

**Comment by Guangyi-Z** [comment]
Hello, `<leader>+NUM` still takes me quite a while to act.
So we don't have the traditional `gt` and `gT` or similar alternatives?

**Comment by wsdjeg** [comment]
gt/T should also works

**Comment by jia2** [comment]
Alt + 1-9 also works on gvim on windows.
