### ISSUE TITLE
Current line not highlighted after SpaceVim start.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2103]
## Expected behavior, english is required
I hope SpaceVim appears same no matter how/when I open the startify. More specifically, I hope current line is highlighted after SpaceVim start as it is configured to highlight current line by default.

## The reproduce ways from Vim starting (Required!)
By default, SpaceVim can highlight the current line. But in the startify page, current line is not highlighted after SpaceVim start, while current line is highlighted when I open the startify with <kbd>SPC a s</kbd>.

## Debug info
I want SpaceVim to highlight cursor column by adding a line "set cursorcolumn" to the bootst_after function, and it works very well. But it also highlight the cursor column in the startify page, it appears not so good and current line is not highlight. But when I open the startify page by pressing <kbd>SPC a s</kbd>, SpaceVim appears exactly what what I want.

**Comment by wsdjeg** [comment]
I can not understand this issue, cursorline or cursorcolumn?

**Comment by wsdjeg** [comment]
add `enable_cursorcolumn = true` to spacevim options. will highlight cursorcolumn in normal mode, and insert mode, both line and column will not be highlight. this feature is enabled in all buffer, included startify buffer.

**Comment by xylinkun** [comment]
I found this option when I read the SpaceVim-config today . I should not use the vim option "set cursorcolumn". Thank you for your reply.
