### ISSUE TITLE
How can I replace yapf with black for formatting python files?

### ISSUE THREAD

**Issue by gennad** [wsdjeg/SpaceVim#2106]
I'm enjoying cmd - b - f but I like [black](https://github.com/ambv/black) formatter more than yapf.
Can I replace yapf with black? What should I do to make it happen? Thank you!

**Comment by wsdjeg** [comment]
@gennad in format layer, `SPC b f` means `:Neoformat`, so you can read `:h neoformat` and change the default format tool for python. and these plugin options can be put into bootstrap function.

**Comment by gennad** [comment]
:+1:  Thank you
