### ISSUE TITLE
Why not make the keybindings consistent with spacemacs?

### ISSUE THREAD

**Issue by oliveratutexas** [wsdjeg/SpaceVim#211]
Just curious as to why you made that decision. Spacemacs won't auto-install on the machine that I'm on, so I tried your expecting the same kind of experience, but was surprised that you decided on that choice.

**Comment by wsdjeg** [comment]
@oliveratutexas Thanks for the feedback, so what feature do you want? as I can see:
1. disable checkinstall plugin by default, there should be an option to set it.
2. use `<space>` as leader? it is easy setting in spacevim, just add `let mapleader = "\<space>"` to your `~/.SpaceVim.d/init.vim`

so anything else?

**Comment by oliveratutexas** [comment]
Oh I suppose also having the pop-up appear with the labels for each key. I
kinda need that cause just having a list of the keybindings is hard to
learn.

**Comment by wsdjeg** [comment]
It is vim feature, what only can be implement is two kinds of key mapping guide:
![2017-02-05_1359x721](https://cloud.githubusercontent.com/assets/13142418/22622826/f88881a8-eb80-11e6-880b-b12e0430689a.png)

 ![2017-02-01_1359x723](https://cloud.githubusercontent.com/assets/13142418/22507351/24af0d74-e8c0-11e6-985e-4a1404b629ed.png)

**Comment by oliveratutexas** [comment]
Hmm okay. Maybe there were errors when I installed it. I'll try it again. Thank you!

**Comment by wsdjeg** [comment]
Welcome, if you get any issues, please let me know, Maybe I can help with that.

**Comment by wsdjeg** [comment]
Hi @oliveratutexas what feature do you want, and what is the issue?

**Comment by oliveratutexas** [comment]
Oh no, my bad, I'm just.... I'm just bad at this lol. Sorry.

Um, the particular issue I had was getting weird character showing up randomly. I don't think I was having that issue beforehand.
[
![screenshot_2017-02-07_10-49-27](https://cloud.githubusercontent.com/assets/4792608/22701397/2ece62c0-ed23-11e6-9487-04cc84d70982.png)
![screenshot_2017-02-07_10-49-07](https://cloud.githubusercontent.com/assets/4792608/22701398/2ecf42b2-ed23-11e6-8142-fccdb0cbd05c.png)

](url)

**Comment by wsdjeg** [comment]
@oliveratutexas how do you get this chars?

**Comment by wsdjeg** [comment]
I can not understand this issue, is it issue with SpaceVim?
