### ISSUE TITLE
Unable to get debug info on old vim

### ISSUE THREAD

**Issue by rcasta74** [wsdjeg/SpaceVim#2126]
## The reproduce ways from Vim starting (Required!)
Start old vim, for example from centos 7.5:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 10 2018 23:54:40)
Included patches: 1-160, 399, 402-403, 1099
```
Press <kbd>SPC h I</kbd> and you will get error:
```
Error detected while processing function SpaceVim#issue#report..<SNR>211_open..<SNR>211_template..<SNR>14_execute..SpaceVim#logger#viewLog..SpaceVim#health#report..Spac
eVim#health#environment#check:
line    2:
E121: Undefined variable: v:progpath
E116: Invalid arguments for function add
Error detected while processing function SpaceVim#issue#report..<SNR>211_open..<SNR>211_template..<SNR>14_execute:
line    9:
E171: Missing :endif
```
Type `:SPDebugInfo` and you will get error:
```
Error detected while processing function SpaceVim#logger#viewLog..SpaceVim#health#report..SpaceVim#health#environment#check:
line    2:
E121: Undefined variable: v:progpath
E116: Invalid arguments for function add
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
`v:progpath` is a missing feature in your vim, I will try to add compatible API for it.

**Comment by rcasta74** [comment]
The fix resolve the error 'Undefined variable: v:progpath', but the issue template is still not properly opened on old vim since the result of command ':SPDebugInfo' is missing.
This happen because the command ':SPDebugInfo' is executed with the compatible 'execute' function, but running the function 'SpaceVim#options#list' within 'SpaceVim#logger#viewLog' the compatible 'execute' function is called again, so the command ':redir => output' is called again before the command ':redir END' closing the active redirection.

**Comment by wsdjeg** [comment]
got  it. I will try to fix it.
