### ISSUE TITLE
Unable di disable plugins on old vim.

### ISSUE THREAD

**Issue by rcasta74** [wsdjeg/SpaceVim#2129]
## Expected behavior, english is required
We should be able to disable plugins on old vim using neobundle plugin manager.

## The reproduce ways from Vim starting (Required!)
Add a disabled_plugins list into .SpaceVim.d/init.toml using old vim (without patch-7.4.2071)
Starting vim now, following error will appear:
```
Error detected while processing function SpaceVim#custom#load..SpaceVim#custom#apply:
line    5:
E706: Variable type mismatch for: value
```
After solving it with following patch:
```
diff --git a/autoload/SpaceVim/custom.vim b/autoload/SpaceVim/custom.vim
index 0c306d77..b7d3a348 100644
--- a/autoload/SpaceVim/custom.vim
+++ b/autoload/SpaceVim/custom.vim
@@ -85,6 +85,7 @@ function! SpaceVim#custom#apply(config) abort
     let options = get(a:config, 'options', {})
     for [name, value] in items(options)
       exe 'let g:spacevim_' . name . ' = value'
+      unlet value
     endfor
     let layers = get(a:config, 'layers', [])
     for layer in layers
```
the plugins are still not disabled since the default plugin_manager selected is neobundle

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Thanks for your hotfix.
