### ISSUE TITLE
Will SpaceVim support defx.nvim as default file explorer?

### ISSUE THREAD

**Issue by ZhiruiLi** [wsdjeg/SpaceVim#2135]
From https://github.com/Shougo/vimfiler.vim :
Active development on vimfiler.vim has stopped. 
The new plugin is https://github.com/Shougo/defx.nvim , which depends on denite.nvim
Will SpaceVim support defx.nvim as default file explorer?

**Comment by wsdjeg** [comment]
of cause when it is stable.
