### ISSUE TITLE
problem about fold

### ISSUE THREAD

**Issue by latpaw** [wsdjeg/SpaceVim#2142]
## Expected behavior, english is required  
auto fold  
## The reproduce ways from Vim starting (Required!)  
vim open a js file  
  
nothing error.  
but foldmethod is set to manual, and i can not create a fold manually.  
It has to set foldmethod to syntax everytime   
Add bootstrap_after and bootstrap_before as the documentation, it just don't work.  
  
![image](https://user-images.githubusercontent.com/1464608/45203605-45827a80-b2af-11e8-8b41-0c723b365c29.png)

**Comment by wsdjeg** [comment]
@latpaw What is the result of `:verbose set foldmethod`?

**Comment by latpaw** [comment]
@wsdjeg just "foldmethod=manual"
![image](https://user-images.githubusercontent.com/1464608/45204655-7b752e00-b2b2-11e8-809d-9e70881364dd.png)

**Comment by wsdjeg** [comment]
SpaceVim do not set the foldmethond thouth, It should be a upstream plugin, in bootstrap functinon, I think you can use

```vim
augroup myspacevim
  au!
  au FileType javascript setlocal foldmethod=syntax
augroup END
```

**Comment by latpaw** [comment]
@wsdjeg , thanks , problem solved

**Comment by danshumaker** [comment]
Hi, my php folds are not working.  I'm new to SpaceVim and the above "boostrap function" doesn't look like the toml format. I was under the impression that ~/.SpaceVim.d/init.toml was where all the customizations should go?
Where should the above function go (assuming it is still the proper fix for my folds)?

**Comment by xiuliren** [comment]
It turns out that I have to edit the system file to change it to manual
`/usr/share/nvim/runtime/ftplugin/rst.vim`
