### ISSUE TITLE
Chinese andicons  display normally in the vim and mvim -v when use iterm2 , but not in the macvim.

### ISSUE THREAD

**Issue by Huang-Jinxian** [wsdjeg/SpaceVim#2148]
## question
when I open the Mac vim, the some icon in the GUI can't display.
And I have the correct setting follow the issue #771 .But the icon is still undisplay.

## platform
* OS: Mac OS 10.13.6
* item2
* Default vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)
* MACVIM version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 14 2018 05:28:49)
* Space vim version: version : 0.9.0-dev   by : spacevim.org

## Screenshots
- iterm2 setting
![iterm2 setting](https://user-images.githubusercontent.com/22197930/45252809-9073bf00-b38f-11e8-9e12-1ac88de4ab40.png)

- display on the vim in iterm2
![iterm2 is normal](https://user-images.githubusercontent.com/22197930/45252673-1b06ef00-b38d-11e8-95c1-7f54656dc414.png)

- display on the mccvim 
![this is in macvim](https://user-images.githubusercontent.com/22197930/45253191-dd5a9400-b395-11e8-81d5-ea6ab80a0241.png)

**Comment by wsdjeg** [comment]
This is usage of macvim, you need to change the macvim's fonts.
