### ISSUE TITLE
when I install spacevim, will it remove my original vim?

### ISSUE THREAD

**Issue by makerjackie** [wsdjeg/SpaceVim#2152]
I want to try spacevim, but I'm afraid that it would remove my original vim, which means I have to config my vim again if I don't want to use spacevim, especially, I have to reinstall "youCompleteMe" plugin, which is a little time consuming

**Comment by makerjackie** [comment]
No, it won't remove your vim, but it will rename it to vim backup, if you don't want to use spacevim, simply run the command below, and you can get back to your original vim. 
```
curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
```

I think the official document is not that good, it should **emphasis** that old vimer can try spacevim without worrying about their originial vimrc. I will try to improve spacevim doc if I have time.

**Comment by wsdjeg** [comment]
Thanks. Maybe add tips to faq is better?

**Comment by makerjackie** [comment]
Sorry, I do not have a habit to look at github's wiki (so I didn't find FAQ a few days ago). But I think many people won't read github wiki too, instead, we just look at https://spacevim.org/. It would be better to add FAQ to the home page of https://spacevim.org/.

**Comment by makerjackie** [comment]
homepage's FAQ and mandarin's version is out-of-date

**Comment by wsdjeg** [comment]
in home page we only list few question, and a link to faq page:
https://spacevim.org/faq/

**Comment by wsdjeg** [comment]
missing link to faq in spacevim home page, I will add it.
