### ISSUE TITLE
close file on vue project was too slow.

### ISSUE THREAD

**Issue by yb3616** [wsdjeg/SpaceVim#2154]
## Expected behavior, english is required
close vim immediately when i type `:qa`

## The reproduce ways from Vim starting (Required!)
1. create vue project with vue-cli3 `vue create my-app`
2. `cd my-app`
3. `nvim src/App.vue`
4. `:qa` immediately 
5. all done.
Through `htop`, I found it is because of the program  `ctags -f ...`  is running when i close vim/neovim. I guess vim was waiting for  it before close itself.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![01](https://user-images.githubusercontent.com/8839021/45275067-207b4b00-b4ed-11e8-91b2-d62cbfe0c4b3.PNG)

**Comment by wsdjeg** [comment]
you should provide more debug info.

**Comment by wsdjeg** [comment]
1. I think you should show the full command line of ctags, in the picture, I can not see the full command line, then I do not know wchich plugin call this command.
