### ISSUE TITLE
My Nerdtree do not show git status!

### ISSUE THREAD

**Issue by rivalak** [wsdjeg/SpaceVim#2156]
## Screenshots

![image](https://user-images.githubusercontent.com/42036026/45307616-09bb0f80-b552-11e8-8fd9-a01c54cd2acc.png)
## What is more
I tried to the commond :checkhealth, and this is the result.
![image](https://user-images.githubusercontent.com/42036026/45307736-61597b00-b552-11e8-8ad3-c48177e42af0.png)
And I tried to rebuild my neovim as the advice, but it was making no much difference.

**Comment by wsdjeg** [comment]
by default, we use vimfiler instead of nerdtree. to enable git status, you can use:

```toml
[options]
    enable_vimfiler_gitstatus = true
```

**Comment by rivalak** [comment]
i

**Comment by rivalak** [comment]
I am afraid my vimfiler is not working either. According to your advice, I disable the nerdtree and add the "enable_vimfiler_gitstatus = true" in my init.toml, but it is not working.
### screenshots
![image](https://user-images.githubusercontent.com/42036026/45338628-ad430900-b5c0-11e8-927d-cf8f61659133.png)

**Comment by rivalak** [comment]
I have solved this problem ! The key to avoid this issues is the root directory in your nerdtree must be a git folder.
