### ISSUE TITLE
statusline change to inactive when open and close denite buffer.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2159]
@Shougo 

Thanks for create denite, and I just find a issue when using it in SpaceVim, SpaceVim use `WinEnter` autocmd to change the statusline, but I hope denite works same as temp buffer, which means this buffer will be closed after item is selected. 

so I need:

1. denite do not sent WinLeaver to previous windows when is it openned.
2. call WinEnter autocmd when use `q` in normal mode to close denite.

**Comment by wsdjeg** [comment]
as a temp fix for this issue:

```viml
func! s:warp_denite(cmd)
     set ei=WinEnter,WinLeave
     exe a:cmd
     set ei&
     doautocmd WinEnter
endf
```

useing denite:

```vim
call s:warp_denite('Denite outline')
```

**Comment by Shougo** [comment]
> Thanks for create denite, and I just find a issue when using it in SpaceVim, SpaceVim use WinEnter autocmd to change the statusline, but I hope denite works same as temp buffer, which means this buffer will be closed after item is selected.

I don't fully understand.  I think you should not use WinEnter autocmd for the feature.

denite may not send events.  If so, I will fix.

Please describe the behavior more clearly.

> denite do not sent WinLeaver to previous windows when is it openned.

I won't change the behavior.
Because WinLeave event should be sent.

> call WinEnter autocmd when use q in normal mode to close denite.

I don't understand.  Please compare denite with other buffer behavior.
I will check it.

**Comment by wsdjeg** [comment]
@Shougo Thanks for reply, I can not reproduce it in simple vimrc, the only issue is, when open denite buffer, then do not select any item, just press `esc q` to close the denite buffer, after clossing denite buffer, the statusline of current windows shows it is inactive windows.
