### ISSUE TITLE
the `g:spacevim_disabled_plugins` option does not work well

### ISSUE THREAD

**Issue by jiahut** [wsdjeg/SpaceVim#216]
## Environment Information
- OS:  macOs 10.12
- vim version: vim8 

###  configuration 
> vim   ~/.SpaceVim.d/init.vim

```vimscript
...
" add custom plugins.
let g:spacevim_custom_plugins = [
            \ ['tpope/vim-commentary'],
            \ ]
" disable particular plugin
let g:spacevim_disabled_plugins = [
            \ ['scrooloose/nerdcommenter'],
            \ ]
```

when restart vim, I fond that the `scrooloose/nerdcommenter` plugin had enabled all of the same.

**Comment by wsdjeg** [comment]
This options works well, but `'scrooloose/nerdcommenter'` is merged plugin, so you need `call dein#recache_runtimepath()`, and restart vim.

**Comment by wsdjeg** [comment]
and merge feature is a great idea of dein.vim, it make vim start faster,so I do not want to change it to unmerged plugin.

**Comment by jiahut** [comment]
could add each plugin with `enabled`option ? so user can cover its option to `disabled` global.

**Comment by wsdjeg** [comment]
I can not understand, what do you want?

**Comment by jiahut** [comment]
@wsdjeg  make the each plugin as an object,  the `enabled` option is its property. 
then loading the plugins can rely on its `enabled` property , the default is true,  and it can be configured in custom scripts.

**Comment by wsdjeg** [comment]
SpaceVim has same thing Like this, you can use layer.
