### ISSUE TITLE
My spacevim can not  enable autocomplete

### ISSUE THREAD

**Issue by rivalak** [wsdjeg/SpaceVim#2161]
## Screenshots
![image](https://user-images.githubusercontent.com/42036026/45490052-aff85680-b798-11e8-9622-074218d202d8.png)

**Comment by wsdjeg** [comment]
if you enable ycm in SpaceVim, the ycm should be downloaded into:

```
~/.cache/vimfiles/repos/github.com/Valloric/YouCompleteMe/
```

you need to compile it, read the doc of ycm.

**Comment by rivalak** [comment]
Thank you very much !
That works for me.
### screenshot
![image](https://user-images.githubusercontent.com/42036026/45490977-2007dc00-b79b-11e8-88da-4adcc0a0038c.png)

**Comment by wsdjeg** [comment]
welcome :)
