### ISSUE TITLE
About SpaceVim Markdown document syntax problem

### ISSUE THREAD

**Issue by TyCoding** [wsdjeg/SpaceVim#2166]
## Using SpaceVim  Write Markdown document encounter a problem 

For Example: use SpaceVim wrte Markdown, if write `**` two star, in the SpaceVim, will hide this two star, if you write one or there star, SpaceVim will test syntax problem, but we can't see.

in SpaceVim:

![9dfb0bb02f1548064f24b5110529cc21](https://user-images.githubusercontent.com/36946717/45582667-6ae23a80-b8e6-11e8-805c-1585c1e9f589.jpg)

but in practice:
![9ce7e492cc23951eab99a045c76090e3](https://user-images.githubusercontent.com/36946717/45582669-70d81b80-b8e6-11e8-827d-2edf39dc81dd.jpg)

if setting `set cocu=` will 
![6fa64884-018d-4b26-a3ee-1b20497c40b5](https://user-images.githubusercontent.com/36946717/45582672-759ccf80-b8e6-11e8-9db3-dd92da8dbf20.png)

so, What solutions do you have?

**Comment by wsdjeg** [comment]
same issue in json file, I think It should be a plugin which change the cocu option. In SpaceVim we should prvide an option to setting this, and other plugin should not override it.

**Comment by wsdjeg** [comment]
see #2531
