### ISSUE TITLE
How do I set vim's settings?

### ISSUE THREAD

**Issue by xahon** [wsdjeg/SpaceVim#2167]
I want to add `cursorcolumn` with its `highlight` command

here is what I had in `vimrc`

```Vim
set cursorcolumn
:hi CursorColumn cterm=NONE ctermbg=238 guibg=238 guifg=white
```

Where should I write it now?
~/.vimrc doesn't seem to be sourced

**P.S.** I tried to do like this https://github.com/SpaceVim/SpaceVim/issues/1704#issuecomment-388600338 but it's not working too

**Comment by wsdjeg** [comment]
I have tried with neovim, add 

```
set cursorcolumn
:hi CursorColumn cterm=NONE ctermbg=238 guibg=238 guifg=white
```

to bootstrap function, `set cursorcolumn` works well, the highlight does not work, It is because colorscheme always change the the highlight of the CursorColumn.

and in vim8, you can not use the color number 238, and I get this error

```
E254: Cannot allocate color 238
```

**Comment by llllIIIIllll** [comment]
add your command in `~/.SpaceVim/vimrc `

**Comment by wsdjeg** [comment]
pleace read the [documentation of SpaceVim](https://spacevim.org/documentation/), and you should check `:h SpaceVim` in vim.

**Comment by pjfitzgibbons** [comment]
SpaceVim document actually does not address how to set base-vim settings (like for ctrl-p).

**Comment by acgreek** [comment]
Some one needs to address this. I don't see how I can continue using spacevim without a number of my custom setting I've gotten used to over the years. I have a hard time accepting that there isn't a way to add a native vim setting, someone just needs to document how to do or else I need to dedicate probably half a day of hacking to figure it out

**Comment by wsdjeg** [comment]
you should read bootstrap function section in spacevim document.

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] How do I set vim's settings? (#2167)
发件人：Anthony Carathimas
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,State change


Some one needs to address this. I don't see how I can continue using spacevim without a number of my custom setting I've gotten used to over the years. I have a hard time accepting that there isn't a way to add a native vim setting, someone just needs to document how to do or else I need to dedicate probably half a day of hacking to figure it out

―

**Comment by haukebruno** [comment]
Same question here.

I've tried the approach of https://github.com/SpaceVim/SpaceVim/issues/1853#issuecomment-398883972

_~/.SpaceVim.d/autoload/myconfig.vim_
`set colorcolumn=80`

In _~/.SpaceVim.d/init.toml_ I use `bootstrap_after = "myconfig#after"` but this doesn't help. My goal is to always display the colorcolumn.

Disclaimer: Spacevim noob + vim beginner. :grimacing:

**Comment by qins** [comment]
@haukebruno Try this:

1. add `bootstrap_after = "myconfig#after"` to  options in ~/.SpaceVim.d/init.toml
2. In ~/.SpaceVim.d/autoload/myconfig.vim add:
```
function! myspacevim#after() abort
  set noro
  and other commands
endfunction
```
then open new vim ;D

**Comment by haukebruno** [comment]
Thanks @qins 
This works like a charm, I appreciate that :)

**Comment by jerabaul29** [comment]
Note for users of neovim, the file to edit is ```.SpaceVim/init.vim```

**Comment by jerabaul29** [comment]
Seems also ```.SpaceVim/config/neovim.vim``` is also fine.

**Comment by wsdjeg** [comment]
You should not edit any file in `~/.SpaceVim`, use bootstrap function instead.

**Comment by jerabaul29** [comment]
Mmh, ok, so you recommend the qins solution then rather, right?

**Comment by wsdjeg** [comment]
To use vimscript, you need to read the bootstrap function doc. in bootstrap function, you can use vimscript instead of toml.

**Comment by fireglow** [comment]
For anybody also finding this issue, there is another project called [space-vim](https://github.com/liuchengxu/space-vim), which includes a visible place for user configurations as a default.
The `private/` directory has its own [README](https://github.com/liuchengxu/space-vim/blob/master/private/README.md), and the necessary [`UserInit()`](https://github.com/liuchengxu/space-vim#userinit) and [`UserConfig()`](https://github.com/liuchengxu/space-vim#userconfig) functions are also documented.
