### ISSUE TITLE
No fold found in python file

### ISSUE THREAD

**Issue by hrishikeshvganu** [wsdjeg/SpaceVim#2168]
## Expected behavior, english is required
1. Spacevim with neovim standard configuration
2. python and autocomplete layers installed in `init.toml`
3. When I press `zA` all levels should be folded

## The reproduce ways from Vim starting (Required!)
1. Start nvim
2. Press `zA` when editing a python file
3. I get a `No folds found error (see screenshot)`

## Debug info
When I run `:set foldmethod=indent` the same command `zA` and related `zM`works flawlessly

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![image](https://user-images.githubusercontent.com/7539765/45585318-12b83200-b900-11e8-89d2-6f851d47ad27.png)

**Comment by wsdjeg** [comment]
SpaceVim do not change the foldmethon by default, if you want to change it, please add it to bootstrap function.

**Comment by hrishikeshvganu** [comment]
Ok. But then isn't this a bug in the lang#python layer? if a file type needs indent based fold that should just work if the corresponding layer is active

**Comment by wsdjeg** [comment]
It is not a bug, in vim we have many methon to fold code, ident is not default method. and no python plugin use it as default.

**Comment by budisentosa** [comment]
@wsdjeg 
is there any workaround, so on python file load = always set foldmethod=indent ?
shoud i put on init.toml ?
how? 
ty b4

**Comment by Hernrup** [comment]
I would also like to know how to set foldmethod=indent for only python files in the best way.

**Comment by danshumaker** [comment]
I have the same issue with PHP folds not working. It looks like we should install the https://github.com/rayburgemeestre/phpfolding.vim  plugin.. Or is there a better way?

**Comment by spicelfreep** [comment]
no way  I  don't want to install a plugin any way!!!

**Comment by austinmw** [comment]
Also curious about how to `:set foldmethod=indent` for all `.py` files

**Comment by setpill** [comment]
This is a bug or missing feature - it is clearly expected that having a language layer active should configure folds correctly for that language if opening files of that type. Please reopen.

**Comment by setpill** [comment]
FWIW this seems to work as a tempfix:

```
[[custom_plugins]]
	name = 'tmhedberg/simpylfold'
	on_ft = ['python']
```

**Comment by wsdjeg** [comment]
@setpill the foldmethod is not changed in spacevim as I know. if you think this is a missing feature, please use new issue for feature request.
