### ISSUE TITLE
Vim native functions that doesn't work

### ISSUE THREAD

**Issue by lilydjwg** [wsdjeg/SpaceVim#217]
I find the following functions doesn't work as expected by a Vimer:

* open cmdwin with `q:`, `q/`, `q?`
* open cmdwin in ex-mode with `<C-f>`
* record macros with `qX`. This is replaced by `\qrX`, but it should be documented to newcomers
* format text with `Q`

Also, default UI expects special fonts. This should be documented to newcomers, or just don't use it until the user opts in.

I expect SpaceVim to be friendly to newcomers, i.e. both new Vimers and old Vimers without prior experience with SpaceVim.

BTW, `:h spacevim` doesn't jump to where one expects.

**Comment by wsdjeg** [comment]
Thanks for your issues, `be friendly to newcomers, i.e. both new Vimers and old Vimers without prior experience with SpaceVim` also is one of main goals of SpaceVim.
I update some doc for open cmdwin 

SpaceVim has mapped normal <kbd>q</kbd> as smart buffer close, the normal func of <kbd>q</kbd>
can be get by <kbd>`<leader>` q r</kbd>

##### Native functions

Key   | Mode | Action
----- |:----:| ------------------
`<leader>` + `qr` | Normal | Same as native `q`
`<leader>` + `qr/` | Normal | Same as native `q/`, open cmdwin
`<leader>` + `qr?` | Normal | Same as native `q?`, open cmdwin
`<leader>` + `qr:` | Normal | Same as native `q:`, open cmdwin

**Comment by wsdjeg** [comment]
> open cmdwin in ex-mode with `<C-f>`

I can not find this feature in `vim -u NONE`.



> format text with Q

`Q` is for goto ex-mode, so how to format text by `Q`?

**Comment by lilydjwg** [comment]
Please use `vim -N -u NONE`.

`Q` is mapped by defaults.vim (earlier vimrc_example.vim).

**Comment by wsdjeg** [comment]
I got it , it is just `map Q gq`, I will add this to default layer

**Comment by wsdjeg** [comment]
So where is `<c-f>`

**Comment by lilydjwg** [comment]
It's the `cedit` option.

**Comment by wsdjeg** [comment]
@lilydjwg oh, I have cmap for `<c-f>`, why? I just want to use gnu cmdline edit and move feature. here is some links for it.
http://teohm.com/blog/shortcuts-to-move-faster-in-bash-command-line/
http://web.mit.edu/gnu/doc/html/features_7.html
https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-Point.html

ok, before this issue, I do not use `<c-f>` to open cmdwin, but now , I think open cmdwin in cmd-mode is very useful.

maybe should change `cedit` option and add doc.

**Comment by wsdjeg** [comment]
@lilydjwg I think we should not add `:h spacevim`, you can try to complete this word in cmdline, it is hard, but it is easy to complete `:h SpaceVim`, just type `:h Sp<tab>`, you will see all the tags for SpaceVim, but `:h sp<tab>` show too many other tags, BTW, if you do not want to type `shift + s`, `:h spacevim<tab>` also will show SpaceVim tags.
for example `:h spacevim-f<tab>`, you will see `SpaceVim-faq` and `SpaceVim-functions` in the statusline.

**Comment by lilydjwg** [comment]
On Wed, Feb 08, 2017 at 05:00:31AM -0800, Wang Shidong wrote:
> @lilydjwg I think we should not add `:h spacevim`, you can try to complete this word in cmdline, it is hard, but it is easy to complete `:h SpaceVim`, just type `:h Sp<tab>`, you will see all the tags for SpaceVim, but `:h sp<tab>` show too many other tags, BTW, if you do not want to type `shift + s`, `:h spacevim<tab>` also will show SpaceVim tags.
> for example `:h spacevim-f<tab>`, you will see `SpaceVim-faq` and `SpaceVim-functions` in the statusline.

Adding `:h spacevim` doesn't remove `:h SpaceVim`. `:h spacevim<tab>`
shows lots of variables. And I don't want to complete when the term is
short, so that I don't have to stop to locate and read text.

BTW, maybe you should put the help link on the startify buffer.

-- 
Best regards,
lilydjwg

**Comment by wsdjeg** [comment]
@lilydjwg ok, I have add `spacevim` tag in doc.

**Comment by jfemiani** [comment]
If I use this to record a macro then the final `\qr` is part of the macro. Should I worry about that?

If I type `\qr1ihello^[\qr` (that was an escape key, not ^[) and then `:ec @1` then I get `ihello^[\qr`.  I expect to get `ihello^[`.

**Comment by wsdjeg** [comment]
please us new issue.

**Comment by qiuwei** [comment]
I am a heavy macro user. q getting remapped is really annoying.
