### ISSUE TITLE
SpaceVim launch failure on Ubuntu 14.04 with vim 8.1

### ISSUE THREAD

**Issue by heliopetuous** [wsdjeg/SpaceVim#2177]
## Expected behavior, english is required
After installation, Vim successfully launch

## The reproduce ways from Vim starting (Required!)
On Ubuntu 14.04, build vim 8.x latest code and install, install spacevim using official script or using this offline package(https://github.com/Gabirel/Hack-SpaceVim/releases). Then start vim.

## Debug info
<kbd>SPC h I</kbd> seems not working

## Screenshots

Error detected while processing /home/username/.SpaceVim/config/main.vim:
line   26:
E116: Invalid arguments for function fnamemodify(expand('<sfile>'),
E15: Invalid expression: fnamemodify(expand('<sfile>'),
line   27:
E10: \ should be followed by /, ? or &
line   28:
E10: \ should be followed by /, ? or &
line   34:
E121: Undefined variable: g:_spacevim_root_dir
E116: Invalid arguments for function fnamemodify(g:_spacevim_root_dir, ':p:h:h')
E15: Invalid expression: ',' . fnamemodify(g:_spacevim_root_dir, ':p:h:h')
Error detected while processing /home/username/.SpaceVim/vimrc:
line   11:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
how do you install, and what is git status in `~/.SpaceVim`

**Comment by heliopetuous** [comment]
Sorry for not reply in time, I was on a meeting until now.

For the 1st question, I think I mentioned in the main thread that I'm using the official installing script, and I have also tried the offline install package which is provided by https://github.com/Gabirel/Hack-SpaceVim/releases. Both of them give the same results.

I'm not sure what you mean by git status, so I'm pasting the result of "git status" in .SpaceVim:
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

**Comment by heliopetuous** [comment]
The title may not describe the problem appropriately, so I've  changed it into "SpaceVim launch failure" instead of "Install failure".

**Comment by wsdjeg** [comment]
you can try `vim -u ~/.SpaceVim/vimrc`

**Comment by heliopetuous** [comment]
OK, vim -u ~/.SpaceVim/vimrc does launch successfully.
While using plain "vim" still gives the same launch failure result.

**Comment by heliopetuous** [comment]
May I ask what does "vim -u ~/.SpaceVim/vimrc" do?
And whether this is a problem that needs solution, or not a problem?

**Comment by wsdjeg** [comment]
I think your installation is wrong, you should make sure you have no file `~/.vimrc`, and `~/.vim` is link to `~/.SpaceVim`

**Comment by heliopetuous** [comment]
Thanks for the advice!
I finally found there's a vimrc file in my $VIM folder because I'm using a preinstalled os image.
After I renamed the /usr/share/vim/vimrc file, everything seems to be fine.

**Comment by heliopetuous** [comment]
Oh, except the color :) (For I'm using ssh to connect, the effect is like below)

![spacevim](https://user-images.githubusercontent.com/17633000/45683610-af840500-bb76-11e8-9fb3-b9c39164b3fc.PNG)

=========================Update==================================
I try disable true color and things looks good enough to me now:
![spacevim](https://user-images.githubusercontent.com/17633000/45684241-4a311380-bb78-11e8-8e9f-dc060c3b87df.PNG)

Thanks again.
