### ISSUE TITLE
cscope support

### ISSUE THREAD

**Issue by hongjiujing** [wsdjeg/SpaceVim#2178]
## Expected behavior, english is required
add cscope  database automatically 
SPC m c C work in a symbol
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
SpaceVim layers:                                                                                                          
 13                                                                                                                           
 12 - VersionControl:       not loaded          https://spacevim.org/layers/VersionControl                                    
 11 + autocomplete:             loaded          https://spacevim.org/layers/autocomplete                                      
 10 - chat:                 not loaded          https://spacevim.org/layers/chat                                              
  9 + checkers:                 loaded          https://spacevim.org/layers/checkers                                          
  8 - chinese:              not loaded          https://spacevim.org/layers/chinese                                           
  7 - colorscheme:          not loaded          https://spacevim.org/layers/colorscheme                                       
  6 + core/banner:              loaded          https://spacevim.org/layers/core/banner                                       
  5 + core/statusline:          loaded          https://spacevim.org/layers/core/statusline                                   
  4 + core/tabline:             loaded          https://spacevim.org/layers/core/tabline                                      
  3 + core:                     loaded          https://spacevim.org/layers/core                                              
  2 + cscope:                   loaded          https://spacevim.org/layers/cscope                                            
  1 - ctrlp:                not loaded          https://spacevim.org/layers/ctrlp                                             
15  - debug:                not loaded          https://spacevim.org/layers/debug                                             
  1 + denite:                   loaded          https://spacevim.org/layers/denite                                            
  2 + edit:                     loaded          https://spacevim.org/layers/edit                                              
  3 - exprfold:             not loaded          no exists                                                                     
  4 - floobits:             not loaded          https://spacevim.org/layers/floobits                                         
If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

https://asciinema.org/a/m8T9rl2COUItYg9AFOuyJfLtT

**Comment by hongjiujing** [comment]
vim --version | grep 8.0
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 14 2018 07:55:41)

**Comment by wsdjeg** [comment]
we have cscope layer
