### ISSUE TITLE
Many bugs report

### ISSUE THREAD

**Issue by makerjackie** [wsdjeg/SpaceVim#2187]
1. `z a` to toggle a fold but show `No fold found` in python code
2. I enable python layer, but `spc l i r` will delete all code instead of `remove unused imports with autoflake`
3. I use fuzzy finder unite, but after `spc f f`, I can not use `ctrl + v` to vsplit file. (`ctrl+s` work after I disable it using `stick stty -ixon in a startup script(~/.bashrc).`)
4. I enable shell layer but I can't close it using `spc ,` as [document](https://spacevim.org/layers/shell/) says. Btw, [the document about shell layer](https://spacevim.org/documentation/#managing-projects) is out-of-date ( you can't use `spc p ,` to open a shell ). The only way I can close shell window is `:only`

**Comment by wsdjeg** [comment]
1. I do not think it is a bug, the foldmethod is manual by default, and SpaceVim do not change it, so we can not fold code in python, but I think maybe users can config it in bootstrap function. read `:h fdm` for more info.

2. `SPC l i r` is calling `Neoformat autoflake`, I think maybe it is a bug of neoformat
cc @sbdchd

3. I will check it.

4. the doc is updated in #2181 , `SPC '` is for open and jump to opened shell windows, you can use `Ctrl + d` to close shell in terminal mode, or use `<Esc>` to switch to normal mode, then presss `q` to smart quit.
