### ISSUE TITLE
Script for Uninstallation? 

### ISSUE THREAD

**Issue by oliveratutexas** [wsdjeg/SpaceVim#219]
## Expected behavior, english is recommend
I tried deleting all the files inside .vim .nvim .SpaceVim 
and .vim .config/nvim/* etc. I did that re-installed but I'm still having an odd issue. Is there a certain script I should run for a good clean uninstallation?

## Environment Information
- OS: Gallium OS
- vim version: 7.4
- neovim version: 0.2.0

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
you can find it in `curl -sLf https://spacevim.org/install.sh | bash -s -- -h`, and what make you want to uninstall it?

**Comment by wsdjeg** [comment]
Sorry let talk in the odd issue. reopen that issue
