### ISSUE TITLE
vim shows E484 when startup

### ISSUE THREAD

**Issue by michelfei** [wsdjeg/SpaceVim#2192]
vim启动时出现如下图的错误。
操作系统win10
![capture](https://user-images.githubusercontent.com/16935668/45925241-1a04be80-bf44-11e8-8543-b35cd5df709f.PNG)

点击ok后界面如下图，

![capture2](https://user-images.githubusercontent.com/16935668/45925433-c5fbd900-bf47-11e8-830c-57f52bcf37fc.PNG)

**Comment by wsdjeg** [comment]
It seems a bug of dein, func `dein#install#_rm` is failed to run. cc @Shougo
