### ISSUE TITLE
Errors After Install

### ISSUE THREAD

**Issue by pertrai1** [wsdjeg/SpaceVim#2194]
## Expected behavior, english is required
When I open vim I should not receive errors everytime I start typing

## The reproduce ways from Vim starting (Required!)
* Open vim first time after installing

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
* I can't because anytime I try to type in vim I keep getting these errors:
```
Error detected while processing function <lambda>2[1]..completor#do[9]..completor#utils#get_completer:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <lambda>2[1]..completor#do[9]..completor#utils#get_completer:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <lambda>2[1]..completor#do[9]..completor#utils#get_completer:
line    1:
NameError: name 'completor_api' is not defined
Press ENTER or type command to continue
Error detected while processing function <lambda>2[1]..completor#do[9]..completor#utils#get_completer:
line    2:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <lambda>2[1]..completor#do[9]..completor#utils#get_completer:
line    2:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <lambda>2[1]..completor#do[9]..completor#utils#get_completer:
line    2:
NameError: name 'res' is not defined
Press ENTER or type command to continue
```
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![spacevim-error](https://user-images.githubusercontent.com/442374/45930850-f5ecb180-bf32-11e8-8d9c-1282d719903b.png)

**Comment by yuruiz** [comment]
same here

**Comment by wsdjeg** [comment]
first, make sure your vim support `+python` feature, it seems your vim do not support `+python` and completor.vim reports these errors.
