### ISSUE TITLE
What is the leader?

### ISSUE THREAD

**Issue by mnivoliez** [wsdjeg/SpaceVim#22]
Hello! I found SpaceVim this morning. I'm coming from Spacemacs and before that I was already a vim user. Wich lead me to a question, what is the leader key by default? I tried "space", "," , "\", ";".
Nothing seems to work. I tried to refined the leader key to "space" which work but I fear it could enter conflict with other command.

Best.

**Comment by wuranbo** [comment]
try

> let mapleader="," 

check out this: http://learnvimscriptthehardway.stevelosh.com/chapters/06.html  @mnivoliez

**Comment by wsdjeg** [comment]
@mnivoliez see `:h mapleader` in vim, I do not change the default leader of vim.

**Comment by mnivoliez** [comment]
I think I found the why. I have tried "\\" but I'm currently using a mac. In order to put "\" you have to use ALT+SHIFT+":".

**Comment by wsdjeg** [comment]
the default leader should be `\`. now what do you want to do. I think I can help you.

**Comment by justinmoon** [comment]
Naming this project "spacevim" doesn't make much sense if the leader isn't "space" ...

**Comment by wsdjeg** [comment]
spacevim do not means using  space in vim. It means provide more space for vim, And you can use vim do any thing you like.

Please see :h leader in vim. closing

**Comment by justinmoon** [comment]
Sure, but then it's no longer "like spacemacs, but for vim". It's a vim distribution co-opting the spacemacs name.

**Comment by wsdjeg** [comment]
@superquest what is spacemacs? it is layer based useage of emacs. and now SpaceVim is modular configuration for vim. so what is the differences? you mean I must has same file structure as spacemacs? use `layers` and use `+` before directory for each modular?

I do not think it is good idea, what I like about spacemacs is just the `modular config` or `layers config`, user only need load the layers(modes) he want.

thanks for feedback, let's stop this useless argument. we should spend more time to help user who need vim.

**Comment by dynofu** [comment]
i think it might be better to have a place to document these info in a more organized way

```
* [SPC] 

* <Leader> - \ - :help mapleader 

* <LocalLeader> - \ - :help maplocalleader

* s - window leader :SPDebuginfo!
https://spacevim.org/documentation/#vim-compatible-mode
The s key does replace cursor char, but in SpaceVim it is the Window key bindings specific leader key by default (which can be set on another key binding in dotfile). If you still prefer the origin function of s, you can use an empty string to disable this feature.
```
