### ISSUE TITLE
how  can I add custom snippet

### ISSUE THREAD

**Issue by onerciller** [wsdjeg/SpaceVim#220]
I want to add custom snippet for php or any language, how can I do this ?

**Comment by Shougo** [comment]
`:NeoSnippetEdit`

**Comment by wsdjeg** [comment]
In SpaceVim:

`let g:neosnippet#snippets_directory` is a list.
[SpaceVim's snippets,  SpaceVim.d's global snippets, SpaceVim.d's local snippets].

If using 'NeoSnippetEdit', first dir will be used. It will add files to SpaceVim, it is not good.

It is bug of spacevim, I will fix it, and add documentation.
