### ISSUE TITLE
Add a Docker way to run?

### ISSUE THREAD

**Issue by Kuangcp** [wsdjeg/SpaceVim#2200]
I hope to add Docker mode to run, which can make the original vim and spaceVim work together,
 giving the novice a cleaner learning environment, easy to uninstall and update.

If I agree with the proposal, I can write dockerfile. thanks

**Comment by wsdjeg** [comment]
you can check https://github.com/SpaceVim/SpaceVim/tree/master/docker I do not push it to dockhub.

**Comment by Kuangcp** [comment]
OK

**Comment by Kuangcp** [comment]
this script https://spacevim.org/install.sh  can use `git clone --depth 1 URL` , 
to  reduce the size of the download repository

**Comment by wsdjeg** [comment]
@Kuangcp I just add a linked hub repo, It will build and publish automatically:

https://hub.docker.com/r/spacevim/spacevim/
