### ISSUE TITLE
Unit/Integration tests

### ISSUE THREAD

**Issue by Melkor333** [wsdjeg/SpaceVim#2204]
When looking at spacemacs, we see that it has a HUGE amount of open issues (and is also very badly maintained at moment).
Right now SpaceVim has only a few. But thinking about how more and more layers are being added, I'm a bit scared that at some point the amount of bugs will also become more and more up to an unmaintanable state.

Maybe it would be clever to create a testing framework which is able to check if all keybindings produce the expected output when tested with all compatible layers. This would ensure that layers stay compatible, help in finding bugs and hopefully keep the project healthy..

I am not very experienced so I can't say how much effort it would take to create and implement a testing framework, so maybe it would need way too much work. But since most times the checks are very similar ("just" comparing the before & after of keybindings) I assume implementing it shouldn't take too much time if the framework itself is done properly...

What do you think?

**Comment by Melkor333** [comment]
Of course some testing frameworks already exist, like  [this one](https://github.com/inkarkat/runVimTests) which also lists other frameworks. So maybe we can use one of those...

**Comment by wsdjeg** [comment]
@Melkor333 SpaceVim use vader to test , you can check the `test/` dir.
