### ISSUE TITLE
Replace Vimfiler with Defx for default file tree explorer

### ISSUE THREAD

**Issue by jssee** [wsdjeg/SpaceVim#2205]
Vimfiler has been deprecated in favor of Defx, which works with denite (vimfiler did not). Shougo has said he has stopped updating vim filer.

**Comment by Shougo** [comment]
defx.nvim is better in the feature.
But current defx.nvim is not stable.

So the replace should be not now.

**Comment by jssee** [comment]
Makes sense. Ill close this for now.
