### ISSUE TITLE
Converting init.vim to init.toml

### ISSUE THREAD

**Issue by tokelove** [wsdjeg/SpaceVim#2206]
I'm in the process of converting my spacevim init.vim to init.toml and I had the following to have vimwiki's that are opened with \-w-1 or \-w-2 etc...

```
let g:vimwiki_list = [
                        \{'path': '~/vimwiki/one.wiki'},
                        \{'path': '~/vimwiki/two.wiki'},
                        \{'path': '~/vimwiki/three.wiki'},
                        \{'path': '~/vimwiki/four.wiki'},
                \]
```

Does anybody know what the formatting for this would be in toml?

**Comment by wsdjeg** [comment]
you need to use bootstrap function, please check:

https://spacevim.org/documentation/#bootstrap-functions

**Comment by tokelove** [comment]
Apologies if I've missed something. I have the following under [options] in init.toml:

`bootstrap_before = "myspacevim#before"`

In 'autoload/myspacevim.vim' I have the following:

` func! myspacevim#before() abort
	 let g:vimwiki_list = [
                        \{'path': '~/vimwiki/one.wiki'},
                        \{'path': '~/vimwiki/two.wiki'},
                        \{'path': '~/vimwiki/three.wiki'},
                        \{'path': '~/vimwiki/four.wiki'},
                \]
 endif
`

**Comment by wsdjeg** [comment]
Hi, you can press `SPC h L` to see the startup log, you should see:

```
[ SpaceVim ] [09:34:35] [ Info ] myspacevim#before called
```

if you find this, and your config is not works, I think it is bug of vimwiki, the plugin ovrride your config, you can move this to `bootstrap_after` which will be called after `VimEnter` event.
