### ISSUE TITLE
保存go项目的文件时, 报错. 丢失了gopath.

### ISSUE THREAD

**Issue by lcg635** [wsdjeg/SpaceVim#221]
![111](https://cloud.githubusercontent.com/assets/1639178/22720772/ce01752a-ede7-11e6-958d-491807c60673.png)
如图, :GoPath 命令能得到正确的gopath, 但是保存时没有用上

**Comment by lcg635** [comment]
暂时在配置文件中添加
au FileType go let $GOPATH = go#path#Detect()
来解决了

**Comment by wsdjeg** [comment]
我觉得是这是设置问题，正常情况下`GOPATH`这个值是需要设置在bashrc里面的。

**Comment by lcg635** [comment]
因为每个项目的GOPATH都会不一样, 我用了gb来管理依赖

**Comment by wsdjeg** [comment]
谢谢,那么SpaceVim是否需要修改呢，针对这个问题。
