### ISSUE TITLE
Feature Request in Documentation for dependency

### ISSUE THREAD

**Issue by kayfay** [wsdjeg/SpaceVim#2211]
## Feature Request

Documentation, Feature Request

Can we do something for dependency recommendations on [Getting Started](https://spacevim.org/quick-start-guide/)?

For example, using `pip3 install neovim` for deoplete instead of neocomplete in autocompletion.

**Comment by kayfay** [comment]
Take a look at commit for docs/quick-start-guide.md Commits on Sep 27, 2018 for an example.
https://github.com/SpaceVim/SpaceVim/commit/f88ebe9948b3111482d812ae4943f6195b9f64ad

**Comment by wsdjeg** [comment]
thanks, but as I know SpaceVim should works well with out `+python` feature, and the complete methond to switch to neocomplcache.

**Comment by wsdjeg** [comment]
At a minimum, SpaceVim requires `git` and `curl` to be installed. Both tools
are needed for downloading plugins and fonts.

If you are using Vim/Neovim in terminal, you also need to set the font of your terminal.
