### ISSUE TITLE
encode problem(icon missing)

### ISSUE THREAD

**Issue by orlowang** [wsdjeg/SpaceVim#2214]
## Expected behavior, english is required
normal
## The reproduce ways from Vim starting (Required!)
on mojave os, first install
## Debug info
mojave(10.14)
vim(8.0)

## Screenshots

<img width="1427" alt="screen shot 2018-09-28 at 10 55 25 am" src="https://user-images.githubusercontent.com/5770548/46186771-e09ccc00-c312-11e8-964c-6fc78ab214d3.png">

**Comment by wsdjeg** [comment]
you need to install nerd-fonts.
