### ISSUE TITLE
theme and syntax highlighting are broken when upgrade vim to 8.1

### ISSUE THREAD

**Issue by orlowang** [wsdjeg/SpaceVim#2215]
+ **syntax highlighting is not work**
+ **all themes seems broken** 

## The reproduce ways from Vim starting (Required!)
upgrade vim to 8.1
### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(vi)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:44:26] [ Info ] SpaceVim startup status is: [1, '/Users/owcc']
[ SpaceVim ] [15:44:26] [ Info ] find config file: /Users/owcc/.SpaceVim.d/init.toml
[ SpaceVim ] [15:44:26] [ Info ] loadding cached config: /Users/owcc/.cache/SpaceVim/conf/_Users_owcc__SpaceVim_d_init_toml.json
[ SpaceVim ] [15:44:27] [ Info ] try to open SpaceVim welcome page
```

## Screenshots

<img width="1025" alt="4e6234d6-e45c-4e38-bfc1-e624d2173522" src="https://user-images.githubusercontent.com/5770548/46195270-70a03d00-c336-11e8-98ce-afa4e597b34c.png">

**Comment by wsdjeg** [comment]
which version do you compare with? it works well in vim7.4?

**Comment by wsdjeg** [comment]
https://spacevim.org/faq/#why-spacevim-can-not-display-default-colorscheme

**Comment by orlowang** [comment]
it works perfect in vim8.0, but not support shell because term feature is lost, so I upgrade vim to 8.1 by brew(mac os) then hit this issue

**Comment by wsdjeg** [comment]
try to use item2, if you are using mac os.

**Comment by wsdjeg** [comment]
you can disable true colors in SpaceVim. item do not support true colors.
