### ISSUE TITLE
error detected when open a java file with spacevim

### ISSUE THREAD

**Issue by rivalak** [wsdjeg/SpaceVim#2217]
## Screenshots

![image](https://user-images.githubusercontent.com/42036026/46240585-6b95c900-c3dc-11e8-91df-150e5f6bfff7.png)

**Comment by wsdjeg** [comment]
there is no debug info I can not fix it, you should at least post your vim version and os info and jdk version.

**Comment by rivalak** [comment]
install java-jre can solve this problem.
