### ISSUE TITLE
Combining existing gVim with SpaceVim

### ISSUE THREAD

**Issue by carlca** [wsdjeg/SpaceVim#222]
## Expected behavior, english is recommend
I expected to see gVim magically transformed into SpaceVim just like in the pictures at spacevim.org!

## Environment Information
- OS: Windows 10 Pro 64 bit Insider Preview 15014
- vim version: Version 8.0.295 - TuxProject.de version
Used libraries: Perl 5.24.1, Python 2.7.12, Python 3.6.0, Racket 6.7, Ruby 2.4.0, Lua 5.3.3, Tcl 8.6.4, libXpm. 

- neovim version: N/A

## The reproduce ways from Vim starting (Required!)
I carried out the ```git clone https://github.com/SpaceVim/SpaceVim.git vimfiles``` command in my home directory after backing up my existing ```vimfiles``` folder to ```vimfilesOLD```. I then merged the contents of ```vimfilesOLD``` into the newly created ```vimfiles``` using a folder comparison tool (Beyond Compare). When I started gVim (using the same 8.0.295 executable as before) nothing had changed, that I could see.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
```:message``` gives ```-- No lines in buffer --```

```:echo SpaceVim#logger#viewLog()``` gives...

```
### SpaceVim options :
'''viml
'''

### SpaceVim Health checking ...

SpaceVim clipboard support check report:
Checking +clipboard:
        SUCCEED!
SpaceVim lua support check report:
Checking +lua
        Failed : to support +lua you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
        SUCCEED!
Checking +python:
        SUCCEED!

### SpaceVim runtime log :

'''log
[ SpaceVim ] : logger file C:\Users\Carl\.SpaceVim\.SpaceVim.log does not exists, only log for current process will be shown! 
'''

```
```logger#viewLog()``` gives...
```E492: Not an editor command: logger#viewLog()```

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

Contents of ~/_vimrc...

```
call plug#begin()
Plug 'fatih/vim-go'
Plug 'shougo/neocomplete.vim'
Plug 'ervandew/supertab'
Plug 'tomasr/molokai'
Plug 'junegunn/goyo.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'mru.vim'
Plug 'flazz/vim-colorschemes'
Plug 'nsf/gocode'
Plug 'troydm/easytree.vim'
Plug 'lifepillar/vim-outlaw'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'mattn/webapi-vim'
Plug 'mattn/emmet-vim'
Plug 'davidhalter/jedi-vim'
Plug 'jodosha/vim-godebug'
Plug 'rjohnsondev/vim-compiler-go'
call plug#end()

set foldcolumn=5
autocmd Colorscheme * highlight FoldColumn guifg=bg guibg=bg
colorscheme onedark
let g:molokai_original = 1
set guifont=Raize:h10
source $VIMRUNTIME/mswin.vim
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
set nonu
set guioptions-=L  "remove left-hand scroll bar
let g:goyo_width = 90
let g:goyo_height = 90
let g:goyo_margin_top = 10
let g:goyo_margin_bottom = 10

source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction
```

I don't like the look of the message about lua. It took me enough time to find the TuxProjects.de build that was done with Python + Python3. Any advice, apart from switch to Linux!!

Interesting that when I do ```:version``` I get the following...
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  2 2017 20:16:30)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-295
Compiled by hp@HP-PC
Huge version with GUI.  Features included (+) or not (-):
+acl                +eval               +mouse              +syntax
+arabic             +ex_extra           +mouseshape         +tag_binary
+autocmd            +extra_search       +multi_byte_ime/dyn +tag_old_static
+balloon_eval       +farsi              +multi_lang         -tag_any_white
+browse             +file_in_path       +mzscheme/dyn       +tcl/dyn
++builtin_terms     +find_in_path       +netbeans_intg      -termguicolors
+byte_offset        +float              +num64              -tgetent
+channel            +folding            +ole                -termresponse
+cindent            -footer             +packages           +textobjects
+clientserver       +gettext/dyn        +path_extra         +timers
+clipboard          -hangul_input       +perl/dyn           +title
+cmdline_compl      +iconv/dyn          +persistent_undo    +toolbar
+cmdline_hist       +insert_expand      -postscript         +user_commands
+cmdline_info       +job                +printer            +vertsplit
+comments           +jumplist           +profile            +virtualedit
+conceal            +keymap             +python/dyn         +visual
+cryptv             +lambda             +python3/dyn        +visualextra
+cscope             +langmap            +quickfix           +viminfo
+cursorbind         +libcall            +reltime            +vreplace
+cursorshape        +linebreak          +rightleft          +wildignore
+dialog_con_gui     +lispindent         +ruby/dyn           +wildmenu
+diff               +listcmds           +scrollbind         +windows
+digraphs           +localmap           +signs              +writebackup
+directx            +lua/dyn            +smartindent        -xfontset
-dnd                +menu               +startuptime        -xim
-ebcdic             +mksession          +statusline         +xpm_w32
+emacs_tags         +modify_fname       -sun_workshop       -xterm_save
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE 
-DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 
-D_WIN32_WINNT=0x0501  /Fo.\ObjGXOULYHTRZAMD64/ /MP -DHAVE_STDINT_H /Ox /GL 
-DNDEBUG  /MD -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DGLOBAL_IME 
-DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV 
-DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" 
-DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\
" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" 
-DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python36.dll\" 
-DFEAT_MZSCHEME -I "C:\Users\hp\Desktop\racket-x64\include" -DDYNAMIC_MZSCHEME 
-DDYNAMIC_MZSCH_DLL=\"libracketxxxxxxx.dll\" -DDYNAMIC_MZGC_DLL=\"libmzgcxxxxxxx.d
ll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL 
-DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VE
R=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE 
/Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib 
advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib
```

which as you can see includes ```+lua/dyn```. Can your lua detection code be 100% relied upon, I am wondering?

Sorry for length of this post, I just wanted to supply as much useful information as possible,

Thanks,
Carl

**Comment by wsdjeg** [comment]
nice post， I will look into it tonight. Now it is 9:00am.

**Comment by carlca** [comment]
No rush. It's just gone 1:00am here in England. Time for me to stop messing around on the internet and get some sleep. Have a good day!!

**Comment by wsdjeg** [comment]
@carlca I just update the readme, you need remove `~/_vimrc`, and SpaceVim's config file is `~/.SpaceVim.d/init.vim`.

**Comment by wsdjeg** [comment]
vim includes +lua/dyn,  so if you want lua support , you should have lua.exe in your PATH.

**Comment by carlca** [comment]
OK. I've removed _vimrc and restarted gVim and it certainly looks different. However, I cannot find ```.SpaceVim.d/init.vim``` anywhere; I'm just doing a computer wide search for ```init.vim```. Back in a second...

**Comment by carlca** [comment]
All the ```init.vim``` s that I possess!

<img width="503" alt="init vim" src="https://cloud.githubusercontent.com/assets/260612/22833903/6a208ddc-efab-11e6-90bb-46b58e986318.png">

**Comment by wsdjeg** [comment]
You need create ~/.SpaceVim.d/init.vim

**Comment by carlca** [comment]
It all works. Wow! What is the best way of learning all the new functionality? I know there's the vim tutorial for the basic vim stuff, but it looks like there's a lot to learn!

**Comment by carlca** [comment]
I'm gradually getting hang of SpaceVim. However, I cannot understand the way line numbers are implemented. Have a look at this screen grab...

<img width="293" alt="go" src="https://cloud.githubusercontent.com/assets/260612/22857265/e0d4d340-f099-11e6-9e4c-9e57ea879a8c.png">

The line numbers appear to radiate out from the current line both upwards and downwards. Of course as the current line number changes, so the list of numbers changes giving a rather off putting ripple effect.

I've tried to disable the line numbers with ```set nonu``` and ```setlocal nonumber``` but they still show up. How can I get rid of them?

The more I think about them the more I'm convinced that they are not meant as line numbers. I cannot imagine for what purpose they are intended!

**Comment by wsdjeg** [comment]
Oh, sorry, SpaceVim has 
```viml
    set relativenumber
    set number
```
so if you do not like it , you can add 
```viml
    set norelativenumber
    set nonumber
```
to your `~/.SpaceVim.d/init.vim`, BTW, you can type `\nu` in normal mode to toggle line number.

**Comment by carlca** [comment]
Thanks a lot for that. Is there a single list anywhere which shows all of the SpaceVim commands? That would save you having to bother with me asking questions all the time!!

**Comment by wsdjeg** [comment]
I think you can have a look at `:h SpaceVim` and the readme, if you are family with vimscript, I think you can check out the code of SpaceVim. Maybe you can also find some bug and send me PR.

welcome for any question about spacevim.

**Comment by carlca** [comment]
I have just stupidly deleted my ~/vimfiles/bundle folder. Is there any way of rebuilding it automatically?

**Comment by carlca** [comment]
No worries it was only causing a problem because I was experimenting with enabling YouCompleteMe which I have since disabled.
