### ISSUE TITLE
Add srcery colorscheme

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2222]
https://github.com/srcery-colors/srcery-vim

This colorscheme looks nice, and I want to include it into colorscheme layer, and add statusline support for it.

**Comment by tranhoangcore** [comment]
@wsdjeg Screry-Vim updating failed.

**Comment by joelazar** [comment]
> @wsdjeg Screry-Vim updating failed.

+1

**Comment by lebensterben** [comment]
@tranhoangcore @joelazar 
Same here. You can disable it by adding `disabled_plugins = ["srcery-vim"]` under `[options]` section.
