### ISSUE TITLE
Documentation for the custom color palette for the statusline

### ISSUE THREAD

**Issue by thedelchop** [wsdjeg/SpaceVim#2227]
Is there any documentation about how SpaceVim uses `g:spacevim_custom_color_palette` to decorate the statusline/tabline?  I'd like to adapt the palette for the [Dracula Theme](https://draculatheme.com), but I can't decipher what that array of arrays is used for and what they represent.

I'd be happy to make a PR adding to the documentation if I could get some guidance on how they work.

Thanks

**Comment by wsdjeg** [comment]
in SpaceVim documentation, there is a statusline section, in this section, you can see the doc for color palette.

https://spacevim.org/documentation/#statusline

**Comment by thedelchop** [comment]
Thank you.
