### ISSUE TITLE
Add support of swig

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#223]
## Expected behavior
please consider adding support of swig in spacevim, including syntax highlight and auto-completion.

**Comment by wsdjeg** [comment]
Will look into it, thanks.

**Comment by wsdjeg** [comment]
Only found https://github.com/SpaceVim/vim-swig

**Comment by wsdjeg** [comment]
the last update is four years ago, I want to fork it and make some changes.

**Comment by Gabirel** [comment]
oooh, four years ago. that's a long time

**Comment by wsdjeg** [comment]
What I can do now is only add `SpaceVim/vim-swig`, but PR welcome.
