### ISSUE TITLE
spacevim cant auto install

### ISSUE THREAD

**Issue by awkj** [wsdjeg/SpaceVim#2233]
## Expected behavior, english is required
When I use curl -sLf https://spacevim.org/cn/install.sh | bash , Spacevim should auto install and add .Spacevim.d and other folder (only have .Spacevim)
## The reproduce ways from Vim starting (Required!)
I use docker is https://github.com/phusion/baseimage-docker
and creaet a container,use default vim version
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
sorry , I think the config can't apply to vim, so I can't give the info
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

and:
Is this is a bug or ? Can have user manual to install ?

**Comment by awkj** [comment]
I fix the problem by update vim to 8.1 ,but I think it a bug.

**Comment by wsdjeg** [comment]
@awkj SpaceVim install script will not create SpaceVim.d fold, but when start gvim or vim or neovim, the vim will check the custom config, if it does not exist, vim will create it from template.

**Comment by wsdjeg** [comment]
Ok, I will add some log about it.
