### ISSUE TITLE
Can not use arrow keys in vim's terminal

### ISSUE THREAD

**Issue by ihexon** [wsdjeg/SpaceVim#2234]
I notice the key binding in `"autoload/SpaceVim/layers/shell.vim"` 
line 42
```
 if has('nvim') || exists(':tnoremap') == 2                                                                                                                                               
    ┊ exe 'tnoremap <silent><C-Right> <C-\><C-n>:<C-u>wincmd l<CR>'                                                                                                                          
    ┊ exe 'tnoremap <silent><C-Left>  <C-\><C-n>:<C-u>wincmd h<CR>'                                                                                                                          
    ┊ exe 'tnoremap <silent><C-Up>    <C-\><C-n>:<C-u>wincmd k<CR>'                                                                                                                          
    ┊ exe 'tnoremap <silent><C-Down>  <C-\><C-n>:<C-u>wincmd j<CR>'                                                                                                                          
    ┊ exe 'tnoremap <silent><M-Left>  <C-\><C-n>:<C-u>bprev<CR>'                                                                                                                             
    ┊ exe 'tnoremap <silent><M-Right>  <C-\><C-n>:<C-u>bnext<CR>'                                                                                                                            
    ┊ exe 'tnoremap <silent><esc>     <C-\><C-n>'          
```
THIS result I can not use arrow keys in vim's terminal `:terminal`

**Comment by wsdjeg** [comment]
It is `<C-Left>`, so I do not know  why `<Left>` does not work

**Comment by ihexon** [comment]
Mybe should comment out this pices of code so let everything work right

**Comment by wsdjeg** [comment]
@ihexon why this mapping break the arrow key in terminal? as I know in shell layer we only map `Ctrl + arrow` key.

**Comment by eh-am** [comment]
got same issue, don't understand exactly what's happening, but when hitting the arrow up key it shows "E21: Cannot make changes, 'modifiable' is off", so it seems it's treating the shell as a text file (if I enter normal mode while in the shell I can move with hjkl keys)

**Comment by wsdjeg** [comment]
What is your os?

________________________________
wsdjeg@outlook.com

**Comment by eh-am** [comment]
`Linux localhost.localdomain 4.19.9-300.fc29.x86_64 #1 SMP Thu Dec 13 17:25:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

`Fedora release 29 (Twenty Nine)`

Using fish shell:
`fish, version 2.7.1`

**Comment by ihexon** [comment]
I guess most of people have this issue,Same issue happend on Debian.

**Comment by wsdjeg** [comment]
OK I will check it. This issue only happened in vim? or both neovim and vim?


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Can not use arrow keys in vim's terminal (#2234)
发件人：做梦专业户
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Comment


I guess most of people have this issue,Same issue happend on Debian.

―

**Comment by eduardohenriquearnold** [comment]
I am facing the same issue with Ubuntu 17.10. Any suggestions?

**Comment by ihexon** [comment]
> I am facing the same issue with Ubuntu 17.10. Any suggestions?

just comment out 
```
if has('nvim') || exists(':tnoremap') == 2
 exe 'tnoremap <silent><C-Right> <C-\><C-n>:<C-u>wincmd l<CR>'
 exe 'tnoremap <silent><C-Left> <C-\><C-n>:<C-u>wincmd h<CR>' 
exe 'tnoremap <silent><C-Up> <C-\><C-n>:<C-u>wincmd k<CR>'
 exe 'tnoremap <silent><C-Down> <C-\><C-n>:<C-u>wincmd j<CR>'
 exe 'tnoremap <silent><M-Left> <C-\><C-n>:<C-u>bprev<CR>'
 exe 'tnoremap <silent><M-Right> <C-\><C-n>:<C-u>bnext<CR>' 
exe 'tnoremap <silent><esc> <C-\><C-n>' 
```

**Comment by eduardohenriquearnold** [comment]
> > I am facing the same issue with Ubuntu 17.10. Any suggestions?
> 
> just comment out
> 
> ```
> if has('nvim') || exists(':tnoremap') == 2
>  exe 'tnoremap <silent><C-Right> <C-\><C-n>:<C-u>wincmd l<CR>'
>  exe 'tnoremap <silent><C-Left> <C-\><C-n>:<C-u>wincmd h<CR>' 
> exe 'tnoremap <silent><C-Up> <C-\><C-n>:<C-u>wincmd k<CR>'
>  exe 'tnoremap <silent><C-Down> <C-\><C-n>:<C-u>wincmd j<CR>'
>  exe 'tnoremap <silent><M-Left> <C-\><C-n>:<C-u>bprev<CR>'
>  exe 'tnoremap <silent><M-Right> <C-\><C-n>:<C-u>bnext<CR>' 
> exe 'tnoremap <silent><esc> <C-\><C-n>' 
> ```

If I do this I can use the keys, but cannot get to normal mode in the terminal. Meaning that I cannot get back to vim until I close the terminal. I have tried commenting all the lines but the `<silent><esc>` since I thought it was the key to get back to normal mode. But then the keys stop working again.

Can't you reproduce this issue? I am using vim on Ubuntu 17.10:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

**Comment by eduardohenriquearnold** [comment]
Decided to use neovim, whatever the problem was, it seemed to be related to vim.

**Comment by ihexon** [comment]
> > > I am facing the same issue with Ubuntu 17.10. Any suggestions?
> > 
> > 
> > just comment out
> > ```
> > if has('nvim') || exists(':tnoremap') == 2
> >  exe 'tnoremap <silent><C-Right> <C-\><C-n>:<C-u>wincmd l<CR>'
> >  exe 'tnoremap <silent><C-Left> <C-\><C-n>:<C-u>wincmd h<CR>' 
> > exe 'tnoremap <silent><C-Up> <C-\><C-n>:<C-u>wincmd k<CR>'
> >  exe 'tnoremap <silent><C-Down> <C-\><C-n>:<C-u>wincmd j<CR>'
> >  exe 'tnoremap <silent><M-Left> <C-\><C-n>:<C-u>bprev<CR>'
> >  exe 'tnoremap <silent><M-Right> <C-\><C-n>:<C-u>bnext<CR>' 
> > exe 'tnoremap <silent><esc> <C-\><C-n>' 
> > ```
> 
> If I do this I can use the keys, but cannot get to normal mode in the terminal. Meaning that I cannot get back to vim until I close the terminal. I have tried commenting all the lines but the `<silent><esc>` since I thought it was the key to get back to normal mode. But then the keys stop working again.
> 
> Can't you reproduce this issue? I am using vim on Ubuntu 17.10:
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
> Included patches: 1-1453

GO NORMAL MOD，PLEASE `ctrl+w+N(not n)`

**Comment by LuisJoseSanchez** [comment]
> got same issue, don't understand exactly what's happening, but when hitting the arrow up key it shows "E21: Cannot make changes, 'modifiable' is off", so it seems it's treating the shell as a text file (if I enter normal mode while in the shell I can move with hjkl keys)

I have the same problem.

**Comment by wsdjeg** [comment]
please use new issue

**Comment by LuisJoseSanchez** [comment]
Hi Wang. I deinstalled vim and installed neovim; ¡problem solved!

**Comment by wsdjeg** [comment]
OK

**Comment by cesrjimenez** [comment]
Is there a solution to this problem for those who want to keep vim and not neovim?

**Comment by AminFadaee** [comment]
If you only comment this line:
```exe 'tnoremap <silent><esc> <C-\><C-n>' ```
in the `autoload/SpaceVim/layers/shell.vim` file, the arrow key would work just fine, of course for switching to normal mode, you would have to use `<C-\><C-n>` instead of `esc`.
