### ISSUE TITLE
安装的时候报错 fatal:could not create leading directories

### ISSUE THREAD

**Issue by edisonlove** [wsdjeg/SpaceVim#224]
## Expected behavior, english is recommend
install successful

## Environment Information
- OS:win7
- vim version:
- neovim version:latest

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
No useful info, I can not debug for this issue, clossing.
