### ISSUE TITLE
FlyGrep "Replace" mode

### ISSUE THREAD

**Issue by thedelchop** [wsdjeg/SpaceVim#2251]
After reading most of the source for FlyGrep, I discovered that it has, what it calls "Replace" mode.  This awesome feature seems like its meant to allow you to replace all occurrences of your search pattern with a new word, but I'm not totally sure how or if its meant to work inside of SpaceVim.  So I guess I'm wondering, does it work?  If so, how are you meant to use it after you enter "Replace" mode (<Ctrl - r>), it feels like its an iedit instance since `S` starts up a replacement for all instance of the word, but I am unable to determine how to apply those changes or leave "Replace" mode.

**Comment by wsdjeg** [comment]
@thedelchop hello, the replace mode is just an idea in flygrep, as I know, it does not works well now, but I will improve it in next release. I think it is awesome feature. but before implement this feature, some discussion is need. 

1. as we knwo flygrep is to async run command, so when you press `Ctrl-r` maybe the command has not be finished, I think we need to wait for the command run to end.

2. the flygrep windows show both file path and line content. when run replace mode, the file path should be avoid.

3. provide key binding for apply changings and cancel.

**Comment by thedelchop** [comment]
yeah that makes a lot of sense, I can try to help @wsdjeg maybe I'll leave this open and ask some questions in here if I have any thanks.

**Comment by wsdjeg** [comment]
we just change the `ctrl+r` function, now this key binding is for read content from register. the replace mode is `Alt+r`, or maybe changed in the feature.

**Comment by wsdjeg** [comment]
![IMG_20190926_073622_798](https://user-images.githubusercontent.com/13142418/65647172-6dff2300-e030-11e9-882c-e5bbc4dd36b4.jpg)
