### ISSUE TITLE
How to use SpaceVim in Oracle afiedt?

### ISSUE THREAD

**Issue by pain3992** [wsdjeg/SpaceVim#2253]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

i'm korean, so english is not good

i use oracle vi(afiedt.buf)

(oracle) DEFINE _EDITOR = vi

but this is not SpaceVim

help me!

**Comment by wsdjeg** [comment]
sorry, SpaceVim only support vim and neovim.
