### ISSUE TITLE
Language Server Protcol layer has problem by julia's version.

### ISSUE THREAD

**Issue by p1scescom** [wsdjeg/SpaceVim#2257]
Thank you for your working.
When I use lsp layer for julia, I found a problem by julia's version.
Now its config s:lsp_servers['julia'] is

https://github.com/SpaceVim/SpaceVim/blob/cc6d32effeec6597e94ec145388761ad0b3e226c/autoload/SpaceVim/layers/lsp.vim#L97

But, Julia v0.7 or later doesn't have STDIN and STDOUT (and STDERR). 
they are renamed lowcase: stdin and stdout (and stderr).
So I think that its config is necessary to switch in case of julia's version.

**Comment by wsdjeg** [comment]
Ok, I will add an layer option for setting julia version.

**Comment by p1scescom** [comment]
thank you for reply quickly.

**Comment by wsdjeg** [comment]
@p1scescom in current version, you can set julia lsp command when using lsp layer. please check the layer doc.
