### ISSUE TITLE
SpaceVim and Neovim Hangs

### ISSUE THREAD

**Issue by tfer** [wsdjeg/SpaceVim#2259]
## Expected behavior, english is required
nvim-qt waits forever nvim.exe to return, says: Retry
## The reproduce ways from Vim starting (Required!)
Win 10, Neovim 3.1 64 bit installed, SpaceVim installed.  Start Neovim from sart Menu
## Debug info
 Running nvim.exe from Powershell give this error:

PS C:\Users\tfeth> & nvim

Error detected while processing function <SNR>151_LoadRemotePlugins[1]..<SNR>151_GetManifest[1]..<SNR>151_GetManifestPath:

line 16:

E739: Cannot create directory C:\Users\tfeth\AppData\Local\/nvim: file already exists

Press ENTER or type command to continue

then you have to control-C to regain the console.

Note that you can start a terminal version of Neovim with:

& nvim --noplugin

where the ampersand means "call" in powershell

Could someone help to get around this?, I have not even been able to track down what file is generating this error.

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
N/A
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by samr** [comment]
I am having the same issue. For me, that function is in rplugin.vim , which is under $NEOVIM_INSTALL_DIR/share/nvim/runtime/plugin.

If you look at the code for that, it is failing because it expects nvim to be a diretory, but it's a symlink.

For me I just sidestepped the whole issues by adding the following to my bootstrap function ... a la https://spacevim.org/documentation/#bootstrap-functions

func! myspacevim#before() abort
    let g:loaded_remote_plugins = 'disable neovim remote plugins'
    " ... the rest ...
endf

Alternatively, if you need remote plugins, you can simply comment out the is_directory() check in the rplugin.vim.

**Comment by tfer** [comment]
Thanks for the reply samr.  It took me a long time to track down where rplugin.vim is on my system, found it at "C:\Users\tfeth\scoop\apps\neovim\current\Neovim\share\nvim\runtime\plugin\rplugin.vim", it ended up there I suppose because I installed Neovim via scoop.  

In the path above, I believe "current" is the symlink, so the code is failing because of that I guess.  I'm not using remote plugins, (yet), so I guess I'll try "commenting out".

code line 19-26:
`
let dest = fnamemodify(expand(dest), ':p')
  if !empty(dest)
    let dest .= ('/' ==# dest[-1:] ? '' : '/') . 'nvim'
    if !isdirectory(dest)
      call mkdir(dest, 'p', 0700)
    endif
    let manifest_base = dest
  endif
`
to:
`
let dest = fnamemodify(expand(dest), ':p')
  if !empty(dest)
    let dest .= ('/' ==# dest[-1:] ? '' : '/') . 'nvim'
    "if !isdirectory(dest)
     " call mkdir(dest, 'p', 0700)
    "endif
    let manifest_base = dest
  endif
`
I'll try that and see if it works.

Tom

**Comment by tfer** [comment]
Okay, that worked, nvim-qt.exe starts and connects to a nvim.exe that doesn't get stalled by SpaceVim.

I'll leave this open as a general solution is needed and put into SpaceVim

Tom

**Comment by wsdjeg** [comment]
hello, really sorry for late reply, I am also using Windows now. but it is Win 7.can you have a try with nvim -u SpaceVim/init.vim ?

the spacevim install cmd only create link in ~/AppData/local/nvim

**Comment by wsdjeg** [comment]
`resolve()` function has been fixed in vim see:

- https://github.com/vim/vim/issues/4211
- https://github.com/vim/vim/pull/3896
- https://github.com/vim/vim/issues/147
