### ISSUE TITLE
Question: How to show vimfiler on the left?

### ISSUE THREAD

**Issue by mikepc** [wsdjeg/SpaceVim#2263]
I'm so used to always having my project files on the left, it's really tough to switch to looking at my project files on the right.

Is there a way to configure vimfiler to load on the left? I don't care if it's on <SPC> 2 or <SPC> 1 but I just prefer to have my files on the left.

I have googled it a bit, but gave up after an hour or so.

**Comment by PeterDing** [comment]
Adding `sidebar_direction = 'left'` to your `~/.SpaceVim.d/init.toml`.

```toml
[options]
    sidebar_direction = 'left'
```

**Comment by mikepc** [comment]
sadly I can't get this to work using this syntax. No errors are presented but vimfiler is still on the right?

**Comment by mikepc** [comment]
To clarify I created a new file in the ~/.SpaceVim.d/ directory called init.toml and pasted in your syntax verbatim.

I also tried vimfiler_direction = 'left'

And I tried changing 'left' to "left" 

It might also be worth mentioning that this isn't mentioned in:
https://github.com/SpaceVim/SpaceVim/blob/master/doc/SpaceVim.txt

If I can get it to work I'll add it to the docs

**Comment by PeterDing** [comment]
I didn't express explicitly, sorry.

### For setting `nerdtree`

Adding following to `~/.SpaceVim.d/init.toml` is working.

```toml
[options]
    sidebar_direction = 'left'
```

You can see the code:

https://github.com/SpaceVim/SpaceVim/blob/a651a017f635347e90eb37a98503e948f87206f7/autoload/SpaceVim.vim#L485

and

https://github.com/SpaceVim/SpaceVim/blob/7c9a90498b93c1b5875ff39383c49874a29aa64e/config/plugins/nerdtree.vim#L2

### For setting `vimfiler` to left sider of window

You need to add a global variable to your function `myspacevim#before()` at `myspacevim.vim`. ([doc](https://spacevim.org/documentation/#bootstrap-functions))

```vim
let g:vimfiler_direction = 'topleft'
```

You can see the code:

https://github.com/SpaceVim/SpaceVim/blob/ee02a29869a7e077723739b843403e9d3c38a811/config/plugins/vimfiler.vim#L51

and

https://github.com/Shougo/vimfiler.vim/blob/e15fdc4b52a3d2e082283362ba041126121739f8/doc/vimfiler.txt#L945

Or, you can use command `VimFiler -direction=topleft` directly at vim/neovim.

**Comment by mikepc** [comment]
YAY! You fixed it! Thank you so much <3

**Comment by Shougo** [comment]
The issue should be closed.

**Comment by wsdjeg** [comment]
Thank you.

**Comment by awkj** [comment]
I saw this answer solved my problem, I was very fortunate to meet my former colleague.
and I config in options(init.toml)
```conf
filemanager = "nerdtree"
sidebar_direction = 'left'
```

**Comment by Double1996** [comment]
Thanks !!!

**Comment by TanZng** [comment]
As this is the first google entry I would like to add that now you can use:

```toml
[options]
    filetree_direction = "left"
```
No matter the `filemanager` 😃  . According this docs https://spacevim.org/documentation/#file-tree
