### ISSUE TITLE
Turn off auto-completion for English words?

### ISSUE THREAD

**Issue by peidaqi** [wsdjeg/SpaceVim#2264]
Is it possible to turn off auto-completion for English words? It is quite annoying because it adds a long list of useless items as candidates.

**Comment by Shougo** [comment]
Do you use deoplete.nvim?
You can disable look source for it.
Please read deoplete.nvim documentation.

**Comment by peidaqi** [comment]
I think that's what's for default. I went through deoplete-options and it seems to be linked to neco-look, but I cannot figure out how to turn it off....

**Comment by Shougo** [comment]
You can disable neco-look plugin in SpaceVim.
I don't know what is the proper solution in SpaceVim.

**Comment by peidaqi** [comment]
Tried 
`let g:spacevim_disabled_plugins = ['neco-look'] `
 Doesnt work.

**Comment by marcelomendes** [comment]
Well, I found the solution in the docs. My bad I didn't read it properly. (https://spacevim.org/documentation/#custom-configuration)
So, to disable neco-look you have to add `disabled_plugins = ["neco-look"]` in your ~/.SpaceVim.d/init.toml

**Comment by wsdjeg** [comment]
Thanks for all of you, and yes, you can disable the plugin in toml file.

**Comment by peidaqi** [comment]
Thanks @marcelomendes . @wsdjeg is it possible to make this the default behavior?
I don't think many vim users will find English word looking up useful.

**Comment by wsdjeg** [comment]
sorry, can not, because this plugin has been added since v0.1.0

**Comment by peidaqi** [comment]
@wsdjeg well maybe we can simply add the 'disalbe_plugins' line in init.toml as default?

**Comment by LucianU** [comment]
I also vote for disabling the `neco-look` plugin by default. Most developers don't need alphabetical suggestions for how to name their functions or classes.

**Comment by stfl** [comment]
It would actually be the best to only load the plugin if 'spell' is set.

It used to have it like this in dein. I don't know if that still works. And I don't know what happens if spell is toggled..

```
call dein#add('ujihisa/neco-look', {
         \ 'if': 'executable("look")',
         \ 'on_if': '&spell',
\ })
```

**Comment by Shougo** [comment]
You can configure deoplete like this.

```vim
call deoplete#custom#source('look', 'filetypes', ['help', 'gitcommit'])
```

**Comment by xiuliren** [comment]
or adding a commented out line in default toml file with some comments?
```
# uncomment this will disable the autocomplete of english words
#disabled_plugins = ["neco-look"]
```

**Comment by wsdjeg** [comment]
@jingpengw I do not want to add too many content in the toml example file.

**Comment by wsdjeg** [comment]
@stfl use `'if': 'executable("look")'` seems better.
