### ISSUE TITLE
When cursor move to "(" "[" and "{", you will see the error

### ISSUE THREAD

**Issue by Near-Tam** [wsdjeg/SpaceVim#2266]
When cursor move to "(" "[" and "{", you will see the error, as follow:
Error detected while processing function 125..126..<SNR>141_add_matches:
line   23:
E117: Unknown function: matchaddpos

Who has met  and solved this problem？

**Comment by Near-Tam** [comment]
![2018-10-18 11 24 13](https://user-images.githubusercontent.com/23352749/47129599-7bf8df80-d2c8-11e8-980d-63859a486dad.png)

**Comment by wsdjeg** [comment]
ok, it is a bug of upstream plugin. I will check it.

**Comment by Near-Tam** [comment]
> ok, it is a bug of upstream plugin. I will check it.

Thanks. But this bug appears only in the vim7.4, vim8.0 is ok.

**Comment by wsdjeg** [comment]
This has been fixed, if your vim has no matchaddpos func, this plugin will not be loaded, please update SpaceVim.
