### ISSUE TITLE
E117: Unknown function: EasyMotion#highlight#InitHL

### ISSUE THREAD

**Issue by zloopk09** [wsdjeg/SpaceVim#2268]
## Expected behavior, english is required
when I open vim, it says:
Error detected while processing /Users/username/.cache/vimfiles/.cache/vimrc/.dein/plugin/easyoperator/line.vim:
line   81:
E117: Unknown function: EasyMotion#highlight#InitHL
Press ENTER or type command to continue

and after I pressed enter, it shows:
![image](https://user-images.githubusercontent.com/7008207/47217822-4218fd80-d3dc-11e8-890d-d0389b1df792.png)

# The reproduce ways from Vim starting (Required!)
Just after I installed SpaceVim, it shows this.
how should I fix this?

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
you can reinstall these plugins, please read `:h SPReinstall`, for example `:SPReinstall vim-easymotion`
