### ISSUE TITLE
Q: How to turn off all mouse integration?

### ISSUE THREAD

**Issue by HouzuoGuo** [wsdjeg/SpaceVim#2269]
The usual trick `:set mouse-=a` doesn't help with it, quite unfortunately, afterwards mouse keys still results in selection of text in the active buffer.

What's the SpaceVim's way of turning off mouse integration? Many thanks.

**Comment by martianzhang** [comment]
I use `:set mouse=''` disable mouse trigger action.

**Comment by HouzuoGuo** [comment]
thanks very much @martianzhang, though `:set mouse=''` yielded syntax error, neovim happily accepted `:set mouse=` and successfully disabled mouse integration.
