### ISSUE TITLE
Error when use Tab in SpaceVim 

### ISSUE THREAD

**Issue by Robin-Wujw** [wsdjeg/SpaceVim#2274]
when I use tab in Spacevim with vim8.1 
it shows that : 
Error detected while processing function SpaceVim#mapping#tab[1]..SpaceVim#mapping#tab#i_tab[4]..neosnippet#expandable[1]..neosnippet#ma
ppings#expandable[2]..neosnippet#helpers#get_snippets:
line    9:
E712: Argument of extend() must be a List or Dictionary

**Comment by wsdjeg** [comment]
no issue template and reproduce step.

**Comment by ReedyBear** [comment]
I had this error. 

In my `init.toml`, I changed the tabkey autocompletion behavior to `nil`:
```
[[layers]]
    name = "autocomplete"
    auto_completion_tab_key_behavior = "nil"
```

Note that I also had errors with UltiSnips & deoplete. I think the problem originated with ultisnips, but this was an easier fix than troubleshooting that.
