### ISSUE TITLE
E21: Cannot make changes, 'Modifiable' is off

### ISSUE THREAD

**Issue by sshsu** [wsdjeg/SpaceVim#2275]
when i use shell window  in vim , it reminds me of an error "E21 Cannot make changes, 'modifiable' is off " if i expect  getting last shell directive by key up-arrow.  After searched solution of 'E21',  blogs told me it can be handled by using directive ':set ma' in vim ,however ,another error 'E946: Cannot make a ternimal with running job modifiable:ma' occured, when i used directive ':set ma'. can somebody help?

**Comment by wsdjeg** [comment]
I can not understand your question, please use issue template, and post reproduce step.

**Comment by dyxushuai** [comment]
this happend in easymotion and quicfix buffer
