### ISSUE TITLE
Question : Can we change the width of the `tree`/`filemanager` displayed within the terminal ?

### ISSUE THREAD

**Issue by cmoulliard** [wsdjeg/SpaceVim#2276]
Can we change the width of the `tree`/`filemanager` displayed within the terminal ?

![screenshot 2018-10-25 11 37 57](https://user-images.githubusercontent.com/463790/47491124-78c29e00-d84a-11e8-95bf-f7677185a70c.png)

**Comment by wsdjeg** [comment]
of cause you can, It is SpaceVim option, by default it is 30.

```toml
[options]
   sidebar_width = 30
```
