### ISSUE TITLE
Question: how to search a file in current directory or locate a file by filename？

### ISSUE THREAD

**Issue by sshsu** [wsdjeg/SpaceVim#2277]
first, the reason i dont like using command ':find filename' is that command 'find' no only needs to set search path but also acts not well while searching some files below directory( often cannot find them)   

as the question tittle,  does the catalogue plugin 'vimfiler' of spacevim provide a function of search(or locate) a file by filename? I have  read about the document of 'vimfiler' on website 
(https://github.com/Shougo/vimfiler.vim/blob/master/doc/vimfiler.txt#L538) and found shortcut key 'gf' may be what i want, however, it cannot be used and causes some errors such as  'E117 unknow function:<SNR>167_selected' ,'E15 invalid expression <SNR>167_selected' ，can somebody help?

**Comment by xiuliren** [comment]
I use `SPC f f` to search in current folder. don't know how to search in the whole github repo. @wsdjeg  any ideas?

**Comment by wsdjeg** [comment]
you can use `SPC p f` or `<C-p>` in normal mode.

**Comment by sshsu** [comment]
thanks all,  I am using plugin LeaderF now by modifying spacevim's config file  ".Spacevim.d/init.toml" to add it, a really amazing plugin

**Comment by sshsu** [comment]
but still cannot get a directory tree plugin which supports fuzzy search，expecting

**Comment by wsdjeg** [comment]
what do you mean `a directory tree plugin which supports fuzzy search`?

**Comment by ghost** [comment]
> you can use `SPC p f` or `<C-p>` in normal mode.

This key binding is not defined in my case, do you know how to fix it? I am getting this error:

```
key binding is not defined: [SPC]-p-f
```

**Comment by coppercash** [comment]
> [SPC]-p-f

I figured it out.
I needed to enable a fuzzy finder layer.
Checkout this [section](https://spacevim.org/documentation/#fuzzy-finder) .
