### ISSUE TITLE
Neosnippet "<TAB> to next placeholder" default shortcut addition

### ISSUE THREAD

**Issue by isentropic** [wsdjeg/SpaceVim#2278]
"Feature suggestion"
It would be great to have default Neosnippet's "\<TAB\> moving to next placeholder within a snippet" motion to be remapped to something not intervening with SpaceVim's shortcuts.

This is needed when \<TAB\> is mapped to 'cycle', and \<RETURN\> is mapped to 'smart'.

**Comment by wsdjeg** [comment]
I will look into it, If `<tab>` is mapped to `cycle` and then we should not use it as neosnippet's key binding? so which key is better?

**Comment by stfl** [comment]
it would be nice to have sth like 'cycle_snippet'

```
  elseif s:tab_key_behavior ==# 'cycle_snippet'

inoremap <silent><expr> <Tab>  pumvisible() ? "\<Down>"
    \ : neosnippet#jumpable() ? "\<Plug>(neosnippet_jump)"
    \ : "<Tab>"
```

*this is untested* but does that make sense?

**Comment by wsdjeg** [comment]
when using `cycle`, it means `tab` is only used to sycle the pupopmenu. then we need to add new key bindings for snippet jumpping.

**Comment by wsdjeg** [comment]
in current version of spacevim, the `auto-completion-tab-key-behavior` has four actions to choose. please check the doc.
