### ISSUE TITLE
<↑>and k this key 

### ISSUE THREAD

**Issue by paragon-h** [wsdjeg/SpaceVim#2279]
When I Open a file,
Use the j key to bot 
but use the k key can not to top
![pv8oug p a4dbni 0v pes7](https://user-images.githubusercontent.com/42363586/47540673-dddcc900-d908-11e8-8c09-dbaf0e5bb46b.png)

**Comment by wsdjeg** [comment]
you vim is too old, and `vim-matchup` need function matchaddpos.
