### ISSUE TITLE
Display abnormal when launching vim or nvim after install spacevim

### ISSUE THREAD

**Issue by vancaho** [wsdjeg/SpaceVim#2281]
Hi, recently I install spaceVim in ubuntu 16.04 64bit. However when I launch vim/nvim to open python file in tmux session, the display is  abnormal: when I move cursor up and down the content moves. But if  I launch vim/nvim without in tmux, the display seems normal.

**Comment by vancaho** [comment]
![default](https://user-images.githubusercontent.com/15372990/47605134-0366f100-da35-11e8-841d-af8b0f411cee.JPG)
![2](https://user-images.githubusercontent.com/15372990/47605139-1083e000-da35-11e8-9104-c20ce7b6067b.JPG)
The above two images show the abnormal display when open a py file
The following image shows that when I launch vim without in tmux
![3](https://user-images.githubusercontent.com/15372990/47605162-71131d00-da35-11e8-95d0-8a188f58416c.JPG)

**Comment by crisidev** [comment]
What is your $TERM variable inside tmux?

Can you please try to launch vim as `TERM=screen-256color vim filename.py`?

**Comment by vancaho** [comment]
I fogot one thing: I install spacevim and tumx on a ubuntu 16.04 server, and use the terminal in macos to remotely ssh to the server. The $TERM variable inside tmux in ubuntu is  `screen`. Using `TERM=screen-256color vim filename.py`  seems do not make things better.
![image](https://user-images.githubusercontent.com/15372990/47610670-d266da80-da8d-11e8-89d9-106df1f6cdd7.png)
From the above image, the `r` letter before `return` is abnormal

**Comment by vancaho** [comment]
![image](https://user-images.githubusercontent.com/15372990/47610766-f3c8c600-da8f-11e8-9d29-a1d9c8e397ec.png)
When launch nvim within tmux from ssh(macos iterm2-->ubuntu), the startup image shows abnormal

**Comment by vancaho** [comment]
Solved! I can solve the problem with `tmux -u` command

**Comment by wsdjeg** [comment]
Ok, nice to hear that.
