### ISSUE TITLE
The design of SpaceVim v1.0.0

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2285]
v1.0.0 should be first stable version of SpaceVim, the milestone is [v1.0.0](https://github.com/SpaceVim/SpaceVim/milestone/13).

**Comment by ghost** [comment]
More support for LSP component, and let users can design user's own layer, that function can let SpaceVim be more flexible, and externable it easy.

**Comment by wsdjeg** [comment]
in SpaceVim, users can enable lsp layer, also can create custom layer, so what feature is missing?


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] The design of SpaceVim v1.0.0 (#2285)
发件人：Anonymous
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Author


More support for LSP component, and let users can design user's own layer, that function can let SpaceVim be more flexible, and externable it easy.

―

**Comment by ghost** [comment]
I know user can enable lsp layer, but SpaceVim support's language LSP port is very very small, Hope add more languages LSP port in SpaceVim
