### ISSUE TITLE
How to specify the arguments when debugging or executing a script?

### ISSUE THREAD

**Issue by vancaho** [wsdjeg/SpaceVim#2286]
Hi, I want to use the debugger or execute a python script in SpaceVim. However, I can't find the entry to specify the arguments for the scrpit. 
How to specify the arguments when debugging or executing a script?

**Comment by wsdjeg** [comment]
In current version, It does not support it, but maybe it will be added in the feature. And if you are family with SpaceVim, you can register your own runner.

**Comment by wsdjeg** [comment]
You can use `call SpaceVim#plugins#runner#open('test.py arge')` now.
