### ISSUE TITLE
Autoflake clear my whole .py

### ISSUE THREAD

**Issue by hsingll** [wsdjeg/SpaceVim#2293]
## Expected behavior
When using autoflake to remove unused imports,the whole .py will be cleared.

## The reproduce ways from Vim starting (Required!)
Enable layer "lang#python",using shortcut "SPC l i r".

## Screenshots
![qq20181110-164056-hd](https://user-images.githubusercontent.com/26346635/48299357-b6d8e680-e507-11e8-9cd6-c4828df0e3eb.gif)

**Comment by adawalli** [comment]
@wsdjeg - I am seeing this behavior as well

**Comment by ssfdust** [comment]
It's the problem in neoformat.
https://github.com/neoformat/neoformat/pull/1
https://github.com/sbdchd/neoformat/pull/200

**Comment by adawalli** [comment]
Thanks for the update and PR's @ssfdust !

**Comment by wsdjeg** [comment]
Hello, I just update neoformat and spacevim, can you have a try? @UniqueSimon

**Comment by adawalli** [comment]
well, **[SPC] l i r** no longer wipes out my buffer. The bad news is that it doesn't actually remove any imports.

I just get a message saying **Neoformat: no change necessary with autoflake**

**Comment by hsingll** [comment]
the same as @adawalli ,neither empty my file nor remove unused imports. @wsdjeg

**Comment by ssfdust** [comment]
It's my mistake for not checking availability on the non-standard library. I have added the option, it should work as expected, but due to the limitation from autoflake, it won't work on the multi-line import.
https://github.com/myint/autoflake/issues/41

**Comment by adawalli** [comment]
Thanks working for me now!

**Comment by wsdjeg** [comment]
just update neoformat，please check it again.


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Autoflake clear my whole .py (#2293)
发件人：UniqueSimon
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Mention


the same as @adawalli<https://github.com/adawalli> ,neither empty my file nor remove unused imports. @wsdjeg<https://github.com/wsdjeg>

―

**Comment by hsingll** [comment]
It works! @wsdjeg.Thank you.

**Comment by adawalli** [comment]
even multine works now! Thanks @wsdjeg and @ssfdust !
