### ISSUE TITLE
 Alt/Meta+normal mode key from insert mode doesn't consistently produce the expected results

### ISSUE THREAD

**Issue by tobimensch** [wsdjeg/SpaceVim#2294]
## Expected behavior, english is required
I'm using Alt+I as example, but this applies to all Alt+normal mode key combinations.
As a vimmer I'm trying to reduce the number of keystrokes and I want to avoid using ESC, if possible.
There's the neat trick of using Alt/Meta + normal mode key to leave insert mode and execute the normal mode key combination without using ESC. This works in default vim/nvim.

## The reproduce ways from Vim starting (Required!)
Start vim. Enter some text in insert mode. Try Alt-I to continue writing at the start of line.
For me this fails and vim stays in insert mode and an I character is inserted.
However sometimes the expected behavior can be observed. It appears random to me,
so I can't tell what I do differently in these cases.

**Comment by wsdjeg** [comment]
sorry, I can not understand this question, as I know in vim, `ALt + I` is same as `<Esc>I`.

**Comment by tobimensch** [comment]
@wsdjeg 
It works sometimes, but randomly doesn't. It doesn't work consistently.
