### ISSUE TITLE
SpaceVim GUI not loading properly

### ISSUE THREAD

**Issue by MarkusLee626** [wsdjeg/SpaceVim#2295]
## Behaviour
As soon as I install SpaceVim the graphics seem to be distorted with a lot of icons not loading properly.

## How to reproduce
Simply starting vim

## Debug info
I've got a bit of a complicated set up. Currently using the ubuntu version of the linux subsystem on Windows. Also got zsh set up and is using the Hyper terminal.

OS: Windows
Vim: 8.0

## Screenshots
![image](https://user-images.githubusercontent.com/25385344/48388632-f400cc80-e6f1-11e8-81f5-040e62437af5.png)

**Comment by hsingll** [comment]
install this font.
https://github.com/ryanoasis/nerd-fonts

**Comment by wsdjeg** [comment]
yeah, you need to install the fonts.
