### ISSUE TITLE
local config is not sourced by spacevim with neovim 

### ISSUE THREAD

**Issue by roadtest** [wsdjeg/SpaceVim#2296]
## The reproduce ways from Vim starting (Required!)
OS: macos 10.13.6
neovim: v0.3.1

I have some local setting in ~/.local.vim as below: 
`$ more ~/.local.vim 

 map \<c\-k\> \<space\>ft
  if has("persistent_undo")
    set undodir=~/.vim/.undodir/
    set undofile
 endif
 nnoremap \<F12\> :UndotreeToggle<cr>`

``

When i started nvim, it is not being sourced. If i added above config to ~/.config/nvim/init.vim, it works. Seems SpaceVim doesn't source ~/.local.vim  when run with neovim.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

  1 - OS: mac
  2 - vim version: -
  3 - neovim version: 0.3.1
  4 - SpaceVim version: 1.0.0-dev
  5 - SpaceVim status:
  6
  7 ```
  8 On branch master
  9 Your branch is up to date with 'origin/master'.
 10
 11 Untracked files:
 12   (use "git add <file>..." to include in what will be committed)
 13
 14   .local.vim
 15
 16 nothing added to commit but untracked files present (use "git add" to track)
 17 ```
 18
 19 ## The reproduce ways from Vim starting (Required!)
 20
 21 ## Output of the `:SPDebugInfo!`
 22
 23 <details><summary> SpaceVim debug information </summary>
 24
 25 ### SpaceVim options :
 26
 27 ```toml
 28   auto_disable_touchpad = 1
 29   autocomplete_method = 'asyncomplete'
 30   autocomplete_parens = 1
 31   background = 'dark'
 32   buffer_index_type = 4
 33   checkinstall = 1
 34   colorscheme = 'gruvbox'
 35   colorscheme_bg = 'dark'
 36   colorscheme_default = 'desert'
 37   custom_color_palette = []
 38   custom_plugins = [['mbbill/undotree', {'name': 'mbbill/undotree', 'merged': 0}]]
 39   debug_level = 1
 40   default_indent = 2
 ❶  * issue_report.md  markdown  ❖ ⓢ                                                                                                                                                                         | utf-8  6:0  Top

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please read the doc, and quick start guide, SpaceVim do not use local.vim as local config.
