### ISSUE TITLE
Using swedish ä

### ISSUE THREAD

**Issue by passar** [wsdjeg/SpaceVim#2297]
## Expected behavior, english is required
Pressing ä in insert mode should type the letter ä.

## The reproduce ways from Vim starting (Required!)
Pressing ä in insert mode does act as backspace. In the : menu ä acts like a C-backspace.

## Debug info

It might be a feature but unintentionally made Swedish hard to type.

## Screenshots
Nothing to see, ä removes.

**Comment by wsdjeg** [comment]
sorry, I can not reproduce it, but can you reproduce without SpaceVim?
