### ISSUE TITLE
layer default <Leader> y /<Leader> p not work

### ISSUE THREAD

**Issue by glock42** [wsdjeg/SpaceVim#2300]
I use my laptop to SSH my lab machine and use the SpaceVim to edit my code.

But I found that I use `<Leader> y ` to copy the content in SpaceVim, but the host system's paste is the original thing. Vice versa.

 The `<Leader> y /<Leader> p ` doesn't work, even if I add the `default` layer.

My env as follows.
VIM - Vi IMproved 8.1
Lab machine: ubuntu 16.04
Host machine: macOS 10.14.1 
And the latest SpaceVim version.

Btw, how to auto toggle the `tagbar` or `Vimfiler` when I open the file?

Thank you.

**Comment by wsdjeg** [comment]
make sure your vim support register `+` or `*`, the tagbar key binding is `F2` and vimfiler is `F3`, please read doc.
