### ISSUE TITLE
Installation instructions without piping into bash

### ISSUE THREAD

**Issue by yotamN** [wsdjeg/SpaceVim#2302]
Please consider adding installation instructions without piping the installation script into bash or maybe even make it the recommended way. Piping into bash is bad practice and should not be the recommended or at least the only way to install it.

From my understanding of the script, the instructions won't be too hard, maybe except the fonts.

**Comment by wsdjeg** [comment]
pull request is welcome, and I will check it.

**Comment by wsdjeg** [comment]
Sorry, It is more eary for user install SpaceVim, which inlcude ( check old vim config, back, check requiltment, etc.)
