### ISSUE TITLE
vim macro is not working well

### ISSUE THREAD

**Issue by makerjackie** [wsdjeg/SpaceVim#2304]
For example, start recording a macro to register a
```
q + a
```
then join two line using `J` and move to next line
```
J + j
```
finally, stop recording
```
q
```
but when you enter
```
@a
```
It work strange, first it `j` then `J'

**Comment by wsdjeg** [comment]
@Jackiexiao Do you use vimcompatable mode? and can you reproduce it in gvim?

**Comment by wsdjeg** [comment]
This is feature of vim it self.
