### ISSUE TITLE
Bug about multi-line comments in python

### ISSUE THREAD

**Issue by xz-dev** [wsdjeg/SpaceVim#2308]
## Expected behavior

Quickly typing "" in a python file should automatically complete """, 
at least not the cursor jumps in the video.

## The reproduce ways from Vim starting

Open or create any python file using spacevim.

## Debug info

SpaceVim layers:

- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete
- chat:                 not loaded          https://spacevim.org/layers/chat
+ checkers:                 loaded          https://spacevim.org/layers/checkers
- chinese:              not loaded          https://spacevim.org/layers/chinese
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme
+ core/banner:              loaded          https://spacevim.org/layers/core/banner
+ core/statusline:          loaded          https://spacevim.org/layers/core/statusline
+ core/tabline:             loaded          https://spacevim.org/layers/core/tabline
+ core:                     loaded          https://spacevim.org/layers/core
- cscope:               not loaded          https://spacevim.org/layers/cscope
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp
- debug:                not loaded          https://spacevim.org/layers/debug
- denite:               not loaded          https://spacevim.org/layers/denite
+ edit:                     loaded          https://spacevim.org/layers/edit
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits
+ format:                   loaded          https://spacevim.org/layers/format
- fzf:                  not loaded          https://spacevim.org/layers/fzf
- games:                not loaded          no exists
- git:                  not loaded          https://spacevim.org/layers/git
- github:               not loaded          https://spacevim.org/layers/github
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese
- lang/WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly
- lang/agda:            not loaded          https://spacevim.org/layers/lang/agda
- lang/asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc
- lang/autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey
- lang/c:               not loaded          https://spacevim.org/layers/lang/c
- lang/clojure:         not loaded          https://spacevim.org/layers/lang/clojure
- lang/crystal:         not loaded          no exists
- lang/csharp:          not loaded          https://spacevim.org/layers/lang/csharp
- lang/dart:            not loaded          https://spacevim.org/layers/lang/dart
- lang/dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile
- lang/elixir:          not loaded          https://spacevim.org/layers/lang/elixir
- lang/elm:             not loaded          https://spacevim.org/layers/lang/elm
- lang/erlang:          not loaded          https://spacevim.org/layers/lang/erlang
- lang/extra:           not loaded          https://spacevim.org/layers/lang/extra
- lang/fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp
- lang/go:              not loaded          https://spacevim.org/layers/lang/go
- lang/haskell:         not loaded          https://spacevim.org/layers/lang/haskell
- lang/html:            not loaded          https://spacevim.org/layers/lang/html
- lang/java:            not loaded          https://spacevim.org/layers/lang/java
- lang/javascript:      not loaded          https://spacevim.org/layers/lang/javascript
- lang/json:            not loaded          no exists
- lang/julia:           not loaded          https://spacevim.org/layers/lang/julia
- lang/kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin
- lang/latex:           not loaded          https://spacevim.org/layers/lang/latex
- lang/lisp:            not loaded          https://spacevim.org/layers/lang/lisp
- lang/lua:             not loaded          https://spacevim.org/layers/lang/lua
- lang/markdown:        not loaded          https://spacevim.org/layers/lang/markdown
- lang/nim:             not loaded          https://spacevim.org/layers/lang/nim
- lang/ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml
- lang/perl:            not loaded          https://spacevim.org/layers/lang/perl
- lang/php:             not loaded          https://spacevim.org/layers/lang/php
- lang/plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml
- lang/pony:            not loaded          no exists
- lang/ps1:             not loaded          no exists
- lang/puppet:          not loaded          https://spacevim.org/layers/lang/puppet
- lang/purescript:      not loaded          https://spacevim.org/layers/lang/purescript
+ lang/python:              loaded          https://spacevim.org/layers/lang/python
- lang/r:               not loaded          no exists
- lang/ruby:            not loaded          https://spacevim.org/layers/lang/ruby
- lang/rust:            not loaded          https://spacevim.org/layers/lang/rust
- lang/scala:           not loaded          https://spacevim.org/layers/lang/scala
- lang/scheme:          not loaded          https://spacevim.org/layers/lang/scheme
- lang/sh:              not loaded          https://spacevim.org/layers/lang/sh
- lang/solidity:        not loaded          no exists
- lang/swift:           not loaded          https://spacevim.org/layers/lang/swift
- lang/swig:            not loaded          no exists
- lang/toml:            not loaded          no exists
- lang/typescript:      not loaded          https://spacevim.org/layers/lang/typescript
- lang/vim:             not loaded          https://spacevim.org/layers/lang/vim
- lang/vue:             not loaded          https://spacevim.org/layers/lang/vue
- lang/xml:             not loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell
- sudo:                 not loaded          https://spacevim.org/layers/sudo
- tags:                 not loaded          https://spacevim.org/layers/tags
- tmux:                 not loaded          https://spacevim.org/layers/tmux
- tools/dash:           not loaded          https://spacevim.org/layers/tools/dash
- tools/screensaver:    not loaded          no exists
- tools:                not loaded          https://spacevim.org/layers/tools
+ ui:                       loaded          https://spacevim.org/layers/ui
- unite:                not loaded          https://spacevim.org/layers/unite
- vim:                  not loaded          no exists

## Screenshots

https://asciinema.org/a/BhcUw5wM9arUCj7vxc50Oj3wt

**Comment by wsdjeg** [comment]
This feature of `Raimondi/delimitMate`, and if you want this plugin do not complete `"`, you need to config it in bootstrap function.

**Comment by wsdjeg** [comment]
Maybe we should add a layer option for this feature.

**Comment by xz-dev** [comment]
@wsdjeg But I want it could complete """, is there a way to implement it? :smiley:
