### ISSUE TITLE
Is there a standalone mnemonic key bindings navigation plugin

### ISSUE THREAD

**Issue by JensenJiang** [wsdjeg/SpaceVim#2314]
I really like the feature mentioned in "https://spacevim.org/mnemonic-key-bindings-navigation/", but the auto config coming with SpaceVim contradict a lot with my old config. Is there a standalone plugin for this feature, or is there a way to disable all other functionalities except this?

**Comment by stfl** [comment]
The plugin to display the key bindings is hecal3/vim-leader-guide
It's not fun to configure, in my opinion :P

**Comment by wsdjeg** [comment]
Yeah, you can use vim-leader-guide, but in SpaceVim, I have rewrite a new plugin for this feature, so It is not same as that plugin.

**Comment by stfl** [comment]
I see. Thanks for clarifying.
Is your plugin available as a standalone plugin?

**Comment by wsdjeg** [comment]
sorry, it is not. because it need SpaceVim core api.
