### ISSUE TITLE
default minor mode

### ISSUE THREAD

**Issue by tinybeachthor** [wsdjeg/SpaceVim#2316]
Is there a way to set some "minor modes" to be on by default.

For example, to have syntax checking and highlighting of long lines in every buffer on by default?

**Comment by wsdjeg** [comment]
Nice feature request, and I will try to add this feature.

________________________________
wsdjeg@outlook.com

**Comment by wsdjeg** [comment]
@WhoMeNope hi, I have open an PR about this feature, sorry for so long time. please checkout #3076
