### ISSUE TITLE
Add description of mapping on leader menu

### ISSUE THREAD

**Issue by kabasakalis** [wsdjeg/SpaceVim#2317]
I would like to be able to describe my custom leader mapping, instead of showing only the mapped command. For example in the screenshot shown I would like to add "Paste from clipboard".  Is there currently a way to do this?  

![image](https://user-images.githubusercontent.com/323951/49345780-63832f80-f692-11e8-8563-2c7a208a0711.png)

**Comment by stfl** [comment]
If you want to change this in you're .SpaceVim.d you can create a bootstrap_before function in which you define a custom mapping that is used is spacevim to feed it into LeaderGuide...

sth like this (from my config).. which is for SPC not for <leader>.. There is an equivalent function for that..

      call SpaceVim#custom#SPC('nmap', ['x', 'a'], '<Plug>(LiveEasyAlign)', 'align interactive operator', 0)

The last argument 0 means that it is a mapping, whereas if it is 1 it is a Command (called with **:** )

The <leader>p mapping is actually a default mapping in SpaceVim. (I don't know which layer though). The default also does not have a description, so if you care to update it there it would be useful for others.
And <leader>y only works for visual.. So there's room for improvement.

PS: Also you mappings for c and x look interesting to me. I will integrate that into my config.

**Comment by kabasakalis** [comment]
I am aware of `SpaceVim#custom#SPC` but this works for mappings that begin with `SPC`. I have set my neovim leader to  `;`. I would like to do the same thing with my custom leader bindings.

**Comment by stfl** [comment]
Ok. it seams there is no function like SpaceVim#custom#Leader... in https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/custom.vim
There should be @wsdjeg 

The mappings for "+p are defined in autoload/SpaceVim/default.vim

**Comment by Gabirel** [comment]
Same issue here. Can you add support for mapping into the group `<leader>` as well? @wsdjeg 

https://github.com/SpaceVim/SpaceVim/blob/bed0d306ff53c9faaa9adb3f0332c9f59a2978e3/autoload/SpaceVim/custom.vim#L78-L80

Like this above: 
```vim
function! SpaceVim#custom#Leader(m, keys, cmd, desc, is_cmd) abort 
    " ...
endfunction
```

**Comment by Gabirel** [comment]
@wsdjeg Any updates/plans on this? Although I don't think that's necessary, maybe I open another issue for this?

**Comment by wsdjeg** [comment]
Pleae use new issue instead. This has been closed.
