### ISSUE TITLE
Is there any way to change g:tagbar_left ?

### ISSUE THREAD

**Issue by zoumo** [wsdjeg/SpaceVim#2318]
I want to place the filetree on left and tagbar on right
So I need to change the g:tagbar_left = 0

I tried to modify it in the bootstrap_before or after phase, but it didn't work

So Is there any way to change g:tagbar_left ?
@wsdjeg

**Comment by wsdjeg** [comment]
There is an option for these sidebar, but it is still WIP.

________________________________
wsdjeg@outlook.com

**Comment by zoumo** [comment]
@wsdjeg 
要不还是用中文交流吧
我看到有一些变量，比如
```
g:vimfiler_direction
g:tagbar_left
```
我想要去修改它，当时目前好像没有一个机制可以直接影响到他们

**Comment by wsdjeg** [comment]
如果觉得英文交流比较麻烦，可以直接在 SpaceVim 中文聊天室交流。

________________________________
wsdjeg@outlook.com
