### ISSUE TITLE
SPC e n should select the first item. Single item in quickfix not accessable

### ISSUE THREAD

**Issue by stfl** [wsdjeg/SpaceVim#2319]
## Expected behavior, english is required

<kbd>SPC e n</kbd> jumps to the next error. It initially selects the first item, so <kbd>SPC e n</kbd> selects the next one. The first invocation of <kbd>SPC e n</kbd> should select the first item.
If there is only one item in quickfix, it's not accessable at all.

**Comment by wsdjeg** [comment]
ok，I will look into it. It seems a key bindings issue.

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] SPC e n should select the first item. Single item in quickfix not accessable (#2319)
发件人：Stefan Lendl
收件人：SpaceVim/SpaceVim
抄送：Subscribed

Expected behavior, english is required

SPC e n jumps to the next error. It initially selects the first item, so SPC e n selects the next one. The first invocation of SPC e n should select the first item.
If there is only one item in quickfix, it's not accessable at all.

―

**Comment by stfl** [comment]
Btw I was using neomake.

**Comment by wsdjeg** [comment]
@stfl `SPC e n` is mapped to `:lnext` so it should only works well for location list, it do not support quickfix list, if you want to switch between quckfix list, I think you can use `Leader q j` and `Leader q k`. here `Leader` means `\` by default.

**Comment by stfl** [comment]
So I guess it was my mistake pointing out quickfix when actually location list is used.

It makes sense for it to be mapped to :lnext because neomake adds it's findings to the location list. 
<kbd>SPC e n</kbd> is the mapping to navigate through errors reported by neomake / ALE. It should therefor also be possible to jump to the first error...

**Comment by stfl** [comment]
The same is also true for <kbd>Leader q j</kbd> and therelike.. if there is only one item, it's not accessable through that mapping

Also mappings should be equal to <kbd>SPC e n|p</kbd>   >> <kbd>Leader q n|p</kbd>
or the other way around.. or both..
there should also be a <kbd>Leader q o</kbd> to open the quickfix

This issue should be reopened.

**Comment by stfl** [comment]
maybe like this: https://stackoverflow.com/questions/27198612/vim-location-list-how-to-go-to-first-location-if-at-last-location

or using unimpaired as it is already available.

**Comment by wsdjeg** [comment]
Ok, I will create a quickfix and location list plugin, it should works well for both quickfix list and location list.

**Comment by wsdjeg** [comment]
I just change the key bindings:

`SPC e n` will try to run `lnext`, if the location list is empty, it will try to run `cnext`, if both qflist and location list are empty, it will print error message. `SPC e p/N` has same logic.

`SPC e l` will try to open location list, if location list is empty, it will try to open qflist, if both are empty, it will print error message too.
