### ISSUE TITLE
Windows home dir name including space causes SpaceVim installation failed.

### ISSUE THREAD

**Issue by THMonster** [wsdjeg/SpaceVim#232]
## Expected behavior, english is recommend
由于windows用户名有空格,导致无法正常安装

## Environment Information
- OS: win10
- vim version: gvim8.0.69
- neovim version:

## The reproduce ways from Vim starting (Required!)
使用任意一台用户名带空格的windows电脑安装SpaceVim即可重现错误

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

![7t_36uoz mfxf adkohl_0c](https://cloud.githubusercontent.com/assets/5125031/22929675/d47f421e-f2f7-11e6-9ab1-c37851ae77e9.png)

**Comment by wsdjeg** [comment]
@IsoaSFlus can you test #233 ?

**Comment by THMonster** [comment]
@wsdjeg it doesn't work.
![qq 20170214231053](https://cloud.githubusercontent.com/assets/5125031/22934859/8362fe5c-f30b-11e6-96e4-139e33c2bb8a.png)
![qq 20170214231331](https://cloud.githubusercontent.com/assets/5125031/22934876/8e9d5dda-f30b-11e6-8472-1d0f5f85560c.png)
![qq 20170214231118](https://cloud.githubusercontent.com/assets/5125031/22934883/94542a1a-f30b-11e6-896d-31992d61f2ae.png)

**Comment by wsdjeg** [comment]
I am sorry, but can you test it again? I just make some chanages.

**Comment by THMonster** [comment]
@wsdjeg sadly, doesn't work.
![qq 20170215213602](https://cloud.githubusercontent.com/assets/5125031/22976721/f31c3aa4-f3c6-11e6-882b-d4b67088637a.png)
![qq 20170215213630](https://cloud.githubusercontent.com/assets/5125031/22976729/fb7e04d4-f3c6-11e6-8ad7-39d65e5fcd25.png)
![qq 20170215213635](https://cloud.githubusercontent.com/assets/5125031/22976753/11c0a0e4-f3c7-11e6-9ce3-4f49fd4f5d34.png)

**Comment by wsdjeg** [comment]
I just push some change.

**Comment by THMonster** [comment]
@wsdjeg again...
![qq 20170215230340](https://cloud.githubusercontent.com/assets/5125031/22979962/115196f2-f3d3-11e6-9542-70ebd4e5bea2.png)

**Comment by wsdjeg** [comment]
https://stackoverflow.com/questions/16376035/fatal-could-not-create-work-tree-dir-kivy

 I can not fix it, but there is a link for this issue.

**Comment by THMonster** [comment]
@wsdjeg it seems that the "\\" before space cause the fatal,i deleted it then it  works well
![qq 20170215230340](https://cloud.githubusercontent.com/assets/5125031/23003631/1753e5d2-f42d-11e6-8546-bcb703b55023.png)

**Comment by wsdjeg** [comment]
Thanks, should be fixed now.
