### ISSUE TITLE
logging in with github doesnt work on docs site

### ISSUE THREAD

**Issue by idkjs** [wsdjeg/SpaceVim#2342]
## Expected behavior, english is required
Should be able to login successfully on docs site

## The reproduce ways from Vim starting (Required!)
Go to `https://spacevim.org/use-vim-as-ide/` scroll to bottom and click `login with github`
## Debug info
You get the following object popup and nothing happens after.
<img width="1392" alt="screen shot 2018-12-14 at 10 34 41 am" src="https://user-images.githubusercontent.com/2370391/49995371-40a72400-ff8c-11e8-95f9-a9d5e21ead33.png">

**Comment by wsdjeg** [comment]
This is issue with gitment, I can not fix it.

**Comment by wsdjeg** [comment]
Let make this issue opened, I hope gitment author fix this issue.
