### ISSUE TITLE
Neovim 1.6 and 1.7 Theme or some plugins not working

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [wsdjeg/SpaceVim#235]
## Environment Information
- OS: Mac OS 10.12.3
- vim version: 7.4
- neovim version: 1.6 & 1.7

## The reproduce ways from Vim starting (Required!)
brew install neovim

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
![screen shot 2017-02-14 at 1 35 46 pm](https://cloud.githubusercontent.com/assets/29370/22943247/cf112a5a-f2ba-11e6-92a0-f69068408245.png)

I'm using default SpaceVim config, no changes. Everything works fine in neovim 1.4 but not in 1.6 or 1.7

**Comment by wsdjeg** [comment]
Neovim add 'termguicolors' at 0.1.6, so you need make sure your terminal support true colors. I do not use Mac, but as far as I know, item2 support true colors.

**Comment by CodeMonkeyKevin** [comment]
thx mister. iTerm2 worked.

**Comment by wsdjeg** [comment]
Nice
