### ISSUE TITLE
How to reach same look

### ISSUE THREAD

**Issue by kaldown** [wsdjeg/SpaceVim#236]
## Expected behavior, english is recommend
After installing SpaceVim on both Vim and nVim, there is not even close look to that one you gave on README

## Environment Information
- OS: debian 8.6
- vim version: 7.4
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)
just run any file from Vim or nVim and compare to screenshots on main page.
Can't find anything about configuring SpaceVim on docs you gave.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
:message -> Messages maintainer: Bram Moolenaar <Bram@vim.org>
:echo SpaceVim#logger#viewLog() -> how to put all this text to a file ?

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

There is no config, just installed from scratch, even Vim almost pure

![nvim](https://cloud.githubusercontent.com/assets/3754017/22943667/739a1e08-f2ff-11e6-8c80-caafaee65e1b.png)
![vim](https://cloud.githubusercontent.com/assets/3754017/22943705/90e8fe5c-f2ff-11e6-832a-8327ee657ecf.png)

**Comment by wsdjeg** [comment]
Your terminal do not support true colors. And you should install a powerline fonts.

You can find the font in my dotfiles.
