### ISSUE TITLE
Ctrl+R is failed in detached FlyGrep

### ISSUE THREAD

**Issue by unclechu** [wsdjeg/SpaceVim#2366]
## Expected behavior, english is required

`Ctrl+R` (to paste from register) is failed in detached FlyGrep. I'd expect `^R` to work as in any other window, to paste from some register. I guess "detach" script is not copying some "iedit" modules into detached plugin (see error text in screenshot below).

## The reproduce ways from Vim starting (Required!)

```bash
tmp_dir=`mktemp -d`
git clone --recursive https://github.com/wsdjeg/FlyGrep.vim -- "$tmp_dir"
echo "se rtp+=$tmp_dir" > "$tmp_dir/init.vim"
nvim -u "$tmp_dir/init.vim" '+FlyGrep' # type some text then and press ^R
rm -rf -- "$tmp_dir" # cleanup
```

## Screenshots

After pressing `Ctrl-R` (after entered some text):
![screenshot from 2018-12-19 22-22-39](https://user-images.githubusercontent.com/799353/50242968-d9023600-03dc-11e9-9d79-df960cad9ff0.png)

**Comment by wsdjeg** [comment]
this feature is still wip

**Comment by wsdjeg** [comment]
This feature has been added.
