### ISSUE TITLE
open file in another project does not change project root because of cache

### ISSUE THREAD

**Issue by dyno** [wsdjeg/SpaceVim#2367]
https://github.com/SpaceVim/SpaceVim/blob/8710393b4b917cc033d59e6d8e2992233ca07f7e/autoload/SpaceVim/plugins/projectmanager.vim#L82

**Comment by wsdjeg** [comment]
the cache is b: scope value, if you open new buffer, this value is not exist. do you have a simple reproduce step.


---

Shidong Wang

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] open file in another project does not change project root because of cache (#2367)
发件人：Dyno Fu
收件人：SpaceVim/SpaceVim
抄送：Subscribed


https://github.com/SpaceVim/SpaceVim/blob/8710393b4b917cc033d59e6d8e2992233ca07f7e/autoload/SpaceVim/plugins/projectmanager.vim#L82

―

**Comment by dyno** [comment]
added a bit debug info shows that at the time of the loading, 
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [23:59:00] [ Info ] Startup with argv: ['/Users/dynofu/Code/whatever/setup.cfg']
[ SpaceVim ] [23:59:00] [ Info ] Start to find root for: /Users/dynofu/Code/whatever/setup.cfgwith .git/,_darcs/,.hg/,.bzr/,.svn/,.SpaceVim.d/
[ SpaceVim ] [23:59:00] [ Info ]         (.git/):/Users/dynofu/Code/whatever/.git/
[ SpaceVim ] [23:59:00] [ Info ] change to root:/Users/dynofu/Code/whatever

it looks like my `project_rooter_patterns = ["Makefile", "setup.cfg", "Pipfile", ".git"]` is not effective at the loading time.

**Comment by dyno** [comment]
yes. have a multi projects layout reside in the same git repository.

```
[dynofu@DFu-MAC-SJ: whatever]$ ls -al
total 104
drwxr-xr-x   10 dynofu  staff    320 Dec 21 00:13 .
drwxr-xr-x+ 168 dynofu  staff   5376 Dec 21 00:13 ..
drwxr-xr-x   12 dynofu  staff    384 Dec 21 00:12 .git
drwxr-xr-x    7 dynofu  staff    224 May  7  2018 .venv
-rw-r--r--    1 dynofu  staff  16384 Dec 21 00:13 GPATH
-rw-r--r--    1 dynofu  staff  16384 Dec 21 00:13 GRTAGS
-rw-r--r--    1 dynofu  staff  16384 Dec 21 00:13 GTAGS
-rw-------    1 dynofu  staff    381 Dec 21 00:13 tags
drwxr-xr-x    4 dynofu  staff    128 Dec 21 00:12 whatever1
drwxr-xr-x    4 dynofu  staff    128 Dec 21 00:12 whatever2
[dynofu@DFu-MAC-SJ: whatever]$ tree .
.
├── GPATH
├── GRTAGS
├── GTAGS
├── tags
├── whatever1
│   ├── Pipfile
│   └── Pipfile.lock
└── whatever2
    ├── Pipfile
    └── Pipfile.lock

2 directories, 8 files
```
`project_rooter_patterns = ["Makefile", "setup.cfg", "Pipfile", ".git"]`
now edit file with `vim whatever1/Pipfile`, expect `:pwd` to be in `whatever1` (where the Pipfile resides), but it shows `whatever` where the `.git/` exists.

**Comment by dyno** [comment]
the first problem i report is basically the symptom of the above problem. 
when edit a `whatever1/Pipfile`, the root has been set to `whatever`. if i unset the cache `call setbufvar('%', 'rootDir', '')` then switch back now it works as expected. so the problem is really how to make the `project_rooter_patterns` setting effective if i `vim whatever1/Pipfile` - edit a file directly.

**Comment by wsdjeg** [comment]
SpaceVim will try to find root before loadding custom config, so that is why It can not find your project root. yes, if the project rooter patterns is change the cache should be cleared.
