### ISSUE TITLE
let g:spacevim_unite_leader = "\<Space>" 不生效

### ISSUE THREAD

**Issue by lcg635** [wsdjeg/SpaceVim#238]
let g:spacevim_unite_leader = "\<Space>" 不生效

默认的<unite>为f, 但是我经常使用f在行内跳转
如果把mapleader设置为空格, 那两个空格就打不开menu:CustomKeyMaps

**Comment by wsdjeg** [comment]
@lcg635 I have fixed this issue, please update SpaceVim. and you should use 
```vim
let g:spacevim_unite_leader = "<Space>"
```
instead of
```viml
let g:spacevim_unite_leader = "\<Space>"
```
