### ISSUE TITLE
The vim Plugin "luochen1990/rainbow" doesn't work in SpaceVim.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2380]
## Expected behavior
"luochen1990/rainbow" is a nice plugin for vim. It can color Parentheses in a nice way so that users can  see the pairs of parentheses easily. But it doesn't work in SpaceVim. And I have installed it by adding these lines below to `init.toml`.
```
[[custom_plugins]]
    name = 'luochen1990/rainbow'
    merged = 0
```

## Debug info

SpaceVim layers:

+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
+ chinese:                  loaded          https://spacevim.org/layers/chinese/
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- debug:                not loaded          https://spacevim.org/layers/debug/
- denite:               not loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
+ format:                   loaded          https://spacevim.org/layers/format/
- fzf:                  not loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
+ git:                      loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
- lang#c:               not loaded          https://spacevim.org/layers/lang/c/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#crystal:         not loaded          no exists
- lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
- lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
- lang#go:              not loaded          https://spacevim.org/layers/lang/go/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
- lang#html:            not loaded          https://spacevim.org/layers/lang/html/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
- lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
+ lang#latex:               loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
+ lang#markdown:            loaded          https://spacevim.org/layers/lang/markdown/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
- lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          no exists
- lang#ps1:             not loaded          no exists
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
+ lang#python:              loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          no exists
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
- lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
- lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
- lang#solidity:        not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#toml:            not loaded          no exists
- lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
+ lang#vim:                 loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#xml:             not loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell/
- sudo:                 not loaded          https://spacevim.org/layers/sudo/
- tags:                 not loaded          https://spacevim.org/layers/tags/
- test:                 not loaded          https://spacevim.org/layers/test/
- tmux:                 not loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#screensaver:    not loaded          no exists
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
- vim:                  not loaded          no exists

**Comment by dyno** [comment]
i also use the rainbow plugin and same configuration in init.toml but it works just fine.

**Comment by xylinkun** [comment]
> i also use the rainbow plugin and same configuration in init.toml but it works just fine.

What is your OS? I use Win 10 and gvim, it not works.

**Comment by wsdjeg** [comment]
please load tools layer, and we have https://github.com/junegunn/rainbow_parentheses.vim installed.

**Comment by xylinkun** [comment]
> please load tools layer, and we have https://github.com/junegunn/rainbow_parentheses.vim installed.

I have enable the layer tools, but the rainbow_parentheses.vim doesn't works still.

**Comment by leafonsword** [comment]
> please load tools layer, and we have https://github.com/junegunn/rainbow_parentheses.vim installed.

does rainbow_parentheses enabled default? My spacevim is 1.3, but I couldn't see colorful parentheses ~

**Comment by rudresh-dixit** [comment]
Run `:RainbowLoad` in vim command mode after enabling 
`[[layers]]`
`name = 'tools'`
in init.toml file in `.SpaceVim.d` directory and it should work fine.

**Comment by leftrk** [comment]
in `~/.SpaceVim.d/autoload/myspacevim.vim`

setting like
```
augroup rainbow_example
  autocmd!
  autocmd FileType lisp,clojure,scheme RainbowParentheses
augroup END
```

**Comment by wsdjeg** [comment]
This is because this autocmd group has been overrided in spaceivm's tools layer:

```
  augroup rainbow_lisp
    autocmd!
    autocmd FileType lisp,clojure,scheme,racket,java RainbowParentheses
  augroup END
```

please checkout runtime log via `SPC h L`, make sure your bootstrap function has been loaded, and move your autocmd to bootstrap_after function.

or use another autocmd group name, for example `augroup custom_rainbow`
