### ISSUE TITLE
[SPC h I] Not working

### ISSUE THREAD

**Issue by andersonjoseph** [wsdjeg/SpaceVim#2383]
I'm having problems with the autocompletion, but I can't get Debug info for open the Issue. When I press <kbd>SPC h I</kbd> a new empty tab is opened and there's nothing in my clipboard

## screenshot

![image](https://user-images.githubusercontent.com/22438127/50459467-035a7300-094a-11e9-9041-c18cce9465af.png)

**Comment by wsdjeg** [comment]
do you see any error message? and what is your Vim version.


---

Shidong Wang

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] [SPC h I] Not working (#2383)
发件人："Anderson. J"
收件人：SpaceVim/SpaceVim
抄送：Subscribed


I'm having problems with the autocompletion, but I can't get Debug info for open the Issue. When I press SPC h I a new empty tab is opened and there's nothing in my clipboard

screenshot

[image]<https://user-images.githubusercontent.com/22438127/50459467-035a7300-094a-11e9-9041-c18cce9465af.png>

―

**Comment by andersonjoseph** [comment]
Vim 8.1 (Windows 7)
I don't see any error message. But when I execute ```:messages``` I see: ```Vim(let): E684: list index out of range: 1```

**Comment by wsdjeg** [comment]
I also use Windows and vim8, but I can not reproduce it. is your spacevim up to date?


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] [SPC h I] Not working (#2383)
发件人："Anderson. J"
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Comment


Vim 8.1 (Windows 7)
I don't see any error message. But when I execute :messages I see: Vim(let): E684: list index out of range: 1

―

**Comment by andersonjoseph** [comment]
Yeah, I've just downloaded it yesterday, I'm 'Already up-to-date' from this repo :confused:

**Comment by wsdjeg** [comment]
strange, I will test it in again.


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] [SPC h I] Not working (#2383)
发件人："Anderson. J"
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Comment


Yeah, I've just downloaded it yesterday, I'm 'Already up-to-date' from this repo 😕

**Comment by wsdjeg** [comment]
I can not reproduce it.

**Comment by xylinkun** [comment]
[SPC h I]  not working on my computer too. Windows 10 and gvim. what I get is only a blank issue_report.md file opened in a new buffer. And I cannot see any error messages.
