### ISSUE TITLE
autocomplete layer interferes with coc.vim (coc-java) autocompletion for Java.

### ISSUE THREAD

**Issue by kabasakalis** [wsdjeg/SpaceVim#2385]
The  autocomplete layer of Spacevim is blocking LSP autocompletion with `coc.vim` plugin, and specifically  with `coc-java` extension for Java.
The layer has to be  disabled it in init.toml for LSP autocompletion to work.
```
[[layers]]
name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
  enable = false
```

**Comment by wsdjeg** [comment]
If you are using coc, I think you do not need lsp layer, as coc support lsp feature.

________________________________
wsdjeg@outlook.com

**Comment by kabasakalis** [comment]
I managed to solve this by disabling autocomplete layer but maybe I must disable `lang#java` layer.
What is the syntax for this? Something like
```
[[layers]]
  name = 'lang#java'
  enable = false
```

**Comment by wsdjeg** [comment]
Yeah, if you want to diable a layer you can use enable = flase

________________________________
wsdjeg@outlook.com
