### ISSUE TITLE
bépo layout in home row

### ISSUE THREAD

**Issue by thooams** [wsdjeg/SpaceVim#2389]
I'm bépo user, how did you integrate the support of the bépo in spacevim. 
I don't find an explanation about bepo in your source code.
https://github.com/SpaceVim/SpaceVim/blob/df4810fa80610aec247d45322d9923e9a65ee8c8/docs/documentation.md#L123

Thanks

**Comment by YoEight** [comment]
Any news on this? I'm in the same situation as @thooams and can't find any documentation on the BEPO subject.

**Comment by YoEight** [comment]
I got `hjkl` mapped to `ctsr` like this for example (I used `bootstrap_before` as mentioned in the doc).
```
    noremap c h
    noremap r l
    noremap t j
    noremap s k
```

Everything works except when I pressed `t` (equiv. of `j`) for going down, `nvim` doesn't do a regular down, and frankly, I don't know what kind of movement it does in this case.

I looked into [default.vim] so see if I can find the offending SpaceVim keybinding but have failed so far.

Thanks for your help.

[default.vim]: https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/default.vim

**Comment by cljoly** [comment]
Looks like BEPO support was first announced in 41e49e56 by @wsdjeg, but I couldn’t find how to use it from there… How can I enable BEPO support ?

**Comment by wsdjeg** [comment]
hi, I just searching the github, and found two plugin for this feature:

- https://github.com/Ergodis/vim-bepo
- https://github.com/michamos/vim-bepo

can you have a try with this two plugins via `custom_plugins` section in spacevim toml file.

**Comment by wsdjeg** [comment]
> Everything works except when I pressed t (equiv. of j) for going down, 

It is overried by clever-f
