### ISSUE TITLE
Use runner to run file which is not in current window

### ISSUE THREAD

**Issue by todorovski-m** [wsdjeg/SpaceVim#2398]
It would be nice to modify runner plugin so that it can run files other than the current file.

For example, in Python it is a common practice to have a file say `one.py` which imports some code from file `two.py`. In such situations one may edit file `two.py` and would like to run the code from `one.py` in order to test the code he has written in `two.py` (which is in the current window).

In this case I now run `one.py`, while editing `two.py` using the command `:!python one.py`. It will be much more convenient to run `one.py` with the runner if there is a possibility to define a master file, which always will be run with `SPC l r`.

**Comment by todorovski-m** [comment]
Another possibility is to write a function as follows
```
function RunMaster()
  :b one.py
  :call SpaceVim#plugins#runner#open()
  :b two.py
endfunction
```
or in a more general form
```
let master_file = "~/Desktop/one.py"

function RunMaster(file)
  let current_file = expand('%:t')
  :exe ':b ' . a:file
  :call SpaceVim#plugins#runner#open()
  :exe ':b ' . current_file
endfunction
```
and make a call to the function `:call RunMaster(master_file)`

In order to make successful run even if master file is not open we have to modify the function as follows
```
let master_file = "~/Desktop/one.py"

function RunMaster(file)
  let current_file = expand('%:t')
  if bufwinnr(a:file) < 0
    :exe 'edit ' . a:file
  endif
  :exe ':b ' . a:file
  :call SpaceVim#plugins#runner#open()
  :exe ':b ' . current_file
endfunction
```

**Comment by wsdjeg** [comment]
please check https://github.com/SpaceVim/SpaceVim/pull/2397


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Use runner to run file which is not in current window (#2398)
发件人：todorovski-m
收件人：SpaceVim/SpaceVim
抄送：Subscribed


Another possibility is to write a function as follows

function RunMaster()
  :b one.py
  :call SpaceVim#plugins#runner#open()
  :b two.py
endfunction


―

**Comment by wsdjeg** [comment]
@todorovski-m I just want to add follow feature:

- Run code file of current active Text Editor

In language layer, we have register default command for each language, key binding is `SPC l r`, for python, it is:

```vim
  " note, the first argument is filetype, and the second argument is command, we will try
  " to run printf(a:runner, bufname('%'))
  call SpaceVim#plugins#runner#reg_runner('lua', 'lua %s')
```

- Run code file through context menu of file explorer

as I know gvim support open file from file explorer, and I will try to find how to use that func.

- Run selected code snippet in Text Editor
- Run code per Shebang
- Run custom command

This has been done in #2397, runner's public api support using argv.

- Stop code running

I will add an func to stop the code runner job.

- View output in Output Window

this has been done.

- Set default language to run

I will create a fuzzy filetype source(maybe denite and unite) for this feature.

- Select language to run

same as above

- Support REPL by running code in Integrated Terminal

SpaceVim provide a default repl plugin, and I will add some document.

**Comment by wsdjeg** [comment]
- Run code file through context menu of file explorer

![select_file_to_run](https://user-images.githubusercontent.com/13142418/50556363-015e2e80-0d13-11e9-9a96-cea25ee3f444.gif)
