### ISSUE TITLE
[website] Markdown tables not rendered correctly

### ISSUE THREAD

**Issue by kikito** [wsdjeg/SpaceVim#24]
(The website project has no issue tracker)

The markdown tables used to list several things in the website are not being rendered as html tables on the website:

![screen shot 2017-01-04 at 11 45 57](https://cloud.githubusercontent.com/assets/63131/21640043/89e6c0c8-d273-11e6-9b0a-90f12775deae.png)

**Comment by wsdjeg** [comment]
Should be fixed, thanks for feedback, and thanks for @benjaminjosephw's quick fix.
