### ISSUE TITLE
disable window only, but keep line with warning

### ISSUE THREAD

**Issue by terroo** [wsdjeg/SpaceVim#2403]
In what file can I disable the error window, but keep the line reporting the error?

Example: 

![](https://i.redd.it/vgi23a6h2u721.png)

**Comment by wsdjeg** [comment]
in current version you only can use bootstrap function. and add

let g:neomake_open_list = 0

But I think I should add an layer option for this feature. after that option has been added. you can load checkers layer via

[[layers]]
name = "checkers"
open-list = 0


---

Shidong Wang

-------- 原始邮件 --------
主题：[SpaceVim/SpaceVim] disable window only, but keep line with warning (#2403)
发件人：Marcos Oliveira
收件人：SpaceVim/SpaceVim
抄送：Subscribed


In what file can I disable the error window, but keep the line reporting the error?

Example:

[https://camo.githubusercontent.com/b478d17e10430e6c530cd9c8fd145f504ca168a0/68747470733a2f2f692e726564642e69742f766769323361366832753732312e706e67]<https://camo.githubusercontent.com/b478d17e10430e6c530cd9c8fd145f504ca168a0/68747470733a2f2f692e726564642e69742f766769323361366832753732312e706e67>

―

**Comment by terroo** [comment]
thank you very much for the information, I will close this issue
