### ISSUE TITLE
Why this statement has error?

### ISSUE THREAD

**Issue by leafonsword** [wsdjeg/SpaceVim#2404]
While editing my code,  spacevim shows this statement has a syntax error:
<img width="604" alt="default" src="https://user-images.githubusercontent.com/1754580/50584114-5f704a80-0ea8-11e9-9e85-55ace48c51fc.png">
but this statement is right, and runs ok in Python3~

**Comment by wsdjeg** [comment]
You have Python2 in your path?

**Comment by leafonsword** [comment]
@wsdjeg yes，python2 is os's default python version, but I installed a python3 in an extra dir,;
system's python cmd is python2
system's python2 cmd is python2
system's python3 cmd is python3
how could I solve this?

**Comment by wsdjeg** [comment]
you need to use bootstrap function, and It is configuration question of neomake. in SpaceVim we use neomake as default syntax lint, you can disable python maker for python file. Just readding `:h neomake-faq` and the question 6.2.
