### ISSUE TITLE
Tried to read every document, how do you make the width size of VimFiler larger

### ISSUE THREAD

**Issue by gcstang** [wsdjeg/SpaceVim#241]
## Environment Information
- OS: MAC
- vim version: 8.0
- neovim version: 0.1.7

Just need to be pointed to some documentation, if it exists.

**Comment by wsdjeg** [comment]
Updated, please read `:h g:spacevim_sidebar_width`, and you can add `let g:spacevim_sidebar_width = 45` to`~/.SpaceVim.d/init.vim` to set the value of width of sidebar of spacevim.

**Comment by gcstang** [comment]
I tried that command and there is no difference in size of the right pane, I even tried it up to 200 no difference.
I also opened vim and used the help ":h g:spacevim_sidebar_width" but it says "E149: Sorry, no help for g:spacevim_sidebar_width"

**Comment by wsdjeg** [comment]
Do you update SpaceVim?

**Comment by gcstang** [comment]
Just installed it yesterday so it should be up to date.

Is there something I should run to show what versions you may want to see?

**Comment by gcstang** [comment]
When I run "vim" I see

version : 0.1.0-dev   by : spacevim.org

**Comment by wsdjeg** [comment]
please run `git pull` in `~/.SpaceVim`, I update it about 15 mins ago.

**Comment by gcstang** [comment]
updated, help works now but still no difference in size on the right even with a setting of 200.

**Comment by wsdjeg** [comment]
where do you add this setting?

**Comment by gcstang** [comment]
`" execute 'source' fnamemodify(expand('<sfile>'), ':h').'/config/main.vim'

" set the options of SpaceVim
let g:spacevim_colorscheme = 'solarized'
let g:spacevim_sidebar_width = 200

" setting layers, load 'lang#java' layer.
call SpaceVim#layers#load('lang#java')

" add custom plugins.
let g:spacevim_custom_plugins = [
 \ ['plasticboy/vim-markdown', {'on_ft' : 'markdown'}],
 \ ['wsdjeg/GitHub.vim'],
 \ ]

 " custom mappings:
 nnoremap <c-l> :Ydc<cr>`

**Comment by wsdjeg** [comment]
please read `:h SpaceVim-config` again.

**Comment by gcstang** [comment]
got it!  Thank you.

needed to create 
.SpaceVim.d/init.vim

**Comment by wsdjeg** [comment]
Yeah, you can create it in HOME, or the root of your project.

**Comment by gcstang** [comment]
yeah used home i.e. ~

commented out all the other settings I had as well, found it on a site somewhere.

What are the settings you use for the Java IDE in your blog post, wasn't clear to me how you set up your init.vim for that.

**Comment by wsdjeg** [comment]
you can checkout my DotFiles repo, there is a SpaceVim.d directory in it.

**Comment by gcstang** [comment]
thank you

**Comment by cebaa** [comment]
@wsdjeg Is there a way to change the value at runtime? I tried `:let g:spacevim_sidebar_width = 50` and I see it set to that value, but the sidebar is not picking the new value.

Also, after I resize with <kbd>50</kbd><kbd>ctrl+w</kbd><kbd>|</kbd> and then switch between the other window and back to file tree (i.e. <kbd>tab</kbd> twice), it reverts to the default value - any way to make it not auto-resize back?

nvim v0.3.8 if that matters.

**Comment by wsdjeg** [comment]
no as I know, you can request feature in defx repo.发自我的华为手机
