### ISSUE TITLE
Standard macro key (q) is remapped

### ISSUE THREAD

**Issue by camdencheek** [wsdjeg/SpaceVim#242]
The macro key "q" should work as it does in standard vim, triggering a the recording of a macro. Currently it is remapped to :<C-U>call zvim#util#SmartClose()<CR>
Changing basic keymappings of vim is unexpected for the default options of a distribution.

## Environment Information
- OS: Linux
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)

Start vim
Attempt to record a macro by pressing 'q' in normal mode, nothing happens
":map q" outputs :<C-U>call zvim#util#SmartClose()<CR>

**Comment by wsdjeg** [comment]
Same as #217
