### ISSUE TITLE
Plugins don't load. Color scheme doesn't change.

### ISSUE THREAD

**Issue by ChrisBFusion** [wsdjeg/SpaceVim#245]
## Expected behavior, english is recommend
Some of the changes I make in my init.vim file don't seem to work. Mainly the color scheme doesn't change from the default and that custom plugins don't load (as verified by \<leader\>lp and by checking the contents of ~/.cache directory). The mouse and vimfiler configuration lines do work.

## Environment Information
- OS: Mac OS 10.12.3
- vim version:
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)

1. Add the following to ~/.config/nvim/init.vim
```execute 'source' fnamemodify(expand('<sfile>'), ':h').'/config/main.vim'

" set the options of SpaceVim
set mouse=a

let g:spacevim_colorscheme = 'solarized'


" setting layers, load 'lang#javascript' layer.
call SpaceVim#layers#load('lang#javascript')

" add custom plugins.
let g:spacevim_custom_plugins = [
 \ ['tpope/vim-obsession'],
 \ ['dhruvasagar/vim-prosession'],
 \ ['eugen0329/vim-esearch', {'on_cmd' : 'esearch'}],
 \ ]

" custom mappings:
 
" Shougo/vimfiler.vim
let g:vimfiler_tree_opened_icon = '‚ñæ'
let g:vimfiler_tree_closed_icon = '‚ñ∏'

" eugen0329/vim-esearch
let g:esearch = {
  \ 'adapter':    'ag',
  \ 'backend':    'nvim',
  \ 'out':        'win',
  \ 'batch_size': 1000,
  \ 'use':        ['visual', 'hlsearch', 'last'],
  \}
```

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
:message (empty)
:echo SpaceVim#logger#### SpaceVim Options :

```viml
g:spacevim_version = '0.1.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'solarized'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['tpope/vim-obsession'], ['dhruvasagar/vim-prosession'], ['eugen0329/vim-esearch', {'on_cmd': 'esearch'}]]
g:spacevim_hiddenfileinfo = 1
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store'
g:spacevim_use_colorscheme = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_debug = 0
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'unite', 'github', 'denite
', 'ctrlp', 'autocomplete', 'nvim', 'osx', 'colorscheme', 'lang#javascript']
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/chris/.cache/vimfiles/'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_warning_symbol = '⚠'
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 0
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_max_column = 120
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file /Users/chris/.SpaceVim/.SpaceVim.log does not exists, only log for current process will be shown!
````

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
Read the documents please, SpaceVim's config file is not in .cache directory.
EDIT:
not in `~/.config/`.

**Comment by wsdjeg** [comment]
It is ~/. Spacevim.d/init.vim

**Comment by ChrisBFusion** [comment]
I believe there is a misunderstanding. I never said it was in the .cache directory. I said it was in ~/.config/nvim/init.vim which is symlinked to ~/.SpaceVim/. This is exactly how the install script set everything up. Note that the install script did not install init.vim in a directory called ~/. Spacevim.d/.

Also, if it were in the wrong location, how is it that some entries added to the ~/.SpaceVim/init.vim file take effect?

**Comment by wsdjeg** [comment]
> Note that the install script did not install init.vim in a directory called ~/. Spacevim.d/.

you should create `~/.SpaceVim.d/` yourself, and create a init.vim in it, it is your custom config file. you should not edit anything in `~/.SpaceVim/` and its symlinks.
