### ISSUE TITLE
希望使用  fugitive 代替 gina 作为 git layer ！ 用 nerdtree 代替  vimfiler，作为文件管理的唯一配置

### ISSUE THREAD

**Issue by Double1996** [wsdjeg/SpaceVim#2455]
- fugitive 功能更加强大，而且 每天都在更新
- gina 已经处于2年没有更新的状态
- git layer 很多功能缺失, 没有 merge ，checkout 等等，希望开发者能够完善。。

--- 
- 以及使用 nerdtree 作为默认文件管理树，vimfiler 也是相同的问题，运行速度慢，不更新。 虽然可以很方便的自己替换插件，但是 应该为普通用户提供 最好的 layer 设定。
- 不清楚开发者选择插件的时候考虑的角度是什么？ 个人认为 速度> 功能 >  star 数

---
强烈建议 用 nerdtree 代替  vimfiler。 完全没有必要维护 两种不同的文件管理器。 而且代码里面有根据文件管理 选择加载插件的方式！！！！

![](http://ww1.sinaimg.cn/large/005FiKNpgy1fz2wmgvxsdj311g05xq4f.jpg)

这样导致选择 nerdtree 作为插件的情况下， debug layer 是失效的， 因为 debug 插件必须依赖于 Shougo/vimproc.vim。

**Comment by wsdjeg** [comment]
Thanks, but english only on github issue.

**Comment by Double1996** [comment]
请问你有这方面的计划吗？

**Comment by wsdjeg** [comment]
@Double1996 english only in github issue, the repo watchers will get email when user comment. also see #2563
