### ISSUE TITLE
Could you please add amperser/proselint as new layer of SpaceVim?

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2459]
This may potentially attract foreign users to SpaceVim. Or any other linter is OK.

**Comment by wsdjeg** [comment]
What is proselint and amperser? if it is lint, I think neomake should support it.

**Comment by xylinkun** [comment]
https://github.com/amperser/proselint

**Comment by wsdjeg** [comment]
I think, it is supported by neomake or ale.
