### ISSUE TITLE
Separated FlyGrep starts with error message

### ISSUE THREAD

**Issue by unclechu** [wsdjeg/SpaceVim#2463]
Related to https://github.com/SpaceVim/SpaceVim/issues/2448
Commit: https://github.com/wsdjeg/FlyGrep.vim/commit/f314f7a9289da8a7be2f5052a85ed8264ef5d85f

It works but when I call `:FlyGrep` I get this error message first time (second call is okay):
![screenshot from 2019-01-11 02-36-24](https://user-images.githubusercontent.com/799353/51034935-70604080-15b9-11e9-8ddf-99db2128b1b4.png)

**Comment by wsdjeg** [comment]
fixed
