### ISSUE TITLE
The code completion select the first word by default

### ISSUE THREAD

**Issue by 0xff91** [wsdjeg/SpaceVim#247]
## Environment Information
- OS: ubuntu
- vim version: 8.0
- neovim version: no

## The reproduce ways from Vim starting (Required!)
when i input a word,  like this, i input 'mod', the code completion engine will show the completion word like mode, models, modern and so on, but it selected the first word 'mode' by default and when i click the button 'tab', it will select the second word 'models'. sure, i can not select the first word when i first click the button 'tab'  , i must tab tab tab  a round to back the first word. how to solve ?? tku!!

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
echo SpaceVim#logger#viewLog()

**Comment by wsdjeg** [comment]
Ok, I found it, it is due to your vim has no lua support, so complcache is the default complete engin, I will try to fix it.
