### ISSUE TITLE
Missing keybidings for location list

### ISSUE THREAD

**Issue by chenlijun99** [wsdjeg/SpaceVim#2474]
## Expected behavior, english is required

We already have quickfix movements keybindings, but no one for location list.
Is there any rationale behind this?

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
`SPC e n/N` is quickfix + location list key bindings, if quickfix is empty, `SPC e n` will jump to next position of location list.

**Comment by chenlijun99** [comment]
Uh, I didn't see it. But it's only available if the `checkers` layer is enabled. 
Since I'm using language server, I don't want the clutter that a second checker might introduce.

How should we handle the feature overlap between the `checkers` layer and the `lsp` layer?

**Comment by wsdjeg** [comment]
hmm, I will look into it. BTW I do not like the idea of lsp, one plugin should do one thing, and do it well. the lsp layer can not provide all the feature inplemented in neomake or ale.

**Comment by chenlijun99** [comment]
Yeah, everyone has his own opinion about the granularity that the "each module should do one thing, and do it well" should have.
Objectively, with the birth of LSP I've seen way more and better smart language features for plain editors like Vim or Emacs.

**Comment by wsdjeg** [comment]
so, this issue is about how to handle error list when checker layer is disabled and lsp layer is enabled?

**Comment by stfl** [comment]
Couldn't this just be <kbd>\<leader> l ...</kbd>
Similar to <kbd>\<leader> q ...</kbd> For quickfix? 
For those who are familiar with vim having this direct control as a default option is nice.
I was looking for this a couple of times expecting it to be there and then remembered that it was controlled through [spc] e

**Comment by wsdjeg** [comment]
in spacevim, the key binding `SPC e n` and `SPC e p/N` will try to use location list first. if there is no location list, it try to use quickfix list. so I think if you want to use location list, you can use `SPC e n` and `SPC e N/p`.

**Comment by chenlijun99** [comment]
It seems that it's pretty hard to have an uniform error handling strategy for all language server client plugins. E.g. AFAICT coc.nvim is providing the error in a custom implemented list.

**Comment by wsdjeg** [comment]
I will only add location list key binding for  lsp layer, and to handled error from language server, it is work of lsp client. I am waitting for neovim's build-in lsp client, or you can have look at my pr about it.

https://github.com/SpaceVim/SpaceVim/pull/2627

**Comment by chenlijun99** [comment]
I'm looking forward for that too.
