### ISSUE TITLE
The text users searched by "*, #, / or ?" in file tree window should not be highlitghted.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2476]
When user search some text in current buffer. The text in file tree will be highlighted too. In my opinion, the text in file tree window or any others windows should not be highlighted.

**Comment by wsdjeg** [comment]
This is feature of vim it self, and can not be fixed.

**Comment by wsdjeg** [comment]
If I have time, I will implement this feature, BTW pr is welcome.
