### ISSUE TITLE
init.toml use utf-8 as default encoding

### ISSUE THREAD

**Issue by zydxhs** [wsdjeg/SpaceVim#2478]
## Expected behavior, english is required
The configuration read failed after the non-english character in the Init.toml file. For example, when guifont is set to Chinese fonts, the font settings do not take effect.

init.toml requires the use of utf-8 file encoding with BOM.

## The reproduce ways from Vim starting (Required!)
1. delete all spacevim's file and configure, include .SpaceVim and .SpaceVim.d and .cache directory.
2. Install Spacevim with Install.cmd.
3. Start Spacevim once to generate init.toml.
4. View the encoding of init.toml file, it's not utf-8 encoding.
   Or, by executing the "set guifont" command in Vim, you can see that the value of Guifont is garbled.

**Comment by wsdjeg** [comment]
I also using win 7, and I can not reproduce it, so how did you check the encoding of that file?

**Comment by zydxhs** [comment]
Open the init.toml file using the EmEditor, and it's file encoding is displayed in the status bar.
My OS is win7 x64 Chinese.

**Comment by zydxhs** [comment]
I found the reason.
The default configuration file generated, is utf-8 without BOM, some editors may recognized as GB312.
So, please change it's file encoding from utf-8 to utf-8 with BOM.

**Comment by wsdjeg** [comment]
I can not reproduce it, PR is welcome.
