### ISSUE TITLE
使用gita执行:Gita status报错

### ISSUE THREAD

**Issue by lcg635** [wsdjeg/SpaceVim#248]
错误信息如下

![538b953f-4ef0-465b-901a-028f63439c4e](https://cloud.githubusercontent.com/assets/1639178/23014162/d2a7d862-f468-11e6-848e-c64d38ceb788.png)

**Comment by wsdjeg** [comment]
Your vim or neovim is too old.
```
v:t_string | neovim: +nightly | vim: +v7.4.2071
```
