### ISSUE TITLE
rlang layer configuration doesn't act like milestone guides

### ISSUE THREAD

**Issue by kayfay** [wsdjeg/SpaceVim#2482]
## Expected behavior, english is required
I'm interested in using the R layer but I'm not sure how to configure it accordingly to the guides posted under its addition during the 2017-2018 milestone.

## The reproduce ways from Vim starting (Required!)
View the guides and notice that autocompletion is not enabled, in terminal shell is not functional, also I'm not sure how to configure the bootstrap options.

I believe these options would enable autocompletion
`cat ~/.SpaceVim.d/autoload/myspacevim.vim
# https://www.reddit.com/r/vim/comments/93xr5g/autocomplete_omnicomplete_for_gnu_r/
# https://spacevim.org/layers/lang/python/
 
 
func! myspacevim#before() abort
    let g:R_in_buffer = 1
    let g:maplocalleader = ','
    let g:R_show_args = 1         " show the arguments for functions with autocompletion
    let g:R_args_in_stline = 0    " do not show arguments in statusline
    let g:R_in_buffer = 0         " I want R in an external terminal, because I use I3
    let g:R_assign = 0            " do not convert _ into <-, annoying!
    let g:R_insert_mode_cmds = 1  " allow R commands in insert mode
    let g:R_term_cmd = 'st -n R'  " command to execute R in my terminal , with window name R
    let g:R_clear_line = 0        " do not clear line before executing a command, sadly does not work with st
    let g:R_args = ['--no-save']  " call R with the --no-save option
    autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif     " exit R when you exit the vim
endf
 
 
func! myspacevim#after() abort
endf`

would love to help! thanks wang

**Comment by kayfay** [comment]
Update



cat ~/.SpaceVim.d/autoload/myspacevim.vim
" https://www.reddit.com/r/vim/comments/93xr5g/autocomplete_omnicomplete_for_gnu_r/
" https://spacevim.org/layers/lang/python/


func! myspacevim#before() abort
endf


func! myspacevim#after() abort
    let g:R_in_buffer = 1
    let g:maplocalleader = ','
    let g:R_show_args = 1         " show the arguments for functions with autocompletion
    let g:R_args_in_stline = 0    " do not show arguments in statusline
    let g:R_in_buffer = 0         " I want R in an external terminal, because I use I3
    let g:R_assign = 0            " do not convert _ into <-, annoying!
    let g:R_insert_mode_cmds = 1  " allow R commands in insert mode
    let g:R_term_cmd = 'st -n R'  " command to execute R in my terminal , with window name R
    let g:R_clear_line = 0        " do not clear line before executing a command, sadly does not work with st
    let g:R_args = ['--no-save']  " call R with the --no-save option
    autocmd VimLeave * if exists("g:SendCmdToR") && string(g:SendCmdToR) != "function('SendCmdToR_fake')" | call RQuit("nosave") | endif     " exit R when you exit the vim

endf

**Comment by wsdjeg** [comment]
I have forked the nvim-R, and I will rewrite it base on SpaceVim feature. If you family with R language, I hope you can also provide some ideas.

why do not use nvim-R? the ui is not beautiful, the plugin do not use autoload feature. there are some duplicate feature of spacevim.

**Comment by kayfay** [comment]
I am not sure that I understand you, I thought that these were nvim-R configuration options and added them to a bootstrap function in order to set them

**Comment by kayfay** [comment]
using \rh in a new vertical split buffer
using \rf in a terminal in a new horizontal split buffer
are two useful options
