### ISSUE TITLE
Feature Request: Generate a feed for Dash (and Zeal)

### ISSUE THREAD

**Issue by lewalkingdad** [wsdjeg/SpaceVim#2488]
## Feature Request

That would be great if we could access the documentation when offline, ideally using a doc viewer such as Dash (OSX) (That will make it then available for Zeal Linux & Windows).

There is a guide to generate a docset :
Source :https://kapeli.com/docsets#dashDocset

I hope I'll find time to generate the docset and submit a PR (if you think it's relevant)

**Comment by wsdjeg** [comment]
SpaceVim website is generated via jekyll, I think you can use local website.

just run `bundle install` and `bundle exec jekyll server` in docs directory.

**Comment by kifirkin** [comment]
@wsdjeg Dash is not only for OSX, but also works on iOS and there is no way to run `jekyll` there
