### ISSUE TITLE
How the set eht syntastic?

### ISSUE THREAD

**Issue by BlasphemyAngels** [wsdjeg/SpaceVim#250]
## Expected behavior, english is recommend
I want to disable some syntax warnning. So I config the main.vim follow:
`let g:syntastic_python_checkers=['pylint']`
`let g:syntastic_python_pylint_args='--disable=E501,C0301,R0903,C0103,locally-disabled,invalid-name'`
but it didn't work. How to do it?
## Environment Information
- OS: Ubuntu
- vim version: 8.0

**Comment by wsdjeg** [comment]
`:h g:spacevim_enable_neomake`, you can add `let g:spacevim_enable_neomake = 0` to your custom config file.

**Comment by BlasphemyAngels** [comment]
It didn't work too. it got a error `E149: Sorry, no help for g:spacevim_enable_neomake` when use the command `:h g:spacevim_enable_neomake`.

**Comment by wsdjeg** [comment]
How about add `let g:spacevim_enable_neomake = 0` to `~/.SpaceVim.d/init.vim`?

**Comment by BlasphemyAngels** [comment]
It didn't work.

**Comment by wsdjeg** [comment]
`call dein#install()` to install the plugin.

**Comment by BlasphemyAngels** [comment]
`[dein] You may have used the wrong plugin name, or all of the plugins are already installed.`
Got this.

**Comment by wsdjeg** [comment]
please check out ~/.cache/vimfiles/repos/github.com/wsdjeg, if there is syntastic

**Comment by BlasphemyAngels** [comment]
It doesn't have.

**Comment by BlasphemyAngels** [comment]
` ~/.SpaceVim/config/plugins` In this dir, I find a file: `syntastic.vim`. But it doesn't work after I config it.

**Comment by wsdjeg** [comment]
It works well for me,
![2017-02-16-19 56 39](https://cloud.githubusercontent.com/assets/13142418/23020490/4eb81430-f482-11e6-9367-8b2fd59a239d.png)

you should not edit anything in `~/.SpaceVim`, custom config file is `~/.SpaceVim.d/init.vim`

**Comment by BlasphemyAngels** [comment]
`~/.SpaceVim.d` The file doesn't exist in my computer！

**Comment by BlasphemyAngels** [comment]
`~/.SpaceVim.d/` The dir doesn't exist in my computer.

**Comment by wsdjeg** [comment]
you should create your self. see #245

**Comment by Crushmyr** [comment]
你好，我想禁用一些pylint的错误，请问要设置哪个参数呢？

**Comment by Crushmyr** [comment]
您好，请问怎么才能禁用掉一些pylint的语法错误呢？我看了下neomake的的帮助文档，没有什么收获。。
