### ISSUE TITLE
improve fzf layer with fzf.vim

### ISSUE THREAD

**Issue by SleepyBag** [wsdjeg/SpaceVim#2503]
I noticed that the fzf layer is powered by default fzf vim integration now. However, this integration provides little functions and is hard to use.
In fact, the author of fzf has provided another tool named fzf.vim, which provides many convenient commands. For example, my favorite Bline, which could search any single line in a buffer. It's homepage is here:

https://github.com/junegunn/fzf.vim

I notice that you have done a lot of great jobs in fzf layer. However, some of them have in fact been written by junegunn, such as Colors command for searching colorschemes. I believe that this plugin could relieve you from the pain of developing some new functions ;-)

**Comment by wsdjeg** [comment]
This issue has been discussed when fzf layer is created, I do not want to use fzf.vim

**Comment by wsdjeg** [comment]
see #1502
