### ISSUE TITLE
Feature Request: ability to set the custom leader

### ISSUE THREAD

**Issue by devonkinghorn** [wsdjeg/SpaceVim#2504]
Right now the custom leader is always SPC.

Last year I gave spacemacs a month long try and preferred changing the spacemacs leader from SPC to ','. It reduced the number of errors I made.

I would appreciate the ability to set the custom leader to any key.

**Comment by wsdjeg** [comment]
This feature looks nice, and maybe we can add new spacevim option custom_leader?

________________________________
wsdjeg@outlook.com

**Comment by devonkinghorn** [comment]
I think the easier it is to customize spacevim, the faster it will catch on

**Comment by franzejr** [comment]
Any progress on this ?

**Comment by wsdjeg** [comment]
currently, no.
