### ISSUE TITLE
Add 'tpope/vim-speeddating' plugin

### ISSUE THREAD

**Issue by AlexLov** [wsdjeg/SpaceVim#2516]
This plugin is quite useful to work with dates.

**Comment by wsdjeg** [comment]
I do not want to increase the number of SpaceVim's default plugins, so which layer do you think this plugin should be placed, and or a new layer?

**Comment by AlexLov** [comment]
I thought about `edit` layer as this plugin seems related to vim-surround and vim-repeat and quite simple, but if you strongly against adding new plugins to default layers then `tools` might be a good place for it.

**Comment by wsdjeg** [comment]
I recommand to use custom_plugins for this plugin.
