### ISSUE TITLE
Unable to write parentheses in SpaceVim

### ISSUE THREAD

**Issue by LiZhiHao97** [wsdjeg/SpaceVim#2522]
After I downloaded SpaceVim, vim will get stuck when writing the parentheses, and the other symbols won't.
System: MAC OS

**Comment by TheNorthEestern** [comment]
I'm also encountering this issue.

**Comment by LiZhiHao97** [comment]
> I'm also encountering this issue.
我发生这种情况好像是因为插件没有正确安装，当插件安装完后就解决了。

**Comment by LiZhiHao97** [comment]
> I'm also encountering this issue.

This happens to me because the plugin is not installed correctly and is resolved when the plugin is installed.
