### ISSUE TITLE
nvim config is messed up after  uninstalling spacevim :(

### ISSUE THREAD

**Issue by 4vrel** [wsdjeg/SpaceVim#2524]
nvim verstion: 0.1.7
os : debian-9

I have installed Spacevim and after uninstalling it each time I open nvim I got the following error message:
```
Error detected while processing function spaceneovim#bootstrap[6]..<SNR>2_load_spaceneovim_functionality[34]..spaceneovim#install_enabled_plugins:
line    2:
E117: Unknown function: plug#begin
Press ENTER or type command to continue

```
## Expected behavior, english is required
No error message related to spacevim after uninstalling it

## The reproduce ways from Vim starting (Required!)
install SpaceVim with install script.
First I uninstalled SpaceVim by 
`rm -rf .config/nvim && mv .config/nvim_back .config.nvim`
and then 
`rm  .vim && mv .vim_back .vim`
Still got the error message !
Finally I did : 
`curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall`
and : 
`:UpdateRemotePlugins`
But I still got the error message :(

I have to say, I think spacevim is a great initiative and cheers for you to make this project exist, but having to debug a program after uninstalling it is pretty annoying :/

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
spaceneovim and space-vim is not SpaceVim. make sure you are using SpaceVim. the website is spacevim.org

**Comment by 4vrel** [comment]
thanks , sorry for the bad energie
