### ISSUE TITLE
python indent error: the tab always is 4 space.

### ISSUE THREAD

**Issue by riseOfCurse** [wsdjeg/SpaceVim#2530]
Whatever I write for bootstrap_after, the 4 space indent can't be covered.

I've located the problematic upstream plugin：
~/.cache/vimfiles/repos/github.com/Vimjas/vim-python-pep8-indent/indent

**Comment by riseOfCurse** [comment]
Maybe the real issue is not here, but if I add set shiftwidth=2 at the end of file(~/.cache/vimfiles/repos/github.com/Vimjas/vim-python-pep8-indent/indent/python.vim)
the indent of .py files will be changed to 2 space

**Comment by wsdjeg** [comment]
`:h SpaceVim-options-default_indent`
