### ISSUE TITLE
unify conceal feature in SpaceVim

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2531]
1. set conceallevel=0 by default ?

**Comment by kitaev-chen** [comment]
> 1. set conceallevel=0 by default ?

et conceallevel=1 ?
let g:tex_conceal='abdmg'

ref from https://castel.dev/post/lecture-notes-1/

**Comment by wsdjeg** [comment]
we have `SPC t c` key binding for toggle conceal.

**Comment by YihaoJW** [comment]
Is that possible to set TEX Conceal at Default?
