### ISSUE TITLE
install.sh: Fail to download fonts with space in file name w/o any error indications

### ISSUE THREAD

**Issue by Gowee** [wsdjeg/SpaceVim#2532]
As is in the title, in the **install.sh** provided on the Quick Start page, the bash function `download_font` relies on *curl* to downloads font from *raw.github...*:

https://github.com/SpaceVim/SpaceVim/blob/56e39b40e250d1d5e6216d11d10a1b43ba866875/docs/install.sh#L347

. But there are spaces in more than half of the bundled fonts as is listed in `install_font`, such as:

https://github.com/SpaceVim/SpaceVim/blob/56e39b40e250d1d5e6216d11d10a1b43ba866875/docs/install.sh#L359

. *curl* will get nothing other than an *HTTP 400 Bad Request* error with an empty body for all those of fonts with spaces in file name. What's worse, due to the option **-s** set, curl will silently ignore this error and continue. This leads to failing to install more than half of those fonts. I notice that users have been complaining about this issue, see #721, #771, etc (although some of these may be because of forgetting to set terminal font). 

This problem may be fixed by simply renaming those files or replace spaces by `%20` so that *curl* correctly interprets it (I am not sure how to properly escape URL in shell). Besides, to make sure no error is ignored silently, `-fsSL` may be necessary. And `set -u` for *bash* might also help. 

---

Another trivial problem ~~for curiosity~~: why is *SauceCodePro ...* the default GUI font while it is not installed by default?

**Comment by wsdjeg** [comment]
Thanks for you issue, but I have added `"` surround the url, so not need to escape the space, It works well in my linux pc.

I will add the SaucoCodePro link.

**Comment by Gowee** [comment]
@wsdjeg Hi. I also work on Linux and got a contradictory result. Could u plz try to
 `curl -s -o "DejaVu Sans Mono Bold Oblique for Powerline.ttf" "https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/DejaVu Sans Mono Bold Oblique for Powerline.ttf"` and check whether the downloaded file is empty or not?

**Comment by Rom1deTroyes** [comment]
Hello, and thanx for all the work on spacevim (-:

Same escape problem on Debian Stable.

```bash
romain@:~/src/Fonts$ curl  -o "DejaVu Sans Mono Bold Oblique for Powerline.ttf" "https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/DejaVu Sans Mono Bold Oblique for Powerline.ttf"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
romain@:~/src/Fonts$ curl  -o "DejaVu Sans Mono Bold Oblique for Powerline.ttf" "https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/DejaVu%20Sans%20Mono%20Bold%20Oblique%20for%20Powerline.ttf"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  231k  100  231k    0     0  1092k      0 --:--:-- --:--:-- --:--:-- 1096k


romain@:~/src/Fonts$ curl -I "https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/DejaVu Sans Mono Bold Oblique for Powerline.ttf"
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 0

romain@:~/src/Fonts$ curl -I "https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/DejaVu%20Sans%20Mono%20Bold%20Oblique%20for%20Powerline.ttf"
HTTP/1.1 200 OK
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
ETag: [...]
Content-Type: application/octet-stream
Cache-Control: max-age=300
X-Geo-Block-List:
X-GitHub-Request-Id: [...]
Content-Length: 236820
Accept-Ranges: bytes
Date: Thu, 31 Jan 2019 21:56:21 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-cdg12345-CDG
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: [...]
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: [...]
Expires: Thu, 31 Jan 2019 22:01:21 GMT
Source-Age: 0

romain@:~/src/Fonts$ curl --version
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2q zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```
++
    Romain

**Comment by wsdjeg** [comment]
Thanks for all your info. I will try to fix it.

**Comment by cebaa** [comment]
Workaround for now - change this line in the script:

```
url="https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/$1"
```

to

```
url="https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/${1// /%20}"
```

Line 340 in my script.

**Comment by wsdjeg** [comment]
Thanks, PR is welcome!



--
Best regards,
wsdjeg
 
From: cebaa
Date: 2019-09-07 02:41
To: SpaceVim/SpaceVim
CC: Wang Shidong; Mention
Subject: Re: [SpaceVim/SpaceVim] install.sh: Fail to download fonts with space in file name w/o any error indications (#2532)
Workaround for now - change this line in the script:
url="https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/$1"

to
url="https://raw.githubusercontent.com/wsdjeg/DotFiles/master/local/share/fonts/${1// /%20}"

Line 340 in my script.

**Comment by bwasilewski** [comment]
This still is not working for me, seeing 

install_fonts:18: = not found
