### ISSUE TITLE
Some beginner's questions

### ISSUE THREAD

**Issue by mosheavni** [wsdjeg/SpaceVim#2533]
👋🏼 Hi everyone, SpaceVim noob here.
The documentation seems to lack the basics and this is where I'm stuck,
1. Nowhere where it says how to open a new tab
2. The actions to fully close a tab are too long to be used. What I came up with is:
Double click to create a tab, `SPC t t` to open tab manager, go to tab, hit `x`, go to the tab that was deleted (usually with `<leader> 2`, close it with `sq`
I bet there's an easier way
3. Is there a way to search the mappings by the functionality? I'd like to know each plugin's key binding and how to use it.
Thanks. 🙏🏼

**Comment by wsdjeg** [comment]
@Moshem123 

1. how to open a tab, It should same as in origin vim, just use `:tabnew` command, or use tab manager.
2. in tab manager you can use normal `N` or `n` open create named tab, the tab name will be shown on the tabline.
3. `<leader> f SPC` is for searching mapping in SpaceVim .

**Comment by wsdjeg** [comment]
BTW, `SPC w f` is for create new tab.

**Comment by wsdjeg** [comment]
![default](https://user-images.githubusercontent.com/13142418/52057647-85206a80-25a0-11e9-8983-3150efff8c20.png)

**Comment by mosheavni** [comment]
> @Moshem123
> 
> 1. how to open a tab, It should same as in origin vim, just use `:tabnew` command, or use tab manager.
> 2. in tab manager you can use normal `N` or `n` open create named tab, the tab name will be shown on the tabline.
> 3. `<leader> f SPC` is for searching mapping in SpaceVim .

About 3, it's not working, there's no `f` in the leader menu. :(
![screen shot 2019-01-31 at 22 41 25](https://user-images.githubusercontent.com/17252601/52083958-9621a980-25a9-11e9-8804-3dcfa697f6bb.png)

**Comment by wsdjeg** [comment]
You need to load one fuzzy finder layer, SpaceVim has following fuzzy find layers:

- denite: use shougo's denite.nvim
- unite: use unite.vim
- ctrlp: use ctrlp.vim
- fzf: use fzf
- fzy: use fzy

**Comment by mosheavni** [comment]
I installed fzf and still can't find anything in the menu to look for mappings:
![2019-02-06_17-33-13](https://user-images.githubusercontent.com/17252601/52352521-6523f780-2a35-11e9-84a8-e9eb5bf8cbf7.png)

**Comment by wsdjeg** [comment]
This has been done in latest version. the default key bindings is `<Leader> f SPC`
