### ISSUE TITLE
how to change the split window size?

### ISSUE THREAD

**Issue by 0xff91** [wsdjeg/SpaceVim#256]
Hello,  i have some questions as below, i am using arch os and nvim now.
1. When I using the shortcut key 's' + 'v', spaceVim split a new window, but how i can change the new window's size?
2. When I input the character ', ", {, (, [, it can not complete the character's other part? how I can set it?

**Comment by wsdjeg** [comment]
It the the usage of vim, 's'+'o' will make the window to the the only one, if you want to change size, you need type `<c-w>`+`<`  or  `<c-w>`+`>` , you also can use number  ,  `<c-w>`+30 + `<` .

SpaceVim use neosnippet to complete pairs.
