### ISSUE TITLE
conceallevel = 0 does not work

### ISSUE THREAD

**Issue by gagiuntoli** [wsdjeg/SpaceVim#2560]
## Expected behavior
    When I set conceallevel = 0 I expected to see in a latex document what I write (for example $\sigma$ )

## The reproduce ways from Vim starting
    When I open Vim I see what I want but when the cursors is over it and I enter in edit mode I start seeing the unicode 𝜎.

![screenshot from 2019-02-09 10-41-03](https://user-images.githubusercontent.com/25662036/52519135-384f2a80-2c57-11e9-896b-229e3ec4cc0b.png)

![screenshot from 2019-02-09 10-40-33](https://user-images.githubusercontent.com/25662036/52519132-28cfe180-2c57-11e9-9d32-79c35451803e.png)

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/issues/2531

**Comment by gagiuntoli** [comment]
the problem is that it starts with conceallevel = 0  but when I enter in Insert mode it changes to conceallevel = 2
