### ISSUE TITLE
How to configure SpaceVim's log level?

### ISSUE THREAD

**Issue by chenlijun99** [wsdjeg/SpaceVim#2561]
## Expected behavior, english is required
With

```vim
let g:spacevim_debug_level             = 3
```

or

```toml
[options]
    debug_level = 3
```
warnings should be disabled.

## The reproduce ways from Vim starting (Required!)
Set `debug_level` to 3. Do something that causes SpaceVim to log a warn. `debug_level` didn't take effect

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
It is hard to implement this feature, because the logger function is called before loading custom configuration file, just same as python_prog in neovim. maybe we can use environment variable。

**Comment by chenlijun99** [comment]
That would be OK.

Actually I don't need it anymore. I wanted to change the log level because otherwise the `lsp` layer keeps warning on each vim startup that some language server is not executable (I use the same Vim configuration on multiple machines, and not every machine has all lsp servers installed).
The easiest solution is just to install the lsp server to get rid of the warning. Just a matter of minutes.

But it would be still good to leave to the user the possibility to configure the log level.

**Comment by chenlijun99** [comment]
Alternatively, could we source a file at the very beginning of SpaceVim?

Let's say in `SpaceVim/init.vim`

```vim
silent! source "$HOME/SpaceVim.d/SpaceVim_override.vim"
```
Yeah, I admit that it's quite a hack.

**Comment by wsdjeg** [comment]
@free-easy It is a hack, but the code of spacevim repo has been changed, you can not update it via `git pull` etc.

**Comment by chenlijun99** [comment]
Please note that I told to put `SpaceVim_override.vim` in the user's configuration directory `SpaceVim.d`, not in `~/SpaceVim`.
Even if  `SpaceVim_override.vim` is put in `~/SpaceVim`, we can avoid to pollute the SpaceVim repository by adding `SpaceVim_override.vim` to gitignore.

The same approach is valid for #2564, where I suggested to use `coc#config` instead of putting `coc-settings.json` in `~/SpaceVim`. But we could add `coc-settings.json` to `.gitignore`, so as to allow users to put their files.

**Comment by wsdjeg** [comment]
>I wanted to change the log level because otherwise the lsp layer keeps warning on each vim startup that some language server is not executable

what is warnning message, if it is not generated from spacevim, I can not disable it.

**Comment by chenlijun99** [comment]
The warning message comes from

https://github.com/SpaceVim/SpaceVim/blob/7539f3e10d0c1f8a25bbeb08c4b075582cc38105/autoload/SpaceVim/layers/lsp.vim#L117-L121
