### ISSUE TITLE
Possibility to use fugitive as git layer main plugin

### ISSUE THREAD

**Issue by chenlijun99** [wsdjeg/SpaceVim#2563]
AFAICT, fugitive is the best known git plugin. Is there any reason why it isn't used in the git layer?

**Comment by chenlijun99** [comment]
Would you be willing to accept any PR in this regard? Or `fugitive` is just a "No no" for SpaceVim?

**Comment by wsdjeg** [comment]
what is the issue with current implementation, in git layer, we are using gita or gina. if people who do not use git, he may use VersionControl layer.

**Comment by chenlijun99** [comment]
As explained by @Double1996 in #2455, I think that fugitive is better too.
That may be a matter of personal taste, but, just like the other layers supporting different plugins (fuzzy search layer with `fzf`, `denite`, `leaderf`, etc., autocomplete layer with a lot of possible customization for the end user regarding which autocomplete plugin to use, etc, etc.), the git layer should support fugitive, which is arguably the most established git plugin.

**Comment by wsdjeg** [comment]
Ok, will add an option to enable fugitive as default tool in git layer, but the default behavivor will not be changed.

**Comment by chenlijun99** [comment]
Certainly! I agree that the default behavior has to be kept.

Thank you!
