### ISSUE TITLE
What can be done with the new features in vim/neovim?

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2567]
This issue will be used to post the new features merged in neovim/vim, and discussion about what can be done with these new features is welcome. based on https://github.com/neovim/neovim/commit/3ff1228f785705a46a0bd24fb5dc2bf76b6dad68

[commit history page](https://github.com/neovim/neovim/commits/master?after=2816bc8620ca373145842641ce77805f4321b2bc+69)

- `nvim_create_buf` to create a new empty buffer.
-  `pumblend` option for semi-transparent popupmen
- add new Signal event
- Implement popupmenu as a floating grid internally to reduce flicker
- make 'listchars' and 'fillchars' local to window
- patch 8.1.0519 Add `gettagstack()` and `settagstack()`
- api: `nvim_win_close`, close windows by id
- api: `nvim_open_win`, open floating windows
- :terminal events: TermEnter/TermLeave

**Comment by thawk** [comment]
It's very useful to have 'listchars' local to window.
Markdown use two space before line endings to insert a "hard line break".  It's good to show trailing spaces for markdown but not for other files.

**Comment by wsdjeg** [comment]
Yeah, I will add this feature.
