### ISSUE TITLE
Global tags search

### ISSUE THREAD

**Issue by zhaogang92** [wsdjeg/SpaceVim#2568]
Is there any shortcut or existing keybinding for global tags search? I know there are some existing ways for search outline (symbols in the current file), but I didn't find a way to search global tags yet. By that I mean a functionality similar to the `Tags` command in fzf.vim plugin.

**Comment by wsdjeg** [comment]
in current version, no, but I will add this feature, the key binding should be `<Leader> f t` - fuzzy find global tags.
