### ISSUE TITLE
Disable error windows when editing tex files

### ISSUE THREAD

**Issue by zhaogang92** [wsdjeg/SpaceVim#2569]
When editing tex files, there will be two error message windows, as shown below:
![image](https://user-images.githubusercontent.com/1066718/52530931-52c6e980-2cd3-11e9-8b00-97f285ce7508.png)

You can find the tex file here [sample tex](https://gist.github.com/zhaogang92/f23503ff51ccb02fea49e963aaa9157c)

My configuration of spacevim is here: [config](https://gist.github.com/zhaogang92/491363edfd81759867cc207d0e7a4fd7)

In fact the first error message window shows meaningless error messages. Very likely it's generated by a non-latex checker.

Is it possible to integrate these messages into one window? Just like what we have when coding.

Further, is it possible to disable the checker for specific type of files? Because tex files usually give lots of warning message. It would be better if the checker can be disabled. Or only error messages will be shown.

**Comment by ChasingZenith** [comment]
May I ask you how did you solve this problem, I find it really annoying.
