### ISSUE TITLE
Please enable all syntax highlighting

### ISSUE THREAD

**Issue by zydxhs** [wsdjeg/SpaceVim#2585]
## Please enable all syntax highlighting for default

I usually use vim to view files in different programming languages, rather than for programming development.At the same time, I don't want to slow down vim's performance by installing too many plug-ins.

It is recommended that syntax highlighting for all supported file types be enabled by default.

**Comment by wsdjeg** [comment]
Vim has default syntax highlith for different programming languages, you do not need to enable all layer, btw, you can use custom_plugin to add only syntax file for different progrmming languages.

for example https://github.com/sheerun/vim-polyglot but I do not use such wrapped plugin.
