### ISSUE TITLE
languagetool check for grammar and spelling (vim-grammarous)

### ISSUE THREAD

**Issue by aliceinwire** [wsdjeg/SpaceVim#2586]
languagetool check for grammar and spelling [(vim-grammarous)](https://github.com/rhysd/vim-grammarous)

**Comment by freddie-freeloader** [comment]
May I ask why this was closed? :slightly_smiling_face:

**Comment by aliceinwire** [comment]
[[custom_plugins]]
name = 'rhysd/vim-grammarous'
merged = 0
on_cmd = ['GrammarCheck']
