### ISSUE TITLE
Please enable use touchpad in insert mode

### ISSUE THREAD

**Issue by DragonTang** [wsdjeg/SpaceVim#2591]
I have used spacevim for several days, It is much beautiful,but it can not use touchpad and mouse in insert mode,it can be used in normal mode.I think write code is much longer time than edit.If i can't use touchpad or mouse position the cursor in the insert mode,I must write a word and then change it to the normal mode to move cursor, I think it is much trouble.So if it can use mouse in the insert mode,and edit code in the normal mode will be much cool.

**Comment by wsdjeg** [comment]
issue is for bug report and feature request **only**, to ask question plugin use gitter chatting room. BTW, please search key words `touchpat` in issue tracker before open new one, someone maybe asked this question before.

https://github.com/SpaceVim/SpaceVim/issues/2223
