### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by iamkarlson** [wsdjeg/SpaceVim#26]
Is in any script to install at windows 10 ?

**Comment by wsdjeg** [comment]
Sorry I do not use windows, but it should works well in windows. just unzip this repo to `~/dotfiles`.

BTW, PR for windows install script is welcome.

**Comment by onerciller** [comment]
yes I cannot install on windows 8 too.  I'd appreciate it  if you can make install script for windows

**Comment by wsdjeg** [comment]
Install in windows is very simple, just backup your vimfiles in your user directory, then clone this repo as vimfiles. 

here is what do after start a cmd;

![qq 20170108195801](https://cloud.githubusercontent.com/assets/13142418/21749625/92a5e1ea-d5dd-11e6-97ff-048fc29695df.png)

after this command, your SpaceVim has been installed, the first time when you start vim, SpaceVim will auto install all the plugins. then you should wait for it.

after every thing is done, you should be able to use SpaceVim in windows. here is the screenshot I made in win7.
![qq 20170108195336](https://cloud.githubusercontent.com/assets/13142418/21749622/8c246008-d5dd-11e6-8fd4-37c39715069e.png)
![qq 20170108195301](https://cloud.githubusercontent.com/assets/13142418/21749623/8e6d7430-d5dd-11e6-88e9-c25b44307fc2.png)

**Comment by jon-peel** [comment]
Hi, I can't figure out how to do this.

cloning the repo into `vimfiles` is not a problem.
Then I try running `vim`, `neovim`, and `gvim`, but absolutely nothing happens.

**Comment by jon-peel** [comment]
I managed to get this working.
I renamed vimfiles to .vim, and removed the vimrc

**Comment by wsdjeg** [comment]
OK

**Comment by kujifined** [comment]
> Hi, I can't figure out how to do this.
> 
> cloning the repo into `vimfiles` is not a problem.
> Then I try running `vim`, `neovim`, and `gvim`, but absolutely nothing happens.

the same problem, maybe somebody solved it, pls help!

**Comment by blurk** [comment]
### This work for me, may be it will help
**Go to** `C:\Users\%your_username%\AppData\Local\nvim`
**Copy** all the files inside .SpaceVim to it

**Comment by Alberto2K** [comment]
Same issue. Cannot open spacevim.
I used the install.cmd to a directory .spacevim and then tried to run vim, vi, spacevim, and nothing worked.
Also, move the files to another directory as suggestion, also didn't work
I use Windows 10 PRO.

**Comment by KrOstir** [comment]
This has been fixed with PR #4643. The 'install.cmd' should work.
