### ISSUE TITLE
更新后出现E171和E117错误

### ISSUE THREAD

**Issue by michelfei** [wsdjeg/SpaceVim#2600]
更新后出现如图错误，删除.cache内文件后依然跳出错误
![GitHawk Upload by michelfei](https://i.imgur.com/RrxhxYW.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wsdjeg** [comment]
english only, and following the installation step on the websiet or hack-spacevim
