### ISSUE TITLE
SpaceVim note and TODOs manager layer

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#261]
1, manager note
2, async with github repo
3, manager TODOs

**Comment by a-b** [comment]
Sounds like a mix of vimwiki and emacs org-mode to me ;)

**Comment by lymslive** [comment]
https://github.com/lymslive/vnote
I have an idea for note in vim, however this plug is far away from complete though.

**Comment by wsdjeg** [comment]
if vnote is done, please let me know, I will add this plugin to spacevim, and I think english readme it better for all the user around the world, I do not like to write doc in chinese.

**Comment by wsdjeg** [comment]
@lymslive 
first time I have install this plugin I get
```
Error detected while processing function vnote#GetNoteBook[2]..class#notebook#new[2]..40[3]..class#notebook#ctor[2]..49:                               
line    7:                                                                                                                                             
cannot set notebook to directory that not exists: /home/wsdjeg/notebook 
```

I think this should be in readme, or autocreate dir. maybe create dir in user home is not good idea.

**Comment by wsdjeg** [comment]
As vnote only support vim8, I just make the plugin lazy loaded, and we should found out a plugin for old version vim.

**Comment by wsdjeg** [comment]
https://github.com/Dimercel/todo-vim

https://github.com/mivok/vimtodo

https://github.com/baruchel/vim-notebook

https://github.com/Zuckonit/vim-gnote

https://github.com/vim-scripts/notes.vim
https://github.com/xolox/vim-notes
https://github.com/trobrock/evernote.vim

**Comment by lymslive** [comment]
I have use xolox many years before, but only for short time, and not used any more

**Comment by wsdjeg** [comment]
I have tried vnote, it looks nice, but I think still some more word need to be done, I wang to fork it to SpaceVim org.

**Comment by wsdjeg** [comment]
@lymslive We still using vnote for note and todo manager, I hope you can fix old version support. It is easy to change v:ture to a funcref.

for Todo manager, I recommand to use `:Ag Todo`. you will see something like:

![Uploading 2017-03-30-20:55:15.png…]()
