### ISSUE TITLE
Get `<` and `>` default behavior back as operators

### ISSUE THREAD

**Issue by rezende** [wsdjeg/SpaceVim#2616]
Hi, 

I really like to use `<` and `>` as operators, the way it's normal in vim (get back their default behaviors)

(So I can do `<2j` for example - instead in Spacevim I have to do `V2j<`)

So, how is the best way to get their behaviors back?

Or, is there a indent operator in SpaceVim that I don't know about?

Thanks

**Comment by wsdjeg** [comment]
`<2j` looks better. I will try to fix it.

**Comment by rezende** [comment]
Thanks, 
To expand a bit:

Doing `<2j` (indent this line + 2 lines below it) is the default vim/nvim behavior. 

In SpaceVim, `<` has  `<<`'s functionality. So the only way to operate in anything that's not a line is by entering Visual mode.

**Comment by wsdjeg** [comment]
But in normal mode, if I just want to change the indent of current line, I need to presss extra `<` or `>`.

**Comment by rezende** [comment]
Yes, that's what I meant by saying that ```In SpaceVim, `<` has `<<`'s functionality.```

To indent just one line it's totally fine. It's just when trying to indent stuff that's not a line that I have to enter Visual mode.

In summary I just wanted a way to disable SpaceVim changes on `<` and `>`

**Comment by wsdjeg** [comment]
in current version of SpaceVim, you can use bootstrap_after function, in the function, just use `nunmap <` and `nunmap >`

**Comment by rezende** [comment]
That solves it for me. Thanks!
