### ISSUE TITLE
Spacevim Statusline is the greatest!!!

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2622]
### Firstly Spacevim has hands down the greatest status line in all of the vim/neovim universe!
I absolutely love it! It's gorgeous, idk if it's technically as featureful as airline but it feels like it offers more than airline and still some how feels light. I honestly love it so much that I was going to try to replicate it until I got burried in 1500 lines of code and still couldn't quite get it to work like it does in spacevim (I am not well versed in vimscript). Which brings me to my second point....

### Have you guys ever thought of making your omnipotent statusline into it's own plugin? 
I feel like it would make it easier on you guys to add features in the future and it would be beneficial to everyone who likes your statusline (and those who don't know they like it yet) that don't want to use ALL of Spacevim.

**Comment by wsdjeg** [comment]
sorry, I do not plan to detach statusline plugin, as it is based on th core code of spacevim, and is changed all the time, even in a simple PR. I do not have mach time to manager two repo with duplicate code. If you want to use satusline plugin, I recommand to use:

- airline: awesome but slow
- lightline: simple, fast
- or even the statusline plugin of space-vim ( yeah, another spacemacs like vim conf)
