### ISSUE TITLE
Vim will die if :e! under nerd tree

### ISSUE THREAD

**Issue by p-z-l** [wsdjeg/SpaceVim#2629]
If you do the command ":e!" in nerdtree window.  The screen will freeze until you kill the vim process, while in vimfilter mode I should wait only for few seconds.
I was doing this because it wanna refresh the file tree.
Is that any solution for this or I can have another way to refresh the file manager?

**Comment by wsdjeg** [comment]
I will update the key bindings of filetree, including vimfiler and nerdtree.

**Comment by wsdjeg** [comment]
You can use `ctrl-r` to refresh filetree in both vimfiler or nerdtee.
