### ISSUE TITLE
E194: No alternate file name to substitute for '#'

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#263]
## Expected behavior
`nnoremap <leader>sv :source ~/.SpaceVim.d/init.vim<cr>` was just added into my `init.vim`

Then I opened up a new vim, pressed `\sv`, and error shows.

I want to know whether this works for me or not. 

More importantly, what does this erros means?
![image](https://cloud.githubusercontent.com/assets/12933851/23090543/41d59eae-f5db-11e6-8dab-e3e773baee13.png)

Also, you should notice that vim opened two windows for me. But only the upper windows is what I want.

## Environment Information
- OS: Arch Linux
- vim version:8.0

## The reproduce ways from Vim starting (Required!)
1. add `nnoremap <leader>sv :source ~/.SpaceVim.d/init.vim<cr>` into your `init.vim`
2. open your vim
3. `\sv`

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
`:message`:
![image](https://cloud.githubusercontent.com/assets/12933851/23090558/8af8200c-f5db-11e6-8c9f-e6a004ac6987.png)

---
`:echo SpaceVim#logger#viewLog()`
![image](https://cloud.githubusercontent.com/assets/12933851/23090567/c3c8c012-f5db-11e6-9ba4-acc98b5749c9.png)

**Comment by wsdjeg** [comment]
`\sv` has been overrided!

you can check it out by `:map \sv`.

**Comment by Gabirel** [comment]
Thanks.

I re-mapped them as `\svf`. This does the job.

**Comment by wsdjeg** [comment]
if you  really want to use`\sv`, you can put the definition in to a VimEnter autocmd .
see #100 #144

**Comment by Gabirel** [comment]
OK, I got it
