### ISSUE TITLE
Set background on gui or terminal in different way

### ISSUE THREAD

**Issue by fernandoferreira-me** [wsdjeg/SpaceVim#2637]
Hi

I'd like to set my background as dark on terminal and light on gui (MacVim)

Is that possible?

On vanilla vim, it should be something like

set background=dark
if has("gui_macvim")
    set background=light
endif

**Comment by xylinkun** [comment]
You should these code in bootstrap function. Please find the documentation here. https://spacevim.org/documentation/#bootstrap-functions
