### ISSUE TITLE
Please replace `iamcco/markdown-preview.vim` with `iamcco/markdown-preview.nvim`?  

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#2641]
As mentioned in the homepage of `mardown-preview.vim` repo, 
> warning: PLEASE USE https://github.com/iamcco/markdown-preview.nvim INSTEAD
--- 

A more general question, how to replace certain plugin in Spacevim?

**Comment by wsdjeg** [comment]
1. disable plugin.
2. add custom plugin.
