### ISSUE TITLE
Show error when press SPC *

### ISSUE THREAD

**Issue by HanielF** [wsdjeg/SpaceVim#2642]
## Expected behavior, english is required
After updating spacevim, i found that toggled window shows something error.
A blank line appears at the top of the window, and the last line is gone.

## The reproduce ways from Vim starting (Required!)
SPC p 
C-h
n

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
https://asciinema.org/a/EoIgGam6sfOxlzlao8hmTZAxJ

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by nafest** [comment]
Seems to be a regression with https://github.com/SpaceVim/SpaceVim/commit/f956b74a842821fa74374ed3f08774fc7c0fba1e
Going back to the commit before that fixes the issue.

**Comment by wsdjeg** [comment]
fixed.

**Comment by HanielF** [comment]
Okey. Thanks
