### ISSUE TITLE
something wrong when editing .ex or .exs files

### ISSUE THREAD

**Issue by CellPhoneYeah** [wsdjeg/SpaceVim#2646]
## In ubuntu18.4, vim8.0 environment, I want to edit the elixir code with spacevim, so I modified the configuration according to the official tutorial, but there was a problem when editing,  although I reinstallation ubuntu system and spacevim many times

```
Error detected while processing function <SNR>182_complete_timeout[6]..<SNR>182_python_cm_complete_timeout[2]..<SNR>182_python_refresh_completions: 
line  38:
E714: List required
Press ENTER or type command to continue

```
![spacevim_error](https://user-images.githubusercontent.com/19988436/54012398-e4c9f100-41b0-11e9-8050-20312aa25a36.png)

**Comment by wsdjeg** [comment]
There is no `_complete_timeout` function in SpaceVim, it should be a bug of upstream plugin, I can not fix it.

**Comment by CellPhoneYeah** [comment]
thanks
