### ISSUE TITLE
FlyGrep how to choose Options

### ISSUE THREAD

**Issue by Double1996** [wsdjeg/SpaceVim#2647]
In the new version it seems to be updating the new features of Neovim, Ctrl+n CTRL+p the shortcut keys to select Options up and down the flygrep is invalidated! Why is this?

**Comment by wsdjeg** [comment]
english only

**Comment by Double1996** [comment]
In the new version it seems to be updating the new features of Neovim, Ctrl+n CTRL+p the shortcut keys to select Options up and down the flygrep is invalidated! Why is this?

**Comment by Double1996** [comment]
> english only

In the new version it seems to be updating the new features of Neovim, Ctrl+n CTRL+p the shortcut keys to select Options up and down the flygrep is invalidated! Why is this?
