### ISSUE TITLE
No color shows in statusline when using PuTTY or a Linux terminal without GUI.

### ISSUE THREAD

**Issue by ZhuJiaYou** [wsdjeg/SpaceVim#2648]
**Expected behavior**
There should be colors based on the current colorscheme show in statusline.

**The reproduce ways from Vim starting** 
Using SpaceVim with PuTTY or a Linux terminal without GUI.

**Debug info**
None.

**Screenshots**
The upper and lower status bars have no color.
![SpaceVim1](https://user-images.githubusercontent.com/32535222/54066746-98de8100-4270-11e9-9aaa-9da4000f21ca.jpg)

And my OS is deepin 15.8.

**Comment by wsdjeg** [comment]
checkout spacevim faq
