### ISSUE TITLE
Delete useless repository by SpaceVim

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#265]
## Expected behavior
Today SpaceVim changed its `[tomasr/molokai]` into `[Gabirel/molokai]`.

However, `tomasr/molokai` cannot get deleted automatically by SpaceVim. This feature will cause redundancy in `~/.cache/vimfiles/repo/github.com`.

I hope SpaceVim could delete useless repository by itself. 

![image](https://cloud.githubusercontent.com/assets/12933851/23091789/37c15796-f5f9-11e6-9db0-fea6ebf22a4f.png)

![image](https://cloud.githubusercontent.com/assets/12933851/23091792/42d73d9e-f5f9-11e6-9b5c-9dba6b1bdee9.png)

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)
execute: `git pull` in SpaceVim folder

**Comment by wsdjeg** [comment]
sorry, repos is managered by dein, dein do not support delete repos.

**Comment by Gabirel** [comment]
oh~ that doesn't sound good

**Comment by wsdjeg** [comment]
It is feature of dein, and no need delete the cache.
