### ISSUE TITLE
Can't change UI toggles(or anything) globally

### ISSUE THREAD

**Issue by f0s3** [wsdjeg/SpaceVim#2656]
Hello.
I haven't found anything in the docs and in google and I am new to SpaceVim so I would like to know whether it is possible to run "SPC t 8" (or virtually any command) on vim startup as I would like it to be.
Right now every time I open vim I do SPC t 8.
Lead me to the way it could be done.

**Comment by wsdjeg** [comment]
please use gitter for asking question.
