### ISSUE TITLE
[Ruby] Indentation dont follow dots.  When insert a dot, it lose the identation

### ISSUE THREAD

**Issue by otavioschwanck** [wsdjeg/SpaceVim#2657]
## Expected behavior, english is required
1 - Indent fallowing the last line
2 - Dont lose identation when press "dot" .

## The reproduce ways from Vim starting (Required!)
Open a .rb file
Create a line with:
MyModel.do_thigs({}).create_something.rule_the_world
Create a second line with:
<spaces_until_first_dote_fo_first_line>.something()

Press "o" on second line.
The identation dont follow the dot.

Indent the third line until first dot and insert: .my_second_awesome_function()

Go to normal mode, return to insert mode and press . (dot).

The indentation is gone ;(

-

On my last vim file it not occurs, dont know why.

## Screenshots

![indentation lose 2](https://user-images.githubusercontent.com/9551316/54173911-95125080-4462-11e9-95df-0b7aee6d15bd.gif)

**Comment by wsdjeg** [comment]
it seems a ftplugin bug. I will look into it.

**Comment by wsdjeg** [comment]
@otavioschwanck I think this is issue of vim-ruby plugin, I can not fix it now.
