### ISSUE TITLE
FlyGrep Mapping && How to use <cword> func? 

### ISSUE THREAD

**Issue by tobbeone** [wsdjeg/SpaceVim#2659]
Hello, everybody.
   I had a problem for a long time, and I didn't found any answers in the previous issues.
   I use FlyGrep in vim-plug, I want to grep the character under the cursor, when I configured mapping this, it didn't work:
   noremap mg :FlyGrep <CR> <C-R>=expand("<cword>")<CR>
  Is there a way to make it work? Thanks. 🙏🏼🙏🏼🙏🏼

**Comment by tobbeone** [comment]
noremap mg :FlyGrep <CR> <C-R>=expand("<cword>")<CR>
![20190313104546](https://user-images.githubusercontent.com/37936389/54250048-3db4d300-457d-11e9-98ab-2619fbcf36ae.png)

**Comment by wsdjeg** [comment]
Please use gitter for question.
