### ISSUE TITLE
cannot set *.styl filetype as css filetype

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#267]
## Expected behavior
CSS syntax highlight is expected when opening a styl file.

I add `au BufNewFile,BufRead *.styl set ft=css` into `~/.SpaceVim.d/init.vim` just like in traditional `vimrc`

But it fails to me.

![image](https://cloud.githubusercontent.com/assets/12933851/23093669/aa7456fa-f624-11e6-9d14-0bfd7a3102a0.png)

## Environment Information
- OS: Arch Linux
- vim version: 8.0

**Comment by wsdjeg** [comment]
I just found it in `~/.cache/vimfiles/.cache/init.vim/.dein/ftdetect/ftdetect.vim`, and dein mearge most of the plugins, so I can not found which one set it.

**Comment by wsdjeg** [comment]
got it, should be `wavded/vim-stylus`

**Comment by wsdjeg** [comment]
it is https://github.com/wavded/vim-stylus.

and you can disable it, and update runtime cache.

**Comment by Gabirel** [comment]
It has default syntax highlight for stylus? Why it doesn't work for me?

It it has syntax highlight for stylus, then I just don't need to set `*.styl` as `*.css`.

**Comment by Gabirel** [comment]
@wsdjeg 
I don't want to open another new issue because it belongs to here.

So, in general, I still have no syntax highlight for my `stylus` file.

Also, I want `*.swig` to have syntax highlight just like `*.html`. So I put this below into `init.vim`, which works for me:
`au BufNewFile,BufRead *.swig set ft=html`


![image](https://cloud.githubusercontent.com/assets/12933851/24309922/be23512a-1108-11e7-9034-ba76ee86af7b.png)

But you can't do it with `.styls` file.
![image](https://cloud.githubusercontent.com/assets/12933851/24309942/d8973dbe-1108-11e7-9260-84b763aa67da.png)
![image](https://cloud.githubusercontent.com/assets/12933851/24309958/e5bb5d40-1108-11e7-80d7-db3649ecf8cb.png)

If I `set ft=css`, it works though:
![image](https://cloud.githubusercontent.com/assets/12933851/24309969/f6c89d32-1108-11e7-881c-4257b14bedc1.png)

**Comment by wsdjeg** [comment]
`call SpaceVim#layers#load('lang#swig')` should fix it.

seems https://github.com/wavded/vim-stylus has some issue with stylus

**Comment by wsdjeg** [comment]
oh, sorry SpaceVim has some wrong setting, I will fix it.

**Comment by wsdjeg** [comment]
Should be fixed, no need add

![](https://cloud.githubusercontent.com/assets/12933851/24309942/d8973dbe-1108-11e7-9260-84b763aa67da.png)

**Comment by wsdjeg** [comment]
` *.styl` file should works well by default,

if you want `*.swig` file works well you need add `call SpaceVim#layers#load('lang#swig')` to your custom config.

**Comment by Gabirel** [comment]
Oh, that's really fantastic feature of SpaceVim. 
Thank you very much.

**Comment by wsdjeg** [comment]
any problem about this issue?

**Comment by Gabirel** [comment]
No, I've tried it an hour ago. It works very well.
Thank you

**Comment by wsdjeg** [comment]
welcome!
