### ISSUE TITLE
Rust layer broken

### ISSUE THREAD

**Issue by avastmick** [wsdjeg/SpaceVim#2680]
## Expected behavior, english is required

Include the `lang#rust` layer in `init.toml` enables handling for Rust language files.

## The reproduce ways from Vim starting (Required!)
- Enable `lang#rust` layer in `init.toml`
- Update SpaceVim using `:SPUpdate`

Open new nvim instance and error below is seen - SpaceVim is not loaded.

Disable Rust layer and error doesn't appear, but Rust language functions are limited.

## Debug info

Cannot do this as SpaceVim does not load

## Screenshots

![SpaceVim rust layer error](https://user-images.githubusercontent.com/16931995/54500754-1a15d200-495b-11e9-8e68-6acbd19b5761.png)

**Comment by wsdjeg** [comment]
oh, it is a bug in https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/lang/rust.vim

the `rust#lang` should be changed to `lang#rust` in function name.

**Comment by wsdjeg** [comment]
we need to add test to avoid this issue.
