### ISSUE TITLE
Remapping t does not work

### ISSUE THREAD

**Issue by eclipseo** [wsdjeg/SpaceVim#2692]
For Dvorak and Bepo layout, we need to remap the movement keys as such:

```
" [HJKL] -> {CTSR}
nnoremap c h
nnoremap r l
nnoremap t j
nnoremap s k
```

Everything work but the "t" mapping which does not move down as expected.
Why is that? How can this be fixed?

**Comment by wsdjeg** [comment]
I think you can check it via `:map t`, it should be overried by other plugins, you can use bootstrap_after function to overrided it, or use VimEnter autocmd.
