### ISSUE TITLE
iedit I and A dont work (Multiple Cursor dont work too)

### ISSUE THREAD

**Issue by otavioschwanck** [wsdjeg/SpaceVim#2697]
## Expected behavior, english is required
I moves the cursor to start of cursor's line
A moves the cursor to end of cursor's line

## The reproduce ways from Vim starting (Required!)

1 - Copy that code to a .rb file:
```
def process
  # My Code Here
  # Pressing I or A dont work, only i or a
  generate_csv(param)
end

def generate_csv(param)
  # My Other Code Here
end
```
2 - move cursor to generate_csv
3 - press SPC s e
4 - Press I (Nothing happens
5 - Press A (Nothing happens)
6 - Press i (Works)
7 - Press esc, and press a (Works too)

## Screenshots
![iedit bug](https://user-images.githubusercontent.com/9551316/54897227-5048d980-4ea6-11e9-96c8-f843be677405.gif)

**Comment by wsdjeg** [comment]
Yeah, in current version iedit do not support `I` and `A` in iedit-Normal mode, but I will add it.

**Comment by wsdjeg** [comment]
@otavioschwanck I have opened PR #2705 which has add these two normal command. any other command should we add?

**Comment by otavioschwanck** [comment]
> @otavioschwanck I have opened PR #2705 which has add these two normal command. any other command should we add?

Just these, many thanks!
