### ISSUE TITLE
Leader Key for emmet

### ISSUE THREAD

**Issue by StandardNerd** [wsdjeg/SpaceVim#2698]
I enabled emmet plugin and I'm trying to execute emmet in insert mode.
But neither the spacevim 

> Ctrl-e

from https://spacevim.org/layers/lang/html/

nor the default emmet 

> Ctrl-y ,

 does work.

What's the correct leader key to execute emmet in insert mode?

**Comment by StandardNerd** [comment]
I could solve this issue by redefining trigger key:

in ~/.SpaceVim/vimrc

`let g:user_emmet_leader_key='<C-Z>'`

Now it works with 

> ctrl z ,

**Comment by wsdjeg** [comment]
as `~/.SpaceVim` is a git repo, you should not change content in it.
