### ISSUE TITLE
close tab on the top 

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#270]
## Expected behavior
I want to close index `2` and `3`. 
![image](https://cloud.githubusercontent.com/assets/12933851/23094662/32053478-f638-11e6-9373-09044841e8e4.png)

1. How can I close tabs I don't need, such as index `2` and `3`?
2. What does it means big number in each tab label?
3. What plugin it is? `vim-airline`? 
4. I HIGHLY recommend you put all these frequent shortcuts in document.

**Comment by wsdjeg** [comment]
It is vim-airline, and the bug number is buffer number, and small one is the index of the buffer in the tabline. 
as you can see in the pic, if you want to delete index 2, you can run `:bd 4`.

**Comment by wsdjeg** [comment]
also you can wirte a script to clear up all the unshown buffers. I think it is easy.

**Comment by Gabirel** [comment]
1. Why does the big number start from `0`?
2. Am I able to move the last buffer tab to the first one or the second? Sometimes I want the tab to become the first.
3. No, of course it is not easy. I have no idea about `viml`. So, I don't know how to write this.

**Comment by wsdjeg** [comment]
1. It is vim feature

2. I do not know how to change it.

3. Use for loop to delete all the buffers which buffer number is not same as current buffer.

**Comment by Gabirel** [comment]
fine, thank you for your help

**Comment by wsdjeg** [comment]
@Gabirel I have implement this feature, and the default mapping is `sc`.
