### ISSUE TITLE
enable language features for lang#asciidoc

### ISSUE THREAD

**Issue by gour** [wsdjeg/SpaceVim#2703]
Hello,

as we have chatted recently, this is a reminder to enable language-specific features of [vim-asciidoc](https://github.com/dahu/vim-asciidoc) plugin in `lang#asciidoc` layer.

Sincerely,
Gour

**Comment by wsdjeg** [comment]
@gour can you list all the key bindings we should added, all of them should be used in normal mode. start with `SPC l`.

**Comment by gour** [comment]
@wsdjeg give me some time since I was exploring some alternatives to Asciidoc, but yesterday 'discovered' another [vim plugin](https://github.com/habamax/vim-asciidoctor) and I believe you should include that one.

**Comment by wsdjeg** [comment]
@gour sorry, we can not change plugin plugin to vim-asciidoctor, because this layer use a forked version amd maintained by myself. BTW `asciidoctor` is not a filetype.
