### ISSUE TITLE
[Wish] Add airblade/vim-gitgutter do git layer

### ISSUE THREAD

**Issue by otavioschwanck** [wsdjeg/SpaceVim#2706]
Its a very nice plugin to show the difference direct on file.
![image](https://user-images.githubusercontent.com/9551316/55181642-d006ca80-516a-11e9-9fc4-d349f8167dc2.png)

I had to install via custom_plugins, its easy, but would be nice for new comers.

**Comment by mertyildiran** [comment]
@otavioschwanck there is one already: https://spacevim.org/layers/VersionControl/

**Comment by wsdjeg** [comment]
This has been done
