### ISSUE TITLE
Cant enter in iedit mode from visual mode

### ISSUE THREAD

**Issue by otavioschwanck** [wsdjeg/SpaceVim#2707]
## Expected behavior, english is required

After select with visual, press SPC s e and enter in iedit with selected text.

## The reproduce ways from Vim starting (Required!)

Create a text with
```
My AwesomeVim
My AwesomeVim
```

Select Awesome with visual mode.
press SPC s e

## Screenshots
![iedit](https://user-images.githubusercontent.com/9551316/55182183-e9f4dd00-516b-11e9-88df-97c1e198f3b0.gif)

**Comment by wsdjeg** [comment]
this feature looks nice. +1

**Comment by jsecchiero** [comment]
i have installed spacevim exactly for this and seems like this must be already working from the doc:
```
SpaceVim uses a powerful iedit mode to quick edit multiple occurrences of a symbol or selection.
```
If selection is not arbitrary the actual use is limited to a single word selection/editing.

**Comment by wsdjeg** [comment]
This has been done

![float](https://user-images.githubusercontent.com/13142418/56400709-e98dc480-6287-11e9-86f8-96cdbb8ccc59.gif)

**Comment by wsdjeg** [comment]
there is a bug, when only select `Awesome` it does not work.

**Comment by jsecchiero** [comment]
thanks @wsdjeg for the example, for me also works correctly, but doesn't work if i select a part of a word:
_this is an ex**ample** and doesn't work_

**Comment by wsdjeg** [comment]
I just debug it, and find out it is because we use ` "\\<" . a:need . "\\>"` to find iterm. so the part of word can not be find. here is an example:

```
this is a line
this is islents
```

then if your cursor is on `is` in first line, iedit mode should only select the two `is`, and ignore `is` in  `islents`.

**Comment by jsecchiero** [comment]
don't understand why you close the issue, is fixed?

**Comment by wsdjeg** [comment]
please see my comments above. iedit should ignore part of word

**Comment by alk-mandrianarijaona** [comment]
hi @wsdjeg I understand iedit can not be used with visual select mode. Is there a way to bulk update part of text like the example with `Awesome` above?

**Comment by wsdjeg** [comment]
@alk-mandrianarijaona this issue has been fixed, iedit support visual mode now. If it does not work for you, please use new issue.

**Comment by alk-mandrianarijaona** [comment]
@wsdjeg thanks, I will do that
