### ISSUE TITLE
[Wish] iedit - J and K equivalent of spacemacs

### ISSUE THREAD

**Issue by otavioschwanck** [wsdjeg/SpaceVim#2708]
Reference:
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#replacing-text-with-iedit

In spacemacs, you cant delimiter the area of action of iedit, its super useful when you dont want to change every match on the file.

**Comment by wsdjeg** [comment]
Hello, I do not understand this feature, what does it mean?

**Comment by otavioschwanck** [comment]
Here a demonstration:
https://www.dropbox.com/s/by4cvayx05inl8s/spacemacs.mkv?dl=0

**Comment by wsdjeg** [comment]
sorry for late reply, I just check the doc of spacemacs, but still can not find out what does it mean, failed to open this demo.

**Comment by wsdjeg** [comment]
~~I will send this to google groups, and close issue.~~

sorry.

**Comment by wsdjeg** [comment]
@otavioschwanck Hi, I want to add this feature in next release, but I still can not understand this feature, can you record as screen for it? the previous link shows me the file does exists.

**Comment by wsdjeg** [comment]
Move to https://groups.google.com/d/msgid/spacevim/ME3P282MB184221C0506AA22880827C0ED4209%40ME3P282MB1842.AUSP282.PROD.OUTLOOK.COM
