### ISSUE TITLE
[Wish] FZF Project Switcher

### ISSUE THREAD

**Issue by otavioschwanck** [wsdjeg/SpaceVim#2712]
## Expected behavior, english is required

Press SPC p p

Change the project.

## The reproduce ways from Vim starting (Required!)

Use the fzf layer, and try to swtich project with SPC p p

## Screenshots
![fzf](https://user-images.githubusercontent.com/9551316/55236207-309b1380-520e-11e9-9ed4-6d560a7d1cd7.gif)

**Comment by wsdjeg** [comment]
I will add denite support for this feature, I do not know if fzf support menu feature.

**Comment by wsdjeg** [comment]
I have installed fzf in windows, so I will test fzf.
