### ISSUE TITLE
Neomake is showing fly with lint_on_the_fly = false

### ISSUE THREAD

**Issue by otavioschwanck** [wsdjeg/SpaceVim#2713]
## Expected behavior, english is required
Dont show the fly.

## The reproduce ways from Vim starting (Required!)
Create a ruby file with rubocop errors. ( i guess JS file works too)

Save the file

## Screenshots
![neomake lint on the fly](https://user-images.githubusercontent.com/9551316/55237841-d2702f80-5211-11e9-8be5-6d7194effded.gif)

**Comment by wsdjeg** [comment]
I think it is a bug. I will check IT tonight.

**Comment by wsdjeg** [comment]
when you save the file, the lint will check the file, this not the work of option `lint_on_the_fly`.
