### ISSUE TITLE
Could you please add s, x, r and R to the iedit model?

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2719]
Could you please add s, x, r and R to the iedit model?

**Comment by xylinkun** [comment]
And how to replace the cursor ▮ by |?

**Comment by wsdjeg** [comment]
what function should this key provide?

**Comment by xylinkun** [comment]
Just like them in normal model.

**Comment by wsdjeg** [comment]
`s` and `x` have been added, I do not know why we should add `r`. if user want to replace char under cursor, I think he can press `s` + char.
