### ISSUE TITLE
could you pls add cancel return to flygrep, so it will not open floating window if I quit halfway.

### ISSUE THREAD

**Issue by alanding1989** [wsdjeg/SpaceVim#2721]

**Comment by wsdjeg** [comment]
I can not understand. do you have reproduce step.

**Comment by alanding1989** [comment]
> I can not understand. do you have reproduce step.

for example, I press **[SPC]sf** to grep in arbitrary directory, after I entered pattern words, before entering the searching directory, I found I was wrong, I just want to grep in current buffer, now I push ESC to **cancel** this grep action, it will continue to open the **blank** window, but I don`t want it to open the **blank** window when I **quit** this grep.

**Comment by alanding1989** [comment]
> I can not understand. do you have reproduce step.

### just want restart grep and do nothing (do not open blank grep result window) when pressing quit/cancel key in half way grep process.

**Comment by wsdjeg** [comment]
I think it is same as #1947, what you want is to resume flygrep windows after closing it.
