### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by p-z-l** [wsdjeg/SpaceVim#2727]
### As the title says ↑
Heres my environment:

macOS.
Vim 8.1

**Everything seems fine during install**
<img width="637" alt="Screen Shot 2019-04-05 at 7 33 38 PM" src="https://user-images.githubusercontent.com/43706386/55624957-00d5a800-57da-11e9-97db-eadc295556eb.png">

**when i launch Vim, it shows a classic Vim startup screen without any SpaceVim features**

<img width="1680" alt="Screen Shot 2019-04-05 at 7 40 11 PM" src="https://user-images.githubusercontent.com/43706386/55625215-b30d6f80-57da-11e9-9a34-0cd4372b8f7d.png">

**I checked the dependencies using command `curl -sLf https://spacevim.org/install.sh | bash -s -- -c`**

<img width="783" alt="Screen Shot 2019-04-05 at 7 29 54 PM" src="https://user-images.githubusercontent.com/43706386/55625288-e05a1d80-57da-11e9-84ba-e8d3eaf86617.png">

**Comment by p-z-l** [comment]
P.S. I tried install&reinstall for several times, but still

**Comment by wsdjeg** [comment]
Do you try to remove `~/.vim` and `~/.config/nvim`? and reinstall spacevim again?

**Comment by p-z-l** [comment]
yeah! it works
thanks very much

**Comment by wsdjeg** [comment]
hmm, It seems a bug, if `~/.vim` exist, the install script should move it to `~/.vim_back`.
