### ISSUE TITLE
Modeline can't show correctly

### ISSUE THREAD

**Issue by zachzhao1984** [wsdjeg/SpaceVim#2729]
## Expected behavior, english is required
   Modeline show completely
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
![a](https://user-images.githubusercontent.com/445029/55683499-031f3a00-5973-11e9-876b-90d145a539d1.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
It is issue with  font or terminal. I can do nothing about it.

**Comment by zachzhao1984** [comment]
> It is issue with font or terminal. I can do nothing about it.

I use konsole on Manjaro kde edition
