### ISSUE TITLE
How to install custom theme 'ayu'

### ISSUE THREAD

**Issue by nitin88** [wsdjeg/SpaceVim#2730]
I am trying to install `ayu` theme from here - https://github.com/ayu-theme/ayu-vim

I have added these to `init.toml` 

```
[[layers]]
	name = "colorscheme"
[[custom_plugins]]
	name = "ayu-theme/ayu-vim"
	merged = false

[options]
	# set spacevim theme. by default colorscheme layer is not loaded,
	# if you want to use more colorscheme, please load the colorscheme
	# layer
	colorscheme = "ayu"
	colorscheme_bg = "light"
```

However it's not loading the color scheme.
Please let me know how to fix this.

**Comment by wsdjeg** [comment]
please run `SPUpdate ayu-vim` to make sure ayu has been installled.
