### ISSUE TITLE
How can I get native ctrl-x back and keep windows_leader?

### ISSUE THREAD

**Issue by zxdposter** [wsdjeg/SpaceVim#2731]
I try use vimcompatible, but it will close windows_leader.

![image](https://user-images.githubusercontent.com/13846260/55870126-7b2b7100-5bba-11e9-81f1-bfa20fa5675a.png)

**Comment by wsdjeg** [comment]
currently we can not do that, but you can use umap command in bootstrap_after function to unmap that key.
