### ISSUE TITLE
Enhancement: Startup time using daemon mode or similar?

### ISSUE THREAD

**Issue by vnijs** [wsdjeg/SpaceVim#2748]
Related to https://github.com/SpaceVim/SpaceVim/issues/206. Spacevim is still plenty fast for me but I was wondering if something like `emacs --daemon` is possible to speed it up even more. See example below for spacemacs:

https://medium.com/@bobbypriambodo/blazingly-fast-spacemacs-with-persistent-server-92260f2118b7

**Comment by wsdjeg** [comment]
@vnijs do you have a try switch the filetree to defx?

**Comment by vnijs** [comment]
That does indeed appear to be a bit faster with nvim. Nice! Thanks @wsdjeg
