### ISSUE TITLE
Create FAQ section

### ISSUE THREAD

**Issue by a-b** [wsdjeg/SpaceVim#275]
## Expected behavior, english is recommend

I'd like to add FAQ section similar to the documentation.
As a first FAQ question I'd like to get an answer how to change leader `\` to the ` ` (space)

## Environment Information
- OS: osx
- vim version:
- neovim version: latest

## The reproduce ways from Vim starting (Required!)
go to the http://spacevim.org/

**Comment by wsdjeg** [comment]
SpaceVim has FAQ in help file. Do you mean add this to website?

**Comment by Gabirel** [comment]
Also, create `Quick Start` section on README.md and website for those key shortcuts which are frequently used and other stuff.

**Comment by wsdjeg** [comment]
@Gabirel @a-b ok, let move to #277
