### ISSUE TITLE
Can I set up my own .vimrc ?

### ISSUE THREAD

**Issue by jpixy** [wsdjeg/SpaceVim#2752]
How can I setup my own .vimrc ?
for example, where I should put 

set tabstop=4  
set shiftwidth=4  
set ruler 

these my own configuration ?

Thanks.

**Comment by Gabirel** [comment]
Please check this: https://spacevim.org/quick-start-guide/

You may have to create a directory named `.SpaceVim.d`.

SpaceVim supports two kinds of config file.
- `~/.SpaceVim.d/init.toml`
- `~/.SpaceVim.d/init.vim`

You may also check the template in [quick-start-guide](https://spacevim.org/quick-start-guide/) or [the template](https://github.com/Gabirel/Hack-SpaceVim/issues/10).

I believe you did not check the documentation. You may want to check them first.

**Comment by jpixy** [comment]
I try to create my own ~/.SpaceVim.d/init.vim. 

But it doesn;'t work , and it will generate new ~/.SpaceVim.d/init.toml file automatically. 

So how can I to specify my own configuration file to ~/.SpaceVim.d/init.vim ?
Or both config files (*.toml + *.vim) can work at same time ?

**Comment by Gabirel** [comment]
I can't reproduce your problem on my computer. Also, I believe that SpaceVim won't generate `init.toml` automatically unless you execute `:SPConfig` from vim

Try to delete `init.toml`. There's no risk doing it.

> Or both config files (*.toml + *.vim) can work at the same time?

I am not sure about this one. Only one config file is recommended.

**Comment by andersonbosa** [comment]
hi, @jpixy you could use the two files? `init.toml` and `init.vim`?

**Comment by Gabirel** [comment]
@andersonbosa Use `init.vim` if you are an experienced vim user. If not, use `init.toml`. Do not use both of them at the same time.
Personally, I recommend to use `init.vim` although SpaceVim prefers `init.toml`.
