### ISSUE TITLE
[Wish]Template engine syntax highlighting

### ISSUE THREAD

**Issue by garigari-kun** [wsdjeg/SpaceVim#2758]
When I edit slim file, it seems like syntax highlighting is not working.

<img width="420" alt="スクリーンショット 2019-04-21 2 10 13" src="https://user-images.githubusercontent.com/12244481/56460244-a6903600-63da-11e9-8db5-102552925ba7.png">

I'd like to add [this](https://github.com/slim-template/vim-slim) plugin to html layer.
https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/lang/html.vim

What do you think?

**Comment by wsdjeg** [comment]
How about add a new layer `lang#slim`?

**Comment by garigari-kun** [comment]
That sounds good.
Can I make PR for that?

**Comment by wsdjeg** [comment]
of course you can do it.
