### ISSUE TITLE
SpaceVim commands.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#276]
I do not like commands, it is hard to debug. But some people ask me to add commands for SpaceVim.
These commands will be added:
`SPSetOpt`
Set and check options, just like what `set` did in vim.
`SPDebugInfo`
Output debug information of SpaceVim

**Comment by lymslive** [comment]
In the opposite, I love commands much more. In my option, command also have some advance compare to maps. This repository may inspirit you more or less.
https://github.com/lymslive/MicroCommand

**Comment by wsdjeg** [comment]
@lymslive Thanks, will have a look, I know command is easy to use for user, but it is hard for plugin author to debug, that is why dein.vim also do not use command.
