### ISSUE TITLE
Tagbar show nothing content with golang source

### ISSUE THREAD

**Issue by 02040402** [wsdjeg/SpaceVim#2763]
![Screen Shot 2019-04-23 at 10 56 15](https://user-images.githubusercontent.com/49627449/56546854-84530f80-65b6-11e9-97e1-c26ea0c2197e.png)

But work for ruby source.

**Comment by wsdjeg** [comment]
ctags do not support golang by default, I think you need to install https://github.com/universal-ctags/ctags
