### ISSUE TITLE
Update contents of website.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#277]
- [ ] Add faq section to website

- [ ] Add quick start section

- [ ] Update contents of each page

- [ ] improve menu bar

**Comment by lsrdg** [comment]
What do you mean by "improve the menu bar"? Restyle, add new stuff? I was considering turning it into a liquid's loop in instead of manually written html. Any thoughts on that?

Where should the FAQ and the Quickstart sections be?

**Comment by wsdjeg** [comment]
@lsrdg I mean restyle, 
1. home
2. about
     - version
     - readmap
3. development
     - layer design
     - build plugin basd on public apis
     - bug report and feature request
4. community
5. documentation
6. support spacevim

**Comment by wsdjeg** [comment]
Move to #297
