### ISSUE TITLE
It's not intuitive how to uninstall on windows, still.

### ISSUE THREAD

**Issue by Colemata** [wsdjeg/SpaceVim#2777]
## Expected behavior, english is required

There should be an easy way to uninstall on windows machines, there isn't.

## The reproduce ways from Vim starting (Required!)

N/A

## Debug info

N/A

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

N/A

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
why do not use gitter for asking questions?
