### ISSUE TITLE
Error while run python Code completion

### ISSUE THREAD

**Issue by YakinRubaiat** [wsdjeg/SpaceVim#2779]
![Selection_008](https://user-images.githubusercontent.com/22772621/57091093-36fb3e80-6d2a-11e9-9861-7fc29c0e7dbd.png)
Hello, I get this error when running a python script. The script is not how output anyway. 

OS: Linux(Ubuntu)
Anaconda python 

```
Error detected while processing function SpaceVim#plugins#runner#open[11]..<SNR>
71_async_run[87]..122:
line    2:
E117: Unknown function: chanclose
```
I think I have to rewrite the PATH somewhere to anaconda python path.

**Comment by ssfdust** [comment]
Hello. It's highly recommanded to run python script in the virtual environment. Alternatively, you can set the Python execute file path as the shebang at the head of your script, which can be read by SpaceVim.

**Comment by wsdjeg** [comment]
It seems your vim is too old. `E117: Unknown function: chanclose`
