### ISSUE TITLE
hi , will spacevim consider compatible with spacemacs keybindings .  add a layer for ctjhoa/spacevim key bindings 

### ISSUE THREAD

**Issue by leiwang-ninjia** [wsdjeg/SpaceVim#278]
## Environment Information
- OS:
- vim version:
- neovim version:

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
Can you list the mappings?

**Comment by leiwang-ninjia** [comment]
I hope i can get some consistent key-mapping,  spacemacs's key mapping seems easy to remember and use.
https://github.com/ctjhoa/spacevim/blob/master/plugin/spacevim.vim

**Comment by wsdjeg** [comment]
SpaceVim has its own mappings layer, I think you can read the documents of SpaceVim, and find out what mappings do you want to be added .

**Comment by leiwang-ninjia** [comment]
ok, thanks.
