### ISSUE TITLE
Feature Request: install SpaceVim with Homebrew on macOS

### ISSUE THREAD

**Issue by simonrouse9461** [wsdjeg/SpaceVim#2785]
Fetching the install.sh script with a long curl command is a forbidding and inelegant way of installing modern terminal tools. In contrast, a simple and easy-to-memorize installation procedure can be extremely helpful for attracting new users. 

To this end, it will be really nice if the SpaceVim installation script can be installed by simply typing `brew install spacevim` on macOS, which will place the SpaceVim installation script under /usr/local/bin. In this way, user can run commands like `spacevim -i vim` and `spacevim -u` very conveniently and effortlessly without searching for or remembering the url every time.

**Comment by wsdjeg** [comment]
I think you can create alise in your basrc, spacevim is a config distro for vim and neovim.

**Comment by jhirbour** [comment]
I'd say it also promotes bad security practices. I'd much rather see a homebrew package.
