### ISSUE TITLE
SPUpdate take too much time for downloading the "LanguageClient"

### ISSUE THREAD

**Issue by y9c** [wsdjeg/SpaceVim#2786]
seem that running `SPUpdate` will triger `install.sh` script in ` ~/.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim`, even if the repo is up to date.

this script will download the binary again, and slow down the process.

**Comment by y9c** [comment]
https://github.com/SpaceVim/SpaceVim/blob/d85cb639cb89c1f089ebad316cc3e5b60d013548/autoload/SpaceVim/layers/lsp.vim#L16

**Comment by wsdjeg** [comment]
This is the feature, build process will be called when update done. because sometime user may rebuild the plugin.

**Comment by y9c** [comment]
no one would like to rebuild a plugin again when the code is not changed at all...

**Comment by ssfdust** [comment]
> no one would like to rebuild a plugin again when the code is not changed at all...

No, sometimes when the system upgrades for libraries, we indeed need to rebuild the plugin, though there is no change for code at all. The problem often occurs on some rolling-release Linux distribution, such as Archlinux.

**Comment by y9c** [comment]
@ssfdust As far as I know, this plugin is written in rust, which is not dynamic link with system libs.

I use Arch too...

**Comment by wsdjeg** [comment]
This is feature of dein or spacevim, I can not fix it, but you can do following steps:

1. load lsp layer
2. disable plugin `LanguageClient-neovim`
3. add custom plugin `autozimu/LanguageClient-neovim`

all above can be done in toml file.
