### ISSUE TITLE
Installing custom plugins that only load for certain filetypes

### ISSUE THREAD

**Issue by thedelchop** [wsdjeg/SpaceVim#2802]
If I am add a custom plugin that I only want loaded when working with a specific filetype, is there a way that it can be done inside the init.toml file?

For example, is something like this correct?

```
[[custom_plugins]]
  name = 'mxw/vim-jsx'
  merged = false
  on_ft = 'jsx'
```

I tried to find an answer to this someplace in the docs but didn't have any success.

**Comment by wsdjeg** [comment]
do you have a try, as I know this should works.

**Comment by thedelchop** [comment]
Seems you are correct, thank you!
