### ISSUE TITLE
Add support of Racket

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2803]
Hi Team:
  Do you consider to add racket spacevim support. I think a good implementation for racket plugin is [racket-vim](https://github.com/wlangstroth/vim-racket).

**Comment by wsdjeg** [comment]
yeah just have a look at this plugin. I will try to add it. so which completion plugin do you use for racket?

**Comment by ghost** [comment]
Currently I didn't find one yet. Since racket is a dialect scheme, I think the autocomplete part from scheme is enough.(test auto-complete from spacevim-scheme for a little while, it can work, but not sure about underlying bugs). 
Racket has a relatively complete implementation in emacs, you can read it [here](https://docs.racket-lang.org/guide/Emacs.html). I am sorry that I am not good at configuring vim :P

**Comment by ghost** [comment]
Opps, you just added the layers while I am typing
