### ISSUE TITLE
Error occured when open a go file in the file tree

### ISSUE THREAD

**Issue by leonlyo** [wsdjeg/SpaceVim#2806]
hi,friends, i have a trouble when i open a go file in the file tree
the error is below:
[unite.vim] function <SNR>247_register[9]..go#lsp#DidOpen, line 13
[unite.vim] Vim(call):E718: Funcref required
[unite.vim] Error occurred while executing "open" action!

**Comment by leonlyo** [comment]
![image](https://user-images.githubusercontent.com/28377743/57437286-08262080-7274-11e9-9832-a85580ae13fa.png)

**Comment by wsdjeg** [comment]
please install gopls, I just install this command and everything works well now. and this can only be fixed in vim-go.
