### ISSUE TITLE
Vimproc is not code signed on Mac.

### ISSUE THREAD

**Issue by apocalypse2012** [wsdjeg/SpaceVim#2810]
Using new install of Spacevim on a 2018 Mac Pro. Trying to start the python debugger gives me this...

dlerror = "dlopen(/Users/raymond/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim/lib/vimproc_mac.so, 0x0005): code signature in (/Users/raymond/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim/lib/vimproc_mac.so) not valid for use in process: mapped file has no Team 
ID and is not a platform binary (signed with custom identity or adhoc?)"

**Comment by wsdjeg** [comment]
I am not sure if it is a bug of https://github.com/Shougo/vimproc.vim, but nothing can be done in spacevim.
