### ISSUE TITLE
tags layout不能正常查找

### ISSUE THREAD

**Issue by jiansongjay** [wsdjeg/SpaceVim#2815]
环境准备：
1. 已经按照文档装好了global，ctags，pygments。
2. 配置好了tags layout
3. SPC m+g+c 建立数据库，SPC m+g+u 更新数据库

使用：
SPC m+g+d 查找函数定义时弹出错误：No tag matches

**Comment by wsdjeg** [comment]
github is for english only, for chinese issue report please use https://gitee.com/spacevim/SpaceVim/issues

**Comment by thouger** [comment]
same problem
