### ISSUE TITLE
Default mapping doesn't work

### ISSUE THREAD

**Issue by rikohabib** [wsdjeg/SpaceVim#2817]
## Expected behavior, english is required
I want the default mapping to works
## The reproduce ways from Vim starting (Required!)
1. $ vim somefile.ext
2. `<SPC> f t` 
  [which-key] Fail to execute, no such mapping     
3.` <SPC> j w`        
SPC j w is undefined                 
## Debug info
Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
SPC h I is undefined

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
you are using space-vim which is not current project. spacevim website is spacevim.org and this github.
