### ISSUE TITLE
Coloesheme Not Working Just Blue Color

### ISSUE THREAD

**Issue by ahmedselim2017** [wsdjeg/SpaceVim#2824]
Today when i opened spacevim the ColorScheme was just blue! [![blue theme][1]][1] 

  [1]: https://i.stack.imgur.com/8Qwu8.png

My init.toml:

    [options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true

    enable_statusline_mode = false
    [[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

    [[layers]]
    name="colorscheme"

    [[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

    [[layers]]
    name="lang#python"

Vim Version:

        VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 20:00:52)
        macOS version
        Included patches: 1-1200
        Compiled by Homebrew
        Huge version without GUI.  Features included (+) or not (-):
        +acl               +extra_search      +mouse_netterm     -tag_old_static
        +arabic            -farsi             +mouse_sgr         -tag_any_white
        +autocmd           +file_in_path      -mouse_sysmouse    -tcl
        +autochdir         +find_in_path      +mouse_urxvt       +termguicolors
        -autoservername    +float             +mouse_xterm       +terminal
        -balloon_eval      +folding           +multi_byte        +terminfo
        +balloon_eval_term -footer            +multi_lang        +termresponse
        -browse            +fork()            -mzscheme          +textobjects
        ++builtin_terms    +gettext           +netbeans_intg     +textprop
        +byte_offset       -hangul_input      +num64             +timers
        +channel           +iconv             +packages          +title
        +cindent           +insert_expand     +path_extra        -toolbar
        -clientserver      +job               +perl              +user_commands
        +clipboard         +jumplist          +persistent_undo   +vartabs
        +cmdline_compl     +keymap            +postscript        +vertsplit
        +cmdline_hist      +lambda            +printer           +virtualedit
        +cmdline_info      +langmap           +profile           +visual
        +comments          +libcall           -python            +visualextra
        +conceal           +linebreak         +python3           +viminfo
        +cryptv            +lispindent        +quickfix          +vreplace
        +cscope            +listcmds          +reltime           +wildignore
        +cursorbind        +localmap          +rightleft         +wildmenu
        +cursorshape       +lua               +ruby              +windows
        +dialog_con        +menu              +scrollbind        +writebackup
        +diff              +mksession         +signs             -X11
        +digraphs          +modify_fname      +smartindent       -xfontset
        -dnd               +mouse             +startuptime       -xim
        -ebcdic            -mouseshape        +statusline        -xpm
        +emacs_tags        +mouse_dec         -sun_workshop      -xsmp
        +eval              -mouse_gpm         +syntax            -xterm_clipboard
        +ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
           system vimrc file: "$VIM/vimrc"
             user vimrc file: "$HOME/.vimrc"
         2nd user vimrc file: "~/.vim/vimrc"
              user exrc file: "$HOME/.exrc"
               defaults file: "$VIMRUNTIME/defaults.vim"
          fall-back for $VIM: "/usr/local/share/vim"
        Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
        Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6

**Comment by wsdjeg** [comment]
make sure your terminal support true colors.
