### ISSUE TITLE
is it possible to turn off error explaination in the line below?

### ISSUE THREAD

**Issue by Peppershaker** [wsdjeg/SpaceVim#2829]
Using python, after the file saves the style checker runs, however, is it possible to turn off the error suggestion in the line below? 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/15576531/57892177-075d3380-780c-11e9-8940-84c6f28a9d87.png">

**Comment by y9c** [comment]
There is several arguments in Spacevim to control the display of this message, but none of them works well. It might be a bug in the Spacevim checker layer. 

https://github.com/SpaceVim/SpaceVim/blob/8118fab5a8018749df21601df3f9f63a6d9ca055/autoload/SpaceVim/layers/checkers.vim#L58

**Comment by Peppershaker** [comment]
thanks! i set the delay longer which is good enough.
is there a way to set this config in the main config file instead editing it in place?

**Comment by y9c** [comment]
`call SpaceVim#layers#load('checkers', { 'show_cursor_error': 0 })`

**Comment by Peppershaker** [comment]
thank you sir

**Comment by wsdjeg** [comment]
Please read https://spacevim.org/layers/checkers/

**Comment by y9c** [comment]
Bug solved just by closing the issue?

**Comment by wsdjeg** [comment]
there is layer option for disable showing error below current line

**Comment by ssfdust** [comment]
@yech1990 Please get to gitter for discussing.
[SpaceVim/Cn](https://gitter.im/SpaceVim/cn)

**Comment by y9c** [comment]
The cause of this issue is that inline message will not disappear, even after the cursor was move away and the line with error has been modified. Disabling this feature will not solve this problem.

**Comment by wsdjeg** [comment]
>  even after the cursor was move away and the line with error has been modified.

this is not reported above as I know, I reopen this issue, but reproduce step is still needed.
