### ISSUE TITLE
how can i format source code by google style?

### ISSUE THREAD

**Issue by xhzzhang** [wsdjeg/SpaceVim#2830]
## Expected behavior, english is required
I'm expected format source code by google code style.

## The reproduce ways from Vim starting (Required!)
Hope a new hotkey to format all buffer or all files

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
SpaceVim use neoformat as default format plugins, you need to find a command line tool which support google style, and config neoformat, note, in spacevim, you need to use bootstrap function to config neoformat.
