### ISSUE TITLE
How to map Shift-Enter or Ctrl-Enter to 'l s l' (trigger the `repl` pkg to send line for Python IDE) 

### ISSUE THREAD

**Issue by shern2** [wsdjeg/SpaceVim#2833]
#### Expected behavior
I am using the Python layer.
After initializing the REPL engine and visual-select several lines of code, hitting `Shift-Enter` or `Ctrl-Enter` will send the code to the REPL engine.

#### Attempts
Have added the options to `init.toml`:
```
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"
```
Then tried various methods to add the autoload function (`~/.SpaceVim.d/autoload/myspacevim.vim`), two of which are listed below:

```
function! myspacevim#after() abort
  noremap <S-Enter>:call SpaceVim#plugins#repl#send("line")
endfunction
```
or 
```
function! myspacevim#after() abort
    call SpaceVim#custom#SPCGroupName(['Shift'], '+TestGroup')
    call SpaceVim#custom#SPC('noremap', ['<silent><S-Enter>'], 'call SpaceVim#plugins#repl#send("line")', 'send line to REPL engine', 1)
endfunction
```

How can I do this?

Thanks in advance. (Great repo btw. Loving the setup. Just want to cut down on the keystrokes and make it similar to Jupyter-notebook).

**Comment by wsdjeg** [comment]
The first one should works well, but I do not know if neovim support `<S-Enter>`.

**Comment by wsdjeg** [comment]
It should be `noremap <silent> <S-Enter> :call SpaceVim#plugins#repl#send("line")<cr>`
