### ISSUE TITLE
Searching in a new/temporary buffer does not work

### ISSUE THREAD

**Issue by oemergenc** [wsdjeg/SpaceVim#2835]
## Expected behavior, english is required
Searching in a new/temporary buffer does not work. Instead the default search searches in the current directory. I would expect that matching lines of the current buffer are displayed although the buffer was not saved to a file yet. Using the traditional `/` key works as expected.

## The reproduce ways from Vim starting (Required!)
Make sure you have copied a bunch of text lines in your system clipboard.
Follow the following commands
```
vim
press e on the start page of space vim
SPC b P
SPC s s
```
Enter a keyword which exists in the current buffer. No results of the current buffer are found, only results from files existing in the current directory are found.

**Comment by wsdjeg** [comment]
You should save the buffer first, flygrep using the path of current file to search pattarn.
