### ISSUE TITLE
first open gvim

### ISSUE THREAD

**Issue by ea5y** [wsdjeg/SpaceVim#2837]
处理 function <SNR>2_resolve 时发生错误:

第    4 行:

E484: 无法打开文件 C:\Users\gopin\AppData\Local\Tem
p\VIo8FCE.tmp

处理 C:\Users\gopin\vimfiles\config\main.vim 
时发生错误:

第   63 行:

E117: Unknown function: SpaceVim#begin

处理 C:\Users\gopin\vimfiles\vimrc 时发生错误:

第   11 行:

E171: 缺少 :endif

**Comment by wsdjeg** [comment]
english only, and no os info
