### ISSUE TITLE
Detached FlyGrep fails to open

### ISSUE THREAD

**Issue by unclechu** [wsdjeg/SpaceVim#2838]
![Screenshot from 2019-05-19 23-43-47](https://user-images.githubusercontent.com/799353/57987863-1e13bc80-7a90-11e9-97b2-89e87a398778.png)
Commit: https://github.com/wsdjeg/FlyGrep.vim/commit/d7bfdfdcb5bdbbc4f788547490d3335a1a9ee6c1

**Comment by unclechu** [comment]
@wsdjeg When this fix will be delivered to https://github.com/wsdjeg/FlyGrep.vim repo?

**Comment by wsdjeg** [comment]
I will check the bot.

**Comment by wsdjeg** [comment]
@unclechu sorry, just fixed it again.

**Comment by unclechu** [comment]
@wsdjeg Okay, thanks. It works now but shows an error at start:
![Screenshot from 2019-05-27 15-26-05](https://user-images.githubusercontent.com/799353/58419653-de526380-8093-11e9-9650-87b819591381.png)

**Comment by wsdjeg** [comment]
please update flygrep and recache dein,

**Comment by wsdjeg** [comment]
@unclechu It is a bug, I will fix it. also see https://github.com/wsdjeg/FlyGrep.vim/pull/9
