### ISSUE TITLE
窗口管理s部分不理解

### ISSUE THREAD

**Issue by Mark24Code** [wsdjeg/SpaceVim#284]
普通编辑器（比如Sublime）使用场景的覆盖

左边是日常场景，（括号里是 操作） 尾巴是状态
1.开启一个文件，目录（vim + 目录，vim+ 文件） ok
2. 开启多个文件（在目录树里浏览，打开多个buffer） ok
3. 关闭当前tab （当前buffer）不影响其他buffer ------A
4. tab间切换 （buffers之间切换"<leader>"+"-"） ok
5. 关闭全部tab（关闭全部buffers） -----B

这边A和B部分，不太理解
s+Q 是按下 s +(Shift+q) 么
s+o，s+q,s+Q 这边工作表现好像不太一致，总是一下子全退出

**Comment by wsdjeg** [comment]
稍等

**Comment by wsdjeg** [comment]
这部分文档可能有点问题，sc应该是关闭其他所有buffers. so指的是关闭其他窗口，让当前窗口占据整个屏幕。

**Comment by wsdjeg** [comment]
我看了，确实是文档问题。

**Comment by wsdjeg** [comment]
> s+Q 是按下 s +(Shift+q) 么

是的，相当于执行 `：bd`


> s+o，s+q,s+Q 这边工作表现好像不太一致，总是一下子全退出

so问题因该不大，相当于 `:only`,  `sQ`已经`q`都是有关闭窗口的操作，至于为什么会一下子自动全关闭了，是由于 文件树窗口默认不作为最后一个窗口，比如目前我有左右两个窗口，左边是文件，右边是文件树窗口，如果我在左边执行`:q`，那么整个vim都会关闭。

这种思想其实很简单理解就是，不要把 文件树当作一个buffer，上面这种情况，就看作只有一个buffer，此时执行`:q`自然会关闭整个vim。
