### ISSUE TITLE
how to add multi_byte_ime  config?

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2841]
I added below in .SpaceVim.d\myspacevim.vim
function! myspacevim#before() abort
    if has('multi_byte_ime')
	    highlight Cursor guibg=Green guifg=NONE
	    highlight CursorIM guibg=Purple guifg=NONE
	endif
`endfunction  

I add below in .SpaceVim.d\init.toml
bootstrap_before = "myspacevim#before"

All don't work.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please read doc aga, it should be `.SpaceVim.d\autoload\myspacevim.vim`
