### ISSUE TITLE
random-theme don't work.

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2843]
I add the below in C:\Users\Administrator\.SpaceVim.d\init.toml and o finish updating plugin.

[[layers]]
name = "colorscheme"
random_theme = true

It dosen't work when I reopen gvim in windows 7.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by ssfdust** [comment]
Hello. The theme changes are frequency, daily, hourly , weekly, not every time you start vim.
