### ISSUE TITLE
New feature TODO annotations

### ISSUE THREAD

**Issue by s13g3lb4um** [wsdjeg/SpaceVim#2844]
The TODO annotations is available on spacevim development, but not in the default install branch.

see this plugin for Atom, search all todo notations in a working directory, load the file especified when this is selecting https://atom.io/packages/todo-show

**Comment by wsdjeg** [comment]
Yeah, currently the todo manager plugin is not stable. thanks for your link, and I will have a look at that atom plugin.

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/vim-todo
