### ISSUE TITLE
can not installed on mac 10.14.2

### ISSUE THREAD

**Issue by JackXuXin** [wsdjeg/SpaceVim#2848]
install process:
1.curl -sLf https://spacevim.org/install.sh | bash 
the console output:
![image](https://user-images.githubusercontent.com/24310518/58398480-c07f0180-8087-11e9-9b71-02363f4f5567.png)
2.open vim
![image](https://user-images.githubusercontent.com/24310518/58398504-d1c80e00-8087-11e9-8b42-634c2d326461.png)
is not work!

**Comment by wsdjeg** [comment]
sorry, I can not fix it, you should be able to create any file in your `home` dir.
