### ISSUE TITLE
Per-project configuration

### ISSUE THREAD

**Issue by TheAifam5** [wsdjeg/SpaceVim#2853]
Hey!

I want to configure SpaceVIM per project and... I've created the `.SpaceVim.d` directory with empty `init.toml` (because I want to only set some things via autoload) and I've added the configuration to `autoload` directory inside the `.SpaceVim.d`.

The problem is that the global configuration is being ignored and replaced by project configuration (even if is empty) - all configuration is reseted.

I'm new in SpaceVim and VIM :)

How I can set the following configuration only for a specific project?
```
let g:ale_linters_explicit = 1
let g:airline#extensions#ale#enabled = 1

let g:ale_linters = { 'c++': ['ccls'], 'c': ['ccls'] }
let g:ale_fixers = { 'c++': ['uncrustify'], 'c': ['uncrustify'] }

let g:ale_cpp_cppcheck_executable = 'cppcheck'
let g:ale_cpp_cppcheck_options = '--enable=all --inconclusive --inline-suppr '

let g:ale_fix_on_save = 1
```

Regards,
TheAifam5

**Comment by stfl** [comment]
look at this example: 

https://github.com/SpaceVim/SpaceVim/blob/master/.SpaceVim.d/init.vim

**Comment by TheAifam5** [comment]
@stfl Ah you mean `let g:spacevim_force_global_config = 1` that flag ? :D

**Comment by wsdjeg** [comment]
you can create `.SpaceVim.d/init.toml` in the root of your project. and put bootstrap function in it.

**Comment by TheAifam5** [comment]
I tried and `init.toml` was replaced by the project config. Nvm i just left SpaceVIM.
