### ISSUE TITLE
Git Clone Depth

### ISSUE THREAD

**Issue by danieldjewell** [wsdjeg/SpaceVim#2857]
I think this is probably related to #2840 too - I suppose this is a feature request? (I don't know how you want to classify this :grin:)

The various git clone operations that run (whether to install a plugin/layer or otherwise) do not consistently use --depth=1. The result is that .config/nvim/ and .cache/vimfiles/ are *big* (especially with lots of layers). 

It would be nice to have an option of 

* git clone with a depth of 1 always (e.g. "Production" mode - no git history required)
* git clone with full history (e.g. "Dev"/"Debug" mode -- to allow for work on plugins without separate cloning ... although, it is relatively simple to change a shallow --depth=1 clone into an unshallow clone, when needed.)

The result of the current behavior is:

* Unneeded disk space usage (you don't need a full git repo history to run the plugins)
* Unneeded bandwidth usage during cloning (which makes the install process slower)
* Additional git cpu cycles required (to process the entire repo and checkout)

As sort of a workaround, I ended up writing a little script that I could run from the ```./cache/vimfiles/``` directory to clean things up. https://github.com/danieldjewell/git-shallowall

**Comment by wsdjeg** [comment]
ok, I will add this feature.
