### ISSUE TITLE
Uninstaller problems

### ISSUE THREAD

**Issue by TheAifam5** [wsdjeg/SpaceVim#2860]
1. The uninstaller does not uninstall installed fonts.
2. The uninstaller does not give the ability to install `SpaceVIM` without the fonts
2a. The user can have already installed the fonts (like ArchLinux users)
3. Uninstaller does not cleanup everything.

Regards,
TheAifam5

**Comment by MadWombat** [comment]
For me uninstaller didn't do anything at all. I had to delete the spacevim config dir, remove the links for vim and nvim and move original configs back and reset my terminal config to get the fonts back.

**Comment by wsdjeg** [comment]
the uninstaller only will remove the link to spacevim, you need to delete fonts manuly
