### ISSUE TITLE
when using denite layer will pop up error message

### ISSUE THREAD

**Issue by xiaozhu1337** [wsdjeg/SpaceVim#2863]
## Expected behavior, english is required
Enable denite layer and use related function will pop up error message
## The reproduce ways from Vim starting (Required!)
normal install ,when press <kbd>SPC f f</kbd> ,the error message will pop up
## Debug info

when press <kbd>SPC h I</kbd>, only display spacevim layer, no debug info

## Screenshots
<img width="905" alt="屏幕快照 2019-06-01 23 44 34" src="https://user-images.githubusercontent.com/50901869/58750622-5ae7a680-84c7-11e9-883a-d8b80e4bf970.png">

**Comment by barkanido** [comment]
I think that in https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/core/statusline.vim the function `SpaceVim#layers#core#statusline#denite_mode` calls `denite#get_status_mode`, which was broken in [this commit](https://github.com/Shougo/denite.nvim/pull/624/files#diff-5b33ed186e984bc683f9fca553e8e1eeL25) as part of
https://github.com/Shougo/denite.nvim/pull/624 

this line should now be probably be replaced with `denite#get_status('mode')`

**Comment by Shougo** [comment]
> this line should now be probably be replaced with denite#get_status('mode')

Yes.  The functions are old and removed in the latest version.

https://github.com/SpaceVim/SpaceVim/pull/2826  Fixes the problem.

**Comment by wsdjeg** [comment]
I am still using old version of denite, and I will try to fix it later.

**Comment by alex88** [comment]
Is there a workaround to be able to use it for now?

**Comment by wsdjeg** [comment]
This issue has been fixed, please updated spacevim.
