### ISSUE TITLE
vimproc.vim failed 我已多次阅读文档

### ISSUE THREAD

**Issue by xx299x** [wsdjeg/SpaceVim#2869]
![image](https://user-images.githubusercontent.com/23482348/58806199-454dba80-8648-11e9-9ddb-9e80c96ec201.png)
无论是在windows还是在Linux ，ubuntu下，都是如此，不知道该如何处理....在这上面花了很多的时间...希望能有人解答一下

**Comment by wsdjeg** [comment]
English only
