### ISSUE TITLE
Neoformat doesn't work

### ISSUE THREAD

**Issue by tokelove** [wsdjeg/SpaceVim#2876]
## Expected behavior, english is required
- Use `[spc] b f` OR `:Neoformat`
- python file I have open is formatted

## The reproduce ways from Vim starting (Required!)
- Open a python files
- Press `[spc] b f` OR `:Neoformat`

## Debug info

:messages gives the following error:

```
Error detected while processing function neoformat#Neoformat[5]..<SNR>211_neoformat:
line   83:
E484: Can't open file <empty>
```

**Comment by happyhq** [comment]
when I  format the solidity code，I meet the same problem。
How to solve this problem？please。

**Comment by replicant0wnz** [comment]
So what was the fix for this? I'm getting the same thing.

**Comment by kronodeus** [comment]
Happening for me as well

**Comment by syominsergey** [comment]
I have the same error when editing java files and trying to format them:
```
Vim(let):E484: Can't open file <empty>
Error detected while processing function neoformat#Neoformat[5]..<SNR>245_neoformat:
line   83:
E484: Can't open file <empty>
Vim(let):E484: Can't open file <empty>
```
Even after update to version 1.3.0-dev of SpaceVim (I have also updated plugins).
Does anybody know workaround?

**Comment by replicant0wnz** [comment]
FYI, it's being tracked here:

https://github.com/SpaceVim/SpaceVim/issues/3008

**Comment by wangxiaoerYah** [comment]
I also got this error
