### ISSUE TITLE
ability to limit opened buffer number 

### ISSUE THREAD

**Issue by holyshipt** [wsdjeg/SpaceVim#2877]
## Expected behavior, english is required
have a configurable value to limit opened buffer number.

## The reproduce ways from Vim starting (Required!)
opening multiple files makes it hard to navigate between them.

## Debug info
None
## Screenshots
![Screen Shot 2019-06-07 at 5 07 15 PM](https://user-images.githubusercontent.com/46989746/59139245-be018f00-8946-11e9-9a02-58f4105e5029.png)

**Comment by wsdjeg** [comment]
yeah, this will be improved when new tabline plugin is finished.
