### ISSUE TITLE
Feature: Add 2 config options in install script

### ISSUE THREAD

**Issue by mseidl** [wsdjeg/SpaceVim#288]
Nice things would be to configure where .SpaceVim gets cloned too(instead of just under $HOME), and also would be a cool option to set the dein cache dir.  I'm not sure if this is the right place for setting the cache dir, but when you install spacevim and it immediately clones dein and then installs other plugins right away.

**Comment by wsdjeg** [comment]
two options:

1. I think it  is hard to change, for example , if I add this feature, maybe  you can use `$SPACEVIMDIR=~/foo ~/.install.sh` to install spacevim to ~/.foo, but next time if you want to update spacevim, ~/.install.sh will not work, it do not know what the dir is. only if you have added `export $SPACEVIMDIR=~/foo` to your bashrc.

2. there is an option for it. please check it out in `:h SpaceVim`
