### ISSUE TITLE
Add vcs conflict marker unimpaired binding

### ISSUE THREAD

**Issue by akrawchyk** [wsdjeg/SpaceVim#2886]
vim-unimpaired binds `[n` and `]n` to go to previous and next vcs conflict marker: https://github.com/tpope/vim-unimpaired/blob/master/doc/unimpaired.txt#L53-L59

I'm interested in adding this mapping to the SpaceVim unimpaired bindings. So, when there are vcs conflict markers in the current buffer, pressing `]n` will go to the next conflict marker, and pressing `[n` will go to the previous conflict marker.

**Comment by wsdjeg** [comment]
in spacevim, it is `[c` and `]c`

**Comment by akrawchyk** [comment]
@wsdjeg thanks for the quick response. I tried what you suggested but it doesn't seem to work for me. The use case I'm thinking of is when I have a file with merge conflicts open. `]c` tells me there isn't a next chunk. I'm trying to jump to the `>>>>>>>>` in git conflicts for example.

**Comment by wsdjeg** [comment]
@akrawchyk just find one plugin provides this feature, https://github.com/rhysd/conflict-marker.vim I will have a try with it, if it works well, I will add it into SpaceVim plugin list.

**Comment by akrawchyk** [comment]
@wsdjeg is it possible to use the existing mapping from `vim-unimpaired`? Also please tell me how I can help you implement this, I'm happy to help.

**Comment by wsdjeg** [comment]
please check #2932


---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Add vcs conflict marker unimpaired binding (#2886)
发件人：Andrew Krawchyk
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Mention


@wsdjeg<https://github.com/wsdjeg> is it possible to use the existing mapping from vim-unimpaired? Also please tell me how I can help you implement this, I'm happy to help.

―

**Comment by akrawchyk** [comment]
thanks @wsdjeg !

**Comment by wsdjeg** [comment]
no problem.

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Add vcs conflict marker unimpaired binding (#2886)
发件人：Andrew Krawchyk
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Mention


thanks @wsdjeg<https://github.com/wsdjeg> !

―
