### ISSUE TITLE
cannot use lsp for c++

### ISSUE THREAD

**Issue by shelper** [wsdjeg/SpaceVim#2892]
## Expected behavior, english is required
use lsp for c++ with clangd

## The reproduce ways from Vim starting (Required!)
i am on mac, with llvm already installed
put following to `init.toml`
[[layer]]
name = 'lsp'
filetypes=[
  "c",
  "cpp"
]

# Debug info
[ SpaceVim ] [15:12:08] [ Warn ] Failed to enable lsp for c, clangd is not executable!
[ SpaceVim ] [15:12:08] [ Warn ] Failed to enable lsp for cpp, clangd is not executable!

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
make sure you have clangd installed.

**Comment by shelper** [comment]
I think i have clangd installed, and it is the alias of `clangd-8`
seems the lsp works when i set override_cmd to `clangd-8`, but not `clangd` although it is just the alias of `clangd-8`

i wonder if it is possible to make it work with alias command as well.

**Comment by wsdjeg** [comment]
read the doc of lsp layer, you can change the language server command of c++.

**Comment by shelper** [comment]
i read it before i post this ...
not sure if i explained well of what i mean here. 
i was able to make LSP work using ['clangd-8'], but not ['clangd'] even i set `alias clangd = clangd-8`, However i think lsp should also work if i set `alias clangd=clangd-8` and still using ['clangd']
