### ISSUE TITLE
Language server protocol doesn't recognize local installation of executables.

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2895]
## Expected behavior, english is required

Shell can find commands `pyls` and `typescript-language-server` in `$PATH`, Below's warning shouldn't appears:

```
[ SpaceVim ] [22:24:32] [ Warn ] Failed to enable lsp for python, pyls is not executable!
[ SpaceVim ] [22:24:32] [ Warn ] Failed to enable lsp for typescript, typescript-language-server is not executable!
Press ENTER or type command to continue
```

## The reproduce ways from Vim starting (Required!)

Run installation and update environment variable `PATH`:

```
pip install --user python-language-server
yarn global add javascript-typescript-langserver
export PATH="$(yarn global bin):$PATH"
export PATH="~/.local/bin:$PATH"
```

Append to file `~/.SpaceVim.d/init.toml`:

```
  [[layers]]
  name = 'lsp'
  filetypes = [
    "python",
    "typescript"
  ]
```

## Debug info

At line 140 in `~/.SpaceVim/autoload/SpaceVim/layers/lsp.vim`:
`if executable(cmd)` works incorrectly. My temporal workaround is edit it as `if 1` to pass check, then everything works as expect.

## Screenshots

No screenshot.

**Comment by ssfdust** [comment]
Would you paste your spacevim runtime log. The shortcut is SPC h L.

**Comment by ghost** [comment]
executable() simply returns incorrect result without causing any error nor warning in log. those [ Warn ] are submitted by layer `lsp.vim` itself.
If I install language server by system package manager, those warnings won't show.

**Comment by ssfdust** [comment]
What is your OS?

**Comment by ghost** [comment]
Archlinux linux-5.1.12.arch1
NVIM v0.3.7

**Comment by ssfdust** [comment]
That's interesting. I have the same environment with you, while both pyls and vue-language-server work for me.

**Comment by Herschenglime** [comment]
I'm having this issue as well with global npm installed programs in ~/.config/npm-global/bin (javascript-typescript-stdio and bash-language-server in particular), but only for neovim GUIs. It's recognized to be part of my path and works fine when I run nvim in my shell, but trying to use neovide or nvim-qt throws that error.

I followed the guides on the wiki for setting lsp up, but perhaps there's another step in getting it recognized in programs outside the shell.
