### ISSUE TITLE
Code runner can not print

### ISSUE THREAD

**Issue by Le0000000000n** [wsdjeg/SpaceVim#2898]
## Expected behavior, english is required
Hi! I am testing SpaceVim and I am trying to print 'hello world' on to screen. However the hello world does not appear on screen.

## The reproduce ways from Vim starting (Required!)
I installed SpaceVim. Set language to python. Ran the code. And this appears.

## Debug info
![image](https://user-images.githubusercontent.com/7270964/59763075-4bd86500-92cb-11e9-94b8-cd99c8aa20e8.png)

## Screenshots
![image](https://user-images.githubusercontent.com/7270964/59762869-d10f4a00-92ca-11e9-8a48-45de785e6be9.png)

**Comment by wsdjeg** [comment]
I can not reproduce it, it works well for me.
