### ISSUE TITLE
Global search is not highlight with `spacevim` theme

### ISSUE THREAD

**Issue by Double1996** [wsdjeg/SpaceVim#2908]
![](https://ws1.sinaimg.cn/large/005FiKNpgy1g4dd5cjjuxj30wc0or0z0.jpg)

such as picture , when I use spacevim theme in my config. And use  **SPC S /** , then is not highlight options line .

**Comment by wsdjeg** [comment]
I want to say the SpaceVim colorscheme is not finished, if it is done,maybe it will be the default colorsheme.

________________________________
wsdjeg@outlook.com

**Comment by Double1996** [comment]
> I want to say the SpaceVim colorscheme is not finished, if it is done,maybe it will be the default colorsheme.

I hope to finish it as soon as possible.  Unfortunately, I can't write a theme. if I can , I will help you。 Do you have QQ group ?

**Comment by wsdjeg** [comment]
we do not use QQ group. use gitter instead. for Chinese discussion it is:

https://gitter.im/SpaceVim/cn

for English :

https://gitter.im/SpaceVim/SpaceVim

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Global search is not highlight with `spacevim` theme (#2908)
发件人：Forrest Shuang
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Comment


I want to say the SpaceVim colorscheme is not finished, if it is done,maybe it will be the default colorsheme.

I hope to finish it as soon as possible. Unfortunately, I can't write a theme. if I can , I will help you。 Do you have QQ group ?

―

**Comment by wsdjeg** [comment]
fixed.
