### ISSUE TITLE
SPC-b n doesn't switch to next buffer

### ISSUE THREAD

**Issue by ngw** [wsdjeg/SpaceVim#2914]
##  Expected behavior, english is required

<kbd>tab</kbd> or <kbd>SPC-b n</kbd> should switch focus to next buffer
When in insert mode, <kbd>tab</kbd> behaves as expected (it inserts a /t).

## The reproduce ways from Vim starting (Required!)
 
I start vim with a directory, <kbd>tab</kbd> or <kbd>SPC-b n</kbd> should switch focus to vimfiler, but nothing happens.
Same behaviour with a normal buffer.

## Versions

Spacevim 1.2.0-dev
vim 8.1 (neovim has the same behaviour)
Alacritty 0.3.2 (termite has the same behaviour)
Manjaro 18.0.4

**Comment by wsdjeg** [comment]
I can not reproduce it, when start vim with a directory, welcome screen should be openned.

**Comment by ngw** [comment]
It disappeared. I really have no idea... Sorry about the burden and thanks for the patience.

**Comment by wsdjeg** [comment]
Ok.
