### ISSUE TITLE
Improve documentation on how to add standard vim settings

### ISSUE THREAD

**Issue by acgreek** [wsdjeg/SpaceVim#2919]
Yes, I have read the manual and the FAQ and :help SpaceVim and still keep banging my head against the wall unable to figure how to add vim settings. Please just add a simple example of how one can go about doing it. For example, I want to remove all white space at the end of every line on save. I find via google that I just need to add to my .vimrc

 autocmd BufWritePre * :%s/\s\+$//e

obviously, adding this to .vimrc does has no effect. After adding and running vim:

:autocmd BufWritePre                                                                                                                                                     
--- Auto-Commands ---
SpaceVim_core  BufWritePre

next I go look at the SpaceVim manual and it says I should put the configuration in .SpaceVim.d/init.toml. I add the configuration to the init.toml, and great now it I get an ton of error messages when I open any file.

I guess I need to SpaceVim specific options but I don't see one specifically for this setting

next I go look at the :h SpaceVim-config and it says I should add the setting to the /.SpaceVim.d/init.vim file

this file doesn't exist, and when I add the setting there, there is no effect (I'm guessing this is just the documentation being out of data, because I saw else where is says the init.vim was replaced with toml version 

So after this I tried, using the bootstraping functions

create a ~/.SpaceVim.d/autoload/myspacevim.vim 
function! myspacevim#before() abort                                                                                                                                  
   autocmd BufWritePre * %s/\s\+$//e                                                                                                                                
   nnoremap jk <Esc>                                                                                                                                                
endfunction 

(also tried adding the after function as well) with no success. On saving of my file.py with extra whitespace at the end, there was no effect.

rm -rf .SpaceVim .SpaceVim.d
and kept my original .vimrc with the setting in place, and it worked perfectly .

**Comment by acgreek** [comment]
So disappointed that I decide to try another vim configuration solution and came upon EverVim

https://github.com/LER0ever/EverVim

Fortunately, it uses a native .vim configuration file and  by default appears to remove white from the end of lines

**Comment by wsdjeg** [comment]
use augroup to make sure your autocmd do not be overrided. also make sure bootstrap function has been loaded successfully. you can use `SPC h L` to check the runtime log.

**Comment by wsdjeg** [comment]
feeling free to choose the one you think which is best for you.

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Improve documentation on how to add standard vim settings (#2919)
发件人：Anthony Carathimas
收件人：SpaceVim/SpaceVim
抄送：Subscribed


So disappointed that I decide to try another vim configuration solution and came upon EverVim

https://github.com/LER0ever/EverVim

Fortunately, it uses a native .vim configuration file and by default appears to remove white from the end of lines

―
