### ISSUE TITLE
Error Using Shortcuts

### ISSUE THREAD

**Issue by NWuensche** [wsdjeg/SpaceVim#292]
## Expected behavior, english is recommend
Hello everybody, 
I tried to install Spacevim, but everytime I try to e.g. press o for a new line, I get the following error

``
Error detected while processing function <SNR>26_tool:                                       
line    2:                                                                                   
E492: Not an editor command:         IndentLinesToggle   
``

I never had problems while using normal vim. 

## Environment Information
- OS: Arch Linux
- vim version: 8.0
- neovim version: 0.1.7 (But not used)

## The reproduce ways from Vim starting (Required!)
Install Spacevim as told on the home page.
open any file with vim
press 'o'

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

``
E492: Not an editor command:         IndentLinesToggle
Error detected while processing function <SNR>26_tool:
``

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

config file is untouched

**Comment by wsdjeg** [comment]
You need wait for the process of installing plugin.

**Comment by NWuensche** [comment]
Thanks for the answer! But what do you mean with wait? It said that installation was finished.

Edit: I found the missing command in the README. I made a PR to add it also on the website.
