### ISSUE TITLE
Feature request: allow selecting branch (stable, dev) when installing/updating spacevim

### ISSUE THREAD

**Issue by tranzystorekk** [wsdjeg/SpaceVim#2925]
Currently installing SpaceVim or updating it using SPUpdate always fetches the dev branch.

Users should be able to select the branch when installing/updating. It could be done using a new install flag and a new config parameter.

**Comment by wsdjeg** [comment]
`SPUpdate` is to run `git pull` only, you can run git command in `~/.SpaceVim` to switch to stable tags.
