### ISSUE TITLE
can't enable markdown preview

### ISSUE THREAD

**Issue by langleegelang** [wsdjeg/SpaceVim#2926]
## Expected behavior, english is required

can preview markdown

## The reproduce ways from Vim starting (Required!)
1. add lang#markdown support markdown
2. open a markdown file
3. wait plugins install finish
4. running for whole night `markdown-preview.nvim` and `vim-node-rpc` still building

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
**I tried, no debug info in my clipboard**
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please post debug info instead of layer list.

________________________________
wsdjeg@outlook.com

**Comment by wsdjeg** [comment]
OK，just see your issue has been updated, you vim do not support +clipboard.

to enable markdown preview feature, you need make sure markdown-preview.nvim and vim-node-rpc installed successfully. please read the doc:

1. https://github.com/iamcco/markdown-preview.nvim

you need to install yarn  

https://yarn.bootcss.com/docs/install/#windows-stable

**Comment by wsdjeg** [comment]
github issue is for bug report and feature request, not for ask question, this is not a bug of spacevim, it is usage of markdown-preview.nvim. maybe ask in https://gitter.im/SpaceVim/SpaceVim is better.

**Comment by langleegelang** [comment]
I used vim as a editor for a few years, never used it as a IDE. I read the document you gave, it still hard for me to enable this feature.

life is short, I don't have much time to delve into these plugins installation. I will use vscode as the first IDE choice.

thanks for your contribution to OS.

**Comment by wsdjeg** [comment]
OK ;)

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] can't enable markdown preview (#2926)
发件人：Phil Cheng
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,State change


I used vim as a editor for a few years, never used it as a IDE. I read the document you gave, it still hard for me to enable this feature.

life is short, I don't have much time to delve into these plugins installation. I will use vscode as the first IDE choice.

thanks for your contribution to OS.

―
