### ISSUE TITLE
add fish script support for lang#sh layer

### ISSUE THREAD

**Issue by zachzhao1984** [wsdjeg/SpaceVim#2934]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by zachzhao1984** [comment]
actually this is a feature request, not a bug

**Comment by wsdjeg** [comment]
for feature request there should be new issue template, I will fix it. BTW, what do you think about new layer name lang#fish ?

________________________________
wsdjeg@outlook.com

**Comment by zachzhao1984** [comment]
I think name lang#fish is fine

**Comment by wsdjeg** [comment]
currently we hava lang#sh layer, also layer page has been added in website. how about included fish into it?

________________________________
wsdjeg@outlook.com

**Comment by zachzhao1984** [comment]
That is exactly what I wish for~

**Comment by wsdjeg** [comment]
done
