### ISSUE TITLE
Opening guide breaks listchars

### ISSUE THREAD

**Issue by Ugzuzg** [wsdjeg/SpaceVim#2939]
## Expected behavior, english is required

Hidden characters should stay the same when opening guide.

## The reproduce ways from Vim starting (Required!)

1. Toggle hidden characters on if not displayed (SPC t l)
2. Enter some tabs
3. Press SPC and wait for guide to be visible
4. See `^I` instead of chosen tab symbol

This is happening because `listchars` is overridden here:
https://github.com/SpaceVim/SpaceVim/blob/331139505ad257bb2e1df6f44557aeda8b247a24/autoload/SpaceVim/mapping/guide.vim#L552

## Debug info

```
SpaceVim layers:

+ VersionControl:           loaded          https://spacevim.org/layers/VersionControl/
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
- chinese:              not loaded          https://spacevim.org/layers/chinese/
+ colorscheme:              loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- debug:                not loaded          https://spacevim.org/layers/debug/
+ denite:                   loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
+ format:                   loaded          https://spacevim.org/layers/format/
- fzf:                  not loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
+ git:                      loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
- lang#c:               not loaded          https://spacevim.org/layers/lang/c/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
- lang#crystal:         not loaded          no exists
- lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
- lang#d:               not loaded          https://spacevim.org/layers/lang/d/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
- lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
- lang#go:              not loaded          https://spacevim.org/layers/lang/go/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
+ lang#html:                loaded          https://spacevim.org/layers/lang/html/
- lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
- lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
- lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
- lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
- lang#markdown:        not loaded          https://spacevim.org/layers/lang/markdown/
- lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
- lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
- lang#pascal:          not loaded          no exists
- lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
- lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
- lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
- lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
- lang#python:          not loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          https://spacevim.org/layers/lang/r/
- lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
- lang#red:             not loaded          https://spacevim.org/layers/lang/red/
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
- lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
- lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
- lang#slim:            not loaded          no exists
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
+ lang#toml:                loaded          no exists
+ lang#typescript:          loaded          https://spacevim.org/layers/lang/typescript/
- lang#v:               not loaded          https://spacevim.org/layers/lang/v/
+ lang#vim:                 loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
+ lang#xml:                 loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
+ lsp:                      loaded          no exists
- mail:                 not loaded          no exists
+ operator:                 loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell/
+ sudo:                     loaded          https://spacevim.org/layers/sudo/
- tags:                 not loaded          no exists
- test:                 not loaded          https://spacevim.org/layers/test/
- tmux:                 not loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#mpv:            not loaded          no exists
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- vim:                  not loaded          no exists
```

## Screenshots

[![asciicast](https://asciinema.org/a/FjW0fMqV4dgUjX4CNCGYqFBfW.svg)](https://asciinema.org/a/FjW0fMqV4dgUjX4CNCGYqFBfW)

**Comment by wsdjeg** [comment]
I can not reproduce it, please update your neovim or vim, the listchar option should local to windows.

________________________________
wsdjeg@outlook.com

**Comment by Ugzuzg** [comment]
It is already the latest version:
```
% nvim --version                                                                                                 ~
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by wsdjeg** [comment]
ok, i will have a try again.

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] Opening guide breaks listchars (#2939)
发件人：Jaryk
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Comment


It is already the latest version:

% nvim --version                                                                                                 ~
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info


―

**Comment by thuleqaid** [comment]
i experienced same problem.

1. Open a tab indent c source file
![Image20190718_143909](https://user-images.githubusercontent.com/1270758/61434929-df07c780-a969-11e9-9a29-05e0e5dcdd1c.png)
  Tab is shown as ">----"

2. Press "\"
![Image20190718_143918](https://user-images.githubusercontent.com/1270758/61434976-fa72d280-a969-11e9-8c49-f9c0eef6933c.png)
  Tab is shown as "^I"

3. Press "Esc"
![Image20190718_143922](https://user-images.githubusercontent.com/1270758/61434991-02327700-a96a-11e9-9c70-fec58f29f16d.png)
  Tab does not get back.

**Comment by thuleqaid** [comment]
![Image20190718_144332](https://user-images.githubusercontent.com/1270758/61435175-808f1900-a96a-11e9-9229-7d3839262475.png)

SpaceVim layers:

+ autocomplete:             loaded          no exists
- chat:                 not loaded          no exists
+ checkers:                 loaded          no exists
- chinese:              not loaded          no exists
- colorscheme:          not loaded          no exists
+ core#banner:              loaded          no exists
+ core#statusline:          loaded          no exists
+ core#tabline:             loaded          no exists
+ core:                     loaded          no exists
+ cscope:                   loaded          no exists
- ctrlp:                not loaded          no exists
- debug:                not loaded          no exists
- denite:               not loaded          no exists
+ edit:                     loaded          no exists
- exprfold:             not loaded          no exists
- floobits:             not loaded          no exists
+ format:                   loaded          no exists
- fzf:                  not loaded          no exists
- games:                not loaded          no exists
- git:                  not loaded          no exists
- github:               not loaded          no exists
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          no exists
- lang#agda:            not loaded          no exists
- lang#asciidoc:        not loaded          no exists
- lang#autohotkey:      not loaded          no exists
- lang#c:               not loaded          no exists
- lang#clojure:         not loaded          no exists
- lang#coffeescript:    not loaded          no exists
- lang#crystal:         not loaded          no exists
- lang#csharp:          not loaded          no exists
- lang#dart:            not loaded          no exists
- lang#dockerfile:      not loaded          no exists
- lang#elixir:          not loaded          no exists
- lang#elm:             not loaded          no exists
- lang#erlang:          not loaded          no exists
- lang#extra:           not loaded          no exists
- lang#fsharp:          not loaded          no exists
- lang#go:              not loaded          no exists
- lang#graphql:         not loaded          no exists
- lang#haskell:         not loaded          no exists
- lang#html:            not loaded          no exists
- lang#ipynb:           not loaded          no exists
- lang#java:            not loaded          no exists
- lang#javascript:      not loaded          no exists
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          no exists
- lang#kotlin:          not loaded          no exists
- lang#latex:           not loaded          no exists
- lang#lisp:            not loaded          no exists
- lang#lua:             not loaded          no exists
- lang#markdown:        not loaded          no exists
- lang#nim:             not loaded          no exists
- lang#ocaml:           not loaded          no exists
- lang#perl:            not loaded          no exists
- lang#php:             not loaded          no exists
+ lang#plantuml:            loaded          no exists
- lang#pony:            not loaded          no exists
- lang#processing:      not loaded          no exists
- lang#ps1:             not loaded          no exists
- lang#puppet:          not loaded          no exists
- lang#purescript:      not loaded          no exists
+ lang#python:              loaded          no exists
- lang#r:               not loaded          no exists
- lang#racket:          not loaded          no exists
- lang#red:             not loaded          no exists
- lang#ruby:            not loaded          no exists
+ lang#rust:                loaded          no exists
- lang#scala:           not loaded          no exists
- lang#scheme:          not loaded          no exists
- lang#sh:              not loaded          no exists
- lang#slim:            not loaded          no exists
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#swift:           not loaded          no exists
- lang#swig:            not loaded          no exists
- lang#toml:            not loaded          no exists
- lang#typescript:      not loaded          no exists
- lang#vim:             not loaded          no exists
- lang#vue:             not loaded          no exists
- lang#WebAssembly:     not loaded          no exists
- lang#xml:             not loaded          no exists
- leaderf:              not loaded          no exists
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          no exists
- sudo:                 not loaded          no exists
- tags:                 not loaded          no exists
- test:                 not loaded          no exists
- tmux:                 not loaded          no exists
- tools#dash:           not loaded          no exists
- tools#mpv:            not loaded          no exists
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          no exists
+ tools:                    loaded          no exists
+ ui:                       loaded          no exists
- unite:                not loaded          no exists
- VersionControl:       not loaded          no exists
- vim:                  not loaded          no exists
