### ISSUE TITLE
Allow split screen from file search

### ISSUE THREAD

**Issue by songz** [wsdjeg/SpaceVim#2946]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm searching for a file and then realize that I can't split screen directly. I have to stop my search, open a buffer, then search for a file again.

**Describe the solution you'd like**
When I'm searching for a file `SPC p f`, I should be able to directly type `CTRL v` or to open the highlighted file in a new vertical buffer.

**Describe alternatives you've considered**
This seems to be common functionality in the other search plugins.

**Comment by wsdjeg** [comment]
the SPC p f key binding is definded by fuzzy find layer, so which fuzzy find layer do you use?


________________________________
wsdjeg@outlook.com

**Comment by danshumaker** [comment]
I use the ripgrep (fzf) layer.  I'll try others if they will support search index split screens.  Which ones support CTRL v ? I use to use CTRL v   All the time and miss it since switching to SpaceVim (FlyGrep)

**Comment by danshumaker** [comment]
Sorry, I was searching for `SPC sr` (FlyGrep) keymappings and not fzf `SPC pf` key bindings.  Same question remains though...  Would love to be able to do `v` within the FlyGrep output. It looks like the tab key is the only option for opening files.  Will open a new ticket for FlyGrep customization.

**Comment by wsdjeg** [comment]
@songz I just have a try with ctrlp layer, and `ctrl-v` works well for me.

@danshumaker do you mean add key bindings to open result in flygrep vertically?

**Comment by danshumaker** [comment]
@wsdjeg yes vertically split within flygrep.  Added more details within #2990

**Comment by wsdjeg** [comment]
Ok, I will add these features.



wsdjeg@163.com
 
From: Dan Shumaker
Date: 2019-08-08 05:44
To: SpaceVim/SpaceVim
CC: Wang Shidong; Mention
Subject: Re: [SpaceVim/SpaceVim] Allow split screen from file search (#2946)
@wsdjeg yes vertically split within flygrep. Added more details within #2990
