### ISSUE TITLE
key binding for Bookmark plugin overwrites keybinding for mark.

### ISSUE THREAD

**Issue by GreggJensen** [wsdjeg/SpaceVim#295]
## Expected behavior, english is recommend
pressing 'm' + (a-z) is supposed to mark a position in the file which can they be used, for example, to yank from a different line to that line and those lines will be put into a buffer which can then be pasted somewhere else in the file.  With SpaceVim the keybinding for the Bookmark plugin overwrites the 'm' key for it's own purpose.  This is NOT the same kind of mark as the original mark and can't be used as a replacement.  And because the 'm' key is overwritten the original meaning would either have to be re-bound to another key or SpaceVim binding of the 'm' key for book marks should use a different key.

## Environment Information
- OS: OS/X
- vim version:
- neovim version: latest

## The reproduce ways from Vim starting (Required!)
got to a position in a file where you will want to yank a number of lines that you don't want to count. press 'm' and then 'a'.  Then go to the line at the end of the section that you would want to yank and press 'y' and single quote (') and then 'a' and it will reply with no mark set.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
I just add some doc in #297

**Comment by GreggJensen** [comment]
That will work, thanks for the quick update.

**Comment by wsdjeg** [comment]
welcome. 😄
