### ISSUE TITLE
One tip may help enhanced c/c++ sementic highlight

### ISSUE THREAD

**Issue by jidibinlin** [wsdjeg/SpaceVim#2957]
Though the c/c++ layer has clang_syntax_highlight option, I found it worked not very well but I find one solution for you. I haven`t try it but I think it works for you.

** jackguo380/vim-lsp-cxx-highlight ** this is a vim plugin that assoiated with LSP. It uses ccls or cquery as the LSP back end. Ccls`s wiki also mention it(just follow this url "https://github.com/MaskRay/ccls/wiki/Editor-Configuration") 
I didn`t hack spacevim well, Ihope you can consider my tip use ccls as the LSP back end and use vim-lsp-cxx-highlight highlighting code.

**Comment by wsdjeg** [comment]
@jidibinlin Thanks for your info, I will have a try with this plugin, it looks awesome, does other programming language support this feature?

**Comment by jidibinlin** [comment]
There is a plugin called vim-lldb that used to debug c/c++ code. I have used it, vim-lldb works fine on my archlinux

**Comment by jidibinlin** [comment]
what I know just c/c++

**Comment by jidibinlin** [comment]
@wsdjeg 
## Hi! I had made the sementic highlight work.I config it in this way.  
* use coc.nvim as the lsp-client(LanguageClient-neovim should also work but i don`t know how to config it)
* type :CocConfig command in nvim to generate the coc-settings.json and config it.
## But this way is not very elementory for SpaceVim for what SpaceVim natively config coc.nvim through init.tom.

**Comment by jidibinlin** [comment]
* my config for .SpaceVim/coc-settings,json
```
 {
      "languageserver": {
          "ccls": {
              "command": "ccls",
              "filetypes": ["c", "cpp"],
               "rootPatterns":[".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
               "initializationOptions": {
                   "cache": {
                       "directory": "/tmp/ccls"
                   },
                   "highlight": {"lsRanges": true } 
               }
           }
       }
 }
```
"highlight": {"lsRanges: true"} is to enable the sementic highlight

**Comment by wsdjeg** [comment]
This can be done with lsp plugin, nothing need to be done with spacevim. BTW, not all language server support this feature.
