### ISSUE TITLE
One idea for a powerful integration of gdb/lldb to debugger language that they support

### ISSUE THREAD

**Issue by jidibinlin** [wsdjeg/SpaceVim#2958]
### Yesterday I find the [voltron.](https://github.com/snare/voltron) from GitHub. It`s a  extensible debugger UI toolkit written in Python.   
* For I think Voltron split different debugger messages(Registers,Disassembly,Stack Memory,Breakpoints,Backtrace) into different terminal and the message can cowork togather. The author use iterm to split terminal just like tmux. 
* So I think this thing for spacevim just create different shell windows in different position and show different debugger messages
* If this can be real. spacevim may have a powerful debugger for many languages for gdb/lldb can not only debug c/c++ but also python....

**Comment by wsdjeg** [comment]
Do you have a look at neodebug? It seems provide this features.

https://github.com/cpiger/NeoDebug
