### ISSUE TITLE
Menu with possible commands (Leader Guide?) is not displayed

### ISSUE THREAD

**Issue by actionless** [wsdjeg/SpaceVim#296]
## The reproduce ways from Vim starting (Required!)

1) press Leader key

## Expected behavior, english is recommend

Expected result:
Menu with possible commands (Leader Guide?) is displayed
https://cloud.githubusercontent.com/assets/13142418/23339920/590f2e9a-fc67-11e6-99ec-794f79ba0902.png

Actual result:
nothing happens. However some command gets executed if i continue typing different keys after leader.

## Environment Information
- OS: Arch Linux
- vim version: 8.0.0329
- neovim version: 0.1.7

### SpaceVim Options :

```viml
g:spacevim_version = '0.2.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_hiddenfileinfo = 1
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store'
g:spacevim_use_colorscheme = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_enable_neocomplcache = 0
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_enable_debug = 0
g:spacevim_buffer_index_type = 0
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_unite_leader = 'f'
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', '
scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'unite', 'github', 'denite', 'ctrlp', 'au
tocomplete', 'nvim', 'linux', 'colorscheme']
g:spacevim_sidebar_width = 30
g:spacevim_enable_cursorline = 0
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/lie/.cache/vimfiles/'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 0
g:spacevim_enable_ycm = 0
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_max_column = 120
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file /home/lie/.SpaceVim/.SpaceVim.log does not exists, only log for current process will be shown!
```

**Comment by wsdjeg** [comment]
Press leader key, and wait for about 1s.

Leader guide should not be opened if you remember the shortcut, but only when you forgot what the shortcut is.

**Comment by actionless** [comment]
i am waiting but it not shows up, is there any `call` to open it explicitly?

**Comment by wsdjeg** [comment]
Does your plugins installation finished? SpaceVim should automatically install all the needed plugins.

**Comment by actionless** [comment]
mb i am just doing something wrong:

```
:call dein#install()

[dein] Target plugins are not found.
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.
```

and also i can see `startify` with SpaceVim logo and other plugins

**Comment by wsdjeg** [comment]
Default leader is `\`

**Comment by actionless** [comment]
yup, and as i told doing something like `\lp` or any other keybinding works, but menu never shows up, i am waiting for it long enough

**Comment by actionless** [comment]
btw, i have the same problem in both vim and nvim

**Comment by actionless** [comment]
mb only that plugin haven't installed correctly? how can i check that?

**Comment by wsdjeg** [comment]
@actionless can you check in vim `:LeaderGuide '\' `? it should open the menu.

**Comment by actionless** [comment]
yes, it opens

**Comment by wsdjeg** [comment]
so, how about type `\g` and wait for about 1s?

**Comment by actionless** [comment]
nothing

**Comment by wsdjeg** [comment]
so can you show me your custom config? it should be `~/.SpaceVim.d/init.vim`,

BTW, what is the result of `git -C ~/.SpaceVim/ status` in terminal.

**Comment by actionless** [comment]
no `~/.SpaceVim.d/init.vim`


```
$ git -C ~/.SpaceVim/ status
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working tree clean

 
$ git -C ~/.SpaceVim/ show
commit 1322b791e3de0dc5a21ac34e4fa945b933dee7ef
Merge: 3f37136 39854b1
Author: Wang Shidong <wsdjeg@users.noreply.github.com>
Date:   Sun Feb 26 21:15:10 2017 +0800

    Merge pull request #291 from SpaceVim/airline

    Add messletters api



$ cd ~/.SpaceVim

$ git pull origin dev
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 16 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
From https://github.com/SpaceVim/SpaceVim
 * branch            dev        -> FETCH_HEAD
   1322b79..7684509  dev        -> origin/dev
Updating 1322b79..7684509
Fast-forward
 autoload/vimfiler/columns/gitstatus.vim | 138 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 config/plugins/vimfiler.vim             |   3 +-
 docs/documentation.md                   |  18 +++++++++
 docs/sponsors.md                        |   5 +++
 4 files changed, 162 insertions(+), 2 deletions(-)
 create mode 100644 autoload/vimfiler/columns/gitstatus.vim
```


after i've updated to the latest, the problem not resolved, however, nvim is now loading about 10 seconds after this update

**Comment by wsdjeg** [comment]
sorry, my fault, but I think you should read `:h g:spacevim_realtime_leader_guide`, I have 
`let g:spacevim_realtime_leader_guide=1` in my custom config.

**Comment by wsdjeg** [comment]
The last update do not add any plugins, but a plugin for vimfiler, and it will not be loaded on startup, so I do not know why it need 10s.

**Comment by actionless** [comment]
because vimfiler is displayed by default

**Comment by wsdjeg** [comment]
I got it. git status need  long time , if your project is too big. so should this feature disabled by default?

**Comment by actionless** [comment]
idk, but it could be pretty inconvenient if opening the editor without specifying file as an argument from home as a working directory

**Comment by wsdjeg** [comment]
I have added an options `g:spacevim_enable_vimfiler_welcome`, it should works well.

**Comment by actionless** [comment]
thanks!
