### ISSUE TITLE
Is there any function to add a  language specific key mapping?

### ISSUE THREAD

**Issue by dindom999** [wsdjeg/SpaceVim#2960]
I know there is a way to add [SPC] mapping like 

    function! myspacevim#before() abort
        call SpaceVim#custom#SPCGroupName(['G'], '+TestGroup')
        call SpaceVim#custom#SPC('nore', ['G', 't'], 'echom 1', 'echomessage 1', 1)
    endfunction
    
But if I need to add a key mapping for `, f f` to `:!autopep8 --in-place %` when editing a python file, how to do it ?

**Comment by wsdjeg** [comment]
as I remember there is an issue discuss about this. https://github.com/SpaceVim/SpaceVim/pull/2868
