### ISSUE TITLE
please consider support offline installation

### ISSUE THREAD

**Issue by yudar1024** [wsdjeg/SpaceVim#2969]
**Is your feature request related to a problem? Please describe.**
I'd like to setup a spacevim in offline environment includs all plugins , but there's no guild in official site.  
**Describe the solution you'd like**
1 prvoide a guide to install spacevim with offline environment
2 due to all configuration in .Spacevim folder, please consider package the plugins in .Spacevim/plugins to support offiline installation senario
3 btw we use neovim.

**Comment by wsdjeg** [comment]
This is what you want: https://github.com/Gabirel/Hack-SpaceVim
