### ISSUE TITLE
vim-todo E488,  triling characters

### ISSUE THREAD

**Issue by leoatchina** [wsdjeg/SpaceVim#2980]
## Expected behavior, english is required
I am using [vim-todo](https://github.com/wsdjeg/vim-todo)  seperated from SpaceVim , and I have already fixed a bug by setting `g:spacevim_debug_level` to 0 in my config,  but this bug still happend 
![image](https://user-images.githubusercontent.com/4470821/62188490-2dbc5500-b39f-11e9-96ff-b01113d3c519.png)

## The reproduce ways from Vim starting (Required!)
Just do `:OpenTodo`,  without the framework of `SpaceVim`, it will rise an `E488` error `Trailing characters`.  
When vim8,  the error message will block  vim untill  I press any key, after that  the list workplace rise up.
In neovim3.8, accually this error also happend,  but disapear quickly so it  block nothing

## Screenshots
![image](https://user-images.githubusercontent.com/4470821/62188791-0914ad00-b3a0-11e9-965d-fce0cce96470.png)

**Comment by wsdjeg** [comment]
@leoatchina I think it is not a bug, `OpenTodo` command do not support argvs, so your mapping should be:

```
nnoremap <silent> <c-p>t :<c-u>OpenTodo<cr>
```

**Comment by wsdjeg** [comment]
Got it, it seems the plugin use an undefinded value

**Comment by leoatchina** [comment]
Ok, that works !

**Comment by leoatchina** [comment]
Still not work ...... the same bug

**Comment by wsdjeg** [comment]
I can not reproduce it. the mini vimrc is needed.

**Comment by leoatchina** [comment]
here after is the mini vimrc, I prefer to use `vim-plug`, and successfully installed `vim-todo`, the 
`error` rised when I do `:OpenTodo`,  while this plug **works**
```
set nocompatible
" use vim-plug to install plugs
set rtp=$HOME/.vim-plug,$VIMRUNTIME
let $PLUG_PATH = expand('$HOME/.vim/plug')
set rtp+=$PLUG_PATH
call plug#begin($PLUG_PATH)
	if executable('rg')
	    Plug 'wsdjeg/vim-todo', {'branch': 'master'}
	endif
call plug#end()
```
