### ISSUE TITLE
Add vertical split keybinding option to FlyGrep

### ISSUE THREAD

**Issue by danshumaker** [wsdjeg/SpaceVim#2990]
**Is your feature request related to a problem?**
Related: https://github.com/SpaceVim/SpaceVim/issues/2946
Problem: Only Tab option to open a file from FlyGrep

**Describe the solution you'd like**

In the buffer search results (Quickfix) window of FlyGrep  `SPC srp`, I'd love to be able to open multiple files from the search results with a keybinding like `v` for vertical split or `h` for horizontal split - all the while keeping the quickfix search results window open. The only option to open a file is the tab key which then closes the search results.

**Describe alternatives you've considered**
The FlyGrep repo doesn't have issues turned on or would have submitted there:  https://github.com/wsdjeg/FlyGrep.vim

Also can't find where (or how) it's done in the other non-spacevim plugins I've used: 
https://github.com/rking/ag.vim/blob/master/autoload/ag.vim

But do see the usage here: https://vimawesome.com/plugin/ag-vim-back-to-december#keyboard-shortcuts

Config options don't seem documented here: https://spacevim.org/grep-on-the-fly-in-spacevim/

**Comment by wsdjeg** [comment]
It has been done. two key binding in flygrep `ctrl-s` and `ctrl-v`, we can not use `ctrl-h`, because it is same as `<BackSpace>`

**Comment by danshumaker** [comment]
Thanks so much @wsdjeg , however I don't see in the documentation how to get updates?  Do I re-install from scratch to get the latest code?  Thanks again.

**Comment by danshumaker** [comment]
:SPUpdate seemed to do the trick!  :)

**Comment by danshumaker** [comment]
@wsdjeg Trying this for the first time , the splits work but the other part of the feature request was 

> all the while keeping the quickfix search results window open. The only option to open a file is the tab key which then closes the search results.

Unfortunately, the search results goes away after you use the new `ctrl-s` or `ctrl-v` keys.  Can you keep the search results loaded please? 

It is VERY often the case that when I'm researching and searching for things I want to open three or four files from the search results.  The way the current code is functioning I'd have to do three or four different searches to get all the files I want loaded.

**Comment by wsdjeg** [comment]
do you have a try with neovim?

**Comment by danshumaker** [comment]
Just tried it with neovim, same results. The search window disappears.

https://asciinema.org/a/LAAjnsdvQ3Fk8CQxlrwAoDHTY

Is there an option or preference setting to keep it open?
