### ISSUE TITLE
Highlight last character of selection?

### ISSUE THREAD

**Issue by peidaqi** [wsdjeg/SpaceVim#2993]
**Is your feature request related to a problem? Please describe.**

By default, vim will not highlight the last character of a selection in visual mode, i.e.

![image](https://user-images.githubusercontent.com/18495787/62786706-27119a00-ba91-11e9-9ae1-0fc3c7a66450.png)

the cursor is at the last character 'f'. It is selected, but as the white cursor blinks, the background of this character shows black instead of yellowish white as the rest of the selection.

**Describe the solution you'd like**

As the cursor blinks, this character also shows a yellowish white background so it's easy to see where the selection is - consistent with any other modern editors.

**Describe alternatives you've considered**

**Additional context**

**Comment by wsdjeg** [comment]
which colorscheme are you using, I think it is a bug of colorscheme, I can not reproduce it in `one` colorscheme. and if you want to check it, you can add:

```toml
[options]
    colorscheme = 'one'
```
