### ISSUE TITLE
Custom status line color scheme?

### ISSUE THREAD

**Issue by TehNewbie** [wsdjeg/SpaceVim#2995]
Hi there! I hope you don't mind me not using the issue template. I just wanted to ask if there is a way to apply a custom theme to the status line. I was messing around with SpaceVim on a live session and don't have any screenshots, but from what I see, the status line stays the same when using a downloaded color scheme.
Take for example the "Tender" scheme. I added it with the [[custom_plugins]] section and it worked, but the status line didn't change. It was still "Gruvbox" themed if I am not mistaken.
Again, I didn't use the bug report template, as I am not quite sure if it really is a bug, or if I was missing something. Thanks in advance! :smile:

**Comment by wsdjeg** [comment]
In the doc, you can see it:

https://spacevim.org/documentation/#colorschemes

**Comment by TehNewbie** [comment]
Thank you for trying to help, but I've actually read this section before. You see, when I add your official "colorscheme" layer, and add a theme from it, like "molokai", both the main window and status bar change, everything works fine. But if I add a custom, downloaded color scheme (with the "custom_plugins" section), the status bar stays the same. Sorry if I'm missing something obvious.

**Comment by wsdjeg** [comment]
you need to use colorscheme template.

**Comment by TehNewbie** [comment]
Alrighty, I took another look at the doc, and now I see what you mean. Looks like I was a bit tired yesterday, hah :smile: 
I'll poke around it some more. Seems like the issue is solved, I'll go ahead and close it. Keep up the good work!
