### ISSUE TITLE
Status bar icons get cut off in GVim.

### ISSUE THREAD

**Issue by TehNewbie** [wsdjeg/SpaceVim#2997]
## Expected behavior, english is required
The icons of status bar should appear normally, without being cut off.

## The reproduce ways from Vim starting (Required!)
Just run GVim with SpaceVim installed.

## Debug info
I'm using vanilla SpaceVim installation on Manjaro. The only thing I changed was the font of GVim. The issue appears with other fonts as well.

## Screenshots
Here's Vim running in Konsole with the Iosevka Nerd Font:
![konsole](https://user-images.githubusercontent.com/5496550/62839040-0c077b80-bc85-11e9-9abc-e809dafd26cf.png)

Here we have GVim with the same font:
![gvim](https://user-images.githubusercontent.com/5496550/62839042-10339900-bc85-11e9-931d-c18a6b3a7f07.png)

Here's Konsole again, this time with Hack Nerd Font:
![konsole1](https://user-images.githubusercontent.com/5496550/62839043-145fb680-bc85-11e9-8f2f-d8bc8b7b60a7.png)

And here's GVim once more:
![gvim1](https://user-images.githubusercontent.com/5496550/62839045-175aa700-bc85-11e9-81f6-1372f6d8be0d.png)

The top bar also has this problem. Here's Konsole without the cut off icon:
![konsole2](https://user-images.githubusercontent.com/5496550/62839115-ea5ac400-bc85-11e9-9ddd-aeec5f308e58.png)

And here's GVim:
![gvim2](https://user-images.githubusercontent.com/5496550/62839121-f5adef80-bc85-11e9-9dde-134b0d3444a9.png)

Not a very noticeable quirk, but I thought I'd report it anyway.

**Comment by wsdjeg** [comment]
It seems issue with fonts, I can not fix it.
