### ISSUE TITLE
Crash when edit file

### ISSUE THREAD

**Issue by xhzzhang** [wsdjeg/SpaceVim#3001]
## Expected behavior, english is required
Works well.

## The reproduce ways from Vim starting (Required!)
Spacevim was crashed when type number after '=' or type other code under editing mode

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

Vim: Caught deadly signal SEGV
Vim: preserving files...
Segmentation fault

**Comment by wsdjeg** [comment]
I can not debug it without log
