### ISSUE TITLE
Is there some plugin in spacevim can de the thing similar to codeglance?

### ISSUE THREAD

**Issue by hongyi-zhao** [wsdjeg/SpaceVim#3013]
Hi,

Is there some plugin can let vim embeded a code minimap similar to the one found in Sublime/idea into the editor pane? 

Say, similar to the following one doing for jetbrains tools:
https://plugins.jetbrains.com/plugin/7275-codeglance/

Regards

**Comment by wsdjeg** [comment]
no, as I know vim do not support this feature.
