### ISSUE TITLE
I always get error messages when I type text

### ISSUE THREAD

**Issue by jiahao-jayden** [wsdjeg/SpaceVim#3017]
## My_error
I always get error messages when I type text
## Screenshots
![myUpNT.png](https://s2.ax1x.com/2019/08/24/myUpNT.png)

**Comment by wsdjeg** [comment]
same as https://github.com/SpaceVim/SpaceVim/issues/2264

**Comment by wsdjeg** [comment]
I have fixed this issue, you can update spacevim.
