### ISSUE TITLE
Differences between myspacevim#init and myspacevim#before

### ISSUE THREAD

**Issue by hongyi-zhao** [wsdjeg/SpaceVim#3018]
Hi,

I noticed that in the document, for bootstrap functions, the examples names are as follows:

myspacevim#init
myspacevim#before
myspacevim#after

Since we only have two type of bootstrap functions, namely `bootstrap_before` and `bootstrap_after`.  So, what's the differences between myspacevim#init and myspacevim#before when using for functions name?

Regards

**Comment by wsdjeg** [comment]
please use gitter for asking question about this, this is not a feature request or even a bug report.
