### ISSUE TITLE
How can i disable VimFiler for creating window on the startup?

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [wsdjeg/SpaceVim#302]
How can i disable VimFiler for creating window on the startup?

## Environment Information
- OS: Mac 10.12
- vim version: 8.0
- neovim version: 1.7

## The reproduce ways from Vim starting (Required!)
this is the default behavior

**Comment by wsdjeg** [comment]
`:h g:spacevim_enable_vimfiler_welcome`

**Comment by CodeMonkeyKevin** [comment]
Thx Mister

**Comment by wsdjeg** [comment]
welcome.
