### ISSUE TITLE
Please close Neomake in c/c++ layer for what LSP with ccls backened already have syntax check

### ISSUE THREAD

**Issue by jidibinlin** [wsdjeg/SpaceVim#3026]
**Spacevim have more than one syntax check for c/c++ layer**
* Neomake
* LSP with ccls backened 
![Neomake has Been closed](https://user-images.githubusercontent.com/38578679/63769746-2177d900-c906-11e9-9cde-852d26741b99.png)
I closed Neomake in this picture. LSP do this best for c/c++ layer.

**Comment by jidibinlin** [comment]
I find when I closed the neomake the icon for locating the error line will lose color like this
![2019-08-27_20-14](https://user-images.githubusercontent.com/38578679/63770310-79630f80-c907-11e9-9014-f2c71eeae60a.png)

**Comment by wsdjeg** [comment]
why do not use issue template, and which lsp plugin do you use?

**Comment by jidibinlin** [comment]
spacevim built in

**Comment by jidibinlin** [comment]
![2019-08-27_21-09](https://user-images.githubusercontent.com/38578679/63774209-56d4f480-c90f-11e9-8d08-4df72943ac6f.png)
my config for c/c++

**Comment by jidibinlin** [comment]
Sorry! I readed Doc wroted in chinese for the last time. I read the Doc wroted in English right now. I find chinese Doc quite different with english Doc. So I have a mistake when answer which lsp plugin I use.It`s my fault.

I just use LanguageClient-neovim.

**Comment by wsdjeg** [comment]
you can disable checker layers:

```
[[layers]]
    name = "checkers"
    enable = false
```
