### ISSUE TITLE
SPC s l always returns empty

### ISSUE THREAD

**Issue by ghedamat** [wsdjeg/SpaceVim#3027]
## Expected behavior, english is required

Hey there, if my read of the documentation and the help is correct

`SPC s l` after a successful search (i.e with `SPC s /`) should show the last search results

I was not able to get this to work on multiple spacevim installs, the quickfix buffer is always empty when I access it using `SPC s l`

## The reproduce ways from Vim starting (Required!)

* do a search with `SPC s /`
* see result
* press enter on one result
* type `SPC s l` and observe an empty list

## Debug info
I tried on a plain spacevim install with no custom options activated

## Notes

apologies if I'm misunderstanding the feature

thanks for the great project!

**Comment by wsdjeg** [comment]
as I know. SPC s l and SPC e l is to open quickfix list.

the issue is both searching plugin and lint plugin are using quickfix list.
