### ISSUE TITLE
"Unknown function: vimfiler#custom#profile" error when startup vim.

### ISSUE THREAD

**Issue by CrisLi** [wsdjeg/SpaceVim#303]
## Environment Information
- OS: 10.11.6
- vim version: 8.0.386
- neovim version:

## The reproduce ways from Vim starting (Required!)

 $ curl -sLf https://spacevim.org/install.sh | bash
 $ curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
 $ sh ./installer.sh ~/.cache/dein
 $ vim
[dein] Error occurred while executing hook: vimfiler.vim
[dein] Vim(call):E117: Unknown function: vimfiler#custom#profile
Press ENTER or type command to continue

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

:call dein#install()
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.

**Comment by wsdjeg** [comment]
vimfiler has not been installed. you should not install dein manually.

**Comment by CrisLi** [comment]
I am following the install document, there is no place mentioned I should install `vimfiler` first.

@wsdjeg 

Do you mean I should install `vimfiler` manually after I run `$ curl -sLf https://spacevim.org/install.sh | bash` ?

**Comment by wsdjeg** [comment]
SpaceVim will automatically install all plugins when vim  start up.
