### ISSUE TITLE
where is my original vimrc and .vim/ ?

### ISSUE THREAD

**Issue by opriz** [wsdjeg/SpaceVim#3039]
I have tried to use spacevim. But just cannot find my original vimrc at ~/.vimrc, nor old things in ~/.vim/
I don't have a complete backup on these things.It's really frustrated if i just lost them.I spent a lot of time on them.
If spacevim will remove these things, why not report a warning when install ? And why don't make spacevim just compatible with users' original settings?

**Comment by wsdjeg** [comment]
please read the installation message, it print a message like:

```
Backup $HOME/.vimrc to $HOME/.vimrc_back
```

**Comment by wsdjeg** [comment]
and `~/.vim` should be `~/.vim_back`

**Comment by opriz** [comment]
@wsdjeg thanks for telling. 
I tried to install again, there sure be a backup message.But i think backup messages are more important for users than many other ones, recommand to change a color and update readme.
BTW, I didn't find ways to fully uninstall spacevim in docs until got  #1845. 
Spacevim is really a nice editor, but there are many improvements could be done for documentations for new users.
I' ll try for some time, If I really like it I'd like to do something for this project.

**Comment by wsdjeg** [comment]
thanks you. I will update the quick start guide about it.
