### ISSUE TITLE
Short of .SpaceVim.d

### ISSUE THREAD

**Issue by hongjiujin** [wsdjeg/SpaceVim#305]
## Expected behavior, english is recommend
Short of .SpaceVim.d directory after install

## Environment Information
- OS:Ubuntu14.04
- vim version:7.4.52 through apt-get 
- neovim version:

## The reproduce ways from Vim starting (Required!)
After install package

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.
[tommy@tommy-VirtualBox ~]$curl -sLf https://spacevim.org/install.sh | bash
Cloning into '/home/tommy/.SpaceVim'...
remote: Counting objects: 3324, done.
remote: Compressing objects: 100% (168/168), done.
remote: Total 3324 (delta 104), reused 0 (delta 0), pack-reused 3126
Receiving objects: 100% (3324/3324), 757.46 KiB | 4.00 KiB/s, done.
Resolving deltas: 100% (2157/2157), done.
Checking connectivity... done.
Successfully clone SpaceVim
Installed SpaceVim for vim
Installed SpaceVim for neovim

[tommy@tommy-VirtualBox ~]$ls -al
total 1756
drwxr-xr-x 42 tommy tommy   4096 Mar  2 10:19 .
drwxr-xr-x  3 root  root    4096 Sep  2 09:38 ..
drwx------  3 tommy tommy   4096 Sep  2 11:08 .adobe
drwxrwxr-x  3 tommy tommy   4096 Mar  2 09:49 autoload
-rw-------  1 tommy tommy  28089 Mar  2 09:36 .bash_history
-rw-r--r--  1 tommy tommy    220 Sep  2 09:38 .bash_logout
-rw-r--r--  1 tommy tommy   3829 Feb 24 18:07 .bashrc
drwxrwxr-x  2 tommy tommy   4096 Dec 22 14:35 bin
drwxr--r--  2 tommy tommy   4096 Dec 13 17:56 .byteexec
drwx------ 27 tommy tommy   4096 Mar  1 15:33 .cache
drwx------  3 tommy tommy   4096 Sep  2 09:48 .compiz
drwxrwxr-x  3 tommy tommy   4096 Mar  2 09:49 config
drwx------ 23 tommy tommy   4096 Feb 28 10:17 .config
drwxr-xr-x  5 tommy tommy   4096 Feb 28 11:06 .data
drwx------  3 tommy tommy   4096 Sep  2 09:48 .dbus
-rw-r--r--  1 tommy tommy     25 Sep  2 15:13 .dmrc
drwxrwxr-x  2 tommy tommy   4096 Mar  2 09:49 doc
drwxrwxr-x  3 tommy tommy   4096 Mar  2 09:49 docs
drwxr-xr-x  2 tommy tommy   4096 Sep  2 11:10 Downloads
-rw-r--r--  1 tommy tommy   8980 Sep  2 09:38 examples.desktop
drwxrwxr-x  2 tommy tommy   4096 Sep 19 12:31 .fonts
drwx------  3 tommy tommy   4096 Mar  2 09:36 .gconf
-rw-rw-r--  1 tommy tommy     81 Dec 22 09:00 .gitconfig
drwx------  2 root  root    4096 Feb 15 09:38 .gvfs
drwxrwxr-x  3 tommy tommy   4096 Sep  2 15:17 .ibus
-rw-------  1 tommy tommy  29718 Mar  2 09:36 .ICEauthority
-rwxrwxrwx  1 root  root     240 Nov 21 10:50 .kermrc
drwxr-xr-x  4 tommy tommy   4096 Oct 26 09:36 kgtp
drwxrwxr-x  4 tommy tommy   4096 Dec 13 17:57 .lantern
-rw-------  1 tommy tommy     81 Feb 15 16:43 .lesshst
drwx------  5 tommy tommy   4096 Sep 19 12:30 .local
drwxrwxr-x  2 tommy tommy   4096 Nov 25 13:26 log
drwx------  3 tommy tommy   4096 Sep  2 11:08 .macromedia
-rw-r--r--  1 tommy tommy 697184 Mar  2 09:40 minicom.log
-rw-r--r--  1 tommy tommy 697184 Dec  2 10:18 minicom.log~
-rw-r--r--  1 tommy tommy     75 Nov 21 10:39 .minirc.dfl
drwx------  4 tommy tommy   4096 Sep  2 11:08 .mozilla
drwxrwxr-x  4 tommy tommy   4096 Mar  1 15:31 mygithub
-rw-rw-r--  1 tommy tommy    253 Sep 23 12:38 notes
-rw-r--r--  1 tommy tommy    259 Sep  2 15:14 .pam_environment
-rw-r--r--  1 tommy tommy    748 Sep 19 12:31 .profile
drwxrwxr-x  2 tommy tommy   4096 Jan 17 16:57 .qemu-launcher
drwxrwxr-x  3 tommy tommy   4096 Oct 10 10:03 .repoconfig
-rw-rw-r--  1 tommy tommy      2 Dec 13 17:33 .repo_.gitconfig.json
-rw-rw-r--  1 tommy tommy    105 Dec 22 09:00 .repopickle_.gitconfig
drwxr-xr-x  2 tommy tommy   4096 Feb 28 13:49 .rpmdb
**drwxrwxr-x  8 tommy tommy   4096 Mar  2 10:18 .SpaceVim**
-rw-rw-r--  1 tommy tommy    913 Nov 22 10:07 .tmux.conf
drwxrwxr-x  4 tommy tommy   4096 Nov 21 11:10 .vandyke
-rw-r-----  1 tommy tommy      5 Mar  2 09:36 .vboxclient-clipboard.pid
-rw-r-----  1 tommy tommy      5 Mar  2 09:36 .vboxclient-display.pid
-rw-r-----  1 tommy tommy      5 Mar  2 09:36 .vboxclient-draganddrop.pid
-rw-r-----  1 tommy tommy      5 Mar  2 09:36 .vboxclient-seamless.pid
lrwxrwxrwx  1 tommy tommy     21 Feb 28 10:17 .vim -> /home/tommy/.SpaceVim
drwxr-xr-x  3 tommy tommy   4096 Feb 13 11:06 .vim_back
-rw-------  1 tommy tommy  15523 Mar  2 10:19 .viminfo
-rw-rw-r--  1 tommy tommy    347 Feb 20 11:03 .vimrc_back
drwxrwxr-x 10 tommy tommy   4096 Feb  3 13:57 workbench
-rw-------  1 tommy tommy     61 Mar  2 09:36 .Xauthority
drwxrwxr-x  2 tommy tommy   4096 Sep  2 15:03 .xinput.d
-rw-rw-r--  1 tommy tommy    131 Sep  2 11:24 .xinputrc
-rw-------  1 tommy tommy     35 Mar  2 09:36 .xsession-errors
-rw-------  1 tommy tommy    821 Mar  2 09:36 .xsession-errors.old
-rw-rw-r--  1 tommy tommy  35211 Feb 28 14:00 .zcompdump

**Comment by wsdjeg** [comment]
~/. SpaceVim is core code of spacevim
~/.vim is a link to it.
~/. SpaceVim.d/ is custom config dir. you need create it yourself.
