### ISSUE TITLE
Support Go debugger

### ISSUE THREAD

**Issue by mna** [wsdjeg/SpaceVim#3054]
**Is your feature request related to a problem? Please describe.**
Regarding the core pillars, the behaviour of the `debug` layer is inconsistent. AFAIK, it only works for Ruby and Python (?), it would be nice to add support for other languages - the one I'm most interested in is Go so I'm opening the issue for that one, as Go has a decent debugger in Delve (https://github.com/go-delve/delve).

**Describe the solution you'd like**
When activating the `debug` layer, the behaviour described in https://spacevim.org/layers/debug/ works for Go via the Delve debugger.

Thanks,
Martin

**Comment by wsdjeg** [comment]
This will be done in wsdjeg/vim-debug, it is included in debug layer.

**Comment by mna** [comment]
Note that there's https://github.com/sebdah/vim-delve that exists, might be helpful as inspiration.

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/vim-debug/pull/1

**Comment by mna** [comment]
🎉looking forward to trying this out! Thanks a lot!

**Comment by masihtehrani** [comment]
> **Is your feature request related to a problem? Please describe.**
> Regarding the core pillars, the behaviour of the `debug` layer is inconsistent. AFAIK, it only works for Ruby and Python (?), it would be nice to add support for other languages - the one I'm most interested in is Go so I'm opening the issue for that one, as Go has a decent debugger in Delve (https://github.com/go-delve/delve).
> 
> **Describe the solution you'd like**
> When activating the `debug` layer, the behaviour described in https://spacevim.org/layers/debug/ works for Go via the Delve debugger.
> 
> Thanks,
> Martin

I have same your problem and my debug mod not work on golang
https://asciinema.org/a/aTExJJD4074QO7OTopNP6q3zv
