### ISSUE TITLE
deoplete and denite backward compatibility

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#3057]
## Expected behavior, english is required

deoplete key bindings should works well in all version!

```
E117: Unknown function: deoplete#mappings#smart_close_popup
```

**Comment by wsdjeg** [comment]
@Shougo I think the development of plugin should keep backward compatibility, currently I get too many error about deoplete and denite, and I am not sure if defx is same. I do not update my plugins all days, maybe 3-4 month.

now, I need to fork a old version to make spacevim works well.

**Comment by Shougo** [comment]
@wsdjeg Please read `:help deoplete-compatibility`.
The backward compatibility problem is already documented.

For example:

```
2019.07.16
* Remove old deoplete#mappings# mappings.  You need to use new mappings.
```

And in the new API exists long time ago.

Note:  This is not bug.

**Comment by Shougo** [comment]
Why SpaceVim cannot use new APIs?
It is very important to follow upstream.

For example:  You have not tested new APIs in denite.
Other users have tested.

The same problem may be occurred in other plugins.
My plugins may be changed frequently than other plugins.
But you have decided to use my plugins in SpaceVim.

**Comment by jyscao** [comment]
Since I'm a heavy deoplete user, I can help out with maintenance on the SpaceVim side if @wsdjeg doesn't have time. I'd definitely prefer SpaceVim followed deoplete changes instead of maintaining an older fork of it.

**Comment by wsdjeg** [comment]
@Shougo @dyno OK，Thanks, I will use the upstream version now, the issue is:

1. in current version of spacevim, some deoplete key bindings does not works, I do not know how many APIs have been chaneged, I need to check the doc.

2. all denite keybinding config does not work, 

3. denite layer is broken now.

**Comment by wsdjeg** [comment]
BTW, we need a API to tell me which version of deoplete I am using. then I can use:

```
if deoplete#version() >= xxx
  use new api
else
  use old one
endif

**Comment by Shougo** [comment]
https://github.com/SpaceVim/SpaceVim/issues/3057#issuecomment-531555345

You should check existing function instead.

`if exists('*deoplete#smart_close_popup')`

**Comment by wsdjeg** [comment]
before the script `autoload/deoplete.vim` is loaded, this function always return 0, even if it is new version.

________________________________
--
Best regards,
wsdjeg

**Comment by Shougo** [comment]
> all denite keybinding config does not work,

You should check `denite#get_status_mode()` exists.
It is removed in the new version.

**Comment by Shougo** [comment]
> before the script `autoload/deoplete.vim` is loaded, this function always return 0, even if it is new version.

Yes.  So you should call `deoplete#initialize()` before that.

But I don't think the check is needed.
You should replace new mappings.
It exists long ago.

**Comment by Shougo** [comment]
In denite, you need to replace current layer especially mappings.

**Comment by wsdjeg** [comment]
I have merged that PR, but the kay mapping for denite is still not fixed, I can not fix it now, because I do not understand current version of denite.

1. I want to start insert mode by default, `call denite#custom#option('default', {'start-filter' : 1 })` does not work.

2. I want highlight the cursor line when in insert mode, in current verison of denite, insert mode mean filter mode, which is in a new windows (new buffer), so the `set cursorline` does not work, or maybe it is changed by autocmd, I always disable cursorline of other windows, only enable cussorline for current windows.

3.  in filter mode, can not use `tab` `shift-tab` to run same key binding just like <denite:move_to_next_line>.

4. in filter mode, can not use Enter to do open action.

________________________________
--
Best regards,
wsdjeg

**Comment by Shougo** [comment]
> 1. I want to start insert mode by default, `call denite#custom#option('default', {'start-filter' : 1 })` does not work.

```vim
call denite#custom#option('default', {'start_filter' : 1 })
```

> 2. I want highlight the cursor line when in insert mode, in current verison of denite, insert mode mean filter mode, which is in a new windows (new buffer), so the `set cursorline` does not work, or maybe it is changed by autocmd, I always disable cursorline of other windows, only enable cussorline for current windows.

```vim
autocmd FileType denite-filter setlocal cursorline
```

> 3.  in filter mode, can not use `tab` `shift-tab` to run same key binding just like `<denite:move_to_next_line>`.

```
Q: I want to move the cursor in a Denite filter window, while in insert mode.

A: Really? It is not the Vim way to move the cursor while in insert mode. You
must force this behaviour. >

	autocmd FileType denite-filter call s:denite_filter_my_settings()
	function! s:denite_filter_my_settings() abort
	  inoremap <silent><buffer> <C-j>
	  \ <Esc><C-w>p:call cursor(line('.')+1,0)<CR><C-w>pA
	  inoremap <silent><buffer> <C-k>
	  \ <Esc><C-w>p:call cursor(line('.')-1,0)<CR><C-w>pA
	endfunction

Note: This is very slow in Vim8 environment. See the |denite-examples| for an
example mapping from insert mode to filter mode.
```

> 4. in filter mode, can not use Enter to do open action.

```
Q: I want to call default action in denite filter window.

A: >

	autocmd FileType denite-filter call s:denite_filter_my_settings()
	function! s:denite_filter_my_settings() abort
	  inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
	endfunction
```

Please read the documentation.

**Comment by wsdjeg** [comment]
@Shougo I have fix the denite support in spacevim, both old and new version of denite.

**Comment by Shougo** [comment]
Thanks
