### ISSUE TITLE
git layer should be improved

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#306]
we should use more stable plugin, and I do not want to change the url every mounth, as development of vim-gita is closed, I should found out a new plugin, so anyone can show me recommendation?

what are the plugins I have used?
1. [fugitive](https://github.com/tpope/vim-fugitive): I do not want to use `system()` and `:!git`.
2. [vimagit](https://github.com/jreybert/vimagit):
3. [gita](https://github.com/lambdalisue/vim-gita): development is closed
4. [gina](https://github.com/lambdalisue/gina.vim): will have a try

**Comment by wsdjeg** [comment]
@lambdalisue Hi I am Shidong Wang, I wang to use your plugin as default git layer, but does gina support old version vim? I need a stable version git plugin.

**Comment by lambdalisue** [comment]
What did you mean by old? As README said, gina supports Vim 8.0.027 or above or Neovim 0.1.7 or above. While gina is an **asynchronous** git plugin which requires a **job** feature, this is a minimum version and gina will never support older one.

**Comment by lambdalisue** [comment]
Additionally, note that gina.vim is in a beta phase and behaviors might be changed without backward compatibility.

The first production version will be released when I finish

1. Add statusline/tabline component (WIP)
2. Add command completion
3. Reconsider and settle `Gina commit` behavior
4. Refactoring the internal code (exporting self-vital modules to external vital modules)

**Comment by wsdjeg** [comment]
got it, thanks, so I need to use gita for vim7.4, and gina for vim8. as SpaceVim is a vim distribution, it should support vim7.4, so I will not remove gita.

thanks for all your work.

**Comment by lambdalisue** [comment]
OK. Note that you need to do `let g:gita#suppress_warning = 1` to suppress a warning message.

https://github.com/lambdalisue/vim-gita/blob/master/autoload/gita.vim#L38
