### ISSUE TITLE
Vimproc build faild

### ISSUE THREAD

**Issue by floatval** [wsdjeg/SpaceVim#3060]
Using *isntall.sh* to automatic SpaceVim 1.30, all plugins can install well but vimproc.
I read vimproc docs, It said when you need to complex it , **Must as root to run make**.
Then i get in 

>  ~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim
Then run ** sudo make ** , can build vimproc.

**Comment by Shougo** [comment]
I think root build is not needed.
I have checked vimproc documentation, but `sudo make` is not documented.

What is the error messages?

**Comment by floatval** [comment]
> I think root build is not needed.
> I have checked vimproc documentation, but `sudo make` is not documented.
> 
> What is the error messages?

Thanks for you replyling.
Sorry,  I cann't reproduct it. And i don't remeber that wrong message...
By the way, it maybe says make[1]*** somemessage ** 😂

**Comment by Shougo** [comment]
Oh.  OK

**Comment by duytrung** [comment]
Hi Shougo,

I have the same issue on linux AntiX 19.2. How to fix this?
Thanks a lot
Ps: I found there is no need to use sudo/su to install on AntiX as all installations are based on user's folder. If I have to install with admin rights then when I use the program I have to use as super user.
Sorry but the system I'm using is quite old and I don't mind to upgrade to newer version of Windows. Instead, I use Linux AntiX version 19 for general web browsing and learn to use Vim/Emacs.
