### ISSUE TITLE
How can i install release version not dev version.

### ISSUE THREAD

**Issue by Heono** [wsdjeg/SpaceVim#3068]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

I tried to install spacevim with ' curl -sLf https://spacevim.org/install.sh | bash' command. but this command installed 1.3.0-dev version not 1.2.0 release version. How can i install release version? 
![image](https://user-images.githubusercontent.com/30615629/65156521-36a9d880-da6a-11e9-98e0-1e8270e497c7.png)

**Comment by wsdjeg** [comment]
you can checkout the tag in the repo:

```
cd ~/.SpaceVim
git checkout v1.2.0
```
