### ISSUE TITLE
Solarized palette not working in leaderGuide in nvim

### ISSUE THREAD

**Issue by stfl** [wsdjeg/SpaceVim#3072]
The solarized colors are not working for the leaderGuide.
I am using NeoSolarized and the colors look like the following.
I tried to change the values in `autoload/SpaceVim/mapping/guide/theme/solarized.vim` but these values don't seem to be considered at all.

I tried with gui colors as well as without and double checked for terminal true color support

![image](https://user-images.githubusercontent.com/1321542/65269128-d887fe80-db18-11e9-98ca-5a320b50e936.png)

**Comment by stfl** [comment]
I just checked in vim 8.1 the leaderGuide is displayed correctly

**Comment by wsdjeg** [comment]
can you reproduce it in latest version of neovim and vim?

--
Best regards,
wsdjeg

**Comment by stfl** [comment]
I am seeing the problem with nvim 0.3.8 from the repo and with nvim 0.4.2 appimage.

**Comment by wsdjeg** [comment]
seems this issue only huppend in neovim, it works well in gvim for me.

**Comment by wsdjeg** [comment]
@stfl It seems not a bug of SpaceVim, in the guide buffer, the hilight is definded by syntax file:

https://github.com/SpaceVim/SpaceVim/blob/master/syntax/leaderGuide.vim

in this file, we use hightligh group: Identifier, Type, Type and SpaceVimLeaderGuiderGroupName.

the SpaceVimLeaderGuiderGroupName is definded by:

```
  hi SpaceVimLeaderGuiderGroupName cterm=bold ctermfg=175 gui=bold guifg=#d3869b
```

**Comment by stfl** [comment]
And you can confirm that in nvim these hi groups are actually in use for the leader buffer?
How can I check this myself?

**Comment by wsdjeg** [comment]
The reproduce step is:

1. run `nvim text.txt`
2. run `:colorscheme NeoSolarized`
3. run `:set ft=leaderGuide`
4. insert text to current buffer:

```
[s] sss   [s] sss
[s] sss   [s] sss
[s] +ss   [s] sss
```

5. run `:set winhighlight=Normal:Pmenu`

**Comment by stfl** [comment]
Thanks for fixing this.
