### ISSUE TITLE
Permission denided error when using Docker image

### ISSUE THREAD

**Issue by krisleech** [wsdjeg/SpaceVim#3073]
## Expected behavior, english is required

When running docker container I do not get permission denied error when it tries to write config on start.

## The reproduce ways from Vim starting (Required!)

```
docker pull spacevim/spacevim
docker run -it -v ~/.SpaceVim.d:/home/spacevim/.SpaceVim.d --rm spacevim/spacevim nvim
```

```
Error detected while processing function SpaceVim#custom#autoconfig[6]..<SNR>94_menu[35]..<SNR>25_basic_mode[4]..<SNR>25_write_to_config:
line   13:
E482: Can't open file /home/spacevim/.SpaceVim.d/init.toml for writing: permission denied
```

It does seem the local directory, on the host machine, `~/.SpaceVim.d` is created, but is empty.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by krisleech** [comment]
![26256](https://user-images.githubusercontent.com/66143/65323118-7246be80-dba0-11e9-84f4-c714dfc555c5.png)

**Comment by wsdjeg** [comment]
sorry, I do not use docker, hope some can help.

**Comment by ghost** [comment]
It’s because the user in the container doesn’t have permissions to write to you local user home directory. You either need to explicitly grant write permissions to the uid/gid of the container user or mount a directory that the user can write to.

**Comment by ghost** [comment]
This can be closed. It’s Docker problem, not a Spacevim issue.
