### ISSUE TITLE
happen core dumped when make build on docker direction

### ISSUE THREAD

**Issue by woaitubage** [wsdjeg/SpaceVim#3077]
I'm new for docker and spacevim. but love using docker build spacevimbut .
but when I build Dockerfile for SpaceVim on centos 7.6.1810,.
this kernel of system  is Linux k8s-master 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

this is errror info:
Step 14/16 : RUN nvim --headless +'call dein#install()' +qall
 ---> Running in c3c0826f42ad

Error detected while processing /home/spacevim/.SpaceVim/autoload/SpaceVim/layers/tmux.vim:
line  121:
E121: Undefined variable: g:spacevim_statusline_inactive_separator
E15: Invalid expression: g:spacevim_statusline_inactive_separator
Error detected while processing function SpaceVim#custom#load[16]..SpaceVim#custom#apply:
line   24:
E171: Missing :endif
Error detected while processing function SpaceVim#custom#load:
line   16:
E171: Missing :endifError detected while processing command line:
E117: Unknown function: dein#installnvim: ../src/nvim/message.c:2231: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
Aborted (core dumped)
The command '/bin/sh -c nvim --headless +'call dein#install()' +qall' returned a non-zero code: 134
make: *** [build] Error 134
who have some solution for me ,thank you.

**Comment by wsdjeg** [comment]
make sure you you have ability to read your docker file.
