### ISSUE TITLE
Clean install on Ubuntu (Server), vimfiler command not being found

### ISSUE THREAD

**Issue by regiellis** [wsdjeg/SpaceVim#3095]
## Expected behavior, english is required
On a clean install, being the default, providing there are not install errors on 
initial launch, and the default configuration is used; Spacevim should launch 
with the ability to navigate files via vimfiler.

##The reproduce ways from Vim starting (Required!)
Under OS Ubuntu 18.04.3
Use the provided quick start instructions provided in the Spacevim quick start documentation
Start and verify that all plugins are installed with no error messages; e.g. all green check marks

## Debug info
Unable to do this as of this initial report as I am working in Blink via and iPad connect to a Digital Ocean
Server. Will follow up this report with a comment contenting the debug information.

## Screenshots
See above; 

## Notes
This is error only occurs when working on my iPad Pro when connected via Blink to the external server. On my Ubuntu shell I am running .oh-my-zsh with no plugins and a base bones development server. All build tools are installed and brew is used to install other libs or programs. No additional layers are added or loaded in Spacevim and not her other settings have been changed or added. This seems to happen in both vim and nvim.

* Forget any typos as Siri is very pushy about adding its creative writing style on what I type.

**Comment by wsdjeg** [comment]
is there any error message or screenshort, I can not understand what the issue is about. you can not user filetree (key binding is F3).

**Comment by regiellis** [comment]
### Debug Info
[debug.txt](https://github.com/SpaceVim/SpaceVim/files/3668435/debug.txt)

### Screenshots
<img width="1923" alt="Screen Shot 2019-09-29 at 9 21 34 PM" src="https://user-images.githubusercontent.com/1148310/65843351-4396b980-e2ff-11e9-9221-2fc937c5fd99.png">
<img width="1929" alt="Screen Shot 2019-09-29 at 9 13 18 PM" src="https://user-images.githubusercontent.com/1148310/65843352-442f5000-e2ff-11e9-9d75-4dbf622ffa14.png">

This is on a clean install, no changes to the configuration.

**Comment by Shougo** [comment]
vimfiler is not installed or loaded.

**Comment by regiellis** [comment]
> vimfiler is not installed or loaded.

Yes I know, however, when installing and launching SpaceVim for the first time... I can see that VimFiler is installed on the plugins run. Is this only a hook for SpaceVim to work with VimFiler, does it need to be installed manually?

**Comment by wsdjeg** [comment]
I think your plugin vimfiler is failed to installed. please run `:SPReinstall vimfiler.vim`.

**Comment by regiellis** [comment]
Unfortunately this does not fix the issue... I have SpaceVim running fine on all my Macs, but all my ubuntu servers refuse to install vimfiler.

<img width="1366" alt="run mosh bynine_development zsh" src="https://user-images.githubusercontent.com/1148310/66053454-5d531f00-e500-11e9-91a3-fe2fda7fef20.png">

**Comment by wsdjeg** [comment]
vimfiler require unite.vim and vimproc.vim, I think maybe it is because your vimproc.vim has not been builded. I recommanded to run `:SPReinstall vimproc.vim unite.vim vimfiler.vim`. if everything is done, just run into dir: `~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim` and build vimproc.

**Comment by linusjf** [comment]
I have a similar issue or problem. On just executing vim without any filename, I have the same error message. Executing above update commands and executing make does not resolve the issue.
