### ISSUE TITLE
jedi-vim failed to initialize Python

### ISSUE THREAD

**Issue by Reveyer** [wsdjeg/SpaceVim#3097]
## Expected behavior, english is required
I have install jedi model, but get this error as follow

##### jedi-vim version

 - jedi-vim git version: b4b2f3e-dirty
 - jedi git submodule status: -005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi
 - parso git submodule status: -c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/home/dutir_2t/zhangbo/anaconda3/envs/chip/bin/python3`
 - global sys.version: `3.5.2 (default, Nov 23 2017, 16:37:01), [GCC 5.4.0 20160609]`
 - global site module: `/usr/lib/python3.5/site.py`
ERROR: could not import the "jedi" Python module: ImportError: No module named 'jedi'
  Traceback (most recent call last):
    File "/home/dutir_2t/zhangbo/.cache/vimfiles/jedi-vim/pythonx/jedi_vim.py", line 113, in <module>
      import jedi

##### Settings

```
  omnifunc=
  completeopt=menu,menuone,longest
        Last set from ~/.SpaceVim/autoload/SpaceVim/default.vim
```

**Comment by wsdjeg** [comment]
what is your vim version?

**Comment by Reveyer** [comment]
7.4的，是在学校服务器上，没有root权限
需要更新到8吗？

**Comment by wsdjeg** [comment]
It seems a issue or bug of upstream plugin, I can not fix it.

**Comment by wsdjeg** [comment]
the vim-jedi should handled this kind of error, and provide more debug info.
