### ISSUE TITLE
recommend plugin:vim-leader-guide

### ISSUE THREAD

**Issue by tracyone** [wsdjeg/SpaceVim#31]
[vim-leader-guide](https://github.com/hecal3/vim-leader-guide)

spacemacs like function:displays the available key bindings **automatically** and **dynamically**.

No need any config,just add following keymap.

```viml
# suppose leader is space
nnoremap <silent> <leader> :<c-u>LeaderGuide '<Space>'<CR>
vnoremap <silent> <leader> :<c-u>LeaderGuideVisual '<Space>'<CR>
```

**Comment by wsdjeg** [comment]
Thanks for recommanding plugin, will check it out, By default SpaceVim use `f<space>` to open mapping menu. and user can fuzzy find what he want by describtion, not only mapping itself, I think it should be more useful. and after fuzzy find mappings, just type enter to execute the mappings.

see this picture:

![2017-01-05-00 26 18](https://cloud.githubusercontent.com/assets/13142418/21649766/c3431e10-d2dd-11e6-83d9-553a9b3f462c.png)

**Comment by wsdjeg** [comment]
@tracyone I will add this feature.
SpaceVim Should has this feature, them we have two ways to find a mappings;
1. search mappings by `key`
2. search mappings by `description`

working on `improve leader` branch.

**Comment by wsdjeg** [comment]
I have add this plugin, the next work is to improve the comfig for this plugin.

**Comment by wsdjeg** [comment]
@zer4tul hi, I just see you send a PR to space-vim, use the vim-leader-guide to implement the leader guide layer. I think it is a nice feature.
    SpaceVim has a feature just like it, But I use unite to implement it, with this feature, user can fuzzy find the mapping he want by description or key sequence, after type the mapping, use `Enter` to execute this mapping.
    and I am not family with vim-leader-guide, some people want SpaceVim also has this feature, so I will add this plugin.
    before doing this, I should ask:
1. does vim-leader-guide use getchar() in while loop to find what the user is pressing? if so, It is not good idea. while loop maybe broken by errors in other job.
2. does vim-leader-guide use `echo` to build prompt? if so this feature maybe broken by message eached by other job, or if the message is to long, you will get `press ENTER or type command to continue` instead of prompt.

in the end, I really hope you can also support SpaceVim, thanks!

**Comment by zer4tul** [comment]
i can't answer these two questions now. i must dig into the code first. as i said in space-vim's PR, i will try to make it work like which-key in vim.

**Comment by wsdjeg** [comment]
@zer4tul I think most of the hotkey, user can remember it, the guider should not affect the useage of origin vim, so I create unite mapping guide. user can use the hotkey without affect from the guide. and if he do not remember it, he can use `f<space>` to open mappings guide, there is a picture about this guide in the readme.

well, I can add vim-leader-guide groups, but it should not be enable by default. will provide a option to set it.

**Comment by zer4tul** [comment]
Sorry for late. I'm busy for work these days. It's the end of the year, you know. 

In my opinion, users can remember at least most of the daily used key mappings. Actually, my fingers can remember all daily used key mappings, then I can't use other editors ( I'll insert lots of "hjkl" things ).

What one need to prompt is those key mappings not used so often. The mapping guide is one solution, but the user must interrupt what he is doing to search for the key mapping.

What spacemacs' "Mnemonic" want to do ( I think ) is:

> 1. You know what you want to do.
> 2. You hit the mapleader, but you forget the following key stroke.
> 3. When timeout reaches, the prompt prompts out.
> 4. You can following the prompt, hit key by key, and done what you want.

In all these steps above, the user is still doing what he want to do. 
As a general propose vim distribution, we don't know which key mappings are daily used by the users. The solution given by spacemacs is "Mnemonic".

Maybe we can do it with unite only? I didn't use unite before. I think we can have a try, even if I don't know if we can implement it in spacevim or not.

**Comment by wsdjeg** [comment]
@zer4tul I hace implement this in SpaceVim, but now only use unite, by default, if user type `<leader>`, the mapping memu will not be opened, In this way, SpaceVim will not affect the user who remember the mappings, if user do not remember, just type `f<space>` to open mapping menu, and search for the mapping by description or key sequence.

for more info, see #106
