### ISSUE TITLE
Editor for shell: cannot escape Problems window due to vim error

### ISSUE THREAD

**Issue by HouzuoGuo** [wsdjeg/SpaceVim#3101]
## The reproduce ways from Vim starting (Required!)
1. Use SpaceVim on master at 361744f65850db8ed0450942b4b7de92501fcf77
2. Install "shellcheck" and use the shell layer in SpaceVim.
3. Enter some problematic shell code and save.
4. Observe that "Problems" window shows up as expected. However, user cannot navigate away from the window with `CTRL+HJKL`, nor can the "Problems" window be dismissed with `q`.

## Screenshots
![image](https://user-images.githubusercontent.com/563872/65877657-e4838400-e394-11e9-8dda-67d060c134d1.png)

## Complete configuration
<pre>
[options]
    statusline_inactive_separator = "nil"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
  name = "denite"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "nil"
  auto-completion-tab-key-behavior = "smart"
  auto-completion-complete-with-key-sequence = "nil"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 25

[[layers]]
  name = "tmux"

[[layers]]
  name = "git"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#extra"
</pre>

**Comment by wsdjeg** [comment]
How about disable the `tmux` layer?

**Comment by HouzuoGuo** [comment]
I've removed tmux layer from init.toml, but still cannot move focus out of the Problems window, this time the error says:

```
Neomake: Error during User autocmd for NeomakeFinished: Vim(return):E716: Key not present in Dictionary: title ==# ':setqflist()') ? '' :  '%#SpaceVim_statusline_c#' . getqflist({'title' : 0}).title . '%#SpaceVim_statusline_c_SpaceVim_statusline_z#' . s:lsep ).
```

**Comment by HouzuoGuo** [comment]
The new error can be easily dismissed with Ctrl+C, after its dismissal I still cannot move focus out of Problems window

**Comment by wsdjeg** [comment]
what is your terminal?

**Comment by HouzuoGuo** [comment]
tmux-256color inside tmux, host terminal is xterm-256color

**Comment by wsdjeg** [comment]
Oh, sorry, the key binding should be Ctrl + arrow key
--------------
wsdjeg

**Comment by HouzuoGuo** [comment]
My tmux settings use:

```
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
```

coupled with tmux layer in SpaceVim, i can freely move between tmux panels and vim windows using the key combo Ctrl+HJKL, quite handy.

FYI, trying to escape the vim Problems window with Ctrl+arrow key ends up with this error:

```
Error detected while processing function SpaceVim#layers#core#statusline#get:
line   13:
E716: Key not present in Dictionary: title ==# ':setqflist()') ? '' :  '%#SpaceVim_statusline_c#' . getqflist({'title' : 0}).title . '%#SpaceVim_statusline_c_SpaceVim_statusline_z#' . s:lsep )
E15: Invalid expression: '%#SpaceVim_statusline_ia#'  . s:winnr(1) . '%#SpaceVim_statusline_ia_SpaceVim_statusline_b#' . s:lsep . '%#SpaceVim_statusline_b#' . ' QuickFix %#SpaceVim_statusline_b_SpaceVim_statusline_c#' . s:lsep . ((getqflist({'title' : 0}).title ==# ':setqflist()') ? '' :  '%#SpaceVim_statusline_c#' . getqflist({'title' : 0}).title . '%#SpaceVim_statusline_c_SpaceVim_statusline_z#' . s:lsep )
```

Once the error is dismissed, I could successfully moved that cursor out of the Problems window.

**Comment by wsdjeg** [comment]
this has been  fixed. please update spacevim

**Comment by HouzuoGuo** [comment]
Lovely - it works! Thank you.
