### ISSUE TITLE
Add config option to show hidden files (dotfiles) by default

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#3102]
**Is your feature request related to a problem? Please describe.**
I would like a way to show hidden files in the tree without having to toggle every time.

**Describe the solution you'd like**
Add a configuration property in init.toml to control file visibility.

**Describe alternatives you've considered**
Use a bootstrap function.

**Additional context**
As a devops engineer, I frequently work on dotfiles and it's tedious to toggle the feature every time I open SpaceVim.

Thanks for a fantastic project, btw!

**Comment by wsdjeg** [comment]
Yeah, there should be an option for this, I will add it.
