### ISSUE TITLE
Denite fails to load: unknown function: _denite_init

### ISSUE THREAD

**Issue by HouzuoGuo** [wsdjeg/SpaceVim#3104]
This is a fresh installation of SpaceVim at master revision `dcb16a2e3fdb22255090f58351824e94fdb8ff1f`, here is `init.toml`:

<pre>
[options]
    statusline_inactive_separator = "nil"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "nil"
  auto-completion-tab-key-behavior = "smart"
  auto-completion-complete-with-key-sequence = "nil"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 25

[[layers]]
  name = "tmux"

[[layers]]
  name = "git"

[[layers]]
  name = "tools"

[[layers]]
  name = "format"

[[layers]]
  name = "cscope"

[[layers]]
  name = "debug"

[[layers]]
  name = "gtags"
[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#powershell"

[[layers]]
  name = "denite"
</pre>

Immediately after, denite fails to load due to:

<code>
[denite] Vim(call):E117: Unknown function: _denite_init
[denite] function <SNR>47_warp_denite[1]..denite#helper#call_denite[7]..denite#start[4]..<SNR>258_start[1]..denite#initialize[1]..denite#init#_initialize, line 33
[denite] denite failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.
Press ENTER or type command to continue
</code>

**Comment by Shougo** [comment]
You need to execute UpdateRemotePlugins command.

**Comment by HouzuoGuo** [comment]
@Shougo thanks for the hint however it doesn't help. The same error message shows up afterwards even after neovim itself has already been restarted.

**Comment by Shougo** [comment]
Please upload :checkhealth and :UpdateRemotePlugins result.
If you use dein.vim, you need to use dein#remote_plugins() instead.

**Comment by HouzuoGuo** [comment]
It went away after reinstalling SpaceVim:

https://gist.github.com/HouzuoGuo/9a48c6d28b90a16434ccfbdd9d9e4065

**Comment by Shougo** [comment]
OK
