### ISSUE TITLE
shotcut for leaderf is so strange

### ISSUE THREAD

**Issue by jidibinlin** [wsdjeg/SpaceVim#3110]
## Expected behavior, english is required
**\<leader\> f** can`t open the submenu for **\<leader\> f m** or **\<leader\> f e** ...
## The reproduce ways from Vim starting (Required!)
add leaderf layer to init.tom and open nvim then type \ (leader key for fuzzy find )

## Screenshots
![leaderf](https://user-images.githubusercontent.com/38578679/66053965-d89aec00-e565-11e9-8da7-a36147ee49c9.png)

**Comment by wsdjeg** [comment]
![image](https://user-images.githubusercontent.com/13142418/66056579-ee121500-e569-11e9-9833-4553c1501b09.png)
I can not reproduce it, please make sure your spacevim is latest version.

**Comment by wsdjeg** [comment]
sorry, I am using ctrlp layer, I will test leaderf layer.

**Comment by wsdjeg** [comment]
@jidibinlin I can not fix it, because neovim's python support is not compatible with vim. it has no `vim.bindeval` and `vim.Function`. etc. 

I think neovim's python-mode should keep compatible with vim8. 

cc @justinmk

**Comment by justinmk** [comment]
> I think neovim's python-mode should keep compatible with vim8.

No, that is out of scope. The Vim 7.4 if_pyth is supported, and that's it.

**Comment by wsdjeg** [comment]
if no, how does people use old vim plugins which is written in Python

**Comment by wsdjeg** [comment]
fixed!
