### ISSUE TITLE
Not enough customization

### ISSUE THREAD

**Issue by kepbod** [wsdjeg/SpaceVim#312]
## Expected behavior, english is recommend
Since SpaceVim called itself as one vim distribution, it should have many settings that could be customized. However, [the customization](https://github.com/SpaceVim/SpaceVim#quick-start-guide) is so limited. In addition, lots of plugins were installed, but I did not know where I could put my configurations for each plugin. The file organization is so wired, and I could not found what have been done to my vim, which is very intolerable to a vim user.

## Environment Information
- OS:
- vim version:
- neovim version:

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
so what is the real feature request? can you list them, I will try to implement these features.

**Comment by v-leonhou** [comment]
@wsdjeg  i got the same feeling sometimes ,so i will list some of my bad feelings using spacevim,may i open an issue to show that list??   I think spacevim could get better.........

**Comment by wsdjeg** [comment]
of course, thanks

**Comment by astromac** [comment]
Well,, this issue (https://github.com/SpaceVim/SpaceVim/issues/314) you closed would seem to go a long way into satisfying @kepbod and @v-leonhou needs as well as my own. If I cannot tailor SpaceVim to meet my specific needs then I won't use SpaceVim.

Don't get me wrong, I think SpaceVim is great and I want to use it but I think Vim users, as a rule, expect to be able to tweak the setup to their liking.

**Comment by wsdjeg** [comment]
@astromac yes, I also think SpaceVim should be able to be setting as what user want.  yes, I will improve all the plugin settings. Sorry for clossing #314 .

**Comment by wsdjeg** [comment]
SpaceVim support local and global config, you can add config option into it.
