### ISSUE TITLE
Add a configuration for SpaceVim#plugins#a#get_alt() 

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3130]
SpaceVim has a ``:A`` command, that calls SpaceVim#plugins#a#get_alt() to jump to header/source/test files.  But it depends on the ``.project_alt.json`` file, which **must** be put in EVERY project, that forces we put the same ``.project_alt.json`` file everywhere.

Since ``.project_alt.json`` is nothing but a JSON, maybe we can add a ``b:``/``g:`` option.  If the option exists, load the configuation from it instead of the ``.project_alt.json`` file.  It make it possible to setup filetype specified insteads of project specified settings.

FYI, I have a complicated setting for ``vim-fswitch`` plugin to handle different directory structure for lib/app, but I don't think others need these:

```vim
    autocmd! vimrc BufEnter *.h,*.hpp
                \  let b:fswitchdst='cpp,c,ipp,cxx'
                \| let b:fswitchlocs='reg:/include/src/,reg:/include.*/src/,ifrel:|/include/|../src|,reg:!\<include/\w\+/!src/!,reg:!\<include/\(\w\+/\)\{2}!src/!,reg:!\<include/\(\w\+/\)\{3}!src/!,reg:!\<include/\(\w\+/\)\{4}!src/!,reg:!sscc\(/[^/]\+\|\)/.*!libs\1/**!'
    autocmd! vimrc BufEnter *.c,*.cpp,cxx,*.ipp
                \  let b:fswitchdst='h,hpp'
                \| let b:fswitchlocs='reg:/src/include/,reg:|/src|/include/**|,ifrel:|/src/|../include|,reg:|libs/.*|**|'
```

**Comment by wsdjeg** [comment]
@thawk Nice idea.

**Comment by wsdjeg** [comment]
@thawk in your previous comment, it is to use autocmd BufEnter *.h event. it seems it will be applyed to all these files. this idea looks like a global option for all files. how about provide a global options for setting this. or a global config file?

**Comment by thawk** [comment]
I use [vim-fswitch](https://github.com/derekwyatt/vim-fswitch) plugin. It depends on the buffer local variable, so I use ``autocmd`` to set these variables.

I think the above settings in my personal config file are file-type specified.  Per project based settings in SpaceVim is good too.  I think header/source/testing file names and locations have a more tightly relation to file type than to project. 

Maybe a filetype based option, override-able at project level, suits most conditions?  Aka., have a default project, set default options in that project, and override it in concrete project.  If we can detect project type by rooter-pattern, it could be possible to have different option value for different project type. But I don't know whether we really need this complication.

**Comment by wsdjeg** [comment]
I am working on this feature now. in old version, the plugin will read config info from a file. I will add an option for it, the plugin will check this option, if it is empty then read config info from the file.
