### ISSUE TITLE
Autoscroll should stop when user move the cursor

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3132]
The newly added autoscroll feature is good for REPL and for async run.  But when a program need some time to run, we can't see the early output until it stops.

For example, when I start compile a large project, I want to correct the errors as soon as I see it, maybe I will cancel the build when I find fatal errors.  For this purpose, I need to scroll up to see the early output instead of lastest output.

It's better to auto scroll while and only while the cursor is on the last line.

**Comment by wsdjeg** [comment]
yeah, we should add this feature.
