### ISSUE TITLE
Add the ability to go up a directory in FZF

### ISSUE THREAD

**Issue by rj-calvin** [wsdjeg/SpaceVim#3137]
Often, when I'm working I will end up within the subdirectories of my projects. As such, when I want to jump to somewhere else in the hierarchy, my first instinct is to always go for fuzzy find (since it's quicker than navigating the file tree). However, as it currently exists, fuzzy find can't allow you to change the root directory of the search, meaning I am locked to the directory I'm already sitting in.

Ideally, a mapping for something along the lines of `r'^..'` would work really well for this. Though I'm not sure how easy it is to match the beginning of a line in a VimL keymap.

**Comment by jyscao** [comment]
Using FZF you can search from the root of your project with `SPC p f`, which just maps to the FZF command `:FzfFiles`

The searching for files in the directory of your current buffer is actually a SpaceVim thing that requires calling FZF in a custom manner.

**Comment by rj-calvin** [comment]
Oh! Alright, that actually is sufficient for most of my use cases.
