### ISSUE TITLE
Tex codeblock syntax highlight not work in lang#markdown layer

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3138]
## Expected behavior, english is required

When the lang#latex layer is enabled, ``tex`` code block should be correctly highlighted.

## The reproduce ways from Vim starting (Required!)

1. Enable ``lang#latex`` layer in ``init.toml``
2. Create ``test.tex``, input

       ```tex
       $\frac{1}{3} = \frac{x_1}{y_1}$
       ```

3. It should be colourful, but not.
4. Enable the non-existed ``lang#tex`` layer in ``init.toml`` and try again，the aboved code is highlight correctly

## The Cause

The code in ``SpaceVim#layers#lang#markdown#config()`` fills ``g:markdown_nested_languages`` with names of all enabled ``lang#`` layers.  Those names were used as code block name in the ``vim-markdown`` and load the syntax file with same name for highlighting.

Because SpaceVim has ``lang#latex`` layer, but what vim has is ``syntax/tex.vim`` not ``syntax/latex.vim``, so the syntax file can't be correctly loaded.

**Should we rename the latex layer, or let the latex layer load ``syntax/tex.vim`` instead?**

**Comment by wsdjeg** [comment]
so what is the correct language name? for java the language is java and the filetype is java and the layer is lang#java too.  we recomamnd to use latex as the layer and language name, as spacevim has allready publish the layer page on the website.
--------------
wsdjeg

**Comment by thawk** [comment]
The language name is ``tex``.  The file extension which ``LaTeX`` handles is ``*.tex`` ([Wiki](https://en.wikipedia.org/wiki/LaTeX#Compatibility_and_converters)).  Also the syntax file provied by vim/nvim is ``syntax/tex.vim``.

**Comment by wsdjeg** [comment]
so what is latex, and why the prefix `la` is added?
--------------
wsdjeg

**Comment by thawk** [comment]
Actually, I am not a TeX/LaTeX user.  I just want to write some Tex formula in Markdown document.   
I found some descriptions:

* [[texhax] learning tex vs latex](https://tug.org/pipermail/texhax/2009-October/013645.html)

  - LaTeX is a script-like user interface to the binary TeX program, i.e., 
Knuth's versions up to TeX3, or extensions of the latter, most notably: 
e-TeX, pdfTeX, XeTeX.

  - Plain TeX is kind of an alternative user interface to TeX, but with a few 
exceptions, it is just a part of LaTeX. ... "in a silent way", however: 
plain TeX code is present in the LaTeX source latex.ltx, but usual LaTeX 
documentation doesn't mention it. Plain TeX and LaTeX are called "formats".

  - When you are writing `tex', it is not quite clear whether you are referring 
to the binary or to the format Plain TeX. This confusion seems to lurk in 
other postings.

* [What is the difference between TeX and LaTeX?](https://tex.stackexchange.com/questions/49/what-is-the-difference-between-tex-and-latex)

  - TeX is both a program (which does the typesetting, tex-core) and format (a set of macros that the engine uses, plain-tex). Looked at in either way, TeX gives you the basics only. If you read the source for The TeXBook, you'll see that Knuth wrote more macros to be able to typeset the book, and made a format for that.

  - LaTeX is a generalised set of macros to let you do many things. Most people don't want to have to program TeX, especially to set up things like sections, title pages, bibliographies and so on. LaTeX provides all of that: these are the 'macros' that it is made up of.

* [TeX Wikipedia](https://en.wikipedia.org/wiki/TeX)

  - TeX is a typesetting system (or a "formatting system") which was designed and mostly written by Donald Knuth and released in 1978. TeX is a popular means of typesetting complex mathematical formulae; it has been noted as one of the most sophisticated digital typographical systems.
   - It is also used for many other typesetting tasks, especially in the form of LaTeX, ConTeXt, and other macro packages. 

* [LaTeX Wikipedia](https://en.wikipedia.org/wiki/LaTeX): 

  - LaTeX is a document preparation system.
  - LaTeX uses the TeX typesetting program for formatting its output, and is itself written in the TeX macro language. 
  - LaTeX is intended to provide a high-level, descriptive markup language that accesses the power of TeX in an easier way for writers. In essence, TeX handles the layout side, while LaTeX handles the content side for document processing. LaTeX comprises a collection of TeX macros and a program to process LaTeX documents, and because the plain TeX formatting commands are elementary, it provides authors with ready-made commands for formatting and layout requirements such as chapter headings, footnotes, cross-references and bibliographies.

**Comment by wsdjeg** [comment]
Thanks for your info.
