### ISSUE TITLE
No mode prompt text (ie. --INSERT--, --VISUAL--) after installing SpaceVim

### ISSUE THREAD

**Issue by wuya666** [wsdjeg/SpaceVim#3140]
## Expected behavior, english is required

The editor should still show "-- INSERT --" and "-- VISUAL --" prompt text when it enters insert/visual mode at the bottom of the editor.

## The reproduce ways from Vim starting (Required!)

1. Install SpaceVim

2. use vim to open some text file

3. press i or v

4. I expect the text "-- INSERT --" or "-- VISUAL --" to display at the bottom of the editor, but it seems I get different results for different systems.

5. On one system, I get the prompt text to show correct with vim, but no prompt text shows for neovim. On another system, there's no prompt text for both vim and neovim.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

For vim on one system you can see the "-- INSERT --" prompt text
![image](https://user-images.githubusercontent.com/30381159/66672109-244d4400-ec90-11e9-8274-1252d35b49e6.png)

For vim on another system there's no "-- INSERT --" prompt text, just the buffer number changes from greenish to bluish to show that it's in insert mode already.

normal mode
![image](https://user-images.githubusercontent.com/30381159/66672461-e69ceb00-ec90-11e9-9e54-5cacba15ca0a.png)

insert mode
![image](https://user-images.githubusercontent.com/30381159/66672344-accbe480-ec90-11e9-8cda-0ca836ff1c1b.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please use enable_statusline_mode = true in your SpaceVim configuration file.

**Comment by wuya666** [comment]
> please use enable_statusline_mode = true in your SpaceVim configuration file.

Hmmm, it is usable, but it's not exactly the same thing, and somehow in my first system if I use `enable_statusline_mode = true` it becomes something that looks really funny like this

![image](https://user-images.githubusercontent.com/30381159/66698093-9b74ed80-ed0d-11e9-802d-1e23fa2ba962.png)

![image](https://user-images.githubusercontent.com/30381159/66698107-ae87bd80-ed0d-11e9-8ee3-0a29511ffc11.png)

So it seems the "-- INSERT --"/"-- VISUAL --" prompt is intentionally hidden by SpaceVim but this "feature" is somehow broken on my first system's vim?
