### ISSUE TITLE
Can not see git information in gutter

### ISSUE THREAD

**Issue by adds68** [wsdjeg/SpaceVim#3147]
## Expected behavior, english is required
I've added both Git and Versioncontrol layers, which should show vcs information in the gutter of spacevim, however it does not.

## The reproduce ways from Vim starting (Required!)

Adding both Git and Versioncontrol layers and starting spacevim

**Comment by jyscao** [comment]
`:sign list` to see all your defined signs (aka gutter region)

**Comment by adds68** [comment]
Hi thanks for the response, this lists:

`sign GitGutterLineAdded text=+  linehl= texthl=GitGutterAdd numhl=
sign GitGutterLineModified text=~  linehl= texthl=GitGutterChange numhl=
sign GitGutterLineRemoved text=_  linehl= texthl=GitGutterDelete numhl=
sign GitGutterLineRemovedFirstLine text=‾  linehl= texthl=GitGutterDelete numhl=
sign GitGutterLineRemovedAboveAndBelow text=[  linehl= texthl=GitGutterDelete numhl=
sign GitGutterLineModifiedRemoved text=~_ linehl= texthl=GitGutterChangeDelete numhl=
`
I can't see anything around commit message, how do i enable more of these?

**Comment by wsdjeg** [comment]
This sign will shown when you make some change in your git repo.
