### ISSUE TITLE
Cursos jumping to beginning of line on saving a file

### ISSUE THREAD

**Issue by stfl** [wsdjeg/SpaceVim#3159]
# Jumping on save

I am seeing sometimes weird cursor jumps in nvim and vim.
Both of the effects described below do not happen immediately when starting vim but after some time.
It also does not appear for all open buffers but only some buffers are affected.

When I save the file the cursor jumps to the beginning of the line like <kbd>^</kbd>.
It also looks like some plugins are re-reading the file without saving. So the curso jumps when leaving insert mode. The cursor jumps at the same time the sign column updates.

This is really annoying because I have to jump back to the position I was before.

I have tried to disable several layers. But even with only "edit" enabled it appears after some time.
The git layer especially GitGutter seams to make the situation appear more frequently.

This problem sometime disappears again.

# jumping on `:e`

Another thing that happens is when re-reading the file with `:e` the cursor jumps to a completely different line. Probably the line which was cached at saving the file at last close or something. This line it jumps to is always the same.

This happens sometimes while the other cursor jumping does not occur.

## The reproduce ways from Vim starting

I have not managed to reproduce the issue at vim start. It just comes after some time.
I have tried to disable several layers. But even with only "edit" enabled it appears after some time.
The git layer especially GitGutter seams to make the situation appear more frequently.

I have seen this with vim 8.1 nvim 0.3.8 and nvim 0.4.2
Does anybody else experience this issue?

I will try to gather some more debug information on the next occurence..

**Comment by stfl** [comment]
When the problem does not show I noticed, when I save the file, the cursor blinks and approx 1 sec later, the cursor blinks again but stays at the same location.
If the problem occurs the cursor would jump on that second blink.

**Comment by stfl** [comment]
`:9verbose w`

```
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
Executing BufWritePre Autocommands for "*"
autocommand call SpaceVim#plugins#mkdir#CreateCurrent()
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
Executing BufWritePre Autocommands for "*"
autocommand call s:SyncAutocmd('BufWritePre', +expand('<abuf>'))
Executing BufWritePre Autocommands for "*"
autocommand call neosnippet#handlers#_all_clear_markers()
"gstfishstitcher/src/gstfishstitch.cpp" 909L, 31990C written
Writing undo file: /home/sll/.cache/SpaceVim/undofile/%home%sll%work%palspective%camhead%gstfishstitcher%src%gstfishstitch.cpp
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
Executing BufWritePost Autocommands for "*"
autocommand let &l:statusline = SpaceVim#layers#core#statusline#get(1)
                    Executing BufWritePost Autocommands for "*"
autocommand :call setbufvar('%', 'rootDir', '') | call SpaceVim#plugins#projectmanager#current_root()
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
chdir(/home/sll/work/palspective/camhead)
chdir(.git)
chdir(/home/sll/work/palspective/camhead)
chdir(/home/sll/work/palspective/camhead/)
/home/sll/work/palspective/camhead
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
Executing BufWritePost Autocommands for "*"
autocommand call s:append(expand('<amatch>'))
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
Executing BufWritePost Autocommands for "*"
autocommand call s:Autocmd('BufWritePost', +expand('<abuf>'))
Executing BufWritePost Autocommands for "*"
autocommand call fugitive#ReloadStatus(-1, 0)
Executing BufWritePost Autocommands for "*"
autocommand call s:HandleBufWrite(fnamemodify(expand('<afile>'), ':p'))
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
chdir(/home/sll/work/palspective/camhead)
chdir(gstfishstitcher/src)
chdir(/home/sll/work/palspective/camhead)
```

**Comment by jyscao** [comment]
I also have this issue sometimes, and been meaning to look into it myself. But likewise, have not been able to pin down a reliable way of reproducing it.

**Comment by wsdjeg** [comment]
I need reproduce step, when write which file?

**Comment by stfl** [comment]
I will try to figure out how to reproduce it. @jyscao have you managed to find deterministic steps to reproduce it?

**Comment by jyscao** [comment]
@Stefan Lendl, no I have not been able to. I'll try to once I finish up
some more urgent tasks.

*Jethro Cao*

**Comment by jyscao** [comment]
@stfl I still can't reproduce the bug reliably. But one workaround I've found is to switch to different buffer, then switch back immediately, and that would temporarily (for unknown length of time) make this misbehavior go away.

**Comment by stfl** [comment]
It seams like I don't see the bug anymore. I've tried so many different configs and it looks like it's related to setting in the lsp layer. Either filetype or layers.override_cmd.
I've seen the issue with deoplete as well as coc.nvim.

Without setting a filetype and override_cmd but instead installing coc plugins like coc-rls I don't get the random jumping to the start of the line anymore.
the `:e` issue still shows up but that is not that severe.

It looks like this really annoying long standing issue in my config (which drove me nuts and made me consider alternatives) is now solved for me.

I guess the issue (supposedly in the lsp layer) still exists!
@jyscao doe you have override_cmd set in lsp layer? Maybe changing something there solves it for you as well.

**Comment by thawk** [comment]
I think this issue maybe related to vim-signify.  

This issue occurs only occurs while vim is idle.  So it's most posiible related to ``autocmd CursorHold``.  I found that vim-signify register a CursorHold event, and when a disable it using ``augroup signify | au! | augroup END``, the issue seems to disappear.

Because this issue can't be reproduce reliably, I can just have a guess, but can't confirm.

**Comment by jyscao** [comment]
I posted a question on Vim stack exchange regarding this problem and referencing this specific issue thread not too long ago: https://vi.stackexchange.com/q/22048/24816

However I've not had the time to test out the suggestions given in the 2 comments. If any of you guys can find the time to run some of those diagnosis steps that'll be great. Almost certainly we aren't the only ones having this annoying issue.

@stfl I do use deoplete, though not coc.nvim and also not the LSP layer, so I'm not convinced that's the root cause of the issue. But I'll double check override_cmd in my config just to be sure.

@thawk I'll try disabling augroup signify and see if that helps. Will report back either way.

**Comment by stfl** [comment]
@thawk I disabled the git and VersionControl layers but even withouth signify or GitGutter I saw the issue..

**Comment by stfl** [comment]
I just saw the issue again. This time only in cpp files. In Rust I am still not seeing it..

**Comment by thawk** [comment]
I saw the issue again. 

With ``au CursorHold``, I saw  two augroups: ``signify`` and ``TagbarAutoCmds``.  When I disable the later with ``:augroup TagbarAutoCmds | au! | augroup END``, the issue remains.  But when I disable the ``signify`` with ``:augroup signify | au! | augroup END``, the issue disappears.

I can't confirm whether disabling VersionControl layer works or not. Maybe ``signify`` and/or other plugin triggers something that cause this issue? Would you try disabling some augroup when the issue occurs to find out more information?

**Comment by stfl** [comment]
I tried now to disable augroup signify but the issue still remains.
I actually disable all au in CursorHold and it still remains.

I kept on disabling various other augroups until it disappeared and it stopped at `augroup SpaceVim_core | au! | augroup END`

**Comment by stfl** [comment]
now the problem appeared again but disabling SpaceVim_core did not fix it..
I also noticed, that it also appears when switching back and forth between tmux panes.

The issue disapeared now after I closed the vimfiler buffer with `Q`

**Comment by stfl** [comment]
I might have to go back to an older version of spacevim and try to figure out since when this is happening..
I remember I first saw it around the time GitGutter was added..

**Comment by thawk** [comment]
@stfl Maybe my issue is difference from yours.  My issue is the cursor jumps to the begin of line after several seconds when I stop typing.  So I think it is triggered by the CursorHold event, and it seems to works when I disable the signify augroup.

Maybe your issue is triggered by another event. I suggest you to check other events related to file saving.

**Comment by stfl** [comment]
I guess so.. I still suspect that there is one function / autocmd that moves the cursor but is triggered from different situations..

**Comment by wsdjeg** [comment]
there must be a reproduce step. I can not reproduce it. please provide mini config and reproduce step.

**Comment by stfl** [comment]
I noticed that the issue disappears when switch window or change window layout with sth like `:vsp`
then it is gone every time. 

@wsdjeg 
I might have narrowed it down to `incsearch` layer.
If I disable it, the issue does not appear at all. (at least for the last 5 hours)

**Comment by thawk** [comment]
As @stfl said, it may related to ``incsearch`` layer.  And I can reproduce this issue:

1. ``vim ~/.SpaceVim/README.md``
1. ``zR`` to open all folds
1. `` gg`` to jump to begin of the file
1. ``/Gitter<CR>`` to begin search
1. ``n`` to jump to next match
1. ``k`` move cursor to previous line and leave hlsearch
1. wait a few seconds, and the cursor is jump to bol

I think the ``n`` to search next is the key.  I try reopen the file, press ``gg``, ``n``, and ``k``, the issue occurs.

BTW, when I search using ``[SPC]sB`` or similar keys, sometimes the search string may be appended with ``(_incsearch-nohlsearch)``.  I think this may caused by the similar reason.

**Comment by thawk** [comment]
I have a minimal ``init.toml`` to firing the issue as below.
You can ses that I disabled all pluging inside ``incsearch`` layer, the issue sill exists.  But when I disable the ``incsearch`` layer, it disappears.  When I disable the ``vim-signify`` plugin, the issue disappears too.  But I still have no idea how these happen.

```toml
[options]
    # disabled_plugins=['vim-signify']
    disabled_plugins=['incsearch.vim', 'incsearch-fuzzy.vim', 'incsearch-easymotion.vim', 'vim-asterisk', 'vim-visual-star-search', 'vim-over']
    # disabled_plugins=['incsearch.vim', 'incsearch-fuzzy.vim', 'incsearch-easymotion.vim', 'vim-asterisk', 'vim-visual-star-search', 'vim-over', 'vim-signify']

[[layers]]
    name = 'autocomplete'
    enable = false

[[layers]]
    name = 'checkers'
    enable = false

[[layers]]
    name = 'core#banner'
    enable = false

[[layers]]
    name = 'core#statusline'
    enable = false

[[layers]]
    name = 'core#tabline'
    enable = false

[[layers]]
    name = 'core'
    enable = false

[[layers]]
    name = 'edit'
    enable = false

[[layers]]
    name = 'format'
    enable = false

[[layers]]
    name = 'ui'
    enable = false

[[layers]]
    name = 'VersionControl'

[[layers]]
    name = 'incsearch'
    enable = true
```

**Comment by wsdjeg** [comment]
I still can not reproduce this issue.

**Comment by wsdjeg** [comment]
@stfl I think it is because these lines:

You can try to comment out these lines，

https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/incsearch.vim#L104-L109

**Comment by thawk** [comment]
@wsdjeg Yes, it seems to work after commenting those lines.
BTW, I suggest using ``getpos()``/``setpos()`` to avoid using a bookmark.

**Comment by wsdjeg** [comment]
Ok, PR is welcome, and you can test it locally. :)
--------------
wsdjeg

**Comment by wsdjeg** [comment]
hi, I can reproduce it now. there are two issues need to be fixed.
