### ISSUE TITLE
How to share one spacevim between two users in linux ? eg: root user and other normal user.

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#316]
I got error like this on my computer when i logger my computer as normal user:
![qtum_w7 l3p 7r4sda3qz s](https://cloud.githubusercontent.com/assets/8463045/23685990/fdfe90ae-03e1-11e7-8035-04d8e83cd3fd.png)
  but it runs well on root user except that vimfiler loads very very slow

## Environment Information
- OS: ubuntu
- vim version: vim 8
and my vim installation path is /usr/local/vim8/
![hiy v 40h1f7aq kua1uwtg](https://cloud.githubusercontent.com/assets/8463045/23686106/998710fa-03e2-11e7-8a81-ae0480b9af35.png)

my spacevim dir is /vagrant/data/SpaceVim/
![zu j d431t1 t d_e 0 q6](https://cloud.githubusercontent.com/assets/8463045/23686144/ce701046-03e2-11e7-8ccb-b9ae1cd97a33.png)

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
here is the log message
![z8g2yxdhrhx g2p usw 3 a](https://cloud.githubusercontent.com/assets/8463045/23686064/6ca689b2-03e2-11e7-8bb4-b40df645c2d7.png)

**Comment by wsdjeg** [comment]
I just test it, it works well for me. here is how I install SpaceVim for `root` add `wsdjeg`.
by default the user is wsdjeg, so I install SpaceVim via 
```
curl -sLf https://spacevim.org/install.sh | bash
```
this meams SpaceVim is cloned to `/home/wsdjeg/.SpaceVim`, and `/home/wsdjeg/.vim` is just a link to it.
then add this to custom config of `wsdjeg` and `root`
`/home/wsdjeg/.SpaceVim.d/init.vim` and `/home/root/.SpaceVim.d/init.vim`
```
let g:spacevim_plugin_bundle_dir = '/home/wsdjeg/.cache/vimfiles/'
```
so this value will not be changed by `$HOME`.

then how to start vim?
`vim -u /home/wsdjeg/.SpaceVim/init.vim`

BTW, you can add this to bashrc
```
alias vim='vim -u /home/wsdjeg/.SpaceVim/init.vim
```

**Comment by v-leonhou** [comment]
I can't say anything beacause it 's so werid , it just run well in normal user ,i have no time to figure out what is the problem ,but anyway anything got well ,i think it is my computer enviroment that caused the problem ,thanks for your reply
