### ISSUE TITLE
The function s:split_string(newline)  works not very well for Python file.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#3174]
## Expected behavior, english is required

Split string properly. For instance: split the string "testWord" to "test""Word" in a Python file.

## The reproduce ways from Vim starting (Required!)

Open a Python file and type in a string, such as "testWord", and keep the cursor on any char in the string "testWord". Then hit <kbd>[SPC] j s</kbd> or <kbd>[SPC] j S</kbd>. Then you will find SpaceVim treat the first char 't' in the string "testWord" as a string identifier.
But this function works very well for vim files.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
we need to add string concatenator when split string.

in viml

```
echo 'sss'
```

->

```
echo 'ss' . 's'
```

and

```
echo 'ss'
   \ . 's'
```
