### ISSUE TITLE
Open vim error: all databases has been cleared!

### ISSUE THREAD

**Issue by BlasphemyAngels** [wsdjeg/SpaceVim#3178]
MacOS
Every time, it exist a information when open the vim:

all databases has been cleared!
Press ENTER or type command to continue

how to fix it ?

**Comment by thbertoldi** [comment]
That's from cscope layer, line 87 on autoload/cscope.vim from cscope.vim project.

**Comment by psifertex** [comment]
Is it normal though? It's kinda annoying and for now I'm just disabling cscope.
