### ISSUE TITLE
Use `textwidth` rather the hardcoded 80 columns for long lines highlighting

### ISSUE THREAD

**Issue by Kerl13** [wsdjeg/SpaceVim#3179]
Hi,

When toggling "highlight-long-lines" with [SPC]-t-8, the long lines indicator highlights everything that goes beyond the 80th column. I think it's a good default but it becomes a bit frustrating when using a different `textwidth` because line-wrapping and long-lines-highlighting then become inconsistent.

I'd suggest using `textwidth` in `toggle_fill_column` when it is set to a positive value, falling back to the default `80` otherwise.

I can open a PR with the patch if you're okay with this change.

**Comment by wsdjeg** [comment]
the last char of the key binding is 8, so use 80 is better.

**Comment by Kerl13** [comment]
How about adding a different key binding then? The `highlight-long-lines` feature of spacevim is quite appreciable and it would benefit all the people who don't use a 80 cols formatting everywhere.

Also, I noticed that currently, all columns starting from the 80th are highlighted. Wouldn't it be more relevant to start at 81?
