### ISSUE TITLE
Clear `not implemented` message for debug layer

### ISSUE THREAD

**Issue by cedroyer** [wsdjeg/SpaceVim#3181]
Currently, it seems that `debug` layer is not ready/implemented, but nothing in the doc or even the log message `read :h vebugger-launching` (that doesn't work) let us think so.

I have to go in SpaceVim code and look for this [repo](https://github.com/wsdjeg/debug.vim) to understand  the current state of this layer.

Could you just put a clear message log or specify in the doc that this layer is not yet functional ?

## Expected behavior, english is required

have a clear log message that echo `debug layer is not implemented yet` (or something like that).

## The reproduce ways from Vim starting (Required!)

Add debug layer in ~/.SpaceVim.d/init.toml:
```
[[layers]]
name="debug"
```
And try to use it <kbd>SPC d l</kbd>.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Do you read `:h vebugger-launching`?

**Comment by cedroyer** [comment]
It returns me: `E149: Sorry, no help for vebugger-launching`

**Comment by wsdjeg** [comment]
@cedroyer sorry, I forgot to push. and it is https://github.com/wsdjeg/vim-debug

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/vim-debug
