### ISSUE TITLE
How do I configure Python linter for the lsp layer?

### ISSUE THREAD

**Issue by dclong** [wsdjeg/SpaceVim#3186]
I love the lsp layer in SpaceVim! However, there's a slight issue with the Python linter in the lsp layer. It reports the following warnings on my formatting which is done using `yapf` using the following settings (.style.yapf). How can I configure the Python linter for the lsp layer so that it respect the yapf settings and stop complaining about it?
```
[style]
based_on_style = facebook
column_limit = 88
```

![image](https://user-images.githubusercontent.com/824507/67443431-b242fc00-f5b9-11e9-9311-10000334cc22.png)

**Comment by Guzzii** [comment]
@dclong Linters often have their own configuration methods through command line argument or a configuration file in project root or $home. I don't think you can make any linter respect yapf which is a code formatter. You best bet is to set up the linter in a way close to how yapf would format your code.

**Comment by wsdjeg** [comment]
It must be reproduce able, you can create simple python project, and post your spacevim config, I will test it.
