### ISSUE TITLE
Adding [[layers]] name = "lang#python" to .Spacevim.d/init.toml causes problem

### ISSUE THREAD

**Issue by philipmac** [wsdjeg/SpaceVim#3187]
Fresh installation, add:
`[[layers]] name = "lang#python"` 

results in:

`Error detected while processing /home/macmenaminpe/.SpaceVim/autoload/SpaceVim/api/iconv/bytes.vim:
line    1:
E15: Invalid expression: expand('<sfile>:p:r:gs?[\\/]?#?:s?^.*#autoload#??:s?$?#?')^M
Error detected while processing function SpaceVim#end[94]..SpaceVim#plugins#load[4]..<SNR>47_load_plugins:
line   16:
E170: Missing :endfor
Error detected while processing function SpaceVim#end[94]..SpaceVim#plugins#load:
line    4:
E171: Missing :endif
Press ENTER or type command to continue:`

on launch. 

Reproduce : always

**Comment by veso-k** [comment]
Same to me.

**Comment by yldcs** [comment]
Same to me.  last week，this issue did not appear .

**Comment by veso-k** [comment]
Have you tried it after :SPUpdate ?

**Comment by yldcs** [comment]
yes, But it doesn't work！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "veso-k"<notifications@github.com&gt;; 
发送时间: 2019年10月24日(星期四) 晚上8:07
收件人: "SpaceVim/SpaceVim"<SpaceVim@noreply.github.com&gt;; 
抄送: "#^_^#"<2514018084@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [SpaceVim/SpaceVim] Adding [[layers]] name = &quot;lang#python&quot; to .Spacevim.d/init.toml causes problem (#3187)




Have you tried it after :SPUpdate ?

**Comment by veso-k** [comment]
Same for GO layer.

**Comment by yldcs** [comment]
> Same for GO layer
bytes.vim is a new file ，which maybe cause this issue.

**Comment by veso-k** [comment]
SpaceVim version 1.3-0-dev

**Comment by witem** [comment]
Problem after PR: https://github.com/SpaceVim/SpaceVim/pull/3183

You can manualy checkout in `~/.SpaceVim/` to commit beffore merge it PR(`3404dc74bd5e42a084acb85d64902ab48c8edb10`)

**Comment by QingYuan-L** [comment]
Same for c/c++

**Comment by philipmac** [comment]
> Problem after PR: #3183
> 
> You can manualy checkout in `~/.SpaceVim/` to commit beffore merge it PR(`3404dc74bd5e42a084acb85d64902ab48c8edb10`)

Can confirm, checking out a commit before this fixes issue.

edit, the offending commit seems to be later than this. 

It seems to be:

`abe59e3d2380cde3d1c16f57ba3a5da3d5e878cc`

**Comment by wsdjeg** [comment]
fixed by #3190

**Comment by yldcs** [comment]
The following method works for me. I remove the several folder：.SpaceVim , .SpaceVim.d , .config/nvim, .cache/*. And then reinstall Spacevim.
