### ISSUE TITLE
10月24日更新报错 回退到之前版本就没有问题

### ISSUE THREAD

**Issue by rdcentermrzhi** [wsdjeg/SpaceVim#3188]
Error detected while processing /root/.SpaceVim/autoload/SpaceVim/api/iconv/bytes.vim:
line    1:
E15: Invalid expression: expand('<sfile>:p:r:gs?[\\/]?#?:s?^.*#autoload#??:s?$?#?')^M
Error detected while processing function SpaceVim#end[94]..SpaceVim#plugins#load[4]..<SNR>48_load_plugins:
line   16:
E170: Missing :endfor
Error detected while processing function SpaceVim#end[94]..SpaceVim#plugins#load:
line    4:

**Comment by TargetLiu** [comment]
遇到同样的问题了。。。

**Comment by wsdjeg** [comment]
I will fixed it. but github is for english only.

**Comment by witem** [comment]
Hi @wsdjeg 
After update I  have same problem:

```
Error detected while processing /home/user/.SpaceVim/autoload/SpaceVim/api/iconv/bytes.vim:
line    1:
E15: Invalid expression: expand('<sfile>:p:r:gs?[\\/]?#?:s?^.*#autoload#??:s?$?#?')^M
Error detected while processing function SpaceVim#end[94]..SpaceVim#plugins#load[4]..<SNR>60_load_plugins:
line   16:
E170: Missing :endfor
Error detected while processing function SpaceVim#end[94]..SpaceVim#plugins#load:
line    4:
E171: Missing :endif
```

How to fix it?
