### ISSUE TITLE
Disabling plugins doesn't work ?

### ISSUE THREAD

**Issue by Thierry** [wsdjeg/SpaceVim#32]
Hi,

Documentation mentions a g:spacevim_disabled_plugins variable to disable some plugins, but I fail to make it work nor can I find it anywhere in the code except in the documentation itself.

Can you confirm that this hasn't been implemented yet ? or abandoned but left in the docs ?

Thanks in advance,
Regards,
Thierry

**Comment by wsdjeg** [comment]
sorry, this feature has not been implement.

EXIT:  My next work it implement it.
