### ISSUE TITLE
dwm unknow function issue

### ISSUE THREAD

**Issue by hongjiujin** [wsdjeg/SpaceVim#320]
## Environment Information
- OS:Ubuntu14.04
- vim version: 7.4.52                                                                             
- neovim version:

## The reproduce ways from Vim starting (Required!)
[tommy@tommy-VirtualBox ]$vim
Error detected while processing /home/tommy//.cache/vimfiles/.cache/vimrc/.dein/plugin/dwm.vim:
line 19:
E117: Unknown function: unite#custom_action
Press ENTER or type command to continue

[dein] ( 1/63) |Lightning | ['git', 'clone', '--recursive', 'https://github.com/wimstefan/Lightnin.../.cache/vimfiles/repos/github.com/wimstefan/Lightning']

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
I make a fork of unite-dwm, so I use the fork in SpaceVim, this issue should be fixed.

**Comment by hongjiujin** [comment]
[tommy@tommy-VirtualBox ~]$vim
Error detected while processing function cmass#director#hPluginLocal:
line   11:
E121: Undefined variable: v:false
E15: Invalid expression: v:false
E121: Undefined variable: v:false
E15: Invalid expression: v:false
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
Please install vim8
