### ISSUE TITLE
clang autocomplete works poorly

### ISSUE THREAD

**Issue by dnaihao** [wsdjeg/SpaceVim#3202]
## Expected behavior, english is required
I have already enabled the lang#c layer in the init.toml in .Spacevim.d. However, it seems that clang is working fine when I try to type simple C++ data types.
![Screenshot from 2019-10-26 21-01-44](https://user-images.githubusercontent.com/46325823/67627970-37394a00-f834-11e9-9e42-2f9e31684c28.png)

But it fails to autocomplete the method in the standard library:
![Screenshot from 2019-10-26 21-02-01](https://user-images.githubusercontent.com/46325823/67627980-5d5eea00-f834-11e9-94e3-3d4a5b4c8dd4.png)

## The reproduce ways from Vim starting (Required!)
Add 
```
[[layers]]
name = "lang#c
```
to the init.toml file in .Spacevim.d repo to enable the lang#c layer.
Do
```
sudo apt install clang
```
to install clang

My 
```
echo | clang -E -v -x c++ -
```
outputs
![Screenshot from 2019-10-26 21-09-07](https://user-images.githubusercontent.com/46325823/67628012-e9711180-f834-11e9-875b-cd7a54abbc97.png)

**Comment by wsdjeg** [comment]
sorry, for late reply, in the second picture,  where does `pq` definded?

**Comment by wsdjeg** [comment]
Compiler options can be configured in a `.clang` file in each project root. Example of `.clang` file:

```
-DDEBUG
-include ../config.h
-I../common
-I/usr/include/c++/4.5.3/
-I/usr/include/c++/4.5.3/x86_64-slackware-linux/
```
