### ISSUE TITLE
Unknown window obstructs file search result

### ISSUE THREAD

**Issue by HouzuoGuo** [wsdjeg/SpaceVim#3204]
Hello!

When I press Ctrl+P in order to search for a file to open, this rather unusual window of irrelevant candidates pops up:
![1](https://user-images.githubusercontent.com/563872/67850598-5f18fe00-fb11-11e9-90ff-e8cf4933900f.png)

Next, as search filter input is given, the unusual window dismisses itself and is then replaced with proper search result:

![2](https://user-images.githubusercontent.com/563872/67850678-8bcd1580-fb11-11e9-9c11-70f8c98b2b0f.png)

This is normally not an issue, however, every third time I do Ctrl+P the unusual window does not dismiss. The search results appear in a window behind it and hence the search result isn't visible.

Where does that window come from?

Here's my `init.toml`:

<pre>
[options]
    statusline_inactive_separator = "nil"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
  name = "denite"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "nil"
  auto-completion-tab-key-behavior = "smart"
  auto-completion-complete-with-key-sequence = "nil"
  auto_completion_delay = 500

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 25

[[layers]]
  name = "tmux"

[[layers]]
  name = "git"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#extra"

</pre>

**Comment by jyscao** [comment]
`<Ctrl-p>` for you performs the same functionality as `SPC p f` (rec files search in project root)?

**Comment by HouzuoGuo** [comment]
@jyscao Indeed they appear to perform the same search function.

**Comment by jyscao** [comment]
So does the obstruction of search results on every third invocation of Denite also happen if you use `SPC p f`?

**Comment by HouzuoGuo** [comment]
@jyscao That's affirmative.

BTW - I was wrong about the "every third time" observation. Whether the strange window stays (and obstructs denite search result window) seems to be rather random, it happens less often when I open a project consisting of *.go files, but way more often when a project consists of *.js files mostly.

**Comment by HouzuoGuo** [comment]
Here's the problem in live action:

1. Open a Javascript project and execute SPC-p-f (or Ctrl+P)

![bad1](https://user-images.githubusercontent.com/563872/67856671-bf15a180-fb1d-11e9-8d03-815c11216eb3.png)

Observe that, the strange window shows up and stays - even after I have already entered search criteria.

2. I try to dismiss the strange window with ESC

![bad2](https://user-images.githubusercontent.com/563872/67856761-ebc9b900-fb1d-11e9-987e-994163f6518c.png)

The window dismisses, exposing denite search result.

**Comment by jyscao** [comment]
Sorry man, I can't reproduce the problem using Denite, which I've stopped using a while back due to quirks of similar nature (UI and input-related) that I kept on experiencing. I know @wsdjeg uses denite, maybe he has an idea of what's going on?

**Comment by HouzuoGuo** [comment]
@jyscao that's all right. I'm also little disappointed at the stability of denite integration in SpaceVim. Do you use an alternative layer/plugin to help with quick file search filter?

**Comment by jyscao** [comment]
@HouzuoGuo In fact I do, FZF works much nicer in SpaceVim imo. Also if all you want from your fuzzy finder is project navigation, then you should also consider the new layer I added for this plugin called CtrlSpace, which is by far the best plugin I've ever used for this purpose.

**Comment by wsdjeg** [comment]
It is feature of denite, denite provides two mode, normal mode and insert mode, in insert mode if you press Esc, it switch to normal mode, and the denite windows will keep opened. you can press q to close the windows now.

You want to close denite in insert mode?
--------------
wsdjeg

**Comment by HouzuoGuo** [comment]
@jyscao thanks very much for the recommendation, I substituted denite with fzf and woah it's smart!

@wsdjeg In the faulty case, the quick search filter input disappears when I press ESC, so there's no way to perform the search action at all.
