### ISSUE TITLE
Conditional enable layer in init.toml

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3207]
I share my [SpaceVim configuration](https://github.com/thawk/dotspacevim) between multiple computers, including Linux/Windows/MacOS. These computers have different usage (for work, for home; for developing, for desktop).

Based on different usage and different packagaes installed, I want to enable different layers on different computer. e.g., I enable the ``gtags`` for developing, but I when I save a file in desktop computer, an error occurs saying ``you need to install global``, so I want to just enable ``gtags`` layer in my developing environment.

I know I can manual call ``SpaceVim#layers#disable()`` to disable an unneeded layer, be it's hard to maintain.  I suggest to add an ``if`` condition for layer configuration in ``init.toml``.  e.g.: 

```toml
[[layers]]
  name = 'gtags'
  if = 'executable("global")'
```

**Comment by wsdjeg** [comment]
That is a nice feature. I will look into it.
