### ISSUE TITLE
markdown-preview plugin always build failed...

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#3208]
![图片](https://user-images.githubusercontent.com/1751829/67925722-19326780-fbef-11e9-91f3-d13a69c11466.png)

**Comment by deepseeksss** [comment]
must install yarn first

**Comment by jyscao** [comment]
@Matrix-Zhang If your source for SpaceVim has #3154 then `npm` would be able to build `markdown-preview.nvim` too

**Comment by hedich** [comment]
i am having this issue now and i do have yarn installed, (1.22.0)
any ide how to solve this?

**Comment by wsdjeg** [comment]
Just simple run `yarn install` or `npm install` in the directory of the plugin. the dir should be:

~/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim

**Comment by willismonroe** [comment]
I've run both `yarn install` and `npm install` in that directory, both commands completed successfully but SpaceVim still reports "Building failed" and the <SPC>-<l>-<p> "live preview" doesn't work.

**Comment by thomdlee** [comment]
I am having this issue as well, I have run the suggested commands and then done a plugin update, build still fails.

@willismonroe did you ever find a fix for this?

**Comment by genzouw** [comment]
> Just simple run `yarn install` or `npm install` in the directory of the plugin. the dir should be: ~/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim

@wsdjeg thanks !
I am success by your advice.
