### ISSUE TITLE
I can't seem to make the fonts/UI look good

### ISSUE THREAD

**Issue by pablote** [wsdjeg/SpaceVim#3216]
## Expected behavior, english is required

I expect the UI to look good/right, but some fonts seem to be missing and I see a [?] character instead in several places. I understand that a nerd-font is required for this to work, I've already installed it, but it didn't had any effect (see screenshots).

## The reproduce ways from Vim starting (Required!)

what? just running `vim` shows the problem. This is on macOS 10.14.6.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below. 

<img width="1310" alt="Screen Shot 2019-11-04 at 19 27 27" src="https://user-images.githubusercontent.com/2463995/68163418-38a3fa00-ff39-11e9-9990-9b1dcff99bb7.png">

Not working, not sure why. All other options under `SPC h` work, but not this one, it doesn't do anything. Showing the output of `SPC h L` instead:

## Screenshots

![Screen Shot 2019-11-04 at 19 24 46](https://user-images.githubusercontent.com/2463995/68163450-4d808d80-ff39-11e9-9ffd-ec7434138d39.png)
<img width="1385" alt="Screen Shot 2019-11-04 at 19 24 28" src="https://user-images.githubusercontent.com/2463995/68163462-53766e80-ff39-11e9-941f-91d6d505bbd1.png">

**Comment by Guzzii** [comment]
@pablote Did you run SpaceVim in a terminal emulator?

**Comment by pablote** [comment]
Yes, I've tested it from iTerm2 and the mac Terminal app

**Comment by Guzzii** [comment]
Setting the font to nerd font from your terminal preference will fix the problem. gui_font in the options is used when spacevim is running from a gui app like macvim.app or nvim-qt.app.

**Comment by pablote** [comment]
awesome, that worked, thanks for the clarification
