### ISSUE TITLE
How Does Java Lombok configure?

### ISSUE THREAD

**Issue by xqiljkxw** [wsdjeg/SpaceVim#3220]
How Does Java Lombok configure?

**Comment by wsdjeg** [comment]
~~lombok is a new language which can be translated to java. the syntax highlight is different from java.~~

sorry, java  layer support maven project, so you can use pom.xml to add lombok.

**Comment by pghalliday** [comment]
I've been fighting for a while now to get a Gradle project working properly which I thought was supposed to be supported. Does your last comment mean that Gradle projects are not supported?

I have had considerable issues getting javacomplete2 and Neomake to work with a Gradle project, I had to hack the Neomake classpath to match the javacomplete2 classpath and now I find that the lombok annotations are not being processed. Should I just give up? :(

**Comment by wsdjeg** [comment]
@pghalliday sorry, I do not know, as I know jc2 supports gradle project, ans the classpath should be used in neomake, I do not know why it des not know, maybe you can use mini proejct example in neomake github repo.

BTW, comment on closed issue maybe will not get reply. for general disscussion, you can use gitter chat.

**Comment by pghalliday** [comment]
Thanks for the response :) I'm going to put this down for now as it's super frustrating, but I should pick it up later and look into these issues. I think at least some of them are known:

https://github.com/neomake/neomake/issues/1971

And I had to adjust this workaround as `g:JavaComplete_ProjectKey` is empty in my project:

https://gist.github.com/Amar1729/49221cee3b9fc48fa3033893757d4473
