### ISSUE TITLE
How to remove typing suggestions when typing English?

### ISSUE THREAD

**Issue by thomasd3** [wsdjeg/SpaceVim#3224]
I have tried discord, gitter and telegram and couldn't get an answer:

When I type some English text, I have suggestion popups coming all the time, based on words in the buffer. How can this be disabled completely?

**Comment by Shougo** [comment]
You can disable auto complete layer or

```vim
call deoplete#custom#option('auto_complete', v:false)
```

**Comment by thomasd3** [comment]
what do you mean by 'call'? I'm a total newbie to this :) is it a line I put in the init.toml file? (I'm looking for a permanent forever removal of that, not disabling it in the current instance)

**Comment by thomasd3** [comment]
I have removed the deoplete plugin completely (remove the folders) and I still see the popup, so maybe we're not talking about the same thing.

this is the one I am talking about:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/14313218/68981720-a89d6480-0804-11ea-9ead-be07b80fbada.png">

**Comment by Shougo** [comment]
ncm2 plugin seems enabled instead.
You need to disable auto completion layer.

**Comment by wsdjeg** [comment]
It is not issue with spacevim, in spacevim we do not use ncm2

**Comment by thomasd3** [comment]
it's not ncm2:

```
[thomas:~/.SpaceVim/config/plugins] $ sudo find ~ -name '*ncm2*'
[thomas:~/.SpaceVim/config/plugins] $

```

what other plugin could cause this?

**Comment by thomasd3** [comment]
I just confirmed it is in SpaceVim:

> curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall

popup gone

I re-install, that popup is back

I just have no clue what does this.

**Comment by Shougo** [comment]
I think SpaceVim uses some auto completion plugin.
Please read this.

https://spacevim.org/layers/autocomplete/

**Comment by thomasd3** [comment]
that was it! thanks.

solution:
> chmod 0 ~/.SpaceVim/autoload/SpaceVim/layers/autocomplete.vim

**Comment by aryvector** [comment]
I think just removing the call function of deoplete plugin in the autocomplete.vim would be fine.

![removedeoplete](https://user-images.githubusercontent.com/70763668/100480200-78abc100-30e8-11eb-9357-5721c430c819.png)
