### ISSUE TITLE
Linux 下 界面部分字符显示方块，参照git的截图，可以看到是几个特殊字符未显示正常

### ISSUE THREAD

**Issue by zqq1314521** [wsdjeg/SpaceVim#323]
## Environment Information
- OS: 虚拟机+elementary OS 
- vim version: 7.4
- neovim version: 

## The reproduce ways from Vim starting (Required!)

![208558407](https://cloud.githubusercontent.com/assets/11797135/23744964/5a085924-04f1-11e7-8027-34d0780cea75.png)

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
你需要安装相应的powerline字体。这个方块就是不识别的字体。

**Comment by zqq1314521** [comment]
thx a lot 我试试 确实是缺少字体的问题 谢谢了

**Comment by tao12345666333** [comment]
@zqq1314521  可以参考 https://github.com/tao12345666333/vim/issues/6

**Comment by wsdjeg** [comment]
谢谢

**Comment by wsdjeg** [comment]
@tao12345666333 刚才我看了你的配置，有几个很老的插件，比如tabman，有什么特性么，五年都没有更新了，你还在用，为什么不用airline呢？

**Comment by tao12345666333** [comment]
@wsdjeg  tabman 可以很方便的管理tab https://github.com/tao12345666333/vim/blob/master/README-zh.md#灵活的tab管理  

状态栏是在用 Airline

**Comment by wsdjeg** [comment]
我还是比较喜欢细腻一点的界面，这个插件我看了，tabline不是很好看，如果可以配合airline 的tabline扩展倒是不错的选择，有时间可以协助搞搞spacevim呀😄

**Comment by tao12345666333** [comment]
@wsdjeg  好的，我抽空看下 😄
