### ISSUE TITLE
Auto save buffer

### ISSUE THREAD

**Issue by exic** [wsdjeg/SpaceVim#3233]
Many modern IDEs/Editors have auto save (e. g. IntelliJ), you don't need to press `Ctrl+s`/`:w<CR>`/`SPC f s` constantly to write the current file to disk. Wouldn't that be a nice feature for spacevim, too?

**Describe alternatives you've considered**
Before spacevim, I've had those lines in my .vimrc, where would I put those now?
`set autowrite`
`autocmd InsertLeave,TextChanged,FocusLost,BufLeave * silent! update`

I've seen plugins, like in #3025, but that seems a bit too much.

**Comment by wsdjeg** [comment]
You can use use bootstrap function. https://spacevim.org/documentation/#bootstrap-functions

**Comment by rduan** [comment]
Hi, Could you explain how to set it using bootstrap function?  thanks.

**Comment by genzouw** [comment]
This thread is a good tip. thanks.

**Comment by wsdjeg** [comment]
This feature has been added, please checkout the [`edit` layer doc](https://spacevim.org/layers/edit/) or `:h SpaceVim-layers-edit`
