### ISSUE TITLE
Pane Navigation Shouldn't Be Mapped to Arrow Keys

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#324]
## Expected behavior, english is recommend
SpaceVim remaps C-H, C-J, C-K, C-L to use the C-Left, C-Up, C-Down, and C-Right for pane navigation. 

There are several issues with this. On OSX, these are global default shortcut keys used for desktop navigation. SpaceVim is essentially unusable on OSX.

The other issue is that the use of arrow keys is anti-Vim. A majority of people using Vim use hjkl since it is 1) the default and 2) much more efficient since your hand never leaves the home row.

```
umap <C-Left>
nnoremap <silent> <C-H> :<C-u>wincmd h<CR>
```

I tried doing this with all of the pane navigation shortcuts in my config, and it almost worked okay, but C-H is bound to Unite help. This is odd because the rest of the Unite shortcuts use the leader.

https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bvim/better-defaults/README.md

This is a project in a similar vain, but with better shorcut keys.

## Environment Information
- OS: OSX
- vim version:
- neovim version:

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
Sorry, it is the default mapping of SpaceVim, and most of the user has been used to all the mappings, me too.

and if you do not like the mapping, I think you can remap it.

**Comment by nate0001** [comment]
So you're going to alienate all Mac users? At least fix the unite mapping.

**Comment by wsdjeg** [comment]
@nate0001 no, but what mapping do you want? or just remove `<c-h,j,k,l>`?

**Comment by ghost** [comment]
As I explained, C-H is bound to unite help when all other unite keys are bound with leader.

**Comment by wsdjeg** [comment]
oh， sorry， that is a bad mapping, will remove it.

**Comment by wsdjeg** [comment]
fixed in #331

**Comment by ghost** [comment]
Maybe have a setting for use_classic_navigation_keys or something and default to this for OSX. That way people that are already accustomed to arrow keys won't have to switch, and people that want classic hjkl can easily have it set.

**Comment by wsdjeg** [comment]
for me, I use `ctrl`+ arrow keys, but I think ctrl + hjkl is very common keymapping in vim. why osx user can  not use it?

**Comment by wsdjeg** [comment]
`vim -u NONE`, in insert mode the default `<C-j>` is `^@`, it means `Enter`.

**Comment by ghost** [comment]
ctrl+arrow keys are global shortcuts in OSX

**Comment by wsdjeg** [comment]
now you can use SPC+w+hjkl

**Comment by inscapist** [comment]
Adding the tmux layer [here](https://spacevim.org/layers/tmux/) works for me

**Comment by wsdjeg** [comment]
@sagittaros thanks, this issue is too old, but I think this issue has gone.

**Comment by codeanpeace** [comment]
Hey, I just ran into this trying out spacevim today. The problem seems to be that the tmux layer lets you ctrl+hjkl across tmux/spacevim panes but within spacevim panes themselves, only ctrl+arrows or space+w+hjkl works.

I imagine that for people who are used to being able to ctrl+hjkl across all panes regardless of whether they're tmux or vim panes, this is a big usability issue as now we have to account and adjust for the different interface depending on the type of pane.

Is there a way to add an option to the tmux layer that allows for ctrl+hjkl instead of or in addition to ctrl+arrows for pane navigation?
