### ISSUE TITLE
vimfiler error

### ISSUE THREAD

**Issue by AlirezaParsi** [wsdjeg/SpaceVim#3240]
## Environment Information
 - OS: linux (Android Termux)
 - vim version: 8.1.2350
 - neovim version: -
 - SpaceVim version: 1.4.0-dev
- branch origin/master
==============================

Hi 👋 , when i open vim have this error :

`[dein] command VimFiler is not found.`

and vimfiler is already installed.

how fix ? 
![Screenshot_20191129-140814_Termux(1)](https://user-images.githubusercontent.com/29276037/69865179-c2838080-12b5-11ea-8289-ff029d15be56.jpg)

**Comment by wsdjeg** [comment]
vimfiler need vimproc
