### ISSUE TITLE
Full jedi-vim support for python

### ISSUE THREAD

**Issue by daufinsyd** [wsdjeg/SpaceVim#3241]
**Is your feature request related to a problem? Please describe.**
Only a subset of the jedi-vim features seems to be available in space-vim (eg. there is no <leader> r or <leader> n).

**Describe the solution you'd like**
All the features of jedi-vim are available in spacevim

**Describe alternatives you've considered**
use jedi-vim without spacevim ?

**Additional context**
If it can't be done, it would be great to have memo in https://spacevim.org/layers/lang/python/ explaining the jedi-vim integration limitations.

Thanks a lot :)

**Comment by Guzzii** [comment]
> Only a subset of the jedi-vim features seems to be available in space-vim (eg. there is no r or n).

@daufinsyd What exact features are you referring to when you say `there is no r or n`?

**Comment by daufinsyd** [comment]
@Guzzii 
sorry, it seems that the word 'leader' within \<\> was removed. I meant 
`<leader>r and <leader>n`
which correspond to "Renaming" and "Usages". Those are really useful to replace all references of a variable for example.

**Comment by Guzzii** [comment]
@daufinsyd Got you. Interestingly, renaming and usages from Jedi-vim both work for me in neovim. See if you defined the same key bindings for other plugins.

**Comment by daufinsyd** [comment]
@Guzzii 
Okay my bad, I found out (after an eternity) that "s" was a window leader (whatever that means) and "\" was the actual leader I wanted (though it is local or global .. no idea).
I close the bug but I think it would be nice to clearly indicate what is the default leader instead of saying that <leader> is the default vim leader (and how to change it), the same way it's done for the "window" leader.
