### ISSUE TITLE
spacevim start error

### ISSUE THREAD

**Issue by yangshao** [wsdjeg/SpaceVim#3243]
Hi, I installed the spacevim via offline way. when i start it, it reports the following error: 
Error detected while processing /home10/syang634/.cache/vimfiles/.cache/vimrc/.dein/autoload/cscope.vim:
line   49:
E716: Key not present in Dictionary: unify_path('~/.cache/SpaceVim/cscope/')
line   50:
E121: Undefined variable: s:cscope_cache_dir
Error detected while processing function cscope#loadIndex:
line    2:
E121: Undefined variable: s:cscope_cache_dir
E116: Invalid arguments for function isdirectory(s:cscope_cache_dir)
Press ENTER or type command to continue

How can i fix this?

**Comment by wsdjeg** [comment]
I think your spacevim is too old, please update it.
--------------
wsdjeg

**Comment by yangshao** [comment]
@wsdjeg Thanks, where can i download the latest offline package?

**Comment by wsdjeg** [comment]
Please checkout the github page of spacevim
--------------
wsdjeg

**Comment by yangshao** [comment]
@wsdjeg hi, due to some reason, i can only do the offline install. it seems there is no latest offline package of spacevim.

**Comment by jyscao** [comment]
@yangshao You're on Linux right? Have you tried installing SpaceVim via the bash script as per: https://spacevim.org/quick-start-guide/

Edit: by "due to some reason, i can only do the offline install", do you mean that you have no network access on the computer you're trying to use SpaceVim on?
