### ISSUE TITLE
gvim does not install plugins

### ISSUE THREAD

**Issue by offchan42** [wsdjeg/SpaceVim#3250]
## Expected behavior, English is required
gVim should install new plugins as described by the following command
![image](https://user-images.githubusercontent.com/15215732/70559264-e9488d80-1bb8-11ea-8165-da232f16e003.png)

## The reproduce ways from Vim starting (Required!)
1. Install gVim from this link: https://www.vim.org/download.php ![image](https://user-images.githubusercontent.com/15215732/70559344-1006c400-1bb9-11ea-9c9b-d67e8423a9b9.png)
2. Open command prompt in admin mode and type `install.cmd`, then wait for it to finish. After it finishes, I type `gvim` and saw that no plugins are being installed.  
![image](https://user-images.githubusercontent.com/15215732/70559530-6a078980-1bb9-11ea-968d-c588bc60f0fc.png)

Everything is followed by this guide: https://spacevim.org/quick-start-guide/

## Debug info

I use Windows 10 64 bit.

**Comment by someuser549** [comment]
Although this doesn't fix the problem, it is a temporary fix. 

After installing GVim and executing the batch file with administrator privileges, create a `.vimrc` file in your `$HOME` directory. This directoy usually is in `C:/Users/<User>` or in `C:/Users/<User>/Appdata/Local`. In this file put the following command:
````
:source ~/.spacevim/init.vim
````
This should fix the issue.

**Comment by offchan42** [comment]
Yeah, it seems to help. But I wonder why it's the first barrier to installing on Windows and it's not mentioned anywhere on the installation guide?

Maybe SpaceVim people don't use Windows?

Should I remove that line from .vimrc when it's done installing?

**Comment by someuser549** [comment]
I think people that use this kind of text editors are mostly on UNIX platforms. One of two things should be happening here, either the batch script should change the environmental variables of Vim properly or there should be a line added to the documentation reflecting this step. 

You souldn't remove the line from the file. If you do, Vim will go back to its default state.

**Comment by offchan42** [comment]
So this workaround is not bad, right? If so I will close the issue because it seems like it's working.

**Comment by someuser549** [comment]
It seems to work, so yeah, I think it is ok.

**Comment by offchan42** [comment]
OK. Thank you.

**Comment by AdarshI** [comment]
> Although this doesn't fix the problem, it is a temporary fix.
> 
> After installing GVim and executing the batch file with administrator privileges, create a `.vimrc` file in your `$HOME` directory. This directoy usually is in `C:/Users/<User>` or in `C:/Users/<User>/Appdata/Local`. In this file put the following command:
> 
> ```
> :source ~/.spacevim/init.vim
> ```
> 
> This should fix the issue.

When I try to source, I get this error. I have the same problem as OC

![image](https://user-images.githubusercontent.com/11846492/104219112-87c5a480-53f2-11eb-97c6-41e2a147d263.png)

**Comment by AdarshI** [comment]
> Although this doesn't fix the problem, it is a temporary fix.
> 
> After installing GVim and executing the batch file with administrator privileges, create a `.vimrc` file in your `$HOME` directory. This directoy usually is in `C:/Users/<User>` or in `C:/Users/<User>/Appdata/Local`. In this file put the following command:
> 
> ```
> :source ~/.spacevim/init.vim
> ```
> 
> This should fix the issue.

I have the same problem as OC, but when sourcing that file I get this

![image](https://user-images.githubusercontent.com/11846492/104230779-dd09b200-5402-11eb-8b6b-4982666ff08f.png)

**Comment by AndreaCatania** [comment]
Hello, for me the correct fix is add the following line inside the `.vimrc`
```
:source ~/.spacevim/vimrc
```

This file `~/.spacevim/vimrc` has the correct code to start SpaceVim. Hope the windows installation file is fixed soon https://spacevim.org/quick-start-guide/#windows

cc @wsdjeg

**Comment by 17Swagat** [comment]
> Hello, for me the correct fix is add the following line inside the `.vimrc`
> 
> ```
> :source ~/.spacevim/vimrc
> ```
> 
> This file `~/.spacevim/vimrc` has the correct code to start SpaceVim. Hope the windows installation file is fixed soon https://spacevim.org/quick-start-guide/#windows
> 
> cc @wsdjeg

THANKS A LOT MAN IT WORKED FOR ME
