### ISSUE TITLE
Fix CursorLine highlighting in new versions of Neovim

### ISSUE THREAD

**Issue by zfzackfrost** [wsdjeg/SpaceVim#3251]
**The Problem**
I recently tried SpaceVim for the first time and I love it. However, there is one thing that I believe can make the experience better for those of us that use it with Neovim. In recent releases of Neovim, the priority of the `Normal` highlighting group has been raised so that it overrides things like the `CursorLine` group. See [this issue](https://github.com/neovim/neovim/issues/9019) for details. The issue is still open but the team makes it sound like they intend to keep things this way. 

**Describe the solution you'd like**
Most solutions discussed in the issue linked above involve colorscheme authors modifying their themes to work with the newest Neovim. My solution from [this reply](https://github.com/neovim/neovim/issues/9019#issuecomment-521532103) will work with any colorscheme (as far as I know) without extra work by the SpaceVim user. 

**Additional context**
For reference here is the vimscript snippet from the workaround I referenced above:
```vim
function! s:CustomizeColors()
	if has('guirunning') || has('termguicolors')
		let cursorline_gui=''
		let cursorline_cterm='ctermfg=white'
	else
		let cursorline_gui='guifg=white'
		let cursorline_cterm=''
	endif
	exec 'hi CursorLine ' . cursorline_gui . ' ' . cursorline_cterm 
endfunction

augroup OnColorScheme
	autocmd!
	autocmd ColorScheme,BufEnter,BufWinEnter * call s:CustomizeColors()
augroup END
```
This is originally from the Neovim git so it doesn't follow SpaceVim conventions. However, I have tested this code and it works as intended for me.

**Comment by wsdjeg** [comment]
Ok, I will check it.

**Comment by wsdjeg** [comment]
@zfzackfrost which colorschem are you using, I can not reproduce it in vim-one.

**Comment by zfzackfrost** [comment]
> @zfzackfrost which colorschem are you using, I can not reproduce it in vim-one.

Gruvbox should trigger the visual artifacts. Not all Vim filetypes cause this promblem, but I can confirm that Vimscript will.

**Comment by wsdjeg** [comment]
@zfzackfrost hello, as neovim 0.4.3 has been released, does this issue still happened in latest version, but I can not reproduce it in spacevim, whcih colorscheme are you using?
