### ISSUE TITLE
After run :SPUdate my vim can't run correct

### ISSUE THREAD

**Issue by xushaobo** [wsdjeg/SpaceVim#3257]
E492: Not an editor command: ^M
line   10:
E15: Invalid expression: 1^M
line   23:
E171: Missing :endif
Press ENTER or type command to continue
   ~  vim ~/.SpaceVim/vimrc 
Error detected while processing /home/manbofish/.SpaceVim/vimrc:
line    8:
E492: Not an editor command: ^M
line   10:
E15: Invalid expression: 1^M
line   23:
E171: Missing :endif
Press ENTER or type command to continue
   ~  vim ~/.SpaceVim/vimrc
Error detected while processing /home/manbofish/.SpaceVim/vimrc:
line    9:
E15: Invalid expression: 1^M
line   22:
E171: Missing :endif
Press ENTER or type command to continue
   ~  nvim
Error detected while processing /home/manbofish/.SpaceVim/init.vim:
line    8:
E492: Not an editor command: ^M
line    9:
E15: Invalid expression: ^M
E15: Invalid expression: ^M
Error detected while processing /home/manbofish/.SpaceVim/filetype.vim:
line    8:
E492: Not an editor command: ^M
line   10:
E216: No such group or event: ^M
line   14:
E492: Not an editor command: ^M
Press ENTER or type command to continue

**Comment by jyscao** [comment]
You still having this problem?

**Comment by wsdjeg** [comment]
This is issue with your git config.
