### ISSUE TITLE
Folding showing question mark.

### ISSUE THREAD

**Issue by duqcyxwd** [wsdjeg/SpaceVim#3259]
## Folding now showing as a question mark 

Fold any code and the question mark is shown:

## Screenshots
For example:

![Screen Shot 2019-12-17 at 7 54 13 PM](https://user-images.githubusercontent.com/2519905/71046826-90707c00-2107-11ea-8b7a-559fa450a549.png)

I think it can be fix here: https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/default.vim#L336

All we need is using a standard character.

**Comment by jyscao** [comment]
Did the character show up properly for you before, because it does for me? It's a unicode "centered-small-dot" (not the actual name, just my description).

**Comment by wsdjeg** [comment]
Ok, let's change it to a standard character.
