### ISSUE TITLE
[SPC]TF not work as expected

### ISSUE THREAD

**Issue by vincent-vivian-liu** [wsdjeg/SpaceVim#3261]
## Expected behavior, english is required
`SPC T F` is supposed to toggle full screen, which is nnoremaped to `F11`.
But the `F11` is also nnoremaped to other vim function call.
While nnoremap is used to disable to recursive mapping.

## The reproduce ways from Vim starting (Required!)
just hint
`SPC T F`
in the normal mode
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by jyscao** [comment]
> But the F11 is also nnoremaped to other vim function call

By that I guess you mean the lines below in `autoload/SpaceVim/layers/ui.vim`:

```
  if has('nvim')
    nnoremap <silent> <F11> :call <SID>toggle_full_screen()<Cr>
  else
    nnoremap <silent> <F11> :call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)<cr>
  endif
```

However, I'm not convinced that those even work. Because when I changed the command <kbd>F11</kbd> mapped to, pressing <kbd>F11</kbd> still full-screened my terminal window, which is what it does even without this added mapping inside SpaceVim.

But yes, `SPC-T-F` indeed doesn't seem to work as advertised.

**Comment by wsdjeg** [comment]
If you are using gvim, make sure you have gvimfullscreen.dll in your path.

**Comment by vincent-vivian-liu** [comment]
> If you are using gvim, make sure you have gvimfullscreen.dll in your path.

Thanks for your reply.
Yes, you are right.
Sorry, I report that error with missed info.
I use ubuntu 14, and i installed wmctrl for supporting full-screen and define a toggle-fullscreen function using wmctrl in ~/.SpaceVim.d/autoload/myspacevim.vim, as i think (may not correct) gvimfullscreen.dll not work in Linux env.
In fact, what I really mean is two-fold:
1, nnoremaped for `<F11>` should be changed to nmap to support recursive.
2, Even though `n~~nore~~map <F11>`, in `ubuntu 14 + gvim + wmctrl`, if you type `[SPC] T F` not so quickly, you can't let fullscreen function work. Only if you type `[SPC] T F` very fast will let gvim calling the final toggle-fullscreen function. So i recommend just `nnoremap <F11> :call [your toggle-fullscreen function]` using `SpaceVim#mapping#sapce#def` will be better.

**Comment by vincent-vivian-liu** [comment]
> > But the F11 is also nnoremaped to other vim function call
> 
> By that I guess you mean the lines below in `autoload/SpaceVim/layers/ui.vim`:
> 
> ```
>   if has('nvim')
>     nnoremap <silent> <F11> :call <SID>toggle_full_screen()<Cr>
>   else
>     nnoremap <silent> <F11> :call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)<cr>
>   endif
> ```
> 
> However, I'm not convinced that those even work. Because when I changed the command F11 mapped to, pressing F11 still full-screened my terminal window, which is what it does even without this added mapping inside SpaceVim.
> 
> But yes, `SPC-T-F` indeed doesn't seem to work as advertised.

Yes, that is the place where `<F11>` really be defined.
And yes, Terminal works well as when typing `<F11>`, this event may be caught by the terminal first but not by the vim.
But in gvim, when typing `<F11>`, this event, can be caught by the gvim. 
And gvim will call function which is configured by SpaceVim#mapping#space#def for `fullscreen-frame` and nnoremap for `<F11>`  in .../ui.vim.

**Comment by wsdjeg** [comment]
@vincent-vivian-liu hi, sorry for later reply, I still can not reporuce it in spacevim, if you are using key binding out vim itself, for example, the winctrl key binding, this key can not be call in vim script.

**EDIT:** just note, if the key is call befored it is send to vim, there is nothing can be done in vim.
