### ISSUE TITLE
python_host_problem

### ISSUE THREAD

**Issue by matianhe3** [wsdjeg/SpaceVim#3263]
![image](https://user-images.githubusercontent.com/24929062/71303121-492c0900-23ef-11ea-9a6d-a76c6988d709.png)
I try `let·g:python3_host_prog = "/usr/local/bin/python3"` in .SpaceVim/config/main.vim
and `export PYTHON3_HOST_PROG='which python3'`

**Comment by jyscao** [comment]
Don't set that variable in `config/main.vim`, it'll just get overwritten when you update SpaceVim.

Instead set it from the bootstrap functions, which allows you to just set it like you normally would inside of your personal `vimrc` config. See this section of the docs: https://spacevim.org/documentation/#bootstrap-functions

**Comment by wsdjeg** [comment]
please checkout spacevim faq，

spacevim.org/faq<http://spacevim.org/faq>/



发自我的小米手机
在 Jethro Cao <notifications@github.com>，2019年12月22日 15:37写道：

Don't set that variable in config/main.vim, it'll just get overwritten when you update SpaceVim.

Instead set it from the bootstrap functions, which allows you to just set it like you normally would inside of your personal vimrc config. See this section of the docs: https://spacevim.org/documentation/#bootstrap-functions
