### ISSUE TITLE
TypeScript REPL

### ISSUE THREAD

**Issue by blackxored** [wsdjeg/SpaceVim#3264]
TypeScript needs a REPL with (probably) `ts-node`.

**Comment by jyscao** [comment]
Good feature request.

In the meanwhile, if you know of an existing vim plugin for typscript REPL support, then you can start using it by adding it to your custom plugins, see: https://spacevim.org/documentation/#custom-configuration

**Comment by wsdjeg** [comment]
@blackxored I just open an PR for this feature, but `ts-node` do not print result to stdout/stderr.

**Comment by wsdjeg** [comment]
@blackxored @jyscao the ts-node develop team has fixed this issue now, so this can be used in SpaceVim.

https://github.com/TypeStrong/ts-node/issues/1013
