### ISSUE TITLE
[string "vim chunk"]:1: module 'spacevim.api.vim.window' not found:

### ISSUE THREAD

**Issue by BlasphemyAngels** [wsdjeg/SpaceVim#3265]
![image](https://user-images.githubusercontent.com/16065707/71443932-d2717180-2748-11ea-94fd-b13df251d69a.png)

mac os
vim 8

**Comment by jyscao** [comment]
Do you have the steps to reproduce these error messages?

**Comment by wsdjeg** [comment]
It seems a bug, the path has be not been added to lua runtime.

**Comment by zenlinux121** [comment]
> It seems a bug, the path has be not been added to lua runtime.

Hello @wsdjeg how can we add the path to spacevim Lua runtime on Linux ?
I have the same error message when trying to execute REPL for python in Debian 10 and SpaceVim 1.4.0-dev-0c8b422d

Thank you.

**Comment by wsdjeg** [comment]
in vimrc of spacevim you can find this code:

```vim
    if has('lua')
        let s:plugin_dir = fnamemodify(expand('<sfile>'), ':h').'\lua'
        let s:str = s:plugin_dir . '\?.lua;' . s:plugin_dir . '\?\init.lua;'
        silent! lua package.path=vim.eval("s:str") .. package.path
        if empty(v:errmsg)
            let g:_spacevim_if_lua = 1
        endif
    endif
```

I am not sure will it can not add the path to lua runtime.

**Comment by zenlinux121** [comment]
> in vimrc of spacevim you can find this code:
> 
> ```viml
>     if has('lua')
>         let s:plugin_dir = fnamemodify(expand('<sfile>'), ':h').'\lua'
>         let s:str = s:plugin_dir . '\?.lua;' . s:plugin_dir . '\?\init.lua;'
>         silent! lua package.path=vim.eval("s:str") .. package.path
>         if empty(v:errmsg)
>             let g:_spacevim_if_lua = 1
>         endif
>     endif
> ```
> 
> I am not sure will it can not add the path to lua runtime.

Thank you I will check it.
