### ISSUE TITLE
There is no “~/.SpaceVim.d/init.toml” by default after install spacevim sucessfully

### ISSUE THREAD

**Issue by flytoylf** [wsdjeg/SpaceVim#3267]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by jyscao** [comment]
Hmmm, you could try creating the directory plus the TOML config yourself, and see if that gets loaded successfully upon starting SpaceVim. Use this as a template for your own config file: https://spacevim.org/quick-start-guide/

If that doesn't work, we can debug from there.

**Comment by cdmistman** [comment]
I just ran into this 20 minutes ago.

I ran neovim, selected the mode (normal vs dark-powered), and then the file was created
