### ISSUE TITLE
spacevim on termux can't use vimfiler and defx

### ISSUE THREAD

**Issue by luoyou** [wsdjeg/SpaceVim#3268]
## Expected behavior, english is required
use file tree

## The reproduce ways from Vim starting (Required!)
everytime, start spacevim, there is no file tree.  
use ```SPC f o```, it notice：
```
vim:E492: Not an editor command: VimFiler -finf
```

## Screenshots
![图片](https://user-images.githubusercontent.com/2688923/71545329-c98cd400-29c4-11ea-9343-18293d728b17.png)

I found two closed issue:
https://github.com/SpaceVim/SpaceVim/issues/3240
https://github.com/SpaceVim/SpaceVim/issues/2464
But, There is no solution.

I try use defx, But It notice:
```
[defx] defx requires Python3 support("+python3")
```
But I have installed python3 in termux.

Termux is a linux app on android.

**Comment by Shougo** [comment]
You need to study about what is +python3.
Please describe your environment information more clearly.

**Comment by luoyou** [comment]
Sorry,  the bug template has no Environment Information, so forgot to fill it out.

## Environment Information
- OS: linux (Android Termux)
- vim version: 8.2
- neovim version: -
- SpaceVim version: 1.4.0-dev
- branch origin/master

https://github.com/SpaceVim/SpaceVim/issues/3240#issuecomment-560045952 has a solution, but i don't know how to use.

The +python3, I google it, but not found anything about it. Can you give me some related documents.

Thank you very much.

**Comment by Shougo** [comment]
I recommend for you to read
defx documentation.
https://github.com/Shougo/defx.nvim/blob/master/README.md#installation

**Comment by Shougo** [comment]
To enable +python3 you need to build Vim with Python3.
I think it is not easy for Android terminal environment.

**Comment by Shougo** [comment]
Hm.  vim-python package is available in Termux.

**Comment by luoyou** [comment]
Thanks, I have solved the problem.

Record possible problems under termux, and hope to help others.

VimFiler can't use, and no solution found.
Switch to defx.
Need:
```
pkg install vim-python
pkg install clang
pkg install python
pip install pynvim
```
Then It can use.

Thanks author for help @Shougo

**Comment by monkeyxite** [comment]
Spent hours for this issue since checkheath provider shows python3 + "OK" but could not run py3 or has('python3') successfully.

Luck me found this issue and solution before I open a new ticket, and  supposing this FAQ item should put into a more clear place:
https://spacevim.org/faq/#how-to-enable-py-and-py3-in-neovim
