### ISSUE TITLE
Need document for layer structure and how to make custom layer

### ISSUE THREAD

**Issue by yang-ling** [wsdjeg/SpaceVim#327]
This is not a bug report but document request.

I have read through spacevim's help page in vim, document on this github repository and on official website, but I didn't find any document describing layer structure or how to make custom layer.

Such document will benefit users a lot.

**Comment by wsdjeg** [comment]
@yang-ling Thanks, and what you want is here

https://spacevim.org/development

**Comment by yang-ling** [comment]
Thanks for reply. I didn't check development document before.

That document describes how to write a layer. It is useful.

But is it possible to write a custom layer? I mean say I write a layer named `foo`, and its file is `foo.vim`. Is it possible that I put `foo.vim` under `~/.SpaceVim.d/` and load it as a layer?

I know I can put `foo.vim` under `autoload/SpaceVim/layers/` and load it, but this path is under this repository's control and I don't want to push this `foo.vim` to this repository.

I think my request is something like Spacemacs's `private` directory. Spacemacs's `private` directory is ignored by the repository. Users can make layers under `private` directory and use the custom layers just as other built-in layers.

**Comment by wsdjeg** [comment]
of cause, you can do it.
`~/.SpaceVim.d/` also be added to &rtp.

**Comment by yang-ling** [comment]
@wsdjeg 
Thanks for reply. Do I need write some codes to load custom layer?

I guess `call add(g:spacevim_plugin_groups, 'foo')` is required, right?

**Comment by wsdjeg** [comment]
`call SpaceVim#layers#load('foo')` is better, as show in the develop page, if in the layer there is only one plugin, it is better use `g:spacevim_custom_plugins`

**Comment by yang-ling** [comment]
> call SpaceVim#layers#load('foo') is better, as show in the develop page,

I have to read develop page more carefully.

Thanks for your explanation.
