### ISSUE TITLE
Python REPL not working - E117: Unknown function: bufload

### ISSUE THREAD

**Issue by naefl** [wsdjeg/SpaceVim#3282]
Running on 16.04 Ubuntu docker, fresh install via curl -sLf https://spacevim.org/install.sh | bash

## Expected behavior, english is required

Repl should open to send code to

## The reproduce ways from Vim starting (Required!)

`vim test.py`

`SPC l s i`

## Debug info

Error detected while processing function SpaceVim#plugins#repl#start[5]..<SNR>71_start[10]..43:
line   43:
E117: Unknown function: bufload

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![image](https://user-images.githubusercontent.com/26996526/71784777-4e7b7d00-2fc5-11ea-9af1-ac8b1b931fa3.png)

**Comment by wsdjeg** [comment]
it seems your vim is too old. the version does not have bufload() function. please update your vim. BTW, I will fix it for old vim.

**Comment by Shougo** [comment]
Hm.
bufload function is added in Vim 8.1.1610.
It is not supported in old Vim.

**Comment by wsdjeg** [comment]
```
      " in vim, setbufline will not load buffer automatically
      " but in neovim, nvim_buf_set_lines will do it.
      " @fixme vim issue #5044
      " https://github.com/vim/vim/issues/5044
      let endtext = a:end > lct ? [] : getbufline(a:buffer, a:end + 1, '$')
      if !buflisted(a:buffer)
        call bufload(a:buffer)
      endif
```

here is code which call bufload function, this is used in SpaceVim buffer api (buf_set_lines). I do not know how to fix it.

**Comment by Shougo** [comment]
You need to :edit the file instead.

**Comment by wsdjeg** [comment]
This should be fixed.
