### ISSUE TITLE
Denite crashes on symlinks

### ISSUE THREAD

**Issue by pedrowilkens** [wsdjeg/SpaceVim#3288]
When i search with `SPC p f` denite crashes with message shown in the second screenshot.
Python Version is 3.7.5
neovim Version is v0.3.8

is it denite specific ? Any idea how to solve this problem ? I would like to use SpaceVim as my ide of choice..
### init.toml file
![init toml](https://user-images.githubusercontent.com/25964087/72254090-5c538280-3603-11ea-8aaf-f91fab676074.png)

## Expected behavior, english is required
It should search for files in the project
## The reproduce ways from Vim starting (Required!)
starting vim and typing `SPC p f` in a directory with cycling symlinks

## Screenshots
It seems that it has Problems with symlinks.
![loop](https://user-images.githubusercontent.com/25964087/72255116-3da2bb00-3606-11ea-9875-6e0cb1439b8a.png)

![link](https://user-images.githubusercontent.com/25964087/72255010-edc3f400-3605-11ea-928e-d5b422e83537.png)

**Comment by Shougo** [comment]
It is find command's feature.

You can change the command.

```vim
	" Change file/rec command.
	call denite#custom#var('file/rec', 'command',
	\ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
	" For ripgrep
	" Note: It is slower than ag
	call denite#custom#var('file/rec', 'command',
	\ ['rg', '--files', '--glob', '!.git'])
	" For Pt(the platinum searcher)
	" NOTE: It also supports windows.
	call denite#custom#var('file/rec', 'command',
	\ ['pt', '--follow', '--nocolor', '--nogroup',
	\  (has('win32') ? '-g:' : '-g='), ''])
	" For python script scantree.py
	" Read bellow on this file to learn more about scantree.py
	call denite#custom#var('file/rec', 'command',
	\ ['scantree.py', '--path', ':directory'])
```

Note:  Please read denite's documentation.

**Comment by pedrowilkens** [comment]
Yes I will, I am new to the Vim world and Spacevim, but i love it. Thank you very much for your answer. It did help.

**Comment by Shougo** [comment]
It is closeable?

**Comment by wsdjeg** [comment]
@pedrowilkens Just install another seraching command line tool, such as ag or rg.
