### ISSUE TITLE
Cannot use CMD+C to copy highlighted text into system clipboard

### ISSUE THREAD

**Issue by DanielYWoo** [wsdjeg/SpaceVim#3289]
**Is your feature request related to a problem? Please describe.**
Use v to select text, then I cannot use CMD+C to copy highlighted text into system clipboard.

**Describe the solution you'd like**
Support CMD+C to copy selected text by "v"

**Describe alternatives you've considered**
N/A

**Additional context**
Catalina 10.15.2
tried both iTerm2 & terminal
latest version of spacevim

**Comment by wsdjeg** [comment]
Please use `\ y` to copy to system clipboard, we do not change the default key binding, when using neovim, you can not use `CMD - c` to copy by default. of cause, you can add this key binding into your bootsrtap function, please read `:h <D` in neovim.
