### ISSUE TITLE
Vimspector

### ISSUE THREAD

**Issue by stfl** [wsdjeg/SpaceVim#3294]
[puremourning/vimspector: vimspector](https://github.com/puremourning/vimspector) now supports also neovim and could be an interesting extension / replacement in the the debug layer

**Comment by jidibinlin** [comment]
@stfl  I had used this plugin. It`s very nice but still have some issues. vimspector may be the most powerfull vim debug plugin we ever konw

**Comment by wsdjeg** [comment]
Thank you for advice, before we included this plugin, we should make sure:

1. it works well in neovim and vim
2. it can be used in Linux/Mac and Windows.

**Comment by sudodaksh** [comment]
I think it does @wsdjeg 
There are particular settings for windows and neovim but it does work on it.

**Comment by JryChn** [comment]
agree!

**Comment by mkubasz** [comment]
Agree and waiting in spacevim

**Comment by jermaine007** [comment]
so any news about this plugin?

**Comment by Djedouas** [comment]
Waiting for it in spacevim too, what is there to do?

**Comment by wsdjeg** [comment]
This plugin requires `+python` or `+python3` feature. but it is not enabled by default in vim. we can not use it by default.

**Comment by Grafcube** [comment]
Is it alright if I try to implement this and send a pull request? It will only use vimspector if a config is set in `init.toml`.
