### ISSUE TITLE
windows platform autocomplete bug with python

### ISSUE THREAD

**Issue by 5dash** [wsdjeg/SpaceVim#3295]
windows10
nvim version 0.4.3
SpaceVim version 1.3.0
on WSL it's work perfectly, but on Windows add configuration layers `name = "lang#python"` 
plugin installed 
not appear completion as WSL as normal
trt add `let g:python3_host_prog = 'D:\\Anaconda\\Anaconda3\\python.exe'` in `C:\Users\username\.SpaceVim\init.vim` also not work only buffer info
![bug](https://user-images.githubusercontent.com/53204626/72814755-90ccdb80-3ca0-11ea-88f8-d8424bbe8ade.png)

**Comment by wsdjeg** [comment]
please checkout https://spacevim.org/faq/#how-to-enable-py-and-py3-in-neovim
