### ISSUE TITLE
Cannot create directory: /home/username/.cache/SpaceVim/backup

### ISSUE THREAD

**Issue by BBge** [wsdjeg/SpaceVim#3296]
I use the command: `vim ~/.zshrc`
and it returns that:
`Error detected while processing function SpaceVim#begin[25]..SpaceVim#default#options:`
`line   65:`
`E739: Cannot create directory: /home/username/.cache/SpaceVim/backup`
`Error detected while processing function SpaceVim#custom#load:`
`line   15:`
`E482: Can't create file`
`/home/username/.cache/SpaceVim/conf/_home_username__SpaceVim_d_init_toml.json`
`Error detected while processing function SpaceVim#end[94]..SpaceVim#plugins#load[4]..`
`<SNR>45_load_plugins:`
`line   18:`
`E108: No such variable: "g:_spacevim_plugin_layer"`
`Press ENTER or type command to continue`

I am using ubuntu 18.04.
Thanks!

**Comment by wsdjeg** [comment]
@BBge what is your vim version? and why you can not create dir `/home/username/.cache/SpaceVim/backup`?

**Comment by BBge** [comment]
> @BBge what is your vim version? and why you can not create dir `/home/username/.cache/SpaceVim/backup`?

I am using the VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41).
`mkdir /home/username/.cache/SpaceVim/backup`
`mkdir: cannot create directory ‘/home/username/.cache/SpaceVim/backup’: Permission denied`

**Comment by BBge** [comment]
I have fixed this problem by `chmod -R 777 /home/username/.cache/SpaceVim`.
Thanks!
