### ISSUE TITLE
Support Chez Scheme dialect

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3298]
**What is language?**

lang#scheme

**Which platform does the language support?**

- [x] windows
- [x] Mac os
- [x] Windows

**Any suggest vim plugins for this language?**

No

**Additional context**

[Chez Scheme](https://cisco.github.io/ChezScheme/) is a Scheme dialect by Cisco Inc.  Its executable named 'scheme' at Windows, but named 'chez' at HomeBrew.  Because SpaceVim doesn't support conditional layer option, it prevents  one ``init.toml`` to be used at two OS.

**Comment by wsdjeg** [comment]
@thawk `lang#scheme` layer has been added in spacevim.

https://spacevim.org/layers/lang/scheme/

EDIT:

the guile scheme supported is added in #3127

**Comment by wsdjeg** [comment]
> Because SpaceVim doesn't support conditional layer option, it prevents one init.toml to be used at two OS.

yeah, this should be improved.

**Comment by wsdjeg** [comment]
I have just installed Chez Scheme in my Window 7 OS, after installation done, it provide 4 executable in start menu:

- Chez Scheme 32-bit nonthreaded: `C:\Program Files (x86)\Chez Scheme 9.5\bin\i3nt\scheme.exe`
- Chez Scheme 32-bit threaded: `C:\Program Files (x86)\Chez Scheme 9.5\bin\ti3nt\scheme.exe`
- Chez Scheme 64-bit nonthreaded: `C:\Program Files\Chez Scheme 9.5\bin\a6nt\scheme.exe`
- Chez Scheme 64-bit threaded: `C:\Program Files\Chez Scheme 9.5\bin\ta6nt\scheme.exe`

the only differences is the path of the executable.

so maybe this layer should provide a layer option to set the path of the executable. for example:

```
[[layers]]
  name = "lang#scheme"
  scheme_interpreter = "C:\Program Files\Chez Scheme 9.5\bin\ta6nt\scheme.exe"
```

**Comment by thawk** [comment]
For the different interpreter path, a proper setup of ``PATH`` should work.
Even Chez Scheme for Windows, there are two executable provided: ``scheme.exe`` and ``petite.exe``.  So I think the ability to change repl runner, not the fixed ``scheme``, is helpful.  And it's better to choose runner at run time to make ``init.toml`` sharable between multiple computer.  The easiest way is add chez scheme dialect support, and hardcode interpreter name in the lang#scheme.vim.

**Comment by wsdjeg** [comment]
@thawk It is hard to change runner in init.toml. Because you need to add some complex syntax, and toml does not support these syntaxes. in current version of SpaceVim, there is already one layer option:
`dialect`, which can be set to `mit-scheme` or `guile`.

if we add `scheme_interpreter`, it maybe break backward compatibility.

cc @jyscao

**Comment by wsdjeg** [comment]
I have Update the scheme layer, but the runner output seems wrong:

```
[Running] echo | "C:\Program Files\Chez Scheme 9.5\bin\ta6nt\scheme.exe" C:\Users\wsdjeg\Desktop\test.ss && echo

--------------------
Chez Scheme Version 9.5
Copyright 1984-2017 Cisco Systems, Inc.

Exception: variable ECHO is not bound
Exception: variable 閿熸枻鎷烽敓鑺傝揪鎷风姸鎬侀敓鏂ゆ嫹 is not bound
> > > 
ECHO 处于打开状态。

[Done] exited with code=0 in 0.180308 seconds
```

**Comment by wsdjeg** [comment]
Windows os support has been done.

![Chez Scheme runner](https://user-images.githubusercontent.com/13142418/72999390-47b08f00-3e3a-11ea-9417-ff8d88fc092d.png)

**Comment by thawk** [comment]
> @thawk It is hard to change runner in init.toml. Because you need to add some complex syntax, and toml does not support these syntaxes. in current version of SpaceVim, there is already one layer option:
> `dialect`, which can be set to `mit-scheme` or `guile`.
> 
> if we add `scheme_interpreter`, it maybe break backward compatibility.
> 
> cc @jyscao

I agree that it's difficult to change runner in init.toml.  This is why I suggest to a chez dialect instead.  It's much easier to check if ``chez`` exists and using ``chez`` instead of ``scheme`` while ``chez`` dialect is used.
