### ISSUE TITLE
Can't get the ui

### ISSUE THREAD

**Issue by adeleglise** [wsdjeg/SpaceVim#33]
Hi,

First of all, thanks a lot for sharing your work !

The problem is I can't reproduce the ui showed on the screenshot https://github.com/SpaceVim/SpaceVim#awesome-ui

What I am missing ? Is ther something to install ? 

I'm on archlinux, using terminator and vim.

I've followed the steps to install spacevim, including dein.

**Comment by wsdjeg** [comment]
@adeleglise do you install all the plugins by `call dein#install()`, BTW you should have `git` in your PATH.

**Comment by adeleglise** [comment]
What I've done : 

ran curl -sLf https://raw.githubusercontent.com/SpaceVim/SpaceVim/dev/install.sh | bash
ran vim
:call dein#install()

My path contains /usr/bin and git executable is in /usr/bin.

**Comment by wsdjeg** [comment]
after `call dein#install()`, you should wait a long time. then restart your vim.

**Comment by adeleglise** [comment]
Yep, it takes sometime.

I have restarted vim and this is what it looks like now : 

https://lut.im/0Wfm0JYiFD/Q4AYMNtETJniO7ci.png

**Comment by wsdjeg** [comment]
@adeleglise Type `<F2>` to open tagbar, `<F3>` to open vimfiler, and you will see some thing like the picture shown in the readme. BTW you should install a powerline font. you can get it from my own DotFiles repo. 
https://github.com/wsdjeg/DotFiles/tree/master/fonts

**Comment by adeleglise** [comment]
Yup, got it for the tagbar and the file explorer. Maybe i'm just missing powerline font.

Thanks for your answers.

**Comment by wsdjeg** [comment]
welcome

**Comment by adeleglise** [comment]
Just to know, what terminal emulator are you using ?

The problem is, with terminator, key bindings overlaps.

**Comment by wsdjeg** [comment]
I am using termite.
