### ISSUE TITLE
SpaceVim can't work on my macbook pro

### ISSUE THREAD

**Issue by hkyyx** [wsdjeg/SpaceVim#330]
## Expected behavior, english is recommend
I installed spacevim according the official document, but when i open the vim , nothing changed.
I don't why

## Environment Information
- OS: OSX 10.11.6
- vim version: 7.3
- neovim version:

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by hkyyx** [comment]
Because dein.vim need vim 7.4 or above, when i update my vim , this problem is solved.
Please add requirements for spacevim

**Comment by wsdjeg** [comment]
Thanks, will add it.
