### ISSUE TITLE
How to completely wipe out SpaceVim from a system?

### ISSUE THREAD

**Issue by dzintars** [wsdjeg/SpaceVim#3309]
**Is your feature request related to a problem? Please describe.**
Hi. In [SpaceVim documentation](https://spacevim.org/documentation/) I can't find a section about how to completely remove SpaceVim with all its artifacts.

**Describe the solution you'd like**
Would be nice to add such section at the end of documentation.

**Describe alternatives you've considered**

**Additional context**

**Comment by wsdjeg** [comment]
For more info about the install script, please check:

```bash
curl -sLf https://spacevim.org/install.sh | bash -s -- -h
```

this can be seen in [quick start guide](https://spacevim.org/quick-start-guide/)

**Comment by dzintars** [comment]
@wsdjeg I know where to find a install scripts and how to examine those. But i am taking about `remove`, `uninstall` instructions in the documentation.
As a simple user, i want to read an documented instruction on how to completely remove current software from my system.

**Comment by wsdjeg** [comment]
document is for general usage and configuration, it not for tell you how to install or uninstall something, you can checkout the doc of other project, such as vim or neovim or spacemacs, the install/uninstall section should be list on quick-start-guide only.
