### ISSUE TITLE
markdown-preview plugin not working after fresh install anymore

### ISSUE THREAD

**Issue by msphinct** [wsdjeg/SpaceVim#3323]
## 
Hi, I'm on ubuntu 19.04 and using SpaceVim 1.3.0 with neovim 0.4.3  
I've been using SpaceVim for a while now, and I use MarkdownPreview all the time.
Big fan of SpaceVim! So here's what I found.

MarkdownPreview used to open a page in my browswer when viewing an 'md' file.
I've been using it for over a year now, and it just stopped working recently.  I tried removing all my layers except that one and it still doesn't work. I'm guessing something changed in the plugin.

I found a work around by:

cd ~/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim
yarn install # This step is the work around - asciinema below
cd app ; yarn install

## The reproduce ways from Vim starting (Required!)

1. Do a 'Fresh' install with 'SPUpdate' for the markdown-preview plugin.
2. Open an .md file and view messages after nothing is sent to the browser.
    eg., vi README.md
       :MarkdownPreview # does not work now
       :messages

internal/modules/cjs/loader.js:583                                                                                                                                    
    throw err;                                                                                                                                                        
    ^                                                                                                                                                                 
Error: Cannot find module 'msgpack-lite'                                                                                                                              
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)                                                                                       
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)                                                                                                  
    at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                         
    at require (internal/modules/cjs/helpers.js:22:18)                                                                                                                
    at Object.<anonymous> (/home/pete/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim/app/lib/app/preloadmodules.js:7:21)                               
    at Module._compile (internal/modules/cjs/loader.js:689:30)                                                                                                        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                                                          
    at Module.load (internal/modules/cjs/loader.js:599:32)                                                                                                            
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                                                                                          
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)    

## Debug info                                                                                                                                                         
SpaceVim layers:                                                                                                                                                      

- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
- chinese:              not loaded          https://spacevim.org/layers/chinese/
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- ctrlspace:            not loaded          https://spacevim.org/layers/ctrlspace/
- debug:                not loaded          https://spacevim.org/layers/debug/
- denite:               not loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
+ format:                   loaded          https://spacevim.org/layers/format/
- fzf:                  not loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
- git:                  not loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- gtags:                not loaded          https://spacevim.org/layers/gtags/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#assembly:        not loaded          https://spacevim.org/layers/lang/assembly/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
- lang#batch:           not loaded          https://spacevim.org/layers/lang/batch/
- lang#c:               not loaded          https://spacevim.org/layers/lang/c/
- lang#chapel:          not loaded          https://spacevim.org/layers/lang/chapel/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
- lang#crystal:         not loaded          https://spacevim.org/layers/lang/crystal/
- lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
- lang#d:               not loaded          https://spacevim.org/layers/lang/d/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
- lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
- lang#foxpro:          not loaded          https://spacevim.org/layers/lang/foxpro/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
- lang#go:              not loaded          https://spacevim.org/layers/lang/go/
- lang#goby:            not loaded          https://spacevim.org/layers/lang/goby/
- lang#gosu:            not loaded          https://spacevim.org/layers/lang/gosu/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
- lang#hack:            not loaded          https://spacevim.org/layers/lang/hack/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
- lang#html:            not loaded          https://spacevim.org/layers/lang/html/
- lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
- lang#idris:           not loaded          https://spacevim.org/layers/lang/idris/
- lang#io:              not loaded          https://spacevim.org/layers/lang/io/
- lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
- lang#j:               not loaded          https://spacevim.org/layers/lang/j/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
- lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
- lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
+ lang#markdown:            loaded          https://spacevim.org/layers/lang/markdown/
- lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#nix:             not loaded          https://spacevim.org/layers/lang/nix/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
- lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
- lang#pascal:          not loaded          no exists
- lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
- lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
- lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
- lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
- lang#python:          not loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          https://spacevim.org/layers/lang/r/
- lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
- lang#red:             not loaded          https://spacevim.org/layers/lang/red/
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
- lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
- lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
- lang#slim:            not loaded          no exists
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
- lang#toml:            not loaded          no exists
- lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
- lang#v:               not loaded          https://spacevim.org/layers/lang/v/
- lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
- lang#wolfram:         not loaded          https://spacevim.org/layers/lang/wolfram/
- lang#xml:             not loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell/
- sudo:                 not loaded          https://spacevim.org/layers/sudo/
- test:                 not loaded          https://spacevim.org/layers/test/
- tmux:                 not loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#mpv:            not loaded          no exists
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- vim:                  not loaded          no exists

# My very small init.toml for testing
[options]

    automatic_update = 0
    bootstrap_after = "myspacevim#after"
    bootstrap_before = "myspacevim#before"
    buffer_index_type = 4
    checkinstall = 0
    default_indent = 2
    enable_debug = 0
    max_column = 120
    realtime_leader_guide = 1
    vimcompatible = 1
    enable_vimfiler_welcome = 0
    disabled_plugins = [ "vim-zsh", "gruvbox", "molokai", "NeoSolarized" ]

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#markdown"
merged = "yes"

## Screenshots

Here is how to reproduce it.

https://asciinema.org/a/WUv0zEDiwR07gqLb0obOqf4U7

Please let me know if there is anything else I can do to help.  Thanks for all of your work guys.  I dig SpaceVim a lot!!

**Comment by wsdjeg** [comment]
this seems an issse with the plugin itself.

github.com/iamcco/markdown-preview.nvim

**Comment by msphinct** [comment]
Hey, First of all thanks for looking at this.  I can see you've done some work since this was reported, and it's appeared too have cleaned up a lot of the errors.  

Did you actually try it from "SPUpdate?  It might be that if you run it directly with 'dein', it works, but SPUpdate still won't see the whole install through even though it builds properly. 

After you try the SPUpdate method,  MarkdownPreview just returns with the same 'messages' error, but you can't see them unless you do ":messages".  So, I'm sure a lot of people aren't seeing the errors, and unless they run MarkdownPreview, they're probably unaware.

Maybe the plugin's seemingly harmless warnings are still preventing  SPUdate from completeing the install for me.  I've went ahead and submitted an issue with the maintainer.  I have to do what 'dein' does by hand for it to complete the install and actually launch the browser.  There are less warnings by far now but there's still some that might be preventing a clean install.

https://github.com/SpaceVim/SpaceVim/issues/3323

Please let me know if there is anything I can do.  I love SpaceVim so much.  Keep it up man!  I've been doing this for many years, and I don't get excited much. But for some reason SpaceVim has really made things fun again :)

Thanks!

**Comment by wsdjeg** [comment]
Thanks, I have reopened this issue, and I will look into it. the plugin manager buffer is a list of plugin, I do not know where should I put the error message, maybe use a popup windows when press some key.

**Comment by msphinct** [comment]
Hey thanks for looking at this again.  I'd be happy to help, if there is anything I can do.

Pete

**Comment by iamcco** [comment]
The warning message from the installation should not break the installation.

**Comment by msphinct** [comment]
I'll just put a link to my comment here in case wsdjeg  isn't subscribed:
https://github.com/iamcco/markdown-preview.nvim/issues/130#issuecomment-582005408

**Comment by msphinct** [comment]
Hey, that plugin needs 'yarn' specifically, so using s:node_pkgm for it when it's defaulting to npm is breaking that plugin
I'll submit a diff. Please let me know if there is anything else---or if I'm not understanding something.

Thanks again for all your work on this!

**Comment by msphinct** [comment]
Actually, I'm not sure how to deal with submitting a patch with the dual language stuff.  So, here's my temp fix for you.  At least people will again be able to use it:

diff --git a/autoload/SpaceVim/layers/lang/markdown.vim b/autoload/SpaceVim/layers/lang/markdown.vim
index e530b569..624db753 100644
--- a/autoload/SpaceVim/layers/lang/markdown.vim
+++ b/autoload/SpaceVim/layers/lang/markdown.vim
@@ -38,7 +38,7 @@ function! SpaceVim#layers#lang#markdown#plugins() abort
   call add(plugins, ['iamcco/markdown-preview.nvim',
         \ { 'on_ft' : 'markdown',
         \ 'depends': 'open-browser.vim',
-        \ 'build' : 'cd app & ' . s:node_pkgm . ' install' }])
+        \ 'build' : 'cd app & yarn install' }])
   if !has('nvim')
     call add(plugins, ['neoclide/vim-node-rpc',  {'merged': 0, 'build' : s:node_pkgm . ' install'}])
   endif

**Comment by wsdjeg** [comment]
@msphinct please use markdown instead. BTW, the `s:node_pkgm` should will be npm if npm is executable.

**Comment by msphinct** [comment]
Right, but s:node_pkgm if it's 'npm' doesn't work for markdown-preview, which was what I wanted to use.  It's been in SpaceVim since I stared using it.  I like that plugin a lot.

Are you saying you no longer want to support markdown-preview?  It's enabled in the markdown layer.

I'm confused?  Does npm work for markdown-preview?  Or, if something doesn't fit the model where s;node_pkgm isn't set to npm,  you don't want it in there?

It's seems pretty simple to just leave it as 'yarn' just for that plugin and  it just works.

**Comment by wsdjeg** [comment]
This option s:node_pkgm is added by the author of markdown-proview.nvim, It should works well with both npm and yarn, if something is broken, It should be changed. 

cc @iamcco

**Comment by iamcco** [comment]
`markdown-proview.nvim` support both npm and yarn to install, but I don't know what is `s:node_pkgm`.

**Comment by wsdjeg** [comment]
if executable('npm')
    let s:node_pkgm = 'npm'
  elseif executable('yarn')
    let s:node_pkgm = 'yarn'
  else
    let s:node_pkgm = ''
    call SpaceVim#logger#error('npm or yarn is required to build iamcco/markdown-preview and neoclide/vim-node-rpc')
  endif
  call add(plugins, ['iamcco/markdown-preview.nvim',
        \ { 'on_ft' : 'markdown',
        \ 'depends': 'open-browser.vim',
        \ 'build' : 'cd app & ' . s:node_pkgm . ' install' }])

**Comment by iamcco** [comment]
It must be related to the latest dein update. https://github.com/iamcco/markdown-preview.nvim/pull/128

> Note: The command is executed in plugin top directory.
If you need cd command, you must use "sh -c". >
call dein#add('wincent/command-t', {
\ 'build':
\ 'sh -c "cd ruby/command-t && ruby extconf.rb && make"'
\ })

**Comment by iamcco** [comment]
I have add dependencies to outside of app directory, so it can install the right dependencies even if `cd app` fail.

**Comment by msphinct** [comment]
Okay, well there seems to be some confusion.  I was not suggesting you get rid of s:node_pkgm to hold the 'npm or yarn'.  I was giving you a work around so the SpaceVim markdown layer would work until you find a fix.

**Comment by msphinct** [comment]
Okay, I went ahead and removed yarn completely and setup npm with the extra modules you suggested on your docs.

That appears to have fixed it completely.  Thanks guys!!

**Comment by msphinct** [comment]
I'll go ahead and close this.  Thanks again!

**Comment by wsdjeg** [comment]
@msphinct The author of markdown-preview.nvim has blocked me on github, so I can not connect with the plugin author.

**Comment by msphinct** [comment]
Hey, I'm sorry to hear that.  I really am happy it's all working.
People get sensitive and take things personally, when they are alone
supporting some code.
Whenever people have issues with my stuff, I always assume they are right,
and offer to help.
That way no one's feeling's get hurt. Life is too short, and I'd rather be
happy than right :)-.

I try follow three simple rules for life:
1. Be kind.
2. Be kind.
3 Be kind.

If you are kind enough to a lot of people, you get blessings down the road
that you don't even know about.

I leave the blame and pride to others.  I just work on spreading my vibe.
If someone isn't kind to me, we'll  just show them how it's done.

Take care brother, and please let me know if there is anything I can do to
help in anyway I can.

Thanks!!

Pete

**Comment by wsdjeg** [comment]
@msphinct Thanks, all plugins used in SpaceVim must be maintainable, so maybe we can not use ths plugin in SpaceVim anymore. I just searching all the website, and find maybe plugins, I will have a try with both of them, and repleace current one.

**Comment by jmperdev** [comment]
I change markdown-preview.nvim branch to solve it.
cd  .cache/vimfiles/repos/github.com/iamcco
rm -rf markdown-preview.nvim
git clone git@github.com:iamcco/markdown-preview.nvim.git
cd markdown-preview.nvim
git checkout separate-pre-build-node
cd app & yarn install

**Comment by jotline** [comment]
@itswcg It works for me.
