### ISSUE TITLE
Install SpaceVim separately from default Vim

### ISSUE THREAD

**Issue by christophergeiger3** [wsdjeg/SpaceVim#3324]
**Is your feature request related to a problem? Please describe.**
To my knowledge, there's currently no canonical way to have both a default version of Vim, and a SpaceVim version on the same machine.

**Describe the solution you'd like**
Would it be plausible for this to be an installer setting? I'm thinking this would be difficult to implement though. If there's a simple way to have two separate installs, please let me know (it would be nice to have that info in the wiki).

**Comment by wsdjeg** [comment]
no, we can not provide this package, because SpaceVim should works well in both gvim8.2 and gvim8.1 or even vim7.4 and neovim. we can only provide script to download spacevim itself. the version of vim or neovim is based on your os, you can choose the version yourself.
