### ISSUE TITLE
VimFiler doesn't work in docker image

### ISSUE THREAD

**Issue by matmarczak** [wsdjeg/SpaceVim#3334]
## Expected behavior, english is required
Press `<space>fo` to open file browser

## The reproduce ways from Vim starting (Required!)
Run steps defined in docs:
1. Pull latest image
2. Try to run `<space>fo`, error: `E492: not an editor command: VimFiler -find`

## Debug info
No debug info

## Screenshots
If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by ghost** [comment]
Try `<space> f t`

**Comment by yaroslavya** [comment]
The VimFiler plugin seems to be missing in the docker installation. Can be fixed by changing the **.SpaceVim/vimrc** by adding this line:

`Plugin 'Shougo/vimfiler.vim'`

Next time you open nvim it will install all the plugins and SpaceVim will have a filetree.
