### ISSUE TITLE
Tab manager should use buffer name as default tab name

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3339]
**Is your feature request related to a problem? Please describe.**
When using the ``junkblocker/patchreview-vim`` plugin to do code review, it opens many tabs, one for a file.  Because tab count is more than 10, can't switch directly.  And because the tab name is empty, It's hard to swtich to the tab I want in the tab manager.

**Describe the solution you'd like**
The tabline use buffer name if tab name is not set, but the tab manager doesn't has a default tab name.  Use the same same for tabline and tab manager is convenient for user.

**Comment by wsdjeg** [comment]
![微信截图_20200207224154](https://user-images.githubusercontent.com/13142418/74038474-38fdd680-49fb-11ea-93a2-afedd5ae2790.png)
we can add this feature, but if the buffer name of a tab is a plugin buffer, the name will look strange.
