### ISSUE TITLE
call dein#update errors occured

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#334]
## Expected behavior, english is recommend

no errors when dein#update()

## Environment Information
- OS: ubuntu 17.04
- vim version: 8.0
- neovim version: none

## The reproduce ways from Vim starting (Required!)

:call dein#update()

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
![tim 20170314114426](https://cloud.githubusercontent.com/assets/1751829/23885043/a505e398-08ab-11e7-93f6-3f9fff31121a.png)

**Comment by wsdjeg** [comment]
我是可以正常安装的
```
[dein] Update started: (2017/03/14 21:59:36)                                                                                                           
[dein] Done: (2017/03/14 22:00:15)
```
可以用一下命令修复
```
call dein#reinstall(['vimperator.vim'])
```
