### ISSUE TITLE
Add option for to default window position of view-git-* 

### ISSUE THREAD

**Issue by zabil** [wsdjeg/SpaceVim#3360]
**Is your feature request related to a problem? Please describe.**
SPC g d, for the VersionControlLayer, always opens window on top of the current window/buffer. I use a wide screen and I'd like to split my screen vertically and see the diff on the right hand side.

**Describe the solution you'd like**
Have a way to configure the default position of the git diff/blame etc to the right side for e.g. 
[[layers]]
   name = "VersionControl"
   default_position = "right"

**Describe alternatives you've considered**
I tried toggling the window layout SPC w + which works for the shell window but not here as it is opened in a buffer? I need to split the window to the right SPC w / and then do a git diff.

**Additional context**
Something like this

<img width="1433" alt="Screenshot 2020-02-18 at 11 35 34" src="https://user-images.githubusercontent.com/54427/74732765-d3071f80-5242-11ea-9ce6-947805d62bdd.png">

**Comment by wsdjeg** [comment]
Ok. I have added `git_diff_position` option, but this option maybe changed in next version, because we have too many windows needs this feature. for example `git log`, `git blame` `git commit` etc.
