### ISSUE TITLE
Incorrect document and implement for tasks

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3364]
## Expected behavior, english is required

1. document says using variables like \$**{relativeFileDirname}** for variable substitute, but \$**(relativeFileDirname)** is used.  I think it's a typo.
2. \$**(**relativeFileDirname**)** is expected to be a relative dirname, but it expands to the full dirname. I think the calls to ``s:FILE.unify_path()`` should provide the second argument to prevent the path being expanded to full path.

**Comment by wsdjeg** [comment]
1. what type? It is `$(relativeFileDirname)`

2. yeah, this is a bug, and will be fixed soon.

**Comment by thawk** [comment]
>     1. what type? It is `$(relativeFileDirname)`

In the document, ``{``/``}`` is used, but ``(``/``)`` is used in the code.

**Comment by thawk** [comment]
>     2. yeah, this is a bug, and will be fixed soon.

``$(relativeFile)`` need to be fixed too.

**Comment by wsdjeg** [comment]
I have opened new PR #3370 for this issue.
