### ISSUE TITLE
Register tasks for FileType/CompilerType

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3367]
**Is your feature request related to a problem? Please describe.**
tasks is project based, must be set for every individual project.  But for **ALL** python files, or for **ALL** CMake projects, there're some common tasks.  It's better to have the ability to register common tasks at file type/compiler type level instead of duplicated all the tasks again and again between projects.

**Describe the solution you'd like**
Maybe expose some register API like which provided by runner/repl?  Besides the FileType based register method, I think a project based register method is valueable too.  For example, after a project is detected as a CMake project, we can register common build tasks for all files inside the project.

**Additional context**
By now, filetype based compiler setting and project based compiler setting is conflicted.  e.g. I can set ``makeprg`` to ``lilypond`` for a single ``.ly`` file, but when I organize multiple ``.ly`` files into a project, I perfer using a build tool to build the files.  I think the introduction of tasks can solve this problem by add file based task and project based task alltogeter.

**Comment by wsdjeg** [comment]
> It's better to have the ability to register common tasks 

you can use global tasks config, the config file is `~/.SpaceVim.d/tasks.toml` which is added in #3370

> after a project is detected as a CMake project, we can register common build tasks for all files inside the project.

do you mean generate tasks file automatically?

**Comment by thawk** [comment]
What I mean is provide an API to be used in ``autocmd FileType`` or other script.
e.g. When a cpp file is opened, cpp related tasks can be auto added.  When a python file is opened, only python related tasks is listed, cpp ones shouldn't be listed.

Something like ``SpaceVim#plugins#tasks#register_file_task(task)``, ``SpaceVim#plugins#tasks#register_project_task(task)`` is good.  For the previous one, buffer variable can be used to store file based tasks.  For the latter one, maybe we can associate tasks with ``b:_spacevim_project_name``?

**Comment by wsdjeg** [comment]
the implementation of SpaceVim's task is based on vscode's tasks system, I have read it's doc, and do not find any thing about this.

the feature you want has been added in runner plugin, the language specific key binding `SPC l r` which is to open runner based on the default runner for current filetype.

**Comment by thawk** [comment]
In vscode, besides the user custom tasks, they can [auto-detect task](https://code.visualstudio.com/docs/editor/tasks#_task-autodetection), and contribute tasks by [task provider](https://code.visualstudio.com/api/extension-guides/task-provider).  It's good to have this ability.

**Comment by wsdjeg** [comment]
I have read the doc, but I do not know how to implement the auto-detect task feature. for a node js project, you should be able to see a `package.json` in the root. so how to generate task based on this file?

for example in https://github.com/spicydonuts/eslint-starter/blob/master/package.json

```json
{
  "name": "eslint-starter",
  "version": "1.0.0",
  "description": "Tiny eslint example",
  "main": "src/server.js",
  "scripts": {
    "start": "node .",
    "lint": "eslint src",
    "test": "npm run lint && echo \"Write some tests!\"",
    "watch": "nodemon --watch src --exec \"npm run test && npm run start\""
  },
  "keywords": [
    "eslint",
    "lint",
    "starter",
    "example",
    "atom",
    "standard",
    "standardjs"
  ],
  "author": "Michael Trotter",
  "license": "MIT",
  "repository": "https://github.com/spicydonuts/eslint-starter",
  "devDependencies": {
    "eslint": "^1.10.3",
    "eslint-config-standard": "^4.4.0",
    "eslint-plugin-standard": "^1.3.1",
    "nodemon": "^1.8.1"
  },
  "dependencies": {
    "express": "^4.13.3"
  }
}
```

the scripts key provides four tasks

```
  "scripts": {
    "start": "node .",
    "lint": "eslint src",
    "test": "npm run lint && echo \"Write some tests!\"",
    "watch": "nodemon --watch src --exec \"npm run test && npm run start\""
  },
```

so maybe we can use this.

**Comment by thawk** [comment]
As said in the document, vscode extension call [Tasks.registerTaskProvider](https://code.visualstudio.com/api/references/vscode-api#tasks.registerTaskProvider) to register [TaskProvider](https://code.visualstudio.com/api/references/vscode-api#TaskProvider) instance into vscode.  It's TaskProvider's job to generate tasks.

In the [task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/task-provider-sample), tasks are generated by executing ``rake -AT -f Rakefile``.

I think SpaceVim needn't to provide tasks by itself. It can just provide a way or an API to let the plugins/users to generate tasks by themself.  We don't need to do these, but we can give the power to the community to do this.

**Comment by wsdjeg** [comment]
@thawk #3374 should works, it supports detect npm tasks:

clone [eslint-starter](https://github.com/spicydonuts/eslint-starter), open file in this project, then press `SPC p t r`, you should see:

![微信截图_20200222160327](https://user-images.githubusercontent.com/13142418/75088801-e8ef4a00-558c-11ea-9bc0-075c2c348aa2.png)

the detected tasks has `(detected)` in then end.

**Comment by thawk** [comment]
Why not put the npm tasks detect code in the javascript layer?  I think it's not possible to add detect code for everything.  It's better register a provider at layer init, and call every provider to collect tasks when needed.

**Comment by wsdjeg** [comment]
Ok, two things will be done:

1. move npm task auto-detection code to javascript layer, or maybe typescript layer too, I do not know how many language use npm as package manager.

2. create a task provider api, of cause the doc will be added to the page.

**Comment by wsdjeg** [comment]
@thawk in #3375, the task provider api has been added.

**Comment by thawk** [comment]
It's quite good!  Thx!
