### ISSUE TITLE
Unify all dirnames for tasks variable substitute

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3369]
**Is your feature request related to a problem? Please describe.**
Unified path (add an ending slash for dirname) makes it easy to construct a correct path.

``relativeFileDirname`` and ``fileDirname`` in tasks are unified to have an ending slash.  But other variables, like ``workspaceFolder`` is not unified.  And this unifiy rule is not described in the document.

**Describe the solution you'd like**
1. Unify all dirnames, so we don't need to bother whether we should add a slash between two variable.
2. Describe it in the document, so all users know how to use it.

BTW, thanks for all the great jobs.

**Comment by wsdjeg** [comment]
slash should be added after a directory. I will improve the doc in #3370
