### ISSUE TITLE
MarkdownPreview command doesn't work

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#337]
## Expected behavior, english is recommend
According to [markdown-preview.vim](https://github.com/iamcco/markdown-preview.vim) description page. It should open a web browser to display rendered markdown as a html page after I type `MarkdownPreview` command. 

## Environment Information
- OS: macOS Sierra 10.12.3
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 17 2017 14:02:50)
- neovim version: 

## The reproduce ways from Vim starting (Required!)
1. vim test.md
2. Shift + : 
3. type `MarkdownPreview`
4. Type Enter
![screen shot 2017-03-16 at 01 33 48](https://cloud.githubusercontent.com/assets/2555093/23977864/ad3b361a-09e8-11e7-9b3a-0abcafde4fd3.png)

as you can see from the screenshot, after I type the command, nothing happens.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by icearith** [comment]
I am a beginner vim user, I am wondering if this problem is related to lazy load feature of dein.vim? Because when I use `[leader] + l + p`, I can find the markdown preview plugin.

![screen shot 2017-03-16 at 01 39 44](https://cloud.githubusercontent.com/assets/2555093/23978028/97eac0b8-09e9-11e7-982e-ba48170bd028.png)

**Comment by wsdjeg** [comment]
sorry the plugin use chrome by default,it should check other tools, will fix it latter.

**Comment by icearith** [comment]
@wsdjeg I have chrome installed on my Mac actually. I also typed command `message`, it seems like there is no error message caused by `MarkdownPreview` command.

![screen shot 2017-03-16 at 01 44 13](https://cloud.githubusercontent.com/assets/2555093/23978113/15e4231a-09ea-11e7-8160-41b06d895bb6.png)

**Comment by wsdjeg** [comment]
your chrome is opened? is there any page be opened?

**Comment by wsdjeg** [comment]
leader l p 
select preview plugin 
type enter to open github page of that plugin, try to read the readme, hope that will help

**Comment by icearith** [comment]
No, I didn't open my chrome. 

It also doesn't work after I open google-chrome.

**Comment by wsdjeg** [comment]
I will test it.

**Comment by icearith** [comment]
@wsdjeg  many thanks, I was a Atom user with Vim key bindings. However I suffered from the bad performance of Atom. It tasks ages when Atom launch, so I switch to vim today. another problem raise, I don't know vim script... :(

**Comment by icearith** [comment]
@wsdjeg I installed a new copy of SpaceVim on another Mac with the same OS version and `NVIM 0.1.7`, it doesn't work as well. I looked into the source code of MarkdownPreview, it launches a web server on localhost:8686 to serve the rendered html pages. However, I didn't find the 8686 port was active with `netstat` command. Any suggestions?

**Comment by wsdjeg** [comment]
@iamcco hi, is there any debug func for markdown preview plugin?

**Comment by iamcco** [comment]
@wsdjeg it doesn't have any debug function 😢

**Comment by wsdjeg** [comment]
@icearith I think it is issue with that plug, @iamcco will you add debug func? or what can I do for this plugin?

**Comment by icearith** [comment]
@wsdjeg Actually, I just disabled this plugin and are using another alternative. Anyway, Thank you :)

**Comment by wsdjeg** [comment]
welcome.

**Comment by Gabirel** [comment]
@icearith What's your alternative? Please tell me. Thanks

**Comment by icearith** [comment]
@Gabirel Sorry for my late reply. 

It is
``` 
'JamshedVesuna/vim-markdown-preview', {'on_ft' : 'markdown'}
```

**Comment by Gabirel** [comment]
Thanks. :no_mouth:

**Comment by LouisU** [comment]
MarkdownPreview command doesn't work  on Apple M1(Big Sur  11.2).

================================
1. Chrome installed
2. with all default settings in README of markdown-preview. try :MarkdownPreview.    Nothing happened but with a "ownPreview" word  flashed in the right corner
3. Then add let g:mkdp_path_to_chrome = "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome". try :MarkdownPreview,   got the same result of step 2.
