### ISSUE TITLE
Installer will create a folder named `~` under home directory

### ISSUE THREAD

**Issue by diszone** [wsdjeg/SpaceVim#338]
## Expected behavior, english is recommend
A directory named `~` will be created under home directory during installation.

## Environment Information
- OS: Mac OS X
- vim version:
- neovim version: 0.17

## The reproduce ways from Vim starting (Required!)
```
curl -sLf https://spacevim.org/install.sh | bash
```

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
A directory named `~` will be created under home directory.  The content of this directory looks like:
```
~/~/.cache/vimfilesrepos/github.com/Shougo/dein.vim
```

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
oh, it is a bug, will check it tonight.

**Comment by wsdjeg** [comment]
@cjppku I can not reproduce it , what is your custom conifg, and 
what is the result of 
`:echo g:spacevim_plugin_bundle_dir`

**Comment by v-leonhou** [comment]
i had met the same bug ,but i haven't take it in my heart ago.

**Comment by wsdjeg** [comment]
but I can not reproduce it, does it happend with default config?

**Comment by v-leonhou** [comment]
yes,probably the default config,my home dir also have the ~ directory

**Comment by wsdjeg** [comment]
do you mean `/home/root/~/`?

**Comment by v-leonhou** [comment]
/home/leon/~

**Comment by wsdjeg** [comment]
can you delete it, and with default config, will this dir be created again?

**Comment by v-leonhou** [comment]
not created again ,it disapperead

**Comment by wsdjeg** [comment]
I think it should be fixed in master.
