### ISSUE TITLE
Docker `make build` takes forever

### ISSUE THREAD

**Issue by barraponto** [wsdjeg/SpaceVim#3380]
## Expected behavior, english is required

Docker command should complete within a reasonable amount of time (10 minutes? idk). 

## The reproduce ways from Vim starting (Required!)

Run the `make build` command.

## Debug info

During Step 14 `dein#install()` installs all plugins. When it gets to building deoplete-go, it seems to take forever to compile `./python/objToJSON.c`.

**Comment by wsdjeg** [comment]
maybe this is a bug of upstream, I can not reproduce it it.

**Comment by barraponto** [comment]
```
$ docker --version      
Docker version 19.03.6-ce, build 369ce74a3c
```

**Comment by benabhi** [comment]
I was about to post the same problem ^^

Testing in virtualbox 6.1, on ubuntu 18.04 and 19.10

Docker version 18.09.7, build 2d0083d
Docker version 19.03.6, build 369ce74a3c

![Captura de pantalla de 2020-02-27 02-08-45](https://user-images.githubusercontent.com/1945599/75414296-d23b5100-5906-11ea-8f9b-6630c4971630.png)

Stuck in the same place everytime and in both SO and docker versions. I left running more than 4 hours.

**Comment by samwdp** [comment]
I have the same problem, posted a new issue about it to get some attention

**Comment by wsdjeg** [comment]
spacevim makefile only contains:

```
build:
	mkdir -p $@
```

I do not know why it takse forever. maybe this is not issue with spacevim itself,
