### ISSUE TITLE
Error detected while processing fuction SpaceVim#plugins#runner#open[11]__<SNR>65_async_run[85]__45>

### ISSUE THREAD

**Issue by aboutyty** [wsdjeg/SpaceVim#3382]
I installed SpaceVim on Windows10 and want to used it as a python IDE, I've installed all the packages required
When I test for a simple print("Hello") py file, the error occurs

Error detected while processing fuction SpaceVim#plugins#runner#open[11]__<SNR>65_async_run[85]__45>
E370: Could not load library lua53.dll
Lua library cannot be loaded

![image](https://user-images.githubusercontent.com/52515583/75461664-10477c00-59be-11ea-8f88-91e099e16610.png)

and my Lua folder
![image](https://user-images.githubusercontent.com/52515583/75461769-340ac200-59be-11ea-844a-0cb55f9b1592.png)

and my environment path
![image](https://user-images.githubusercontent.com/52515583/75461929-6ae0d800-59be-11ea-8129-c36cd82dea97.png)

**Comment by wsdjeg** [comment]
This is not issue with spacevim, it general vim question to make your vim support `+lua` feature.

**Comment by sakurawald** [comment]
this works for me !
after i upgrade gvim from 8.2 to 8.1, then my code completor is valid.
besides, you just need to add lua5.3 to your PATH, then everything goes well.

**Comment by wsdjeg** [comment]
Maybe you can switch to neovim, which has luajit by default.
