### ISSUE TITLE
Why can't it insert a newline with `Enter` in this case?

### ISSUE THREAD

**Issue by skyroam** [wsdjeg/SpaceVim#3383]
## Expected behavior, english is required
I 'm a new vimmer. When I use the function of `autocomplete` to complete the word and want to insert a newline with `Enter`, however, it doesn't work. The cursor is still there. I don't know why, please help.

## The reproduce ways from Vim starting (Required!)
Just complete the word with `tab` and press `Enter` .
## Debug info
I don't know how to do this.
## Screenshots
![layer](https://user-images.githubusercontent.com/20261736/75501270-81ad1c00-5a0a-11ea-8055-20f740fd7e22.PNG)

![case](https://user-images.githubusercontent.com/20261736/75500926-5675fd00-5a09-11ea-9584-2e111e736483.PNG)
This is the case where I can't insert a newline by pressing `Enter`.

**Comment by Shougo** [comment]
It is Vim normal behavior.
