### ISSUE TITLE
install.cmd doesn't work (creates a file symlink not a dir one)

### ISSUE THREAD

**Issue by barcharcraz** [wsdjeg/SpaceVim#3386]
## Expected behavior, english is required
installcmd seems to want to make a symlink from ~/vimfiles to ~/.spacevim (I'm on vim8). However it doesn't pass the `/D` parameter to mklink, meaning a file symlink gets created instead of a directory symlink. On windows the "is this a directory" property is stored in the containing directory, not in the inode, so dir symlinks and file symlinks are different.
## The reproduce ways from Vim starting (Required!)
run install.cmd and start vim(8)

**Comment by wsdjeg** [comment]
Thanks, do you mean we need to use `mklink /D` instead?

**Comment by barcharcraz** [comment]
yep!

Also you may want to consider mklink /J which makes a junction point (they only work for directories, but they don't require admin (if you turn on "developer mode" then symlinks work too, usually (the app creating the symlink needs to call `CreateSymbolicLink` with the `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` flag). mklink does this, and I think New-Item does it with powershell preview but not with powershell 5.

Anyhow junctions should work for this case, the thing junctions don't allow is like junctions to a relative path.

**Comment by barcharcraz** [comment]
I made a PR for this and another issue

**Comment by wsdjeg** [comment]
thanks for your work.
