### ISSUE TITLE
How to configure yaml layer indenting options?

### ISSUE THREAD

**Issue by jamesla** [wsdjeg/SpaceVim#3388]
I am wanting to configure my yaml indentation behaviour so that it uses no spaces when writing a list. I've looked all through the docs but I can't find anywhere that mentions how to configure this. 

How could I configure the yaml linter so instead of:

```
some_list:
  - test1
  - test2
```

to:

```
some_list:
- test1
- test2
```

**Comment by wsdjeg** [comment]
@jamesla It seems not issue with SpaceVim, we do not have yaml layer, but we can add layer in the future. to add yaml layer we need to find out the yaml plugin for vim.
