### ISSUE TITLE
deoplete is looking for gocode even though vim-go does not use it.

### ISSUE THREAD

**Issue by HouzuoGuo** [wsdjeg/SpaceVim#3389]
## Expected behavior, english is required

Hey! I've been using SpaceVim to work with Go for couple of months already and it has always worked quite well - until last week. All suddenly I'm getting this message in vim:

```
vim-go: initialized gopls
[deoplete] gocode binary not found.  Use :messages / see above for error details.
```

vim-go has been using gopls instead of the legacy gocode for many months already (`~/.SpaceVim.d/autoload/myspacevim.vim`):

```
  let g:go_info_mode = 'gopls'
  let g:go_def_mode = 'gopls'
  let g:go_info_mode = 'gopls'
  let g:go_referrers_mode = 'gopls'
```

Is there a problem with SpaceVim or is it with Deoplete?

## The reproduce ways from Vim starting (Required!)

<pre>
howard@hzgl-dev-ubuntu ~/g/s/g/H/laitos> cat ~/.SpaceVim.d/init.toml
[options]
    statusline_inactive_separator = "nil"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
  name = "fzf"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "nil"
  auto-completion-tab-key-behavior = "smart"
  auto-completion-complete-with-key-sequence = "nil"
  auto_completion_delay = 500

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 25

[[layers]]
  name = "tmux"

[[layers]]
  name = "git"

[[layers]]
  name = "sudo"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#csharp"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#extra"
</pre>

<pre>
howard@hzgl-dev-ubuntu ~/g/s/g/H/laitos> cat ~/.SpaceVim.d/autoload/myspacevim.vim
func! myspacevim#before() abort
  set shell=/bin/bash
endf

func! myspacevim#after() abort
  set shell=/bin/bash
  set mouse=

  let g:go_test_show_name = 1
  let g:go_test_timeout= '120s'

  let g:go_info_mode = 'gopls'
  let g:go_def_mode = 'gopls'
  let g:go_info_mode = 'gopls'
  let g:go_referrers_mode = 'gopls'

  let g:go_auto_type_info = 1
  let g:go_auto_sameids = 1
  let g:go_updatetime = 1000

  let g:go_guru_scope = ["github.com/HouzuoGuo/...", "github.com/kotarock/..."]

  let g:go_term_enabled = 1

  let g:go_gopls_enabled = 1
  let g:go_gopls_complete_unimported = 1
  let g:go_gopls_deep_completion = 1
  let g:go_gopls_fuzzy_matching = 1
  let g:go_gopls_staticcheck = 1
  let g:go_gopls_use_placeholders = 1

  let g:go_fmt_autosave = 1
  let g:go_fmt_command = "goimports"

  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_function_calls = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1

endf
</pre>

Spacevim is at commit 5d4c83c6c2312df201e00146fe87d6d80b4b9faf.

## Debug info
<pre>
SpaceVim layers:

- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
- chinese:              not loaded          https://spacevim.org/layers/chinese/
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- ctrlspace:            not loaded          https://spacevim.org/layers/ctrlspace/
- debug:                not loaded          https://spacevim.org/layers/debug/
- denite:               not loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
+ format:                   loaded          https://spacevim.org/layers/format/
- fuzzy:                not loaded          no exists
+ fzf:                      loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
+ git:                      loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- gtags:                not loaded          https://spacevim.org/layers/gtags/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#aspectj:         not loaded          https://spacevim.org/layers/lang/aspectj/
- lang#assembly:        not loaded          https://spacevim.org/layers/lang/assembly/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
- lang#batch:           not loaded          https://spacevim.org/layers/lang/batch/
+ lang#c:                   loaded          https://spacevim.org/layers/lang/c/
- lang#chapel:          not loaded          https://spacevim.org/layers/lang/chapel/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
- lang#crystal:         not loaded          https://spacevim.org/layers/lang/crystal/
+ lang#csharp:              loaded          https://spacevim.org/layers/lang/csharp/
- lang#d:               not loaded          https://spacevim.org/layers/lang/d/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
+ lang#dockerfile:          loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
+ lang#extra:               loaded          https://spacevim.org/layers/lang/extra/
- lang#foxpro:          not loaded          https://spacevim.org/layers/lang/foxpro/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
+ lang#go:                  loaded          https://spacevim.org/layers/lang/go/
- lang#goby:            not loaded          https://spacevim.org/layers/lang/goby/
- lang#gosu:            not loaded          https://spacevim.org/layers/lang/gosu/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
- lang#hack:            not loaded          https://spacevim.org/layers/lang/hack/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
+ lang#html:                loaded          https://spacevim.org/layers/lang/html/
- lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
- lang#idris:           not loaded          https://spacevim.org/layers/lang/idris/
- lang#io:              not loaded          https://spacevim.org/layers/lang/io/
- lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
- lang#j:               not loaded          https://spacevim.org/layers/lang/j/
- lang#janet:           not loaded          https://spacevim.org/layers/lang/janet/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
+ lang#javascript:          loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
- lang#lasso:           not loaded          https://spacevim.org/layers/lang/lasso/
- lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
+ lang#markdown:            loaded          https://spacevim.org/layers/lang/markdown/
- lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#nix:             not loaded          https://spacevim.org/layers/lang/nix/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
- lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
- lang#pascal:          not loaded          https://spacevim.org/layers/lang/pascal/
- lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
- lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
- lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
- lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
+ lang#python:              loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          https://spacevim.org/layers/lang/r/
- lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
- lang#red:             not loaded          https://spacevim.org/layers/lang/red/
- lang#ring:            not loaded          https://spacevim.org/layers/lang/ring/
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
- lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
+ lang#sh:                  loaded          https://spacevim.org/layers/lang/sh/
- lang#slim:            not loaded          https://spacevim.org/layers/lang/slim/
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
- lang#toml:            not loaded          no exists
- lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
- lang#v:               not loaded          https://spacevim.org/layers/lang/v/
- lang#vbnet:           not loaded          https://spacevim.org/layers/lang/vbnet/
- lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
- lang#wdl:             not loaded          no exists
- lang#wolfram:         not loaded          https://spacevim.org/layers/lang/wolfram/
- lang#xml:             not loaded          no exists
- lang#xquery:          not loaded          no exists
- lang#zig:             not loaded          https://spacevim.org/layers/lang/zig/
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell/
+ sudo:                     loaded          https://spacevim.org/layers/sudo/
- test:                 not loaded          https://spacevim.org/layers/test/
+ tmux:                     loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#mpv:            not loaded          no exists
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- vim:                  not loaded          no exists

</pre>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![image](https://user-images.githubusercontent.com/563872/75655156-f0d47b80-5c69-11ea-88af-ec0a25a8c19f.png)

**Comment by HouzuoGuo** [comment]
forgot to mention - since deoplete complained about not being able to find `gocode`, autocompletion for go no longer works (where it used to work.)

**Comment by Shougo** [comment]
It seems deoplete-go error.
https://github.com/deoplete-plugins/deoplete-go
It uses gocode for completion.

**Comment by Shougo** [comment]
deoplete doesn't use vim-go completion.

**Comment by HouzuoGuo** [comment]
@Shougo Thanks for your reply. I found the solution here:

https://github.com/fatih/vim-go/pull/2231/files

**Comment by AaronKrystal** [comment]
I have the same issue on `SpaceVim 1.5.0-dev-8887be16`

```
[deoplete] gocode binary not found. 
```

**Comment by mattmart3** [comment]
Same issue with `SpaceVim 2.1.0-dev-15a33422`.
[The solution linked by @HouzuoGuo](https://github.com/SpaceVim/SpaceVim/issues/3389#issuecomment-593457212) does not work for me.
A quick workaround I found so far is to disable deoplete-go from Spacevim:
```diff
diff --git a/autoload/SpaceVim/layers/lang/go.vim b/autoload/SpaceVim/layers/lang/go.vim
index 70a0de1c..2d3a4a38 100644
--- a/autoload/SpaceVim/layers/lang/go.vim
+++ b/autoload/SpaceVim/layers/lang/go.vim
@@ -101,9 +101,9 @@ let s:go_interpreter = 'python3'

 function! SpaceVim#layers#lang#go#plugins() abort
   let plugins = [['fatih/vim-go', { 'on_ft' : 'go', 'loadconf_before' : 1}]]
-  if has('nvim') && g:spacevim_autocomplete_method ==# 'deoplete'
-    call add(plugins, ['zchee/deoplete-go', {'on_ft' : 'go', 'build': 'make'}])
-  endif
+  "if has('nvim') && g:spacevim_autocomplete_method ==# 'deoplete'
+  "  call add(plugins, ['zchee/deoplete-go', {'on_ft' : 'go', 'build': 'make'}])
+  "endif
   return plugins
 endfunction
 ```

**Comment by Shougo** [comment]
deoplete-go is too old and it should not be enabled...
