### ISSUE TITLE
Cannot input () into files and showing indentLines has not been installed

### ISSUE THREAD

**Issue by blzsb** [wsdjeg/SpaceVim#3390]
## Expected behavior, english is required

When I tried to input "()" into any file, the editor stuck and the CPU usage rised to maximum of a single core.
The editor shows indentLines has not been installed. I have tried :call dein#install(["indentLine"]) but it cannot find the target plugin.
I am using SpaceVim 1.4.0-dev and Neovim 0.4.3 for win64.

## The reproduce ways from Vim starting (Required!)

Start the nvim-qt.exe, open any file and get into the insert mode. Press"(", and the error will occur.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

Since the editor stuck that time, no debug info can be obtained.

## Screenshots
![微信截图_20200303112733](https://user-images.githubusercontent.com/21072650/75742185-d7a1fc80-5d47-11ea-8da0-aa3964c3902c.png)
![微信截图_20200303111944](https://user-images.githubusercontent.com/21072650/75742182-d53fa280-5d47-11ea-94de-2da881779d9d.png)
![微信截图_20200303121531](https://user-images.githubusercontent.com/21072650/75742486-b8f03580-5d48-11ea-8c68-92d84d8fa58a.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
use `SPReinstall indentLine`.
