### ISSUE TITLE
spacevim not init on Vim on MacOS

### ISSUE THREAD

**Issue by Arconapalus** [wsdjeg/SpaceVim#3394]
## Expected behavior, english is required
Install spacevim on MacOS 10.15.3 and started Vim and spacevim was not init
I previously had this installed and change home folders and now it isn't working. I did  a uninstall and rm all .spacevim* and resintalled and still not init. 
vim version 8.1.1312 
MacOS 10.15.3

## The reproduce ways from Vim starting (Required!)
curl -sLf https://spacevim.org/install.sh | bash for linux/macos 
execute Vim in bash 
spacevim didn't init or installed plugin 

## Debug info
Can't get the debug 
Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
[➭] Trying to clone SpaceVim
Cloning into '/Users/nAme/.SpaceVim'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 29246 (delta 5), reused 12 (delta 4), pack-reused 29222
Receiving objects: 100% (29246/29246), 10.88 MiB | 16.88 MiB/s, done.
Resolving deltas: 100% (21957/21957), done.
[✔] Successfully clone SpaceVim
ln: /Users/nAme/.vim: File exists
[✔] Installed SpaceVim for vim
ln: /Users/nAme/.config/nvim: File exists
[✔] Installed SpaceVim for neovim
[✔] Downloaded DejaVu Sans Mono Bold Oblique for Powerline.ttf
[✔] Downloaded DejaVu Sans Mono Bold for Powerline.ttf
[✔] Downloaded DejaVu Sans Mono Oblique for Powerline.ttf
[✔] Downloaded DejaVu Sans Mono for Powerline.ttf
[✔] Downloaded DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf
[✔] Downloaded Ubuntu Mono derivative Powerline Nerd Font Complete.ttf
[✔] Downloaded WEBDINGS.TTF
[✔] Downloaded WINGDNG2.ttf
[✔] Downloaded WINGDNG3.ttf
[✔] Downloaded devicons.ttf
[✔] Downloaded mtextra.ttf
[✔] Downloaded symbol.ttf
[✔] Downloaded wingding.ttf
[➭] Updating font cache, please wait ...
[✔] font cache done!

Almost done!
==============================================================================
==    Open Vim or Neovim and it will install the plugins automatically      ==
==============================================================================

That's it. Thanks for installing SpaceVim. Enjoy!

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by ghost** [comment]
Try setting ‘SPACEVIMDIR’ to point to the current install location in your ‘.bashrc’

**Comment by Arconapalus** [comment]
Didn't work but I was able to manually install it on macos and then use a alias to install plugin etc.

**Comment by wsdjeg** [comment]
@Arconapalus if you vim do not load the spacevim, you can check it via `:scriptnames` command, this command shows the order of scripts your vim has loaded.
