### ISSUE TITLE
[rust] cargo project and workspace

### ISSUE THREAD

**Issue by audacioustux** [wsdjeg/SpaceVim#3404]
cargo project should be detected by looking for Cargo.toml file (not .git dir)
& in cargo workspace on cargo run (SPC l c r), a list with all the (--bin) projects would be great!

& cargo-watch support would be great

**Comment by wsdjeg** [comment]
@audacioustux SpaceVim support custom task system, so this can easily done in your bootstrap function instead of adding into spacevim. of cause, we should add a simple guide for it.
