### ISSUE TITLE
Colemak mappings

### ISSUE THREAD

**Issue by mlapai** [wsdjeg/SpaceVim#3407]
Hi,

I've tried to remap standard movement mappings to HNEI (colemak) as well as some other keybindings and I've put them inside of `after` and `before` function in `spacevim.vim`, even tried creating `.vimrc` in my `$HOME` directory, but i guess that its not loaded. 
They worked fine inside of actual spacevim, but Vimfiler still preserves the old ones, making it really weird to use. How can i actually remap those on global level so that every plugin, or at least Vimfiler uses remapped values.

Maping's I'm trying to use inside of `spacevim.vim`.

```
function! myspacevim#after() abort

  "################# COLEMAK BINDINGS #################

  noremap n j
  noremap e k
  noremap i l

  noremap I L

  noremap k n
  noremap K N

  noremap u i
  noremap U I

  noremap t f
  noremap T F

  noremap l u
  noremap L U

  noremap y o
  noremap Y O

  noremap dd gg
  noremap D G

  noremap <C-f> <C-e>
  noremap <C-j> <C-y>

  noremap <C-s> <C-d>
  noremap <C-l> <C-u>

  noremap <C-t> <C-f>

  noremap f e
  noremap F E

  noremap j y
  noremap s d

endfunction
```

**Comment by wsdjeg** [comment]
you seems can not do it, all the plugin buffer using Filetype autocmd to defind new key bindings. To hack this, you need to change the vimfiler's keybinding yourself in bootstrap function. OR maybe we can add the keyboard layer option in the feture.
