### ISSUE TITLE
Too many arguments for function: globpath?

### ISSUE THREAD

**Issue by bodyno** [wsdjeg/SpaceVim#341]
When I install spacevim. Type vim then show this log. How to do with it?

![image](https://cloud.githubusercontent.com/assets/5443058/24068786/a17bcd9e-0bd2-11e7-9194-e0b9884c81cf.png)

- OS: centos 7
- vim version: 7.4

[dein] Error occurred while executing hook: unite.vim
[dein] Vim(let):E118: Too many arguments for function: globpath
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
Your vim is too old, it should > 7.4.279, and now I can not found out which plugin use four argv in globpath(), only `has('patch-7.4.279')` return 1, this function will works well,

**Comment by bodyno** [comment]
Yean. After I install vim 8. Problem solved. Thanks

**Comment by wsdjeg** [comment]
Welcome.
