### ISSUE TITLE
autogenerated init.toml contradicts documentation

### ISSUE THREAD

**Issue by Jemi** [wsdjeg/SpaceVim#3413]
The autogenerated init.toml contains at least two lines that contradict the documentation: 
auto-completion-return-key-behavior = "complete"
-and-
auto-completion-tab-key-behavior = "smart"

The documentation at: https://spacevim.org/layers/autocomplete/ says these should be:
auto_completion_return_key_behavior = "complete"
-and-
auto_completion_tab_key_behavior = "smart"

## Expected behavior, english is required
The autogenerated init.toml should conform to the language described in the documentation.

## The reproduce ways from Vim starting (Required!)
1. install spacevim
2. open init.toml
3. observe the 4 lines under '# Enable autocomplete layer'

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
SpaceVim layers:

- VersionControl:       not loaded          no exists
+ autocomplete:             loaded          no exists
- chat:                 not loaded          no exists
+ checkers:                 loaded          no exists
- chinese:              not loaded          no exists
+ colorscheme:              loaded          no exists
+ core#banner:              loaded          no exists
+ core#statusline:          loaded          no exists
+ core#tabline:             loaded          no exists
+ core:                     loaded          no exists
- cscope:               not loaded          no exists
- ctrlp:                not loaded          no exists
- ctrlspace:            not loaded          no exists
- debug:                not loaded          no exists
- denite:               not loaded          no exists
+ edit:                     loaded          no exists
- exprfold:             not loaded          no exists
- floobits:             not loaded          no exists
+ format:                   loaded          no exists
- fuzzy:                not loaded          no exists
+ fzf:                      loaded          no exists
- games:                not loaded          no exists
- git:                  not loaded          no exists
- github:               not loaded          no exists
- gtags:                not loaded          no exists
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          no exists
- lang#WebAssembly:     not loaded          no exists
- lang#agda:            not loaded          no exists
- lang#asciidoc:        not loaded          no exists
- lang#aspectj:         not loaded          no exists
- lang#assembly:        not loaded          no exists
- lang#autohotkey:      not loaded          no exists
- lang#batch:           not loaded          no exists
- lang#c:               not loaded          no exists
- lang#chapel:          not loaded          no exists
- lang#clojure:         not loaded          no exists
- lang#coffeescript:    not loaded          no exists
- lang#crystal:         not loaded          no exists
- lang#csharp:          not loaded          no exists
- lang#d:               not loaded          no exists
- lang#dart:            not loaded          no exists
- lang#dockerfile:      not loaded          no exists
- lang#elixir:          not loaded          no exists
- lang#elm:             not loaded          no exists
- lang#erlang:          not loaded          no exists
- lang#extra:           not loaded          no exists
- lang#foxpro:          not loaded          no exists
- lang#fsharp:          not loaded          no exists
- lang#go:              not loaded          no exists
- lang#goby:            not loaded          no exists
- lang#gosu:            not loaded          no exists
- lang#graphql:         not loaded          no exists
- lang#groovy:          not loaded          no exists
- lang#hack:            not loaded          no exists
- lang#haskell:         not loaded          no exists
- lang#html:            not loaded          no exists
- lang#hy:              not loaded          no exists
- lang#idris:           not loaded          no exists
- lang#io:              not loaded          no exists
- lang#ipynb:           not loaded          no exists
- lang#j:               not loaded          no exists
- lang#janet:           not loaded          no exists
- lang#java:            not loaded          no exists
- lang#javascript:      not loaded          no exists
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          no exists
- lang#kotlin:          not loaded          no exists
- lang#lasso:           not loaded          no exists
- lang#latex:           not loaded          no exists
- lang#lisp:            not loaded          no exists
- lang#livescript:      not loaded          no exists
- lang#lua:             not loaded          no exists
- lang#markdown:        not loaded          no exists
- lang#matlab:          not loaded          no exists
- lang#nim:             not loaded          no exists
- lang#nix:             not loaded          no exists
- lang#ocaml:           not loaded          no exists
- lang#pact:            not loaded          no exists
- lang#pascal:          not loaded          no exists
- lang#perl:            not loaded          no exists
- lang#php:             not loaded          no exists
- lang#plantuml:        not loaded          no exists
- lang#pony:            not loaded          no exists
- lang#powershell:      not loaded          no exists
- lang#processing:      not loaded          no exists
- lang#prolog:          not loaded          no exists
- lang#puppet:          not loaded          no exists
- lang#purescript:      not loaded          no exists
- lang#python:          not loaded          no exists
- lang#r:               not loaded          no exists
- lang#racket:          not loaded          no exists
- lang#red:             not loaded          no exists
- lang#ring:            not loaded          no exists
- lang#ruby:            not loaded          no exists
- lang#rust:            not loaded          no exists
- lang#scala:           not loaded          no exists
- lang#scheme:          not loaded          no exists
- lang#sh:              not loaded          no exists
- lang#slim:            not loaded          no exists
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#swift:           not loaded          no exists
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          no exists
- lang#toml:            not loaded          no exists
- lang#typescript:      not loaded          no exists
- lang#v:               not loaded          no exists
- lang#vbnet:           not loaded          no exists
- lang#vim:             not loaded          no exists
- lang#vue:             not loaded          no exists
- lang#wdl:             not loaded          no exists
- lang#wolfram:         not loaded          no exists
- lang#xml:             not loaded          no exists
- lang#xquery:          not loaded          no exists
- lang#zig:             not loaded          no exists
- leaderf:              not loaded          no exists
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          no exists
- sudo:                 not loaded          no exists
- test:                 not loaded          no exists
- tmux:                 not loaded          no exists
- tools#dash:           not loaded          no exists
- tools#mpv:            not loaded          no exists
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          no exists
- tools:                not loaded          no exists
+ ui:                       loaded          no exists
- unite:                not loaded          no exists
- vim:                  not loaded          no exists

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by ghost** [comment]
See: https://github.com/SpaceVim/SpaceVim/blob/e2530924acb7eac46b956c2155356284a4a9392b/mode/basic.toml#L34
https://github.com/SpaceVim/SpaceVim/blob/e2530924acb7eac46b956c2155356284a4a9392b/mode/basic.toml#L35
I’m on my phone at the moment. Will open a PR later if I have time.

**Comment by wsdjeg** [comment]
Thanks, I will fix it, and the naming rules is changed in following pr

https://github.com/SpaceVim/SpaceVim/pull/3037
