### ISSUE TITLE
Separate website, blog, etc. into separate projects under the same group.

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#3416]
**Is your feature request related to a problem? Please describe.**
When I clone SpaceVim, I want it to be the minimal size possible.

**Describe the solution you'd like**
Separate projects for website, blog, and other pieces not directly related ot the functionality of SpaceVim.

**Describe alternatives you've considered**
I currently run from a stripped down fork, which is not ideal.

**Additional context**
This would help to minimize the size of docker images containing SpaceVim.

**Comment by wsdjeg** [comment]
no, all things should be same version, and you can set clone depth.
