### ISSUE TITLE
SpaceVim IDE for R does not support .lintr file. 

### ISSUE THREAD

**Issue by linusjf** [wsdjeg/SpaceVim#3418]
SpaceVim IDE does not support usage of .lintr file that overrides the default configuration supported by lintr package in R.  Running the lintr package manually on file recognises these changes and errors and warnings are no longer flagged. The SpaceVim IDE does not recognise these changes and continues to flag warnings within the IDE.

## Expected behavior
The IDE must support any changes made to lintr configuration via it's settings files.

## The reproduce ways from Vim starting 
Create a .lintr file under project or root directory and override existing defaults.

E.g

https://github.com/Fernal73/LearnR/blob/development/.lintr

https://github.com/jimhester/lintr/blob/master/.lintr

**Comment by wsdjeg** [comment]
@Fernal73 Does `.lintr` file is in current dir, I mean make sure your current directory is the root of your project. in SpaceVim, the default lint plugin is neomake. you can checkout the config in neomake: https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/r.vim

```vim
" vim: ts=4 sw=4 et

function! neomake#makers#ft#r#EnabledMakers() abort
    return ['lintr']
endfunction

function! neomake#makers#ft#r#lintr() abort
    return {
        \ 'exe': 'R',
        \ 'args': ['--slave', '--no-restore', '--no-save', '-e lintr::lint("%t")'],
        \ 'append_file': 0,
        \ 'errorformat':
        \   '%W%f:%l:%c: style: %m,' .
        \   '%W%f:%l:%c: warning: %m,' .
        \   '%E%f:%l:%c: error: %m,'
        \ }
endfunction
```

**Comment by linusjf** [comment]
Moving the .lintr file to the working directory i.e., the directory from
which vim is launched makes no difference. The modified .lintr
configuration is ignored.

Apparently, the .lintr file is not being picked up; neither from the top
parent directory where . Rprofile resides nor from the working directory.

**Comment by linusjf** [comment]
in SpaceVim, the default lint plugin is neomake. you can checkout the config in neomake: https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/r.vim
> 
> ```viml
> " vim: ts=4 sw=4 et
> 
> function! neomake#makers#ft#r#EnabledMakers() abort
>     return ['lintr']
> endfunction
> 
> function! neomake#makers#ft#r#lintr() abort
>     return {
>         \ 'exe': 'R',
>         \ 'args': ['--slave', '--no-restore', '--no-save', '-e lintr::lint("%t")'],
>         \ 'append_file': 0,
>         \ 'errorformat':
>         \   '%W%f:%l:%c: style: %m,' .
>         \   '%W%f:%l:%c: warning: %m,' .
>         \   '%E%f:%l:%c: error: %m,'
>         \ }
> endfunction
> ```

Where would I find the above file in my SpaceVim installation?

**Comment by linusjf** [comment]
I did not actually have NeoMake installed since I had set enable_neomake and enable_ale to true simultaneously.
Setting the latter to false installed NeoMake and thus I see why the NeoMake way of specifying the R command is a problem since it opens a split window to lint the file every time. This is highly annoying after getting used to ALE.
Is there some way of turning off the split window and having the output redirected to the file window with NeoMake?

Alternatively, have ALE support the .lintr file configuration?

**Comment by linusjf** [comment]
https://github.com/dense-analysis/ale/blob/master/ale_linters/r/lintr.vim

My specific problem is with this file in ALE in which if I substitute the contents of my .lintr with_defaults method , I am able to resolve the issue. ALE, apparently , does not refer to any .lintr configuration file, preferring to use the configuration specified in its ale_linter configuration file above.

**Comment by linusjf** [comment]
Should this issue be closed or should ALE look for a .lintr file to use if found?

**Comment by linusjf** [comment]
That brings me to another issue:

Where and how do I add an Ale fixer in SpaceVim?

https://github.com/dense-analysis/ale/blob/master/README.md#usage-fixing

I'd like to run styler on save.

**Comment by wsdjeg** [comment]
you can sue bootstrap function to config ale.

**Comment by linusjf** [comment]
That's all very fine.
But where do I define my ALE fixers?
:ALEFix gives me the following message:

No fixers have been defined.
Try :ALEFixSuggest.

:ALEFixSuggest gibes me the following :


Try the following fixers appropriate for

  'styler' - Fix R files with styler.

  Try the following generic fixers:



  'remove_trailing_lines' - Remove all bla
  'trim_whitespace' - Remove all trailing

  See :help ale-fix-configuration

   Press q to close this window

https://spacevim.org/documentation/#bootstrap-functions

I've created the myspace.vim file under .SpaceVim.d as in the example.

But it has no effect.

:ALEInfo shows ale-fixers empty.

This is the content of my myspace.vim file.

```
function! myspacevim#before() abort
let g:neomake_enabled_c_makers = ['clang']
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'javascript': ['prettier', 'eslint'],
\   'r': ['styler']
\}
" Set this variable to 1 to fix files when you save them.
let g:ale_fix_on_save = 1
" Enable completion where available.
" This setting must be set before ALE is loaded.
"
" You should not turn this setting on if you wish to use ALE as a completion
" source for other completion plugins, like Deoplete.
let g:ale_completion_enabled = 1
nnoremap jk <Esc>
endfunction

function! myspacevim#after() abort
iunmap jk
endfunction
```

Do you expect me to be digging into the inner workings of ALE which is installed under the . caches directory on my setup?

As far as I can see, ale_fixers are just referenced once under the directory plugin in file ale.vim and the fixers are empty. 

I could populate this list there itself but would I be breaking the architecture by doing that?

**Comment by linusjf** [comment]
https://github.com/dense-analysis/ale/issues/1878#issuecomment-418529035

This doesn't seem to work either.

**Comment by linusjf** [comment]
> you can sue bootstrap function to config ale.

What the hell do you mean by 'sue'? Did you mean 'sew'? I've not come across any such expression before.

**Comment by linusjf** [comment]
``` function! myspacevim#before() abort let g:neomake_enabled_c_makers = ['clang'] let g:ale_fixers = { \ '*': ['remove_trailing_lines', 'trim_whitespace'], \ 'javascript': ['prettier', 'eslint'], \ 'r': ['styler'] \} " Set this variable to 1 to fix files when you save them. let g:ale_fix_on_save = 1 " Enable completion where available. " This setting must be set before ALE is loaded. " " You should not turn this setting on if you wish to use ALE as a completion " source for other completion plugins, like Deoplete. let g:ale_completion_enabled = 1 nnoremap jk <Esc> endfunction function! myspacevim#after() abort iunmap jk endfunction ``` 

Actually, this worked.
The file name had to be changed to myspacevim.vim.

g:ale_fix_on_save = 1 however, throws a temporary file not found exception as shown below:

Error detected while processing function <SNR>213_NeoVimCallback[29]..<lambda>8[1]..<SNR>210_ExitCallback[28]..<SNR>236_HandleExit:
line    8:
E484: Can't open file /data/data/com.termux/files/usr/tmp/nvimSGpyrd/12/lint.R

This is specifically an error when :wqa is invoked and a fix has not been applied. It works fine in all other cases, AFAIK.
