### ISSUE TITLE
Why does screen show this window when I type":w"?

### ISSUE THREAD

**Issue by leafonsword** [wsdjeg/SpaceVim#3420]
Everytime I save a Python code file typing ":w", the red window will appear like below, it's disturbing; Does a plugin lead to this effect? 
![image](https://user-images.githubusercontent.com/1754580/77721908-25e4ab80-7027-11ea-9401-00575fce18da.png)

**Comment by wsdjeg** [comment]
This feature is provided by `checkers` layer.

**Comment by leafonsword** [comment]
@wsdjeg But how could I disable `checkers ` layer?
I use 
```
disabled_plugins = ['checkers'] 
```
and
```
[[layers]]
   # name = "checkers"
   # show_cursor_error = false
```

But neither of two methods has efficient!

**Comment by wsdjeg** [comment]
please read the layers doc,

https://spacevim.org/layers/

**Comment by leafonsword** [comment]
@wsdjeg it works，thanks~
