### ISSUE TITLE
x vim-easymotion: Installing failed

### ISSUE THREAD

**Issue by mr-kelly** [wsdjeg/SpaceVim#3423]
When I install the latest SpaceVim....  v1.3.0

## Screenshots

<img width="562" alt="WX20200328-112814@2x" src="https://user-images.githubusercontent.com/520852/77813892-42481d00-70e7-11ea-8a78-a5964798c81c.png">

**Comment by wsdjeg** [comment]
with command `SPReinstall`,  you can reinstall the plugin.
