### ISSUE TITLE
Add Universal Ctags To TagBar forked plugin

### ISSUE THREAD

**Issue by strazto** [wsdjeg/SpaceVim#3426]
**Is your feature request related to a problem? Please describe.**

Exuberant Ctags is no longer maintained, and has been replaced by the very active Universal Ctags. 

It appears to significantly extend Exuberant, and natively supports a **lot** more languages.

The [base tagbar repo](https://github.com/majutsushi/tagbar) has actually already added support for Universal ctags, but SpaceVim's fork does not. 

**Describe the solution you'd like**

I hope that you can update your fork of TagBar to include Universal Ctags support. 

Here is a comparison between the forks - An alarming detail is that at some stage it looks like someone has refactored all of the strings to only use single quotes, which makes a pull request seem a lot more significant. 

https://github.com/wsdjeg/tagbar/compare/master...majutsushi:master

**Comment by wsdjeg** [comment]
@mstr3336 PR is welcome, we use forked repo to implement some feature based on SpaceVim API. which can not be used in origin repo.

**Comment by strazto** [comment]
I put the PR in on the fork, but I don't think my tests are really working yet, so I'm not convinced

**Comment by wsdjeg** [comment]
@mstr3336 thanks, I will look into this issue.

**Comment by wsdjeg** [comment]
closed, we use upstream repo now,
