### ISSUE TITLE
code sharing, pastebin, dpaste like feature

### ISSUE THREAD

**Issue by aasutossh** [wsdjeg/SpaceVim#3427]
I'd like to be able to paste a file or selected text into a [`pastebin`](http://pastebin.com) or [`dpaste`](http://dpaste.com) like service. It would fit SpaceVim pretty well.

I think there are some terminal applications for this like [`pastebinit`](https://github.com/jessfraz/pastebinit) and others. But being able to paste only selected text quickly would be so good.

Edit: links

**Comment by wsdjeg** [comment]
thanks, I also think it is a useful feature. but which command should we use, the default key binding for paste text into clipboard is `Leader y`.

**Comment by wsdjeg** [comment]
pastebin can not be used in chinese. so this can not be set as default tool.

dpaste support api, so we can use `curl` command.
