### ISSUE TITLE
Python black formatter

### ISSUE THREAD

**Issue by rgarrigue** [wsdjeg/SpaceVim#3429]
HI there

There's yapf & autopep8 available as python formatter. Could you please add black ? With the -S option toggable.

Best regards

**Comment by PeterDing** [comment]
SpaceVim uses `neoformat` to format code. To use `black`, you need to add following lines to `~/.SpaceVim.d/autoload/myspacevim.vim` (more details: [doc](https://spacevim.org/documentation/#custom-configuration)).

```vim
let g:neoformat_python_black = {
    \ 'exe': 'black',
    \ 'stdin': 1,
    \ 'args': ['-q', '-'],
    \ }
let g:neoformat_enabled_python = ['black']
```

**Comment by rgarrigue** [comment]
Thanks @PeterDing . It works on a SPACE b f, an explicit message tells me "Neoformat: black formatter buffer".

But if I add `  format_on_save = 1` on save in my `.SpaceVim.d/init.toml`, saving tells me "Neoformat: formatter yapf failed". Normal it's not installed. How can I tell it to use black on save ?

**Comment by PeterDing** [comment]
`black` is not used when `format_on_save = 1` is added, because the author uses `yapf` as the default when `format_on_save = 1` is set.
https://github.com/SpaceVim/SpaceVim/blob/d1ba7d7cf2172398d808d990aa6ffeb30efa5e49/autoload/SpaceVim/layers/lang/python.vim#L143
@wsdjeg

**Comment by rgarrigue** [comment]
Ok, indeed it works after a 

    sed -i 's;yapf;black;' $HOME/.SpaceVim/autoload/SpaceVim/layers/lang/python.vim

Can I override this cleanly ? Since I guess not, I pinged the author on the related PR to see if he can add this upstream.

**Comment by wsdjeg** [comment]
@rgarrigue @PeterDing thanks, we should not use the yapf as the default format when save a file, this should based on the user's config. so change the line:

```
 autocmd BufWritePost *.py Neoformat yapf 
```

to

```
autocmd BufWritePost *.py Neoformat
```

**Comment by rgarrigue** [comment]
Thanks @wsdjeg :-)
