### ISSUE TITLE
Neoformat doesn't work

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#344]
## Expected behavior, english is recommend
 Neoformat should format my code after I produce some code which violates the conventions. 
## Environment Information
- OS: macOS Sierra 10.12.3 
- vim version:
- neovim version: NVIM 0.1.7

## The reproduce ways from Vim starting (Required!)

after opening file test.go
make some changes which violates the conventions.
type `:Neoformat`, 
format my code

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
always outputs: 
Neoformat: attempted all formatters for current filetype

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

I don't have any custom configs. Also, the Neoformat also does not work for java and python. 
Could you please help me :)

**Comment by wsdjeg** [comment]
will look in to it.

**Comment by wsdjeg** [comment]
Now java format should works well. please download google-java-format-1.3-all-deps.jar form 
https://github.com/google/google-java-format/releases

and set `g:spacevim_layer_lang_java_formatter` to the path of this jar file in your custom configration file. for example
```vim
let g:spacevim_layer_lang_java_formatter = expand('~/Downloads/google-java-format-1.3-all-deps.jar')
```

**Comment by wsdjeg** [comment]
here is a video

https://asciinema.org/a/ckbir30pn2qi5nexphjt1ptls

**Comment by icearith** [comment]
@wsdjeg Lovely, I noticed that you have changed some config of SpaveVim, does it mean that I need to update the plugin by installing the plugin again?

**Comment by wsdjeg** [comment]
just run git pull in ～/.SpaceVim

**Comment by icearith** [comment]
@wsdjeg  sorry for bothering. I tried this method. But it still doesn't work. The same output
`Neoformat: attempted all formatters for current filetype` produced every time.

I only have one line of custom configuration in .SpaceVim.d/init.vim, which is:
```vim
 let g:spacevim_layer_lang_java_formatter = expand('~/.cache/google-java-format-1.3-all-deps.jar')
```

I tried to run `:echo g:spacevim_layer_lang_java_formatter`, which outputs the right path I set. 

is there any suggestions for error tracking?

**Comment by icearith** [comment]
@wsdjeg by the way, I read the description of Neoformat, which already contains formatter for java, such as `['uncrustify', 'astyle', 'clang-format']`, I installed `uncrustify` via `brew install`. why cannot I use `uncrustify` directly?  

When I run `: Neoformat uncrustify`, it also gives the same output as I mentioned before.

**Comment by wsdjeg** [comment]
sorry I do not use uncrustify, I think the format config must has some errors.

**Comment by wsdjeg** [comment]
I will have a try with `uncrustify`

**Comment by wsdjeg** [comment]
in neoformat default config for uncrustify this no -c option, so you need set `UNCRUSTIFY_CONFIG` evn.
`Specify the config file with '-c file' or set UNCRUSTIFY_CONFIG`

**Comment by icearith** [comment]
@wsdjeg I have the config file put in `$HOME/.uncrustify.cfg`, but it still doesn't work and gives 

```
Neoformat: attempted all formatters for current filetype
```

It's ok when I try to format python.

**Comment by icearith** [comment]
@wsdjeg, I also tried google format, it doesn't work as well. :)

**Comment by wsdjeg** [comment]
I just test in cli, it works well, 
`u2ncrustify  -q -l JAVA -f src/main/java/com/wsdjeg/chat/Server.java ` works well, it can output formated code, but in this plugin it does not work,
my config file is ~/.uncrustify/ben.cfg
and I have 
```
export UNCRUSTIFY_CONFIG="$HOME/.uncrustify/ben.cfg"
```
in bashrc, but it still not work.

cc @sbdchd

**Comment by icearith** [comment]
@wsdjeg I have the same test result. uncrustify works well in bash. but it does not work in neoformat.

**Comment by sbdchd** [comment]
@wsdjeg How does the following work?

```diff
diff --git a/autoload/neoformat/formatters/java.vim b/autoload/neoformat/formatters/java.vim
index 68b0df9..bf3f396 100644
--- a/autoload/neoformat/formatters/java.vim
+++ b/autoload/neoformat/formatters/java.vim
@@ -5,7 +5,7 @@ endfunction
 function! neoformat#formatters#java#uncrustify() abort
      return {
             \ 'exe': 'uncrustify',
-            \ 'args': ['-q', '-l JAVA', '-f'],
+            \ 'args': ['-q', '-l JAVA'],
             \ 'stdin': 1,
             \ }
 endfunction
```

**Comment by wsdjeg** [comment]
why should we remove `-f` options, I test in in cli, and it generate a unuseful file.
```
✔ wsdjeg:Chatting [ master | ✔  ] ➭ uncrustify  -q -l JAVA src/main/java/com/wsdjeg/chat/Server.java 
✔ wsdjeg:Chatting [ master | …1 ] ➭ git status 
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	src/main/java/com/wsdjeg/chat/Server.java.uncrustify

nothing added to commit but untracked files present (use "git add" to track)
✔ wsdjeg:Chatting [ master | …1 ] ➭ 
```

**Comment by sbdchd** [comment]
I think Neoformat should ultimately be running the following command
```
❯ cat server.java | uncrustify -q -l JAVA
class Server {

    public static void main(String[] args) {
        System.out.println("hello world");
    }

} 
```

**Comment by wsdjeg** [comment]
@sbdchd it works well, I just test it.

**Comment by wsdjeg** [comment]
I am not sure all the formatter should remove `-f` options.

EDIT:
here is the diff:
```diff
✔ wsdjeg:neoformat [ master | ✚ 1 ] ➭ git diff 
diff --git a/autoload/neoformat/formatters/java.vim b/autoload/neoformat/formatters/java.vim
index 68b0df9..de903ed 100644
--- a/autoload/neoformat/formatters/java.vim
+++ b/autoload/neoformat/formatters/java.vim
@@ -5,7 +5,7 @@ endfunction
 function! neoformat#formatters#java#uncrustify() abort
      return {
             \ 'exe': 'uncrustify',
-            \ 'args': ['-q', '-l JAVA', '-f'],
+            \ 'args': ['-q', '-l JAVA',],
             \ 'stdin': 1,
             \ }
 endfunction
```
