### ISSUE TITLE
languageclient-neovim:building failed

### ISSUE THREAD

**Issue by SadSock** [wsdjeg/SpaceVim#3441]
<img width="403" alt="图片" src="https://user-images.githubusercontent.com/7643216/79059319-0e562580-7cab-11ea-8675-cc008a1e4209.png">

**Comment by SadSock** [comment]
# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    guifont = "SauceCodePro Nerd Font Mono:h14"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"


[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "cpp"
  ]
  [layers.override_cmd]
    rust = ["rustup", "run", "nightly", "rls"]

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#c"


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
    name = "chinese"

[[layers]]
    name = "denite"

#[[layers]]
#    name = 'checkers'

**Comment by SadSock** [comment]
`# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    guifont = "SauceCodePro Nerd Font Mono:h14"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"


[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "cpp"
  ]
  [layers.override_cmd]
    rust = ["rustup", "run", "nightly", "rls"]

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#c"


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
    name = "chinese"

[[layers]]
    name = "denite"

#[[layers]]
#    name = 'checkers'`

**Comment by SadSock** [comment]
> [options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    guifont = "SauceCodePro Nerd Font Mono:h14"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

**Comment by wsdjeg** [comment]
@SadSock What is your os, the building command of this plugin is `bash install.sh`.

**Comment by SadSock** [comment]
I solve this problem by reinstall spacevim.

**Comment by wsdjeg** [comment]
ok
