### ISSUE TITLE
[SPC]el doesn't "toggle-showing-the-error-list"

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3449]
## Expected behavior, english is required

While error-list is not opened, pressing ``[SPC]el`` to open it, else close it.  But ``[SPC]el``/``[SPC]eL`` doesn't close error-list when it's already opened.

## The reproduce ways from Vim starting (Required!)

1. vim test.cpp
2. ``:Neomake``
3. pressing ``[SPC]el`` or ``[SPC]eL``, the error-list is opened
4. press again, the error-list remains open

**Comment by wsdjeg** [comment]
we need a function to check if the error-list is opened. the error-list should include quickfix list and location list.

BTW, too many plugins are based on quickfix or location list. if the quickfix/location list are opened, But the content is not error information. we should replace the content of error-list.
