### ISSUE TITLE
Usability improvement on first install | Update README

### ISSUE THREAD

**Issue by FazleArefin** [wsdjeg/SpaceVim#345]
I tried out SpaceVim yesterday for the first time. The one issue I had was I wasn't calling `call dein#install()` on initial launch of vim after SpaceVim install. 

I think the README needs to highlight this step more explicitly so new users do not overlook this step. Instead of 

```
curl -sLf https://spacevim.org/install.sh | bash
```

It's better to make this step

```
curl -sLf https://spacevim.org/install.sh | bash
vim "+call dein#install()"
```

**Comment by wsdjeg** [comment]
SpaceVim  will auto run dein#install(), if there is uninstalled plugin. No need call this function yourself.

**Comment by wsdjeg** [comment]
Please  read :help  g:spacevim_checkinstall

**Comment by FazleArefin** [comment]
Yes, it does run it automatically. But during the process vim becomes very unresponsive and sluggish. First time users who are impatient, might end up thinking SpaceVim is broken and will immediately uninstall SpaceVim. First impressions count.

**Comment by wsdjeg** [comment]
yeah， it is big issue, readme  need  to be improved. Can you help me with it? English  is not my native  language .

**Comment by FazleArefin** [comment]
Although I'm quite busy, I can probably help you with the readme. Let me know which sections you need help with.

**Comment by wsdjeg** [comment]
I am not sure if I should disable checkinstall feature of spacevim.

**Comment by wsdjeg** [comment]
I have disable checkinstall feature.
