### ISSUE TITLE
Two quickfix windows exists at the same time

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3450]
## Expected behavior, english is required

While editing ``cpp`` files with ``g:neomake_open_list = 2``, a neomake quickfix window will be opened after saving the buffer.  Then use ``:make`` to build the project, a second quickfix window is opened below the neomake one. 

The strangest thing is, pressing ``q`` inside either quickfix window will close both windows.  I use ``g:neomake_open_list = 0`` to solve this problem, but I think this should be an issue.

## The reproduce ways from Vim starting (Required!)

1. open some c++ sources with something wrong to produce some warnings/errors (an empty file with just few chars in it works)
1. save the file to show the neomake quickfix window
1. ``:make`` to build it
1. ``:copen`` to open the second quickfix window

## Debug info

```
- OS: mac
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 
```

## Screenshots

<img width="817" alt="two_quickfix" src="https://user-images.githubusercontent.com/457419/79414842-509aa200-7fde-11ea-943d-ca776057db3a.png">

**Comment by wsdjeg** [comment]
@thawk by default the neomake is using location list, and the `:make` command is using quickfix list, so when saving a file and run `:make` command, you should see two list windows: location list and quickfix list. neomake also provides an option to use quickfix list instead of location list. you can config it in bootstrap function.

this seems a issue with vim itself. if two plugin are using the quickfix list at same time. IMO, maybe neomake should provide an open API for getting errorlist infomation for cached value. so when another plugin is using location list, we can resume the error list.

cc @blueyed

**Comment by wsdjeg** [comment]
This is not bug, but feature, neomake use location list by default in spacevim. when save cpp file, it will run `Neomake` by default, the result will be put into location list. `:make` command is vim's buildin command, it will put result into qucifix. `copen` is to open quickfix windows.

**Comment by blueyed** [comment]
Yeah, there are both a location and quickfix lists.
This is useful in general to have a list for the buffer (linting/Neomake), and the project (make, grep etc).

> The strangest thing is, pressing `q` inside either quickfix window will close both windows. I use `g:neomake_open_list = 0` to solve this problem, but I think this should be an issue.

Check `:verbose map q` (inside one of the windows).
Maybe the mapping/function there then needs to be fixed to only close the current (`ft=qf`) window, not all of them.

**Comment by wsdjeg** [comment]
@blueyed Thanks, I have test it, it seems a bug of spacevim key binding, when press `q` in location list windows, both of them will be closed. do you know how to check if it is quickfix window or location list windows.

just found some info:

- https://vi.stackexchange.com/questions/16585/how-to-differentiate-quickfix-window-buffers-and-location-list-buffers
