### ISSUE TITLE
What did you guys do for slow startup?

### ISSUE THREAD

**Issue by robertwt7** [wsdjeg/SpaceVim#3455]
Hey guys, 

First timer here, I'm always using vs code  with vim plugin previously. 

Had a look at spacevim and thought it would be awesome for me to edit in commandline straightaway!

I realise that someone reported this issue a while ago [#1975 ](https://github.com/SpaceVim/SpaceVim/issues/1975) and it was merged at version 1 (i assume it should be fixed by now)?

My version for spacevim is 1.5.0-dev with neovim but i'm getting 1.7sec startup time (crazy!)

Here's all of my log files

Vanilla vim: 0.05s
nvim with spacevim: 1.7s
vim with spacevim: 1.3s
[s_rob.log](https://github.com/SpaceVim/SpaceVim/files/4490699/s_rob.log)
[s_vim.log](https://github.com/SpaceVim/SpaceVim/files/4490700/s_vim.log)
[s_nvim.log](https://github.com/SpaceVim/SpaceVim/files/4490701/s_nvim.log)

What should I do? 

I really thought spacevim will be a promising project for command line editor. Please help!

What i did according to issue #1975 

Put this in my `.zshrc`:
```
export PYTHON_HOST_PROG=`which python2`
export PYTHON3_HOST_PROG=`which python3`
```

Got an error:
```
function SpaceVim#util#haspy3lib[5]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line
 4
Vim(if):Error invoking 'poll' on channel 3:^@ch 3 was closed by the client
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated l
og file. Also, the host stderr is available in messages.
```

Edit:
I'm running on windows WSL version 1 with ssd
Haven't tried yet on my macbook

**Comment by wsdjeg** [comment]
Yeah, it is known issue, but it is hard to debug. it is only 500ms in my os.

**Comment by Guzzii** [comment]
@wsdjeg I am having the same issue but much more server. It takes about 6 secs for me with latest 15" MacBook Pro. The main time is spent on the following files.

```bash
5196.421  5185.426  5184.397: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/autoload/provider/python3.vim
```

**Comment by Guzzii** [comment]
@wsdjeg @robertwt7 Oops, by defining `PYTHON_HOST_PROG` and `PYTHON3_HOST_PROG ` in env variables, startup becomes instant for me.

**Comment by robertwt7** [comment]
I have `PYTHON_HOST_PROG` and `PYTHON3_HOST_PROG` actually. For some reason it still takes that long for now :/ 

I'm trying it on WSL on my PC. Not sure how it goes on my macbook pro 15

**Comment by tranhoangcore** [comment]
**Archlinux + Neovim**: 431ms.
I think it's hard to know where the real problem lies. 
Probably due to different hardware between us.

**Comment by wsdjeg** [comment]
The issue must be reproduce able and pinted to the code. which function or command should we improve.
