### ISSUE TITLE
REPL C ,executing job failed: No such file or directory

### ISSUE THREAD

**Issue by 404-not-find** [wsdjeg/SpaceVim#3458]
when I write C reffer ,https://spacevim.org/use-vim-as-a-c-cpp-ide/ .Start a igcc inferior REPL process with SPC l s i  ,I got [REPL executable] 'igcc' ,executing job failed: No such file or directory
![image](https://user-images.githubusercontent.com/3479503/79632053-74511a00-818f-11ea-97cb-3f05c726027d.png)

**Comment by wsdjeg** [comment]
why do not read the error message?

```
[REPL executable] 'igcc' 
executing job failed: No such file or directory
```

means can not find the executable file `igcc` in your path.
