### ISSUE TITLE
Installation on Windows 10 seems to not work

### ISSUE THREAD

**Issue by Skips75** [wsdjeg/SpaceVim#3463]
## Expected behavior, english is required
After executing install.cmd as admin on Win10 I expected that SpaceVim installation completed
by means of a init.toml generation.

## The reproduce ways from Vim starting (Required!)
Gvim 8.2 and git installed on Windows10 via scoop utility.
Downloaded install.cmd and executed as admin in Powershell.
install.cmd runs successfully, it clones git repo into c:\users\utente\.SpaceVim and 
successfully creates c:\users\utenet\vimfiles symlink.
When I run Gvim no Vinrun.exe executes and no dein.vim is downloaded: nothing happens.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
you can use `:scriptnames` command to check which vimrc is used. make sure `~/vimfiles/vimrc` is used in your os.

**Comment by okokgoodtwo** [comment]
> you can use `:scriptnames` command to check which vimrc is used. make sure `~/vimfiles/vimrc` is used in your os.

        I have the same problem,I run the cmd.exe successfully,After the installation,The cmd terminal tell me that if I RUN the Gvim.exe,the spacevim plugin will automatically continue its downloads But **NOTHING HAPPENED** when I run it.
        I don't really understand what you have said. Could you give me some more instructions in detail? Thank you !
