### ISSUE TITLE
vim-todo not working without spacevim

### ISSUE THREAD

**Issue by breuerfelix** [wsdjeg/SpaceVim#3466]
## Expected behavior, english is required

https://github.com/wsdjeg/vim-todo  
it says it works without spacevim and automatically detaches. it doesn't  
because this repo has no issues i think its also related to spacevim (since its programmed for that) so i will try my best here since i think this is a simple powerful plugin

## The reproduce ways from Vim starting (Required!)

add the plugin with your plugin manager without spacevim  
`:OpenTodo` in the command line

## Debug info

i am on linux with neovim

## Screenshots

![2020-04-21-210901_1254x244_scrot](https://user-images.githubusercontent.com/36931468/79904341-cce51900-8414-11ea-97ca-f0ef16a63cb4.png)

**Comment by wsdjeg** [comment]
It seems the attached file is missing, will fix it later.

**Comment by breuerfelix** [comment]
awesome, looking forwards for tests :)

**Comment by breuerfelix** [comment]
![image](https://user-images.githubusercontent.com/36931468/91752556-ccc90700-ebc6-11ea-914d-c6e1bfe9e362.png)
this is the error i am getting after your PR (btw thanks for that!)  
just letting you know, maybe there is something wrong in my place now, i dont know.

**Comment by wsdjeg** [comment]
Hmm, sorry, I do not why, This works well in latest version of spacevim.

**Comment by romgrk** [comment]
Hey, I think there are two issues here:
 - The plugin (https://github.com/wsdjeg/vim-todo) doesn't mention that the syntax is `@todo my message here` as opposed to the more common `TODO my message here`. That combined with the fact that there is no empty placeholder message makes in sort that a user installing the plugin from the vim-todo repo will end up with an empty window.
 - Something is causing the "E488: Trailing characters"

@breuerfelix if you add `// @todo test` somewhere in the repo you're testing the plugin in, does it appear when you do `:OpenTodo`?

**Comment by romgrk** [comment]
The file `plugin/todo.vim` was using DOS line endings, so (neo)vim was reading `command! OpenTodo call todo#open()\r`, that's the trailing character. Not applicable in SpaceVim, and I've opened a PR for [vim-todo](https://github.com/wsdjeg/vim-todo/pull/2).

But really #3819 should be addressed. `TODO|FIXME|XXX` are very standard when marking inline tasks. (EDIT: addressed [here](https://github.com/wsdjeg/vim-todo/pull/3))

**Comment by wsdjeg** [comment]
Vim toto is mirror repo, maybe we should fix it in spacevim repo.

**Comment by romgrk** [comment]
Ergh. Mfiiiine. I'll open a PR on spacevim in a moment.
