### ISSUE TITLE
SpaceVim Blocked(dead)

### ISSUE THREAD

**Issue by Ander456** [wsdjeg/SpaceVim#3471]
1. i quit the space vim use :q
2. i open the same project use vim xxx
3. i open the same file  ex:abc.cpp
4. spacevim blocked like dead

**Comment by Ander456** [comment]
oh .another thing
1. macos Majove 10.14.6

**Comment by tranhoangcore** [comment]
Follow the steps that follow you, however, I think it works well.
If you find any problems, please read carefully the necessary information about error reports.

**Comment by Ander456** [comment]
i known, because of the backup file . fuck the backup
