### ISSUE TITLE
Status line :: Indication of paste mode :: Circled letter

### ISSUE THREAD

**Issue by lcrockett** [wsdjeg/SpaceVim#3473]
**Is your feature request related to a problem? Please describe.**
Unless you remembered, it is not clear wether or not you're in paste mode. Within SpaceVim there are no visual indications for this.

**Describe the solution you'd like**
It would be nice to have a circled 'p' letter appearing in the status line that indicates you're in paste mode. Similar to the current behaviour of showing a circled 's' letter that appears if syntax checking has been enabled.

**Describe alternatives you've considered**
Considering the status line is quite an integrated part of SpaceVim, no considerations have been made to achieve the above otherwise.

**Additional context**
In order to show the current status (in text) of paste mode one can use the following to retrieve it's status
`return "%{ &paste ? '\ paste\ ':'\ nopaste\ '}"`

**Comment by wsdjeg** [comment]
Yeah, this should be shown on statusline. In other statusline plugin it will show `Paste >` before the statusline if this option is on.  circled 'p' is not a good idea, because we will use it for toggle pair mode, just same as `SPC t p` do in spacemacs.

**Comment by lcrockett** [comment]
Showing 'Paste >' before the statusline if in paste mode sounds like a good idea.
