### ISSUE TITLE
Status line :: Inclusion for external module :: drzel/vim-line-no-indicator

### ISSUE THREAD

**Issue by lcrockett** [wsdjeg/SpaceVim#3474]
**Is your feature request related to a problem? Please describe.**
As the status line is quite an integrated part of SpaceVim, it is not trivial to include custom plugins that modify the status line when using SpaceVim.

**Describe the solution you'd like**
Either allow for custom parts within the SpaceVim controlled status line, or a duplication of the behaviour the custom plugin, vim-line-no-indicator, offers. Currently there is a percentage based indication. The custom plugin referred to however offers different visualisations of this indication.

**Describe alternatives you've considered**
No alternatives have been explored considering the tight integration between SpaceVim and the status line.

**Additional context**
GitHub repo as an example of the desired functionality; https://github.com/drzel/vim-line-no-indicator

**Comment by wsdjeg** [comment]
This plugin looks nice, But the built-in statusline do not support custom section now, I will add this feature.

**Comment by lcrockett** [comment]
Great ! If I can help testing it, let me know.
