### ISSUE TITLE
Install for an offline container

### ISSUE THREAD

**Issue by kakulukia** [wsdjeg/SpaceVim#3477]
Im trying to install SpaceVim in a container that will be used in a restricted environment with no internet access. So i was wondering if there is an undocumented version of the installation, that also triggers the first startup and installation of plugins?

The desired solution is an unattended install that also installs all plugins.

**Comment by wsdjeg** [comment]
Yes, this is not documented in the website. But you can use this command

vim "+call dein#install#_update([], 'update', 0)" '+qall'

**Comment by kakulukia** [comment]
hmmm .. nearly awesome .. this works nicely in my shell, but the Dockerfile wont finish to build.

It looks like it hangs at
"Press ENTER or type command to continue"
but i will strip this down to a minimal Dockerfile later and add it to the ticket.

But its definitely a good start, thx @wsdjeg !

**Comment by kakulukia** [comment]
git clone https://github.com/Shougo/dein.vim "/root/.cache/vimfiles/repos/github.com/Shougo/dein.vim"
    vim "+call dein#install#_update([], 'update', 0)" '+qall'

Those two commands do the trick.
The docker build output looks kinda funny, but i now have a working vim instance.

Nice!

Shall i leave this ticket open so this trick gets merged into the docs somewhere?
This manual ´git clone´ also feels a bit of "that might break very easily".

**Comment by wsdjeg** [comment]
Thanks, can you send a pull request?

**Comment by wsdjeg** [comment]
Most of the default plugin has been added into bundle diretory, so this can be closed.
