### ISSUE TITLE
Consider vim-sleuth for improved indentation settings

### ISSUE THREAD

**Issue by setpill** [wsdjeg/SpaceVim#3498]
**Is your feature request related to a problem? Please describe.**
Different languages and projects have different indentation practices. Setting static settings with `default_indent` and `expand_tab` is not sufficient. EditorConfig is nice, but ideally things should "just work" out of the box without manually adding configs to every project (after all, isn't that the point of SpaceVim?)

**Describe the solution you'd like**
Use https://github.com/tpope/vim-sleuth. It is excellent.

**Describe alternatives you've considered**
None, really. I've used vim-sleuth in my own `.vimrc` for ages, and it works perfectly.

**Additional context**
I've tried setting up vim-sleuth via `[[custom_plugins]]` but it's not working quite perfectly with SpaceVim. It is replacing spaces with tabs when this is not appropriate. Not sure what is the cause of this yet - `default_indent` and `expand_tab` are not set in my SpaceVim config. There seems to be some detrimental interaction.

**Comment by wsdjeg** [comment]
@setpill sorry, we can not include this plugin, because, it will confuse users. people who have set `default_indent` ot `expand_tab` option may not works well with this plugin. this kind of option should be set manully, and should be controlled by configuration files  precisely instead of gussed by a plugin.

**Comment by setpill** [comment]
I agree that local configuration (either in init.toml or project-specific) should override vim-sleuth's guesses. But in my experience, vim-sleuth "just does it right" 99% of the time.

The way I am reading your argument is that you want to force people to use config files for this, but I don't think that's what you want. Could you clarify?

**Comment by wsdjeg** [comment]
for a project, it should contains a config file for all the indent option for files in a project, and make sure all people use save indent option.

because not all people use save tools to edit code. so we use editconfig, this kind of config can be used by vim vscode etc.
--------------
wsdjeg

**Comment by setpill** [comment]
Most projects that I work on do not have such config file. I would like to be able to use SpaceVim even in these circumstances without manually writing this config file. Please consider supporting autodetection in the absence of configuration.
