### ISSUE TITLE
Unclear how to uninstall, or find backups

### ISSUE THREAD

**Issue by dharness** [wsdjeg/SpaceVim#35]
Upon installation I get the following message:
```
Successfully clone SpaceVim
BackUp /Users/dharness/.vimrc
BackUp /Users/dharness/.vim
Installed SpaceVim for vim
BackUp /Users/dharness/.config/nvim
Installed SpaceVim for neovim
```

It is not clear to me where my .vimrc has been backed up to? A mention of this in the README would be nice, even better would be:

```
curl spacevim.org/uninstall.sh -sSf | sh
```

_nit: `Successfully clone SpaceVim` should say `Successfully *cloned* SpaceVim`_

EDIT: For anyone else looking, they are in .vim_back and .vimrc_back

**Comment by wsdjeg** [comment]
yeah, thanks for feedback, will add to TODO list.
help from https://stackoverflow.com/questions/4642915/passing-parameters-to-bash-when-executing-a-script-fetched-by-curl

- [ ] uninstall script. will implement something like:
   `curl -sSf url | bash -s -- install name`, here support vim and neovim
   `curl -sSf url | bash -s -- uninstall`

- [ ] Update readme for backups.

**Comment by LocNguyenHuu** [comment]
@dharness Please tell me what the best way to completely uninstall spacevim on OSX?

**Comment by xclidongbo** [comment]
How uninstall ?

**Comment by dharness** [comment]
sorry @xclidongbo , I don't remember the specifics. I would guess you can just:
`rm -rf  ~/.vimrc .vim` all the space vim stuff, and then copy your old stuff back
` mv ~/.vim_back ~/.vim && mv ~/.vimrc_back ~/.vimrc` 

**untested**

**Comment by xclidongbo** [comment]
@dharness  Thanks.
