### ISSUE TITLE
how can I close syntax highlight when open a .tex file

### ISSUE THREAD

**Issue by lengyijun** [wsdjeg/SpaceVim#3503]
I have append this in ~/.SpaceVim.d/init.toml

```
[[layers]]
  name = "lang#latex"
  enable = false

```
but nothing happened

**Comment by thilofischer** [comment]
This is not a SpaceVim specific answer, but you can do it as described here:
https://stackoverflow.com/a/27440576

`autocmd! bufreadpost *.tex set syntax=off`

This command should be executed after SpaceVim has loaded its config.

**Comment by wsdjeg** [comment]
@thilofischer thanks.
--------------
wsdjeg
