### ISSUE TITLE
Highlight the word and the same words under the cursor

### ISSUE THREAD

**Issue by jidibinlin** [wsdjeg/SpaceVim#3504]
**Describe the solution you'd like**
Highlight the word and the same words under the cursor

**Additional context**

![customized](https://user-images.githubusercontent.com/38578679/80856666-5a7b0100-8c7e-11ea-8c1d-5aeb4c9c0580.gif)

This gif is from [dominikduda/vim_current_word](https://github.com/dominikduda/vim_current_word)

**Comment by wsdjeg** [comment]
This can be included in UI layer, but should be disabled by default, just add a layer option to enable it. PR is welcome.
