### ISSUE TITLE
How to add Doxygen to SpaceVim?How to support cross-tool-chain?

### ISSUE THREAD

**Issue by ChangmingTian** [wsdjeg/SpaceVim#3505]
1.How to add Doxygen to SpaceVim?
2.Quickfix window showup after run ":w",How to disable this feature?
    I am working on Cortex-M0
    Some information in the Quickfix window is useless
    It is not comfortable to close Quickfix after run ":w".
3.My project directory is like:
   /stm32/gcc/
  my makefile is in /stm32/gcc/
  every time I run vim,pwm jump to /stm32 not keep /stm32/gcc

**Comment by ChangmingTian** [comment]
Add this to init.toml can disable neomake,then no Quickfix window show up after run ":w".
[options]
disabled_plugins = ["neomake"]

**Comment by wsdjeg** [comment]
1. SpaceVim has provide an option `lint_on_save`, you can set it to false

```toml
[options]
    lint_on_save = false
```

2. SpaceVim will find the root based on `project_rooter_patterns` option, the default value is  `['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']`
