### ISSUE TITLE
The quickfix buffer should show search result after `SPC s f`

### ISSUE THREAD

**Issue by blueway** [wsdjeg/SpaceVim#3509]
**Is your feature request related to a problem? Please describe.**
Inconvenient to view search results， I need to search  in an arbitrary directory
because my project is big
**Describe the solution you'd like**
The quickfix buffer should show search result after `SPC s f`

**Describe alternatives you've considered**
no
**Additional context**
no

**Comment by wsdjeg** [comment]
`SPC s f` is try to use flygrep to search text, the result will not be shown in quickfix, it you need to use quickfix, run `:Grepper` command.

**Comment by blueway** [comment]
`:Grepper` and `vimgrep` can't seem to search in an arbitrary directory
