### ISSUE TITLE
can not install plugin after a fresh installation in university cluster

### ISSUE THREAD

**Issue by xiuliren** [wsdjeg/SpaceVim#3512]
## Expected behavior, english is required
install plugins automatically in the first launch of spacevim
The vim version is 7.4
## The reproduce ways from Vim starting (Required!)
In university cluster (I do not have root permission), I installed SpaceVim using:
```
curl -sLf https://spacevim.org/install.sh | bash
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
somehow, I can not copy out the info. Almost all the plugins are `not loaded` since the installation failed.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
when I launch SpaceVim for the first time.
![image](https://user-images.githubusercontent.com/7651573/81209961-2e71bf80-8f9f-11ea-8903-4624e76ab7f1.png)

the information shown after <kbd>SPC h I</kbd>
![image](https://user-images.githubusercontent.com/7651573/81209865-100bc400-8f9f-11ea-956f-64d612d9ab69.png)

**Comment by wsdjeg** [comment]
This maybe a issue with old vim, do you have a try with neovim v0.4.3?
