### ISSUE TITLE
coc.nvim install failed under windows

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#3516]
![image](https://user-images.githubusercontent.com/1751829/81296259-35cec100-90a4-11ea-93e2-18066bdc0642.png)

**Comment by PeterDing** [comment]
@wsdjeg On May 9 2020, coc.nvim project has deleted the `coc.nvim/install.sh` file. It breaks following code:
https://github.com/SpaceVim/SpaceVim/blob/b90c7fb57a516bf473b7f1af5d32f832914ca9dc/autoload/SpaceVim/layers/autocomplete.vim#L70

**Comment by rohit-s8** [comment]
Yes I had the same problem on macos as well. The installation needs to be changed according to https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#using-deinvim

**Comment by vperilla** [comment]
Same on archlinux 
[https://asciinema.org/a/tm0vmai6BsqRggM0001QSJmBf](https://asciinema.org/a/tm0vmai6BsqRggM0001QSJmBf)

**Comment by PeterDing** [comment]
Guys, there is a temporary solution to fix the issue.
```shell
cd ~/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/
git checkout .
git pull
git checkout release
```

**Comment by martinigoyanes** [comment]
> Guys, there is a temporary solution to fix the issue.
> 
> ```shell
> cd ~/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/
> git checkout .
> git pull
> git checkout release
> ```

This doest solve anything for me.
<img width="1440" alt="Screen Shot 2020-06-01 at 1 42 05 PM" src="https://user-images.githubusercontent.com/58919465/83405833-b1a2fb80-a40d-11ea-959e-a455773ccf71.png">

**Comment by PeterDing** [comment]
@dev-martin Maybe, you need to clone `coc.nvim` again to the directory.

```shell
cd ~/.cache/vimfiles/repos/github.com/neoclide/
rm -fr coc.nvim
git clone https://github.com/neoclide/coc.nvim
cd coc.nvim
git checkout release
```
