### ISSUE TITLE
I do not see ++ in debug mode and the debug does not work

### ISSUE THREAD

**Issue by sun-peach** [wsdjeg/SpaceVim#3519]
## What expected
I have done a lot of debugging before with spacevim. This time when I hit SPC d l, the debug mode is enabled. But I do not see ++, and then I hit SPC d c, the debugger does not run.

## Reproduce

It just suddenly happen, I don't know how to reproduce it.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
The command does not work, I try to paste it here. But it does not work. 

## Screenshots

![image](https://user-images.githubusercontent.com/14579257/81495484-69a51480-9265-11ea-91c1-1690361d64ad.png)

**Comment by wsdjeg** [comment]
which language do you debug?

**Comment by wsdjeg** [comment]
This plugin should works well with python, you should lunch debuger first.
