### ISSUE TITLE
[Q] Add custom plugin without using `init.toml`

### ISSUE THREAD

**Issue by NightMachinery** [wsdjeg/SpaceVim#3527]
I want to add some custom plugins, and I don't want to spend the energy learning how to translate each command into `init.toml`'s DSL. Is there a way I can just use normal vim code?

I have tried placing the code in bootstrap functions:

```
func! myspacevim#before() abort
  call dein#add('junegunn/fzf', { 'build': './install --all', 'merged': 0 })
  call dein#add('junegunn/fzf.vim', { 'depends': 'fzf' })
endf
```

But it doesn't work.

PS: I have spent quite a bit of energy on translating these commands to toml.init, with no luck.

```
 [[custom_plugins]]
 name = [ 'junegunn/fzf', 'build' : './install --all' ]
 merged = false

 [[custom_plugins]]
 name = [ 'junegunn/fzf.vim', 'depends' : 'fzf' ]
```

But even if it had worked, it is a very bad practice to force users to use a custom DSL to do simple things. Especially when that DSL will effectively lock the users in to Spacevim.

**Comment by wsdjeg** [comment]
no, custom plugin only can be added via toml file, It should be:

```
 [[custom_plugins]]
   name = 'junegunn/fzf'
  build = './install --all'
   merged = false
```
