### ISSUE TITLE
Change Vimfiler into NERDTree

### ISSUE THREAD

**Issue by goFrendiAsgard** [wsdjeg/SpaceVim#353]
Hi,  Seems that spacevim has both, vimfiler and NERDTree. By default it uses vimfiler. I used to use NERDTree. How can I change the default manager to NERDTree (something like let g:somevariable='NERDTree' or something).

Thx :)

**Comment by wsdjeg** [comment]
@goFrendiAsgard there is a option for filemanager, please see `:h g:spacevim_filemanager`, BTW, if you want to config spacevim, I recommend you to read `:h SpaceVim-config`.

**Comment by goFrendiAsgard** [comment]
Perfect.... 多谢 @wsdjeg

**Comment by sheharyarn** [comment]
For future reference, this is what you need to put in your config file:

```vim
let g:spacevim_filemanager = 'NerdTree'
```

**Comment by amer** [comment]
Use lowercase letters.
```
let g:spacevim_filemanager = 'nerdtree'
```
