### ISSUE TITLE
Error in Autocommands for TypeScript 

### ISSUE THREAD

**Issue by akshgpt7** [wsdjeg/SpaceVim#3530]
## Expected behavior, english is required
TypeScript (*.ts) files should open normally, without any Autocommand errors. 
Also, CursorMoved Autocommands are throwing error.

## The reproduce ways from Vim starting (Required!)
Open a TypeScript file.

## Screenshots
![Screenshot from 2020-05-13 09-47-24](https://user-images.githubusercontent.com/20405311/81770744-c838ef80-94fe-11ea-920e-fb10093782b6.png)

**Comment by heyyou3** [comment]
Please try it.

https://github.com/SpaceVim/SpaceVim/issues/1800#issuecomment-396638535
