### ISSUE TITLE
Can SpaceVim add PowerShell-Beautifier as powershell a format tools?

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#3532]
**Is your feature request related to a problem? Please describe.**
So far. SpaceVim cannot format PowerShell code via <key>SPC b f</key>.

**Describe the solution you'd like**
add "PowerShell-Beautifier" as PowerShell format tool. user need to install it first via `Install-Module -Name PowerShell-Beautifier`.

**Comment by wsdjeg** [comment]
We us forked version of neoformat, maybe this can be added into layer config. and PR is welcome.

**Comment by wsdjeg** [comment]
@ssfjhh what is the doc link for Powershell-beautifier? Does neoformat support this feature now?

**Comment by wsdjeg** [comment]
closed, there was no response.
