### ISSUE TITLE
How can I execute my Specific shell by SpaceVim on Windows?

### ISSUE THREAD

**Issue by DeCalvin2006** [wsdjeg/SpaceVim#3533]
I got a problem running vim 8.2 with SpaceVim latest(1.5-dev) and the shell plugin on Windows 10. 

Last Weekend I found SpaceVim from Bing Search, then I try it on my Arch Linux.It's a really nice "Extension" for Vim and It even makes Vim an IDE! (All the Developers know,IDE is Different from Text Editor.) I'm so EXCITED! :D

Then I installed SpaceVim and Vim 8.2 on Windows(Because I am a middle school student and I have to Use it to Study Online. Damn It!). However, When I open vim with Powershell,Installed Plugins and press <kbd>SPC</kbd>+<kbd>"</kbd>, it doesn't open powershell in the window, but it opens a CMD in the new window!  :(

I'm disappointed.So how can I use powershell(or other shells,except CMD) as my shell in SpaceVim?

---
Chinese Version:

我在Windows上运行Vim8.2+SpaceVim1.5-dev的shell插件时遇到了问题.

上周末我在Bing必应搜索上找到了SpaceVim,然后在我的Arch Linux上尝试了一下.它真的是一个好的Vim"扩展"并且它甚至把某些人的Vim变成了一个IDE!(众所周知,IDE和Text Editor是有区别的.) 我太兴奋了! :D

然后我就在我的Windows(因为我是个中学生而且我要上网课.真令人不爽.)上安装了Vim8.2和SpaceVim. 但是,当我打开Vim, 安装好插件, 然后按下 <kbd>SPC</kbd>+<kbd>"</kbd>打开Shell时,它并没有按照我的意思打开Powershell, 而是打开了CMD! :(

我很失望. 所以我怎么才能在SpaceVim里将Powershell(或者别的Shell,除了CMD)作为我的默认Shell?

My English is not good.If you are Chinese,you can read Chinese Version. If  you aren't,you can Use Translator to Translate it to English or your Language. :D

**Comment by wsdjeg** [comment]
you can add `let $SHELL='powershell'` to your bootstrap function.

**Comment by Rom1deTroyes** [comment]
I don't know much about Powershell, but on the Windows machines I'm forced to use, I always install [Git For Windows](https://gitforwindows.org/) : it brings you a decent terminal emulator ([mintty](https://code.google.com/archive/p/mintty/)), a not so bad version of bash, and minimal gnu toolbox (ssh, scp, cat, find, ... and git !).

SpaceVim work well out of the box (exept maybe some well documented things you have to do by hand, like choosing the font of you terminal - or maybe it's fine now ?).

An other way could be using [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), and have somme more robust things, but I'm not allowed to install this at work, so I don't know if it's better :-$

**Comment by wsdjeg** [comment]
in shell layer, the logic is:

```
        if s:SYSTEM.isWindows
          let shell = empty($SHELL) ? 'cmd.exe' : $SHELL
        else
          let shell = empty($SHELL) ? 'bash' : $SHELL
        endif
```

so you can change the evn `$SHELL` in bootstrap function to the path of `powershell.exe`.
