### ISSUE TITLE
autocomplete for nodejs module failure happens

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#354]
## Expected behavior
I want `SpaceVim` to help me complete methods, which is never written before, automatically.

There is no doubt that you can't just complete your code manually for too many modules of `nodejs`.

So I want this 3rd line of code:
![image](https://cloud.githubusercontent.com/assets/12933851/24307829/aad710d2-1100-11e7-9624-1ef15fd907e6.png)

It does show up because I've already written it above.

But if I never did that and also I need the name of method called `fs.readFileSync()`?

The answer is `NO`.

BTW, the module of `fs` is the basic module embedded in nodejs. I haven't talked about modules from 3rd party. Also, I'm using the latest code too: https://github.com/SpaceVim/SpaceVim/commit/4d5e5136289cfe9263213b6fa514c65be56d2f5c

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## File For Testing
`test.js`:
```javascript

var fs = require("fs");

var data = fs.readFileSync('input.txt');

console.log(data.toString());
console.log("The end!");
```

`input.txt`:
```txt
https://spacevim.org/
```

## `init.vim`
```viml
let g:spacevim_colorscheme  =   'molokai'
let g:spacevim_max_column   =   80
let g:spacevim_error_symbol =   '✗'
let g:spacevim_buffer_index_type = 4
let g:spacevim_enable_guicolors = 0
"let g:spacevim_custom_plugins=[
"            \ ['SpaceVim/vim-luacomplete'],
"            \
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#markdown')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('tmux')
```

**Comment by wsdjeg** [comment]
it works well for me in neovim, I will test in in vim.

https://asciinema.org/a/av7jlg2tg5qzo3xz0uvttp1d0

**Comment by wsdjeg** [comment]
I have fixed it.  please run `npm install` in `~/.cache/vimfiles/repos/github.com/ternjs/tern_for_vim/`

**Comment by Gabirel** [comment]
Can SpaceVim do it automatically for users instead of running `npm install` by users?

**Comment by wsdjeg** [comment]
I have add auto command for this plugin, this command will be runned when first time install tern-for-vim, or when reinstall it.
you can do it like 
`call dein#reinstall(['tern_for_vim'])`

**Comment by Gabirel** [comment]
It works, thanks

**Comment by Gabirel** [comment]
How can I be able to complete code of `electron` module(which is the 3rd party module)?

I make sure I've installed `electron` module on my labtop

Here're the codes for testing:
```javascript
const electron = require('electron');
const {app} = electron;

const {BrowserWindow} = electron;

let win;

function createWindow() {
	win = new BrowserWindow({
		width: 800,
		height: 600
	});

	win.loadURL(`file://${__dirname}/index.html`);

	win.webContents.openDevTools();

	win.on('closed', () => {
		win = null;
	});
}

app.on('ready', createWindow);

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();	
	}
});

app.on('activate', () => {
	if (win === null) {
		createWindow();
	}
})
```

**Comment by wsdjeg** [comment]
where is your cursor, and what do you want complete?

**Comment by Gabirel** [comment]
All of it. Especially code after `.`

For example: `win.loadURL`, `win.webContents.openDevTools` and etc.

These methods are original function in `electron` module.

**Comment by Gabirel** [comment]
By the way, you may have some trouble installing `electron` on your PC in China. You can try `express`, which is more easier for you to install.

Here are anthor codes for testing: 

```javascript
//express_demo.js
var express = require('express');
var app = express();
 
app.get('/', function (req, res) {
   res.send('Hello World');
})
 
var server = app.listen(8081, function () {
 
  var host = server.address().address
  var port = server.address().port
 
  console.log("app instance，URL: http://%s:%s", host, port)
 
})
```

**Comment by wsdjeg** [comment]
I just test in vim and neovim ,both works well for me

**Comment by Gabirel** [comment]
No way! Could you make a video for me please?

**Comment by wsdjeg** [comment]
https://asciinema.org/a/ej7884f3ergkb2unku44qha08

**Comment by Gabirel** [comment]
No, it's impossible that `express` only has few methods.
![image](https://cloud.githubusercontent.com/assets/12933851/24588910/f8e610d4-1803-11e7-8aeb-fafb1d5da69f.png)
This means SpaceVim doesn't finish its autocompletion job very well.

Here're main methods `express` has: [Express API](http://expressjs.com/zh-cn/4x/api.html#express.router)

**Comment by wsdjeg** [comment]
I think you should open issue in tern_for_vim repo, and SpaceVim can do nothing about it, it is issue about the omni func.
