### ISSUE TITLE
coc.nvim build failing

### ISSUE THREAD

**Issue by desirelabs** [wsdjeg/SpaceVim#3540]
Hello, thanks for this great project. I have an issue making coc work with Spacevim.

## Expected behavior, english is required

Coc shall work using the default layer.

## The reproduce ways from Vim starting (Required!)

*In init.toml*
**activate autocomplete layer**
```
[[layers]]
  name = "autocomplete"
```
**set coc as autocomplete method**
```
[[options]]
  autocomplete_method = "coc"
```
## Debug info

On vim start, the following message shows up : 
```
[coc.nvim] javascript file not found, please compile the code or use release branch.
Press ENTER or type command to continue
```

If I attempt SPUpdate : 
```
x coc.nvim: Building failed.
```

**debug info**

```
[denite] Vim(let):E117: Unknown function: yarp#py3
[denite] function <SNR>30_warp_denite[1]..denite#helper#call_denite[7]..denite#start[4]..<SNR>210_start[1]..denite#initialize[1]..denite#init#_initialize, line 28
[denite] denite requires vim-hug-neovim-rpc plugin in Vim.
[denite] denite requires nvim-yarp plugin.
Error detected while processing modelines:
line  140:
E518: Unknown option: not
```

**Comment by vperilla** [comment]
[https://github.com/SpaceVim/SpaceVim/issues/3516#issuecomment-626476490](https://github.com/SpaceVim/SpaceVim/issues/3516#issuecomment-626476490)

**Comment by mandaputtra** [comment]
For people who encounter these issue here my workaround following the docs in coc.

```
cd ~/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/
git pull origin master
yarn install --frozen-lockfile
```

**Comment by neovea** [comment]
Thanks @mandaputtra i’ll give it a shot
