### ISSUE TITLE
Please add lang#flutter

### ISSUE THREAD

**Issue by shivahnshankar** [wsdjeg/SpaceVim#3543]
I see that there is a lang#dart layer. However there is no lang#flutter layer yet. Is this WIP?
I tried coc.nvim with the coc-flutter extension and it seems to be working great. Hopefully it should be easy to to integrate this in SpaceVim.

**Comment by wsdjeg** [comment]
flutter is a language?

**Comment by shivahnshankar** [comment]
Well Flutter is more like a framework for creating apps using Dart as the backend language. However, lang#dart wouldn't work since there are Flutter components (widgets) that are not provided entirely by the Dart lang server. Plus coc-flutter provides additional commands like "flutter run",  hot reload, start an emulator etc that are indispensable for flutter development.

**Comment by wsdjeg** [comment]
No, we can not add this kind of layer, because one language maybe have more them one framework. all of these should be included in `lang#dart` layer. Maybe this issue should be a feature request for flutter support in `lang#dart` layer.

**Comment by shivahnshankar** [comment]
i understand. However, in emacs/spacemacs, i believe they have "additional packages" for flutter on top of dart lsp.
[https://github.com/emacs-lsp/lsp-dart#additional-packages](https://github.com/emacs-lsp/lsp-dart#additional-packages).
in doom emacs init.el, configuration is as follows:
(dart +flutter +lsp)
WIll open a new feature request under lang#dart
