### ISSUE TITLE
how to disable vimfiler at startup?

### ISSUE THREAD

**Issue by alvinseptiano** [wsdjeg/SpaceVim#3545]

**Comment by spazmantiz** [comment]
Give me reason why u ckoaed thia

**Comment by alvinseptiano** [comment]
Give reason why you closed this

**Comment by wsdjeg** [comment]
Github issue is for bug report and feature request, not for ask question which has been documentted in doc. Please use gitter.im/SpaceVim/SpaceVim instead. and checkout spacevim.org/community/ for more info.
--------------
wsdjeg
