### ISSUE TITLE
Theme does not load when launching vim in tmux - No More #43

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#355]
## Expected behavior
Vim's colorscheme isn't loaded correctly when in `tmux`.

I've tried #43 
Unfortunately, It doesn't work for me.

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)
I don't know whether you can reproduce because as I know some people DO solve their problems by something like this below:
`env TERM=xterm-256color tmux -2`
`env TERM=screen-256color tmux -2`
`tmux -2;vim`

Nothing works for me. I don't know why.

I've also changed my colorscheme too, however it still doesn't work for me.

I don't know what should I do right now.

## init.vim
```viml
let g:spacevim_colorscheme  =   'molokai'
let g:spacevim_max_column   =   80
let g:spacevim_error_symbol =   '✗'
let g:spacevim_buffer_index_type = 4
let g:spacevim_enable_guicolors = 0
"let g:spacevim_custom_plugins=[
"            \ ['SpaceVim/vim-luacomplete'],
"            \
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#markdown')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('tmux')
nnoremap <leader>svf :source ~/.SpaceVim.d/init.vim<cr>
au BufNewFile,BufRead *.styl set ft=css
```

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.2.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'molokai'
g:spacevim_enable_guicolors = 0
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 4
g:spacevim_hiddenfileinfo = 1
g:spacevim_error_symbol = '✗'
g:spacevim_vim_plug_installed = 0
g:spacevim_max_column = 80
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF
,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_debug = 0
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'f
ormat', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang
#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'unite',
'github', 'denite', 'ctrlp', 'autocomplete', 'vim', 'linux', 'lang#lua', 'lang#x
ml', 'lang#c', 'lang#javascript', 'tmux', 'colorscheme']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/gabriel/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/h
osts'     
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 0
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
```

**Comment by wsdjeg** [comment]
@Gabirel remove `let g:spacevim_enable_guicolors = 0`, will fix it.

**Comment by wsdjeg** [comment]
https://asciinema.org/a/aode0v9wdvlogqgq2nqrip5i0

if you remove `let g:spacevim_enable_guicolors = 0`

you will see 

https://asciinema.org/a/89sm6hx3yvwy68igwc4jv5xc7

**Comment by Gabirel** [comment]
No, it fails again.

Here's the [demo](https://asciinema.org/a/a0coo9nmfosir0jhcpj3sbkis)

**Comment by wsdjeg** [comment]
can you have a try with termite? and does your terminal support true colors?

**Comment by Gabirel** [comment]
how can I know whether my terminal support true colors? 
My terminal is `xfce4-terminal`

No, I don't want to try any other new terminals.

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/DotFiles/blob/master/scripts/test_24bit.sh

**Comment by Gabirel** [comment]
![image](https://cloud.githubusercontent.com/assets/12933851/24331298/f15062f2-1263-11e7-958f-20cd03bb77dc.png)

**Comment by wsdjeg** [comment]
It is too strange, I need to look into it.

**Comment by Gabirel** [comment]
What? Strange? why ? It looks so colorful

**Comment by wsdjeg** [comment]
I means this issue is too strange, your teminal should works well with true color, but why it can not works well in tmux, and I am so sorry, I do not use tmux, I use neovim for split terminals.

**Comment by wsdjeg** [comment]
![2017-03-26-23 23 21](https://cloud.githubusercontent.com/assets/13142418/24332583/8dfb1248-127b-11e7-93c8-da60e9b480d3.png)

**Comment by wsdjeg** [comment]
after enable true colors
![2017-03-26-23 39 21](https://cloud.githubusercontent.com/assets/13142418/24332692/d0fd1328-127d-11e7-8c39-d1c6613e00a5.png)

**Comment by Gabirel** [comment]
results in tmux:
![image](https://cloud.githubusercontent.com/assets/12933851/24332708/2b45751e-127e-11e7-9ac5-a40c4a6d5ef7.png)

**Comment by jetm** [comment]
Hi @Gabirel and @wsdjeg: I have this similar issue with SpaceVim using Arch Linux + konsole/xfce4-terminal + tmux. I could fixed with the follow settings:

~/.tmux.conf:
\# Add truecolor support
\# Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc"

~/.SpaceVim.d/init.vim:
" Fix colorscheme for tmux + vim
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

**Comment by Gabirel** [comment]
@jetm 

I got these. What are these?
https://asciinema.org/a/el8j9nwob89vabxq14s06l5qc

**Comment by jetm** [comment]
@Gabirel:
That is something different for what I got. I would recheck your configuration and start over with a clean configuration file.  
My whole SpaceVim config: http://pastebin.com/Am7RQJZe. And for TrueColor the settings above makes the difference for me. I am using zsh as shell.

**Comment by Gabirel** [comment]
@jetm Thanks for telling us.
Now SpaceVim has already fixed this issue in https://github.com/SpaceVim/SpaceVim/commit/360cc4f25d48c73113e7c761edcabade59278185

these below are no longer needed.
```viml
" Fix colorscheme for tmux + vim
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```
