### ISSUE TITLE
真是够够的，不吐不快

### ISSUE THREAD

**Issue by kdurant** [wsdjeg/SpaceVim#3551]
你有什么理由非要解散vim的qq群？强制让大家使用其他通信工具，这符合开源软件的精神吗？

你有什么资格去解散vim群？这个群以前就因为某种原因被解散过，后来经过大家努力，又重新恢复了。别人把群主让给你了，你就可以随意解散？

你又为什么言而无信？明明在群里看到说不解散了，为什么又说话不算话？

**Comment by wsdjeg** [comment]
请问这个跟 SpaceVim 有什么关系，为什么需要在这里开 issue？并且，关于解散，群里已经有讨论过原因，同时目前大多数人已经转移到 Telegram 了。

开源软件的精神，不是让你随意在无关的项目下面，使用中文询问完全不相干的事情。
