### ISSUE TITLE
Install latest version of SpaceVim offline

### ISSUE THREAD

**Issue by suliveevil** [wsdjeg/SpaceVim#3554]
## why offline?

I'm using iVim on iPadOS , it has python and lua environment , but git is not included.
If there is a way to install **latest version** of SpaceVim offline for iVim , it will be great for iPadOS users like me.

## why open this issue?

Hack-SpaceVim is stalled for a while, so I have to report this feature request here.

**Comment by wsdjeg** [comment]
we are going to provide a all-in-one version of spacevim. but it is still WIP.

please checkout https://github.com/SpaceVim/SpaceVim/pull/3542
--------------
wsdjeg

**Comment by Gabirel** [comment]
@suliveevil Give it a try for bundled version of SpaceVim.  It should support your request (with limited functionality but enough for your daily usage).

It still works to install SpaceVim offline in an old-fashion way stated in Hack-SapceVim. But maybe you may encounter different issues when compiling something on your iPadOS.

**Comment by suliveevil** [comment]
I will try that.

iVim have greenlet integrated which is required by pynvim.
pynvim is required by dein.

**Comment by suliveevil** [comment]
It didn't work, I got a dark screen without anything show up.
I will back to my own config.

**Comment by wsdjeg** [comment]
> I got a dark screen without anything show up

when first time run spacevim, vimfiler will download dll file from it's release page. please wait for it.
