### ISSUE TITLE
TOO MANY BUGS FOR ME

### ISSUE THREAD

**Issue by Corgile** [wsdjeg/SpaceVim#3562]
Terminal：Git Bash
OS：Windows10 1909

<center><h1>Configs</h1></center>

> summary

doing `source vimrc` cmd gets errors
The vimrc file : https://paste.ubuntu.com/p/J2v5bVM4vP/

> details

when i finished modifying the vimrc file and then did `source ~/.vim/vimrc`：

![image](https://user-images.githubusercontent.com/48396880/83341959-dfa81300-a31b-11ea-8904-a96df6c07fd2.png)

after i press enter, its theme changed from gruvbox to this ：

![image](https://user-images.githubusercontent.com/48396880/83341974-0c5c2a80-a31c-11ea-917b-229d010b1fdb.png)

Then i tried to source vimrc outside：

![image](https://user-images.githubusercontent.com/48396880/83342083-90fb7880-a31d-11ea-9d59-1cf7a9ea5f55.png)

---

<h1><center>Language support</center></h1>

> summary

whatever c/c++ , java or python , `SPC l r ` does not work at all and gets the same problem; 
all code edit areas are placed with the running window(Buffer), 
don't know how to close the running windows
The toml file: https://paste.ubuntu.com/p/W4Dgfyr7XS/

> details

## Python

i'm sure i got packages and environment installed correctly

![image](https://user-images.githubusercontent.com/48396880/83342259-d9b43100-a31f-11ea-84df-28aba41539d5.png)

- run a hello world.py

![image](https://user-images.githubusercontent.com/48396880/83342695-e6875380-a324-11ea-9a98-275a644af756.png)

The code area is replaced with the running window, (not knowing how to close the running windows, ) I then execute the cmd `:q ` to close the current window but it returned to the bash line.

![image](https://user-images.githubusercontent.com/48396880/83343129-f6089b80-a328-11ea-9e86-46ed8543b62a.png)

(As you can see, running vim also gets such errors)

## c/c++

this is a hello world C program, doing SPC l r

![image](https://user-images.githubusercontent.com/48396880/83343155-32d49280-a329-11ea-8b6d-83381c17f8b3.png)

## Java

-  select file and press enter

![image](https://user-images.githubusercontent.com/48396880/83342635-43363e80-a324-11ea-8d2f-cd6f2033ce27.png)

- running hello.java gets the same errors as running py, all windows replaced, 

Looking forward some helpful replies  THANKS

**Comment by wsdjeg** [comment]
> when i finished modifying the vimrc file and then did source ~/.vim/vimrc

please follow the quick start guide to install spacevim!!.

> `SPC l r` is to try to run `env python -`, make sure env is in your path, and you can add `#!/usr/bin/python3`  to use python3
