### ISSUE TITLE
Proposal for vim-coc installation

### ISSUE THREAD

**Issue by chocopowwwa** [wsdjeg/SpaceVim#3565]
**Is your feature request related to a problem? Please describe.**
*feature request*: Recently https://github.com/SpaceVim/SpaceVim/commit/f0d4ab2f6f9b7fd9bd61b4be21fadb560b74e1fa has been commited to master and I aware that you prefer using yarn install the binary is executable, I think it is wise to do that, vim-coc also recommend using the release branch instead of building it from source.

**Describe the solution you'd like**
I think a better solution is to provide an option in autocomplete layer so use can specify which the branch they she/he want, I personally prefer to use `release` branch intend of master branch+doing a bunch of npm install

**Describe alternatives you've considered**

**Additional context**

**Comment by wsdjeg** [comment]
The default branch of coc is release now, so this can be closed.
