### ISSUE TITLE
Error detected while processing function <SNR>237_JobVimOnErrorHandler[3]..javacomplete#classpath#gradle#BuildClasspathHandler[49]..<SNR>237_JobVimOnErrorHandler[3]..javacomplete#classpath#gradle#BuildClasspathHandler:  

### ISSUE THREAD

**Issue by gianlucanotaro** [wsdjeg/SpaceVim#3566]
This happens every time I open a java file for the first time after starting space vim.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/24224668/83569811-5d8b3a80-a525-11ea-8434-6788329343bb.png">

the only configs I made in the config file are the two code blocks from the tutorial here: [https://spacevim.org/use-vim-as-a-java-ide/](url)

I have access to the java functions with leader l but when I try to use any of them nothing happens at all. 

Version is current version and all plugins are up to date

**Comment by ghost** [comment]
I disabled javacomplete2 in init.toml. Deoplete handles completion just fine.

**Comment by wsdjeg** [comment]
This is because your java project is failed to build. you can try to build it in command line.
