### ISSUE TITLE
Requirements Documentation is needed

### ISSUE THREAD

**Issue by suliveevil** [wsdjeg/SpaceVim#3567]
Would you please add a ```requirements``` list in Documentation?
AFAK, dein requires Git.

I want something like this

```markdown

## Operating System

Windows      - Vim、GVim
macOS         - Vim、MacVim
iOS/iPadOS  - Vim、iVim

## Language 

Lua（not necessary）
Python （not necessary）

## Softwares

Git （plugin necessary）
Bash/Zsh （plugin necessary）


## Minimal Install

Vim version 7.x.xxxx (Huge)
with feature:
popupmenu
…
```

**Comment by wsdjeg** [comment]
please read https://spacevim.org/quick-start-guide/

**Comment by suliveevil** [comment]
Git and curl is just not enough to use full power of SpaceVim.
At least, dein need pynvim, that means SpaceVim requires `python` and  python modules: `pynvim` `greenlet` `msgpack`  .
