### ISSUE TITLE
Ctags install instructions for mac are out of date

### ISSUE THREAD

**Issue by patrickshobe** [wsdjeg/SpaceVim#3568]
## Expected behavior, english is required
brew to install correctly
## The reproduce ways from Vim starting (Required!)
Run `brew install global --with-pygments --with-ctags`
## Debug info
Command fails with `Error: invalid option: --with-pygments`
Homebrew Version: `2.3.0`
MacOS Version: `10.15.5`

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@patrickshobe Thanks PR is welcome, I do not use Mac os.
