### ISSUE TITLE
jump/change list transient state

### ISSUE THREAD

**Issue by circld** [wsdjeg/SpaceVim#3569]
**Describe the solution you'd like**
A feature improvement that I, and I hope others, would find useful would be a transient state for jump and change lists.

**Describe alternatives you've considered**
To be clear, the existing functionality for jumping already exists. The existing jump forward/backwards (`[SPC]-j-f/b`) key mappings are quite useful, but they can be a bit cumbersome to jump repeatedly. Jumping to change locations (`g;`, `g,`) is likewise unwieldy.

**Additional context**
I did my best to implement something that captures the functionality I'd like, though I recognize that the way I worked around the re-mapping of `<tab>` is far from ideal (but perhaps a non-issue if this is defined directly in `layers/core.vim`?):

```
" defined in custom_config#before function

" workaround to access jump forward since tab remapped by SpaceVim
nnoremap <f5> <c-i>

function! Jump_transient_state() abort
  let state = SpaceVim#api#import('transient_state')
  call state.set_title('Jump Transient State')
  call state.defind_keys(
        \ {
        \ 'layout' : 'vertical split',
        \ 'left' : [
        \ {
        \ 'key' : 'j',
        \ 'desc' : 'next jump',
        \ 'func' : '',
        \ 'cmd' : 'try | exe "norm \<f5>"| catch | endtry ',
        \ 'exit' : 0,
        \ },
        \ {
        \ 'key' : 'J',
        \ 'desc' : 'previous jump',
        \ 'func' : '',
        \ 'cmd' : 'try | exe "norm \<c-o>" | catch | endtry',
        \ 'exit' : 0,
        \ },
        \ ],
        \ 'right' : [
        \ {
        \ 'key' : 'c',
        \ 'desc' : 'next change',
        \ 'func' : '',
        \ 'cmd' : "try | exe 'norm g,' | catch | endtry",
        \ 'exit' : 0,
        \ },
        \ {
        \ 'key' : 'C',
        \ 'desc' : 'previous change',
        \ 'func' : '',
        \ 'cmd' : "try | exe 'norm g;' | catch | endtry",
        \ 'exit' : 0,
        \ },
        \ {
        \ 'key' : 'q',
        \ 'desc' : 'quit',
        \ 'func' : '',
        \ 'cmd' : '',
        \ 'exit' : 1,
        \ },
        \ ],
        \ }
        \ )
  call state.open()
endfunction

call SpaceVim#custom#SPC('nore', ['j', '.'], 'call Jump_transient_state()', 'jump-transient-state', 1)
```

Thanks again for the wonderful work on this `vim` distribution-- it is a joy to use!

**Comment by wsdjeg** [comment]
@circld Thanks, can you send a pull request. I think this feature is useful too.

**Comment by wsdjeg** [comment]
This feature has been added, please update spacevim.
