### ISSUE TITLE
Autocomplete failure in almost every file

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#357]
## Expected behavior
`#include <vector>` auto-completion is expected.

I thought it popped up for me, which means I can use `tab` to complete code.
However it doesn't.

Hope that figure 1 becomes figure 2.

Figure 1:
![image](https://cloud.githubusercontent.com/assets/12933851/24309473/ddd2412c-1106-11e7-89a2-beda5efe1b84.png)

Figure 2:
![image](https://cloud.githubusercontent.com/assets/12933851/24309566/4cb2b982-1107-11e7-9c67-e42f91a95f4e.png)

It also fails not just on `vector`, but also on `iostream`(very basic header)

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)
1. `vim test.cpp`, and code like this below:
![image](https://cloud.githubusercontent.com/assets/12933851/24309496/f8b7048c-1106-11e7-891d-53285d7a6432.png)

2. press `Tab`, and you should get this:
![image](https://cloud.githubusercontent.com/assets/12933851/24309507/0c0dac0c-1107-11e7-85c8-4e22c911de46.png)

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
Nothing special here, I guess

**Comment by wsdjeg** [comment]
https://asciinema.org/a/55a3w26g6mdgf51f0tqxst7ll

I can reprodue it, I will fix it.

**Comment by Gabirel** [comment]
Same problems when editing nodejs script.

**Comment by Gabirel** [comment]
It happens in javascript too. This is significantly slowing down or even starting to piss me off.

https://asciinema.org/a/dqho4bgks54tzjwcrshg6mtk0

**Comment by wsdjeg** [comment]
please check #387 , I am working on it. but it is not finished.

**Comment by Gabirel** [comment]
Also, errors in every file
I think these are related with your changes in SpaceVim too.
```log
Messages maintainer: Bram Moolenaar <Bram@vim.org>
[dein] Error occurred while executing hook: neocomplete
[dein] Vim(let):E121: Undefined variable: g:neocomplete#keyword_pattern

Press ENTER or type command to continue
```

**Comment by wsdjeg** [comment]
which branch do you test, and how do you get this issue?

**Comment by Gabirel** [comment]
Ohhhh, it seems that you don't know these errors. Need I start a new issue to let you fix this?

branch: `dev`
And latest code

**Comment by wsdjeg** [comment]
you can create a new issue about it.
