### ISSUE TITLE
C++: a whole bunch of RED errors(horrible) after pressing `tab` with `mainn`

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#358]
## Expected behavior
No HORRIBLE RED errors any more. That's all.

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)
1. code these:
![image](https://cloud.githubusercontent.com/assets/12933851/24310224/0987fb06-110a-11e7-850d-104d6380d24f.png)

2. Results:
![image](https://cloud.githubusercontent.com/assets/12933851/24310303/5e944a5a-110a-11e7-924f-39379935d7b7.png)

3. You still get what you want, but with errors.
![image](https://cloud.githubusercontent.com/assets/12933851/24310310/64e8cbc4-110a-11e7-80d5-915aa03a7e10.png)

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
```log
Messages maintainer: Bram Moolenaar <Bram@vim.org>
--No lines in buffer--
Error detected while processing function <SNR>211_snippets_expand_or_jump[1]..<S
NR>211_snippets_expand[15]..neosnippet#view#_expand[20]..neosnippet#view#_insert
[72]..neosnippet#view#_jump[31]..neosnippet#view#_search_snippet_range[2]..<SNR>
269_substitute_placeholder_marker:
line   29:
E486: Pattern not found: \m<|1|>
Error detected while processing function <SNR>211_snippets_expand_or_jump[1]..<S
NR>211_snippets_expand:
line   15:
E171: Missing :endif
Error detected while processing function <SNR>211_snippets_expand_or_jump:
line    1:
E171: Missing :endif
Error detected while processing function <SNR>211_snippets_expand_or_jump[1]..<S
NR>211_snippets_expand[15]..neosnippet#view#_expand[20]..neosnippet#view#_insert
[72]..neosnippet#view#_jump[31]..neosnippet#view#_search_snippet_range[2]..<SNR>
269_substitute_placeholder_marker:
line   29:
E486: Pattern not found: \m<|1|>
Error detected while processing function <SNR>211_snippets_expand_or_jump[1]..<S
NR>211_snippets_expand:
line   15:
E171: Missing :endif
```

## init.vim
```viml
let g:spacevim_colorscheme  =   'molokai'
let g:spacevim_max_column   =   80
let g:spacevim_error_symbol =   '✗'
let g:spacevim_buffer_index_type = 4
let g:spacevim_enable_guicolors = 0
"let g:spacevim_custom_plugins=[
"            \ ['SpaceVim/vim-luacomplete'],
"            \
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#lua')
call SpaceVim#layers#load('lang#markdown')
call SpaceVim#layers#load('lang#xml')
call SpaceVim#layers#load('tmux')
nnoremap <leader>svf :source ~/.SpaceVim.d/init.vim<cr>
au BufNewFile,BufRead *.swig set ft=html
au BufNewFile,BufRead *.styl set ft=css
```

**Comment by Gabirel** [comment]
@wsdjeg 
I'm sorry. I don't know why I can't reproduce again. But one thing I can ensure you that those bunch of red errors shows many times(more than 5 times)

`SpaceVim` performs very badly and I am feeling very uncomfortable with it when editing with C++.

For example:
1. 
![image](https://cloud.githubusercontent.com/assets/12933851/24310797/45abd15a-110c-11e7-842b-ff915bb23c94.png)

2. just click button `delete`
![image](https://cloud.githubusercontent.com/assets/12933851/24310919/be814a74-110c-11e7-9686-63ec72061bcc.png)


3. you shall see this:
![image](https://cloud.githubusercontent.com/assets/12933851/24310838/6438b994-110c-11e7-9f5d-caf3f292e642.png)

Why?? I hate this

**Comment by wsdjeg** [comment]
it is feature of vim, vim use  
```
<`1:s`>
``` 


to mark jumplist. and this how neosnippet works.

after type `mon;` no need type delete, just `tab` again, you will jump to second argv.

**Comment by wsdjeg** [comment]
and if you do not delete `<`, this mark will be hidden, then if you delete `<`, the left part can not be hidde,

**Comment by wsdjeg** [comment]
https://asciinema.org/a/18x5h49fpcy05mhnuup1lisyu

here is a video

**Comment by Gabirel** [comment]
Fine, I don't like it though.

What about those red errors mentioned before?

**Comment by wsdjeg** [comment]
I have tried too many times, and I can not get the red errors.

**Comment by Gabirel** [comment]
Fine, I thought you could fix them according to those red errors.

I am gonna close it

**Comment by wsdjeg** [comment]
the red error is because <is deleted. and can not find jump position. so please do not use delete when eapand argv or snippet.
