### ISSUE TITLE
Updating Plugins Fails

### ISSUE THREAD

**Issue by PeterDing** [wsdjeg/SpaceVim#3585]
## Expected behavior, english is required
It is `Fri Jun 19 12:11:16 CST 2020`. I update plugins with `:SPUpdate`, but it fails and obstructs without response.
I delete all relative files of `SpaceVim` except `~/.cache/SpaceVim` and then reinstall `SpaceVim`, but I get same issue as above updating.
I also try to install `SpaceVim` at a new linux server, but the issue repeats.

<img width="520" alt="Screen Shot 2020-06-19 at 12 21 10 PM" src="https://user-images.githubusercontent.com/670690/85096613-69fedb00-b227-11ea-8200-89018b88043e.png">

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by ksamborski** [comment]
I think the problem is missing `bundle/clever-f.vim` in the repository. Because of that I can't install or update any plugins. But if I clone clever-f repo into `bundle/clever-f.vim` it works again.

**Comment by ChasingZenith** [comment]
I think that you can have a look at 
https://github.com/SpaceVim/SpaceVim/issues/3577#issuecomment-646491749

But I think this issue have not been solved. Every time I run
```
:SPUpdte
```
I will get the same issue again.

**Comment by crisidev** [comment]
Same here.. The issue is that when you run :SPUpdate, the .Spacevim git get corrupted and a bunch of files are just deleted..

**Comment by crisidev** [comment]
Before SPUpdate:

```
❯❯❯ ~/.SpaceVim git status                                                                                                              
On branch master
Your branch is up to date with 'origin/master'.
```

After SPUpdate:

```
❯❯❯ ~/.SpaceVim git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    bundle/context_filetype.vim/LICENSE
	deleted:    bundle/context_filetype.vim/autoload/context_filetype.vim
	deleted:    bundle/context_filetype.vim/doc/context_filetype.jax
	deleted:    bundle/context_filetype.vim/doc/context_filetype.txt
	deleted:    bundle/context_filetype.vim/test/test.vim
	deleted:    bundle/context_filetype.vim/test/test_files/test.html
	deleted:    bundle/context_filetype.vim/test/test_files/test.md
	deleted:    bundle/context_filetype.vim/test/test_files/test.ny
	deleted:    bundle/context_filetype.vim/test/test_files/test.vim
	deleted:    bundle/defx-git/LICENSE
	deleted:    bundle/defx-git/README.md
	deleted:    bundle/defx-git/ftplugin/defx.vim
	deleted:    bundle/defx-git/rplugin/python3/defx/column/git.py
	deleted:    bundle/defx-icons/LICENSE
	deleted:    bundle/defx-icons/README.md
	deleted:    bundle/defx-icons/plugin/defx_icons.vim
	deleted:    bundle/defx-icons/rplugin/python3/defx/column/icons.py
	deleted:    bundle/defx.nvim/.github/ISSUE_TEMPLATE.md
	deleted:    bundle/defx.nvim/.gitignore
	deleted:    bundle/defx.nvim/.travis.yml
	deleted:    bundle/defx.nvim/LICENSE
	deleted:    bundle/defx.nvim/Makefile
	deleted:    bundle/defx.nvim/README.md
	deleted:    bundle/defx.nvim/autoload/defx.vim
	deleted:    bundle/defx.nvim/autoload/defx/custom.vim
	deleted:    bundle/defx.nvim/autoload/defx/exrename.vim
	deleted:    bundle/defx.nvim/autoload/defx/init.vim
	deleted:    bundle/defx.nvim/autoload/defx/util.vim
	deleted:    bundle/defx.nvim/autoload/health/defx.vim
	deleted:    bundle/defx.nvim/doc/defx.txt
	deleted:    bundle/defx.nvim/plugin/defx.vim
	deleted:    bundle/defx.nvim/rplugin/python3/defx/__init__.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/action.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/base/__init__.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/base/column.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/base/kind.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/base/source.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/clipboard.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/__init__.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/filename.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/icon.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/indent.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/mark.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/size.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/space.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/time.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/column/type.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/context.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/defx.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/kind/__init__.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/kind/file.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/rplugin.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/session.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/sort.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/source/__init__.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/source/file.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/util.py
	deleted:    bundle/defx.nvim/rplugin/python3/defx/view.py
	deleted:    bundle/defx.nvim/rplugin/python3/denite/source/defx/__init__.py
	deleted:    bundle/defx.nvim/rplugin/python3/denite/source/defx/drive.py
	deleted:    bundle/defx.nvim/rplugin/python3/denite/source/defx/history.py
	deleted:    bundle/defx.nvim/rplugin/python3/denite/source/defx/session.py
	deleted:    bundle/defx.nvim/test/autoload/defx/custom.vim
	deleted:    bundle/defx.nvim/test/conftest.py
	deleted:    bundle/defx.nvim/test/requirements.txt
	deleted:    bundle/defx.nvim/test/rplugin/python3/defx/test_defx.py
	deleted:    bundle/delimitMate/.gitignore
	deleted:    bundle/delimitMate/Makefile
	deleted:    bundle/delimitMate/README.md
	deleted:    bundle/delimitMate/autoload/delimitMate.vim
	deleted:    bundle/delimitMate/basic_vimrc
	deleted:    bundle/delimitMate/doc/delimitMate.txt
	deleted:    bundle/delimitMate/plugin/delimitMate.vim
	deleted:    bundle/delimitMate/test/Makefile
	deleted:    bundle/delimitMate/test/README.md
	deleted:    bundle/delimitMate/test/_setup.vim
	deleted:    bundle/delimitMate/test/autoclose_matchpairs.txt
	deleted:    bundle/delimitMate/test/autoclose_matchpairs.vim
	deleted:    bundle/delimitMate/test/autoclose_quotes.txt
	deleted:    bundle/delimitMate/test/autoclose_quotes.vim
	deleted:    bundle/delimitMate/test/eol_marker.vim
	deleted:    bundle/delimitMate/test/expand_cr.txt
	deleted:    bundle/delimitMate/test/expand_cr.vim
	deleted:    bundle/delimitMate/test/expand_space.txt
	deleted:    bundle/delimitMate/test/expand_space.vim
	deleted:    bundle/delimitMate/test/first_buffer_no_ft.vim
```

**Comment by robertwt7** [comment]
This is the same with #3577 , probably you can revert back to 1.4

**Comment by SlyBouhafs** [comment]
I am having the same issue here, every time i open Spacevim or run :SPUpdate, it returns the skip local status and gets stuck there.

![Capture d’écran 2020-06-21 à 3 12 48 PM](https://user-images.githubusercontent.com/1410462/85226903-cb62ad80-b3d1-11ea-9947-01f2b7cfc909.png)

**Comment by crisidev** [comment]
@wsdjeg Is there any update on this? Would you recommend to switch back to 1.4?

**Comment by ProgramFan** [comment]
I can confirm the same issue.

**Comment by rahuldhir** [comment]
Having the same issue. Temporarily solved by `cd ~/.vim/bundle && git checkout v1.4.0`

**Comment by Shougo** [comment]
The broken commit is https://github.com/SpaceVim/SpaceVim/commit/aebee1b28b26654a1a667a53bece387ab4d2ec1a.

Because https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/plugins/manager.vim#L243 removes local bundle dir.
It is SpaceVim updater's problem.
I think it should check `local` attribute.

@wsdjeg Ping.

**Comment by Shougo** [comment]
I recommend for SpaceVim users to use older version of SpaceVim until the issue is fixed.

**Comment by bestouff** [comment]
** for people with broken installation after `SPUpdate` ** here's a command that worked for me:
```console
# cd ~/.SpaceVim
# git reset --hard
```

**Comment by yeongsheng-tan** [comment]
> ** for people with broken installation after `SPUpdate` ** here's a command that worked for me:
> 
> ```
> # cd ~/.SpaceVim
> # git reset --hard
> ```

I attest the following works:
```
cd ~/.SpaceVim && git reset --hard origin/master
git checkout v1.4.0
```
However, thereafter, most plugins update works via `:SPUpdate`, except, it ends with:
`[ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 1` 
`x SpaceVim: Updating failed,  The plugin dir is dirty`

**Comment by wsdjeg** [comment]
@Shougo Thanks, in SpaceVim/bundle dir, all of this directory is not git repo, so all of this plugin can not be updated, these plugin will be skiped when run `:SPUpdate` command. It is not git sub repo. Same as #3577

**Comment by Shougo** [comment]
Yes.  But the bundled(local) directories are removed when updating.
This is feature of SpaceVim?  Really?

**Comment by Shougo** [comment]
The remove is intended feature?
https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/plugins/manager.vim#L243

The install is skipped in SPUpdate.  But `delete()` is not skipped.  It seems danger behavior.

**Comment by crisidev** [comment]
It is clearly a regression since 1.4 works fine and allows plugin to update and does not mess up with the bundle directory..

**Comment by wsdjeg** [comment]
This seems a bug of SpaceVim plugin manager. I will check it.
