### ISSUE TITLE
How to clear files of unused plugins?

### ISSUE THREAD

**Issue by Aquaakuma** [wsdjeg/SpaceVim#3588]
After I deleted the configure of custom plugins, The files related to the plugins still exist  in ~/.cache/repo/......./, Can you add a script to SpaceVim? eg. SPClean, Easy to clean up unused plugins.

**Comment by SlyBouhafs** [comment]
It is actually [dein.vim](https://github.com/Shougo/dein.vim) under the hood. You can see the unused plugins via `dein#check_clean()` and you can remove the unused plugins either by deleting their repos or doing like it is said in the documentation : 

```	
call map(dein#check_clean(), "delete(v:val, 'rf')")
call dein#recache_runtimepath()
```
+1 for making it a feature.
