### ISSUE TITLE
Flygrep

### ISSUE THREAD

**Issue by gj1118** [wsdjeg/SpaceVim#3596]
## Expected behavior, english is required
When I grep with FlyGrep , and the search results are displayed, the selected file should be opened when I press "Enter"

## The reproduce ways from Vim starting 

1. Open a folder in Neovim. I use `nvim .`
2. In nvim , enter `:FlyGrep`
3. The flygrep panel opens 
4. Enter the search term
5. now from the list select any other file other than the first file. 
6. Notice that the selected file does not open.

I am using `MacOS 10.14.6`. I am using `ITerm 3.3.11` and the following NeoVim version 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"
```

## Debug info
I dont know how to get debug info from FlyGrep. Please note that I am using FlyGrep independently of SpaceVim.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
what huppend when you press `Enter`? how did you select the item?

**Comment by gj1118** [comment]
Please see the attached video for more information. there are a couple of errors that also come up while I am grepping which is why I prepared this demo. Please let me know if you need any other information. 
https://www.youtube.com/watch?v=GwKedeKK9Ng

Thanks

**Comment by gj1118** [comment]
Hi, my sincere apologies for the spam, but can you please let me know which this could be happening please ? If you think I have not provided the complete information, please let me know what else you would need from me and I will provide it as soon as I can.

Thanks

**Comment by wsdjeg** [comment]
sorry, I can not reproduce it,
