### ISSUE TITLE
Error: Not an editor command: IndentLinesToggle

### ISSUE THREAD

**Issue by xcoderzach** [wsdjeg/SpaceVim#36]
Once installed, I get the following error twice every time I enter insert mode.

`E492: Not an editor command:         IndentLinesToggle`

**Comment by felipebueno** [comment]
Same here.

I did run the ```call dein#install()``` function and it went ok until it tried to compile a plugin (don't know which one yet). The last command called by dein was ```make -f make_unix.mak``` and then my terminal window froze.

![spacevim](https://cloud.githubusercontent.com/assets/241271/21658148/873afd2e-d2ac-11e6-9a7a-6faefd3ac3e5.png)

**Comment by EwanValentine** [comment]
call dein:install() should be call dein#install() I think!

**Comment by felipebueno** [comment]
Oh, right, that was just a typo here... I called it with ```#``` on neovim :smile:

**Comment by wsdjeg** [comment]
see #20
