### ISSUE TITLE
changed cursor style, quit not recovered.

### ISSUE THREAD

**Issue by gatspy** [wsdjeg/SpaceVim#360]
## Expected behavior
iterm the cursor use underline and blinking.
when use nvim edit file,the cursor changed to box,then quit, the cursor also box.

## Environment Information
- OS: os x 10.11
- vim version:
- neovim version:0.1.7

**Comment by wsdjeg** [comment]
it is issue of neovim, can you have a try with neovim 0.2.0-dev, the master branch of neovim.

**Comment by wsdjeg** [comment]
if your neovim is too old , please use `let g:spacevim_terminal_cursor_shape = 0` to disable this feature.
