### ISSUE TITLE
Allow using prettier for formatting Markdown on Linux

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#3600]
**Is your feature request related to a problem? Please describe.**
Currently, prettier formatting with Neoformat for Markdown is only enabled on Windows.

**Describe the solution you'd like**
Fallback to using prettier if remark isn't installed or add a config option to choose.

**Describe alternatives you've considered**
Currently I run prettier manually.

**Additional context**

**Comment by wsdjeg** [comment]
closed in #3677
