### ISSUE TITLE
[Question] - how to change Markdown layer syntax highlighting?

### ISSUE THREAD

**Issue by Datamance** [wsdjeg/SpaceVim#3602]
I'd like to be able to change the coloring and styling for different text elements in Markdown - for instance, differentiating the header colors so that they're not all bolded and blue.

How might one go about this?

**Comment by wsdjeg** [comment]
This is general vim script question, and you can read `:h :hi`. To change the head of markdown file, you need to add extra vim script in bootstrap function. the higroup is `markdownH1`  to `markdownH6`
