### ISSUE TITLE
Create terminalfont variable to set font

### ISSUE THREAD

**Issue by redeemefy** [wsdjeg/SpaceVim#3604]
**Is your feature request related to a problem? Please describe.**
I open the `:h SpaceVim-config` looking the option to change the font in terminal vim since setting the `guifont` has no effect in vim terminal

**Describe the solution you'd like**
```
[options]
    guifont = 'Operator Mono Hack Nerd Font:h16'
```
☝️ has no effect in terminal vim.

**Describe alternatives you've considered**
`:h SpaceVim-config` looking for a variable to set font in terminal vim.

**Additional context**
Mac 10.15.4
SapceVim 1.5.0
NVIM 0.4.3

**Comment by wsdjeg** [comment]
Terminal font can only be set in terminal's config pannel. It can not be done in vim. So this feature can not be implemented. sorry!
