### ISSUE TITLE
Can't override default mappings

### ISSUE THREAD

**Issue by TiuSh** [wsdjeg/SpaceVim#361]
## Expected behavior, english is recommend

Mappings defined in `~/.Spacevim.d/init.vim` should override default SpaceVim mappings.

## Environment Information
- OS: macOS Sierra 10.12.3
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)

1. Open an empty buffer
2. Press `Ctrl + L`
3. The message `Hello World` doesn't appear in command line (as it should)

## ~./Spacevim.d/init.vim

```
nmap <C-l> :echo "Hello World"<cr>
```

**Comment by wsdjeg** [comment]
Fixed, thanks for report bugs, and I think it is better to use `nnoremap` instead of `nmap`.

**Comment by TiuSh** [comment]
Thanks ! 👍
