### ISSUE TITLE
Add custom <Leader> key mapping with descriptions

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#3611]
### Description
**Is your feature request related to a problem? Please describe.**

I can add custom key mapping with `SPC` via the API:  https://github.com/SpaceVim/SpaceVim/blob/bed0d306ff53c9faaa9adb3f0332c9f59a2978e3/autoload/SpaceVim/custom.vim#L78-L80

But I am not able to add `<Leader>`-prefix key mapping via the same way.
 For example, add `<Leader>rn` for my vim:
```viml
nmap <leader>rn <Plug>(coc-rename)
```

**Describe the solution you'd like**

Maybe we could do this via API below:
```viml
function! SpaceVim#custom#Leader(m, keys, cmd, desc, is_cmd) abort 
    " ...
endfunction
```

In this way, I maybe call this API via codes below for my custom key mapping:
```viml
call SpaceVim#custom#Leader('nmap', ['r', 'n'], '<Plug>(coc-rename)', 'Refactor via coc', 0)
```

### Misc
The related issue: https://github.com/SpaceVim/SpaceVim/issues/2317

But this feature was skipped via adding the requested key mapping into SpaceVim, which doesn't solve the original issue. So I created this issue for this feature request.

**Comment by wizard-28** [comment]
Any updates on this?

**Comment by wsdjeg** [comment]
This feature has been added.
