### ISSUE TITLE
About the file manager

### ISSUE THREAD

**Issue by hypghzy** [wsdjeg/SpaceVim#3614]
I'm wondering if the defx can be customized like it was in the original vim. I tried to copy my original modification code from my old .vimrc to the spacevim custom configuration, but it could not work. It will show those lines while I was opening the vim.

Error detected while processing function SpaceVim#custom#load[34]..<SNR>20_load_glob_conf[11]..48[7]..47[6]..54[20]..69[8]..56[1]..50[5]..53:
line    8:
E605: Exception not caught: toml API: Illegal toml format at `defx#custom#option('_', {'.
Error detected while processing function SpaceVim#custom#load[34]..<SNR>20_load_glob_conf[11]..48[7]..47[6]..54[20]..69[8]..56[1]..50
line    5:
E171: Missing :endif
Error detected while processing function SpaceVim#custom#load[34]..<SNR>20_load_glob_conf[11]..48[7]..47[6]..54[20]..69:
line    8:
E170: Missing :endwhile
Error detected while processing function SpaceVim#custom#load[34]..<SNR>20_load_glob_conf[11]..48[7]..47[6]..54:
line   20:
E171: Missing :endif
Error detected while processing function SpaceVim#custom#load[34]..<SNR>20_load_glob_conf:
line   11:
E171: Missing :endif
Error detected while processing function SpaceVim#custom#load:
line   34:
E171: Missing :endif
Error detected while processing /home/bruce/.SpaceVim/vimrc:
line   25:
E171: Missing :endif
Press ENTER or type command to continue

Is there any way that I can customized defx in the Spacevim?

**Comment by wsdjeg** [comment]
no, please read the spacevim doc for how to config spacevim and it's plugin.
