### ISSUE TITLE
Can't replace vim-easymotion default mapping

### ISSUE THREAD

**Issue by TiuSh** [wsdjeg/SpaceVim#362]
## Expected behavior, english is recommend

Setting `map <leader>. <Plug>(easymotion-prefix)` in `init.vim` should replace the default mapping `<leader><leader>` for  `vim-easymotion` plugin. Instead it correctly maps `<leader>.`, but `<leader><leader>` is still mapped to `vim-easymotion` (as if the plugin was loaded twice). 

## Environment Information
- OS: macOS Sierra 10.12.3
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)

1. Open an empty buffer
2. Hit `, + ,`
3. The message `Hello World` doesn't appear in command line (as it should)

## ~/.Spacevim.d/init.vim

```
" Map leader key to ,
let mapleader = ","

" Use <leader>. as a prefix for easymotion commands
map <leader>. <Plug>(easymotion-prefix)

" Enable default mappings
let g:EasyMotion_do_mapping = 1

" Test mappings
nnoremap <leader>, :echo "Hello World"<cr>
```

**Comment by wsdjeg** [comment]
sorry, should be fixed.
