### ISSUE TITLE
Install SpaceVim with pathogen

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#3620]
**Is your feature request related to a problem? Please describe.**

Hi, thanks for providing such a great project. I am a newbie to vim and want to develop Java with Vim. This project looks very promising. However, I have already used the [ultimate vimrc](https://github.com/amix/vimrc), which seems to use pathogen as the plugin management. So I wonder if it's possible to use this SpaceVim project with pathogen?

**Describe the solution you'd like**
A guide on how to use SpaceVim as a plugin. For example, just clone this project into the normal plugin folder.

**Comment by wsdjeg** [comment]
no, this can not be implemented.
