### ISSUE TITLE
Being able to modify "command under writing" in the terminal

### ISSUE THREAD

**Issue by jerabaul29** [wsdjeg/SpaceVim#3626]
It seems that at present, it is not possible to modify the "command under writing" in the terminal from the normal mode. For example in the present case, I cannot type ```c w``` to change ```ehco``` to ```echo```.

I understand that the previous commands / outputs should probably not be modifiable, but I think the command "currently under writing" should be fully editable without any limitation.

Any idea how to fix this / get this behavior?

Illustration: "Cannot make changes, modifiable is off". Should be true for everything until the start of the last prompt, but not for the command under writing. I think if the "uneditable except command under writing" is not editable, that everything should be made editable instead, as not being able to edit the command under writing is a really big hurdle.

![Screenshot from 2020-07-12 20-10-04](https://user-images.githubusercontent.com/8382834/87253535-46bcf980-c47c-11ea-9b8b-9e4c3aaaa382.png)

**Comment by wsdjeg** [comment]
This is feature, terminal buffer do not support modified.
