### ISSUE TITLE
How can't i use like idea of JAVA.

### ISSUE THREAD

**Issue by zhangmingshuang** [wsdjeg/SpaceVim#3629]
i use neovim + spacevim in an ubuntu system. dosomething java code.
i install with the offical document.`
eg:
`install.sh`

and set the configuration ( ~/.SpaceVim.d/init.toml) layers:
```sh
autocomplete, tagbar, checkers, lsp
```

it's working better when i edit a simple java file.
but, it's not support when i open a java project. like `springboot + maven`.

it can't auto prompt like `@SpringApllication` or any parent class method overridable.

so, how to build a better java idea? it can work like `idea`.  java codes and jar dependencies codes `Auto prompt` when i input something code.

**Comment by TamaMcGlinn** [comment]
Have you tried enabling [the java layer](https://spacevim.org/layers/lang/java/)?

**Comment by wsdjeg** [comment]
make sure java layer is loaed, also you can use lsp layer with java language server.
