### ISSUE TITLE
A better way  to quit code runner(spc l r) window

### ISSUE THREAD

**Issue by kktt007** [wsdjeg/SpaceVim#3637]
**Is your feature request related to a problem? Please describe.**

Move to below windows and press `q` is a bit slow way.

If we could quit code runner quicker after `spc l r`, it is very friendly and cool, thanks.

**Comment by wsdjeg** [comment]
@kktt007 hello, I want to know, how does other text editor do  this? for example vscode or sublime.

**Comment by kktt007** [comment]
hello.
vscode use `ctrl`+` to show or hide terminal. Below official keybinding doc for your ref. 
https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-keybindings

**Comment by wsdjeg** [comment]
I have test the terminal of vscode, yeah, ``` ctrl-` ``` is better to toggle terminal. But REPL buffer is not terminal.

**Comment by kktt007** [comment]
> I have test the terminal of vscode, yeah, `` ctrl-` `` is better to toggle terminal. But REPL buffer is not terminal.

REPL is so cool. In fact, i just want to hide REPL buffer or show it asap. So we don' need to open a extra terminal by tmux. (writting Ruby by Spacevim is a enjoyable thing, thanks Spacevim ^_^)

**Comment by wsdjeg** [comment]
Maybe We can "merged" `code runner` buffer and  `repl` buffer into one window, use `` ctrl-` `` to toggle the window.

**Comment by kktt007** [comment]
> Maybe We can "merged" `code runner` buffer and `repl` buffer into one window, use `` ctrl-` `` to toggle the window.

As you like, you are a master at vim.  Thanks, wsdjeg.

**Comment by Djedouas** [comment]
+1 for this feature !

**Comment by wsdjeg** [comment]
we have three kinds of windows:
1. code runner
2. repl windows
3. terminal, opened by `SPC '`

we can add `` ctrl-` ``to toggle terminal.

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/commit/70e3570082248c7a1714c3ad21b2a13b09c46ae5

this feature has been added.
