### ISSUE TITLE
E355: Unknown option: t_8f

### ISSUE THREAD

**Issue by jasl** [wsdjeg/SpaceVim#364]
At the newest commit of dev@c4df42b, when starting Vim by just type `vi`, I got 
```
Error detected while processing /Users/jasl/.SpaceVim/config/general.vim:
line   30:
E355: Unknown option: t_8f
Press ENTER or type command to continue
```
I didn't do any modify with SpaceVim. I think this issue relates to #355 

## Environment Information
- OS: macOS 10.12.3
- vim version: 8.0.0512 via `homebrew`
- neovim version: not installed

## The reproduce ways from Vim starting (Required!)

just type `vi`

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

`:message` shows

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing /Users/jasl/.SpaceVim/config/general.vim:
line   30:
E355: Unknown option: t_8f
```

partial of `:echo SpaceVim#logger#viewLog()` (output is too long)

```
### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vi(vi)
version: 704
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gik, or build from sources.
Checking +python:
      SUCCEED!
```

**Comment by jdu** [comment]
Same issue with following setup:

OS: macOS 10.12.3
vim version: vim 7.4 (system default)
neovim version: 0.1.7 via homebrew

**Comment by wsdjeg** [comment]
@jdu @jasl 

sorry, this option need `patch 7.4.1770`, I will add a check.

**Comment by wsdjeg** [comment]
Fixed.
