### ISSUE TITLE
if u type the letters jk too fast in insert mode it deletes a char and exits insert mode wtf?

### ISSUE THREAD

**Issue by kernelzeroday** [wsdjeg/SpaceVim#3641]
dude

**Comment by melpomenex** [comment]
I have replicated this issue when typing 'iijk' in insert mode

**Comment by kernelzeroday** [comment]
btw this has been a thing since forever i just updated to 1.5.0 or whatever and its still happening, if u type slow its fine but fr lol wth

**Comment by Rom1deTroyes** [comment]
Please look at issue #3598 : this is a known feature in SpaceVim, and a long term combo used by vimers in their `.vimrc`to escape insert mode.

**Comment by wsdjeg** [comment]
The `jk` key has been mapped to `<Esc>` in insert mode. To disable this key binding, set `escape_key_binding` to empty string.

  ```toml
  [options]
      escape_key_binding = ''
  ```

also, please read https://spacevim.org/documentation/#vim-compatible-mode
