### ISSUE TITLE
nixpkg derivation

### ISSUE THREAD

**Issue by fzakaria** [wsdjeg/SpaceVim#3646]
**Describe the solution you'd like**
I am trying to contribute a [nixpkg](https://github.com/NixOS/nixpkgs) derivation for SpaceVim.
You can find it currently in https://github.com/NixOS/nixpkgs/pull/93365/files

I am seeking feedback from SpaceVim developers or anyone else interested in giving it a go.

**Additional context**
Nix (nixpkgs) is a reproducible cross platform package system. Its a way to describe the full dependency chain necessary for an application assuming nothing about the system or [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).

Packages that are installed via nixpkgs are reproducible including all their dependencies & don't suffer from the diamond dependency problem.

This installation method suits very well SpaceVim that tries to combine a couple of power-user tooling such as _fzf_ & _ripgrep_
The package script I put forward would make it so that spacevim installation declares those dependencies.

Once the derivation is complete, SpaceVim can offer an alternative installation process that can run side-by-side with an existing neovim or vim installation.

```bash
nix-env -i spacevim
```

**Comment by wsdjeg** [comment]
@fzakaria Thanks, LGTM.

**Comment by shadowrylander** [comment]
Morgan Freeman Narration: Sadly, they did not get this merged. 😹

But I would also like to see this merged; I'm currently using sourcing a SpaceVim flake input through home-manager, as shown here: https://git.smart-cactus.org/ben/ben-env/-/blob/5aceb0389e71384780f87bdd8708419932f0e98b/home-manager/spacevim.nix

**Comment by wsdjeg** [comment]
thanks :)
