### ISSUE TITLE
init.vim file structure

### ISSUE THREAD

**Issue by TiuSh** [wsdjeg/SpaceVim#365]
It would be useful to be able to structure the `init.d` file like Spacemacs : 

```vim
function! SpaceVim#dotfile#layers
  " Layers declaration 

  call SpaceVim#layers#load('lang#go')
  call SpaceVim#layers#load('ui')

  let g:spacevim_disabled_plugins=[
    \ ['junegunn/fzf.vim'],
    \ ]

  let g:spacevim_custom_plugins = [
    \ ['plasticboy/vim-markdown', {'on_ft' : 'markdown'}],
    \ ['wsdjeg/GitHub.vim'],
    \ ]
endfunction

function! SpaceVim#dotfile#init
  " Initialization function
  " Called before layers configuration, useful to set SpaceVim 
  " and layers configuration variables

  let mapleader = ","
  let g:spacevim_windows_leader = 's'
  let g:spacevim_unite_leader = 'f'
  let g:spacevim_colorscheme = 'jellybeans'
endfunction

function! SpaceVim#dotfile#config
  " Configuration function for user code
  " Called after layers configuration, this is the place where you want to define 
  " mappings and custom commands

  nnoremap <leader>, :echo "Hello World"<cr>
endfunction
```

What do you think about that ?

**Comment by wsdjeg** [comment]
name SpaceVim#dotfile#layers should be in &rtp/SpaceVim/dotfile/layers.vim

so I think we can support ~/SpaceVim.d/autoload/SpaceVim/custom.vim

and this functions

SpaceVim#custom#layers()
SpaceVim#custom#init()
SpaceVim#custom#config()

**Comment by TiuSh** [comment]
Sorry, I was actually talking about the `~/.SpaceVim/init.vim` file :)
I thought it would be helpful to be able to execute Vim commands at a specific time during SpaceVim initialization process, using some predefined functions (like `~/.spacemacs`).

**Comment by wsdjeg** [comment]
it is neovim init file, the main init file is config/main.vim

**Comment by wsdjeg** [comment]
@TiuSh SpaceVim use `~/.SpaceVim.d/` as custom configration dir, user should not change anything in `~/.SpaceVim/`.

see https://github.com/Gabirel/Hack-SpaceVim/issues/10 for how to config.

**Comment by TiuSh** [comment]
My bad, it was just another typo !... I really meant `~/.SpaceVim.d/init.vim` 😛 
Your solution to execute a function before entering in Vim is what I was looking for : 
```vim
augroup custom_config
    au!
    au VimEnter * call s:customSetting()
augroup END
func s:customSetting()

endf
```
But I still think it would be clearer to have a default  `~/.SpaceVim.d/init.vim` with all these functions already defined.

**Comment by wsdjeg** [comment]
hmm, will support it.
