### ISSUE TITLE
Vimfiler mappings overrided by spacevim

### ISSUE THREAD

**Issue by SleepyBag** [wsdjeg/SpaceVim#3664]
As the document of vimfiler suggested, I create my own vimfiler mapping:

```
autocmd FileType vimfiler nmap <buffer> <tab> <Plug>(vimfiler_expand_tree)
```

However, this mapping is overrided by `vimfilerinit()` of spacevim.

So I wonder if there is a better way to do key-binding in `vimfilerinit()`, rather than to just map some keys.

**Comment by wsdjeg** [comment]
currently, no. because when `vimcompatible` is `true`, `Tab` and `Shift-Tab` are used for switch to next/previous windows.

**Comment by wsdjeg** [comment]
This is defaut logic of vim autocmd, vimfiler is a lazy loaded plugin, it's configuration is loaded when this plugin is loaded, it is after your bootstrap function.

you can use hack scrip to implement this:

use timer to implement this feature.
