### ISSUE TITLE
bug from the latest version of ctrl+p

### ISSUE THREAD

**Issue by devcui** [wsdjeg/SpaceVim#3668]
## Debug info

i reinstall my os today,and install spacevim & ctrlp plugin,
but it tell me some help when is push ctrl+p

## Screenshots

like this
<img width="585" alt="图片" src="https://user-images.githubusercontent.com/26159886/88804449-80159900-d1e0-11ea-9b0e-d2ce6ba78b92.png">

**Comment by wsdjeg** [comment]
This is a bug of ctrlp.vim itself. I can not fix it. please open issue in it's repo.
