### ISSUE TITLE
code navigation support

### ISSUE THREAD

**Issue by edisonlove** [wsdjeg/SpaceVim#367]
## Expected behavior, english is recommend
ctags auto generate by workspace :https://github.com/yangyangwithgnu/use_vim_as_ide
function call jump:https://github.com/brookhong/cscope.vim

hope it more powerful in spacevim

## Environment Information
- OS:*
- vim version:*
- neovim version:*

**Comment by wsdjeg** [comment]
I have add the old cscope.vim

BTW I fork a new one, and  make some change, PR is here https://github.com/brookhong/cscope.vim/pull/27

**Comment by wsdjeg** [comment]
any other plugin recommanded?

**Comment by jetm** [comment]
@wsdjeg: I recommend rtags (https://github.com/lyuts/vim-rtags) as indexer/completer of C/C++ code and replacement of ctags and cscope.

**Comment by wsdjeg** [comment]
It looks good, I will test it. :+1:

**Comment by wsdjeg** [comment]
It looks nice! I will add it.



-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] code navigation support (#367)
发件人：Javier Ti�
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,Mention


@wsdjeg<https://github.com/wsdjeg>: I recommend rtags (https://github.com/lyuts/vim-rtags) as indexer/completer of C/C++ code and replacement of ctags and cscope.
