### ISSUE TITLE
Add tmux clipboard support in tmux layer

### ISSUE THREAD

**Issue by SleepyBag** [wsdjeg/SpaceVim#3670]
Sometimes I work remotely and there is no system clipboard available. So I want vim clip things to tmux clipboard when I use "+" register. 

I think this function could be added into tmux layer. When system clipboard is not available, vim could fallback to tmux clipboard. How do you think about it?

**Comment by wsdjeg** [comment]
I do not use tmux, so we need help, how to update the context in tmux clipboard? or how to read from tmux clipboard?

**Comment by SleepyBag** [comment]
To send text to tmux clipboard:

```
tmux loadb ${filename}
```

where the content is in the file named ${filename}. Besides, ${filename} could be "-" and then it will load from stdin.

To load text from tmux clipboard:

```
tmux show-buffer
```

And if you are interested in this feature, I would like to implement it, too.

**Comment by wsdjeg** [comment]
Which key binding should we use, by default, we use `Leader y` and `Leader p` to communicate with system clipboard. Maybe we can make this key binding also work with tmux clipboard. for example:

when we press `Leader y`, then add the selection text to system clipboard and tmux clipboard.

**Comment by SleepyBag** [comment]
I think it could be a fallback for system cliboard.
When system clipboard is not available, which often happens when I work remotely, vim could send content to tmux.
When system clipboard is available, I don't think people prefer to use tmux clipboard. If they do, we could leave an interface for binding.

**Comment by wsdjeg** [comment]
> When system clipboard is not available, 

you can not check it, this only can check if the system clipboard is available on reomote, not your current pc.

**Comment by SleepyBag** [comment]
Yeah, that's what I mean. We are not going to check the cilpboard in your current PC, but in the remote system.

Imagine you are working remotely. You press \<leader\>y to copy things. And you find that doesn't work because vim can only access the clipboard of the remote machine, but it doesn't have one. It is kind of annoying that then you have to select, copy and paste text in the terminal emulator's manner.
But if vim is running in tmux. It could recognize tmux clipboard as the system clipboard. You press \<leader\>y copying text and paste it in any other tmux pane. It is as smooth as there is a clipboard in the remote system.

**Comment by wsdjeg** [comment]
But I do not use tmux, maybe PR is welcome, we can talk about this feature in PR.

**Comment by SleepyBag** [comment]
OK. I'll work on it.
