### ISSUE TITLE
error when using FZF

### ISSUE THREAD

**Issue by verajosemanuel** [wsdjeg/SpaceVim#3672]
I have FZF installed and working ok in command line.
Activated FZF search in Spacevim adding this to toml config file:

[[layers]]
name = "fzf"

restarted SpaceVim, plugins are installed and started searching with space + f

`not an editor command FZF`

tried to open rencent files with space + f + r

`unknown function fzf#wrap`

   OS: Ubuntu 20.4 Gnome 64-bit
VIM v0.4.3

**Comment by wsdjeg** [comment]
Do you run `SPInstall` to install all the plugins?

**Comment by verajosemanuel** [comment]
yeah, but a message says: 

Warning: All plugins are installed.

anyway it worked after rebooting laptop.

thanks

**Comment by wsdjeg** [comment]
Do you load the fzf layer?

**Comment by verajosemanuel** [comment]
yes, worked from start when rebooting machine

**Comment by patzhang** [comment]
fzf should be trigger with <leader> + f and the default <leader> is \.
Can you try \ + f instead of SPC + f ?

**Comment by verajosemanuel** [comment]
it worked just rebooting the machine
