### ISSUE TITLE
能否提供一个精简版的分支

### ISSUE THREAD

**Issue by Nhjkl** [wsdjeg/SpaceVim#3676]
对于我一个入门不久的小白来说，一直想整理一份属于自己的vim配置，但是自己对vim理解不深，写出便于维护，扩展性好的配置确实不容易， 发现spacevim对这些方面做的非常好，我也常常在spaceVim源码里找一些小工具，想学习spacevim源码但体系太庞大无从下手，想说是不是可以通过一个精简点的分支便于学习（比如仅支持noevim），这里也只是一个小小的希望，知道开源不易。点赞

**Comment by wsdjeg** [comment]
No, we can not provide such kind version. but more comment will be added into spacevim source code, and make it easier to read. Of couse, PR is welcome.

**Comment by wsdjeg** [comment]
如果需要学习 Vim，可以查看 vim-china.org  上面的教程。

**Comment by Nhjkl** [comment]
ok， 感谢
