### ISSUE TITLE
auto mkdir floobits folder in HOME

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#368]
## Expected behavior, english is recommend

not auto mkdir this folder

## Environment Information
- OS: ubuntu 17.04
- vim version: vim8
- neovim version: any

## The reproduce ways from Vim starting (Required!)

always

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
can you delete it?
```
rm floobits
rm: cannot remove 'floobits': Is a directory
```
~~I test in my  home ,  this dir should not be created.~~

~~and floobits-neovim only be loaded when you use their command.~~

sorry, I got it, I will fix it.

**Comment by wsdjeg** [comment]
sorry this dir is used by this plugin, it is a greate plugin you should have a try, you can edit some file with other people on the net.

https://github.com/Floobits/floobits-neovim

**Comment by sethbc** [comment]
this really shouldn't be enabled by default.  don't include plugins that mess with the layout in your home directory, or have the plugin modify it.  come on, that response was just horrible.

**Comment by wsdjeg** [comment]
but this should be fixed in that plugin. not in spacevim. rplugin can not be lazy loaded.

**Comment by anselmio** [comment]
I assume @Matrix-Zhang and @sethbc have already moved on or solved this, but in case someone stumbles on this and the explanation by @wsdjeg doesn't help, you can just disable the floobits plugin with
```
let g:spacevim_disabled_plugins=[
    \ ['Floobits/floobits-neovim']
    \ ]
```

in `~/.SpaceVim.d/init.vim`

and then run `:UpdateRemotePlugins` and remove the directory and it shouldn't get recreated anymore.

**Comment by wsdjeg** [comment]
Thanks
