### ISSUE TITLE
Update TagBar

### ISSUE THREAD

**Issue by strazto** [wsdjeg/SpaceVim#3683]
Hi there - 

You bundled tagbar here:

https://github.com/SpaceVim/SpaceVim/pull/3542/commits/28fcec9db7d47af796580230ee2d00113e1fe4f0

Not long after you bundled it, tagbar added some compatibility workarounds for the snap distro of universal-ctags.

https://github.com/majutsushi/tagbar/issues/568 https://github.com/majutsushi/tagbar/pull/610

For now, I won't use the snap distro, but I wonder if you could bring your bundled tagbar to upstream's HEAD?

Thanks!

**Comment by wsdjeg** [comment]
@mstr3336 thanks for your info, but tagbar#610 does not fix the temp file reading issue, as I know, ctags or other tags manager command should support read context from stdin.

**Comment by strazto** [comment]
Yeah, also, just not using the snap distro helps. I suggested some documentation clarification to tagbar regarding the snap limitations

**Comment by wsdjeg** [comment]
@matthewstrasiotto I will improve the tagbar, as we do not use the upstream version, so we can not update it directly, but if you think any patch is useful, please check pick and send PR to spacevim. I do not think preservim/tagbar#568 preservim/tagbar#610 can fix the temp issue, this only add option to hidden this bug.

**Comment by strazto** [comment]
Thanks wang, once I understood the issue lay with snap, i stopped worrying about this thing.

By the way, I'd like to thank you for all of the work you do on this project. you help people so much and so often and SpaceVim has helped make my terminal feel very productive and comfortable.

The only other text editor i use is Rstudio, because its R specific features are very mature, but even then i use spacevim a lot. 
The project helped teach me to not fear the command line 🙂
