### ISSUE TITLE
How would I go about changing the space indicator colour?

### ISSUE THREAD

**Issue by EwanValentine** [wsdjeg/SpaceVim#369]
More of a question than a bug, the line indicators are really useful, but on some themes they're too bright, which mean it becomes difficult to read code. Is there a way I can override it? 

<img width="184" alt="screen shot 2017-03-28 at 12 45 50" src="https://cloud.githubusercontent.com/assets/1155123/24403395/9b542b52-13b4-11e7-8db4-ad4209bcfbd8.png">

**Comment by wsdjeg** [comment]
what colorscheme?

**Comment by EwanValentine** [comment]
@wsdjeg `https://github.com/liuchengxu/space-vim-dark`

**Comment by EwanValentine** [comment]
I think it's this... 
```

"""""""""""""""""""""""""""""""""""""""""""
" Plugins
"""""""""""""""""""""""""""""""""""""""""""
" vim-indent-guides {
let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd  guibg=#708090 ctermbg=237
hi IndentGuidesEven guibg=#696969 ctermbg=239
" }
``` 

Sorry this probably isn't related to this repo!

**Comment by wsdjeg** [comment]
@EwanValentine Which spacevim do you use, SpaceVim is not space-vim, and I do not have this config in SpaceVim, the vim-indent-guides should use it's default setting.

**Comment by wsdjeg** [comment]
I don this user should set hi command like this, because plugin should has it's default value. this setting will break many other plugins.

**Comment by EwanValentine** [comment]
I'm using this SpaceVim, but with that theme. I tried the other spacevim, but this one's wayyy better IMO, but I really liked the default theme of the other one. I'll look into vim-ident-guide! Thanks for your help!

**Comment by wsdjeg** [comment]
@EwanValentine  I will test that colorscheme. sorry for missunderstand.

**Comment by wsdjeg** [comment]
Let me have a try.

**Comment by wsdjeg** [comment]
@EwanValentine I will create a new colorscheme, meybe it will looks like the link you show me , but it is not the same, I will base on the old emacs theme.

**Comment by EwanValentine** [comment]
Not to worry :) thanks again!

**Comment by wsdjeg** [comment]
do you have a try with https://github.com/colepeters/spacemacs-theme.vim?

I think this one maybe is better.
