### ISSUE TITLE
A straightforward way to keep the latest release

### ISSUE THREAD

**Issue by GreyTeardrop** [wsdjeg/SpaceVim#3694]
### Is your feature request related to a problem? Please describe.

I would like to see a straightforward way to follow the latest released version of SpaceVim vs the latest dev version, mostly for stability purposes (the last thing that pushed me to think about that was https://github.com/SpaceVim/SpaceVim/issues/3688 bug).

Really minor, but it also is a bit more aesthetically pleasing to see "1.4.0" and "1.5.0" as SpaceVim versions instead of "1.4.0-dev" and "1.5.0-dev".

This ticket is a follow-up on https://github.com/SpaceVim/SpaceVim/issues/2734 and https://github.com/SpaceVim/SpaceVim/issues/3068.

Right now, SpaceVim installation checks out the `master` branch and follows all its development. It's possible to manually check out the release version by running

```
git checkout vX.Y.Z
```
in SpaceVim directory. This has a downside that `SPUpdate` fails on SpaceVim itself with
```
x SpaceVim: Updating failed,  The plugin dir is dirty
```

### Describe the solution you'd like

The simplest way around that probably won't add too much maintenance overhead is to add another Git branch (e.g. `release`) that is always set to the latest tag on `master`. Then, checking out that branch should be enough to keep SpaceVim on the latest release version all the time.

Optionally, SpaceVim installation script might accept an optional flag to check out the `release` branch from the start (and keep checking out `master` if no flag is provided).

### Describe alternatives you've considered

As an alternative, `SPUpdate` can be changed to silently handle the case when SpaceVim is in a detached head state (like when the tag is checked out) and skip the update (optionally warning the user that SpaceVim won't be updated automatically). Document, that manual update to the latest release/tag can be done via command like
```
git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
```

**Comment by MikeSmithEU** [comment]
As `1.6.0-dev` seems broken (see #3688), +1 for above proposal.

**Comment by wsdjeg** [comment]
> `git checkout $(git describe --tags $(git rev-list --tags --max-count=1))`

@GreyTeardrop Thanks, This seems do not supported in windows cmd.exe,

**Comment by GreyTeardrop** [comment]
> > `git checkout $(git describe --tags $(git rev-list --tags --max-count=1))`
> 
> @GreyTeardrop Thanks, This seems do not supported in windows cmd.exe,

Sure, I've tests that on Mac only, I imagine it should work in any POSIX-compatible shell, but Windows would need another way.
