### ISSUE TITLE
Remapping over f and s is a bit too heavy handed

### ISSUE THREAD

**Issue by zeroasterisk** [wsdjeg/SpaceVim#370]
## Expected behavior, english is recommend

in normal mode `f` should move to the first matching character on the line

if you do `:h f` it should show you:

![ss](https://puu.sh/v1cpg/423e37f023.png)

if you do `:h s` it should show you:

![ss](https://puu.sh/v1ddt/ee15e526f1.png)

I have found the configuration to change them, conveniently this is on the README _(though it took me a while to find it and figure out what was over-riding those keys)_:

```
" Set windows shortcut leader [Window], default is `s`
let g:spacevim_windows_leader = 's'

" Set unite work flow shortcut leader [Unite], default is `f`
let g:spacevim_unite_leader = 'f'
```

I have switched these (for now) to `_` and `-` - but I'm considering moving to `<F8>` or something:

```
let g:spacevim_windows_leader = '_'
let g:spacevim_unite_leader = '-'
```

This is obviously a design choice, and perhaps a fine one, but it did throw me for a loop for a while.

I also had to do some janky `nnoremap q q` thing, because some unknown thing was stopping me from recording macros by default.

## Proposal

I suggest you chose less commonly used keys to do default mappings, or include in the documentation more information about "do you use the `f` movement key? if so, here's how to get it back"

## Environment Information
- OS: OSX
- neovim version: NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDIS
ABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-
color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170109-13192-2e3pqy/neovim-0.1.7/build/config -I/tmp/ne
ovim-20170109-13192-2e3pqy/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/
usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170109-13192-
2e3pqy/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170109-13192-2e3pqy/neovim-0.1.7/build/include

**Comment by wsdjeg** [comment]
I think `f` should not be used, but `s` is ok, as we only map `s` in normal mode, you can use `s` in visual mode as before. if you only want to delete one char, you can use `c` or `x`, why only `s`. I remember there is a post about why we can map `s` in normal mode.

**Comment by wsdjeg** [comment]
I like to use s for windows func, also many people like use f for unite, I am not sure I should change the default of SpaceVim. how about:
```viml
nnoremap <leader>f f
nnoremap <leader>F F
```

**Comment by wsdjeg** [comment]
I will add a func for test the frequency of key. after add this func.
you can add this to custome setting to find out how many times do you use these keys.
