### ISSUE TITLE
Move by display line in word wrap mode

### ISSUE THREAD

**Issue by gryftir** [wsdjeg/SpaceVim#3708]
**Is your feature request related to a problem? Please describe.**

Currently when you enter wrap mode, commands don't work by display line by default. Some commands that don't work by display line by default are j,k,0,^,$,I,A. 

**Describe the solution you'd like**
remap line based commands in normal and operator pending mode to work for display lines when the wrap minor mode is active.

**Describe alternatives you've considered**
There may exist a plugin that sets these, which would simplify maintenance

**Additional context**
These are useful particularly for writing prose.

**Comment by wsdjeg** [comment]
@gryftir This is default feature of vim and neovim, change it maybe make users confuse.

if you want this feature, you can use bootstrap function. here is some tips:

```viml
nnoremap j gj
nnoremap k gk
nnoremap 0 g0
nnoremap I g0i
nnoremap A g$a
```
