### ISSUE TITLE
unable to set my own config for plugins

### ISSUE THREAD

**Issue by zeroasterisk** [wsdjeg/SpaceVim#373]
## Expected behavior, english is recommend

I expect to be able to set my own config for plugins... for example:

You have:
`let g:ctrlp_root_markers = 'pom.xml'`
I want:
`let g:ctrlp_root_markers = ['package.json', 'settings.json']`

Ideally - we could have a second "override.vim" file or something, or every one of your configs should be optional, only if not otherwise set.

**Comment by wsdjeg** [comment]
can you send a PR, just change to
`let g:ctrlp_root_markers = get(g:, 'ctrlp_root_markers', 'pom.xml')`

**Comment by wsdjeg** [comment]
override.vim will not work for lazyload plugin's config, lazy load plugin's config is loaded when plugin is loaded not startup.
