### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#3733]
Hi, I am the author of [SpaceVim](https://spacevim.org), which is a community-driven modular vim distribution. It is four years old on github now. If you are new to SpaceVim, we recommend to checkout the [quick-start-guide](https://spacevim.org/quick-start-guide/) first.

We are looking for contributors:

## language layer maintainers

Currently we have many programming languages layer, the full list can be found in [Available layers](https://spacevim.org/layers/) page. A programming language layer is an layer which provides language specific function for this programming language. Including:

- syntax highlight
- indent
- compiler: This can be done with [checkers](https://spacevim.org/layers/checkers/) layer.
- language specific key binding:

## documentation maintainers

I'm not a native English speaker,  so the documentation wrote by me sometimes is hard to understand, we hope there are some native english speakers can help us to improve the documentation.

## community admins

The [SpaceVim comminuty](https://spacevim.org/community/) provides three types of community:

1. chatting room: This is a channel bridged with gitter. irc, telegram etc.

2. forum: The default forum of spacevim is reddit, 

3. mail list or github issue: This is for bug report and new feature request.

### Language forum

As SpaceVim is a IDE-like vim distribution for different programming language, sometimes we need to discuss the language specific questions, I think it is better to use the language forum. Currently I have found following language forums:

- Elixir: https://elixirforum.com/
  - discussions: [1](https://elixirforum.com/t/spacevim-like-spacemacs-but-for-vim/7465), [2](https://elixirforum.com/t/author-of-spacevim-wanting-to-improve-the-elixir-layer-please-help/10897)
- Elm: https://discourse.elm-lang.org/
  - discussion: [1](https://discourse.elm-lang.org/t/use-spacevim-as-general-ide-for-elm/5274)
- Golang: https://forum.golangbridge.org/
  - discussion: [1](https://forum.golangbridge.org/t/use-spacevim-as-go-ide/20345)
- Nim: https://forum.nim-lang.org/
  - discussion: [1](https://forum.nim-lang.org/t/4120)

### TODO

- [SpaceVim cheatsheet](https://github.com/SpaceVim/SpaceVim/issues/3682)

**Comment by arun-mani-j** [comment]
Hello. I can help in writing documentation. I'm not a native English speaker, but I can proof-read it with my native English speaking friends. :)

**Comment by wsdjeg** [comment]
@J-Arun-Mani Thanks for your help, :)

**Comment by wsdjeg** [comment]
Hi, I will close this issue in #3808, because I think the issue should not be a place to look for contributors. The contributing guide of SpaceVim should be improved.
