### ISSUE TITLE
strange error messages on mac os catalina (E576: Error while reading ShaDa file: there is an item at position ..)

### ISSUE THREAD

**Issue by a43mrk** [wsdjeg/SpaceVim#3755]
<img width="803" alt="Screen Shot 2020-09-02 at 11 49 49" src="https://user-images.githubusercontent.com/52528432/91960601-c47de280-ed12-11ea-819d-e49636e4f2a4.png">

**Comment by Shougo** [comment]
It is not denite error messages.

**Comment by a43mrk** [comment]
yes, checkhealth result is ok for denite.
everything is ok on healthcheck. I don't know what is this msg...

**Comment by a43mrk** [comment]
solved deleting .local/share/nvim/shada/main.shada
like it was solved at https://github.com/neovim/neovim/issues/6875

**Comment by todd-dsm** [comment]
I think this one has regressed. Saw this on macOS Catalina (10.15.7) while opening nvim (v0.4.4) for the first time.

```vim
Error detected while processing CursorHold Autocommands for "*":
E886: System error while opening ShaDa file /Users/vimr/.local/share/nvim/shada/main.shada for reading: no such file or directory
```

![image](https://user-images.githubusercontent.com/2463935/98453934-838bbb00-2113-11eb-8235-7c32479b282c.png)
