### ISSUE TITLE
Cant make built (docker)

### ISSUE THREAD

**Issue by 1m-N00b** [wsdjeg/SpaceVim#3757]
## Error
I'm trying to build [it](https://github.com/SpaceVim/SpaceVim/tree/master/docker) using the docker as described here, but I can't proceed from here.

Pressing enter does not change it. And i arleady installed [it](https://imgur.com/a/hHhWE4G)

[Error detail](https://imgur.com/a/C0hcqXO)

**Comment by wsdjeg** [comment]
can you use official docker img? the build is passed. https://hub.docker.com/r/spacevim/spacevim/
