### ISSUE TITLE
runtimepath is wrong

### ISSUE THREAD

**Issue by revegnay** [wsdjeg/SpaceVim#376]
![qq 20170330103743](https://cloud.githubusercontent.com/assets/1030074/24485168/16eb9b84-1535-11e7-81c0-ae033bde2d4c.png)

runtimepath is wrong

**Comment by wsdjeg** [comment]
sorry, I do not use windows, can you show me more info about this issue?
what is your os?
how do you start vim?
gvim or vim?

**Comment by wsdjeg** [comment]
please check your `g:spacevim_plugin_bundle_dir`.

it should be `let g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles/'`
