### ISSUE TITLE
Add doc for dein's merged option

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#3771]
In the Docs under `[[custom plugins]]`, the example uses `merged = false`.
 but the meaning of merged is not documented.

**Comment by gunnarx** [comment]
Yes and since the usage of merged is a little complex (I saw your answer), and it isn't immediately important, so I think it might be enough to make a reference link.  Someting like "For other parameters, see [dein documentation (link)]".
