### ISSUE TITLE
Cannot create dictionary /tmp/v1qu5Aw in ubuntu 18.04

### ISSUE THREAD

**Issue by WDXC** [wsdjeg/SpaceVim#3776]
**when i use SPC+l+r to run code , system will create /tmp/v1qu5Aw.**
**but in Spacevim ,it show me cannot create dictionary /tmp/v1qu5Aw**

**when i delete v1qu5Aw from /tmp ,it show me this:**
[Compile] ['g++', '-o', '/tmp/v1qu5Aw/9', '-xc++', '-', 'STDIN']
[Running] /tmp/v1qu5Aw/9

--------------------
/usr/bin/ld: cannot open output file /tmp/v1qu5Aw/9: No such file or directory                                                                                
collect2: error: ld returned 1 exit status

[Done] exited with code=1 in 0.211693 seconds

**Comment by wsdjeg** [comment]
![image](https://user-images.githubusercontent.com/13142418/92328641-c50cd500-f094-11ea-8f59-887bd0e64f32.png)

I can not reproduce it in windows, I think it is based on os, and what is `/usr/bin/ld`, why `g++` command call this command.

**Comment by wsdjeg** [comment]
This has been fixed in #3800 . Thanks
