### ISSUE TITLE
<Leader>y doesn't yank to the system clipboard

### ISSUE THREAD

**Issue by raw-bin** [wsdjeg/SpaceVim#3781]
## Expected behavior, english is required

As per the SpaceVim documentation, (see: https://spacevim.org/layers/default/), the 'core' layer is enabled by default. With this layer enabled, <Leader>y should yank the relevant text object to the system clipboard.

This doesn't work as expected. No text is copied to the system clipboard. The following message appears in the vim command/status window:

`key bindings is not defined:   -y`

Tested with SpaceVim at commit 18b105c2db7abd8177ee3e1d397452f6aaeba860 on:
- Ubuntu 20.04 on x86_64 host.
- Ubuntu 20.04 under WSL2.

## The reproduce ways from Vim starting (Required!)

1. Start SpaceVim
2. With the cursor on some text, press <Leader>p.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

SpaceVim layers:

- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
- chinese:              not loaded          https://spacevim.org/layers/chinese/
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- ctrlspace:            not loaded          https://spacevim.org/layers/ctrlspace/
- debug:                not loaded          https://spacevim.org/layers/debug/
- denite:               not loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
- foldsearch:           not loaded          https://spacevim.org/layers/foldsearch/
+ format:                   loaded          https://spacevim.org/layers/format/
- fuzzy:                not loaded          no exists
+ fzf:                      loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
- git:                  not loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- gtags:                not loaded          https://spacevim.org/layers/gtags/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#actionscript:    not loaded          https://spacevim.org/layers/lang/actionscript/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#aspectj:         not loaded          https://spacevim.org/layers/lang/aspectj/
- lang#assembly:        not loaded          https://spacevim.org/layers/lang/assembly/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
- lang#batch:           not loaded          https://spacevim.org/layers/lang/batch/
- lang#c:               not loaded          https://spacevim.org/layers/lang/c/
- lang#chapel:          not loaded          https://spacevim.org/layers/lang/chapel/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
- lang#crystal:         not loaded          https://spacevim.org/layers/lang/crystal/
- lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
- lang#d:               not loaded          https://spacevim.org/layers/lang/d/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
- lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#eiffel:          not loaded          https://spacevim.org/layers/lang/eiffel/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
- lang#factor:          not loaded          no exists
- lang#forth:           not loaded          no exists
- lang#fortran:         not loaded          https://spacevim.org/layers/lang/fortran/
- lang#foxpro:          not loaded          https://spacevim.org/layers/lang/foxpro/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
- lang#go:              not loaded          https://spacevim.org/layers/lang/go/
- lang#goby:            not loaded          https://spacevim.org/layers/lang/goby/
- lang#gosu:            not loaded          https://spacevim.org/layers/lang/gosu/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
- lang#hack:            not loaded          https://spacevim.org/layers/lang/hack/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
- lang#html:            not loaded          https://spacevim.org/layers/lang/html/
- lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
- lang#idris:           not loaded          https://spacevim.org/layers/lang/idris/
- lang#io:              not loaded          https://spacevim.org/layers/lang/io/
- lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
- lang#j:               not loaded          https://spacevim.org/layers/lang/j/
- lang#janet:           not loaded          https://spacevim.org/layers/lang/janet/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
- lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
- lang#lasso:           not loaded          https://spacevim.org/layers/lang/lasso/
- lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
- lang#markdown:        not loaded          https://spacevim.org/layers/lang/markdown/
- lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
- lang#moonscript:      not loaded          https://spacevim.org/layers/lang/moonscript/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#nix:             not loaded          https://spacevim.org/layers/lang/nix/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
- lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
- lang#pascal:          not loaded          https://spacevim.org/layers/lang/pascal/
- lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
- lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
- lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
- lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
- lang#python:          not loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          https://spacevim.org/layers/lang/r/
- lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
- lang#red:             not loaded          https://spacevim.org/layers/lang/red/
- lang#ring:            not loaded          https://spacevim.org/layers/lang/ring/
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
+ lang#rust:                loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
- lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
- lang#slim:            not loaded          https://spacevim.org/layers/lang/slim/
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#supercollider:   not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
- lang#toml:            not loaded          https://spacevim.org/layers/lang/toml/
- lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
- lang#v:               not loaded          https://spacevim.org/layers/lang/v/
- lang#vbnet:           not loaded          https://spacevim.org/layers/lang/vbnet/
- lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
- lang#wdl:             not loaded          no exists
- lang#wolfram:         not loaded          https://spacevim.org/layers/lang/wolfram/
- lang#xml:             not loaded          https://spacevim.org/layers/lang/xml/
- lang#xquery:          not loaded          no exists
- lang#zig:             not loaded          https://spacevim.org/layers/lang/zig/
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
- lsp:                  not loaded          https://spacevim.org/layers/language-server-protocol/
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell/
- sudo:                 not loaded          https://spacevim.org/layers/sudo/
- test:                 not loaded          https://spacevim.org/layers/test/
+ tmux:                     loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#mpv:            not loaded          https://spacevim.org/layers/tools/mpv/
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- vim:                  not loaded          no exists

## Screenshots

No screenshot required.

**Comment by wsdjeg** [comment]
@raw-bin It seems default behavior, `Leader y` is not used in Normal mode, so it is not defined. This key binding is definded in Visual mode, you can try to select text, then press `Leader y`.

for example, press `Vjjj` and `Leader Y`

**Comment by raw-bin** [comment]
Hmm. That doesn't appear to work on my setup. I also still get the 'Key bindings is not defined...' message in the command line.

**Comment by wsdjeg** [comment]
@raw-bin I have test it in my so, and it works well, in visual mode, if you press `<Leader>` in normal mode, the guide buffer, will be opened, and you can see `[y]` in it, then press `y`, the selection will be yarked.

**Comment by raw-bin** [comment]
That's odd! I don't see any `[y]` option in the guide buffer when I press `<Leader>` in normal mode! I'll try and do a screencast.

**Comment by raw-bin** [comment]
@wsdjeg : https://asciinema.org/a/3Z92Yyp488wp549C7s6Dff0AP

**Comment by wsdjeg** [comment]
can you use gif? I can not see the full screen in asciinema

**Comment by raw-bin** [comment]
Hopefully this is better ? https://asciinema.org/a/7zgCTo7FAPgyIRYnUhgJ9q1Na

**Comment by Rom1deTroyes** [comment]
No problem here :
![image](https://user-images.githubusercontent.com/8625432/92601880-a2a1d400-f2ad-11ea-8c89-15254f207621.png)

In `Visual` mode, pressing my <kbd>Leader</kbd> key (<kbd>\\</kbd> by default) pop's up the menu with <kbd>y</kbd> mapped to the desktop clipboard (XA_SECONDARY or `+` buffer).

In `Normal` mode, I got the message : `key bindings is not defined:   <leader>-y`.

Note that your <kbd>Leader</kbd> seems to be remapped (to <kbd>~</kbd> ?), and your error message is not about `leader` but about `~` so maybe there is something to seek here ?

How (where and when) do you define your leader key ?
Does `V\y` (select current line, default-leader yank) does something ?

**Comment by raw-bin** [comment]
Hi @Rom1deTroyes.

I remap the leader key to '~' in a custom `~/SpaceVim.d/autoload/myspacevim.vim`. I assume that that shouldn't cause problems here ?

Having said that, it appears that if I switch to visual mode by pressing 'v', then select a region and then use `\` followed by `y` that works!

So it appears that the statement: `Leader`-y will yank to the clipboard is wrong. The correct statement appears to be: `\-y` will yank to the clipboard.

Could you confirm that please ?

Thanks

**Comment by wsdjeg** [comment]
@raw-bin Got it. In SpaceVim, the key binding definition `<Leader>y` is definded in `SpaceVim#default#keyBindings()`, which is called before `SpaceVim#custom#load()`, so the `<Leader>` is `\`. so I should move all these key bindings after custom script.

That means this is a bug of spacevim.

**Comment by raw-bin** [comment]
Great! Thanks @wsdjeg !

**Comment by woss** [comment]
in my case the issue was that X11 didn't have Private and Public firewall access. adding that I can use spacevim in wsl2 using the Leader -> y and get stuff in my windows machine
