### ISSUE TITLE
tagbar not found

### ISSUE THREAD

**Issue by haoyifan** [wsdjeg/SpaceVim#379]
## Environment Information
- OS: Ubuntu 16.04
- vim version: 7.4
- neovim version:

## The reproduce ways from Vim starting (Required!)
When I pressed F2 in my vim, it didn't toggle TagBar even if it's already installed.

![image](https://cloud.githubusercontent.com/assets/16672909/24509562/ab7e2948-1534-11e7-8746-6547992d430f.png)
![image](https://cloud.githubusercontent.com/assets/16672909/24509568/af2117ae-1534-11e7-9c0b-f3513295a5a0.png)

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

I'm using default SpaceVim configuration

**Comment by wsdjeg** [comment]
it is not `tagbar not found`, but `ctags not found`, you need install ctags.
