### ISSUE TITLE
Code Navigation Engine

### ISSUE THREAD

**Issue by mckila** [wsdjeg/SpaceVim#3795]
*Current Implementation*

With the current gtags layer implementation the default options for code navigation are 
* find-definition of cword
* find-reference of cword 
* find-symbol of cword 
* find-cursor-string

Which are all great code navigation actions, however, they all automatically open new windows forcing window sprawl and context switching

*Proposed feature*

what if all the current functions available of the gtags layer could  be interactively selected in a denite menu and inside denite you have the option of "peeking" at the code snippet (i.e. definition, symbol, reference) as well as opening the selected item in new window, buffer, or split window.  Using dentie would also give ability to  display options from old denite UI or new denite UI (floating window)

*sample workflow*

(If Gtags layer is enabled) - Enabling the Denite layer automatcally gives the developer code navigation engine with the following options
* "Peeking"  or "Snippet Preview" of definition||symbol||Reference||String code snippet (This is Default behavior)
* open new window (at tagged item line number)
* open new v/s split (at tagged item line number)

cword:select -> denite_menu ("S"ymbol || "D"efinition || "R"eference || "F"ind string) 
  inside Denite....
 

    |_Selected_tag(Peek [Symbol || Definition || if Reference < 2 || if find_string < 2  ] )
    |_Selected_tag(New_window [Symbol || Definition || if Reference < 2 || if find_string < 2  ] )
    |_Selected_tag(New_Split [Symbol || Definition || if Reference < 2 || if find_string < 2  ] )
       |_Selected_tag(browse with fuzzy find  [  Reference_Occurances || Find_String_Occurances ])
       |_Selected_tag_Occurance("P"eek(Occurance_filter_code snippet)  || "N"_window || "New_split || "C"lose )
           

here is an example 
https://github.com/semanticart/tag-peek.vim
But using the gtags as a source for denite as opposed to a plain neovim window like the tag-peek.vim plugin would be much more feature rich for code navigating options
examples:
1) fuzzy finding code patterns on the filtered list of occurances of Find_string and or references in current project directory or arbitrary directory
2) using gtags layer and denite layer integration may also allow a selected item from arbitrary project directory in the code navigation menu to open selected object in a new window, - in a new project context  giving the developer more advanced project managment in spacevim (this probably would happen automatically with the current project management layer capabilities in spacevim)

adding such a feature would give the feel and workflow of other code editors like VSCode but more advanced and allowing the developer to choose his or her context switching using this denite powered code navigation-command prompt and Engine
 versus generically forcing it as the gtags layer does currently

**Comment by wsdjeg** [comment]
Hi @mckila, the gtags layer should provide all the basic logic for using global command, and if denite or any other fuzzy find layer is enabled, pick up feature can be enabled. Maybe I have missunderstood your feature request, does pick up require fuzzy finder?

**Comment by mckila** [comment]
Hi @wsdjeg , nice work on the spacevim project. gets better everyday. 👍 

Yes the  Gtags layer does provide all basic logic for using global command. however i am looking for a solution to provide the ability to "peek" at tags and  or references like this
 
https://github.com/semanticart/tag-peek.vim
and this
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-view-and-edit-code-by-using-peek-definition-alt-plus-f12?view=vs-2019#:~:text=You%20can%20use%20the%20Peek,in%20a%20separate%20code%20window.

Currently gtags only allows to "jump" to the class definition which automatically throws you into a new window, and or list all reference occurrences which also only gives an option of opening file.

**Comment by wsdjeg** [comment]
Ok, Got it, it is a prview windows, and the tags info will be displayed in the windows.

**Comment by mckila** [comment]
Correct but with options Provided by mnemonic key bindings of...

core of implementation:

preview  cword definition (default)
preview cword nearest reference or symbol (default)
search cword reference or symbol  and allow preview (in the current project)
search cword string reference in arbitrary project powered by  project manager + gtags
ctrl or space"O"pen definition or reference to a new window (in the current project)
ctrl or space"O"pen definition or reference to a new window (in new project)


Advanced or Version 2

ctrl or space  "E"dit  in the preview window if cword in current project.. 

Lastly

 options to  let user define all keymappings (if the preview window  is powered by denite). 👍

**Comment by thawk** [comment]
I agree not jumping by default when there's more than one candicates.  It seems at most time, the first one isn't what I needed.

**Comment by wsdjeg** [comment]
the `gtags` and `cscope` layer has been updated.

**Comment by thawk** [comment]
Yes, confirmed.  It works fine!
