### ISSUE TITLE
unit search function broken

### ISSUE THREAD

**Issue by leiwang-ninjia** [wsdjeg/SpaceVim#380]
## Expected behavior, english is recommend

[Unite]g  search with Ag , report error that  [unite.vim] [grep] /usr/bin/ag: unrecognized option '--exclude=tags
:Unite   interactive grep search works well , but in 3.0 version ,this also broken.

## Environment Information
- OS:fedora
- vim version:8.0
- neovim version:

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
hmm, I can reproduce it, will fix it.

**Comment by wsdjeg** [comment]
@zeroasterisk
PR #375 cause this bug. 
In the plugin config, not all value should use get().
