### ISSUE TITLE
bootstrap_after function is not called before opening a command-line file

### ISSUE THREAD

**Issue by randomizedthinking** [wsdjeg/SpaceVim#3813]
## Expected behavior
When open a file at command line, such as `vi myprog.py`, the `bootstrap_after` function should be called before the file gets opened. In my case, the py filetype requires certain configurations defined in the `bootsrap_after` function call, then some errors occur.

The configurations can be re-arranged to `bootstrap_before` function to avoid the issue. Yet, I think the issue should be addressed in spacevim, otherwise, any settings in `bootstrap_after` can potentially cause some unexpected behaviors.

## The reproduce ways from Vim starting (Required!)
The way to duplicate the bug is as follows. The same idea can be generalized to other configurations or filetypes.

1. Turn on modelineexpr for py filetype in your `bootstrap_after` function.

    ````vim
    autocmd FileType python setlocal modelineexpr
    ````

2. Create a myprog.py file with some modeline information embeded. For instance, the first line as follows:

    ````python
    # vim: foldmethod=expr;
    ````

3. Open the file through command-line: `vi myprog.py`, then an error would be thrown: `Invalid argument: foldmethod=expr;`.

On the otherhand, it would be okay to open `vi` first, then open the given file.

## Debug info

The debug info has no useful information for this bug.

**Comment by wsdjeg** [comment]
hmm, I do not know why, the `bootstrap after` function is called on `VimEnter` autocmd. maybe it is because this autocmd is too late.

**Comment by randomizedthinking** [comment]
It could be. I noticed that sometimes we have to wait a bit for spacevim to get ready. We could well receive errors if typing too fast at startup.

I assume this is not an easy one to fix.

**Comment by wsdjeg** [comment]
This is not bug, this is vim feature, you should use `# vim: foldmethod=expr` instead.

**Comment by wsdjeg** [comment]
you will get same error when you run `set foldmethod=expr;` in command line.

**Comment by randomizedthinking** [comment]
The bug report I submitted were not precise when trying to get a minimal reproducible example.

But the main issue is still valid though: the file is opened before the `bootstrap_after` call is executed.
