### ISSUE TITLE
support scala Metals using the coc-metals

### ISSUE THREAD

**Issue by blueway** [wsdjeg/SpaceVim#3814]
**Is your feature request related to a problem? Please describe.**
scala Metals with LSP clients for Vim 

**Describe the solution you'd like**
 https://scalameta.org/metals/docs/editors/vim.html

**Describe alternatives you've considered**

**Additional context**

**Comment by wsdjeg** [comment]
@blueway coc's plugin do not need modified vim script, I think this can be done via coc install command, so anything need to be done in spacevim?

**Comment by blueway** [comment]
Ok, I've seen the configuration of scala Metals in scala layer
