### ISSUE TITLE
Changing vim-todo to fine "TODO" instead of "@todo"?

### ISSUE THREAD

**Issue by macintacos** [wsdjeg/SpaceVim#3819]
I'm trying to figure out a way to make it so that the todo manager in SpaceVim can search for "TODO" instead of "@todo". Is this possible?

**Comment by wsdjeg** [comment]
No, we can not add this feature, we need a prefix before tag, because `TODO` is too general word in context, and we are using `grep prefix + tag` to search whole project, if the prefix is empty, the command will be `grep tag`, for example `grep TODO`, it will list too many unwanted results.

**Comment by macintacos** [comment]
I'd argue that if the user knowingly passes words that they know they will only use for this plugin (i.e. "TODO"/"FIXME"/etc.), there won't be too many unwanted results since those words would only be used in instances where you'd _want_ to surface them. There's no real difference between the results you get back from "@todo" and "todo" if you are certain that "todo" isn't going to be used in any other context.

But I mean hey, it's your plugin, understandable if you don't want to add it.

**Comment by wsdjeg** [comment]
OK I reopen this issue, maybe there is a better way to find toto list.

**Comment by romgrk** [comment]
Fixes this: https://github.com/wsdjeg/vim-todo/pull/3
