### ISSUE TITLE
[string "vim chunk"]:1: attempt to index global 'w' (a nil value)

### ISSUE THREAD

**Issue by hairy-crab** [wsdjeg/SpaceVim#3829]
### i run my python code correctly,exit code is 0.But the ruuner print erro,how can i close it or fix it?
my code is:
`import pandas as pd ;
print(pd.__version__)`
its result is:
![image](https://user-images.githubusercontent.com/28957394/93955562-e01e4c80-fd04-11ea-93d5-45179242bd9c.png)
but the runner output is:
![image](https://user-images.githubusercontent.com/28957394/93955842-8bc79c80-fd05-11ea-9721-1e4408731e03.png)
How can I close Runner or fix it?

**Comment by wsdjeg** [comment]
@LiGang0 can you reproduce it in latest version of spacevim?

**Comment by hairy-crab** [comment]
yes,1.6.0-dev

**Comment by hairy-crab** [comment]
this error occur when i type "SPC l r"

**Comment by AndrewGEvans95** [comment]
Currently experiencing the same issue.

**Comment by rajeshduggal** [comment]
Not sure if this is related or useful... I'm running WSL ubuntu on Win10. When I create a completely blank Hi.java file, or even if the file is valid and has a main method.  When I tell spacevim to run the main method..  "SPC l r m" I see similar error vim chunk error messages, before the output is displayed.
![spacevim-vimchunk](https://user-images.githubusercontent.com/27322/107125216-8d3dcf80-6876-11eb-96a4-745b2db56702.png)

**Comment by rajeshduggal** [comment]
I complete forgot about this.. and just tried running it again in my WSL environment, and it's working now! (I'm running version 1.7.0-dev) (I may have installed a different version of python a few weeks ago, I'm not sure)

**Comment by wsdjeg** [comment]
@rajeshduggal Ok, closed.
