### ISSUE TITLE
has('gui_running') returning false / guifont not setting properly

### ISSUE THREAD

**Issue by WispOfTheWinds** [wsdjeg/SpaceVim#3834]
## Expected behavior, english is required

Using a Neovim GUI should cause `has('gui_running')` to return true. This is used as a condition to set `guifont` in [config/general.vim](https://github.com/SpaceVim/SpaceVim/blob/276d761ae227e93b91116984245103f32f69a11a/config/general.vim#L31)

## The reproduce ways from Vim starting (Required!)

I tested this in goneovim and neovim-qt by setting `guifont` in my init.toml to the desired font. Neovim was not picking up the setting, but setting `guifont` manually _within_ neovim worked just fine.

I didn't get too into it, but config/general.vim may be running before the GUI actually launches, so `has('gui_running')` is returning false? Just a guess (see [equalsraf/neovim-qt #219](https://github.com/equalsraf/neovim-qt/issues/219))

I was able to get `guifont` to set correctly by removing the `has('gui_running')` condition.

## Debug info

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status:

**Comment by wsdjeg** [comment]
This is a bug of neovim, I can not fix it, in neovim, `has('gui_running')` always return false.

**Comment by WispOfTheWinds** [comment]
Is there any reason not to take out that condition? Taking it out, at least until it's fixed upstream, allows the guifont option to work as expected.

**Comment by wsdjeg** [comment]
there is no way to fix it. neovim-qy use ginit.vim as config, so we have a ginit.vim in this repo. I do not use goneovim.
