### ISSUE TITLE
Status Line Separator Error

### ISSUE THREAD

**Issue by shishaofengap** [wsdjeg/SpaceVim#3835]
### Reality

 init.toml

```
    statusline_separator='slant'
    statusline_iseparator='slant'
```

The bottom **statusline** has not changed

![image](https://user-images.githubusercontent.com/28386157/94135389-fb6c9180-fe95-11ea-9224-be19687fdded.png)

### Try to fix

```
diff --git a/autoload/SpaceVim/layers/core/statusline.vim b/autoload/SpaceVim/layers/core/statusline.vim
index ba7e95fb..1539e387 100644
--- a/autoload/SpaceVim/layers/core/statusline.vim
+++ b/autoload/SpaceVim/layers/core/statusline.vim
@@ -88,9 +88,6 @@ let s:loaded_sections = ['syntax checking', 'major mode', 'minor mode lighters',
 let s:loaded_sections_r = g:spacevim_statusline_right_sections
 let s:loaded_sections_l = g:spacevim_statusline_left_sections
 
-let [s:lsep , s:rsep] = get(s:separators, g:spacevim_statusline_separator, s:separators['arrow'])
-let [s:ilsep , s:irsep] = get(s:i_separators, g:spacevim_statusline_iseparator, s:i_separators['arrow'])
-
 if SpaceVim#layers#isLoaded('checkers')
   call add(s:loaded_modes, 'syntax-checking')
 endif
@@ -667,6 +664,10 @@ function! SpaceVim#layers#core#statusline#rsep() abort
 endfunction
 
 function! SpaceVim#layers#core#statusline#config() abort
+
+  let [s:lsep , s:rsep] = get(s:separators, g:spacevim_statusline_separator, s:separators['arrow'])
+  let [s:ilsep , s:irsep] = get(s:i_separators, g:spacevim_statusline_iseparator, s:i_separators['arrow'])
+
   call SpaceVim#mapping#space#def('nnoremap', ['t', 'm', 'm'], 'call SpaceVim#layers#core#statusline#toggle_section("minor mode lighters")',
         \ 'toggle the minor mode lighters', 1)
   call SpaceVim#mapping#space#def('nnoremap', ['t', 'm', 'M'], 'call SpaceVim#layers#core#statusline#toggle_section("major mode")',
```

![image](https://user-images.githubusercontent.com/28386157/94135617-4c7c8580-fe96-11ea-926b-199803782051.png)

**Comment by wsdjeg** [comment]
@ssfzxc Thanks, It is a bug, I will fix it.

**Comment by wsdjeg** [comment]
@ssfzxc I can not reproduce it. what is your config? and what is your debug info? With folowing config:

```
# SpaceVim options {{{
[options]
    enable_statusline_mode = true
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
    statusline_separator='slant'
    statusline_iseparator='slant'
    buffer_index_type = 0
    default_indent = 4
```

![image](https://user-images.githubusercontent.com/13142418/94151591-2e6e4f80-fead-11ea-8f2d-72ed1f66bf3b.png)

**Comment by shishaofengap** [comment]
@wsdjeg  I'm Sorry,  This is Screenshot error

### vim

![image](https://user-images.githubusercontent.com/28386157/94214496-4e812b80-ff0c-11ea-883c-ad43b585948d.png)

### gvim 

![image](https://user-images.githubusercontent.com/28386157/94214619-a28c1000-ff0c-11ea-9797-81c63dd9224d.png)


###  Vim  Version

![image](https://user-images.githubusercontent.com/28386157/94214566-78d2e900-ff0c-11ea-8a66-5104c3f8e069.png)

![image](https://user-images.githubusercontent.com/28386157/94214679-c5b6bf80-ff0c-11ea-9f06-425016f93020.png)

**Comment by wsdjeg** [comment]
I think your configuration is not loaded, you can copy following into spacevim configuration, and restart vim.

```
# SpaceVim options {{{
[options]
    enable_statusline_mode = true
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
    statusline_separator='slant'
    statusline_iseparator='slant'
    buffer_index_type = 0
    default_indent = 4
```

**Comment by femtomatic** [comment]
Hi, I had the same problem as @ssfzxc, I'm not sure why the issue is closed. I changed my configuration to the values suggested by @wsdjeg but it did not work, but when I tried the patch suggested by @ssfzxc it corrected the situation.

**Comment by wsdjeg** [comment]
But I can not reproduce it, the statusline script is loaded after custom config, so, the configuration should be loaded.

**Comment by nedludd** [comment]
I have the same issue.  Replaced my entire config with the one you specified above @wsdjeg.

-------------------------------------------------------
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -clipboard         -dnd               +gettext           +listcmds          -mouse_sysmouse    +postscript        +spell             +textobjects       +wildignore
+arabic            +cmdline_compl     -ebcdic            -hangul_input      +localmap          +mouse_urxvt       +printer           +startuptime       +textprop          +wildmenu
+autocmd           +cmdline_hist      +emacs_tags        +iconv             +lua/dyn           +mouse_xterm       +profile           +statusline        +timers            +windows
+autochdir         +cmdline_info      +eval              +insert_expand     +menu              +multi_byte        +python/dyn        -sun_workshop      +title             +writebackup
-autoservername    +comments          +ex_extra          +ipv6              +mksession         +multi_lang        +python3/dyn       +syntax            -toolbar           -X11
-balloon_eval      +conceal           +extra_search      +job               +modify_fname      -mzscheme          +quickfix          +tag_binary        +user_commands     -xfontset
+balloon_eval_term +cryptv            -farsi             +jumplist          +mouse             +netbeans_intg     +reltime           -tag_old_static    +vartabs           -xim
-browse            +cscope            +file_in_path      +keymap            -mouseshape        +num64             +rightleft         -tag_any_white     +vertsplit         -xpm
++builtin_terms    +cursorbind        +find_in_path      +lambda            +mouse_dec         +packages          +ruby/dyn          +tcl/dyn           +virtualedit       -xsmp
+byte_offset       +cursorshape       +float             +langmap           +mouse_gpm         +path_extra        +scrollbind        +termguicolors     +visual            -xterm_clipboard
+channel           +dialog_con        +folding           +libcall           -mouse_jsbterm     +perl/dyn          +signs             +terminal          +visualextra       -xterm_save
+cindent           +diff              -footer            +linebreak         +mouse_netterm     +persistent_undo   +smartindent       +terminfo          +viminfo
-clientserver      +digraphs          +fork()            +lispindent        +mouse_sgr         +popupwin          -sound             +termresponse      +vreplace

![2020-10-25-111437_1920x1080_scrot](https://user-images.githubusercontent.com/17875/97111185-cb422980-16b3-11eb-9448-1ab65bbb658a.png)

**Comment by julytang** [comment]
@wsdjeg this bug shows on vim 8.2 2200. And vim 8.2 850 works fine without this bug. I think this bug is produced by new version of vim

**Comment by dylanbmorgan** [comment]
> I think your configuration is not loaded, you can copy following into spacevim configuration, and restart vim.
> 
> ```
> # SpaceVim options {{{
> [options]
>     enable_statusline_mode = true
>     enable_tabline_filetype_icon = true
>     enable_os_fileformat_icon = true
>     statusline_unicode_symbols = true
>     statusline_separator='slant'
>     statusline_iseparator='slant'
>     buffer_index_type = 0
>     default_indent = 4
> ```

Copied this config and not getting slants either

**Comment by HaxNet** [comment]
anyone figure this out yet? I can't get the bottom status line to even have the arrow. It is always the bar

**Comment by thawk** [comment]
I can confirm this with vim 8.2.2637. @wsdjeg 

In my nvim, it seems status_line.vim is loaded twice instead of once.  First with "nil", second with "arrow".  So the status line is correct after the second load.

But in vim, status_line.vim is loaded just once.  It's loaded from main.vim[66] -> SpaceVim#begin[76] -> Spacevim#default#layers[8] -> SpaceVim#layers#load[7].  And the init.toml is loaded from main.vim[68] -> SpaceVim#custom#load, right after loading status_line.vim.  So the setting inside init.toml doesn't take effect in my vim.

I don't know why nvim load status_line.vim twice, but I think it should load it before processing user configuration.

**Comment by wsdjeg** [comment]
@thawk Thanks, script in spacevim should not be loaded twice. I will try to fix it.
