### ISSUE TITLE
Open from flygrep buffer into new tab

### ISSUE THREAD

**Issue by Zamua** [wsdjeg/SpaceVim#3836]
**Is your feature request related to a problem? Please describe.**
When using flygrep, opened files open on top of the current window. Jumping back and forth can be cumbersome.

**Describe the solution you'd like**
I would like to be able to open files from the flygrep buffer into a new tab. Proposed shortcut is shift+enter (if possible)

**Describe alternatives you've considered**
Currently I use SPC j b and SPC j f to jump between the flygrep file and existing file

**Additional context**
none

**Comment by wsdjeg** [comment]
currently, only support one key binding to open item. it is `<Enter>`, and it will open the file in current window and jump to the position of the item. the command to open the file is `:edit {file name}`.

To open it in other window, for example, `split`, `vsplit` or `tabedit`. we need to add new commands:

in fuzzy finder layer, for example [denite](https://spacevim.org/layers/denite/):


key binding | description
-- | --
`<Enter>` | Run default action
`Ctrl-t` | Open in a new tab
