### ISSUE TITLE
Add an option to choose c++ standard

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3842]
**Is your feature request related to a problem? Please describe.**
g++ defaults to C++ 98, so when I run a C++ source file using the runner, it always failed to compiled.

**Describe the solution you'd like**
As the document in ``lang/c.vim``, when ``tweekmonster/deoplete-clang2`` is used, ``g:deoplete#sources#clang#std`` can be used to set C++ standard.  Why not add an common option (``cpp_std`` or something) to ``lang/c.vim`` layer, and use it for both runner/repl/checker/lsp ?

**Describe alternatives you've considered**
Have a way to change ``opt`` for specified runner can be another way.

**Comment by wsdjeg** [comment]
in `lang#c` layer, this function has been register to project manager,

```
function! s:update_clang_flag() abort
  if filereadable('.clang')
    let argvs = readfile('.clang')
    call s:update_checkers_argv(argvs, ['c', 'cpp'])
    call s:update_autocomplete_argv(argvs, ['c', 'cpp'])
    call s:update_neoinclude(argvs, ['c', 'cpp'])
  endif
endfunction
```

Thats means, if there is `.clang` file in the root, the options in `.clang` file should be applayed to the language tools. 

I will open new PR to update this feature.

**Comment by wsdjeg** [comment]
With #3847, create a `.clang` file in the root of your project, and add following context

```
-std=c11
```

then the code runner, will read the file as options.

```
[Compile] ['gcc', '-o', 'C:/Users/wsdjeg/AppData/Local/Temp/nvimWVubqS/2', '-std=c11', '-xc', '-', 'STDIN']
[Running] C:/Users/wsdjeg/AppData/Local/Temp/nvimWVubqS/2

--------------------
hello, world!

[Done] exited with code=0 in 0.176443 seconds
```

**Comment by thawk** [comment]
Sorry, maybe I am missing somthing, but I didn't found the code in ``lang/c.vim`` to update  ``s:clang_std``.  When I set ``clang_std`` in the ``init.toml``, the option used by the runner is not changed.
BTW, not all g++ version supports ``c++1z``, but I haven't found the way to tell g++ to use latest standard it supported like msvc.
