### ISSUE TITLE
再s+o之后打开tagbar窗口和vimfiler窗口，窗口位置错乱

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#385]
这个问题复现非常简单，所以我就不截图了，环境是nvim ，ubuntu,在我打开vi编写代码时候，想关掉tagbar和vimfiler窗口，于是用了spacevim提供的s+o快捷键，非常方便，但是再我关掉之后再f2+f3打开tagbar和vimfiler时，发现窗口位置错乱

**Comment by wsdjeg** [comment]
@Shougo

I test this issue with Tagbar and nerdtree, it does not happened, here is a video

https://asciinema.org/a/9vvnhsk2dx6x78mexc2ktvaxe

I think maybe it is because vimfiler do not update the width of other buffers when use `:only` command.

**Comment by Shougo** [comment]
@wsdjeg Please create new issue and the minimal vimrc and the reproduce ways without SpaceVim.
I will test it.

**Comment by v-leonhou** [comment]
i haved tested nerdtree too, when i use nerdtree ,got no problem,so it's vimfiler's problem @wsdjeg

**Comment by Shougo** [comment]
I cannot fix the problem.  Because, @wsdjeg does not create the minimal vimrc and the reproduce ways.

**Comment by wsdjeg** [comment]
I will create minivimrc latter, please wait. now  I am working on ui for dein.

**Comment by Shougo** [comment]
OK.

**Comment by v-leonhou** [comment]
这个问题解决了么？@wsdjeq

**Comment by wsdjeg** [comment]
```viml
set rtp+=~/.cache/vimfiles/repos/github.com/majutsushi/tagbar/
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/vimfiler.vim/
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/unite.vim/
call vimfiler#custom#profile('default', 'context', {
      \ 'explorer' : 1,
      \ 'winwidth' : 30,
      \ 'winminwidth' : 30,
      \ 'toggle' : 1,
      \ 'auto_expand': 1,
      \ 'direction' : 'rightbelow',
      \ 'parent': 0,
      \ 'status' : 1,
      \ 'safe' : 0,
      \ 'split' : 1,
      \ 'hidden': 1,
      \ 'no_quit' : 1,
      \ 'force_hide' : 0,
      \ })
let g:tagbar_left = get(g:, 'tagbar_left', 1)
let g:tagbar_sort = get(g:, 'tagbar_sort', 0)
let g:tagbar_compact = get(g:, 'tagbar_compact', 1)
```

reprodoce step:
1. vim -u test.vim test.md
2. :Vimfiler
3. :Tagbar
4. `<ctrl+w><left>`, to move cursor to test.md buffer.
5. :only
6. :Tagbar
7. :Vimfiler

**Comment by Shougo** [comment]
OK, I will try it.

**Comment by Shougo** [comment]
I have reproduced the problem.

**Comment by v-leonhou** [comment]
can you fix it? @Shougo

**Comment by Shougo** [comment]
Yes.  I will fix it later.

**Comment by Shougo** [comment]
I have fixed the problem.
Please update vimfiler.

**Comment by v-leonhou** [comment]
got it ,thanks
