### ISSUE TITLE
vscode 和 vim用户的一些建议

### ISSUE THREAD

**Issue by minrui-hust** [wsdjeg/SpaceVim#3851]
来来回回在vscode 和vim之前横跳了很多次。我总结了一下我横跳的原因，只说最重要的：
各自劣势：
vscode：无法手不离键
vim：没有统一的插件setting方式，各个插件各有个的风格

核心优势
vscode 统一的插件管理系统，下载统一，配置方式统一，同时功能丰富
vim 的核心优势是键不离手

如果有vim的发行版本能够兼顾两者的优势，那么我觉得就是心目中理想的vim。

spacevim，通过屏蔽掉了原生插件的很多功能来统一配置，感觉有些因噎废食。
个人觉得，应该往coc.nvim的路上走，统一所有插件的setting。要让插件的功能多样性释放，屏蔽掉配置方式的多样性。

**Comment by wsdjeg** [comment]
谢谢，其实我觉得 Vim 插件配置方式是使用 Vim 脚本，相比 vscode 以及 coc 的 json 文件，要更加灵活，因为 json 的值类型有限，使用 Vim 脚本甚至可以定义一些临时函数等等。


SpaceVim 目前除了支持 toml（类似于 json，至少语法含义上一样） 配置之外，还支持启动函数里写 Vim 脚本，并未像你所说的，屏蔽掉插件原生功能，你一样可以正常使用。当然，如果遇到不能使用的功能，可以提交issue。

此外，SpaceVim 支持 coc，默认未使用罢了，因为我还没找到何时的兼容方式，可以自行启用，配置。

最后，感谢提出意见，不过github issue 仅限于英文交流，如果需要中文交流，可以使用 gitee。
