### ISSUE TITLE
The syntax checking section of statusline with ale don't work well

### ISSUE THREAD

**Issue by mrbeardad** [wsdjeg/SpaceVim#3856]
## Expected behavior, english is required
The syntax checking section of statusline with ALE should be updated after ale linted.

## The reproduce ways from Vim starting (Required!)
1. `nvim test.cpp`
2. insert some code with error syntax which is like `std::cout <<;`
3. Trigger ALE to lint current buffer
4. ale goes right but the syntax checking section of statusline is didn't updated

To fix it:
```diff
@@ -119,7 +126,7 @@ function! SpaceVim#layers#checkers#config() abort
         endif
       endif
     elseif g:spacevim_enable_ale && SpaceVim#layers#isLoaded('core#statusline')
-      autocmd User ALELint
+      autocmd User ALELintPost
             \ let &l:statusline = SpaceVim#layers#core#statusline#get(1)
     endif
   augroup END
```

**Comment by wsdjeg** [comment]
as I remember, it works in old version of ale, maybe it is because ale change the autocmd event name?

**Comment by wsdjeg** [comment]
fixed! https://github.com/SpaceVim/SpaceVim/blob/1629ba4c92473f17de61246ee963730b9771ba70/autoload/SpaceVim/layers/checkers.vim#L170
