### ISSUE TITLE
SpaceVim - Copy text on selection is not working 

### ISSUE THREAD

**Issue by m-stojanovic** [wsdjeg/SpaceVim#3861]
## Expected behavior, English is required
Before, installing SpaceVim, it was possible to copy the text on the highlight
Tested this on a few different terminals. Always the same result.
After I highlight the text, it is not possible to paste it anywhere. 
I went through the whole SpaceVim Documentation, but the copy on highlight is not mentioned. 
I don't need other options to copy text with keyboard shortcuts. I m asking, is this possible to do by adding some custom options?
**Copy on the selection option** is not working in SpaceVim. 

## The reproduce ways from Vim starting (Required!)
```
1. vim testfile.txt
2. Highlight some text you want to copy to the clipboard
3. Paste it anywhere on the terminal, Computer or Browser, etc.
```
## Debug info
- It worked normally in Vim ( before I have installed SpaceVim ) 
- It still works when I highlight text on my terminal outside of the SpaceVim ( so it is not a terminal issue )
- Tried on both bash and zsh shell ( so it is not a shell issue ) 
- It just doesn't work in SpaceVim

## Screenshots
![image](https://user-images.githubusercontent.com/56040933/94989516-bc190180-0575-11eb-99c8-26268d4168a3.png)

**Comment by wsdjeg** [comment]
What is `Copy on the highlight option`?

how did you highlight text?

**Comment by m-stojanovic** [comment]
It's an option that is available on every terminal. Maybe better is to say 'Copy on selection'. Its an option that every terminal has. 
But that option is not working in SpaceVim. So when I do the selection of a text in SpaceVim, it is not copied to the clipboard and I can't paste it anywhere. 
I highlighted the text with a mouse cursor
I will correct the title to 'selection'.

**Comment by wsdjeg** [comment]
Sorry, I do not use this feature, so I do not know why it does not work, maybe because we have `set mouse=a` by default, can you check `set mouse=`?

**Comment by m-stojanovic** [comment]
Yes, I can. 
`set mouse=nv`
Do you have a suggestion what should be the value to enable copy on selection option?
![image](https://user-images.githubusercontent.com/56040933/94994274-dfa07400-0596-11eb-8519-63eba3c0db47.png)

**Comment by m-stojanovic** [comment]
Ok an update, I made it work bu removing `'=nv' `part on `set mouse` settings. 
But after I have done that, every time I want to open a file with vim, I get 
`Press ENTER or type command to continue`
After I Press ENTER, I enter SpaceVim and I can do copy on selection. But, I have to press enter before opening any file. Do you have any suggestions for this?
![image](https://user-images.githubusercontent.com/56040933/94994445-eb406a80-0597-11eb-8c17-db838cf4b283.png)

**Comment by m-stojanovic** [comment]
Ok, I have corrected that setting and returned the `=` sign.
So now the setting looks like `set mouse=`
And the problem is solved! I can enter SpaceVim without need to `Press ENTER or type command to continue`
And I can do a copy on the selection inside of SpaceVim.
It is also possible to do `set mouse=v or set mouse=r`, and it will work too!
Thanks, @wsdjeg on pointing me to the correct setting!
