### ISSUE TITLE
How to permanently remove line numbers in SpaceVim?

### ISSUE THREAD

**Issue by m-stojanovic** [wsdjeg/SpaceVim#3870]
## Expected behavior, english is required
I need to **permanently** remove line numbers in SpaceVim.

## The reproduce ways from Vim starting (Required!)
Solutions that I have tried:
```
set nonu
set nonumber
set nu
relativenumber = "false"
nonu = "true"
nu = "false"
nonumbers = "true"
```
## Debug info
None of the above solutions is working. They work only for the currently opened session in the SpaceVim.
I need a solution that will work permanently, s**o whenever SpaceVim is opened, those line numbers are already removed.** 
It's not practical to remove line numbers each time SpaceVim is opened.
Does anyone have suggestions on how to solve this problem?
Please press <kbd>SPC h I</kbd>, debug info will be put into the clipboard, then paste all content below.

## Screenshots

![image](https://user-images.githubusercontent.com/56040933/95177266-4a7fc400-07be-11eb-9788-5a7cc6377a54.png)

**Comment by wsdjeg** [comment]
Use bootstrap function to `set nonumber`
