### ISSUE TITLE
Send additional contents for REPL

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3882]
**Is your feature request related to a problem? Please describe.**
When I use [``Standard ML``](https://www.smlnj.org), the Interactive System requires:
> Input to the top level interpreter (i.e., declarations and expressions) **must be** terminated by a semicolon (and carriage return) before the system will evaluate it.

So the code ``val foo = 1 + 1`` in the source file should be sent as ``val foo = 1 + 1;`` to tell the system to evaluate it.  (The ``;`` can be place after the newline)

**Describe the solution you'd like**
An additional argument for ``SpaceVim#plugins#repl#send(type)`` can be used to send addtional contents.

* for empty string, just work the old way
* for a string, append it to the contents
* for a function, call the function with contents, using the return value as actual content to be sent.  It let the layer author do anything needed, not just appending a semicolon

**Describe alternatives you've considered**
Add an API to send plain strings, so layer author can bind a new hotkey to send a semicolon or something as needed.

**Additional context**
The [REPL module](https://github.com/jez/vim-better-sml/blob/master/autoload/bettersml/repl.vim) of [vim-better-sml](https://github.com/jez/vim-better-sml) plugin constructs and send specified contents not in the buffer to easy development.

**Comment by wsdjeg** [comment]
I think there are too many case we need to cover, add extra string `;`, call function etc. the best way is adding a new repl api, for plugin developer to send plain strings.

**Comment by thawk** [comment]
I agree.  I suggest to provide a way to prevent plugin developers handling line/buffer/selection.  Some helper functions should be helpful.

**Comment by wsdjeg** [comment]
@thawk instead of adding new function, improve existing function with backword compatible is better. so I create a new [PR](https://github.com/SpaceVim/SpaceVim/pull/3884) for this feature. with this PR, you can use `raw` type with second argv.

this PR will not break old key bindings and private layer.

for the case you need in sml:

```vim
call SpaceVim#plugins#repl#send('raw', getline('.') . ';')
```

**Comment by thawk** [comment]
I think it is better to extract the following code to a function to avoid unnessary code repeat:

```vim
    if a:type ==# 'line'
      call s:JOB.send(s:job_id, [getline('.'), ''])
    elseif a:type ==# 'buffer'
      call s:JOB.send(s:job_id, getline(1, '$') + [''])
    elseif a:type ==# 'selection'
      let begin = getpos("'<")
      let end = getpos("'>")
      if begin[1] != 0 && end[1] != 0
        call s:JOB.send(s:job_id, getline(begin[1], end[1]) + [''])
      else
        echohl WarningMsg
        echo 'no selection text'
        echohl None
      endif
    endif
```

**Comment by wsdjeg** [comment]
Hmm, sorry, I do not understand, which part of code is repeat?

**Comment by thawk** [comment]
By using the new ``raw`` mode, we need to handle content range (``line``/``buffer``/``selection``) correctly.  The code used is almost the same as in repl.vim.  If we have a function, like ``get_repl_content()``, we can just:

```vim
  call SpaceVim#mapping#space#langSPC('nmap', ['l','s', 'l'],
        \ 'call SpaceVim#plugins#repl#send("raw", get_repl_content("line") . ";")',
        \ 'send line and keep code buffer focused', 1)
  call SpaceVim#mapping#space#langSPC('nmap', ['l','s', 'b'],
        \ 'call SpaceVim#plugins#repl#send("raw", get_repl_content("buffer") . ";")',
        \ 'send buffer and keep code buffer focused', 1)
  call SpaceVim#mapping#space#langSPC('nmap', ['l','s', 's'],
        \ 'call SpaceVim#plugins#repl#send("raw", get_repl_content("selection") . ";")',
        \ 'send selection and keep code buffer focused', 1)
```

If we don't do so much checking like in ``repl.vim``, it's not so hard to implement with ``get_repl_content()``.  But it can make our lives easier, and if we support more selection mode latter, it's easier to extend.

**Comment by wsdjeg** [comment]
It is not same, job.send use list as second argv, we need to build argv before run job,send.

in repl#send function. we check `a:type == line` first, because this is top used case. and then check `a:type == raw`.

in viml if a:type == line, the vim script in other case will not be executed, it will be faster. 

if we implement `get_repl_context` function, I think we do not need the first argv, just `send(get_repl_context() . ';')`, but this will breack the compatible.

BTW, `getline('.')` and `getline(1, '$')` is faster than wrap a outer function, I think.

**Comment by thawk** [comment]
To avoid breaking compatible, we can add a new function, like ``send_raw()``.  But current PR version is good enough to support my requirement.

**Comment by wsdjeg** [comment]
@thawk yeah, my first commit of this pr is adding `send_raw(str)` function, but I do not want to create two public apis for one function, It will increase the doc. in this PR, I add a `:h spacevim-usage-repl` for using repl public api. this is under `spacevim-usage` section. `spacevim-usage` should cover all context in `use-vim-as-ide` post in website.

**Comment by thawk** [comment]
@wsdjeg It's better support list of string for ''raw" mode.  I found that, I must join lines using ``\r`` instead of ``\n`` to make sml work in neovim in my MacOS.  I think it's better to let vim join the strings itself.

**Comment by wsdjeg** [comment]
raw means the really context of the sended text including line end. users who want to build the context should consider what os they are using.

I do not test in mac os. But if the type is selection, is try to send list to repl. can you test if it works for you?

maybe a new issue for this, I think the topic is not same.
