### ISSUE TITLE
Add a cheatsheet for every compound shortcut

### ISSUE THREAD

**Issue by Eisiem** [wsdjeg/SpaceVim#3883]
I find SV pop-up cheatsheets for _SPC_, _g_ and _z_ very helpful, and I think having one for every compound key (_y_, _d_, _c_, etc.) could improve discoverability and help newcomers.

Of course this could be quite annoying if one already knows vim well. For that reason I think it should be a setting on the config file, and maybe an option when starting SV for the first time.

**Comment by wsdjeg** [comment]
@Eisiem Vim does not have key binding with _d_, _y_ prefix. after press `d` in normal node, it is operater mode. in this mode, you can use text opject and movement. for example `diw`. `diw` is not a full key binding, it is not same as `gj` etc.

**Comment by Eisiem** [comment]
@wsdjeg I see... And there is no way to work around it and accomplish the feature request?

**Comment by wsdjeg** [comment]
yeah, we can not add this.
