### ISSUE TITLE
job.send() shouldn't convert string to list

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3887]
Using ``repl#send('raw')`` to send a multi-line string, it should send out a multi-line string.  But in the result, newlines are replaced by ``NUL``(``0x00``).

* ``:help chansend()`` says, **"any newlines in an item (of list) will be sent as NUL"**:

  > {data} may be a string, string convertible, or a list.  If
  > {data} is a list, the items will be joined by newlines; any
  > newlines in an item will be sent as NUL. 

* ``job.send()`` converts argument of type ``string`` into ``list`` for neovim:
  ```vim
  if self.nvim_job
    if has_key(self.jobs, a:id)
      if type(a:data) == type('')
        call jobsend(a:id, [a:data, ''])
      else
        call jobsend(a:id, a:data)
      endif
  ```

* Any raw string contains ``\n`` will be convert to a list by job api, thus all newlines are replaced by NULs by neovim

``job.send()`` should simply append a ``\n`` to string argument, it should works as expected.

**Comment by wsdjeg** [comment]
ok, merged, thanks.
