### ISSUE TITLE
gvim 8.2 not installing spacevim plugin after first startup

### ISSUE THREAD

**Issue by tnmeesters** [wsdjeg/SpaceVim#3894]
I tried the following solution.

https://github.com/SpaceVim/SpaceVim/issues/3250

But it did not work for me.
Any ideas what might be done?

Thank you.

**Comment by wsdjeg** [comment]
first, you should at least post what os you are using:

**Windows**

1. the default config of vim is `~/_vimrc`, you should remove/rename it, and let vim skip this position.
2. after run install.cmd, there should be a `~/vimfiles` which is a link to `~/.SpaceVim`, if there is not, you can create it with `mklink` command.

**Linux/mac**

1. install.sh should be able to rename `~/.vimrc` to `~/.vimrc_back`, and everything should works well.

**Comment by Marcalitus** [comment]
> first, you should at least post what os you are using:
> 
> **Windows**
> 
> 1. the default config of vim is `~/_vimrc`, you should remove/rename it, and let vim skip this position.
> 2. after run install.cmd, there should be a `~/vimfiles` which is a link to `~/.SpaceVim`, if there is not, you can create it with `mklink` command.
> 
> **Linux/mac**
> 
> 1. install.sh should be able to rename `~/.vimrc` to `~/.vimrc_back`, and everything should works well.

![image](https://user-images.githubusercontent.com/45339914/99733519-54d9f100-2ad2-11eb-9939-7e170a540e60.png)

It still isn't working for me even though I followed these steps.

**Comment by Marcalitus** [comment]
> first, you should at least post what os you are using:
> 
> **Windows**
> 
> 1. the default config of vim is `~/_vimrc`, you should remove/rename it, and let vim skip this position.
> 2. after run install.cmd, there should be a `~/vimfiles` which is a link to `~/.SpaceVim`, if there is not, you can create it with `mklink` command.
> 
> **Linux/mac**
> 
> 1. install.sh should be able to rename `~/.vimrc` to `~/.vimrc_back`, and everything should works well.

![image_2020-11-20_014837](https://user-images.githubusercontent.com/45339914/99733629-818e0880-2ad2-11eb-8958-02397cacaae6.png)

I followed these steps and my vim is still not install the plugin nor is it working to link them. I also did these in command prompt admin mode.
