### ISSUE TITLE
[SpaceVim] Remove Vertical highlighted indent lines with bootstrap function

### ISSUE THREAD

**Issue by m-stojanovic** [wsdjeg/SpaceVim#3907]
### Expected behavior, English is required
I need to permanently remove ident highlighted vertical lines in SpaceVim.
I need a config option that replicates the **SPC t h i**
With **SPC t h i** I can remove vertical indent highlighted lines. But I need that to do before I open a file with SpaceVim.
For that, I use bootstrap functions. But I don't know how to represent **SPC t h i** in bootstrap function.

### The reproduce ways from Vim starting (Required!)
Solutions that I have tried:

function! myspacevim#before() abort
  set indentkeys-=0#     
endfunction

### Debug info
The solution is not working.
I need a solution that will work permanently, so whenever SpaceVim is opened, those vertical highlighted lines are already removed.

Does anyone have suggestions on how to solve this problem?

### Screenshoots
![image](https://user-images.githubusercontent.com/56040933/96255605-7c133f00-0fb7-11eb-8276-046b20954d53.png)

**Comment by wsdjeg** [comment]
```toml
[[layers]]
  name = "ui"
  enable_sidebar = false
  enable_indentline = false
```

**Comment by m-stojanovic** [comment]
> ```toml
> [[layers]]
>   name = "ui"
>   enable_sidebar = false
>   enable_indentline = false
> ```

Hello @wsdjeg 

I have tried your suggestion, but it is not working. 
Becides 
```
[[layers]]
  name = "ui"
  enable_sidebar = false
  enable_indentline = false
```

I have tried also 
```
[options]
  enable_sidebar = false
  enable_indentline = false
```

```
[options]
indentline_char = ' '
```

But non of the solutions is not working, Can you still help me to find the proper one?
![image](https://user-images.githubusercontent.com/56040933/96373292-dbb24b80-116b-11eb-8ea1-2355f6f87283.png)
