### ISSUE TITLE
keep original key-binding 

### ISSUE THREAD

**Issue by leiwang-ninjia** [wsdjeg/SpaceVim#391]
## Expected behavior, english is recommend
keep original key-binding 

## Environment Information
- OS:ubuntu 16.04 
- vim version:8.0
- neovim version:NA

## The reproduce ways from Vim starting (Required!)
it seems a little clumsy for guys who already accustomed with classical key-bindings.

1. can you use lead q for smart Close, keep a as original register 
call SpaceVim#mapping#def('nnoremap <silent>', '\<leader\>q', ':<C-u>call zvim#util#SmartClose()<cr>'

2. for quickfix next/before,  i think **]q/[q** is classical. (i can't remember who define this, seems tpope)
_---  call SpaceVim#mapping#def('nnoremap', '\<Leader\>qj', ':cnext<CR>',_
+++ call SpaceVim#mapping#def('nnoremap', ']q', ':cnext<CR>'
 \ 'Jump to next quickfix list position',

3. change qq meaning 
---  call SpaceVim#mapping#def('nnoremap', '\<Leader\>qq', ':cclose<CR>',
+++  call SpaceVim#mapping#def('nnoremap', '\<Leader\>qq', ':q!<CR>',
         \ 'Close quickfix list window',
## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
1. I use smartclose more than 300 times a day, but the origin `q`, only less than 20 times, so I map q as smartclose, and the origin function of q is `\qr`.

2. for quickfix, why I use `\qj/k`? It is easy to manager via key guide, and for location-list you can use `\lj/k`. please just type `\q`, and wait for about 1s, you will see the guide. I never use `]q/[q` before, If user like it, we can add this mapping to spacevim. but as `]q/[q` is for quickfix, how about location-list?

**Comment by leiwang-ninjia** [comment]
ok

**Comment by leiwang-ninjia** [comment]
2. for quickfix, why I use \qj/k? It is easy to manager via key guide, and for location-list you can use \lj/k. please just type \q, and wait for about 1s, you will see the guide. I never use ]q/[q before, If user like it, we can add this mapping to spacevim. but as ]q/[q is for quickfix, how about location-list?
 ]q/[q is for quickfix  ]l/[l for localtion-list,

3, Also can you add region-expand feature , v/V for xmap exapnd/shrink region, thanks

	xmap v <Plug>(expand_region_expand)
	xmap V <Plug>(expand_region_shrink)

**Comment by wsdjeg** [comment]
hmm, I can add `[q/]q` and `[l/]l`.

what is `<Plug>(expand_region_expand)` and `<Plug>(expand_region_shrink)`?

**Comment by leiwang-ninjia** [comment]
for expand visual region, something like this .
vim-expand-region can be seen in your doc, it seems it still not enabled yet.
if dein#tap('vim-expand-region') "{{{
	xmap v <Plug>(expand_region_expand)
	xmap V <Plug>(expand_region_shrink)
endif

**Comment by wsdjeg** [comment]
I use dein hooks for load plugin's config, the config only be loaded when the plugin is loaded, so no need use `dein#tab` to check install. 

hmm, I will look into this plugin.

**Comment by wsdjeg** [comment]
oh, sorry, I just delete this plugin sometimes, and I am looking for this plugin for long time, will add it.

**Comment by wsdjeg** [comment]
@leiwang-ninjia I have added the plugin via #394 , can you test it?

**Comment by leiwang-ninjia** [comment]
it works , thanks

**Comment by wsdjeg** [comment]
ok. I will merge it. Anything else need to be fixed?
