### ISSUE TITLE
Initialization Error on Windows 10

### ISSUE THREAD

**Issue by Anogoya-Dagaate** [wsdjeg/SpaceVim#3912]
## SpaceVim Fails During Initial Set-up for Downloading Plugins
Setting up SpaceVim on Windows 10 an initialization error is generated as follows:
I fixed the problem by editing the culprit file to comment out all references to "_spacevim_if_lua"
Just reporting it to help other Windows users.

## The reproduce ways from Vim starting (Required!)
1. Launch gVim after following the instructions at https://spacevim.org/quick-start-guide/#windows
2. The attached error is generated

## Debug info
Error detected while processing ~/.spacevim/autoload/SpaceVim/api/vim/window.vim:

line 43:
E121: Undefined variabble: g:_spacevim_if_lua
E15: Invalid expression: g:_spavevim_if_lua

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
![image](https://user-images.githubusercontent.com/20682130/96376091-f32d0c80-114a-11eb-8da5-5663aa423535.png)

![image](https://user-images.githubusercontent.com/20682130/96376253-c62d2980-114b-11eb-9564-0f2ff8617a90.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
`g:_spacevim_if_lua` has been definded in https://github.com/SpaceVim/SpaceVim/blob/4db31814e2489fea564995a3618f9496925e7eb9/vimrc, make sure your spacevim is latest version, and nothing has been changed in `~/.SpaceVim`.

**Comment by Anogoya-Dagaate** [comment]
Cool thanks, I'll check  it out if  that resolves  the  issue!
