### ISSUE TITLE
Change LSP server for PHP

### ISSUE THREAD

**Issue by gbprod** [wsdjeg/SpaceVim#3916]
The default [lsp server used for php](https://github.com/SpaceVim/SpaceVim/blob/751725315fe5f8147fd391fcd629dc06c52aa0af/autoload/SpaceVim/layers/lang/php.vim#L24) (https://github.com/felixfbecker/php-language-server) seems unmaintained and not working with php7.4.

Seems that [phpactor](https://github.com/phpactor/phpactor) is well maintained and have bundled [vim](https://github.com/phpactor/phpactor/blob/develop/plugin/phpactor.vim) and [coc](https://github.com/phpactor/coc-phpactor) plugins. I think we should replace usage of `felixfbecker/php-language-server` by `phpactor` in `lang#php` layer if `lsp` layer is active.

Regarding to [lsp implementation reference](https://microsoft.github.io/language-server-protocol/implementors/servers/), 2 other candidate could replace php-language-server : 
 
 - [intelephense](https://intelephense.com/) : works well but not as complete as phpactor and require a licence to access all functionnalities.
 - [Serenata](https://gitlab.com/Serenata/Serenata) but I can't manage to make it works with vim :sweat_smile: 

If it's ok, I could work on a PR :)

**Comment by wsdjeg** [comment]
feel free to send PR, Thanks.
