### ISSUE TITLE
[SpaceVim] Remove Vertical highlighted indent lines with bootstrap function #2

### ISSUE THREAD

**Issue by m-stojanovic** [wsdjeg/SpaceVim#3918]
## Expected behavior, english is required
This issue is related to https://github.com/SpaceVim/SpaceVim/issues/3907 as that one got closed and I haven't still found out the solution to the problem. Which I need very much. I have updated this one with more solutions that I have tried. Please check. Thank you!

I need to permanently remove ident highlighted vertical lines in SpaceVim.
I need a config option that replicates the SPC t h i
With SPC t h i I can remove vertical indent highlighted lines. But I need that to do before I open a file with SpaceVim.
For that, I use bootstrap functions. But I don't know how to represent SPC t h i in bootstrap function.
## The reproduce ways from Vim starting (Required!)
Solutions that I have tried:

```
function! myspacevim#before() abort
set indentkeys-=0#
endfunction

```
And I have tried the answer from @wsdjeg in my previous post, but it did not work for me. As the issue got closed, I had to open a new one to ask again for the help.
```[[layers]]
  name = "ui"
  enable_sidebar = false
  enable_indentline = false
```

I have tried also

```
[options]
  enable_sidebar = false
  enable_indentline = false

[options]
indentline_char = ' '
```

## Debug info
The solutions are not working.
I need a solution that will work permanently, so whenever SpaceVim is opened, those vertical highlighted lines are already removed.

Does anyone have suggestions on how to solve this problem?
## Screenshots

![image](https://user-images.githubusercontent.com/56040933/96704736-b0f70b80-1394-11eb-9856-7393d06e41d9.png)

**Comment by wsdjeg** [comment]
```
[[layers]]
    name = 'ui'
    enable_scrollbar = true
    enable_indentline = false
```

for me, this works fine, maybe you need to update spacevim.

**Comment by m-stojanovic** [comment]
I have updated the spacevim, still not working...
