### ISSUE TITLE
E121: Undefined variable: g:_spacevim_if_lua

### ISSUE THREAD

**Issue by sfengyuan** [wsdjeg/SpaceVim#3928]
## The reproduce ways from Vim starting (Required!)
1. Install the gvim on windows
2. run the installation batch files
3. add `:source ~/.spacevim/init.vim` in _vimrc
4. click the gvim shortcut
Then:
```
Error detected while processing C:\Users\MYNAME\.spacevim\autoload\Space
Vim\api\vim\window.vim:

line   43:

E121: Undefined variable: g:_spacevim_if_lua
```

## Debug info

Could not load spacevim feature

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please following the installation guide.

**Comment by emrea-works** [comment]
That error comes after adding the ``:source ~/.spacevim/init.vim`` as a solution of the issue : https://github.com/SpaceVim/SpaceVim/issues/3250 when we install spacevim 2.0.0
