### ISSUE TITLE
Typo on documentation "intallation instead of installation"

### ISSUE THREAD

**Issue by bjcross** [wsdjeg/SpaceVim#3933]
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by bjcross** [comment]
sed -i s/intallation/installation docs/install.cmd

**Comment by wsdjeg** [comment]
Thanks
