### ISSUE TITLE
Fuzzy finding of tags in all layers

### ISSUE THREAD

**Issue by chrisRidgers** [wsdjeg/SpaceVim#3936]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to navigate to code unrelated to the symbols described in the file you're currently editing.  (maybe you're looking at a template file but want to go to a controller).  In many editors, you would press a key, and type the name of the symbol you wanted to go to, with options being provided to you as you type.

As an example, in Webstorm (on a Mac): Cmd+O allows you to search class defintions, Cmd+Alt+O allows you to search symbols.

I'd like to be able to fuzzily search my projects symbols and jump to their defintions

**Describe the solution you'd like**

I'd like to be able to fuzzy search my entire project for symbols - being able to navigate to them as a result, and be able to do this consistently with any fuzzy matching layer.  Specifically though, I would like this working in the  layer suggested in the documentation: denite.  

As a bonus:

- I would like to be able to separately search classes from other symbols like functions
- I would like symbols to include base language symbols as well as my project symbols (possibly based on the loading of a specific `lang#...` layer.  Would presumably need to be able to resolve that languages files somewhere on the host system).
- Results found would be prioritized based on similarity and namespace, results in my projects namespace should come above similar matches in my vendor libraries etc (this may be php specific, but i suspect not would have to tie to `lang` layer?).

**Describe alternatives you've considered**

Currently in SpaceVim your options are (to my knowledge):

- Find files in project by file name (not too bad in my use case, normally my class names match my files names)
- Use the gtags layer to populate a quickfix list with tags, and the fuzzy search the quickfix results (works, but has too many steps)
- Navigate to definitions using the lsp layer (specifically phpactors commands which arent currently key map bound to my knowledge)
- Use the fzf fuzzy layer, which includes the keymap `leader f t` and appears to provide fuzzy tag searching. https://spacevim.org/layers/fzf/

I also noticed this denite plugin on the internet but I have not tested it: https://github.com/ozelentok/denite-gtags

**Additional context**

This may also come under the scope of feature request: https://github.com/SpaceVim/SpaceVim/issues/3795

Example of the flow using gtags layer and quick fix fuzzy matching:
![image](https://user-images.githubusercontent.com/5954265/98058054-ba27b400-1e3b-11eb-93a3-0ee7cfe04ca1.png)

Example of the flow using the fzf implementation:
![image](https://user-images.githubusercontent.com/5954265/98058123-dd526380-1e3b-11eb-94f8-f4fda41a06ad.png)

**Comment by thawk** [comment]
Agree.
I used [unite-gtags](https://github.com/hewes/unite-gtags) before using SpaceVim.  That plugin provides a ``gtags/completion`` to do fuzzy finding.  I perfer using lower/upper case hotkey for finding cword and fuzzy finding .
e.g. ``SPC m g d`` for finding definition of cword, and ``SPC m g D`` for fuzzy finding tags in project.

**Comment by wsdjeg** [comment]
@chrisRidgers @thawk Hi, in https://github.com/SpaceVim/SpaceVim/pull/3981 I have added a ctags manager, which will generate ctags database for current project and update the vim's `&tags` option, so you can use `ctrl-]` key binding, this is default key binding of vim. and you can also use `leader f t` key binding, but you need to enable the `leaderf` layer.

**Comment by chrisRidgers** [comment]
Ill give this a test this weekend
