### ISSUE TITLE
Saving a file with SpaceVim causes inotifywait to crash

### ISSUE THREAD

**Issue by lippirk** [wsdjeg/SpaceVim#3938]
I have a inotifywait loop running on a file, but when I save the file using SpaceVim, the loop crashes. The loop works correctly if I use a different editor, like mousepad

## Expected behavior, english is required
I expect to be able to run inotifywait without SpaceVim causing it to crash

## The reproduce ways from Vim starting (Required!)

In one shell session, run `touch /tmp/test && while inotifywait -e modify test; do cat test; done`.
In another shell session, run `vim /tmp/test`, modify the file, and then save it. I see that the while loop in the first shell crashes

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

(I tried the above but nothing was put into the clipboard, and I only see information about the different SpaceVim layers)

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by lippirk** [comment]
I find that `while inotifywait -e modify test || true; do cat test; done` _does_ work as expected. However I am still interested to know why vim causes `inotifywait -e modify test` to exit with code 1 rather than code 0

**Comment by wsdjeg** [comment]
@lippirk Did you have a try with `vim -u NONE /tmp/test`?
