### ISSUE TITLE
need the ability to copy text in vim

### ISSUE THREAD

**Issue by todd-dsm** [wsdjeg/SpaceVim#3945]
**ISSUE**
When I highlight text in the editor and go to copy it, I can't. The system just makes a noise to register that this operation is not supported and does not let me copy text from the window.

**SOLUTION**
copy text from the editor while in the system terminal; i.e.:

![image](https://user-images.githubusercontent.com/2463935/98455841-cdcc6680-212a-11eb-9a7c-3cda63f33fef.png)

**Describe alternatives you've considered**

**Additional context**
macOS Catalina (10.15.7). This _TEST_ account uses default shell, zsh; my _main_ account uses the bash shell. Using "Terminal" (system terminal) EDITOR=nvim (v0.4.4).
* The copy operation is attempted by using 2 fingers in the bottom right of the trackpad. 
* It also behaves this way with vim `+clipboard` enabled.
* If I were to open either vim or nvim and `:ve`, I would be able to highlight and copy from the version info buffer to the system clipboard.
* Were I to attempt this under my main profile, it would work with the same binaries.

![image](https://user-images.githubusercontent.com/2463935/98455930-bfcb1580-212b-11eb-9d01-3b0f96e99a79.png)

**Comment by gbprod** [comment]
I've you tried `<leader>-y` ? (See https://spacevim.org/documentation/#copy-and-paste)

**Comment by wsdjeg** [comment]
when using vim without `+clipboard` feature, maybe we can use `xsel` or `xclip` to community with system clipboard.

**Comment by lengyijun** [comment]
> I've you tried `<leader>-y` ? (See https://spacevim.org/documentation/#copy-and-paste)

If I use spacevim in ssh session, I can't copy the text into my local clipboard.

**Comment by wsdjeg** [comment]
Nothing can be done with spacevim, this is feature of vim, after running `:version`, the cmdline page is opened, it is not general buffer.

**Comment by todd-dsm** [comment]
Sorry it took so long to get back to this, I've created a few screen recordings. One is my vim build (vimSimple) and the other is SpaceVim, which which just will not copy text. 

vim copy in the terminal: pass https://youtu.be/CmVjROKOXZM (vimSimple)

vim copy in the terminal: fail https://youtu.be/L-_y3a86tcE (SpaceVim)

But, it's clear that the installed version of vim supports copy/pasting. This is a SpaceVim issue.

**Comment by mobailabs** [comment]
@todd-dsm +1
