### ISSUE TITLE
autocomplete for GNU Bash

### ISSUE THREAD

**Issue by todd-dsm** [wsdjeg/SpaceVim#3946]
**ISSUE**
I spend all day programming in bash; my [current setup] auto-completes common constructs for me, it produces a drop-down with previously defined variables and it's driven entirely by tabbing and filling in blanks. Example:
https://asciinema.org/a/371269

I'm terrible with vimL and it's difficult to maintain. 

**Describe the solution you'd like**
I would like to archive my project and use SpaceVim but I need to have equivalent functionality.

**Describe alternatives you've considered**
maintaining my own, which is painful

**Additional context**
none

[current setup]:https://github.com/todd-dsm/vimSimple

**Comment by wsdjeg** [comment]
@todd-dsm This feature has already been added in spacevim, it is included in autocomplete layer, which is enabled by default.

if you are using deoplete as complete_method, it support buffer words completion, and snippet complete is provided by neosnippet.
