### ISSUE TITLE
Cursor shape can not config

### ISSUE THREAD

**Issue by friendfish** [wsdjeg/SpaceVim#3949]
## Expected behavior, english is required
cursor shape can change to no-blinking, however it failed.

## The reproduce ways from Vim starting (Required!)
add the "terminal_cursor_shape = 1" in the toml file, after reboot vim8.2, it does not make sense.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
This option is only for neovim now.
