### ISSUE TITLE
poor performance with syslog files

### ISSUE THREAD

**Issue by nodoubleg** [wsdjeg/SpaceVim#395]
## Expected behavior, english is recommend
open a syslog file with view, scrolling through file should be quick. With Vim 8.0.0535, MacVim 8.0.525,  or Neovim, performance is varying shades of abysmal.

## Environment Information
- OS: macOS 10.12.4
- vim version: 7.4, as shipped by Apple; 8.0.0535 from HomeBrew; MacVim 8.0.525
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)
1. obtain a syslog file that is a few hundred lines long
2. open with ```view```, ```nvim -R```, or mview.
3. use arrow keys or j/k to move up and down the file.
4. Observe high cpu usage and sluggish performance.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

Config is stock SpaceVim. Tested with SpaceVim branches master (3fa447f) and dev (7504b33).

### :message output
Messages maintainer: Bram Moolenaar <Bram@vim.org>
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr  2 2017 05:50:02)
Press ENTER or type command to continue

#### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 0
g:spacevim_hiddenfileinfo = 1
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_max_column = 120
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_debug = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = 'Inconsolata\ for\ Powerline\ 13'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'e
diting', 'indents', 'navigation', 'misc', 'core', 'unite', 'github', 'ctrlp', 'autocomplete', 'nvim', 'osx', 'colorscheme']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/gmason/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 0
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_leader_guide_vertical = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(nvim)
version: 704
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log

```

**Comment by wsdjeg** [comment]
Can you check why cup is high using? which process? and which command?

**Comment by wsdjeg** [comment]
add this to your custom configration file
```
let g:indentLine_faster = 1
set nowrap
```

**Comment by nodoubleg** [comment]
The CPU was being consumed by the editor process (vim or nvim). Commands used to view/open log files: 
```
view /var/log/system.log
mview /var/log/system.log
nvim -R /var/log/system.log
``` 

setting ```let g:intentline_faster = 1``` fixed the performance problem for vim 8. Should this be set by default in SpaceVim?

**Comment by wsdjeg** [comment]
I have test it, if set it to 1, it is too ugly in normal file. I think this should be set in user's config file. the default value of  `intentline` (the plugin which provide indent line feature) also is not 1.

**Comment by v-leonhou** [comment]
i have met the same problem and  added let g:intentline_faster = 1 to my .~/.Spacevim.d/init.vim 
but it doesn't  get the problem sovled ,
maybe du to the lua support is not installed in my nvim????

**Comment by Shougo** [comment]
indentLine is slow plugin.
It uses column highlight feature.

**Comment by v-leonhou** [comment]
@Shougo @wsdjeg  so what may i do to solve the problem but not remove the indentline plugin,
anyother configuration can help?

**Comment by wsdjeg** [comment]
I can not reproduce it, If you can point out which process cause it, I will fix it. and I think you can use
```
let g:indentLine_faster = 1
set nowrap
```

**Comment by v-leonhou** [comment]
got it ,so why not add
```
 let g:indentLine_faster = 1
```
 to spacevim src , i think maybe there is lots of somebody meet the same problem,not just me @wsdjeg

**Comment by ghost** [comment]
@wsdjeg without
```vim
let g:indentLine_faster = 1
```
the performance is very poor even on very small files. For example, here you can clearly see how it takes 2 cores to 100% for nothing, just by scrolling a small C source.

<img width="1080" alt="screenshot_20170428_205610" src="https://cloud.githubusercontent.com/assets/10786469/25543448/df47eece-2c56-11e7-80ce-b0f9a5140716.png">

You can try it all yourself, here's the source file:
[main.c.zip](https://github.com/SpaceVim/SpaceVim/files/965319/main.c.zip)

This option is must-have for at least mediocre performance (because even with it the speed and smoothness is kinda meh, scrolling has a visible choke even with the option enabled on the file above in comparison to default vim config).

**Comment by ghost** [comment]
Oh, I just discovered that this option ruins the indentation and/or highlighting (https://github.com/Yggdroot/indentLine/issues/58) (also checked on the file above). Now I understand why this cannot be included.
