### ISSUE TITLE
projectmanager

### ISSUE THREAD

**Issue by dripfeeder** [wsdjeg/SpaceVim#3950]
Hi.
os: archlinux
spacevim after start error:

[https://imgur.com/60Vhw9l](url)

**Comment by wsdjeg** [comment]
sorry, I can not see this image, imgur is blocked here, please upload on github issue.

**Comment by dripfeeder** [comment]
sorry!
_

> Error detected while processing function SpaceVim#end[98]..SpaceVim#plugins#projectmanager#RootchandgeCallback[6]..<SNR>99_cache_project:
> line    1:
> E689: Can only index a List or Dictionary
> Error detected while processing function SpaceVim#plugins#projectmanager#current_root[22]..SpaceVim#plugins#projectmanager#RootchandgeCallback[6]..<SNR>99_cache_project:
> line    1:
> E689: Can only index a List or Dictionary
> E689: Can only index a List or Dictionary
> Press ENTER or type command to continue

_

`

**Comment by CircuitCipher** [comment]
I had this same problem and fixed it by following the advice from #3944 (This ticket should be marked a dup)

They suggested deleting
`~/.cache/SpaceVim/projects.json`

**Comment by dripfeeder** [comment]
Thank you very much! Happened
