### ISSUE TITLE
deoplete-go requires gocode dependency

### ISSUE THREAD

**Issue by zhtluo** [wsdjeg/SpaceVim#3957]
## Expected behavior, english is required

deoplete-go should run without error.

## The reproduce ways from Vim starting (Required!)

Add golang layer.

## Screenshots

It is stated on the page of deoplete-go (https://github.com/deoplete-plugins/deoplete-go) that the installation of gocode is required. However, SpaceVim does not perform the installation automatically.

It is worth noting that there are a lot of different versions of gocode over the Internet. However, I found only this specific repo of gocode (https://github.com/stamblerre/gocode) works with the plugin. All other libraries of gocode, including the one instructed to be installed on the deoplete-go page, seem to be incompatible with the plugin.

**Comment by wsdjeg** [comment]
what can be done in SpaceVim side?

**Comment by wsdjeg** [comment]
closed, because nothing can be done in spacevim. when install this plugin, spacevim will run `make` comamnd for this plugin, the makefile should be updated in this plugin.
