### ISSUE TITLE
status line separator don't show the arrows in vim, but in neovim it shows the arrows

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#3958]
![2020-11-14-003331_2560x1440_scrot](https://user-images.githubusercontent.com/2177069/99140598-3e82ef80-2611-11eb-8d1d-7699806a012a.png)

nvim
![2020-11-14-005349_2560x1440_scrot](https://user-images.githubusercontent.com/2177069/99140924-e7cae500-2613-11eb-8949-a201d1841e44.png)

**Comment by wsdjeg** [comment]
ok, Thanks for reporting, it seems same as #3835

**Comment by wsdjeg** [comment]
It is same as #3835.
