### ISSUE TITLE
The default theme does not work with vim 8.0

### ISSUE THREAD

**Issue by Aya-Yang** [wsdjeg/SpaceVim#396]
## Expected behavior, english is recommend
The default theme does not work with vim 8.0

## Environment Information
- OS:macos 10.12 Ubuntu 14.04
- vim version:8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
The theme becomes gray and does not have the same effect it should be

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by Gabirel** [comment]
It works for me though. 
Can you post your screenshot?

**Comment by Aya-Yang** [comment]
![screenshot from 2017-04-06 09 35 20](https://cloud.githubusercontent.com/assets/12084255/24733792/62cfb090-1aac-11e7-8d9e-6dcb80116afc.png)

**Comment by wsdjeg** [comment]
Ubuntu14.04`s GNOME-terminal do not support true colors.

**Comment by wsdjeg** [comment]
```
sudo add-apt-repository ppa:gnome3-team/gnome3-staging
sudo apt-get update 
sudo apt-get install gnome-terminal 
sudo add-apt-repository -r ppa:gnome3-team/gnome3-staging
```
