### ISSUE TITLE
Statusline colorscheme for "one" with light background

### ISSUE THREAD

**Issue by TheWall89** [wsdjeg/SpaceVim#3968]
The color palette for the `one` colorscheme provides a nice statusline on a dark background. I don't quite like it on a light background. I created a color palette using colors from https://github.com/rakr/vim-one.

Tabline:
![image](https://user-images.githubusercontent.com/2626117/99558564-2a017700-29c4-11eb-9838-b26b41b14dda.png)

Statusline:
![image](https://user-images.githubusercontent.com/2626117/99558651-3ede0a80-29c4-11eb-8802-d9688946a1ab.png)
![image](https://user-images.githubusercontent.com/2626117/99558672-443b5500-29c4-11eb-9912-66d645eceb82.png)
![image](https://user-images.githubusercontent.com/2626117/99558723-4f8e8080-29c4-11eb-86da-bbd209bfa191.png)

I would like to open a PR and change [one.vim](https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/mapping/guide/theme/one.vim) but this would remove the dark palette and I'm sure a lot of people are using that. Should we create a `onelight` colorscheme? If yes, how to proceed?

Anyway, the color palette is available [here](https://gist.github.com/TheWall89/f29fcb2d09f65a3981635152b801ce9b) for anyone who wants to use it. If this is enough, this issue can be closed.

**Comment by wsdjeg** [comment]
@TheWall89 thanks, this is awesome, the one colorscheme template for spacevim is https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/mapping/guide/theme/one.vim, this is a function to return template, maybe we can use `if &light` to chack the background option.

**Comment by TheWall89** [comment]
Not an expert in vimscript but I'll try the `if` solution and I'll let you know soon.
