### ISSUE TITLE
Make tab index on tabline consistent. 

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3971]
**Is your feature request related to a problem? Please describe.**

e.g. We have the following tabs, and we are in tab 4 javacomplete.vim

```
<- 10 | 1 foo.vim | 2 Foo.java | 3 SpaceVim.vim | 4 javacomplete.vim | 5 util.vim | 13 ->
```

``\5`` jump to tab ``util.vim``, tabline becomes:

```
<- 13 | 1 javacomplete.vim | 2 util.vim | 3 tab1.txt | 4 long_tab2.txt | 5 tab3.txt | 10 ->
```

We notify the tab index is changed.

``\1`` return to tab ``javacomplete.vim``, tabline maybe
```
<- 10 | 1 foo.vim | 2 Foo.java | 3 SpaceVim.vim | 4 javacomplete.vim | 5 util.vim | 13 ->
```

The tab index change make it hard to jump between tabs.

e.g. The``PatchReview`` plugin opens one tab for each file (tens of files), and I need to frequence swtich between .h/.cpp.  The inconsist tab index make it hard to jump.

**Describe the solution you'd like**
Remember the left most shown tab index, and try keep it consistent, not jump consider previous tab index and current tab index.

BTW, if the ``gr`` PR(#3728) can be merged, it should helps a lot.

**Comment by wsdjeg** [comment]
the current implementaion is try to show more tabs when you want to switch tabs, for example, if you are in tab index 2, and press `\5`,  we should list the tabs after `tab 5`. this is how chrome or other app does.

If you just want to switch between buffers, for example, current buffer and previous buffer, you can use `SPC Tab`, this key binding is for just between two buffers.

**Comment by thawk** [comment]
I agree to show more tabs possible, but:

1. By fixing the left most tab index when possible, it wouldn't reduce the number of visible tabs
2. In the mentioned ``PatchReview`` plugin, it shows one tab for a file, and in each tab, it shows two buffer side by side in difference mode to compare two versions of the same file. So ``SPC Tab`` doesn't help much, but ``gr``  (switch to previous tab) helps.
3. In my firefox, switching to another visible tab doesn't change the shown tabs in tab bar, only change focus.  It can easy switch between two tabs without scrolling tab bar.

**Comment by wsdjeg** [comment]
@thawk This feature has been implemented in lua version. and You can test it in neovim 0.9.0+
