### ISSUE TITLE
Error when open a fortran code file

### ISSUE THREAD

**Issue by CubeTian** [wsdjeg/SpaceVim#3974]
## Expected behavior, english is required
Open a fortran file normally.
## The reproduce ways from Vim starting (Required!)
Just add fortran module, and vim XXX.f90 .
## Debug info
Error detected while processing /root/.SpaceVim/bundle/fortran.vim/indent/fortran.vim:                    
line   14:
E492: Not an editor command: ^M
line   17:
E15: Invalid expression: (b:fortran_fixed_source != 1)^M
line   91:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
@CubeTian thanks for reporting, it seems the fileformat of this file is wrong, I will fix it.
