### ISSUE TITLE
C: change code style

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#398]
## Expected behavior
I want a different code style for C/C++, instead of the default.

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)
![image](https://cloud.githubusercontent.com/assets/12933851/24704533/abced8e2-1a3a-11e7-9904-8b6cbdded858.png)

I don't like this kind of code style.

I prefer this:
![image](https://cloud.githubusercontent.com/assets/12933851/24704569/d57e3f34-1a3a-11e7-8531-4361dcf94680.png)

Am I able to do this without modifying manually, which means make complete engine do it for me?

**Comment by wsdjeg** [comment]
what is the difference between these two pictures?

**Comment by Gabirel** [comment]
```c
while (i >= 0) {
    i++;
}
```

The another position of braces:
```c
while (i >= 0)
{
    i++;
}
```

**Comment by wsdjeg** [comment]
It is default snippets in [neosnippet-snippets](https://github.com/Shougo/neosnippet-snippets), you want write your own snippet.

I will add an example for you.

**Comment by wsdjeg** [comment]
open a c file, run `:NeoSnippetEdit` command. 
the file `~/.SpaceVim.d/snippets/c.snip` will be opened. then add: 
```
snippet     while
options     head
abbr        while () {}
    while (${1:#:condition})
    {
        ${0:TARGET}
    }

```

**Comment by Gabirel** [comment]
what about other snippets? For example, `if-else`, `do-until` and `for`?

There's any more convenient way to do this?

**Comment by wsdjeg** [comment]
please read `:h neosnippet` and https://github.com/Shougo/neosnippet-snippets/blob/master/neosnippets/c.snip

you also can write your own snippet.

**Comment by Gabirel** [comment]
That's too time-wasting to reformat the whole snippets even if I can do it with a bunch of time.

Does `SpaceVim` support any code reformatting or something like this, like `gg=G`?

But `gg=G` isn't good enough for each coders.

**Comment by wsdjeg** [comment]
SpaceVim use neoformat for code formatting. but I am not sure if it can change the code stype.

**Comment by Gabirel** [comment]
I will look into it. 
Any future plans for make code formatting become one of APIs?

**Comment by wsdjeg** [comment]
hmm, APIs is just a mass of public functions, I will imporve neoformat setting in the future.

**Comment by Gabirel** [comment]
I've looked into [sbdchd/neoformat](https://github.com/sbdchd/neoformat
)
Well, It's just kind of another layer of another tools. And it's hard to use even if you do some configuration. I can't customize my own code style or code style normally used.


Let's just keep this issue open until you improved code formatting of `SpaceVim`.

**Comment by Gabirel** [comment]
I just notice that [sbdchd/neoformat](https://github.com/sbdchd/neoformat
) also can use `astyle` to format code.

But I do hate this plugin. It doesn't have good designs on configuration. I have to change his original code to make some changes. 

No! This means I have to change code in `~/.cache/vimfiles/repos/github.com/sbdchd/neoformat/autoload/neoformat/formatters/*.vim` to do some configurations.

So, I don't like this feature.

I would rather choose `astyle`(by doing it by myself) to format my code than choose this plugin.

**Comment by wsdjeg** [comment]
please readme doc of neoformate, you can set formater yourself.

**Comment by Gabirel** [comment]
No, I've read that. I know that it can format code for me. But the way that plugins doing, is not my cake. Very inconvenient

**Comment by wsdjeg** [comment]
why? if changing *.vim can work, why you can not set a local formater yourself? you can disable all default formater for c file, and create a new one.

**Comment by Gabirel** [comment]
that's not the point.

The point is that you have to change your directory all way to ``/.cache/vimfiles/repos/github.com/sbdchd/neoformat/autoload/neoformat/formatters/*.vim`.

Also, it has so many `*.vim`, how can I know which file I modified? and how can I always remember back up these files? So, this plugin doesn't have any config mode, I hate it. It's antihuman

**Comment by tracyone** [comment]
try clang-format....

**Comment by Gabirel** [comment]
No, you guys are missing the point.

[sbdchd/neoformat](https://github.com/sbdchd/neoformat) use `clang-format` or `astyle` to reformat the code. I know this.

The point is that [sbdchd/neoformat](https://github.com/sbdchd/neoformat) too redudant to use without any configuration. Whoever wants to use this plugin has to modify its source code to customize.

**Comment by wsdjeg** [comment]
no need edite src of neoformat. you can have a look java layer.

**Comment by Gabirel** [comment]
```viml
 let g:neoformat_java_googlefmt = {
          \ 'exe': 'java',
          \ 'args': ['-jar', get(g:,'spacevim_layer_lang_java_formatter', '')],
          \ 'replace': 0,
          \ 'stdin': 0,
          \ 'no_append': 0,
          \ }
```

So, you mean this? I can just write it into my `init.vim`? Is that right?

**Comment by wsdjeg** [comment]
```viml
    let g:neoformat_enabled_c = ['astyle']
    let g:neoformat_c_astyle = {
            \ 'exe': 'astyle',
            \ 'args': ['--mode=c'],
            \ 'stdin': 1,
            \ }
```

you can change the args to anything you like.

**Comment by Gabirel** [comment]
So, I can put these into `~/.SpaceVim.d/init.vim`? Right?

**Comment by wsdjeg** [comment]
yeah. no need to edit src of plugin.

**Comment by Gabirel** [comment]
OK, Thanks
