### ISSUE TITLE
How To Configure SPC Timeout?

### ISSUE THREAD

**Issue by therealgymmy** [wsdjeg/SpaceVim#3980]
Hi, I understand that the menubar only shows up after a brief period of inactivity (indicating user doesn't know the next key to press). How can I configure this timeout? I found an old issue mentioning ttimeoutlen, but it didn't make a difference after setting it to 10 (from 50).

**Comment by gbprod** [comment]
You can set `timeoutlen` in your bootstrap function :

```
function! myspacevim#before() abort
    set timeoutlen=300
endfunction
```

Ref:
 - https://spacevim.org/documentation/#bootstrap-functions
 - https://spacevim.org/documentation/#mappings-guide
