### ISSUE TITLE
Using python, spc l r does not return output

### ISSUE THREAD

**Issue by jcress** [wsdjeg/SpaceVim#3982]
## Expected behavior, english is required
spc l r should run script.py and return std out in a runner bujffer

## The reproduce ways from Vim starting (Required!)
vi script.py
spc l r

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
 23 SpaceVim layers:
 22 
 21 - VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
 20 + autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
 19 - chat:                 not loaded          https://spacevim.org/layers/chat/
 18 + checkers:                 loaded          https://spacevim.org/layers/checkers/
 17 - chinese:              not loaded          https://spacevim.org/layers/chinese/
 16 - colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
 15 + core#banner:              loaded          https://spacevim.org/layers/core/banner/
 14 + core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
 13 + core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
 12 + core:                     loaded          https://spacevim.org/layers/core/
 11 - cscope:               not loaded          https://spacevim.org/layers/cscope/
 10 - ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
  9 - ctrlspace:            not loaded          https://spacevim.org/layers/ctrlspace/
  8 - debug:                not loaded          https://spacevim.org/layers/debug/
  7 - denite:               not loaded          https://spacevim.org/layers/denite/
  6 + edit:                     loaded          https://spacevim.org/layers/edit/
  5 - exprfold:             not loaded          no exists
  4 - floobits:             not loaded          https://spacevim.org/layers/floobits/
  3 - foldsearch:           not loaded          https://spacevim.org/layers/foldsearch/
  2 + format:                   loaded          https://spacevim.org/layers/format/
  1 - fuzzy:                not loaded          no exists
26  - fzf:                  not loaded          https://spacevim.org/layers/fzf/
  1 - games:                not loaded          no exists
  2 - git:                  not loaded          https://spacevim.org/layers/git/
  3 - github:               not loaded          https://spacevim.org/layers/github/
  4 - gtags:                not loaded          https://spacevim.org/layers/gtags/
  5 - incsearch:            not loaded          no exists
  6 - indentmove:           not loaded          no exists
  7 - japanese:             not loaded          https://spacevim.org/layers/japanese/
  8 - lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
  9 - lang#actionscript:    not loaded          https://spacevim.org/layers/lang/actionscript/
 10 - lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
 11 - lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
 12 - lang#aspectj:         not loaded          https://spacevim.org/layers/lang/aspectj/
 13 - lang#assembly:        not loaded          https://spacevim.org/layers/lang/assembly/
 14 - lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
 15 - lang#batch:           not loaded          https://spacevim.org/layers/lang/batch/
 16 - lang#c:               not loaded          https://spacevim.org/layers/lang/c/
 17 - lang#chapel:          not loaded          https://spacevim.org/layers/lang/chapel/
 18 - lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
 19 - lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
 20 - lang#crystal:         not loaded          https://spacevim.org/layers/lang/crystal/
 21 - lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
 22 - lang#d:               not loaded          https://spacevim.org/layers/lang/d/
 23 - lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
 24 - lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
 25 - lang#eiffel:          not loaded          https://spacevim.org/layers/lang/eiffel/
 26 - lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
 27 - lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
 28 - lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
 11 - lang#factor:          not loaded          no exists
 10 - lang#forth:           not loaded          no exists
  9 - lang#fortran:         not loaded          https://spacevim.org/layers/lang/fortran/
  8 - lang#foxpro:          not loaded          https://spacevim.org/layers/lang/foxpro/
  7 - lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
  6 - lang#go:              not loaded          https://spacevim.org/layers/lang/go/
  5 - lang#goby:            not loaded          https://spacevim.org/layers/lang/goby/
  4 - lang#gosu:            not loaded          https://spacevim.org/layers/lang/gosu/
  3 - lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
  2 - lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
  1 - lang#hack:            not loaded          https://spacevim.org/layers/lang/hack/
67  - lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
  1 - lang#html:            not loaded          https://spacevim.org/layers/lang/html/
  2 - lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
  3 - lang#idris:           not loaded          https://spacevim.org/layers/lang/idris/
  4 - lang#io:              not loaded          https://spacevim.org/layers/lang/io/
  5 - lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
  6 - lang#j:               not loaded          https://spacevim.org/layers/lang/j/
  7 - lang#janet:           not loaded          https://spacevim.org/layers/lang/janet/
  8 - lang#java:            not loaded          https://spacevim.org/layers/lang/java/
  9 - lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
 10 - lang#json:            not loaded          no exists
 11 - lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
 12 - lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
 13 - lang#lasso:           not loaded          https://spacevim.org/layers/lang/lasso/
 14 - lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
 15 - lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
 16 - lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
 17 - lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
 18 - lang#markdown:        not loaded          https://spacevim.org/layers/lang/markdown/
 19 - lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
 20 - lang#moonscript:      not loaded          https://spacevim.org/layers/lang/moonscript/
 21 - lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
 22 - lang#nix:             not loaded          https://spacevim.org/layers/lang/nix/
 23 - lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
 24 - lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
 25 - lang#pascal:          not loaded          https://spacevim.org/layers/lang/pascal/
 26 - lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
 27 - lang#php:             not loaded          https://spacevim.org/layers/lang/php/
 28 - lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
 29 - lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
 30 - lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
 31 - lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
 32 - lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
 33 - lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
 34 - lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
 35 + lang#python:              loaded          https://spacevim.org/layers/lang/python/
 36 - lang#r:               not loaded          https://spacevim.org/layers/lang/r/
 37 - lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
 38 - lang#red:             not loaded          https://spacevim.org/layers/lang/red/
 39 - lang#ring:            not loaded          https://spacevim.org/layers/lang/ring/
lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
  1 - lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
  2 - lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
  3 - lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
  4 - lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
  5 - lang#slim:            not loaded          https://spacevim.org/layers/lang/slim/
  6 - lang#solidity:        not loaded          no exists
  7 - lang#sql:             not loaded          no exists
  8 - lang#supercollider:   not loaded          no exists
  9 - lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
 10 - lang#swig:            not loaded          no exists
 11 - lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
 12 - lang#toml:            not loaded          https://spacevim.org/layers/lang/toml/
 13 - lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
 14 - lang#v:               not loaded          https://spacevim.org/layers/lang/v/
 15 - lang#vbnet:           not loaded          https://spacevim.org/layers/lang/vbnet/
 16 - lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
 17 - lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
 18 - lang#wdl:             not loaded          no exists
 19 - lang#wolfram:         not loaded          https://spacevim.org/layers/lang/wolfram/
 20 - lang#xml:             not loaded          https://spacevim.org/layers/lang/xml/
 21 - lang#xquery:          not loaded          no exists
 22 - lang#zig:             not loaded          https://spacevim.org/layers/lang/zig/
 23 - leaderf:              not loaded          https://spacevim.org/layers/leaderf/
 24 - lsp:                  not loaded          https://spacevim.org/layers/language-server-protocol/
 25 - mail:                 not loaded          no exists
 26 - operator:             not loaded          no exists
 27 - org:                  not loaded          no exists
 28 + shell:                    loaded          https://spacevim.org/layers/shell/
 29 - sudo:                 not loaded          https://spacevim.org/layers/sudo/
 30 - test:                 not loaded          https://spacevim.org/layers/test/
 31 - tmux:                 not loaded          https://spacevim.org/layers/tmux/
 32 - tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
 33 - tools#mpv:            not loaded          https://spacevim.org/layers/tools/mpv/
 34 - tools#screensaver:    not loaded          no exists
 35 - tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
 36 - tools:                not loaded          https://spacevim.org/layers/tools/
 37 + ui:                       loaded          https://spacevim.org/layers/ui/
 38 - unite:                not loaded          https://spacevim.org/layers/unite/
 39 - vim:                  not loaded          no exists

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![Screenshot from 2020-11-22 13-56-00](https://user-images.githubusercontent.com/6474632/100297218-2ccc1100-2f5c-11eb-85c6-73e1ba3f4d48.png)

**Comment by wsdjeg** [comment]
Debug info is missing, the key binding is `SPC h I` not `SPC h l`
