### ISSUE TITLE
Option to have the fill column indicator visible on start

### ISSUE THREAD

**Issue by 80KiloMett** [wsdjeg/SpaceVim#3987]
**Is your feature request related to a problem? Please describe.**
I would like to have the fill column indicator visible without having to toggle it.

**Describe the solution you'd like**
A variable I can set in `~/.SpaceVim.d/init.toml` that let's me choose the initial state of the fill column. Something like:
```
[options]
...
fill_column_visible=[0|1]
...
```

**Describe alternatives you've considered**
It is possible to achieve this with `set cc=80` in the bootstrap_before function. This however confuses the toggle. The first time after start, when I toggle the fill column via `[SPC]tf` it sets cc to g:spacevim_maxcolumn, hitting toggle again makes the fill column disappear.

**Comment by wsdjeg** [comment]
hi @80KiloMett I am working on a PR for cache major mode, maybe this will cover this feature request. https://github.com/SpaceVim/SpaceVim/pull/3076
