### ISSUE TITLE
Display Startify instead of empty buffer

### ISSUE THREAD

**Issue by ck3mp3r** [wsdjeg/SpaceVim#3988]
**Is your feature request related to a problem? Please describe.**
This is just a suggestion for general usability improvement.

**Describe the solution you'd like**
Once the last open buffer is closed and the file manager is visible, instead of defaulting to an empty buffer, display `startify` again.

**Comment by wsdjeg** [comment]
@ck3mp3r yeah, open startify is better than open a new empty buffer.

**Comment by wsdjeg** [comment]
I have added this feature, now the key binding `SPC b d` will open startify if the current buffer is last one.

**Comment by ck3mp3r** [comment]
@wsdjeg thanks for adding this, already enjoying this very much.
