### ISSUE TITLE
SpaceVim + NeoVim + Windows 10 how to

### ISSUE THREAD

**Issue by davenport** [wsdjeg/SpaceVim#400]
## Expected behavior, english is recommend

How to setup SpaceVim + NeoVim + Windows 10

## Environment Information
- OS: Windows 10 64bit
- vim version:
- neovim version: v0.2.0-1174-gdd24ebff  (64bit 4/4/2017)

Has anybody setup SpaceVim + NeoVim + Windows 10 (64 bit) ?

What version of Neovim and Python and ... did you use?

Can you please outline your install process and configuration?

**Comment by wsdjeg** [comment]
I will write a post about it.

**Comment by wsdjeg** [comment]
please check https://github.com/Gabirel/Hack-SpaceVim
