### ISSUE TITLE
windisk.vim does't work probaly in vim8.2 in win 10, while it works well in nvim0.4.4

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#4003]
## Expected behavior: when I tried to change the disk directory with <kbd>SPC-f-d</kbd>, it came out the uncomplete disk info, after I choose any of the labels and press<kbd>enter</kbd>, it failed to change the disk directory.
![diskinfo](https://user-images.githubusercontent.com/10368438/101571017-83345780-3a12-11eb-968b-5ab9001bb01d.PNG)
![disiinfo_full](https://user-images.githubusercontent.com/10368438/101571556-c098e500-3a12-11eb-8879-3eb8e5b50114.PNG)
![result](https://user-images.githubusercontent.com/10368438/101571685-c989b680-3a12-11eb-9c8d-fd22ad373f47.PNG)

## some more steps, I tried to trace the script. It seems failed in iconv the disk info from 'cp936', to 'utf-8', so I put the raw wmic info together,using <kbd>wmic LOGICALDISK LIST BRIEF > wmic.txt</kbd>. hope it helps. BTW finally, I changed to  nvim and it works fine.

![wmic result](https://user-images.githubusercontent.com/10368438/101571813-d27a8800-3a12-11eb-83ce-2ef8d46f70a6.PNG)
[wmic.txt](https://github.com/SpaceVim/SpaceVim/files/5663354/wmic.txt)

## Debug info

SpaceVimGuideCursor xxx links to Cursor
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
No matching autocommands
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103:
line   72:
Lua library cannot be loaded.
SpaceVimGuideCursor xxx links to Cursor
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
No matching autocommands
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103:
line   72:
Lua library cannot be loaded.
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
Error detected while processing function <SNR>100_BMRemove:
line    9:
E329: No menu "__windisk__ (6)	C:\vim\vim82"

No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
No matching autocommands
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
55 fewer lines

SpaceVimGuideCursor xxx links to Cursor
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
No matching autocommands
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[32]..103:
line   72:
Lua library cannot be loaded.
SpaceVimGuideCursor xxx links to Cursor
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
No matching autocommands
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[4]..<SNR>56_winopen[65]..<SNR>56_updateStatusline[9]..113[35]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103[38]..103:
line   72:
Lua library cannot be loaded.
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103:
line   72:
E370: Could not load library lua53.dll
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>56_start_buffer[38]..<SNR>56_wait_for_input[27]..<SNR>56_handle_input[4]..<SNR>56_start_buffer[32]..103:
line   72:
Lua library cannot be loaded.
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (
No matching autocommands
No matching autocommands
Error detected while processing function <SNR>138_setup[36]..<SNR>138_Map[11]..<SNR>138_AutoClose:
line    9:
E225: global mapping already exists for (

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please use github issue template.
