### ISSUE TITLE
How to disable the popup viewer for the key-bindings description?

### ISSUE THREAD

**Issue by cgxxv** [wsdjeg/SpaceVim#4004]
I want to disable the key-bindings popup viewer because I already keep in my mind about the keys I am using frequently. By the way, it seems to have a problem with the colorscheme in terminal, also in GUI (MacVim) app. I test the colorscheme gruvbox and SpaceVim which doesn't have the same problem.

![Lark20201211-190416](https://user-images.githubusercontent.com/18651103/101896417-f3460780-3be3-11eb-9d09-49060bb0abd1.png)

**Comment by wsdjeg** [comment]
You can not disable it now, if you remanber this key binding, just press it quicklly, and the help buffer will not be opened. this colorscheme seems do not support you terminal, and you can choose another one.
