### ISSUE TITLE
Feature request: Mouse integration 

### ISSUE THREAD

**Issue by FazleArefin** [wsdjeg/SpaceVim#401]
Spacemacs supports mouse interaction. It would be good if SpaceVim also had this feature.

**Comment by wsdjeg** [comment]
I will add these feathers. can you list some useful mouse function?

**Comment by wsdjeg** [comment]
I have change default mouse to `nv`, so in normal or visual mode you can use mouse:
1. select text
2. change buffer via click on tabline
3. close tab via click `X` in tabline
4. open dir in vimfiler buffer via double click
5. open file in vimfiler buffer via double click

**Comment by FazleArefin** [comment]
I have an issue: double clicking a file in vimfiler opens it in GEdit Text Editor instead of vim.

I am using Ubuntu GNOME 17.04 and GEdit is my default text editor.

**Comment by wsdjeg** [comment]
done. You can test it.

**Comment by negativo** [comment]
same issue, double clicking on a filename it opens the default system editor and not in the buffer ( ubuntu 16.04 )

**Comment by jgogstad** [comment]
I'm also seeing this behaviour on `dev` (`5bd361f`), both in vim and neovim. Clicks on buffers also doesn't work.

**Comment by wsdjeg** [comment]
please open new issue with issue template.

**Comment by woss** [comment]
I have the same issue with some files. JS files are opened correctly Y(A)ML not.

**Comment by wsdjeg** [comment]
you can open new issue with issue template

**Comment by woss** [comment]
@wsdjeg is this a bug or a missing feature?

**Comment by wsdjeg** [comment]
I do not know what is your issue.

**Comment by woss** [comment]
When I double-click on a file in the file tree ( using MacVim )  JS files are opened with MacVim (same instance) others are opened with default editor. Is that a bug/ missing feature/ missing configuration?

**Comment by wsdjeg** [comment]
It is feature, you should use enter instead of double click, in vimfiler double click will open file via xdg-open.

**Comment by woss** [comment]
Oh, ok :) thanks for the clarification. Maybe that should be somewhere mentioned?

**Comment by wsdjeg** [comment]
you can read :h vimfiler

**Comment by wsdjeg** [comment]
maybe this should be added to spacevim doc.
