### ISSUE TITLE
How do I change settings to enable copying and pasting from external sources to vim/nvim?

### ISSUE THREAD

**Issue by Joe23232** [wsdjeg/SpaceVim#4023]
I installed `spacevim` and using `nvim`, if I copy some text from a web browser as an example, how do I paste it in `nvim` and vice versa?

I have tried using `\`+`p` but that still pastes from internal buffer. Is there some setting I need to enable or something?

**Comment by Rom1deTroyes** [comment]
<kbd>\\</kbd> is the default leader key, if you search for a buffer, you should look at the <kbd>"</kbd> key :smile:

On Unix based systems, you get two main buffers, <kbd>*</kbd> for what you have selected with your mouse, and <kbd>+</kbd> for what you had copied with a <kbd>Ctrl</kbd>+<kbd>c</kbd> on your browser.

So <kbd>"</kbd><kbd>+</kbd><kbd>p</kbd> (3 keys one after an other)will paste what you have copied earlier, and <kbd>"</kbd><kbd>+</kbd><kbd>Y</kbd> will copy all the line to the clipboard.

Bonus : in `insert` mode, you can use <kbd>Ctrl</kbd>+<kbd>r</kbd><kbd>Buffer</kbd> to paste the buffer where you are 🎉
