### ISSUE TITLE
Problem with UltiSnips engine and snippets directory

### ISSUE THREAD

**Issue by zivlakmilos** [wsdjeg/SpaceVim#4024]
I had problem. First I configure SpaceVim to use UltiSnips by specify snippet engine in init.toml file

`[options]
    snippet_engine = "ultisnips"`

When I tried to edit snippets with command `:UltiSnipsEdit` I get message that UltiSnips was not able to find default snippets directory (see screenshot).

![image](https://user-images.githubusercontent.com/11087976/103287579-23164d00-49e3-11eb-8674-a892e9fc1386.png)

I start to dig into SpaceVim and UltiSnips source code and I found that UltiSnips checking for `g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit` as directory for snippets.

[https://github.com/SirVer/ultisnips/blob/c270950492d71bac0317d47d42cd0884eefe6490/pythonx/UltiSnips/snippet_manager.py#L838](https://github.com/SirVer/ultisnips/blob/c270950492d71bac0317d47d42cd0884eefe6490/pythonx/UltiSnips/snippet_manager.py#L838)

I fix issue by adding following line of code at the end of [https://github.com/SpaceVim/SpaceVim/blob/master/config/plugins_before/ultisnips.vim](https://github.com/SpaceVim/SpaceVim/blob/master/config/plugins_before/ultisnips.vim) file:
`let g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit = '~/.SpaceVim.d/UltiSnips'`

I don't know is this good solutions. Maybe UltiSnips change variable new in latest version. Or it's just workaround. But this was solve my issue.

**Comment by wsdjeg** [comment]
in spacevim, we use `let g:UltiSnipsSnippetsDir = '~/.SpaceVim.d/UltiSnips'` by default, this plugin change the config option name?  I think it is a bug of this plugin, the development of ultisnips should keep backword compatible.

**Comment by zivlakmilos** [comment]
I checked commit history of UltiShips. and it's looks like that in last version they start checking only `g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit` instead of directories in `g:UltiSnipsSnippetDirectories` for editing. And this new variable is used only for editing according to they documentation. This is strange. I don't know why they did this.

https://github.com/SirVer/ultisnips/commit/c270950492d71bac0317d47d42cd0884eefe6490
https://github.com/SirVer/ultisnips/pull/1301

**Comment by wsdjeg** [comment]
Sorry for late reply, this is a bug, I need to make sure how does ultisnips change it's logic.

**Comment by wsdjeg** [comment]
This has been fixed.
