### ISSUE TITLE
awesome colorscheme for vim/neovim

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#403]
I will list some awesome colorschemes here, and most of them well be added to SpaceVim's colorscheme layer. If you like these colorschemes, please star their repos in github.

### [rakr/vim-one](https://github.com/rakr/vim-one)
![](https://raw.githubusercontent.com/rakr/vim-one/master/screenshots/new-logo.png)

**Comment by wsdjeg** [comment]
@rakr Thanks for the nice colorscheme, I want to add it to SpaceVim, 😄

**Comment by wsdjeg** [comment]
### [sonph/onehalf](https://github.com/sonph/onehalf)
![](https://raw.githubusercontent.com/sonph/onehalf/master/screenshots/main.png)

**Comment by wsdjeg** [comment]
### SpaceVim default colorscheme [gruvbox](https://github.com/morhetz/gruvbox)

![](https://camo.githubusercontent.com/2fcf604967167347f15ca8be125d32b18db9bc28/687474703a2f2f692e696d6775722e636f6d2f476b496c38466e2e706e67)

**Comment by jetm** [comment]
SpaceVim already has https://github.com/joshdick/onedark.vim, I have found it very similar to vim-one. Which one is the better? I was looking and it's hard to see differences, but I would bet for onedark, it has more Github stars, forks, support to different vim projects, terminal (tmux) and more Github issues solved.

If you ask me, I would put onedark by default as colorscheme. I found it better than grubox. But, it could be just matter of particular taste.

**Comment by wsdjeg** [comment]
~~I have tried onedark, but what I see in the screen is most all dark colors, it is hard to find what I want. hmm, Color contrast is too small .~~

sorry, I will try more in gui.

**Comment by jetm** [comment]
@wsdjeg: Yes, as I said, it could be a matter of taste, monitor qualitative, contrast/brightness settings, etc. Like this is how it looks onedark for me:

![tmux vim spacevim zsh](https://cloud.githubusercontent.com/assets/474838/24765090/c0c3b672-1ab3-11e7-9666-50154397c0b1.png)

**Comment by rakr** [comment]
Thanks for picking my color scheme. 
@jetm the biggest difference is that vim one has a light and dark version. Aside from that both version try to mimic the current atom one theme. 
Keep in mind that vim one has less than one year of official existence (hence the number of starts)

**Comment by jetm** [comment]
@rakr: Thanks for your response. I tested vim one and I like it as well as onedark. 

One suggestion, could you be willing to fix the colors for C/C++ language? Look in the image, C/C++ comments are shown brighter than onedark does. In my opinion (no an expert on colors schemes), comments should be more obscure, like onedark is showing. (vim one at the left, onedark at the right)

![comparing-onedark-one](https://cloud.githubusercontent.com/assets/474838/24778459/ed2b7f90-1ae7-11e7-80c2-8a55c23fa9a3.png)

In vim one I saw C/C++ are not among stable programming languages. But, this might be a trigger to support them. Let me know if you want me to submit an issue in vim one GitHub repo.

**Comment by rakr** [comment]
Feel free to open an issue. I'll work on that this weekend

**Comment by jetm** [comment]
@rakr: Done https://github.com/rakr/vim-one/issues/42. Thanks!

**Comment by rakr** [comment]
Thanks @jetm, your pull request has been merged

**Comment by ghost** [comment]
so cool

**Comment by deepseeksss** [comment]
when should spacevim support this colorscheme ?

**Comment by wsdjeg** [comment]
@Matrix-Zhang I have added vim-one. you can use 
`let g:spacevim_colorscheme             = 'one'`

**Comment by deepseeksss** [comment]
how to use light theme instead of the default dark???
------------------------------------------------------------------------
set background=light

**Comment by jetm** [comment]
@Matrix-Zhang: It is possible to change between light and dark with `:call ToggleBG()`.
