### ISSUE TITLE
Allow custom commands for code runner (SPC l r)

### ISSUE THREAD

**Issue by lunw1024** [wsdjeg/SpaceVim#4038]
**Is your feature request related to a problem? Please describe.**
E.g. Cannot find ways to change the compile command `g++` to `clang` in code runner (SPC l r)

**Describe the solution you'd like**
adding a config item for custom command

**Comment by wsdjeg** [comment]
yeah, currently we do not provide simple function for custom code runner command, I am still thinking about how to implement this feature. before it is done, I think you can use [custom task](https://spacevim.org/documentation/#tasks)

**Comment by wsdjeg** [comment]
this has been done, you can checkout the doc:

https://spacevim.org/documentation/#custom-runner
