### ISSUE TITLE
Change directory to current folder when no project files are found

### ISSUE THREAD

**Issue by kjgfcdb** [wsdjeg/SpaceVim#4039]
Sometimes I want to edit a single file which is not in a project. In previous stable release (v1.5.0), the working directory is the folder where this file locates in. But in the new stable release (v1.6.0), the working directory becomes the folder where `Spacevim` configuration files locate in.

So is it possible to add an option that allow vim to change its working directory to current folder when no project files are found?

**Comment by wsdjeg** [comment]
please post the runtime log.

**Comment by kjgfcdb** [comment]
@wsdjeg 
Here are my `SPDebugInfo` and `SPRuntimelog` command results:

[debuginfo.txt](https://github.com/SpaceVim/SpaceVim/files/5760232/debuginfo.txt)
[runtime.log](https://github.com/SpaceVim/SpaceVim/files/5760233/runtime.log)

**Comment by kjgfcdb** [comment]
[runtime.log](https://github.com/SpaceVim/SpaceVim/files/5760234/runtime.log)
[debuginfo.txt](https://github.com/SpaceVim/SpaceVim/files/5760235/debuginfo.txt)

**Comment by kjgfcdb** [comment]
This problem is fixed in commit 421c059d. Thanks for your effort!

**Comment by wsdjeg** [comment]
OK. nice
