### ISSUE TITLE
cscope python reports "Key not present in Dictionary" every time before showing results

### ISSUE THREAD

**Issue by tsonglew** [wsdjeg/SpaceVim#4048]
## Expected behavior, english is required

no errors when run <kbd>SPC m c r</kbd> and other cscope commands

## The reproduce ways from Vim starting (Required!)

Open a Python file and try any command after <kbd>SPC m c</kbd>

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

```
Error detected while processing function cscope#find[8]..<SNR>181_updateDBs[2]..<SNR>181_CreateDB:
line    2:
E716: Key not present in Dictionary: _home_***__home_***_
E15: Invalid expression: s:dbs[dir]['id']
line   23:
E716: Key not present in Dictionary: _home_***__home_*** created: /home/<username>/.cache/SpaceVim/cscope/_home_***__home_***/cscope.db
```

`***` is my working directory after home joined with '_'

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
It is a bug of cscope.vim in spacevim.
