### ISSUE TITLE
Syntastic doesn't support c++11 in SpaceVim

### ISSUE THREAD

**Issue by haoyifan** [wsdjeg/SpaceVim#405]
## Environment Information
- OS: Ubuntu 16.04
- vim version: 7.4
- neovim version:

## The reproduce ways from Vim starting (Required!)
When I edit a cpp file containing keyword "auto" and then type :w to save the file, the syntastic would throw an error saying that I need to enable c++11 support. My machine has g++ supporting c++11, and the code compiles.

I added the following two lines to main.vim, but it doesn't  work
`let g:syntastic_cpp_compiler = "g++"`
`let g:syntastic_cpp_compiler_options = "-std=c++11 -Wall -Wextra -Wpedantic"`

I also saw other people saying that I need to also setup ycm along with syntastic because ycm overrides several settings in syntastic, but I don't think SpaceVim uses ycm.

I also tested out the above syntastic setting in another machine without SpaceVim, and the checker can recognize c++11 syntax. Am I configuring my syntastic in the wrong place? Or I should make other changes?

![2017-04-06 8 15 56](https://cloud.githubusercontent.com/assets/16672909/24780432/4473fc88-1b05-11e7-87bc-0d02cd97713c.png)

![2017-04-06 8 16 09](https://cloud.githubusercontent.com/assets/16672909/24780431/40119808-1b05-11e7-8331-ca4cd114a5b1.png)

**Comment by wsdjeg** [comment]
SpaceVim custom configration file is ～/.SpaceVim.d/init.vim, please do not change anything in ～/.SpaceVim

by default we use neomake instead of syntastic. you should read `:h Neomake`.

**Comment by haoyifan** [comment]
I figured that out. Thanks!
