### ISSUE TITLE
gocode binary not found.

### ISSUE THREAD

**Issue by jeonjonghyeok** [wsdjeg/SpaceVim#4055]
## Expected behavior, english is required

I think it is an error that the go-code binary file could not be found.
However, the $GOPATH/bin/gocode file exists.

I don't know why
## Environment Information
  - OS: mac
  - vim version: -
  - neovim version: 0.4.4
  - SpaceVim version: 1.7.0-dev
  - SpaceVim status: 5b7607a1^@
 
## The reproduce ways from Vim starting (Required!)
 - Open go file
 -  enter anything
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
<img width="491" alt="Screen Shot 2021-01-19 at 4 33 55 PM" src="https://user-images.githubusercontent.com/47622475/105002130-28136d00-5a74-11eb-9627-5aa525bd92f1.png">

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
Please read deoplete-go documentation.
https://github.com/deoplete-plugins/deoplete-go#gdeopletesourcesgogocode_binary

The default path is empty.
You need to set the path.

**Comment by jeonjonghyeok** [comment]
> Please read deoplete-go documentation.
> https://github.com/deoplete-plugins/deoplete-go#gdeopletesourcesgogocode_binary
> 
> The default path is empty.
> You need to set the path.

I couldn't solve it for a long time
I solved it thanks to you. Thank you very much.

**Comment by Shougo** [comment]
the issue should be closed

**Comment by wsdjeg** [comment]
Thanks.
