### ISSUE TITLE
JavaScript eslint does not look for global setting and fail on extension

### ISSUE THREAD

**Issue by convers39** [wsdjeg/SpaceVim#4057]
## Expected behavior, english is required
I follow the doc to set up the env for JavaScript: [here](https://spacevim.org/use-vim-as-a-javascript-ide/)

I expect that I can use a global setting of eslint to lint my code on save.

## The reproduce ways from Vim starting (Required!)

So there are 2 phases of this issue:
- Before I install `eslint-cli`:
When I save the file or format the file, spacevim will trigger the linting to look for a global `.eslintrc` setting file as expected, while it will report an error that the extends of `airbnb` is not found.

- After I install `eslint-cli`:
Now it will not look for a global `.eslintrc`, instead will report an error said cannot find local eslint.
At this moment I cannot reproduce the first phase issue now, even if I uninstall the `eslint-cli` it still reports this 'cannot find local eslint' error.
However, when I reinstall `eslint` globally by `npm install -g eslint`, the issue returns to the first phase.

Here are my settings in `init.toml`:

```vim
56  [[layers]]
  1   name = "lang#javascript"
  2   auto_fix = true
  3
  4 [[layers]]
  5   name = "format"
  6   format_on_save = true
```
In my home directory, I have this `.eslintrc` file:
```vim
 6 {
  5   "extends": ["airbnb-base"],
  4   "env": {
  3   ┊ "node": true,
  2   ┊ "es6": true,
  1   ┊ "browser": true
7     },
  1   "rules": {
  2   ┊ "no-console": "off"
  3   }
  4 }

```

#### Phase 1: 
Before install `eslint-cli` or reinstall `eslint` globally
```
Neomake: eslint: unexpected output on stderr:
Oops! Something went wrong! :(
ESLint: 7.18.0
ESLint couldn't find the config "airbnb-base" to extend from. Please check that the name of the config is correct.
The config "airbnb-base" was referenced from the config file in "/Users/Jerry/.eslintrc".
If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

#### Phase 2:
After install `eslint-cli` globally:
```
Neomake: eslint: unexpected output on stderr: Cannot find local ESLint!
Please install ESLint by `npm install eslint --save-dev`.
```

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Sorry for late reply, It seems a bug of spacevim and neomake. but I can not reproduce it now.

**Comment by wsdjeg** [comment]
[eslint-cli](https://github.com/eslint/eslint-cli/issues) is a local eslint executor. so you need to install eslint and run `eslint --init` as I know, The Neomake debug info should contains the full comamnd of lint.
