### ISSUE TITLE
Vim-GTK

### ISSUE THREAD

**Issue by JesusChapman** [wsdjeg/SpaceVim#4061]
Space vim is a very good ide I like, but..., there is a bug or error, I am now using vim-gtk, because it is more versatile to use,  vim gtk It looks like this :

![Screenshot_20210126-131944](https://user-images.githubusercontent.com/64093255/105887349-a07caf80-5fd9-11eb-8a21-bff360cc0989.png)

But when installing space, vim, tube a very horrible experience with the graphical interface, :

![Screenshot_20210126-132046](https://user-images.githubusercontent.com/64093255/105887452-c2763200-5fd9-11eb-8b3c-2d8272c41e2b.png)

Me gustaría que quitaran eso o añadieran soporte para vim-gtk

**Comment by wsdjeg** [comment]
you need to install nerd-fonts

**Comment by JesusChapman** [comment]
Okey, y los botones?
