### ISSUE TITLE
Support for more powerline separators

### ISSUE THREAD

**Issue by 1dancook** [wsdjeg/SpaceVim#4062]
Would be great to see full support for different glyphs provided by nerd font for powerline. 

Some examples and a list of glyphs are here: [https://awesomeopensource.com/project/ryanoasis/powerline-extra-symbols](https://awesomeopensource.com/project/ryanoasis/powerline-extra-symbols)

Or, please indicate how someone can customize this in their config.

Thanks!

**Comment by wsdjeg** [comment]
@1dancook most of these has been added into `core#statusline` layer
