### ISSUE TITLE
how to keep FlyGrep window open?

### ISSUE THREAD

**Issue by scil** [wsdjeg/SpaceVim#4074]
## Describe the behavior that you expect from SpaceVim

I hope FlyGrep window keep open after a file item opened, and later, I can easily jump back to FlyGrep window.

## Describe the problem

**[This is a mandatory section]**

sometime I need to open multiple files in FlyGrep window.

## Describe steps to reproduce the problem

**[This is a mandatory section]**

press `SPC s d` and search something, FlyGrep window open and show a list of files. Press `Enter` then the FlyGrep window disapear.

**Comment by wsdjeg** [comment]
No, flygrep do not support this feature, but, you can use preview feature of flygrep, and the key binding is `Ctrl-p`
