### ISSUE TITLE
Should code actions work?

### ISSUE THREAD

**Issue by pimeys** [wsdjeg/SpaceVim#4077]
I've been evaluatin SpaceVim for the past few days, and I'm wondering when using lsp, cog and rust-analyzer, should I be able to execute code actions with some keyboard shortcut? In Doom Emacs it's handily in `<SPC> + c + a`, but I haven't found any docs how it should work.

For neovim-lsp, there's instructions the function `lua vim.lsp.buf.code_action()`, but on SpaceVim I get an error `attempt to index field 'lsp' (a nil value).

I also see the docs mentioning how code actions should work, but nothing about how and with what command.

With code actions I mean automatic imports, implementing stubs for traits and all that stuff.

**Comment by wsdjeg** [comment]
@pimeys Hi, the lsp layer of spacevim use language-client.nvim for neovim, and vim-lsp for vim8, so the code action feature should be provided by these two plugins. But yeah, we do not provide key binding for it, bucause I do not know which key binding is the best one for code actions.

BTW, the neovim-lsp requires neovim 0.5.0, maybe we need to wait for the 0.5.0 release.

**Comment by pimeys** [comment]
Good to know. In my FreeBSD laptop I'm having 0.4.4 (even in ports) right now. Maybe I need to wait and continue using Emacs for a while, see where NeoVim's at when it hits 0.5.

**Comment by wsdjeg** [comment]
the nvim lsp has been added. so you can use the code action now.
