### ISSUE TITLE
javac config support

### ISSUE THREAD

**Issue by edisonlove** [wsdjeg/SpaceVim#409]
## Environment Information
- OS:windows
- vim version:8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
i can't find javac config for neomake ,but ale lint with " let g:ale_java_javac_options = '-encoding UTF-8'" works well,can fix it or tell me how to config in neomake?

**Comment by wsdjeg** [comment]
you should read doc of neomake, and it's javac chacker

**Comment by wsdjeg** [comment]
use `g:neomake_java_javac_options`
