### ISSUE TITLE
Error detected while processing function SpaceVim#commands#update_plugin

### ISSUE THREAD

**Issue by Yuchen971** [wsdjeg/SpaceVim#4099]
## Expected behavior, english is required
I installed spacevim according to the readme and found that the plugin could not be installed.
vim, neovim, and spacevim have all been reinstalled and the problem still exists.

## The reproduce ways from Vim starting (Required!)
Once installed it will prompts
## Debug info
line    6:
E171: Missing :endif
ErroUpdating plugins (5/51)sing function SpaceVim#commands#update_pl
ugin[9]..SpaceVim#plugins#manager#update[59]..<SNR>190_pull[45]..<SN
R>190_pull[45]..<SNR>190_pull[45]..<SNR>190_pull[45]..<SNR>190_pull[
45]..<SNR>190_pull:
line    6:
E171: Missing :endif
Error detected while processing function SpaceVim#commands#update_pl
ugin[9]..SpaceVim#plugins#manager#update[59]..<SNR>190_pull[45]..<SN
R>190_pull[45]..<SNR>190_pull[45]..<SNR>190_pull[45]..<SNR>190_pull:

line   45:
E171: Missing :endif
Error detected while processing function SpaceVim#commands#update_pl
ugin[9]..SpaceVim#plugins#manager#update[59]..<SNR>190_pull[45]..<SN
R>190_pull[45]..<SNR>190_pull[45]..<SNR>190_pull:
line   45:
E171: Missing :endif
Error detected while processing function SpaceVim#commands#update_pl
ugin[9]..SpaceVim#plugins#manager#update[59]..<SNR>190_pull[45]..<SN
R>190_pull[45]..<SNR>190_pull:
line   45:
E171: Missing :endif
Error detected while processing function SpaceVim#commands#update_pl
ugin[9]..SpaceVim#plugins#manager#update[59]..<SNR>190_pull[45]..<SN
R>190_pull:
line   45:
E171: Missing :endif
Error detected while processing function SpaceVim#commands#update_pl
ugin[9]..SpaceVim#plugins#manager#update[59]..<SNR>190_pull:
line   45:
E171: Missing :endif
Error detected while processing function SpaceVim#commands#update_pl
ugin[9]..SpaceVim#plugins#manager#update:
line   59:
E171: Missing :endif
Error detected while processing function SpaceVim#commands#update_pl
ugin:
line    9:
E171: Missing :endif
Press ENTER or type command to continue
## Screenshots
<img width="893" alt="Screen Shot 2021-02-17 at 5 46 49 pm" src="https://user-images.githubusercontent.com/54530856/108186263-1f33bb00-7148-11eb-8308-339e397cf3ce.png">

<img width="1322" alt="Screen Shot 2021-02-17 at 5 50 32 pm" src="https://user-images.githubusercontent.com/54530856/108186727-aed96980-7148-11eb-995c-5a7b27240b5a.png">

**Comment by wsdjeg** [comment]
what's the reproduce step? and what is your vim version?

**Comment by Yuchen971** [comment]
I have this problem every time I install it.
even if I reinstall all the files about vim and spacevim I still get the error, the plugin installer doesnt work

the vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 28 2020 13:00:25)
macOS version
Included patches: 1-2164
Compiled by Homebrew

**Comment by Yuchen971** [comment]
sorry, fixed it. it was my ssh error.
