### ISSUE TITLE
Python 3 not handle when using with spacevim on osx sierra

### ISSUE THREAD

**Issue by mnivoliez** [wsdjeg/SpaceVim#41]
Hello. I encounter a strange behavior.
### What is expected
`:echo has('python3') = 1`
### What I got
`:echo has('python3') = 0`
### Details
At first I thought it was a neovim problem, but when running `nvim -u NORC`, `:echo has('python3') = 1`.

I'm using OSX Sierra, iTerm2.
`python --version = Python 2.7.13`
`python3 --version = Python 3.6.0`
`nvim --version NVIM 0.1.7`

**Comment by wsdjeg** [comment]
@mnivoliez you need install python-client for neovim. see https://github.com/neovim/neovim/wiki/Installing-Neovim

BTW, here is my stack for neovim in ubuntu.
Q:how to install neovim in ubuntu?
A:
```bash
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
sudo apt-get install python python3 python-dev python3-dev python-pip python3-pip
pip2 install --user neovim
pip2 install --upgrade --user neovim
pip3 install --user neovim
pip3 install --upgrade --user neovim
```

I think you should use `pip3 install --user neovim`, and `let g:python3_host_prog = '/path/to/python3'`

see https://neovim.io/doc/user/provider.html#provider-python

**Comment by mnivoliez** [comment]
It's already done. I got the problem only when launching neovim with spacevim config. 

```
pip3 install --user neovim
Requirement already satisfied: neovim in ./Library/Python/3.6/lib/python/site-packages
Requirement already satisfied: greenlet in /usr/local/lib/python3.6/site-packages (from neovim)
Requirement already satisfied: msgpack-python>=0.4.0 in /usr/local/lib/python3.6/site-packages (from neovim)
```

when launching `nvim`:
`:echo has('python3') = 0`
`:echo system([g:python3_host_prog, '--version']) = Python 3.6.0`
when launching with `nvim -u NORC`
`:echo has('python3') = 1`
`:echo system([g:python3_host_prog, '--version']) = Python 3.6.0`

I use archlinux at home, the problem did not show up.

**Comment by wsdjeg** [comment]
@mnivoliez so what is the result of `:CheckHealth`?

**Comment by mnivoliez** [comment]
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.12
  - SUCCESS: Latest python2-neovim is installed: 0.1.12

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.0
  - INFO: python3-neovim version: 0.1.12
  - SUCCESS: Latest python3-neovim is installed: 0.1.12

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
  - INFO: Host Executable: /usr/local/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1
```

**Comment by wsdjeg** [comment]
Maybe your g:var been overrite. what is the result of `echo g:python3_host_prog`. If it is overrited, it is a bug of SpaceVim.

**Comment by mnivoliez** [comment]
It returns me `/usr/local/bin/python3` wich is what I put in my `.local.vim`. 
```
which python3
/usr/local/bin/python3
```

**Comment by wsdjeg** [comment]
ok, no idea. will ask it in #neovim tonight. It should  be bug.

**Comment by FrankFang** [comment]
It occurs to me too.

**Comment by mhinz** [comment]
I'm using nvim 0.1.7 and Python 3.6 on macOS as well.

@FrankFang Same versions?

What's the output of:

```
nvim -u NORC +'CheckHealth provider' +'echo has("python3")'
```

If the `:CheckHealth` output for Python 3 looks good but you still see a `0` in the command-line, something is wrong for sure.

**Comment by mnivoliez** [comment]
Ok, so here the output I got for `nvim -u NORC +'CheckHealth provider' +'echo has("python3")'`:
```
health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.12
  - SUCCESS: Latest python2-neovim is installed: 0.1.12

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.0
  - INFO: python3-neovim version: 0.1.12
  - SUCCESS: Latest python3-neovim is installed: 0.1.12

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
  - INFO: Host Executable: /usr/local/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1
```
and 1 for python.

**Comment by mhinz** [comment]
Okay, then it's most likely a bug in SpaceVim not in Neovim. Hmm.

**Comment by satansdeer** [comment]
Getting the same issue.

**Comment by jvlar** [comment]
It seems to come from [here](https://github.com/SpaceVim/SpaceVim/blob/759ddf01c921a048e93b683c2d79937c49a50490/config/init.vim#L64)
```
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
```
This is fine on Linux but on mac python is in `/usr/local/bin`

I changed the path there and now `:echo has('python3')` returns `1`.

**Comment by wsdjeg** [comment]
@jeromevlarouche @mnivoliez if so, #42 maybe can fix this issue.

**Comment by jvlar** [comment]
#42 doesn't fix it for me, I guess that by default `python_host_prog` isn't set so it defaults back to the wrong path for osx

**Comment by wsdjeg** [comment]
@jeromevlarouche you should set `python_host_prog` in `~/.local.vim` if the default path is ~~not~~ wrong for you. If after setting this value in `~/.local.vim` nvim works well, #42 should be merged.

**Comment by mhinz** [comment]
Then it should be mentioned in the documentation, because it could happen that people installed the Python module or the Ruby gem for neovim properly, but it still won't work, since SpaceVim sets a hardcoded path.

IMHO, setting a wrong fixed path is worse (more confusing) than not setting `g:python_host_prog` and friends at all, since then, Neovim will figure it out itself. Then, if it takes too long for them at starting time, they can still set those variables.

**Comment by wsdjeg** [comment]
@mhinz neovim now can figure it out itself? if so I will remove this value setting for linux

**Comment by mhinz** [comment]
It _should_, yup. It tries all working Python installations until importing the `neovim` module succeeds: [provider#pythonx#Detect()](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim#L49-L62)

**Comment by wsdjeg** [comment]
There is no `python3.6` in the list, though, will that cause a issue?

**Comment by mhinz** [comment]
Well, you usually have a symlink to `python3` or `python3` points to `python3.6`, so it should work nevertheless. But you're right, I'll add it to Neovim.

**Comment by wsdjeg** [comment]
ok, will remove the setting.

**Comment by wsdjeg** [comment]
Done.
