### ISSUE TITLE
[dein] Plugin name "vimshell.vim" is already defined

### ISSUE THREAD

**Issue by jrossmann** [wsdjeg/SpaceVim#4101]
## Expected behavior, english is required
vim startup without error messages

## The reproduce ways from Vim starting (Required!)
start vim with my init.toml:

[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    #colorscheme = "gruvbox"
    #colorscheme_bg = "dark"
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    # Update SpaceVim automatically
    automatic_update = true
    # Default indentation 4
    default_indent = 4
    # Use nerdtree filemanager
    filemanager = "nerdtree"

# Default enabled layers
# autocomplete    - Code autocompletion
# checkers        - Syntax checking
# format          - Code formatting
# edit            - Edit key bindings
# ui              - IDE-line UI
# core            - SpaceVim core layer
# core#banner     - Default banners for welcome page
# core#statusline - Heavily customized powerline
# core#tabline    - Simple tabline
#
# Enable autocomplete layer
[[layers]]
    name = 'autocomplete    - Simple tabline'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

# Enable shell layer
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

# Enable colorscheme layer
[[layers]]
    name="colorscheme"

# Enable denite layer (fuzzy finder)
[[layers]]
    name = "denite"

# Enable foldsearch layer
[[layers]]
    name = "foldsearch"

# Enable git layer
[[layers]]
    name = "git"

# Enable github layer
[[layers]]
    name = "github"

# Enable VersionControl layer
[[layers]]
    name="VersionControl"

# Enable Jupyter Notebook support
[[layers]]
    name="lang#ipynb"

#Enable html language support
[[layers]]
    name = "lang#html"

# Enable javascript language support
[[layers]]
    name = "lang#javascript"

# Enable markdown support
[[layers]]
    name = "lang#markdown"

# Enable powershell support
[[layers]]
    name = "lang#powershell"

# Enable python language support
[[layers]]
    name="lang#python"
    python_interpreter = "C:\Users\Jan\AppData\Local\Microsoft\Windows Apps\python.exe"

# Enable xml support
[[layers]]
    name = "lang#xml"

# Enable test layer
[[layers]]
    name = "test"

# Enable tools layer
[[layers]]
    name = "tools"

# Enable vim script support
[[layers]]
    name = "vim"

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: 8.1.2269
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: bf748e1e

## Screenshots
> vim
[dein] Plugin name "vimshell.vim" is already defined.
Press ENTER or type command to continue

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Debug info is missing, this has been fixed, please update your SpaceVim.
