### ISSUE TITLE
E121: Undefined variable: words

### ISSUE THREAD

**Issue by rajeshduggal** [wsdjeg/SpaceVim#4103]
## Expected behavior, english is required
I enabled the java layer and language server. When I type in a class name and a dot (e.g: `new Random().` ), I expect it to show me a list of methods. Instead it shows the message: "E121: Undefined variable: words""
I was able to fix this by following these instructions: https://github.com/Shougo/deoplete.nvim#requirements
By running this: `pip3 install --user pynvim`
(I needed to install pip3 on my system first)

## The reproduce ways from Vim starting (Required!)
Turn on the java layer, install the language server, and run "pip3 uninstall pynvim".
Edit a java class.. enter:
`new Random().`
And then you'll see the E121 error.
Maybe this pynvim install step should be added into the spacevim installation steps, or into the installation docs for spacevim users to do manually.

**Comment by Shougo** [comment]
I have fixed it in the latest of neocomplete.
It seems omnifunc implementation error though.

**Comment by wsdjeg** [comment]
@Shougo Thanks, I have update the neocomplete in spacevim, and autocomplete layer is loaded by default, so I use bundle plugin instead.
