### ISSUE TITLE
No [option] for line wrapping

### ISSUE THREAD

**Issue by Diablo-D3** [wsdjeg/SpaceVim#4104]
Currently, SpaceVim has no way to `:set wrap` as an option in init.toml.

**Comment by wsdjeg** [comment]
Vim has 342 `echo len(getcompletion('', 'option'))` options, we can not add all of them into spacevim options. maybe we should provide a better way to setting vim's option in spacevim's toml file. for example:

```
[vim_options]
     xxx = xxx
```

**Comment by interstellarvoyager** [comment]
> ```
> [vim_options]
>      xxx = xxx
> ```

having this would make a world of difference. i have a .vimrc file with a few ```set``` commands that i sadly cannot automatically run anymore.  i tried pasting these in some of the .vim files etc in .SpaceVim/, but that did nothing. anyways, my two cents
