### ISSUE TITLE
fzf plugin is only partially functional right now - a lot of power is currently missing

### ISSUE THREAD

**Issue by zeroasterisk** [wsdjeg/SpaceVim#411]
## Expected behavior, english is recommend

The FZF plugin 
### working

- [x] the `fzf` plugin is loaded via SpaceVim (cool)
- [x] I can run `:FZF` and `:call fzf#run()` correctly
- [x] I can install other plugins which use `fzf` and they seem to work fine (eg: [fzf-filemru](https://github.com/tweekmonster/fzf-filemru) )
- when I show a list of results i can open them using `<enter>`

### not working

- [ ] if I load it myself in custom plugins, it seems to not exist (ok, I can deal)
- [x] I can not run any of the other [handy built in commands](https://github.com/junegunn/fzf.vim#commands) - they don't seem to exist
 - [x] no `:Files`
 - [x] no `:History`
- [x] when I show a list of results i can open them using `<enter>` but I can not open them in a new tab (or split) using `CTRL+t`

... so basically - it's mostly there, but a lot of the vim plugin convenience seems to be lost...

Can we re-enable somehow?

re #406 (see that for my config and whatnot)

**Comment by wsdjeg** [comment]
what is ctrl+t?

**Comment by wsdjeg** [comment]
ctrl+t works well for me.

**Comment by wsdjeg** [comment]
SpaceVim only has fzf installed, there is no fzf.vim, and fzf-filemru need fzf.vim. you should add fzf.vim to your custom plugins.

**Comment by zeroasterisk** [comment]
Thanks! 

I have installed [junegunn/fzf.vim](https://github.com/zeroasterisk/home/blob/master/.SpaceVim.d/init.vim#L15) and now have `:History` (checked off above)...
