### ISSUE TITLE
Tabline display wrong color

### ISSUE THREAD

**Issue by mrbeardad** [wsdjeg/SpaceVim#4114]
## The reproduce ways from Vim starting (Required!)
1. Enter neovim
2. Execute commnad `:tabe`
3. Modify the new buffer in new tab
4. ![image](https://user-images.githubusercontent.com/54128430/109287751-f81f6c80-785e-11eb-9112-8d94e3d79b70.png)

**Comment by wsdjeg** [comment]
Thanks, this is a bug of the tabline plugin in spacevim.
