### ISSUE TITLE
gtags has issues on 1.7.0-dev

### ISSUE THREAD

**Issue by Guobacai** [wsdjeg/SpaceVim#4118]
Under the project folder, using `SPC m g c` to create a tag database.
But, when I try to locate any function definition by using `Ctrl ]`, it reports the following error:

> E432: Tags file not sorted:
> E426: tag not found:

Here is my layers setup:
[[layers]]
name = 'gtags'
gtagslabel = 'pygments'

## Expected behavior, english is required
It should show the definition of the function.

## The reproduce ways from Vim starting (Required!)
1. Go the root directory of the project
2. type `vim`
3. Run command `SPC m g c`
4. Open a source code file and find a function
5. Hit `Ctrl ]`

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

I am a newbie to the spacevim. I am trying to use spacevim as my daily development env of Javascript.

There might be something I didn't setup correctly. But, I have followed all the instructions in this doc: https://spacevim.org/layers/gtags/

So, I assume this might be an issue on 1.7.0-dev. If it is not, could you advice how to setup it correctly?

**Comment by wsdjeg** [comment]
@Guobacai which programming language are you using?

**Comment by wsdjeg** [comment]
`ctrl-]` is not key binding for gtags, it is for ctags.

**Comment by wsdjeg** [comment]
you should install https://github.com/universal-ctags/ctags, and when saving file, the ctags database of current project will be updated. I have tested it with my js project, it works well for me.
