### ISSUE TITLE
Unique folder paths for swap files

### ISSUE THREAD

**Issue by f-r-o-g** [wsdjeg/SpaceVim#4121]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated writing Ansible playbooks, when Neovim was killed for some reason. The issue is trying to figure out after restarting Neovim which swapfile belongs to which Ansible role when they have the same name. Which is rather common.

**Steps to reproduce**
```
mkdir test1 test2
touch test1/test.yml
touch test2/test.yml
nvim test1/test.yml test2/test.yml
killall nvim

ls -l .cache/SpaceVim/swap/
-rw-r--r-- 1 test test 4.0K Mar  2 23:06 test.yml.swo
-rw-r--r-- 1 test test 4.0K Mar  2 23:05 test.yml.swp
```
**Describe the solution you'd like**
Open the files I worked with last without guessing if this is the right file. Or the option to configure the behavior in the init.toml.

**Describe alternatives you've considered**
My current workaround is to edit .SpaceVim/autoload/SpaceVim/default.vim
and add two slashes to the swap directory.
`let g:swap_dir = g:data_dir . 'swap//'`
```
ls -l .cache/SpaceVim/swap/
-rw-r--r-- 1 test test 4.0K Mar  2 23:32 %home%test%test1%test.yml.swp
-rw-r--r-- 1 test test 4.0K Mar  2 23:32 %home%test%test2%test.yml.swp
```

**Comment by wsdjeg** [comment]
@f-r-o-g Thank you, but why adding two slash can fix this issue, is there any info about this?

**Comment by f-r-o-g** [comment]
@wsdjeg I found this in the [Vim documentation](http://vimdoc.sourceforge.net/htmldoc/options.html#'directory')

> For Unix and Win32, if a directory ends in two path separators "//"
	  or "\\", the swap file name will be built from the complete path to
	  the file with all path separators substituted to percent '%' signs.
	  This will ensure file name uniqueness in the preserve directory.
	  On Win32, when a separating comma is following, you must use "//",
	  since "\\" will include the comma in the file name.
