### ISSUE TITLE
use file instead of stdin on python.vim

### ISSUE THREAD

**Issue by CyberDruga** [wsdjeg/SpaceVim#4128]
**Is your feature request related to a problem? Please describe.**
Since Python layer uses stdin i can't use the \_\_file\_\_ variable because it is only defined on file execution.

**Describe the solution you'd like**
It would be nice to expose an option on init.toml to opt in or out of using stdin with python layer.

**Describe alternatives you've considered**
I really don't see any benefit in executing a python script from stdin. So also hard coding it to use the file would work just fine.

**Additional context**
Here I try to show \_\_file\_\_ value with stdin enabled:
![image](https://user-images.githubusercontent.com/22626848/110886758-ec549100-82c7-11eb-9240-7115d675d856.png)
And here I try to show \_\_file\_\_ value with stdin disabled:
![image](https://user-images.githubusercontent.com/22626848/110886874-17d77b80-82c8-11eb-95a3-6d5708d00175.png)

the only changes being the __opt__ from one dash to two dashes and __usestdin__ from 1 to 0

**Comment by wsdjeg** [comment]
same as https://github.com/SpaceVim/SpaceVim/issues/3904, and has been fixed.
