### ISSUE TITLE
Unknown function: <SNR>68_set_buf_line after fresh install

### ISSUE THREAD

**Issue by versine** [wsdjeg/SpaceVim#413]
## Expected behavior
Immediately after installing SpaceVim, starting MacVim gives me this error:

> Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install:
> line   13:
> E117: Unknown function: <SNR>68_set_buf_line

and after pressing enter once:
> [dein] command NERDTreeToggle is not found.  

Expected behavior is this doesn't happen :)

## Environment Information
- OS: macOS Sierra 10.12.4
- vim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2017 15:38:21)
MacOS X (unix) version
Included patches: 1-525
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cursorbind      +fullscreen      +modify_fname    +path_extra      +syntax          +viminfo
+arabic          +cursorshape     -gettext         +mouse           +perl/dyn        +tag_binary      +vreplace
+autocmd         +dialog_con_gui  -hangul_input    +mouseshape      +persistent_undo +tag_old_static  +wildignore
+balloon_eval    +diff            +iconv           +mouse_dec       +postscript      -tag_any_white   +wildmenu
+browse          +digraphs        +insert_expand   -mouse_gpm       +printer         -tcl             +windows
++builtin_terms  +dnd             +job             -mouse_jsbterm   +profile         +termguicolors   +writebackup
+byte_offset     -ebcdic          +jumplist        +mouse_netterm   +python/dyn      +terminfo        -X11
+channel         +emacs_tags      +keymap          +mouse_sgr       +python3/dyn     +termresponse    -xfontset
+cindent         +eval            +lambda          -mouse_sysmouse  +quickfix        +textobjects     +xim
+clientserver    +ex_extra        +langmap         +mouse_urxvt     +reltime         +timers          -xpm
+clipboard       +extra_search    +libcall         +mouse_xterm     +rightleft       +title           -xsmp
+cmdline_compl   +farsi           +linebreak       +multi_byte      +ruby/dyn        +toolbar         -xterm_clipboard
+cmdline_hist    +file_in_path    +lispindent      +multi_lang      +scrollbind      +transparency    -xterm_save
+cmdline_info    +find_in_path    +listcmds        -mzscheme        +signs           +user_commands
+comments        +float           +localmap        +netbeans_intg   +smartindent     +vertsplit
+conceal         +folding         +lua/dyn         +num64           +startuptime     +virtualedit
+cryptv          -footer          +menu            +odbeditor       +statusline      +visual
+cscope          +fork()          +mksession       +packages        -sun_workshop    +visualextra

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
`:message` produces

> Messages maintainer: Bram Moolenaar <Bram@vim.org>
> Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install:
> line   13:
> E117: Unknown function: <SNR>68_set_buf_line
> [dein] command NERDTreeToggle is not found.  

`:echo SpaceVim#logger#viewLog()` opens the SpaceVim options list.

**Comment by jefft255** [comment]
I have the exact same issue on a freshly built vim 8.0. I am running Bash on Windows 10 (Ubuntu 14.04 subsystem).

**Comment by wsdjeg** [comment]
Hmm, your vim do not support python? 

Will fix it.

**Comment by idchlife** [comment]
this is odd, @wsdjeg , every fresh installation on fresh ubuntu based system I get simiilar error:

```python
Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install[18]..<SNR>115_setl
ine[2]..6:
line   19:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install[18]..<SNR>115_setl
ine[2]..6:
line   19:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install[18]..<SNR>115_setl
ine[2]..6:
line   19:
AttributeError: module 'string' has no attribute 'atoi'
Press ENTER or type command to continue
```

**Comment by wsdjeg** [comment]
please create new issue
