### ISSUE TITLE
add to runner auto focus/quick close 

### ISSUE THREAD

**Issue by kobzar** [wsdjeg/SpaceVim#4130]
The problem is when you are working on small devices with 10 inch.
After we run the code the part of display (bottom) is busy by results window.
The are many actions we must do to make screen space free.
Select results window and close it. For example its look like
<Space> 1 q
Ctrl w w q
This commands is to long for usually actions.
Could you provide the solution to make results window is active when RUN is finished/runned ?
That we can press q and continue working with code in main window?
Thanks.

**Comment by wsdjeg** [comment]
Move to google mail list.
