### ISSUE TITLE
neocomplete does not work with Vim 8.2.1066+.

### ISSUE THREAD

**Issue by sayhei** [wsdjeg/SpaceVim#4132]
OS: macOs11.2.2 

when i use vim (version:8.2)
when i edit a file,this error out: 
      _**neocomplete does not work with Vim 8.2.1066+.**_ 
then i set autocomplete_method = "deoplete",anthor error is happened :
      <img width="1061" alt="WX20210315-152228@2x" src="https://user-images.githubusercontent.com/8320880/111117280-498b6380-85a2-11eb-9e7b-9b5456159359.png">

then i use neovim(0.4.4)
these errors are gone,but anthor error turn out.
i follow [https://spacevim.org/use-vim-as-a-java-ide/](https://spacevim.org/use-vim-as-a-java-ide/) to set up my java enviroment step by step ,when i use _**Spc l e**_ to Rename symbol ,i see: 

<img width="408" alt="企业微信20210315-152103@2x" src="https://user-images.githubusercontent.com/8320880/111117142-1517a780-85a2-11eb-9dfe-c779dfc59224.png">

I tried to install and configure many times, but failed. Who can help me。

**Comment by Shougo** [comment]
> neocomplete does not work with Vim 8.2.1066+.

You cannot use neocomplete in the Vim.  Because Vim breaks the backward compatibility.

> then i set autocomplete_method = "deoplete",anthor error is happened :

You need to install `pynvim` module by `pip3`.
https://github.com/roxma/vim-hug-neovim-rpc#requirements

**Comment by sayhei** [comment]
after i installed pynvim module by pip3,
![image](https://user-images.githubusercontent.com/8320880/111265633-60928a00-8664-11eb-83f9-508c1a2e20dc.png)
the same error:
> [vim-hug-neovim-rpc] Vim(pythonx):ModuleNotFoundError: No module named 'neovim'
![image](https://user-images.githubusercontent.com/8320880/111265711-7902a480-8664-11eb-9c92-ea2c1e67d7dc.png)

**Comment by Shougo** [comment]
You should pynvim is available in Vim Python.

**Comment by Shougo** [comment]
I think your Python is different environment from Vim Python.

**Comment by sayhei** [comment]
thanks, i found it ,my vim python is different with my python

**Comment by Shougo** [comment]
Oh, as I thought

**Comment by chris-aeviator** [comment]
so how to solve this? I have used my vim console (`:!pip3 install pynvim`) which says "requirement already satisfied" but still run into this when e.g. running `:call deoplete#enable()`

EDIT: seems only `:py3 import pip; pip.main(['install', '--user', 'pynvim'])` succeeds for me, calling `python3 -m pip....` did not do the job, neither did pip3 install
