### ISSUE TITLE
Don't jump to first match when there're multiple matches for gtags layer

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#4135]
**Is your feature request related to a problem? Please describe.**
In large project, there always functions with the same name.  When using gtags layer (e.g. ``SPC m g d`` or ``SPC m g r``), it will have multiple matches.  Currently, SpaceVim jump to first match automatically, which may or may not user want.  When it's not what user want, an unnecceary buffer is opened, and the buffer list is cluttered up.

**Describe the solution you'd like**
Don't jump to first match when there're multiple matches, let user choose which one to open.

**Describe alternatives you've considered**
Add an option to control whether automatically jump to first match.

**Comment by wsdjeg** [comment]
This is feature of command `:cexpr`, I can not fix it now. as I know in neomake or other lint plugin, it will not jump to the first error, but I do not know how to do it.

**Comment by thawk** [comment]
It seem like neomake use ``setline()`` instead ``:cexpr``.
After some surfing, it seems that both vim/neovim support ``:cgete[xpr]``, which just like ``:cexpr`` but don't jump to the first error.

**Comment by wsdjeg** [comment]
`setline()` can not change the context of qf windows, it should `setqflist()`. I will checkout `:cgete`

**Comment by wsdjeg** [comment]
In #4172, gtags will not jump to the matches any more. we should check if the there is only one result, then jump to that position.

**Comment by thawk** [comment]
* we can check whether there is multiple result
  ```vim
  l:result =~# '\n.'
  ```
* because ``cgetexpr`` doesn't focus on quickfix window, we should open and jump to it. I have try the following logic:
  - get buffer number of quickfix: ``let l:qf = filter(tabpagebuflist(), 'getbufvar(v:val, "&buftype") ==# "quickfix"')``
  - if ``!empty(l:qf)``, use ``bufwinnr()`` to get window number from previous result: ``let l:wnr = bufwinnr(l:qf[0])``
  - if ``l:wnr >= 0``, quickfix window is already opened, ``exe l:wnr . "wincmd w"``, or ``copen`` to open it

**Comment by wsdjeg** [comment]
Ok, I will improve the `gtags` layer, and maybe we should use `job` feature instead of `system()` for running gtags command.

**Comment by wsdjeg** [comment]
@thawk The gtags layer has been updated, and did you test the latest version of spacevim?

**Comment by thawk** [comment]
Yes, the latest version **doesn't** jump to the first match.
I wish if the quickfix window is not opened automatically while there's only one match.  Since we have jump to it, it's not use to open it.

**Comment by wsdjeg** [comment]
the code is:

```
  cgetexpr l:result

  let &efm = l:efm_org

  " If there is only one item, jump to the position.
  if len(getqflist()) ==# 1
    silent cc
  endif
```

I think it is what you want, only if there is only one match, jump to it.

**Comment by wsdjeg** [comment]
you can load the `gtags` layer via:

```
[[layers]]
    name = 'gtags'
    open_quickfix = 0
```

for more info, checkout `:h SpaceVim-layer-gtags`

**Comment by thawk** [comment]
Yes, it does what it said.  I can hit [SPC]el to toggle it.
It could be better if quickfix isn't open automatelly when there's only one match, so we don't need to close it manually.

**Comment by wsdjeg** [comment]
I think it is a new bug or feature request. Pleasce use new email thread.
--------------
wsdjeg

**Comment by wsdjeg** [comment]
This commit should be what you need:

https://github.com/SpaceVim/SpaceVim/commit/1bbc24ea4d0d905e38fd7ded1516f36f7a1bb92b
--------------
wsdjeg
