### ISSUE TITLE
[Feature Request] Add an option to use upstream versions of bundled plugins

### ISSUE THREAD

**Issue by zeertzjq** [wsdjeg/SpaceVim#4138]
**Is your feature request related to a problem? Please describe.**
Bundled plugins are too old. Some of them are several months behind their upstream versions.

**Describe the solution you'd like**
Add an option to use upstream versions of bundled plugins.

**Describe alternatives you've considered**
Add every bundled plugin to `disabled_plugins` and add them as `custom_plugins`. I have not tried this and am not sure whether this will work.

**Comment by wsdjeg** [comment]
Sorry, This can not be done in SpaceVim, because we need to check all of the updated before merged into spacevim, we need to fix the compatiblity.
