### ISSUE TITLE
CPU consume a lot when not in git repo directory

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#4142]
## Expected behavior, english is required

If git layer and VersionControl layer is enabled, then when current directory isn't inside a git repo, SpaceVim spends lots of CPU to try to get git branch name again and again.

* ``SpaceVim#layers#VersionControl#config()`` adds a ``vcs`` section for ``s:git_branch()``
* ``s:git_branch()`` use ``%{git#branch#current()}``
* ``%{git#branch#current()}`` checks if ``s:branch`` is empty, if so, call ``s:update_branch_name()``
* ``s:update_branch_name()`` calls shell command ``git rev-parse --abbrev-ref HEAD``

Becuase we are not in git repo, it already can't get git branch name, so ``s:branch`` is already empty, and it try getting branch name again and again.
In my server with RHEL 7, it use almost one CPU for every nvim instance.

Maybe we should remember the last directory, and update cache when and only when current directory is changed?

## The reproduce ways from Vim starting (Required!)

* Make sure ``VersionControl`` and ``git`` layer is enabled in ``init.toml``
* Enter a directory, not in git repo.
* run nvim

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Yeah, this is default logic of vcs function.

**Comment by thawk** [comment]
I have a quick and dirty solution, add a ``s:last_update = 0``, and only call ``s:update_branch_name()`` when ``localtime() > s:last_update``.  It make sures only 1 call in 1 second.

**Comment by wsdjeg** [comment]
I have fixed this issue, please update spacevim.

**Comment by thawk** [comment]
@wsdjeg 
Thx, but it seems not work as expected.
In ``s:on_stdout_show_branch()``, when pwd is not in git repo, branch name ``b`` is always empty, so it will not update ``s:branch_info``.  I suggest to update ``s:branch_info`` whether or not ``b`` is empty.

**Comment by wsdjeg** [comment]
@thawk This is expected behavior, if pwd is not git repo, this function should be called again and agin until someone run `:Git init` 
 in spacevim or `git init` outsite vim. and the job command in this function will be called only once a second.

**Comment by thawk** [comment]
@wsdjeg VIM is a general editor, we shouldn't require every file to be version managed, let alone be managed by git.  It's not necessary to check whether pwd is managed by git hundreds time per second.  A little modification is good enough to reduce CPU consumption from near 100% to near 0%.

**Comment by wsdjeg** [comment]
Ok, I reopen this issue, we need a better logic for branch name detection.

**Comment by wsdjeg** [comment]
moved to https://groups.google.com/d/msgid/spacevim/ME3P282MB18429F07DBAF2B6E9142CB47D4209%40ME3P282MB1842.AUSP282.PROD.OUTLOOK.COM

**Comment by wsdjeg** [comment]
@thawk I can not fix this issue now. the branch detection should be on the fly. If we stop the detction when git branch return empty string. we can not start the detection again.

**Comment by wsdjeg** [comment]
and if vim support `+timer` maybe we can implement this feature.

**Comment by thawk** [comment]
> I can not fix this issue now. the branch detection should be on the fly. If we stop the detction when git branch return empty string. we can not start the detection again.

I think we don't need to stop detection, reduce detection fequence is good enough.  e.g. if current query is 1s later after previous query, we can do query again.

**Comment by wsdjeg** [comment]
without timer, you can not set the timeout, the script will be run again and again.

**Comment by thawk** [comment]
We don't need to prevent the script to be run, but prevent it runs hundreds times per second.  So I think prevent repeated calls in a second is good enough, and it shouldn't affect the functional.

**Comment by wsdjeg** [comment]
@thawk I have fixed this issue. the updatetime is added when job exit.
