### ISSUE TITLE
Getting questions marks in the FileTree Mac

### ISSUE THREAD

**Issue by vuvgaG** [wsdjeg/SpaceVim#4144]
## The reproduce ways from Vim starting (Required!)

Default install on a MacOS 11.2.3

## Debug info

I can't use the \<leader\> key to get any information in my clipboard.

## Screenshots

<img width="619" alt="image" src="https://user-images.githubusercontent.com/75189112/112763520-a8b69280-8ffc-11eb-85f6-77372796c8a9.png">

**Comment by wsdjeg** [comment]
You need to install nerd-fonts.
