### ISSUE TITLE
Typing golang code is very hard since an error message keeps popping up

### ISSUE THREAD

**Issue by vuvgaG** [wsdjeg/SpaceVim#4149]
## Expected behavior, english is required

I expect to be able to type code without an error dialog being shown.

## The reproduce ways from Vim starting (Required!)

Default vim installation mac osx 11.2.3

Install gocode layer

## Debug info

Is the error i'm given, how can I get more info on this?

```
[deoplete] gocode panicked.
```

**Comment by Shougo** [comment]
> Install gocode layer

What is gocode layer?  It is not included in SpaceVim.

Which gocode do you use?  Please explain.

**Comment by Shougo** [comment]
And you should use LSP instead.
deoplete-go is very old and it does not works well in the latest go.
No magic.

**Comment by vuvgaG** [comment]
After removing 
![image](https://user-images.githubusercontent.com/75189112/113450130-34626180-93f7-11eb-9eb8-77142e47416e.png)
This just lets me point to the go-code binary 

I get 

![image](https://user-images.githubusercontent.com/75189112/113450078-1bf24700-93f7-11eb-81ba-2ab2bb18e33c.png)

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

**Comment by Shougo** [comment]
> Which gocode do you use? Please explain.

This means you must use the gocode.
https://github.com/stamblerre/gocode

**Comment by Shougo** [comment]
And I don't recommend for you to use deoplete-go.
It does not work well in the latest go binary.
LSP completion is better.

**Comment by vuvgaG** [comment]
> And I don't recommend for you to use deoplete-go.
> It does not work well in the latest go binary.
> LSP completion is better.

Thats what i'm not understanding. How can I enable use usage of LSP. I've upgraded neovim to 0.5 version, how to I configure spacevim to use their LSP facilities ? How can I replace deplete-go? Is that not what the layers do? Would the change require me submitting a PR? i'm happy to do it, just it would be my first.

Love the project by the way. I've been working on my own vim file for a while and I was just getting to the point where plugins would conflict with each other. So this layer idea is great!!!! If only the on boarding was easier. I find that i'm very slow at being able to get things like this installed. And that's what stopped me getting setup before.

**Comment by Shougo** [comment]
> Thats what i'm not understanding. How can I enable use usage of LSP. I've upgraded neovim to 0.5 version, how to I configure spacevim to use their LSP facilities ? How can I replace deplete-go? Is that not what the layers do? Would the change require me submitting a PR? i'm happy to do it, just it would be my first.

I don't know about LSP layer feature.

**Comment by vuvgaG-dukgu3-wysnox** [comment]
> > Thats what i'm not understanding. How can I enable use usage of LSP. I've upgraded neovim to 0.5 version, how to I configure spacevim to use their LSP facilities ? How can I replace deplete-go? Is that not what the layers do? Would the change require me submitting a PR? i'm happy to do it, just it would be my first.
> 
> I don't know about LSP layer feature.

What would be relevant to adding this?

**Comment by vuvgaG** [comment]
> > Thats what i'm not understanding. How can I enable use usage of LSP. I've upgraded neovim to 0.5 version, how to I configure spacevim to use their LSP facilities ? How can I replace deplete-go? Is that not what the layers do? Would the change require me submitting a PR? i'm happy to do it, just it would be my first.
> 
> I don't know about LSP layer feature.

Where can I find the source code for each layer?

**Comment by Shougo** [comment]
Please read this.
https://github.com/SpaceVim/SpaceVim/blob/6a9b01def5e53eebfbaf8ca0d0b6da2a3ddbba09/docs/layers/language-server-protocol.md

**Comment by vuvgaG** [comment]
> > Thats what i'm not understanding. How can I enable use usage of LSP. I've upgraded neovim to 0.5 version, how to I configure spacevim to use their LSP facilities ? How can I replace deplete-go? Is that not what the layers do? Would the change require me submitting a PR? i'm happy to do it, just it would be my first.
> 
> I don't know about LSP layer feature.
