### ISSUE TITLE
SpaceVim screenshots

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#415]
This is a list of SpaceVim screenshorts from users.

**Comment by jetm** [comment]
zsh + tmux (TrueColor) + Spacevim (onedark colorscheme):

<img width="1128" alt="screenshot_20170408_174951" src="https://cloud.githubusercontent.com/assets/474838/24833355/e1565b66-1c83-11e7-85ae-cccc5ed50e4e.png">

**Comment by icearith** [comment]
@jetm which color scheme or theme are you using for tmux?

**Comment by jetm** [comment]
@icearith: I am using [tmux-onedark-theme](https://github.com/odedlaz/tmux-onedark-theme).

**Comment by tracyone** [comment]
[vimr](https://github.com/qvacua/vimr)

<img width="1392" alt="2017-04-11 10 07 26" src="https://cloud.githubusercontent.com/assets/4246425/24913471/dec3e274-1f03-11e7-85aa-898e55fb9fd8.png">

**Comment by wsdjeg** [comment]
@tracyone vimr with SpaceVim? looks very nice.

**Comment by icearith** [comment]
[MacVIM](http://macvim-dev.github.io/macvim/)

![macvim](https://cloud.githubusercontent.com/assets/2555093/24932023/8febcf82-1f07-11e7-8f3f-2abecfbcd8c7.png)

**Comment by wsdjeg** [comment]
![2017-04-12-19 36 27](https://cloud.githubusercontent.com/assets/13142418/24955849/bab3e0fa-1fb7-11e7-86b4-e4b3e64b19a6.png)

**Comment by wsdjeg** [comment]
![2017-04-12-22 45 20](https://cloud.githubusercontent.com/assets/13142418/24963996/a2688828-1fd2-11e7-856a-6b5af349d303.png)

**Comment by wsdjeg** [comment]
Hide split line:
![2017-04-16-23 43 39](https://cloud.githubusercontent.com/assets/13142418/25072373/fc0964ea-22fe-11e7-8be4-375593925bbe.png)

**Comment by unr** [comment]
![image](https://cloud.githubusercontent.com/assets/317957/25405767/549d20ae-29d2-11e7-93e6-54aabbcf768f.png)
![image](https://cloud.githubusercontent.com/assets/317957/25405790/6d42c2ee-29d2-11e7-85e9-b1f7a969018c.png)

**Comment by astromac** [comment]
Neovim on iTerm2 using the SpaceVim color scheme _base16-solarized-dark_

Depicts a common frontend development scenario with JavaScript (jQuery), SASS, and PHP buffers.

Non-code buffers show a Neovim terminal, a TagBar window, a Vimfiler window and a TernJS definition window.

![screen shot 2017-04-26 at 4 28 07 pm](https://cloud.githubusercontent.com/assets/296716/25455341/6af0b728-2a9d-11e7-9721-d2a694dde1a8.png)

**Comment by wsdjeg** [comment]
@astromac nice picture!

**Comment by wsdjeg** [comment]
[![asciicast](https://asciinema.org/a/c5cfke53zkvc81hdpvr22egf5.png)](https://asciinema.org/a/c5cfke53zkvc81hdpvr22egf5)

**Comment by wsdjeg** [comment]
![2017-04-29-20 54 49](https://cloud.githubusercontent.com/assets/13142418/25555650/d7d2c07e-2d1e-11e7-975d-646a07b38a62.png)

**Comment by wsdjeg** [comment]
![tabmanager](https://cloud.githubusercontent.com/assets/13142418/26024878/115b6a90-380e-11e7-9560-10fa4f154bfa.gif)

**Comment by itgoyo** [comment]
@tracyone how to use spacevim preview markdown? 😃

**Comment by icearith** [comment]
VimR with SpaceVim, awesome experience.
The scrolling is really smooth, just like the experience of native macOS Apps. 

The built-in markdown preview of VimR is really an ideal alternative to browser-based tricks.  Gotta have a try @wsdjeg .

<img width="1440" alt="wx20171206-092853 2x" src="https://user-images.githubusercontent.com/2555093/33639829-3c2c0fc0-da68-11e7-9b51-97d75ef979fa.png">

**Comment by wsdjeg** [comment]
Thanks for your info.

**Comment by wsdjeg** [comment]
![2017-12-10-20 02 42](https://user-images.githubusercontent.com/13142418/33804722-bc241f50-dd70-11e7-8dd8-b45827c0019c.png)

**Comment by wsdjeg** [comment]
![2017-12-10-20-07-38](https://user-images.githubusercontent.com/13142418/33804739-52dbc498-dd71-11e7-97e5-ed0fa6ec1719.gif)

**Comment by wsdjeg** [comment]
![2017-12-10-20-19-27](https://user-images.githubusercontent.com/13142418/33804844-1fd00896-dd73-11e7-9685-1c3e189464ad.gif)

**Comment by wsdjeg** [comment]
![2017-12-10_1365x59](https://user-images.githubusercontent.com/13142418/33804880-b9177142-dd73-11e7-82d5-1780dc27e7e3.png)

**Comment by wsdjeg** [comment]
![2017-12-19-21-30-26](https://user-images.githubusercontent.com/13142418/34159605-758461ba-e48f-11e7-873c-fc358ce59a42.gif)

**Comment by wsdjeg** [comment]
![2017-12-23-19-58-16](https://user-images.githubusercontent.com/13142418/34319468-0e1da668-e7a9-11e7-82e0-465225a8ed3f.gif)

If you failed to installed plugin, pressing `gf` on the line of that plugin will open a terminal with path of this plugin.

**Comment by EscapeLife** [comment]
<img width="1273" alt="2018-03-31 23 54 03" src="https://user-images.githubusercontent.com/16237571/38164945-d9f99e6c-353e-11e8-8651-1d8067a76aff.png">

**Comment by ZivLi** [comment]
@astromac nice picture! And which theme of oh-my-zsh do you use?

**Comment by Hellowor1d** [comment]
> Neovim on iTerm2 using the SpaceVim color scheme _base16-solarized-dark_
> 
> Depicts a common frontend development scenario with JavaScript (jQuery), SASS, and PHP buffers.
> 
> Non-code buffers show a Neovim terminal, a TagBar window, a Vimfiler window and a TernJS definition window.
> 
> ![screen shot 2017-04-26 at 4 28 07 pm](https://cloud.githubusercontent.com/assets/296716/25455341/6af0b728-2a9d-11e7-9721-d2a694dde1a8.png)

So beautiful picture it is, may we have a look at your setting ? sincerely

**Comment by wsdjeg** [comment]
Hello, everyone, anyone has 4K screem?

**Comment by RizaHKhan** [comment]
I think my version is lacking something. The status bar is all weird and is missing icons:

![image](https://user-images.githubusercontent.com/51720003/97252059-80253500-17df-11eb-98cd-2c87a3bea53b.png)

Any potential fixes?

**Comment by wsdjeg** [comment]
@RizaHKhan you need to install nerd-fonts.

**Comment by RizaHKhan** [comment]
@wsdjeg 

![image](https://user-images.githubusercontent.com/51720003/97253933-b49af000-17e3-11eb-9c12-3bf86d3bcc74.png)
Like this? If so, didn't help

**Comment by wsdjeg** [comment]
no, nerd-fonts is not Vim plugin, you need to read it's doc.

**Comment by caowei1517** [comment]
![image](https://user-images.githubusercontent.com/102411513/162409422-f6666ffb-786e-4af8-be11-69a4ba6ad905.png)
How to set it to the theme in the figure above and ask for help. thank you!
