### ISSUE TITLE
The install.sh reported NEED 'GIT' (COMMAND NOT FOUND), version 1.7.0-dev

### ISSUE THREAD

**Issue by nszaaa3** [wsdjeg/SpaceVim#4155]
When I use this command 'curl -sLf https://spacevim.org/install.sh | bash -s -- -h', nothing happend,
then I tried download the shell to install mannually, it reported need git, and the version is 1.7.0-dev.

**Comment by Diablo-D3** [comment]
The install script requires `git`.

See https://raw.githubusercontent.com/SpaceVim/SpaceVim/master/docs/install.sh for the raw text.
