### ISSUE TITLE
Remove Neocomplete and Neocomplcache support

### ISSUE THREAD

**Issue by Diablo-D3** [wsdjeg/SpaceVim#4156]
Neocomplete/Neocomplcache is no longer supported by author, doesn't work on anything newer than vim 8.1.x, or any Neovim, support for it should be removed. The author is the esteemed Shougo and Spacevim already supports his new plugin, Deoplete.

See also #4157

**Comment by wsdjeg** [comment]
Sorry, we can not remove neocomplete and neocomplcache support, because I always use vim7.4 in old os.

NOTE: the development of these plugins are done, but these plugins are not deprecated.
