### ISSUE TITLE
Using kite as default autocomplete tool?

### ISSUE THREAD

**Issue by sisrfeng** [wsdjeg/SpaceVim#4161]
**Describe the solution you'd like**
Would you mind using kite, an AI based tool,  as default autocomplete tool? I have installed kite, but now it is not so compatible with spacevim

**Describe alternatives you've considered**
Tabnine is also based on AI, but I think it is not sa powerful as kite

**Additional context**
https://www.kite.com/

**Comment by Shougo** [comment]
https://www.kite.com/download/

Hm...
To create the account is needed.

**Comment by sisrfeng** [comment]
it is free

**Comment by Shougo** [comment]
I don't want to create the account

**Comment by sisrfeng** [comment]
Would you mind telling me why?
I think it cost little time to create the account, and kite is really powful

**Comment by Shougo** [comment]
To create the account means I need manage the account.

**Comment by Shougo** [comment]
OK.  It can be installed without create account.

https://github.com/kiteco/vim-plugin
You can use it for completion.

**Comment by wsdjeg** [comment]
closed, we can not use this plugin as default autocomplete tool.
