### ISSUE TITLE
Segmentation Fault when trying to open vim after install script

### ISSUE THREAD

**Issue by hurnhu** [wsdjeg/SpaceVim#418]
## Expected behavior, english is recommend

I have just rand the install script (curl -sLf https://spacevim.org/install.sh | bash)
open vim and the below error occurs about 5 different times with different error on functions each time.

Error detected while processing function 29:
line    1:
E716: Key not present in Dictionary: _opts, 'on_stdout')
E116: Invalid arguments for function has_key(self._opts, 'on_stdout')
E15: Invalid expression: has_key(self._opts, 'on_stdout')

after it is done erroring out vim closes with a seg fault

## Environment Information
- OS: Ubuntu 16.04.2 LTS
- vim version: version 7.4.1689
- neovim version: not installed

## The reproduce ways from Vim starting (Required!)
1. run curl -sLf https://spacevim.org/install.sh | bash
2. open vim->seg fault

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
unable to open vim

**Comment by aviggiano** [comment]
Same here

- OS: Ubuntu 16.04.1 LTS
- vim version: version 7.4.1689
- neovim version: not installed

**Comment by wsdjeg** [comment]
does your vim has python support?

**Comment by aviggiano** [comment]
I'm not sure, how can I check it?

**Comment by wsdjeg** [comment]
in vim, :echo has('python')

**Comment by aviggiano** [comment]
It outputs `0`

**Comment by wsdjeg** [comment]
you should install vim-gtk,

**Comment by aviggiano** [comment]
Thanks, it worked ([ref](http://askubuntu.com/questions/775059/vim-python-support-on-ubuntu-16-04))

**Comment by wsdjeg** [comment]
Nice, but I think I should fix supporting of vim without +python feature.
