### ISSUE TITLE
tabline confused with tab and buffer

### ISSUE THREAD

**Issue by TangMonk** [wsdjeg/SpaceVim#4188]
Sometime tabline show buffers:

![image](https://user-images.githubusercontent.com/3498786/114291157-c9c8ba00-9ab7-11eb-80ab-a275622c6296.png)

But sometimes tabline show tabs:

![image](https://user-images.githubusercontent.com/3498786/114291169-d64d1280-9ab7-11eb-9e9c-bfa30084edf4.png)

That made me confused, How can I set the default to show tabs, do not show buffers on the tabline just like other familiar editors.

**Comment by wsdjeg** [comment]
please read [vim's tabpage windows and buffer](https://github.com/wsdjeg/vim-galore-zh_cn#%E7%BC%93%E5%86%B2%E5%8C%BA%E7%AA%97%E5%8F%A3%E6%A0%87%E7%AD%BE)

if there are more than one tabs, the tabpage list will be displayed on tabline. if there is only one tabpage, the buffer list will be displayed.

**Comment by TangMonk** [comment]
@wsdjeg, after reading the wiki, I still feel uncomfortable
  
  When tab shows, I often use `:q` to quit tab, But sometime I quit Vim instance accidentally because I am not check the tabline right side status is tab or buffer.
  
  When I close all tab except one exist, the tabline will burst out suddenly, that's weird
  
  
  
  https://user-images.githubusercontent.com/3498786/114296341-65205600-9add-11eb-9a02-2bc0ea57d53a.mov
  
  
  
  I wish there is a way to change tabline tab and buffer behavior for example:
  
  ```
  [options]
      tabline_show_buffers_or_tabs = 'tabs'
  ```

**Comment by wsdjeg** [comment]
`:q` is not used for close tab. it is to close window. You should use `:tabclose` to close tab. 

If you found something unexpected, it must be reproduce able, then we can fix or improve it.

**Comment by wsdjeg** [comment]
I have looked into your video, it is expected behavior. when run `:q` , the tabpage is closed. But the buffer is not deleted. the there are many buffers opened, so all of them will be displayed.

**Comment by TangMonk** [comment]
@wsdjeg Thanks for reply, that's kind of different with other familiar editors,  I think I need to get used to the behavior of tabline. this might be an advantage for some users, but I think there is a option for users is better.
