### ISSUE TITLE
Can not close :help buffer using 

### ISSUE THREAD

**Issue by dalanicolai** [wsdjeg/SpaceVim#4193]
## Expected behavior, english is required

`SPC b d` closes :help buffer

## The reproduce ways from Vim starting (Required!)

start vim
open help: eg. `:help g`
try to close with `SPC b d`

## Debug info
 Clipborad does not work yet

**Comment by wsdjeg** [comment]
ok, this is a bug of SPC b d, in the function, unlisted buffers are skiped:

https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/mapping.vim#L189

**Comment by dalanicolai** [comment]
It is also the case for the configuration file.
After opening the file `SPC f v d` I can not close it with `SPC b d`
