### ISSUE TITLE
In vim `SPC f v d` does not work

### ISSUE THREAD

**Issue by dalanicolai** [wsdjeg/SpaceVim#4196]
## Expected behavior, english is required
In vim `SPC f v d` should open config file (as it does correctly in neovim)

## The reproduce ways from Vim starting (Required!)
Start Spacevim with vim and try to open config with `SPC f v d`

## Debug info
Clipboard does not work yet

**Comment by wsdjeg** [comment]
what is the behavior of `SPC f v d` in your vim?

**Comment by dalanicolai** [comment]
It works correctly now after I updated Spacevim. Before that `SPC f v d` made vim hang up, while in neovim it worked fine...

**Comment by wsdjeg** [comment]
so this issue can be closed? Nothing can be done if it is not reproduce able in master.
