### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by cuckootan** [wsdjeg/SpaceVim#422]
"TaskList.vim" and "ctrlp-cmdpalette" plugins installing failure.

OS: MacOS (10.12.14) and Ubuntu (16.04)

**Comment by wsdjeg** [comment]
I can not reproduce it;
`:SPUpdate ctrlp-cmdpalette TaskList.vim` works well for me;

**Comment by tracyone** [comment]
same issue when open vim file

OS: MacOS (10.12.13)

**Comment by tracyone** [comment]
still failed after SPupdate TaskList.vim

**Comment by wsdjeg** [comment]
@tracyone can you try with vpn? it is just an `git pull` command, and should not be failed.
