### ISSUE TITLE
Tagbar: Filetype detection is turned off, skipping plugin 

### ISSUE THREAD

**Issue by kenis1108** [wsdjeg/SpaceVim#4221]
## Debug info

Tagbar: Filetype detection is turned off, skipping plugin 

## Screenshots

![QQ截图20210421205003](https://user-images.githubusercontent.com/45393183/115556483-4db64980-a2e3-11eb-9d0c-81cddcbb474d.png)

**Comment by wsdjeg** [comment]
No reproduce step, and no debug info, I can not fix it, BTW, please following the doc of spacevim to install and configurate it.

**Comment by kenis1108** [comment]
ok

**Comment by Skyr** [comment]
I get the error when starting vim ("Press ENTER...").
I can provoke it when activating the lang#plantuml layer. My SpaceVim checkout is at current head (3568bcbfae0e2dc98c794c984f66d7fcc65ddedc). Here is my 
[init.toml](https://github.com/SpaceVim/SpaceVim/files/6393498/init.toml.txt), I hope this helps reproducing.
