### ISSUE TITLE
Update PHP layers please

### ISSUE THREAD

**Issue by saifulapm** [wsdjeg/SpaceVim#4231]
Hey Guys, In PHP layer, we are still using PHP_Beautifier for formatting code which not working anymore. We should change something new.

**Comment by wsdjeg** [comment]
so, which command should we use?

**Comment by saifulapm** [comment]
Hey.. For Better PHP syntax, We can use: https://github.com/2072/vim-syntax-for-PHP
For Indent: https://github.com/2072/PHP-Indenting-for-VIm

And For formatting code: https://github.com/stephpy/vim-php-cs-fixer

I think this will be improved PHP layers. 

Thanks

**Comment by wsdjeg** [comment]
@saifulapm I just check the vim's default php syntax, the last changed time is 2020 year. https://github.com/vim/vim/blob/master/runtime/syntax/php.vim
