### ISSUE TITLE
Add Update Command to Update SpaceVim

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#424]
## Expected behavior
I can update `SpaceVim` to the latest version without open a new terminal. Just like `:SPUpdate`

**Comment by wsdjeg** [comment]
hmm, how about `:SPUpdate -self`? or `-l`?

**Comment by tracyone** [comment]
but you have to restart vim ...

**Comment by wsdjeg** [comment]
yeah, it is feature of vim.

**Comment by Gabirel** [comment]
Why not just get rid of redundancy? Just make `:SPUpdate` to update all, including SpaceVim and a massive of plugins

**Comment by wsdjeg** [comment]
how could I do, when I just update spacevim instead of plugins?

**Comment by Gabirel** [comment]
Let's pretend that `SpaceVim` is one of plugins, hahahahaha :laughing:

**Comment by wsdjeg** [comment]
That should be nice, `:SPUpdate SpaceVim`.

**Comment by Gabirel** [comment]
SpaceVim doesn't have auto-completion for `:SPUdate SpaceVim`
