### ISSUE TITLE
Python auto import

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4242]
**Is your feature request related to a problem? Please describe.**

When I use autocompletion to import for example `QAbtractItemModel` from `PyQt5.QtCore` I got suggested `QAbstractItemModel` with `Ctrl-space` and typing the first letters.

It means that SpaceVim was able to find it in the `dist-packages/PyQt5/QtCore.pyi` file. Note the `pyi` extension.

If I use `gd` mapping on `QAbstractItemModel` class in my code **before** writing the import statement, SpaceVim is unable to find the declaration. `jedi-vim: Couldn't find any definitions for this.`

If I user `gd` mapping **after** writing the import statement, all goes well and I'm taken to the definition in the `dist-packages/PyQt5/QtCore.pyi` file.

**Describe the solution you'd like**

It can be one of 

1. Hit a key, say F5, to add a python import statement of the tag under cursor (say at the top of the file, configurable option)
2. Automatically add the import statement upon autocompletion validation when writing

**Describe alternatives you've considered**

I use a vim plugin at https://github.com/mgedmin/python-imports.vim but it does not work for this `QAbstractItemModel` saying `Tag not found`.

**Additional context**

I'm confused because apparently the `.pyi` files are not indexed with ctags, so I don't know how SpaceVim can find the definition in the `dist-packages/PyQt5/QtCore.pyi` file and propose it with the autocompletion when writing the import statement.

I don't know either how SpaceVim can find the definition even after having written the import statement.

**Comment by wsdjeg** [comment]
@Djedouas I do not know how to implement this feature, but as I know, the lsp server of python support this fetaure.
