### ISSUE TITLE
 emmet vim does not work on files with extension .JSX

### ISSUE THREAD

**Issue by CMOISDEAD** [wsdjeg/SpaceVim#4247]
Emmet only works with HTML files but not with React files (.JSX) I can't find a way to fix it in space vim.
I configured the leader key, and it works perfect... but only in HTML

I am a bit new to vim. 
Thank you <3

**Comment by wsdjeg** [comment]
`mattn/emmet-vim` is included in `lang#html` layer, and the default script is:

```
function! SpaceVim#layers#lang#html#config() abort
  let g:user_emmet_leader_key = s:user_emmet_leader_key
  augroup spacevim_lang_html
    autocmd!
    autocmd FileType html,css,scss,sass,less,javascript,jsp,vue,eex,php call s:install_emmet()
    autocmd Filetype html setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
  augroup END
endfunction
```

That means it only works for: html,css,scss,sass,less,javascript,jsp,vue,eex,php

two question:

1. which layer should we move emmet to? `autocomplete` layer?
2. add a layer option to add other filetypes

**Comment by Syakhisk** [comment]
I think moving emmet to `autocomplete` layers seems to be the most suitable since it's basically an autocomplete tools. Probably give another `option` item to the user whether to also include emmet in the completion tools.
