### ISSUE TITLE
colorscheme solarized display error

### ISSUE THREAD

**Issue by fcying** [wsdjeg/SpaceVim#425]
default colorscheme display right
![image](https://cloud.githubusercontent.com/assets/106934/24909243/aff2f5a6-1ef5-11e7-91d5-5373b6ee18b3.png)

solarized display error
![image](https://cloud.githubusercontent.com/assets/106934/24909261/c5ada634-1ef5-11e7-94ab-40e5e2cf2d6c.png)

os: ubuntu 16.04 + nvim

**Comment by wsdjeg** [comment]
solarized do not support true colors. you should use Neosolarized

**Comment by fcying** [comment]
@wsdjeg 

Neosolarized display error too.
![image](https://cloud.githubusercontent.com/assets/106934/24911707/813a13f8-1efe-11e7-9f12-d8e6f8f003b7.png)
![image](https://cloud.githubusercontent.com/assets/106934/24911719/8a7c8554-1efe-11e7-8e43-f25c96800725.png)

Official renderings:
![image](https://cloud.githubusercontent.com/assets/106934/24911772/b35b7ce6-1efe-11e7-9ab0-0556683a4fd7.png)

**Comment by wsdjeg** [comment]
your terminal do not support true color, and the default colorscheme now you see is just 256 instead of true color.

**Comment by fcying** [comment]
I'm useing nvim in tmux 2.1, I will upgrade to tmux 2.3 for support true color , tks~
