### ISSUE TITLE
Page links in the docs

### ISSUE THREAD

**Issue by 0xIsho** [wsdjeg/SpaceVim#4254]
Quick question, how do you link other pages in the documentation?

My last [commit](https://github.com/SpaceVim/SpaceVim/commit/c5e691c322c2c848afa98bef19f546408ce93cd0) was broken (sorry about that). in the `unite` layer's page, the link to `denite` isn't working!

`unite` isn't maintained anymore, and in the repository they advice to use `denite`.
I linked `denite` in `unite`'s docs page (i used `./denite` as the link, since denite's page is in the same directory), but the link is broken (which is really confusing, since the page is in the same directory, it should work!), so how do i link pages in the documentation?

**Comment by wsdjeg** [comment]
in page spacevim.org/xxxxx/ if you want to link to spacevim.org/ffff/ you can use (../ffff)

**Comment by 0xIsho** [comment]
I opened a PR that should solve the issue.
