### ISSUE TITLE
ubuntu 20.04 with latest spacevim 

### ISSUE THREAD

**Issue by freephys** [wsdjeg/SpaceVim#4258]
## Expected behavior, english is required
When run ipython from VimShell, expect to see both ipython input and output.
This affects the REPL as well

## The reproduce ways from Vim starting (Required!)
 the python is in a virtual env  from anaconda3. 
activate the venv. 
VimShell, run ipython
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
![Capture-spacevim](https://user-images.githubusercontent.com/128408/117393914-c0feb480-aeba-11eb-8da7-cd769098bc97.JPG)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
please use shell layer instead.
