### ISSUE TITLE
字体下载很慢

### ISSUE THREAD

**Issue by ifnk** [wsdjeg/SpaceVim#4267]
根据官网 的 第一步  curl -sLf https://spacevim.org/cn/install.sh | bash

[➭] 正在更新 SpaceVim...
已经是最新的。
[✔] SpaceVim 更新已完成
[✔] 已为 vim 安装了 SpaceVim
[✔] 已为 neovim 安装了 SpaceVim
[✔] 已下载 DejaVu Sans Mono Bold Oblique for Powerline.ttf
[✔] 已下载 DejaVu Sans Mono Bold for Powerline.ttf
[✔] 已下载 DejaVu Sans Mono Oblique for Powerline.ttf
[✔] 已下载 DejaVu Sans Mono for Powerline.ttf
[✔] 已下载 DroidSansMonoForPowerlinePlusNerdFileTypesMono.otf
[✔] 已下载 Ubuntu Mono derivative Powerline Nerd Font Complete.ttf
[➭] 正在下载 WEBDINGS.TTF
[✔] 已下载 WEBDINGS.TTF
[✔] 已下载 WINGDNG2.ttf
[✔] 已下载 WINGDNG3.ttf
[➭] 正在下载 devicons.ttf

## Debug info

就一直卡走下载字体上面 了，已经卡了一个小时了…… 

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
Nothing can be done now.
