### ISSUE TITLE
choose python virtual env

### ISSUE THREAD

**Issue by freephys** [wsdjeg/SpaceVim#4269]
**Is your feature request related to a problem? Please describe.**
vs code can select python interpreter. But do not know if spacevim can do it or not.
The original issues comes from that pudb was installed in an anaconda virtual env. but vim can not load the packages even launched after activating inside venv. 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Error detected while processing /home/lsx/.cache/vimfiles/repos/github.com/mvanderkamp/vim-pudb-and-jam/plugin/pudb.vim:
line   39:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lsx/.cache/vimfiles/repos/github.com/mvanderkamp/vim-pudb-and-jam/pythonx/pudb_and_jam.py", line 7, in <module>
    from pudb.settings import load_breakpoints, save_breakpoints
ModuleNotFoundError: No module named 'pudb'

**Comment by freephys** [comment]
found issues that vim can not load packages installed inside anaconda venv

**Comment by wsdjeg** [comment]
if you are using neovim, it is based on the default python host command.

**Comment by wsdjeg** [comment]
moved to google mail list.
