### ISSUE TITLE
Website documention issue, `SPC w f` is create new tab

### ISSUE THREAD

**Issue by JonasGao** [wsdjeg/SpaceVim#4270]
Document expected:
![image](https://user-images.githubusercontent.com/4549584/119081309-4e4f1680-ba2e-11eb-902a-81a42c251dfc.png)

Actual:
![image](https://user-images.githubusercontent.com/4549584/119081362-6c1c7b80-ba2e-11eb-81ad-29218e1ae967.png)

In fact, I don't know if this is a ISSUE. I don't know if I should mention PR directly or what to do. I think it’s better to mention an issue first.
(Translated by Google)

**Comment by wsdjeg** [comment]
Please update SpaceVim, this key binding is changed.
