### ISSUE TITLE
List of supported fonts under terminal

### ISSUE THREAD

**Issue by shaonianche** [wsdjeg/SpaceVim#4279]
Is there a list of commonly used fonts supported? Under Terminal, this gives people a better choice of how to set their terminal fonts, in addition to the default font (SourceCodePro Nerd Font Mono);

If not, I can help test and organize

**Comment by wsdjeg** [comment]
moved to https://groups.google.com/d/msgid/spacevim/ME3P282MB18427AE4629103941E1E4E20D4209%40ME3P282MB1842.AUSP282.PROD.OUTLOOK.COM

**Comment by wsdjeg** [comment]
All fonts should be able to supported in vim or terminal, if you are using terminal, nothing can be done in vim to configura the font.
