### ISSUE TITLE
Consider dynamic welcome page

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#429]
## Expected behavior
Make SpaceVim have a dynamic welcome page. A good example: metasploit console
It will be more lovely. 

Here's the demo: https://asciinema.org/a/2x7hin43z0ffku3entsm0hdrt

**Comment by wsdjeg** [comment]
@Gabirel please read `:h *g:startify_custom_header`. you can change it to anything.

but I think SpaceVim should has it's own list of banners.

**Comment by wsdjeg** [comment]
@Gabirel now I have implement this feature, but only one page is in the page list, PR welcome.

**Comment by wsdjeg** [comment]
`call SpaceVim#layers#load('core#banner')` will load the banners.

**Comment by wsdjeg** [comment]
![2017-04-12-22 45 20](https://cloud.githubusercontent.com/assets/13142418/24964024/b8a54f0e-1fd2-11e7-8372-25806b7a2721.png)
