### ISSUE TITLE
vim-gitgutter and splitjoin.vim plugins can't be updated

### ISSUE THREAD

**Issue by typeoneerror** [wsdjeg/SpaceVim#4292]
![Screen Shot 2021-06-22 at 10 58 58](https://user-images.githubusercontent.com/218700/122976097-dd5e8f80-d348-11eb-8264-3680c8e2384d.png)

When I use the method described in the docs to `gf` and update the repository, neither of these two seems to be valid:

```
fatal: not a git repository (or any of the parent directories): .git
```

There is a .git folder in the directory.

**Comment by wsdjeg** [comment]
you can reinstall these plugin, read `h :SPReinstall`.
