### ISSUE TITLE
xcodebuild delaying SpaceVim start

### ISSUE THREAD

**Issue by kakulukia** [wsdjeg/SpaceVim#4294]
Hi!

Id like to get rid of this bug on my system where consistently after every reboot (and also some unknown time after not using vim) xcodebuild is rebuilding(?) SpaceVim or at least delaying its startup by quite some time.
Running SaceVim after that will start it instantly as usual.

The only clue i found, was a hint to `sudo xcodebuild -license accept` which i tried, but that didnt change a thing.

This is not only tied to SpaceVim and also happens for other tools from time to time, but so far SpaceVim was the only tool that i could reproduce it with reliably.

I dont see errors, warnings or other stuff. The only thing popping up is xcodebuild in iTerms tab title which is representing the currently running app. I also am able to reproduce that with the osx default Terminal and bash vs. my default ZSH shell.

Has anyone stumbled across this weird behaviour or might have another hint for me as to how i could get rid of it?

xcodebuild -version
Xcode 12.4
Build version 12D4e

OSX: 10.15.7 (19H1030)

Its probably not related to SpaceVim and more of a weird xcode setting .. anyhow i figured here might be someone who could help, because other users might have had the same issue.

Best regards
Andy

**Comment by wsdjeg** [comment]
I do not think it is a bug of SpaceVim, there is no `xcodebuild` command in SpaceVim.

**Comment by kakulukia** [comment]
Yes, i know and said so in the previous post. But maybe someone experienced the same bug while using SpaceVim on OSX.

Anyone?

**Comment by wsdjeg** [comment]
If it is not reproduceable, I can not fix it.

**Comment by cice** [comment]
> Yes, i know and said so in the previous post. But maybe someone experienced the same bug while using SpaceVim on OSX.
> 
> Anyone?

i have the same issue. something, somewhere calls xcodebuild and delays the start for sometimes 10-20 seconds.

**Comment by kakulukia** [comment]
Thx! :) 

At least for me it happens only once per boot, but if someone knows how to trace the actual problem im more than happy to reboot a few times to test stuff.

Is it the same for you, @cice ?
