### ISSUE TITLE
E553: No more items when there's exactly one result for gtags

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#4296]
When the result list has exactly one item, ``cnext`` is used to jump to it in ``s:ExecLoad()`` inside ``autoload/gtags.vim``.  This cause ``E553: No more items`` and it doesn't jump to the position.

**Comment by wsdjeg** [comment]
@thawk Hi, thanks, and sorry for later replay. I will test it.

**Comment by wsdjeg** [comment]
I have added:

```
  " If there is only one item, jump to the position.
  if len(getqflist()) ==# 1
    cnext
  endif
```
