### ISSUE TITLE
Expanding markdown headings

### ISSUE THREAD

**Issue by Marin-Kitagawa** [wsdjeg/SpaceVim#4298]
This is a question. I have set `vimcompatible` mode to true and yet I can't expand the headings collapsed in a `markdown` file using `SPC`. Is there a way to expand the headings (i.e. in-built) in SpaceVim? Like with a single keystroke?

Specifically, I want it for using it along with `f`.

**Comment by wsdjeg** [comment]
@ruby-zen there is not such key binding, and I do not know what do you mean by `Expanding markdown headings`.
