### ISSUE TITLE
Theme does not load when launching vim in tmux

### ISSUE THREAD

**Issue by fedragon** [wsdjeg/SpaceVim#43]
Hi thanks for creating this bundle!
I have a "cosmetic" issue: I'm running SpaceVim in `vim` and the theme does not load if I'm launching it from `tmux`; if I launch it outside of `tmux`, it loads properly. I regularly use `vim` in `tmux` and theme loads properly. Do you have any clue why this could happen?

Versions:
vim 8.0
tmux 2.3
spacevim just cloned :)

**Comment by wsdjeg** [comment]
sorry, I do not use tmux. this should not be issue of colorscheme. maybe config of tmux or your terminal.
Will search for some info about this issue.

**Comment by wsdjeg** [comment]
I just see too many answer about this issue.
https://stackoverflow.com/questions/10158508/lose-vim-colorscheme-in-tmux-mode

https://askubuntu.com/questions/125526/vim-in-tmux-display-wrong-colors

https://askubuntu.com/questions/739620/vim-theme-showing-up-strange-in-tmux

hope this is useful for you.

**Comment by fedragon** [comment]
Hi @wsdjeg thanks for looking into it. 
As I mentioned, I use tmux + vim regularly so I am already aware of how to deal with them, with a vanilla vim installation, but this doesn't seem to apply to SpaceVim. I'll see if I can find the reason.

**Comment by wsdjeg** [comment]
@fedragon I can fix it , will send pr tonight.

**Comment by fedragon** [comment]
oh nice 👍

**Comment by wsdjeg** [comment]
@fedragon I think it is issue about true colors, you can disable true color of SpaceVim by add `let g:spacevim_enable_guicolors = 0` to `~/.local.vim`.

**Comment by wsdjeg** [comment]
BTW, as I know, `tmux +2` will support true colors.

**Comment by gzxultra** [comment]
Hi all,
I got the same problem when using `tmux` & `space vim` and I solved this finally.
This problem is caused by `tmux` rather than `space vim` configuration, we need to force `tmux` using 256 colors.

step1.
Add the followings to your .zshrc/.bashrc files.
```shell
alias tmux='TERM=screen-256color tmux -2'
alias tmuxinator='TERM=screen-256color tmuxinator'
alias tmux='TERM=screen-256color tmux'
```

step2.
Add this to your `~/.local.vim`.
```shell
let g:spacevim_enable_guicolors = 0
```

Hope this helps.
