### ISSUE TITLE
[Rust layer] rustfmt_cmd option does nothing :(

### ISSUE THREAD

**Issue by truchi** [wsdjeg/SpaceVim#4307]
Hello,

When writing Rust, one is very annoyed by the fact that if you want to get the cool features of the auto-formatter `rustfmt` you either have to:
1. set the nightly toolchain as the default toolchain (some/most people don't want that)
2. run `cargo +nightly fmt`

Rust layer has a `rustfmt_cmd` option: I am pretty confident to say it does nothing. Searched the repo for `rustfmt` and tried `touch`ing a file.

Could someone with vim foos fix that please?
<3

**Comment by wsdjeg** [comment]
This is bug of `lang#rust` layer, we use `neoformat` as default format plugin, bug `rustfmt_cmd` is not for this plugin. I will fix it later.
