### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by mekanix** [wsdjeg/SpaceVim#4308]
I understand that support for something like this is not easy and should not be take lightly, but as [Svelte](https://svelte.dev) is gaining more and more support in vim through plugins/snippets it would  be great to have support for it. There are few files already shipped with SpaceVim:
```
find . -iname '*svelte*'
./bundle/neoformat/autoload/neoformat/formatters/svelte.vim
./bundle/vim-snippets/UltiSnips/svelte.snippets
./bundle/vim-snippets/snippets/svelte.snippets
```
There are also plugins like [vim-svelte](https://github.com/evanleck/vim-svelte) (with the list of alternatives at the bottom of the README).

If anyone would help me, I'd like to write the support for this "language". Would layer be proper way to implement it? Any tips or guidance you can provide is appreciated.

**Comment by wsdjeg** [comment]
PR is welcome.

**Comment by mekanix** [comment]
Should it be layer?

**Comment by wsdjeg** [comment]
yeah, it should be `lang#svelte` layer.

**Comment by mekanix** [comment]
I have first version somewhat working. It's all recognized and indentation/highlighting is working, but I have this error at start:
```
Error detected while processing /usr/home/meka/.cache/vimfiles/.cache/init.vim/.dein/ftdetect/ftdetect.vim:
line   73:
E117: Unknown function: polyglot#init#init
```
Of course, commenting that line makes it go away, but I don't understand where this file is generated from nor why is `polyglot#init#init` always called. Can you help, please?

The repo is https://github.com/mekanix/SpaceVim/tree/feature/svelte

**Comment by mekanix** [comment]
I've been running this layer for months now and besides that E117 error everything works fine. I was wondering can we define dummy `polyglot#init#init` function if one is not already defined? Would that be acceptable?

**Comment by MegaKeegMan** [comment]
The commit mentioned above does not seem to be relevant to this issue, and I am not sure that this issue should be closed. Shouldn't the svelte layer be available? Is this something that will be completed?
