### ISSUE TITLE
add toggle auto parens mode `SPC t p`

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#4312]

**Comment by oeyoews** [comment]
> _没有提供说明。_

now , if i enable this paste-mode use `SPC t p`, the key `jk`(quit insert mode)  is disable ,  unless shut down this paste-mode use `SPC t p` angin

**Comment by wsdjeg** [comment]
`SPC t p` is used as toggle-paste mode, so we need to use another key binding.
