### ISSUE TITLE
spacevim cannot install defx

### ISSUE THREAD

**Issue by idealLight** [wsdjeg/SpaceVim#4315]
i'm trying to switch vimfiler to defx, but got msg "defx require +python3"
**Environment Information**
OS:WIN10
VIM: 8.2
NEOVIM : none
SPACEVIM: 1.8
PYTHON: 3.8.1
i try install defx as [defx](https://github.com/Shougo/defx.nvim/blob/master/README.md) suggest, but won't work.
![py3sup](https://user-images.githubusercontent.com/86812486/124384491-0ea16d00-dd04-11eb-927d-6c1c7e9b7877.png)
 denite plug also report this error

any help appreciated.

**Comment by idealLight** [comment]
I find it is actually py3 support issue on windows.
'python3' works in cmd window, but echo has('python3') return 0.  has('python') return 0.
I try [py support step](https://github.com/Gabirel/Hack-SpaceVim/blob/master/en_US/FAQ.adoc#without-python-support) but do not work.

**Comment by wsdjeg** [comment]
switch to neovim, then it will be easier to add py3 support.

**Comment by idealLight** [comment]
> switch to neovim, then it will be easier to add py3 support.

indead, it is a way. 
for neovim, it need installing pynvim and config python3_host_prog
