### ISSUE TITLE
After using the floating window, the StatusLine cannot be changed according to the current mode

### ISSUE THREAD

**Issue by starunity** [wsdjeg/SpaceVim#4317]
Add voldikss/vim-translator translation plugin in SpaceVim.d/init.toml
```
[[custom_plugins]]
    repo = "voldikss/vim-translator"
    merged = false
```
Choose a word to translate
![image](https://user-images.githubusercontent.com/35394552/124345612-9a37d280-dc0c-11eb-844e-34a70c831ee7.png)

Display translation in a window
`:TranslateW`
![image](https://user-images.githubusercontent.com/35394552/124345631-be93af00-dc0c-11eb-9c76-0d028b297648.png)

Move the cursor and the floating window will automatically close
Then StatusLine will look like this
![image](https://user-images.githubusercontent.com/35394552/124345782-77f28480-dc0d-11eb-96c7-0785e0f87157.png)

Then the StatusLine cannot be changed according to the current mode
![image](https://user-images.githubusercontent.com/35394552/124345833-d91a5800-dc0d-11eb-9977-2e7933c7e552.png)

If you use `:w` to save the file, StatusLine becomes the correct state
![image](https://user-images.githubusercontent.com/35394552/124345865-0ebf4100-dc0e-11eb-967e-1e8764e999b7.png)

Finally, the coc.nvim prompt window has the same problem

Translate by Google

Terminal: st 0.8.4
NeoVim: NVIM v0.4
SpaceVim: 1.8.0-dev

**Comment by wsdjeg** [comment]
@wsdjeg I think it is a bug of translate plugin, SpaceVim's notify api also use floating windows, but the statusline works well. and I will check it.

**Comment by wsdjeg** [comment]
closed, this has been fixed.
