### ISSUE TITLE
Spacevim run showing output multiple times

### ISSUE THREAD

**Issue by vuvgaG** [wsdjeg/SpaceVim#4320]
![image](https://user-images.githubusercontent.com/75189112/124379703-77f79080-dcb0-11eb-8c04-1454097e9ace.png)

When running a simple script its outputting the results multiple times. This happens in multiples languages. Happy to do the pr if its easy just let me know the code parts.

**Comment by wsdjeg** [comment]
@vuvgaG reproduce step and debug info is needed. press `SPC h I`
