### ISSUE TITLE
how to copy/paste files in vimfiler 

### ISSUE THREAD

**Issue by johnsonkee** [wsdjeg/SpaceVim#4323]
Hello, I am using SpaceVim as my vim IDE. Its file-tree plugin is vimfiler, I can use "y Y" to copy a file, but I don't know to paste the copied file. Could you tell me how to do it? Thank you!

**Comment by johnsonkee** [comment]
I touch "P"， but it does not work.

**Comment by wsdjeg** [comment]
@johnsonkee make sure you have xclip installed, and have `xclip-pastefile` and `xclip-copyfile` in your PATH.

**Comment by johnsonkee** [comment]
could you tell me how to&nbsp;
have&nbsp;xclip-pastefile&nbsp;and&nbsp;xclip-copyfile&nbsp;in my PATH.

？

---Original---
From: "Wang ***@***.***&gt;
Date: Sun, Aug 8, 2021 14:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SpaceVim/SpaceVim] how to copy/paste files in vimfiler  (#4323)




 
@johnsonkee make sure you have xclip installed, and have xclip-pastefile and xclip-copyfile in your PATH.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by johnsonkee** [comment]
could you tell me how to do "and have xclip-pastefile and xclip-copyfile in your PATH"?
