### ISSUE TITLE
Install the portable without admin rights

### ISSUE THREAD

**Issue by duytrung** [wsdjeg/SpaceVim#4326]
Hello,

I'd like to install in a portable folder without admin rights like the following:
1. open cmd 
2. set paths
3. use vim with spacevim plugin

How can I manually install without having to run the install.cmd with admin right?

Thanks for your feedback

**Comment by wsdjeg** [comment]
@duytrung This ia based on your system, you can install spacevim without `install.cmd` command. just clone this repo to the path you want. than run `vim -u ~/path/to/spacevim/vimrc` .
