### ISSUE TITLE
Todo manager not working properly

### ISSUE THREAD

**Issue by joelazar** [wsdjeg/SpaceVim#4329]
It looks like the todo manager no longer find the todo comments:

![image](https://user-images.githubusercontent.com/16268238/124797807-fc693e00-df52-11eb-9674-499ebb516d11.png)

I'm using neovim 0.5 and latest spacevim (3f3a4912dfdf).

**Comment by wsdjeg** [comment]
please upload the runtime log. use key binding `SPC h L`

**Comment by kayleg** [comment]
Same issue here, but I think mine is related to `ripgrep` 13 as no searches work with it.
(using mac and neovim)

Todo logs cmd: 

```
['rg', '--hidden', '--no-heading', '--color=never', '--with-filename', '--line-number', '--column', '-g', '!.git', '-e', 'TODO\b|FIXME\b|XXX\b|QUESTION\b']
```

I think the command needs to tell `ripgrep` not to expect socket input:

https://github.com/BurntSushi/ripgrep/issues/1892

**Comment by joelazar** [comment]
> please upload the runtime log. use key binding `SPC h L`

here you go: https://pastebin.com/P0Wkx4Fp

**Comment by wsdjeg** [comment]
This ia a bug of `rg` I think, it includes an incompatible patch. I cannot fix it.
