### ISSUE TITLE
Find on mac

### ISSUE THREAD

**Issue by vuvgaG** [wsdjeg/SpaceVim#4331]
When trying to find (leader f /). I'm getting no results

I'm using the latest macOS 

running the command 

```
find -not --iwholename "*.git" Scanner.java
```

Produces nothing. Is this a compatibility issue. Should Spacevim handle macOS out of the box. Happy to PR.

**Comment by wsdjeg** [comment]
@vuvgaG I do not use macos, what should be the default command of find in macos?
