### ISSUE TITLE
gtags command fail for search reference

### ISSUE THREAD

**Issue by idealLight** [wsdjeg/SpaceVim#4333]
I have installed the global tool. <SPC>_mgc work as it create tag file in .cache\SpaceVim\tags\D_projectdir. But when I want to find ref(<SPC>_mgr), error msg "Error command failed. command line: global --result=ctags-x -qf "filepath"". 

**Environment Information**
OS:WIN10
VIM: 8.2
NEOVIM : 0.4.3
SPACEVIM: 1.8
PYTHON: 3.8.1

I add some debug info in gtags.vim:
`  if v:shell_error != 0

    if v:shell_error == 2

      call s:Error('invalid arguments. (gtags.vim requires GLOBAL 5.7 or later)')

    elseif v:shell_error == 3

      call s:Error('GTAGS not found.')

    else

      call s:Error('global command failed. error: ' . v:shell_error)

    endif

    return

  endif`
I get shell_error=1. I do not know what it excatly means and how to fix it.

pls：I add some info in ExecGlobal function, i see the GTAGSROOT and GTAGSDBPATH are correct,  l:restore_gtagsroot = 1, l:restore_gtagsdbpath = 1.

**Comment by idealLight** [comment]
it seem someone else also find the problem, he comment below the [blog](https://zhougy0717.github.io/2019/03/24/SpaceVim_gtags_and_cscope/). but no solution

**Comment by wsdjeg** [comment]
@idealLight there is no reproduce step, you can create a simple github repo, I will test it, gtags layer now works well for me.
