### ISSUE TITLE
cscope fail for search reference

### ISSUE THREAD

**Issue by idealLight** [wsdjeg/SpaceVim#4334]
**Environment Information**
OS:WIN10
VIM: 8.2
NEOVIM : 0.4.3
SPACEVIM: 1.8
PYTHON: 3.8.1
:[SPC]mgcr , message show "Vim(let):E716 Key not present in Directory:D_projectdir"

It seems no tags tools can be used in such env, hope author can fix it ASAP. @wsdjeg

**Comment by wsdjeg** [comment]
What is `SPCmgcr`? there is no such key binding. what is the reuslt of `SPC m c l` and `SPC m c i`?
