### ISSUE TITLE
status line separator arrows do not appear when launched from within tmux

### ISSUE THREAD

**Issue by rv-nath** [wsdjeg/SpaceVim#4339]
I am using Garuda Linux with tmux version 3.2a.  Recently installed neovim and spacevim.  Everything is smooth, except for the arrows in the status line.  When I run nvim in the terminal (without tmux), the status line separators with arrows look fine.  The problem occurs only when I run nvim inside of tmux session..

I have configured custom files for spacevim as below.

1. ~/.SpaceVim.d/status-line.toml
```
vikatakavi@vikatakavi-homepc ~> cat ~/.SpaceVim.d/status-line.toml
[[layers]]
name = "core#statusline"

[options]
# options for statusline
# Set the statusline separators of statusline, default is "arrow"
statusline_separator = "arrow"
# Set the statusline separators of inactive statusline
statusline_iseparator = "bar"

```

2. ~/.SpaceVim.d/tmux.toml
```
vikatakavi@vikatakavi-homepc ~> cat ~/.SpaceVim.d/tmux.toml
[[layers]]
name = "tmux"


[[layers]]
name = "tmux"
tmux_navigator_modifier = "alt"
```

# nvim without using tmux
![nvim-without-tmux](https://user-images.githubusercontent.com/87602915/126064834-ef86db40-0fc2-42b9-871c-cb71b6b1a690.png)

# nvim within tmux
![nvim-with-tmux](https://user-images.githubusercontent.com/87602915/126064857-cb5cda0a-dc29-4f9e-a2a1-f969f928b7bd.png)

Can someone help me with fixing this issue.

**Comment by wsdjeg** [comment]
I think this is same issue: https://github.com/gpakosz/.tmux/issues/171
