### ISSUE TITLE
Locale error

### ISSUE THREAD

**Issue by Rawa** [wsdjeg/SpaceVim#434]
## Expected behavior, english is recommend
Normal start of neovim with SpaceVim

## Environment Information
- OS: Arch Linux
- vim version:
- neovim version: 0.1.7

## The reproduce ways from Vim starting (Required!)
Install neovim och Arch Linux, install Spacevim.

```
rawa@rawa ➜  ~ nvim
Error detected while processing /home/rawa/.SpaceVim/config/init.vim:
line   32:
E197: Cannot set language to "en_US.UTF-8"
Press ENTER or type command to continue
```

As in Sun OS the locale has different formatting.
```
rawa@rawa ➜  ~ locale
LANG=en_GB.UTF-8
LC_CTYPE=sv_SE.UTF-8
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE=sv_SE.UTF-8
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES=en_GB.UTF-8
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```
Changing the setting from lan en_GB.UTF-8 from en_US.utf8 fixes my issue

Maybe this is a too big requirement for SpaceVim?

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
I think it is better to use `en_US.utf8`. Use English for anything in vim will make it easy for paser the message.
