### ISSUE TITLE
A problem with gd for typescript

### ISSUE THREAD

**Issue by KhromovE** [wsdjeg/SpaceVim#4342]
I use lsp for typescript and when I try to do `gd` I get an error

```
Error detected while processing function SpaceVim#mapping#gd[2]..<SNR>52_go_to_typescriptreact_def:
line    3:
E492: Not an editor command:       TSDef
```

What am I doing wrong?

**Comment by wsdjeg** [comment]
the lsp layer has not been enabled, because when lsp layer is enabled for typescript file, `gd` will run `SpaceVim#lsp#go_to_def()`. you need to enable lsp:

```
[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "javascript",
    "typescript"
  ]
```
```
