### ISSUE TITLE
Markdown preview is failed to build on MacAir(M1 apple silicon)

### ISSUE THREAD

**Issue by espseongsm** [wsdjeg/SpaceVim#4344]
<img width="471" alt="Screen Shot 2021-07-23 at 10 26 41 PM" src="https://user-images.githubusercontent.com/59265733/126790112-90368af5-2292-419c-84ba-52c7eea748ec.png">

Please help to build it correctly. I can't preview markdown files.

**Comment by wsdjeg** [comment]
you can go to `~/.cache/vimfiles/repos/github.com/neoclide/vim-node-rpc`, and run `npm install` or `yarn install`.
