### ISSUE TITLE
Make StatusLine move to the bottom of the screen

### ISSUE THREAD

**Issue by codeRSH** [wsdjeg/SpaceVim#4348]
I am using SpaceVim on Git Bash in Windows Terminal. 

Currently the StatusLine seems to be slightly above the bottom of screen. 

![image](https://user-images.githubusercontent.com/4953198/127770328-863f6ee6-21e4-4648-aac1-0acfc63c538e.png)

I am not able to find any option to move it to the bottom or change its position in general. Can you please help.

**Comment by wsdjeg** [comment]
There is no option for this feature. It based on your font size.

**Comment by codeRSH** [comment]
Even after increasing the font size the StatusLine remains slightly above the bottom of the screen. 

But now I realize the bottom portion of the screen is actually to write the ex mode commands. So, it can't be completely moved to the bottom. Thanks for the help. Closing the issue.

**Comment by wsdjeg** [comment]
You're welcome.
