### ISSUE TITLE
Can we skip font download when installed on a headless server without X server?

### ISSUE THREAD

**Issue by yusiwen** [wsdjeg/SpaceVim#4354]
I found that , when running install.sh, lots of fonts were downloaded, even though my server is headless without X server.
The situation became really awkward because of my poor connection bandwidth. It took me almost half an hour to finish the installation. Can we just skip the GUI-related preparations and configurations while running install.sh if no X server process is detected?

**Comment by wsdjeg** [comment]
we can add a new option `--no-fonts`

**Comment by yusiwen** [comment]
@wsdjeg Thanks
