### ISSUE TITLE
MarkdownPreview: 220_BrowserStart error

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#438]
## Expected behavior, english is recommend
No errors

## Environment Information
- OS: Arch Linux
- vim version: 8.0

## The reproduce ways from Vim starting (Required!)
1. vim test.md

2. `:MarkdownPreview`

3. You can see errors here:

![image](https://cloud.githubusercontent.com/assets/12933851/25060718/e7e3379e-21d6-11e7-9259-e3f9ed3a96b3.png)

This is different from #337 

## init.vim
```viml
let g:mkdp_path_to_chrome = '/usr/bin/google-chrome-stable'
let g:mkdp_auto_start = 1
```

**Comment by Gabirel** [comment]
Reference:
- https://github.com/iamcco/markdown-preview.vim/issues/37
- https://github.com/iamcco/markdown-preview.vim/issues/36
- https://github.com/iamcco/markdown-preview.vim/issues/1

@iamcco It still fails. I don't know why

**Comment by Gabirel** [comment]
I've looked into source code. I couldn't fix this issue although I know where the problem is.

For now, I have to abandon https://github.com/iamcco/markdown-preview.vim

Here's the alternative: https://github.com/SpaceVim/SpaceVim/issues/337#issuecomment-296842415

Please don't close this issue until solved

**Comment by wsdjeg** [comment]
@Gabirel markdown layer plugins have been changed, clossing.
