### ISSUE TITLE
Add lua implementation

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#4389]
I have compared the speed of vim script and lua, lua is faster. So I want to rewrite SpaceVim with Lua.

**NOTE:** All vim scripts will be retained to ensure support for older versions of Vim and NeoVim

### How to compare speed

with following vim script, and run:

- `:TestFunc Fibo 1000`
- `:TestFunc Fibo 10000000`
- `:TestFunc LuaFibo 1000`
- `:TestFunc LuaFibo 10000000`

```viml
function! Fibo(N) abort
    let t = a:N
    let b = 0
    while t > 0
        let t = t - 1
        let a = 1
        let b = 1
        let c = 73
        while c > 0
            let c = c - 1
            let tmp = a + b
            let a = b
            let b = tmp
        endwhile
    endwhile
    echo b
endfunction

function! LuaFibo(N) abort
lua << EOF
local a, b, r, c, t
t = vim.api.nvim_eval("str2nr(a:N)")
while t > 0 do
        t = t - 1
        a = 1
        b = 1
        c = 73
        while c > 0 do
                c = c - 1
                r = a + b
                a = b
                b = r
        end
end

print(string.format("%d", b))
EOF
endfunction
function! s:test(...) abort
        " for func in a:000
                let start = reltime()
                call call(a:1,[a:2])
                let sec = reltimefloat(reltime(start))
                echom printf('%s(%d): %.6g sec', a:1, a:2, sec)
        " endfor
endfunction

command! -nargs=+ TestFunc call s:test(<f-args>)
```

results:

```
Fibo(1000): 0.410364 sec
Fibo(10000000): 1470.280914 sec
LuaFibo(1000): 9.052000e-4 sec
LuaFibo(10000000): 1.235385 sec
```

### Use lua version plugin

make sure you are using nvim 0.9.0+.

### Process

**Core:**

- [x] spacevim logger #4398 

**APIs:**

- [x] basic:  #2861 
- [x] file: #4391
- [x] system: #4392
- [x] logger #4395 

**Built-in Plugins:**

The built-in plugins are created based on SpaceVim api, so we need to rewrite the api in lua first.

- [x] a.vim
- [x] projectmanager #4401 
- [x] key binding guide
- [x] code runner
- [x] flygrep

**Other apis:**

- [x] job
- [ ] `data#json` #4396 (simple version)
- [ ] `vim#compatible`
- [x] iconv #4397 
- [x] `data#toml`

**Comment by watzon** [comment]
@wrxck not sure if you're a big Vim or SpaceVim user, but you're the first person that came to mind when I saw Lua

**Comment by wsdjeg** [comment]
I have change the title to `Add lua implementation`, because we are going to add new lua implementation without removing the original VIML version.
