### ISSUE TITLE
New '-' when pressing backspace on osx Sierra

### ISSUE THREAD

**Issue by mnivoliez** [wsdjeg/SpaceVim#44]
When in insertion mode, upon using backspace, nothing is delete, instead I got '-'. The problem shows up only when using spacevim and not when using bare neovim.
#### Before backspace:
[https://gyazo.com/c1f130a26639af92d21a9fdf6ff60c87](url)
#### After backspace:
[https://gyazo.com/34c22565caf1bc8d03d1a1fef223be40](url)

I also got that error:
```
Error detected while processing function deoplete#mappings#smart_close_popup[1]..deoplete#smart_close_popup:
line    1:
E121: Undefined variable: g:deoplete#_context
```
I believe this message to not be directly related to the '-' issue though.

**Comment by wsdjeg** [comment]
Same as #41, `<BS>` has been mapped. neovom has no py3 support. so deoplete.nvim will not be loaded.
