### ISSUE TITLE
Fail to install Tasklist.vim and taglist.vim on macOS

### ISSUE THREAD

**Issue by houzzxiaofeng** [wsdjeg/SpaceVim#440]
## Expected behavior, english is recommend
When vim starts, it always says fail to install Tasklist.vim and taglist.vim

## Environment Information
- OS: macOS 10.11.6
- vim version: VIM - Vi IMproved 8.0 install through brew
- neovim version: NVIM 0.1.7

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.
no custom config

**Comment by wsdjeg** [comment]
![2017-04-15_1358x719](https://cloud.githubusercontent.com/assets/13142418/25060926/1f5b2808-21dc-11e7-939b-5bf4deff5147.png)
I can not reproduce, please update your spacevim.

**Comment by wsdjeg** [comment]
please update spacevim. this issue has been fixed.
