### ISSUE TITLE
Adding more text objects to SpaceVim

### ISSUE THREAD

**Issue by ssbanerje** [wsdjeg/SpaceVim#4405]
**Is your feature request related to a problem?**
Spacevim can be made to include some text objects as default plugins to help programmers. Here are some examples:
1. Add support for function argument text objects: https://github.com/xerus2000/argtextobj.vim
2. Add support for program words text objects (e.g., camel case, hex/binary/ocatal literals: https://github.com/chaoren/vim-wordmotion
3. Add support complex text objects: https://github.com/wellle/targets.vim

**Describe the solution you'd like**
I would imagine that text objects like the two plugins I have listed above could be added as a Layer in SpaceVim. Here is a tentative layer definition. 

```vim
function! SpaceVim#layers#motions#plugins() abort
  let plugins = []
  call add(plugins, ['xerus2000/argtextobj.vim', {'merged': 0}])
  call add(plugins, ['chaoren/vim-wordmotion', {'merged': 0}])
  call add(plugins, ['wellle/targets.vim', {'merged': 0}])
  return plugins
endfunction

function! SpaceVim#layers#motions#config() abort
  " Restore vim behavior
  nmap dw de
  nmap dW dE
  nmap cw ce
  nmap cW cE
endfunction
```

I would imagine that there might be other popular text objects that could also be integrated into such a layer.
This could be part of a layer that gets loaded by default, or part of an opt-in layer that integrates different text-objects and motions together.

**Describe alternatives you've considered**
I see some of the text objects are included in the `bundle/` folder and are included in by default. Maybe more text objects can be added there instead of as a separate layer.

**Comment by wsdjeg** [comment]
@ssbanerje thanks for you info. now we are using vim-textobj-user by default in `edit` layer.
