### ISSUE TITLE
While using VimSpace, I found a strange blank in the corner.(bottom corner and right side corner)

### ISSUE THREAD

**Issue by wangkeunoh** [wsdjeg/SpaceVim#4406]
Hello, I am wangkeun,  
VimSpace is interesting and I'm trying to get used to it.
I noticed something strange while using it. 
With vimspace, vi doesn't fill the screen and shows empty space. Is this a known bug?
thank you for reading this.

## Debug info
OS : Ubuntu 20.04.3 LTS
VimSapce : curl -sLf https://spacevim.org/install.sh | bash (1.8.0-dev)

## Screenshots
![image](https://user-images.githubusercontent.com/19212686/129808590-8d8f44de-6e03-4e1d-a1ee-e8a38a0a4805.png)

**Comment by wangkeunoh** [comment]
The red square is the strange blank space I was talking about.

**Comment by wsdjeg** [comment]
This is issue with vim, nothing can be done in spacevim, maybe you can have a try with neovim.
