### ISSUE TITLE
Cannot create .cache file

### ISSUE THREAD

**Issue by porteron** [wsdjeg/SpaceVim#4413]
Related to the recent issue of https://github.com/SpaceVim/SpaceVim/pull/4409.

After fresh install on macos seeing the following error:
```
➜  ~ vim
Error detected while processing function SpaceVim#custom#load:
line   16:
E482: Can't create file /Users/<user>/.cache/SpaceVim/conf/_Users_<user>__SpaceVim_d_init_toml.json
Press ENTER or type command to continue
```

Problem here is that the `conf` directory does not exists. 

I was able to bypass this error by manually creating the `.cache/SpaceVim/conf` directory.

**Comment by craldaz** [comment]
Do you also see that it breaks the themes?

**Comment by wsdjeg** [comment]
This issue has been fixed. thanks for your feedback.

**Comment by ilaipi** [comment]
cache file always write error  and load failed.

**Comment by wsdjeg** [comment]
@ilaipi use new issue with template and reproduce step.
