### ISSUE TITLE
文件树图标异常

### ISSUE THREAD

**Issue by iChard** [wsdjeg/SpaceVim#4419]
## Expected behavior, english is required
the defx-icons invalid
###  1. enable_vimfiler_filetypeicon = true
all the file icon in the filetree is white，and the .SpaceVim/bundle/defx-icons/plugin/defx_icons.vim is invalid
![image](https://user-images.githubusercontent.com/12317840/130346488-34f8446c-61e3-402b-adfe-02725dff9358.png)

### 2. enable_vimfiler_gitstatus = true
the defx icon is missing while enable_vimfiler_gitstatus = true and enable_vimfiler_filetypeicon=false

![image](https://user-images.githubusercontent.com/12317840/130346454-55bfa28d-066e-4ecf-94ae-873efd9a9a38.png)

**Comment by wsdjeg** [comment]
Thanks for your feedback, but you should use english in github.

**Comment by iChard** [comment]
@wsdjeg  updated，thks
