### ISSUE TITLE
Vim(let):E117: Unknown function: vimproc#ptyopen

### ISSUE THREAD

**Issue by Pferdchen** [wsdjeg/SpaceVim#4426]
OS: Debian 11
vim-nox version 8.2

Add 2 layers in init.toml:
python
debug

Open a python file.
I have no problem with <kbd>SPC l r</kbd>to execute the file,
but problem with Debug.
Firstly <kbd>SPC d b</kbd>, toggle line breakpoint, and
then <kbd>SPC d l</kbd>, launch the debugger

It shows "Vim(let):E117: Unknown function: vimproc#ptyopen"

**Comment by Pferdchen** [comment]
OK, I have found the solution.

The solution for error

```
Vim(let):E117: Unknown function: vimproc#ptyopen
````

is the same as for error

```
[vimproc] vimproc's DLL: "~/.SpaceVim/bundle/vimproc.vim/lib/vimproc_linux64.so" is not found.
````

shown in [quick start quide](https://spacevim.org/quick-start-guide/). But the second error is not shown up at all on my vim startup.

What I wonder is, dein.vim is as a forked repo already in SpaceVim/bundle/, why does install.sh script at line 179 have

```
git clone https://github.com/Shougo/dein.vim.git $HOME/.cache/vimfiles/repos/github.com/Shougo/dein.vim
```

and clones the same repo again during the installation?

**Comment by wsdjeg** [comment]
You need to make the vimproc, in bundle/vimproc.vim dir.

the install script is not updated when dein is merged into bundle dir.
