### ISSUE TITLE
关于spacevim 0.3版本 更新之后的问题

### ISSUE THREAD

**Issue by Aaronluoxiao** [wsdjeg/SpaceVim#444]
我是在windows 上使用的SpaceVim,更新之后 写程序时，大括号{}无法自动缩进（具体见图），不知道具体原因，因为上一版本是正常的
![snipaste20170415_203439](https://cloud.githubusercontent.com/assets/12382026/25071920/7c0a3f9a-22cb-11e7-8063-0a119de6afca.png)

**Comment by wsdjeg** [comment]
fixed.
