### ISSUE TITLE
Can you adapt the Atom One Dark theme to SpaceVim?

### ISSUE THREAD

**Issue by Doomwhite** [wsdjeg/SpaceVim#4448]
**Is your feature request related to a problem? Please describe.**
The Atom One Dark isn't 100% supported by SpaceVim.

**Describe the solution you'd like**
Adapt the Atom One Dark theme to work accordingly.

**Additional Context**
This is how it looks like:
![transferir](https://user-images.githubusercontent.com/40442835/131348332-cc39979d-0a38-4a59-8bb5-95924e229d82.png)

**Comment by wsdjeg** [comment]
@Doomwhite what is the onedark colorscheme? we have `vim-one` in colorscheme, you can change the colorscheme to `one`.
