### ISSUE TITLE
some colorschema need to change cursor color

### ISSUE THREAD

**Issue by coci** [wsdjeg/SpaceVim#4453]
hi,
I used "one" schema layer with the 'light' option. so the cursor is white and the background is white too, is there any option to change the cursor color?

**Comment by wsdjeg** [comment]
![image](https://user-images.githubusercontent.com/13142418/133931212-81c81228-70ee-478a-ac28-d55024ffef43.png)


I can not reproduce it, I think it is issue with your terminal configuration.
