### ISSUE TITLE
Installer Script Fails -- Symlink

### ISSUE THREAD

**Issue by ssbanerje** [wsdjeg/SpaceVim#4466]
## Expected behavior, english is required

The installer script should always run. 

OR 

`git clone` on the repo should succeed.

## The reproduce ways from Vim starting (Required!)

Run the install script in a directory that is backed by a file system that does not support links (e.g., FAT). This seems to be the case on the Github actions MacOS runner (see https://github.com/ssbanerje/dotfiles/runs/3581503715?check_suite_focus=true#step:5:750). 

## Error
```
        /######                                     /##    /##/##             
       /##__  ##                                   | ##   | #|__/             
      | ##  \__/ /######  /######  /####### /######| ##   | ##/##/######/#### 
      |  ###### /##__  ##|____  ##/##_____//##__  #|  ## / ##| #| ##_  ##_  ##
       \____  #| ##  \ ## /######| ##     | ########\  ## ##/| #| ## \ ## \ ##
       /##  \ #| ##  | ##/##__  #| ##     | ##_____/ \  ###/ | #| ## | ## | ##
      |  ######| #######|  ######|  ######|  #######  \  #/  | #| ## | ## | ##
       \______/| ##____/ \_______/\_______/\_______/   \_/   |__|__/ |__/ |__/
               | ##                                                           
               | ##                                                           
               |__/                                                           

                      version : .8.0-dev      by : spacevim.org             

[➭] Trying to clone SpaceVim
Cloning into '/Users/runner/.SpaceVim'...
error: unable to create symlink doc/SpaceVim.cnx: File name too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

[✘] Failed to clone SpaceVim
Error detected while processing command line:
E: Unknown function: dein#install
remote/host: generated rplugin manifest: /Users/runner/.local/share/nvim/rplugin.vimError detected while processing command line:
```

## Potential Solution

Could the symlink be put in by the installer script or by the first execution of vim, if the underlying file system supports it.

**Comment by ssbanerje** [comment]
I have been able to get around this by running the following command before the installer script or git clone.

```sh
git config --global core.symlinks false
```

Is there a better way?

**Comment by yorch** [comment]
Same problem here, although it's not a new installation but an update (`:SPUpdate`)

**Comment by wsdjeg** [comment]
I can not fix it, maybe it is a bug of git? `doc/SpaceVim.cnx` is a link to `bundle/spacevim/doc/spacevim.txt`

**Comment by ssbanerje** [comment]
@wsdjeg I don't think its a bug. If the file system does not support symlinks, git errors out (which seems like the right thing to do). 

Does that symlink have to be in the repo. Maybe it can be created by the installer script or by Spacevim.

They can check if the link creation is possible (i.e., does `ln` fail). In case of failure, they can just copy the relevant file. Also add the symlink to the `.gitignore` so that `:SPUpdate` can go through without flagging a dirty directory.

This way the clone will not fail.

**Comment by hakamadare** [comment]
@ssbanerje in my case i'm on Apple APFS, which definitely supports symlinks; i have checked out other git repositories that contain symlinks.

@wsdjeg would you be willing to revert the commit that introduced the problem (39bf31c4b2ad1ebb8c343c8d2121f50b300fd161), copy the file instead of symlinking it, squash the commits, and then force-push?  otherwise i'm not sure how to proceed past this problem.

**Comment by ssbanerje** [comment]
I can confirm this as well. I can't do a `git pull` or a `:SPUpdate SpaceVim` on MacOS with a APFS file system. Then I guess this problem is not because of file system capabilities but something else.

**Comment by ssbanerje** [comment]
Found it!

On my Linux system, the symlink shows up as -

```
» ls -l
total 192
lrwxrwxrwx 1 subho subho   3333 Sep 15 17:38 SpaceVim.cnx -> '*SpaceVim.txt*'$'\n\n\n''    /######                 /##    /##/##'$'\n''   /##__  ##                                   | ##   | #|__/'$'\n''  | ##  \__//######  /######  /####### /######| ##   | ##/##/######/####'$'\n''  |  ###### /##__  ##|____  ##/##_____//##__  #|  ## / ##| #| ##_  ##_  ##'$'\n''   \____  #| ##  \ ## /######| ##     | ########\  ## ##/| #| ## \ ## \ ##'$'\n''   /## \ #| ##  | ##/##__  #| ##     | ##_____/ \  ###/ | #| ## | ## | ##'$'\n''  |  ######| #######|  ######|  ######|  #######  \  #/  | #| ## | ## | ##'$'\n''   \______/| ##____/ \_______/\_______/\_______/   \_/   |__|__/ |__/ |__/'$'\n''           | ##'$'\n''           | ##'$'\n''           |__/'$'\n''wsdjeg     *spacevim* *SpaceVim*'$'\n\n''=============================================================================='$'\n''CONTENTS                                                   *SpaceVim-contents*'$'\n''  1. 简介.......................................................|SpaceVim-intro|'$'\n''  2. 选项.....................................................|SpaceVim-options|'$'\n''      1. default_indent......................|SpaceVim-options-default_indent|'$'\n''      2. relativenumber......................|SpaceVim-options-relativenumber|'$'\n''  3. Configuration...........................................|SpaceVim-config|'$'\n\n''=============================================================================='$'\n''简介                                                            *SpaceVim-intro*'$'\n\n''SpaceVim 是一个社区驱动的模块化 Vim 配置，这一思想概念起源于 Spacemacs。'$'\n\n''=============================================================================='$'\n''选项                                                          *SpaceVim-options*'$'\n\n''SpaceVim 使用 `~/.SpaceVim.d/init.toml` 作为默认的全局配置文件。所有的选项'$'\n''都可以在该文件中进行设置，同时，`~/.SpaceVim.d/` 将被加入 Vim 的运行时（&rtp）内。因此，可以在该目录下创建私有的 Vim'$'\n''脚本文件。SpaceVim 也支持项目的本地配置，在项目的根目录下，`.SpaceVim.d/init.toml`'$'\n''即为默认的本地配置，`./SpaceVim./` 目录同样会被加入到 Vim 的运行时（&rtp）内。'$'\n\n''以下即为一个配置示例：'$'\n''>'$'\n''  [options]'$'\n''    enable-guicolors = true'$'\n''    max-column = 120'$'\n''<'$'\n\n''=============================================================================='$'\n''DEFAULT_INDENT                               *SpaceVim-options-default_indent*'$'\n\n''设置默认的对齐具体，默认的值为 2。'$'\n''>'$'\n''  default_indent = 2'$'\n''<'$'\n\n''=============================================================================='$'\n''RELATIVENUMBER                               *SpaceVim-options-relativenumber*'$'\n\n''启用/禁用相对行号，相对行号可以用于快速上下多行移动，默认已启用。'$'\n''>'$'\n''  relativenumber = true'$'\n''<'$'\n\n''=============================================================================='$'\n''CONFIGURATION                            *SpaceVim-config*'$'\n\n''                                                   *g:spacevim_default_indent*'$'\n''设置默认的对齐具体，默认的值为 2。'$'\n''>'$'\n''  let g:spacevim_default_indent = 2'$'\n''<'$'\n\n''                                                   *g:spacevim_relativenumber*'$'\n''启用/禁用相对行号，相对行号可以用于快速上下多行移动，默认已启用。'$'\n\n\n''vim:tw=78:ts=8:ft=help:norl:'$'\n'
-rw-rw-r-- 1 subho subho 153533 Sep 15 17:38 SpaceVim.txt
-rw-rw-r-- 1 subho subho  20980 Sep 14 18:48 tags
-rw-rw-r-- 1 subho subho  10426 May  3 11:31 tags-cn
```

Which is the entire content of the file in the link target. One can see it better in a screenshot:
![Screenshot](https://i.imgur.com/RIkVyfA.png)

Something has gone really really wrong here.

Maybe following @hakamadare's advice of squashing all commits from 39bf31c to HEAD+(fix) is the way to go. I would imagine the repo would be unsable in all the intermediate commits.

**Comment by wsdjeg** [comment]
but the master branch is protect branch which do not support force push.

**Comment by ssbanerje** [comment]
@wsdjeg I think as the owner/admin you should be able to force push into any branch. 
If not you can set it up temporarily for all users in Settings > Branches and then disable it later.

**Comment by Rom1deTroyes** [comment]
Note that if you force push on the master branch, there is chance that many users will be stuck when trying to update from the repository.
Reverting the change is a safer way, and may avoid many complex manipulations for beginners to average users... And save precious time from the issues and community that will follow :-$
(Thanx for all the works BTW, this project is very interesting when searching for a easy ready to use vim environment :-)

**Comment by hakamadare** [comment]
i'd prefer a revert as well, so that users don't have to `git reset --hard origin/master` before they will be able to get updates.  @wsdjeg do you know why that symlink looks strange?  what OS does your workstation use?

**Comment by wsdjeg** [comment]
Fixed, please test it again.

**Comment by hakamadare** [comment]
thank you @wsdjeg!  i confirmed the `git config core.symlinks false` config setting is no longer required, and successfully reset back to before the bug was originally introduced, and then reset back to `HEAD`.
