### ISSUE TITLE
flygrep can't seach chinese

### ISSUE THREAD

**Issue by wuxinyiwu** [wsdjeg/SpaceVim#4476]
## The reproduce ways from Vim starting (Required!)
SPC s b,when i seach whith chinese，there is no result ，when i seach whith english or number ，the result is right。
I guess flygrep doesn't support Chinese search。How can I use Chinese search？

## Screenshots
![图片](https://user-images.githubusercontent.com/32120035/134447438-a54cba14-6398-4e58-813a-3f34aa07d107.png)

![图片](https://user-images.githubusercontent.com/32120035/134447406-3fe2df4c-dfaf-4764-8de3-f3f3f1b2c74d.png)

**Comment by wuxinyiwu** [comment]
I solved the problem。Flygrep needs to install search tools like ripgrep。Because spacevim.org/cn/ don't ask me to install search tools,i think spacevim already have them,so you should ask user install search tools，let them don't make the same mistake as me.

**Comment by wsdjeg** [comment]
flygrep supports grep, pt, ag, and ripgrep etc. by default I think you are using grep which has been installed in your os. I do not if grep support chinese. 
--------------
wsdjeg

**Comment by wuxinyiwu** [comment]
Flygrep needs to install search tools like ripgrep。
