### ISSUE TITLE
没整明白colors 和 语法检测等插件是怎么加载的。

### ISSUE THREAD

**Issue by chenyangguang** [wsdjeg/SpaceVim#449]
## 插件层是怎么加载的？ 

init.vim里面配置了 solarized， 但是实际上安装完  vim 和 spacevim 之后， 颜色没变化。然后语法没高亮。
## Environment Information
- OS: ubuntu 14.04
- vim version: 8.0
## The reproduce ways from Vim starting (Required!)

终端直接启动的 vim 
init.vim   config: 

` 
....
let g:spacevim_colorscheme = 'solarized'

call SpaceVim#layers#load('lang#php')
...

`

**Comment by wsdjeg** [comment]
使用`：SPConfig -g` 打开用户配置文件，可能是你配置文件位置搞错了

**Comment by wsdjeg** [comment]
将以下内容加入到 `～/.SpaceVim.d/init.vim`
```viml
let g:spacevim_colorscheme = 'NeoSolarized'
```
