### ISSUE TITLE
the "core#statusline" layer disable the "colorscheme" layer

### ISSUE THREAD

**Issue by taewyth** [wsdjeg/SpaceVim#4490]
I wanted to use the `core#statusline` layer however, as soon as I add the `[options]` tag, it seems to deactivate everything I've put in my `colorscheme` layer.

the colorscheme I try to use is simply SpaceVim, `enable_guicolors` is set to `true` and I'm running it in terminal.

**Comment by wsdjeg** [comment]
please follow the issue template. and  maybe there is syntax error in your toml file.
