### ISSUE TITLE
netrw plugin

### ISSUE THREAD

**Issue by vadimi** [wsdjeg/SpaceVim#4491]
It looks like there was a change recently to disable netrw plugin:

https://github.com/SpaceVim/SpaceVim/blob/654cfc88552a7970a12eb25ee99e80168fdc9bed/autoload/SpaceVim/layers/core.vim#L43

Any chance it can be configrable?

## Expected behavior, english is required
type `:Explore` opens netrw

**Comment by wsdjeg** [comment]
Yeah, this plugin is disable by default. because it conflict with the filetree plugin. the default filetree is nerdtree.
