### ISSUE TITLE
PHP LSP not working

### ISSUE THREAD

**Issue by programmador** [wsdjeg/SpaceVim#4501]
Seems to be not too old issue as I've been upgrading SpaceVim from time to time.
So, lsp after latest upgrade behaves like it does not exist. Except for it's keybindings which do exist but do not spawn any actions.
I've been checking it running:
```
watch "ps aux | grep -i intelephense"
```
Both Spacemacs and older versions of SpaceVim spawn a `node` process while opening a project.
Newer versions of SpaceVim do not spawn it.
There are no error messages anywhere.
Config:
```
[[layers]]
    name = "lsp"
    filetypes = [
        "dart",
        "php",
        "rust",
        "go",
        "typescript",
        "javascript"
    ]
    [layers.override_cmd]
      php = ["intelephense", "--stdio"]
      dart = ["dart", "/opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot", "--lsp"]
      rust = ["rust-analyzer"]
      go = ["gopls", "serve"]
      javascript = ['typescript-language-server', '--stdio']

```
I've encountered the problem on another PC so was ready for the issue and made a backup of `~/.SpaceVim` folder on my mostly used PC before upgrading. After restoring backup everything works nicely.

**Comment by programmador** [comment]
Could be related to #4497

**Comment by wsdjeg** [comment]
@programmador yeah, the lsp layer has been changed for neovim. we are using neovim built-in lsp now. and for php it should be:

```
[[layers]]
    name = 'lsp'
    enabled_clients = ['intelephense']
```

**Comment by programmador** [comment]
Wow, thank You! Now it works. I've grepped `intelephense` and found out that the list should be configured using identifiers from this doc: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
For example `rust_analyzer` instead of `rust-analyzer` (binary name) and `tsserver` instead of `typescript-language-server` and so on.

**Comment by programmador** [comment]
@wsdjeg What completion engine should be configured for native nvim lsp?
coc seems no longer working. I've disabled the option and seems like deoplete was installed as a default. It kind of works but does not import namespaces. Moreover it's github repo says that it's abandoned and ddc should be used instead but I can't see such option in [autocomplete doc](https://spacevim.org/layers/autocomplete/)

**Comment by programmador** [comment]
[Neovim doc](https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion) says:
> Neovim does not support built-in autocompletion. As mentioned in the readme, you can bind the completion results to omnifunc for on-demand completion. To use autocompletion, please use an external plugin. We recommend nvim-cmp, the successor/rewrite of nvim-compe.

Neither of suggested is supported by autocomplete layer
