### ISSUE TITLE
nvim +"Man man" not work as expected

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#4503]
## Expected behavior, english is required

``neovim`` has an internal command ``Man``, which show manpage inside vim.
When we start nvim with ``nvim +"Man man"``, it should display a single window with the manpage of ``man`` command.
But it shows the welcome page.  Pressing ``[SPC]<tab>`` will show the manpage in the upper window.

## The reproduce ways from Vim starting (Required!)

1. Execute the command
   ```sh
   nvim +"Man man"
   ```
2. Press ``[SPC]<tab>``

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
I think it is same as #3559

**Comment by wsdjeg** [comment]
I can not fix this issue, we use https://github.com/SpaceVim/SpaceVim/blob/f6ac73b1756223f202ece3b0d6e8aa5997d0bdb1/autoload/SpaceVim.vim#L1485  to check startup status.

**Comment by wsdjeg** [comment]
https://stackoverflow.com/questions/10357374/is-it-possible-to-access-vims-command-line-arguments-in-vimscript
