### ISSUE TITLE
problems getting lsp to work and "vim-import-js" building failed

### ISSUE THREAD

**Issue by Kenneth-Mata** [wsdjeg/SpaceVim#4504]
## Expected behavior
i guess is the the error message not popping up? i'm totally new to this and saw this was designed for starting users

## The reproduce ways from Vim starting (Required!)

nvim (not sure what to put here)

## Output of the `:SPDebugInfo!`

https://pastebin.com/DKqcp6pK

## Screenshots

![failed to build vim_import_js](https://user-images.githubusercontent.com/92641443/138276865-f2440d7c-aaa6-449b-b72f-05b8c9a7ae86.png)
![failed to enable lsp for javascript](https://user-images.githubusercontent.com/92641443/138276872-1dac4410-2f3e-4f9c-b492-94486f4bb452.png)

I saw this could be a reason in one of the forums
![versions of node, npm and instalation of yarn](https://user-images.githubusercontent.com/92641443/138276876-618047a8-2594-40b9-ac7c-146ab74fe028.png)

**Comment by wsdjeg** [comment]
The issue must be reproduce able, I can not fix the issue which is not reproduce able.

**Comment by elimossrosenberg** [comment]
Hello, I also have the following, which might help reproduce


`[dein] Error occurred while executing hook: nvim-lspconfig`
`[dein] Vim(lua):E5108: Error executing lua [string ":lua"]:40: attempt to index a nil value`

I tried with a fresh install of SpaceVim on Ubuntu 20.04 and on Windows. I tried several versions of nvim >=5.1 including latest stable.

repro is simple with the following `init.toml`

`[[layers]]`
`   name = 'lsp'`
`   enabled_clients = [ 'pyls' ]`
  
  LSP works correctly on older nvim 4.x if I reinsert the `filetypes` into the lsp layer configuration. 
  
  Thanks for reviewing!

**Comment by wsdjeg** [comment]
It is `pylsp`

**Comment by elimossrosenberg** [comment]
Thank you, @wsdjeg. Tested with `enabled_clients = [ 'clangd' ]` and lsp layers are now working on nvim 0.5.1.

**Comment by elimossrosenberg** [comment]
Also working with `enabled_clients = ['clangd', 'pylsp' ]` ;

**Comment by wsdjeg** [comment]
ok. nice!
