### ISSUE TITLE
Use google java format with jdk version over jdk16, needs extra flag

### ISSUE THREAD

**Issue by ForgetAll** [wsdjeg/SpaceVim#4508]
My Device Java version:
```shell
java --version
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```
When I download the jar and try to use it, it doesn't work in vim.And I see [docs](https://github.com/google/google-java-format) it said:
The following flags are required when running on JDK 16, due to JEP 396: Strongly Encapsulate JDK Internals by Default:
```
java \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  -jar google-java-format-1.12.0-all-deps.jar <options> [files...]
```
Worked in command line, it seemed that format jar exec command is in autoload/SpaceVim/layers/lang/java.vim.Changed execute args and it worked in vim, but I think it's not a good idea to make it work that way.Also I don't find way to overwrite this flag in doc.

**Comment by wsdjeg** [comment]
change `g:neoformat_java_googlefmt` in bootstrap after function.
