### ISSUE TITLE
First execute vim crashed

### ISSUE THREAD

**Issue by miraclemore** [wsdjeg/SpaceVim#451]
## Expected behavior, english is recommend
Vim can work

## Environment Information
- OS: ubuntu 16.04.2 + gnome desktop
- vim version: 7.4.1689
- neovim version: N/A (Do not install by myself)

## The reproduce ways from Vim starting (Required!)
1. curl -sLf https://spacevim.org/install.sh | bash
2. vim

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
vim: Caught deadly signal Bus

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.
![screenshot from 2017-04-20 00-05-56](https://cloud.githubusercontent.com/assets/3292065/25190341/7dbf4b60-255e-11e7-9c11-c2b59f4005e9.png)

**Comment by wsdjeg** [comment]
I will try to fix it. and what is :SPDebugInfo!

**Comment by miraclemore** [comment]
I can't enter any command on Vim.

**Comment by wsdjeg** [comment]
I want to reproduce it. can you try vim8?

**Comment by wsdjeg** [comment]
@miraclemore I just build vim 7.4.1689, and I can reproduce this issue.

![2017-04-20_680x109](https://cloud.githubusercontent.com/assets/13142418/25231670/45f01298-260b-11e7-89b8-95fd8bb4c949.png)

**Comment by miraclemore** [comment]
@wsdjeg Yes, i can try Vim8. but currently ubuntu LTS only support package 7.4.1689. It will influence lots of end users.
I see u add Bug-vim label for that. Is that we cant support  7.4.1689 for Spacevim.
Is that the only way to build vim 8.0 on my local for Spacevim ?

**Comment by wsdjeg** [comment]
I will try to fix it.

**Comment by Shougo** [comment]
Unfortunately, 7.4.1689 is beta version.
Especially, Job features.
I see `on_stdout` in the error image.
I think Job features is broken in the version.
SpaceVim should use Job features in Vim 8.0+.

**Comment by wsdjeg** [comment]
OK, will not use job on this version. I am not sure if someone can implement job feature via Python or ruby. 

I want to add this feature to SpaceVim's job API.

**Comment by Shougo** [comment]
dein.vim supports Job feature in Vim8.0/neovim only.
It is the same reason.

**Comment by wsdjeg** [comment]
@Shougo  I have implement `fallback to sync system()` feature when update plugins. and the ui should same as before. `install plugins` feature need more work.
