### ISSUE TITLE
Add a hotkey to display current time

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#4510]
**Is your feature request related to a problem? Please describe.**
While in ``centered buffer mode`` (``[SPC]wc``) in full-screen mode, nothing but the content is shown.  It's better to has a hotkey to display current time, so we don't need to take out the cellphone or exit centered mode just to see the clock.

**Describe the solution you'd like**
Have a hotkey to display current time largely in the center of screen.

**Comment by wsdjeg** [comment]
We have two key binding to display time and data on statusline,  it is `SPC t m d` and `SPC t m t`.

**Comment by thawk** [comment]
> We have two key binding to display time and data on statusline, it is `SPC t m d` and `SPC t m t`.

Yes, I know.  But the statusline itself is hidden in the ``centered buffer mode``.

I found a way to archive it: type ``time`` then press ``TAB``, it will be expanded to current time.  And then undo it.
