### ISSUE TITLE
Missing icons in statusline after fresh install

### ISSUE THREAD

**Issue by pievalentin** [wsdjeg/SpaceVim#4512]
## Expected behavior
Environment:
  - OS: MacOS BigSur 11.6
  - Vim: NVIM v0.5.1
  - iTerm: Build 3.3.7

After a successful fresh install, to have proper icon in the `statusline` and the buffer list. See the screenshot below.

## How to reproduce
1. Run: `curl -sLf https://spacevim.org/install.sh | bash -s -- -i`
2. Open a python file: `vim foo.py`

## Output of the `:SPDebugInfo!`
See this gist:
https://gist.github.com/pievalentin/25fd91652dce2946f266e16e83b2d872

## Screenshots

<img width="976" alt="Screen Shot 2021-11-02 at 11 41 22 AM" src="https://user-images.githubusercontent.com/14977219/139880146-6144c991-cfb4-4224-b0d1-7528a81e5bbc.png">

I think it must be a simple bug 😅 but I could not find a fix in the list of closed issues.

**Comment by wsdjeg** [comment]
You need to install nerd-fonts.

**Comment by pievalentin** [comment]
Ok I was thinking the installation script pulled the nerd font and installed them.

So the fix is to download one of the nerd font and install it on your system. 
After that, in your terminal emulator, modify your profile so that it uses the nerd font.
With the nerd font selected, the icons are showed properly.
