### ISSUE TITLE
lsp autocomplete missing fn args on rust trait impl 

### ISSUE THREAD

**Issue by xusd320** [wsdjeg/SpaceVim#4513]
lsp autocomplete missing fn args on rust trait impl , as blow
<img width="911" alt="Screen Shot 2021-11-04 at 15 21 52" src="https://user-images.githubusercontent.com/16577489/140273326-077aae4d-59e3-4cf2-ac75-ef0a530672d4.png">

**Comment by xusd320** [comment]
I have to type the fn args (&self) by myself.

**Comment by wsdjeg** [comment]
this is issue with lsp server, nothing can be done in spacevim, maybe you can switch to neovim and use the built-in lsp.
