### ISSUE TITLE
SCP to open remote files not working

### ISSUE THREAD

**Issue by logoff** [wsdjeg/SpaceVim#4516]
## Expected behavior, English is required
I expect to get a remote folder or file opened using scp URLs (scp://user@server//absolute/path/to/document)

## The reproduce ways from Vim starting (Required!)

If I use vanilla vim (with `vim --clean`) I can open remote files/folders. If I use SpaceVim config, it doesn't work.

**Comment by wsdjeg** [comment]
as I know  defx do not support remote file. maybe @shougo can provides more infomation about it. I have searched with google, same issue here https://github.com/Shougo/defx.nvim/issues/159

**Comment by wsdjeg** [comment]
I have added bundle defx-sftp, please test this issue again.

**Comment by Shougo** [comment]
Yes.  `defx-sftp` only exists.  You can create plugin for ssh files.
