### ISSUE TITLE
 Too many arguments for function: globpath

### ISSUE THREAD

**Issue by chenyangguang** [wsdjeg/SpaceVim#452]
## Expected behavior, english is recommend
Start up vim normally.

## Environment Information
- OS: ubuntu Kylin 14.04 
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
Git

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
Well, When i start to edit my crontab job(my default edit is vim). The spacevim calls a problem like below.

➜  ~ crontab -e
[dein] Error occurred while executing hook: unite.vim
[dein] Vim(let):E118: Too many arguments for function: globpath
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
It is issue with an old plugin, I will find it out. and fix it.

**Comment by wsdjeg** [comment]
I have fixed it in #447 , please wait for merging.
