### ISSUE TITLE
[LSP] Can't show documentation via [K] or [SPC l d]

### ISSUE THREAD

**Issue by gegoxaren** [wsdjeg/SpaceVim#4525]
## Expected behaviour, english is required
When using a language server that is not built in to the SpaceVim environment, the key-bindings for "show documentation" et.al. do not work.

A warning about `man -w <defition>: no manual entry for <definiton>` is shown.

## The reproduce ways from Vim starting (Required!)
Install the [Vala Language Server](https://github.com/Prince781/vala-language-server), and add the following to the `init.toml` file.

```
[[layers]]
    name = "lsp"
    filetypes = [
        "vala",
        "genie",
    ]
    [layers.override_cmd]
        vala = ["vala-language-server"]
        genie = ["vala-language-server"]

```

Open a Vala project (has to be Meson based), and go to a file and press `K`.

I would suspect that any other language server that does not have native support in SpaceVim will exhibit the same behaviour.

## Output of the `:SPDebugInfo!`
[https://gist.github.com/gegoxaren/758130a730224cdcfaa63a7ad1c6523d](https://gist.github.com/gegoxaren/758130a730224cdcfaa63a7ad1c6523d)

## Screenshots
[https://asciinema.org/a/mppDLvR2MFQepixBsGZBpv9Qc](https://asciinema.org/a/mppDLvR2MFQepixBsGZBpv9Qc)

**Comment by wsdjeg** [comment]
The `lsp` layer doc should be improved. you need to enable `vala_ls` via:

```
[[layers]]
    name = 'lsp'
    enabled_clients = ['vala_ls']
```
