### ISSUE TITLE
[Help needed] Cannot see icons in filetree

### ISSUE THREAD

**Issue by hypghzy** [wsdjeg/SpaceVim#4528]
Will I setting up my new installation, I filed to enable the icons in the filetree.

I have discovered the new option for that setting is 
enable_filetree_filetypeicon
I have added the line
enable_filetree_filetypeicon = true 
under my [options] in init.toml

I have tried it under a freshly installed situation but is does not work.
I have checked the :SPDebugInfo and saw enable_filetree_filetypeicon  = 1, which I think the feature is enabled.
Therefore I wondering is there any other things that I missed.
Any help is greatly appreciated.

**Comment by Rom1deTroyes** [comment]
What font do you use ?

You may need to configure your terminal emulator to use a Nerd Font which have the said symbols.

**Comment by hypghzy** [comment]
> What font do you use ?
> 
> 
> 
> You may need to configure your terminal emulator to use a Nerd Font which have the said symbols.
> 
> 

Thanks for the reply. I have the nerd-fonts installed and the icons in the status bar are displayed correctly. But there is no icon in the fieltree, I think if the symbols are not installed, there would be a symbol that indicate icon not found instead of showing nothing.
