### ISSUE TITLE
Issue on using remark as markdown formatter

### ISSUE THREAD

**Issue by hypghzy** [wsdjeg/SpaceVim#4529]
I found out the SPC+b+f formatting cannot work While I adding lang#markdown layer.
It says "Neoformat: formatters remark failed to run"
After some researching and testing, I managed to change the remarkrc file generated by ~/.SpaceVim/autoload/SpaceVim/layers/lang/markdown.vim from

module.exports = {
  settings: {
    listItemIndent: 'tab',
    stringLength: require('wcwidth'),
  },
  plugins: [
    require('remark-frontmatter'),
  ]
};

into

module.exports = {
  settings: {
    listItemIndent: 'tab',
  },
  plugins: [
    'remark-frontmatter',
  ]
};

I removed the require() and it could work.
But I'm not sure if it's the right way, so maybe someone can please take a look and see if it fix the bug, or I just did something wrong.

**Comment by wsdjeg** [comment]
you need to install remark plugins:

```
npm -g install remark
npm -g install remark-cli
npm -g install remark-stringify
npm -g install remark-frontmatter
npm -g install wcwidth
```
