### ISSUE TITLE
Plugin Install failed

### ISSUE THREAD

**Issue by moreoronce** [wsdjeg/SpaceVim#453]
## Environment Information
- OS: Window 10
- vim version: Vim 8.0 64-bit

## The reproduce ways from Vim starting (Required!)

Open gvim and :SPUPDATE, some plugin update failed. like jedi-vim, nerdtree , unite-everything, open-browser,  onedark, papercolor and oceanic-next

Neither i type :echo have('pyhon2') nor  :echo have('python3'), the result always 0. 
My python version is Python 3.6.0 |Anaconda 4.3.1 (64-bit)

### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 4
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'jellybeans'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['plasticboy/vim-markdown', {'on_ft': 'markdown'}], ['jedi-vim']]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 0
g:spacevim_hiddenfileinfo = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_max_column = 80
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_debug = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 4
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = [['junegunn/fzf.vim'], ['GitHub-api.vim'], ['github-issues.vim'], ['vim-gita.vim'], ['vim-github-dashboard.vim'], ['Mysql.vim'], ['GitHub.vim'], ['vim-youdao-translater.vim'], ['vim-gista.vim'], ['vimwiki.vim'], ['dictionary.vim']]
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = 'DejaVu\ Sans\ Mono'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'default', 'unite', 'github', 'ctrlp', 'autocomplete', 'vim', 'windows', 'lang#vim', 'lang#python', 'colorscheme']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 32
g:spacevim_enable_googlesuggest = 1
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 0
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 0
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_leader_guide_vertical = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(C:\Program Files\Vim\vim80\gvim.exe)
version: 800
OS: Windows
[shell, shellcmdflag, shellslash]: ['C:\Windows\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.
Checking +python:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file C:\Users\chife\.cache\SpaceVim\SpaceVim.log does not exists, only log for current process will be shown!
```

**Comment by wsdjeg** [comment]
the install script of all the plugins is same, If you can install most of the plugins, I think it is not issue with SpaceVim, you should use vpn or ss to connect to github. BTW I think you should install vim from https://github.com/vim/vim-win32-installer/releases

and you should has `python` and `python3` in PATH.

**Comment by moreoronce** [comment]
I am using shadowsocks to connect github so the GFW seems not be the key problem.

After i put python35.dll to system32 folder, the result of :echo has('python3') is 1

i try to install jedi-vim by SPInstall  and got the message said

![image](https://cloud.githubusercontent.com/assets/1954009/25235618/46795ce4-2618-11e7-8aea-b609c4d35eae.png)

**Comment by wsdjeg** [comment]
I can not reproduce it, jedi-vim's path should be `/home/wsdjeg/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim`.

what is the output of `:echo dein#get('jedi-vim').path`

**Comment by moreoronce** [comment]
C:/Users/chife/.cache/vimfiles/repos/github.com/vim-scripts/jedi-vim

**Comment by wsdjeg** [comment]
hmm, What is your custom config?

**Comment by moreoronce** [comment]
" Here are some basic customizations,
" please refer to the ~/.SpaceVim.d/init.vim
" file for all possible options:
let g:spacevim_default_indent = 4
let g:spacevim_max_column     = 80

" Change the default directory where all miscellaneous persistent files go.
" By default it is ~/.cache/vimfiles.
let g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles'

" set SpaceVim colorscheme
let g:spacevim_colorscheme = 'jellybeans'
let g:spacevim_enable_guicolors	= 1

" Set plugin manager, you want to use, default is dein.vim
let g:spacevim_plugin_manager = 'dein'  " neobundle or dein or vim-plug

" use space as `<Leader>`
let mapleader = "\<space>"

" Set windows shortcut leader [Window], default is `s`
let g:spacevim_windows_leader = 's'

" set cachelimit of deopelete
let g:deoplete#tag#cache_limit_size=150000

" Set unite work flow shortcut leader [Unite], default is `f`
let g:spacevim_unite_leader = 'f'

" By default, language specific plugins are not loaded. This can be changed
" with the following, then the plugins for go development will be loaded.
" call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('lang#markdown')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('lang#python')
" loaded ui layer
call SpaceVim#layers#load('ui')

" If there is a particular plugin you don't like, you can define this
" variable to disable them entirely:
let g:spacevim_disabled_plugins=[
    \ ['junegunn/fzf.vim'],
    \ ['GitHub-api.vim'],
    \ ['github-issues.vim'],
    \ ['vim-gita.vim'],
    \ ['vim-github-dashboard.vim'],
    \ ['Mysql.vim'],
    \ ['GitHub.vim'],
    \ ['vim-youdao-translater.vim'],
    \ ['vim-gista.vim'],
    \ ['vimwiki.vim'],
    \ ['dictionary.vim'],
    \ ]

" If you want to add some custom plugins, use these options:
let g:spacevim_custom_plugins = [
    \ ['plasticboy/vim-markdown', {'on_ft' : 'markdown'}],
    \ ['jedi-vim'], 
    \ ]

" set the guifont
let g:spacevim_guifont = 'DejaVu\ Sans\ Mono'

" set path of python
"let g:python_host_prog = '/Users/moreoronce/.pyenv/versions/neovim2/bin/python'
"let g:python3_host_prog = '/USers/moreoronce/.pyenv/versions/neovim3/bin/python'

" set deoplete-jedi
let g:deopelete#sources#jedi#ehable_cache=1
let g:deopelete#sources#jedi#statement_length=30

" enlighted column
set cuc

" set sidebar width
let g:spacevim_sidebar_width=32
" set the max_processes that plugin manager could use
let g:spacevim_plugin_manager_max_processes=4

" allow google suggestion
let g:spacevim_enable_googlesuggest=1

**Comment by wsdjeg** [comment]
```
let g:spacevim_custom_plugins = [
\ ['plasticboy/vim-markdown', {'on_ft' : 'markdown'}],
\ ['jedi-vim'],
\ ]
```

jedi-vim is in `lang#python` layer, you should not add it to g:var, BTW you should not use `jedi-vim`, use `davidhalter/jedi-vim` instead.

**Comment by moreoronce** [comment]
OK, i will try it. Thanks for the reply
