### ISSUE TITLE
Error when pressing SPC

### ISSUE THREAD

**Issue by sadegr** [wsdjeg/SpaceVim#4533]
## Expected behavior, english is required
Expected behavior is the mappings guide opens when you press SPC (space bar key) while in Vim in normal mode.
Instead, I see this error:
```
               Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>64_start_buffer[4]..<SNR>64_winopen[7]..107:
line   21:
E714: List required
Error detected while processing function SpaceVim#mapping#guide#start_by_prefix[29]..<SNR>64_start_buffer:
line    4:
E714: List required
Press ENTER or type command to continue
```

Even pressing Enter or SPC again doesn't cause the mappings menu to show up. I tried looking at the lines mentioned in the error message but unfortunately I'm not familiar enough with Vim script or SpaceVim to figure out what's wrong, any help would be appreciated!

## The reproduce ways from Vim starting (Required!)
1. Install SpaceVim `curl -sLf https://spacevim.org/install.sh | bash`
2. Run Vim `vim`
3. Press SPC (space bar key)

## Output of the `:SPDebugInfo!`
https://gist.github.com/sadegr/3b51ea31924810e333e9517b91ec0c2e

## Screenshots
![SPC](https://user-images.githubusercontent.com/20391979/143968488-bfc7eee8-d253-4ed7-a62b-0d3ad60f6a53.PNG)

**Comment by wsdjeg** [comment]
What is the version of your vim?
