### ISSUE TITLE
[Question]: recommended way to configure Firenvim? 

### ISSUE THREAD

**Issue by dclong** [wsdjeg/SpaceVim#4547]
Firenvim is an awesome tool which allows using NeoVim to edit text in browsers. I'm currently configuring it by editing the `init.vim` file directly. I wonder does SpaceVim has special support (or layer) for firenvim? What is the recommended way to configure Firenvim?

**Comment by wsdjeg** [comment]
I do  not use firenvim, but it should same as neovim, so you can use bootstrap function.

**Comment by wsdjeg** [comment]
I do  not use firenvim, but it should same as neovim, so you can use bootstrap function.
