### ISSUE TITLE
tab renaming is not saved so that tabs fold mistakenly

### ISSUE THREAD

**Issue by Tokubara** [wsdjeg/SpaceVim#4550]
## Expected behavior, english is required

Even when the tab length is not that long, tabline folds some tabs.
I read tabline.vim, and find the problem is because, when we rename a tab in tab manager, the new tab name is not saved. And `s:tabname` just consider the filename, does not take the new name we give into account.
I think the name we give should be saved. And `s:tabname` should be changed.
It will be great if `Ssave` which saves the vim session saves new tab names.

## Screenshots

![image](https://user-images.githubusercontent.com/32409331/147825861-a2a0086d-c7ef-484e-9f27-c1ac56f09cd1.png)

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/32409331/147825825-288e14e5-cf94-46ce-8d35-adc911923b46.png">

**Comment by Tokubara** [comment]
Currently, I make `s:check_len` always return 0.

**Comment by wsdjeg** [comment]
Ok, this is a bug of `s:check_len` function.
