### ISSUE TITLE
Disable checker for some certain filetypes

### ISSUE THREAD

**Issue by iseri27** [wsdjeg/SpaceVim#4553]
I'm using SapceVim to write latex documents, every time i save the file, it will generate many useless warnings. It's really noisy

I read the SpaceVim document and #399 , maybe now the layer "checker" can only be disable globally. But when i'm writing other, like C or python, checker is useful.

So is it possible to disable or enable checker for some certain filetypes ?

**Comment by wsdjeg** [comment]
@Corona09 This feature has been added, please update spacevim.
