### ISSUE TITLE
Update Instructions for JS as IDE (New Instructions from ES-C

### ISSUE THREAD

**Issue by mbarberry** [wsdjeg/SpaceVim#4554]
## Expected behavior, english is required
Eslint does not work based on the instructions on the website page for using SpaceVim as JS IDE. The use of eslint-cli is deprecated and now uses eslint (no cli) 

## The reproduce ways from Vim starting (Required!)
Follow the instructions from the website to use JS as an IDE with ESlint and then try to save a file 

## Output of the `:SPDebugInfo!`
```Cannot find local ESLint!```
```Please install ESLint by npm install eslint --save-dev.```

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
thanks, I will merge that PR after new develop version.
