### ISSUE TITLE
SpaceVim not loading properly from .SpaceVim/vimrc

### ISSUE THREAD

**Issue by calm-tedesco** [wsdjeg/SpaceVim#4558]
Hi, I'm using Debian Sid. SpaceVim does not load automatically when I launch Vim (I reinstalled and recompiled both). When I load the vimrc file with:

`vim -u ~/.SpaceVim/vimrc`

I get the following errors:

```
Error detected while processing /home/calm-tedesco/.SpaceVim/vimrc[25]../home/calm-tedesco/.SpaceVim/main.vim:
line    9:
E117: Unknown function: SpaceVim#logger#info
line   64:
E117: Unknown function: SpaceVim#logger#info
Press ENTER or type command to continue
```

This started happening after changing my username to calm-tedesco. Is it the '-' in the username?

**Comment by LokiLuciferase** [comment]
I have the same issue on Linux Mint 20.2 starting with tag `v1.9.0`. My username consists of only lower case letters.

**Comment by calm-tedesco** [comment]
Hey, @LokiLuciferase . I just reinstalled vim from Debian repositories and that solved it. Do you still have this issue?

**Comment by LokiLuciferase** [comment]
My bad for not completely specifying my environment, I am actually using neovim v0.6.1 from the neovim stable PPA: `http://ppa.launchpad.net/neovim-ppa/stable/ubuntu`

I already switched off the unstable repo containing neovim v0.7.x, but to no avail.
