### ISSUE TITLE
How to use shortcut keys to switch from terminal window to other window 

### ISSUE THREAD

**Issue by xiaolang01** [wsdjeg/SpaceVim#4559]
I want to use shortcut keys to switch from terminal window to other windows, but I didn't find such shortcut keys

**Comment by TorrezMN** [comment]
I think this is already available...

have you tried using:
`<space> + <number>`

press space bar and then a number... (buffer number...)

**Comment by wsdjeg** [comment]
first, you need to swtch to normal mode via `Ctrl-\ Ctrl-n`, then you can use `SPC + number` to swtch to windows. and you can also use `` Ctrl-` `` to hide terminal. and use `SPC '` to reopen it again.
