### ISSUE TITLE
Error detected while proccessing InsertLeave Auto command for "*"

### ISSUE THREAD

**Issue by chenyangguang** [wsdjeg/SpaceVim#456]
## Something wrong crash my compute(over 5 times )
Config global file with command `:SPConfig -g` 
this step is ok. 

## Environment 
- OS:ubuntu Kylin 14.04 
- vim version: 8.0 (install from source with python and lua support and so on.)
- SpaceVim  branch (master)

## start vim in the terminal with 
 `vim`

## crash info.
When i post this config lines: 

let g:spacevim_default_indent = 3
let g:spacevim_max_column     = 80
let g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles/'
let g:spacevim_colorscheme = 'jellybeans'
let g:spacevim_plugin_manager = 'dein'  " neobundle or dein or vim-plug
let mapleader = "\<space>"
let g:spacevim_windows_leader = 's'
let g:spacevim_unite_leader = 'f'
call SpaceVim#layers#load('lang#go')
call SpaceVim#layers#load('ui')
let g:spacevim_disabled_plugins=[
    \ ['junegunn/fzf.vim'],
    \ ]
let g:spacevim_custom_plugins = [
    \ ['plasticboy/vim-markdown', {'on_ft' : 'markdown'}],
    \ ['wsdjeg/GitHub.vim'],
    \ ]
let g:spacevim_guifont = 'DejaVu\ Sans\ Mono\ for\ Powerline\ 11'

into the init.vim after i woke up `:SPConfig -g` command in the vim editor.
There rose an error that crash my computer.  And computer came to die.
Error message below like this: 

 
**_Error detected while proccessing InsertLeave Auto command for "*":
Traceback (most recent call last). 
press enter or type command to continnue._**

 每次启动这个配置的时候，丫的都直接挂掉，死机了。完全没头绪。有点影响工作。现在完全不敢再写这个配置了，生怕每次都挂了需要重启。(PS: Maybe  there is something wrong with my kylin ubuntu14.04  Because it works well at my  ubuntu16.04  sys.)

**Comment by wsdjeg** [comment]
hmm, Will fix it.

**Comment by wsdjeg** [comment]
你的vim小版本是多少，我来测试下

**Comment by chenyangguang** [comment]
➜  ~ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 20 2017 17:51:55)

**Comment by wsdjeg** [comment]
I can not reproduce it in vim in arch.

**Comment by wsdjeg** [comment]
这个问题比较恶心，我在7.4.1689中也遇到一样问题

**Comment by chenyangguang** [comment]
哦，这个可能是低版本里面不兼容？ 我其实很郁闷。因为工作使用的 ubuntu Kylin 14.04, 然后我自己用的是ubuntu 16.04LTS, 环境不一样，编译了不一样的编辑器。 所以这个问题只在一台电脑上出现。后面我也不知道怎么跟踪了。因为太蛋疼了。

**Comment by wsdjeg** [comment]
看不出来你的小版本号

**Comment by chenyangguang** [comment]
坐等spacevim1.0 出来， 我默默地先用着我的spacemacs, 嘻嘻～～

**Comment by wsdjeg** [comment]
@chenyangguang can  not reproduce in vim7.4.001, what is your version info？
