### ISSUE TITLE
Start SpaceVim Error.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#4564]
## Screenshots

Start SpaceVim Error.
![image](https://user-images.githubusercontent.com/5350867/150052765-59bd2c89-d59f-49bc-9062-94d516c87797.png)

**Comment by xylinkun** [comment]
I have found this error is imported by this commit https://github.com/SpaceVim/SpaceVim/commit/283939971496825f122bf27a13432ddf1e78c16e

But I cannot debug it.

**Comment by wsdjeg** [comment]
@NamelessUzer can you test it in latest version, I can not reproduce this issue now.
