### ISSUE TITLE
How to add total lines to statusline

### ISSUE THREAD

**Issue by Mythbusters123** [wsdjeg/SpaceVim#4567]
I saw a vimrc where someone had `<line they are on>/<total number of lines in the file>`. Is there a way to do this in ths spacevim configs? https://i.imgur.com/dWa7FI1.png

**Comment by wsdjeg** [comment]
This feature has been added, use following config:

```
    statusline_right_sections = [
        'fileformat',
        'cursorpos',
        'totallines'
    ]
```
