### ISSUE TITLE
Vim8.0 error on Ubuntu 16.04

### ISSUE THREAD

**Issue by miraclemore** [wsdjeg/SpaceVim#457]
## Expected behavior, english is recommend
Vim can work

## Environment Information
- OS: Ubuntu 16.04
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 22 2017 00:02:06)
- neovim version: N/A

## The reproduce ways from Vim starting (Required!)
According to the documents which Spacevim said, i remove vim 7.4 and build vim 8.0
Then launch vim.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.
Vim build command as below
```
./configure --with-features=huge \
             --enable-multibyte \
             --enable-rubyinterp=yes \
             --enable-python3interp=yes \
             --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
             --enable-perlinterp=yes \
             --enable-luainterp=yes \
             --enable-gui=gtk2 --enable-cscope --prefix=/usr
```
Error detected while processing /home/miracle/.SpaceVim/autoload/SpaceVim.vim:
line   79:
E121: Undefined variable: g:spacevim_plugin_bundle_dir
line   80:
E10: \ should be followed by /, ? or &
line   81:
E10: \ should be followed by /, ? or &
line  300:
E121: Undefined variable: g:spacevim_hosts_url
line  301:
E10: \ should be followed by /, ? or &
line  302:
E121: Undefined variable: g:spacevim_wildignore
line  303:
E10: \ should be followed by /, ? or &
line  304:
E10: \ should be followed by /, ? or &
line  305:
E10: \ should be followed by /, ? or &
Error detected while processing function SpaceVim#default[3]..SpaceVim#default#SetMappings:
line   67:
E10: \ should be followed by /, ? or &
Error detected while processing function SpaceVim#end[2]..SpaceVim#mapping#leader#defindWindowsLeader:
line    2:
E116: Invalid arguments for function zvim#util#defineMap
Error detected while processing /home/miracle/.SpaceVim/config/general.vim:
line    2:
E121: Undefined variable: g:spacevim_wildignore
E15: Invalid expression: 'set wildignore+=' . g:spacevim_wildignore
Error detected while processing function SpaceVim#autocmds#init:
line    4:
E10: \ should be followed by /, ? or &
Error detected while processing /home/miracle/.SpaceVim/config/commands.vim:
line    5:
E10: \ should be followed by /, ? or &

**Comment by wsdjeg** [comment]
how do you install SpaceVim, and what is the result of `git -C ~/.SpaceVim status`, and `git -C ~/.vim status`

**Comment by miraclemore** [comment]
@wsdjeg i followed the below command
1. curl -sLf https://spacevim.org/install.sh | bash
2. vim

**Comment by wsdjeg** [comment]
please show me the result of the command I commend above.

**Comment by miraclemore** [comment]
@wsdjeg  i clean all the vim files, and reinstalled again. There is no error. Maybe some network broken caused that. Thx for your help!

**Comment by wsdjeg** [comment]
nice. 😄

**Comment by yejw5** [comment]
Hello, @wsdjeg ! The same error happened with me. And I tried reinstall vim and spacevim, but the same error messages present again when I run `vim`. I run `git -C ~/.SpaceVim status` and `git -C ~/.vim status`, got the following result:
```
➜  ~ git -C ~/.SpaceVim status
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working directory clean
➜  ~ git -C ~/.vim status
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working directory clean
```

I install spacevim with `Ubuntu 16.04` and `vim 8.0`.

**Comment by yejw5** [comment]
And now, I can run successfully with `nvim` or `vi`. The error message is not trouble with me then.
But when I use `esc` to exit `insert mode`, it is very slow to response. If I input other word after `esc` quickly, the `exit` action will not take effect! Is this a common phenomenon？？？

**Comment by wsdjeg** [comment]
hmm, it should happen first time switch to normal mode?

**Comment by qingguee** [comment]
I met same problem and solved it after I remove all vim packages(vim7.4, p) which installed via Ubuntu.
I was builded vim8 from source code with python3. 
If anyone meet same problem, then you may try this. 

`vim/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed]
vim-addon-manager/xenial,xenial,now 0.5.5 all [installed,automatic]
vim-common/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed]
vim-doc/xenial-updates,xenial-updates,xenial-security,xenial-security,now 2:7.4.1689-3ubuntu1.2 all [installed]
vim-nox-py2/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed,automatic]
vim-python-jedi/xenial,xenial,now 0.9.0-1 all [installed]
vim-runtime/xenial-updates,xenial-updates,xenial-security,xenial-security,now 2:7.4.1689-3ubuntu1.2 all [installed,automatic]
vim-scripts/xenial,xenial,now 20130814ubuntu1 all [installed]
vim-tiny/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed]
vimixdark-gtk-themes/now 3.3 all [installed,local]
`
' 
sudo apt list --installed|grep vim
sudo apt remove vim*
'

**Comment by wsdjeg** [comment]
Thanks.
