### ISSUE TITLE
How can i add ctags to spacevim?

### ISSUE THREAD

**Issue by shie-ld** [wsdjeg/SpaceVim#4579]
I have already a ctags file, It works fine in vim . But as soon i installed spacevim I am not able to get to any tags, it shows no tag defined. How do I fix this issue?

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
If the `gtags` layer is loaded, spacevim will generate ctags file for current project automatically. and it will update `&tags` option too.  you can load the `gtags` layer. If you want to add other ctags file, you can use `set tags+=.....` in bootstarp function.
