### ISSUE TITLE
How to yank all maches after doing searching?

### ISSUE THREAD

**Issue by jsdryan** [wsdjeg/SpaceVim#4580]
<img width="706" alt="CleanShot 2022-02-01 at 00 52 30@2x" src="https://user-images.githubusercontent.com/34669056/151837875-3b2043d9-264b-405a-a8a0-f2516099fcc1.png">

I already try `Leader y`, but it seems it doesn't work.

**Comment by wsdjeg** [comment]
`Leader y` is to copy selected text in visual mode, it is not to yank matches. If you want to yanks matches, you can relace all lines to ip.
```
:%s/^http[s]:\/\///g
:%s/:\d\+$//g
:normal! ggVG"+y
```
