### ISSUE TITLE
No 'spc + p + f' shortcut mapped

### ISSUE THREAD

**Issue by xyjixyjixyji** [wsdjeg/SpaceVim#4581]
I installed SpaceVim today, and I added
```
[[layer]]
  name = "leaderf"
```
to my toml file

But when i am in my SpaceVim editor, pressing 'spc + p + f'  only tells me that the shortcut is not mapped.

Is this a bug or I just get my settings wrong to activate the shortcut?

**Comment by wsdjeg** [comment]
please follow the issue template, and debuginfo is needed.
