### ISSUE TITLE
PHP (and others) "Go to definition/implementation" via LSP, not gtags/ctags

### ISSUE THREAD

**Issue by programmador** [wsdjeg/SpaceVim#4585]
I'm not sure whether it is supported in SpaceVim for other languages but for PHP definitely the only way to find reference/implementation/definition is gtags which does not understand the code in a way to hide unrelevant entries.
For functions with common names such as 'count', 'find', 'getId' it is almost useless as the number of found results could be quite large especially including those from /vendor/ folder of the PHP project.

Probably if it's working the same way also for example for JavaScript/TypeScript - it should be a catastrophe as the number of libs in '/node_modules/' directory is usually enormous.

Spacemacs is using LSP to find references or interface implementations. So it should actually be somehow possible for Spacevim as well.

There is a chance that it would be alittle simplier for neovim with it's built-in LSP. I mean maybe there is an option to implement it once for all available languages. Though I don't know whether neovim's LSP does support this option at all. Moreover probably not all languages need such features as for example "find implementation (of an interface method)". Obviously because not all languages have interfaces.

**Comment by wsdjeg** [comment]
Hi @programmador thanks, this has been fixed, the lsp action will be called if the lsp client is enabled.

**Comment by programmador** [comment]
I do not see any changes (in neovim). Does it work for traditional lsp only or neovim's built-in one should be affected too?

**Comment by dereckson** [comment]
"this has been fixed": can you add a reference to the relevant commit?

**Comment by wsdjeg** [comment]
@programmador This issue should be fixed now, if you enable the php language server in lsp layer. `g d` will use lsp command now. You can load the lsp layer like this:

```
[[layers]]
    name = 'lsp'
    enabled_clients = ['intelephense']
    enable = true
```

and of cause, you need to install intelephense:

```
npm i intelephense -g
```

**Comment by programmador** [comment]
I have lsp enabled exactly in the way You described above, here's my config:
[init.toml.txt](https://github.com/SpaceVim/SpaceVim/files/8479568/init.toml.txt)
I don't see it to work as expected. And I've just done `SPUpdate`.

Here's an illustration. Red strikedthrough items should not have been found.
But they do occur which tells that search results are not from LSP (or maybe LSP did not get search instructions right - unfortunately I don't know how LSP protocol works).
I have the same intelephense in Spacemacs and it finds only what is needed without garbage. I mean it's not an intelephense issue.

Here is what happens when I press `SPC m g d` in SpaceVim
![screenshot_2022-04-13-111849](https://user-images.githubusercontent.com/674995/163133428-0b87aa6f-a00d-4553-8a3f-4806c85b7efb.png)

As for Spacemacs - there is nothing to screenshot for comparing actually as when I press `, g g` it just jumps to another file without showing any results because there is only one exact result found.

Abovementioned is about finding function/method definitions. As for Classes - the situation is actually the same.

Here You can see that two classes are found by SpaceVim though it should find only one as they belong to different namespaces. As I understand it means that they are found not via LSP:

![screenshot_2022-04-13-113404](https://user-images.githubusercontent.com/674995/163135634-8c761fb1-ab97-4dd0-a03f-90dfdbbe639b.png)

Here are Spacemacs results for clarity:

![screenshot_2022-04-13-113519](https://user-images.githubusercontent.com/674995/163135691-925d57dc-03dd-4610-bc73-f347a5cddca5.png)

As You can see there is actualy one search result via Spacemacs+intelephense. It just asks whether to go to the line where class name is declared or to it's constructor.

To illustrate that neovim's built-in LSP is enabled and working with intelephense - here is an autocomplete result:
![screenshot_2022-04-13-113854](https://user-images.githubusercontent.com/674995/163136217-69544df6-fe29-4f2a-b121-aef4863b08e0.png)

For clarity I would also ephasize that it **is not a new issue**. It is the way finding items always worked in SpaceVim so far.
The situation did not change with migrating to neovim's built-in LSP - it worked the same way even when LSP was configured in a slightly different way. So **it is a feature request**.

**Comment by wsdjeg** [comment]
the key bindings with `SPC m g` prefix is for gtags layer, and if you want to use lsp key binding, I think it is `g d` and `d D` in normal mode.

**Comment by programmador** [comment]
Wow, it really works! I used wrong keys. Thank You for Your great work!

**Comment by wsdjeg** [comment]
Ok, I will update the doc about php layer

**Comment by wsdjeg** [comment]
`:h SpaceVim-layers-lang-php` has been updated.

**Comment by programmador** [comment]
`g d` - is the right combination to find a function/method.

`g D` - finds variable/attribute definition. For functions/methods it does smth strange: finds other calls of function/method with the same name in the current file. Probably it's supposed to be used for variables/attributes. Though `g d` does the same thing nicely. I'm not sure I can tell that there's some kind of trouble as different LSP's for different languages could behave a bit differently.

**Comment by wsdjeg** [comment]
Please post the debug info `SPC h I`

**Comment by programmador** [comment]
Here it is:
[debug.txt](https://github.com/SpaceVim/SpaceVim/files/8480275/debug.txt)

I just meant I don't know what is `g D` supposed to do. It can find attributes but `g d` also does it perfectly.
`g d` finds everything: methods, classes, attributes.

**Comment by programmador** [comment]
Here are examples of where `g D` can jump.

- Green is right but `g d` can do the same (at least via intelephense)
- Red is senseless

Anyway intelephense is not the only PHP LSP and I don't know whether our current behaviour estimation is fair enough. Mybe for example if I switch to phpactor I'll see smth different.

![screenshot_2022-04-13-125929](https://user-images.githubusercontent.com/674995/163154574-4f9c0627-f36d-4b1b-923e-969478744081.png)
![screenshot_2022-04-13-130016](https://user-images.githubusercontent.com/674995/163154579-8115ec24-b721-41ac-ae35-c71179a1ef51.png)

**Comment by wsdjeg** [comment]
I have added some log, please update spacevim, and press `g D`, you should be able to see following line in runtime log `SPC h L`

```
lsp client: xxxxxxxxxxxxx
```

so what is your lsp client?

and `g D` is to run `go_to_typedef`

**Comment by programmador** [comment]
```
[ SpaceVim ] [13:36:36] [0.356] [  Info ] lsp client: nvim built-in lsp
```

**Comment by programmador** [comment]
> and g D is to run go_to_typedef

This is why I can't understand what is it supposed to do. At least when we are talking about PHP.

For example what should be treated as a type definition **of a function**?

- In Go function signature could have a dedicated type, for example. But it's not obligatory.
- In Rust it should probably point to built-in Fn,FnOnce,FnMut traits but they are built-in so it's also senseless.
- In PHP we could tell that it's just a place where the function signature is. But `g d` does already jump there perfectly.

What about **variable/attribute instance**?

For example given: `private MyClass $myVar`.
If I place cursor to the place where it is used: `$this->myVar = anything` exactly on `myVar` - here's what happens.
Currently `g D` jumps to a place where the variable was declared `private MyClass $myVar` and puts cursor exactly on a dollar sign (thus on the variable itself, not on it's type).

**variable/attribute declaration**?

If In declaration `private MyClass $myVar` I place cursor onto `$myVar` - nothing actually happens for both `g d` and `g D`.
But when called having cursor onto `MyClass` - there's a difference:

- `g d` jumps to a file containing MyClass declaration
- `g D` jumps upper in the same file to a place where MyClass's namespace is imported via PHP's `use` keyword

**Comment by wsdjeg** [comment]
Ok, neovim provides two functions, `vim.lsp.buf.declaration()` and `vim.lsp.buf.definition()`, in `lang#c` layer, if the lsp is enabled:

- `g d` is to run `vim.lsp.buf.definition()`
- `g D` is to run `vim.lsp.buf.declaration()`

maybe we should use same logic in `lang#php` layer.

**Comment by programmador** [comment]
We can try.

**Comment by wsdjeg** [comment]
@programmador I have update the `lang#php` layer, now `g D` is to run jump to declaration function.

**Comment by programmador** [comment]
Interesting. Looks like it has sense now.
The behaviour of `g D` is now exactly the same as of jump-to in Spacemacs:
![screenshot_2022-04-13-142921](https://user-images.githubusercontent.com/674995/163170876-b96679af-b280-4a92-a2a4-2cf2e490ce0e.png)
So it suggests a line either of class signature or of a constructor signature.

Screenshot of Spacemacs with same behaviour I already posted above, if interesting.

So now it seems perfect. Both `g d` and `g D` seem to have sense and they definitely do not do the same.

P.S. It would be also nice to have features like `find implementation`. Should I create a feature request in a new issue for that?

**Comment by wsdjeg** [comment]
Ok. of cause you can open new issue for feature reqeust. :)
