### ISSUE TITLE
errors when loading the lsp layer

### ISSUE THREAD

**Issue by Nick1296** [wsdjeg/SpaceVim#4596]
Hi this is my first issue, so if anything is wrong please tell me!

I noticed a weird behavior in spacevim lately, there are some lua errors when I run :checkhealth and every time I open neovim with the lsp layer enbeld.
The message is unreadable when I open neovim, but whenerver I open a file with `nvim <filename>` the error is clearly readable and it has something to do with lua not indexing correctly an array.
I attached a screenshot and the debug info.
Thanks for looking into this!

## Expected behavior, english is required
neovim loads without errors, and checkhealth reports a the status of the lspconfig plugin.

## The reproduce ways from Vim starting (Required!)
Start neovim with the lsp layer enabled.
To abe able to red the message start neovim with `nvim <filename>`.

## Output of the `
[nvim-debug-info.txt](https://github.com/SpaceVim/SpaceVim/files/8125993/nvim-debug-info.txt)
:SPDebugInfo!`

## Screenshots
![image](https://user-images.githubusercontent.com/26071946/155359744-7e196809-c313-486f-ada4-84b0a6379522.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
I have updated the bundle plugin, please test again, @Nick1296

**Comment by Nick1296** [comment]
Tried to the same approach with the newest Spacevim update and everything seems to work, thanks for the fix!

PS: I had to modify my `enabled_clients` to match the newest neovim lsp client names, but that should be unrelated to spacevim.

**Comment by wsdjeg** [comment]
ok.
