### ISSUE TITLE
Icons does not download with arguments passing to install.sh

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#4598]
May update the file: install.sh

Fonts will be downloaded by this:
curl -sLf https://spacevim.org/install.sh | bash

But not download via:
curl -sLf https://spacevim.org/install.sh | bash -s -- --install vim
Nor:
curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim

and plugins for neovim still download although pass argument: --install vim

I did not use neovim, just use vim. thx.

**Comment by wsdjeg** [comment]
fixed, thank you!
