### ISSUE TITLE
Shift + Tab doesn't seem to work

### ISSUE THREAD

**Issue by EwanValentine** [wsdjeg/SpaceVim#46]
When switching between buffers, Tab works to go forwards, a expected. However, I can't use Shift + Tab as described in the 'Window Management' docs, to go backwards. Thanks in advance!

**Comment by Shougo** [comment]
`nnoremap <S-Tab>` works in your terminal?
I think it depends on the terminal implementation.

**Comment by wsdjeg** [comment]
@EwanValentine It is my fault, fixed.

**Comment by Shougo** [comment]
Oh...

**Comment by wsdjeg** [comment]
But in some terminal, it should not work, it does not work for me in termite.

**Comment by wsdjeg** [comment]
It should be fixed, I have test it.
