### ISSUE TITLE
Use Neogit as git layer plugin

### ISSUE THREAD

**Issue by alk-mandrianarijaona** [wsdjeg/SpaceVim#4608]
[Neogit](https://github.com/TimUntersberger/neogit) is another git plugin that can be used in replacement to Gina or Fugitive. It is described as a Magit clone for Neovim

**Comment by wsdjeg** [comment]
@alk-mandrianarijaona thank you, but I do not use neogit, and PR is welcome.

**Comment by mikaoelitiana** [comment]
This is not relevant for me anymore as I have switched to [lazygit](https://github.com/jesseduffield/lazygit). This issue can be closed now
