### ISSUE TITLE
LspInfo and checkhealth are failing; attempt to call field 'close_preview_autocmd'

### ISSUE THREAD

**Issue by Matmaus** [wsdjeg/SpaceVim#4609]
I am new to SpaceVim and Vim at all. Just installed neovim + SpaceVim but I get blocked on an error with the LSP layer.

Command `:LSPInfo` priints an error
```
E5108: Error executing lua ...ceVim/bundle/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:202: attempt to call field 'close_preview_autocmd' (a nil value)
stack traceback:
        ...ceVim/bundle/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:202: in function <...ceVim/bundle/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:111>
        .../matus/.SpaceVim/bundle/nvim-lspconfig/lua/lspconfig.lua:21: in function <.../matus/.SpaceVim/bundle/nvim-lspconfig/lua/lspconfig.lua:20>
        [string ":lua"]:1: in main c
```

Also `:checkhealth` prints an error
```
lspconfig: require("lspconfig.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "lspconfig" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: attempt to call field 'check' (a nil value)
    stack traceback:
    [string "luaeval()"]:1: in main chunk
```
I found a closed [issue](https://github.com/neovim/nvim-lspconfig/issues/1579) in `nvim-lspconfig` which seems to be my issue. Therefore I tried to update  `nvim-lspconfig` by `:SPUpdate`. But this package is bundled to the SpaceVim version so it can not be updated separately.
Luckily, I found how to "Debug upstream plugins" in [SpaceVim documentation](https://spacevim.org/documentation/#core-pillars). So I just disabled `nvim-lspconfig` and installed it as a custom plugin, just like suggested in the documentation. LSP seems to be working now. 
Would it be possible to update `nvim-lspconfig`?

## Expected behaviour

`:checkhealth` says the LSP layer is working

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.6.1
- SpaceVim version: 2.0.0-dev
- SpaceVim status: e1d68de4

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting

Register LSP layer
```
[[layers]]
name = "lsp"
```

## Output of the `:SPDebugInfo!`

Here is my failing configuration [spacevim-debug-failing.txt](https://github.com/SpaceVim/SpaceVim/files/8237520/spacevim-debug-failing.txt)
Here is my passing configuration [spacevim-debug-success.txt](https://github.com/SpaceVim/SpaceVim/files/8237521/spacevim-debug-success.txt)

## Screenshots

No screenshots.

**Comment by ypli0629** [comment]
Upgrade bundled nvim-lspconfig by yourself

**Comment by wsdjeg** [comment]
@Matmaus fixed, thanks.
