### ISSUE TITLE
Buffer name and status line show unreadable character

### ISSUE THREAD

**Issue by miraclemore** [wsdjeg/SpaceVim#461]
## Expected behavior, english is recommend
Show Buffer name correct and status line correct

## Environment Information
- OS: Ubuntu 16.04.2
- vim version: 8.0
- neovim version: N/A

## The reproduce ways from Vim starting (Required!)
launch long path file, for instance
```
~/.Spacevim.d/init.vim
```
## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
![screenshot from 2017-04-22 18-17-20](https://cloud.githubusercontent.com/assets/3292065/25303562/08e34464-2788-11e7-939b-d9cc9a3fe7c5.png)

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
you should install powerline fonts, read hack-spacevim.

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/DotFiles/tree/master/fonts

**Comment by ghost** [comment]
I have installed powerline fonts, it still can not be displayed.
![screenshot](https://cloud.githubusercontent.com/assets/16219523/25383255/db217dee-29ed-11e7-9086-7eb67120bf5f.jpg)
![screenshot](https://cloud.githubusercontent.com/assets/16219523/25383279/f9dd3e9e-29ed-11e7-9216-4fab55e0b0f5.jpg)

**Comment by wsdjeg** [comment]
as what I see there is no issue in the two pic.

**Comment by ghost** [comment]
Try out this?
![screenshot](https://cloud.githubusercontent.com/assets/16219523/25386163/fa34fb06-29f8-11e7-8547-c4bfeb7fe2f7.jpg)

**Comment by wsdjeg** [comment]
you mean the char after `utf-8`? you need install unicode font in arch.

**Comment by wsdjeg** [comment]
here is the font I have installed in arch
```
✔ wsdjeg:DotFiles [ master | ✚ 1 ] ➭ cat package_list.txt | grep font
adobe-source-code-pro-fonts
adobe-source-han-sans-cn-fonts
font-bh-ttf
fontconfig
fontsproto
libfontenc
libxfont
libxfont2
nerd-fonts-source-code-pro
noto-fonts
noto-fonts-cjk
noto-fonts-emoji
opendesktop-fonts
wqy-bitmapfont
xorg-font-util
xorg-font-utils
xorg-fonts-alias
xorg-fonts-encodings
xorg-fonts-misc
xorg-mkfontdir
xorg-mkfontscale
```

**Comment by wsdjeg** [comment]
![2017-04-25-20 56 30](https://cloud.githubusercontent.com/assets/13142418/25386475/14bc9c1c-29fa-11e7-86dd-fb5e1aff1126.png)

**Comment by ghost** [comment]
> you mean the char after utf-8? you need install unicode font in arch.

Yes.

I have installed your packages, it does not work...

**Comment by wsdjeg** [comment]
sorry, I do not know why, I think your terminal font is wrong.

**Comment by ghost** [comment]
okay, but thanks.

**Comment by ghost** [comment]
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts
I use this font, It works!
