### ISSUE TITLE
Neovim Built-in LSP PHP: no autocomplete for names intersecting with current class

### ISSUE THREAD

**Issue by programmador** [wsdjeg/SpaceVim#4614]
Built-in LSP does not provide autocomplete for names containing parts of other names.
For example why developing `AbcdeTest` You cannot import (by autocomplete) `Abcde`.
You can either import `AbcdeTest` (which is useless) or any sufficiently distinct name, for example `Zyxwv`

The issue arose few months ago after migrating Spacevim to built-in Neovim LSP.
I have no idea whether it is a Spacevim issue or it should be addressed to Neovim developers.

## Expected behavior, english is required

LSP should provide all available completion options

## The reproduce ways from Vim starting (Required!)

1. Configure Neovim + Spacevim + built-in Neovim LSP + Intelephense (PHP) [init.toml.txt](https://github.com/SpaceVim/SpaceVim/files/8371514/init.toml.txt)
2. Open any class containing Suffix (ex: AbcdeTest)
3. Try to import any symbol containing the same name without suffix (ex. Abcde)

## Screenshots

![screenshot_2022-03-29-154139](https://user-images.githubusercontent.com/674995/160614079-37be5d31-c55b-4fb4-8971-0f19f75757d3.png)
![screenshot_2022-03-29-154302](https://user-images.githubusercontent.com/674995/160614087-1e095913-d9fa-40ff-880f-9896fadab0ac.png)

**Comment by wsdjeg** [comment]
The first picture is not lsp completion, it is buffer words.

**Comment by programmador** [comment]
So it looks like either "buffer words" disables lsp or lsp stops working in abovementioned circumstances thus enabling "buffer words" as a fallback.

**Comment by programmador** [comment]
Here is even more interesting illustration as it's more isolated.

Here we already have similar name which is suggested from "buffer words". The issue is that LSP seems to be accidently disabled. Pay attention also to a non-capital first letters in a suggestion: of course it suggests just a word, not a class.
![screenshot_2022-04-13-152216](https://user-images.githubusercontent.com/674995/163179266-d4397eea-d778-4aee-aeb9-ecebf399ab53.png)

And here is the same place but the behaviour is different - LSP suggests successfully. Because the variable is renamed to a non-similar name beforehand (red color).
![screenshot_2022-04-13-152242](https://user-images.githubusercontent.com/674995/163179268-7d1d6da6-9c50-4d7f-a88c-ddb9c38bdc64.png)

**Comment by wsdjeg** [comment]
@programmador In current version of spacevim, use nvim-cmp by default. can you reproduce this issue now?
