### ISSUE TITLE
Install SourceCodePro Nerd Font Mono in install.sh

### ISSUE THREAD

**Issue by dereckson** [wsdjeg/SpaceVim#4616]
## Expected behavior, english is required
When using https://spacevim.org/install.sh (without --no-fonts), to have all the useful fonts installed.

It installs some fonts, but not the one recommended in the documentation to use, SourceCodePro Nerd Font Mono.

## The reproduce ways from Vim starting (Required!)
$ curl -sLf https://spacevim.org/install.sh | bash
$ ls $HOME/.local/share/fonts/*.ttf

## Output of the `:SPDebugInfo!`
n/a

## Screenshots
```
$ ls $HOME/.local/share/fonts/*.ttf
'DejaVu Sans Mono Bold for Powerline.ttf'          'DejaVu Sans Mono for Powerline.ttf'           devicons.ttf   symbol.ttf                                                 wingding.ttf   WINGDNG3.ttf
'DejaVu Sans Mono Bold Oblique for Powerline.ttf'  'DejaVu Sans Mono Oblique for Powerline.ttf'   mtextra.ttf   'Ubuntu Mono derivative Powerline Nerd Font Complete.ttf'   WINGDNG2.ttf
```

**Comment by wsdjeg** [comment]
Ok, this is an old issue of the installation script, thanks.
