### ISSUE TITLE
directory icon is not showing

### ISSUE THREAD

**Issue by lyr-2000** [wsdjeg/SpaceVim#4617]
## Environment Information

ubuntu 20.04
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

## Screenshots

![image](https://user-images.githubusercontent.com/46613910/161482850-ea2ff3b2-b5ec-435f-9796-3d3131ed8e03.png)

**Comment by wsdjeg** [comment]
This is issue with fout setting of your terminal, you can use [nerd-fonts](https://www.nerdfonts.com/).
