### ISSUE TITLE
Improve PHP layer documentation to explain how to use LSP or ctags or gtags

### ISSUE THREAD

**Issue by dereckson** [wsdjeg/SpaceVim#4619]
**Is your feature request related to a problem? Please describe.**
Current state of the documentation:
* https://spacevim.org/use-vim-as-a-php-ide/ explains to install the gtags layer
* https://spacevim.org/layers/gtags/ recommends the installation of universal ctags

Question not answered by the documentation:
* once that's installed what to be able to use ctrl + clic working?
It seems to be willing to use "tags" file, the one we can create with `uctags -R`, but where to define the location of the tags file? `set tags+=tags,/` doesn't seem to work -> ctrl + clic still reports E433: No tags file                                                                                                                                                                             

Behavior not consistent between the documentation and the behavior:
* gtags layer documentation offers to create a tag database with `SPC m g c`, that part works well
* the search for def/reference or jump file doesn't work: `Error: global command failed. command line: global --result=ctags-x -qde 'BasePayloadAnalyzer'` (the last one is a class name)`

But if in a shell, from the folder I've opened nvim, I write that exact command reported as failed, I've results and a success code of 0:

```
$ global --result=ctags-x -qde 'BasePayloadAnalyzer'  
BasePayloadAnalyzer   10 app/Analyzers/BasePayloadAnalyzer.php abstract class BasePayloadAnalyzer {

$ echo $?
0
```

Other issues about PHP speak about LSP, and in a recent commit you added support for Intelephense or phpactor, documentation is silent about them.

**Describe the solution you'd like**
An example of how to configure a PHP project so we've tags and can use them in a PHP project.

* To be able to do ctrl + clic and something useful happens, a jump to the definition being the less surprising action.

**Describe alternatives you've considered**
**Additional context**
See below.

**Comment by wsdjeg** [comment]
Hi @dereckson I have test `<C-RightMouse>` and `ctrl-]` in rust project. and it works well. I do not know why it does not work for php. make sure the ctags has been generated for current project. the tags is generated automatically when you save a file.

I have test with https://github.com/taoso/tagbar-markdown, and I get `E426: tag not found: matches`


The tags file is generated automatically, the path is: `C:\Users\wsdjeg\.cache\SpaceVim\tags\d__repos_tagbar-markdown_\tags`

```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_FILESEP	slash	/slash or backslash/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PATTERN_LENGTH_LIMIT	96	/0 for no limit/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	5.9.0	/952bd1e9/
Install	d:/repos/tagbar-markdown/README.md	/^### Install$/;"	S	chapter:tagbar markdown extension
Intro	d:/repos/tagbar-markdown/README.md	/^### Intro$/;"	S	chapter:tagbar markdown extension
MDAgenda	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^command! -nargs=0 MDAgenda call s:insertAgenda()$/;"	c
Screenshot	d:/repos/tagbar-markdown/README.md	/^### Screenshot$/;"	S	chapter:tagbar markdown extension
g:tagbar_type_ghmarkdown	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^let g:tagbar_type_ghmarkdown = g:tagbar_type_markdown$/;"	v
g:tagbar_type_markdown	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^	let g:tagbar_type_markdown = {$/;"	v
g:tagbar_type_rmd	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^let g:tagbar_type_rmd = g:tagbar_type_markdown$/;"	v
s:bin_path	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^let s:bin_path = expand('<sfile>:p:h:h').'\/bin\/mdctags'$/;"	v
s:doInsertAgenda	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^function! s:doInsertAgenda(status, response)$/;"	f
s:insertAgenda	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^function! s:insertAgenda()$/;"	f
s:save_cpo	d:/repos/tagbar-markdown/plugin/markdown_tagbar.vim	/^let s:save_cpo = &cpo$/;"	v
tagbar markdown extension	d:/repos/tagbar-markdown/README.md	/^# tagbar markdown extension$/;"	c
```


```
ctags --version
```

```
Universal Ctags 5.9.0(952bd1e9), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Oct 11 2020, 00:07:22
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +unix-path-separator, +iconv, +option-directory, +xpath, +json, +inter
active, +yaml, +case-insensitive-filenames, +packcc
```

**Comment by wsdjeg** [comment]
Ok, rename `bin/mdctags` to `bin/mdctags.php` fix this issue. 

https://github.com/universal-ctags/ctags/issues/3324

**Comment by wsdjeg** [comment]
@dereckson I have update ctags plugin, currentlly it should works well.

**Comment by dereckson** [comment]
By the way, speaking about ctags, here's a complication on FreeBSD:

* /usr/bin/ctags is an historical ctags, not relevant here
* /usr/bin/local/ctags is the path for exuberant ctags
* /usr/bin/local/uctags is the path for universal ctags, as the port maintainer decided to avoid naming conflict with exuberant ctags

Is there any way to configure the defautl ctags path, so we can help it to call the right one (/usr/bin/local/uctags for example on a FreeBSD machine)? Or perhaps a search method trying several paths in cascade?

And something we could also try to document (we because I'm interested to improve that part of the documentation if I've all the pieces of the puzzle): what's the role of GNU global in that tagging work?

**Comment by dereckson** [comment]
Cool the PHP doc update, thanks :)

**Comment by wsdjeg** [comment]
> Is there any way to configure the defautl ctags path, so we can help it to call the right one (/usr/bin/local/uctags for example on a FreeBSD machine)? Or perhaps a search method trying several paths in cascade?

please read `:h SpaceVim-layers-gtags`, you can use  `ctags_bin` layer option.

**Comment by wsdjeg** [comment]
> what's the role of GNU global in that tagging work?

GNU global provides more key bindings,  you can find references too.
