### ISSUE TITLE
Document how to get tagbar working with Rust

### ISSUE THREAD

**Issue by dereckson** [wsdjeg/SpaceVim#4620]
**Is your feature request related to a problem? Please describe.**
When opening a Rust project, then a .rs file, the Tagbar is empty.

**Describe the solution you'd like**
Explain how to fill Tagbar

**Describe alternatives you've considered**
`uctags -R` in the project root to provide a tags file doesn't change anything (well, probably not relevant as other languages don't need that step to fill the tagbar)

**Additional context**
A configuration for that exists: https://github.com/rust-lang/rust.vim/blob/master/ftplugin/rust/tagbar.vim

**Comment by wsdjeg** [comment]
![image](https://user-images.githubusercontent.com/13142418/161669219-b992c97a-b7d4-44e9-86ec-1b44296a20fb.png)

you need to load the rust layer, and it works well for me.

**Comment by dereckson** [comment]
Ah good news it works on your Windows computer.

Yet, the goal is to explain how to make it working on a new genuine SpaceVim installation.

**Comment by wsdjeg** [comment]
What is needed to updated for this issue? If you load the `lang#rust` layer, tagbar should support rust by default. and of cause you need to install https://github.com/universal-ctags/ctags

**Comment by wsdjeg** [comment]
![image](https://user-images.githubusercontent.com/13142418/164651688-88f59d3e-9bd7-46e7-bbc0-3e2657dfa8f1.png)
