### ISSUE TITLE
Should I modify 'init.vim' to `set formatoptions-=cro`?

### ISSUE THREAD

**Issue by archibate** [wsdjeg/SpaceVim#4626]
**Is your feature request related to a problem? Please describe.**

I added `set formatoptions-=cro` to `~/.config/nvim/init.vim`, but it seems doesn't work.
Looking around the documentation, I cannot find how to set `formatoptions` in `init.toml`.
Maybe we could add a `~/.config/nvim/extra_init.vim` for users to add their custom tweaks other than `toml`?

**Describe the solution you'd like**

Can I use some file like `~/config/nvim/custom_init.vim` to load my custom settings?

**Describe alternatives you've considered**

Maybe I could add `alias nvim='nvim -c "set formatoptions-=cro"'` to `~/.bashrc`...

**Additional context**

**Comment by archibate** [comment]
Here is the content of `~/.SpaceVim/init.vim`:
```bash
"=============================================================================
" init.vim --- Entry file for neovim
" Copyright (c) 2016-2022 Wang Shidong & Contributors
" Author: Wang Shidong < wsdjeg@outlook.com >
" URL: https://spacevim.org
" License: GPLv3
"=============================================================================

execute 'source' fnamemodify(expand('<sfile>'), ':h').'/main.vim'

set formatoptions-=cro
set ts=4 sts=4 sw=4 et
```

**Comment by wsdjeg** [comment]
you can use bootstrap_after function, please read https://spacevim.org/documentation/#bootstrap-functions
