### ISSUE TITLE
Basic api for plugin develop

### ISSUE THREAD

**Issue by L-stt** [wsdjeg/SpaceVim#463]
@wsdjeg 
    I do use spacevim and space-vim, but I think SpaceVim's public api is a great idea. I will try to work on some basic APIs, Any api request?
    BTW space-vim has better file structure，and would you like to improve the structure of SpaceVim? I know this will not have any impact on the user, but is conducive to other developers to join。
    
@Gabirel
    Thanks for your hack-spacevim, nice work! would you like to write some thing about SpaceVim's api for plugin developer?

**Comment by Gabirel** [comment]
Sure,thanks for your suggestion.I'll write it later when I'm available.

**Comment by wsdjeg** [comment]
I do not use space-vim, and I do not like the file structure of `+layers`. vim support autoload feature, so you can split it.

for example:
if you want to creat a foo layer, you can creat these files:

`SpaceVim/layer/foo.vim`
```viml
fu! SpaceVim#layer#foo#plugins()
    return [
        \ ['foo/foo'],
        \ ]
endf

fu! SpaceVim#layer#foo#config()
     call SpaceVim#layer#foo#section#test()
endf
```
`SpaceVim/layer/foo/section.vim`
```viml
fu! SpaceVim#layer#foo#section#test()
endf
```

**Comment by L-stt** [comment]
@wsdjeg  got it, hmm, it is better.
