### ISSUE TITLE
bootstrap_before called twice

### ISSUE THREAD

**Issue by OnkV** [wsdjeg/SpaceVim#4641]
SpaceVim: 2.0.0-dev (clean installation)
OS: Debian 11

Vim:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428

```
% cat ~/.SpaceVim.d/autoload/myspacevim.vim

function! myspacevim#before() abort
        echo "before"
endfunction

function! myspacevim#after() abort
        echo "after"
endfunction
```
```
% cat ~/.SpaceVim.d/init.toml | grep bootstrap
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
```
`echo "before"` is called twice with SpaceVim 2.0.0-dev.  It's called once with SpaceVim 1.9.0.

**Comment by wsdjeg** [comment]
This is a bug, I think you are starting vim form `~/`. so spacevim found the global cofig `~/.SpaceVim.d/init.toml` and local config `./.SpaceVim.d/init.toml` that is why the bootstrap function is called twice.

**Comment by OnkV** [comment]
Yes, that's correct.  It only happens when `$HOME` is my cwd.
