### ISSUE TITLE
error when installing spacevim on windows

### ISSUE THREAD

**Issue by zhaob1n** [wsdjeg/SpaceVim#4663]
I have neovim preinstalled and when I try to install space vim, I get [ERROR] Unable to find 'vim.exe' in your PATH. Sure I have only nvim.exe in my path, but doesn't that suffice for spacevim?

**Comment by wsdjeg** [comment]
@hzb-ykpcx How did you install spacevim?

**Comment by zhaob1n** [comment]
> @hzb-ykpcx How did you install spacevim?
by running the install.cmd

**Comment by wsdjeg** [comment]
Ok, thanks
