### ISSUE TITLE
Errors after installation

### ISSUE THREAD

**Issue by JuanCaicedo** [wsdjeg/SpaceVim#467]
## Expected behavior, english is recommend

After following installation guide, running `vim` should open without errors.

## Environment Information
- OS: OSX 10.12.4 
- vim version: 7.4
- neovim version:

## The reproduce ways from Vim starting (Required!)

- I was using OSX's installation of vim with no modifications before installing SpaceVim

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

```
Error detected while processing VimEnter Auto commands for "*":
E117: Unknown function: timer_start
Press ENTER or type command to continue
```

Let me know if I can provide more information 😃

**Comment by Shougo** [comment]
Hm.  SpaceVim uses Vim 8.0 feature timer_start().
It should be fixed.

**Comment by wsdjeg** [comment]
oh, sorry, we should check if `+timer ` is supported.
