### ISSUE TITLE
Easy customization of file-specific syntax highlighting

### ISSUE THREAD

**Issue by johngilbert2000** [wsdjeg/SpaceVim#4671]
**Is your feature request related to a problem? Please describe.**
I would like to [set persistent syntax highlighting](https://stackoverflow.com/questions/11666170/persistent-set-syntax-for-a-given-filetype) for custom file types, but editing `.SpaceVim/vimrc` or the bootstrapping function in `.SpaceVim/autoload/myspacevim.vim` did not allow me to `set syntax=...` for specific file extensions.

**Describe the solution you'd like**
It would be nice if `set syntax` or `set filetype` could be persistently declared in `.SpaceVim.d/init.toml` for specific filetypes.

Something like this could work nicely:
```
[[ extensions ]]
ext = ".cr"
syntax = "ruby"
```

**Comment by wsdjeg** [comment]
Hi @johngilbert2000, sorry for late reply, did you have a try with adding following script into bootstrap function?

```
au BufNewFile,BufRead *.cr                      set syntax=ruby
```
