### ISSUE TITLE
Support of CMake

### ISSUE THREAD

**Issue by zchrissirhcz** [wsdjeg/SpaceVim#4675]
**CMake**

For modern C/C++ projects that have more than 1 source/header file, most of them are organized with CMake. i.e. provide a CMakeLists.txt, and may optionally call some xxx.cmake script files. It will be more convenient if spacevim provide cmake (or say, provide better) support.

CMakeLists.txt and xxx.cmake are both using "the CMake language".

**Which platform does the language support?**

- [x] Linux
- [x] MacOS
- [x] Windows
- [x] And more than the aforementioned 3 platforms: Android NDK, iOS, arm linux, qnx, ... if you have an C/C++ compiler, then you have CMake support.

**Any suggest vim plugins for this language?**

There is already syntax highlight for an opened CMakeLists.txt. That's fine, but not enough.

Just like when we have setup the `lang#c`, we type `std::cout` then there's hint for `<<` or some other completion hints, we also need "hints" for CMake:
- the builtin commands completion (think of them as "printf" for C)
- the builtin variables completion (think of them as "INT_MAX" macros for C)
- the variables we have just typed in previous lines

**Additional context**
Just like vscode's cmake plugin (author: twxs)
<img width="592" alt="截屏2022-05-21 23 02 08" src="https://user-images.githubusercontent.com/3831847/169657373-3afbd66a-15ff-4557-a104-ef09c5c76cbb.png">

**Comment by wsdjeg** [comment]
there are three plugins I just found in github:

- https://github.com/cdelledonne/vim-cmake
- https://github.com/vhdirk/vim-cmake
- https://github.com/ilyachur/cmake4vim

**Comment by zchrissirhcz** [comment]
I previously use this plugin: https://github.com/pboettch/vim-cmake-syntax

**Comment by zchrissirhcz** [comment]
The mentioned 3 plugins are cool, would be required by some people, especially "I don't edit CMakeLists.txt, I just build and compile and install".

There are still some people like me, edit CMakeLists.txt everyday, and syntax completion seems more required. 

Personally, I don't use commands like `CMakeBuild` in VSCode, also don't use in Vim, because I often pass more optional arguments to cmake commands, e.g.:
```
cmake -DCMAKE_INSTALL_PREFIX=~/artifacts/xxx/x.y.z -DCMAKE_BUILD_TYPE=Release -DWITH_NCNN=ON ..
cmake --build .  -j2
cmake --install . --config Release
```

**Comment by zchrissirhcz** [comment]
I forgot to mention, the plugin https://github.com/pboettch/vim-cmake-syntax, is the official cmake download page suggested:  
https://cmake.org/download

<img width="653" alt="截屏2022-05-21 23 50 23" src="https://user-images.githubusercontent.com/3831847/169659359-14e87b34-af57-4bce-8442-598ac2d45b2c.png">

**Comment by wsdjeg** [comment]
@zchrissirhcz the `lang#cmake` layer has been merged. and currently only syntax highlight and lsp is enabled, if you want to use lsp for cmake, you need to install cmake-language-server. The next step, I will implement a `:Cmake` command, wich should support run cmake command in vim. such as:

```
:Cmake --install
:Cmake --build .  -j2
```

**Comment by zchrissirhcz** [comment]
Cool! Thanks for this added feature, I'll have a try when I'm free.

BTW, the documentation is very clear, this really helps me.

**Comment by wsdjeg** [comment]
@zchrissirhcz the `:Cmake` command has been added, and you can use `:Cmake --build . -j2` now. It will run command within code runner.

**Comment by zchrissirhcz** [comment]
@wsdjeg Thanks for adding this `:Cmake` command, and I've tested it, it works.

For the aforementioned LSP support for CMake in SpaceVim, I have trouble using it. The configure file:
```
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp",
    "cmake"
  ]
  [layers.override_cmd]
    c = ["clangd"]

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#cmake"
```

After saving the configure file, in a new opened terminal, do
```
nvim CMakeLists.txt
```
and see warning:
<img width="649" alt="截屏2022-05-25 22 32 19" src="https://user-images.githubusercontent.com/3831847/170288011-1361d355-cade-4ff4-ab36-86aa793e6ba5.png">

And the completion seems not working, I expect giving hints "add_executable" for "add_exec":
<img width="648" alt="截屏2022-05-25 22 35 59" src="https://user-images.githubusercontent.com/3831847/170288300-2c3846d9-9b14-472a-877b-4bc4c13ed9cd.png">


Do I have to change some configuration, and if so, how?

**Comment by zchrissirhcz** [comment]
I've checked that both `cmake` and `clangd` are in PATH:
<img width="463" alt="截屏2022-05-25 22 38 39" src="https://user-images.githubusercontent.com/3831847/170288906-3f3dbead-568a-49d2-b56c-c55aae7c81ee.png">

<img width="463" alt="截屏2022-05-25 22 38 50" src="https://user-images.githubusercontent.com/3831847/170288921-0d009cd5-c394-4fd8-a04c-88cefa3050a9.png">
