### ISSUE TITLE
Adding  project_rooter_patterns = ['node_modules/'] to [options] doesn't exclude the node_modules folder from FlyGrep searches

### ISSUE THREAD

**Issue by ramuyk** [wsdjeg/SpaceVim#4678]
Hi, I'm not completely sure if it's a bug or if I'm missing some detail... But checking the [Advanced Usage ](https://spacevim.org/documentation/#advanced-usage)on the documentation it says that we can make the project ignore certain folders. As I'm working with a node.js project, I want to ignore the `node_modules` folder. So I wrote the following in my `init.toml` file:

```
[options]
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'node_modules/']
```

However, when I try to do some searches with `SPC s p` it still takes a long time to search words because it's also searching inside the `node_modules` folder.

## Expected behavior

It should completely ignore the `node_modules` folder in `SPC s p` searches.

## The reproduce ways from Vim starting

1. Add the following to the `init.toml` file:

```
[options]
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'node_modules/']
```

2. Make a search with `SPC s p` and it'll also search inside the `node_modules` folder.

**Comment by wsdjeg** [comment]
This is not for flygrep, spacevim use this patterns to find project root path. if you want to ignore path, checkout https://spacevim.org/documentation/#custom-searching-tool

for example:

```
    let profile = SpaceVim#mapping#search#getprofile('rg')
    let default_opt = profile.default_opts + ['-g', '!node_modules']
    call SpaceVim#mapping#search#profile({'rg' : {'default_opts' : default_opt}})
```

**Comment by ramuyk** [comment]
Thanks for the response,

Do you mean creating a file in `~/.SpaceVim/autoload/myspacevim.vim` with the following content:

```
function! myspacevim#before() abort
  let profile = SpaceVim#mapping#search#getprofile('rg')
  let default_opt = profile.default_opts + ['-g', '!node_modules']
  call SpaceVim#mapping#search#profile({'rg' : {'default_opts' : default_opt}})
endfunction
```

I'm probably still missing something because flygrep is still searching inside the `node_modules` folder...

**Comment by wsdjeg** [comment]
Use `SPC h L` to checkout the runtime log, you will find the flygrep searching command.
