### ISSUE TITLE
Dart/Flutter LSP configuration options are not respected

### ISSUE THREAD

**Issue by programmador** [wsdjeg/SpaceVim#4679]
I'm using Neovim with it's build-in LSP.
So it seems like an old option `[layers.override_cmd]` is not respected for my configuration.
This causes troubles while trying to replace Dart SDK with Flutter SDK. Especially the dart binary itself.

SpaceVim calls system's Dart binary which version (probably) differs from a Dart binary version in Flutter SDK in my case.
Which consequently causes an error:
```
[ERROR][2022-05-22 15:00:20] .../vim/lsp/rpc.lua:420    "rpc"   "dart"  "stderr"        "Wrong full snapshot version, expected '1441d6b13b8623fa7fbf61433abebd31' found 'd56742caf7b3b3f4bd2df93a9bbb5503'\n"
```
Probably SpaceVim tries to call LSP server this way:
```
dart /opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
```
In this case this is the wrong "dart":
```
$ whereis dart
dart: /usr/bin/dart /opt/dart-sdk/bin/dart /opt/flutter/bin/dart
```
because `/usr/bin/dart` is a symlink to `/opt/dart-sdk/bin/dart`

## Expected behavior, english is required
LSP should be called this way
```
/opt/flutter/bin/cache/dart-sdk/bin/dart /opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
```

## The reproduce ways from Vim starting (Required!)
Just open any dart file inside of a flutter project

## Config
```
[[layers]]
    name = "lsp"
    enabled_clients = [
        'dartls',
        ...
    ]
    filetypes = [
        "dart",
        ...
    ]
    [layers.override_cmd]
      dart = [
          "/opt/flutter/bin/cache/dart-sdk/bin/dart",
          "/opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot",
          "--lsp"
      ]
      ...

[[layers]]
    name = "lang#dart"
    dart_sdk_path = "/opt/flutter/bin/cache/dart-sdk/"
```

As You see I've also found `dart_sdk_path` option in the docs but it also does nothing.
Looks like my config is now a mixture of an old "classic" LSP config and vim's built-in LSP config. But how to force built-in LSP to use custom paths? BTW the question is actual for any LSP+language.

Though... If I completely remove the `override_cmd` section - SpaceVim blaims it cannot execute LSP. So it seems like it embraces the config but just does not respect it's first argument (path to dart binary).

Obviously removing dart from the system and adding `/opt/flutter/bin` to `$PATH` helped as a workaround.

## Output of the `:SPDebugInfo!`
[debug-info.txt](https://github.com/SpaceVim/SpaceVim/files/8750075/debug-info.txt)

**Comment by wsdjeg** [comment]
hello, I think the default command is:

```
['dart', 'language-server', '--protocol=lsp']
```

**Comment by programmador** [comment]
Exactly.
Actually with this config
```
[[layers]]
    name = "lsp"
    enabled_clients = [
        ...
        'tsserver'
        ...
    ]
    filetypes = [
        ...
        "dart",
        ...
    ]
    [layers.override_client_cmds]
      ...
      dartls = [
          "/opt/flutter/bin/cache/dart-sdk/bin/dart",
          "/opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot",
          "--lsp"
      ]
      ...
...
[[layers]]
    name = "lang#dart"
    dart_sdk_path = "/opt/flutter/bin/cache/dart-sdk/"

```

and even with distro's `dart` package installed along with it's flutter variant:
```
> whereis dart
dart: /usr/bin/dart /opt/dart-sdk/bin/dart /opt/flutter/bin/dart
```

I'm able to open flutter project and `:LspInfo` tells the correct binary path:
```
/opt/flutter/bin/cache/dart-sdk/bin/dart
```

but anyway just after SpaceVim startup before opening any files I get the next message:

```
[ SpaceVim ] [15:58:17] [0.147] [ Warn  ] Failed to enable lsp for dart, dart_language_server is not executable!
```

No matter whether non-flutter dart is the only one in the system or installed alongside with "normal" dart.

**Comment by wsdjeg** [comment]
The error comes from [here](https://github.com/SpaceVim/SpaceVim/blob/1629ba4c92473f17de61246ee963730b9771ba70/autoload/SpaceVim/layers/lsp.vim#L292), and I think it is a bug. If `enabed_clients` is used, we should ignore `filetypes`.

**Comment by wsdjeg** [comment]
@programmador I have updated the lsp layer, please use following setting:

```
[[layers]]
    name = 'lsp'
    enabled_clients = ['vimls', 'dartls']
    [layers.override_client_cmds]
    dartls = [
         "/opt/flutter/bin/cache/dart-sdk/bin/dart",
         "/opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot",
         "--lsp"
    ]
```

**Comment by programmador** [comment]
Thank's a lot! Now there are no errors and lsp is working with abovementioned config
