### ISSUE TITLE
Dart/Flutter Autocomplete not working in Neovim's built-in LSP

### ISSUE THREAD

**Issue by programmador** [wsdjeg/SpaceVim#4680]
Unable to select LSP's autocomplete suggestions. Trying to push `arrows` or `tab` just closes the suggestion list. Neither `ctrl+j` or `ctrl+k` do work.

BTW "Text" suggestions completely disable "LSP" ones. I have already described it in #4614 - it currently makes autocomplete completely unusable in SpaceVim+Neovim. Here's how it looks like. You see here only `Text`. Instead You should see either `Constructor` or maybe both. That bug is definitely language-agnostic

![screenshot_2022-05-22-153911](https://user-images.githubusercontent.com/674995/169695663-8a6bdd99-7c97-49ee-b705-09acb6007366.png)

## Expected behavior, english is required
Suggestions should be selectable

## The reproduce ways from Vim starting (Required!)
Open any flutter project, type class/constructor name and open the bracket

## Output of the `:SPDebugInfo!`
[debug-info.txt](https://github.com/SpaceVim/SpaceVim/files/8750073/debug-info.txt)

## Screenshots
![screenshot_2022-05-22-153530](https://user-images.githubusercontent.com/674995/169695506-a8a5c281-9a84-4b8d-9060-bd761cae45ad.png)

**Comment by wsdjeg** [comment]
please following the issue templete, debug info is needed.

**Comment by programmador** [comment]
Added.

**Comment by wsdjeg** [comment]
fixed.
