### ISSUE TITLE
restart-vim-resume-layouts(TODO) not working

### ISSUE THREAD

**Issue by Chuanhuan** [wsdjeg/SpaceVim#4682]
I try to use "restart-vim-resume-layouts(TODO)"  by pressing r then exit all windows.
It didn't work like what I expect.
By checking `spc a o` "open-todo-manager" and I couldn't find any items as well. 

Does anyone know how to resume the windows which last time opened?

**Comment by wsdjeg** [comment]
This key binding has not been implemented, and there is `TODO` flag on it.
