### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by ixodie** [wsdjeg/SpaceVim#469]
Error detected while processing function SpaceVim#commands#install_plugin[4]..Sp
aceVim#plugins#manager#install[36]..<SNR>66_install[19]..12[43]..<SNR>67_systeml
ist:
line    3:
E706: Variable type mismatch for: cmd

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 6 2016 12:07:41)
Included patches: 1-898, 8056
Compiled by root@apple.com

**Comment by wsdjeg** [comment]
@ixodie I can not reproduce in arch, I think you should make sure you vim support py and job.
