### ISSUE TITLE
Spacevim-related files still lingers after uninstallation

### ISSUE THREAD

**Issue by Ross-Li** [wsdjeg/SpaceVim#4703]
## Expected behavior, english is required
The spacevim-related files in `~/.config/nvim` should be be removed after running the uninstallation command 

## The reproduce ways from Vim starting (Required!)
See the screenshot

## Output of the `:SPDebugInfo!`
See the screenshot
As the picture shows, some of the spacevim-related files such as `README.md` and `README.cn.md` still lingers. It is difficult for me to distinguish which files are spacevim-vim related files and which are original neovim-related files. 
As the second picture shows, the `.SpaceVim` folder still lingers after uninstallation.

## Screenshots
![image](https://user-images.githubusercontent.com/61273074/189482188-2be01151-7064-4110-bd11-6bc57763fc7e.png)
![image](https://user-images.githubusercontent.com/61273074/189482468-8868dc53-6784-4404-b830-f107f44ad581.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
I do not know why, the uninstall script is very simple, you can check it:

https://github.com/SpaceVim/SpaceVim/blob/master/docs/install.sh#L195-L225

**Comment by Ross-Li** [comment]
I am not very familiar with bash script, I will look into it when I learn more about it.
