### ISSUE TITLE
ternjs not loaded

### ISSUE THREAD

**Issue by soomtong** [wsdjeg/SpaceVim#471]
## Expected behavior, english is recommend

Clean installed and open some javascript file (.js)
some error message in underline like 'can't open or load tern#enable'

## Environment Information
- OS: Linux Mint (Ubuntu 16.04 based)
- vim version: 8.0
- neovim version:

## Temporary Solution 

edit `tern_for_vim` to  `tern` in `lang/javascript.vim`

```
$ vi .SpaceVim/autoload/SpaceVim/layers/lang/javascript.vim
```
in this file line 7 (at this version of spacevim)
```
call add(plugins,['ternjs/tern', ...
```
save and re init vim then vim update ternjs plugin and we can see install progress.
clear.

thanks.

moderators, this issue can close anytime.

**Comment by wsdjeg** [comment]
`call SpaceVim#layers#load('lang#javascript')`

by default we use ternjs/tern_for_vim.
