### ISSUE TITLE
cannot find  ~/.SpaceVim.d/ directory after install

### ISSUE THREAD

**Issue by chaohi** [wsdjeg/SpaceVim#4711]
website quick start [guide](https://spacevim.org/quick-start-guide/) document says "The default configuration file of SpaceVim is ~/.SpaceVim.d/init.toml". but only .SpaceVim directory exist after install，and init.toml conf file is not found。

**Comment by wsdjeg** [comment]
This file will be generated when you first start VIm.

https://spacevim.org/documentation/#custom-configuration
