### ISSUE TITLE
不能直接打开文件, Startify 总会启动并取代打开的文件 diff的时候更惨不忍睹

### ISSUE THREAD

**Issue by onenew** [wsdjeg/SpaceVim#4712]
https://github.com/SpaceVim/SpaceVim/blob/79c5576fd80647eefdacbd04a06c0621ef46720a/autoload/SpaceVim.vim#L1592-L1599

 if index(v:argv, '--embed') !=# -1 
           \ _||_ len(v:argv) == 1 

应该是
 if index(v:argv, '--embed') !=# -1 
           \ **&&**  len(argv()) == 0

**Comment by wsdjeg** [comment]
same as #4706
