### ISSUE TITLE
SpaceVim freezes after pushing Leader P

### ISSUE THREAD

**Issue by asarchami** [wsdjeg/SpaceVim#4720]
After using `Leader Y` to copy to clipboard neovim freezes and nothing happens. selected text gets copied to the clipboard
## Expected behavior, english is required
Selected text gets cleared and normal function continues
## The reproduce ways from Vim starting (Required!)
select a text and pres `Leader Y`
## Screenshots
![image](https://user-images.githubusercontent.com/58091/194953328-e4877b38-afa1-4238-932f-f5f073b114b6.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by asarchami** [comment]
I found a workaround? After the freeze I can unfreeze using Ctrl + c. Not sure why this is happening

**Comment by wsdjeg** [comment]
What is the result of `:map \p`?

**Comment by asarchami** [comment]
![image](https://user-images.githubusercontent.com/58091/194984975-2ce478ce-7414-42d4-99dc-f4fcb616a585.png)

**Comment by wsdjeg** [comment]
ok, maybe `clipboard#paste('p')` is slow. it use `system()` function.

**Comment by asarchami** [comment]
Weird. Using :set clipboard:unnamedplus just works. I'll use that instead. Thanks

**Comment by wsdjeg** [comment]
please update spacevim, I have add debug log for clipboard. use `SPC h L`, you will see something like:

```
[ clipboard ] [10:49:28] [3.766] [ Info  ] yank_cmd is:'"win32yank.exe" -i --crlf'
[ clipboard ] [10:49:28] [3.766] [ Info  ] paste_cmd is:'"win32yank.exe" -o --lf'
```

**Comment by asarchami** [comment]
Sounds good. Will do when I get the chance. Thanks

**Comment by pd-448482** [comment]
Was this issue solved? I am hitting the same issue with yanking text. Running on linux, my clipboard output is:
```
[ clipboard ] [20:37:42] [3.275] [ Info  ] yank_cmd is:'xclip -quiet -i -selection clipboard'
[ clipboard ] [20:37:42] [3.275] [ Info  ] paste_cmd is:'xclip -o -selection clipboard'
```

**Comment by wsdjeg** [comment]
This has been fixed.

**Comment by pd-448482** [comment]
@wsdjeg Is there a way to confirm I'm running the version with the fix. I was able to get the logs above. But when I use `Leader Y` I can see the `:call clipboard#yank()` at the bottom, but I can't perform any input before `ctrl-c`ing.

**Comment by wsdjeg** [comment]
@pldimarco I think it is an new issue.
