### ISSUE TITLE
Error trying to install Spacevim

### ISSUE THREAD

**Issue by FelipPalermo** [wsdjeg/SpaceVim#4722]
OS : Windows 11
Today i formated my pc, never got an errror trying to install SpaceVim before, but this time i`m getting this message when i open nvim : 

Error detected while processing C:\Users\Felipe Palermo\AppData\Local\nvim\init.vim[9]..C:\Users\Felipe Palermo\AppData\Local\nvim/main.vim[64]..function SpaceVim#end[98]..SpaceVim#plugins#load[3]..SpaceVim#plugins#fetch[4]..dein#add[1]..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*":
E218: autocommand nesting too deep
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
Error detected while processing C:\Users\Felipe Palermo\AppData\Local\nvim\init.vim[9]..C:\Users\Felipe Palermo\AppData\Local\nvim/main.vim[64]..function SpaceVim#end[98]..SpaceVim#plugins#load[3]..SpaceVim#plugins#fetch[4]..dein#add:
line    1:
E117: Unknown function: dein#parse#_add
Error detected while processing BufWinEnter Autocommands for "*"..function SpaceVim#layers#core#statusline#get[232]..<SNR>38_active[4]..<SNR>38_search_count[1]..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*":
E218: autocommand nesting too deep
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
E117: Unknown function: dein#autoload#_on_func
Error detected while processing BufWinEnter Autocommands for "*"..function SpaceVim#layers#core#statusline#get[232]..<SNR>38_active[4]..<SNR>38_search_count:
line    1:
E117: Unknown function: SpaceVim#plugins#searcher#count

Tried with gvim but got the same error.
Idk if it change something but last time i was using Mingw and now i`m using TDM64.
![image](https://user-images.githubusercontent.com/86897377/195263023-a815b3e3-a003-4222-ae28-84c469974b34.png)

**Comment by toddhow** [comment]
I'm experiencing the exact same issue on Windows 10

**Comment by franckspike** [comment]
You might want to have a look at my hardcoded quick-fix patch https://github.com/SpaceVim/SpaceVim/commit/53362ddbcff11d70eff08e508c09a97fa81304f0

C:\Users\fmaheux is a hard link (junction) to C:\Users\Francois Maheux
(in cmd.exe, use mklink.exe /J)
