### ISSUE TITLE
<Leader> modification throws error

### ISSUE THREAD

**Issue by OnPointSM** [wsdjeg/SpaceVim#4725]
## Expected behavior
I want to change the default leader key to another key, (as it happens - 'ù')

## The reproduce ways from Vim starting
I have no user config file for vim [~/.vimrc] only the /etc/vimrc configuration file.
I have appended the precise function given in the documentation, but it results in an error,
(see below)
[The new leader button itself works, however.]

## Output of the `:SPDebugInfo!`
I have tried  - buffer, Y - to copy to clipboard, but I cannot get it to paste....sorry

## Screenshots
![Leader_Key_Error](https://user-images.githubusercontent.com/96946146/195554341-e03b4c8c-1312-4b01-a30b-958a615af619.jpg)

Translated:
Error detected when processing/etc/vimrc:
line 15:
E746: myspacevim#before function name does not match script name

**Comment by wsdjeg** [comment]
you should not use `/etc/vimrc`, please checkout the doc of spacevim, bootstrap function should be in `~/.SpaceVim.d/`
