### ISSUE TITLE
Replace vim-ultest with neotest

### ISSUE THREAD

**Issue by mikaoelitiana** [wsdjeg/SpaceVim#4739]
**Is your feature request related to a problem? Please describe.**
As mentioned on [vim-ultest](https://github.com/rcarriga/vim-ultest) repository, it is now deprecated and should be replaced with [neotest](https://github.com/nvim-neotest/neotest)

> Deprecation Warning
This repo is no longer being actively worked on. I've moved my efforts into [Neotest](https://github.com/nvim-neotest/neotest). If you use NeoVim then I'd suggest switching to that as it will cover all features of vim-ultest. If you're a Vim user, this repo will still work and I will accept PRs but will no longer be adding features.

**Describe the solution you'd like**
Remove vim-ultest and install neotest instead

**Describe alternatives you've considered**
I have installed neotest manually and updated tests key bindings to call neotest functions instead of vim-ultest

**Comment by wsdjeg** [comment]
neotest does not support vim, spacevim needs to support vim8.
