### ISSUE TITLE
Hotkey to toggle syntax-checking on save?

### ISSUE THREAD

**Issue by anoadragon453** [wsdjeg/SpaceVim#474]
## Expected behavior, english is recommend
Hey there, I'd like to be able to turn automatic syntax-checking on save off for some projects. Is there a simple hotkey to do so, or even a .vimrc command?

Some projects need libraries and compiler options that vim does not recognize by default and thus errors show up even though the code is correct.

## Environment Information
- OS: Linux
- vim version: 8.0
- neovim version: N/A

## The reproduce ways from Vim starting (Required!)
* Open a file with code extension
* Write something and save
* Code is auto-compiled and checked for errors

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
:message -> Messages maintainer: Bram Moolenaar <Bram@vim.org>
Don't think it's required

**Comment by wsdjeg** [comment]
`:SPConfig`
add:
`let g:neomake_open_list = 0`

**Comment by anoadragon453** [comment]
Works perfect, thank you!
