### ISSUE TITLE
edit layer 中 fcitx5 支持

### ISSUE THREAD

**Issue by ChasingZenith** [wsdjeg/SpaceVim#4757]
https://github.com/SpaceVim/SpaceVim/blob/e7cb486364a2e7e4281560381a13833a26c7d960/autoload/SpaceVim/layers/edit.vim#L123

经过我的测试，应检测fcitx5，不确定fcitx是否可行
```
executable('fcitx5')
```

**Comment by wsdjeg** [comment]
这是根据你安装的程序版本来的，默认应该只有 `fcitx` 命令。
