### ISSUE TITLE
nvim-cmp is broken

### ISSUE THREAD

**Issue by penggongkui** [wsdjeg/SpaceVim#4761]
## Expected behavior, english is required
It should work
## The reproduce ways from Vim starting (Required!)
autocomplete_method = "nvim-cmp"
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

The bundle nvim-cmp missing the lua/cmp/view folder, we should update the bundle

**Comment by wsdjeg** [comment]
please update spacevim, it works well for me now.
