### ISSUE TITLE
LSP Not working for Clojure (clojure-lsp)

### ISSUE THREAD

**Issue by rawoke083** [wsdjeg/SpaceVim#4766]
## Expected behavior, english is required

Having clojure-lsp working, when pressing :LspInfo (0 clients connected)

## The reproduce ways from Vim starting (Required!)
 - Install  clean SpaceVim
 - Install clojure-lsp and confirm it's in the path and working
 - Create clojure-related config in Spacevim (layers + lsp)

```

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = 'lang#clojure'

[[layers]]
  name = 'lsp'
  filetypes = [
    "clojure",
  ]

[layers.override_cmd]
    clojure = ["clojure-lsp"] 
  enabed_servers=['clojure-lsp']

```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.8.1
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lang#clojure`:ok
  - `lsp`:ok

**Comment by wsdjeg** [comment]
This page is updated, please check it. https://spacevim.org/use-vim-as-a-clojure-ide/

**Comment by wsdjeg** [comment]
I get same issue.

![图片](https://user-images.githubusercontent.com/13142418/229289029-83fadbbb-ee43-4f10-93bd-e6e0e0b5dab9.png)

**Comment by wsdjeg** [comment]
![图片](https://user-images.githubusercontent.com/13142418/229290081-41ca68df-412c-43d0-961f-07f2b6a05a84.png)

everything work well for me now. make sure all jars has been downloaded.
