### ISSUE TITLE
Support vim-preview to preview tag on another buffer

### ISSUE THREAD

**Issue by Javier-Huang** [wsdjeg/SpaceVim#4771]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Can SpaceVim support the vim-preview plugin, https://vimawesome.com/plugin/vim-preview-care-of-itself. Using it and gtags can easily view the function under the cursor without jumping to the corresponding function.

```
[[custom_plugins]]
    repo = "https://github.com/skywind3000/vim-preview.git"
    merged = false
```
Although I can use custom_plugins, when I run :PreviewTag, an unnamed buffer will be generated, and after :PreviewClose, this buffer will not be deleted, which makes my nvim look ugly.

![image](https://user-images.githubusercontent.com/88572822/210164906-ad89b6c6-c8e8-4f48-9124-39421c08954c.png)
I don't know if there is a bug in this plugin itself. I don't know how to read/write vim-script code, so it is very difficult for me to debug this plugin.

So I hope you can support this plugin to SpaceVim, or can you provide a corresponding solution to this problem.

Thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by wsdjeg** [comment]
This is because the plugin do not change `&list` option of preview buffer. BTW the active development of that plugin is stopped. The only future changes will be bug fixes.

**Comment by wsdjeg** [comment]
https://github.com/skywind3000/vim-preview/issues/8
