### ISSUE TITLE
How to install plugins with specific branch

### ISSUE THREAD

**Issue by chenboshuo** [wsdjeg/SpaceVim#4772]
When I try to install [coc.nvim](https://github.com/neoclide/coc.nvim),
it required specific branch, for example
```vim
" Use release branch (recommend)
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Or build from source code by using yarn: https://yarnpkg.com
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
```
However I don't know how to set in `[[custom_plugins]]`  Configuration.
What should I do next? Thank you for your help!

**Comment by wsdjeg** [comment]
It is same as dein.

**Comment by ecotechie** [comment]
For @chenboshuo and anybody looking for how to do this, it's:

```
[[custom_plugins]]
  repo = 'neoclide/coc.nvim'
  rev = 'release'
```

**Comment by wsdjeg** [comment]
thanks
