### ISSUE TITLE
plugin updater doesn't like paths with spaces in them (at least on mswin)

### ISSUE THREAD

**Issue by digidoor** [wsdjeg/SpaceVim#4786]
## Expected behavior, english is required
No deluge of error messages.
## The reproduce ways from Vim starting (Required!)
- Install SpaceVim on mswin from a gitbash terminal (neovim having already been installed).
- Start neo/SpaceVim (selecting dark mode).
- Exit nvim.
- Start nvim. <---- errors on plugin update
## Output of the `:SPDebugInfo!`
Unfortunately, I already reinstalled before thinking to report. No way to test until my plugins are out of date.
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![spacevim-error](https://user-images.githubusercontent.com/37601466/214267993-f70a94fa-014b-4eed-9500-d3f3196994f7.png)
----------- Just the bottom bit ------------------
![listed](https://user-images.githubusercontent.com/37601466/214269424-6454c1bf-0217-4f65-ab9a-734a945b4698.png)

Seems like an issue with spaces in the path names. I reinstalled using regular cmd.exe and so far it is error-free.

**Comment by digidoor** [comment]
Fresh install (which was error free) led to more of the same kind of errors on the third or so startup.
![new-error](https://user-images.githubusercontent.com/37601466/214479999-e8adb72e-38da-4514-845a-ec273f8a9f15.png)
![new-error2](https://user-images.githubusercontent.com/37601466/214480010-f9d57c5e-1f8c-4bb5-8de0-c1b993555629.png)
I'm on a windows machine so I don't have access to https://asciinema.org/. I've taken screenshots instead:
![debug1](https://user-images.githubusercontent.com/37601466/214485775-86666f61-10d3-47c3-971d-a61c2d452976.png)
![debug2](https://user-images.githubusercontent.com/37601466/214485779-c97fcaca-1bb9-4583-b135-aad9facd7738.png)
![ebug3](https://user-images.githubusercontent.com/37601466/214485786-95b8c7a3-0b0b-4282-a68e-6eab9cb78c95.png)
![debug4](https://user-images.githubusercontent.com/37601466/214485795-a70e540c-6e52-4b3b-9a50-d7a00e404f74.png)
I can't tell whether the errors are being handled correctly or if it leads to broken plug-ins so I'd like to reinstall all of them. Is there a way to do that? Using `:SPUpdate` updated nothing after the first error I reported—which is why I reinstalled—defaulting to "skip local plugin" for everything. `:SPReinstall` would be perfect if there was some kind of "all" option. As it is, it's a long list and in no particular order in the autocomplete menu.

**Comment by wsdjeg** [comment]
same as #4721
