### ISSUE TITLE
<Space>wp to switch to the previous window

### ISSUE THREAD

**Issue by digidoor** [wsdjeg/SpaceVim#4787]
Simple request: vim and neovim use ^Wp in normal mode to switch to the previous window. SpaceVim has most of unmoddified vim's keybindings or a spaced-up version but not this one even though SpaceVim isn't using `<Space>`wp. So yeah, to sum up: add `<Space>`wp as a binding to switch to the previous window; it doesn't conflict with anything and it's consistent with the other keybinds that have been "spaced up".

**Comment by wsdjeg** [comment]
Hi, the key binding `SPC w w` do the samething.
