### ISSUE TITLE
spacevim not auto installed after brand new install neovim

### ISSUE THREAD

**Issue by deepseeksss** [wsdjeg/SpaceVim#4790]
i have new note book,  after i installed the spacevim and neovim, i open the neovim, nothing happend, no messages too

**Comment by 60ke** [comment]
+1

**Comment by 60ke** [comment]
> i have new note book, after i installed the spacevim and neovim, i open the neovim, nothing happend, no messages too

run `ln -s ~/.SpaceVim ~/.config/nvim` will be ok

**Comment by chrisjune** [comment]
> run ln -s ~/.SpaceVim ~/.config/nvim will be ok

It helps a lot!

**Comment by LinuxPenguin99** [comment]
> > i have new note book, after i installed the spacevim and neovim, i open the neovim, nothing happend, no messages too
> 
> run `ln -s ~/.SpaceVim ~/.config/nvim` will be ok

It worked! Thank you!
