### ISSUE TITLE
Can't open online file by its URL

### ISSUE THREAD

**Issue by twio142** [wsdjeg/SpaceVim#4799]
## Expected behavior, english is required

When trying to open a online file by its URL, vim shows a blank editor instead of loading the file (which should be the case without SpaceVim). Supposedly the url is treated as a local path that doesn't exist.

## The reproduce ways from Vim starting (Required!)

`:e https://url-of-a-online-file`

## Output of the `:SPDebugInfo!`

No error is thrown.

**Comment by wsdjeg** [comment]
You need to change `enable_netrw` option in `core` layer:

https://spacevim.org/layers/core/
