### ISSUE TITLE
feature suggestion: open a directory using vimfiler welcome

### ISSUE THREAD

**Issue by bonds** [wsdjeg/SpaceVim#480]
## Expected behavior, english is recommend

````nvim /home/scott/```` will open nvim and launch the vimfiler welcome; instead it launches nvim then immediately exits

## Environment Information
- OS: OpenBSD 6.1
- vim version: 
- neovim version: NVIM v0.2.0-1501-g51a2d8dc

## The reproduce ways from Vim starting (Required!)

````$ nvim /home/scott```` (or any other directory)

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

n/a

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
These is same issue I have got, I have some idea about vim/neovim welcome page:

1. now my pwd is `~`, the home directory of current user.
2. open vim or nvim with a file name, such as `vim forks/neovim/src/main.c`, will open vim with only one window no matter whether the file is existed, what in the window is just a buffer contains such file, and the `getpwd()` should return `~/forks/neovim`, this means auto change the pwd to the root of a project.
3. open vim or nvim with a directory. 
    - directory existe: keep cursor in the vimfiler buffer, the pwd should be the project root of such direcory. ( It should be better, open the directory in vimfiler buffer`.
    - directory does not existe: I don't know, any idea?

**Comment by bonds** [comment]
> "directory does not existe: I don't know, any idea?"

So, if you try ````nvim /home/missingdirectory/```` I suggest vimfiler welcome screen opens in the current directory, basically ignoring the specified directory.

If you try ````nvim /home/missingdirectory```` without the trailing slash, so it could be a missing file or a missing directory, I suggest treating it like a missing file, and create a new buffer that will save to that file name.

**Comment by wsdjeg** [comment]
`

> f you try nvim /home/missingdirectory without the trailing slash,

this should be same as `nvim /home/foo.xxx`

> So, if you try nvim /home/missingdirectory/ I suggest vimfiler welcome screen opens in the current directory, basically ignoring the specified directory.

will try to support it.

**Comment by wsdjeg** [comment]
@Shougo
I have test it in vim and neovim, here is the minivimrc, 
```viml
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/vimfiler.vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/unite.vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/vimproc.vim
set nocp
let g:vimfiler_as_default_explorer = get(g:, 'vimfiler_as_default_explorer', 1)
augroup vfinit
  au!
  autocmd BufEnter * if (winnr('$') == 1 && &filetype ==# 'vimfiler') |
        \ q | endif
augroup END
```

in vim `vim -u test.vim dir/` will open vim with vimfiler buffer.
but in neovim, `nvim -u test.vim dir/`, nvim will auto exit.

**Comment by Shougo** [comment]
> in vim vim -u test.vim dir/ will open vim with vimfiler buffer.

I don't know why Vim works.
But in neovim, it is feature.

vimfiler opens the directory before BufEnter, so it will be exited by `:quit` command.

It should be:

```vim
  autocmd BufEnter * if (!has('vim_starting') && winnr('$') == 1 && &filetype ==# 'vimfiler') |
        \ q | endif
```

**Comment by wsdjeg** [comment]
@Shougo Thanks , it works well now.

@bonds now my next work is to enable `startify` and `vimfiler` when open nvim/vim with a dir. (cursor should keeped in vimfiler buffer).

**Comment by wsdjeg** [comment]
@bonds I have implement all the features in doc branch.

**Comment by bonds** [comment]
awesome, thank you!
I tried it out and it works great

When testing I noticed: When I type "nvim ." or "nvim ./" or "nvim /absdirname/" I get the welcome screen (good), but when I type "nvim relativedirname" or "nvim relativedirename/" with a directory that exists, I get vimfiler (good) but on the left instead of the right (bad) and without the welcome screen (bad). Its already an improved behaviour, launching vimfiler instead of just quitting, but it would be even better if it launched the welcome screen with relative directories. The behaviour is consistent with both nvim and vim.

**Comment by wsdjeg** [comment]
@bonds do you pull the latest version of doc branch? here is a what I get:

https://asciinema.org/a/5ys3gmztnjm689v6lgv3idflx

it works well for me, when use `nvim relativedirname`, it will open vim with two windows, on the left is welcome page, and on the right is vimfiler buffer, both of theirs pwd is the relativedirname.

**Comment by bonds** [comment]
A couple more observations:

* when opening a directory (i.e. ````nvim /home/scott````, vimfiler starts with focus instead of the welcome screen area, it would be better if he welcome screen area had focus, consistent with the behaviour when you type ````cd /home/scott; nvim````

https://asciinema.org/a/5upp90yaezwni5ficodo7syvg

* if I open a relative directory (i.e. ````nvim reldir```` and the type ````f f```` to search for a file, then select a file and hit enter, nvim exits instead of loading the file

https://asciinema.org/a/5va58nw8mhxjpwr9wpotwme12

I'm testing with commit 42553721310f16414f30a4f2e78ad92e1c8d0f0d

**Comment by bonds** [comment]
@wsdjeg sometimes it works (brings up the welcome screen), sometimes it doesn't (shows only vimfiler with no welcome screen):

https://asciinema.org/a/30tz3hbcsmfy9a9k41xqhx58a

I haven't figured out a pattern yet, but it seems to at least be consistent for a given path...it either works every time or it does not work every time.

**Comment by wsdjeg** [comment]
got it. will fix it later.

**Comment by bonds** [comment]
Thanks @wsdjeg! I also noticed that sometimes the line numbers are missing:

https://asciinema.org/a/9m8ivok5qag8gqma79s6d90jr

**Comment by wsdjeg** [comment]
how do you open that file in welcome page? use Enter?

**Comment by bonds** [comment]
yes, or to be more precise: ctrl-ww to switch from vimfiler to the 
welcome screen area, then j to move the cursor down to that line, then 
enter to open the file

**Comment by wsdjeg** [comment]
@bonds I just reproduce it sometimes `set nu?` return `nonumber`.

**Comment by wsdjeg** [comment]
There are more than two issues in this issue, can you please split them in different issues? That will be easy for me to fix them.

**Comment by bonds** [comment]
Sure!

**Comment by wsdjeg** [comment]
is this issue still happen?

**Comment by bonds** [comment]
Feature works great, I don't know of any other issues.

**Comment by wsdjeg** [comment]
nice . so I close  this issue.
