### ISSUE TITLE
:set list in ~/.SpaceVim.d/init.toml

### ISSUE THREAD

**Issue by onlyoneofme** [wsdjeg/SpaceVim#4801]
There are many options I could change using `~/.SpaceVim.d/init.toml` like this:
```
[options]
        expand_tab = true
```
 is there such an option for `:list`? I didn't find any

**Comment by wsdjeg** [comment]
No, maybe you need to use bootstrap funtion.

**Comment by onlyoneofme** [comment]
@wsdjeg thanks for the answer! Is it relevant to add this option to `init.toml` I mean to this repository or the only way is to use some workaround like bootstrap function? As I can see contribution to this repository is opened, but not from PR, what is the other way?
