### ISSUE TITLE
There is error report when exit neovim using :wq while gtags auto_update is enable.

### ISSUE THREAD

**Issue by Geniuze** [wsdjeg/SpaceVim#4806]
Here is the error reported:

Error detected while processing function 111[4]..84:                                        
line    8:                                    
E5555: API call: Vim:E322: line number out of range: 1 past the end

**Comment by wsdjeg** [comment]
I can not reproduce this issue, and the error message is too simple.

**Comment by Geniuze** [comment]
I guess maybe it is caused by the gtags auto_update function call back, but neovim has been closed. Because :w will trigger neovim to write buffer and update gtags db.
