### ISSUE TITLE
telescope trying to find zettelkasten resulting in error screen

### ISSUE THREAD

**Issue by bobby-b-song** [wsdjeg/SpaceVim#4807]
## Expected behavior, english is required
When `telescope` layer is enabled, it seems that the plugin will proactively trying to find `zettelkasten`, this will result in a flash of error at startup.

## The reproduce ways from Vim starting (Required!)
Minimum `init.toml`
```
[[layers]]
  name = "telescope"
```
Then start Spacevim
## Output of the `:SPDebugInfo!`
https://gist.github.com/bsong0/b85d97aba0e252ec791e472e774b7bbb
## Screenshots

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/85090456/227738975-697380bf-a869-4573-a4a6-e6e526a30f89.png">

**Comment by bobby-b-song** [comment]
I'm able to locate the bug to line 7 on `$HOME/.SpaceVim/config/plugins/telescope.vim`.

```
lua require('telescope').load_extension('task')
>>> lua require('telescope').load_extension('zettelkasten_template')
if filereadable(g:_spacevim_root_dir . 'bundle/telescope-fzf-native.nvim/build/libfzf.so')
``` 


Commenting line 7 fixes this problem. Maybe you can add a if statement to determine if we need to import the zettelkasten module.

**Comment by wsdjeg** [comment]
Ok, thanks.
