### ISSUE TITLE
feature suggestion: run some config after global config

### ISSUE THREAD

**Issue by bonds** [wsdjeg/SpaceVim#481]
## Expected behavior, english is recommend

This config snippet from my old vimrc doesn't work with SpaceVim:

````
" Highlight the 80th character
" make sure this happens after setting the colorscheme or it may be ignored
highlight TooLong ctermbg=1 guibg=DarkRed
match TooLong /\%>79v.*\%<81v/
````

but it would be nice if it did. I'm guessing my config is loaded before the global SpaceVim config? If so, it would be nice to be able to have some user config run later.

## Environment Information
- OS: OpenBSD 6.1
- vim version:
- neovim version: NVIM v0.2.0-1501-g51a2d8dc

## The reproduce ways from Vim starting (Required!)

See above.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

**Comment by wsdjeg** [comment]
hmm, can you have a try with below?
```viml
augroup custom_config
    au!
    au VimEnter * call s:customMappings()
augroup END
func s:customMappings()
     highlight TooLong ctermbg=1 guibg=DarkRed
     syntax match TooLong /\%>79v.*\%<81v/
endf
```

and maybe you should wait for #478 

I have implement some ui toggle mapping for these:

key mapping | desc
--------------- | -------------------
`SPC t 8` | highlight any character past the 80th column
`SPC t f` 	 | display the fill column (by default the fill column is set to 80)

**Comment by bonds** [comment]
Thank you for the idea, that's a neat way to do it. Unfortunately I tried it and it had no effect. It looks like the ui toggle that's coming is to highlight every character after the 80th? I'm trying for just highlight the 80th column. Looks like ````:help colorcolumn```` does what I want, except that I can only get it to highlight the 80th column in grey, the color settings have no effect:

````
set colorcolumn=80
hi ColorColumn ctermbg=red guibg=red
````
it highlights only the 80th column and only when there's something on that line, which is what I want, but, its grey not red. Perhaps my ColorColumn setting is being overwritten by a plugin or something else? If I type in the ````hi ColorColumn ctermbg=red guibg=red```` while Vim is running, it changes the color, so I think it must be set somewhere else. If I could just have MY settings apply last, that would help I think. :)

**Comment by bonds** [comment]
Ok, this worked!:

````
augroup custom_config
    au!
    au VimEnter * call s:customMappings()
augroup END
func s:customMappings()
    hi ColorColumn ctermbg=red guibg=red
endf
set colorcolumn=80
````

Thanks!

**Comment by wsdjeg** [comment]
@bonds in doc branch, `Space + t +f` should be able toggle the highlight of 80 column.
what I did is just `set cc=80` and `set cc=`.
