### ISSUE TITLE
NvimTree not setup on v2.1.0

### ISSUE THREAD

**Issue by xusd320** [wsdjeg/SpaceVim#4817]
## Screenshots
<img width="606" alt="image" src="https://user-images.githubusercontent.com/16577489/228873056-205bc1a7-7539-45ea-a65c-2314da28eb2c.png">

This bug seems be related to this commit: https://github.com/SpaceVim/SpaceVim/commit/10043da3516c5d98a3450ccd6929d460bc362604#diff-5f0b96754081a63068e3aed646aca74e4e3e8510bba8dd9b033bac9a99dda747

When I revert blow lines in file plugins.vim, it works fine
<img width="1801" alt="image" src="https://user-images.githubusercontent.com/16577489/228872277-675bfcbd-1e68-4739-9787-8725f910150b.png">

**Comment by xusd320** [comment]
My neovim version is 0.8.3

**Comment by wsdjeg** [comment]
fixed, please update spacevim.
