### ISSUE TITLE
The structure of a code runner

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#4820]
the code runner plugin will be improved, and the structure of a runner will be changed too. currently it is:

1. a `String`, will be run directly
2. a `List` with two items, the first one is a dict,
3. a `Dict`.

```
{
   'exe'  :  string or function
   'opt' : list,
   'targetopt' : the target option,
   'usestdin' : true or false
}
```

**Comment by lsq** [comment]
![图片](https://user-images.githubusercontent.com/1617256/230251986-617f7b7d-a3ca-4012-9bf3-320d4bc5dfea.png)
上面把-xc - 移到-l 前面，就不会报错了，在windows的mingw64环境下和ubuntu下都测试过
---------------------------------------------
大佬，这个discuss是不是能解决runner顺序的问题，我就不再单独提ISSUE了。

**Comment by wsdjeg** [comment]
这个在原有的基础上就可以实现，不需要修改源码，可以自定义 runner
