### ISSUE TITLE
layer#c std=c++20 not woking

### ISSUE THREAD

**Issue by dayu521** [wsdjeg/SpaceVim#4826]
https://github.com/SpaceVim/SpaceVim/blob/49a995f7b9e06acb03f5eee0a8390b8868dbac45/autoload/SpaceVim/layers/lang/c.vim#L50

https://spacevim.org/use-vim-as-a-c-cpp-ide/

![Screenshot_20230404_095507](https://user-images.githubusercontent.com/38237890/229666630-7fce99fe-a5db-4add-b2a7-dd61e1d89765.png)

There is a conflict between the source code on Github and the documents from the official website

**Comment by wsdjeg** [comment]
Thanks, I will fix the doc.

**Comment by wsdjeg** [comment]
This is just two different example, so no conflict.

**Comment by dayu521** [comment]
I substituted  `[layers.clang_std] ` for `[layer.clang_std] ` in init.toml file.Under which i added one line `cpp=c++20`.,then it works.

**Comment by wsdjeg** [comment]
The doc has been updated, thanks.
