### ISSUE TITLE
How to use mouse selection to copy to system clipboard

### ISSUE THREAD

**Issue by icefery** [wsdjeg/SpaceVim#4827]
**Is your feature request related to a problem? Please describe.**

Sorry I am not good at vim, with ubuntu native vim, mouse selection will be copied to system clipboad as default, but SpaceVim will not.

**Describe the solution you'd like**

Mouse selection will automatically be copied to system clipboard.

**Describe alternatives you've considered**

Edit with `vim file`, but copy with `cat <file>`.

**Additional context**

**Comment by wsdjeg** [comment]
this is general usage of default vim. in spacevim, you can use key binding  `\ y` in visual mode.
