### ISSUE TITLE
Toml config overlay

### ISSUE THREAD

**Issue by robertek** [wsdjeg/SpaceVim#4832]
**Is your feature request related to a problem? Please describe.**
The case is simple. I have multiple systems where i share my config for anything useful (.dotfiles). But some systems are different from the others. Still I can have a nearly 80% of my init.toml the same on any of the systems. I have not found a convenient way to have the rest 20% (mainly different layers) configuration set up and have the init.toml shared.

**Describe the solution you'd like**
The best solution I can imagine is to have a local.toml. Which will append or even overwrite parts of the settings added to the init.toml. And actually it will done the same as having the project based .SpaceVim.d/init.toml config.

So the logic would be following:
```
source ~/.SpaceVim.d/init.toml
if filereadable(~/.SpaceVim.d/local.toml)
         source ~/.SpaceVim.d/local.toml
endif
if filereadable($cur_proj_dir/.SpaceVim.d/init.toml)
        source $cur_proj_dir/.SpaceVim.d/init.toml
endif
```

**Describe alternatives you've considered**
I have considered having a bootstrap function set in init.toml and than add a different vim config files that are loaded on different host. This is fine for a simple vim config, but I do not know how to apply that for a more complex cases and mainly the things like simply enabling a layer.
In simple vimrc configuration I have done this using
```
if filereadable(expand("~/.vimrc.local"))
        :source ~/.vimrc.local
endif 
```

**Additional context**
Maybe this can be done already, but I did not found it (so maybe only documentation is missing).
I may also try to code this myself and push request, but I'm still in the beginning of understanding your code. Maybe with some pointers I may do it.

**Comment by wsdjeg** [comment]
hi, currently, spacevim support global config `~/.SpaceVim.d/init.toml` and project config `~/path/to/proj/.SpaceVim.d/init.toml`.
