### ISSUE TITLE
Support nvim 0.9.0 in LSP.vim

### ISSUE THREAD

**Issue by Saafo** [wsdjeg/SpaceVim#4842]
## Expected behavior, english is required

Cannot use lsp in nvim 0.9.0

Seems the version is hard coded here and not update with 0.9.0

https://github.com/SpaceVim/SpaceVim/blob/f61fc738f0a3e27b7140a45df89097c14fbf2d77/autoload/SpaceVim/layers/lsp.vim#L65

## The reproduce ways from Vim starting (Required!)

1. upgrade nvim to  0.9.0
2. cannot use lsp in spacevim

## Output of the `:SPDebugInfo!`

logs aboud lsp:

```
Checking SpaceVim layer health:
  - `lsp`:ok

[[layers]]
  name="lsp"
  enabled_clients=['sourcekit-lsp']
  filetypes=['swift', 'rust']
```

**Comment by wsdjeg** [comment]
in neovim 0.9.0, `has('nvim-0.8.0')` also return v:true.
