### ISSUE TITLE
Error at the first run

### ISSUE THREAD

**Issue by zxkmm** [wsdjeg/SpaceVim#4844]
## Expected behavior, english is required
Spacevim run successfully
## The reproduce ways from Vim starting (Required!)
install spacevim with ``curl -sLf https://spacevim.org/install.sh | bash``
$ vim
## Output of the `:SPDebugInfo!`
Spacevim did'n run so no debug log
## Screenshots
![image](https://user-images.githubusercontent.com/24917424/232998724-69fecacb-0ce0-4b1d-b5f8-cfa628ffb50e.png)
If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

## Enviroments
Manjaro.ver
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.1.0
DISTRIB_CODENAME=Talos
DISTRIB_DESCRIPTION="Manjaro Linux"
```
Nushell.ver
```
╭────────────────────┬──────────────────────────────────────────────────────────────────╮
│ version            │ 0.78.0                                                           │
│ branch             │ makepkg                                                          │
│ commit_hash        │ 2ec20286371f1d90a77fdd5d82818c6c5851f090                         │
│ build_os           │ linux-x86_64                                                     │
│ build_target       │ x86_64-unknown-linux-gnu                                         │
│ rust_version       │ rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) │
│ cargo_version      │ cargo 1.68.2                                                     │
│ build_time         │ 2023-04-05 02:09:35 +00:00                                       │
│ build_rust_channel │ release                                                          │
│ features           │ default, zip                                                     │
│ installed_plugins  │                                                                  │
╰────────────────────┴──────────────────────────────────────────────────────────────────╯

```

**Comment by wsdjeg** [comment]
the error is from https://github.com/wsdjeg/SpaceVim/blob/3020fd6ff2c957c6273478897651db669ab0b5ae/autoload/SpaceVim.vim#L1690, I do not know why `system('uname -a')` failed in your vim.

**Comment by zxkmm** [comment]
My first thought is that nushell doesn't return a string when do ``uname -a``, but after I edit that line to       ``let s:uname = string(system('uname -s'))``, the error is still there. and it even happens on bash. pretty weird.

Edit: the error gone after i switched to bash

**Comment by zxkmm** [comment]
https://github.com/nushell/nushell/issues/8981#issuecomment-1519951061

**Comment by zxkmm** [comment]
Seems the crash is not likely caused by that line.....  
 it's still buggy even if I directly gave ``s:uname`` a string it might want. 
``let s:uname = "Linux"``

**Comment by zxkmm** [comment]
Bug of nushell. Closing.
