### ISSUE TITLE
The Iedit mode in SpaceVim is not functioning properly.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#4847]
## Expected behavior, english is required

Instead of only editing the highlighted string when entering Iedit mode, it actually edits all occurrences of the string throughout the document.

## The reproduce ways from Vim starting (Required!)

locate cursor in some word and type "*", all the words under cursor wil be highlighted. Then press `SPC s e` to enter Iedit mode and edit it. all the same string will be edited.

for example: type these words to a document in Vim, wordUnderCursor wordUnderCursorShouldNotBeEdited wordUnderCursor.
And locate your cursor to the word "wordUnderCursor" and type "*", the 2 words "wordUnderCursor" will be highlighted. and then press `SPC s e`, all the 3 string "wordUnderCursor" in this document will be edited.

## Screenshots

![image](https://user-images.githubusercontent.com/5350867/233767820-829b2b35-43cd-4294-91c4-7e2a34c00dbd.png)

**Comment by wsdjeg** [comment]
This is default behavior of `SPC s e`, this key binding will not read info from ~~visual mode~~ `*` highlight info. if you want to manager occurrences, you need to use highlight plugin, the key binding is `SPC s h`.

![图片](https://user-images.githubusercontent.com/13142418/233789405-7e4bd20c-cdb0-4a14-8432-351528fe3d93.png)

then press `e`

![图片](https://user-images.githubusercontent.com/13142418/233789425-52ebddb5-84ba-4668-9783-07736a015ac6.png)
