### ISSUE TITLE
my <C-p> mapping is ignored when in the home directory

### ISSUE THREAD

**Issue by bonds** [wsdjeg/SpaceVim#486]
## Expected behavior, english is recommend

I can map ````<C-p>```` to whatever I want and it will always work.

## Environment Information
- OS:
- vim version:
- neovim version:

## The reproduce ways from Vim starting (Required!)

Launch vim while in your home directory. Type ctrl-p and notice that it doesn't use whatever mapping you set.

## Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"

````
:verbose map <C-p>
n  <C-P>       *@:<C-U>CtrlP ~\DotFiles<CR>
        Last set from ~/.SpaceVim/config/plugins/vim-startify.vim
n  <C-P>       * :Sfind<CR>
        Last set from ~/.SpaceVim.d/init.vim
````

the offending lines in vim-startify.vim are these:

````
fu! <SID>startify_mapping()
  if getcwd() == $VIM || getcwd() == expand('~')
    nnoremap <silent><buffer> <c-p> :<c-u>CtrlP ~\DotFiles<cr>
  endif
  call s:update_logo()
endf
augroup startify_map
  au!
  autocmd FileType startify nnoremap <buffer><F2> <Nop>
  autocmd FileType startify call <SID>startify_mapping()
  autocmd FileType startify setl scrolloff=0 nowrap
augroup END
````

They are easy enough to comment out, but I'm wondering what the 'right' way to get ````<C-p>```` to do what I want is.

**Comment by bonds** [comment]
And, just for background, what I'm trying to use ````<C-p>```` for is fzf.

**Comment by wsdjeg** [comment]
It is feature of ctrlp.
you need set g:ctrlp_map to empty.

https://github.com/wsdjeg/DotFiles/blob/master/SpaceVim.d/init.vim#L45-L46

**Comment by wsdjeg** [comment]
sorry for missunderstand

**Comment by wsdjeg** [comment]
but use `ctrlp` in home dir `~` is very slow, I think denite is better.

**Comment by bonds** [comment]
FZF is much faster than either ctrlp or denite, and it works fine in the 
home directory. I'd like to use it instead, but my mapping is getting 
overridden in the home directory.
