### ISSUE TITLE
Question LSP configuration

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4861]
# Pylsp configuration

I would like to set the maximum line length for pylsp.

[Here](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) I found that there is a configuration parameter.

How/where can I do that with SpaceVim?

Thanks

**Comment by wsdjeg** [comment]
You need to use bootstrap function. and If you are using neovim, the lspconfig is enabled by default when you load lsp layer. The use `lua require('lspconfig').pylsp.setup()` function.
