### ISSUE TITLE
code blocked by float frame

### ISSUE THREAD

**Issue by hermanzhaozzzz** [wsdjeg/SpaceVim#4868]
As I entered the code, the code prompt obscured my previous line of code

code prompt obscured (can not see)
![Xnip2023-05-26_16-58-59](https://github.com/SpaceVim/SpaceVim/assets/39041821/4ae85a35-ea55-4b43-8976-4ff80226d26c)

real code
![Xnip2023-05-26_16-59-06](https://github.com/SpaceVim/SpaceVim/assets/39041821/e5cbf641-82ec-4c93-8a53-0fc8a4e09ea2)

I did not write any thing, when the code prompt frame shows, I can not see my code last line.

Could I change some config info to avoid this? Many thanks!

**Comment by wsdjeg** [comment]
What is your Vim version and `SPC h L` debug info is needed.

**Comment by hermanzhaozzzz** [comment]
I think It might coused by jupyterlab. and I never met it now. so I will close this issue. thankyou for your time!
