### ISSUE TITLE
[Question] How does SpaceVim automatically detect the file encoding?

### ISSUE THREAD

**Issue by qiuwei** [wsdjeg/SpaceVim#4869]
SpaceVim automatically detects the encoding of files for CJK languages.
How is this achieved? I would like to achieve something similar for my own vimrc.

Many thanks!

**Comment by wsdjeg** [comment]
Maby be it it https://gitlab.com/SpaceVim/SpaceVim/blob/ec123916629cbe64123d9baa76732c0e21a92dbf/autoload/SpaceVim.vim#L1920
