### ISSUE TITLE
Feature Request: SPC bindings

### ISSUE THREAD

**Issue by reem** [wsdjeg/SpaceVim#487]
This is just a feature request for some particularly useful bindings from spacemacs:

`SPC-f-f`: open `VimFiler` in the directory of the current buffer
`SPC-p-f`: fuzzy search for files in the current project
`SPC-p-/`: fuzzy search for text through the entire project
`SPC-/`: fuzzy search for text through current buffer
`SPC-b-b`: fuzzy search through open and recently closed buffers

**Comment by wsdjeg** [comment]
Nice feature request. will implement these features.

**Comment by reem** [comment]
Also:

`SPC-e-l`: toggle showing the lint/checker error list

**Comment by wsdjeg** [comment]
I just have a try with spacemacs, and as I know:

`SPC-f-f` will open a buffer for fuzzy find file in the dir of current buffer. So I thin use `CtrlP` `Unide` or `Denite` should be better then use vimfiler, vimfiler is a plugin just like nerdtree in spacemacs.

**Comment by wsdjeg** [comment]
I have added these new features, can you test the PR?

**Comment by reem** [comment]
Opened an issue for SPC-p/f-f not working for me, the others work great, thanks!

**Comment by wsdjeg** [comment]
will look into it.
