### ISSUE TITLE
Feature Request: incremental search-replace

### ISSUE THREAD

**Issue by reem** [wsdjeg/SpaceVim#488]
In spacemacs, when using `s` to replace data in a selection, (e.g. `:%s/target/tothis/g`) spacemacs will show a live preview of the application of that replace - this makes it *much* easier to write very complicated search/replace queries on the fly, and vastly reduces the number of times you have to undo and subtly change your query after applying it.

**Comment by wsdjeg** [comment]
@reem If you are using neovim, this feature can be easy get by `inccommand` feature.

**Comment by wsdjeg** [comment]
@reem you can read `:h 'icm'` in neovim.

**Comment by wsdjeg** [comment]
@reem here is a vedio:

[![asciicast](https://asciinema.org/a/7k3is7lueuf3242862mi8deoj.png)](https://asciinema.org/a/7k3is7lueuf3242862mi8deoj)

**Comment by reem** [comment]
Great! Is there any way to get this in vanilla vim? I am currently not using neovim due to some slowness when using neovim with SpaceVim - I haven't reported an issue because I don't have any useful repro information other than "it's slow when scrolling" and that doesn't feel very helpful.

**Comment by wsdjeg** [comment]
Does you mean tt is not slow when scrolling in vim? 

icm feature is only implemented in neovim. I do not known if there is anything vim plugin provide this feature. Maybe vim-over?

**Comment by reem** [comment]
I've opened a separate issue for the lag I am observing: https://github.com/SpaceVim/SpaceVim/issues/515

**Comment by wsdjeg** [comment]
see #503
