### ISSUE TITLE
[Question] How does SpaceVim in WSL2 open the * System paste board？

### ISSUE THREAD

**Issue by cumtlzy** [wsdjeg/SpaceVim#4887]
### Is your feature request related to a problem? Please describe..

I use WSL2 (ubuntu20.04) in Windows 11
I noticed that <Leader> y written in "use document" can be written to the +/* paste board.

I tried SpaceVim in windows and it can be copied to the +/* system paste board in this way.
But SpaceVim in WSL2 doesn't seem to work.

Then I looked at the register through ":reg" and found no * or +, only 0-9, :, %, /

How does SpaceVim in WSL2 open the * or + System paste board？Or how can I copy to Windows 11?

### Describe the solution you'd like.

How does SpaceVim in WSL2 open the * or + System paste board？Or how can I copy to Windows 11?

**Comment by Rom1deTroyes** [comment]
Until last week, I used to have a Win10+wsl2 installation at work. For copy/paste between wsl and windows, an XServer was needed on the windows side, making `*` and `+` registers to be mapped to the windows clip board.

Neovim had theses two registers, but legacy vim.tiny does not.

It seems that wsl2 now works with wslg, using wayland and pulse-audio to interact with Win11... Providing a Microsoft vision to how things should be.
Hopefully (for me), I'll never have to work with such a config anymore :-)

**Comment by wsdjeg** [comment]
It seems not a feature request, please use matrix room for general usage question. issue is only for bug report and feature request.
