### ISSUE TITLE
nerdtree window should not open any current buffers

### ISSUE THREAD

**Issue by noisecode3** [wsdjeg/SpaceVim#4888]
### Expected behavior.

I figure this side window should not change to the regular buffers(from tab layout). I don't know if its possible to change per window.

### The reproduce ways from Vim starting.

\ and some number when in nerdtree will require me use ":q" and f3 to get back.
I think \ should not work the same with the nerdtree window, there is a configuration weirdness
or a pitfall for scatterbrains.

**Comment by wsdjeg** [comment]
please make the reprodce step more clearlly, I can not reproduce it.

**Comment by noisecode3** [comment]
1. open a buffer in the main window (buffer 1)
2. In normal mode go to nerdtree with "space 2"
3. now "\ 1" will open buffer 1 in nerdtree window to the right and not in the middle...

**Comment by wsdjeg** [comment]
I think it is default behavior of vim. leader + number is to run :b + number.

**Comment by noisecode3** [comment]
I think ```\ + NUMBER``` should be disable when nerd-tree or any other toggle window that is active. OR it should be followed with a question/statement like ```Enter window number:``` but only for toggled side windows. And its not going to be on by default maybe? Something you can set in spacevims config file, I would want it like that, I think there is more people but not sure. Sometimes when I'm stressed I get it wrong, lol.

also if its only 1 middle main window and all other windows are toggle windows, it don't need to ask Enter window number, just move to that window and open the buffer there, makes sense to me.

**Comment by wsdjeg** [comment]
@noisecode3 Hi, This feature seems hard to implement, we need a option to distinguish between normal buffer/win and nerdtree etc.

**Comment by wsdjeg** [comment]
This feature has been added. please update spacevim
