### ISSUE TITLE
[question]: 

### ISSUE THREAD

**Issue by Rishang** [wsdjeg/SpaceVim#4889]
### Is your feature request related to a problem? Please describe..

How to disable `Auto plugin updates`

![image](https://github.com/SpaceVim/SpaceVim/assets/30040885/5902bde3-8a14-4f05-b540-1f77c0fdabb9)

This happens almost too often when i open vim

### Describe the solution you'd like.

There should be option to disable auto-updates for plugins

**Comment by Rishang** [comment]
@wsdjeg Please at least help me on this, i just need a way to disable updates coming from `PluginManager`

**Comment by wsdjeg** [comment]
@Rishang  https://github.com/SpaceVim/SpaceVim/issues/4884

**Comment by Rishang** [comment]
Thankyou and Sorry both at same time :)
