### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 120ace** [wsdjeg/SpaceVim#4896]
### Expected behavior.

Open console, type `nvim`, successfully use SpaceVim.

### The reproduce ways from Vim starting.

**What I'm using:**

-   Windows 10, 22h2.
-   NeoVIm 0.9.1: installed with Scoop Package Manager using a global install: `scoop install neovim --global`.
-   Python 3.11.4: installed with Scoop Package Manager with the global command: `scoop install python --global`.
-   PyNvim 0.4.3: installed as root: `pyp3 install pynvim`.
- SpaceVim: Installed as root with the install script for Windows provided by SpaceVim.org.

Per the recommendation on the SpaceVim.org I hooked NeoVim to python and verified it worked with a `:checkhealth`.

When I run `nvim` from a command prompt, I get this:

> Error detected while processing C:\users\School Work 1\Appdata\Local\nvim\init.vim[64]..function SpacVim#end[99]...SpaceVim#plugins#load[3]...SpaceVim#plugins#fetch[4]..dein#add[1]..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..:
E218: autocommand nesting too deep
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
e117: Unkown function: dein#autoload#_on_func
Error detected while processing X:\Users\School Work 1\AppData\Local\nvim\init.vim[64]..function SpaceVim[99]..SpaceVim#plugins#load[3]..SpaceVim#plugins#fetch[4]..dein#add:line 1:
E117 Unkown function: dein#parse#_add
Error detected while processing BufWinENter Autocommands for "*"..function SpaceVim#layer#core#statusline#get[245]..<SNR>39_active[4]..<SNR>39_search_count[1]..FuncUndefined autocommands for "*" FuncUndefined autocommands for "*" FuncUndefined autocommands for "*" FuncUndefined autocommands for "*" FuncUndefined autocommands for "*" FuncUndefined autocommands for "*" FuncUndefined autocommands for "*" FuncUndefined autocommands for "*" FuncUndefined autocommands for "*"
E218: autocommand nesting too deep
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
e117: Unknown function: dein#autoload#_on_func
Error Detected while processing BufWinEnter Autocommand for "*"..function SpaceVim#layers#core#statusline#get[245]..<SNR>39_active[4]..<SNR>39_search_count: line 1:
E117 Unkown function: SpaceVim#plugins#searcher#count
>

I have hand typed all of the above, the console wouldn't let me copy anything, please excuse any errors.

I am a complete newbie when it comes to any of this, please help.

### Output of the `:SPDebugInfo!`

Error detected while processing function SpaceVim#logger#viewLog:
line    3:
E5108: Error executing lua function SpaceVim#logger#viewLog[3]..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*"..FuncUndefined Autocommands for "*": Vim(call):E218: autocommand nesting too deep
stack traceback:
        [C]: in function 'call'
        C:\Users\School Work 1\.SpaceVim\/lua/spacevim/logger.lua:69: in function 'viewLog'
        [string "luaeval()"]:1: in main chunk

**Comment by wsdjeg** [comment]
can not fix it, seems there is space in username. and please do not use issue without title.
