### ISSUE TITLE
Scala layer support ENSIME deprecated

### ISSUE THREAD

**Issue by yihuajack** [wsdjeg/SpaceVim#4899]
### Expected behavior.

According to the Quick Start Guide Blogs->[Use Vim as a Scala IDE](https://spacevim.org/use-vim-as-a-scala-ide/), add following TOML to `init.toml`:
```toml
[[layers]]
name = 'lang#scala'
```
At the startup of vim/nvim, related plugins should be correctly installed automatically and Scala support should be ready for use.

### The reproduce ways from Vim starting.

At the startup of vim/nvim, it will try to install ensime-vim and a window is popped-up to sign in GitHub. However, the installation stuck [0/1] and nothing happened. I quitted and checked the cache directory $HOME$\.cache\vimfiles\repos\github.com\ensime\ensime-vim. There is only a `.git` directory under it. I ran `git remote -v` under this directory and it showed:
> origin  https://github.com/ensime/ensime-vim (fetch)
origin  https://github.com/ensime/ensime-vim (push)

However, the repository does not exist. ENSIME probably deleted this repository.

**Comment by wsdjeg** [comment]
https://github.com/ensime/ensime-vim is private repo.
