### ISSUE TITLE
Compatibility with "VSCode Neovim"

### ISSUE THREAD

**Issue by zhiyuanzhai** [wsdjeg/SpaceVim#4904]
### Is your feature request related to a problem? Please describe..

When using "[VSCode Neovim](https://github.com/vscode-neovim/vscode-neovim)" (a VSCode extension utilizing a fully embedded Neovim instance in VSCode), `init.vim` can not be read.

### Describe the solution you'd like.

The reason why "VSCode Neovim" cannot read `init.vim` created by SpaceVim is that it doesn't support many neovim plugins. As mentioned [here](https://github.com/vscode-neovim/vscode-neovim/issues/788#issuecomment-999018656):

> Any plugins which 1. add functionality to insert or command mode 2. provide non-trivial ui functionality 3. replace vscode functionality should be disabled.

The extension provides a variable `g:vscode` to determine whether Neovim is running in VSCode. This allows us to separate those unsupported features.

**Comment by yukiteruamano** [comment]
> The reason why "VSCode Neovim" cannot read `init.vim` created by SpaceVim is that it doesn't support many neovim plugins.

Only for this reason, the request is already meaningless, because so much of the current SpaceVim ecosystem would have to be changed for such a specific one.

**Comment by wsdjeg** [comment]
sorry, I can not add this feature.
