### ISSUE TITLE
No automatic installation when open nvim 0.9.1

### ISSUE THREAD

**Issue by BEMfreshman** [wsdjeg/SpaceVim#4907]
### Expected behavior.

The installation of plugins should be launched the first time nvim is opened.

### The reproduce ways from Vim starting.

1. Install nvim v0.9.1
2. run install.cmd 
3. open nvim

**Comment by wsdjeg** [comment]
You can install spacevim manually:

https://spacevim.org/faq/#how-to-install-spacevim-manually
