### ISSUE TITLE
about terminal switch

### ISSUE THREAD

**Issue by mailliw2010** [wsdjeg/SpaceVim#4911]
### Expected behavior.

when configured shell layers, I use SPACE ‘ to create a terminal. and switch to the terminal window. but when I use Ctrl-Left/Right/Up/Down to switch back to my code, the terminal will become normal mode.which is not my expectation . in original vim, I can use ctrl + w + hjkl  to switch to code and leave the terminal as insert mode. 
Is there other way to do this with spacevim? Thanks.

### The reproduce ways from Vim starting.

A bug happened!

**Comment by wsdjeg** [comment]
what is the version of vim?
