### ISSUE TITLE
Can I update all packages by bash script?

### ISSUE THREAD

**Issue by JaydenFish** [wsdjeg/SpaceVim#4913]
### Is your feature request related to a problem? Please describe..

I want to update packages and spacevim by bash script. `:SPUpdate` is troublesome.
I can update spacevim by git pull --rebase. But how to update packages by bash script?

### Describe the solution you'd like.

A bash command.

**Comment by wsdjeg** [comment]
no. we do not have bash script to update packages. But you can use git pull in each directory of package.
