### ISSUE TITLE
SPC -SPC key not defined 

### ISSUE THREAD

**Issue by jpx40** [wsdjeg/SpaceVim#4914]
### Expected behavior.

Spc key should work. And show typed keys on screen.

### The reproduce ways from Vim starting.

A bug happened!

When I use the SPC (space) key, I can't really use any commands, doesn't matter on which platform. Sometimes after a delay it kinda works. I am relatively new to Spacevim and didn't any config changes. 

It always shows SPC -SPC key not defined bzw SPC - .... key not defined.

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/jonas/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jonas/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 0
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']

**Comment by dqnk** [comment]
Could you post a screenshot? Try pressing SPC and questionmark (?). Does anything show up? Does it say [SPC]-[SPC] not defined? You are supposed to enable some layers first in your .SpaceVim.d/init.toml and then use the keybinds for the layers. If you don't know them, the possible keybinds at every moment show up ~2 seconds after you press SPC.

**Comment by jpx40** [comment]
This issue just happened recently on all my devices. I think it started a month ago it has to do with one of the commits in this time frame. Before that i could see on the bottom which keys i tipped. That was very helpful. I think i can still use most keybindings just the module that showed the typed keys on screen is broken.

**Comment by jpx40** [comment]
<img width="808" alt="Screenshot 2023-08-29 at 19 31 27" src="https://github.com/SpaceVim/SpaceVim/assets/92295347/d1fe9013-7a33-4a94-9bba-7bb12c19d535">

**Comment by jpx40** [comment]
> Could you post a screenshot? Try pressing SPC and questionmark (?). Does anything show up? Does it say [SPC]-[SPC] not defined? You are supposed to enable some layers first in your .SpaceVim.d/init.toml and then use the keybinds for the layers. If you don't know them, the possible keybinds at every moment show up ~2 seconds after you press SPC.

Aren't the key-binds defined by the core Layer which is enabled By default? The SPC and questionmark Command has the same error.

**Comment by jpx40** [comment]
<img width="835" alt="Screenshot 2023-09-01 at 12 05 41" src="https://github.com/SpaceVim/SpaceVim/assets/92295347/06c0141c-89e1-48f2-b115-376b1ea3984f">

**Comment by jpx40** [comment]
> Could you post a screenshot? Try pressing SPC and questionmark (?). Does anything show up? Does it say [SPC]-[SPC] not defined? You are supposed to enable some layers first in your .SpaceVim.d/init.toml and then use the keybinds for the layers. If you don't know them, the possible keybinds at every moment show up ~2 seconds after you press SPC.

Pressing SPC once shows the tooltip.

**Comment by wsdjeg** [comment]
I can not reproduce this issue now. 

1. we do not define `SPC-SPC` key binding.
2. `SPC ?` key binding requires a fuzzy finder layer, for example `telescope` layer.
