### ISSUE TITLE
IDEA compatible

### ISSUE THREAD

**Issue by MmingY** [wsdjeg/SpaceVim#4916]
### Is your feature request related to a problem? Please describe..

I love this and I want to use it in IDEA as well。

### Describe the solution you'd like.

There is a plugin for ideavim in IDEA, but it doesn't work for me through source

**Comment by hw770** [comment]
在提issue前请仔细阅读相关文档.
ideavim只是vim的一个简单模拟, 连大多数插件都不能兼容, 其不能够与SpaceVim这样的vim发行版兼容是完全在预料之中的. 
我认为你至少应当对vim和ideavim有所了解后, 再提issue.
如果你单纯喜欢spacevim的键位, 你可以考虑[MarcoIeni/intellimacs：IntelliJ 平台的类似 Spacemacs 的键绑定。 --- MarcoIeni/intellimacs: Spacemacs' like key bindings for IntelliJ platform.](https://github.com/MarcoIeni/intellimacs)

事实上, SpaceVim和intellimacs都受到emacs发行版Spacemacs的启发, 参考[](https://github.com/MarcoIeni/intellimacs?tab=readme-ov-file#related-projects)

**Comment by Zevan770** [comment]
Please read the relevant documentation carefully before raising an issue.
ideavim is just a simple simulation of vim, and is not compatible with most plug-ins. It is completely expected that it is not compatible with vim distributions such as SpaceVim. 
I think you should at least have some understanding of vim and ideavim before raising an issue.
If you simply like the key bindings of spacevim, you can consider [MarcoIeni/intellimacs: Spacemacs-like key bindings for the IntelliJ platform. --- MarcoIeni/intellimacs: Spacemacs' like key bindings for IntelliJ platform.](https://github.com/MarcoIeni/intellimacs)

In fact, both SpaceVim and intellimacs are inspired by the emacs distribution Spacemacs, see [](https://github.com/MarcoIeni/intellimacs?tab=readme-ov-file#related-projects)
