### ISSUE TITLE
一些内置插件不能加载

### ISSUE THREAD

**Issue by xiaomi-robot-liukai** [wsdjeg/SpaceVim#4924]
作者：
@wsdjeg  您好，我通过“curl -sLf https://spacevim.org/cn/install.sh | bash -s -- --install neovim”进行了安装，通过配置
`[[layers]] 
name = 'leaderf' `
插件不能加载。通过“space h l”也看到此leaderf插件也没有加载，另外试了一下denite也不好使，但是试验了fzf这个插件是能够加载的。
能看下什么原因导致的吗？

**Comment by wsdjeg** [comment]
应该是因为 leaderf 跟 denite 这两个插件都是需要 python3 支持，你需要安装 python，并且通过pip安装 pynvim。

可以通过`:echo has('python3')`来检测你的 Neovim 是否支持 python3.

如果觉得启用python3太麻烦，可以使用 telescope 模块，这个模块是没什么依赖的。

**Comment by xiaomi-robot-liukai** [comment]
> 应该是因为 leaderf 跟 denite 这两个插件都是需要 python3 支持，你需要安装 python，并且通过pip安装 pynvim。
> 
> 可以通过`:echo has('python3')`来检测你的 Neovim 是否支持 python3.
> 
> 如果觉得启用python3太麻烦，可以使用 telescope 模块，这个模块是没什么依赖的。

@wsdjeg 感谢楼主，问题已解决🙏
