### ISSUE TITLE
macbook 安装了git，在安装了spacevim时，进入发现没有”:Git“命令但是有”:GitGutter“

### ISSUE THREAD

**Issue by xiaomi-robot-liukai** [wsdjeg/SpaceVim#4925]
@wsdjeg 作者您好！如题。不知道您遇到过这个问题吗？

**Comment by wsdjeg** [comment]
更新一下吧，之前应该是修改出错了。并且需要启用 `git` 模块。

**Comment by xiaomi-robot-liukai** [comment]
> 更新一下吧，之前应该是修改出错了。并且需要启用 `git` 模块。

@wsdjeg 楼主，您好。已更新生效。感谢支持🙏
