### ISSUE TITLE
Unknown option: belloff=all

### ISSUE THREAD

**Issue by zxbzxb180** [wsdjeg/SpaceVim#4930]
### Expected behavior.

centos7 使用官网脚本安装后，打开vim提示：
Error detected while processing function SpaceVim#begin..SpaceVim#default#options:
line  129:
E518: Unknown option: belloff=all
Press ENTER or type command to continue

在.SpaceVim/autoload/SpaceVim/default.vim注释belloff=all后，SpaceVim颜色主题出现异样

### The reproduce ways from Vim starting.

curl -sLf https://spacevim.org/cn/install.sh | bash

**Comment by wsdjeg** [comment]
vim 的版本信息是什么？

**Comment by zxbzxb180** [comment]
> vim 的版本信息是什么？

vim-enhanced-7.4.629-8.el7_9.x86_64

**Comment by zxbzxb180** [comment]
请问我运行脚本安装后，本地没有生成.SpaceVim.d配置文件是什么情况？.SpaceVim是我从Gitee上拉取后改名的
![image](https://github.com/user-attachments/assets/e3444abd-93b7-40d0-aef6-00f7abf998c9)

**Comment by zxbzxb180** [comment]
我已经执行过多次vim了，但没有出现配置文件和安装插件
![image](https://github.com/user-attachments/assets/86d2e402-4fd4-4e55-bb94-b6dd0a61d9f6)
