### ISSUE TITLE
Tab, Return and python compiler error

### ISSUE THREAD

**Issue by FelipPalermo** [wsdjeg/SpaceVim#4932]
### Expected behavior.

MacBook Pro M1. everything up to date ( python, home-brew, os ... ). 
When I use vim, Tab and return works fine ( except from window splitting that give me a lot of erros ), but in vim neither of these things works. 

( converted to txt ) 
[init.txt](https://github.com/user-attachments/files/16574069/init.txt)

### The reproduce ways from Vim starting.

NA 

### Output of the `:SPDebugInfo!`

NA

**Comment by wsdjeg** [comment]
sorry, I can not reproduce it, more info is needed. error message or reproduce step etc.
