### ISSUE TITLE
What happened to SpaceVim

### ISSUE THREAD

**Issue by SenorGato** [wsdjeg/SpaceVim#4940]
### Expected behavior.

What happened to the theme space vim?  This is the repo it used to point to right?  I know they deprecated Github because the original user did not have access, so I changed my repo to point at the spacevim.com endpoint, but now its back?  It seems to have migrated to yet another Neovim distribution, and now it says the default theme is gruvbox?

### The reproduce ways from Vim starting.

A bug happened!

**Comment by wsdjeg** [comment]
Hi, the github repo is main repo of spacecvim, and `https://spacevim.org/git/repos/SpaceVim/` is redirected to `https://github.com/SpaceVim/SpaceVim.git`
