### ISSUE TITLE
SpaceVim更新之后出现问题

### ISSUE THREAD

**Issue by Aaronluoxiao** [wsdjeg/SpaceVim#498]
使用平台 windows
在vim中使用的SpaceVim,今天更新之后 出现问题，问题描述见图
![qq 20170506080132](https://cloud.githubusercontent.com/assets/12382026/25770029/25dba16e-3233-11e7-9630-d7e6dff2388c.png)

**Comment by wsdjeg** [comment]
it is issue of upstream plugin.

/cc @Yggdroot

**Comment by Aaronluoxiao** [comment]
删除那几个之后 ，每次更新就会自动恢复

**Comment by Yggdroot** [comment]
可能是因为我对indentLine做了git push -f， 不要使用更新这个插件，重新装。

**Comment by wsdjeg** [comment]
那我给spacevim加一个重新安装某个插件的命令

**Comment by wsdjeg** [comment]
`:call dein#reinstall(['indentLine'])`
