### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by fedkey** [wsdjeg/SpaceVim#5]
ubuntu 14.04下，默认字体很难看，很散。 #
![2016-12-29 15 33 33](https://cloud.githubusercontent.com/assets/12322225/21538867/4da42c7c-cddc-11e6-8c1e-be3495692aeb.png)

**Comment by wsdjeg** [comment]
默认字体也许不适合每个人，SpceVim支持 自定义字体;
`:h g:spacevim_guifont`
