### ISSUE TITLE
Colour scheme plugin install

### ISSUE THREAD

**Issue by EwanValentine** [wsdjeg/SpaceVim#50]
Hi there, me again! 

I noticed the colour schemes aren't lazy loaded, but they're included in the list of features, so how do I install/use those? 

If I try `color Atom` I get `colorscheme Atom not found`. 

Thanks in advance!

**Comment by wsdjeg** [comment]
https://github.com/rafi/awesome-vim-colorschemes is a link of collection of colorschemes, but all the sub dir in that repo , you can find it in github. by defalt SpaceVim use `gruvbox`.

https://github.com/morhetz/gruvbox  I think it is the best colorscheme.

well. I will add the list of colorschemes into SpaceVim

**Comment by wsdjeg** [comment]
works well now, and you should use `:colorscheme atom` instead.
