### ISSUE TITLE
推荐插件 vim-over

### ISSUE THREAD

**Issue by KnightPublic** [wsdjeg/SpaceVim#503]
运行图可以参考 [vim-over](https://github.com/osyo-manga/vim-over) github 主页

**Comment by wsdjeg** [comment]
这个插件我没有看出有什么实质性的用处，neovim实现了一个实时预览替换的功能，相比这个，要好很多。

**Comment by wsdjeg** [comment]
可以看下我发在 #488 的视频。

**Comment by KnightPublic** [comment]
[vim-over](https://github.com/osyo-manga/vim-over)  根据官网动图，可以判断 vim-over 实现了下面的功能：

1. 实时预览匹配的字串，实时预览替换后的字串
2. 按 `tab` 键时有搜索功能，可以把和当前子串相同的词自动补全

#488 的视频我看了，跟第一点功能相同，但是没有看到有自动补全的功能，而且我按照你的回复，可不可以理解这个是 neovim 的功能，vim 没有这个功能。

所以 SpaceVim 能否考虑给 vim 的用户添加这个插件？或者考虑其他类似的插件。

**Comment by wsdjeg** [comment]
这个插件比较复杂，我需要看看，谢谢
