### ISSUE TITLE
 Allow for not binding leader in insert mode

### ISSUE THREAD

**Issue by Rawa** [wsdjeg/SpaceVim#504]
## Expected behavior, english is recommend

When using a leader in insert mode with a leader function mapped in insert mode a delay will be caused. E.g if leader is mapped to space a delay of 1 second will go before character is shown.

This is caused by mappings with leader in insert mode. For users that prefer space as leader it would be nice to be able to allow to unbind these properties.

From digging a little i seen the following bindings:
autoload/SpaceVim/layers/lang/java.vim:63:    inoremap <silent> <buffer> <leader>UU <esc>bgUwea
autoload/SpaceVim/layers/lang/java.vim:64:    inoremap <silent> <buffer> <leader>uu <esc>bguwea
autoload/SpaceVim/layers/lang/java.vim:65:    inoremap <silent> <buffer> <leader>ua <esc>bgulea
autoload/SpaceVim/layers/lang/java.vim:66:    inoremap <silent> <buffer> <leader>Ua <esc>bgUlea
autoload/SpaceVim/mapping/leader.vim:10:  inoremap <silent> <Leader><Tab> <C-r>=MyLeaderTabfunc()<CR>
config/plugins/ctrlsf.vim:7:inoremap <leader>st <Esc>:CtrlSFToggle<CR>

In my case only "autoload/SpaceVim/mapping/leader.vim:10:  inoremap <silent> <Leader><Tab> <C-r>=MyLeaderTabfunc()<CR>" are the cause of this issue and there is no way for me in my config to unbind it through iunmap because it is executed after my local config. However, once started ":iunmap <Leader><Tab>" solves the issue.

General question, is there a reason for not executing the using config last? Shouldn't it override all other options?

## Environment Information
- OS: Arch Linux 
- vim version:
- neovim version: nvim 0.1.7

## The reproduce ways from Vim starting (Required!)

Install spacevim, map leader to space.

Btw thanks for the great work, really love spacevim so far!

**Comment by wsdjeg** [comment]
can you have a try do not use Space as leader?  if you use not use space as vim's `<leader>`, it will be use as `[SPC]` only in normal mode.

**Comment by wsdjeg** [comment]
remove mapleader in you custom configration file, and `Space` will not be binded in insert mode.

**Comment by Rawa** [comment]
@wsdjeg 
Don't know if i understood you correctly? Are you suggesting me to map leader to [SPC] or to change my bindings to [SPC]?

To clarify, I want to be able to reach leader actions, through the use of the space button, in Visual mode as well as in Normal mode. Is this feature not supported? Maybe I'm mislead by the documentation?

http://spacevim.org/documentation/#custom-configuration

**Comment by wsdjeg** [comment]
no need to map leader to [SPC],  in spacevim the default leader is ``\``,  but by default you can also use `Space` in normal mode.

**Comment by wsdjeg** [comment]
what I mean, is just remove `let mapleader = "\<space>"` in your config.

**Comment by Rawa** [comment]
Then I can not access leader bindings with space in visual mode, right?

**Comment by Rawa** [comment]
@wsdjeg This does not seem to be the case?

Updated to most recent SpaceVim, and used a minimal config added two lines in my config:

```
nmap <Leader>a= :Tabularize /^[^=]*\zs=<CR>
vmap <Leader>a= :Tabularize /^[^=]*\zs=<CR>
```
Pressing`\a=` works just fine, pressing `<space>a=` does not work. Other Leader actions such as pasting from X11 does not work or using easymotion.

Furthermore, it is not possible to do other leader actions in  visual mode, such as yanking to X11 clipboard. It does not seem like `space` works as leader in normal mode properly?

**Comment by wsdjeg** [comment]
`Space` is not used as leader by default, it is [SPC], and only be used in normal mode.

**Comment by Rawa** [comment]
The goal for me is to have `space` as leader, in some keyboard layouts (such as Nordic) the `\` is very inconveniently placed compared to a US-layout (In the Swedish layout `<Right Alt> + ?` is required to produce a `\`. Thus `,` or `<space>` is a common alternative to use as `<Leader>`, hence why I want to remap leader. Since space is easier to reach I would prefer that.

Mapping leader to space, works just fine. However, as mentioned in the first post, mappings to `<Leader>` in the insert mode will cause delay to the usage of `<space>` in insert mode when typing, thus I would like to be able to remove this mappings in my local config or have the option to disable them (The former seems most reasonable).

However, for some reason the mappings are performed _after_ the local configuration is initialization, thus there is no way in the local configuration files to override these configuration settings, for example through `iunmap <leader><Tab`.

**Comment by wsdjeg** [comment]
spacevim use space as SPC only in normal mode. you should remove let mapleader in custom config. and  to see what mapping is missing.

for example: save file, SPC f s

**Comment by Rawa** [comment]
As mentioned before you reopened this ticket. It was not about SPC in normal mode.

**Comment by wsdjeg** [comment]
so what is the issue, if you do not change leader delay after \ should be ok.

**Comment by wsdjeg** [comment]
vim support imap leader . and we need the feature. for example : when upcase  letter when edit src. \UU should be better. I do not want to swith to normal mode to do this work.

**Comment by Rawa** [comment]
@wsdjeg The ability to override global bindings in the local config, that is the issue. I do not suggest changing the default behaviour of leader for whole spacevim, simply that users may have the option to do overriding changes in their local config and not be forced to modify the spacevim source code.

**Comment by wsdjeg** [comment]
SpaceVim is not origin vim. It has its own mapping system. I should write documentation about how to binding keys in SpaceVim. if override some core func mapping or val, It is may break SpaceVim.

**Comment by Rawa** [comment]
Ofcourse, but isn't this valuable? That you can configure existing behaviour to fit your need?

[spf13](https://github.com/spf13/spf13-vim) solved this throught the use of before and after files. Maybe a similar approach could be useful?

**Comment by wsdjeg** [comment]
@Rawa It is not before and after file issue, it is lazzy hooks file. in spf13 both after and before file will be loaded when start vim. but lazzy hooks file only be loaded when the plugin is loaded,

for example if a lazy plugin's opt is `on_cmd`, and if you do not use that command,  the lazy hooks file will not be loaded.

ok, I will add check for the insert mode mappings.

**Comment by wsdjeg** [comment]
```vim
augroup custom_config
    au!
    au VimEnter * call s:customSetting()
augroup END
func s:customSetting()
      inoremap <silent> <buffer> <leader>UU :echo "hello"<cr>
endf
```

add this snippet to your custom configration file should be ok.
