### ISSUE TITLE
Unable to change colorscheme

### ISSUE THREAD

**Issue by jetm** [wsdjeg/SpaceVim#507]
It's expected to change the Vim colorscheme by using `g:spacevim_colorscheme` and `g:spacevim_colorscheme_bg`, but it has not effect.

When Vim is started and read which color scheme was applied, it shows: 'default'.

## Environment Information
- OS: Arch Linux
- vim version: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 26 2017 07:49:10)
Included patches: 1-586
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm     
```
## The reproduce ways from Vim starting (Required!)

Use the following configuration to set colorscheme 'one' and use 'dark' as background:
```viml
let g:spacevim_colorscheme_bg = 'dark'
let g:spacevim_colorscheme = 'one'
```

### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'one'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 0
g:spacevim_hiddenfileinfo = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_max_column = 120
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.
svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 0
g:spacevim_enable_debug = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', '
javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'naviga
tion', 'misc', 'core', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'vim', 'linux',
'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/tiamarin/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 0
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_leader_guide_vertical = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 800
OS: Linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file /home/tiamarin/.cache/SpaceVim/SpaceVim.log does not exists, only log for cur
rent process will be shown!
```

**Comment by wsdjeg** [comment]
@jetm I think it is issue with vim-one, I just test molokai and many other colorschemes, all of them works well.

**Comment by jetm** [comment]
@wsdjeg: Yes, molokai works. Tested onedark and it has the same issue; when reading colorscheme it shows `default` , instead of `onedark`. I wonder if this issue only applies for True Color colorscheme.

**Comment by wsdjeg** [comment]
no, bothe molokai and gruvbox are true colors.

**Comment by jetm** [comment]
I tested another TC colorscheme: [neodark](https://github.com/KeitaNakamura/neodark.vim); it works well. I think you're right. It seems a bug in [onedark](https://github.com/joshdick/onedark.vim) and [one](https://github.com/rakr/vim-one) colorschemes. Let me put an issue in both projects to look for a fix.

I have submitted both issues in [onedark's issue #99](https://github.com/joshdick/onedark.vim/issues/99) and [vim-one's issue #49](https://github.com/rakr/vim-one/issues/49).

**Comment by joshdick** [comment]
Neodark is including this at the top of of its colorfile:

```vim
highlight clear

if exists('syntax_on')
  syntax reset
endif
```

Does including this manually in your configuration make any difference?

**Comment by jetm** [comment]
@joshdick: running that doesn't make any difference.

**Comment by jetm** [comment]
@wsdjeg: I found after Vim is executed and `colorscheme onedark` or `colorscheme one` is called. The colors are fixed.

**Comment by joshdick** [comment]
I spent quite a while debugging this.

It seems to be caused by an odd combination of SpaceVim exacerbating a Vim bug.

Here's some information about the Vim bug:

- https://groups.google.com/d/msg/vim_dev/afPqwAFNdrU/nqh6tOM87QUJ
- https://www.reddit.com/r/vim/comments/22krs1/using_set_backgrounddark_in_vim_resets_the/

And here's the [relevant code in SpaceVim](https://github.com/SpaceVim/SpaceVim/blob/7e9742a171a6b551b0cc35e5dc180089b19dc444/config/general.vim#L10):

```vim
if count(g:spacevim_plugin_groups, 'colorscheme') && g:spacevim_colorscheme !=# '' "{{{
    try
        exec 'colorscheme ' . g:spacevim_colorscheme
        exec 'set background=' . g:spacevim_colorscheme_bg
    catch
        exec 'colorscheme '. g:spacevim_colorscheme_default
    endtry
else
    exec 'colorscheme '. g:spacevim_colorscheme_default
endif
```

Commenting out the `exec 'set background=' . g:spacevim_colorscheme_bg` makes onedark.vim load with proper/configured colors as expected.

Here's what appears to be happening:

1. `exec 'colorscheme ' . g:spacevim_colorscheme` is run, which for onedark.vim, should be the equivalent of `colorscheme onedark`.

2. At this point, running `:set background` appears to yield `light`, which is part of the Vim bug; `background` should be `dark` since `onedark.vim` is explicitly setting it that way.

3.  `exec 'set background=' . g:spacevim_colorscheme_bg` is run, which should be the equivalent of `set background=dark`. **This causes all colors to be reset since the background color has changed from light to dark**, which is the other part of the Vim bug, and which is causing the behavior you're seeing.

One possible workaround is to move `set background=dark` to the bottom of the affected colorschemes, but I'm not sure how to test that locally because I can't figure out how to get around SpaceVim's (apparently many) layers of caching installed plugins.

`neodark` includes `set background=dark` at the bottom, which is probably why it seems to be unaffected by this bug.

**Comment by wsdjeg** [comment]
really Thanks. I will try to fix it.

**Comment by joshdick** [comment]
@jetm I just pushed joshdick/onedark.vim@22c8bb6067a5b678433f19523ccb41dde7b9aad5 to try to work around this issue. Please update your plugins and let me know whether things work as expected.

**Comment by jetm** [comment]
@joshdick: Thank you very much for your time and excellent analysis of this rare issue.

**Comment by joshdick** [comment]
@wsdjeg @jetm You're welcome!

**Comment by jetm** [comment]
@joshdick: your workaround fixed this issue for onedark colorscheme. Thanks!

**Comment by joshdick** [comment]
@jetm Awesome, glad to hear it!

**Comment by wsdjeg** [comment]
@jetm @joshdick sorry, I can not understand now, any code fix need to be done in SpaceVim?

**Comment by jetm** [comment]
@wsdjeg: @joshdick, made a fix for onedark colorscheme; I think @rakr, author's vim-one, could do a fix as well. I would document this issue in the SpaceVim documentation mention the vim-one colorscheme behavior, maybe from another colorscheme untested and the bug unsolved in Vim. Based on this I think this issue could be close.
For now, if someone wants an Atom dark colorscheme, onedark and neodark are recommended. I would expect @rakr could solve this issue like @joshdick did.

**Comment by joshdick** [comment]
@wsdjeg SpaceVim's execution of `set background` will randomly break colors in some themes that don't have their `set background` line at the bottom. Maybe it's worth conditionally executing that line only in certain situations, but I'm not sure what situations those would be, or the exact reasons the extra `set background` is there right now.

**Comment by wsdjeg** [comment]
@joshdick I think it is hard to fix, because I do not know what situations should I remove that line, BTW I have test most of the colorscheme, They works well.

**Comment by joshdick** [comment]
@wsdjeg I meant to include this URL in my original analysis comment but pasted/duplicated a link to SpaceVim code by accident instead: https://groups.google.com/forum/#!msg/vim_dev/afPqwAFNdrU/nqh6tOM87QUJ I have since updated my previous comment to include that URL.

The linked discussion seems to indicate that only certain cterm colors trigger this behavior, so maybe the likelihood of hitting it is low for most themes, and onedark.vim and vim-one might just be statistically unlucky in this regard. If that's the case, it's probably not necessary to change SpaceVim.

**Comment by rakr** [comment]
First, I saw this issue a week ago, but didn't get the time to reply or act on it.

Agree with @joshdick, I have experienced the same issue and It is related to Vim's behaviour when it sets `ctermbg` for the `Normal` highlight.

A common misconception is that `set bg=dark|light` sets Vim's background, actually, it informs Vim that if a colour is missing, it should be replaced it by a default colour that fits a `light` or `dark` background. The fact that Vim sets the background is a "side-effect", hence why some colorscheme get "broken".

Also, you probably experienced the fact that if sometimes it reverts the value of `g:colorscheme` to `default`, it's somewhat associated with this.

In my case setting the background **before** changing the colorscheme fixed the issue.
Also always use both commands when changing the colorscheme, `set background` **and** `colorscheme`

**Comment by wsdjeg** [comment]
@rakr @joshdick Thanks for info, I have fixed this issue in https://github.com/SpaceVim/SpaceVim/commit/a0a63658791d540a942443558282e9a661b10738

**Comment by wsdjeg** [comment]
@rakr I have move set backgroud before colorscheme, but when I use  vim-one, and set background=dark does not work. but colorscheme is one instead of default.

**Comment by wsdjeg** [comment]
@jetm can you reproduce this issue? I found vim-one does not work in SpaceVim. here is how SpaceVim set colorscheme
```vim
if count(g:spacevim_plugin_groups, 'colorscheme') && g:spacevim_colorscheme !=# '' "{{{
    try
        exec 'set background=' . g:spacevim_colorscheme_bg
        exec 'colorscheme ' . g:spacevim_colorscheme
    catch
        exec 'colorscheme '. g:spacevim_colorscheme_default
    endtry
else
    exec 'colorscheme '. g:spacevim_colorscheme_default
endif
```

**Comment by jetm** [comment]
@wsdjeg: Yes, I can reproduce that problem as well. Instead of vim-one plugin to get an Atom dark color scheme, I changed to onedark plugin. For Atom light color scheme, vim-one works well, but its implementation makes tricky to work together with SpaceVim; I think due to Vim's bug related to background colors. Hope nvim has not this changing color issue.
I would put a _warning_ in SpaceVim documentation. For Atom dark color scheme use: onedark or neodark, for Atom light color scheme use vim-one (it uses light background by default). If you accept this proposal, I can submit a PR with this documentation change.

**Comment by joshdick** [comment]
@jetm Did you mean to say to use onedark instead of vim-one in your previous comment? All of our projects have pretty similar names. 😆

**Comment by jetm** [comment]
@joshdick: yes, I meant that :grin:. I have fixed the comment. Thank you!

**Comment by wsdjeg** [comment]
PR welcome. thanks.

**Comment by wsdjeg** [comment]
@rakr Too many spacevim users get this issue, maybe a "bug" of vim, I want to fix it in vim-one colorscheme, if I done I will send a pr.

**Comment by wsdjeg** [comment]
@jetm https://github.com/rakr/vim-one/pull/72 fix this issue.

**Comment by jetm** [comment]
@wsdjeg: It works. Thanks!
