### ISSUE TITLE
未知原因

### ISSUE THREAD

**Issue by Aaronluoxiao** [wsdjeg/SpaceVim#509]
windows 10 system，
更新SpaceVim之后 出现 警告
![d am1el9l13i x54ar fc5u](https://cloud.githubusercontent.com/assets/12382026/25898950/b6ded33c-3596-11e7-8b4f-7b4ecabdddd3.png)

**Comment by wsdjeg** [comment]
please use english!

BTW, why do not use issue template?

**Comment by wsdjeg** [comment]
I can reproduce it in win7, will try to fix it.

**Comment by wsdjeg** [comment]
Fixed
