### ISSUE TITLE
use unite outline error

### ISSUE THREAD

**Issue by fcying** [wsdjeg/SpaceVim#510]
## Expected behavior, english is recommend
unite outline error

## Environment Information
- OS:ubuntu
- vim version: vim8-596
- not custom init.vim

## init.vim
  0 let mapleader = ";"
  1 call SpaceVim#layers#load('lang#c')
  2 call SpaceVim#layers#load('ui')
  3 let g:spacevim_guifont = 'DejaVu\ Sans\ Mono\ for\ Powerline\ 11'
  4 let g:spacevim_colorscheme = 'NeoSolarized'
  5 set background=light

## The reproduce ways from Vim starting (Required!)
vim t.c
fo
switch func a , b, c
again
...
error

### test file

[t.zip](https://github.com/SpaceVim/SpaceVim/files/989902/t.zip)

## Screenshots
![1](https://cloud.githubusercontent.com/assets/106934/25901033/05ed7f6a-35c8-11e7-9fdb-374e4a877d58.jpg)
![2](https://cloud.githubusercontent.com/assets/106934/25901036/08590012-35c8-11e7-9447-b13986f6067c.jpg)

##SPDebugInfo 
[SpaceVim.log.txt](https://github.com/SpaceVim/SpaceVim/files/989897/SpaceVim.log.txt)

BTW: Why SPDebugInfo can't save a log file auto ?

**Comment by wsdjeg** [comment]
It works well for me, here is a vedio:

https://asciinema.org/a/5z25ltttrevhxw3whprwk4zny

**Comment by Shougo** [comment]
Using unite.vim is not recommended.
Unite.vim has many hard to fix bugs for example the error.

**Comment by wsdjeg** [comment]
@fcying Use `Fo` instead of `fo`, `F` is the denite mappings prefix.
