### ISSUE TITLE
Documentation/Feature Request: custom SPC bindings in init.vim

### ISSUE THREAD

**Issue by reem** [wsdjeg/SpaceVim#517]
Is there existing documentation and/or an example of adding a new SPC binding in my init.vim? I would like to add some random additional utilities for myself that don't belong in upstream spacevim, but everything I've tried that is similar to what is done in SpaceVim itself (e.g. calling `SpaceVim#mapping#space#def`) doesn't work from init.vim.

**Comment by wsdjeg** [comment]
I will add one example and doc for this issue latter.
