### ISSUE TITLE
SpaceVim compared to other spacemacs like clones.

### ISSUE THREAD

**Issue by autoferrit** [wsdjeg/SpaceVim#519]
This is more of a question about space vim, and some of the other similar setups out there.

How does this SpaceVim package compare  to others such as 

https://github.com/Tehnix/spaceneovim

theres others out there too, i saw one named `space-vim` as well. I was just wondering if you or anyone else is familiar with the others and knows the differences. why to use one over the others.

I think it would be nice to get others together to make one better system. rather than a splintered effort.

Thanks.

**Comment by wsdjeg** [comment]
sorry. I do not use any of them, So I can not compare to them.
