### ISSUE TITLE
Undefined variable g:deoplete#_context on pressing backspace in insert mode

### ISSUE THREAD

**Issue by EwanValentine** [wsdjeg/SpaceVim#52]
When I hit backspace in insert mode I get the following error... 

![screen shot 2017-01-06 at 10 31 51](https://cloud.githubusercontent.com/assets/1155123/21715291/8df7717e-d3fb-11e6-85e2-c2c35ac642ae.png)

I'm using neovim 1.7 in Mac OSX Sierra. 

:echo has('python') = 1
:echo has('python3') = 1

**Comment by wsdjeg** [comment]
@EwanValentine have you install all the plugins by `call dein#install()`? deoplete has not been installed.

**Comment by EwanValentine** [comment]
@wsdjeg Yeah I've done that

**Comment by anton-mobilebridge-com** [comment]
Same for me. neovim produces this error. vim does not. Ubuntu 16.04.

**Comment by wsdjeg** [comment]
ok, will look into it, Maybe a bug fo deoplete.

**Comment by wsdjeg** [comment]
@EwanValentine I think your plugin_install_process has not finished, you need `call dein#install()` and wait for it finished,  it it is finished , a red message will be shown. 

then I can not reproduce this issue.

**Comment by taizilongxu** [comment]
+1

**Comment by taizilongxu** [comment]
I found that the vim will load the .cache dein plugin and skip the install plugin step, but when I rm the .cache file , and install spacevim the error say that:

```
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag "g:Lf_WindowPosition" in file /Users/limbo/.cache/vimfiles/.cache/init.vim/.dein/doc/leaderf.txt
[dein] function SpaceVim#end[31]..SpaceVim#plugins#load[171]..zvim#plug#end[10]..dein#install[1]..dein#install#_update[28]..<SNR>20_update_loop[5]..<SNR>20_install_async[9]..<SNR>20_done[7]..dein#install#_recache_runtimepath[20]..<SNR>20_helptags, line 12
[dein] Done: (2017/01/08 00:38:24)
Press ENTER or type command to continue^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

**Comment by wsdjeg** [comment]
I also get same issue, it is due to leadf's duplicate tag in help file.
cc @Yggdroot

**Comment by Yggdroot** [comment]
Sorry, I'll fix it soon.

**Comment by Shougo** [comment]
I have fixed the error.
Please update deoplete.

**Comment by wsdjeg** [comment]
Thanks, it ok now, clossing.
