### ISSUE TITLE
deleting a buffer closes vim

### ISSUE THREAD

**Issue by bonds** [wsdjeg/SpaceVim#521]
# Expected behavior, english is recommend

If multiple buffers are open and I delete one of them, the remaining buffers should remain open, and the active buffer should become the next highest buffer, i.e. if you have buffers 1 to 5 and you select buffer 3 and delete it, the active buffer becomes what used to be buffer 4 (and is now buffer 3 after the previous buffer 3 was deleted).

## Environment Information
- OS: OpenBSD 6.1
- vim version: 
- neovim version: NVIM v0.2.0-1501-g51a2d8dc
- SpaceVim version: 103d4f9c26128354479f0bfe5cdc85ef16b573c8

## The reproduce ways from Vim starting (Required!)

1. launch vim
1. open several buffers
1. notice that you have more than one buffer listed in your top bar
1. type ````:bd<enter>```` to delete a buffer
1. notice that vim closes, instead of remaining open and only deleting the one buffer you meant to delete

### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['Shougo/vimproc.vim', {'build': 'gmake'}], ['enomsg/vim-haskellConcealPlus', {'on_ft': 'haskell'}], ['/home/scott/src/neomake'], ['tpope/vim-commentary'], ['junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}], ['junegunn/fzf.vim']]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_plugin_manager = 'dein'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = [['Shougo/vimproc.vim'], ['neomake/neomake'], ['scrooloose/nerdcommenter'], ['albfan/ag.vim'], ['ctrlpvim/ctrlp.vim']]
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'linux', 'lang#php', 'lang#c', 'incsearch', 'lang#lua', 'lang#perl', 'lang#swig', 'lang#rust', 'lang#java', 'lang#javascript', 'lang#vim', 'lang#python', 'lang#xml', 'lang#haskell', 'lang#elixir', 'tools#screensaver', 'shell', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_dein_installed = 1
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/scott/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(nvim)
version: 704
OS: Linux
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log

```

## Screenshots

https://asciinema.org/a/a2pd9w54bvacd62b81bmfiq67

**Comment by wsdjeg** [comment]
It is feature of vim, when use `:bd` command, current windows and the windows which has current buffer within it  will be cloased,  as it is shown in the vedio, you have two windows, one is buffer, another is vimfiler, so if you run `:bd`, the vimfiler will be the last buffer, and it will be closed.

I recommend you to close current buffer via `sQ`, it is a default normal mappings in SpaceVim. and it will not close vim, it will close current buffer, and open last top buffer. if current buffer is the last one, a new buffer will be opened.

**Comment by bonds** [comment]
I don't think that's correct. If I open several buffers in vim and then delete one, vim stays open and goes to the next remaining buffer. I demonstrate this here, with no vimrc:

https://asciinema.org/a/3rjqd3o3wtcffs64wp78ocmlp

**Comment by wsdjeg** [comment]
if you have more than one windows, `:bd` will close all windows which has current buffer in it.
so if you run `:bd`, current windows will be close, and vimfiler buffer will be the last windows.

but SpaceVim have a autocmd for vimfiler to check if vimfiler is the last windows, if it is last windows, close it.

**Comment by wsdjeg** [comment]
```vim
  autocmd BufEnter * if (!has('vim_starting') && winnr('$') == 1 && &filetype ==# 'vimfiler') |
        \ q | endif
```

here is why vim will autoclose when run `:bd`.

**Comment by bonds** [comment]
Got it. Well, I guess I was expecting ````:bd```` to do what ````sQ```` is doing. I'll just use ````sQ```` as you said, but other vim users may be surprised like I was. Thanks for your consideration!

**Comment by tofuhead** [comment]
I found this issue because I had the same problem, SpaceVim closing up when doing :bd. 
well, the thing is, for me it seems to do the same thing even if I use "sQ" 

.b

**Comment by emctague** [comment]
Echoing @tofuhead here, `sQ` is forcing SpaceVim to close for me even if I open multiple files, same with `:q` and `:bd`.

**Comment by wsdjeg** [comment]
This issue is too old, to delete a buffer, you should use `SPC b d`, and if you want to close windows, use `q`.
