### ISSUE TITLE
Request colorscheme Nord to be put into spacevim

### ISSUE THREAD

**Issue by Simbaclaws** [wsdjeg/SpaceVim#524]
I'd like to request that the colorscheme "nord" will be put into spacevim, I'm using it for all my terminals currently. It would be nice if this would be added to spacevim. I saw in the faq that I should create a PR for requesting new themes... Not sure what a PR is but I suppose it's an issue on github? My apoligies if I'm too much of a noob to understand simple things...

a link to nord can be found here: https://github.com/arcticicestudio/nord-vim

**Comment by wsdjeg** [comment]
this colorscheme looks very nice, I also want to add it, so, can you send a PR?

just add it to : 

https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/layers/colorscheme.vim
