### ISSUE TITLE
phpcd.vim:  Building failed

### ISSUE THREAD

**Issue by Kpjas** [wsdjeg/SpaceVim#527]
## Expected behavior
Correct installation of the plugin

## Environment Information
- OS: Linux
- vim version: 8.0 
- neovim version: 0.2.0

## The reproduce ways from Vim starting
Error message see below
 

>        phpcd.vim:  Building failed 

During SpaceVim installation and
:SPUpdate

**Comment by wsdjeg** [comment]
see https://github.com/SpaceVim/SpaceVim/blob/dev/docs/layers/lang/php.md for System requirement.
