### ISSUE TITLE
Edit A New File but happens Unknown function: systemlist

### ISSUE THREAD

**Issue by nickChenyx** [wsdjeg/SpaceVim#533]
## Expected behavior, english is recommend
want to use SpaceVim to write a demo,  use `curl -sLf https://spacevim.org/install.sh | bash -s install vim` to install.

## Environment Information
- OS: centos 7.2
- vim version: VIM - Vi IMproved 7.4
- neovim version: /

## The reproduce ways from Vim starting (Required!)
just  `vim SpaceVimDemo` (SpaceVimDemo is not already exits)

## Output of the ':SPDebugInfo!'
please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.
```
Error detected while processing function SpaceVim#commands#install_plugin..SpaceVim#plugins#manager#install..<SNR>72_install..16..<SNR>73_systemlist:
line    4:
E117: Unknown function: systemlist
Press ENTER or type command to continue
Error detected while processing function SpaceVim#commands#install_plugin..SpaceVim#plugins#manager#install..<SNR>72_install..16..<SNR>73_systemlist:
line    4:
E15: Invalid expression: a:0 == 0 ? systemlist(excmd) : systemlist(excmd, a:1)
```

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
![](http://i1.piimg.com/588926/72826d97b010d7b4.png)

**Comment by Shougo** [comment]
Your Vim seems old.
systemlist() is implemented in Vim 7.4.248.
