### ISSUE TITLE
Hang in opening php file in windows

### ISSUE THREAD

**Issue by Mofiqul** [wsdjeg/SpaceVim#534]
I am getting problem in opening php files in fresh install of spacevim, whenever I try to open a php file it hangs and become unresponsive and I can not do anything unless I restart my vim.

- OS: Windows 7
- vim version:8.0

**Comment by wsdjeg** [comment]
What is `:SPDebugInfo!`?

**Comment by wsdjeg** [comment]
close, if you can provide more info about this issue, it will be easy to reproduce.

**Comment by lhyaax** [comment]
I have same problem...
