### ISSUE TITLE
Can not change firefox to  chromium to preview markdown

### ISSUE THREAD

**Issue by lsk-boy-f** [wsdjeg/SpaceVim#539]
I added these code in the profile `~/.SpaceVim.d/init.vim`
```
let g:mkdp_path_to_chrome= 'chromium-browser'
```
but I found it don't work as the preview command use firefox to preview.

Then I found something in the file `SpaceVim/autoload/SpaceVim/layers/lang/markdown.vim`

```
if executable('firefox')
        let g:mkdp_path_to_chrome= 'firefox'
endif
```

How can I overide the variable ?

## Environment Information
- OS: Ubuntu 16.04 64bit / Linux 4.10.1-041001-generic
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 22 2016 18:12:20)

**Comment by wsdjeg** [comment]
you have both chrome and firefox installed?

**Comment by lsk-boy-f** [comment]
Yes. As below:
```
$ which firefox 
/usr/bin/firefox
 ~ [11:05:57]
$ which chromium-browser  
/usr/bin/chromium-browser
```

**Comment by wsdjeg** [comment]
This patch should fix the issue
```diff
- if executable('firefox') 
-     let g:mkdp_path_to_chrome= 'firefox'
-  endif 
+ if executable('firefox')
+     let g:mkdp_path_to_chrome= get(g:, 'mkdp_path_to_chrome', 'firefox')
+ endif 
```

**Comment by lsk-boy-f** [comment]
:smile:  Thanks, it solve the problem.

But I get another issue:
When I start to preview the markdown ,  the broswer open a tab, but  it show nothing until I scroll the md file in vim. Like this:
![](http://ww1.sinaimg.cn/large/a794ab9bly1ffo6x0zdanj21gg0pujrc.jpg)

**Comment by wsdjeg** [comment]
I think it maybe issue with that plugin, but I can not fix it, BTW, It works well with firefox.

**Comment by lsk-boy-f** [comment]
Maybe it's the plugin's issue, I met the same issue in the firefox, :cry: 

Now you can close the issue. Thanks very much.

**Comment by wsdjeg** [comment]
I will close it when that patch be merged :]
