### ISSUE TITLE
Generate markdown file for vim help file.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#545]
Hi @dbarnett :

we use google's vimdoc to generate help file automatically, now we need to generate markdown file from vim file or vim help file, any idea?

### why?

we use `docs/` as the root of spacevim.org, github will parser all the markdown files in this directory, and generate html files for the website. so I want to generate a markdown file in specified directory with specified name, for example:

```sh
# generate help file
vimdoc .
# generate help markdown file
vimdoc . -o docs/help/vimdoc.md
```

### what have been done?

I have search from google, what I get is : 

1. [vim-markdown-helpfile](https://github.com/mklabs/vim-markdown-helpfile): A vim plugin and cli tool to generate vim helpfile from markdown,  last update is 5 years ago.

2. https://github.com/google/vimdoc/issues/30, but it is an opened issue, and is to generate html not markdown

**Comment by dbarnett** [comment]
Actually we already had google/vimdoc#87 tracking markdown generation, but that's not implemented either. I'll comment on that issue with some more details.

**Comment by wsdjeg** [comment]
I found a project for generate html from doc file, http://www.sphinx-doc.org/en/stable/

and an example is https://vim-autoflake.readthedocs.io/en/latest/
