### ISSUE TITLE
Lisp support

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#546]
I just find a plugin https://github.com/l04m33/vlime

and I will create a lang#lisp layer

hi @l04m33

thanks for creatting vlime, I want to use this plugin in lang#lisp layer, as I know you are a chinese, can we talk more about this layer?

for language layer, I think we should support:
- completion
- syntax checking, we use neomake
- format, we use neoformat

**Comment by l04m33** [comment]
太好了， SpaceVim 能集成 Vlime 的話， Vlime 也能有多些用戶，這應該不是壞事 ：）

我自己並沒有用過 SpaceVim ，所以需要些時間了解一下，你能給我個方向或者相關文檔麼？

至於你說的對 language layer 的要求， Vlime 的情況是這樣的：

* 有自動補全機制；
* 沒有語法檢查功能，因為寫 Common Lisp 的工作流一般是直接編譯文件然後看編譯器輸出（編譯過程是通過調用 Swank 服務器的 API 實現的，這和 neomake 調用外部程序的做法不同），而且市面上沒有通用的 linter；
* 自動格式化僅限於調整縮進，這是參照 Emacs 的做法，根據 Swank 提供的數據用 Vimscript 實現的，也和 neoformat 調用外部程序的做法不同。

PS: 似乎你也說中文，我就直接用中文回覆了。當然如果你希望在這裡用英文交流也是沒問題的 ：）

**Comment by wsdjeg** [comment]
感谢， 首先我需要对这个插件近一步了解下，我来新建一个layer，具体的，我们再来讨论。

**Comment by wsdjeg** [comment]
我安装了所有依赖： cli 执行截图 如下：

![2017-05-21-22 15 10](https://cloud.githubusercontent.com/assets/13142418/26284667/7c0f0764-3e73-11e7-8f16-17adc8872ca5.png)

下面来测试插件。

**Comment by wsdjeg** [comment]
nvim 下运行完美，不过有一个问题，我貌似补全不是自动的，需要手动， 可能是deoplete的lisp 补全启动表达式我设置的不对。

![2017-05-21-22 29 36](https://cloud.githubusercontent.com/assets/13142418/26284778/6a39a542-3e75-11e7-83ca-57abccea8a7b.png)

总之，可以正常工作了。

下面我新建一个PR，具体需要解决的问题会在PR中体现。

**Comment by l04m33** [comment]
> 我貌似补全不是自动的，需要手动

Vlime 的「自動補全」要用 `<Tab>` 或者 `<C-x><C-o>` 觸發，是這個意思嗎？還是說這些鍵位工作不正常？ Vlime 的補全比較特別，是用 `omnifunc` + `complete()` 實現的，我不清楚會不會對 deoplete 的補全有影響。

另外 Vlime 會跳過有衝突的鍵位，如果有默認鍵位工作不正常的話，可以檢查一下 `g:vlime_skipped_mappings` 變量（ `:help g:vlime_skipped_mappings` 有說明）

**Comment by wsdjeg** [comment]
我明白这个补全的原理，目前我选做的就是设置下deoplete针对lisp的参数，让其自动补全，和模糊匹配，而不是需要手动启动补全。比如在JAVA中，我在变量后面输入点号，就会自动展开该变量所有的函数，然后我可以模糊匹配输入并选择其中某个函数。晚些时候我可以录个视频。

另外, spacevim针对语言的快捷键都是Space l 开头的，我可能需要对快捷键在做个定制，我看了下你插件的实现，应该是在不同窗口有不同的一套快捷键，我想问的是这些窗口的filetype有没有设置？

**Comment by l04m33** [comment]
嗯我明白你的「自動補全」的概念，看來是之前我們對「自動」的定義不一樣 ：） 我猜就是這樣，以防萬一跟你確認一下是不是 Vlime bug 了而已，不需要錄視頻，我們用你的這個定義就可以了。

>　我想问的是这些窗口的filetype有没有设置？

有的， `:help vlime-mappings-remap` 裡有所有窗口的 filetype 列表。

**Comment by wsdjeg** [comment]
@l04m33 请问你对于vim的autoload特性了解吗，能不能将plugin中的这些方法都移到autoload里面，这样可以加快插件启动速度，而且 大写开头的方法，确实不怎么推荐，你可以参考下google的viml 代码规范。如果需要，我可以尝试提交PR

**Comment by wsdjeg** [comment]
快捷键相对比较多，我借助 SpaceVim 的快捷键导航系统，做了一个导航功能，可以看下这个视频：

[![asciicast](https://asciinema.org/a/azjyuqrm48lafd7xrel20h1zn.png)](https://asciinema.org/a/azjyuqrm48lafd7xrel20h1zn)

**Comment by l04m33** [comment]
> 能不能将plugin中的这些方法都移到autoload里面

有這個計劃。我還想要同時梳理一下 API 的，工作量比較大，應該要花些時間。我先搞一搞，差不多了再 ping 你，這樣 OK 不？

> 我借助 SpaceVim 的快捷键导航系统，做了一个导航功能

看著不錯！這些快捷鍵是放在 SpaveVim 這邊還是需要 merge 到 Vlime 裡？ 是手動一個一個 remap 的嗎？我是不是可以在 Vlime 這邊做點什麼，方便你 remap 這些快捷鍵？

**Comment by wsdjeg** [comment]
> 我先搞一搞，差不多了再 ping 你，這樣 OK 不？

没问题




> 看著不錯！這些快捷鍵是放在 SpaveVim 這邊還是需要 merge 到 Vlime 裡？ 是手動一個一個 remap 的嗎？我是不是可以在 Vlime 這邊做點什麼，方便你 remap 這些快捷鍵？

这个是 SpaceVim 自带的功能，不需要merge到 vlime里面，实际上，我也就是remap了下，我可以通过修改 vlime 中控制默认映射的 全局变量，我记得，mapping.vim 里面会检测是否存在全局变量，如果不存在，才定义的，不需要在 vlime 里面修改什么。

不过我倒是在测试这个插件的时候，发现在neovim中启动新服务端失败，以下是 `\rr` 结果：

```
Reading from channel output...

/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `sbcl --load /home/wsdjeg/.cache/vimfiles/repos/github.com/l04m33/vlime/lisp/load-vlime.lisp --eval (vlime:main)'
```

**Comment by l04m33** [comment]
> 不过我倒是在测试这个插件的时候，发现在neovim中启动新服务端失败，以下是 `\rr` 结果：

這是個 bug ， l04m33/vlime@36504c53e0ee5a8a2ed8a0cda50a79f163a3b7d0 應該修好了

**Comment by wsdjeg** [comment]
Thanks, :]

**Comment by wsdjeg** [comment]
@l04m33 我基本上已经修改了这个模块，但是SpaceVim本身可能还有一些需要修改，这个问题可以close了，谢谢。
