### ISSUE TITLE
SPC e c clear all errors does not work.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#547]
@blueyed

does neomake have function for clear all errors ( and close qf window)?

I have read the doc of neomake, I can not find the function for this feature.

**Comment by blueyed** [comment]
Not really / easily.

I've created https://github.com/neomake/neomake/issues/1342.  Please review, if that's what you need.

**Comment by wsdjeg** [comment]
@blueyed  I  just use `sign unplace *` and `call setloclist(0, [])` this two command will clear sign and locationlist, but it can not clear warnning message when move cursor to the error line.

**Comment by wsdjeg** [comment]
I mark this issue as v0.5 milestones, will implement this feature before v0.5.0 is released.
