### ISSUE TITLE
for gradle project, Neomake doesn't work for java syntax checker

### ISSUE THREAD

**Issue by iquicktest** [wsdjeg/SpaceVim#552]
## Expected behavior, english is recommend
for gradle project, Neomake doesn't work for java syntax checker

## Environment Information
- OS:  MAC
- vim version: vim 8
- neovim version: NVIM v0.2.0

## The reproduce ways from Vim starting (Required!)
1. open a gradle project
2. try to save a script with syntax checker
3. nothing happen.

## Output of the ':SPDebugInfo!'

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_custom_plugins = [['plasticboy/vim-markdown', {'on_ft': 'markdown'}], ['davidhalter/jedi-vim'], ['lambdalisue/vim-gita']]
g:spacevim_buffer_index_type = 1
g:spacevim_error_symbol = '✖'
g:spacevim_max_column = 120
g:spacevim_vim_help_language = 'en'
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_enable_neomake = 1
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_warning_symbol = '⚠'
g:spacevim_realtime_leader_guide = 1
g:spacevim_denite_leader = 'F'
g:spacevim_enable_cursorline = 1
g:spacevim_leader_guide_vertical = 0
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_hiddenfileinfo = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = ','
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_debug = 1
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_autocomplete_method = 'ycm'
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_enable_ycm = 1
g:spacevim_neobundle_installed = 0
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_automatic_update = 1
g:spacevim_src_root = 'E:\sources\'
g:spacevim_enable_powerline_fonts = 1
g:spacevim_simple_mode = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_guifont = ''
g:spacevim_language = ''
g:spacevim_plugin_bundle_dir = '~/.cache/vimfiles'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_colorscheme_default = 'desert'
g:spacevim_statusline_separator = 'arrow'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_enable_neocomplcache = 0
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_unite_leader = 'f'
g:spacevim_disabled_plugins = []
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'naviga
tion', 'misc', 'core', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'osx', 'incsearch', 'lang#lua', 'lang#java', 'lang#javascript', 'lang#vim', 'lang#python', 'lang#xml', 'tools#sc
reensaver', 'shell', 'colorscheme', 'core#banner', 'core#statusline', 'core#tabline']
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_leader_guide_hspace = 5
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.2.0/bin/nvim)
version: 704
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

Here is the result from ps -ef | grep java:
/Library/Java/Home/bin/java -Xdock:name=Gradle -Xdock:icon=/Users/myname/Dropbox/Project-MobileTestSuite/media/gradle.icns -Dorg.gradle.appname=gradlew -classpath /Users/myname/Dropbox/project/MobileTestSuite/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain -q -I /var/folders/rz/_n4xmn116vbg9s6dxxk6ssv40000gn/T/nvim4RkQg3/2 classpath

## Screenshots


If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by wsdjeg** [comment]
any example project, I will test it.

BTW, it should be issue with neomake.

**Comment by iquicktest** [comment]
hi bro, just create a gradle project, open it by spacevim and it doesn't work. I already tried maven can work. but gradle cannot work.  If it is a issue, any work around for that before fixed?

**Comment by wsdjeg** [comment]
I think you should make sure you have `./gradlew` executeable

here is how gradle project get classpath
```
                let f = tempname()
                if s:is_windows
                    let gradle_cmd = '.\gradlew.bat'
                else
                    let gradle_cmd = './gradlew'
                endif
                call writefile(["allprojects{apply from: '" . g:neomake_java_checker_home . s:psep. 'java'. s:psep. "classpath.gradle'}"], f)
                let ret = system(gradle_cmd . ' -q -I ' . shellescape(f) . ' classpath' )
                if v:shell_error == 0
                    let cp = filter(split(ret, "\n"), "v:val =~# '^CLASSPATH:'")[0][10:]
                    if filereadable(getcwd() . s:psep . 'build.gradle')
                        let out_putdir = s:GlobPathList(getcwd(), join(
                                    \ ['**', 'build', 'intermediates', 'classes', 'debug'],
                                    \ s:psep), 0)
                        for classes in out_putdir
                            let cp .= s:ClassSep() . classes
                        endfor
                    endif
                else
                    let cp = ''
                endif
```

https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/java.vim

**Comment by wsdjeg** [comment]
@iquicktest what is your gradle command? do you use `./gradlew builde`?

**Comment by shoemakerdr** [comment]
Hi! I'm having the same issue. Getting a lot of `cannot find symbol` errors I'm not exactly sure how to configure my `gradle.build` to work with the classpath. When I open a gradle project I get a message that says `Gradle classpath built successfully`, but when I check, the classpath is just an empty string.

**Comment by shoemakerdr** [comment]
For reference, this is the repo I'm trying to use it with: https://github.com/shoemakerdr/tictactoe-java

**Comment by wsdjeg** [comment]
@shoemakerdr ok, I will test this repo.

**Comment by shoemakerdr** [comment]
So it looks like it is making the classpath. Looking under `~/.cache/javacomplete2/classpath` there's a file that has the correct classpath. I can't figure out why I'm getting all these errors if the classpath is set correctly. Not sure where to go with this one.

**Comment by shoemakerdr** [comment]
Ok, so the `Gradle classpath built successfully` is from [javacomplete](https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete/classpath/gradle.vim#L49). It looks like for some reason NeoMake's javac classpath isn't being set.

**Comment by shoemakerdr** [comment]
Ok, after looking at the log for this, I've realized this is 100% a Neomake issue. I'll open an issue there, so you can close this one.

**Comment by wsdjeg** [comment]
OK
