### ISSUE TITLE
How to add C++11 syntax check

### ISSUE THREAD

**Issue by ChenKexiong** [wsdjeg/SpaceVim#555]
## Expected behavior, english is recommend
The bottom of spacevim popped up errors when I edit a cpp file with C++11 features.

## Environment Information
- OS: Ubuntu 16.04LTS
- vim version: 7.4

## The reproduce ways from Vim starting (Required!)
Input following code with newly installed spacevim. Then input ":w" and press Enter to save the file.
```cpp
#include <iostream>
#include <memory>

int main(void)
{
    std::shared_ptr<int> p = std::make_shared<int>(2333);
    std::cout << *p << std::endl;
    return 0;
}
```

## Output of the ':SPDebugInfo!'
How to get output of the ':SPDebugInfo!' ????
please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

## Screenshots
![2017-05-23 18-28-44](https://cloud.githubusercontent.com/assets/7435196/26350486/f13eeab8-3fe5-11e7-8edd-aec9c741204b.png)

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/issues/176

**Comment by wsdjeg** [comment]
```
let g:neomake_cpp_enable_markers=['clang']
let g:neomake_cpp_clang_args = ["-std=c++11", "-Wextra", "-Wall", "-fsanitize=undefined","-g"]
```
this does not work for me. hmm I do not use c++, need help though.

**Comment by jetm** [comment]
It works for me with gcc and clang compilers.

For gcc use:
```vim
let g:neomake_cpp_enable_markers=['g++']
let g:neomake_cpp_clang_args = ["-std=c++11"]
```
For clang use: 
```vim
let g:neomake_cpp_enable_markers=['clang']
let g:neomake_cpp_clang_args = ["-std=c++11"]
```
@wsdjeg: the extra settings beside `-std=c++11` are not neccessaries. This one tell to the compiler use the libs and includes for C++11.

**Comment by jetm** [comment]
@ChenKexiong: from your image, I think you are using syntastic plugin. I recommend you use neomake: `let g:spacevim_enable_neomake = 1` and combine with above setting to let the compiler work with c++11 syntax as is expected.

**Comment by wsdjeg** [comment]
@jetm `:Neomake clang` and `:Neomake gcc` works well with these config. but `:Neomake` still get errors, 
`echo g:neomake_cpp_enable_markers` show me `['clang']`, but `clangcheck` maker still running.

ok it should be `let g:neomake_cpp_enabled_makers=['clang']`

**Comment by zhewang95** [comment]
I added 
`
let g:neomake_cpp_enabled_makers=['g++']
let g:neomake_cpp_clang_args = ["-std=c++11"]
`
to my ~/.SpaceVim.d/init.vim, but I get `Neomake: [1.-:3] Invalid maker name: "g++".` error.  
I also try to change `g++` to `gcc` but the `-std=c++11` don't make effect, I still get errors about c++11 features.

But when I change g++ to `clang` and install clang on my `Ubuntu`, neomake work properly...
