### ISSUE TITLE
new file's fileencoding is null

### ISSUE THREAD

**Issue by KnightPublic** [wsdjeg/SpaceVim#557]
## Expected behavior, english is recommend

```
:$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 20 2017 01:03:47)
Included patches: 1-494
:$ vim a.sh
 NORMAL | master | a.sh                                           | sh |     | 100%   0/1 :  1
:set fileencoding?
  fileencoding=
```

## Environment Information
- OS: Windows
- vim version: 
- neovim version: null

## Output of the ':SPDebugInfo!'

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by wsdjeg** [comment]
I can not reproduce this issue, can you test it with latest version of SpaceVim.

**Comment by KnightPublic** [comment]
The latest version does not have this proble.

**Comment by wsdjeg** [comment]
so can be closed?

**Comment by KnightPublic** [comment]
Yes
