### ISSUE TITLE
Question: Can't override SpaceVim key map

### ISSUE THREAD

**Issue by sheharyarn** [wsdjeg/SpaceVim#566]
I switched to `SpaceVim` for the first time this week, and it broke a lot of my vim configs. I've been able to get most of them to work after going through the docs and changing some things, but some of my keymaps still aren't working with `vim` / `macvim` but do work with `neovim` / `VimR` / `neovim.app`.

Since it only works with neovim variants, I think it overrides the Denite maps, but doesn't do the same with Unite ones. I'm mapping <kbd>Leader</kbd><kbd>[</kbd> and <kbd>Leader</kbd><kbd>]</kbd> to switch to the next/previous tabs; I've have also tried mapping them directly in vim, but they still don't work:

```vim
noremap <Leader>[ :tabprev<CR>
noremap <Leader>] :tabnext<CR>
```
and calling them gives this:

```
[tag] Caching Done!                                                                                                                                                            [
unite.vim] unite buffer "default" candidates are empty
Press ENTER or type command to continue
```

<img width="983" alt="screen shot 2017-05-27 at 5 06 26 pm" src="https://cloud.githubusercontent.com/assets/2355108/26524470/f456f790-4300-11e7-89e3-4f55fdb8005f.png">

## Expected behavior

Should switch the next or previous tabs on hitting <kbd>Leader</kbd><kbd>[</kbd> and <kbd>Leader</kbd><kbd>]</kbd>

## Environment Information

- **OS:** MacOS Sierra (Version 10.12.4)
- **Vim:** Version 8.0 (2016 Sep 12, compiled Jan 28 2017 08:02:52)
- **MacVim:** Version 8.0 (2016 Sep 12, compiled May  8 2017 15:44:54)

## Reproduce Issue

You can try setting the map yourself in vim. Alternatively, you can download my [vim dotfiles here](https://github.com/sheharyarn/dotfiles/tree/master/Vim) and follow the steps mentioned to get my exact setup.

## :SPDebugInfo!

```viml
### SpaceVim Options :

g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_custom_plugins = [['jistr/vim-nerdtree-tabs'], ['vim-airline/vim-airline'], ['vim-airline/vim-airline-themes']]
g:spacevim_error_symbol = 'x'
g:spacevim_running = 1
g:spacevim_max_column = 120
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_enable_neomake = 1
g:spacevim_warning_symbol = '!'
g:spacevim_realtime_leader_guide = 0
g:spacevim_denite_leader = 'F'
g:spacevim_enable_cursorline = 1
g:spacevim_leader_guide_vertical = 0
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme = 'onedark'
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_hiddenfileinfo = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_buffer_index_type = 3
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_debug = 1
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_enable_ycm = 0
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_neobundle_installed = 0
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_enable_powerline_fonts = 1
g:spacevim_simple_mode = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_guifont = ''
g:spacevim_language = ''
g:spacevim_plugin_bundle_dir = '/Users/Psy/.cache/vimfiles/'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'NerdTree'
g:spacevim_statusline_separator = 'arrow'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_enable_neocomplcache = 0
g:spacevim_dein_installed = 1
g:spacevim_unite_leader = 'f'
g:spacevim_disabled_plugins = []
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'ctrlp', 'autocomplete', 'vim', 'osx', 'shell', 'incsearch', 'tools#screensaver', 'lang#c', 'lang#xml', 'lang#vim', 'lang#elixir', 'lang#python', 'lang#javascript', 'colorscheme', 'core#banner']
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_leader_guide_hspace = 5


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/usr/local/Cellar/macvim/8.0-124/MacVim.app/Contents/MacOS/Vim)
version: 800
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gik, or build from sources.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

[ SpaceVim ] : logger file /Users/Psy/.cache/SpaceVim/SpaceVim.log does not exists, only log for current process will be shown!
```

**Comment by wsdjeg** [comment]
SpaceVim has it's own mappings for tab jump:

#### Unimpaired bindings

Mappings | Description
-------- | -----------
`[ SPC` | Insert space above
`] SPC` | Insert space below
`[ b` | Go to previous buffer
`] b` | Go to next buffer
`[ f` | Go to previous file in directory
`] f` | Go to next file in directory
`[ l` | Go to the previous error
`] l` | Go to the next error
`[ c` | Go to the previous vcs hunk
`] c` | Go to the next vcs hunk
`[ q` | Go to the previous error
`] q` | Go to the next error
`[ t` | Go to the previous frame
`] t` | Go to the next frame
`[ w` | Go to the previous window
`] w` | Go to the next window
`[ e` | Move line up
`] e` | Move line down
`[ p` | Paste above current line
`] p` | Paste below current line
`g p` | Select pasted text

**Comment by wsdjeg** [comment]
if you want to override some mappings, use a `autocmd VimEnter`

**Comment by sheharyarn** [comment]
I tried this, but it doesn't work either:

```vim
autocmd VimEnter * nnoremap <Leader>[ :tabprev<CR> 
```

Also is there a command or a documentation page that lists all spacevim maps? I didn't find anything in `:h spacevim`

**Comment by jetm** [comment]
@sheharyarn: `SPC ?` shows all SpaceVim maps and `SPC h SPC` shows SpaceVim help. Just press down `SPC` and you will see a guide to follow by actions; this is the beauty of SpaceVim.

**Comment by wsdjeg** [comment]
@sheharyarn fixed. leader [ and leader ] mapping should works now.

**Comment by apgrc** [comment]
Overwrite works for SpaceVim default keys using VimEnter or with bootstrap before/after only if the key map is pressed before the guide appears. After the guide appears, then the default SpaceVim command is executed.

Also, the text on the guide only updates for unassigned key maps. Default key maps does not get updated on overwrite.
