### ISSUE TITLE
completion in gitcommit buffer.

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#567]
see:  https://github.com/neovim/neovim/commit/52727d98d76983f73e214369fe98ef541031395c

when edit a commit message, I hope we can complete the commit history. and the popmenu should looks like:
```
bc4a2e1576c6 help, man.vim: "outline" (TOC) feature #5169
58422f17d8e7 'guicursor' works in the TUI (and sends info to UIs) #6423
129f107c0c26 api: nvim_get_mode() #6247
0b59f988f447 api/ui: externalize tabline #6583
bc6d868d00a7 'listchars': `Whitespace` highlight group #6367
6afa7d66cd63 writefile() obeys 'fsync' option #6427
c60e409471c5 eval.c refactor (also improves some error messages) #5119
```
we can fuzzy match both the md5 number and the commit title.

@lambdalisue will gina support this feature?

**Comment by wsdjeg** [comment]
the complete item could be 
```json
{
"word" : "bc4a2e1576c6",
"abbr" : "bc4a2e1",
"menu" : "help, man.vim: 'outline' (TOC) feature #5169"
}
```

**Comment by wsdjeg** [comment]
hmm sorry, close now, we need get info from github's v3 APIs, so this is not the work of gina, will try to implement it locally.

**Comment by lambdalisue** [comment]
You can use https://github.com/lambdalisue/gina.vim/blob/master/autoload/gina/complete/commit.vim

Note that you need wrap functions and have to modify the candidates while the candidates is for Command completion and not for Input completion.
