### ISSUE TITLE
Error detected while processing function <SNR>28_tool

### ISSUE THREAD

**Issue by cinuized** [wsdjeg/SpaceVim#57]
after installing spacevim, when hit "i" for insert, encounter this error:
`Error detected while processing function <SNR>28_tool`
`E492: Not an editor command:         IndentLinesToggle`

same error when hit "I“, "O", "o", "a"

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/issues?utf8=✓&q=is:issue%20is:closed%20IndentLinesToggle%20

`call dein#install()` before use SpaceVim`

**Comment by wsdjeg** [comment]
well, I should enable checkinstall by defult.

**Comment by tracyone** [comment]
It will be user friendly if the plugins can be auto install at the first time of starting vim.

**Comment by wsdjeg** [comment]
@tracyone done

**Comment by wsdjeg** [comment]
but checkinstall take some time. It you are sure all plugins is installed, you can disable it by add `let g:spacevim_checkinstall = 0` in `~/.local.vim`
