### ISSUE TITLE
Nvim-qt The default window is too small

### ISSUE THREAD

**Issue by liuhuancom** [wsdjeg/SpaceVim#570]
## Environment Information
- OS:win7
- vim version: cmder vim 7.4.1721
- neovim version:0.4.0-dev

Click nvim-qt.exe to run the default window is too small 

![qqq 20170529121509](https://cloud.githubusercontent.com/assets/3874638/26536508/1786bf56-446a-11e7-87da-5d748f4a5856.png)

**Comment by wsdjeg** [comment]
see https://github.com/equalsraf/neovim-qt/issues/251

**Comment by liuhuancom** [comment]
```
nvim-qt.exe -qwindowgeometry 1400x900
```
