### ISSUE TITLE
f to move back and forward

### ISSUE THREAD

**Issue by saward** [wsdjeg/SpaceVim#571]
Hi,

I'm trying to give vim(neovim+spacevim) a serious try as my main editor, and looking through the various ways I can be better.

I'm trying to use 'f<char>' to skip forward and back.  This works with base vim and neovim, but with spacevim it doesn't.  I don't understand what's happening when I use 'f<char>', but it does have the word 'unite' down the bottom.

I'd like to navigate using 'f<char>' as happens in base vim, but I don't understand well enough what spacevim has done (or how to configure vim well enough yet) to know what to do to fix it.  Is there a way to restore the functionality?

Thanks!

**Comment by saward** [comment]
Actually, just noticed in the README this example:

    let g:spacevim_unite_leader = 'f'

Changing that restores functionality.  Is there a better leader option for unite that is not likely to conflict with other vim features?

**Comment by wsdjeg** [comment]
I do not use `f`'s origin func, if you do need this feature, add `let g:spacevim_unite_leader = ''` to you custom configration file.

for me I use `SPC j j` to quick jump to a char in current screen.

see : 

[![asciicast](https://asciinema.org/a/1y7q9xx5gia21v9i89lad709t.png)](https://asciinema.org/a/1y7q9xx5gia21v9i89lad709t)

and here is the doc:

##### Jumping

Key Binding | Description
----------- | -----------
`SPC j 0` | go to the beginning of line (and set a mark at the previous location in the line)
`SPC j $` | go to the end of line (and set a mark at the previous location in the line)
`SPC j b` | undo a jump (go back to previous location)
`SPC j d` | jump to a listing of the current directory
`SPC j D` | jump to a listing of the current directory (other window)
`SPC j f` | jump to the definition of an vim script function (TODO)
`SPC j i` | jump to a definition in buffer (denite outline)
`SPC j I` | jump to a definition in any buffer (denite outline)
`SPC j j` | jump to a character in the buffer (easymotion)
`SPC j J` | jump to a suite of two characters in the buffer (easymotion)
`SPC j k` | jump to next line and indent it using auto-indent rules
`SPC j l` | jump to a line with avy (easymotion)
`SPC j q` | show the dumb-jump quick look tooltip (TODO)
`SPC j u` | jump to a URL in the current buffer (TODO)
`SPC j v` | jump to the definition/declaration of an Emacs Lisp variable (TODO)
`SPC j w` | jump to a word in the current buffer (easymotion)(TODO)

**Comment by wsdjeg** [comment]
use `SPC j l` to quick jump to a line. BTW if you need Unite and `f`, you can use `\f`, it is same as `f`.

**Comment by saward** [comment]
I assume SPC is space?  If so, these commands do not seem to work for me in the manner you describe (spacevim for neovim).

**Comment by wsdjeg** [comment]
please update spacevim, I just merge this branch.

**Comment by wsdjeg** [comment]
@saward can you run `:SPCUpdate SpaceVim`?

**Comment by jetm** [comment]
I tested @wsdjeg and it works well the new jumping update. Thanks!
Also, the `\fN` as `\FN` works as expected as well.

**Comment by saward** [comment]
@wsdjeg just tried :SPCUpdate SpaceVim and it tells me "Not an editor command:  SPCUpdate SpaceVim".

The \fN works for me.

**Comment by saward** [comment]
Now that I pay attention more, pressing SPC j does come up with a panel at the bottom that appears to be accepting commands (and lists some options) and has [SPC] listed, so it may just be that I'm not understanding how to use it correctly.

**Comment by wsdjeg** [comment]
@saward your spacevim is too old. re run the installation bash command.

**Comment by saward** [comment]
I installed spacevim for the first time around a week ago, and ran an update in the last 24 hours.  Edit: by "update", I mean I reran the neovim install from the install.sh file.

**Comment by wsdjeg** [comment]
ohh, sorry it is :SPUpdate. you can complete this command via tab after :SP
