### ISSUE TITLE
E716 and E15: tabline colorscheme error

### ISSUE THREAD

**Issue by LFly3** [wsdjeg/SpaceVim#577]
## Expected behavior, english is recommend
About SpaceVim colorscheme bug
## Environment Information
- OS: Debian
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
when i edit vim-script type file and markdown  type file

## Output of the ':SPDebugInfo!'
As shown below, edit the configuration file will be an error, edit some other files will appear such a mistake, I am sorry I did not statistics the wrong file type
   ![](http://hexoblog.oss-cn-qingdao.aliyuncs.com/issue/colorscheme-error.png)

## Screenshots
Under normal circumstances to edit a C test file, after touch space+t+m+b then show me under information:
   ![](http://hexoblog.oss-cn-qingdao.aliyuncs.com/issue/tabline-colorscheme-normal.png)

edit markdown files, touch space+t+m+b tabline style as shown below:
   ![](http://hexoblog.oss-cn-qingdao.aliyuncs.com/issue/tabline-colorscheme-error.png)

## SpaceVim custom configuration files
my SpaceVim custom config files[github link address](https://github.com/urloong/dotfiles/blob/master/SpaceVim.d/init.vim)

**Comment by wsdjeg** [comment]
see #550 , please wait for #549 .

**Comment by LFly3** [comment]
thx😃，it’s working now！SpaceVim is very nice 👍, i luv it.
