### ISSUE TITLE
推荐中文自动格式化插件——pangu.vim

### ISSUE THREAD

**Issue by KnightPublic** [wsdjeg/SpaceVim#583]
[pangu.vim](https://github.com/hotoo/pangu.vim) 插件的主要功能（摘自 github）

> ### 功能
> - 中英文字符间增加一个半角空白。
> - 中文前后的半角标点转成全角标点。
> - 全角英文、数字转成半角字符。
> - 连续的句号自动转省略号。
> - 感叹号、问号最多允许连续重复 3 次。
> - 其他中文标点符号不允许重复出现。

参考的中文编辑规范：[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)

目前已知缺陷：

1. 一行内有多处匹配需要添加空格时，可能存在空格添加不完全的问题
1. 前台正则替换，会阻塞主窗口进程

推荐和 vim 的段落整理（[formattig](http://vimdoc.sourceforge.net/htmldoc/change.html#formatting)）进行整合，在对文章进行编写/修改后调用插件进行非规范纠正 + 自动段落整理。

**Comment by wsdjeg** [comment]
有好几个中文技术文档指南或者指北，我也在看，但是我觉得中文文档结构复杂，还是不要让插件自行修改内容为好，避免不必要的内容误删，我的建议是，开发一个仅仅提示错误位置的插件，类似于neomake等等这类语法检查插件，该插件我已初步实现框架，在  https://github.com/wsdjeg/vim-galore-zh_cn 中的 vim 脚本，主要用于检查该项目中的中文规范。

**Comment by wsdjeg** [comment]
we use remark for formatting text.
