### ISSUE TITLE
Extra unknown character between buffer index and file name

### ISSUE THREAD

**Issue by icearith** [wsdjeg/SpaceVim#586]
## Expected behavior, english is recommend

When open a new file, the filename and its corresponding buffer index should display on the tabling.

## Environment Information
- OS: 10.12.5 (16F73)
- vim version: 
- neovim version: NVIM 0.2.0

## The reproduce ways from Vim starting (Required!)

vim ~/.SpaceVim.d/init.vim

## Output of the ':SPDebugInfo!'

please post log below, if you want me reproduce your issue quickly, post your custom config here will be better.

configuration file: `~/.SpaceVim.d/init.vim`

```vim
" set SpaceVim colorscheme
let g:spacevim_colorscheme_bg = 'dark'
set background=dark
"let g:spacevim_colorscheme = 'one'
let g:one_allow_italics = 1 " I love italic for comments

"let g:spacevim_checkinstall = 1
let g:spacevim_enable_vimfiler_welcome = 0

" If you want to add some custom plugins, use these options:
let g:spacevim_custom_plugins = [
    \ ['terryma/vim-smooth-scroll'],
    \ ['derekwyatt/vim-scala', {'on_ft' : 'scala'}]
    \ ]

let g:spacevim_disabled_plugins=[
    \ ['tmux-navigator']
    \ ]

let vim_markdown_preview_github=1

let g:python_host_skip_check=1
let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_skip_check=1
let g:python3_host_prog = '/usr/local/bin/python3'
let g:ruby_host_skip_check=1


"let g:spacevim_lint_on_save = 0

noremap <silent> <c-u> :call smooth_scroll#up(&scroll, 0, 2)<CR>
noremap <silent> <c-d> :call smooth_scroll#down(&scroll, 0, 2)<CR>
noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 0, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 0, 4)<CR>

"set clipboard=unnamed
let g:mkdp_path_to_chrome = "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome"
```

## Screenshots
![screen shot 2017-05-31 at 5 13 25 pm](https://cloud.githubusercontent.com/assets/2555093/26642315/38a0afd2-4625-11e7-8587-62fee17a7d03.png)

**Comment by wsdjeg** [comment]
you can use `g:spacevim_enable_tabline_filetype_icon` to hide this icon. please update spacevim

**Comment by icearith** [comment]
@wsdjeg I pulled the latest commits, this icon disappeared. But I am wondering why this icon doesn't display correctly. I am sure I have UTF-8 enabled, because I have tested my tmux with utf-8 output, which works well.
