### ISSUE TITLE
Can't entirely disable the annoying `indentLine` plugin.

### ISSUE THREAD

**Issue by andyleejordan** [wsdjeg/SpaceVim#589]
## Expected behavior, english is recommend

Entirely disable the annoying `indentLine` plugin.

## Environment Information

- OS:OSX
- vim version:800
- neovim version:

## The reproduce ways from Vim starting (Required!)

Add to `~/.SpaceVim.d/init.vim`:
```
let g:spacevim_disabled_plugins = [
    \ ['Yggdroot/indentLine'],
    \ ]
```
Note: other settings in this file (like my theme) are picked up just fine.

### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.4.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'NeoSolarized'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['iCyMind/NeoSolarized']]
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 0
g:spacevim_hiddenfileinfo = 1
g:spacevim_gitcommit_pr_icon = 'p'
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = 'i'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = [['Yggdroot/indentLine']]
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = 'Hack'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'vim', 'osx', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/andrew/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/Applications/MacVim.app/Contents/MacOS/Vim)
version: 800
OS: OSX
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file /Users/andrew/.cache/SpaceVim/SpaceVim.log does not exists, only log for current process will be shown!
```
## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by andyleejordan** [comment]
FYI I removed `~/.cache/vimfiles/repos/github.com/Yggdroot/indentLine`, restarted Vim, and it reinstalled it.

**Comment by wsdjeg** [comment]
why this plugin need to be removed, have you try SPC h t i

**Comment by andyleejordan** [comment]
@wsdjeg Would still rather have it disabled; but okay, how would I set this permanently? (I.e. what variable does `SPC h t i` correspond to, and how would I find that out in the future?)

**Comment by wsdjeg** [comment]
hmm add `let g:indentLine_enabled = 0` to your custom config will disable this plugin by default.

**Comment by andyleejordan** [comment]
Thanks @wsdjeg!

**Comment by crisidev** [comment]
I would like to have this reopen and fixed in some way. If indentLine is disabled, it will still set the concellevel to 2, which mess up with various configurations where conceallevel should be 0.

**Comment by wsdjeg** [comment]
@crisidev  any reproduce step?

**Comment by crisidev** [comment]
For example I want vim json to show the quotes around string, which does not work if conceallevel is  > 0 and indentLine sets the level to 2, no matter what you do.

**Comment by wsdjeg** [comment]
you should use :verbose set conceallevel to see which plugin change it.

**Comment by crisidev** [comment]
I already checked and it is indentLines.

**Comment by crisidev** [comment]
I can print you the output if needed, but it is definitely indentLines. It does it also if let g:indentLine_enabled = 0 is set.

**Comment by wsdjeg** [comment]
hmm, I think maybe this is a bug of indentline, please report to the issue track of that plugin, I think when `g:indentLine_enabled == 0`, the conceallevel should not be changed.

**Comment by crisidev** [comment]
This should fix the issue:

```
let g:indentLine_enabled = 1
let g:vim_json_syntax_conceal = 0
let g:indentLine_noConcealCursor='nc'
let g:vim_json_syntax_conceal = 0
```

I will test it once home.

**Comment by crisidev** [comment]
I know it is an hack, but it comes from indentLines issue tracker and looks like it is the only one working. I'll keep you posted.

**Comment by crisidev** [comment]
This is the only configuration that works for me:
```
let g:indentLine_conceallevel = 0
let g:indentLine_concealcursor = 'nc'
let g:indentLine_setConceal = 0
let g:indentLine_enabled = 0
let g:indentLine_setColors = 0
```

**Comment by wsdjeg** [comment]
got it，thanks.

**Comment by dleen** [comment]
FYI this PR for indentLines: https://github.com/Yggdroot/indentLine/pull/240 seems to solve the issue for me by setting:

```
let g:vim_json_syntax_conceal = 0
```

in the `#before` SpaceVim hook.
