### ISSUE TITLE
How to setup? For 'List all the starred repos in github.com'

### ISSUE THREAD

**Issue by caoer** [wsdjeg/SpaceVim#590]
Hi, I think the documentation is missing. Not sure how to setup it. It shouldn't work if I did not enter the API key? since SpaceVim doesn't know who am I...

```
 fuzzy find and open the website of the repo. default key is <leader>ls 
```

**Comment by wsdjeg** [comment]
yeah, we need to update document.

**Comment by wsdjeg** [comment]
I have 586 starred repos, it take me some time to get the list, so first time you type `\ls` will take a long time.

**Comment by wsdjeg** [comment]
set `g:spacevim_github_username`.

**Comment by caoer** [comment]
![1__tmux__tmux__and_what_is_the_leader__ _issue__22_ _spacevim_spacevim](https://cloud.githubusercontent.com/assets/225856/26694642/1c94e20c-46d6-11e7-8367-d9993d278a91.png)

hi @wsdjeg  got this error, any clue?

**Comment by wsdjeg** [comment]
your starred repos is too many, and github's api only allow 60+/min, as I know. I am not sure how to fix it. how about only show 500+ repos instead of all repos.

**Comment by caoer** [comment]
I see. Currently, it freezes the vim for 10+ seconds which make it not very usable. Showing 500+ is good for me. That's most used stars.
but speak of implementation, I can think if we can cache the star repos in local, then the search will be instant, but that requires a lot of works and not sure if this functionality is used by many?
I'm willing to help but I know nothing about vim script. 😿

**Comment by wsdjeg** [comment]
ok, will try to add this feature.
