### ISSUE TITLE
What is this question mark?

### ISSUE THREAD

**Issue by caoer** [wsdjeg/SpaceVim#596]
![1__tmux__tmux_](https://cloud.githubusercontent.com/assets/225856/26694483/8f563512-46d5-11e7-87e1-971f794bf2b5.png)

A picture worth a million words.. see screen above. What is this question mark? I've tried to changed dozens of fonts but it still exists. Mono, Powerline, standarnd fonts they all have it... no clue.. 😢

**Comment by icearith** [comment]
@caoer this is the file icon, just pull the latest commits or run the update command to update the SpaceVim

**Comment by caoer** [comment]
@icearith hi, I did using the latest dev branch, not being able to see it. But since I know it is file type icon, going to disable it. 😄

**Comment by icearith** [comment]
@caoer I just suffered from this issue. please refer to #586

**Comment by caoer** [comment]
@icearith got it, gonna watch that issue. Thanks!

**Comment by wsdjeg** [comment]
@icearith here is all my installed font, 
```
wsdjeg:SpaceVim [ undowindow | ✔  ] ➭ pacman -Ss font | grep installed
extra/adobe-source-code-pro-fonts 2.030ro+1.050it-3 [installed]
extra/font-bh-ttf 1.0.3-3 [installed]
extra/fontconfig 2.12.1-4 [installed]
extra/fontsproto 2.1.3-1 [installed]
extra/freetype2 2.8-2 [installed]
extra/libfontenc 1.1.3-1 [installed]
extra/libotf 0.9.13-2 [installed]
extra/libxfont 1.5.2-1 [installed]
extra/libxfont2 2.0.1-1 [installed]
extra/libxft 2.3.2-1 [installed]
extra/noto-fonts 20170428-1 [installed]
extra/noto-fonts-cjk 20170512-1 [installed]
extra/noto-fonts-emoji 20170519-1 [installed]
extra/ttf-arphic-ukai 0.2.20080216.1-5 [installed]
extra/ttf-arphic-uming 0.2.20080216.1-5 [installed]
extra/ttf-bitstream-vera 1.10-11 [installed]
extra/ttf-cheapskate 2.0-11 [installed]
extra/ttf-dejavu 2.37-1 [installed]
extra/xorg-bdftopcf 1.0.5-1 (xorg xorg-apps) [installed]
extra/xorg-font-util 1.3.1-1 (xorg-fonts xorg) [installed]
extra/xorg-font-utils 7.6-4 [installed]
extra/xorg-fonts-alias 1.0.3-1 [installed]
extra/xorg-fonts-encodings 1.0.4-4 (xorg-fonts xorg) [installed]
extra/xorg-fonts-misc 1.0.3-5 [installed]
extra/xorg-mkfontdir 1.0.7-8 (xorg xorg-apps) [installed]
extra/xorg-mkfontscale 1.1.2-1 (xorg-apps xorg) [installed]
community/adobe-source-han-sans-cn-fonts 1.004-2 [installed]
community/opendesktop-fonts 1.4.2-4 [installed]
community/wqy-bitmapfont 1.0.0RC1-2 [installed]
community/wqy-zenhei 0.9.45-6 [installed]
```

and I think these is what you need:
```
extra/noto-fonts 20170428-1 [installed]
extra/noto-fonts-cjk 20170512-1 [installed]
extra/noto-fonts-emoji 20170519-1 [installed]
```

**Comment by wsdjeg** [comment]
```
wsdjeg:SpaceVim [ undowindow | ✔  ] ➭ pacman -Ss unicode | grep installed
core/icu 59.1-1 [installed]
core/libunistring 0.9.7-1 [installed]
core/perl 5.24.1-1 (base) [installed]
extra/fribidi 0.19.7-1 [installed]
extra/ttf-arphic-ukai 0.2.20080216.1-5 [installed]
extra/ttf-arphic-uming 0.2.20080216.1-5 [installed]
community/rxvt-unicode 9.22-2 [installed]
community/rxvt-unicode-terminfo 9.22-2 [installed]
```

**Comment by icearith** [comment]
@wsdjeg My environment is 
NeoVim
iTerm2
Tmux 

I installed `noto-fonts`, `noto-fonts-cjk`, `not-fonts-emoji`

After that, I change the font for non-ascii character to `noto mono for powerline`, it still didn't work. So I am gonna try the fonts you listed below. 

By the way , I find an interesting plugin: https://github.com/ryanoasis/vim-devicons which seems like what you want.

**Comment by wsdjeg** [comment]
hmm. Maybe it is the font you need. you can read the plugin'S readme.

**Comment by icearith** [comment]
Dear @wsdjeg & @caoer 

After several attempts, I got a simple solution. 

1. Clone this repository: https://github.com/ryanoasis/nerd-fonts

```shell
git clone git@github.com:ryanoasis/nerd-fonts.git
```
2. Install a patched font 

```shell
cd nerd-fonts

# This command will install all the patched fonts
./install 

or 

# Install a specific font , this command will install patched Meslo font, with Powerline and DevIcons
./install Meslo
```

3. After that, either set the GUI font in the Vim config or set the font for Non-Ascii character in iTerm2


4. Done

## Here is a screenshot

![screen shot 2017-06-03 at 1 17 47 pm](https://cloud.githubusercontent.com/assets/2555093/26753486/2a7900c6-485f-11e7-829e-5f25774f2b05.png)

**Comment by wsdjeg** [comment]
@icearith great!!!!

but as I can see in your picture, you nvim is not using true colors, you should use tmux 2.0 and run tmux via `tmux -2`.

**Comment by icearith** [comment]
@wsdjeg  I am also confused by this issue, because I have last Tmux 2.5 installed. The color scheme seems different from the screenshot in SpaceVim's document. 

I tested my true color setting, because to be honest, I don't know what True color is. the result is:

![screen shot 2017-06-03 at 1 50 56 pm](https://cloud.githubusercontent.com/assets/2555093/26753689/d1781e26-4863-11e7-8278-88233314627b.png)

```shell 
echo $TERM
```

The value is `xterm-256color`

Given the above facts, could you please help me distinguish what's wrong with my environment.

**Comment by wsdjeg** [comment]
see https://github.com/Gabirel/Hack-SpaceVim/issues/7

**Comment by caoer** [comment]
@icearith 24 bit color is awesome!
try to run this: https://github.com/gnachman/iTerm2/blob/master/tests/24-bit-color.sh
see if you can get a very smooth color line. 
true color has 24bit colors instead of 256.

![1__tmux__tmux_](https://cloud.githubusercontent.com/assets/225856/26754942/ea948c3a-4851-11e7-98ca-675bcdf7ee26.png)

Also checkout following post for setup. What's your $TERM inside tmux and outside of tmux? 
and make sure tmux info return Tc flag as ture. 
```
 tmux info | grep Tc
197: Tc: (flag) true
```

I've spent hours and hours on this issue. And the last found makes me cry. It was accidentally put tmux-254color instead of tmux-256color. So, be careful. 

https://bruinsslot.jp/post/how-to-enable-true-color-for-neovim-tmux-and-gnome-terminal/
https://sunaku.github.io/tmux-24bit-color.html

**Comment by icearith** [comment]
@wsdjeg @caoer  

I solved this problem with your help. Thank you :)
