### ISSUE TITLE
New Search Feature

### ISSUE THREAD

**Issue by zy-mimicry** [wsdjeg/SpaceVim#597]
### Vim New Feature Requirement
 > Search Feature

1. A shortcut key to call out the search window
2. After entering the desired keyword, the window disappears; the background worker thread performs the search;
3. Search does not affect the editing performance, can be edited normally
4. After the search is completed, give the status prompt, and can be achieved through the shortcut keys to wake up the search results;
5. Search results can be opened in a new window, and you can press the shortcut key to jump, you can preview, edit and save.

Thanks
zy-mcat

**Comment by wsdjeg** [comment]
SpaceVim will add this feature before v0.4.0 is released.

**Comment by wsdjeg** [comment]
@Shougo does unite/denite support this feature? if there is no such feature, I want to use job to implement it.

**Comment by Shougo** [comment]
@wsdjeg Unite/Denite has not the feature.  Because they does not support background tasks.

**Comment by wsdjeg** [comment]
Ok. thanks. I will start a new PR for searching background in spacevim.
