### ISSUE TITLE
How to load buffer?

### ISSUE THREAD

**Issue by caoer** [wsdjeg/SpaceVim#598]
After running SpaceVim for a few hours, it becomes very slow. I'm not sure how to debug it. But restart it makes it very fast.
But by doing so, all open buffers and tabs are gone. Is there an official to load previous saved buffer?
I'm seeing `[SPC] f S` to save all buffer, but not being able to find load all buffer option. 
Can we save and load tab as well?

**Comment by wsdjeg** [comment]
@caoer you need use vim with +lua feature, or use neovim with +py +py3 feature. when you save all buffers, you can list all buffers via `SPC b b`.
and you need to read doc for SpaceVim's tabline:

1. it will list all listed buffers when vim has only one tab
2. if there are more than one tab, will list all the tabs, and each item show the tabpagewin buffer name.

tabs or buffer? you can check it on the top right of the tabline, you will see `Tabs` or `Buffers`.

**Comment by caoer** [comment]
hi, @wsdjeg I think you misunderstood what I meant. I'm aware of the differences of Tab and Buffers.

I'm having trouble load previous `saved` buffer. (not sure if I'm using the term wrong). Take sublime as an example, if I opened 5 windows in sublime, and then my computer got a power failer, the system goes to reboot sequence. But the next time I open sublime (after rebooted), it will open my previous 5 windows for me, even with unsaved changes.

Is there any similar functionality in SpaceVim?

**Comment by wsdjeg** [comment]
@caoer I think it is called `session` in vim. so SpaceVim should also support session menager.

**Comment by caoer** [comment]
👍

**Comment by wsdjeg** [comment]
use `fn` to create new session, and `fs` to list all sessions, and fuzzy find the session by name,
