### ISSUE TITLE
没有可自行配置选项的文件

### ISSUE THREAD

**Issue by fedkey** [wsdjeg/SpaceVim#6]
spacevim的配置很丰富，然而，有些小众化的需求，可能不是所有的用户都需要的，加在spacevim配置文件里面，担心下次更新会消失。

希望能够提供一个可以自行配置选项的配置文件，这样不会影响到后期更新spacevim

感谢！

**Comment by wsdjeg** [comment]
目前SpaceVim载入的用户配置文件 是 `getcwd() . '/.local.vim`, 即为当前目录下的 `.local.vim`, 我现在打算加上另外一个功能，即支持`～/.local.vim`. 在这个文件中 可以是一些自己的私人全局配置。这样你看是否满足需求？

**Comment by fedkey** [comment]
谢谢，就是这样的功能。
