### ISSUE TITLE
how to use spacevim 

### ISSUE THREAD

**Issue by codesuper-god** [wsdjeg/SpaceVim#601]
## Expected behavior, english is recommended
I want use my spacevim to open multiple files.But whenever I open vim with the command vim *.c,I press the F3 key to open the file buffer. select a file to open,the emergence of this situatiojn .I don't know how to do it. 

## Environment Information
- OS:ubuntu 16.04
- vim version:vim 7.4
![image](https://cloud.githubusercontent.com/assets/24927547/26753819/81b14112-4834-11e7-9570-2df60a819723.png)

I do not want to cover the list of previously opened files. While the picture above the situation, so I do not know how to switch to the previous buffer. Please tell me a good way to manage multiple files.

**Comment by wsdjeg** [comment]
@codesuper-god  `vim *.c` will load all the c files in current directory, the all the file names will be listed on the tabline, this is feature of SpaceVim's tabline.  then open file explorer via `F3`, this will open `Vimfiler`, use `j/k` to move cursor in vimfiler, `o` to expand directory, `<Cr>` to open file. BTW you can use `'` to mark file in vimfiler, then use `<cr>` to open all marked files.

**Comment by codesuper-god** [comment]
Thank you so much!

**Comment by wsdjeg** [comment]
I think you can read our documentation,  https://github.com/SpaceVim/SpaceVim/blob/buffer/docs/documentation.md
