### ISSUE TITLE
what's happened?

### ISSUE THREAD

**Issue by dyfire** [wsdjeg/SpaceVim#603]
error message like this ,how to fix this ?
```
Error detected while processing function <SNR>180_doFold:
Error detected while processing function <SNR>180_doFold[1]..<SNR>180_doFold[2]..phpfold#Fold:
```

## Environment Information
- OS:
- vim version:
- neovim version:

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
how to you get this issue? what is the reproduce step?

**Comment by wsdjeg** [comment]
php file folds works well in vim and neovim, and I can not reproduce it.

**Comment by dyfire** [comment]
hi @wsdjeg ,

my os is  mac(os 10.12.2)
1. first install spacevim like this curl -sLf https://spacevim.org/install.sh | bash.
2.vim ,(start auto upgrade).
3.vim *.json,*.xml is well, but ,when i try to vim *.php, i got the problem,

Perhaps the only reason of my local php, so can u tell me how to disable phpfolds？

Best Regards.

**Comment by wsdjeg** [comment]
@dyfire can you copy the whole eary message, now the messege do not show me what the error is? you can use `:let @+=execute(':message')` to copy the message to clipboard, the paste here.

**Comment by dyfire** [comment]
@wsdjeg like this?
```
:^@Messages maintainer: Bram Moolenaar <Bram@vim.org>^@Error detected while processing function <SNR>180_doFold[2]..phpfold#Fold:^@line    2:^@E714: List required^@Error detected wh
ile processing function <SNR>180_doFold:^@line    1:^@E474: Invalid argument^@Error detected while processing function <SNR>180_doFold[2]..phpfold#Fold:^@line    2:^@E714: List requ
ired^@E714: List required^@Error detected while processing function <SNR>180_doFold:^@line    1:^@E474: Invalid argument^@Error detected while processing function <SNR>180_doFold[2]
..phpfold#Fold:^@line    2:^@E714: List required^@Error detected while processing function <SNR>180_doFold:^@line    1:^@E488: Trailing characters^@Error detected while processing f
unction <SNR>180_doFold[2]..phpfold#Fold:^@line    2:^@E714: List required^@E714: List required^@E714: List required^@Error detected while processing function <SNR>180_doFold:^@line
    1:^@E474: Invalid argument^@Error detected while processing function <SNR>180_doFold[2]..phpfold#Fold:^@line    2:^@E714: List required^@E714: List required^MError detected whil
e processing function <SNR>180_doFold:^Mline    1:^ME474: Invalid argument^MError detected while processing function <SNR>180_doFold[2]..phpfold#Fold:^Mline    2:^ME714: List requir
ed^MError detected while processing function <SNR>180_doFold:^Mline    1:^MError detected while processing function <SNR>180_doFold[1]..<SNR>180_doFold[2]..phpfold#Fold:^Mline    2:
^ME714: List required^ME488: Trailing characters^MError detected while processing function <SNR>180_doFold[2]..phpfold#Fold:^Mline    2:^ME714: List required^MNo matching autocomman
ds^M^M^M^M^M^M^M^M^M^M^M^ME486: Pattern not found: u(multiple-cursors-detect)db^ME486: Pattern not found: DB
```

can help u to find the reasons?

Best Regards.

**Comment by wsdjeg** [comment]
can you show me the example PHP file.

**Comment by wsdjeg** [comment]
@dyfire ping, I think an example php file will help me to fix this issue.

**Comment by chairping** [comment]
phpfold 插件需要composer install 安装php依赖类， spacevim 代码安装phpfold的时候， 没有执行composer install 命令， 所以打开php文件的时候才会出现那个错误。 英文不好，只能输入中文
😆

**Comment by wsdjeg** [comment]
~~我看了这个插件，没见到他们readme写到这个呀。~~

**Comment by dyfire** [comment]
@wsdjeg i found the reasons. when the spacevim init, there is not autoexec "composer update" for phpfold.vim project. so there is not found the 'vendor/autoload.php'.  so now it works . thanks  all.

**Comment by wsdjeg** [comment]
@dyfire yeah, I have add command for auto run `composer update` when first time install this plugin.
