### ISSUE TITLE
enter vim pop up a message `EndOfBuffer    xxx links to NonText`

### ISSUE THREAD

**Issue by fcying** [wsdjeg/SpaceVim#604]
## Expected behavior, english is recommended
After I set 'let g:spacevim_colorscheme = 'solarized'', enter vim will pop up a message 'EndOfBuffer    xxx links to NonText'

## Environment Information
- OS:ubuntu
- vim version:vim8

## The reproduce ways from Vim starting (Required!)
set init.vim
```
let g:spacevim_colorscheme = 'solarized'
let g:spacevim_colorscheme_bg = 'light'
```
enter vim

**Comment by wsdjeg** [comment]
are you using gvim or vim in terminal?

**Comment by fcying** [comment]
@wsdjeg  using vim in terminal: xfce4-terminal 0.6.3

**Comment by wsdjeg** [comment]
@fcying can you try `let g:spacevim_colorscheme = 'NeoSolarized'`? as I know solarized has some issue with true colors.

**Comment by wsdjeg** [comment]
@fcying `solarized` do not support true colors, so it is bug of solarized, and you should use `NeoSolarized`

**Comment by wsdjeg** [comment]
@fcying solarized has no gui colors, so you will get this warning, and I have fix it, now, please update spacevim
