### ISSUE TITLE
neomake 错误

### ISSUE THREAD

**Issue by cuckootan** [wsdjeg/SpaceVim#609]
## Expected behavior, english is recommended

neomake 出错

## Environment Information
- OS: macos10.12.5
- vim version: 8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)

let g:neomake_vim_enabled_makers = ['vimlint', 'vint']

## Screenshots

<img width="606" alt="screen shot 2017-06-07 at 12 07 18 am" src="https://user-images.githubusercontent.com/7947605/26839449-9ea11192-4b15-11e7-984e-3c074b3118e9.png">

**Comment by wsdjeg** [comment]
@cuckootan you should install vint and vimlint, if you want to use this two tools as vim script's lint.
