### ISSUE TITLE
there is no git checkout merge pull operation in spacevim? 

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#611]
this is not a bug issue ,just a feature request,will spacevim support for this??

**Comment by wsdjeg** [comment]
@v-leonhou what feature do you want?
`git checkout` and `git merge`?

**Comment by v-leonhou** [comment]
yes , maybe both are right

**Comment by wsdjeg** [comment]
@v-leonhou issue is opened in gina repo, https://github.com/lambdalisue/gina.vim/issues/97
