### ISSUE TITLE
deoplete php complete problem

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#613]
## Expected behavior, english is recommended
when i am typing someword in my spacevim like the picture ,deoplete offerred me the candidate words including the snippet ,seeing the picture, but when i typed the enter keyboard ,the abbr is auto inserted while i am expecting the snippet code 

## Environment Information
- OS: ubuntu 
- neovim version:NVIM v0.2.0-899-gdf1e7b7

## The reproduce ways from Vim starting (Required!)
just edite a php project ,and load the php layer in ini.vim 
 
## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.
pic1:
![image](https://user-images.githubusercontent.com/8463045/26914108-e513c7ea-4c51-11e7-8b0c-b6f57516446f.png)

pic2:
![image](https://user-images.githubusercontent.com/8463045/26914116-f59aa232-4c51-11e7-88a2-5e3e0d240c7f.png)

**Comment by Shougo** [comment]
> when i am typing someword in my spacevim like the picture ,deoplete offerred me the candidate words including the snippet ,seeing the picture, but when i typed the enter keyboard ,the abbr is auto inserted while i am expecting the snippet code

I don't understand.
Please describe the expected behavior.

I think it is neosnippet feature.

**Comment by Shougo** [comment]
I think you need to press `<Plug>(neosnippet_expand)` key.
I don't know what is mapped in SpaceVim.

**Comment by wsdjeg** [comment]
I try to reproduce it, but  where is  this snippet comes from?

minivimrc
```vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/neosnippet.vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/neosnippet-snippets

imap <cr> <Plug>(neosnippet_expand)


" deoplete options
let g:deoplete#enable_at_startup = get(g:, 'deoplete#enable_at_startup', 1)
" init deoplet option dict
let g:deoplete#ignore_sources = get(g:,'deoplete#ignore_sources',{})
let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
let g:deoplete#omni_patterns = get(g:, 'deoplete#omni_patterns', {})


" php
let g:deoplete#omni#input_patterns.php = get(g:deoplete#omni#input_patterns, 'php', [
      \'[^. \t0-9]\.\w*',
      \'[^. \t0-9]\->\w*',
      \'[^. \t0-9]\::\w*',
      \])
let g:deoplete#ignore_sources.php = get(g:deoplete#ignore_sources, 'php', ['phpcd', 'around', 'member'])
```

**Comment by wsdjeg** [comment]
got it, `ag assertNot` show me 
```
repos/github.com/honza/vim-snippets/snippets/php.snippets
594:snippet asne "$this->assertNotEquals($a, $b)"
595:	$this->assertNotEquals(${1:$expected}, ${2:$actual});
606:snippet asncon "$this->assertNotContains($needle, $haystack)"
607:	$this->assertNotContains(${1:$needle}, ${2:$haystack});
624:snippet asnco "$this->assertNotCount($count, $haystack)"
625:	$this->assertNotCount(${1:$count}, ${2:$haystack});
630:snippet asnnu "$this->assertNotNull($a)"
631:	$this->assertNotNull(${1});
```
I will improve the minivimrc, and try to find the issue.

**Comment by wsdjeg** [comment]
@Shougo I think this is neosnippet issue: here is a vedio:

https://asciinema.org/a/5e8jwb9esof9azuuq4jnadd1e

**Comment by wsdjeg** [comment]
@Shougo I can reproduce now. here is mini vimrc:
```vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/neosnippet.vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/neosnippet-snippets
set rtp+=~/.cache/vimfiles/repos/github.com/honza/vim-snippets

imap <cr> <Plug>(neosnippet_expand)


" deoplete options
let g:deoplete#enable_at_startup = get(g:, 'deoplete#enable_at_startup', 1)
" init deoplet option dict
let g:deoplete#ignore_sources = get(g:,'deoplete#ignore_sources',{})
let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
let g:deoplete#omni_patterns = get(g:, 'deoplete#omni_patterns', {})


" php
let g:deoplete#omni#input_patterns.php = get(g:deoplete#omni#input_patterns, 'php', [
      \'[^. \t0-9]\.\w*',
      \'[^. \t0-9]\->\w*',
      \'[^. \t0-9]\::\w*',
      \])
let g:deoplete#ignore_sources.php = get(g:deoplete#ignore_sources, 'php', ['phpcd', 'around', 'member'])


let g:neosnippet#snippets_directory = get(g:,'neosnippet#snippets_directory',
      \ '')
if empty(g:neosnippet#snippets_directory)
  let g:neosnippet#snippets_directory = [expand('~/.SpaceVim/snippets/'),
        \ expand('~/.SpaceVim.d/snippets/')]
elseif type(g:spacevim_force_global_config) == type('')
  let g:neosnippet#snippets_directory = [expand('~/.SpaceVim/snippets/'),
        \ expand('~/.SpaceVim.d/snippets/')] +
        \ [g:neosnippet#snippets_directory]
elseif type(g:spacevim_force_global_config) == type([])
  let g:neosnippet#snippets_directory = [expand('~/.SpaceVim/snippets/'),
        \ expand('~/.SpaceVim.d/snippets/')] +
        \ g:neosnippet#snippets_directory
endif

  let g:neosnippet#snippets_directory = [getcwd() . '/.Spacevim.d/snippets'] +
        \ g:neosnippet#snippets_directory
let g:neosnippet#enable_snipmate_compatibility =
      \ get(g:, 'neosnippet#enable_snipmate_compatibility', 1)
let g:neosnippet#enable_complete_done =
      \ get(g:, 'neosnippet#enable_complete_done', 1)

if !exists('g:neosnippet#completed_pairs')
  let g:neosnippet#completed_pairs = {}
endif
let g:neosnippet#completed_pairs.java = {'(' : ')'}
if g:neosnippet#enable_complete_done
  let g:neopairs#enable = 0
endif

" vim:set et sw=2 cc=80:

```

here is reproduce step:

1. vim -u test.vim main.php
2. type `i$asnnu<C-n><cr>`  (`i` is to switch to insert mode)
nothing happend, but if I type `iasnnu<c-n><cr>`, this snippet will be expanded.
I think it is not issue with neosnippet, because afte type `i$asnnu<C-n><cr>`, you will see `$asnnu__this_assertNotNull_a` it is not a snippt (there is a `$` at the begining), and after type `iasnnu<c-n>` you will see `asnnu__this_assertNotNull_a`, it is a snippet, so expanding works well.

ok, now I think the issue is : 
1. after type `i$asn`, snippet `asnnu__this_assertNotNull_a` should not be completed.

**Comment by Shougo** [comment]
I have fixed the problem.
Please update neosnippet

**Comment by Shougo** [comment]
> but when i typed the enter keyboard ,the abbr is auto inserted while i am expecting the snippet code

This is for snipMate compatibility problem.
The snippet trigger has the documentation.
And these are not unique.

**Comment by wsdjeg** [comment]
Thanks, will have a try latter.

**Comment by wsdjeg** [comment]
@v-leonhou any update?
