### ISSUE TITLE
Error detected while processing /home/yyf/.SpaceVim/autoload/SpaceVim.vim

### ISSUE THREAD

**Issue by yyfcc17** [wsdjeg/SpaceVim#615]
screenshot:
![image](https://user-images.githubusercontent.com/14891271/26959184-591e87ce-4d01-11e7-92a7-d79ea957385b.png)

**Comment by wsdjeg** [comment]
how do you install SpaceVim?

**Comment by yyfcc17** [comment]
curl -sLf https://spacevim.org/install.sh | bash
![image](https://user-images.githubusercontent.com/14891271/26959461-d97ebd98-4d02-11e7-8288-b621c55fe095.png)

**Comment by wsdjeg** [comment]
@yyfcc17 
can you show me the result in shell?
```
git -C ~/.vim status
```
and
```
cat ~/.SpaceVim.d/init.vim
```
```

**Comment by yyfcc17** [comment]
![image](https://user-images.githubusercontent.com/14891271/26976839-3c41eff4-4d58-11e7-9116-059006f86de1.png)
![image](https://user-images.githubusercontent.com/14891271/26976941-a6d0054a-4d58-11e7-87d8-c1d34397dc2b.png)
i compiled vim8.0 from source and it worked perfectly. i just wanted to try SpaceVim for the first time today.

**Comment by wsdjeg** [comment]
but this issue is really strange, I can not reproduce it, what is outout of 
`cat ~/.vimrc` and `cat ~/.vim/vimrc`

**Comment by yyfcc17** [comment]
it's strange that sometimes i run `curl -sLf https://spacevim.org/install.sh | bash`
it doesn't work. i need to run it several times, then it starts to work
![image](https://user-images.githubusercontent.com/14891271/27016429-4c576288-4f52-11e7-8399-f3265825883c.png)
And there are the results:
![image](https://user-images.githubusercontent.com/14891271/27016454-8ad2230e-4f52-11e7-9eee-63bb4659aa9b.png)
![image](https://user-images.githubusercontent.com/14891271/27016469-ad2e4676-4f52-11e7-8695-bf055d4be66e.png)

**Comment by wsdjeg** [comment]
can you install SpaceVim  via these commands.

```sh
rm ~/.vimrc
rm -rf ~/.vim
git clone https://github.com/SpaceVim/SpaceVim.git ~/.vim
```

**Comment by yyfcc17** [comment]
No, the errors are the same.

**Comment by Shougo** [comment]
@yyfcc17 Your Vim seems compatible mode or tiny.
You should upload `:version` result.

**Comment by yyfcc17** [comment]
There are the results:

yyf@yyf:~$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 17 2017 09:51:16)
Included patches: 1-566
Compiled by yyf@yyf
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -L/build/buildd/ruby1.9.1-1.9.3.484/debian/lib -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl   -ldl  -L/usr/lib -llua5.1 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config -lpython2.7   -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib

**Comment by yyfcc17** [comment]
There are the results:

![image](https://user-images.githubusercontent.com/14891271/27330407-db974df6-55eb-11e7-867c-bfc69dc7e8bd.png)
![image](https://user-images.githubusercontent.com/14891271/27330447-005561d2-55ec-11e7-8812-25713e303a6b.png)

**Comment by wsdjeg** [comment]
I think it is issue of your vim, you should compile it yourself, as you show in the first picture: you vim do not support this kind of vim script

```vim
let g:spacevim_plugin_bundle_dir
      \ = $HOME. join(['', '.cache', 'vimfiles', ''],
      \ SpaceVim#api#import('file').separator)
```

**Comment by yyfcc17** [comment]
Yes, I compiled vim by myself. How can I fix it? Could you tell me which line indicates that my vim doesn't support this kind of vim script?

**Comment by wsdjeg** [comment]
hmm, I do not use vim8 though, I recommend to use neovim, it is easy to compile neovim just `git clone ...` and `make CMAKE_BUILD_TYPE=RelWithDebInfo`
