### ISSUE TITLE
How to use spacevim view funciton definitions.

### ISSUE THREAD

**Issue by codesuper-god** [wsdjeg/SpaceVim#616]
## Expected behavior

Now,i wuold like to use spacevim to do linux driver development.You know to do linux driver development generally see linux kernel source.Linux kernel code so much,if there is no good source code editing tool,in fact ,it's difficult to develop.So I am looking for a tool to achieve the function jump.If you know tell me.If there is a link to use,send it to me 

## Environment Information
- OS:ubuntu 16.04
- vim version:vim-7.4

**Comment by tracyone** [comment]
use cscope.

make cscope tags

**Comment by Yggdroot** [comment]
Use `:LeaderfBufTag` or `:LeaderfFunction`.

**Comment by wsdjeg** [comment]
@codesuper-god use F2 to open tagbar, use  fo to open unite outline, or use Fo to open denite outline

**Comment by codesuper-god** [comment]
@wsdjeg hello,I have tried f0,it can be achieved in a docoument under the function of the jump,but if I want to achieve the function jump between multiple documents ,how should i do? I tried Fo,it doesn't work.

**Comment by codesuper-god** [comment]
@Yggdroot  I tried your method,but didn't have the instruction that you said.

**Comment by Yggdroot** [comment]
@wsdjeg fo and Fo do not work for me either on Windows.

**Comment by Yggdroot** [comment]
@codesuper-god Don't use the tab to complete the command, just type the command.

**Comment by wsdjeg** [comment]
i can't understand, what do you want, tagbar is to show function and value in current file.

**Comment by codesuper-god** [comment]
@wsdjeg  我说 F2只能弹出一个窗口，上面显示函数的定义，和变量的定义，但是并不能够实现跳转。 f0 可以查看到函数的定义，并且实现跳转，但是它只能实现当前文件的跳转。   我现在想如果函数的定义或变量的定义在另一个文件中。我应该怎么做，才能实现跳转呢

**Comment by Yggdroot** [comment]
@codesuper-god 如果你要跳转的文件已经打开，可以使用`:LeaderfBufTagAll` 或 `:LeaderfFunctionAll`, 这两个命令在spacevim里没有默认加载，可以直接在命令行里敲。

**Comment by codesuper-god** [comment]
那样岂不是太麻烦了，每次都要按这么多键 。而且如果文没有打开，你打算怎么做呢？

**Comment by Yggdroot** [comment]
你vim是刚入门吧，可以自己map 个快捷键

**Comment by codesuper-god** [comment]
@Yggdroot  好吧，我确实是vim初学者，但是我还有一个问题，如果那个文件没有打开。有什么对应按键能实现函数跳转吗？

**Comment by Yggdroot** [comment]
如果没有打开，只能用ctags了，生成个tags文件，然后用<c-]>来跳转，这是vim自带的功能。
如果生成了tags，也可以使用`:LeaderfTag`这个命令。

**Comment by wsdjeg** [comment]
spacevim 内置了tags支持，你可以用`ft`快捷键打开unite-ctags. 你需要安装ctags

**Comment by wsdjeg** [comment]
@codesuper-god ctags支持，还是需要提升一下，提升后，对于浏览整个项目所有函数将变的更加方便。

**Comment by codesuper-god** [comment]
Thank you so much.

**Comment by codesuper-god** [comment]
![image](https://user-images.githubusercontent.com/24927547/27250746-1ddb6c9e-52fc-11e7-9592-23eff86dd249.png)
在这些选项中，并没有直接跳转光标所在位置函数或变量定义的选项，大部分都要借助搜索功能才能实现跳转。
例如你说的f + t 
![image](https://user-images.githubusercontent.com/24927547/27250759-5a74e752-52fc-11e7-8a31-84675536c0fe.png)

而且这个选项对于一个庞大的工程来讲，加载的速度是相当慢的。

**Comment by jackalchenxu** [comment]
大型的项目下，使用ctags会很慢， 最终导致查询和跳转变得很慢； 稍有经验的都会换成cscope；
这么简单的需求，spacevim都未考虑？难道创建spacevim是为了在console的vim环境下敲文档吗？

**Comment by tracyone** [comment]
因为楼主不写c语言，然后这个仓库没几个人做贡献，没有达到所谓的community driven。

**Comment by ssfdust** [comment]
@jackalchenxu 我觉得简单提交一个PR比吐槽要实在地多得多。

**Comment by wsdjeg** [comment]
请查看 tags layer。这一模块采用的是 gun global, 这个工具配合辅助工具，对大部分语言支持很完美，甚至 vim 脚本。 可以用来列出 定义处 和 引用处。
