### ISSUE TITLE
Leader should be space by default

### ISSUE THREAD

**Issue by tracyone** [wsdjeg/SpaceVim#62]
All the keymap should be start with space Because "Like spacemacs, but for vim."

**Comment by wsdjeg** [comment]
it is easy changed by user,  most of the vim user do not use space as leader, some of them use `,` and `;` and `\`. 

I will add doc for it. BTW SpaceVim has many kinds of leader.
1. origin leader
2. origin localleader
3. windows func leader
4. Unite leader
5. Denite leader (TODO)
6. Searcher leader (TODO)
7. `g` leader。

**Comment by wsdjeg** [comment]
Let's move the talk to #31 .
