### ISSUE TITLE
Runtime error when quit from vim.

### ISSUE THREAD

**Issue by Yggdroot** [wsdjeg/SpaceVim#621]
## Environment Information
- OS: Windows 10
- vim version: vim8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
Start vim, then quit it with `:q`. The error occurs.

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![image](https://user-images.githubusercontent.com/2705841/27027240-30989d5a-4f93-11e7-9215-ba76643d2dd3.png)

**Comment by wsdjeg** [comment]
@Yggdroot how to you get you gvim package?  and can you post text instead of pic, then I can copy the error message to search for info.

**Comment by wsdjeg** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/microsoft-visual-c-runtime-library-runtime-error/f32da816-d8a7-4b05-9975-b9f4144af62b
