### ISSUE TITLE
冒昧问下大大，如何修改默认字体呢

### ISSUE THREAD

**Issue by zqq1314521** [wsdjeg/SpaceVim#622]
## Environment Information
- OS:Win7
- vim version:
- neovim version:

## Output of the ':SPDebugInfo!'

" set the guifont
比如如下字体：Source Code Pro
不论怎么修改，貌似都是默认字体，能解答下吗？谢谢
let g:spacevim_guifont = 'Source\ Code\ Pro-Regular\ 12'

**Comment by wsdjeg** [comment]
你用的是gvim还是终端？这个选项只对GUI有效果，如果需要修改终端Vim字体，那么需要修改终端的配制。

**Comment by zqq1314521** [comment]
不好意思，我没有填写更具体的信息 使用的是gvim，win7的系统，DejaVu Sans  Mono  for  Powerline我已安装，我只是奇怪 我改用其他字体 貌似都不生效，在vim通过命令：set guifont是可以修改的，而在配置文件中，不论我如何修改，貌似都是DejaVu Sans  Mono  for  Powerline字体，是我字体的名称输入有误吗？谢谢

**Comment by wsdjeg** [comment]
你可以使用`:set guifont=*`命令，打开字体设置窗口，选择对应字体，发现，确认，然后用`:echo &guifont`命令看对应的值，将这个值写到用户配置，转义空格。

**Comment by zqq1314521** [comment]
:set guifont=SourceCodePro-Regular:h12
在vim中命令生效，
:echo&guifont
SourceCodePro-Regular:h12
貌似没有空格
按照let g:spacevim_guifont = 'SourceCodePro-Regular\ 12'
没有效果
let g:spacevim_guifont = 'Source\ Code\ Pro-Regular\ 12'也不行，貌似换成Arial也不行呐
麻烦您了 还有办法吗？你那里可以修改吗？

**Comment by wsdjeg** [comment]
let g:spacevim_guifont = 'SourceCodePro-Regular:h12'

**Comment by zqq1314521** [comment]
麻烦您了，但还是没有作用 我改天换台电脑 再试试吧

**Comment by wsdjeg** [comment]
@zqq1314521 你有字体文件么，可以发我邮件，我来测试一下

**Comment by wsdjeg** [comment]
@zqq1314521 here is my config, and it works well for me.

`let g:spacevim_guifont = 'Source_Code_Pro:h11:cANSI:qDRAFT'`

**Comment by zqq1314521** [comment]
不好意思 好久没来看，今天我试了下，起作用了 我的系统里有两个/.SpaceVim.d/，我一直改错了，麻烦哥们你了

**Comment by cyancity** [comment]
If you use the latest SpaveVim Release (0.9.0-dev), and you use macvim or gvim etc
And you want to change you guifont, it is easy

just put the next line in `~/.SpaceVim.d/init.toml`
`guifont = "Operator Mono Book Nerd Font Complete:h14"`

The Font is my font config, you can type `:set guifont` to show your current font and set it to your config
