### ISSUE TITLE
Buildin explore width fixed

### ISSUE THREAD

**Issue by phonzia** [wsdjeg/SpaceVim#623]
:Expolre command open a explorer in current buffer, but the buffer width is changed to a fixed width, this behavior is not friendly.

**Comment by wsdjeg** [comment]
@phonzia can you show me an example? I just try in gvim without spacevim, after run `:Ex`  you will see
![qq 20170616155605](https://user-images.githubusercontent.com/13142418/27217449-780399a8-52ac-11e7-9c7b-ea05e3888fff.png)
