### ISSUE TITLE
g:spacevim_colorscheme not work

### ISSUE THREAD

**Issue by tracyone** [wsdjeg/SpaceVim#63]
```vim
let g:spacevim_colorscheme='PaperColor'
```

but execute `:colorscheme PaperColor` in vim or nvim is work.

- vim 8.0 
- neovim2.0
- macOS
- terminal.APP
- iterm2.app
- bash
- zsh
- tmux or no tmux

**Comment by wsdjeg** [comment]
can not repo, `let g:spacevim_colorscheme='atom'` works well for me.

**Comment by wsdjeg** [comment]
try again `let g:spacevim_colorscheme='PaperColor'` also works well for me.

**Comment by tracyone** [comment]
@wsdjeg update

**Comment by wsdjeg** [comment]
@tracyone so does it work well for you ?

**Comment by tracyone** [comment]
no .

**Comment by wsdjeg** [comment]
can you test it in terminal? and what is the value of `g:spacevim_colorschem`

**Comment by tracyone** [comment]
The variable's value is correct.

```vim
:colorshceme
```
output is PaperColor

but the color not right

<img width="762" alt="2017-01-07 11 53 43" src="https://cloud.githubusercontent.com/assets/4246425/21742985/8c94dd6e-d534-11e6-9d04-5de9ae67178d.png">

**Comment by wsdjeg** [comment]
so what is your `~/.local.vim`? I want to repoduce this.

**Comment by tracyone** [comment]
just

 let g:spacevim_colorscheme='PaperColor'

**Comment by wsdjeg** [comment]
If you do not add this option, does `gruvbox` loaded correct?

**Comment by wsdjeg** [comment]
@tracyone repodued!! I will try to find where is the iessue.
no syntax hi
![2017-01-08-00 10 44](https://cloud.githubusercontent.com/assets/13142418/21743137/16fdb8f2-d537-11e6-8d4e-230051962773.png)

**Comment by wsdjeg** [comment]
after `:syntax on` colorscheme look well
