### ISSUE TITLE
There ocer a warning

### ISSUE THREAD

**Issue by moonccl** [wsdjeg/SpaceVim#634]
## Environment Information
- OS: archlinux
- neovim version:NVIM v0.2.0

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![error](https://github.com/BlasphemyAngels/MarkDownPhotos/blob/master/bug.png?raw=true)

**Comment by wsdjeg** [comment]
there is no reproduce step, and no example cpp file.
