### ISSUE TITLE
Mouse(in X, not just the vim cursor) freeze in insert mode

### ISSUE THREAD

**Issue by kusk** [wsdjeg/SpaceVim#636]
Every time I go to insert mode, the mouse(Xorg, not the Vim cursor) freeze until I leave it again. Can't find if its a feature or a bug. A completely clean vim and other other vim"packs" like spf13 doesn't have the problem. 

Different terminals has been tried.

## Environment Information
- OS: Ubuntu 17.04(Xubuntu)
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 12:13:35)

## The reproduce ways from Vim starting (Required!)

The error happens with a completely fresh install.

**Comment by wsdjeg** [comment]
oh, it is the feature, because spacevim use `set mouse=a` by defalut, when in insert mode, the cursor position maybe changed by Xorg cursor ( touchpad). I will add an option to disable this feature.

**Comment by wsdjeg** [comment]
@kusk there is an option for this feature, if you want to disable it, add `let g:spacevim_auto_disable_touchpad = 0` to you custom configration file.
