### ISSUE TITLE
macvim crash

### ISSUE THREAD

**Issue by tracyone** [wsdjeg/SpaceVim#64]
macvim crash immediately after start.

following is the output from terminl:

> Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
Current thread 0x00007fffc43c93c0 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.

I don't know what config cause this

**Comment by wsdjeg** [comment]
can you use vim in terminal? does it works well? I do not use macvim, it is hard to debug.

**Comment by wsdjeg** [comment]
use `git -C ~/.SpaceVim reset --hard HEAD^` one by one, to find which commit cause this issue.

**Comment by tracyone** [comment]
😊，I hope someone meet this problem and solve it...I know nothing about python....

Keep this issue open,because I met this problem when  this repo start.

**Comment by wsdjeg** [comment]
This maybe bug of macvim? and does it happened everytime?

**Comment by tracyone** [comment]
macvim with my heavy vim config just work fine

**Comment by wsdjeg** [comment]
here is some usefull link, hope these can help you;
https://stackoverflow.com/questions/38132755/importerror-no-module-named-encodings

https://github.com/powerline/powerline/issues/1363

https://github.com/jordwalke/VimBox/issues/23

https://stackoverflow.com/questions/28749679/vim-crashes-when-used-with-conda-python3-on-windows-7

**Comment by AlphaLiu** [comment]
SpaceVim works fine in my macvim...
my macvim is 8.0.

**Comment by wsdjeg** [comment]
It should be issue of macvim. all of SpaceVim source is viml, I do not think viml can make vim crash, If so, It is but of vim or maybe macvim.

**Comment by SteamedFish** [comment]
This is actually a VIM bug which was fixed at https://github.com/vim/vim/commit/0424958bde3d3e74c721ba39ab4d5a4744897393
