### ISSUE TITLE
Error message when starting in a directory including space

### ISSUE THREAD

**Issue by demon386** [wsdjeg/SpaceVim#640]
## Expected behavior, english is recommended
When I start vim inside a directory including a space, it shows error message (see attached screenshot)

## Environment Information
- OS: macOS Sierra
- vim version:8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
When I start vim inside a directory including a space, it shows error message (see attached screenshot)

## Screenshots
![image](https://user-images.githubusercontent.com/1246611/27292347-c8733362-5545-11e7-9e81-d918a51b16cb.png)

**Comment by techgaun** [comment]
@demon386 you should check the latest dev branch by updating your SpaceVim.. this should be fixed now.
