### ISSUE TITLE
Spacevim default separators look strange

### ISSUE THREAD

**Issue by ssfdust** [wsdjeg/SpaceVim#643]
## Expected behavior, english is recommended
https://github.com/rogual/neovim-dot-app/issues/215
I am using spacevim with neovim-qt and run into the problem.The problem seems similar to this issue 215.But when I disable spacevim statusline and switch to the airline, the separators show properly. I think this may be bug of spacevim instead of neovim-qt.
After all the plugins are loaded, re-sourcing the general.vim file or reloading any colorscheme will fix the problem.I have tried move the action of loading general.vim to the last step in main.vim, but this doesn't work.
Any idea Please?
Thanks in Advance. 

## Environment Information
- OS: Archlinux Plasma 5.10
- vim version:
- neovim-qt version:latest from git
- neovim version: v0.2.0

## The reproduce ways from Vim starting (Required!)
Keep the default configuraion and start neovim-qt.Then reload any colorscheme. 

## Screenshots
http://imgur.com/a/6giQs

**Comment by wsdjeg** [comment]
@ssfdust this is a neovim's bug, when nvim startup we can not get the gui colors value even if &ctermguicolors == 1

**Comment by wsdjeg** [comment]
@ssfdust when you see this bug, can use show me `:hi SpaceVim_statusline_a_SpaceVim_statusline_b`

**Comment by ssfdust** [comment]
SpaceVim_statusline_a_SpaceVim_statusline_b xxx ctermfg=246 ctermbg=239 guifg=#a89984 guibg=#504945
And there is no change on the variable after reloading colorscheme.
@wsdjeg
