### ISSUE TITLE
中文输入，编辑窗口左下角出现输入法弹窗闪烁问题

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#644]
When entering Chinese, the blinking input box appears below the input window
中文输入，编辑窗口左下角出现输入法弹窗闪烁问题

**Comment by wsdjeg** [comment]
能不能用工具录一个视频，这个问题我测试过，只在nvim中出现，并且只有在 垂直分割窗口时候出现。

**Comment by wy15** [comment]
bfb2c9e9827f1c9c3fed88b0b33356382f41f1d4
这个提交之后出现的，每个窗口都会有一个光标在闪烁
![sp](https://user-images.githubusercontent.com/1898296/27365178-3f2b6746-5671-11e7-9816-76baccdacb9f.png)

**Comment by Gabirel** [comment]
@xiaobagou 你这个statusline最左边的风格有点好看啊，`No Name`右边其他的不好看，这个是怎么搞的？

**Comment by wy15** [comment]
@Gabirel 
let g:spacevim_statusline_separator = 'fire'

**Comment by Gabirel** [comment]
@xiaobagou 谢谢
