### ISSUE TITLE
spacevim sometimes crashes while completing

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#653]
spacevim sometimes crashes while completing,the complete menu just remained in my screen ,which should disapear ,while the complete is done,i don't know while this crashes ,it seems hard to reproduce the issue,so i just supply the error message here.

## Environment Information
- OS:ubuntu14.04
- vim version:nvim
- neovim version:NVIM v0.2.0-899-gdf1e7b7
Build type: Debug

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![tim 20170622133329](https://user-images.githubusercontent.com/8463045/27418708-7442c72e-574f-11e7-9c06-139c025dc485.png)
![tim 20170622133351](https://user-images.githubusercontent.com/8463045/27418711-77c9eecc-574f-11e7-9670-064e19ece10a.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
The reproduce way is needed.
I think it is the plugin bug.

**Comment by wsdjeg** [comment]
If you provide reproduce step, I will test it.
