### ISSUE TITLE
filetype doesn't work

### ISSUE THREAD

**Issue by moonccl** [wsdjeg/SpaceVim#655]
while I wirte the script "if &filetype=.." to the SpaceVim.d/init.vim, It doesn't work!

## Environment Information
- OS: Arch Linux
- vim version: 8.0

**Comment by Shougo** [comment]
You should upload the example.
I don't understand it.

**Comment by wsdjeg** [comment]
why use `&filetype` in init.vim. init.vim is loaded when vim starting. so no buffer is loaded. there is no &filetype.

if you want to run function when filetype is setted. for example java FileType, you should use

au! FileType java call SomeFunc()
