### ISSUE TITLE
Hidden formatting on auto complete

### ISSUE THREAD

**Issue by saward** [wsdjeg/SpaceVim#656]
Hi,

Not really sure how to figure out what plugin or setting is causing this, but when I use autocomplete for a function with Go, it seems to include hidden characters with it.  If I set conceallevel=0, I can now see the junk characters.  For example:

> someFunc(applicationID int64\`><\`4:#:, userID int64\`>)<\`5\`>

Is this something being done by SpaceVim, or do you know which plugin might be responsible?  Or, how I would go about determining that?

Thanks!

On an unrelated note, I had some other issues with shortcuts in a different issue here, and you suggested updating which I did.  Despite saying that I had, it seemed that the branch was wrong on my local git repo, so I fixed that and now it's updated.

**Comment by Shougo** [comment]
This is neosnippet feature.
neosnippet uses the marker to detect the placeholder.

**Comment by Aya-Yang** [comment]
I have the same problem, is there a way to solve it?

**Comment by wsdjeg** [comment]
it is neosnippet feature. you need to use Tab to jump.

**Comment by tenfyzhong** [comment]
I have an idea. Stop the neosnippet this feature and instead of [tenfyzhong/CompleteParameter.vim](https://github.com/tenfyzhong/CompleteParameter.vim). I will make it compatible with deoplete(the default complete engine for spacevim) as soon as possible.
