### ISSUE TITLE
souce $MYVIMRC error occured

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#667]
## Expected behavior, english is recommended
when i changed my init.vim configuration , and source $MYVIMRC ,the error occured

## Environment Information
- OS:ubuntu 14.04
- vim version:
- neovim version:NVIM v0.2.0-899-gdf1e7b7

## The reproduce ways from Vim starting (Required!)
just start nvim and :source $MYVIMRC

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![tim 20170626100553](https://user-images.githubusercontent.com/8463045/27522238-0da2e188-5a57-11e7-9a2d-4fc803ede4f0.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
you should not re source vimrc. it is not recommend. and it will break many plugins.

**Comment by Shougo** [comment]
@wsdjeg I think SpaceVim should support vimrc reloading.
