### ISSUE TITLE
line numbers scrolling with cursor

### ISSUE THREAD

**Issue by iyogeshjoshi** [wsdjeg/SpaceVim#674]
It seems whenever I change line, line numbers are changing with the cursor, It always starting as 1 from the line on which there is the cursor. please check

## Environment
OS: macOS Sierra 10.12.5
Vim: Vim 8.0
Iterm2: Build 3.1.beta.5

**Comment by wsdjeg** [comment]
It is `relativenumber`. I will fix it.

**Comment by wsdjeg** [comment]
I have fix it in cursor branch, and when it is merged, you can disable relativenumber by add `let g:spacevim_relativenumber = 0` to your custom configration file. and you can use `SPC t n` to toggle line number.
