### ISSUE TITLE
<Leader>cc brings up quickfix window rather than running NERDComment comment out command

### ISSUE THREAD

**Issue by bravecorvus** [wsdjeg/SpaceVim#678]
## Expected behavior, english is recommended
\<Leader\>cc from Normal
Comment out the current line or text selected in visual mode.

## Environment Information
- OS: macOS 10.12.5
- neovim version: v0.2.0

## The reproduce ways from Vim starting (Required!)
\<Leader\>cc from Normal

Just \<Leader\>c will bring up the option c for Toggle comment lines help window, but no other options are shown.

![c](https://68.media.tumblr.com/0ba2c643b0471d548b14a554d8cfae9b/tumblr_os7yx08hHk1s5a4bko1_1280.png)

## Output of the ':SPDebugInfo!'
?
please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![problem](https://68.media.tumblr.com/411b7c00631099d0292c874691e1a296/tumblr_os7yogXMmP1s5a4bko1_1280.png)

**Comment by wsdjeg** [comment]
I will test it tonight. It should be a bug.
