### ISSUE TITLE
<leader> gd (Git diff) not working

### ISSUE THREAD

**Issue by bravecorvus** [wsdjeg/SpaceVim#690]
## Expected behavior, english is recommended
<leader\>gd should bring up Git diff

## Environment Information
- OS: 10.12.5
- vim version:
- neovim version: 0.2.0

## The reproduce ways from Vim starting (Required!)
Normal <leader\>gd

## Output of the ':SPDebugInfo!'
?
please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![screenshot](https://68.media.tumblr.com/4defc566f8f38d0d6540ccb824e91f79/tumblr_osbwlhX77U1s5a4bko1_1280.png)
If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@gilgameshskytrooper in spacevim Leader is not Space, spacevim use `<Space>` as `[SPC]` only in normal mode, but `<Leader>` can be used not only in normal mode but also in insert mode, if we use `<Space>` as a `<Leader>` and with some imap, `<Space>` will cause input delay.

The default `<Leader>` is `\`, It is same as vim's default behaviour. so You should press `\gd`.
