### ISSUE TITLE
see an install error in a fresh openSUSE Leap42.2

### ISSUE THREAD

**Issue by ls-zhu** [wsdjeg/SpaceVim#691]
Error detected while processing function SpaceVim#commands#install_plugin..SpaceVim#plugins#manager#install..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_in
stall..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_insta
ll_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..2
8..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit.
.<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>
82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82
_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_in
stall_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install
..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_ex
it..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<S
NR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR
>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on
_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_inst
all..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install
_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..28..<SNR>82_on_install_exit..<SNR>82_install..<SNR>82_msg_on_start..<SNR>82_set_buf_line..<SNR>82_focus_main_win:
line    3:
E169: Command too recursive

**Comment by wsdjeg** [comment]
@ls-zhu I think you should use vim8 with +python support.

**Comment by ls-zhu** [comment]
Thanks, it is a resolved after updating vim to 8.x
