### ISSUE TITLE
Question: Could i start a python program directly out of spacevim?

### ISSUE THREAD

**Issue by poulpoulsen** [wsdjeg/SpaceVim#693]
## Environment Information
- OS: Win81 64bit
- vim version: 8.0
- neovim version:

## Question
hello,
could i start a python program directly out of spacevim?
if so, how could i configure that?

Regards
Poul

**Comment by wsdjeg** [comment]
it is same as vim, you can use `:!python main.py`.

spacevim support `SPC !`
