### ISSUE TITLE
Show update percentage when updating plugins

### ISSUE THREAD

**Issue by abinashmeher999** [wsdjeg/SpaceVim#698]
## Feature Request
I just installed SpaceVim and I must say it's great. Thanks a lot for the project! :slightly_smiling_face: 

When the plugins update just after the installation (or while `:SPUpdate`) they don't show any status about what percent of download has finished.

The state starts from `Updating...` and changes to `Updating done.` upon completion. There is no way to know if an installation is stuck at a plugin or continuing as expected when it shows `Updating...` for a long time(possible for large plugins).

A status indicator with the message that indicates the percentage of download would be great.

**Comment by wsdjeg** [comment]
This seems like a nice feature
