### ISSUE TITLE
The function of the key "h"  was changed 

### ISSUE THREAD

**Issue by HanielF** [wsdjeg/SpaceVim#700]
## Environment Information
-OS:Fedora 25
- vim version:8.0
-spacevim version:0.4.0-dev

Problem:
After i exit the insert pattern, sometimes ,the key "h" will make you back to the first line.
what's more ,the key "j" will delete the line ,key "l" will force you to the last line.  Key "k" won't make any response.
However,the functions of  "i" "o" and "a" weren't changed. 
The problem will disappear just after reentering the insert pattern and exit.

I haven't changed any config of spacevim .

**Comment by wsdjeg** [comment]
@HanielF I do not mapping `h` and `l`. can you provide a reproduce step like:
1. enter vim with : `vim test.txt`
2. press `iabcd<Esc>h`

**Comment by HanielF** [comment]
You should know It's a uncertain phenomenon.

**Comment by wsdjeg** [comment]
@HanielF but I can not reproduce it,  `h` means move cursor back one char, `l` means move cursor right

**Comment by HanielF** [comment]
I do know the real meaning of those keys. Well .I would make a video to show you the problem another time i encounter the problem.

**Comment by wsdjeg** [comment]
ok,

**Comment by HanielF** [comment]
I am sorry to reply so late. Now I have cofirmed that the error is caused by my own fault. I pressed the Capslock before incautiously.

**Comment by wsdjeg** [comment]
ohh, that is H instead of h.
