### ISSUE TITLE
startup give error

### ISSUE THREAD

**Issue by linchen2chris** [wsdjeg/SpaceVim#704]
## Expected behavior, english is recommended
start vim it enter spacevim

## Environment Information
- OS: mac OS 
- vim version: 7.4
- neovim version: 

## The reproduce ways from Vim starting (Required!)
- open terminal
- type vim
- then get 
error detected while processing ~/.SpaceVim.d/init.vim:
line    2:
E117: Unknown function: SpaceVim#custom#SPC
E117: Unknown function: SpaceVim#custom#SPC
## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

<img width="601" alt="screen shot 2017-07-04 at 4 42 24 pm" src="https://user-images.githubusercontent.com/3970087/27822329-e2192da6-60d7-11e7-94bf-2bb889c9d151.png">

**Comment by tenfyzhong** [comment]
Have you modify the ~/.SpaceVim.d/init.vim file?

**Comment by wsdjeg** [comment]
how do you install spacevim?

**Comment by linchen2chris** [comment]
@tenfyzhong  No, 
@wsdjeg  I just follow the install steps:  ```curl -sLf https://spacevim.org/install.sh | bash```

**Comment by linchen2chris** [comment]
this is the install screenshot
<img width="715" alt="screen shot 2017-07-04 at 5 51 00 pm" src="https://user-images.githubusercontent.com/3970087/27825232-7f059420-60e1-11e7-826d-4b63973d2177.png">

<img width="247" alt="screen shot 2017-07-04 at 5 52 46 pm" src="https://user-images.githubusercontent.com/3970087/27825280-9f88ce1a-60e1-11e7-9718-8f580b98ded8.png">

**Comment by Shougo** [comment]
Your SpaceVim installation seems broken.
I think you should reinstall SpaceVim.

**Comment by wsdjeg** [comment]
your custom config `~/.SpaceVim.d/init.vim` is wrong. please read the example in readme or wiki.

**Comment by linchen2chris** [comment]
delete  folder .vim and .SpaceVim.d then I reinstall it. The error disappears.
Thanks guys, @Shougo @wsdjeg @tenfyzhong
