### ISSUE TITLE
Split user-config and officia-config

### ISSUE THREAD

**Issue by colinlabs** [wsdjeg/SpaceVim#71]
Make a opinion, take a look at the entire directory structure,
`~ /. SpaceVim` link to ` ~ /. Vim`,no problem, but for user-defined configuration, no corresponding to centrally manage user configuration, such as **spacemacs**, it has one `. spacemacs.d` directory, default generates a `init. el`, as the user configuration entry, users can customize here configuration, and can be incorporated into their VCS, implementation and the separation of user layer, or so for user-defined configuration is very difficult to maintain. My this spacemac.d independent configuration, for example, `https://github.com/co1inlee/dotfile/tree/master/spacemacs.d`, full control of their own, do not rely on and spacemacs. Although the README says, there is a `.local.vim` configuration file, but just a file, may be somewhat limited

**Comment by wsdjeg** [comment]
how about `~/.SpaceVim.d`  and `.SpaceVim.d`? these two directory will be added into runtimepath. it will works just like local plugin.

**Comment by colinlabs** [comment]
cool, only this directory fit with **SpaceVim**

**Comment by wsdjeg** [comment]
Done, I will push code tonight.
