### ISSUE TITLE
找不到termguicolors变量

### ISSUE THREAD

**Issue by anbenqishi** [wsdjeg/SpaceVim#725]
默认安装完，打开vim，提示找不到termguicolors options，本地确实没有这个选项，但是看提示，应该是哪个脚本里面的代码没有判断是否存在就拿来用了，想知道是哪个脚本? 谢谢（应该不需要提供环境与安装信息吧）

"g.vim" 13L, 379C
Error detected while processing function SpaceVim#autocmds#VimEnter..5:
line    5:
E113: Unknown option: termguicolors
Press ENTER or type command to continue
Error detected while processing function SpaceVim#autocmds#VimEnter..5:
line    5:
E15: Invalid expression: &termguicolors || has('gui_running')
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
OK，这个确实是一个问题，晚些时候修复下。
