### ISSUE TITLE
cannot find vimlint on save

### ISSUE THREAD

**Issue by tetsusoh** [wsdjeg/SpaceVim#729]
## Error
get follow error message on saving vim file.
```
Neomake: [1.-:3:1] Exe (vimlint) of maker vimlint is not executable.
```

vim-vimlint is installed.
```
➜  ~ % ls .cache/vimfiles/repos/github.com/syngan/vim-vimlint
README.md autoload  bin       doc       plugin    resource  test      themis
➜  ~ %
```

I tried to set `let g:neomake_vim_enabled_makers = ['vimlint', 'vint']` in `init.vim` but doesn't fix the issue. 

## vim version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 22 2017 03:02:45)
MacOS X (unix) version
Included patches: 1-648

**Comment by wsdjeg** [comment]
vimlint should be executable in your PATH. you can check out my DotFiles. And there is a vimlint in local/bin

**Comment by wsdjeg** [comment]
I have fix the dark powered mode.
press `SPC f v d`:
then change:
```vim
let g:neomake_vim_enabled_makers = ['vimlint', 'vint']
```

to 

```vim
let g:neomake_vim_enabled_makers = []
if executable('vimlint')
    call add(g:neomake_vim_enabled_makers, 'vimlint') 
endif
if executable('vint')
    call add(g:neomake_vim_enabled_makers, 'vint') 
endif
```
