### ISSUE TITLE
how to install custom plugin

### ISSUE THREAD

**Issue by xqey** [wsdjeg/SpaceVim#73]
hi, 
I want to install custom plugin however I can't intstall plugin for instance  there is no autopairs plugin and I want to install it how I can install it.

**Comment by wsdjeg** [comment]
This feature should be added, will do it.

**Comment by xqey** [comment]
hi thanks for your support and help. I read documentation and I added my custom plugin in this way. 
but it did not installed.  what is reason for this ?   
```
let g:spacevim_custom_plugins = [
        \ ['jiangmiao/auto-pairs'],
        \ ]
```

**Comment by wsdjeg** [comment]
it works well for me, when add this into config, the first time you start vim. SpaceVim will aotoinstall auto-pairs, then restart vim.

**Comment by xqey** [comment]
finally I fixed it. this is completely is my mistake. thank you for your help again.

**Comment by wsdjeg** [comment]
Welcome

**Comment by EwanValentine** [comment]
Would you add you custom plugins block within your `init.vim` file?  I have...

```
let g:spacevim_custom_plugins = [
  \ ['fatih/vim-go',               { 'on_ft' : 'go'}],
  \ ['keith/swift.vim',            { 'on_ft' : 'swift'}],
  \ ['leafgarland/typescript-vim', { 'on_ft' : 'typescript' }],
  \ ]
```

But I don't have Swift highlighting? Might be an issue with the plugin itself, but thought I'd double check

**Comment by wsdjeg** [comment]
This issue is too old, in current version of SpaceVim, we use toml as default configuration file, so if you want to add custom plugins, you could add:

```toml
# custom plugins {{{
[[custom_plugins]]
name = 'lilydjwg/colorizer'
merged = 0
# }}}
```

**Comment by wqingzex** [comment]
@wsdjeg 
where to write custom_plugins config?

**Comment by wsdjeg** [comment]
just press `SPC f v d`.

**Comment by wqingzex** [comment]
yes, for example I install aperezdc/vim-template, and want to set 
```
let g:templates_directory = '~/.templates.fork'
```

how can i do that

**Comment by wsdjeg** [comment]
please read online doc of spacevim

**Comment by wqingzex** [comment]
cann't find that

**Comment by liniminil** [comment]
@qingzew put it in the `bootstrap_before` function.
[https://spacevim.org/documentation/#bootstrap-functions](https://spacevim.org/documentation/#bootstrap-functions)

**Comment by TheAlienMann** [comment]
how should I install this plugin?

[Markdown preview, it’s got a nvim extension, I hink that is causing [](problem](https://github.com/iamcco/markdown-preview.nvim))

[https://github.com/iamcco/markdown-preview.nvim](url)

**Comment by dereckson** [comment]
Can you document how to write several plugins in the [[custom_plugins]] configuration block in TOML?

**Comment by wsdjeg** [comment]
Ok, I will update the document.
