### ISSUE TITLE
mac下部分图标乱码

### ISSUE THREAD

**Issue by kkooff114** [wsdjeg/SpaceVim#733]
![dfbf3846-866c-4572-a5ed-cf3d871fdfa3](https://user-images.githubusercontent.com/4495876/28365434-24ae7358-6cbb-11e7-89dd-5418650e4b00.png)

**Comment by wsdjeg** [comment]
你这是 终端还是macvim？ 另外，这个三角形不是乱麻，三角字体没有问题，倒是颜色有问题，左上角的问号确实是乱麻，我需要更新下安装教程。

**Comment by kkooff114** [comment]
@wsdjeg 乱码问题解决了, 但是三角形的问题如何解决?

**Comment by wsdjeg** [comment]
你提供的信息太少了，这个是终端还是gui.你的vim版本多少

**Comment by qichaotang** [comment]
@wsdjeg 乱码问题解决了么？我也是mac,vim 8.0,终端，也是 左上角的问号 问题

**Comment by kkooff114** [comment]
### MacVim(Custom Version 8.0.596 (133))
![image](https://user-images.githubusercontent.com/4495876/28583774-ed2cd79e-719c-11e7-8eec-7f6b4299bb16.png)

### Terminal
![image](https://user-images.githubusercontent.com/4495876/28583832-2d2f1f3c-719d-11e7-887c-3d0537c2e353.png)

### iTerm
![image](https://user-images.githubusercontent.com/4495876/28583858-4516ce9c-719d-11e7-80a9-5a8d82a4ae2a.png)

### 版本:
![image](https://user-images.githubusercontent.com/4495876/28583889-62bc7dd4-719d-11e7-9f09-f089c9335ccc.png)

----
目前iTerm不会乱码, 应该是设置了`Non-ASCII Font` 为`PowerLineSymbols`的原因.

但是:

1. iTerm的三角不对齐, 以及奇怪的三角颜色怎么解决
2. Terminal和MacVim怎么设置`Non-ASCII Font`?

@wsdjeg

**Comment by wsdjeg** [comment]
can you have a try with item2 instead of item.

**Comment by kkooff114** [comment]
我就是用的iterm2

**Comment by gradyjiang** [comment]
<img width="1001" alt="4d4b4760-baa3-476c-a26c-b661c3a5488c" src="https://user-images.githubusercontent.com/30748169/29125488-6fad7e5a-7d4e-11e7-9be7-261542e29067.png">


@wsdjeg 我这边是vim8.0 macOS10.12.7
左上角还是有个乱码，不知道是不是字符补丁里是不是确实这个特殊的字符？望dalao解答

**Comment by wsdjeg** [comment]
可以看下 #771
