### ISSUE TITLE
Content organization

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#738]
- what should be included in [readme](https://github.com/SpaceVim/SpaceVim/blob/dev/README.md)?
- what should be included in [core website](https://spacevim.org) and  https://github.com/SpaceVim/SpaceVim.github.io?
- what should be included in [wiki](https://github.com/SpaceVim/SpaceVim/wiki)?
- what should be included in [doc/SpaceVim.txt](https://github.com/SpaceVim/SpaceVim/blob/dev/doc/SpaceVim.txt)?

**Comment by jetm** [comment]
- **README** should be briefly: description project, an image of SpaceVim, install instructions, (documentation, wiki, ...) links and license footer.
- **core website**:  description project + install instructions as the first page, the rest of page should documentation, blog, link to github.
- **wiki**: FAQ section, how to contribute, how to custom or develop for SpaceVim, how to set up SpaceVim for specifying settings like SpaceVim as C/C++ IDE or SpaceVim as Java IDE and so on.
- **doc/SpaceVim.txt**: only keymap documentation and settings documentation.

**Comment by wsdjeg** [comment]
for long time , I do not know how to manger wiki's git log, now I want to use git subtree.

https://help.github.com/articles/about-git-subtree-merges/

**Comment by wsdjeg** [comment]
@jetm I will update the wiki and website, all the contents should be put in the website, and the wiki should a visual link network. becasue wiki can not be managed in the main repo.

the contents of the website is placed in `docs/` directory of the main repo. and it is easy to manage the website's content via git.

**Comment by hrokr** [comment]
Perhaps a second file, Quickstart.md, with a link from the readme.
