### ISSUE TITLE
SpaceVim is slow after a while. 

### ISSUE THREAD

**Issue by caoer** [wsdjeg/SpaceVim#740]
## Expected behavior, english is recommended
Hi, I've experiencing slowness using SpaceVIM for a while in a large node js project, namely if `node_modules/` folder contains a lot of files. If it's a small project, it acts fast. The difference is hard to see, but the feeling is very noticeable. This won't happen if the vim is being opened in a small project for a while. 

SO... I used a stupid method to test. I used an iPhone's stop timer to count, and then open a file, hold down 'w' key, see how long will it reach to the end of the file. If I use vim -u NONE, it is 12.89 seconds. If I use SpaceVIM, freshly opened, it's 12.69 seconds. They are quite same, but if I used it in a project I worked on for a while, (vim is been keep open for around 3 hours.) the test is 15.45 seconds. 

I tried different config settings, found out that if it seems NerdTree is slower than vimfiler, is it?. I'm using iterm2 + tmux + neovim. 

I guess it has something to do with a plugin's settings, can you point me any directions or plugin so I can lookup deeper? 

## Environment Information
- OS:
- vim version:
- neovim version:

### SpaceVim Options :

```viml
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_custom_plugins = [['plasticboy/vim-markdown', {'on_ft': 'markdown'}], ['mhinz/vim-sayonara'], ['caoer/nginx-vim-syntax'], ['vim-scripts/BufOnly.vim'], ['honza/dockerfile.vim'], ['keith/tmux.vim'], ['keith/cocoapods.vim']]
g:spacevim_buffer_index_type = 4
g:spacevim_gitcommit_pr_icon = 'p'
g:spacevim_error_symbol = '‚úñ'
g:spacevim_max_column = 120
g:spacevim_enable_insert_leader = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_dein_installed = 1
g:spacevim_enable_neomake = 1
g:spacevim_relativenumber = 1
g:spacevim_warning_symbol = '‚ö†'
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_denite_leader = 'f'
g:spacevim_enable_cursorline = 1
g:spacevim_leader_guide_vertical = 0
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.4.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_hiddenfileinfo = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = ''
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_debug = 0
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_enable_ycm = 0
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_neobundle_installed = 0
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_enable_powerline_fonts = 1
g:spacevim_simple_mode = 0
g:spacevim_enable_guicolors = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_gitcommit_issue_icon = 'i'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_guifont = ''
g:spacevim_language = ''
g:spacevim_plugin_bundle_dir = '/Users/caoer115/.cache/vimfiles/'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'nerdtree'
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_statusline_separator = 'arrow'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_enable_neocomplcache = 0
g:spacevim_auto_disable_touchpad = 1
g:spacevim_unite_leader = 'F'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'osx', 'lang#c', 'incsearch', 'lang#lua', 'lang#javascript', 'lang#vim', 'lang#xml', 'shell', 'tmux', 'colorscheme', 'core#banner']
g:spacevim_disabled_plugins = [['syngan/vim-vimlint'], ['Raimondi/delimitMate'], ['ujihisa/neco-look']]
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_leader_guide_hspace = 5
g:spacevim_windows_index_type = 2
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/HEAD-023f67c/bin/nvim)
version: 704
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file /Users/caoer115/.cache/SpaceVim/SpaceVim.log does not exists, only log for current process will be shown!
```

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by caoer** [comment]
I've noticed another thing when vim is slow, the cursor is being flashed in other places. much like in this: https://github.com/SpaceVim/SpaceVim/issues/660

but once I reopen it, it won't flash that often, only appear randomly.

**Comment by wsdjeg** [comment]
use vim with so many plugins, I recommend do not keep your vim open for long time, because many plugin save values or cache, and these thing will be bigger, it make vim slow.

**Comment by caoer** [comment]
got it!
