### ISSUE TITLE
:SPUpdate hangs

### ISSUE THREAD

**Issue by axler8r** [wsdjeg/SpaceVim#741]
## Expected behavior
`:SPUpdate` runs through all updates and gets stuck on last item `+SpaceVim: Updating...`

Here is the output form `ps -ef | grep vim` when `:SPUpdate` hangs:
```bash
axl       6252  6184  0 13:15 pts/18   00:00:02 vim
axl      19564 19399  1 13:19 pts/21   00:00:02 vim
axl      19578 19564  0 13:19 pts/21   00:00:00 python2 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() /home/axl/.cache/vimfiles/repos/github.com/floobits/floobits-neovim/rplugin/python/floobits
axl      30827 19564  0 13:20 pts/21   00:00:00 /usr/bin/fish -c rm -rf "/home/axl/.cache/vimfiles/.cache/init.vim/temp/21472"
```
Killing `vim` (neovim) doesn't break anything, but the update does not succeed — none of the 218 updates happened.

## Environment Information
- OS:
Ubuntu 16.04

- vim version:

- neovim version:
```bash
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-9avUof/neovim-0.1.7/build/config -I/build/neovim-9avUof/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-9avUof/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-9avUof/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

## The reproduce ways from Vim starting (Required!)
Start neovim. `:SPUpdate` press enter.

### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.4.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'base16-monokai'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 0
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = 'p'
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 100
g:spacevim_enable_debug = 0
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_enable_insert_leader = 1
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = 'i'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'linux', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/home/axl/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_filemanager = 'vimfiler'
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 704
OS: Linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log

```

## Screenshots

![screenshot from 2017-07-22 10-44-48](https://user-images.githubusercontent.com/16062326/28489757-fba3b09c-6eca-11e7-9744-f92ad825f2e7.png)

**Comment by wsdjeg** [comment]
can you please have a try with neovim v 0.2.0 or above?

**Comment by wsdjeg** [comment]
maybe it is not hangs, when all plugins is downloaded, dein will `re_cache_runtimepath`, it will merge all plugins into one path, and make `&rtp` shorter.

**Comment by Shougo** [comment]
Yes.  It seems the feature.

**Comment by axler8r** [comment]
There is no progress, even if I leave the update overnight.

**Comment by wsdjeg** [comment]
@axler8tor run `git -C ~/.vim checkout .` and reopen vim, run `:SPUpdate SpaceVim`

**Comment by axler8r** [comment]
Each time I do a `ps -ef | grep vim` while `:PSUpdate` is hanging, I see _this_ line `/usr/bin/fish -c rm -rf "/home/axl/.cache/vimfiles/.cache/init.vim/temp/XXXX"` where `XXXX` is a couple of numbers. After I delete the `/home/axl/.cache/vimfiles/.cache/init.vim/temp/XXXX` directory it shows up again in the next `ps`. Once I deleted all the directories and killed the process associated with it, the update succeeds.

**Comment by axler8r** [comment]
I tried `git -C ...`. `:SPUpate` still hangs. The previous steps (remove the `…/.cache/…` and kill the associated process, completes the `:SPUpdate`.

**Comment by wsdjeg** [comment]
dees `call dein#recache_runtimepath()` hangs?

**Comment by axler8r** [comment]
How can I check that?

**Comment by wsdjeg** [comment]
how long does vim hungs when run `:SPUpdate SpaceVim`?

**Comment by axler8r** [comment]
Forever.

**Comment by Shougo** [comment]
Why rm command is failed in fish shell...
I don't know.
Please change the shell in Vim.

`set shell=bash`

**Comment by Shougo** [comment]
And neovim ver.0.1.7 is too old.
The update of neovim is recommended.

**Comment by axler8r** [comment]
Setting the shell to bash worked.

**Comment by igalic** [comment]
in theory, `fish -c foo --bar "baz"` should _just_ work…

**Comment by wsdjeg** [comment]
@axler8tor I have update the plugin manager ui, we use `job` to run `build`, add will error will be show in the plugin manager buffer, like:
the build option is `'build' : ['composer', 'install']`, and it is a list. if the argv is not executeable, you will see the message.

![2017-07-29_581x133](https://user-images.githubusercontent.com/13142418/28742571-ce9d40cc-7465-11e7-99a5-935361f2d4c9.png)

in spacevim, we use dein paser plugin list, but we do not use dein to pull/build plugins. and dein's build use  `execute '!' . s:args2string(a:cmd)` to run build progress, it is not asynchronous, and do not support list.

@Shougo I think dein's plugin option : `build` should support list. and use job feature.

**Comment by Shougo** [comment]
@wsdjeg `build` supports list.

```
function! Args2String(args) abort
  return type(a:args) == type('') ? a:args :
        \ join(map(copy(a:args), '''"'' . v:val . ''"'''))
endfunction
```

You can test `:echo Args2String(['composer', 'install'])`.
It is `"composer" "install"`.
I think `composer` is not executable.

> @Shougo I think dein's plugin option : build should support list. and use job feature.

I don't use job feature.
Because, if I use job feature, it blocks the output.
I think it should not.

**Comment by wsdjeg** [comment]
why job will blocks the output ?

**Comment by Shougo** [comment]
It is the implementation problem.
dein should implement `:!` alternative.

**Comment by Shougo** [comment]
I have implemented the feature.
