### ISSUE TITLE
home page logo error

### ISSUE THREAD

**Issue by wYuanHpp** [wsdjeg/SpaceVim#742]
## system:osx ;vim8.0  
*  frist open spacevim and the home page logo looks weird. so it's right ?

![wechatimg754](https://user-images.githubusercontent.com/20528803/28491813-e3a31f78-6f29-11e7-815a-082c6ce6757e.jpeg)

**Comment by wsdjeg** [comment]
It is right, there are many kinds if logo, the a random one will be show when spacevim startup.
