### ISSUE TITLE
'Find files in the directory of the current buffer' broken when default shell is fish

### ISSUE THREAD

**Issue by everson** [wsdjeg/SpaceVim#743]
## Expected behavior

'Find files in the directory of the current buffer' (SPC f f) should list matching files as I type.

## Environment Information
- OS: MacOS 10.12.4
- vim version: 8.0.648 (MacVim) / 7.4 vim
- neovim version: v0.2.0

Note that this happens on MacVim 8, neovim (newest from Homebrew), stock vim 7.4.

## The reproduce ways from Vim starting (Required!)

- open vim in any directory
- type [Spc f f]
- get this as output http://take.ms/Qaqjd
- As I type, other 'ag' options are shown

### SpaceVim Options :
  ```
  1
  2 viml
  3 g:spacevim_enable_os_fileformat_icon = 0
  4 g:spacevim_leader_guide_position = 'botright'
  5 g:spacevim_version = '0.4.0-dev'
  6 g:spacevim_force_global_config = 0
  7 g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler']
  8 g:spacevim_default_indent = 2
  9 g:spacevim_enable_key_frequency = 0
 10 g:spacevim_enable_javacomplete2_py = 0
 11 g:spacevim_enable_powerline_fonts = 1
 12 g:spacevim_statusline_separator = 'arrow'
 13 g:spacevim_warning_symbol = '⚠'
 14 g:spacevim_simple_mode = 0
 15 g:spacevim_colorscheme = 'gruvbox'
 16 g:spacevim_enable_guicolors = 1
 17 g:spacevim_custom_plugins = []
 18 g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
 19 g:spacevim_buffer_index_type = 0
 20 g:spacevim_hiddenfileinfo = 1
 21 g:spacevim_statusline_inactive_separator = 'arrow'
 22 g:spacevim_gitcommit_pr_icon = 'p'
 23 g:spacevim_plugin_manager = 'dein'
 24 g:spacevim_error_symbol = '✖'
 25 g:spacevim_vim_plug_installed = 0
 26 g:spacevim_windows_leader = 's'
 27 g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
 28 g:spacevim_use_colorscheme = 1
 29 g:spacevim_enable_cursorcolumn = 0
 30 g:spacevim_colorscheme_bg = 'dark'
 31 g:spacevim_enable_neocomplcache = 0
 32 g:spacevim_leader_guide_sort_horizontal = 0
 32 g:spacevim_enable_cursorline = 1
 31 g:spacevim_lint_on_the_fly = 0
 30 g:spacevim_debug_level = 1
 29 g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
 28 g:spacevim_filemanager = 'vimfiler'
 27 g:spacevim_enable_vimfiler_gitstatus = 0
 26 
 25
 24
 23 ### SpaceVim Health checking :
 22
 21 SpaceVim clipboard support check report:
 20 Checking +clipboard:
 19     ¦ SUCCEED!
 18 SpaceVim environment check report:
 17 Current progpath: nvim(/usr/local/Cellar/neovim/0.2.0_1/bin/nvim)
 16 version: 704
 15 OS: OSX
 14 [shell, shellcmdflag, shellslash]: ['/usr/local/bin/fish', '-c', 0]
 13 SpaceVim lua support check report:
 12 Checking +lua:
 11     ¦ Failed : Known issue, neovim do not support lua now.
 10 SpaceVim python support check report:
  9 Checking +python3:
  8     ¦ Failed : to support +python3, you need run `pip3 install neovim`
  7 Checking +python:
  6     ¦ Failed : to support +python, you need run `pip2 install neovim`
  5
  4 ### SpaceVim runtime log :
  3
  2 log
  1 [ SpaceVim ] : logger file /Users/johnny/.cache/SpaceVim/SpaceVim.log does not exists, only log for current process will be shown!
111 
```
## Screenshots

https://asciinema.org/a/J09cMzCfZVO6zqBUO9ldstFw5

**Comment by wsdjeg** [comment]
I can confirm it is a bug. Will fix it.

**Comment by wsdjeg** [comment]
@everson I can not reproduce it within arch, my shell is bash.

**Comment by everson** [comment]
I thought it might be related to the fact that I use fish as my default shell. I tried starting from bash but it didn't help. I will later try to set bash as my default shell to see if that is the problem 

Enviado do meu iPhone

**Comment by wsdjeg** [comment]
here is some idea for debug:
1. what is the value of `g:ctrlp_user_command`
2. as I see when your vim startup a message is show `"." is a directory`, I think this should be the main reason. I will look into ctrlp's source code, and try to find how to debug it.

**Comment by everson** [comment]
Still not at a computer to try. But I have also tried invoking the command
with a file open via nerdtree.

Em dom, 23 de jul de 2017 às 09:37, Wang Shidong <notifications@github.com>
escreveu:

**Comment by wsdjeg** [comment]
I just read ctrlp src, here is how ctrlp run user command
```vim
	if s:usrcmdasync && v:version >= 800 && exists('*job_start')
		if exists('s:job')
			call job_stop(s:job)
		en
		let g:ctrlp_allfiles = []
		let s:job = job_start([&shell, &shellcmdflag, printf(lscmd, path)], {'callback': 'ctrlp#addfile'})
	elsei has('patch-7.4-597') && !(has('win32') || has('win64'))
		let g:ctrlp_allfiles = systemlist(printf(lscmd, path))
	el
		let g:ctrlp_allfiles = split(system(printf(lscmd, path)), "\n")
	en
```

I think ctrlp use job only for vim8, and not for neovim and old vim, in neovim and old vim, it use `system()` or `systemlist()`, and it is slow and not asynchronous.

**Comment by everson** [comment]
I reinstalled everything to make sure I didn't have any custom config or broken setup. Now I cannot even reproduce the issue on MacVim (8.xx), it closes the editor when I do `[SPC f f]`.

The value of `g:ctrlp_user_command` is:
```
g:ctrlp_user_command   ag %s --hidden -i  -g "" --ignore */tmp/* --ignore *.so --ignore *.swp --ignore *.zip --ignore *.class --ignore tags --ignore *.jpg --ignore *.ttf --ignore *.
TTF --ignore *.png --ignore */target/* --ignore .git --ignore .svn --ignore .hg --ignore .DS_Store --ignore *.svg
```

If I try the above command on fish, it outputs the same result I get when trying from macvim. If I try the same command from bash, then it results in a valid search. So, I believe that it is using the user shell but creating bash-specific commands.

**Comment by wsdjeg** [comment]
@everson you can not exe this command in shell,  the g:ctrlp_user_command is used as a argv of `printf()`

BTW, can you test with this step:
1. open macvim
2. run `:set shell=path/to/bash`, here maybe it is `/usr/bin/bash`, it depends of your os.
3. press `SPC f f`

**Comment by everson** [comment]
Doing that worked. Is this something I can override in spacevim settings?

**Comment by wsdjeg** [comment]
You can press `SPC f v d` then add one line `set shell=/usr/bin/bash`,then save the file with `:w`.

**Comment by everson** [comment]
Thank you @wsdjeg! Are you closing because it can be fixed via config or any code change have been done?

**Comment by wsdjeg** [comment]
Yeah, after add `set shell=/usr/bin/bash` to `~/.SpaceVim.d/init.vim` should works. I do not use fish, I do not know why ctrlp can not run the command.

**Comment by wsdjeg** [comment]
If it does not, will reopen it.

**Comment by everson** [comment]
Again, thank you! I updated the title to make it easier for other people having the same issue to find the solution.
