### ISSUE TITLE
<SPC> ff does not work on Windows 10.

### ISSUE THREAD

**Issue by Yggdroot** [wsdjeg/SpaceVim#745]
## Environment Information
- OS: windows
- vim version: 8.0.692
- neovim version:

## The reproduce ways from Vim starting (Required!)

Launch gvim, press <SPC>ff, it always shows "no entries".

## Screenshots

![qq 20170724172811](https://user-images.githubusercontent.com/2705841/28517033-b48a0b1c-7095-11e7-8888-9b49789e5024.png)

**Comment by wsdjeg** [comment]
I think it is due to how ctrlp run cmd.

**Comment by wsdjeg** [comment]
This should be fixed in #798
