### ISSUE TITLE
Some advice for spacevim

### ISSUE THREAD

**Issue by TesterlifeRaymond** [wsdjeg/SpaceVim#747]
## Environment Information
- OS: MacOs
- vim version: 8.0
- neovim version:

Hi dear wsdjeg:
     spacevim is so beautiful!

    im a pythoner , shortcuts are not enough to satisfy some of my application scenarios, 
        1: go to define function
        2: buffer run python file
        3: Automatic generation of file head
            example : 
                     """
                     # -*- coding: utf-8 -*-
                     # @Author:
                     # @Date:   2017-07-12 13:57:51
                     # @FileName:  test_bvt_cases.py
                     # @Project: test_appium
                     # @Last Modified by: 
                     # @Last Modified time: 2017-07-24 11:39:18
                    """

**Comment by wsdjeg** [comment]
will look into it later.
