### ISSUE TITLE
Question: how to force load "lazy plugin"

### ISSUE THREAD

**Issue by AdrianMusial** [wsdjeg/SpaceVim#754]
I checked documentation, faq, google etc. and can't find out how to forcibly load "lazy plugin"?
I'd like to be able to load 'ntpeters/vim-better-whitespace' plugin, which is defined in tools layer with:
```
\ ['ntpeters/vim-better-whitespace',  { 'on_cmd' : 'StripWhitespace'}],
```
So to load it I have to use command :StripWhitespace, which is uncomfortable, because I don't know if there actually are any extra whitespaces to use this command.

**Comment by wsdjeg** [comment]
@AdrianMusial in SpaceVim you can use `SPC t w` toggle the `whitespace status` in the statusline ( by default it is not shown), and if there are extra white space, you will see something like `< trailing[169] ` at the end of the statusline. BTW you can also use `SPC x d w` to delete the extra whitespace.

**Comment by AdrianMusial** [comment]
Yep, that's true, this just example. There are few more cases when I want to not lazy load particular plugins, but to force loading for them.
In this case my config:
```
autocmd ColorScheme * hi ExtraWhitespace ctermbg=red guibg=red
```
is not working without calling :StripWhitespace, but after that it works.

**Comment by wsdjeg** [comment]
press `SPC f v d` and add:

```vim
let g:spacevim_custom_plugins = [
            \ ['ntpeters/vim-better-whitespace', {'merged' : 0}],
            \ ]
```

**Comment by AdrianMusial** [comment]
Wow it works flawlessly! Thank you so much!

**Comment by wsdjeg** [comment]
welcome! 😄
