### ISSUE TITLE
Installation fails with "Key not present in dictionay"

### ISSUE THREAD

**Issue by jgogstad** [wsdjeg/SpaceVim#761]
On macOS Sierra

    brew install vim --with-override-system-vi --with-python3 --with-lua
    vim --version | head -n1
    # VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 30 2017 14:22:59)
    curl -sLf https://spacevim.org/install.sh | bash
    # This installs OK
    vim

The installation process fails with a lot of red lines saying

    Error detected while processing function 92[2]..<SNR>107_on_install_stdout:
    line    9:
    E716: Key not present in Dictionary: 18
    E116: Invalid arguments for function <SNR>107_msg_on_install_process
    E716: Key not present in Dictionary: 18
    E116: Invalid arguments for function <SNR>107_msg_on_install_process
    E716: Key not present in Dictionary: 18
    E116: Invalid arguments for function <SNR>107_msg_on_install_process
    Error detected while processing function 89[2]..<SNR>107_on_install_stdout:
    line    9:
    E716: Key not present in Dictionary: 17
    E116: Invalid arguments for function <SNR>107_msg_on_install_process
    E716: Key not present in Dictionary: 17
    E116: Invalid arguments for function <SNR>107_msg_on_install_process
    E716: Key not present in Dictionary: 17
    Error detected while processing function 89[2]..<SNR>107_on_install_stdout[9]..83[2]..<SNR>107_on_install_stdout:
    line    9:
    E716: Key not present in Dictionary: 15
    E116: Invalid arguments for function <SNR>107_msg_on_install_process
    Error detected while processing function 89[2]..<SNR>107_on_install_stdout[9]..360[2]..<SNR>107_on_install_exit:
    line   14:
    E691: Can only compare List with List
    E15: Invalid expression: get(s:pulling_repos[id], 'build', '') !=# ''
    Error detected while processing function 89[2]..<SNR>107_on_install_stdout[9]..357[2]..<SNR>107_on_install_exit:
    line   14:
    E691: Can only compare List with List
    E15: Invalid expression: get(s:pulling_repos[id], 'build', '') !=# ''

See the asciinema link at the bottom

## Environment Information
- OS: macOS Sierra 10.12.6
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 30 2017 14:22:59)
- neovim version: N/A

SpaceVim revision:
```
git --git-dir "$HOME/.SpaceVim/.git" log -1 | head -n1
# commit b1904b4098874c62219677225bcc858480b3edba
```

## The reproduce ways from Vim starting (Required!)
See description

## Output of the ':SPDebugInfo!'
```viml
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.4.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = 'p'
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = 'i'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'neocomplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'l
ang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'githu
b', 'denite', 'ctrlp', 'autocomplete', 'vim', 'osx', 'incsearch', 'lang#c', 'lang#elixir', 'lang#haskell', 'lang#java', 'lang#javascript', 'lang#l
ua', 'lang#perl', 'lang#php', 'lang#python', 'lang#rust', 'lang#swig', 'lang#tmux', 'lang#vim', 'lang#xml', 'shell', 'tools#screensaver', 'colorsc
heme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/jgogstad/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_leader_guide_vertical = 0
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_realtime_leader_guide = 1
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_filemanager = 'vimfiler'
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :
```
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 800
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.
```
### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file /Users/jgogstad/.cache/SpaceVim/SpaceVim.log does not exists, only log for current process will be shown!
```

## Screenshots

https://asciinema.org/a/t45vhIxSj6uN5HNCQmzhWAjdC

**Comment by jgogstad** [comment]
Thanks for taking the time looking at this @wsdjeg 

I'm afraid that your fix doesn't solve the problem. I did a `git pull` and got the same result, see https://asciinema.org/a/AeseqiQWA3s4mAGhhWH1y1FHX

**Comment by wsdjeg** [comment]
@jgogstad I can not reproduce it in latest version of spacevim, what is your vim version?

**Comment by wsdjeg** [comment]
can you test with
```
rm -rf ~/.vim
rm -rf ~/.SpaceVim
# then reinstall spacevim
```

**Comment by jgogstad** [comment]
Tried with no luck: https://asciinema.org/a/3QW7KsMAm3ncS13NfVAgy0NKS

Is there any other state I can delete?

**Comment by wsdjeg** [comment]
@jgogstad when the popmenu is opened,

```
dark powered mode
basic mode
```

then which key do you press?

**Comment by ssfdust** [comment]
How about having a try to neovim.Maybe there is something wrong with your vim, I guess.

**Comment by jgogstad** [comment]
This was solved by moving to neovim, just for the record

**Comment by yang** [comment]
Also seeing the same errors on a fresh installation of vim and spacevim. Using the latest vim and macvim from macports.

**Comment by yang** [comment]
![screen shot 2018-06-29 at 4 44 20 pm](https://user-images.githubusercontent.com/7129/42246531-cde63360-7ed1-11e8-96eb-96ae41ee43a9.png)

**Comment by XgDuan** [comment]
I have meet the same error today. Could you please tell me your solution? @yang

**Comment by ducalpha** [comment]
I got the same problem and got stuck today. Finally, the solution is to install vim 8:
```
sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim
```
