### ISSUE TITLE
doautocmd User CompleteParameterFailed

### ISSUE THREAD

**Issue by BlasphemyAngels** [wsdjeg/SpaceVim#763]
when I use the vim after update, I got a error when I use the complete：

os.path():doautocmd User CompleteParameterFailed

## Environment Information
- OS: arch linux
- vim version: 8.0

**Comment by wsdjeg** [comment]
this is issue with CompleteParameter, should be fixed by  https://github.com/tenfyzhong/CompleteParameter.vim/pull/14

**Comment by BlasphemyAngels** [comment]
what is it meaning? I don't understand. can you tell me how to fix it?

**Comment by wsdjeg** [comment]
I mean this is a issue with that plugin, and I can do nothing with it in spacevim.

**Comment by tenfyzhong** [comment]
This has fixed. Please run `:SPUpdate CompleteParameter.vim`
@wsdjeg this issue can be closed.

**Comment by wsdjeg** [comment]
Ok, I will test it tonight.

**Comment by wsdjeg** [comment]
@tenfyzhong  do you merge the dev branch of your plugin?

**Comment by tenfyzhong** [comment]
@wsdjeg merged.

**Comment by wsdjeg** [comment]
@tenfyzhong 
~~It does not work for me.~~

~~1. vim test.vim~~
~~2. press `o(((` you will see~~


sorry, it works.
