### ISSUE TITLE
output with bgcolor in iTerm2 when execute mvim after install spacevim

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#767]
## Environment Information
- OS:  Darwin MacBook-Pro-2.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
- vim version:mvim
- neovim version:0.3.0

## The reproduce ways from Vim starting (Required!)
$ mvim

## Screenshots

![image](https://user-images.githubusercontent.com/13595898/28912496-0e97a3f2-7867-11e7-8356-2266a363a923.png)

**Comment by wsdjeg** [comment]
I can not understand, do you use latest version of neovim?

**Comment by ghost** [comment]
我用的是mvim，
安装方式是
```
curl -sLf https://spacevim.org/install.sh | bash
```

**Comment by iPixelOldC** [comment]
我觉得这种终端配色突然出错，一般重开终端就好了吧。（我以前遇到过，不过可能情况和你不一样）所以，当你重开终端后，还是一样的问题？

 @wsdjeg mvim就是MacVim啦（据说和vim没啥差别）不是neovim啦

**Comment by ghost** [comment]
@iPixelOldC 其实敲换行就没问题了,但这也属于一个问题，你说是不？

**Comment by wsdjeg** [comment]
我算是明白问题了，你是在终端启动一个gui程序吗？然后终端有额外的输出？

**Comment by ghost** [comment]
是的

**Comment by wsdjeg** [comment]
这个问题，只能是macvim去修复了，spacevim只是vim 脚本，对gui程序的 stdout 没法修改的，而且，启动时候spacevim并没有打印任何东西到控制台。
