### ISSUE TITLE
About adding more intelligent objective-C auto completion

### ISSUE THREAD

**Issue by harrywang-1523** [wsdjeg/SpaceVim#770]
It seems that the SpaceVim comes with some auto-completion for objective-C but is not strong enough compared with [deoplete-clang2](https://github.com/tweekmonster/deoplete-clang2). No place holder was inserted. I am wondering if you could integrate this feature into your next version?

**Comment by wsdjeg** [comment]
deoplete-clang2 has  already been added to spacevim.
