### ISSUE TITLE
Neopair broken for () exiting, still working for [] {} and <>

### ISSUE THREAD

**Issue by bravecorvus** [wsdjeg/SpaceVim#772]
## Expected behavior, english is recommended
When creating an opening parenthesis, `(`, neopair generates the correct closing parenthesis and the placement of the cursor as follows: `(@CURSOR)`. After typing what you need to type, you just type `)` to exit the statement as follows: `(ENTERED TEXT)@CURSOR`

## Environment Information
- OS: macOS 10.12.6
- neovim version: v0.2.0 (Build type: Release) (has python3, no configuration issues, remote plugins up to date, ruby provider there)

## The reproduce ways from Vim starting (Required!)
When creating an opening parenthesis, `(`, neopair generates the correct closing parenthesis and the placement of the cursor as follows: `(@CURSOR)`. After typing what you need to type, typing `)` does not exit the statement, but instead adds an extra `)` to the the buffer as follows: `(ENTERED TEXT)@CURSOR)`

Note: the expected behavior is still working with `{}` and `[]`. Just the regular parenthesis is affected.

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
[![Error](https://68.media.tumblr.com/912c54a9521a1ed0b977af3f7e5927e6/tumblr_ouhez04U8W1s5a4bko1_540.png)](https://youtu.be/fQHmW0JDIa0)

**Comment by bravecorvus** [comment]
After a little more research, it has come to light that the specific plugin conflict is in neopairs.vim (which is responsible for generating the closing parenthesis automatically when `(` is typed and letting the user exit the brace via `)`.

I am not sure what could be causing this issue since the only keys I remapped for insert mode is `kj` for escape. I sure as hell do not remember changing `)` to be something else.

**Comment by emc2314** [comment]
Same here.
And one more problem, whenever I type something like "if (i < 5)" it turns out to be "if (i <5>)".

**Comment by wsdjeg** [comment]
@tenfyzhong I think this is issue with delimitMate and completeparameter, in spacevim, we use : 

```
  let g:delimitMate_matchpairs = '[:],{:},<:>'
  inoremap <silent><expr> ( complete_parameter#pre_complete("()")
```

so the complete pairs has been dieabled for `(`, I think maybe completeParameter use another `key` as the default mappings or use `completeDone` autocmd should be better.

**Comment by bravecorvus** [comment]
I'm not a vimscript ninja, so can you tell me what I need to do to bring back the previous behavior? Or is this something to be fixed on your end?

**Comment by tenfyzhong** [comment]
It's impossible to use CompleteDone event, the event was triggered when select an item. 
We can remove `let g:delimitMate_matchpairs = '[:],{:},<:>'`. I test it ok.

**Comment by bravecorvus** [comment]
Thanks fam
