### ISSUE TITLE
Vim shows a black screen on Mac with SpaceVim installed just now.

### ISSUE THREAD

**Issue by Ionizing** [wsdjeg/SpaceVim#773]
## Expected behavior, english is recommended
I cannot see any thing expect a black screen in terminal after I installed SpaceVim just now.

## Environment Information
- OS: OS X 10.11
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  9 2017 05:35:55)
- neovim version: Not installed

## The reproduce ways from Vim starting (Required!)
> $ vim

then the issue comes.

## Output of the ':SPDebugInfo!'
Sorry, I cannot see what I typed in vim.

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![screen shot 2017-08-11 at 3 03 51 am](https://user-images.githubusercontent.com/17506747/29187274-b88d73a2-7e41-11e7-80fc-c02bbb048a50.png)

**Comment by wsdjeg** [comment]
your terminal do not support true colors, you can have a try with item2

**Comment by Ionizing** [comment]
I got it. Thanks a lot.

Ionizing Radiation

On Aug 11, 2017, at 08:21, Wang Shidong <notifications@github.com<mailto:notifications@github.com>> wrote:


your terminal do not support true colors, you can have a try with item2

**Comment by wsdjeg** [comment]
welcome.
