### ISSUE TITLE
cannot disable autocomplete for delimters

### ISSUE THREAD

**Issue by vitiral** [wsdjeg/SpaceVim#774]
I tried removing the `delimitMate` plugin [as suggested in the example config](http://spacevim.org/documentation/)

```
let g:spacevim_disabled_plugins=[
\ ['Raimondi/delimitMate'],
\ ]
```

However, the plugin still seems to exist (at least it appears with `:h delmitMate`) and delmiters are stil auto completed.

Love this configuration btw!

**Comment by wsdjeg** [comment]
you need to use plugin name instead of repo name for this option.

```vim
let g:spacevim_disabled_plugins = ['delimitMate']
```

should works.

**Comment by vitiral** [comment]
ok, that stopped auto-completing quotes and `[]`, but parenthesis are still auto-completing (in multiple languages, I tried `.py`, `.rs`, `.js` and `.md` files)

**Comment by wsdjeg** [comment]
same issue as #772 

I this completeParameter should provide a plugin_mappings
