### ISSUE TITLE
Would like to be able to override readonly default

### ISSUE THREAD

**Issue by shoemakerdr** [wsdjeg/SpaceVim#775]
I can't find a place to override the readonly default. I've been searching around in the documentation and can't find where I can set to not readonly. I know about the buffer writable toggle, but I don't want to have to toggle it for every single buffer.

What I've been doing is `:set noro` whenever I open up vim, but this is annoying to do every time. Is there anywhere I could add that setting? I've tried adding it in the .vimrc and the init.vim files, but neither worked.

Thanks!

Derek

**Comment by shoemakerdr** [comment]
I was pulling my hair out last night on this one, and I still haven't figured it out, but I noticed that all the documentation points to configs being in the "\~/.SpaceVim.d/" directory. However, it automatically installed the SpaceVim.d directory in "\~/.SpaceVim". Could this be a source of my issue? I was looking at some of the script for loading custom configs, and they seem to assume .SpaceVim.d will be in my home directory.

**Comment by wsdjeg** [comment]
sorry for later reply, what is the output of `: verbose set readonly`

**Comment by shoemakerdr** [comment]
[vimlog.txt](https://github.com/SpaceVim/SpaceVim/files/1220976/vimlog.txt)
The output is the same:
`WARNING: Changing a readonly file`
And then when I make a change and try to save:
`E45: 'readonly' option is set (add ! to override)`

I did run it in verbose logging mode and sent it to a vimlog. The phrase readonly was repeated many times through the file-- mostly it seemed through calling the same function from vimfiler. It also called it once from startify. I attached a file with a couple selections from the vimlog.

**Comment by wsdjeg** [comment]
@shoemakerdr I think it is plugin's feature, when you open vim with out filename, then the welcome page and vimfiler will be opened by default, and these kind of  buffer are readonly.

but when start vim via `vim foo.txt`, then the welcome page will not been opened.

here is how I check the argv for vim:

```vim
function! s:parser_argv() abort
    if !argc()
        return [1, getcwd()]
    elseif argv(0) =~# '/$'
        let f = expand(argv(0))
        if isdirectory(f)
            return [1, f]
        else
            return [1, getcwd()]
        endif
    elseif argv(0) ==# '.'
        return [1, getcwd()]
    elseif isdirectory(expand(argv(0)))
        return [1, expand(argv(0)) ]
    else
        return [0]
    endif
endfunction
let s:status = s:parser_argv()
if s:status[0]
    let g:_spacevim_enter_dir = s:status[1]
    augroup SPwelcome
        au!
        autocmd VimEnter * call SpaceVim#welcome()
    augroup END
endif

```

**Comment by matiasbastos** [comment]
This issue is driving me crazy, used to have the version 0.6 and was ok, now on 0.7 I'm having this issue. There is a fix?
