### ISSUE TITLE
:SPUpdate will stuck because of the absense of unite-ctags repo

### ISSUE THREAD

**Issue by emc2314** [wsdjeg/SpaceVim#777]
## Expected behavior, english is recommended
Vim will stuck when Spacevim trying to update unite-ctags.

## Environment Information
- OS:  Any
- vim version: Any
- neovim version: Any

## The reproduce ways from Vim starting (Required!)
:SPUpdate <Enter>
And wait.

## Possible Reason
The repo [unite-ctags](http://github.com/voi/unite-ctags) does not exist anymore. Git will request username and password thus stuck there.

**Comment by jeremyjh** [comment]
Running into this too. I'm new to SpaceVim, is there a way to disable a package so that I can stop seeing the credentials prompt each time I open vim?

**Comment by ssfdust** [comment]
Same here.
It will prevent the credentials by deleting the related component from autoload/SpaceVim/layers/unite.vim. @jeremyjh 
But I think upstream will fix the problem very soon.So just wait...

**Comment by wsdjeg** [comment]
Thanks, I think it is due to the author delete the repo.
