### ISSUE TITLE
Failed to install unite-ctags

### ISSUE THREAD

**Issue by emhaye** [wsdjeg/SpaceVim#778]
This repo doesn't exists
https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/layers/unite.vim#L52

**Comment by wsdjeg** [comment]
Thanks, I will remove that plugin.

**Comment by hmozju** [comment]
hey,the plugin"unite-ctags could not auto-upgrade",when open vi ,it displays"unite-ctags:Installing Failed". so uh,could you please mend it , I'd appreciate it!

**Comment by wsdjeg** [comment]
Update SpaceVim

**Comment by hmozju** [comment]
I've tried this way,but it made no sense.


 

-------- 原始邮件 --------
发件人：Wang Shidong <notifications@github.com>
时间：周三 8月30日 18:32
收件人：SpaceVim/SpaceVim <SpaceVim@noreply.github.com>
抄送："M. Huang" <huangmin_ustc@163.com>,Comment <comment@noreply.github.com>
主题：Re: [SpaceVim/SpaceVim] Failed to install unite-ctags (#778)

**Comment by igalic** [comment]
git pull on .vim?

**Comment by wsdjeg** [comment]
@hmozju  you need run `git pull` in `~/.vim` in linux or mac, or `~/vimfiles` in windows.

**Comment by hmozju** [comment]
@wsdjeg @igalic Thank you for your help,problem fixed!
