### ISSUE TITLE
How do we remove SpaceVim from our system completely?

### ISSUE THREAD

**Issue by andysolomon** [wsdjeg/SpaceVim#78]
I made a mistake an installed this version of VIM. How do I completely remove it, as I don't want to use this at all.

**Comment by wsdjeg** [comment]
SpaceVim is not a editer, but just a config for vim, it is downloaded in `~/.SpaceVim` and make a link to `~/.vim`, you can just remove the link `~/.vim`, and copy your back_up `~/.vim_back` and `~/.vimrc_back` as `~/.vim` and `~/.vimrc`

**Comment by rguruprakash** [comment]
In my case, I have to also restore my `~/.config/nvim`

```
rm ~/.config/nvim
mv ~/.config/nvim_back ~/.config/nvim
```

**Comment by wsdjeg** [comment]
please read [How to uninstall SpaceVim?](https://spacevim.org/faq/#how-to-uninstall-spacevim) in FAQ page. or https://github.com/SpaceVim/SpaceVim/issues/1845#issuecomment-398245276
