### ISSUE TITLE
How to use org mode?

### ISSUE THREAD

**Issue by konradzdeb** [wsdjeg/SpaceVim#786]
I would like to know if it's possible to utilise the [org-mode](https://github.com/jceb/vim-orgmode) in [SpaceVim](http://spacevim.org/), the SpaceVim [*documentation*](http://spacevim.org/documentation/) refers to org mode:
> SPC t m c	toggle the org task clock (available in org layer)

However, the org-layer is not listed in [available layers](http://spacevim.org/layers/).

**Comment by wsdjeg** [comment]
as I know there is no org mode for vim.

**Comment by crisidev** [comment]
I used for years https://github.com/hsitz/VimOrganizer which is a more or less compatible version of orgmode for Vim. 

Please note, it requires Emacs as a dependency for some of the advanced stuff.

**Comment by zhujinxuan** [comment]
I think these questions should be answered before developing org-mode:

1. Shall we remap the keys?  By default, the vim-orgmode and VimOrganizer use `C-c` and `<localleader>` for org-mode operations; however, it is not consistent with SpaceVim behaviors. SpaceVim would like to use `SPC` or `SPC l` for org-modes operation with customized help infomation.

2. Shall we still use the keymaps heavily for org-mode;  The advantage of use `C-c` is that it is easy for insert-mode without leaving.  However, I think Ultisnips with python might be a better choice.  For example, we could customize `-tt inline` snippets that, for a time range `<12:00>-tt<TAB>`, we would get `<12:00-currenttime>`.  I think we could operate org-mode faster by ultisnips rather by insert-mode keymaps.

3.  What are we doing with org-mode?  Personally, I am using org-mode for life management and book reading notes.  Therefore, I will write some ultisnip snippets for time statistics and alike.  My question here is that, except the default functions by VimOrganizer or by vim-orgmode or by emacs-orgmode,  is there anything else we should provide?

**Comment by crisidev** [comment]
I use it mostly for note taking and exporting in various formats. Also calendars and tasks integration is quite handy. I pull the tasks from my work task manager and update them inside org mode using a custom python plugin. 

Regarding the mapping, I think it should follow spacevim general rules, but also leave the user the possibility to use the default Emacs like mapping.

**Comment by wsdjeg** [comment]
I just create https://github.com/SpaceVim/org-mode, and I will working on it later.

I think use spacevim default snippt plugin neosnippet will be better.

for key mapping, I think SPC l is easy to press than C-c, and if all the mapping only will be used in org buffer. I think language specified mapping will be better

**Comment by PeteW** [comment]
I use [vim org mode](https://github.com/jceb/vim-orgmode) on top of spacevim. I just add the plugin like any other to my init.vim and it seems to work fine out of the box without any conflicts that I've encountered.

**Comment by wsdjeg** [comment]
@PeteW Thanks for your info. :)

**Comment by wsdjeg** [comment]
I just have forked VimOrganizer into org-mode, and will make some changed.

**Comment by wsdjeg** [comment]
@konradedgar If you want to use vim-orgmode, you can use org mode on top of spacevim, just like what petew did.

**Comment by vnijs** [comment]
Just noticed this was closed. What is the recommended process to enable org-mode exactly? Thx

**Comment by zhujinxuan** [comment]
@vnijs I think both wsdjeg and I do not have time on that.

**Comment by vnijs** [comment]
Got it @zhujinxuan. I was just wondering how to enable org-mode as @PeteW suggested. It seems that adding the following to .SpaceVim.d/init.toml works:

```
[[custom_plugins]]
name = 'jceb/vim-orgmode'
```

**Comment by wsdjeg** [comment]
hello, everyone, I have opened new issue about the org mode in vim:

https://github.com/SpaceVim/SpaceVim/issues/3793
