### ISSUE TITLE
gq for reformatting doesn't work

### ISSUE THREAD

**Issue by vitiral** [wsdjeg/SpaceVim#787]
## Expected behavior
The command `gq` in normal mode usually results in auto-text wrapping, as described [here](https://robots.thoughtbot.com/wrap-existing-text-at-80-characters-in-vim) or via `:h gq`. However, this was removed (and q is not mapped to anything).

## Possible Workaround
A workaround is to just add `nnoremap gq gq` to the top of `~/.SpaceVim.d/init.vim`

**Comment by vitiral** [comment]
A workaround is to just add `nnoremap gq gq` to the top of `~/.SpaceVim.d/init.vim`

**Comment by wsdjeg** [comment]
@vitiral when will you use `gq`?

**Comment by vitiral** [comment]
mostly when editing documentation strings or markdown files. When I change anything I just press `gq` and the entire block of text is formatted to 80 columns.

**Comment by wsdjeg** [comment]
ok, I have added this mappings.
