### ISSUE TITLE
emmet cant't work with "C-y ,"

### ISSUE THREAD

**Issue by xushaobo** [wsdjeg/SpaceVim#788]
I have already reinstall and update Spacevim several times,and the emmet(html plug) can't work in Spacevim. However when I try the command ":help emmet" ,it really shows the help and show me some examples as:  Type abbreviation as 'div>p#foo$*3>a' and type '<C-y>,'.
So,I think the Plug has already be installed right?
But how can I use it with the right way.I really really ... hate writing html by hand -.-
Any help or Suggestions can help me out the hot water.

**Comment by milkdeliver** [comment]
Same issue here.Not working with emmet shortcut.Any solutions?
