### ISSUE TITLE
:Ack command conflict with phpfold#Fold (Invalid range)

### ISSUE THREAD

**Issue by xushaobo** [wsdjeg/SpaceVim#789]
The error message:
Error detected wile processing function <SNR>263 doFold[2]..phpfold#Fold:
line  8:
E16: Invalid range: 25,30fold

**Comment by wsdjeg** [comment]
@xushaobo  what is the reproduce step?

**Comment by wsdjeg** [comment]
I just test ack.vim. it is too old, and is unmaintained, BTW, when use `:Ack foo` the result will be outout to terminal. I think this kind of plugin should use background search command instead,

I recommand to use `ag.vim` and the command is `:Ag`.
