### ISSUE TITLE
unite-ctags could not auto-upgrade

### ISSUE THREAD

**Issue by lujianmei** [wsdjeg/SpaceVim#791]
unite-ctags could not auto-upgrade, because it does not exist anymore.

![image](https://user-images.githubusercontent.com/6612785/29506315-9f48d83e-867d-11e7-81c8-b70d915db296.png)

**Comment by Shougo** [comment]
https://github.com/SpaceVim/SpaceVim/issues/778
https://github.com/SpaceVim/SpaceVim/issues/777

**Comment by lujianmei** [comment]
thanks, that was quick response.
checkout to dev, and it is ok now.

**Comment by wsdjeg** [comment]
this issue has been fixed on dev branch.

**Comment by hmozju** [comment]
so how to solve this problem?

**Comment by zhujinxuan** [comment]
@hmozju It will be solved in next master I think.  Or you could try `git pull origin dev` at `.vim` at this moment.
