### ISSUE TITLE
wrong arg parsing

### ISSUE THREAD

**Issue by kaldown** [wsdjeg/SpaceVim#802]
![2017-08-26--22 31 15_345x215_scrot](https://user-images.githubusercontent.com/3754017/29744495-57265f38-8aae-11e7-99ca-7d22aec7401d.png)

vim: 8.0
OS: debian 9

No custom config

**Comment by wsdjeg** [comment]
@kaldown what the issue is? `[B]` is not omni source, is just buffer source, which contains the words from current buffer.

**Comment by kaldown** [comment]
@wsdjeg the issue is about giving wrong possible params when bracket opens

**Comment by wsdjeg** [comment]
OK I will test it.

**Comment by wsdjeg** [comment]
in SpaceVim, after completion done, there are two kind of argv expand plugins, one is neosnippet, and the other is CompleteParameter.vim.

here is the a terminal record:

https://asciinema.org/a/MurO3TodhdHFJt7yIv1kh8bFY

@tenfyzhong I think neosnippet works well, but I am not sure why I can not get your plugin working.

**Comment by tenfyzhong** [comment]
I use `v:completed_item` to complete the parameters. It seems the completion engine give wrong message. Please give me complete engine configuration. 

btw, I think @kaldown only want the completed items `arg1` and `arg2`, but not other three items?

**Comment by wsdjeg** [comment]
ok, I will check the value of `v:completed_item`

**Comment by wsdjeg** [comment]
I have reproduce this issue, and the `v:complete_item` is 

```
{'word': 'test_func', 'menu': '[jedi] ', 'info': 'test_func(arg1, arg2)', 'kind': 'function', 'abbr': 'test_func(arg1, arg2)'}
```

**Comment by tenfyzhong** [comment]
CompleteParameter is not support jedi. I will support tomorrow.

**Comment by wsdjeg** [comment]
Thanks, it works fixed.
