### ISSUE TITLE
How to overwrite some default SPC mapping?

### ISSUE THREAD

**Issue by zhujinxuan** [wsdjeg/SpaceVim#807]
Hi, I am trying to swap the `SPC c l` with `SPC c L`, for using `l` for toggle comments and `L` for comment, because it is more frequent to uncomment a line than comment a line twice.   But I failed 
to swap the default setting by 
``` vim
call SpaceVim#custom#SPC('nmap', ['c', 'L'], '<Plug>NERDCommenterComment', 'comment lines', 0, 1)
call SpaceVim#custom#SPC('nmap', ['c', 'l'], '<Plug>NERDCommenterInvert', 'toggle comment lines', 0, 1)
call SpaceVim#custom#SPC('nmap', ['c', 'P'], 'vip<Plug>NERDCommenterComment', 'comment paragraphs', 0, 1)
call SpaceVim#custom#SPC('nmap', ['c', 'p'], 'vip<Plug>NERDCommenterInvert', 'toggle comment paragraphs', 0, 1)
```

Is there a method in SpaceVim#custom or Space#mappings to overwrite or erase the default key mappings?  
Thanks a lot.

**Comment by zhujinxuan** [comment]
Sorry, I just find that I should not use `0` in the function arguments... My mistake.

Sorry for wasting your time.

**Comment by wsdjeg** [comment]
welcome. 👍
