### ISSUE TITLE
Detect of rust files as hercules one.

### ISSUE THREAD

**Issue by mnivoliez** [wsdjeg/SpaceVim#81]
When opening a rust file like `main.rs`, the file is detect as a rust file but upon entering insert mode, the file get detect as a hercules file.
[When opening the file](https://gyazo.com/18f7614bcbf3d16f62a601fa628693b7)
[When entering insert mode](https://gyazo.com/8090a1b7703f5e25fbfad205fac94286)

A similar issue was reference at [rust.vim](https://github.com/rust-lang/rust.vim/issues/10) but the workaround proposed isn't working.

**Comment by wsdjeg** [comment]
can reproduced, but I can not fix it , I will look into it.

**Comment by wsdjeg** [comment]
@Shougo, I can not reproduce without SpaceVim, it should a issue with some plugin with `on_i` option.
1. start vim , vim test.rs
2. `:verbose set filetype
```
filetype=rust                                                                                                                                        
        Last set from ~/.cache/vimfiles/.cache/init.vim/.dein/ftdetect/ftdetect.vim
```
3. type `i`, then `esc`, then `:verbose set filetype`
```
iletype=hercules                                                                                                                                    
        Last set from /usr/local/share/nvim/runtime/filetype.vim 
```

**Comment by mnivoliez** [comment]
@wsdjeg, that's exactly the output I get when running the same command.

**Comment by wsdjeg** [comment]
@mnivoliez It is dein bug, Shougo will fix it, please wait. and thanks for feedback.

**Comment by Shougo** [comment]
I have fixed the problem.
Please update dein.vim.

**Comment by wsdjeg** [comment]
LGTM, thanks, clossing

**Comment by mnivoliez** [comment]
Sadly the issue appeared again.

**Comment by wsdjeg** [comment]
Update dein, Now it works well for me.

**Comment by mnivoliez** [comment]
```
rm -rf .cache/vimfiles
nvim
```
Still got the problem.

**Comment by wsdjeg** [comment]
@mnivoliez why do you rm all the vimfiles?

what you should do is just `call dein#update()`.

**Comment by wsdjeg** [comment]
@mnivoliez oh, sorry, it is my fault, SpaceVim do not load rust layer now , I will fix it.

**Comment by wsdjeg** [comment]
@mnivoliez please update spacevim, and read `:h SpaceVim-config` and `:h SpaceVim-layer-lang-rust`.

**Comment by mnivoliez** [comment]
I updated SpaceVim, `call dein#update()` just in case and add `call SpaceVim#layers#load('lang#rust')` to my `local.vim`. But still, my file.rs is still detected as hercule one.

**Comment by wsdjeg** [comment]
You should use ~/.SpaceVim.d/init.vim, and you can create new issue with issue_tamplete.

**Comment by mnivoliez** [comment]
Never mind, I change to SpaceVim.d and the bug disappeared.

**Comment by wsdjeg** [comment]
greate, enjoy spacevim.
