### ISSUE TITLE
Request for a Clojure layer

### ISSUE THREAD

**Issue by abhi18av** [wsdjeg/SpaceVim#813]
Hi everyone,

I was wondering whether there are plans to include a clojure layer as well?

Perhaps with the neovim nodejs client and `lumo` , it could be really handy.

**Comment by wsdjeg** [comment]
I will look into it. and any recommend plugins do you use?

**Comment by abhi18av** [comment]
Yup. I'll link to some blog posts which explain how things go together.

- https://blog.jeaye.com/2016/11/30/vim-clojure/

- https://juxt.pro/blog/posts/vim-1.html

- http://blog.cognitect.com/blog/2017/4/17/clojure-for-neovim-for-clojure

There is also a `clojure-vim` organization here which focuses specifically on `neovim`

- https://github.com/clojure-vim

**Comment by wsdjeg** [comment]
great, I will have a look.

**Comment by zhujinxuan** [comment]
@abhi18av It will help a lot if you could provide part of your old/current .vimrc that related to the closure.  Then I could try to write a closure layer based on your old config(if @wsdjeg does not mind).

BTW, do you use vim-slime and REPL in developing clojure scripts?

**Comment by wsdjeg** [comment]
@zhujinxuan  PR is welcome, 👍 .

**Comment by abhi18av** [comment]
Hi @zhujinxuan ,

Oh, my dotFiles are pretty much in a mess atm but I'd start again with http://markwoodhall.com/21-05-2016-my-clojure-workflow-and-setup/ as a guiding principle.

Thanks for volunteering on this one :+1:

**Comment by wsdjeg** [comment]
@abhi18av I will add a `lang#clojure` layer, and these feature should be supported:

1. autocompletion
2. syntax checking
3. REPL
