### ISSUE TITLE
Keybindings for vim-orgmode

### ISSUE THREAD

**Issue by zhujinxuan** [wsdjeg/SpaceVim#815]
I am customizing some keymaps for vim-orgmode.  But I find some problems in choosing the keymaps.  By default, the vim-org use `<localleader>` and a quick fix is to use C-c as `<localleader>`.  However, this solution cannot take advantage from SpaceVim's help info after `[SPC]`.

Therefore, I have some questions for the key mode in the SpaceVim
1. How to write a SpaceVim keymode to display help info and prepare for the following keymaps? (like `[SPC]` and `[SPC] t`)
2. How to ensure the key mode only works in org files.  Because, in other code files, I would like to use `C-c` for vim-slime. 

Thanks a lot for developing SpaceVim~

**Comment by wsdjeg** [comment]
@zhujinxuan It should be language specified mappings, you can checkout lang#java layer, but language specified mappings must begin with `[SPC] l`.

I do not edit org file, which plugin do you use for org file?

**Comment by zhujinxuan** [comment]
@wsdjeg I use only vim-orgmode.  However, it is not as powerful as emacs org-mode.  I am writing some ultisnips snippets to empower it. 

Related to the org-mode, there are often some user customized global keymaps to open `~/org/diary.org`, `~/org/todo.org` and some agenda files alike.  I think it might be not very good to maps these keymaps to `[SPC] l`.  Shall I map them to `SPC j` or some alike?

BTW, about `[SPC] l`, does that mean any keymaps in `[SPC] l` is local in buffer and is not worried about conflicts with other keymaps?  I do not see document in [http://spacevim.org/documentation/](http://spacevim.org/documentation).

**Comment by crisidev** [comment]
Have you tried https://github.com/hsitz/VimOrganizer ? it is nearly as powerful as Emacs orgmode. I would like to integrate it as a layer as soon as I have time.

**Comment by zhujinxuan** [comment]
@crisidev No yet.  I once worried about it because its development stopped 3 years ago.  But I will have a try~

**Comment by wsdjeg** [comment]
maybe we can create a org-mode repo in SpaceVim org. and includes the feature we want.

**Comment by wsdjeg** [comment]
and I do not want to use plugins which will not be updated. It will make it hard to debug and fix bug.

**Comment by wsdjeg** [comment]
@zhujinxuan @crisidev let's move talk to #786
