### ISSUE TITLE
need TypeScript lang layer

### ISSUE THREAD

**Issue by eperfect** [wsdjeg/SpaceVim#816]
use leafgarland/typescript-vim to edit typescript language,suggest to add typescript layer

**Comment by wsdjeg** [comment]
@eperfect any recommend plugins for typescript?

**Comment by eperfect** [comment]
just leafgarland/typescript-vim,i think other plugins such as easymotion,youcompleteme are in common use

**Comment by andrewdhazlett** [comment]
https://github.com/Quramy/tsuquyomi would also be nice. I'm happy to help out on this

**Comment by wsdjeg** [comment]
I start to working on this layer.
