### ISSUE TITLE
Cannot install Custom Plugins

### ISSUE THREAD

**Issue by EItanya** [wsdjeg/SpaceVim#819]
## Expected behavior,
I am trying to download custom plugins, but dein is throwing an error telling me that vim-scripts.org is deprecated. After this message the download fails. 

## System
- OS: MAC OS 10.12.16
- vim version:
- neovim version: 0.2.0

## Reproduction
To reproduce this error simple start up nvim

## Custom Config
" Dark powered mode of SpaceVim, generated by SpaceVim automatically.
let g:spacevim_enable_debug = 1
let g:spacevim_realtime_leader_guide = 1

let g:spacevim_plugin_manager = 'dein'

call SpaceVim#layers#load('ui')
call SpaceVim#layers#load('incsearch')
call SpaceVim#layers#load('lang#c')
call SpaceVim#layers#load('lang#java')
call SpaceVim#layers#load('lang#javascript')
call SpaceVim#layers#load('lang#perl')
call SpaceVim#layers#load('lang#python')
call SpaceVim#layers#load('lang#tmux')
call SpaceVim#layers#load('lang#vim')
call SpaceVim#layers#load('shell')
call SpaceVim#layers#load('tools#screensaver')
let g:spacevim_enable_vimfiler_welcome = 1
let g:spacevim_enable_debug = 1
let g:deoplete#auto_complete_delay = 150
let g:spacevim_enable_tabline_filetype_icon = 1
let g:spacevim_enable_os_fileformat_icon = 1
let g:spacevim_buffer_index_type = 1
let g:neomake_vim_enabled_makers = []

let g:spacevim_plugin_groups_include = ['javascript', 'core', 'web', 'lang', 'autocomplete']
let g:spacevim_custom_plugins = ['valloric/youcompleteme']

if executable('vimlint')
    call add(g:neomake_vim_enabled_makers, 'vimlint')
endif
if executable('vint')
    call add(g:neomake_vim_enabled_makers, 'vint')
endif
if has('python3')
    let g:ctrlp_map = ''
    nnoremap <silent> <C-p> :Denite file_rec<CR>
endif
let g:clang2_placeholder_next = ''
let g:clang2_placeholder_prev = ''

" User Settings
let g:spacevim_default_indent = 4
let g:spacevim_max_column = 80
let g:spacevim_colorscheme = 'onedark'

## Screenshots

![screen shot 2017-09-01 at 1 27 04 pm 3](https://user-images.githubusercontent.com/4185086/29983430-65087e12-8f1b-11e7-99eb-26b1446b491d.png)

**Comment by wsdjeg** [comment]
@EItanya I think you can remove 

```
let g:spacevim_plugin_groups_include = ['javascript', 'core', 'web', 'lang', 'autocomplete']
let g:spacevim_custom_plugins = ['valloric/youcompleteme']
```

I do not recommend to use `g:spacevim_plugin_groups_include`, BTW if you want to use YCM, you can read `:h g:spacevim_enable_ycm`

**Comment by wsdjeg** [comment]
@EItanya I think you need read `:h g:spacevim_custom_plugins`, this option is a list, and each item also is list.
