### ISSUE TITLE
Errors when opening a Typescript

### ISSUE THREAD

**Issue by nicpolhamus** [wsdjeg/SpaceVim#822]
## Environment Information
- OS: MacOS 10.12.6
- vim version: 8.0
- neovim version: 0.2.0

## The reproduce ways from Vim starting (Required!)
I'm running off of a base install of SpaceVim. Errors occur whenever I open up a typescript file.

## Output of the ':SPDebugInfo!'
Error detected while processing function <SNR>268_HighlightEnclosingTagsIfPossible[
12]..<SNR>268_HighlightEnclosingTags:
line    1:
E714: List required
line    5:
E121: Undefined variable: opening_tag_line
E15: Invalid expression: opening_tag_line < first_window_line
line    9:
E121: Undefined variable: opening_tag_line
E15: Invalid expression: '2match ' . s:match_group . ' /' . '\(\%' . opening_tag_line . 'l\%' . opening_tag_column . 'c<\/\?\_s*\zs.\{-
}\ze[ >\/\n]\)\|' . '\(\%' . closing_tag_line . 'l\%' . closing_tag_column . 'c<\/\?\_s*\zs.\{-}\ze[ >\/]\)' . '/'

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
hi @BagelTheKid SpaceVim do not has typescript layer now, see #816 , we are working on this layer.
