### ISSUE TITLE
请问显示的行数是动态的，这个怎么在vim里面使用？

### ISSUE THREAD

**Issue by banduoba** [wsdjeg/SpaceVim#826]
[比如移动到70行，70行上下显示的行的数字是1-20，如附件图片，请问为什么这么显示以及如何使用这个动态显示呢？
<img width="847" alt="ww" src="https://user-images.githubusercontent.com/4811366/30092723-3e06e99e-92f3-11e7-9f4f-7fb0f87ca8b7.png">

**Comment by wsdjeg** [comment]
read, `:h nu` and `:h rnu`
