### ISSUE TITLE
 SpaceVim#end..SpaceVim#plugins#load

### ISSUE THREAD

**Issue by hongjiujing** [wsdjeg/SpaceVim#827]
## Environment Information
- OS:Ubuntu14.04
- vim version:7.4
- neovim version:

## The reproduce ways from Vim starting (Required!)
vim file
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..<SNR>38_load_plugins..<SNR>38_loadLayerConfig..SpaceVim#layers#edit#config:
line   16:
E121: Undefined variable: g:_spacevim_mappings_space
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load..<SNR>38_load_plugins:
line   16:
E170: Missing :endfor
Error detected while processing function SpaceVim#end..SpaceVim#plugins#load:
line    4:
E171: Missing :endif
Error detected while processing /home/tommy/.SpaceVim/vimrc:
line    3:
E171: Missing :endif
Press ENTER or type command to continue

## Output of the ':SPDebugInfo!'
NERDRPlace             <]
spacevim_enable_os_fileformat_icon #0
spacevim_leader_guide_position  botright
spacevim_version       0.5.0-dev
EasyMotion_off_screen_search #1
spacevim_force_global_config #0
unite_source_menu_menus {'MpvPlayer': {'command_candidates': [], 'description': 'Musics list                   <leader>lm'}, 'AddedPlugins': {'command_candidates': [['
[lang]                   [groenewege/vim-less]                     [lazy loaded]  [{''on_ft'': [''less'']}]', 'OpenBrowser https://github.com/groenewege/vim-less'], ['
[lang]                   [cakebaker/scss-syntax.vim]               [lazy loaded]  [{''on_ft'': [''scss'', ''sass'']}]', 'OpenBrowser https://github.com/cakebaker/scss-
syntax.vim'], ['[lang]                   [hail2u/vim-css3-syntax]                  [lazy loaded]  [{''on_ft'': [''css'', ''scss'', ''sass'']}]', 'OpenBrowser https://g
ithub.com/hail2u/vim-css3-syntax'], ['[lang]                   [ap/vim-css-color]                        [lazy loaded]  [{''on_ft'': [''css'', ''scss'', ''sass'', ''le
ss'', ''styl'']}]', 'OpenBrowser https://github.com/ap/vim-css-color'], ['[lang]                   [othree/html5.vim]                        [lazy loaded]  [{''on_ft''
: [''html'']}]', 'OpenBrowser https://github.com/othree/html5.vim'], ['[lang]                   [wavded/vim-stylus]                       [lazy loaded]  [{''on_ft'': [
''stylus'']}]', 'OpenBrowser https://github.com/wavded/vim-stylus'], ['[lang]                   [digitaltoad/vim-jade]                    [lazy loaded]  [{''on_ft'': [
''jade'']}]', 'OpenBrowser https://github.com/digitaltoad/vim-jade'], ['[lang]                   [juvenn/mustache.vim]                     [lazy loaded]  [{''on_ft'':
[''mustache'']}]', 'OpenBrowser https://github.com/juvenn/mustache.vim'], ['[lang]                   [leafgarland/typescript-vim]              [lazy loaded]  [{''on_ft
'': [''typescript'']}]', 'OpenBrowser https://github.com/leafgarland/typescript-vim'], ['[lang]                   [kchmck/vim-coffee-script]                [lazy loade
d]  [{''on_ft'': [''coffee'']}]', 'OpenBrowser https://github.com/kchmck/vim-coffee-script'], ['[lang]                   [elzr/vim-json]                           [laz
y loaded]  [{''on_ft'': [''javascript'', ''json'']}]', 'OpenBrowser https://github.com/elzr/vim-json'], ['[lang]                   [elixir-lang/vim-elixir]
      [lazy loaded]  [{''on_ft'': ''elixir''}]', 'OpenBrowser https://github.com/elixir-lang/vim-elixir'], ['[lang]                   [PotatoesMaster/i3-vim-syntax]
         [lazy loaded]  [{''on_ft'': ''i3''}]', 'OpenBrowser https://github.com/PotatoesMaster/i3-vim-syntax'], ['[lang]                   [isundil/vim-irssi-syntax]
              [lazy loaded]  [{''on_ft'': ''irssi''}]', 'OpenBrowser https://github.com/isundil/vim-irssi-syntax'], ['[lang]                   [lervag/vimtex]
                  [lazy loaded]  [{''on_ft'': ''tex''}]', 'OpenBrowser https://github.com/lervag/vimtex'], ['[lang]                   [vimperator/vimperator.vim]
         [lazy loaded]  [{''on_ft'': ''vimperator''}]', 'OpenBrowser https://github.com/vimperator/vimperator.vim'], ['[lang]                   [voxpupuli/vim-puppet]
                   [lazy loaded]  [{''on_ft'': ''puppet''}]', 'OpenBrowser https://github.com/voxpupuli/vim-puppet'], ['[lang]                   [peterhoeg/vim-qml]
                    [lazy loaded]  [{''on_ft'': ''qml''}]', 'OpenBrowser https://github.com/peterhoeg/vim-qml'], ['[lang]                   [cespare/vim-toml]
               [lazy loaded]  [{''on_ft'': ''toml''}]', 'OpenBrowser https://github.com/cespare/vim-toml'], ['[edit]                   [tpope/vim-surround]', 'OpenBrow
ser https://github.com/tpope/vim-surround'], ['[edit]                   [tpope/vim-repeat]', 'OpenBrowser https://github.com/tpope/vim-repeat'], ['[edit]
     [junegunn/vim-emoji]', 'OpenBrowser https://github.com/junegunn/vim-emoji'], ['[edit]                   [terryma/vim-multiple-cursors]', 'OpenBrowser https://gith
ub.com/terryma/vim-multiple-cursors'], ['[edit]                   [terryma/vim-expand-region]               [lazy loaded]  [{''loadconf'': 1}]', 'OpenBrowser https://g
ithub.com/terryma/vim-expand-region'], ['[edit]                   [kana/vim-textobj-user]', 'OpenBrowser https://github.com/kana/vim-textobj-user'], ['[edit]
         [kana/vim-textobj-indent]', 'OpenBrowser https://github.com/kana/vim-textobj-indent'], ['[edit]                   [kana/vim-textobj-line]', 'OpenBrowser https
://github.com/kana/vim-textobj-line'], ['[edit]                   [kana/vim-textobj-entire]', 'OpenBrowser https://github.com/kana/vim-textobj-entire'], ['[edit]
             [scrooloose/nerdcommenter]                [lazy loaded]  [{''loadconf'': 1}]', 'OpenBrowser https://github.com/scrooloose/nerdcommenter'], ['[edit]
            [mattn/emmet-vim]                         [lazy loaded]  [{''on_cmd'': ''EmmetInstall''}]', 'OpenBrowser https://github.com/mattn/emmet-vim'], ['[edit]
               [gcmt/wildfire.vim]                       [lazy loaded]  [{''on_map'': ''<Plug>(wildfire-''}]', 'OpenBrowser https://github.com/gcmt/wildfire.vim'], ['[
edit]                   [easymotion/vim-easymotion]', 'OpenBrowser https://github.com/easymotion/vim-easymotion'], ['[edit]                   [haya14busa/vim-easyopera

tor-line]', 'OpenBrowser https://github.com/haya14busa/vim-easyoperator-line'], ['[edit]                   [editorconfig/editorconfig-vim]           [lazy loaded]  [{'
'on_cmd'': ''EditorConfigReload''}]', 'OpenBrowser https://github.com/editorconfig/editorconfig-vim'], ['[edit]                   [floobits/floobits-neovim]
     [lazy loaded]  [{''on_cmd'': [''FlooJoinWorkspace'', ''FlooShareDirPublic'', ''FlooShareDirPrivate'']}]', 'OpenBrowser https://github.com/floobits/floobits-neovim
']], 'description': 'All the Added plugins                    <leader>lp'}, 'CustomKeyMaps': {'command_candidates': [['➤ Open qq chatting room
                             <M-x>', 'call chat#chatting#OpenMsgWin()'], ['➤ Open weixin chatting room                                                  <M-w>', 'call c
hat#chatting#OpenMsgWin()'], ['➤ Open chatting room                                                         <M-c>', 'call chat#chatting#OpenMsgWin()'], ['➤ format curr
ent buffer                                                         g=', 'call zvim#format'], ['➤ Copy buffer absolute path to X11 clipboard
     <C-c>', 'call zvim#util#CopyToClipboard()'], ['➤ Switch to next window or tab                                               <Tab>', 'wincmd w'], ['➤ Switch to pre
vious window or tab                                         <S-Tab>', 'wincmd p'], ['➤ Smart close windows                                                            q
', 'call zvim#util#SmartClose()'], ['➤ Defind window prefix                                                    [Window]', 'normal [Window]'], ['➤ Use s as window prefi
x                                                         s', 'normal s'], ['➤ vsplit vertically,switch to next window                                [Window]p', 'vspl
it | wincmd w'], ['➤ split window                                                           [Window]v', 'split'], ['➤ vsplit window
                      [Window]g', 'vsplit'], ['➤ Create new tab                                                         [Window]t', 'tabnew'], ['➤ Close other windows
                                                   [Window]o', 'only'], ['➤ Empty current buffer                                                   [Window]x', 'call zv
im#util#BufferEmpty()'], ['➤ Switch to the last buffer                                              [Window]\', 'b#'], ['➤ Close current windows
                           [Window]q', 'close'], ['➤ delete current windows                                                 [Window]Q', 'call SpaceVim#mapping#close_cu
rrent_buffer()'], ['➤ Clear all the buffers                                                  [Window]c', 'call SpaceVim#mapping#clearBuffers()'], ['➤ Save current file
                                                      <Leader>w', ':w<CR>'], ['➤ Save current file                                                      <Leader>w', '<E
sc>:w<CR>'], ['➤ Jump to next location list position                                   <Leader>lj', ':lnext<CR>'], ['➤ Jump to previous location list position
                      <Leader>lk', ':lprev<CR>'], ['➤ Close the window showing the location list                            <Leader>lq', ':lclose<CR>'], ['➤ Jump to ne
xt quickfix list position                                   <Leader>qj', ':cnext<CR>'], ['➤ Jump to previous quickfix list position                               <Lead
er>qk', ':cprev<CR>'], ['➤ Close quickfix list window                                            <Leader>qq', ':cclose<CR>'], ['➤ Toggle recording
                                 <Leader>qr', 'q'], ['➤ Yank the github link of current file to X11 clipboard              <Leader><C-c>', 'call zvim#util#CopyToClipbo
ard(1)'], ['➤ Yank the github link of current line to X11 clipboard              <Leader><C-l>', 'call zvim#util#CopyToClipboard(2)'], ['➤ Yank the github link of curr
ent selection to X11 clipboard         <Leader><C-l>', 'call zvim#util#CopyToClipboard(3)'], ['➤ Sourced selection.
 <Leader>S', 'echo ''Use <leader>S to sourced selection.'''], ['➤ Source line                                                            <Leader>S', 'echo ''Use <leade
r>S to sourced line.'''], ['➤ Open previous buffer in split window                                  <Leader>sv', ':call SpaceVim#mapping#split_previous_buffer()<CR>'],
 ['➤ Open previous buffer in vsplit window                                 <Leader>sg', 'call SpaceVim#mapping#vertical_split_previous_buffer()'], ['➤ Goto declaration
                                                              gd', '']], 'description': 'Custom mapped keyboard shortcuts                   [unite]<SPACE>'}, 'MyStarre
drepos': {'command_candidates': [], 'description': 'All github repos starred by me                   <leader>ls'}}
spacevim_smartcloseignoreft ['help', 'tagbar', 'vimfiler']
spacevim_default_indent #3
spacevim_enable_key_frequency #0
leaderGuide_submode_mappings {'p': 'page_up', '<C-C>': 'win_close', 'n': 'page_down', 'u': 'undo'}
spacevim_enable_javacomplete2_py #0
EasyMotion_move_highlight #1
multi_cursor_visual_maps {'T': 1, 'a': 1, 't': 1, 'F': 1, 'f': 1, 'i': 1}

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
how do you install spacevim?

**Comment by hongjiujing** [comment]
Hi ,

used curl -sLf https://spacevim.org/install.sh | bash to install.

I try several times to uninstall and install, issue remain the same.

**Comment by wsdjeg** [comment]
I can not reproduce this issue, I think your installation step is not right. please check the output of these command in terminal.

```
git -C ~/.vim status
file ~/.vim
file ~/.vimrc
vim --version
```

then copy all the output here.

**Comment by hongjiujing** [comment]
[tommy@tommy-VirtualBox ~]$git -C ~/.vim status
fatal: Not a git repository (or any of the parent directories): .git
[tommy@tommy-VirtualBox ~]$file ~/.vim
/home/tommy/.vim: directory 
[tommy@tommy-VirtualBox ~]$file ~/.vimrc 
/home/tommy/.vimrc: ASCII text
[tommy@tommy-VirtualBox ~]$vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
Included patches: 1-52
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions      
[tommy@tommy-VirtualBox ~]$

**Comment by wsdjeg** [comment]
I do not know why it can not work, your spacevim is not installed successfully, 

what is the output of 

```
curl -sLf https://spacevim.org/install.sh | bash
```

**Comment by hongjiujing** [comment]
Hi,
Issue is fixed after rm -rf .SpaceVim* and re-install.
Thanks.

**Comment by hongjiujing** [comment]
Hi,

it seems that there are something wrong with installing some plugin.

1   Updating plugins (4/23)                                            │1                                                                     
  1 [========                                          ]               │~                                                                     
  2                                                                    │~                                                                     
  3 x vim-terminal: Installing failed.                                 │~                                                                     
  4 x vim-textobj-indent: Installing failed.                           │~                                                                     
  5 - vim-textobj-line: Installing done.                               │~                                                                     
  6 x vim-textobj-user: Installing failed.                             │~                                                                     
  7 + vim-unite-giti: Updating...
