### ISSUE TITLE
[Improvement] Add shortcut key that closes all buffers that are saved

### ISSUE THREAD

**Issue by yxliang01** [wsdjeg/SpaceVim#828]
This would be very useful for cleaning up the files opened by VIM. For example, you have been changing quite a few files. Some of them might not be saved and some changes are needed to be reviewed before really saving. When you want to shut down, instead of trying to close buffers one by one to check which ones are not saved, we can just have the shortcut I proposed to save time.

Thanks!

**Comment by wsdjeg** [comment]
nice improvement, I will add this feature.

**Comment by wsdjeg** [comment]
I just implement this feature, here is how this key binding works:

1. get a list contains the buffer numbers of all listed buffer, so plugin buffers will no be included.
2. remove the buffers in current tab from the list, so this key binding will not break window layer.
3. filter all saved buffer from the list.

you can have a try with #830

**Comment by yxliang01** [comment]
@wsdjeg Thank you for adding this function quickly! It does exactly what I want. Good job!
