### ISSUE TITLE
EditorConfig-Vim doesn't load `.editorconfig` until executing `:EditorConfigReload`

### ISSUE THREAD

**Issue by yxliang01** [wsdjeg/SpaceVim#829]
I have already executed `:SPUpdate` to update to the latest version. But, the problem still persists. Executed `let g:EditorConfig_verbose = 1` to try get useful information when doing `:EditorConfigReload`. But, it only says EditorConfig is applied to XXX file which is not helpful. I am still not sure whether this is an upstream issue though. But, I am lack of Vim experience...

Thanks!

**Comment by wsdjeg** [comment]
sorry for the later reply, I have fixed it, please update spacevim.

**Comment by yxliang01** [comment]
Will test soon! Thanks! :)
