### ISSUE TITLE
vim crash when enable googlesuggest

### ISSUE THREAD

**Issue by colinlabs** [wsdjeg/SpaceVim#83]
enable variable：
```
let g:spacevim_enable_googlesuggest    = 1
let g:spacevim_auto_download_neobundle = 1
let g:spacevim_dein_installed          = 1
```

**Comment by wsdjeg** [comment]
> let g:spacevim_auto_download_neobundle = 1
 this options is uselese , and SpaceVim do not use is now. can be deleted from src of SpaceVim

> let g:spacevim_enable_googlesuggest    = 1
  this options just enable two plugins which need google support.

> let g:spacevim_dein_installed          = 1
   this option just tell SpaceVim do not check if dein has been installed, by default it is 0, and SpaceVim will check if it is installed, if not, will auto download dein.

I have test with adding this three options into `~/.SpaceVim.d/init.vim`, and no errors, plugin can bu auto installed. here is the picture.

![2017-01-10-22 38 18](https://cloud.githubusercontent.com/assets/13142418/21810310/3dc38fd8-d786-11e6-9737-d73d94faa613.png)

BTW, my evn:
vim8,
neovim:master
os : arch

**Comment by colinlabs** [comment]
close! maybe this is my problem, i interrupt download plugins

**Comment by wsdjeg** [comment]
ok
