### ISSUE TITLE
Ctrl+c无法复制选中的内容到系统剪贴板

### ISSUE THREAD

**Issue by lcg635** [wsdjeg/SpaceVim#831]
如题, 直接使用"+y就可以复制

**Comment by wsdjeg** [comment]
并不是所有终端程序都支持 `<C-c>`映射的， 在 vim 中你是无法使用这个映射的，但是在 neovim 中可以， 为了兼容 vim 所有没有映射这个快捷键， 最简单的测试方式是 `:nnoremap <c-c> :echo 1<cr>`, 然后安 ctrl+c 来测试，目前已知的是 neovim neovim-qt gvim 下都正常，但是 vim 下不正常， 终端 vim 下无法使用 bash 常用的快捷键 `C-s` `C-q` 和 `C-c`.

**Comment by lcg635** [comment]
vnoremap \<silent> \<C-c> "+y

我自己添加了这个快捷键之后, 就可以正常复制了. 应该不是因为不支持\<C-c>

**Comment by wsdjeg** [comment]
那么你可以将这个添加到配置中，临时自己用

**Comment by lcg635** [comment]
@wsdjeg 发现复制到系统剪贴板是被映射成 Ctrl+shift+c了, 也就是\<C-C>
