### ISSUE TITLE
set so=999 没效果

### ISSUE THREAD

**Issue by lcg635** [wsdjeg/SpaceVim#832]
在.SpaceVim.d/init.vim 中加上set so=999 没效果

**Comment by wsdjeg** [comment]
It works well for me, spacevim set scrolloff before load custom config, so you can override it. if it does not work, you can read `:verbose set so`.

for me, if I add `set so=999` to custom config, I will see

```
  scrolloff=999                                                                                                                                        
        Last set from ~/DotFiles/SpaceVim.d/init.vim
```

**Comment by lcg635** [comment]
scrolloff=0
        Last set from ~/.SpaceVim/config/plugins/vim-startify.vim
