### ISSUE TITLE
在iterm2中, 没办法双击选中内容的同时, 复制选中的内容到系统剪贴板

### ISSUE THREAD

**Issue by lcg635** [wsdjeg/SpaceVim#834]
这个有没有办法支持?

**Comment by tenfyzhong** [comment]
这个不是vim的特性。也支持不了。

**Comment by wsdjeg** [comment]
@lcg635 这个特性是可以实现的，但是问题是双击的时候是 normal 模式，如何判定需要选择内容呢？是双击点的词还是段落，还是行？这个有没有什么标准呢，比如在网页中，双击的时候是选择当前词。但是这对中文支持不好。比如说， @tenfyzhong 说的这句话，我进行双击，如果双击在 `这个不是`，则选择的整个 `这个不是`，如果是双击在 `vim` 中任意一个字母上，则选择的是 `vim`。

我测试了 `expand('<cword>')`, 有类似功能，或者 `viw` 也类似，但是这受到 `'iskeyword'`这已选项影响。

**Comment by lcg635** [comment]
可能说双击不太确定,

就是像使用iterm2时一样, 只要用鼠标选中了某些内容, 就自动复制这些内容到系统剪贴板.

**Comment by tenfyzhong** [comment]
@lcg635 iterm默认是支持选中即复制的。你只要从`"*`的寄存器去粘贴就行了。

**Comment by wsdjeg** [comment]
这是由系统决定的，我在 arch 下，如果在浏览器下选择了某个内容，但是并没有按下 ctrl + c 进行复制，我的寄存器里面还是会存储这个内容的。
