### ISSUE TITLE
Disable CompleteParameter plugin with using ultisnips and autocompletion

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#838]
Hello,
I was wondering if it is possible to disable CompleteParameter.vim when using "smart" Tab.

It does not play nice with ultisnips and YCM (which I use a lot) and it is hardcoded in the autocompletion behavior when typing "(" after a method.

Thanks

**Comment by wsdjeg** [comment]
I do not use ycm an ultisnips, will test it later.

**Comment by tenfyzhong** [comment]
@crisidev It works well for me. Can you record a screenshot to show me the problem？

**Comment by crisidev** [comment]
What is does not work for me is moving to next or previous parameter using ultisnips binding. If I use neosnippets it works properly.

From CompleteParameter.vim README:
```
### Can't jump to next parameter
If you use `ultinsips`, you must load `ultisnips` before this plugin. In other 
words, if you use `plug` to load plugins, `Plug 'SirVer/ultisnips'` must before 
`Plug 'tenfyzhong/CompleteParameter.vim'` in your vimrc. 


### How to accept the selected function but not parameters
You can type `<c-y>` key to accept the selected function and stop completion.
When the popup menu is disappeared, the parameters will not be insert. 


### The mapping `<c-j>` doesn't jump to the next parameter, but delete the selected words. 
If you use neosnippet, Please set `g:neosnippet#disable_select_mode_mappings`
to 0. It will remove all select mappings. 
If you don't use neosnippet, please send me a issue, and give me the plugins
you are using. 
```

I set these options in my init.vim as specified by CompleteParameter.vim README:
```
let g:complete_parameter_use_ultisnips_mapping = 1
let g:neosnippet#disable_select_mode_mappings = 0
```

If I tap Tab, there is no movement and selection of next parameter.

**Comment by wsdjeg** [comment]
@crisidev can you show me the content of your `SpaceVim.d/init.vim`? I will test it.

**Comment by crisidev** [comment]
Here is my SpaceVim config: https://pastebin.com/AgT8sdj0

Be aware that my plugin (crisidev/crisibeans) creates overrides to disable CompleteParameter.vim: https://github.com/crisidev/crisibeans/blob/master/autoload/complete_parameter.vim

**Comment by wsdjeg** [comment]
@crisidev which language do you edit? can you provide example file? I just install YCM, and it works well for me.

**Comment by wsdjeg** [comment]
@crisidev what is output of  `:verbose imap <tab>`?

how about run `imap <silent><expr><TAB> SpaceVim#mapping#tab()` ?

**Comment by crisidev** [comment]
Weird, I cannot reproduce the issue anymore.. tab works fine also for me now.

Let me try to reinstall the plugins from scratch and see if I can reproduce it again.

**Comment by crisidev** [comment]
After reinstalling all the plugins the issue is there again.

I am editing a python file. I type ```logging.info(``` and CompleteParameter is completing the parameters. If I hit Tab, I cannot move through parameters, hence it is frustrating to go back and forth with arrow and delete / update them.

Here is the output of what you asked:
```
:verbose imap <tab>
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
        Last set from ~/.cache/vimfiles/repos/github.com/SirVer/ultisnips/autoload/UltiSnips/map_keys.vim
```

If I remap it with
```
imap <silent><expr><TAB> SpaceVim#mapping#tab() 
```
the behaviour is the same.

**Comment by wsdjeg** [comment]
OK I will test it later.

**Comment by crisidev** [comment]
This is still not working BTW :)

**Comment by wsdjeg** [comment]
move to #1078
