### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by obiknows** [wsdjeg/SpaceVim#84]
Is there some sort of uninstall script or a list of files that can be removed to go back to the previous vim configuration?

**Comment by wsdjeg** [comment]
Please read the readme `Install` section.

**Comment by wsdjeg** [comment]
also you can search `uninstall` in issue list.

**Comment by wsdjeg** [comment]
`curl -sLf https://spacevim.org/install.sh | bash -s -- uninstall`

**Comment by hhqqnu** [comment]
download install.sh file
execute `sh install.sh uninstall`

**Comment by nmcalabroso** [comment]
Problem is that this doesn't uninstall the installed plugins.

**Comment by jgogstad** [comment]
So, for the record, the plugins are located at `~/.cache/vimfiles`. You have to delete them manually.

**Comment by ghost** [comment]
I ran `curl -sLf https://spacevim.org/install.sh | bash -s -- uninstall` on my OS X machine and it updated the local branch and didn't uninstall anything 😅 (see output here: https://user-images.githubusercontent.com/3915598/29235965-f4b5bdb8-7e9f-11e7-987c-cac68a190d04.png)

I tried what hhqqnu suggested and it did the same. (see output here: https://user-images.githubusercontent.com/3915598/29235950-d644efde-7e9f-11e7-9073-1a22fd622a0e.png)


Any hints for me?

**Comment by ghost** [comment]
✅ After reading the code in `install.sh` I resolved my issue.

The command should be as follows (**note the `--uninstall` argument**):

1. `curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall` 
1. `sh /path/to/install.sh --uninstall`

**Comment by WangNingning1994** [comment]
As mentioned above, I tried this:

1. curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
2. delete space vim folder and uninstalled successfully

**Comment by ktomk** [comment]
As mentioned above, I tried this:

1. `curl -sLf https://spacevim.org/install.sh | bash -s -- uninstall`
2.  delete space vim folder to uninstall successfully
    1. `cd ~`
    2. `mv -vi -- .spacevim{,~}`
    3. `mv -vi .space-vim{,~}`

Second step as a one-liner: `$ cd ~ && mv -vi -- .spacevim{,~} ; mv -vi -- .spacevim{,~}`

It eventually uninstalled successfully. It might be that there was still a broken symlink (symbolic link) or so. These are easy to detect.

/E: updated

**Comment by TheM3tabaron** [comment]
> Please read the readme `Install` section.

easy for most of us to clean up your mess after testing your vim hack. But a pain for noobs.
You purposely left out uninstall information, leaving beginners helpless. Not cool!

**Comment by dminca** [comment]
Very uncool. There is [no documented](https://spacevim.org/quick-start-guide/#install) _uninstall_ operation in the documentation. 😉 
If you provide a way to install & test it, provide also a documented way of uninstalling in order for the people to provide fast feedback about it.

Otherwise you're left over with a bunch of grumpy people (me as well) that try out software with bad/or lack of documentation

**Comment by wsdjeg** [comment]
@dminca 

plesea check the doc, there is:

For more info about the install script, please check:

```
curl -sLf https://spacevim.org/install.sh | bash -s -- -h
````

the install script has provide more than 5 options, I **do not** want to list all of them one by one.
