### ISSUE TITLE
issue  about press TAB in vim insert mode 

### ISSUE THREAD

**Issue by hongjiujin** [wsdjeg/SpaceVim#842]
## Environment Information
- OS:Ubuntu14.04
- vim version:7.4
- neovim version:

## The reproduce ways from Vim starting (Required!)
Vim insert mode, press TAB

Error detected while processing function SpaceVim#mapping#tab..SpaceVim#mapping#tab#i_tab..complete_parameter#jumpable..cmp#jumpable..<SNR>240
_debug_log:                                                                                                                                   
line    1:                                                                                                                                    
E121: Undefined variable: g:complete_parameter_log_level                                                                                      
Press ENTER or type command to continue 

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
what is the reproduce step? does all the plugins have been installed successfully?

please run `:SPUpdate` to update all the plugins.

**Comment by hongjiujin** [comment]
[tommy@tommy-VirtualBox rt-thread]$curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
==> Trying to uninstall SpaceVim
[✔] Uninstall SpaceVim for vim
[✔] Recover from /home/tommy/.vim_back
[✔] Recover from /home/tommy/.vimrc_back
[✔] Uninstall SpaceVim for neovim
[tommy@tommy-VirtualBox rt-thread]$sudo rm -rf ~/.SpaceVim/

[tommy@tommy-VirtualBox rt-thread]$curl -sLf https://spacevim.org/install.sh | bash -s
==> Trying to clone SpaceVim
Cloning into '/home/tommy/.SpaceVim'...
remote: Counting objects: 9628, done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 9628 (delta 85), reused 93 (delta 48), pack-reused 9483
Receiving objects: 100% (9628/9628), 2.49 MiB | 68.00 KiB/s, done.
Resolving deltas: 100% (6771/6771), done.
Checking connectivity... done.
[✔] Successfully clone SpaceVim
[✔] Backup /home/tommy/.vimrc to /home/tommy/.vimrc_back
[✔] BackUp /home/tommy/.vim to /home/tommy/.vim_back
[✔] Installed SpaceVim for vim
[✔] Installed SpaceVim for neovim

 ❶  PlugManager                                       <ify  startify  ❖ ⓢ    master   unix|utf-8  All   ❷  vimfiler                
Error detected while processing function SpaceVim#commands#update_plugin..SpaceVim#plugins#manager#update..<SNR>214_pull..51..<SNR>214_on_pull
_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_
pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>2
14_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit.
.<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..

**Comment by hongjiujin** [comment]
❶  PlugManager                                                     
Error detected while processing function SpaceVim#commands#update_plugin..SpaceVim#plugins#manager#update..<SNR>214_pull..51..<SNR>214_on_pull
_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_
pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>2
14_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit.
.<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..
51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_
pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>
214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<S
NR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_e
xit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pu
ll..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214
_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<
SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51
..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pu
ll_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>21
4_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR
>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exi
t..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull
..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_o
n_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SNR>214_pull..51..<SNR>214_on_pull_exit..<SN
R>214_msg_on_updated_done..<SNR>214_set_buf_line:                                                                                             
line    1:                                                                                                                                    
E169: Command too recursive                                                                                                                   
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
please update vim to vim8, or use neovim.
