### ISSUE TITLE
Documentation for mapleader is incorrect option

### ISSUE THREAD

**Issue by mseidl** [wsdjeg/SpaceVim#847]
## Expected behavior, english is recommended
The space should be the leader and no error should happen
this works:
`let mapleader = "<space>"`

## Environment Information
- OS:  opensuse leap 42.2
- neovim version: git

## The reproduce ways from Vim starting (Required!)
put 
`let mapleader = "\<space>"`  
in the init.vim

## Output of the running nvim
`Error detected while processing function SpaceVim#end[73]..SpaceVim#plugins#load[4]..<SNR>32_load_plugins[16]..<SNR>32_loadLayerConfig[2]..SpaceVim#layers#edit#config:
line   16:
E121: Undefined variable: g:_spacevim_mappings_space
Error detected while processing function SpaceVim#end[73]..SpaceVim#plugins#load[4]..<SNR>32_load_plugins:
line   16:
E170: Missing :endfor
Error detected while processing function SpaceVim#end[73]..SpaceVim#plugins#load:
line    4:
E171: Missing :endif
Press ENTER or type command to continue`

**Comment by wsdjeg** [comment]
I do not recommand to use `mapleader`, SpaceVim do not change the Leader of vim, it is still `\`, but in normal mode and visual mode, you can use `<Space>` as the custom leader.

but this issue should be fixed, I will look into it.
