### ISSUE TITLE
[Request] Support for git workflow within SpaceVim

### ISSUE THREAD

**Issue by abhi18av** [wsdjeg/SpaceVim#852]
Hi SpeceVim team,

This is a feature request for the inclusion of something like https://github.com/jreybert/vimagit for managing git workflow from within the editor.

**Comment by wsdjeg** [comment]
in SpaceVim, we use these plugins:
https://github.com/lambdalisue/gina.vim for vim8/neovim
https://github.com/lambdalisue/vim-gita for old version of vim

and the default mapping is begin with `<Leader>g`, by default the `Leader` is `\`.

**Comment by wsdjeg** [comment]
please have a look at #867
