### ISSUE TITLE
cann't use CTRL+I to jump

### ISSUE THREAD

**Issue by zuiaiqun** [wsdjeg/SpaceVim#855]
I have been used to using `CTRL+I` and `CTRL+O` to jump。But after I use `SpaceVim`, it does't work. How can I use `CTRL+I` to jump?

**Comment by wsdjeg** [comment]
in vim, `ctrl+i` is same as `<Tab>`, in SpaceVim, we have mapped `<tab>` as `:wincmd w`. it is used to jump to below/right of  the current window.

see:

```
CTRL-W w					*CTRL-W_w* *CTRL-W_CTRL-W*
CTRL-W CTRL-W	Without count: move cursor to window below/right of the
		current one.  If there is no window below or right, go to
		top-left window.
		With count: go to Nth window (windows are numbered from
		top-left to bottom-right).  To obtain the window number see
		|bufwinnr()| and |winnr()|.  When N is larger than the number
		of windows go to the last window.
```

**Comment by wsdjeg** [comment]
hmm, these mapping are also very useful, maybe we should not change the behavior.

```
							*CTRL-O*
CTRL-O			Go to [count] Older cursor position in jump list
			(not a motion command).

<Tab>		or					*CTRL-I* *<Tab>*
CTRL-I			Go to [count] newer cursor position in jump list
			(not a motion command).

```

**Comment by crisidev** [comment]
I have remapped them to behave as they should (jumper to prev / next cursor position). 

I think SpaceVim should not touch these widely used and standard mappings.

**Comment by zuiaiqun** [comment]
OK. After I have removed the code `call SpaceVim#mapping#def('nnoremap <silent>', '<Tab>', ':wincmd w<CR>', 'Switch to next window or tab','wincmd w')` in the file `SpaceVim/default.vim`, it works again.

**Comment by wsdjeg** [comment]
see: https://github.com/neovim/neovim/issues/5916

in the plan of neovim, they will distinguish Tab and ctrl-i, and I think it is usefull. after this plan is implemented, we will keep  the origin function of `ctrl+i`, and use `tab` for jump to next windows.

**Comment by wsdjeg** [comment]
We can do nothing for this feature, only when neovim/vim can distinguish `<C-i>` and `<Tab>`. Now if you do not like SpaceVim override vim origin key bindings,  use `vimcompatible` mode.
