### ISSUE TITLE
The curl download script is using 0.5.0-dev?

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#856]
Is the install script supposed to be using version 0.5.0-dev. It seems that version is not installing correctly and I would like to use 0.4.0-dev. Is this normal to take the dev branch?

**Comment by wsdjeg** [comment]
@rykerrumsey 0.4.0-dev is too old, and it is before 0.4.0 release, the order is `0.4.0-dev` -> `0.4.0` -> `0.5.0-dev`, add we will release `0.5.0` after all known bugs are fixed.

the spacevim directory `~/.SpaceVim` is a git project, you can checkout the `v0.4.0` tags, all tags can be seen here: https://github.com/SpaceVim/SpaceVim/tags

**Comment by ghost** [comment]
Sorry, I meant the 0.4.0 branch. Thanks for the speedy response and great work on the project!

**Comment by wsdjeg** [comment]
welcome.
