### ISSUE TITLE
Seems like spacevim_statusline_unicode_symbols doesn't have effect

### ISSUE THREAD

**Issue by kirill-gerasimenko** [wsdjeg/SpaceVim#857]
## Expected behavior, english is recommended
When doing this in the config `let g:spacevim_statusline_unicode_symbols = 0` I expect that unicode symbols will disabled in favor of simple characters

## Environment Information
- OS: Latest Windows 10 Pro
- vim version:
- neovim version: v0.2.1-885

## The reproduce ways from Vim starting (Required!)
Just run neowim

### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 1
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.5.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 1
g:spacevim_hiddenfileinfo = 1
g:spacevim_statusline_inactive_separator = 'arrow'
g:spacevim_gitcommit_pr_icon = 'p'
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_enable_cursorcolumn = 0
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 1
g:spacevim_enable_insert_leader = 1
g:spacevim_auto_disable_touchpad = 1
g:spacevim_vim_help_language = 'en'
g:spacevim_gitcommit_issue_icon = 'i'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_statusline_unicode_symbols = 0
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = 'DejaVu\ Sans\ Mono\ for\ Powerline\:h10'
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'ctrlp', 'autocomplete', 'nvim', 'windows', 'incsearch', 'lang#c', 'lang#elixir', 'lang#haskell', 'lang#java', 'lang#javascript', 'lang#lua', 'lang#perl', 'lang#php', 'lang#python', 'lang#rust', 'lang#swig', 'lang#tmux', 'lang#vim', 'lang#xml', 'shell', 'tools#screensaver', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = 'C:\Users\kiril\.cache\vimfiles\'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_relativenumber = 1
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
g:spacevim_github_username = ''
g:spacevim_leader_guide_hspace = 5
g:spacevim_realtime_leader_guide = 1
g:spacevim_src_root = 'E:\sources\'
g:spacevim_denite_leader = 'F'
g:spacevim_leader_guide_vertical = 0
g:spacevim_checkinstall = 1
g:spacevim_windows_index_type = 0
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_enable_vimfiler_gitstatus = 0
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(C:\Posh\bin\neovim\bin\nvim.exe)
version: 800
OS: Windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      SUCCEED!

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![image](https://user-images.githubusercontent.com/3036330/30641061-f5772fb8-9e05-11e7-97f9-7e9ba376c811.png)

![image](https://user-images.githubusercontent.com/3036330/30641080-0491cdaa-9e06-11e7-90dc-593fa0b83a30.png)

**Comment by wsdjeg** [comment]
It (only can see half of symbols ) is known issue in windows, I do not know how to fix it, but if you like to disable unicode symbols, I will add this feature.

**Comment by wsdjeg** [comment]
same issue as https://github.com/ryanoasis/vim-devicons/issues/133

**Comment by kirill-gerasimenko** [comment]
I thought `spacevim_statusline_unicode_symbols` is already there as it is described in the documentation. It would be great if it worked, thanks a lot!

As for half-cut icons - I've also seen it the editor (some help text uses glyphs, and they are also cut), so might be related to nvim itself.

**Comment by wsdjeg** [comment]
as the document says, `let g:spacevim_statusline_unicode_symbols = 0` should only disable the unicode symbols in `Minor Modes` in statusline, to change the type of window ID number, we need to add new option. as I know there is a `g:spacevim_buffer_index_type` for the SpaceVim buffer index type. but this only works for tabline.

I just push a new branch, and I will fix this issue soon.

**Comment by wsdjeg** [comment]
@kirill-gerasimenko in the new branch, if you add these to your configration file, this issue should be fixed.

```vim
let g:spacevim_statusline_unicode_symbols = 0
let g:spacevim_windows_index_type = 3
let g:spacevim_buffer_index_type = 4
```

**Comment by kirill-gerasimenko** [comment]
Great, thanks a lot!
