### ISSUE TITLE
How can I remove auto installation of plugins for multiple vim installations?

### ISSUE THREAD

**Issue by hggz** [wsdjeg/SpaceVim#860]
I have a vim installation and a neovim installation. I want to use spacevim with neovim only. Does anyone have any advice on how to disable auto installation of plugins? 

Or rather how can I keep my vim environments separate? 

How can I trigger the plugin installation only for neovim?

Thanks again in advance and thank you very much for this great version. I've been using barebones vim for a few years now as an editor and feel like I could get behind this for more intensive day to day use.

**Comment by wsdjeg** [comment]
You can read `curl -sLf https://spacevim.org/install.sh | bash -s -- -h`

**Comment by wsdjeg** [comment]
```
SpaceVim install script : V 0.5.0-dev

Usage : curl -sLf https://spacevim.org/install.sh | bash -s -- [option] [target]

  This is bootstrap script for SpaceVim.

OPTIONS

 -i, --install            install spacevim for vim or neovim
 -v, --version            Show version information and exit
 -u, --uninstall          Uninstall SpaceVim
 -c, --checkRequirements  checkRequirements for SpaceVim

EXAMPLE

    Install SpaceVim for vim and neovim

        curl -sLf https://spacevim.org/install.sh | bash

    Install SpaceVim for vim only or neovim only

        curl -sLf https://spacevim.org/install.sh | bash -s -- --install vim
        curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim

    Uninstall SpaceVim

        curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall
```
