### ISSUE TITLE
any plan to support Vim8.0?

### ISSUE THREAD

**Issue by hongjiujin** [wsdjeg/SpaceVim#861]
## Environment Information
- OS:
- vim version:
- neovim version:

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
SpaceVim supports vim8.
