### ISSUE TITLE
Error detected while processing function SpaceVim#custom#autoconfi

### ISSUE THREAD

**Issue by hongjiujin** [wsdjeg/SpaceVim#862]
>
[tommy@tommy-VirtualBox ~]$vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 11 2017 08:59:11)
Included patches: 1-1092
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      +python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu -lpython3.4m -lpthread -ldl -lutil -lm      

[tommy@tommy-VirtualBox ~]$ls -al ~/.vim/
total 16
drwxr-xr-x  3 tommy tommy 4096 Feb 13  2017 .
drwxr-xr-x 49 tommy tommy 4096 Sep 21 09:39 ..
drwxrwxr-x  3 tommy tommy 4096 Dec 16  2016 bundle
-rw-rw-r--  1 tommy tommy  170 Dec 16  2016 .netrwhist

[tommy@tommy-VirtualBox ~]$ls -al .Spa*
ls: cannot access .Spa*: No such file or directory

[tommy@tommy-VirtualBox ~]$curl -sLf https://spacevim.org/install.sh | bash 
==> Trying to clone SpaceVim
Cloning into '/home/tommy/.SpaceVim'...
remote: Counting objects: 9654, done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 9654 (delta 102), reused 106 (delta 57), pack-reused 9483
Receiving objects: 100% (9654/9654), 2.51 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (6788/6788), done.
Checking connectivity... done.
[✔] Successfully clone SpaceVim
[✔] Backup /home/tommy/.vimrc to /home/tommy/.vimrc_back
[✔] BackUp /home/tommy/.vim to /home/tommy/.vim_back
[✔] Installed SpaceVim for vim
[✔] Installed SpaceVim for neovim

 
## Environment Information
- OS:ubuntu14.04
- vim version:version 8.0.1092
- neovim version:

## The reproduce ways from Vim starting (Required!)
Cmdline menu: Use j/k/enter and the shortcuts indicated                                                                                       
       >(1)dark powered mode                                                                                                                  
        (2)basic mode                                                                                                                         
Press ENTER or type command to continue                                                                                                       
Error detected while processing function SpaceVim#custom#autoconfig[6]..<SNR>182_menu[20]..66[2]..<SNR>177_on_install_exit[25]..<SNR>177_recac
he_rtp[7]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[47]..<SNR>183_save_rollback[3]..<SNR>183_get_revision_number[13]..<S
NR>183_system_cd[4]..dein#install#_system[10]..80[6]..87:                                                                                     
line    7:                                                                                                                                    
E906: not an open channel                                                                                                                     
Error detected while processing function SpaceVim#custom#autoconfig[6]..<SNR>182_menu[20]..66[2]..<SNR>177_on_install_exit[25]..<SNR>177_recac
he_rtp[7]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[47]..<SNR>183_save_rollback:                                        
line    3:                                                                                                                                    
E170: Missing :endfor                                                                                                                         
Error detected while processing function SpaceVim#custom#autoconfig[6]..<SNR>182_menu[20]..66[2]..<SNR>177_on_install_exit[25]..<SNR>177_recac
he_rtp:                                                                                                                                       
line    7:                                                                                                                                    
E171: Missing :endif                                                                                                                          
Error detected while processing function SpaceVim#custom#autoconfig[6]..<SNR>182_menu[20]..66: 

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by realJustinLee** [comment]
I got the same question too

**Comment by wsdjeg** [comment]
open new issue with issue temple
