### ISSUE TITLE
Getting a ton of errors when trying to edit HTML page

### ISSUE THREAD

**Issue by bravecorvus** [wsdjeg/SpaceVim#864]
## Expected behavior, english is recommended
I can't edit the HTML page

## Environment Information
- OS: macOS 10.12.6
- vim version:
- neovim version: 0.20

## The reproduce ways from Vim starting (Required!)
Begin to edit an HTML page, get lots of errors. (Literally, every time i go into insert mode, every time i go back to normal mode, every time i start typing.

## Output of the ':SPDebugInfo!'
![1](https://68.media.tumblr.com/c87f5f1bc4a111211a80bc52a44d774e/tumblr_owovmtHSpz1s5a4bko2_1280.png)
![2](https://68.media.tumblr.com/1502aadc538e808071336350d7f29784/tumblr_owovmtHSpz1s5a4bko3_1280.png)
![3](https://68.media.tumblr.com/8ecbcd2c25d7e6332f256d52df67d578/tumblr_owovmtHSpz1s5a4bko1_1280.png)

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![Errors](https://68.media.tumblr.com/33c6c1a6bc7255a17083401274e70be3/tumblr_owovdeH2fL1s5a4bko1_1280.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
can you provide example html files? I can not reproduce it, as I can see in the error img, it should issue with tag highlight plugin.

**Comment by bravecorvus** [comment]
Even an empty html file will give me this errors.

e.g.

```:badd test.html```
Then I will get all the above errors.

**Comment by rustikus** [comment]
Not sure what exactly caused the errors for me but I think "fixing" the python executable solved it. 

I did specify the following in my init.vim:
```
" Python specific settings
let g:pymode_python = 'python3'
let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'
```
But the python exec used by nvim was /usr/bin/python which was the old macOS version. So I just linked /usr/local/bin/python2 to /usr/local/bin/python (/usr/local/bin is my first entry in $PATH).

BUT maybe it was unrelated to that and some other changes did resolve it (which I cannot remember right now).

**Comment by bravecorvus** [comment]
@rustikus 

Thanks for the reply

![img](https://78.media.tumblr.com/9ef353dada530404871bdc16b44fa39c/tumblr_owy7k4jVLu1s5a4bko1_1280.png) According to ```:CheckHealth```, neovim already recognizes my python_host_prog as '/usr/bin/python'. If possible, I don't want to symlink python2 to python (cuz i will forget about it and something will screw up an environment a few years down the line lol). Anyways, do you still think it could be the case that I had the same issue as you?

**Comment by bravecorvus** [comment]
If it helps, heres a a video to a test session to demonstrate my issue.

[https://youtu.be/3RlYLYR5o0c](https://youtu.be/3RlYLYR5o0c)

**Comment by bravecorvus** [comment]
@rustikus sorry fam. My bad, you were right on that fix. just did
```ln -s /usr/local/bin/python2 /usr/local/bin/python```

and everything is fixed. weird issue
