### ISSUE TITLE
How to keep preview window open if using 'SPC s r p '

### ISSUE THREAD

**Issue by caoer** [wsdjeg/SpaceVim#865]
How can I keep the preview window open if I using rg to search in project?
I'd like to quickly go through each search result.  
Same goes for using tool like ag, ack, pt..etc.

**Comment by wsdjeg** [comment]
Unite support `--preview` option, but it has too many bugs, I do not know if denite support preview feature.

**Comment by wsdjeg** [comment]
@caoer I have add this feature in flygrep, you can use `<C-p>` to toggle previow windows in flygrep.

**Comment by musicwei** [comment]
so where are we now on this question?
