### ISSUE TITLE
Error after install plugins

### ISSUE THREAD

**Issue by AlphaBrock** [wsdjeg/SpaceVim#868]
Error detected while processing function SpaceVim#commands#install_plugin[4]
SpaceVim#plugins#manager#install[40]
<SNR>133_install[19]..41[60]..<SNR>133_on_install_exit[23]
......................
E169: Command too recursive

- OS:Ubuntu 16.04 xenial
- vim version:VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
 
## screenshot
[Error image](https://imgur.com/a/Fc241)

Is there a way to make it work....Thanks

**Comment by wsdjeg** [comment]
I think you should use vim8 or neovim.

**Comment by AlphaBrock** [comment]
thanks for your reply,its working.
