### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by COLABORATI** [wsdjeg/SpaceVim#873]
Multiple tries to install spacevim failed with errors - Ubuntu 16.04. Did nothing special, just simply followed the install instructions. Look at the screenshots:

![spacevim-first-run](https://user-images.githubusercontent.com/6514273/31202593-87d97786-a963-11e7-9369-bf1e149868af.png)

![spacevim-first-run-c](https://user-images.githubusercontent.com/6514273/31202604-8ee793be-a963-11e7-9abf-b23f2c5e1f28.png)

Very disappointed. You should at least try to install it once before release.

**Comment by wsdjeg** [comment]
This is known bug, and I think you should use vim8 instead, your vim do not support +job.
