### ISSUE TITLE
neocomplete 和multiple-cursors

### ISSUE THREAD

**Issue by pittcat** [wsdjeg/SpaceVim#874]
## Environment Information
- OS:arch linux ，ubuntu
- vim version:8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
先进入了visual模式选中但一个单词，<c-j>选中多个单词，<c-a>a进入insert(好像没搞懂他的正确启动姿势，只是这样偶然可以进insert)
## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

![2017-10-05 10-42-59](https://user-images.githubusercontent.com/22888402/31209301-af7be4c8-a9bc-11e7-9053-5c11328765f7.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by pittcat** [comment]
function! Multiple_cursors_before()                                              
                             exe 'NeoCompleteLock'                                                            
                          endfunction                                                                     
                         function! Multiple_cursors_after()                                               
                             exe 'NeoCompleteUnlock'                                                                                                   
                         endfunction  
添加这个后就没毛病了

**Comment by wsdjeg** [comment]
After you've marked all your locations with Ctrl-n, you can change the visual selection with normal Vim motion commands in Visual mode. You could go to Normal mode by pressing v and wield your motion commands there. Single key command to switch to Insert mode such as c or s from Visual mode or i, a, I, A in Normal mode should work without any issues.

At any time, you can press <Esc> to exit back to regular Vim.

```vim
" Called once right before you start selecting multiple cursors
function! Multiple_cursors_before()
  if exists(':NeoCompleteLock')==2
    exe 'NeoCompleteLock'
  endif
endfunction

" Called once only when the multiple selection is canceled (default <Esc>)
function! Multiple_cursors_after()
  if exists(':NeoCompleteUnlock')==2
    exe 'NeoCompleteUnlock'
  endif
endfunction
```

**Comment by pittcat** [comment]
I am appreciated for your reply and the fantasy spacevim .

**Comment by pittcat** [comment]
I am appreciated for your help and the fantastic spacevim.
