### ISSUE TITLE
It seems that <leader>lp not working as mentioned in documentations

### ISSUE THREAD

**Issue by ocoka** [wsdjeg/SpaceVim#875]
## Expected behavior, english is recommended
When `<leader>lp` was typed it is expected that plugins list should be displayed, 
but instead **[SPC]l - Language Specified** submenu opened

## Environment Information
- OS: 4.4.0-96-generic x86_64 GNU/Linux Ubuntu 16.04.3 LTS
- vim version: --
- neovim version: NVIM v0.2.0

## The reproduce ways from Vim starting (Required!)
Start vim and press `SPC-l-p`

## Output of the ':SPDebugInfo!'

[SPDebugIno.txt](https://github.com/SpaceVim/SpaceVim/files/1358142/SPDebugIno.txt)

**Comment by wsdjeg** [comment]
Leader is \\, and is used in all mode. include insert mode.

SPC is space. and only be used in normal and visual mode.
