### ISSUE TITLE
 <SNR>299_snippets_expand_or_jump

### ISSUE THREAD

**Issue by pittcat** [wsdjeg/SpaceVim#887]
## Environment Information
- OS:arch linux
- vim version:8.0
- neovim version:

## The reproduce ways from Vim starting (Required!)
使用 snippets 具有多个select 的使用输入了想要的module 或者函数名，select模式进入insert模式然后再按Tab，出现 <SNR>299_snippets_expand_or_jump之类的报错。在python js当中都有相似的情况，都与snippets相关，也许是我对有多个select snippets操作不对。
## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![spacevim](https://user-images.githubusercontent.com/22888402/31323987-75604e38-ace0-11e7-8433-b97d48ed01eb.gif)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
Hm.
The mappings seems to be broken.

**Comment by wsdjeg** [comment]
I can not reproduce it, and please post your SpaceVim config and reproduce step.

**Comment by pittcat** [comment]
知道哪里错了，我加了vim-scripts/vim-auto-save和已有的插件矛盾。

**Comment by wsdjeg** [comment]
OK， thanks。
