### ISSUE TITLE
E472 Command Failed

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#89]
E472: Command failed
Error detected while processing function SpaceVim#welcome[1]..<SNR>51_timer_handler[1]..<SNR>51_install_async[5]..<SNR>51_check_loop:
line   15:
E170: Missing :endfor
Error detected while processing function SpaceVim#welcome[1]..<SNR>51_timer_handler[1]..<SNR>51_install_async[5]..<SNR>5
1_check_loop[15]..<SNR>51_check_output[22]..<SNR>51_get_revision_number[15]..dein#install#_cd:
Win10 下安装spacevim报错！没看懂什么意思，是说安装async插件的时候吗？
另外，安装过程中(Linux和windows都是)GUI会假死，看后台进程有一堆的git (Linux下能看到，Windows下看不到)

**Comment by wsdjeg** [comment]
@SeAL80s Readme上面的脚本只是安装SpaceVim的核心部分，初次启动vim会自动安装脚本，大概200+插件，dein是多线程异步管理工具，可以同时下载多个插件，所以才会有多个git进程， 你需要等这个安装过程结束 看到红色`Done`之后再关闭vim。此外 建议提高网络状态，国内访问github比较卡

**Comment by ghost** [comment]
@wsdjeg Linux下等，可以完成，Windows下，一直是Command Failed 
![default](https://cloud.githubusercontent.com/assets/12682385/21848727/47b4c36a-d83d-11e6-87e6-bd74762915af.PNG)
我页怀疑网速，后来挂ShadowSocks ，也还是不行。SS可以看YouTuBe的，网速应该可以的。我再调调看吧

**Comment by wsdjeg** [comment]
你看下dein的README，我觉得dein对windows支持，因该需要一个拷贝文件的命令，你看看你有没有。

### Requirements
- Vim 7.4 or above or NeoVim.
- "xcopy" command in $PATH (Windows)
- "git" command in $PATH (if you want to install github or vim.org plugins)

**Comment by ghost** [comment]
@wsdjeg 多谢！我还没找，应该是这个问题。
另一个问题，在Linux下(Fedora)vim 打开后(刚开机)，会有近办分钟GUI无响应，假死状态。之后就好了，而且之后再关闭vim，打开vim，就没有假死问题了。
另外，一个建议：require应该写在项目主页里，尤其是Windows的安装部分。Linux下，一般都很平滑

**Comment by wsdjeg** [comment]
这个假死状态我也有，这因该是vim py的问题，曾经在#vim上也有人说，这个问题困扰我很久，每次开机第一次启动，需要时间比较差，大概10-15秒。

readme我会加入需求。

**Comment by linhua55** [comment]
假死 是不是因为 访问网络不顺畅    strace应该可以测出来

**Comment by SeAL80s** [comment]
@wsdjeg xcopy是windows系统自带命令，微软自家说不建议使用deprecated.在本例中，xcopy需要管理员权限，用管理员权限打开cmd.exe，然后git clone，执行vim初始化就没问题了。

**Comment by ghost** [comment]
@linhua55 目前的状况是，只在系统刚开机时发生。vim第一次启动会有，之后关闭，再开，就没有假死现象，应该不太会使网络访问吧。感觉有点像同步死锁的问题，好像某个命令timeout后自动放弃了。关键是只在第一次发生

**Comment by wsdjeg** [comment]
最后这次回答能不能用英语，我觉得是dein check问题

**Comment by Shougo** [comment]
I cannot read Chinese...
I have added `dein#cd()` error check.
Please update dein.vim and paste the error messages.

**Comment by ghost** [comment]
@Shougo I reinstalled spacevim . In the cmd window , do 
git clone https://github.com/SpaceVim/SpaceVim.git vimfiles 

then run "vim" in cmd window . There is a message "Not an Editor Command" shows in a flash , i can't read all the context . Then "git receive" process ,i think it's cloning dein repository , then the plugin install process . 
Then these message appeared ,also in a flash ,
[dein]Process timeout (i think this is network related) ,
[dein]Empty revision number:(most of the time),

then thereis error message ,some plugins are not installed ,please use "some command" to see the log (also in a flash ,i can't see the command).dein shows [dein] done . 

But still , some plugins are not installed . I run the command "call dein#install()",shows 
"[dein]You may have used the wrong plugin name ,or all of the plugins are already installed" ! 

clearly , there is still some plugins not installed ,but dein still shows "plugins are already installed" .

reopen vim or gvim ,there is error message shows , some plugins are not loaded .

In the installation process , there is also shows "_timer_handler", "install_async" message , maybe that related to the plugins are not install successfully .
![vim_error_message](https://cloud.githubusercontent.com/assets/12682385/21873334/d4a63f90-d8a8-11e6-8daa-82775829bcb6.PNG)
I add $HOME=D:\ , So D:\ now is my home directory

![vim_version](https://cloud.githubusercontent.com/assets/12682385/21873337/d9de35d0-d8a8-11e6-9184-70ac5f3c464a.PNG)

**Comment by ghost** [comment]
@wsdjeg not a "xcopy" issue , xcopy is a windows system command , but microsoft has been deprecated it . But still has it in windows , I use win 10 64bit .
C:\Users\SeAL80s>xcopy
无效的参数数量
复制了 0 个文件

**Comment by wsdjeg** [comment]
Y can not use 'cd D:\\'。 I think , change to '$HOME=D:' and try again.

**Comment by wsdjeg** [comment]
BYW ,in window cmd you can not use cd D:\ when you are in C. if you want to go to D. just,type D:\ with out cd before it.

**Comment by ghost** [comment]
@wsdjeg Thanks ! Yes ,it's "\\" cause the problem , Changed to $HOME=D: .

Process timeout is network issue ,xx-net solve it . with command ":call dein#update()" ,reinstall the missing plugins of command ":message" shows 

It seems like ,there is no document tells how to use dein ?

**Comment by wsdjeg** [comment]
Please install again with VPN or something else.

**Comment by wsdjeg** [comment]
@Shougo sorry, I have add issue_template, and recommend to use english.

**Comment by wsdjeg** [comment]
you should read dein doc in it·s repo.

**Comment by Shougo** [comment]
@SeAL80s 

You should check the error messages by `:messages` command.

You should increase `g:dein#install_process_timeout` value.
Your network connection is very slow.

>  there is still some plugins not installed ,but dein still shows "plugins are already installed" .

I have fixed the problem.  Please update dein.vim.

For leaderF error, you must install Python2 or Python3.

`:help python-dynamic`
