### ISSUE TITLE
How to disable nerdtree git symbol?

### ISSUE THREAD

**Issue by caoer** [wsdjeg/SpaceVim#903]
How to disable nerdtree git symbol?
I have 
```
let g:spacevim_enable_vimfiler_gitstatus = 0
let g:spacevim_enable_vimfiler_filetypeicon = 0
```
but it seems they are for vimfiler,  not work every time for nerdtree when I open the spacevim, but strangely it works if I press 'R' key to refresh it. (but it does not work every time, the icon hides about 60% of the chance.)

I've switched from iterm2 to [alacritty](https://github.com/jwilm/alacritty) recently. It does not support ligature fonts now. 

BTW, alacritty is really really fast. 
![tmux](https://user-images.githubusercontent.com/225856/31632215-23c6ae0a-b28a-11e7-8bbe-ee3ed379b840.png)

**Comment by wsdjeg** [comment]
I can not reproduce this issue in termite, I think this is issue with your terminal.

**Comment by wsdjeg** [comment]
You want to use nerdtree?

**Comment by caoer** [comment]
@wsdjeg yes, I'm using the terminal alacritty and nerdtree. it can not display icon font nor any ligature font. I like them but iterm2 is too slow for me, so I switched to the blazing fast alacritty...

I want to use nerdtree and disable showing the git status in it.

**Comment by wsdjeg** [comment]
https://github.com/Xuyuanp/nerdtree-git-plugin do not provide option to disable itself,  but I think you can use `let g:loaded_nerdtree_git_status = 1` in SpaceVim's custom config file to disable this plugin.

**Comment by caoer** [comment]
Instead of disabling it, I think I'm going to use ASCII char for git status. 
Thanks for the info!

```vimscript
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
 ```
