### ISSUE TITLE
How to open outline window

### ISSUE THREAD

**Issue by cg831344** [wsdjeg/SpaceVim#906]
I can not find  hot key

**Comment by wsdjeg** [comment]
I will update doc.

**Comment by cg831344** [comment]
@wsdjeg think you

**Comment by cg831344** [comment]
@wsdjeg But,Can you tell me now

**Comment by cg831344** [comment]
I can open the outline window,python can, golang will not work
![image](https://user-images.githubusercontent.com/10991981/31779049-c8019664-b524-11e7-949b-2b35d6d4e036.png)
![image](https://user-images.githubusercontent.com/10991981/31779093-db4c6d02-b524-11e7-8cdc-737a716348f3.png)

**Comment by wsdjeg** [comment]
I have update tags layer doc, please read https://github.com/SpaceVim/SpaceVim/blob/clear_errors/docs/layers/tags.md

**Comment by Oseenix** [comment]
this page is missed, 404: https://github.com/SpaceVim/SpaceVim/blob/clear_errors/docs/layers/tags.md

**Comment by Oseenix** [comment]
here is the available link:  https://github.com/SpaceVim/SpaceVim/blob/master/docs/layers/tags.md
