### ISSUE TITLE
SpaceVim fails to use tab autocomplete 

### ISSUE THREAD

**Issue by shiftre** [wsdjeg/SpaceVim#908]
## Expected behavior, english is recommended

Tab autocomplete should work : /

## Environment Information
- OS: Linux, Debian Jessie
- vim version: 7.4
- neovim version: none

## The reproduce ways from Vim starting (Required!)

Start a new Python 3.5 project, add a few functions, import logging and try to add
mylogger.debug<TAB>

## Output of the ':SPDebugInfo!' 
It broke. It didn't work.

## Screenshots

![image](https://user-images.githubusercontent.com/303679/31796743-ac7b5eb6-b533-11e7-9d9e-b4251626fe9c.png)

**Comment by ssfdust** [comment]
It may be the problem of your configuration.I cannot reproduce the bug here, though I am using python 3.6.I am sorry.

**Comment by wsdjeg** [comment]
your vim is too old. some plugins need v:complete_items .

**Comment by wsdjeg** [comment]
```
completed_item-variable | neovim: +v0.1.0 | vim: +v7.4.774                                                                                             
       v:completed_item | neovim: +v0.1.0 | vim: +v7.4.774
```

**Comment by wsdjeg** [comment]
hmm, ok, I think SpaceVim should check the vim version.
