### ISSUE TITLE
SpaceVim Update has malware

### ISSUE THREAD

**Issue by duytrung** [wsdjeg/SpaceVim#909]
## Environment Information
- OS: Win10
- vim version:
- neovim version: 0.2.1 

## The reproduce ways from Vim starting (Required!)
nvim (enter) 
:SPUpdate

## Output of the ':SPDebugInfo!'

Not available. Nvim was not infected but quarantine since I installed spacevim.

https://www.virustotal.com/#/file/b779113c929555180833d5b468a9aafcc30cbbbf4ff4c03af380575475adf644/detection

## Reference:
https://github.com/neovim/neovim/issues/7415

## Screenshots
![image](https://user-images.githubusercontent.com/2046672/31802116-e0b14c30-b593-11e7-8876-e57f61618769.png)

**Comment by duytrung** [comment]
![image](https://user-images.githubusercontent.com/2046672/31802193-48ad3df8-b594-11e7-91cd-141a952e8165.png)

**Comment by wsdjeg** [comment]
SpaceVim is just a configration for vim/neovim, this issue should be opened in neovim's issue tracker
