### ISSUE TITLE
Error after I add "supertab"

### ISSUE THREAD

**Issue by Coooding-Freshman** [wsdjeg/SpaceVim#91]
After I add "supertab" to the space_custom_plugins,  an error occured when I open my vim.
Every time I open my vim, it tell me that:
"
$ Error detected while processing ~/.cache/vimfiles/.cache/vimrc/.dein/plugin/supertab.vim:
line 1000:
E475: Invalid argument: pumvisible() ? "\<C-P>" : ""
"
And when <Tab> is used to switch the completion, it move upward not downward.
How could I sovle this problem?

**Comment by wsdjeg** [comment]
You do not need add this plugin, SpaceVim has it, But it is under ycm group, by default I do not use ycm, I use neocomplete for vim and deoplete for neovim, both of them a better than ycm for me.

It you want to use ycm, read the doc, you will find how to enable it.

**Comment by Coooding-Freshman** [comment]
After I use ycm the problem also exisit.
When I read .Spacevim/autoload/Spacevim/default.vim I find a terrible problem. Why I can't use tab to select? You have mapped 'Tab' to expand neosnippet but most people want to use 'Tab' to select the next field to fill in the snippet and <C-*> to expand.
I can't change it in .local.vim.

**Comment by wsdjeg** [comment]
Will look into it.

**Comment by Coooding-Freshman** [comment]
I like to use tab to select and \<C-j> to expand, I changed zim#tab() to satisfy my requirement. I can't only change it in my ~/.local.vim. Because of this reason your "ycm" plugins groups can't work well too. Wish you can give us a choice.

**Comment by wsdjeg** [comment]
@Coooding-Freshman I will move all the mapping before custom config, then user can override these mappings themself.

**Comment by wsdjeg** [comment]
@Coooding-Freshman same as #100, I think you can use autocmd to override default mapping.

**Comment by Shougo** [comment]
I think this is supertab bug.
supertab overrides `<Tab>` mapping, but it does not support `<expr>` mapping.
I don't recommend to use supertab plugin for the reason.

**Comment by wsdjeg** [comment]
@Shougo yeah, all SuperTab did is just to check if propupmenu is opennd, I have implement this feature is SpaceVim. I will improve `<tab>` in insert mode.
