### ISSUE TITLE
C++ comments is not set by SpaceVim_core augroup, but by C filetype plugin

### ISSUE THREAD

**Issue by mdavezac** [wsdjeg/SpaceVim#911]
## Expected behavior, english is recommended

The variable `comments` should be set by SpaceVim_core augroup rather than filetype plugin

## Environment Information
- OS: macos
- vim version: ---
- neovim version: 0.2

## The reproduce ways from Vim starting (Required!)

open cpp file and do :verbose set comments

~~~
:Verbose set comments
  comments=sO:* -,mO:*  ,exO:*/,s1:/*,mb:*,ex:*/,://
	Last set from /usr/local/Cellar/neovim/0.2.0_1/share/nvim/runtime/ftplugin/c.vim
~~~

## Output of the ':SPDebugInfo!'

Vanilla neovim without custom config

**Comment by wsdjeg** [comment]
I think the default `&comments` of c filetype has no issue, so I do not change it, just keep it as default. if you want to change it or if you got issue with the default `&comments`, please open issue with the **real issue**.
