### ISSUE TITLE
Trouble with nvim updating plugin unite-ctag

### ISSUE THREAD

**Issue by duytrung** [wsdjeg/SpaceVim#913]
## Expected behavior, english is recommended
Unite-ctag plugin cause startup trouble with nvim.

## Environment Information
- OS: windows 10
- vim version:
- neovim version: 0.2.1

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots
![image](https://user-images.githubusercontent.com/2046672/31858549-f6c08fc2-b741-11e7-951c-ebf78438eefc.png)

Plugin cause nvim stop responding

**Comment by wsdjeg** [comment]
what is your SpaceVim version?  can you have a try with latest version?

**Comment by duytrung** [comment]
how to update to latest testing version?
