### ISSUE TITLE
Editing Java Problem

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#914]
## Expected behavior, english is recommended
when I use SpaceVim to open a Java Source File,Have lot's of error pop up.

## Environment Information
- OS: Ubuntu 16.04 LTS
- vim version: Lastest
- neovim version: Lastest

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
if you can not get the error message, I can not debug it, and I just test it , it works well for me.

maybe you can run `mvn compile test` in `~/.cache/vimfiles/repos/github.com/artur-shaik/vim-javacomplete2/libs/javavi/`

**Comment by ghost** [comment]
OK，i well run it

**Comment by ghost** [comment]
After I run `mvn compile test`,I restart vim to edit java,but I'm still wrong,I see most errors are:Invaild Argument,and Java Plugin Error.

**Comment by wsdjeg** [comment]
what is the error? can you post it here?

**Comment by ghost** [comment]
There were a lot of mistakes that popped out, and they were very fast. I tried to take pictures, but the pictures were very blurry

**Comment by wsdjeg** [comment]
how about use `:message`? or `SPC b m`?

**Comment by ghost** [comment]
as same，i cannot run any vim commands

**Comment by ssfdust** [comment]
how about recording a short video..

**Comment by ghost** [comment]
Just 2 second，The system show：core dump ed.And exiting vim.

**Comment by wsdjeg** [comment]
@c4dr01d please post this info
`vim --version`
`java --version`
