### ISSUE TITLE
Add key bindings

### ISSUE THREAD

**Issue by sei40kr** [wsdjeg/SpaceVim#923]
I think we must decide which keys to bind for language specified features, such like

* Fix imports.
* Show documentation.
* Show variables usage (in file/in project).
* Go to previous/next method
* Go to implementation.
* Go to type declaration.
* Go to super class (or method).
* Go to test class (or method).
* Rename variable.
* Fix linter errors.
* Place breakpoint.
* Start debugging.
* Override interface methods.
* Generate constructor/getter/setter/getter and setter/equals/test method

Once these key mappings are defined, contributors will be able to implement them easily.

**Comment by wsdjeg** [comment]
I think this should be put into development documentation. and I will update it later.

**Comment by wsdjeg** [comment]
@sei40kr I just open a new PR #1221 for this issue. In the latest version of spacevim, what we can keep is runner key bindings and REPL key bindings.

> Fix imports.

This mapping is only exits in python layer, as I know

> Show documentation.

This mapping is documented in lsp layer

> Show variables usage (in file/in project).

has been documented in both tags/cscope layer

> Go to previous/next method

none exist

> Go to implementation.

none exists

> Go to type declaration.

This is `gd`,  and need to register gd_func in layer

> Go to super class (or method).

none exists

> Go to test class (or method).

in java layer, there is a `SPC l j a` for jump to alternate file, I am not sure if this is what you want.

> Rename variable.

documented in lsp layer

> Fix linter errors.

should be documented in checkers layer

> Place breakpoint.
> Start debugging.

both documented in debug layer


> Override interface methods.

none exists

> Generate constructor/getter/setter/getter and setter/equals/test method

this is only existe in java layer, should we keep it?
