### ISSUE TITLE
Ctrl+J in normal mode gets overridden by vim-tmux-navigator

### ISSUE THREAD

**Issue by sei40kr** [wsdjeg/SpaceVim#925]
## Expected behavior, english is recommended

Press `Ctrl+J` in normal mode -> Search the word under caret in current buffer
But with `tmux` layer, Vim tries to go to a buffer/pane below.

## Environment Information

- OS: macOS & Ubuntu 17.04
- vim version: 
- neovim version: 0.2.0

## The reproduce ways from Vim starting (Required!)

Install both layer `edit` and `tmux` .

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@sei40kr I want to use `ctrl_n` and `ctrl_m` for multiple-cursors, and `ctrl_hjkl` for tmux layer.

**Comment by wsdjeg** [comment]
fixed.
