### ISSUE TITLE
Many commands not working in Plugin Mode

### ISSUE THREAD

**Issue by cserb** [wsdjeg/SpaceVim#93]
### Expected behavior, english is recommend
e.g. vimfiler keys like `p`, `sp`, `sv` are not working as expected. Receiving message `E21: Cannot make changes, 'modifiable' is off`

### Environment Information
- OS: macOS 10.12.2
- vim version:
- neovim version: 0.2.0-dev

### The reproduce ways from Vim starting (Required!)
- press F3 to open vimfiler
- choose a file and press `p`

**Comment by wsdjeg** [comment]
~~vimfiler do not has such hotkey.~~

sorry , My fault, will fix it.

**Comment by cserb** [comment]
check out this line:
```
nnoremap <silent><buffer><expr> sv  vimfiler#do_action('split') 
```
it's splitting the vimfiler buffer

**Comment by wsdjeg** [comment]
@cserb yeah, it is not good idea, I think should split left buffer. will look into it.
