### ISSUE TITLE
the F2 button do nothing

### ISSUE THREAD

**Issue by sicong-li** [wsdjeg/SpaceVim#932]
## Expected behavior, english is recommended
  I want get out the Toggle tagbar by F2 but when i press F2 button there is do nothing 
  is there have eny else method to get out the Toggle tagbar?

## Environment Information
- OS: 10.12.6 
- vim version:0.5.0-dev
- neovim version: dont konw about it 

## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
what is the output of :map <F2>

**Comment by sicong-li** [comment]
en this is the out 
  `n  <F2>        *@<Nop>`
and what next i should do?

**Comment by sicong-li** [comment]
`n  t           *@:call <SNR>179_set_mark('T')<CR>
n  v           *@:call <SNR>179_set_mark('V')<CR>
n  <F2>        *@<Nop>
n  <MiddleMouse> *@:enew | execute 'normal! "'.(v:register=='"'?'*':v:register).'gp'<CR>
n  <2-LeftMouse> *@:call   @@startify#open_buffers()<CR>`

**Comment by wsdjeg** [comment]
how about `:TagbarToggle`?
