### ISSUE TITLE
Error detected while processing function zvim#util#CopyToClipboard: E354: Invalid register name: '+'

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#94]
### Environment Information
- OS: Ubuntu 14.04.5 LTS
- vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 11 2017 00:28:24)

### The reproduce ways from Vim starting
when i  open vim and input C-v keyboard the error message occured

 Error detected while processing function zvim#util#CopyToClipboard: E354: Invalid register name: '+'

**Comment by wsdjeg** [comment]
I have add warnning message about it, you need compile vim with `+clipboard` feature.
