### ISSUE TITLE
安装过程失败，打开vim报错

### ISSUE THREAD

**Issue by zhiweio** [wsdjeg/SpaceVim#940]
```bash
$ vi ~/.vimrc
Error detected while processing function rtags#InitPython:
line    1:
E319: Sorry, the command is not available in this version: python3 << endpython
line    2:
E492: Not an editor command: import vim
line    4:
E488: Trailing characters: script_folder = vim.eval('s:script_folder_path')
line    5:
E492: Not an editor command: sys.path.insert(0, script_folder)
line    7:
E492: Not an editor command: import vimrtags
line    9:
E492: Not an editor command: endpython
Press ENTER or type command to continue
```
打开 vim 时报错如上
安装过程中有几个插件安装失败，php相关的

**Comment by wsdjeg** [comment]
you vim do not support `+python` feature.

**Comment by cemsbr** [comment]
I was also having this problem in Debian stretch. Installing vim-nox solved it.

**Comment by wsdjeg** [comment]
@cemsbr  nice!

**Comment by nickfan** [comment]
how to prevent this warn message from open vim on startup?

**Comment by zhiweio** [comment]
@cemsbr Thanks, but I cannot solve it do with your approach in macOS 🙃, and that my vim version is macvim

**Comment by minbaby** [comment]
it seems need python3 support, so just `brew install --force vim --with-python3`

**Comment by lsk-boy-f** [comment]
@minbaby Thanks for your comment. As I got the problem in my OSX with vim8.0,  I used below solved it:

```shell
brew uninstall vim
brew install --force vim --with-python3 --with-override-system-vi
```

**Comment by kadrach** [comment]
Just updated my development machine to Ubuntu Artful, the usual vim packages (tiny, nox, gtk3) are shipped with `-python +python3`, it seems.
