### ISSUE TITLE
如何卸载 how to uninstall

### ISSUE THREAD

**Issue by aizuyan** [wsdjeg/SpaceVim#941]
怎么卸载这个软件呢，发现报错了好多，想卸载了

**Comment by ssfdust** [comment]
curl -sLf https://spacevim.org/install.sh | bash -s -- -h
但是正确做法不应该是解决这些错误吗

**Comment by leafonsword** [comment]
有的人就是想卸载，不想折腾解决错误了，难道不该给这些人一个卸载自由嘛？

**Comment by wsdjeg** [comment]
spacevim provides command to uninstall. please do not use issue to ask question. it is only for bug report.

-------- 原始邮件 --------
主题：Re: [SpaceVim/SpaceVim] 如何卸载 how to uninstall (#941)
发件人：刀尖红叶
收件人：SpaceVim/SpaceVim
抄送：Wang Shidong ,State change


有的人就是想卸载，不想折腾解决错误了，难道不该给这些人一个卸载自由嘛？

―

**Comment by zhulinwei** [comment]
curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall

**Comment by wsdjeg** [comment]
yeah, there is a script for uninstall SpaceVim. but it only remove the symlink, you need to delete `~/.SpaceVim`, if you do not want to use SpaceVim.

________________________________
wsdjeg@outlook.com

发件人： Level.Z<mailto:notifications@github.com>
发送时间： 2018-12-08 19:11
收件人： SpaceVim/SpaceVim<mailto:SpaceVim@noreply.github.com>
抄送： Wang Shidong<mailto:wsdjeg@outlook.com>; State change<mailto:state_change@noreply.github.com>
主题： Re: [SpaceVim/SpaceVim] 如何卸载 how to uninstall (#941)

curl -sLf https://spacevim.org/install.sh | bash -s -- --uninstall

**Comment by Devin-Li** [comment]
curl -L https://spacevim.org/install.sh | bash -s -- --uninstall

**Comment by yaohunzhanyue** [comment]
windows下卸载也是加一样的参数吗？

**Comment by BSDxxxx** [comment]
windows下卸载也是加一样的参数吗？

**Comment by wsdjeg** [comment]
Windows 下没法使用 sh 文件，卸载的话，可以手动删除Home 目录下的 .SpaceVim 文件夹。
