### ISSUE TITLE
there is no autocomplete in SPC + !

### ISSUE THREAD

**Issue by v-leonhou** [wsdjeg/SpaceVim#953]
this problem has no relevance to system or enviroment ？ so,i just type some message here:
## spacevim has no autocomplete feature while i type SPC + ! into shell command mode in spacevim while vim build-in command mode has this feature

中文再来一遍，哈哈，用SPC+!打开shell 命令模式，没有自动补全，但是vim内置的:! 模式下有这个自动补全
比如:! ls /ho         我输入/ho之后再输入tab键就给我自动补全了

**Comment by ssfdust** [comment]
别用vim了 用neovim，bel sp | te拯救世界。

**Comment by wsdjeg** [comment]
这个是 vim 自身的问题， `:!` 模式下 貌似 不可以补全 `git st` 成 `git status`, 似乎只支持 补全 命令后跟者文件名， 此外 `SPC ！` 和 其他任何 vim 的命令补全是一致的， 他实际上就是调用 `input()` 函数，该函数支持指定补全方法，默认unite 指定的 是 `shellcmd`. 因此再 SpaceVim 中无法在做提升。

除非有一种可能，重写一个补全命令行的函数，自定义补全。 shougo 的 终端插件貌似有这些补全函数，包括  https://github.com/Shougo/deol.nvim

但是他的补全似乎只是支持 zsh 

this issue will be keep open until we found a better shell cmd completion function.

**Comment by v-leonhou** [comment]
lint on the fly貌似失效了，最近更新了之后发现老是自动给我lint ,看c的代码，写c的话，老是报错，而实际上这些是我不需要的lint，这个问题是最近更新出现的，不知道有人出现过没，我的配置里面g:spacevim_lint_on_the_fly选项一直是1的，以前也是正常的，最近抽风

**Comment by wsdjeg** [comment]
lin oh the fly 不就是实时检测么? 如果不需要这个功能应该设置为0

**Comment by wsdjeg** [comment]
@v-leonhou
我已经修复这个问题，添加了完整的 命令行补全！

![2017-11-03-19-46-56](https://user-images.githubusercontent.com/13142418/32372643-b454a81a-c0d0-11e7-8834-76cc8c291976.gif)
