### ISSUE TITLE
Customize statusline to show VIM state.

### ISSUE THREAD

**Issue by trirpi** [wsdjeg/SpaceVim#956]
How can I change the statusline so it says which state it is in (e.g.: NORMAL, INSERT, ...)? I saw it shows different colors in the docs, but I couldn't find a way to change the behavior to show the text.  

Thanks in advance.

**Comment by wsdjeg** [comment]
there is an option `g:spacevim_enable_statusline_display_mode`, but it is disabled by default, I think some fix should be done with this option.
