### ISSUE TITLE
重新安装，dein仍然报错

### ISSUE THREAD

**Issue by xushaobo** [wsdjeg/SpaceVim#957]
## Expected behavior, english is recommended
打开nvim的时候，dein报错：
[dein] Error occurred while executing hook: neomake
[dein] Vim(call):E117: Unknown function: neomake#configure#automake
Press ENTER or type command to continue

## Environment Information
- OS: Debian GNU/Linux testing (buster)
- vim version: 

- neovim version:NVIM v0.2.0
## Output of the ':SPDebugInfo!'

please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by Shougo** [comment]
neomake seems not be installed.
But it is called in your vimrc.
