### ISSUE TITLE
How to update to Dev version

### ISSUE THREAD

**Issue by duytrung** [wsdjeg/SpaceVim#960]
## Environment Information
- OS: windows 10
- vim version:
- neovim version: 0.2.1 dev

## The reproduce ways from Vim starting (Required!)

Start like normal
## Output of the ':SPDebugInfo!'

No log required. I would like to update to dev version but there is no dev version 0.5.0 as mentioned.
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@duytrung what is your current version? please upload `SPC h I`

**Comment by duytrung** [comment]
It always show 0,4,0 fatal.

I think that when more people switching to dev build spacevim will have some improvement.

**Comment by wsdjeg** [comment]
you need to reinstall SpaceVim, SpaceVim use dev version as default version.
