### ISSUE TITLE
Solution for "Not an editor command: ^M" issue and suggestions

### ISSUE THREAD

**Issue by mario206** [wsdjeg/SpaceVim#962]
It wasted me a lot of time to solve the installation problems cause by the difference line ending between Unix-style and Windows-style.

see 
[http://jjafuller.com/2017/06/2624/
](http://jjafuller.com/2017/06/2624/)
[https://github.com/VundleVim/Vundle.vim/issues/445
](https://github.com/VundleVim/Vundle.vim/issues/445
)
[https://stackoverflow.com/questions/21902754/vim-startup-errors-invalid-expression-debian
](https://stackoverflow.com/questions/21902754/vim-startup-errors-invalid-expression-debian
)

Neither can I install it all right on OSX nor on Windows before  solving it,making me to wonder whether the project is reliable.
Thus I suggest putting `git config --global core.autocrlf input` to the installation steps.

**Comment by wsdjeg** [comment]
@hellogdut Maybe this should be added to faq instead, if the install script change user's the global config , I think it will make user Confused.

**Comment by wsdjeg** [comment]
https://stackoverflow.com/questions/3206843/how-line-ending-conversions-work-with-git-core-autocrlf-between-different-operat

http://jjafuller.com/2017/06/2624/
