### ISSUE TITLE
Spacevim support payment options

### ISSUE THREAD

**Issue by FazleArefin** [wsdjeg/SpaceVim#969]
I think you should accept cryptocurrency payments like LTC (Litecoin) as alternative payment. BTC (Bitcoin) transaction fees may be a little high at the moment and so LTC is a great choice.

**Comment by wsdjeg** [comment]
@fazlearefin sorry, I do not use LTC and BTC.

**Comment by FazleArefin** [comment]
Since a lot of people in the infotech industry use cryptocurrency I thought it would be a nice way to complement the way you accept tips. You probably already know, it's as simple as installing a multi-currency cryptocurrency wallet and cashing the accumulated amount at coinbase or a local online exchnage.

**Comment by wsdjeg** [comment]
@fazlearefin Thanks, just add BTC address in the readme.
