### ISSUE TITLE
Suggestion: Change tinycomment for tcomment or smth else

### ISSUE THREAD

**Issue by cserb** [wsdjeg/SpaceVim#97]
This is just a suggestion to change `tinycomment` for something else. `tcomment` comes to mind since it's still maintained and tinycomment has seen it's last commit 2 years ago.

btw, `<leader>-v` for commenting is also not working out of the box

**Comment by wsdjeg** [comment]
sorry, README should be updated , I am using NERD Commenter, It is a commenter without `commet` options needed.

**Comment by wsdjeg** [comment]
I have update the readme with a new PR, can you check it?
