### ISSUE TITLE
Editing Java Error Again

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#975]
## Expected behavior, english is recommended
At new SpaceVim version releases,I update my SpaceVim,And try to editing java,the error is show again,but not much more.

## Environment Information
- OS: Ubuntu 16.04 LTS
- vim version: 7.4 (Ubuntu 16.04 LTS Latest version)
- neovim version:

## The reproduce ways from Vim starting (Required!)
No.

## Output of the ':SPDebugInfo!'
Some input file(I just see that)
please post log below, if you want me to reproduce your issue quickly, including your custom config here will be better.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
You shou post the picture or message about the error.
