### ISSUE TITLE
Support jiangmiao/auto-pairs over delimitmate

### ISSUE THREAD

**Issue by crisidev** [wsdjeg/SpaceVim#977]
I would like to suggest to use https://github.com/jiangmiao/auto-pairs instead of delimitmate for automatic pairs matching.

delimitmate has some known bug and it does not automatically indent on new lines when using braces.

Main differences between the two matchers can be found here: http://aftnn.org/post/75730734352/vim-auto-closers-compared

**Comment by wsdjeg** [comment]
@crisidev I just read the post you linked above, and I will have a try woth auto-pairs.

**Comment by crisidev** [comment]
Nice! Thanks!

**Comment by wsdjeg** [comment]
@crisidev  I think delimitmate is well maintained.
ok I will list  all the auto pairs plugins here:

Name |  Pulse (a month) | Opened/Closed issues | Opened/Closed PRs
--- | --- | ---- | -----
[auto-pairs](https://github.com/jiangmiao/auto-pairs) | [monthly pulse](https://github.com/jiangmiao/auto-pairs/pulse/monthly) | 71/84 | 19/23
[delimitMate](https://github.com/Raimondi/delimitMate) | [monthly pulse](https://github.com/Raimondi/delimitMate/pulse/monthly) | 24/204 | 3/33

**Comment by crisidev** [comment]
My point is more about features.. autopair for example goes automatically in next line with autoindent when brackets are opened (very useful in languages where you have curly brackets for functions or when dealing with data structures like hashes and lists)

**Comment by wsdjeg** [comment]
feature request can be implement in spacevim directly, for example, in spacevim

```
{<cr>}
````

you will get a new line with indent.

https://asciinema.org/a/xxyZEQnWYofnYxbrLmOyzPasH

**Comment by wsdjeg** [comment]
@crisidev SpaceVim is hard to debug, so we should not use noactive plugins, I just read all the PRs of autoparis, many are better bug fix, but there is no author reply.

**Comment by crisidev** [comment]
Ok, i see your point. Given you have implemented the specific feature here, feel free to resolve!

**Comment by crisidev** [comment]
I rechecked this issue and it does not work for me. In any language I tried, if I put {<cr>}, they do not go indented.

Are you sure this is working?

**Comment by wsdjeg** [comment]
@crisidev what is the reproduce step? can you use gif?
