### ISSUE TITLE
Error detected while processing function SpaceVim#server#connect

### ISSUE THREAD

**Issue by realJustinLee** [wsdjeg/SpaceVim#978]
## Expected behavior, english is recommended
Normal

## Environment Information
- OS: macOS High Sierra 10.13.2 Beta (17C67b)
- vim version: 8.0.642  
- neovim version: not installed

## The reproduce ways from Vim starting (Required!)

$ vim
Error detected while processing function SpaceVim#server#connect:
line   12:
E942: +clientserver feature not available
Press ENTER or type command to continue

## Output of the ':SPDebugInfo!'

[dbg.txt](https://github.com/SpaceVim/SpaceVim/files/1456600/dbg.txt)

## Screenshots

<img width="1680" alt="2017-11-09 14 54 52" src="https://user-images.githubusercontent.com/17794470/32592334-2f0dc4ec-c55e-11e7-9dff-c331a169df01.png">
<img width="1680" alt="2017-11-09 14 55 47" src="https://user-images.githubusercontent.com/17794470/32592335-2f6230ea-c55e-11e7-8bec-845cac85aae1.png">

**Comment by ncihnegn** [comment]
I have this issue, too.

**Comment by Shougo** [comment]
@wsdjeg I get the reason.

https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/server.vim#L22

It should check `has('clientserver') && exists('*remote_server')`.

```
					*remote_startserver()* *E941* *E942*
remote_startserver({name})
		Become the server {name}.  This fails if already running as a
		server, when |v:servername| is not empty.
		{only available when compiled with the |+clientserver| feature}
```

**Comment by wsdjeg** [comment]
I think maybe this should be issue with vim. when build without serverclient feature. all these functions should not exist. 

hmm, I would add a check for this issue.

Thanks @Shougo.
