### ISSUE TITLE
space-f-f can only find file in current directory and space-p-f can not work

### ISSUE THREAD

**Issue by liadbiz** [wsdjeg/SpaceVim#982]
## Expected behavior, english is recommended
find files in any directory when I type space-f-f, actually I can type and use tab to move around directory 
find files in this project when I  type space-p-f(this feature can not work in my computer)

## Environment Information
- OS:  ubuntu kylin 16.04
- vim version: 8.0
- neovim version: sorry I don't know how to find it

## The reproduce ways from Vim starting (Required!)

+ type sapce-f-f
+ type space-p-f

## Output of the ':SPDebugInfo!'

I run `:SPDebugInfo!`, and then `ggyG` to yank all content, but I can not past it to here by using ctrl-v

## Screenshots

space-f-f in spacevim
![space-f-f-vim](https://user-images.githubusercontent.com/11924130/32639150-6d728e6c-c5fd-11e7-8338-6fd7984fb46c.png)

space-f-f in spacemacs
![space-f-f-emacs](https://user-images.githubusercontent.com/11924130/32639153-71a9ce50-c5fd-11e7-9b1c-b83068fe8c44.png)

space-p-f in spacevim
![space-p-f-vim](https://user-images.githubusercontent.com/11924130/32639175-8ab02e76-c5fd-11e7-9572-02bf50f54937.png)

**Comment by wsdjeg** [comment]
as you can see in the last picture, it is issue with ctrlp and zsh, I will try to fix it.

**Comment by Evidlo** [comment]
`SPC f f` still doesn't behave as expected for me.

I should be able to descend to parent folders from the current directory and also descend into directories in the current directory, but I can do neither.

Currently on `0.6.0-dev`

**Comment by wsdjeg** [comment]
Can open new issue for the feature?

**Comment by ankitsinghaniyaz** [comment]
I don't have this option at all for file search in `0.8.0-dev`

**Comment by wsdjeg** [comment]
please use  gitter for usage discussion
