### ISSUE TITLE
Allow multiple files in ~/.SpaceVim.d/

### ISSUE THREAD

**Issue by nwmcsween** [wsdjeg/SpaceVim#983]
As title says, perhaps something like this:
````
for f in split(globpath('~/.SpaceVim.d/', '*.vim'), '\n')
  exe 'source' f
endfor
````
This allows separation of concerns.

**Comment by wsdjeg** [comment]
@nwmcsween

`~/.SpaceVim.d/` is added to `RTP`, please read `:h rtp`, you can put all vim files into `~/.SpaceVim.d/plugin/`

or you can have a look at:

https://github.com/wsdjeg/DotFiles/tree/master/SpaceVim.d
