### ISSUE TITLE
IndentLinesToggle bug in vim

### ISSUE THREAD

**Issue by zongUMR** [wsdjeg/SpaceVim#99]
### Environment Information
- OS: macOS 10.12.2 
- vim version: 7.4
- neovim version:NVIM 0.1.7

### The reproduce ways from Vim starting (Required!)

When I start VIM, if I press the 'i' key, the vim give me an error message: 'E492: Not an editor command:         IndentLinesToggle'!
If I use neovim, it will be OK!
### Output of the ":message" command, and ":echo SpaceVim#logger#viewLog()"
message: 
  first line: 'Error detected while processing function <SNR>41_tool:'
  second line: 'E492: Not an editor command:         IndentLinesToggle'

**Comment by wsdjeg** [comment]
I think it is due it `indentLines` has not been installed, you should use `:call dein#install(['indentLine'])` to install such plugin.

I just add warnning message , please update SpaceVim.
